### ISSUE TITLE
Excessively High RAM Usage and Subsequent Frame Drop When Holding TC Tools/Weapons

### ISSUE THREAD

**Issue by KasimAhmic** [SlimeKnights/TinkersConstruct#1043]
Occasionally, when I hold a TC weapon or tool such as the Cleaver and Hammer, my RAM usage spikes and less frequently, I'll get a massive frame drop. Playing with VSync drops it down to 20fps and playing without it just makes the gameplay choppy. The main issue I've been having is the high RAM usage. The frame drop, while it doesn't happen as frequently, is still pretty annoying though. I looked it up and I only found that people were having frame rate issues with the Short Bow but nothing else. Could any other mod be causing this to happen or is it just an issue with TC? Also, is there any config option I could change to prevent any of this?

Here are some screenshots of the high RAM usage.
![2014-09-29_10 38 30](https://cloud.githubusercontent.com/assets/1304204/4443400/f3b8d6d0-47e7-11e4-853a-ff52a660f70e.png)
![2014-09-29_10 38 39](https://cloud.githubusercontent.com/assets/1304204/4443450/5b62aa90-47e8-11e4-8a5d-0bbf92c91ef3.png)

Please include the following:

Minecraft version: 1.7.10
Tinkers' Construct version: 1.7.0d3
Forge version/build: 10.13.1208
Mods:
* AE2 - rv1-stable-1
* BiblioCraft - 1.8.1
* BuildCraft - 6.0.18
* Carpenter's Blocks 3.2.7 DEV R3
* Chisel - 1.5.6
* CodeChickenCore - 1.0.3.26
* CoFH Core 3.0.0B6
* CoFHLib - 1.0.0B6-26
* CompactSolars - 4.4.36.313
* Damage Indicators - 3.2.0
* Dimensional Anchors - 59.0.2
* EnderStorage - 1.4.5.24
* Extra Utilities - 1.1.0k
* Factorization - 0.8.87.1
* Immibis Core - 59.0.3
* IndistrialCraft 2 - 2.2.646-experimental
* Inventory Tweaks - 1.58-147
* Iron Chest - 6.0.51.734
* Jabba - 1.1.4
* JourneyMap - 4.0.4
* Liquid XP - 59.0.0
* Mantle - 0.3.1.jenkins180
* MineFactory Reloaded - 2.8.0RC3
* NotEnoughItems - 1.0.3.56
* OpenBlocks - 1.3
* OpenMods - 0.6
* OptiFine 1.7.10_HD_U_A4
* QuarryPlus
* Railcraft - 9.2.1.0
* Redstone Arsenal - 1.1.0B4
* Router Reborn - 1.7.10-1.1.8
* Thermal Expansion - 4.0.0B5
* Thermal Foundation - 1.0.0B3
* Tinkers' Construct 1.7.0d3
* Translocator - 1.1.1.12

**Comment by bonii-xx** [comment]
Should be fixed by 075b769db2be26adc5b492240f67d09defee2535
