### ISSUE TITLE
[Suggestion] Make the crafting table aware of more chest types

### ISSUE THREAD

**Issue by BakermanLP** [SlimeKnights/TinkersConstruct#1087]
Hello,

I've got a suggestion for Tinkers Construct. Can you make the crafting table aware of more chest types like Iron Chests or Better Chest?

I know, that is not easy to manage because of different storage sizes.

But ... it is only a suggestion

Michael (aka BakermanLP)

**Comment by MBfromOK** [comment]
I agree with @FrankXLT, we would appreciate any efforts made on this, you can imaging my chagrin when I "upgraded" from wood to gold and then was unable to see the contents from the crafting station.. I had to bust the chest and replace with wood and then transfer all the contents back in.

**Comment by FrankXLT** [comment]
I am thinking that the contents of the chest could wrap around the crafting table.
