### ISSUE TITLE
Corrupted pages

### ISSUE THREAD

**Issue by WindZel** [SlimeKnights/TinkersConstruct#1107]
Minecraft: 1.7.10
TiC: 1.7.10-1.7.0.build703

Opening the Materials and You book, results in these lovely images.
![2014-10-22_17 56 04](https://cloud.githubusercontent.com/assets/8401787/4738261/b08cbf40-59fb-11e4-95bb-ef064a0c1a20.png)

![2014-10-22_17 56 02](https://cloud.githubusercontent.com/assets/8401787/4738257/a4e41846-59fb-11e4-8ca6-705b2c88f587.png)

This only effects the Materials and You, tools section. Everything else seems to be untouched.

**Comment by Flubbles** [comment]
This issue appears to have reappeared in 1.8.3b
