### ISSUE TITLE
Arrows cant be retrieved

### ISSUE THREAD

**Issue by Zaltorin** [SlimeKnights/TinkersConstruct#1113]
I know that there is a closed version of this bug report, but I dont think that this is a vanilla issue.
If an arrow one shots a mob, instead of bouncing off like in earlier versions of TC (for 1.7.10) and being retrievable, the arrow is lost as though it is a vanilla arrow.  Would like confirmation as to whether or not this is intended behavior.  

Could be a call order change.  previous maybe hit->spawn->damage changed to hit->damage->spawn with the arrow attempting to spawn at the now dead mobs coords

**Comment by bonii-xx** [comment]
Closed due new Arrow mechanics.
