### ISSUE TITLE
Most Bizzare Bug

### ISSUE THREAD

**Issue by tgstyle** [SlimeKnights/TinkersConstruct#1136]
See the details here on EnderIO

https://github.com/CrazyPants/EnderIO/issues/1178

**Comment by tgstyle** [comment]
Latest version 1.8.1 seems like it is fixed. I don't have essence flying at me all the time at spawn now =).

**Comment by bonii-xx** [comment]
Must've been the changes to how the harvesting is done then. Good. :)
