### ISSUE TITLE
Metals Being More Diverse

### ISSUE THREAD

**Issue by 05192000** [SlimeKnights/TinkersConstruct#1169]
And Boni, I don't know about other people, but I personally would love to see more metals in TC. Thanks! 
I forgot to tell you on my other post, Happy Holidays!

**Comment by InkDragon** [comment]
@bonii-xx any chance you can add a poison effect to materials like lead? That way when you hit a mob it could slowly poison them. I know it isn't useful on non-weapon tools, but it would give players a reason to use lead for weapons

**Comment by bonii-xx** [comment]
Lead is not a TCon material.
Thanks for all the ideas everybody, some sound quite promising. Don't expect anything of it in 1.7.10, but a future version will probably contain some of this stuff.

**Comment by laz2727** [comment]
What about something like that:
You take a tool head, dip it in some metal(like bolt crafting), and that gives that part mining level of the metal and 10% of its default durability.
