### ISSUE TITLE
[Feature Request] Minimal textures for liquids

### ISSUE THREAD

**Issue by HanFox** [SlimeKnights/TinkersConstruct#1196]
I did search beforehand, didn't see a similar ticket. I'd actually be surprised if this hadn't already been mentioned.

Considering there are minimal textures for tool parts I was wondering if it could also be an idea to supply them for liquids?

Reduce the current 54 down to maybe 4? liquid.molten.still.png; liquid.molten.flow.png; liquid.still.png and liquid.flow.png?

**Comment by bonii-xx** [comment]
Currently not planned
