### ISSUE TITLE
[Request] Thaumcraft Voidmetal material

### ISSUE THREAD

**Issue by TriforceOfKirby** [SlimeKnights/TinkersConstruct#1202]
Would it be possible to add Thaumcraft's Voidmetal as a material? As for material traits, using the same qualities as described in the Thaumonomicon would make sense, ie.  self-repairing, weakness-inflicting, as well as the Warping trait. The name of the material trait could be simply called "Void".

**Comment by bonii-xx** [comment]
Should be added by extratic soon
