### ISSUE TITLE
Javelin auto repair broken 

### ISSUE THREAD

**Issue by SwornGamer** [SlimeKnights/TinkersConstruct#1229]
I'm not sure if this is intended or not but if you put auto-repair on the Javelins the ammo actually decreases instead of increasing as it should

Tinkers Construct version 1.8.0
Forge version 10.13.2.1272

**Comment by Maieath** [comment]
I'm experiencing another problem with Javelin and auto-repair. It actually restoring the amount of ammo on it, but actual durability stays same. I know its not really wise to hit things with "thrown" weapon, but its still a weapon, right? Durability is lost when i hit something with it, and is not restored with auto-repair.

**Comment by bonii-xx** [comment]
But charges are restored. Just use the durability up.

**Comment by Maieath** [comment]
What? I'm not sure what do you mean, is it possible to make them like, tied together? Or disable durability? Or make it restore-able by auto-repair? :O

**Comment by ThatAshGuy** [comment]
Hey Bonii-xx?
You Know the version of TConstruct with the Javelins is there one for MC 1.7.10 that also has daggers? if so please send me a link on my profile

**Comment by LovelyFlare** [comment]
@ThatAshGuy Go on [CurseForge](https://minecraft.curseforge.com/projects/tinkers-construct) and look yourself.  Not relevant to this issue nor is it even one itself...
