### ISSUE TITLE
Smelteries are a derp

### ISSUE THREAD

**Issue by bonii-xx** [SlimeKnights/TinkersConstruct#1244]
https://github.com/Vazkii/Botania/issues/428

**Comment by laz2727** [comment]
I think the issue is not that it resets when item constantly changes, but why the hell it even happens. Maybe because slots have same slotIndex?
~~And can you unhardcode smelteries please?~~

**Comment by bonii-xx** [comment]
No, the NBT/meta of the item changes, so vanilla Minecraft thinks it's a different item than before.

**Comment by laz2727** [comment]
I know why it would reset if i'd use it in smeltery. But it resets smeltery
slots from the player's inventory. I don't think it's a good sign.
