### ISSUE TITLE
Attempting to apply moss to Traveller's Gloves crashes the client.

### ISSUE THREAD

**Issue by the-vindicar** [SlimeKnights/TinkersConstruct#1253]
It appears that game crashes whenever it attempts to render Gloves with Moss added.

Steps to reproduce the problem:
1. Place Gloves into the tool slot of Tool Forge.
2. Place Ball of Moss into any modifier slot.
3. Client crashes, server is fine. Crash happens every time you open that particular Tool Forge. If broken, items are dropped normally.

Minecraft 1.7.10
Forge 10.13.2.1230
TC 1.6.0d40.1
Mante 0.3.1
Reproduced with no other mods installed.

Crash log: http://pastebin.com/N3cvDubg
Apologies, but I can't find ForgeModLoader-client-0.log (or anything like that) anywhere. =\

**Comment by Cronosus** [comment]
Tinker 1.8.2 crash when player try enchant Traveller's Gloves with redstone
http://pastebin.com/6zqeyjqb

tested in SP wit 1.8.3 and crashing too

**Comment by MrKunji** [comment]
It's on Thermal Smeltery side, already fixed in the current version (you're one version behind).
