### ISSUE TITLE
Can't craft grout.

### ISSUE THREAD

**Issue by nghhi** [SlimeKnights/TinkersConstruct#1263]
I tried making a Smeltery in my private modpack, Compressed Knowledge, and I already knew that the first, basic block to make the smeltery is called Grout. But I can't find a way to craft it. I tried looking at the Tinkers' Construct Wiki and doing the recipe, exactly like it was, but nothing seemed to happen. I tried checking the recipe in Not Enough Items, but everytime I press 'R', nothing happens.
Here's a list of mods I use in Compressed Knowledge:
GalactiCraft
OptiFine
Tinkers' Construct
Lucky Block
Not Enough Items
Ex Nihilo
(It is not including Core Mods. The core mods I'm using are just the cores that are needed to run the mods. They shouldn't have any effect on other mods)

**Comment by bonii-xx** [comment]
Closing due to no more info and probably not a tinkers bug.
