### ISSUE TITLE
Hardcoded strings in books

### ISSUE THREAD

**Issue by Adaptivity** [SlimeKnights/TinkersConstruct#1268]
1. http://i.imgur.com/fONWfiq.jpg
2. http://i.imgur.com/UBw7aOU.jpg
3. http://i.imgur.com/i4WfeUb.jpg (ToolPage.java line 50)
4. http://i.imgur.com/rhrqrYK.jpg (BlockCastPage.java line 53)

Hope you can move them in .lang file.

**Comment by bonii-xx** [comment]
Go have fun @Adaptivity :P
