### ISSUE TITLE
Potential order of operations error

### ISSUE THREAD

**Issue by squeek502** [SlimeKnights/TinkersConstruct#1274]
This looked unintentional to me: https://github.com/SlimeKnights/TinkersConstruct/blob/8560cb23e00b713992968c6ce42b4313e9945a08/src/main/java/tconstruct/weaponry/WeaponryHandler.java#L98

That whole line is pretty perplexing, really.

**Comment by bonii-xx** [comment]
Shaft is the main thing. Arrow is a multiplier. Fletching has minimal impact.
You can't just randomly say it doesn't make sense if you don't take the values used into account. :P
