### ISSUE TITLE
Discrepencies in damage calculations

### ISSUE THREAD

**Issue by squeek502** [SlimeKnights/TinkersConstruct#1277]
Pretty much every place that calculates damage does it slightly differently.

* [ProjectileBase.onHitEntity uses a float, thereby avoiding integer math](https://github.com/SlimeKnights/TinkersConstruct/blob/7eadf0df545e95cb4156531e23598c9b99a5581e/src/main/java/tconstruct/library/entity/ProjectileBase.java#L184-L233)
* [ToolCore.addInformation uses an int and ignores many damage-influencing factors](https://github.com/SlimeKnights/TinkersConstruct/blob/7eadf0df545e95cb4156531e23598c9b99a5581e/src/main/java/tconstruct/library/tools/ToolCore.java#L380-L381)
* [ToolStationGuiHelper.drawThrowingWeaponStats uses a float and truncates to an int at the end](https://github.com/SlimeKnights/TinkersConstruct/blob/7eadf0df545e95cb4156531e23598c9b99a5581e/src/main/java/tconstruct/tools/gui/ToolStationGuiHelper.java#L224-L237)
* [ToolStationGuiHelper.drawWeaponStats uses an int](https://github.com/SlimeKnights/TinkersConstruct/blob/7eadf0df545e95cb4156531e23598c9b99a5581e/src/main/java/tconstruct/tools/gui/ToolStationGuiHelper.java#L198-L220)
* [ProjectileWeapon.addInformation uses a float and only uses the raw "Attack" NBT tag of the ammo](https://github.com/SlimeKnights/TinkersConstruct/blob/8560cb23e00b713992968c6ce42b4313e9945a08/src/main/java/tconstruct/library/weaponry/ProjectileWeapon.java#L426-L435)
* [AbilityHelper.calcDamage uses an int](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/tools/AbilityHelper.java#L220-L258)
* [AbilityHelper.onLeftClickEntity multiplies the return of AbilityHelper.calcDamage (int) by a float](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/tools/AbilityHelper.java#L104)

Ideally, all this should be consolidated to a single place. All of this duplicate logic is pure insanity. Honestly, it's possibly even more insane now than it was when I first wrote TiC Tooltips, and that's saying something.

**Comment by bonii-xx** [comment]
Ideally you wouldn't have to use any custom code for the calculations but can use everything in AbilityHelper. At least that was my intention with refactoring everything in proper functions.
I didn't change the calculations because I didn't want to change any tools/weapons and have unforseen consequences. The reason why I didn't change the calculations was because the ActiveToolMod thingie returns integer, and if I change that to float every 3rd party mod that uses them would become incompatible. My preferred way would be doing full float math and truncating to int in the end. But I'll have to see if I can deprecate the old one without causing compatibility breaks.

**Comment by squeek502** [comment]
> Ideally you wouldn't have to use any custom code for the calculations but can use everything in AbilityHelper

Absolutely, but the fact that nothing outside of AbilityHelper uses AbiltityHelper.calcDamage should hint that it's not yet useful in that regard. For TiC Tooltips, specifically, it's unusable because it assumes context that only exists when you're actually dealing damage (user.isSprinting() being the biggest offender). There would need to be quite a bit more refactoring, in order to adequately separate active damage calculation (with non-null user and targets) and generic damage calculation (for tooltip/gui display).

That's what this issue was intended to suggest. If the TiC code ever gets to a place where it can re-use the same suite of damage calculation methods between ProjectileBase.onHitEntity, ToolCore.addInformation, ToolStationGuiHelper.drawThrowingWeaponStats, ToolStationGuiHelper.drawWeaponStats, ProjectileWeapon.addInformation, and AbilityHelper.onLeftClickEntity, then I'd *for sure* be able to use the same methods in TiC Tooltips.

> My preferred way would be doing full float math and truncating to int in the end.

That's exactly what I did in TiC Tooltips, and it's a perfectly fine solution as long as it's done *consistently* (the float gets truncated at the same place for each calculation). The consistency part would always be slightly questionable until all the duplicate code is consolidated into one (or a few) re-used/shared methods, though.

**Comment by bonii-xx** [comment]
Closing as discussed in IRC.
