### ISSUE TITLE
Crash when open other saves after back to the title

### ISSUE THREAD

**Issue by SinusoidalC** [SlimeKnights/TinkersConstruct#1278]
Seems a TiC problem. CR is here.
https://gist.github.com/SinusoidalC/a88948ef071c27260fc1
logs are too long to put on gist. If you need , I'll put it in my webdisk later.

**Comment by bonii-xx** [comment]
Looks like something (outside Tinkers) corrupted some mappings in your world. Removing the crossbow in your inventory should fix the crash, the question is how the world looks then.
