### ISSUE TITLE
1.8.1 Don´t see the tab for knapsack

### ISSUE THREAD

**Issue by TheJosecraft** [SlimeKnights/TinkersConstruct#1279]
In this version, i dont see the slots for insert the armor tab. in the previous version (1.7.1d) I saw it. I need to press "O" to view. Also i dont see the tab for knapsack

The images:

http://i.gyazo.com/462593bb4cdaee7b2f13a294f7d8c22c.png

http://i.gyazo.com/bd32bb97430d66785a9dd3de70e62b65.png

**Comment by bonii-xx** [comment]
Update NEK.

**Comment by TheJosecraft** [comment]
I've already updated, and its all right. Thank You
