### ISSUE TITLE
Further TC compatibility sugestion;

### ISSUE THREAD

**Issue by MrKunji** [SlimeKnights/TinkersConstruct#1282]
Smelting Cinnabat ore turns into 288 mb of Liquid Quicksilver, then 144 mb poured in the Casting Table results in the proper Quicksilver 'ingot' (due to the metal's nature of turning into a ball); pouring into a Nugget Cast results in a Quicksilver Nugget.

**Comment by bonii-xx** [comment]
There is no quicksilver in Tinkers' Construct and we're not going to add any.

**Comment by TherminatorX** [comment]
TC would be Thaumcraft, I believe.
