### ISSUE TITLE
Boss bar Rendering error with certain tools

### ISSUE THREAD

**Issue by Timemon** [SlimeKnights/TinkersConstruct#1286]
while playing with forge 1.13.2.1277 and tinkers construct 1.8.1 in minecraft 1.7.10
the boss bar does not render correctly when holding the following tools
- Shuriken
- Throwing Knife
- Javelin
- Crossbow
- Longbow

here are some pictures of the error with the various tools and a photo showing the Tinkers Construct and Mantle testing instance.
![2015-01-01_17 58 36](https://cloud.githubusercontent.com/assets/8180536/5591788/e9926b52-91df-11e4-86fa-3af75eb4374d.png)
![2015-01-01_17 58 38](https://cloud.githubusercontent.com/assets/8180536/5591789/e9951244-91df-11e4-917f-b53cc316c3e3.png)
![2015-01-01_17 58 40](https://cloud.githubusercontent.com/assets/8180536/5591790/e998ae2c-91df-11e4-8987-b72d62dcb1d2.png)
![2015-01-01_17 58 42](https://cloud.githubusercontent.com/assets/8180536/5591791/e99bb8ce-91df-11e4-9809-6dcafc162295.png)
![2015-01-01_17 58 44](https://cloud.githubusercontent.com/assets/8180536/5591793/e9a2f09e-91df-11e4-9361-cc3e4b8a515a.png)
![2015-01-01_17 58 49](https://cloud.githubusercontent.com/assets/8180536/5591792/e9a25c10-91df-11e4-8917-1082da71dd24.png)

**Comment by bonii-xx** [comment]
Well that was one annoying bug. Turns out it was the crosshairs.
