### ISSUE TITLE
Tinkers Construct 1.8.1 Crossbow Crash

### ISSUE THREAD

**Issue by king05** [SlimeKnights/TinkersConstruct#1287]
Hi,
after I made me a Crossbow with the new Tinkers Construct 1.8.1 on my server, I got this crash report when i want to join the server.

pastebin.com/5fdvEcmG

openeye.openmods.info/crashes/8dc0698f416c0ad7bf0b4fba7f996a9a

Hope you can help me

Regards king05.

**Comment by iTitus** [comment]
Was reported before...

**Comment by king05** [comment]
hi iTitus
can you tell me please the report number?
I can't find it.
than i can post there the crash report as well

thank you for your fast response.

Regards king05

**Comment by iTitus** [comment]
Sorry, I cannot remember the issue and I cannot search efficiently because I am on mobile.
Maybe @bonii-xx remembers the issue. It was something about Minecraft doing something weird while rendering the items in your hotbar while it is loading a world.

**Comment by bonii-xx** [comment]
#1254
