### ISSUE TITLE
Tinkers Construct issue with NEI

### ISSUE THREAD

**Issue by Gelmo92** [SlimeKnights/TinkersConstruct#1288]
Hi everybody,
I'm having a little problem with the crafting station in the modpack I'm playing.
Whwn I use the NEI (NotEnoughItems-1.7.10-1.0.3.77-universal) to see a recipe and press SHIFT+left mouse button on the "?" symbol, it will put my items in the crafting station only if there aren't chest next to it, so only if the crafting station cannot see any other inventory, except for mine obviously. I've already updated TC to latest version for 1.7.10, that should be TConstruct-1.7.10-1.8.1 but still have this problem... Can you help me please?
Happy New Year =)

**Comment by bonii-xx** [comment]
That's not supported, and has never been supported so far. I don't think it'll be implemented anytime soon, Just move the stuff into your inventory.

**Comment by Gelmo92** [comment]
Ok thanks for the answer, I thought I was doing something wrong XD

**Comment by Entoarox** [comment]
I think he means that the ? button for NEI shift-clicking doesnt work at all when there is an inventory attached to the crafting station, even when the items are in your inventory.
Unless you recently changed that bonii? (and if you did, why did you not put it in the changelog, I'm avoiding placing them near any inventories because of that!)

**Comment by bonii-xx** [comment]
That has pretty much always worked, and also is currently working.

**Comment by Entoarox** [comment]
Strange, last I played with the 1.7 branch (1.7.1c or d i think?) having an inventory next to the crafting station prevented shift-clicking the ? button from working (although normal-clicking for ghost items still worked)

**Comment by Gelmo92** [comment]
Thanks Entoarox it is exactly what I meant

**Comment by bonii-xx** [comment]
https://gfycat.com/TemptingIllinformedKagu

**Comment by bonii-xx** [comment]
Wow, well that's weird. I'll close this then.
