### ISSUE TITLE
Random crash when generating new chunks

### ISSUE THREAD

**Issue by homemmakako** [SlimeKnights/TinkersConstruct#1290]
Sometimes, when I am walking around my world my game crashes for no apparent reason. I've noticed that this crash only happens when new chunks are being generated. Here is the FULL crash log:

http://pastebin.com/gZRfGgjU

**Comment by bonii-xx** [comment]
Yeah, issue with materials that don't support bows/arrows/etc.
Fixed in next Tinkers version.
