### ISSUE TITLE
Allow Oreberry Bushes to be disabled completely

### ISSUE THREAD

**Issue by FixTheBlocks** [SlimeKnights/TinkersConstruct#1291]
Oreberries allow pretty easy, self-sustaining and in combination with certain mods rather lucrative ore farms. Too lucrative with some. I chose to disable their generation on my server but I came across a villager who is selling me a bush anyway. Would it be possible to make them more modular, allowing to disable them completely, instead of just their generation?

**Comment by bonii-xx** [comment]
Well, you could disable the villager?

**Comment by FixTheBlocks** [comment]
I'm not aware of a way to disable certain villagers and I need them for other mods. Does the option in Tinker's Construct which controls the generation of Tinkers' stuff in villages also disable these bush-selling villagers? Or can any random villager trade these items?

**Comment by bonii-xx** [comment]
Only tinkers villagers can sell them. Disabling the village creation from tinkers disables everything that tinkers has to do with villages, including the villager.

**Comment by FixTheBlocks** [comment]
I see. That could be an acceptable solution for me, albeit a bit of a sledge hammer solution. I guess it's your call whether that solves this issue.

**Comment by bonii-xx** [comment]
Well, Villagers only sell oreberries afaik. So the only thing you'd actually lose were the smelteries in the villages.

**Comment by Wulfson** [comment]
Wouldn't you also lose the Tinker's house, which I believe is the only way to get the Cutlass guard pattern?

**Comment by bonii-xx** [comment]
Indeed.

**Comment by bonii-xx** [comment]
This option causes the tinker villager to trade like any other villager. Currently existing trades in the world will still lremain though, but it shoud be fine since they're limited.
