### ISSUE TITLE
Disabling Smeltery Module disables most non-vanilla metals being used for tools

### ISSUE THREAD

**Issue by adudney** [SlimeKnights/TinkersConstruct#1292]
When the smeltery module is disabled in the module config most metals become unusable in tools, even if they're obtainable through other mods (Such as Bronze and Steel) oddly enough, the only exception to this rule is Pig Iron, which functions even with the smeltery module disabled.

This makes iron tools the highest tier of tool craftable, while not necessarily a bad thing, it would be nice to have the choice of using the higher tier materials, even if normally uncraftable. This would allow custom recipes for higher tier materials to work, and for other mods adding in bronze, copper, or steel to function correctly.

Modlist:
Forge 10.13.2.1277
CodeChickenCore-1.7.10-1.0.4.29-universal
Mantle-1.7.10-0.3.2
NotEnoughItems-1.7.10-1.0.4.83-universal
TConstruct-1.7.10-1.8.1
Baubles-1.7.10-1.0.1.10
CodeChickenLib-1.7.10-1.1.1.110-universal
ForgeMultipart-1.7.10-1.1.1.320-universal
MrTJPCore-1.7.10-1.0.3.5-universal

![2015-01-01_21 38 09](https://cloud.githubusercontent.com/assets/246232/5594399/d4edc54c-91fe-11e4-978e-d56e9893cc93.png)
![2015-01-01_21 38 12](https://cloud.githubusercontent.com/assets/246232/5594400/d505d4ac-91fe-11e4-9bca-d41923f5ee5f.png)
![2015-01-01_21 38 15](https://cloud.githubusercontent.com/assets/246232/5594402/d508fa10-91fe-11e4-8fa0-888cd5c2442f.png)
![2015-01-01_21 38 20](https://cloud.githubusercontent.com/assets/246232/5594401/d50771cc-91fe-11e4-8f00-83b3c07b10c6.png)

**Comment by bonii-xx** [comment]
What version of Tcon is that? The latest jenkins build will probably not have any problems due to https://github.com/SlimeKnights/TinkersConstruct/commit/a9f9cbf108102f36a22b997f449b57eec04d7cb7

**Comment by adudney** [comment]
TConstruct-1.7.10-1.8.1, public release version.

**Comment by bonii-xx** [comment]
K, will probably be fixed in the next version then.

**Comment by avuong2962** [comment]
Sorry if this is a stupid question, but don't you need a pattern in the table for it to work?
Also I thought metal parts had to be created in the casting table.
