### ISSUE TITLE
[Suggestion] Move armor modifiers to Materials and You V2 or Tinkers' Weaponry rather than Materials and You V1

### ISSUE THREAD

**Issue by adudney** [SlimeKnights/TinkersConstruct#1294]
Partly because of: https://github.com/SlimeKnights/TinkersConstruct/issues/1293
But also because it makes more sense for them to be with the tool modifiers, or even in their own separate book/weaponry book, rather than at the end of the first volume which contains mostly early starting knowledge.

**Comment by bonii-xx** [comment]
Nah, the 2nd book is already overloaded enough as is. And The 2nd book is 100% tool content. Book 1 is the perfect book for this.
