### ISSUE TITLE
Glass arrows not available in creative

### ISSUE THREAD

**Issue by Adaptivity** [SlimeKnights/TinkersConstruct#1296]
This commit(https://github.com/SlimeKnights/TinkersConstruct/commit/a968f41af7ca6effff55d55135a4bda7657b682b) says that they are available in creative. But they aren't. And @bonii-xx you broke latest TiC build :smile:

**Comment by bonii-xx** [comment]
They are available.. they're just not called glass arrows. It was just a testing/concept thing.

**Comment by bonii-xx** [comment]
Whoops, forgot a class @build, fixed ;P

**Comment by Adaptivity** [comment]
How they calling if it not the secret?

**Comment by bonii-xx** [comment]
"Wooden Arrows" i think.. I never changed the name :P

**Comment by Adaptivity** [comment]
Found them. They should have tooltip, isn't it? "Crafted by a legendary Glassmaker" but this tooltip isn't displayed :smile:

**Comment by bonii-xx** [comment]
As I said they were more testing stuff. Since I never came up with a good way to obtain them I also never fully implemented them.

**Comment by Adaptivity** [comment]
Ok, closing this.

**Comment by bonii-xx** [comment]
There you go.
Btw how long do you expect it'll take to get the localization stuff you're working on done?

**Comment by Adaptivity** [comment]
I might finish it in under 30 mins if I start translating it now. Only Tinkers Weaponry remains to translate.

**Comment by bonii-xx** [comment]
Yup. I want to get an updated version out for some of the bugfixes.

**Comment by Adaptivity** [comment]
Almost finished Tinkers Weaponry. Need to finish bolts translation and test it in-game. Give me an hour.

**Comment by bonii-xx** [comment]
No stress. :)

**Comment by Adaptivity** [comment]
Can you add localization support for "Bane of Pigs" and "InfiMiner"? That's seems to be same code as in "Glass Arrows" but I need some time(since I'm not a coder) to get it working properly. Already got "Bane of Pigs" be translated as "Frying Pan" you should do it better :smile:

**Comment by bonii-xx** [comment]
f5f84afa7657774a43092b6f52b6c78cde9d7687
There you go. Good job with the armor localization btw.
If you want to tell me ad hoc stuff like that it's often times easier to join me in IRC, btw.

**Comment by Adaptivity** [comment]
That was much easier than I expected. I don't use IRC. But that seems I should do.

**Comment by Skullyie** [comment]
@bonii-xx You couldn't think of a way to obtain them?  Why don't you add the chance to find Bane of Pigs in dungeons along with Glass Arrows and the InfiniMiner as a very, very low chance?
