### ISSUE TITLE
Mixing lava and water in smeltery doesn't give you obsidian anymore

### ISSUE THREAD

**Issue by Meegooo** [SlimeKnights/TinkersConstruct#1301]
In 1.7.1 it worked.
IguanaTweaks - 2.1.1.89
TConstruct - 1.8.1 (from Curse)
Forge - 1277

**Comment by Adaptivity** [comment]
It is intentional. But you can change it in the config: https://github.com/SlimeKnights/IguanaTweaksTConstruct/commit/fb6da1420a2bb5a8b4020d661b9158bdaca9c6cc
