### ISSUE TITLE
Lost heart canisters

### ISSUE THREAD

**Issue by Elvarion** [SlimeKnights/TinkersConstruct#1303]
TConstruct-1.7.10-1.8.1

Tested on server only.

If you die and close your client without respawning and then the server restart. You will loose your heart canisters and possibly other Tinker items on the extra inventory.

Had a person ragequit because he died so much and just closed his client. Then we had a server restart and when he came back a day or two later he said his hearts were gone.
So I did some testing and found its when the above happens you loose them.

**Comment by bonii-xx** [comment]
This probably is due to the way that stuff is saved in Tinkers. Can't be fixed without a complete rewrite of all that stuff, so not in 1.7.10.

**Comment by Elvarion** [comment]
Alright, Now its known at least (if it wasn't before)! :)
