### ISSUE TITLE
[Compatibility] Death event still hooked even when death penalty disabled.

### ISSUE THREAD

**Issue by joesephkatana** [SlimeKnights/TinkersConstruct#1306]
Crash report: http://pastebin.com/gkNhXUiq
I'm using 1.7.2 minecraft, 10.12.2.1121 Forge.
When ProjectZulu has its death settings enabled (% chance item drop on death) it instantly crashes if Tinker's Construct is active (when you die).  This happens even with

    B:"Keep hunger on death"=false
    B:"Keep levels on death"=false

    B:"Players drop heads on death"=false

From what I can understand from the error logs and situation, both mods are linked to the death event in such a way that causes a conflict. Disabling Zulu's death features prevents this conflict, but disabling TConstruct's death features does not. This suggests to me that its possible to code it in such a way where it doesn't hook to the death event while its disabled, but Tconstruct just isn't written that way and probably should be.  It also tells me any other death related mod is unlikely to work with Tconstruct.
I hope the broad nature of this incompatibility and the narrowness of the required fix qualifies it for repair.  I'll keep researching the issue.

**Comment by bonii-xx** [comment]
1.7.2 is not supported.
