### ISSUE TITLE
Silk Touch scythe causes metadata loss when used on certain blocks

### ISSUE THREAD

**Issue by the-vindicar** [SlimeKnights/TinkersConstruct#1307]
It appears that some blocks broken by a scythe are dropped correctly - but other blocks in AoE lose metadata when dropped. For example, using scythe on Thaumcraft silverwood leaves (in my world, 649:1) will drop 1 silverwood leaves block and several greatwood leaves block (649:0). Same thing with vanilla leaves - spruce leaves (18:1) become oak leaves (18:0).

Minecraft 1.7.10
Forge 10.13.2.1230
TC 1.7.1d
Mantle 0.3.2

**Comment by bonii-xx** [comment]
Good catch. That was really weird.
