### ISSUE TITLE
crash when placing Seared Tank 845 on any surface, corrupts world

### ISSUE THREAD

**Issue by avuong2962** [SlimeKnights/TinkersConstruct#1308]
-I was playing on a default superflat world.
-NEI showed two Seared Tanks, 845 and 846, I placed 845
-able to duplicate
-playing offline to increase Minecraft speed

Minecraft 1.7.10
Forge 10.13.2.1230
http://pastebin.com/jcnqr4vH

Also, trying to log into the world again resulted in another crash, also duplicated.
I think the world was corrupted.
http://pastebin.com/2L8TkMHi

**Comment by avuong2962** [comment]
Also, trying to log into the world again resulted in another crash, also duplicated.
I think the world was corrupted.
http://pastebin.com/2L8TkMHi

**Comment by avuong2962** [comment]
http://forum.feed-the-beast.com/threads/1-0-1-placing-seared-tank-crashes-game.54341/
Seems to be the same issue.

**Comment by bonii-xx** [comment]
Looks like Tinkers has (and always had) a faulty rendering implementation. It just never happens under normal circumstances. I still have no idea why it happened for you.
Possible candidates would be Shaders and Optifine.

**Comment by avuong2962** [comment]
Optifine Lite A4 is the problem. Doesn't crash with other versions.
