### ISSUE TITLE
HUD health rendering

### ISSUE THREAD

**Issue by pennywis3** [SlimeKnights/TinkersConstruct#1309]
Out of curiosity I wanted to know what happens when the player health exceeds what the TCon handler can handle, and I discovered that once the white hearts are full, half-hearts of the previous colors are rendered with an offset (starting with orange). I'm not sure what's supposed to render instead, the second row of hearts from newhearts.png maybe?
![2015-01-05_02 16 11](https://cloud.githubusercontent.com/assets/4288061/5608329/d7c5ef5e-9480-11e4-93bc-093aea7eea55.png)
TCon-Version: 1.7.10-1.8.1
Absurd amounts of HP were obtained with the Heart Crystals mod.

**Comment by 61352151511** [comment]
I believe this is forge and not tinkers construct due to the fact that other mods (Such as the heart crystal mod, advanced genetics, botania, extra utilities) can all edit the maximum amount of health a player can have without needing tinkers construct.

**Comment by bonii-xx** [comment]
If you have that many hearts, you deserve a broken display. :P
