### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by squeek502** [SlimeKnights/TinkersConstruct#1310]
"Castingt" seems like it should be "Casting": https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/util/IMCHandler.java#L156

**Comment by squeek502** [comment]
Another probable typo that I stumbled upon: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/TinkerTools.java#L849

The last parameter should probably be 1 (stone's matID), not 0 (wood's matID)

**Comment by bonii-xx** [comment]
Correct. Luckily both are not really an issue because the first is only used for Logging, and the second is only an issue if stone is disabled in the tinkers config.
