### ISSUE TITLE
Previously Craftable Slime &  Paper Items Uncraftable?

### ISSUE THREAD

**Issue by MBfromOK** [SlimeKnights/TinkersConstruct#1313]
It's me again Margaret!!!

I have looked at length through forum pages, and then looked long and hard both on the internet and in my configs in an attempt to prevent the following answer(s) that will most likely result in me wearing the Derpface... That being said: Here is my (related) modlist:

MineCraft Mods: A | MineCraft Mods: B
------ | ------
* Minecraft 1.7.10 | * Forge 10.13.2.1236
* FML v 7.10.85.1236 | * OptiFine _1.7.10_HD_U_B1
* Tinkers Construct 1.8.1 | * Tinkers Mechworks 75.Oafb56c
* ExtraTiC 1.0.0 | * TiC Tooltips 1.1.11b
* Iguana Tinker Tweaks 2.0.6 | * Metallurgy-1.7.10-4.0.5.75
* MetallurgyCore-1.7.10-4.0.4.18 | 

So, to the question / problem / bug:

Slime Parts: 
I am trying to make a Bronze excavator with a Slime Rod and at least 1 paper part, the problem is that I can't find a way to create either a Blue Slime Tough Tool Rod or a Paper Large Plate.

    **Note**: Yes, I did craft the slimy mud with sand and dirt and cook it into the Slime Crystal.

Thinking I misunderstood I went put the Slime Crystal in the Smeltery... Nothing happens, same with Slime Crystal in Part Builder with Tough Rod Pattern \ Cast... 

Paper Parts: 
Several sites I found stated that you simply place the appropriate number of papers / paper stacks in the Part Builder next to the desired pattern and Bob's your Uncle... you have the part... or NOT!
Screenshots below of paper attempt with the tool rod, also attempted with the large plate pattern & cast (per the [advice for a great tool](http://tinkers-construct.wikia.com/wiki/Recommended_Tools#Mining_Level_8-11_Hammer) here) .. HELP!
![papersupply](https://cloud.githubusercontent.com/assets/7131008/5624117/8efa0896-9525-11e4-8343-8a7b5cdcbfda.PNG)
![toughpattern](https://cloud.githubusercontent.com/assets/7131008/5624120/92c96aca-9525-11e4-84ea-1ccfbd6f7657.PNG)

    Note: I noticed that there is a very limited list of things that either paper / slime seem
     to be usable for:
 | Paper | Slime
-------- | -------- | --------
Tool Rod Pattern | X | X
Tool Binding Pattern | X | X
Wide Board Pattern | | X
Fletching Pattern | | X

Based off the above list I am guessing that Slime & Paper use has been changed and is now only available for basic tools?

Slime Crystals aren't listed as materials for either the Tough Tool Rod or the Large plate pattern.
![patternmaterials](https://cloud.githubusercontent.com/assets/7131008/5624121/94bfa920-9525-11e4-9ec4-76b1c48af702.PNG)

At this point I am guessing that these utility uses were removed, but just in case it was missed / dropped by accident...

NOTE: Angmallen, Damascus Steel and Certus Quartz show as material.ingredient (screenshot above).

I believe I have the addon that you mention on the forum page site to ensure compatibility with Metallurgy, but I am not 100% as the post didn't name it and the link provided takes you to the Metallurgy 2's forum / download page (that doesn't seem to list any addons).

Thanks!

PS: If there is an official, more accurate, or preferred forum TConstruct users should be using  please tell me, I will create the content if I have to, it would just be nice to have something that is usable.

Also, where and how can I get & use / test TSteelworks? I am fine with compiling / running source, just not sure how that works..

**Comment by bonii-xx** [comment]
Iguana Tinker Tweaks Restriction. As you correctly noticed, it even tells you what's a valid material under the restrictions on the Pattern/Cast. Turn it off or configure it correctly to your liking.
