### ISSUE TITLE
Pink Slime crashing

### ISSUE THREAD

**Issue by Aulton** [SlimeKnights/TinkersConstruct#1316]
So I was trying to make a pink slime crossbow with a pink slime body, crossbow limb, paper binding and a fiery bowstring. Upon placing the materials into the tool forge I crashed to desktop. Upon looking into NEI, I noticed there wasn't a pink slime crossbow, so I figured I would post a log here, and just leave a suggestion to make  the pink slime crossbow pieces uncraftable.

http://paste.atlauncher.com/view/f851bad8

**Comment by bonii-xx** [comment]
Version?

**Comment by Aulton** [comment]
1.8.1

Included in the most recent Resonant Rise 3.

**Comment by bonii-xx** [comment]
Fixed in newest version.
