### ISSUE TITLE
Double-Jump and belt Issue since TConstruct-1.7.10-1.8.0

### ISSUE THREAD

**Issue by Matzl1993** [SlimeKnights/TinkersConstruct#1321]
Hello,

Since 1.8.0 the Double-Jump on Wings, boots or both don´t work.
In Version 1.7.1c the Jump work fine and exactly.
In Version 1.7.1d the Jump don´t work every time.
Now in Version 1.8.2a there is no function with the modification on boots or wings.

The belt is buggy as well.
Switching the belt work in Version 1.7.1c smoothly and nice. Now there are some issues.
Switching don´t work every time or switch twice.

Tinkers Construct and Mantle the only 2 mods which are installed.
Minecraft Version : 1.7.10
Forge-Versions tested : 10.13.1.1217, 10.13.1.1225, 10.13.1.1230(recommend Version), 10.13.1.1240, 10.13.1.1258, 10.13.1.1276
Tconstruct : 1.7.10-1.8.2.a
Mantle : 1.7.10-0.3.2

If you have any question, you can write me a pn ;)

**Comment by bonii-xx** [comment]
Remove/Update NEK.

**Comment by Matzl1993** [comment]
What is NEK?

I have only installed tinkers construct and mantle

**Comment by Mengmoshu** [comment]
NEK is Not Enough Keys.

**Comment by Matzl1993** [comment]
But nek isnt installed. Must i install nek to use the features?

**Comment by Matzl1993** [comment]
Now I have installed NEK without success.
The doublejump dont work.
There are some configs to do?

**Comment by Adaptivity** [comment]
Can confirm this.

**Comment by bonii-xx** [comment]
@TheTemportalist  should probably take a look, he's the only one who messed with the stuff that is connected to that since 1.7.1c

**Comment by JackDraco** [comment]
I'm no expert, but I suspect this may be related to how the code attempts to bind the jump key to ArmorControls.jumpKey, and then checks for that key while in midair. I don't think ArmorControls.jumpKey is being registered properly as a keybinding. Specifically, it looks like the registerKeys() method within ArmorControls is adding the bindings for jump and inventory to the "keys" array *after* it has already attempted to register all the bindings in that array.

I'm still pretty new to this stuff, but maybe this will be helpful to someone. :-)

**Comment by TheTemportalist** [comment]
Ill take a look see when I get a chance. Currently working on quite a lot, mainly with 1.8 updates.

**Comment by Adaptivity** [comment]
Hope it can be fixed for the next release. Because, well, it's broken :D

**Comment by Matzl1993** [comment]
Hello,

Why you close the ticket?

Greetz
Matzl

**Comment by Adaptivity** [comment]
Fixed in Dev. Fix will be available in the next version.

**Comment by TheTemportalist** [comment]
\o/
/me goes and looks at commit

**Comment by bonii-xx** [comment]
The registration for the handler was missing. I have no idea where that went, since I've fixed the handler itself not too long ago, and it worked there.
