### ISSUE TITLE
[Request] MineTweaker Support

### ISSUE THREAD

**Issue by UndeadZeratul** [SlimeKnights/TinkersConstruct#1322]
I'm aware Modtweaker currently adds support, but @joshiejack has stopped working on it a while ago.  Also, I've noticed a few issues when dealing with the smeltery, including https://github.com/joshiejack/ModTweaker/issues/63.  I don't know his policies on giving you the code to integrate it with TiC, but I saw Blood Magic now has the classes from ModTweaker, and they're credited to Josh. [Here's](https://github.com/joshiejack/ModTweaker/tree/master/src/main/java/modtweaker/mods/tconstruct) the classes you'd need to implement in order to get it working.

If TiC had native support for Minetweaker, I feel it'd be able to safely keep up with the mod's updates.

**Comment by bonii-xx** [comment]
Nah. MineTweaker is working fine.
