### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by LeoJonson** [SlimeKnights/TinkersConstruct#1323]
![2015-01-08_11 58 10](https://cloud.githubusercontent.com/assets/7913708/5661596/f3fb1bf4-972d-11e4-96fc-7e5ef9e9000a.png)
WHY ??????????????

**Comment by Techokami** [comment]
Shouldn't that be a Crossbow Body and not a Large Plate?

Sent from my Windows Phone
________________________________

**Comment by LeoJonson** [comment]
It says a large plate sa it cvan be seen ant the bottom of the gray area whwere it says longbow

**Comment by LeoJonson** [comment]
nope doest work just tryed it

**Comment by LeoJonson** [comment]
and some metals from metalurgy don't work

**Comment by laz2727** [comment]
Maybe the string is not registered, use vanilla one.

2015-01-08 18:54 GMT+06:00 LeoJonson <notifications@github.com>:

**Comment by LeoJonson** [comment]
ok il try im report back when I get back home and try it =)

**Comment by bonii-xx** [comment]
You're using material that don't support bows.

**Comment by laz2727** [comment]
Iirc that's Natura string.

**Comment by LeoJonson** [comment]
ok sorry sassy bonii
