### ISSUE TITLE
Mattock gives double the damage it shows

### ISSUE THREAD

**Issue by GuGuISH** [SlimeKnights/TinkersConstruct#1325]
Minecraft version:1.7.10
Mod version:1.7.10-1.8.1
Maybe affecting mods:Iguana Tweaks 1.7.10-2.0.6 , ExtraTiC 1.7.10-1.0.3

Im using the SkyFactory 2 modpack and i noticed after i made a Alumite Mattock, it shows +8 Attack Damage but the damage it really does is 16.

**Comment by UndeadZeratul** [comment]
It could be that the vanilla "+x damage" on the tooltip shows in full hears, whereas the TiC information is shown in raw damage, which is only half hearts.  +8 damage means +8 full hearts, or 16 damage.

**Comment by Elle199** [comment]
Could also be that that is how it is in SkyFactory 2

**Comment by bonii-xx** [comment]
Reproduce it with only the mods you mentioned and I'll take a look.

**Comment by TherminatorX** [comment]
Pretty sure it's what @UndeadZeratul said
