### ISSUE TITLE
Slime Islands don't generate in 1.8.2a?

### ISSUE THREAD

**Issue by Doctordharok** [SlimeKnights/TinkersConstruct#1331]
Hi, I love Tinker's construct, I was working on a mod review and noticed in the most recent version (1.8.2a) SLIME ISLANDS don't appear to be properly generating in the world? I've been flying around in creative in a freshly spawned world for about an hour and passed various biomes but haven't found any - help? Am I doing it wrong or is there a bug?

I've already removed all other mods - I'm using only TConstruct and mantle (0.3.2).

I'm on a new world- I've flown 300 spaces east of world spawn, teleported to 1000,1000 and flown 1000 spaces north, teleported to 1000,-1000 and flown around sporadically- no dice over any biomes I've seen!

My config file appears to permit them:
dimblacklist {
    # True: slime islands wont generate in any ages other than overworld(if enabled); False: will generate in all non-blackisted ages
    B:GenerateSlimeIslandInDim0Only=false

    # Add dimension ID's to prevent slime islands from generating in them
    I:SlimeIslandDimBlacklist <
     >

    # Generate slime islands in flat worlds
    B:genIslandsFlat=true

    # True: slime islands generate in overworld; False they do not generate
    B:slimeIslGenDim0=true
}
But I just can't find one! Forge build 1230 if that's relevant.

**Comment by Adaptivity** [comment]
They are spawning just flawlessly. http://i.imgur.com/pEvziXV.jpg

**Comment by bonii-xx** [comment]
Sounds like bad RNG or you simply might've overlooked them. Also there was an issue with Forge that had to do with worldgen some time ago, so it might also be that Forge issue.

**Comment by kitt3n** [comment]
They spawn just fine, I've found one in 1.8.2a

**Comment by bonii-xx** [comment]
Seems to work perfectly fine. You probably just had bad RNG.
