### ISSUE TITLE
Platinum arrow crash

### ISSUE THREAD

**Issue by Elle199** [SlimeKnights/TinkersConstruct#1332]
When ever you try to make platinum arrows you will crash with TCon 1.8.0. I'm using the fireball1725 firepack and wanted to make some arrows, I tried to use the shiny ingots/platinum but every time it went to render the arrow it would crash me to desktop which means I don't get a crash report. So I can't even find out where the problem is but just wanted to say it so everyone knows. 

Great mod Boni :)

**Comment by laz2727** [comment]
I'm sure that was fixed.
