### ISSUE TITLE
Fluids don't render with colour in the smeltery/casting table

### ISSUE THREAD

**Issue by ganymedes01** [SlimeKnights/TinkersConstruct#1334]
When rendering a fluid the smeltery and the casting table/basin seem ignore the value returned by Fluid.getColour(FluidStack)

**Comment by bonii-xx** [comment]
They do, and it works perfectly fine for the Minechem liquids.

**Comment by ganymedes01** [comment]
Yeah, you're right, it works.
I don't know why it didn't work when I tested it last time. Maybe I had some old version or something...

Sorry about this.

**Comment by bonii-xx** [comment]
Must've been an old version. Support for it is relatively new (I think 1.8.0 or so)
