### ISSUE TITLE
Cant repair electrum tools.

### ISSUE THREAD

**Issue by Zacuis** [SlimeKnights/TinkersConstruct#1338]
Hi i have recently been playing sky factory 2 and mod sauce. in both mod packs i am unable to repair elctrum tools using an ingot. like you can with other tools

**Comment by bonii-xx** [comment]
cc @skyboy
Missed a mapping?

**Comment by Adaptivity** [comment]
Related to: https://github.com/CoFH/Feedback/issues/15

**Comment by skyboy** [comment]
@bonii-xx It appears there's no way to add a repair material without also adding a material for the making parts with the part builder (if this does both, and not just making parts)

**Comment by bonii-xx** [comment]
Possibly. I'll have to double check then.

**Comment by bonii-xx** [comment]
skyboy can you test if the IMC I added works with your stuff? Format is as follows:
tag.setInteger("MaterialId", 123); // the one used when registering the material
tag.setInteger("Value", value); // like the partbuilder material. Ingots should have Value 2
myItemStack.writeToNBT(tag); // the item is sent via nbt.

Message is "addMaterialItem"

**Comment by skyboy** [comment]
```
if (!checkRequiredTags("Material Item", tag, "MaterialId", "Value", "id", "Count", "Damage"))
```
?
Also, for consistency, the item should be in the tag "item" as with the part builder material

**Comment by bonii-xx** [comment]
Moved the item to an "Item" tag, had it directly in it for simplicity. But at least that way intentions are more obvious.
