### ISSUE TITLE
Crash with comparators on smeltery drains

### ISSUE THREAD

**Issue by Ephys** [SlimeKnights/TinkersConstruct#1342]
Placing a comparator in front of a smeltery drain will cause the game to crash when the chunk is unloaded (NPE at that line https://github.com/SlimeKnights/TinkersConstruct/blob/c20d91d3a1d975fd6ae492925612d453c20f7260/src/main/java/tconstruct/smeltery/logic/SmelteryDrainLogic.java#L189 )

Also the smeltery does not mark the drain as dirty when the signal strength changes which forces to place à redstone loop next to the comparator to update it

Crash report: http://pastebin.com/qRfUHSVt
Tinkers' Construct version 1.8.0

**Comment by bonii-xx** [comment]
The problem is not the chunkloading, but that the smeltery is invalid.
