### ISSUE TITLE
Tinkers hammers able to bypass most protection mods.

### ISSUE THREAD

**Issue by DatenThielt** [SlimeKnights/TinkersConstruct#1346]
I am posting this here, and have done so in a few Protection mod githubs, But due to the way Tic hammers break the surrounding blocks it makes them very easy to use to bypass conventional protections like Worldguard, Towny, Prism Logs.  From what I can tell the blocks broken are not associated with the player in any way (Apart from the central block) allowing it to bypass the above mentioned. Is there any way to work around this or a small code change. Thank you.

**Comment by bonii-xx** [comment]
Can you do a local test if this version fixes it? https://dvs1.progwml6.com/jenkins/job/TConstruct_1.7.x/lastSuccessfulBuild/artifact/build/libs/TConstruct-1.7.10-1.8.2.build872.jar

**Comment by DatenThielt** [comment]
Will give it a good old test now!

**Comment by DatenThielt** [comment]
I can confirm that with this version loaded, The tools can no longer bypass any kind of WG/Prism/Towny protection and the user gets the expected error! Thank you Bonii!

**Comment by bonii-xx** [comment]
Perfect, thanks for testing.
