### ISSUE TITLE
Corrupted NBT Chisel Craft to Uncorrupted Dupes.

### ISSUE THREAD

**Issue by Havvy** [SlimeKnights/TinkersConstruct#1348]
When putting a corrupted chisel into the crafting GUI to turn it into a non-corrupted chisel, it does not use up the corrupted chisel, instead giving it 1xp and using a point of durability, as if it successfully chiseled something.

**Comment by bonii-xx** [comment]
Vanilla crafting issue. It's only a chisel. :p
