### ISSUE TITLE
[Suggestion] Different Fuels, Different Max Temperatures

### ISSUE THREAD

**Issue by UndeadZeratul** [SlimeKnights/TinkersConstruct#1349]
So by default, unless something changed recently, the max temperature we can reach with the smeltery is 800.  Now, that is fine for most cases, but what if you wanted a bit more progression with the smeltery, and push some metals' melting points up (or if "realistically" some metals actually do melt at a higher temperature already) above 800?  Would it make sense to have the max temperature of the smeltery be tied to the fuel that's powering it?  At that point, you could also put the fluid type and its max heat in the config, so players and pack makers can tweak/add fuels to the smeltery as they wish, as well as define what fluids provide a higher internal temperature than others, let alone what that max temperature even is.

If I remember correctly, blazing pyrotheum support was added into smelteries a while back, would it make sense that if the smeltery is powered by pyrotheum, it provides a higher maximum temperature than just normal lava?  That way, at the start of a world, players could be limited to what metals can be melted down and processed, until they can craft a reliable amount of pyrotheum, which would then upgrade their smeltery capabilities.

Of course, the default values of these configs could stay as they are so that unless someone actively changes something in their configurations, it's a transparent change.  However, for someone like me, who would love to add multiple molten metals to my smeltery in my pack, but don't want every metal to be able to be melted down within lava's melting temperatures, it would be nice to have this bit of flexibility.

**Comment by bonii-xx** [comment]
That's already how it works. Our metals will never require more heat than lava provides, you wouldn't be able to use Tinkers without oder mods otherwise.
If somebody wants something like that they either have to do it themselves for a modpack, or use the Tinkers API to add the proper support for their stuff.

**Comment by UndeadZeratul** [comment]
Well that's why I was asking, for our modpack.

I know by default nothing requires higher than 800, but if I wanted to melt down, say, enderium, It normally needs pyrotheum, but with a max heat of 800, this could easily be done with just lava.  If a fluid could allow the smeltery to go above 800, then I could fuel my smeltery with that and actually smelt down high tier metals.

I can try to look into something for our "modpack mod" that assists us with various tweaks, but last time we tried, we couldn't get the API jars to work correctly, right @Nincodedo?

**Comment by Nincodedo** [comment]
I tried it a few months ago but couldn't get the jars to work within my dev environment properly. Probably was user error.

**Comment by bonii-xx** [comment]
The API jars are always messed up anyway. Might be they contain a reference they shouldn't. Just copy the files you need in and don't ship them. You shouldn't need more than the TConstructRegistry.

**Comment by UndeadZeratul** [comment]
That's, a weird way to go about doing it, but ok then.  We'll see what we can come up with for our pack then, thanks Bonii!
