### ISSUE TITLE
Comparator on smeltery drains - Revenge of the / by zeo

### ISSUE THREAD

**Issue by Ephys** [SlimeKnights/TinkersConstruct#1350]
I picked up a dev build to let people log on my server again (Thanks for the quick fix !)

However the is now a division by zero exception there on line 193
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/smeltery/logic/SmelteryDrainLogic.java#L193

I'm using this build: https://dvs1.progwml6.com/jenkins/job/TConstruct_1.7.x/871/
Here is a crash report: http://pastebin.com/Cs1Xvxx9

**Comment by bonii-xx** [comment]
Hm, weird. I can't think of any situation when the maximum capacity can be 0.

**Comment by laz2727** [comment]
No smeltery? I can't look at the code right now, but maybe.
