### ISSUE TITLE
Smeltery not updating when items are inserted through Botania Red Stringed Container

### ISSUE THREAD

**Issue by KaiserYoshi** [SlimeKnights/TinkersConstruct#1352]
If items are placed in the Smeltery Controller through Botania's Red Stringed Container, they do not begin melting, and the ghost blocks do not appear inside the Smeltery, unless the player accesses the Smeltery Controller.

Forge 7.10.85.1272
TiCo 1.8.2a

**Comment by bonii-xx** [comment]
It works, it just seems to not sync. Informed @Vazkii

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/commit/b09034c6678b1b4bf413eb482b08cad7d17cc5bb
