### ISSUE TITLE
Broken rendering with tanks + lava

### ISSUE THREAD

**Issue by srs-bsns** [SlimeKnights/TinkersConstruct#1356]
Adding lava to a TiCon tank causes an X-Ray effect.

I was using build 873 from: https://dvs1.progwml6.com/jenkins/job/TConstruct_1.7.x/
But it's likely this bug was introduced in the previous build with the inclusion of commit: https://github.com/SlimeKnights/TinkersConstruct/commit/cd4206df72e8369819cb183758693c79e51e3cd3

Rendering is fine up to, and including, build 871.

Tank without lava:
![](http://www.nihilism.ca/~misc/images/20150119-TiCon-01.png)

Tank with lava:
![](http://www.nihilism.ca/~misc/images/20150119-TiCon-02.png)

Note: This is on an old computer with an old video card (Radeon X850), so this might not happen with newer hadware.

**Comment by DatenThielt** [comment]
I Can confirm this is happening to everyone on our server since updating to the latest build

**Comment by bonii-xx** [comment]
Are you guys using Optifine?
It's one of these really weird cases where the wanted behaviour is not really fixed because minecrafts rendering is a derp.

**Comment by DatenThielt** [comment]
Not using optifine at all, And its only been since we updated tinkers :( and as above, only seems to effect AMD Cards

**Comment by ate0ate** [comment]
I can also confirm this using an intel integrated graphics chip in an i5 laptop. No optifine or rendering mods. I do have fastcraft installed but I can't even play modded minecraft without that.

**Comment by srs-bsns** [comment]
Confirmed fixed.
