### ISSUE TITLE
Lava is Consumed Equally For One Item or 100

### ISSUE THREAD

**Issue by SixOnTheBeach** [SlimeKnights/TinkersConstruct#1357]
I looked and was surprised to find nothing reported of it, but the smeltery consumes an equal amount of lava for one item as it does for 100. Whether this is intended or not, when you have a big enough smeltery, you can basically smelt things for such a minimal cost it's basically free, such as 1000 iron for one bucket of lava.

**Comment by bonii-xx** [comment]
Yes, bigger smelteries are more efficient.

**Comment by SixOnTheBeach** [comment]
That's not higher efficiency though, it's a point of ridiculousness. If it's not a bug, then may I ask for a config to change that?
