### ISSUE TITLE
[Bug] Inventory Tab

### ISSUE THREAD

**Issue by Drakray** [SlimeKnights/TinkersConstruct#1358]
When using other mods that add Tab, like Galacticraft or Custom NPC, sometime Tabs overlap, like in TolkienCraft II (CustomNPC Quest Tab and TC Armor, TC Knapsack and Faction Tab), or Tab are not align correctly when under Buff/Debuff, which cause Tab-clicking a pain

**Comment by the-vindicar** [comment]
Tabs are glitched if user has potion effect applied. It seems that tab "active area" does not correspond with visible tab position.

**Comment by Drakray** [comment]
there is also an overlap of Tab, when there is no potion effect on

**Comment by mDiyo** [comment]
Tabs only appear glitched because of how NEI changes position of the gui.
