### ISSUE TITLE
Can't Repair Platinum Tools

### ISSUE THREAD

**Issue by stephenmc608** [SlimeKnights/TinkersConstruct#1359]
http://forums.atlauncher.com/thread-7875.html

I was playing version 2.2.3 of Sky Factory (http://www.atlauncher.com/pack/SkyFactory) and I made a pickaxe with a Platinum pickaxe head, but when I tried to repair it, I could not. I tried using the Thermal Expansion Shiny ingot and the Ex Nihilo Platinum ingot, but neither worked.

![2015-01-21_23 46 08](https://cloud.githubusercontent.com/assets/8429816/5865828/69de138a-a25a-11e4-944a-8db5af3174e0.png)
![2015-01-21_23 46 19](https://cloud.githubusercontent.com/assets/8429816/5865829/69deb1be-a25a-11e4-9ad3-6a29121dca10.png)
![2015-01-22_14 45 11](https://cloud.githubusercontent.com/assets/8429816/5865834/748c0fd0-a25a-11e4-9acb-322e977c4420.png)

One of the users on the ATLauncher forums was helping me, and they said that there was no config option for it anywhere. I also checked to see if there was one, but I could not find one.

**Comment by UndeadZeratul** [comment]
Isn't this related to https://github.com/SlimeKnights/TinkersConstruct/issues/1338?

**Comment by stephenmc608** [comment]
Well, I guess it is. At least there's more information/pictures on the issue now.
