### ISSUE TITLE
Bounce Pad breaking transparency on everything

### ISSUE THREAD

**Issue by Mathe172** [SlimeKnights/TinkersConstruct#1361]
I noticed a very annoying bug: When placing a bounce pad anywhere in the world, it causes every transparent texture to become opaque. This depends on the angle you're looking, but everytime you place one, the problem starts instantly.
Some pictures:
![2015-01-23_18 36 58](https://cloud.githubusercontent.com/assets/3540742/5879412/6576c28a-a32f-11e4-9c58-1b6d41a382e5.png)
![2015-01-23_18 36 54](https://cloud.githubusercontent.com/assets/3540742/5879414/69feb7c2-a32f-11e4-8e61-9f65edef741f.png)

My setup:
MC 1.7.10
Forge 10.13.2.1230
Mantle 0.3.2
TConstruct 1.8.2a
[Edit: No other mods installed]
Java 1.8u25 / Java 1.7u67 (no arguments other than '-version:"1.7"')
Windows 8.1:amd64:6.3
Intel HD Graphics 4000 (i7 3537U)

(I don't know if all these details are necessary, but just in case it's very rare - if you need even more, just ask ;-) )

**Comment by bonii-xx** [comment]
Yep, quite annoying. Already fixed that recently.
cd4206df72e8369819cb183758693c79e51e3cd3
