### ISSUE TITLE
Seared glass client crash

### ISSUE THREAD

**Issue by Nentify** [SlimeKnights/TinkersConstruct#1362]
http://pastebin.com/uBSetcqK
http://pastebin.com/1gxLPtt5

When covering all sides of seared glass with blocks, the client crashing with the crash reports posted above. I have reproduced this in SSP, but haven't attempted without any other mods as of yet. Optifine is not installed, and the issue still occurs without Fastcraft installed. Window/tank do not crash.

Example: Placing the last block against the seared glass will instantly crash the client before the block is attempted to be placed. Any time you log back in here you will crash.

![](http://i.nentify.me/vtntSUp4.png)

**Comment by Adaptivity** [comment]
Confirmed.

**Comment by Nentify** [comment]
Is it safe to compile this for live production use, or will there be a new release soon?

**Comment by Adaptivity** [comment]
If you really need to fix this crash get latest version from Jenkins: https://dvs1.progwml6.com/jenkins/job/TConstruct_1.7.x/875/ it should be stable as release version.

**Comment by bonii-xx** [comment]
You should never use anything but releases for live-production-use. What you CAN do however, is use a jenkins build, remove the offending block, and then switch back to a release version. ;)
