### ISSUE TITLE
"Materials And You" glitch

### ISSUE THREAD

**Issue by jvpeters-** [SlimeKnights/TinkersConstruct#1363]
All the TConstruct books had most of the pages covered in "▮" with random pages untouched.

It appears to only affect a single world and started around the time when I installed optifine.
It stayed when I uninstalled optifine, but dying seemed to fix it.

**Comment by bonii-xx** [comment]
Optifine is not supported.
There once was a similar bug, but that was fixed many versions ago, check if you're using an old version.
