### ISSUE TITLE
registerBoltCasting() gets called before all materials are registered

### ISSUE THREAD

**Issue by squeek502** [SlimeKnights/TinkersConstruct#1364]
From IRC:
> `[20:00] <seebs> With the new 1.8 bow/arrow stuff, there's NEI examples of thaumium bolts, but I can't seem to make any by hand, and I am wondering if I am doing something obviously wrong.`
> `[20:01] <seebs> If I put a manyullyn tool rod in a casting table, I can pour manyullyn or iron on it.`
> `[20:01] <seebs> If I put a thaumium tool rod in a casting table, it doesn't seem to be willing to pour `anything.
> `[21:21] <seebs> A friend looked at the logs more closely and has a theory.`
> `[21:21] <seebs> The registering of bolts happens before the registering of thaumium.`
> `[21:21] <seebs> So at the time when it's registering bolts, there's no thaumium tool rods to register, and when it adds them, it doesn't also add them as bolts.`

[registerBoltCasting](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/weaponry/TinkerWeaponry.java#L360-L392) gets [called in init](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/weaponry/TinkerWeaponry.java#L119), while [thaumium is added](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/TinkerTools.java#L721) in [postInit](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/TinkerTools.java#L348).

**Comment by bonii-xx** [comment]
That's not the issue. As you can see in the modIntegration function all the parts have to be registered for each material separately. Thaumium simply is not registered for bolt casting and tbh I wouldn't want it to be.
That it shows in NEI is simply a side-effect of how all that stuff is handled. Creative items can have impossible combinations, sadly.

**Comment by squeek502** [comment]
So you're saying you intended to allow pouring molten metal onto a paper tool rod, but not a thaumium one? One of those has to be a bug, right?

**Comment by bonii-xx** [comment]
Paper tool rod is possible? I thought that wasn't possible either, hm.
