### ISSUE TITLE
Rendering Glitch

### ISSUE THREAD

**Issue by CandiceJoy** [SlimeKnights/TinkersConstruct#1365]
This rendering glitch http://puu.sh/eX5K5/a51959e147.png is appearing in TConstruct-1.7.10-1.8.2.build874.jar.  I've spent hours narrowing it down, and the problem is definitively TiCon.  If I remove TiCon or downgrade, the problem goes away and if I add it back the problem comes back.  I will note, though, that the problem does *not* occur in a world free of TiCon blocks.  That is, once the mod is removed and then re-added without refreshing the world, the problem stays gone because there are no longer any TiCon blocks in the world.  I am unable to narrow it down to a specific block or setup.

**Comment by Adaptivity** [comment]
I saw problem similar to this on one forum. Are you using any shaders?

**Comment by bonii-xx** [comment]
#1356
