### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by jeanropke** [SlimeKnights/TinkersConstruct#1368]
I am using a modpack (The 1.7.10 pack), it has been updated.  When I load my world generated in the old version in the new version, Tinkers Construct is crashing Minecraft.

Complete latest.log:
http://paste.ubuntu.com/9862103/

- Thank you and sorry for my bad english.

**Comment by laz2727** [comment]
*Epic voice* Your world has been corrupted.

2015-01-25 21:41 GMT+06:00 jeanropke <notifications@github.com>:

**Comment by jeanropke** [comment]
The modpack has auto backup, and I used a backup 18h ago and it worked. Weird...
