### ISSUE TITLE
[Feature request] removing damage

### ISSUE THREAD

**Issue by svennieke** [SlimeKnights/TinkersConstruct#1374]
i would like to request a creative only feature wich alows you to instead of increase decrease the damage on a tool 
i am requesting thos for upgraded tools like a frying pan with alot of knockback but it would not kill the mob ever
already thanks for reading

**Comment by laz2727** [comment]
Silktouch?

**Comment by HadesDurin** [comment]
no he wants a tool which only knocksback the enemys and doesnot do anydamage to them

**Comment by UndeadZeratul** [comment]
Right, and laz is saying to add another use for Silktouch, wherein putting it on weapons lowers the damage, since the weapon is now silky soft and pillowy.

**Comment by laz2727** [comment]
I say that ST ALREADY lowers damage.

2015-01-28 20:17 GMT+06:00 Undead Zeratul <notifications@github.com>:

**Comment by UndeadZeratul** [comment]
oh?  Well then forgive me, I didn't know it was already implemented.  That's actually good to know :)

**Comment by bonii-xx** [comment]
Sounds to me like you need to do a bit of tinkering to reach what you want ;)

**Comment by TherminatorX** [comment]
Actually, even with ST, you can't make a tool so that it doesn't do damage. This is because it is "+attack damage," so you will only get down to .5 hearts per hit. This is still a possible feature, and therefore an open issue unless boni says otherwise.

**Comment by bonii-xx** [comment]
Reason being that I'm not going to implement it because it's too specific ;P
