### ISSUE TITLE
Breaking grass with Manyullyn shovel takes too long

### ISSUE THREAD

**Issue by johndubya** [SlimeKnights/TinkersConstruct#1375]
I am using Tinker's Construct 1.8.1 for Minecraft 1.7.10.

I recently made a Manyullyn shovel (Manyullyn for both shovel head and tool rod). I added 100 haste with redstone and auto-repair with moss.

I noticed that when targeting dirt blocks, the shovel breaks the blocks almost immediately upon contact, but when breaking grass blocks, it takes about as long as with a vanilla iron shovel.

With an iron shovel, time taken to break dirt and grass is nearly identical, but with a Manyullyn shovel, the difference between the time it takes to break dirt vs. grass is drastic. Is this by design?

**Comment by bonii-xx** [comment]
Can't reproduce, works normally for me. Grass always takes longer to break than Dirt, also Manyullyn isn't that fast.
Could also be that you need to update or some other mod is messing with it.
