### ISSUE TITLE
Oreberry Blocks and Textures Turn Invisible/Wrong Texture

### ISSUE THREAD

**Issue by RickyM90** [SlimeKnights/TinkersConstruct#1376]
Using latest Tinker's build 1.8.2a and Mantle 0.3.2
Textures for Oreberries are not rendering properly and turning invisible. Items themselves have reverted to the default texture
![2015-01-31_00 35 53](https://cloud.githubusercontent.com/assets/10774253/5977212/5c60da34-a8e1-11e4-821d-93c54dcb0137.png)

**Comment by bonii-xx** [comment]
Fix your Optifine.

**Comment by RickyM90** [comment]
Don't have Optifine installed. Its a conflict with Botania I found by testing. Not too sure why though

**Comment by bonii-xx** [comment]
Might be that something gave thos bushes an incorrect metadata

**Comment by RickyM90** [comment]
Might be indeed. Thanks Boni! Really enjoying the new version though. That's only a small bug. I dont mind if they're invisible as long as I know they're there

**Comment by Shirohoshi** [comment]
I would rather the textures work, for me it does that with more then just Oreberry bushes, is also does it to the smeltery stuff, and the tinker tables you use at the beginning to craft tools. sure the weapons and such are still there but it does get hard to figure out where things are and go without forced to put down a sign D:

**Comment by bonii-xx** [comment]
Fix your optifine.

**Comment by themrsheep** [comment]
sorry , how do i fix it ? (my optifine)
