### ISSUE TITLE
[Request] Register shards in the ore dictionary

### ISSUE THREAD

**Issue by ganymedes01** [SlimeKnights/TinkersConstruct#1381]
Would make compatibility easier if the shards (the 0.5 material value stuff) were registered in the ore dictionary

**Comment by bonii-xx** [comment]
Please don't depend on shards for anything. They're way to inconsistent and can't be crafted properly like that. >_>

**Comment by ganymedes01** [comment]
Ah okay, well I wasn't exactly going to depend on them, I was just going to add them automatically using AOBD.

**Comment by laz2727** [comment]
There's no way to get them without adding stuff as tool materials, and it
gets autogenerated with other tool parts.

**Comment by ganymedes01** [comment]
Ah, if it gets auto-generated then there's no point me adding them. I thought of adding them to make it easier for people who might want to add custom metals using them, but since that's not necessary, then no reason to do it:3

Thanks for the feedback :)
