### ISSUE TITLE
Unable to craft stone tools from ore dictionary registered stone?

### ISSUE THREAD

**Issue by ianc1215** [SlimeKnights/TinkersConstruct#1382]
I am running the stable version of Tcon 1.7.x one. In this version I am not able to create tools from Underground Biomes Constructs cobblestone which is registered to the ore dictionary.

When I try to make the part it just does nothing. If I use normal cobblestone it works just fine.

**Comment by bonii-xx** [comment]
If it doesn't work now UBC does its oredicting too late.
