### ISSUE TITLE
Grout and shovels

### ISSUE THREAD

**Issue by TherminatorX** [SlimeKnights/TinkersConstruct#1383]
Digging up the grout block with a vanilla shovel is the same speed as your fist, even a diamond shovel with Efficiency V has the same slowness.

However, Tinker's shovels work just fine. A creative-spawned cobalt shovel just zips through the stuff.

This was noted by someone on my wiki, and my tests have confirmed it. 
I also discovered that a cobalt frying pan can dig faster than a fist. :confused:

**Comment by laz2727** [comment]
That's most likely because vanilla weapons have 1.5 digging speed.

2015-02-04 5:28 GMT+06:00 ThermX <notifications@github.com>:

**Comment by Deshiba** [comment]
@laz2727 Vanilla tools should still dig faster then a fist though.

**Comment by laz2727** [comment]
That's because no one in TinkerWorld sets its HarvestLevel.

2015-02-04 13:58 GMT+06:00 Deshiba <notifications@github.com>:

**Comment by TherminatorX** [comment]
Fix confirmed in a source build from today. Closing this issue.
