### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by Zeveth** [SlimeKnights/TinkersConstruct#1384]
You said that there is a experimental version for 1.8 but i can not download it and get it to work, i have the latest forge and i have tried with the mantle and without, some help would be nice.
"1.8.0 is beta and an experimental build. It contains all the new stuff, and a whole batch of new bugs too! 1.7.1d is the last stable version."

Thanks

**Comment by Techokami** [comment]
Actually, the 1.8.x builds aren't for Minecraft 1.8, they're still for Minecraft 1.7.10. This is because Mojang stomped on A LOT of things used by modders to make adding new blocks and block models a hell.

**Comment by Zeveth** [comment]
Ok thank you for reading and responding :)
