### ISSUE TITLE
Manyullyn Cleaver Beheading V Wither Skeletons not working 

### ISSUE THREAD

**Issue by MrSpencerRecor** [SlimeKnights/TinkersConstruct#1385]
Minecraft version: 1.7.10
Tinkers' Construct version: TCONSTRUCT-1.7.10-1.8.2A

So, I have a beheading V Manyullyn Cleaver, with two tool rods set to Paper, so i can get the extra modifier. I have as it says a 70% chance of getting a skull...i've killed 20-30 Wither Skeletons in the past  couple days and I haven't got one drop. I was able to get skulls from Ender IO from enderman with this Cleaver. But, having killed 20-30 with this and getting no drops...it's a killer.

**Comment by bonii-xx** [comment]
That's because EnderIO replaces the wither skeleton.

**Comment by bonii-xx** [comment]
Let's leave it open until I've talked to CP himself too.

**Comment by MrSpencerRecor** [comment]
o/ Sorry. just thought i'd update ya saying it doesn't work with any level of Beheading

**Comment by bonii-xx** [comment]
Fixed by latest EnderIO version.
