### ISSUE TITLE
Crashes when I press "E"

### ISSUE THREAD

**Issue by fallentaktix** [SlimeKnights/TinkersConstruct#1387]
I press "E" to access my inventory and the game crashes and I get a crash log. I will paste it here

---- Minecraft Crash Report ----
// My bad.

Time: 05/02/15 4:40 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.GuiScreen.field_146292_n from class tconstruct.client.tabs.TabRegistry
	at tconstruct.client.tabs.TabRegistry.guiPostInit(TabRegistry.java:40)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_TabRegistry_guiPostInit_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:257)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:797)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1883)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.client.tabs.TabRegistry.guiPostInit(TabRegistry.java:40)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_TabRegistry_guiPostInit_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:257)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:797)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['FallenTakTix'/7, l='MpServer', x=652.50, y=64.62, z=-320.50]]
	Chunk stats: MultiplayerChunkCache: 390, 390
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (655,64,-317), Chunk: (at 15,4,3 in 40,-20; contains blocks 640,0,-320 to 655,255,-305), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 85 game time, 85 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 206 total; [EntityZombie['Zombie'/2063, l='MpServer', x=613.50, y=26.00, z=-393.50], EntityZombie['Zombie'/2064, l='MpServer', x=620.50, y=22.00, z=-254.50], EntityClientPlayerMP['FallenTakTix'/7, l='MpServer', x=652.50, y=64.62, z=-320.50], EntityBat['Bat'/1059, l='MpServer', x=729.38, y=18.38, z=-360.16], EntityBat['Bat'/1061, l='MpServer', x=727.50, y=19.44, z=-351.47], EntitySquid['Squid'/53, l='MpServer', x=624.07, y=53.95, z=-343.54], EntitySquid['Squid'/54, l='MpServer', x=620.32, y=56.43, z=-345.78], EntityCreeper['Creeper'/1078, l='MpServer', x=725.50, y=23.00, z=-355.50], EntitySquid['Squid'/55, l='MpServer', x=625.13, y=55.97, z=-343.75], EntitySquid['Squid'/56, l='MpServer', x=624.56, y=56.33, z=-351.80], EntitySquid['Squid'/57, l='MpServer', x=619.98, y=56.38, z=-338.04], EntityBat['Bat'/1081, l='MpServer', x=709.25, y=17.29, z=-365.25], EntitySquid['Squid'/58, l='MpServer', x=620.11, y=54.75, z=-343.15], EntityCreeper['Creeper'/2106, l='MpServer', x=678.50, y=28.00, z=-342.50], EntityZombie['Zombie'/2107, l='MpServer', x=677.50, y=28.00, z=-340.50], EntitySquid['Squid'/60, l='MpServer', x=623.37, y=53.12, z=-340.58], EntitySquid['Squid'/61, l='MpServer', x=627.02, y=52.59, z=-335.06], EntitySquid['Squid'/62, l='MpServer', x=624.50, y=56.37, z=-331.50], EntitySquid['Squid'/63, l='MpServer', x=615.71, y=55.16, z=-334.62], EntityCreeper['Creeper'/1604, l='MpServer', x=701.50, y=18.00, z=-371.50], EntitySquid['Squid'/591, l='MpServer', x=711.72, y=57.00, z=-293.67], EntitySquid['Squid'/592, l='MpServer', x=708.83, y=58.31, z=-292.52], EntitySquid['Squid'/593, l='MpServer', x=707.16, y=54.76, z=-295.80], EntitySquid['Squid'/594, l='MpServer', x=710.72, y=58.25, z=-291.52], EntitySquid['Squid'/595, l='MpServer', x=711.19, y=56.42, z=-290.96], EntitySquid['Squid'/596, l='MpServer', x=712.61, y=58.27, z=-293.89], EntitySquid['Squid'/597, l='MpServer', x=712.85, y=58.09, z=-286.92], EntitySquid['Squid'/598, l='MpServer', x=711.96, y=58.12, z=-288.12], EntitySquid['Squid'/600, l='MpServer', x=714.24, y=58.45, z=-295.68], EntityZombie['Zombie'/1112, l='MpServer', x=725.50, y=19.00, z=-357.50], EntitySquid['Squid'/601, l='MpServer', x=711.07, y=58.32, z=-288.82], EntityZombie['Zombie'/1113, l='MpServer', x=725.50, y=19.00, z=-355.50], EntitySquid['Squid'/602, l='MpServer', x=717.04, y=54.29, z=-291.15], EntitySquid['Squid'/603, l='MpServer', x=626.29, y=59.51, z=-333.22], EntitySquid['Squid'/604, l='MpServer', x=625.44, y=59.23, z=-338.64], EntitySquid['Squid'/605, l='MpServer', x=623.56, y=57.31, z=-345.81], EntitySquid['Squid'/606, l='MpServer', x=620.50, y=56.84, z=-337.16], EntitySquid['Squid'/607, l='MpServer', x=619.69, y=57.81, z=-333.01], EntitySquid['Squid'/608, l='MpServer', x=619.53, y=59.00, z=-325.49], EntitySquid['Squid'/609, l='MpServer', x=621.61, y=57.15, z=-331.68], EntitySquid['Squid'/610, l='MpServer', x=623.09, y=58.88, z=-337.83], EntitySquid['Squid'/611, l='MpServer', x=623.25, y=59.38, z=-330.19], EntitySquid['Squid'/612, l='MpServer', x=614.02, y=59.44, z=-332.55], EntitySquid['Squid'/613, l='MpServer', x=618.21, y=55.94, z=-331.68], EntitySquid['Squid'/614, l='MpServer', x=687.60, y=62.41, z=-258.48], EntitySquid['Squid'/618, l='MpServer', x=686.17, y=62.00, z=-265.16], EntitySquid['Squid'/620, l='MpServer', x=680.25, y=60.41, z=-258.60], EntitySquid['Squid'/621, l='MpServer', x=676.78, y=60.07, z=-258.92], EntitySquid['Squid'/622, l='MpServer', x=684.47, y=62.31, z=-259.94], EntitySquid['Squid'/623, l='MpServer', x=685.75, y=62.41, z=-262.50], EntitySquid['Squid'/624, l='MpServer', x=690.84, y=62.32, z=-259.84], EntitySquid['Squid'/113, l='MpServer', x=698.93, y=51.42, z=-375.94], EntitySquid['Squid'/115, l='MpServer', x=696.84, y=51.00, z=-375.55], EntitySquid['Squid'/117, l='MpServer', x=691.25, y=50.32, z=-370.90], EntitySquid['Squid'/118, l='MpServer', x=692.14, y=51.13, z=-373.53], EntitySquid['Squid'/119, l='MpServer', x=688.48, y=51.40, z=-366.63], EntitySquid['Squid'/120, l='MpServer', x=688.87, y=51.34, z=-376.43], EntitySquid['Squid'/121, l='MpServer', x=694.82, y=51.39, z=-372.59], EntitySquid['Squid'/122, l='MpServer', x=692.95, y=50.80, z=-374.85], EntitySquid['Squid'/123, l='MpServer', x=694.50, y=51.00, z=-373.48], EntitySquid['Squid'/124, l='MpServer', x=691.62, y=49.38, z=-377.40], EntitySpider['Spider'/1155, l='MpServer', x=701.35, y=16.00, z=-354.25], EntitySquid['Squid'/644, l='MpServer', x=627.55, y=54.46, z=-380.87], EntitySquid['Squid'/645, l='MpServer', x=631.96, y=51.76, z=-379.57], EntitySquid['Squid'/646, l='MpServer', x=630.90, y=54.36, z=-376.02], EntitySquid['Squid'/647, l='MpServer', x=630.43, y=53.35, z=-377.41], EntitySquid['Squid'/648, l='MpServer', x=637.22, y=54.29, z=-381.67], EntitySquid['Squid'/649, l='MpServer', x=635.42, y=50.73, z=-377.63], EntitySquid['Squid'/650, l='MpServer', x=632.48, y=53.00, z=-379.05], EntitySquid['Squid'/651, l='MpServer', x=633.54, y=54.34, z=-380.91], EntitySquid['Squid'/652, l='MpServer', x=638.84, y=52.87, z=-379.10], EntitySquid['Squid'/653, l='MpServer', x=634.80, y=54.34, z=-381.51], EntityCreeper['Creeper'/1172, l='MpServer', x=668.50, y=32.00, z=-360.50], EntitySquid['Squid'/668, l='MpServer', x=625.03, y=60.28, z=-311.65], EntitySquid['Squid'/669, l='MpServer', x=618.05, y=60.40, z=-305.36], EntityBat['Bat'/1181, l='MpServer', x=660.38, y=14.00, z=-365.00], EntitySquid['Squid'/670, l='MpServer', x=624.65, y=60.34, z=-303.32], EntitySquid['Squid'/671, l='MpServer', x=621.67, y=60.50, z=-305.73], EntitySquid['Squid'/672, l='MpServer', x=621.03, y=58.16, z=-308.56], EntitySquid['Squid'/674, l='MpServer', x=622.87, y=59.85, z=-303.18], EntitySquid['Squid'/675, l='MpServer', x=614.89, y=58.69, z=-299.85], EntitySquid['Squid'/676, l='MpServer', x=620.64, y=60.16, z=-302.53], EntitySquid['Squid'/677, l='MpServer', x=621.45, y=59.39, z=-305.00], EntitySquid['Squid'/678, l='MpServer', x=623.66, y=60.38, z=-311.28], EntitySquid['Squid'/679, l='MpServer', x=621.66, y=60.32, z=-306.97], EntitySquid['Squid'/680, l='MpServer', x=588.47, y=55.48, z=-294.88], EntitySquid['Squid'/684, l='MpServer', x=594.53, y=56.00, z=-294.47], EntitySquid['Squid'/685, l='MpServer', x=594.48, y=54.64, z=-302.48], EntitySquid['Squid'/686, l='MpServer', x=593.87, y=56.01, z=-299.28], EntitySquid['Squid'/687, l='MpServer', x=596.81, y=56.40, z=-296.14], EntitySquid['Squid'/688, l='MpServer', x=595.71, y=53.98, z=-295.30], EntitySquid['Squid'/689, l='MpServer', x=597.90, y=54.13, z=-298.96], EntitySquid['Squid'/690, l='MpServer', x=601.06, y=55.38, z=-295.83], EntitySquid['Squid'/691, l='MpServer', x=602.04, y=56.38, z=-294.33], EntityBat['Bat'/1203, l='MpServer', x=694.66, y=21.60, z=-336.25], EntitySquid['Squid'/692, l='MpServer', x=646.84, y=52.88, z=-368.65], EntitySquid['Squid'/693, l='MpServer', x=645.12, y=53.38, z=-361.36], EntitySquid['Squid'/694, l='MpServer', x=650.03, y=51.74, z=-362.48], EntitySquid['Squid'/695, l='MpServer', x=643.74, y=51.10, z=-365.11], EntitySquid['Squid'/696, l='MpServer', x=655.74, y=51.00, z=-360.39], EntityZombie['Zombie'/1208, l='MpServer', x=725.50, y=19.00, z=-363.50], EntitySquid['Squid'/697, l='MpServer', x=649.94, y=53.00, z=-369.50], EntitySquid['Squid'/698, l='MpServer', x=650.00, y=49.88, z=-365.55], EntitySquid['Squid'/699, l='MpServer', x=649.86, y=52.43, z=-363.51], EntitySquid['Squid'/700, l='MpServer', x=650.94, y=53.28, z=-358.08], EntitySquid['Squid'/701, l='MpServer', x=653.08, y=52.38, z=-365.59], EntitySquid['Squid'/702, l='MpServer', x=657.37, y=53.37, z=-364.63], EntitySquid['Squid'/703, l='MpServer', x=657.50, y=53.43, z=-370.48], EntityCreeper['Creeper'/1734, l='MpServer', x=731.49, y=32.00, z=-244.50], EntityFallingBlock['Falling Block'/2246, l='MpServer', x=736.50, y=34.67, z=-247.50], EntityCreeper['Creeper'/1735, l='MpServer', x=728.50, y=32.00, z=-241.50], EntityFallingBlock['Falling Block'/2247, l='MpServer', x=737.50, y=34.67, z=-247.50], EntityFallingBlock['Falling Block'/2248, l='MpServer', x=736.50, y=36.67, z=-246.50], EntityFallingBlock['Falling Block'/2249, l='MpServer', x=734.50, y=37.67, z=-247.50], EntityFallingBlock['Falling Block'/2250, l='MpServer', x=734.50, y=37.67, z=-246.50], EntityFallingBlock['Falling Block'/2251, l='MpServer', x=735.50, y=37.67, z=-246.50], EntityZombie['Zombie'/1745, l='MpServer', x=688.50, y=26.00, z=-358.50], EntitySkeleton['Skeleton'/2261, l='MpServer', x=695.50, y=24.00, z=-350.50], EntitySquid['Squid'/748, l='MpServer', x=667.96, y=44.98, z=-385.49], EntitySquid['Squid'/752, l='MpServer', x=659.67, y=48.47, z=-383.35], EntityCreeper['Creeper'/2294, l='MpServer', x=710.50, y=24.00, z=-365.50], EntityCreeper['Creeper'/2295, l='MpServer', x=715.50, y=24.00, z=-360.50], EntitySquid['Squid'/759, l='MpServer', x=665.13, y=45.39, z=-383.64], EntitySkeleton['Skeleton'/2296, l='MpServer', x=730.49, y=17.00, z=-360.49], EntitySpider['Spider'/2301, l='MpServer', x=678.50, y=21.00, z=-327.50], EntitySkeleton['Skeleton'/2302, l='MpServer', x=676.50, y=21.00, z=-332.50], EntitySkeleton['Skeleton'/2303, l='MpServer', x=675.50, y=21.00, z=-334.50], EntityZombie['Zombie'/2304, l='MpServer', x=624.50, y=15.00, z=-253.50], EntitySquid['Squid'/286, l='MpServer', x=625.20, y=58.33, z=-265.44], EntitySquid['Squid'/287, l='MpServer', x=624.38, y=58.22, z=-262.13], EntitySkeleton['Skeleton'/2335, l='MpServer', x=702.50, y=29.00, z=-303.50], EntitySquid['Squid'/288, l='MpServer', x=623.79, y=55.95, z=-266.14], EntitySquid['Squid'/289, l='MpServer', x=625.35, y=58.16, z=-260.91], EntitySquid['Squid'/290, l='MpServer', x=634.62, y=55.30, z=-271.68], EntitySquid['Squid'/291, l='MpServer', x=627.94, y=58.18, z=-270.54], EntitySquid['Squid'/292, l='MpServer', x=626.09, y=56.74, z=-265.80], EntitySquid['Squid'/293, l='MpServer', x=630.21, y=58.36, z=-263.63], EntitySquid['Squid'/294, l='MpServer', x=631.53, y=56.69, z=-263.56], EntitySquid['Squid'/295, l='MpServer', x=633.99, y=58.39, z=-259.32], EntitySquid['Squid'/296, l='MpServer', x=632.35, y=56.13, z=-267.04], EntitySquid['Squid'/297, l='MpServer', x=637.46, y=57.81, z=-270.41], EntitySquid['Squid'/298, l='MpServer', x=625.37, y=50.36, z=-366.06], EntitySquid['Squid'/299, l='MpServer', x=623.75, y=50.00, z=-362.30], EntitySquid['Squid'/300, l='MpServer', x=627.03, y=48.12, z=-366.15], EntitySquid['Squid'/301, l='MpServer', x=623.17, y=49.40, z=-360.77], EntitySquid['Squid'/302, l='MpServer', x=621.13, y=50.34, z=-367.31], EntitySquid['Squid'/303, l='MpServer', x=615.38, y=49.72, z=-365.47], EntitySquid['Squid'/305, l='MpServer', x=616.86, y=50.24, z=-373.60], EntitySquid['Squid'/306, l='MpServer', x=618.31, y=48.91, z=-374.80], EntitySquid['Squid'/307, l='MpServer', x=617.03, y=47.73, z=-370.03], EntitySquid['Squid'/308, l='MpServer', x=613.09, y=50.23, z=-375.35], EntitySquid['Squid'/309, l='MpServer', x=616.54, y=48.63, z=-377.41], EntitySquid['Squid'/322, l='MpServer', x=685.02, y=58.45, z=-364.21], EntitySquid['Squid'/323, l='MpServer', x=693.69, y=57.88, z=-365.62], EntitySquid['Squid'/324, l='MpServer', x=688.73, y=60.39, z=-371.53], EntitySquid['Squid'/325, l='MpServer', x=686.99, y=60.46, z=-371.58], EntitySquid['Squid'/326, l='MpServer', x=698.22, y=60.44, z=-365.36], EntitySquid['Squid'/327, l='MpServer', x=693.16, y=60.33, z=-364.53], EntitySquid['Squid'/328, l='MpServer', x=699.51, y=59.00, z=-363.81], EntitySquid['Squid'/329, l='MpServer', x=698.11, y=59.37, z=-366.07], EntitySquid['Squid'/330, l='MpServer', x=694.19, y=59.28, z=-363.71], EntitySquid['Squid'/331, l='MpServer', x=688.32, y=59.17, z=-369.67], EntitySquid['Squid'/332, l='MpServer', x=693.84, y=60.38, z=-366.90], EntitySquid['Squid'/333, l='MpServer', x=697.44, y=60.35, z=-360.82], EntitySquid['Squid'/868, l='MpServer', x=673.32, y=62.32, z=-373.58], EntitySquid['Squid'/869, l='MpServer', x=672.44, y=61.28, z=-366.39], EntitySquid['Squid'/870, l='MpServer', x=672.37, y=61.29, z=-364.28], EntitySquid['Squid'/871, l='MpServer', x=673.34, y=62.39, z=-366.86], EntitySquid['Squid'/872, l='MpServer', x=674.24, y=58.68, z=-360.50], EntitySquid['Squid'/873, l='MpServer', x=672.37, y=61.84, z=-360.56], EntitySquid['Squid'/874, l='MpServer', x=676.54, y=62.16, z=-361.20], EntitySquid['Squid'/875, l='MpServer', x=675.49, y=61.66, z=-365.05], EntitySquid['Squid'/876, l='MpServer', x=674.84, y=59.26, z=-365.11], EntitySquid['Squid'/877, l='MpServer', x=673.66, y=62.39, z=-363.68], EntitySquid['Squid'/878, l='MpServer', x=679.41, y=62.38, z=-362.11], EntitySquid['Squid'/879, l='MpServer', x=677.54, y=61.58, z=-366.68], EntitySkeleton['Skeleton'/1392, l='MpServer', x=590.04, y=23.00, z=-392.50], EntityBat['Bat'/1401, l='MpServer', x=656.44, y=31.92, z=-396.09], EntityBat['Bat'/1403, l='MpServer', x=655.25, y=31.39, z=-397.06], EntityCreeper['Creeper'/1933, l='MpServer', x=573.50, y=18.00, z=-379.50], EntityBat['Bat'/1433, l='MpServer', x=698.22, y=22.67, z=-339.34], EntitySquid['Squid'/971, l='MpServer', x=673.08, y=52.42, z=-269.85], EntitySquid['Squid'/972, l='MpServer', x=664.56, y=52.52, z=-270.80], EntitySquid['Squid'/973, l='MpServer', x=667.16, y=52.39, z=-267.18], EntitySquid['Squid'/974, l='MpServer', x=661.08, y=50.85, z=-270.16], EntitySquid['Squid'/975, l='MpServer', x=662.59, y=52.38, z=-260.59], EntityBat['Bat'/1487, l='MpServer', x=638.89, y=18.00, z=-396.44], EntitySquid['Squid'/976, l='MpServer', x=669.38, y=51.67, z=-267.35], EntityBat['Bat'/1488, l='MpServer', x=639.32, y=17.01, z=-400.02], EntitySkeleton['Skeleton'/2000, l='MpServer', x=715.50, y=18.00, z=-360.50], EntitySquid['Squid'/977, l='MpServer', x=667.89, y=48.61, z=-268.79], EntitySkeleton['Skeleton'/2001, l='MpServer', x=712.00, y=18.00, z=-359.78], EntitySquid['Squid'/978, l='MpServer', x=667.31, y=51.57, z=-272.50], EntitySkeleton['Skeleton'/2002, l='MpServer', x=712.15, y=18.00, z=-358.68], EntitySkeleton['Skeleton'/2003, l='MpServer', x=715.50, y=18.00, z=-359.50], EntitySquid['Squid'/980, l='MpServer', x=661.14, y=51.37, z=-257.89], EntitySquid['Squid'/982, l='MpServer', x=666.25, y=52.34, z=-259.13], EntitySquid['Squid'/1007, l='MpServer', x=590.75, y=47.00, z=-266.63], EntitySquid['Squid'/1008, l='MpServer', x=593.31, y=46.09, z=-266.06], EntitySquid['Squid'/1010, l='MpServer', x=590.42, y=46.91, z=-265.25], EntitySquid['Squid'/1011, l='MpServer', x=595.55, y=45.94, z=-254.30], EntitySquid['Squid'/1012, l='MpServer', x=597.17, y=47.00, z=-259.78], EntitySquid['Squid'/1013, l='MpServer', x=595.90, y=43.92, z=-257.37], EntitySquid['Squid'/1014, l='MpServer', x=594.43, y=43.88, z=-259.17], EntitySquid['Squid'/1015, l='MpServer', x=587.41, y=47.44, z=-264.68], EntitySquid['Squid'/1016, l='MpServer', x=594.08, y=47.16, z=-266.97]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 165345296 bytes (157 MB) / 382873600 bytes (365 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (mantle) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (tconstruct) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6900 Series GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by bonii-xx** [comment]
Looks like the access transformer didn't work. Might be a Forge issue.
