### ISSUE TITLE
Crash upon opening world 

### ISSUE THREAD

**Issue by Arcnz** [SlimeKnights/TinkersConstruct#1390]
http://openeye.openmods.info/crashes/14dd04d3da874bfad009a9927594a76b

When I open a world, the crash report above always happens. I don't have any incompatible mods, so I don't know what happened. I think it's because I was using a different version of TC, but I still don't know.

**Comment by bonii-xx** [comment]
That usually happens when you have a tool with a material that got removed (because you removed the mod that added it, etc)

**Comment by TherminatorX** [comment]
I suggest removing the erroring tool from your inventory w/ NBTExplorer or such, then starting up the world again.

**Comment by bonii-xx** [comment]
Probably fixed via 58031bb521f6ffabc66e6f1424d4dfcdd6bff65b
