### ISSUE TITLE
Swords are not real Weapons

### ISSUE THREAD

**Issue by Drehverschluss** [SlimeKnights/TinkersConstruct#1393]
It seems like that Tinker Weapons are not "real" minecraft weapons. 
I saw this on a mod i tested and also i allready found the line where you made it compatible for the Zelda Mod. 
"@Optional.Interface(modid = "ZeldaItemAPI", iface = "zeldaswordskills.api.item.ISword")"

Would be awesome if you can add such a line for "Dynamic Sword Skills Mod" too or can i make a pull request and add it myself. Would that work?

Thats the Mod wich not work -> http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294232-1-6-4-1-8-dynamic-sword-skills-full-release-for

MFG

**Comment by bonii-xx** [comment]
You do realize that is the same API, right

**Comment by Drehverschluss** [comment]
But thats different classes

**Comment by maxammann** [comment]
@bonii-xx Dynamic Sword Skills Mod doesn't implement ZeldaItemAPI's API afaik.

**Comment by bonii-xx** [comment]
But as far as I know i tested it with that o_O. Does he really have 2 different apis for the same thing?

**Comment by maxammann** [comment]
The project splitted in two parts somehow. Both are up to date, but use different APIs, yes :D

**Comment by bonii-xx** [comment]
Way to completely ignore the "API" part

**Comment by Drehverschluss** [comment]
¿¿

**Comment by bonii-xx** [comment]
Hey @coolAlias why does your Zelda sword skills not ship the dynamic sword skills API, but instead reimplement the api.

**Comment by coolAlias** [comment]
@bonii-xx Dynamic Sword Skills is the result of me ripping out what I could from ZSS to make just the skills work, but I wasn't able to fully separate everything out from within ZSS itself, meaning that they do not use the same code (I wish they did, but they don't).

The 'API' was never part of the plan, nor is it really part of the skills, but a tacked on solution for problems such as weapons which do not extend ItemSword. What I plan on doing is to make the ISword, etc. parts of the API completely separate from both, and then both ZSS and DSS can use the common parts.

**Comment by bonii-xx** [comment]
Yeah, that's what I figured how it'd work, a completely separate API that both use. It should be possible to support both, though, Just because the interfaces have the same name doesn't mean they're the same interface.

**Comment by Drehverschluss** [comment]
Would be awesome if you can support both.

**Comment by coolAlias** [comment]
In this case, they are the exact same interfaces, so it will be easy to extract them. That should make it easy to add support for both mods at once. Hopefully I'll have some time this weekend.

**Comment by Drehverschluss** [comment]
Some update infos?

**Comment by Drehverschluss** [comment]
@coolAlias And how is it going? :)

**Comment by coolAlias** [comment]
It's going to be a while before I get to it.

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/commit/4ec647243f6777e5c47cefa263a280e63faaff6d
Somebody test it. ;P

**Comment by Drehverschluss** [comment]
How shall i test it?

**Comment by Drehverschluss** [comment]
Do i just need to redownload it or merge it myself? 
Sry if the QUestion is dump
You know how is speaking ;)

**Comment by TherminatorX** [comment]
@Drehverschluss Follow the compilation instructions on the repository OP

**Comment by Drehverschluss** [comment]
@bonii-xx tryed to compile the projecet to test it put i get this error.
http://pastebin.com/Zp8xvHfi

**Comment by bonii-xx** [comment]
Well, don't override final fields. :P

**Comment by Drehverschluss** [comment]
I think im just to stupid.
I wait on the new build wich will be done by you ;)

**Comment by maxammann** [comment]
hey @bonii-xx, hätte einen CI/build und maven Server im Angebot, falls du Interresse hast :D 

btw unser Drehverschluss ist auch aus Österreich :D

**Comment by bonii-xx** [comment]
Unser Jenkins erfüllt seinen Zweck recht gut, aber danke.
