### ISSUE TITLE
Tinker's bug - tools made from materials from Thermal Foundation/Expansion aren't repairable?

### ISSUE THREAD

**Issue by DigitolMC** [SlimeKnights/TinkersConstruct#1399]
Minecraft version: 1.7.10
Tinkers' Construct version: TConstruct-1.7.10-1.8.2a
Forge version/build: 7.10.85.1291
Versions of any mods potentially related to the issue: ThermalExpansion-[1.7.10]4.0.0B8-23, ThermalFoundation-[1.7.10]1.0.0RC1-13,
Any relevant screenshots are greatly appreciated.
http://gyazo.com/989cc848d57d9ac477deac18148278fc           
http://gyazo.com/5741b5dec38693b4aa47ed9b373c28ce

Tried to repair using a non broken tool, same result.
Also tried using exact same tool except WITHOUT Iguana Tweaks, same

**Comment by squeek502** [comment]
Not a Tinkers Construct issue: https://github.com/CoFH/Feedback/issues/15
