### ISSUE TITLE
[Compat] Move OreDictionary registering to pre-init

### ISSUE THREAD

**Issue by InfinityRaider** [SlimeKnights/TinkersConstruct#1404]
I have a mechanic in my mod (https://github.com/InfinityRaider/AgriCraft), that relies on detecting certain ores in the ore dictionary. Aluminum ore is one of them. It seems you register your blocks/items to the oredict in init. This causes the issue that aluminum ore is not detected when I run my registering methods (also in init), and as such the crop that needs aluminum ore is not added.
Is it possible for you to move the registering of ores to preInit, for the reason that I do not need to move my registering of new blocks in post-init? This for the purpose of doing everything as soon as possible.

**Comment by bonii-xx** [comment]
I suppose I can move that stuff to preInit since everything should be oredicted as soon as possible.
On another note, in general you shouldn't rely on stuff being oredicted during init. The earliest you can somewhat rely on is postInit. Any reason why you need to

PS: Love the scythe integration. ;)

**Comment by bonii-xx** [comment]
69496722bb78c4dc8a74267ddcebe52b75482d54

**Comment by InfinityRaider** [comment]
Well thanks, I wanted to do it as soon as possible, like if other mods rely on things they still have post-init.  However I moved it to post-init on my side already though because Mekanism does it's oredict registering in init as well :/
Guess this ends my little init crusade.

**Comment by bonii-xx** [comment]
Haha. Well, as I said, own stuff should be registered as early as possible, but you can't rely on anything being oredicted before postInit. During postInit nothing in the oredict should change anymore. Worstcase you can always force loading order.
