### ISSUE TITLE
Drying Rack recipe removed w/GregTech

### ISSUE THREAD

**Issue by KageDragon** [SlimeKnights/TinkersConstruct#1415]
Trying to track this bug down, already checked with Greg, he says it's not something on his end.

When I load GT, the recipe for the drying rack disappears. I can cheat it in, and it otherwise works fine.

TiC 1.8.2a\Mantle 0.3.2\GT 6.00.05

Tried TiC 1.8.2.build891, and versions of GT from 5.0x and up.

No related errors in the log, nothing in the configs that I can see.

**Comment by bonii-xx** [comment]
Then there probably aren't any oredicted slabs or you have the armory disabled.

**Comment by KageDragon** [comment]
Armory is enabled, and this is with only TiC, GT and IC2 installed. There are just the vanilla slabs, and I tried them all.

**Comment by bonii-xx** [comment]
Ask Greg if he does something with the slabWood oredict entry. The drying rack uses a standard oredict recipe.

**Comment by KageDragon** [comment]
Reply from Greg:

>I asked to check if it happens with 6.00.02, where there were no Recipe changes at all, and it still happened according to that Report. And I don't do anything with Slabs right now. I do things with Planks => Slabs, but that is different, since it would remove Plank based Recipes and not Slab based ones.

I've tried using crafting stations, and every other recipe I can find that uses slabWood, and they all work fine. I don't know, it's hardly a deal-breaker, wish forge had more debugging\logging tools to figure it out...

**Comment by bonii-xx** [comment]
Ok, that's what I needed to know. Thanks for getting the info, I'll take a look when I got the time.

**Comment by Dream-Master** [comment]
Add it back with Minetweaker :

// --- Drying Rack
recipes.addShaped(<TConstruct:Armor.DryingRack>, [
[<ore:slabWood>, <ore:slabWood>, <ore:slabWood>]]);

**Comment by bonii-xx** [comment]
I can confirm that the slabWood oredict is there and everything. It seems however that the recipe itself is missing.
Somebody said it might be the UE Plate Recipe Remover (whatever that is?). Apparently it also misfires on MFR plastic. You might want to inform greg.

**Comment by bonii-xx** [comment]
In fact it seems to remove ALL ShapedOreRecipies? Some Thermal Expansion recipies also seem to be missing.

**Comment by KageDragon** [comment]
I can't reproduce the mfr plastic thing, only thing I noticed is that by default it unificates in your inventory to GT plastic, but the recipes are all there, as far as I can tell. I can't find any TE recipes that don't work.
Other ShapelessOreRecipes from TiC work..
