### ISSUE TITLE
Tinkers' Construct crashes client when equipting exo armor on Cauldron server

### ISSUE THREAD

**Issue by thormbush42** [SlimeKnights/TinkersConstruct#1417]
Exactly what the title says. When players spawn and equip such items, the server outputs: http://pastebin.com/8KL75agZ

Minecraft 1.7.10; Tinkers' Construct 1.7.1c

**Comment by bonii-xx** [comment]
Bukkits fault, not supported.

**Comment by TherminatorX** [comment]
@bonii-xx It's even worse: that's an old TiC, and /give was used to give a item w/o NBT. So, duh.
Get it from the creative menu.
