### ISSUE TITLE
items not droping

### ISSUE THREAD

**Issue by Sadseal** [SlimeKnights/TinkersConstruct#1418]
when i mine something like iron i only get the ingot like 40-60% off the time and when i dig a tree i get coal and these are with basic tools not with the fire upgrade what auto smelts i only use iron and slime can i get feed back this is my personal mod pack if i need to list the mods below to help some users just ask and also the other 60% of the time it dont drop any think at all

**Comment by Sadseal** [comment]
the mods i do have installs are to follow
![mods](https://cloud.githubusercontent.com/assets/11145887/6318628/f84b2e86-ba93-11e4-82c7-1661321bd5f9.png)

**Comment by bonii-xx** [comment]
See if it happens with only Tcon. If it doesn't add mods until it does to find out which one caused it.

**Comment by Sadseal** [comment]
no it is tinkers construct it don't do it with any other tool's mod

**Comment by bonii-xx** [comment]
See if it happens with Tcon and Mantle being the only mod loaded. If it doesn't add mods until you find out which one caused it.

**Comment by Sadseal** [comment]
kk
