### ISSUE TITLE
Crash with Tinker's and Pneumaticraft

### ISSUE THREAD

**Issue by blockbreaker1361** [SlimeKnights/TinkersConstruct#1419]
I've reported this on the Pneumaticraft site as well.

http://pastebin.com/UQ45ds3z

**Comment by TherminatorX** [comment]
Reproduction steps/link to PnC issue?

**Comment by blockbreaker1361** [comment]
I have no idea what you're talking about. Please say it in words I can understand. I don't speak "geek".

**Comment by Caeldeth** [comment]
^ That's a great way to get help.

In other words, a step-by-step list of what you were doing right before the crash, and a link to the report you made on the Pneumaticraft site.

Example:
1) Put ore in smelter
2) Waited for ore to smelt
3) Clicked faucet
4) Crash

Also, the link will allow the two dev teams to coordinate potentially.

**Comment by bonii-xx** [comment]
It's thinking that some item from pneumaticraft is a tinkers tool. Sounds like your world got corrupted.

**Comment by blockbreaker1361** [comment]
What happened was that I was out exploring, saw a creeper and tried to shoot it with the crossbow. That's when the game crashed. I went in and took Pneumaticraft out and it now has the same conflict with another mod. bonii-xx, the world isn't corrupted. I'm still playing in it and as long as I don't use the crossbow, everything else is fine.

**Comment by bonii-xx** [comment]
Shouldn't happen anymore next version, however the cause is really weird.
