### ISSUE TITLE
Crashing on mac

### ISSUE THREAD

**Issue by relaxedyellow34** [SlimeKnights/TinkersConstruct#1420]
i am running the lucky block mod, biomes o plenty and tinkers construct through forge, i moved all of the jar files including the mantle into the mod folder and opened them all with achive utility, they are now in folder form not .jar. It seems to crash irregullarly but it will crash if i open the tinkers book to page 3 every time
also it sometimes crashes when i open my inventory and the tool things for making advanced tools in tinkers construct are invisible when i place them. 

here are some crash reports:
http://pastebin.com/mEiGy7mH

if you need any more let me know, thanks

**Comment by TherminatorX** [comment]
a) put those logs on pastebin and get them off here. The text wall hurts people's eyes, and should not be posted in a comment-based system.
b) why in the world would you turn perfectly good .jar mod files into folder junk? use the .jars and try again.

**Comment by relaxedyellow34** [comment]
sorry about the text wall didnt know about paste bin
im trying the .jar thing now
the luckyblocks dowload in a .jar.zip file and i turned it into a .jar but it still looks like a folder in the finder tab

**Comment by relaxedyellow34** [comment]
i tried running it with all the .jar files in the mod folder, it didnt run and it output this
http://pastebin.com/7rCy1Ccy

**Comment by bonii-xx** [comment]
You're running a TCon version from half a year ago.
