### ISSUE TITLE
Tool parts added by other mods cannot be smelted

### ISSUE THREAD

**Issue by codewarrior0** [SlimeKnights/TinkersConstruct#1422]
Casting recipes added for things like TE's Electrum are added via the addPartCastingMaterial IMC.

This IMC adds the casting recipe for the new part, but does not add a melting recipe to the smeltery so the parts cannot be melted back down into molten metals. The addPartCastingMaterial IMC ought to add the melting recipe too.

**Comment by bonii-xx** [comment]
Good catch.
