### ISSUE TITLE
Electrum Tools

### ISSUE THREAD

**Issue by BenAldino** [SlimeKnights/TinkersConstruct#1427]
Hey, I'm not able to repair my electrum tool(electrum pickaxe head, paper binding/tool rod) I've added 1 modifier of redstone and a diamond, I was planning to put on a Flux Capacitor as well but I can't add that either.
Minecraft FTB infinity modpack version 1.7.10
TiC version: I think the newest one.

-Ben

**Comment by bonii-xx** [comment]
Will be able in the next ticon with updated TF.
