### ISSUE TITLE
Crafting Traveller's Boots and equipping them crashes.

### ISSUE THREAD

**Issue by mDiyo** [SlimeKnights/TinkersConstruct#1429]
Getting a fresh pair out of creative mode will give you a working pair. This only applies to crafted boots.

http://pastebin.com/JwdnLdm6

**Comment by warezit** [comment]
I think that's because when you pull them out of Creative Mode, they don't get the required NBT data.

Try crafting them instead.

**Comment by mDiyo** [comment]
The problem is when they're crafted, not when they're pulled out of creative mode.

**Comment by mDiyo** [comment]
Minetweaker shenanigans. Bah.
