### ISSUE TITLE
Crashing with leveled up Crossbow

### ISSUE THREAD

**Issue by Woif1990** [SlimeKnights/TinkersConstruct#1431]
http://pastebin.com/8hZTPNHg

Was playing ME^4 with TiC: 1.7.10-1.8.2a, Iguana tweaks: 2.1.2

Even after removing the crossbow/bolts from my inventory with an editor, the world still crashes, also even after renaming my player.dat

**Comment by bonii-xx** [comment]
Fixed in next version.
