### ISSUE TITLE
Crash when firing a bow with vanilla arrows.

### ISSUE THREAD

**Issue by red3dred** [SlimeKnights/TinkersConstruct#1433]
If i attempt to fire a short or long bow with vanilla arrows, the game just crashes.Does not happen in creative however. At first i thought it was because of Optifine, but after disabling it, and not having even enabled "FpsPlus" for the second test, it crashed again. I noticed this is not a issue for other players, so i'm left wondering if its the Forge version i use or just my computer.

The crash is as follows:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 27/02/15 16:47
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at tconstruct.client.FlexibleToolRenderer.getIcons(FlexibleToolRenderer.java:266)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:60)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.doRender(ProjectileBaseRenderer.java:57)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:21)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:6)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.func_76986_a(ProjectileBaseRenderer.java:20)
	at tconstruct.weaponry.client.item.BowRenderer.specialAnimation(BowRenderer.java:78)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:99)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:232)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:486)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.client.FlexibleToolRenderer.getIcons(FlexibleToolRenderer.java:266)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:60)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.doRender(ProjectileBaseRenderer.java:57)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:21)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:6)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.func_76986_a(ProjectileBaseRenderer.java:20)
	at tconstruct.weaponry.client.item.BowRenderer.specialAnimation(BowRenderer.java:78)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:99)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:232)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:486)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['red3dred'/614, l='MpServer', x=22,81, y=76,62, z=267,59]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (4,64,252), Chunk: (at 4,4,12 in 0,15; contains blocks 0,0,240 to 15,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 59404 game time, 18006 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 57 total; [Entity_SpecialCreeper['Creeper, Level 2'/643, l='MpServer', x=-18,50, y=64,00, z=334,50], Entity_SpecialCreeper['Creeper, Level 1'/644, l='MpServer', x=-15,50, y=64,00, z=337,50], Entity_SpecialCreeper['Creeper, Level 1'/645, l='MpServer', x=-13,50, y=64,00, z=334,50], Entity_SpecialZombie['Zombie, Level 1'/647, l='MpServer', x=-43,50, y=63,00, z=232,50], EntityBat['Bat'/142, l='MpServer', x=-52,25, y=18,65, z=255,28], EntityBat['Bat'/143, l='MpServer', x=-51,13, y=20,00, z=251,50], EntityBat['Bat'/144, l='MpServer', x=-43,28, y=24,15, z=268,00], EntityBat['Bat'/145, l='MpServer', x=-49,47, y=13,74, z=235,66], EntityWeepingAngel['Weeping Angel'/1049, l='MpServer', x=-13,06, y=26,00, z=316,94], EntityDeathCreeper['§cCreeper, Level 5'/159, l='MpServer', x=-33,59, y=69,00, z=200,94], EntityWeepingAngel['Weeping Angel'/927, l='MpServer', x=-11,39, y=24,00, z=316,71], Entity_SpecialCreeper['§cCreeper, Level 5'/160, l='MpServer', x=-33,50, y=70,00, z=207,50], EntityRocketCreeper['Rocket Creeper, Level 1'/161, l='MpServer', x=-46,50, y=64,00, z=216,50], EntityEnderCreeper['Creeper, Level 1'/162, l='MpServer', x=-44,97, y=20,00, z=266,78], Entity_SpecialSpider['Spider, Level 1'/418, l='MpServer', x=99,50, y=69,00, z=238,50], EntitySheep['Sheep'/163, l='MpServer', x=-43,44, y=67,00, z=290,34], EntityDEnchantedBook['Bewitched Tome, Level 2'/419, l='MpServer', x=100,69, y=12,00, z=267,50], Entity_SpecialSkeleton['Skeleton, Level 1'/420, l='MpServer', x=99,38, y=12,00, z=267,50], EntityWeepingAngel['Weeping Angel'/422, l='MpServer', x=102,97, y=12,00, z=257,97], EntityBat['Bat'/1201, l='MpServer', x=-12,24, y=24,68, z=318,00], EntityBat['Bat'/1202, l='MpServer', x=-11,36, y=25,48, z=318,60], Entity_SpecialCreeper['Creeper, Level 3'/180, l='MpServer', x=-27,50, y=68,00, z=190,50], Entity_SpecialCreeper['Creeper, Level 1'/181, l='MpServer', x=-28,50, y=68,00, z=191,50], EntityFireCreeper['Creeper, Level 2'/182, l='MpServer', x=-29,50, y=68,00, z=189,50], EntityDirtCreeper['Creeper, Level 1'/183, l='MpServer', x=-28,50, y=71,00, z=209,50], Entity_SpecialCreeper['Creeper, Level 2'/184, l='MpServer', x=-17,97, y=70,00, z=202,53], EntityCow['Cow'/185, l='MpServer', x=-18,13, y=71,00, z=209,88], EntityCow['Cow'/186, l='MpServer', x=-19,50, y=71,00, z=219,25], EntityCow['Cow'/187, l='MpServer', x=-28,50, y=73,00, z=290,50], EntityCow['Cow'/319, l='MpServer', x=33,50, y=78,00, z=321,38], EntityCow['Cow'/331, l='MpServer', x=57,94, y=72,00, z=242,94], EntityWeepingAngel['Weeping Angel'/715, l='MpServer', x=102,86, y=12,00, z=257,86], EntityFestiveCreeper['Festive Creeper, Level 2'/332, l='MpServer', x=55,50, y=73,00, z=242,50], EntityCow['Cow'/215, l='MpServer', x=-5,97, y=70,00, z=213,09], EntityDSkeletonWarrior['Skeleton Warrior, Level 1'/216, l='MpServer', x=-9,50, y=72,00, z=227,50], EntityBrutishZombie['Zombie, Level 3'/217, l='MpServer', x=-7,16, y=71,00, z=290,50], EntityWeepingAngel['Weeping Angel'/218, l='MpServer', x=-12,03, y=24,00, z=317,97], EntityWeepingAngel['Weeping Angel'/219, l='MpServer', x=-11,31, y=24,00, z=316,78], EntityDirtCreeper['Creeper, Level 1'/220, l='MpServer', x=-12,38, y=24,00, z=320,69], EntityJumpingCreeper['Creeper, Level 2'/221, l='MpServer', x=-11,41, y=24,00, z=320,50], Entity_SpecialSkeleton['Skeleton, Level 1'/355, l='MpServer', x=76,50, y=68,00, z=207,50], EntityCow['Cow'/230, l='MpServer', x=2,88, y=70,00, z=206,84], EntityClientPlayerMP['red3dred'/614, l='MpServer', x=22,81, y=76,62, z=267,59], EntityCow['Cow'/231, l='MpServer', x=4,94, y=70,00, z=204,47], EntityRocketCreeper['Rocket Creeper, Level 2'/232, l='MpServer', x=19,38, y=72,00, z=195,50], EntityCow['Cow'/233, l='MpServer', x=12,03, y=70,00, z=206,84], EntityWeepingAngel['Weeping Angel'/745, l='MpServer', x=-12,58, y=24,00, z=317,42], EntityCow['Cow'/234, l='MpServer', x=2,97, y=70,00, z=211,16], EntityCow['Cow'/244, l='MpServer', x=31,63, y=76,00, z=218,53], EntityCow['Cow'/245, l='MpServer', x=24,28, y=70,00, z=219,72], EntityThiefSkeleton['Skeleton, Level 1'/246, l='MpServer', x=23,50, y=70,00, z=212,50], EntityCow['Cow'/247, l='MpServer', x=23,50, y=73,00, z=224,69], EntityCow['Cow'/248, l='MpServer', x=29,97, y=78,00, z=307,06], EntityCow['Cow'/249, l='MpServer', x=22,31, y=73,00, z=335,31], EntityFestiveCreeper['Festive Creeper, Level 1'/250, l='MpServer', x=16,50, y=67,00, z=342,50], Entity_SpecialSkeleton['Skeleton, Level 1'/382, l='MpServer', x=81,50, y=88,00, z=314,50], Entity_SpecialSkeleton['Skeleton, Level 1'/383, l='MpServer', x=92,50, y=67,00, z=338,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 884992680 bytes (843 MB) / 1240465408 bytes (1183 MB) up to 1398276096 bytes (1333 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1500M -Xms1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 34 mods loaded, 34 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	itemphysic{1.1.2} [ItemPhysic] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.12} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.2} [Treecapitator] ([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	armourersWorkshop{1.7.10-0.26.3.61} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.26.3.61.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Artifacts{1.1.1} [Artifacts] (Artifacts-1.1.1.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bettervillages{0.4} [Better Villages Mod] (BetterVillages-0.4(1.7.10).jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CustomChestLoot{1.1.1} [Custom Chest Loot] (CustomChestLoot-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	rftl{1.7.10} [Rotten Flesh to Leather] (Forge SSP SMP - Rotten Flesh 1.7.2 1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	gvc{0.4.0} [Gliby's Voice Chat Mod] (GlibysVC-1710_040.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	radixcore{1.3.4} [RadixCore] (RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mca{4.1.5} [Minecraft Comes Alive] (MCA-1.7.10-4.1.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mochickens{1.6.0} [Mo Chickens] (MoChickens-1.7.10-V1.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	origin{3.5.1} [Origin] (Origin-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Ping{%MOD_VERSION} [Ping] (Ping-1.7.X-1.0.2.B6-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_Ruins{14.6} [Ruins Spawning System] (Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.377.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SwordPedestal{1.0(1.7.10)} [Sword Pedestal] (SwordPedestal-1.0(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weepingangels{3.3.2} [Weeping Angels] (WeepingAngels-1.7.10-3.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	fyresmodjam{0.0.3f} [The You Will Die Mod] (You_Will_Die_Mod-0.0.3f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.2869, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because EXT_framebuffer_object is supported.
Anisotropic filtering is supported and maximum anisotropy is 2.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [OCD pack 1.8.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by TherminatorX** [comment]
Likely the same as  #1430

Should be fixed in the next update.

**Comment by bonii-xx** [comment]
What exactly did you do, can you reproduce it doing *exactly* the same steps with only tinkers related mods? Can you reproduce it in a new world?

**Comment by red3dred** [comment]
Well, i just make a bow, any bow really (From Tinkers of course) and if i only have vanilla arrows, and right click, it just crashes. I'll see with this mod only and test it.

**Comment by TherminatorX** [comment]
@red3dred Add 5 mods back in at a time and repeat those steps. If we can find out which mod is causing this, it would be most helpful.

**Comment by red3dred** [comment]
Will do. Posting the offending mod as soon as possible.

**Comment by bonii-xx** [comment]
-> Not tinkers fault
