### ISSUE TITLE
Mo Creatures Bloodfish

### ISSUE THREAD

**Issue by Robijnvogel** [SlimeKnights/TinkersConstruct#1435]
My issue is really simple:
There are Mo' Creatures dolphins, fish and crabs spawning in my Blood "tub."
Those creatures barely leave room for me to bathe.

I am assuming your Blood class extends the Vanilla Water class through the grapevine?
Could you do this some other way, that stops these blood-thirsty animals from spawning in the liquid they so desire?

I have also asked Mo' Creatures to fix this on their end with a post about about as seriously themed as this one.

**Comment by 61352151511** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/22e6378e16fbc9429fd901056602f4e7158a8c2b/src/main/java/tconstruct/smeltery/blocks/BloodBlock.java

The BloodBlock extends TConstructFluid which extends BlockFluidClassic.

https://github.com/SlimeKnights/TinkersConstruct/blob/22e6378e16fbc9429fd901056602f4e7158a8c2b/src/main/java/tconstruct/smeltery/blocks/TConstructFluid.java

BlockFluidClassic is a part of minecraft forge, from what I can tell it has nothing to do with water. The Mo'Creatures author is probably checking to see if those mobs can spawn there based on whether it is BlockFluidClassic or not. They should probably switch to checking if it's water.

**Comment by bonii-xx** [comment]
That's just how spawning works, nothing on tcons side.
