### ISSUE TITLE
Add-on help?

### ISSUE THREAD

**Issue by jordsta95** [SlimeKnights/TinkersConstruct#1439]
Hey there, I am looking into making some ticon integration for my mod (so if TiCon is detected then the "vanilla" recipes will be removed, and can only be made through Tinkers methods) So what I was wondering, because I can't really find how to do it, is how do I:
Add smelting recipes (put ore/ingot in smeltery to make liquid)
Add casting recipe (for every possible cast)
And how to change what inherent effect it has (e.g. writable, stonebound. etc.)

**Comment by bonii-xx** [comment]
The https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/TConstructRegistry.java and the remaining library classes should provide everything you need.
