### ISSUE TITLE
Crash with TC 1.8.2a and Nei

### ISSUE THREAD

**Issue by Dream-Master** [SlimeKnights/TinkersConstruct#1440]
My game crash as i looking for smeltery Recipes inside Nei.

https://gist.github.com/Dream-Master/b110177c7fb068d910b5#file-gistfile1-txt

post on Nei Git too:
https://github.com/Chicken-Bones/CodeChickenCore/issues/25

**Comment by bonii-xx** [comment]
One of your mods has faulty integration.

**Comment by Dream-Master** [comment]
Works now. Thanks
