### ISSUE TITLE
Can't repair items made with platinum/shiny

### ISSUE THREAD

**Issue by Chefbarbie** [SlimeKnights/TinkersConstruct#1443]
As title says: I can not repair any item made out of shiny with shiny. 

http://i.imgur.com/YEXEXtf.pngv

**Comment by laz2727** [comment]
Fixed, i thinkю

2015-03-04 19:06 GMT+06:00 Chefbarbie <notifications@github.com>:

**Comment by Adaptivity** [comment]
Update TiC/TE. And use search function: #1359 #1427

**Comment by Chefbarbie** [comment]
So what update is it fixed in? The links provided offer no insight into a solution, just a virtual mouse hunt. A nice response would have been "known issue, no fix" rather than try and teach me how to use the internet.

**Comment by TherminatorX** [comment]
@Chefbarbie It's fixed here in the repository, but it's not available to those who don't want to compile it from source yet. That's coming.
