### ISSUE TITLE
Server startup crash with smeltry and TE

### ISSUE THREAD

**Issue by Funwayguy** [SlimeKnights/TinkersConstruct#1444]
Crash Report:
http://pastebin.com/Pvp9Q1H7

Bug Location:
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/smeltery/blocks/TankAirBlock.java#L59

This crash is occurred when restarting a server. Not exactly sure what the specific smeltry setup was that caused this but I do know that at the line mentioned above, the tile entity is cast to TankAirLogic without checking (I know that it SHOULD be that tile but Minecraft is weird sometimes).

PS: It might be worthwhile to check whether other blocks are making this check because I know SpecialAI sometimes causes issues when mobs grief Tinker's blocks.

**Comment by bonii-xx** [comment]
Sounds more like your mappings broke. That block is not used at all unless you've activated the adaptive smeltery in the options. Which you shouldn't.

**Comment by TherminatorX** [comment]
Remind me again why we even have that code...

**Comment by bonii-xx** [comment]
What code? 168126b900e11c0ce065c6b4cec006701ff1aa60

**Comment by TherminatorX** [comment]
That's one way to solve it. :P

Now we just need to have something telling people what "superfun" actually does, and the config will be good.

**Comment by Funwayguy** [comment]
Thanks for the help. For the record this actually happened on a streamer friend of mine's server running the ByteSized pack. I'll be sure to let him know. Loving the mod by the way

**Comment by mDiyo** [comment]
"Superfun" mode makes the world super fun. I thought that was obvious?

**Comment by bonii-xx** [comment]
No more feedback.
