### ISSUE TITLE
1.7.10 Version Traveller's Chestplate Invisibility

### ISSUE THREAD

**Issue by Hellhound732** [SlimeKnights/TinkersConstruct#1445]
When I got the invisibility upgrade to the Traveller's Chestplate I expected something that made all of my armor invisible, or at least something that made all Traveller's armor from TConstruct invisible. The fact that this ability doesn't even make the chestplate itself invisible makes it seem quite useless.

**Comment by Hellhound732** [comment]
I would also like to mention how when zooming in with the Traveller's Goggles I am mostly unable to zoom out unless I press z about 20 times. The night vision upgrade for the goggles also does not do anything at all. It does not give you night vision.

**Comment by acters124** [comment]
hehe its like having an invisibility cloak but the cloak itself doesn't become invisible xD

**Comment by TherminatorX** [comment]
Would it be possible to have the gear change it's texture based on whether you're shifting or not? (When the stealth modifier is applied, of course)

**Comment by bonii-xx** [comment]
Technically yes, however no armor things will be fixed in 1.7.10
