### ISSUE TITLE
Dupe bug with weaponry

### ISSUE THREAD

**Issue by Fingercomp** [SlimeKnights/TinkersConstruct#1446]
One of the players of my server found a dupe bug: if someone other kills you using any of TConstruct weapon (sword, cleaver etc), all tools from TConstruct on hotbar drop in multiple amount.
http://i.imgur.com/MTiK0o5.png
We're using the latest version of a mod. Forge version is 1231.

**Comment by TherminatorX** [comment]
Wait, so is it if somebody kills you while you're using a TiC tool, or is it if they kill you with a TiC tool, or what? Can you even reproduce this in a TiC(+Mantle) only environment? This seems like a mod/bukkit interaction problem.

Also, update your Forge.

**Comment by Fingercomp** [comment]
1. I mean, if someone kills you with TiC weapon.
2. Just tested in singleplayer. If you kill yourself with dagger, for example, tools drop in multiple amount too.
3. Cauldron 1240 (the latest version) have lots of bugs, so I switched to 1231.

**Comment by bonii-xx** [comment]
Cauldron is not supported.
