### ISSUE TITLE
shiny bolts can't be crafted

### ISSUE THREAD

**Issue by kalenedrael** [SlimeKnights/TinkersConstruct#1448]
TConstruct v1.8.2a, Forge 1.7.10-10.13.2.1291

- melt TE4 shiny ingots in smeltery for fluid.platinum.molten (separate bug?)
- cast shiny tool rod in casting table
- put tool rod in casting table
- smeltery refuses to dispense shiny onto the tool rod when faucet is clicked

This also seems to be the case with shiny rod + any material, as well as any material rod + shiny.

**Comment by laz2727** [comment]
Most likely platinum isn't registered. And since TiC adds no platinum, this
should be closed.

2015-03-07 11:16 GMT+06:00 Chris Lu <notifications@github.com>:

**Comment by kalenedrael** [comment]
Shiny bolts are in NEI though - getting them with cheat mode yields bolts made of shiny and iron. Also, why should you be able to cast shiny parts using molten shiny but not bolts?

**Comment by laz2727** [comment]
Ugh. This is *not* a TiC issue.

2015-03-07 13:30 GMT+06:00 Chris Lu <notifications@github.com>:

**Comment by kalenedrael** [comment]
The parts are clearly from TiC; I don't have ExtraTiC or such. Yes, shiny is from TE4, but this suggests that the TE4 integration that is quite clearly built in is buggy or incomplete.

**Comment by laz2727** [comment]
There's no TE4 metals compat in TiC. So no.

2015-03-07 13:43 GMT+06:00 Chris Lu <notifications@github.com>:

**Comment by kalenedrael** [comment]
Have you looked at the source recently?

I can put TE4 shiny ingots in the smeltery and get molten shiny (fluid.platinum.molten). I can then use this to cast TiC parts like shiny pickaxe heads and tool rods. In addition, NEI quite clearly shows shiny being registered as a TiC part material. It's just that bolt cores with shiny as either part cannot be crafted, even though the items exist and appear to work just fine if I cheat them in.

**Comment by laz2727** [comment]
Yes, i did. No TF metal registration. If you know where it is, link the
.java file.

Ok. TiC is a Minecraft mod. Go tell Mojang about this.

2015-03-07 13:47 GMT+06:00 Chris Lu <notifications@github.com>:

**Comment by kalenedrael** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/eb32fa9f8d681263f3b931c16a3876cf2db08024/src/main/java/tconstruct/plugins/te4/TinkersThermalFoundation.java

and others

**Comment by laz2727** [comment]
It registers TF metals for ingot cast and basin.

2015-03-07 13:51 GMT+06:00 Chris Lu <notifications@github.com>:

**Comment by kalenedrael** [comment]
Must be magic that I can cast a shiny pickaxe head with molten shiny created from TE shiny ingots then.

**Comment by laz2727** [comment]
Or maybe some other mod adds these parts, you know. -_-

2015-03-07 13:55 GMT+06:00 Chris Lu <notifications@github.com>:

**Comment by kalenedrael** [comment]
Can you think of any? I'm not using ExtraTiC.

**Comment by laz2727** [comment]
No idea. TF, maybe. I don't see it in code, but that decompiler i use is
centuries old.

2015-03-07 13:57 GMT+06:00 Chris Lu <notifications@github.com>:

**Comment by kalenedrael** [comment]
I don't think TE/TF has ever interacted with TiC.

**Comment by bonii-xx** [comment]
Update TF.

**Comment by kalenedrael** [comment]
Updated to Thermal Foundation 1.0.0RC4-58, still doesn't work (and smeltery fluid still says 'fluid.platinum.molten').

**Comment by kalenedrael** [comment]
Updated to latest TF/TE/CoFHCore and TConstruct (built from 72b0c85c). Now shiny tool rods can be coated in other materials to make bolts, but I still can't coat tool rods in shiny.
