### ISSUE TITLE
Problem with Bows and Auto-Repair (Moss)

### ISSUE THREAD

**Issue by ignisthedragon** [SlimeKnights/TinkersConstruct#1449]
MC Version: 1.7.10
TC Version: 1.7.10-1.8.2a (the filename say so)

Just a little but pretty anoying thing. If you draw a Bow with auto-repair on it, the draw will reset every time, the bow is repairing itself. 
I would recommend to suspend the self-repair, as long a bow is drawing

**Comment by bonii-xx** [comment]
That's vanilla Minecraft, can't be fixed without coremod.
