### ISSUE TITLE
Crash on modifying Traveller's Boots

### ISSUE THREAD

**Issue by arandommop** [SlimeKnights/TinkersConstruct#1450]
Steps to reproduce:

- Place Traveller's Boots (mine were not at full durability, if relevant) into Tool Forge.
- Place a Ball of Moss or Bounce Pad into the modifier slot.

(The above steps are reversible)
- Game should instantly shut down internal server.

**Comment by TherminatorX** [comment]
Can we have a pastebin-ed crash log?
