### ISSUE TITLE
Beheading not working

### ISSUE THREAD

**Issue by MrRonaldReagan** [SlimeKnights/TinkersConstruct#1452]
I've been sitting at my wither skeleton spawner for a while now killing them with a Sword that has Beheading VI and I'm hardly getting drops. Is anyone else experiencing this issue? I believe the current version is 1.8.2

Is it possible that Looting III could be interfering with it?

**Comment by laz2727** [comment]
Some other mod changes them. I don't think TiC can do anything about it.

**Comment by bonii-xx** [comment]
EnderIO does that. I believe one of the newer versions fixes the problem.
