### ISSUE TITLE
Some items are missing 1.4.7

### ISSUE THREAD

**Issue by iTzBizKiiD** [SlimeKnights/TinkersConstruct#1454]
I startet playing ftb lite and added some extra mods like GraviSuite or Tinkerers Construct, and i startet building the smeltery, but the smeltery additions like the tank or the controller or the drain just arent in the game. Please help

**Comment by bonii-xx** [comment]
We don't support old versions.

**Comment by iTzBizKiiD** [comment]
Where do i get support for older Versions?

**Comment by bonii-xx** [comment]
You don't, you're on your own if you want to use old versions.
