### ISSUE TITLE
Possible wrong tool breakdown

### ISSUE THREAD

**Issue by xterminal86** [SlimeKnights/TinkersConstruct#1455]
I was playing crash landing 1.1.3. I had a bone TC mattock, that had been leveled up couple of times already, and when I started tilling grass for seeds, it suddenly disappeared. I played the game with low sound at the time, so I couldn't hear that it actually broke for sure, but I do remember that tool had low durability. I never experienced such situation before - this was the first time. Also, I was attacked by the spider back then, so I thought that it might be some kind of thieving spider, but then I checked FTB wiki and found no such variation of the creature. So my guess is that this particular tool behaved like a hoe when it was being used on a grass. 

Could you check the code for such possible situation?

Thanks.

**Comment by bonii-xx** [comment]
There was such an issue once, but it got fixed quite a while back. The version in there probably doesn't have that fix yet.
