### ISSUE TITLE
About Tinker Defense.

### ISSUE THREAD

**Issue by Drehverschluss** [SlimeKnights/TinkersConstruct#1457]
Hello sir mister @bonii-xx :)
its me again.

Hope it noot that kinda bad to post something about another mod in your issues. but since the creator from "Tinker Defense" wont response i thought to may ask you.

I have some kinda error what a bit weird. Maby do you have a idea what he did wrong so i can get @p000ison to update the mod for the community. 

Would be a shame if this addon for Tinker and M&B2 gets abandonned.

Here is the error what happens on client at startup.
http://pastebin.com/ijvDB0Eg

MFG

**Comment by laz2727** [comment]
Nope, not our problem.

2015-03-09 22:26 GMT+06:00 Drehverschluss <notifications@github.com>:

**Comment by bonii-xx** [comment]
Looks like you're missing M&B2.

**Comment by Drehverschluss** [comment]
@bonii-xx 
Thanks will try to resolve it or seems like i need to whait :)

@laz2727 
........
Bad day?
