### ISSUE TITLE
faucet not pouring

### ISSUE THREAD

**Issue by DTM450** [SlimeKnights/TinkersConstruct#1458]
Version 1.7.10
Not sure why but I can't pour anything from the smeltery and I can't cast anything

**Comment by TherminatorX** [comment]
Screenshots of your setup, please? We can't help you unless we know how you're trying to do things.

**Comment by bonii-xx** [comment]
Sounds like something is broken.

**Comment by DTM450** [comment]
I worked out what I did wrong I had the smallest smeltery and the back of the drain wasnt facing the center of the smeltery
