### ISSUE TITLE
Crash at startup when using latest build of Tinker's Construct and Forge Multipart (Conflict?)

### ISSUE THREAD

**Issue by ate0ate** [SlimeKnights/TinkersConstruct#1459]
Using any dev build from the Jenkins after build 914 causes this crash at startup. I'm not sure what is happening so I figure I will post this report both here and the Multipart github. This is using forge 1307 and TCon jenkins build 916, build 914 works perfectly...

http://pastebin.com/sTZqrVc0

**Comment by bonii-xx** [comment]
Those builds are broken, don't use them.
