### ISSUE TITLE
Right click "pulls/places" from wrong side/slot

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1461]
If I have a Tinkers Tool on my hot bar slot 1, the right click places what ever I have in slot 9. I would expect it to place the item in slot 2...

**Comment by bonii-xx** [comment]
But that's how it works. :)

**Comment by TheQuadShot** [comment]
Then I guess there is some misunderstanding, If I have a pick in slot 2, and torches in slot 3, and I'm using my pick, and right click, then a torch is placed, this is what I would expect to happen, how ever, if the pick is in slot 1 and torches are in slot 2, and I have cobble in slot 9, the right click will place the cobble, not the torch. It's not consistent with the first scenario I mentioned with the pick.

**Comment by MrKunji** [comment]
The slot 1 is an exception, it's been this way for times.

**Comment by TheQuadShot** [comment]
Oh, sorry, I guess the statement that the right click places what ever is to the right should be changed to mention this exception (I'm not sure where I read/saw/heard about it).

**Comment by TherminatorX** [comment]
In other words: you cannot use RC to place anything in the first two slots, and both slots 1 and 8 use the item in slot 9. Annoying, but not likely to be fixed.

**Comment by TheQuadShot** [comment]
I’m OK with it as is, It didn’t work as expected. The FAQ states that it places the item on the right...
So if there is a bug here, it’s on the FAQ

**Comment by bonii-xx** [comment]
We have an FAQ?

**Comment by TheQuadShot** [comment]
It’s the first question...
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638-tinkers-construct

**Comment by bonii-xx** [comment]
This only says that it's an intentional feature, but nothing about how it works. :)

**Comment by TheQuadShot** [comment]
Yes, and that is kind of my point... If I have a tool to the right, (or the slot 1,9 thing) then it does nothing... It should be doc’ed, else the bug would have been that it doesn’t place torch/block on right click.
