### ISSUE TITLE
Tool parts/items not showing in NEI

### ISSUE THREAD

**Issue by ubermentat** [SlimeKnights/TinkersConstruct#1463]
Forge: 1291
TiC: 1.8.3b

Description: Certain tool parts and items are not showing up in NEI. The wooden variant appears (the one with metadata 0), but none of the other versions appear. For the metal versions, the recipes can still be found by finding the parts in the smeltery melting listings. The only affected items are regular tool rods, regular bindings, scythe heads, and shards/chunks. Everything else in the mod shows up just fine.

**Comment by bonii-xx** [comment]
How do I best put this... No?

**Comment by ubermentat** [comment]
No as in this is intended, or no as in this doesn't happen for anyone else?

**Comment by bonii-xx** [comment]
No as you have something that does that and you have not provided any useful information. Reproduce it with only tinkers and I might believe that it's an issue.

**Comment by darthvader45** [comment]
Found it, it seems to be if you have InpureCore installed, as it sets special NEI filters.  Disable them to see the parts in NEI.
