### ISSUE TITLE
Drawbridge crashing client but not server.

### ISSUE THREAD

**Issue by chardo440** [SlimeKnights/TinkersConstruct#1467]
So my client crashes every time I use iron bars in an advanced draw bridge. I have 3 advanced drawbridges on the ceiling that are supposed to deploy 5 iron bars each to make a portcullis style entrance. However, They each deploy 3 times then I crash. When I log back in though they are fully down and everything is fine. I'll also note that when I retract them there is no issue.  it's just deploying them.

Here is the pastebin below.

http://pastebin.com/MJCqJYcy

**Comment by bonii-xx** [comment]
Ping @Glassmaker
