### ISSUE TITLE
NEI Buggyness

### ISSUE THREAD

**Issue by jjjhfam** [SlimeKnights/TinkersConstruct#1468]
Most of the blocks in NEI turn completely black when mousing over the metals in the smeltery. (I made the GUI smaller so there would be more examples in NEI)
NEI 1.0.4.79
TConstruct 1.8.3b
![2015-03-14_12 56 55](https://cloud.githubusercontent.com/assets/11479840/6653489/e2df156a-ca62-11e4-9f05-444114a3b7c4.png)

**Comment by TherminatorX** [comment]
Confirmed.

**Comment by Ianaver** [comment]
this is an NEI bug not a TiC bug

**Comment by mDiyo** [comment]
This happens with any tooltip in NEI. It is not Smeltery specific.
