### ISSUE TITLE
Traveler's Gear working incorrectly

### ISSUE THREAD

**Issue by MikesJam** [SlimeKnights/TinkersConstruct#1471]
I'm using Tinker's Construct 1.7.10-1.8.3b with Forge 10.13.2.1307 in MC 1.7.10. I have noticed that various aspects of the Traveler's Gear set do not work correctly, if not at all.

* High Step ability on the Traveler's Boots does not work at all.
* Double Jump modifier does not work at all on either the Traveler's Boots or Wings.

I can provide more information if needed. Thank you in advance!

**Comment by TherminatorX** [comment]
Using the same versions, I'm not having any trouble with the double-jump, as my quad-jump works fine.
High-step is most certainly working.

Can you give us the conditions you are testing in? Mine might be different.

**Comment by MikesJam** [comment]
So far, I've only had the chance to use the Traveler's Gear in SMP. I haven't had the chance to test it out in creative yet. Maybe there is a conflict with another mod?

Here's the list of mods that I'm using:
http://puu.sh/gAG3n/eb5c53dd59.png

**Comment by bonii-xx** [comment]
Sounds like another mod is messing with it. If you can find which, you can probably blame the mod author \o/

**Comment by jaspercayne** [comment]
I'll chime in here too. The high step does function like a charm, however I cannot seem to double or triple jump at all, moving the camera or not. The vest doesn't seem to make me really move any faster in water either, while I'm at it.

**Comment by sboeck** [comment]
I'm experiencing the same problems with the boots but NEI and optifine seem to be the only mods to overlap.
http://imgur.com/AgEipGo
