### ISSUE TITLE
1.8.3b Hell on earth.

### ISSUE THREAD

**Issue by mdbakpo** [SlimeKnights/TinkersConstruct#1472]
So, I was trying out 1.8.3b with my magic modpack, I created a new world and Dirt had turned into Soul Sand, Sand into Stone, Stone into Endstone, any log into Netherrack and any leaves into lava sources.

![2015-03-13_14 48 10](https://cloud.githubusercontent.com/assets/6465876/6654058/30a356b2-ca8b-11e4-8af2-5f888b37bc2d.png)

Here's my mod list: (TiCo not included, of course)

![modlist](https://cloud.githubusercontent.com/assets/6465876/6654086/86a925ea-ca8c-11e4-8718-3612c8dcb3ec.PNG)

**Comment by TherminatorX** [comment]
See @mDiyo, this is what I was talking about. :P

@mdbakpo You are having superfun. You did this to yourself.

**Comment by bonii-xx** [comment]
So.. what's the problem here? Sounds super fun to me.

**Comment by laz2727** [comment]
You need to disable superfun in TiC config, if that's not obvious enough,
mdbakpo.
...We need a superfun survival modpak.

2015-03-15 14:29 GMT+06:00 boni <notifications@github.com>:

**Comment by mdbakpo** [comment]
I'm such a noob, sorry for wasting your time people. :P
