### ISSUE TITLE
All TiC bows allow for sharpness to be added as a modifier?

### ISSUE THREAD

**Issue by Ianaver** [SlimeKnights/TinkersConstruct#1473]
for some reason bows allow for sharpness to be added and forces the user to use the bow like a sword for the effect to work, change it to power instead of sharpness on the long and short bows?

**Comment by laz2727** [comment]
Nope. Redstone is the only modifier that matters © devs

**Comment by bonii-xx** [comment]
Welcome to Tinkers. ;o

**Comment by Ianaver** [comment]
(facepalm) I forgot to read the new weaponry book on bows.... sorry :(
