### ISSUE TITLE
All TiC bows don't allow for flame to be added by blaze powder but instead accepts lava crystals

### ISSUE THREAD

**Issue by Ianaver** [SlimeKnights/TinkersConstruct#1474]
TiC bows accept lava crystals as modifiers but not blaze powder. This also forces the user to use the bow as a sword in order to get the flame modifier to work, the flame is not being applied to the arrows, only the bow

**Comment by bonii-xx** [comment]
Not being able to use blaze sounds wrong. But yes, of course you have to hit stuff for it to burn....?

**Comment by Ianaver** [comment]
flame is not being applied to the arrows only the bow it self so in order to make for example; a pig to burn you have to use the bow like a sword and then it will be on fire

**Comment by laz2727** [comment]
Add flame to the arrows. Bow enhancements only affect bow itself.

2015-03-15 21:30 GMT+06:00 Ianaver <notifications@github.com>:

**Comment by Ianaver** [comment]
so..... do I need to close this or no?

**Comment by laz2727** [comment]
No. Bows not accepting blaze powder is unacceptable.

2015-03-15 22:14 GMT+06:00 Ianaver <notifications@github.com>:

**Comment by Ianaver** [comment]
ok sorry I got a bit confused there on your first message

**Comment by bonii-xx** [comment]
Right, now I remember, that's disabled intentionally. Not a bug, woo!

**Comment by Ianaver** [comment]
oh ok sorry about the inconvenience! :)

**Comment by Ianaver** [comment]
*facepalm* I forgot to read the new weaponry book on bows.... sorry
