### ISSUE TITLE
EnviroMine compatibility

### ISSUE THREAD

**Issue by Pablode** [SlimeKnights/TinkersConstruct#1480]
When EnviroMine food spoling is enabled, carrots, apples and melons cannot be used for casting anymore. Can anyone confirm?

Besides that, I hope this is the right place to mention some feature suggestions / tweaks:
-Entities should be on fire when inside a smeltery with lava; Flammable blocks should begin to burn
-Maybe add some liquid sound effect, f.i. from vanilla lava when the smeltery contains molten metal
(-Larger smeltery bases -> apparently already possible, sorry)

**Comment by laz2727** [comment]
You already can build 1x1 to, i think, 9x9 smelteries.

2015-03-16 20:06 GMT+06:00 Pablo Delgado <notifications@github.com>:

**Comment by Pablode** [comment]
You're right, sorry about that. :)

**Comment by bonii-xx** [comment]
Environmine probably changes the carrot/apples/... items which therefore breaks the recipies.

Entities inside a smeltery already take damage if there's a hot liquid in the smeltery.

And no, no sound effects. You can always place a block of lava beneath it if you really want that :P
