### ISSUE TITLE
/give gives you the item but its a blank texture

### ISSUE THREAD

**Issue by djoveryde** [SlimeKnights/TinkersConstruct#1481]
If i use /give player TCONSTRUCT_item, or even the itemid it gives me the item but in the inventory bar theres no icon, if you select it you end up with a multicolored square. Any idea how to fix this?
This is using the latest 1.8.3b version

**Comment by laz2727** [comment]
You have to use creative mode to get TiC items, they are too NBT-dependent
to work with /give.

2015-03-16 23:00 GMT+06:00 djoveryde <notifications@github.com>:

**Comment by bonii-xx** [comment]
Don't use /give.
