### ISSUE TITLE
Silver tools are non-repairable

### ISSUE THREAD

**Issue by DragonEmbers** [SlimeKnights/TinkersConstruct#1482]
Have not tried it with other ThermalExpansion metals yet but silver tools cannot be repaired.

In addition, when using a crafting bench instead of a tool bench it just absorbs the silver supplied as a material without repairing the durability.

**Comment by Adaptivity** [comment]
What version of both Tcon and TE?

**Comment by DragonEmbers** [comment]
Currently tested the bug with TConstruct-1.7.10-1.8.2a and ThaumicExploration-1.7.10-1.1-37

I'm about to try some things out  (other metals, latest versions).

I should also mention that silver from IC2 presents the same behavior.

**Comment by bonii-xx** [comment]
Update.
