### ISSUE TITLE
Issue with Inventory GUI tabs

### ISSUE THREAD

**Issue by crunkazcanbe** [SlimeKnights/TinkersConstruct#1484]
I posted about this issue here https://github.com/micdoodle8/Galacticraft/issues/1505#issuecomment-82581457 and was told to post it here. It happens with just tinkers construct being the only mod installed , but it is really bad with tinkers , Galacticraft, and battle gear 2 mod all installed at one time .

Here is a picture https://imgur.com/hH6DhqJ . Like I was saying it is the same thing when just tinkers is installed . forge 1291 , and forge 1307 are the same issue. I have to use forge 1307 for fastcraft to not crash on structure gen though ,  but it doesn't matter its the same on both recommended forge , and newest forge . 

The guys over on the Galacticraft said they use your code for the tabs . @radfast I dont know if you can explain this better then me , but if you could it would be nice of you .

**Comment by MrKunji** [comment]
Does it happens when you are clear of potion effects?

**Comment by crunkazcanbe** [comment]
Nope it does not everything looks normal then.

**Comment by radfast** [comment]
hi guys.  I'm not sure the OP has only Tinker's Construct installed, he later mentioned that he has a bunch of other mods under his 1.7.10 folder (for example, Baubles) which he didn't clear out.  Hoping for more clarification here ...

**Comment by crunkazcanbe** [comment]
Damn I hate having to prove , but here it is a picture of my mods folder https://imgur.com/IaZTVl8 in game mod list https://imgur.com/6OzF8e9 and F3 with the inventory up showing the issue https://imgur.com/VRl89hl

**Comment by radfast** [comment]
Confirmed the issue happens whenever the player does __not__ have NEI installed.  (I guess most mod players do use NEI).  I'm happy to fix this and post a PR here, will be a day or two coming as I'm not at my development PC right now.

**Comment by bonii-xx** [comment]
#1506
