### ISSUE TITLE
Tools with Tuberous Flux Capacitor won't recharge

### ISSUE THREAD

**Issue by erkro1** [SlimeKnights/TinkersConstruct#1486]
When I upgrade a tool with the Tuberous Flux Capacitor item (looks like a potato and can store 16k RF, it's from Thermal Expansion), it becomes unchargable by any machine.

**Comment by laz2727** [comment]
Just like Tuberous Flux Capacitor. /thread

2015-03-18 21:52 GMT+06:00 erkro1 <notifications@github.com>:

**Comment by erkro1** [comment]
Yeah I learned that too, perhaps it should be blacklisted or something to prevent others from trashing their tools?

**Comment by bonii-xx** [comment]
You can always upgrade the capacitor for free.
