### ISSUE TITLE
Sharpness modifier applying incorrectly

### ISSUE THREAD

**Issue by akvgergo** [SlimeKnights/TinkersConstruct#1487]
Depending on how much quartz i put on a weapon at once, the damage when the modifier gets maxed out changes.
For the testing I used full manyullyn cutlasses, which have the damage of 4 hearts by default.
Here, I put 8 quartz on the tool at once(2 blocks) and the damage was 6 at the end:
![2015-03-18_23 42 50](https://cloud.githubusercontent.com/assets/8812148/6732872/d8c212c2-ce4e-11e4-8e8c-91cfab61df9b.png)
Here, I put 2x8 and then 2 blocks on the sword, the damage was 5,5:
![2015-03-18_23 42 47](https://cloud.githubusercontent.com/assets/8812148/6732923/2cd35b32-ce4f-11e4-97d1-168cf7d34d5c.png)
And then, I put 3 AE2 quartz at once on the sword, which only gave 4,5 damage:
![2015-03-18_23 42 44](https://cloud.githubusercontent.com/assets/8812148/6732952/6088c552-ce4f-11e4-887e-9631d3062c21.png)
Using the latest version of tinkers and iguana tweaks.

**Comment by akvgergo** [comment]
@bonii-xx Can I get an update on this? Are you busy or just not fixing bugs for 1.7.10 anymore? :P

**Comment by bonii-xx** [comment]
Ah yes, forgot to comment. It's a known thing, the canculation goes wonky somewhere sometimes. Considering the state it's in it's not worth looking into it any further though, so I don't plan on fixing it.
