### ISSUE TITLE
Tinkers Contruct 1.8.3b Crash

### ISSUE THREAD

**Issue by StuardBr** [SlimeKnights/TinkersConstruct#1490]
Hello! I'm here to report a crash when i try to open the game, The crash is here: http://pastebin.com/Eprmsf6N

In the version 1.8.2a everything is OK, but today when i updated to the last version, i get this crash.

Tks for the atention.

Versions:
Forge 10.13.2.1291
Tinkers 1.8.3b

**Comment by TherminatorX** [comment]
@bonii-xx It's your item, man.

@StuardBr Try redownloading the mod.

**Comment by StuardBr** [comment]
Same crash redownloading the mod. Any idea?

**Comment by bonii-xx** [comment]
Redownload. Also I'd advice you to actually download from curse instead from weird 3rd party sites.

**Comment by StuardBr** [comment]
Of Course i'm downloading of the official link, in the minecraftforum page: http://www.curse.com/mc-mods/minecraft/tinkers-construct#t1:other-downloads

Same problem

**Comment by bonii-xx** [comment]
"04.01.0-TConstruct-1.7.10-1.8.3b.jar" is not the filename of an official file. ;P
Anyway, problem is the file you have, it seems to be missing stuff.

**Comment by StuardBr** [comment]
I know that, but i'm free to rename the archive to whatever i want, right? I rename all the mods in my modpack to know in what order i installed.Of course, i tested with a new copy of the jar, without change the name, but the still crashing.

**Comment by TherminatorX** [comment]
@StuardBr I wouldn't suggest that.

**Comment by bonii-xx** [comment]
5e366a2e353c90b8d553182c51a98970

**Comment by StuardBr** [comment]
The MD5 is ok, so the file is OK, right? Any other idea?
http://i.imgur.com/W1dTLzF.jpg

**Comment by laz2727** [comment]
The only other thing i see is
> Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in
environment: optifine
But that usually starts, at least. Although i don't think that CJB cheats
are healthy for environment.

2015-03-22 13:40 GMT+06:00 StuardBr <notifications@github.com>:

**Comment by bonii-xx** [comment]
Yes, some other mod in your environment fucked it up. If you use exactly the same tinkers file in an instance with only tinkers and mantle it probably wont happen. ;o

**Comment by StuardBr** [comment]
I'll try to track wath mod is fucking the TC, because is happening only in this new version... If i find the mod i post here.

@iaz2727 I tested without the optifine and same thing. And, what you say with "Healthy for enviroment"? Incompatibilities?

**Comment by bonii-xx** [comment]
There seems to be an issue with the order of mods load in some combinations. Got a full client log?
