### ISSUE TITLE
[Request] Allow more constructor options for adding modifiers

### ISSUE THREAD

**Issue by UndeadZeratul** [SlimeKnights/TinkersConstruct#1493]
As shown [here](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/modifiers/tools/ModReinforced.java#L11), a lot of parameters for reinforced modifiers are defaulted and hardcoded.  Personally, I'd like to add adamantine large plates from ExtraTiC as a modifier that adds reinforced 2, instead of just 1, to my modpack; but because this parameter is hardcoded, it won't allow me to do so.  Would it be possible to add an additional constructor with more parameters exposed so that more levels of reinforced can be added?

**Comment by UndeadZeratul** [comment]
Changing the title to be more generic, as I've had an idea.  Maybe for each modifier class, there's a constructor that takes in each parameter possible, so that the modifier can be fully configurable when added.

The reason I'm asking all of this is because of the mod [Tinkers' Modifiers](http://www.curse.com/mc-mods/minecraft/224971-tinkers-modifiers).  Their config file requires you to pass in each parameter, in order, to add a modifier.  The problem I'm running into are inconsistencies or just plain defaulted or hardcoded values in the constructors provided, the main one being the Reinforced modifier.  I've also noticed the lapis modifier defaults its tooltip to "Lapis" colored blue.  I would like to use Metallurgy's Midasium dust to apply a fortune modifier, but the tooltip is hardcoded and therefore looks off.  If I were able to call a constructor that allowed me to fully configure the modifier, that'd be great.

**Comment by laz2727** [comment]
A LOT of stuff is hardcoded, really. For instance, i wanted to make a
custom tank for smeltery, but nope, everything is hardcoded.

2015-03-21 21:39 GMT+06:00 Undead Zeratul <notifications@github.com>:

**Comment by bonii-xx** [comment]
Simply put: The modifier system sucks and modifiers are a mess. Without a rewrite it doesn't make much sense, therefore not in this version. Sorry bud.

**Comment by bonii-xx** [comment]
If you *really* need it, the best solution is to add a simple mod that adds the custom modifiers as separate modifiers.

**Comment by UndeadZeratul** [comment]
ah, darn.  Fair enough, if you plan on re-writing them anyways, then it makes sense to wait until the next big version.  I can deal with some of the stuff, and work around the rest, it'd just be nice to have is all.  Thanks though!
