### ISSUE TITLE
Reinforced on projectiles

### ISSUE THREAD

**Issue by TherminatorX** [SlimeKnights/TinkersConstruct#1494]
All the new projectile items can have the "Reinforced" modifier placed on them, but it doesn't count to anything.
Example, fill creative paper shurikens with obsidian large plates, and they will still have 8 ammo, and obsidian arrows will always have 9.

**Comment by bonii-xx** [comment]
Reinforced on ammo works with breakchance when hitting entities.

**Comment by TherminatorX** [comment]
Well, that doesn't seem to be working either, then. When applying a obsidian large plate to a NEI cobalt arrow, the break chance doesn't change. The only thing that changed was the "effective durability," which doesn't do anything to them. Unbreakable arrows will not drop.

(Unbreakable shurikens will, though)

**Comment by bonii-xx** [comment]
Everything working as intended.

**Comment by TherminatorX** [comment]
@bonii-xx you just told me that obsidian plates on arrows decrease the break chance, and then when I said they don't, that's intended?
I'm sorry if I come off rude, but I'm confused now.

**Comment by bonii-xx** [comment]
I didn't say they decrease the breakchance. :)
Breakchance takes effect when you hit nothing. Reinforced takes action when you hit something.
