### ISSUE TITLE
Crash when adding ores to smeltary

### ISSUE THREAD

**Issue by biggggg5** [SlimeKnights/TinkersConstruct#1495]
I am running a few different mods in the hope of making a small personal modpack and everything seemed to be working but when i made a smeltery using one that had spawned with a village and when i tried to add iron ore to it my game crashed and produced this crash report that i don't know enough about to understand

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 3/21/15 7:36 PM
Description: Updating screen events

java.lang.NoClassDefFoundError: mantle/utils/ItemMetaWrapper
	at tconstruct.library.crafting.Smeltery.getLiquifyTemperature(Smeltery.java:107)
	at tconstruct.smeltery.logic.SmelteryLogic.updateTemperatures(SmelteryLogic.java:521)
	at tconstruct.smeltery.logic.SmelteryLogic.func_70296_d(SmelteryLogic.java:679)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:157)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at tconstruct.client.gui.NewContainerGui.handleMouseClick(NewContainerGui.java:829)
	at tconstruct.client.gui.NewContainerGui.func_146286_b(NewContainerGui.java:767)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.library.crafting.Smeltery.getLiquifyTemperature(Smeltery.java:107)
	at tconstruct.smeltery.logic.SmelteryLogic.updateTemperatures(SmelteryLogic.java:521)
	at tconstruct.smeltery.logic.SmelteryLogic.func_70296_d(SmelteryLogic.java:679)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:157)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at tconstruct.client.gui.NewContainerGui.handleMouseClick(NewContainerGui.java:829)
	at tconstruct.client.gui.NewContainerGui.func_146286_b(NewContainerGui.java:767)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: tconstruct.smeltery.gui.SmelteryGui

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['biggggg2112'/26554, l='MpServer', x=249.31, y=67.62, z=255.79]]
	Chunk stats: MultiplayerChunkCache: 546, 546
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (224,64,256), Chunk: (at 0,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 512 game time, 512 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 82 total; [EntityTrail['unknown'/26640, l='MpServer', x=249.31, y=67.62, z=255.79], EntityCreeper['Creeper'/26642, l='MpServer', x=329.50, y=23.00, z=252.50], EntitySkeleton['Skeleton'/27672, l='MpServer', x=186.50, y=16.00, z=209.50], EntityItem['item.tile.arsmagica2:desert_nova'/32863, l='MpServer', x=264.78, y=64.13, z=242.84], EntitySkeleton['Skeleton'/26728, l='MpServer', x=190.50, y=26.00, z=233.50], EntitySkeleton['Skeleton'/26729, l='MpServer', x=193.50, y=26.00, z=231.50], EntitySkeleton['Skeleton'/27780, l='MpServer', x=307.44, y=46.00, z=206.06], EntityZombie['Zombie'/27793, l='MpServer', x=231.41, y=28.00, z=233.75], EntityCreeper['Creeper'/27794, l='MpServer', x=237.69, y=29.00, z=230.50], EntityCreeper['Creeper'/27795, l='MpServer', x=236.91, y=29.00, z=229.50], EntityBat['Bat'/26808, l='MpServer', x=189.88, y=15.00, z=225.75], EntityKeese['Keese'/26855, l='MpServer', x=312.73, y=65.12, z=318.57], EntityKeese['Keese'/26857, l='MpServer', x=325.45, y=69.46, z=282.58], EntitySkeleton['Skeleton'/26907, l='MpServer', x=183.88, y=22.00, z=178.50], EntityZombie['Zombie'/26910, l='MpServer', x=185.34, y=20.00, z=178.69], EntityBat['Bat'/26927, l='MpServer', x=204.53, y=29.93, z=204.91], EntityBat['Bat'/26928, l='MpServer', x=193.84, y=20.90, z=212.44], EntityItem['item.item.seeds'/33091, l='MpServer', x=272.47, y=63.13, z=295.38], EntityEnderman['Enderman'/27996, l='MpServer', x=173.63, y=26.00, z=182.94], EntityBat['Bat'/26976, l='MpServer', x=234.47, y=26.96, z=205.31], EntityBat['Bat'/26980, l='MpServer', x=172.06, y=29.90, z=190.00], EntityZombie['Zombie'/26994, l='MpServer', x=203.50, y=26.00, z=210.50], EntitySpider['Spider'/28033, l='MpServer', x=223.25, y=20.00, z=184.53], EntitySpider['Spider'/28035, l='MpServer', x=222.50, y=20.00, z=188.50], EntityCreeper['Creeper'/28036, l='MpServer', x=218.50, y=20.00, z=186.50], EntityCreeper['Creeper'/28037, l='MpServer', x=212.50, y=20.00, z=186.50], EntityCreeper['Creeper'/28038, l='MpServer', x=212.50, y=20.00, z=184.50], EntityKeese['Keese'/27040, l='MpServer', x=186.87, y=29.53, z=241.27], EntitySkeleton['Skeleton'/28112, l='MpServer', x=212.50, y=19.00, z=191.50], EntityZombie['Zombie'/27089, l='MpServer', x=255.06, y=44.00, z=191.50], EntityItem['item.item.seeds'/33236, l='MpServer', x=250.72, y=64.13, z=266.78], EntityItem['item.tile.arsmagica2:desert_nova'/33258, l='MpServer', x=201.25, y=64.13, z=306.28], EntitySkeleton['Skeleton'/27184, l='MpServer', x=176.50, y=13.00, z=229.50], EntitySkeleton['Skeleton'/27186, l='MpServer', x=174.50, y=13.00, z=229.50], EntitySkeleton['Skeleton'/27187, l='MpServer', x=174.50, y=13.00, z=233.50], EntitySkeleton['Skeleton'/27188, l='MpServer', x=175.50, y=13.00, z=235.50], EntitySkeleton['Skeleton'/27189, l='MpServer', x=174.50, y=13.00, z=237.50], EntityItem['item.tile.cloth.white'/33367, l='MpServer', x=209.44, y=68.13, z=198.59], EntityZombie['Zombie'/27234, l='MpServer', x=187.50, y=18.00, z=259.50], EntityZombie['Zombie'/28271, l='MpServer', x=232.50, y=11.00, z=215.50], EntityCreeper['Creeper'/28275, l='MpServer', x=233.50, y=11.00, z=215.50], EntitySpider['Spider'/28344, l='MpServer', x=197.50, y=24.00, z=186.50], EntitySkeleton['Skeleton'/28346, l='MpServer', x=179.88, y=42.00, z=180.38], EntitySkeleton['Skeleton'/28347, l='MpServer', x=191.13, y=39.00, z=181.84], EntitySkeleton['Skeleton'/28348, l='MpServer', x=191.66, y=39.00, z=180.97], EntitySkeleton['Skeleton'/28349, l='MpServer', x=195.16, y=40.00, z=184.50], EntityCreeper['Creeper'/28351, l='MpServer', x=190.47, y=39.00, z=182.69], EntityCreeper['Creeper'/27380, l='MpServer', x=188.63, y=39.00, z=180.03], EntityWitch['Witch'/28434, l='MpServer', x=224.50, y=58.00, z=190.50], EntityWitch['Witch'/28435, l='MpServer', x=223.50, y=58.00, z=188.50], EntityItem['item.tile.arsmagica2:desert_nova'/33564, l='MpServer', x=253.25, y=64.13, z=265.00], EntitySheep['Sheep'/26435, l='MpServer', x=203.78, y=70.00, z=198.06], EntitySheep['Sheep'/26436, l='MpServer', x=198.63, y=70.00, z=199.78], EntitySheep['Sheep'/26437, l='MpServer', x=209.47, y=69.00, z=195.75], EntityVillager['Villager'/26439, l='MpServer', x=232.67, y=68.00, z=262.08], EntityItem['item.item.zss.keysmall'/26441, l='MpServer', x=224.41, y=15.13, z=224.13], EntityItem['item.item.emerald'/26442, l='MpServer', x=225.88, y=16.06, z=227.53], EntityItem['item.item.compass'/26443, l='MpServer', x=226.03, y=15.13, z=224.13], EntityItem['item.item.bucket'/26444, l='MpServer', x=225.97, y=16.06, z=227.88], EntityItem['item.item.zss.shield_deku'/26446, l='MpServer', x=225.94, y=16.06, z=227.19], EntityVillager['Villager'/26447, l='MpServer', x=253.63, y=64.00, z=265.74], EntityDryad['Dryad'/26454, l='MpServer', x=263.50, y=69.00, z=201.50], EntityVillager['Villager'/26455, l='MpServer', x=264.53, y=64.00, z=252.09], EntityVillager['Villager'/26456, l='MpServer', x=249.84, y=64.00, z=266.34], EntityVillager['Villager'/26457, l='MpServer', x=258.47, y=65.00, z=260.66], EntityDryad['Dryad'/26458, l='MpServer', x=252.50, y=64.00, z=279.50], EntityDryad['Dryad'/26459, l='MpServer', x=251.50, y=64.00, z=279.50], EntityVillager['Villager'/26465, l='MpServer', x=275.59, y=66.00, z=244.78], EntityVillager['Villager'/26466, l='MpServer', x=265.16, y=65.00, z=261.50], EntityVillager['Villager'/26468, l='MpServer', x=281.50, y=65.00, z=240.50], EntityVillager['Villager'/26469, l='MpServer', x=286.91, y=64.00, z=258.56], EntityVillager['Villager'/26477, l='MpServer', x=283.84, y=64.00, z=256.56], EntityVillager['Villager'/26478, l='MpServer', x=287.59, y=64.00, z=248.72], EntityDryad['Dryad'/26489, l='MpServer', x=313.50, y=64.00, z=219.50], EntityDryad['Dryad'/26490, l='MpServer', x=313.50, y=64.00, z=221.50], EntityClientPlayerMP['biggggg2112'/26554, l='MpServer', x=249.31, y=67.62, z=255.79], EntityZombie['Zombie'/27601, l='MpServer', x=296.50, y=54.00, z=210.50], EntityZombie['Zombie'/27602, l='MpServer', x=297.50, y=54.00, z=210.50], EntityWaypointContainer['unknown'/26579, l='MpServer', x=0.00, y=0.00, z=0.00], EntitySkeleton['Skeleton'/27629, l='MpServer', x=201.50, y=16.00, z=235.50], EntitySkeleton['Skeleton'/27630, l='MpServer', x=192.88, y=11.11, z=228.30], EntityCreeper['Creeper'/27633, l='MpServer', x=185.50, y=20.00, z=183.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 369116456 bytes (352 MB) / 854155264 bytes (814 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 19 mods loaded, 19 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	zeldaswordskills{1.7.10-0.2.1} [Zelda Sword Skills] (1.7.10-zeldaswordskills-0.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	arsmagica2{1.4.0.005} [Ars Magica 2] (1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	lucky{5.0.0} [Lucky Block] ([1-7-2]_Lucky_Block_v5-0-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	DamageIndicatorsMod{3.1.2} [Damage Indicators] ([1.7.2]DamageIndicatorsMod-3.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	emeraldmod{3.1.3} [EmeraldMod] (EmeraldMod 1.7.2 Forge V3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ExtraUtilities{1.1.0k} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Mantle{1.7.10-165.4bc3343} [Mantle] (Mantle_mc1.7.10_0.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	JotatosPracticalities{0.6.1} [Practicalities] (practicalities-1.7.10-0.6.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	voxelmap{1.7.10} [VoxelMap No Radar] (voxelmapNoRadar-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8610G GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MrKunji** [comment]
Update Tinkers' Construct.

**Comment by biggggg5** [comment]
Got it working! had to update forge too. Thank you!
