### ISSUE TITLE
Longbow Damage Glitch

### ISSUE THREAD

**Issue by KingR17** [SlimeKnights/TinkersConstruct#1498]
Today we updated our server to the 1.3.1 build of FTB Infinity (With 3 additional mods added, Mmm, Iguanas Tinker Tweaks (2.1.2), and Morph).

With this update, the damage values for Tinkers' tools are not working properly.

If I hover over what the damage value should be if you're looking at the GUI description, it says 147.5 hearts, and prior to the update (Which changed Tinkers' Construct to 1.8.3b from 1.8.2a), it dealt the proper damage. 

![2015-03-22_23 40 23](https://cloud.githubusercontent.com/assets/6634533/6774342/da163d74-d0ec-11e4-823e-89b242aeb788.png)

However, after the update, the bow did not deal the damage displayed in the tool's description. 

![2015-03-22_22 49 44](https://cloud.githubusercontent.com/assets/6634533/6774274/1a18120e-d0ec-11e4-89fb-fed215e588d6.png)

We would rather not roll back to 1.8.2 because of the lag using bows cause in that version, but the effectiveness of using bows is severely diminished in 1.8.3 due to this issue. I have tried using the latest version of IguanaTinkerTweaks (2.1.4) with the updated ForgeMultipart in single-player and it did not work properly either.

**Comment by bonii-xx** [comment]
Welcome to 1.8.3, where bow damage actually works properly. The tooltip from TiCTooltips just displays the old value.

**Comment by laz2727** [comment]
We still need a way to reload settings of an item. Maybe allow crafting of
incorrect tools for every tool? Or make Tool Forge recalc everything when
the item is modified with nothing?

2015-03-23 14:17 GMT+06:00 boni <notifications@github.com>:

**Comment by KingR17** [comment]
I can understand how the bows may have needed nerfing, just not quite to the extent that they seem to have been dropped to.

From that I'd like to kind of highlight/discuss the changes to better understand them if you're willing.

How did the damage calculation (bow & modifiers) + (arrow & modifiers) change between this version and the last?

Not sure if you were including the arrows and bow in your statement that just the tool-tip wasn't accurate, but the Tool Forge's description isn't accurate either.

In total, the nerf seems to have rendered longbows so they don't hold any perks (specifically damage) over shortbows anymore, save from a slight bit of zoom & durability increase.

Seeing as shooting OP'd arrows with an unmodified cobalt shortbow and an unmodified longbow only yields a 6 point damage difference, and the shortbow unmodified has a much faster draw speed which more than compensates for the 6 damage point difference.

All of the following were shot with the same arrows, same distance, just different bows.

Arrows Used (Creative Tool Modifiers were used in the making of these arrows in an attempt to find the damage point curve.)
![2015-03-23_15 56 02](https://cloud.githubusercontent.com/assets/6634533/6790518/24cb8dea-d176-11e4-87c5-d6147e8ef1b1.png)

Platinum (Shiny) Longbow with modifiers in Tool Forge.
![2015-03-23_15 56 59](https://cloud.githubusercontent.com/assets/6634533/6790463/c02cfe50-d175-11e4-8292-b5e4eace1a34.png)

Platinum (Shiny) Longbow used on Training Dummy for damage value.
![2015-03-23_15 57 12](https://cloud.githubusercontent.com/assets/6634533/6790466/cb7cdd48-d175-11e4-91aa-4a896a138441.png)

Cobalt Stock Longbow (No Modifiers) used on Training Dummy for damage value.
![2015-03-23_15 57 29](https://cloud.githubusercontent.com/assets/6634533/6790474/d4aa1a84-d175-11e4-9ed3-3d868bfdd3b8.png)

Cobalt Stock Shortbow (No Modifiers) used on Training Dummy for damage value.
![2015-03-23_15 57 43](https://cloud.githubusercontent.com/assets/6634533/6790477/da8640a4-d175-11e4-8227-e38dad5352fe.png)

Kind of wondering why/how the damage values were changed and what the benefit of a long-bow over short-bow is after this change... 

As well as why they were changed so drastically when it takes 10 thousand quartz to get to 140 points of damage, even if the Tool Forge claims it has a higher value.

Anyway, thank you for reading through this if you have; I love the mod, I'm just a bit sad to see Longbows put at such a severe disadvantage to melee weapons and brought down to Shortbow standards.

Thank you for your time, 
-KingR17

**Comment by laz2727** [comment]
That's because quartz now adds flat dmg bonus.

2015-03-24 3:17 GMT+06:00 KingR17 <notifications@github.com>:

**Comment by laz2727** [comment]
So any differences are hidden by that massive bonus.

2015-03-24 15:15 GMT+06:00 Lubimov Nikolay <laz2727@gmail.com>:

**Comment by bonii-xx** [comment]
Quartz adds damage additive instead of multiplicative. You have a shitton of quartz on there, making it literally pointless what materials you use. Distance also is factored in differently, so sniping also gives you higher damage.
Try a realistic environment and you'll see much better numbers.
