### ISSUE TITLE
Mattocks don't work on melons.

### ISSUE THREAD

**Issue by mDiyo** [SlimeKnights/TinkersConstruct#1499]
Mattocks are missing the pumpkin material, which both pumpkins and melons are made of. They should be capable of harvesting every plant.

https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/items/tools/Mattock.java#L45

Edit: The material is Material.gourd

**Comment by KamranMackey** [comment]
@mDiyo You really need to come back to working on Tinkers' Construct. Lots of people miss you.
