### ISSUE TITLE
[Crash] Resizing the smeltery can result in crash on world load.

### ISSUE THREAD

**Issue by ikkonoishi** [SlimeKnights/TinkersConstruct#1501]
Crashlog.
https://gist.github.com/ikkonoishi/7b08f128bf03016099c1

Steps to reproduce.
First build your smeltery like this
http://imgur.com/6Pb9Fml,OmhaUVV,QOCAway#0

Then extend it like this
http://imgur.com/6Pb9Fml,OmhaUVV,QOCAway#1

Then destroy this brick
http://imgur.com/6Pb9Fml,OmhaUVV,QOCAway#2

Notice that the liquids do not expand into the opened block. If you the break the end block on the smeltery the game will crash, and will crash again on launch. Looking at the nbt data of controller I saw that the integer array of melting temperatures only had two entries, but the blocklimit was 3.

**Comment by TherminatorX** [comment]
What happens if you break that block before placing the end block?

**Comment by bonii-xx** [comment]
#1649
