### ISSUE TITLE
Bouncing Pads turning alpha blending off?

### ISSUE THREAD

**Issue by critaL** [SlimeKnights/TinkersConstruct#1503]
Im playing Infinity 1.2.1

So after iv'e placed some bouncing pads on top of eachother i got a weird issue which you can see here: http://imgur.com/a/BqdiS

I posted this on the FTB subreddit and "sfPlayer" the author of "Fastcraft" said this: "That's due to some mod turning alpha blending (transparency rendering) off and not back on"

Here is the thread: https://www.reddit.com/r/feedthebeast/comments/30db29/why_do_this_happen_to_my_textures/

Do you require any more info ? If so let me know :)

**Comment by bonii-xx** [comment]
Fixed in 1.8.3

**Comment by critaL** [comment]
Awesome, thank you!
