### ISSUE TITLE
[Idea] Blast

### ISSUE THREAD

**Issue by Maelstraz** [SlimeKnights/TinkersConstruct#1505]
New modifier: Explosive (consumable: TNT or something similar) - create an explosion on hit.

Awesome for projectiles. :3
But armor with blast protection will be useful. 
Imagine Explosive Scythe or Rapier xD

Not sure about:
May or may not break blocks. Probably not best idea. Maybe split it to Explosive (for entities) and Ruining (for entities and blocks).
May or may not be upgradeable for explosion strength or radius.
May have fuse time and/or cooldown.

Should be disableable in configs to prevent griefing on non-pvp servers.

**Comment by TriforceOfKirby** [comment]
The mechanics could be similar to the blast element in the Monster Hunter series, where you have to hit the mob a few times before an explosion is triggered, or for tools breaking a few blocks. Increasing the level of the modifier could decrease the amount of hits needed between blasts.

It could be split similar to how looting and fortune are split; when put on a weapon, explosions won't break blocks, while when put on a tool, explosions will break blocks.

This could be a pretty useful modifier on tools such as a hammer for increasing the mining radius.
