### ISSUE TITLE
Tool XP applying on incorrect tool

### ISSUE THREAD

**Issue by akvgergo** [SlimeKnights/TinkersConstruct#1508]
If I use a mining tool to throw a weapon (Shuriken) the used mining tool gets the xp instead of the weapon.

**Comment by laz2727** [comment]
IguanaTweaks bug, i think.

2015-03-28 22:39 GMT+06:00 akvgergo <notifications@github.com>:

**Comment by akvgergo** [comment]
@laz2727  I reported here because Boni takes care of both mods, and I didn't find a proper issue tracker for Iguana tweaks. It really doesn't matter as long as the author knows about it :P
