### ISSUE TITLE
Dupe with crafting table

### ISSUE THREAD

**Issue by linkinkov** [SlimeKnights/TinkersConstruct#1509]
http://www.youtube.com/watch?v=LG9m8hFaf6A&feature=youtu.be

Sorry, but video on the russian language, but you can see process of dupe.

**Comment by MrKunji** [comment]
I don't see any actual dupe.

**Comment by linkinkov** [comment]
then chest been droped gui dont closed and can take diamond.

**Comment by MrKunji** [comment]
You didn't end up with an extra diamond, it is only a visual glitch.

**Comment by Adaptivity** [comment]
It's seems not a just visual glitch. He said that another guy took diamond from the chest and the author of the video took it from the chest gui too (when chest actually was broken by another player).

**Comment by linkinkov** [comment]
Okay, thats my video:
http://www.youtube.com/watch?v=AEz9M461nLk

**Comment by linkinkov** [comment]
For fixing just need propertly close chest inventory in crafting table after breaking chest

**Comment by MrHelp** [comment]
http://www.youtube.com/watch?v=xb7g1_kdXC8&feature=youtu.be
for Thaumcraft 4 this dupe give us endless blocks

**Comment by bonii-xx** [comment]
The diamond you get is clientside only. However the item frame dupes it. Funny.

**Comment by laz2727** [comment]
You can also craft it.

2015-04-02 22:41 GMT+06:00 boni <notifications@github.com>:

**Comment by bonii-xx** [comment]
Yes, they're not actually clientside, but simply stacks with size 0. That's pretty evil. :D
