### ISSUE TITLE
Tool Rods Do Not Appear In NEI

### ISSUE THREAD

**Issue by PizzaFrog** [SlimeKnights/TinkersConstruct#1510]
As the title says, tool rods do not appear in NEI. The only ones I see are from the Natura-Tinkers interaction.

Screenshot: http://gyazo.com/5470635028bb5267a3558c4e964dd988

I'm using version 1.7.10-1.8.2a

**Comment by MrKunji** [comment]
Same thing as https://github.com/SlimeKnights/TinkersConstruct/issues/1489, I guess
