### ISSUE TITLE
Arrow Hit Behaviour

### ISSUE THREAD

**Issue by KingR17** [SlimeKnights/TinkersConstruct#1511]
TC Version: 1.8.3 (1.7.10-1.8.3.build919)
Forge Version: 10.13.2.1291

Issue: Arrows bounce back after being shot, and damage you.

With the mod's functionality of having Arrows be in stacks and you can't collect dropped arrows, when arrows are fired, they still do damage to whatever they come in contact with (including you), and can't be collected. Whether this is intentional to discourage the use of bows on mobs within generally close areas or a bug, I do not know.

Tested with Longbows and Shortbows, both can result in you shooting yourself (and potentially killing yourself) if you accidentally shoot something that runs at you and you can't shoot them far enough away.

Thank you for your time,
-KingR17

**Comment by bonii-xx** [comment]
* Arrows can be picked up if you have exactly the same in your inventory
* If the arrow bounces back when you hit something that means the target was invulnerable/can't be damaged. That's vanilla minecraft.

**Comment by KingR17** [comment]
I would like to revise this bug report.

Arrows shot while flying within certain range result in death. Arrows shot as fast as possible at quarter second draw-speed do not damage you when you fire them. However, when you fly and shoot, that's a different story. With a longbow, if you're within about 10 blocks when you shoot, you get shot with your own arrow. With a shortbow, if you're within about 4-6 blocks when you shoot, you get shot with your own arrow. 

I suspect this may have to do with having enough reinforced modifiers to get Unbreakable arrows that causes this issue.

As I said above, this issue only happens when flying and within certain ranges with each bow.

Thank you for your time, as always, and have a great day,
-KingR17
