### ISSUE TITLE
Admin command for inventory

### ISSUE THREAD

**Issue by bookerthegeek** [SlimeKnights/TinkersConstruct#1512]
Hello and thank you for the wonderful mod. I do have a question for you

1. We are on a Server
 * As such, we deal with a lot of grief and theft
 * Sometimes we need to discreetly check what a person has in their inventory
2. So we were wondering if one of the following would be possible
 * Add in an OP'ed only command so that Admins can view / edit what another players has in the extra slots that tinkers adds, and their tinkers backpack.
 * Open the slots / backpack to the forge essentials API so it works with /openinv command on servers
 * Some other wonderful idea that you might have that I have not thought of.

Thank you for taking the time to read this.

**Comment by bonii-xx** [comment]
What you want is an NBT viewer or something similar.

**Comment by Razorskills** [comment]
Here is NBT-Explorer

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

**Comment by TherminatorX** [comment]
@Razorskills That's good for when the server is down, but they would need something that would work while it's running, and in-game.

**Comment by laz2727** [comment]
Ingame NBT editor then, obviously. Google it.

2015-03-31 8:13 GMT+06:00 ThermX <notifications@github.com>:

**Comment by Razorskills** [comment]
Well, the server doesn't really need to be shut down to edit someone's inventory, they just need to be offline.. But yea i see your point.

**Comment by bookerthegeek** [comment]
Thank you for taking the time to consider this.  I understand that their are additional mods that will let admins on a server do what I am asking.  We were hopping that a /command that could be easily used by our Staff Could be implamented. But I will look into other avenues including the in game not editor. 

Wonderfull mod by the way,  and I look forward to see where it goes.
