### ISSUE TITLE
Move UBC support out

### ISSUE THREAD

**Issue by Adaptivity** [SlimeKnights/TinkersConstruct#1513]
There are a better place to it: http://minecraft.curseforge.com/mc-mods/227992-ubc-ore-registrar

**Comment by Adaptivity** [comment]
@bonii-xx ?

**Comment by bonii-xx** [comment]
Not really a good idea, since it'd screw with existing worlds.

**Comment by Adaptivity** [comment]
Thanks for pointing this out @bonii-xx Forestry had removed UBC support in the latest unstable build and I thought it would be better to make same for Tcon. But after update to latest unstable all UBC ore disappeared from my test world :smile: I also pointed it to Forestry devs.
