### ISSUE TITLE
Crashing while replacing of non-metal toolpart for Mattock

### ISSUE THREAD

**Issue by Voidi** [SlimeKnights/TinkersConstruct#1515]
with the option "Deny creation of non-metal mattocks"=true the client crashes if i try to replace a toolpart with a non-metal Material

http://www.dertobi.name/~tobias/upload/Minecraft/fml-client-latest.log

**Comment by bonii-xx** [comment]
Well, why do you have a non-metal mattock with non-metal mattocks being true?

**Comment by laz2727** [comment]
Replacing WITH, afaik.

2015-04-03 15:18 GMT+06:00 boni <notifications@github.com>:
