### ISSUE TITLE
[Suggestion] make clear glass panes lie horizontal instead of vertically on casting table

### ISSUE THREAD

**Issue by Ianaver** [SlimeKnights/TinkersConstruct#1516]
I know this may not be possible, but can you possibly try to make it so that the clear glass panes lie on their side instead of standing up vertically in the casting table since it looks strange?

**Comment by bonii-xx** [comment]
d900e096d7466f57c3c08ef1e781592c50b48561

**Comment by Ianaver** [comment]
@bonii-xx oh cool! i thought that maybe some MC thing might prevent that!
