### ISSUE TITLE
The FluidStack drain() method does not check for equality of fluid types

### ISSUE THREAD

**Issue by asiekierka** [SlimeKnights/TinkersConstruct#1517]
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/smeltery/logic/CastingChannelLogic.java#L383-L387

**Comment by bonii-xx** [comment]
Ignoring the fact that casting channels are a complete derp, I think you are looking for this: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/smeltery/logic/LavaTankLogic.java#L46-L55?

At least I can't find a mention of the casting channels in the linked issue

**Comment by bonii-xx** [comment]
Can we close this now @asiekierka?

**Comment by asiekierka** [comment]
Still a bug, technically.

**Comment by bonii-xx** [comment]
I suppose. But the underlying issue why it was opened is solved I think?
