### ISSUE TITLE
Smeltery not hot enough

### ISSUE THREAD

**Issue by Gunner76th** [SlimeKnights/TinkersConstruct#1518]
I have tried with both the normal seared brick smeltery (the one with sand, gravel, clay yo make grout) as well as the advanced smeltery (the one with gravel soulsand and netherwart) and neither seems to get hot enough to smelt colored redstone into destabilized redstone. In both attempts, I was using lava as the fuel source. 

Does the smeltery accept other types of hot liquids as a fuel source such as pyrothium from Thermal Expansion?

**Comment by laz2727** [comment]
Pyrothenium? Yes, it accepts it.

2015-04-03 23:09 GMT+06:00 Gunner76th <notifications@github.com>:

**Comment by Gunner76th** [comment]
So that is required to reach the 3000c needed, thanks

**Comment by 1kili2** [comment]
ive been searching for the answer to this for ages thank you guys so much

**Comment by Routhinator** [comment]
Question - in 1.10.2 there is no liquid pyrotheum. So, what can we use in 1.10.2 to get hotter smelteries?

**Comment by KnightMiner** [comment]
If a mod adds a hotter recipe, it is on them to add a hotter fuel. As it stands no recipes in Tinkers need more heat than lava provides

**Comment by tenten8401** [comment]
Emerald blocks need more heat than lava provides.

**Comment by rswhisper** [comment]
> Question - in 1.10.2 there is no liquid pyrotheum. So, what can we use in 1.10.2 to get hotter smelteries?

There's now liquid pyrotheum in 1.10...though it doesn't seem to be accepted as a fuel.

**Comment by Favorlock** [comment]
It's not working as mentioned above.

**Comment by KnightMiner** [comment]
Pyrothium is added by Thermal Expansion. If they want it to be a fuel we have an API for them to add it.

**Comment by HerobrineLol** [comment]
Can you send link
and when i install thermal expansion my game crashes
any other way to get to 3000c??

**Comment by KnightMiner** [comment]
This issue is 4 years old, not the place to ask for help. You are free to join our discord for help debugging.

**Comment by HerobrineLol** [comment]
Might be that i have 125 mods installed
