### ISSUE TITLE
Arrow Hit Behaviour - Reinforced Modifer Glitch

### ISSUE THREAD

**Issue by KingR17** [SlimeKnights/TinkersConstruct#1520]
This is a revision to my prior post, and as my comment wasn't replied to I would assume the closed issue makes it so it doesn't give alerts. I have copied my response and am posting it as a new issue now.

Tinkers' Version: 1.8.3 (1.7.10-1.8.3.build919)
Forge Version: 10.13.2.1291
Modpack: FTB Infinity version 1.3.4 with additional mods MmmMmmMmm, Morph, and Iguanas Tinker Tweaks

Report: Arrows shot while flying within certain ranges (different bows result in different distances), result in you being hit by the arrow you're firing. Arrows shot as fast as possible at quarter second draw-speed do not damage you when you fire them if you are standing on the ground. However, when you fly and shoot, that's a different story. With a longbow, if you're within about 10 blocks when you shoot, you get shot with your own arrow. With a shortbow, if you're within about 4-6 blocks when you shoot, you get shot with your own arrow.

I suspect this may have to do with having enough reinforced modifiers to get Unbreakable arrows that causes this issue. After some testing it would appear this is true, as only arrows with the reinforced modifier result in this glitch.

As I said above, this issue only happens when flying and within certain ranges with each bow.
Visually, the arrow appears to be falling to the ground from about where you fire the bow when you shoot the arrow rather than hitting the target. The target will take damage, but the arrow doesn't fire or trail at the target and instead lands at your feet instead of at the target.

This issue is able to be reproduced and can be recorded to demonstrate if required.

Thank you for your time, as always, and have a great day,
-KingR17

**Comment by TherminatorX** [comment]
Please capture the bug in GIF format, if possible. The more idea of what happens, the better.

**Comment by KingR17** [comment]
In the first gif, I'm shooting with both longbow and shortbow. Only modifiers being Redstone on the bows for sake of gif format speed, and reinforced on the second set of arrows. The impact of the arrows hitting me is a tad difficult to see so I have a second gif of the actual instances where the arrows hit me. I'm using Draconic armour as well, so the hearts don't seem to be affected in the gif very much, but you'll see them jump and me get thrown to the side from the impact each time.

Both bows firing normal and reinforced arrows while on the ground and while flying as comparison.
![animation 3](https://cloud.githubusercontent.com/assets/6634533/6999847/88e09aa4-dbdb-11e4-812e-ea73dce8722b.gif)

Arrows hitting me specifically, both longbow and shortbow:
![animation 4](https://cloud.githubusercontent.com/assets/6634533/6999871/26b6b268-dbdc-11e4-9867-205cf7b94275.gif)

Sorry if the gifs aren't particularly high quality. I'm not a fan of the compression and getting the file-size under 10mbs was a bit of a challenge.

Thank you,
-KingR17

**Comment by KingR17** [comment]
Specifically, the second video is the glitch highlight reel. The arrow drops down and hits you, then lands in the ground when the arrow has unbreakable with the reinforced modifier. The arrow does still hit the target, as you can see by the damage value on the dummy, but you're hit in the crossfire somehow.

**Comment by bonii-xx** [comment]
Can't reproduce with only tcon and using flight from Extra Utilities. Might be your armor or some weird lag (in the latter case it'd be clientside only and the damage wouldn't be real)

**Comment by KingR17** [comment]
I will test in SSP, with the mods isolated. Right now this is on a server, and the damage is real in the sense that if I shoot with my normal bow and arrows, which have some serious modifiers on them, I kill myself from the damage and I get a death message that shows up for other players as well.

**Comment by laz2727** [comment]
That happens with vanilla bna too, btw.

**Comment by KingR17** [comment]
The vanilla bow doesn't happen in the same circumstances, or with as absolute results as the Tinkers' bows are though.

Just tested in SSP, results below.

Items used:
-Unmodified Manyullun Longbow
-Manyullun Arrows, taken from creative and modified with 10 obsidian plates for Unbreakable

Flight:
-Morph Mod, and previously used Draconic Evolution, Jetpacks from IC2, although I haven't tried Extra Utilities wings, which I will next.

Issue results when hitting a cow which was flying by were that the bug is still present, and I got hit by the arrow.
So it is still present when using Morph flight and isolating TiC.

I will try with EU now.

**Comment by KingR17** [comment]
I just tested with the same tools and shot a pig while wearing dragon wings from a relatively close distance, maybe 5 blocks diagonally, and still got hit by my own arrow. Only mods present being EU and TiC. I'm not sure why your test didn't result in having the issue unless the version of TiC is different from mine, or perhaps the forge version is causing the issue.

**Comment by bonii-xx** [comment]
I was testing with latest dev version and forge 1291, but nothing changed regarding that stuff in the TiC code so it should behave the same way. Might be a server thing, hm.

**Comment by KingR17** [comment]
I'll try with the latest dev build and that forge version later today and let you know the results. It's rather late atm, going on 1AM here, so I'll get to that this afternoon. 

It's just a bit of an annoyance with Iguanas because at some point it auto-upgrades the arrows to unbreakable so it's not as simple as just not adding the modifier to them to avoid getting hit by them. 

With the arrows I generally use, they're lethal if they hit me so it's a bit awkward to end up with death messages of me shooting myself on the server when I forget to land to shoot the bow. 

Hopefully it's fixed in the latest dev build and it's not a software/hardware issue or something, but I'll have to test this afternoon to be sure.

Thanks for your time, I'll get back to you after testing with those versions.
-KingR17

**Comment by KingR17** [comment]
Hmm, well, is the Dev build available via a download link anywhere or would that be the version that I was currently using? 

The version I have now is listed as a release on the downloads page so I'm inclined to believe that the Dev builds would be something that aren't available to the public. I can try with the dev build if it's available for downloading, if not, then that's fine too. If it's fixed in the dev build, that's good though, so either way, hopefully it works out.

Thank you,
-KingR17

**Comment by bonii-xx** [comment]
Dev builds can be found here: https://dvs1.progwml6.com/jenkins/job/TConstruct_1.7.x/

**Comment by KingR17** [comment]
Tested with the latest Dev build.

I wound up with the same issue, using the same items. 
The arrows don't damage me if they're normal, however they do if they're indestructible. For the sake of fully showing the issue, I have a dropbox link to a video that recorded the issue, and went over everything listed in the mods section, that way there isn't anything lost in translation with the GIF.

https://www.dropbox.com/s/wnp05ecvga6umm0/Tinkers%27%20Construct%20Arrow%20Bug.mp4?dl=0

I did have fastcraft in this, as you can see in the video, but I did try without it as well and the glitch was still there.

**Comment by KingR17** [comment]
Bit of an update. I'm having a similar issue with the crossbow. Whenever the reinforced trait applies to the bolts, I get shot while flying. I tried testing it in a more controlled environment, and found it wasn't an issue with bolts drawn directly from creative, but the visual effect seems to be present still. The bolt dropping to the ground where you stand or where you fly. 

The only difference being that I think the weight of the bolt may make a difference. The bolts drawn from creative were Manyullun with iron tips and feather fletching. My bolts that I usually use are manyullun tool rods, manyullun coating, and slime fletching. I was testing alternative ranged weapons and decided to go try a crossbow, and when I added reinforced, the arrows occasionally hit me, but I take it that's the percentage of times the effect is actually applied when I only have reinforced II on the bolts. 

When I tested in creative, I didn't have the same effect as many times using the default manyullun bolts. So I tried looking at differences between the two bolts and weapons, and the main difference I noticed that I thought could potentially cause the issue with one while not the other is the weight.
The manyullun + manyullun combo is lighter than the manyullun + iron combo. 
Perhaps because the bolts are lighter, they fire from a higher spot, one that's high enough that it makes contact with your own hit-box when it falls to the ground, where if it's a heavier bolt, it does not.

Arrows don't have this issue quite so much. All arrows with Reinforced to unbreaking end up hitting you if you're flying. Crossbows are more... Temperamental I guess. I'll do some testing on the side with different weights of crossbow bolts and see if that is in fact the difference, but I thought I'd give my findings so far. 

So potentially the issue affects most projectile based items with reinforced. I didn't notice any issues with projectiles that didn't use a launcher, such as knives, javelins, etc. But crossbows and bows seem to have that issue.

Not sure how helpful that is, but maybe it can help narrow down the issue to a trait that crossbows and bows both share that the reinforced modifier affects.
I'll do some weight testing with bolts later today and get back with the results.

Thank you,
-KingR17

**Comment by bonii-xx** [comment]
So far I haven't managed to reproduce the issue. :/

**Comment by KingR17** [comment]
Could it be a Java or Hardware issue?

JRE info: 
-Java version 1.8.0 update 31

PC Specs:
-i5 3.5GHz processor
-2TB HDD
-16GB RAM (4-6GB to FTB on average)
-GeForce GTX 650 Ti 2GB
-Windows 8.1 64bit

**Comment by KingR17** [comment]
I just had another person test the glitch and they had the same results as I did. They got hit by arrows fired from short and longbows, and got hit by crossbow bolts. 

I tested with a range of weighted arrows, and arrows lighter than about 6 points damage you, while anything above that level does not damage you.

Here is a video of part of the testing. 
https://www.dropbox.com/s/1xk78lc9dl62ld1/Crossbow%20Bolt%20Weight%20Testing.mp4?dl=0

You'll notice that the bolts stop damaging me after I reach the bolt that weighs 8 points. 

I generally use 5.7 point weighted bolts, and those damage you still, so it has to be somewhere between 6 and 8 where they stop damaging you. They still give an animation of dropping straight down, but they don't harm you when they're higher than 8 or so points of weight.

And the other player did test crossbow damage as well and found that that damaged them too.

I'm not sure why you're not able to replicate this issue, perhaps it's an OS or Java difference, but I hope this is helpful in finding the issue in some way. 

Thank you for your time,
-KingR17

**Comment by bonii-xx** [comment]
Okay, managed to reproduce it now, and found the reason. Basically the arrow/bolt that bounces off with reinforced CAN hit you, but only if it travels long enough. However the speed it bounces back is directly proportional to the speed it hits with. So this only happens when you shoot it with enough force for it to bounce back to where you're standing, while you're standing far enough for it to travel long enough to hit you. Phew.
I'll put an upper cap on the speed and fix the y-speed, that should prevent it from being reflected this extremely while still damaging stuff when it falls from a cliff.

**Comment by bonii-xx** [comment]
..Plus it seems to reset the position sometimes

**Comment by KingR17** [comment]
Just tested with the dev build, and it's working now=)

Thank you for sticking with it,
-KingR17

**Comment by laz2727** [comment]
Fixed in vanilla. No, really, told you it was a vanilla glitch.

https://twitter.com/Dinnerbone/status/593399207886749696
