### ISSUE TITLE
BUG-HP bar goes nuts

### ISSUE THREAD

**Issue by busterGR** [SlimeKnights/TinkersConstruct#1521]
There are a few issues with the hp display when I equip heart canisters.
1)Yellow/orange hearts don't show up, although they are 'there'. This is not very significant, just mildly annoying.
2)My hp bar freaks out whenever I go through a portal(nether, aether, end, etc) and starts changing colors. Max hp goes through the roof, to something like 64 hearts or so. Useful, but kinda game breaking. Resets when I go back to the overworld through the portal in the end. Can't define the cause, might be a mod conflict or just something about tic(most likely the first). Suspected conflict with Galacticraft/Camping mod.

Here is a list of all my the mods I have currently:
Aether II
Archimedes Ships
Bibliocraft
BigTrees
BloodMagic
ChickenChunks
Chisel2
CodeChickenCore
customrecipes
CyanosLootableBodies
EnchantingPlus
extra utilities
GalacticraftCore
GalacticraftPlanets
gilded games util
Growthcraft Apples
Growthcraft Bamboo
Growthcraft Bees
Growthcraft Cellar
Growthcraft Core
Growthcraft Fishtrap
Growthcraft Grapes
Growthcraft Hops
Growthcraft Rice
Hardcore EnderExpansion
Inventroy Tweaks
Iron Chests Mod
Java 7 Checker
Mantle
Minecraft Comes Alive
Metallurgy
Metallurgy Core
Micdoodle Core
NEI
Optifine
RadixCore
Rei's Minimap
TiC
Thaumcraft
Thaumic Upholstry
Thaumic exploration
Thaumic Horizons
Thaumic Tinkerer
Camping Mod
TiC Tooltips
Twilight Forest

**Comment by MrKunji** [comment]
There was a similar issue, it's related to Aether.

**Comment by bonii-xx** [comment]
Yup. Aether 2 as far as we know.
