### ISSUE TITLE
Comparator interaction with fluid tanks requires block updates

### ISSUE THREAD

**Issue by Hyxaru** [SlimeKnights/TinkersConstruct#1523]
When you place down a fluid tank, and a redstone comparator next to it, you asume the comparator gives a signal corresponding to the ammount of fluid inside. This is true when you place the comparator the first time. After that, it will only function when the comparator gets a block update. This kinda breaks redstone control.

**Comment by bonii-xx** [comment]
That's simply how the comparator works. No can do. /o\

**Comment by TherminatorX** [comment]
Really? Tanks don't do block updates when they get filled? I'm pretty sure BUs are how it tells command block status.

**Comment by TherminatorX** [comment]
Fix seems legit.
