### ISSUE TITLE
Smelter GUI crashing internal server and shuts down the game

### ISSUE THREAD

**Issue by Outlandishmango** [SlimeKnights/TinkersConstruct#1525]
hi there first i would like to say this mod is my favorite and i all ways use it in any of my modpacks,

The problem is that if i go into the smeltery to see how much molten metal is in there, i mouse over the little window that shows how much is in there and it crashes my game. i am not sure which crash report you will need to see as i can never make head nor tail of the things hope you will be able to help as like i said i love to use this mod for tools and weapons but at the moment i can't :/ 

EDIT: it started to do it when i put extra utillities mod in i think.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:91)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58)
	at tconstruct.smeltery.gui.SmelteryGui.func_146979_b(SmelteryGui.java:151)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:64)

-- Screen render details --
Details:
	Screen name: tconstruct.smeltery.gui.SmelteryGui
	Mouse location: Scaled: (346, 237). Absolute: (693, 549)
	Screen size: Scaled: (640, 512). Absolute: (1280, 1024). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['<PROFILE NAME>'/234, l='MpServer', x=35.84, y=73.62, z=344.76]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (170,64,192), Chunk: (at 10,4,0 in 10,12; contains blocks 160,0,192 to 175,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 654328 game time, 802104 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntitySheep['Sheep'/22400, l='MpServer', x=-5.50, y=74.00, z=368.66], EntityZombie['Zombie'/17410, l='MpServer', x=55.59, y=44.35, z=286.00], EntitySheep['Sheep'/26693, l='MpServer', x=15.47, y=68.00, z=388.75], EntitySheep['Sheep'/72, l='MpServer', x=25.07, y=71.00, z=313.07], EntitySheep['Sheep'/73, l='MpServer', x=29.50, y=71.00, z=313.09], EntitySheep['Sheep'/74, l='MpServer', x=25.08, y=71.00, z=317.78], EntitySheep['Sheep'/75, l='MpServer', x=25.89, y=71.00, z=316.52], EntitySheep['Sheep'/24151, l='MpServer', x=92.16, y=83.00, z=362.13], EntitySkeleton['Skeleton'/22104, l='MpServer', x=-13.94, y=31.00, z=357.47], EntityCreeper['Creeper'/22171, l='MpServer', x=61.50, y=10.35, z=273.50], EntityPig['Pig'/93, l='MpServer', x=63.72, y=70.00, z=361.81], EntityPig['Pig'/8225, l='MpServer', x=92.19, y=67.00, z=317.47], EntityCreeper['Creeper'/17384, l='MpServer', x=54.00, y=49.00, z=288.56], EntitySheep['Sheep'/9897, l='MpServer', x=-12.81, y=75.00, z=322.81], EntityPig['Pig'/23722, l='MpServer', x=77.50, y=79.00, z=381.31], GCEntityClientPlayerMP['<PROFILE NAME>'/234, l='MpServer', x=35.84, y=73.62, z=344.76], EntityPig['Pig'/43, l='MpServer', x=-15.13, y=71.00, z=307.09], EntityPig['Pig'/23723, l='MpServer', x=64.09, y=73.00, z=374.78], EntitySheep['Sheep'/44, l='MpServer', x=10.50, y=73.00, z=331.81], EntityPig['Pig'/45, l='MpServer', x=-11.72, y=71.00, z=367.69], EntitySheep['Sheep'/46, l='MpServer', x=-12.91, y=72.00, z=358.94], EntitySheep['Sheep'/113, l='MpServer', x=94.50, y=73.00, z=294.50], EntitySheep['Sheep'/114, l='MpServer', x=92.13, y=74.00, z=310.47], EntityZombie['Zombie'/12722, l='MpServer', x=27.78, y=42.00, z=346.16], EntitySheep['Sheep'/115, l='MpServer', x=91.19, y=65.00, z=317.47], EntityZombie['Zombie'/12723, l='MpServer', x=34.56, y=41.00, z=341.13], EntitySheep['Sheep'/116, l='MpServer', x=93.41, y=71.00, z=304.53], EntitySheep['Sheep'/22455, l='MpServer', x=12.75, y=69.00, z=379.31], EntitySheep['Sheep'/59, l='MpServer', x=1.50, y=71.00, z=295.66], EntitySheep['Sheep'/60, l='MpServer', x=14.94, y=44.00, z=356.03], EntitySheep['Sheep'/22460, l='MpServer', x=12.50, y=65.00, z=382.66], EntitySheep['Sheep'/22461, l='MpServer', x=6.47, y=74.00, z=382.34], EntitySheep['Sheep'/22399, l='MpServer', x=0.16, y=67.00, z=370.84]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by TherminatorX** [comment]
We need the entire log, but this crash usually happens when you don't have Mantle installed.

**Comment by bonii-xx** [comment]
1. Complete log
2. Sounds like you're using a forge version with the fluid issues

**Comment by RedAlex** [comment]
That bug are not fix if we use 1.7.10-Forge10.13.3.1362

**Comment by TherminatorX** [comment]
Yeah, it's the funky Forge version RWTema is requiring for EU.
I'm guessing TiC is not going to develop/support this version?

**Comment by bonii-xx** [comment]
0198ba8012afbf01bf6f89cf3b044215e9df0e04

**Comment by Outlandishmango** [comment]
that is all well and good and thanks for the reply but i am not a modder so i have no idea on how to change those things but thanks anyway i will just have to remove tinkers from my mod pack :( cheers and thanks for a brilliant mod.

**Comment by bonii-xx** [comment]
Simple: Wait until an update is released. The link to the commit is just there for versioning purpose.

**Comment by ahmet3939** [comment]
help me TİC  mod open smeltery İs Shut down server error    

 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 26.01.2017 21:43
Description: Rendering screen

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at tconstruct.smeltery.gui.SmelteryGui.func_146979_b(SmelteryGui.java:151)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:64)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at tconstruct.smeltery.gui.SmelteryGui.func_146979_b(SmelteryGui.java:151)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:64)

-- Screen render details --
Details:
	Screen name: tconstruct.smeltery.gui.SmelteryGui
	Mouse location: Scaled: (372, 137). Absolute: (745, 431)
	Screen size: Scaled: (683, 353). Absolute: (1366, 706). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['ahmet3939'/10396, l='MpServer', x=502,06, y=64,64, z=-1797,48]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-190,64,-207), Chunk: (at 2,4,1 in -12,-13; contains blocks -192,0,-208 to -177,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 562479 game time, 35802 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 49 total; [EntityMinecartChest['entity.MinecartChest.name'/76165, l='MpServer', x=530,50, y=37,50, z=-1835,50], EntityChicken['Tavuk'/76173, l='MpServer', x=465,44, y=67,00, z=-1764,47], EntityChicken['Tavuk'/76172, l='MpServer', x=457,59, y=55,00, z=-1774,41], EntityVampire['Vampir'/76559, l='MpServer', x=479,50, y=12,00, z=-1876,50], EntityMinecartChest['entity.MinecartChest.name'/76558, l='MpServer', x=478,50, y=12,50, z=-1875,50], EntityVampire['Vampir'/76561, l='MpServer', x=478,50, y=12,00, z=-1877,50], EntityVampire['Vampir'/76560, l='MpServer', x=479,50, y=12,00, z=-1875,50], EntityHorse['At'/76179, l='MpServer', x=499,28, y=64,00, z=-1773,03], EntityClientPlayerMP['ahmet3939'/10396, l='MpServer', x=502,06, y=64,64, z=-1797,48], EntityChicken['Tavuk'/76050, l='MpServer', x=428,47, y=68,00, z=-1834,47], EntitySkeleton['İskelet'/76562, l='MpServer', x=476,50, y=16,00, z=-1875,50], EntityClientPlayerMP['ahmet3939'/10396, l='MpServer', x=-240,33, y=11,62, z=-356,88], EntityChicken['Tavuk'/76195, l='MpServer', x=442,47, y=61,43, z=-1721,53], EntityChicken['Tavuk'/76194, l='MpServer', x=439,81, y=61,27, z=-1725,69], EntityItem['item.tile.dirt.default'/76213, l='MpServer', x=482,69, y=63,13, z=-1776,44], EntityChicken['Tavuk'/76085, l='MpServer', x=454,53, y=64,00, z=-1805,53], EntityCaveSpider['Mağara örümceği'/76341, l='MpServer', x=-14,63, y=-28,02, z=34,23], EntityTrail['Bilinmeyen'/21301, l='MpServer', x=502,06, y=65,62, z=-1797,48], EntityChicken['Tavuk'/76084, l='MpServer', x=460,47, y=64,00, z=-1820,41], EntityXPOrb['Tecrübe Küresi'/76596, l='MpServer', x=597,41, y=64,25, z=-1790,03], EntityChicken['Tavuk'/76471, l='MpServer', x=567,53, y=62,30, z=-1765,53], EntityItem['item.tile.dirt.default'/76214, l='MpServer', x=483,81, y=62,13, z=-1776,13], EntityChicken['Tavuk'/76473, l='MpServer', x=567,38, y=63,00, z=-1810,53], EntityMinecartChest['entity.MinecartChest.name'/76472, l='MpServer', x=560,50, y=38,50, z=-1832,50], EntityChicken['Tavuk'/76093, l='MpServer', x=445,63, y=64,00, z=-1808,56], EntityChicken['Tavuk'/76223, l='MpServer', x=558,56, y=59,00, z=-1777,44], EntityChicken['Tavuk'/76094, l='MpServer', x=443,47, y=69,00, z=-1764,44], EntityCaveSpider['Mağara örümceği'/76350, l='MpServer', x=21,05, y=-38,94, z=42,26], EntityChicken['Tavuk'/76222, l='MpServer', x=545,53, y=62,48, z=-1786,84], EntityZombie['Zombi'/76609, l='MpServer', x=505,22, y=15,00, z=-1876,00], EntityLeashKnot['entity.LeashKnot.name'/76224, l='MpServer', x=499,50, y=64,50, z=-1775,50], EntityBat['Yarasa'/76995, l='MpServer', x=463,63, y=19,00, z=-1843,69], EntitySkeleton['İskelet'/76615, l='MpServer', x=510,72, y=32,00, z=-1877,25], EntitySkeleton['İskelet'/76614, l='MpServer', x=510,63, y=32,00, z=-1874,31], EntityChicken['Tavuk'/76494, l='MpServer', x=451,72, y=64,00, z=-1852,59], EntityItem['item.tile.dirt.default'/75991, l='MpServer', x=485,28, y=62,13, z=-1773,94], EntityItem['item.tile.dirt.default'/75990, l='MpServer', x=481,75, y=63,13, z=-1773,13], EntityItem['item.tile.dirt.default'/75993, l='MpServer', x=485,06, y=62,13, z=-1775,56], EntityItem['item.tile.dirt.default'/75992, l='MpServer', x=483,63, y=62,13, z=-1773,53], EntityMinecartChest['entity.MinecartChest.name'/76120, l='MpServer', x=536,50, y=33,50, z=-1814,50], EntityChicken['Tavuk'/76507, l='MpServer', x=436,47, y=62,39, z=-1861,53], EntityItem['item.tile.dirt.default'/75994, l='MpServer', x=484,03, y=62,13, z=-1772,13], EntityChicken['Tavuk'/76509, l='MpServer', x=458,38, y=64,00, z=-1861,59], EntityChicken['Tavuk'/76508, l='MpServer', x=449,59, y=67,00, z=-1860,47], EntityMinecartChest['entity.MinecartChest.name'/76510, l='MpServer', x=565,50, y=39,50, z=-1859,50], EntityChicken['Tavuk'/76006, l='MpServer', x=441,41, y=64,00, z=-1800,44], EntityChicken['Tavuk'/76143, l='MpServer', x=539,16, y=62,36, z=-1786,53], EntityChicken['Tavuk'/76145, l='MpServer', x=446,56, y=64,00, z=-1827,47], EntityChicken['Tavuk'/76144, l='MpServer', x=441,47, y=64,00, z=-1825,47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 53727376 bytes (51 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.3.23} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.3.46} [Not Enough Items] (not-enough-items-1.7.10.jar) 
	UCHIJAAAAAAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Core{5.0.7} [BuildCraft] (_BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Builders{5.0.7} [BC Builders] (_BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Energy{5.0.7} [BC Energy] (_BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Factory{5.0.7} [BC Factory] (_BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Transport{5.0.7} [BC Transport] (_BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Silicon{5.0.7} [BC Silicon] (_BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAAAAAAA	IC2{2.2.823-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
	UCHIJAAAAAAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJAAAAAAAAA	AutoFood{59.0.0} [AutoFood] (autofood-59.0.0.jar) 
	UCHIJAAAAAAAAA	Backpack{2.0.1} [Backpack] (Backpacks-Mod (1).jar) 
	UCHIJAAAAAAAAA	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
	UCHIJAAAAAAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNpcs.jar) 
	UCHIJAAAAAAAAA	DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAAAAAAA	Easter Egg Mod{1.0} [Easter Egg Mod] (EasterEggMod V1.0.jar) 
	UCHIJAAAAAAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAAAAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.7.10-2.1.7.254} [Ender IO] (EnderIO-1.7.10-2.1.7.254.jar) 
	UCHIJAAAAAAAAA	FoodPlus{3.2rS} [§bFood Plus] (FoodPlus-1.7.2-3.2rS.jar) 
	UCHIJAAAAAAAAA	ForgeMultipart{1.1.2.332} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.332-universal.jar) 
	UCHIJAAAAAAAAA	McMultipart{1.1.2.332} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.332-universal.jar) 
	UCHIJAAAAAAAAA	hammerz{0.1.7.37} [Hammerz] (Hammerz-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	headshots{0.3} [Headshots] (Headshot-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	iChunUtil{4.0.0} [iChunUtil] (ichun-util-mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	ihouse{2.6} [iHouse Mod] (ihouse-2.6.jar) 
	UCHIJAAAAAAAAA	IronChest{6.0.60.741} [Iron Chest] (Iron Chest.jar) 
	UCHIJAAAAAAAAA	lucky{5.1.0} [Lucky Block] (lucky-block-mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAAAAAAA	Morph{0.9.1} [Morph] (morphing-mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (mrcrayfishs-furniture-mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	multihotbar{1.0} [Multi-Hotbar] (multihotbar-1.7.10-1.1.1.jar) 
	UCHIJAAAAAAAAA	ppapmod{1.4.2} [PPAP Mod] (PPAP Mod-1.7.10-1.4.2.jar) 
	UCHIJAAAAAAAAA	signpic{2.4.4} [SignPicture] (SignPicture-1.7.10-2.4.4-universal.jar) 
	UCHIJAAAAAAAAA	TConstruct{1.7.10-1.8.0.build804} [Tinkers' Construct] (TConstruct-1.7.10-1.8.0.jar) 
	UCHIJAAAAAAAAA	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) 
	UCHIJAAAAAAAAA	thaumicenergistics{0.8.9.3a-rv2} [Thaumic Energistics] (thaumicenergistics-0.8.9.3a-rv2.jar) 
	UCHIJAAAAAAAAA	corerm{1.0b} [RikMuld's Core] (TheCampingMod_2.1f.jar) 
	UCHIJAAAAAAAAA	camping{2.1f} [The Camping Mod 2] (TheCampingMod_2.1f.jar) 
	UCHIJAAAAAAAAA	treeGrowingSimulator{0.0.3} [Tree Growing Simulator 2014] (TreeGrowingSimulator2014-MC1.7.10-0.0.3-22.jar) 
	UCHIJAAAAAAAAA	vampirism{0.7.8.6} [Vampirism] (Vampirism-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJAAAAAAAAA	XaeroMinimap{1.7.7.2} [Xaero's Minimap] (xaeros-minimap-mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	ForgeMicroblock{1.1.2.332} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.332-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 9400M G/integrated/SSE2'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce 9400M G/integrated/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [FNI-Realistic-RPG-1.7.zip]
	Current Language: Türkçe (Türkiye)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by LovelyFlare** [comment]
@ahmet3939 Please make a new issue instead of commenting on a closed and unrelated dead one.  You're also using an unsupported version and not the latest 1.7.10 build.
