### ISSUE TITLE
Modded redstone-like concepts only trigger one faucet at a time on their line.

### ISSUE THREAD

**Issue by Azutte** [SlimeKnights/TinkersConstruct#1526]
[Automagy for one](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2125369-tc4-addon-automagy-automation-and-logistics-v0-22?comment=419), the dev there insists it happens in other mods. I know I've seen a person claim it happens with MFR Rednet cables, in the Tinker's Construct minecraftforum post, but I'm struggling to find their comment at the moment.

**Comment by Dustmuz** [comment]
i had a similar problem when i tried putting a Computercraft computer next to the faucets.. 
i came about this by placing a piece of normal redstone between the computer and the faucets :)

i know it doesnt "solve" the problem, but its a way around it atm

**Comment by bonii-xx** [comment]
Fixed through fix for #834
