### ISSUE TITLE
Repair issue - TC 1.8.3b

### ISSUE THREAD

**Issue by Dustmuz** [SlimeKnights/TinkersConstruct#1531]
i've made a custom pack with the new Curse voice, and ran into a problem

i can not repair tinker construct tools.

complete modlist can be found in the added picture, including version numbers
and image 2 shows a pick made of iron parts, in a tool station with an iron ingot.

Forge version: 10.13.21291
MC version: 1.7.10
![modslist](https://cloud.githubusercontent.com/assets/11715556/7103219/44478346-e09d-11e4-9ebb-5469aceedf6e.png)
![2015-04-11_22 40 34](https://cloud.githubusercontent.com/assets/11715556/7103187/27d435d4-e09c-11e4-9ec5-552ecc1ef9cd.png)

**Comment by bonii-xx** [comment]
Check your log for errors/exceptions.
Also try if it works without Tinkers Modifiers,

**Comment by Dustmuz** [comment]
i found the "Problem"
tinkers modifiers.. 

Thanks A lot for the help..
