### ISSUE TITLE
Crash with forge 1355+ when using a smeltery  

### ISSUE THREAD

**Issue by zed-hex** [SlimeKnights/TinkersConstruct#1532]
With forge 1355+ when using a smeltery it is possible to randomly crash I don’t think this bug has been reported yet. This is the crash log: http://pastebin.com/ezq5RzjK 
This crash happened with forge 1365 and the latest build of TCon

**Comment by TherminatorX** [comment]
The fix for this hasn't been released yet, but it has been reported.

Sooooo, dupe
