### ISSUE TITLE
Crash While Within Smeltery GUI

### ISSUE THREAD

**Issue by Cooolaid** [SlimeKnights/TinkersConstruct#1533]
While having the Smeltery GUI opened, I get a crash.
Sometimes, it does not do it right away, sometimes, it does it when I create a few 
templates in the smelter, then when i go back in the smeltery gui , I get hit with the crash.

Here is the crash output log.
http://pastebin.com/Lfb8pg4Z

**Comment by TherminatorX** [comment]
Dupe
Fixed in repository
