### ISSUE TITLE
Fluid changes require 1355+ but build is still at 1291

### ISSUE THREAD

**Issue by krwminer** [SlimeKnights/TinkersConstruct#1534]
Building the latest from github fails because of the change to fluids requiring Forge 1355+ when build.properties is still at 1291.

**Comment by TherminatorX** [comment]
I was going to test that comparator change, but yeah, this got in the way.

**Comment by krwminer** [comment]
A little painful, but on my local copy I put back the fluid changes and it builds fine for 1291 again. Everything I have is 1291, I have not tested 1355+ yet.

**Comment by bonii-xx** [comment]
Well, I guess this saves me the work of testing if the changes work on 1291 too. Time to increase the required version yet again.

**Comment by bonii-xx** [comment]
19bb390938d422fda2ad2b7d13281c11238aa304
