### ISSUE TITLE
Smeltery crash

### ISSUE THREAD

**Issue by RAVEMASTER1** [SlimeKnights/TinkersConstruct#1537]
Sometimes after a large server load, [Long session or just loaded up world], when I open the smeltery gui, the game crashes. Using MC 1.7.10, TiC 1.8.3b, and Forge 10.13.3.1370.

**Comment by TherminatorX** [comment]
Don't say "I crashed" and not give us the crash log. Put it on pastebin and link it here, or you will receive no help.
