### ISSUE TITLE
Applying upgrades to Tinker Tools does not happen (1.7.10-1.8.4RC1).

### ISSUE THREAD

**Issue by Cooolaid** [SlimeKnights/TinkersConstruct#1540]
Applying upgrades to Tinker Tools does not happen.
Tried it on both iron & wooden table and with Diamond, Emerald, Redstone, Lapis and Nether Quartz.
None of the resources want to upgrade the tinker tools on TConstruct-1.7.10-1.8.4RC1.jar.

http://i.imgur.com/doS2K5e.png

.
.

**Comment by bonii-xx** [comment]
It helps to have free modifiers on your tools.

**Comment by Cooolaid** [comment]
I just created the tool. 
Isnt there suppose to be 3 modifiers slots available on a new tool by what my recollection remembers?
Did you change the way modifiers are applied on brand new tools ?.

**Comment by laz2727** [comment]
Iguana Tweaks? I didn't check the screenshot.

**Comment by Cooolaid** [comment]
Damn, yes. I installed it last night to try it out for the first time. people keep recommending it,
so wanted to find out what the hype was all about.
does it change the way modifiers are applied?
I thought Iguana just adds things.

**Comment by laz2727** [comment]
Ugh. Hate to be the first to say that to you, but IT utterly rebalances TiC.

**Comment by laz2727** [comment]
As in, GT level rebalance.

**Comment by Cooolaid** [comment]
wow ok, very good to know lol 
ok, you should see the look on my face right now..... 
thank you for telling me. I appreciate it very much. :)
Now i have to hunt the net to research this. (scratching my head while panting)..lol

**Comment by laz2727** [comment]
You can try to change configs.
