### ISSUE TITLE
Compatibility crash with Necromancy following 1355

### ISSUE THREAD

**Issue by Drakray** [SlimeKnights/TinkersConstruct#1541]
http://pastebin.com/7T7cG0by
AtomicStryker told me to show this to you ( http://goo.gl/dtI6WA )
Using latest Tinkers, Forge 1369, latest Necromancy
(Tested with 1356, worse crash, might be caused by unupdated mods at the time)
Right now, I removed Necromancy, and all my other mods are compatible(or seems to be)

**Comment by TherminatorX** [comment]
Well, that points at TiC nowhere in the log. If you keep NM, but remove TiC, do you still get the crash?
(This does look a lot like a dupe issue, though)

**Comment by Drakray** [comment]
I can't say, my modpack have too many mods that depends on TC to remove
But I'll try to test

**Comment by djoveryde** [comment]
I can +1 confirm this.
Disabling Tinkers Construct cures this issue.
This is clientside. Serverside loads up fine.

http://pastebin.com/rbe97zkb

**Comment by bonii-xx** [comment]
In this case it's necromancys fault.
@AtomicStryker: You're re-registering the fluid you obtained if blood was already registered in your registry in your client-proxy. I'm not even sure why you'd have that in a client-proxy.

**Comment by AtomicStryker** [comment]
Legacy code i'll assume. Maybe it used to be a two pronged registration. But thanks for notifying me.

**Comment by bonii-xx** [comment]
Np. :)
