### ISSUE TITLE
Issue Creating Hammerhead

### ISSUE THREAD

**Issue by GEnoscyde** [SlimeKnights/TinkersConstruct#1543]
Hello all,
I'm having a problem when trying to make a stone hammerhead to use for a cast. When I put the stencil (using iguanas tweaks) and the stone in the part builder I am unable to take the hammerhead out of the slot. I try and drag it out but it snaps right back and does not consume any of the materials. Has anyone had this issue or know how to solve it? (Sorry if this is the wrong place to post this)
Thanks,
Genoscyde

**Comment by TherminatorX** [comment]
Versions and/or modpacks?
Also, check you configs

**Comment by bonii-xx** [comment]
Sync your configs with the server.
