### ISSUE TITLE
[Feature] Add shift click into crafting stations

### ISSUE THREAD

**Issue by gr8pefish** [SlimeKnights/TinkersConstruct#1545]
Would it be possible to add the ability to shift click items into the 9 slots of the crafting inventory in the crafting station? You might have to do something fancy with the extended inventory with chests so that it still goes in the crafting grid and not the chest.

Ex: shift clicking a stack of cobble from your inventory to the crafting station would put it in the first available slot, do this 9 times with 9 different stacks of cobble and you can quickly craft compressed cobble without having to drag and drop anything. 

It would be a handy feature; I would test it out myself and submit a PR, but I am busy enough as it is, sorry!

**Comment by bonii-xx** [comment]
Not really useful for the work it needs. Use NEIs recipe-fill feature or autocraft. :P

**Comment by AgentK9** [comment]
sometimes NEI does not work though.
