### ISSUE TITLE
Crashing player.dat File with broken Traveller Boots

### ISSUE THREAD

**Issue by Welzfisch** [SlimeKnights/TinkersConstruct#1546]
Hi,

we just encountered a problem with Traveller Boot's and maybe other armor pieces from TConstruct.
What happens and is recreatable:
Player wears Traveller Boots with Durability full 1035/1035 but item Status says "broken".

![2015-04-16_18 28 20](https://cloud.githubusercontent.com/assets/11981722/7186235/92df4178-e468-11e4-8777-cc2120369b89.png)

Player get hit by anything and instantaneously lose all life.
Player can't die, just got a crooked and wiggly view. 
Can't access inventory but can run etc. (Seems like stuck in dieing procedure or something)

I took a look at the player.dat file by using NBT explorer -> result: 
AbsorbtionAmount is status NaN
And HealF is NaN probably due to AbsorptionAmount is NaN
Setting them to
AbsorbtionAmount: 0
HealF: 20
sets player back to life and everything is ok again.

**Comment by TherminatorX** [comment]
Kill those boots.
TiC items are never meant to have enchantments on them.

**Comment by bonii-xx** [comment]
Yeah, those boots look pretty broken (no pun intended). Where did you get them from?

**Comment by Welzfisch** [comment]
We dublicated them in an energy condenser from projectE and enchanted them with books in an anvil XD

Yeah we are trying hard to break the game sometimes :DD

**Comment by bonii-xx** [comment]
Yeah, so the energy conderser messes with the NBT. Not my fault! :P
