### ISSUE TITLE
Crash when mouse over the liquid on smeltery

### ISSUE THREAD

**Issue by lhenrique03** [SlimeKnights/TinkersConstruct#1548]
I'm with the version: 1.8.3b of tinkers' construct. I open the smeltery controller, mouse over the liquid spot and I had this crash http://pastebin.com/7Be0xXYm. Modlist: http://pastebin.com/tky4Wyf6. Youtube video: https://www.youtube.com/watch?v=jt-xKeeN74Q

**Comment by bonii-xx** [comment]
Not enough info.

**Comment by TherminatorX** [comment]
Looks like a dupe to me., in which case it's fixed in the repository.

**Comment by bonii-xx** [comment]
You're using a forge version with the liquid changes but an incompatible tinkers version. Downgrade forge to 1291 or use the alpha.
