### ISSUE TITLE
Traveller's Glove Crashing when attempting to add modifiers

### ISSUE THREAD

**Issue by taiyoko** [SlimeKnights/TinkersConstruct#1550]
Using 1.8.3b

When placing glove in a crafting station or tool forge, game crashes to desktop.

Crash report: http://pastebin.com/6dUsh4eE

**Comment by TherminatorX** [comment]
Looks like Inter-Mod from that second line. Do you still crash when Thermal Smeltery is removed?

**Comment by taiyoko** [comment]
Yeah, looks like it was Thermal Smeltery. When I went to its page it seems
to have been an issue fixed in a newer version than came in my pack, so
I'll see if that clears it up.
