### ISSUE TITLE
 [INCOMPATIBILITY] with Mine and Blade dual wield

### ISSUE THREAD

**Issue by treds34** [SlimeKnights/TinkersConstruct#1551]
your mod is a very helpful my friends server were using it was awesome the weapons and other tool was nice although we use it in mine and blade until now we update it we cant equip any weapons from it.

**Comment by MrKunji** [comment]
Swords works fine in the sword slot.

**Comment by bonii-xx** [comment]
TCon weapons are compatible with M&B.
