### ISSUE TITLE
chrash upon exiting the smeltery

### ISSUE THREAD

**Issue by boydstar** [SlimeKnights/TinkersConstruct#1556]
I am sorry if this has been posted before. I couldn't find it.

The issue:
From time to time when I exit my smeltery my game will just close. no chrash message nothing. however it did generate a [chrash log](http://paste.ee/p/o4jV8) 

please help because it is very annoying.

**Comment by TherminatorX** [comment]
Fixed in latest version. Please update to 1.8.4

**Comment by boydstar** [comment]
Oh I'm sorry I thought I had the latest one,
thanks for helping
