### ISSUE TITLE
[Feature] TE Strongboxes compatibility with the crafing station

### ISSUE THREAD

**Issue by KaseiFR** [SlimeKnights/TinkersConstruct#1559]
Hi,

I really like the interaction between vanilla chests and the tool station. No more buffering material in my inventory:)
Could it be possible to make it compatible with modded chests, such as the TE strongboxes?

**Comment by laz2727** [comment]
Very hard to do iirc. Although i would like smeltery-like automatic slots
and compat for every iinventory.

2015-04-22 17:13 GMT+06:00 KaseiFR <notifications@github.com>:

**Comment by Razorskills** [comment]
IronChests would also be very nice too.

**Comment by TherminatorX** [comment]
See #1087

**Comment by bonii-xx** [comment]
Thanks Therminator, I was looking for that issue but couldn't find it anymore. :D
