### ISSUE TITLE
Materials and You vol 2 Rendering issue

### ISSUE THREAD

**Issue by Nomago** [SlimeKnights/TinkersConstruct#1560]
I have a similar issue to #1363 except I have not had OptiFine installed on this instance at all. I'm using Forge 1291 and have made sure I am using TiCon 1.8.3b, and Mantle 0.3.2. I can not figure out why my pack is doing this. I realize this issue has been fixed in the past, but I can't figure out why its happening in my case. Thanks for any help!

![2015-04-22_09 01 36](https://cloud.githubusercontent.com/assets/11981596/7279246/56203736-e8cf-11e4-9e9f-09aba4d9c469.png)

>Mods List:

>AppleCore-mc1.7.10-1.1.0.jar
appliedenergistics2-rv2-beta-26.jar
Baubles-1.7.10-1.0.1.10.jar
BetterAnvil-4.0.0.0-alpha-1.jar
BiblioCraft[v1.10.2][MC1.7.10].jar
BigReactors-0.4.3A.jar
buildcraft-6.4.8.jar
Carpenter's Blocks v3.3.5 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.16-universal.jar
Chisel2-2.3.10.37.jar
ChiselFacades-1.7.10-2.10-cricket.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.2-262.jar
Decocraft-v1.12b_1.7.10.jar
EnderIO-1.7.10-2.2.8.367.jar
EnderStorage-1.7.10-1.4.5.27-universal.jar
ExtraCells-1.7.10-2.2.65b102.jar
ExtraTiC-1.7.10-1.0.3.jar
extrautilities-1.2.4.jar
fastcraft-1.21.jar
FastLeafDecay-1.7.10-1.0.jar
funky-locomotion-1.7.10-beta-5a.jar
growthcraft-apples-1.7.10-2.1.0.jar
growthcraft-cellar-1.7.10-2.1.0a.jar
growthcraft-core-1.7.10-2.1.0a.jar
growthcraft-grapes-1.7.10-2.1.0.jar
growthcraft-hops-1.7.10-2.1.0.jar
growthcraft-rice-1.7.10-2.1.0a.jar
industrialcraft-2-2.2.710-experimental.jar
InGameInfoXML-1.7.10-2.8.1.80-universal.jar
InventoryTweaks-1.58-147.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.1a_1.7.10.jar
LunatriusCore-1.7.10-1.1.2.21-universal.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-8.1.1.225.jar
MekanismGenerators-1.7.10-8.1.1.225.jar
MekanismTools-1.7.10-8.1.1.225.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
MineTweaker3-1.7.10-3.0.9C.jar
MobiusCore-1.2.5_1.7.10.jar
ModTweaker 2-0.7.5.jar
mystcraft-1.7.10-0.11.4.00.jar
neiaddons-mc1710-1.12.5.17.jar
NEIIntegration-MC1.7.10-1.0.7.jar
NetherOres-[1.7.10]2.3.0-12.jar
NotEnoughItems-1.7.10-1.0.4.95-universal.jar
OpenBlocks-1.7.10-1.4.jar
OpenModsLib-1.7.10-0.7.jar
Opis-1.2.5_1.7.10.jar
Pam's HarvestCraft 1.7.10g.jar
Ruins-1.7.10.jar
SimplyJetpacks-MC1.7.10-1.4.1.jar
Stackie-1.7.10-1.5.1.31-universal.jar
TConstruct-1.7.10-1.8.3b.jar
ThermalDynamics-[1.7.10]1.0.0-122.jar
ThermalExpansion-[1.7.10]4.0.1-182.jar
ThermalFoundation-[1.7.10]1.0.0-81.jar
TiCTooltips-mc1.7.10-1.2.3.jar
twilightforest-1.7.10-2.3.5.jar
UpdateCheckerMod-1.7.10.jar
VeinMiner-1.7.10_0.26.1.unknown.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.2.jar
Wawla-1.2.1_1.7.10.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar

>CodeChickenLib-1.7.10-1.1.3.127-universal.jar
ForgeMultipart-1.7.10-1.1.2.331-universal.jar

>EJML-core-0.26.jar

**Comment by Nomago** [comment]
So I did track this down to something in Opis 1.2.4+, I don't know what it is, but Opis 1.2.3 works fine, but either of the 2 newer versions cause this issue. So I'm not sure if it is anything that can be fixed in TiCon at all.

**Comment by bonii-xx** [comment]
I remember this being caused by some other mod, however I don't know which one. It's not Opis.

**Comment by Nomago** [comment]
It must be an interaction between Opis and something else then, because if I remove only Opis, this issue is gone.

**Comment by KosmosPrime** [comment]
I am having the same issue. After some experimenting, I have found a way to reproduce it: In MC 1.7.10 install Forge build 1395, Mantle 0.3.2, TConstruct 1.8.5 and Mapwriter 2.1.2. I believe that the renderer for the guide allows another component to display, which does not clean up the OGL context properly (or at least not how TC expects to get it back). I am not sure where the issue actually is, but I am guessing it's somewhere in "mantle.client.gui.GuiManual".

**Comment by Robijnvogel** [comment]
Informed ProfMobius:
https://bitbucket.org/ProfMobius/opis/issue/114

**Comment by TherminatorX** [comment]
@Robijnvogel The issue has been tracked down to Mapwriter, not Opis. Prof is not to blame here.

**Comment by Robijnvogel** [comment]
Mapwriter is part of Opis, isn't it?

**Comment by Wulfson** [comment]
Mapwriter is a separate mod...Opis has a tweaked copy of Mapwriter packaged with it

**Comment by Vectron** [comment]
i dont realy think this is a bug on the mapwriter part.
it enables blend befor drawing the map, and disables it when it's done.

in my opinion tic should do the same when writing the book.

on a site node, in the latest version of resonant rise i have the same bug even when mapwriter isnt installed.

**Comment by Adaptivity** [comment]
Confirmed to be fixed.
Using: Forge 1492, Tinkers 1.8.6b, Mantle 0.3.2a, Mapwriter 2.1.7. I didn't test Opis but it should work too.
