### ISSUE TITLE
[Feature] Knapsack item blacklist config: ex Backpacks

### ISSUE THREAD

**Issue by Razorskills** [SlimeKnights/TinkersConstruct#1562]
Hello, I was hoping to request a config option for blacklisting an item from going into the Knapsack. We have 2 mods that add backpacks in our pack and both have config options to blacklist items from the backpacks, so then people cannot have bags inside of bags, just doesn't make sense.

But I haven't found a way "yet" to not allow any of the other backpacks inside of the knapsack.

**Comment by bonii-xx** [comment]
There wont be any further changes done on the armor stuff for 1.7.10
