### ISSUE TITLE
[Idea] Stone chests

### ISSUE THREAD

**Issue by Gotolei** [SlimeKnights/TinkersConstruct#1563]
We have stone ladders and stone torches already, and they're useful in their own places - particularly when wood is scarce or you're down in the mines and have limited resources to work with.

Stone chests would be functionally identical to vanilla chests, except made of cobblestone and with a different texture. Handy if you want to drop off all that extra cobble/dirt/gravel/etc without dumping stack entities all over the ground, and no need to bring logs either.

Would unfortunately still need a 3x3-capable crafting table of some sort, but then again so do vanilla chests.

Bonus feature: tessellation with vanilla chests (possible already with trapped chests, but they require iron and an extra crafting step)

**Comment by bonii-xx** [comment]
No. Also it'd conflict with the furnace recipe.
