### ISSUE TITLE
[Idea] Wrench tool

### ISSUE THREAD

**Issue by Gotolei** [SlimeKnights/TinkersConstruct#1564]
Built with a wrench head and tool rod.

Normally, functions as a basic melee weapon a la frying pan, battlesign etc.
When applicable, functions as a technical wrench similar to the crescent hammer.

If getting a wrench too early on is seen as a balance issue, perhaps have wrench-like actions use durability.
Or maybe make it tier 2 with the head requiring three ingots and using a tough tool rod.

**Comment by TherminatorX** [comment]
Each tech mod comes with their own version of "the wrench." TiC doesn't have use for one, so it wouldn't make sense for one to be put in. It would be a bit like Biomes o' Plenty putting one in. (The only use I can think of one would be changing casting channel orientation)

Also, there is a version of the TE's crescent hammer made specifically for hitting stuff in addition to being a wrench.

**Comment by laz2727** [comment]
Changing casting channel orientation, drain orientation, TMech blocks orientation.
And TiC already has gears it has no use for.

**Comment by bonii-xx** [comment]
No inherit use. Better suited as an addon.
