### ISSUE TITLE
[Feature] Use the Forge Block Break Event for all Tools.

### ISSUE THREAD

**Issue by krwminer** [SlimeKnights/TinkersConstruct#1566]
It would be nice if all the Tools used the Forge Block Break Event. Especially for the Hammer, Scythe, Excavator, LumberAxe and BattleAxe.

**Comment by krwminer** [comment]
Looks like you do use the Events. It is bypasing MyTown2. I will figure out why and repost the issue if needed.

**Comment by bonii-xx** [comment]
There was an old version of Tinkers that didn't. The newer ones should all work. #941

**Comment by krwminer** [comment]
The version I am using is TConstruct-1.7.10-1.8.2a.jar.

For the excavator, the first block I break with it registers a BlockBreakEvent, but for the 8 surrounding blocks I do not get any BlockBreakEvent. Your code at first glance looks like it should provide those BlockBreakEvents...  Still looking into this...

**Comment by krwminer** [comment]
Looks like it should be calling ForgeHooks.onBlockBreakEvent() in HarvestTool.java but when I set a breakpoint on ForgeHooks.onBlockBreakEvent() it only shows the first block break before entering breakExtraBlock(). If I set a breakpoint on ForgeHooks.canHarvestBlock() it stops there for everyone of the 8 blocks surrounding the initial block break.

Something just aint right...

Could you have a look into this?

**Comment by krwminer** [comment]
You are correct. Old version. Thank you. :)
