### ISSUE TITLE
[Suggestion] melting down tools to basic metals (all metal tools only)

### ISSUE THREAD

**Issue by Prophious** [SlimeKnights/TinkersConstruct#1567]
basically the tool can be smelted in the smeltery and give back whatever was used in the tool, but if there is any non-metal part in the tool it will not work 

but when smelting down an all metal there should be some loss to the materials used even if the tool was at 100% durability--- maybe allowing tools/armor to be smelted while they are damaged giving less and less based on what was used to make each piece, like remove mb's  and since each ingot is 144 mb it might not be easy to figure out the correct amount, but it could be rounded then floored to full intinger 

or can have the tools be completely broken down to tool parts, like pickaxe head, binding and tool rod for a normal pickaxe

idk... maybe this is a good idea, but maybe then again its not

**Comment by bonii-xx** [comment]
No.
