### ISSUE TITLE
Update to 1.8+?

### ISSUE THREAD

**Issue by Prophious** [SlimeKnights/TinkersConstruct#1568]
perhaps updating the mod to version 1.8+ i would prefer 1.8.3+ for best performance, i know its alot of coding, but any plans for a version update?

tbh i think this is one of the most popular mods and if this one goes to a newer version of minecraft others will follow suit.... so plz update it if you can

**Comment by AgentK9** [comment]
already in progress

**Comment by Prophious** [comment]
oh awesome, may i ask what version you are going to
