### ISSUE TITLE
render issue

### ISSUE THREAD

**Issue by ZzMCPEzZ** [SlimeKnights/TinkersConstruct#1569]
hello all.

I have found a little render bug:
![2015-04-24_11 20 18](https://cloud.githubusercontent.com/assets/11927133/7316070/ebcf6b1c-ea73-11e4-98c3-bf404d951a6c.png)

**Comment by covers1624** [comment]
It is not a render bug.
This happens because the cast texture doesn't have the exact same cut out as a shovel head.

**Comment by ZzMCPEzZ** [comment]
ok but, why that append only cobalt ?

**Comment by covers1624** [comment]
The shovel head must be a bit smaller with cobalt.
