### ISSUE TITLE
[Suggestion] Forge 1291 Compatible

### ISSUE THREAD

**Issue by Dream-Master** [SlimeKnights/TinkersConstruct#1570]
I see other Mods like Forestry be compatible to old and new Version of Forge (Liquid Update)
Is it possible to add this Support to your new 1.8.4 Version ?

**Comment by bonii-xx** [comment]
No. Use 1.8.3b for <1251 and 1.8.4a for >1291.

**Comment by Dream-Master** [comment]
Any reason ?

**Comment by bonii-xx** [comment]
Because there's no reason to.
