### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by flamin9001** [SlimeKnights/TinkersConstruct#1571]
http://paste.ubuntu.com/10890072/

**Comment by flamin9001** [comment]
help fix it please

**Comment by MrKunji** [comment]
Update Mantle and use a stable version of TCon.
Also remove Optifine, just in case.

**Comment by flamin9001** [comment]
Where should I get the stable version of TCP

**Comment by flamin9001** [comment]
Tcon

**Comment by MrKunji** [comment]
http://www.curse.com/mc-mods/minecraft/tinkers-construct#other-downloads
Use 1.8.3b until you update your Forge, or it may crash.

**Comment by flamin9001** [comment]
I updated both the tcon and forge

**Comment by flamin9001** [comment]
nothing happens now my minecraft wont open after i press play
