### ISSUE TITLE
Incorrect animation on chisel use

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1572]
When using a chisel, it does the eating animation. It does apply "change" to block. 
It would also be nice if the chisel would "go back" to beginning of changes, instead of it being a "one way" change. (I end up with blocks that I don't want and I can't change them)

**Comment by TherminatorX** [comment]
Change the title and focus of your issue and it might make it past the first look.
The chisel using the eating animation is just that: an animation.
However, I would like the idea of a "cycle" or something, to undo a change if there's some client-sever desync.

**Comment by Wulfson** [comment]
The chisel using the eating animation is working as intended.

**Comment by TheQuadShot** [comment]
lol, Your kidding me, right!?

**Comment by laz2727** [comment]
Nope. This is the correct animation.

**Comment by TherminatorX** [comment]
@TheQuadShot Use the second part of your issue, or close this one and open a new one based on it. The first part only makes long-term users roll their eyes, no offense meant.
