### ISSUE TITLE
Molten aluminum brass renamed to aluminium brass in code

### ISSUE THREAD

**Issue by Adaptivity** [SlimeKnights/TinkersConstruct#1575]
@bonii-xx by this [commit](https://github.com/SlimeKnights/TinkersConstruct/commit/3508fe5c09b7d91a67a0ce757b239ed2c4795890) you changed *aluminumbrass* to *aluminiumbrass*. So, now the name of fluid is missing in-game, you should either change it back to aluminumbrass or change this [line](https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tinker/lang/en_US.lang#L642) to aluminium. You decide :)

**Comment by TherminatorX** [comment]
http://en.wikipedia.org/wiki/Aluminium#Etymology
Basically, the extra "I" was suggested by an anonymous person because "aluminum" didn't sound as classical and so that the ending would conform with 52% of the other recently discovered elements. Go figure.
I'll put in my two cents and say I prefer the first option, due to personal, well, preference.

**Comment by laz2727** [comment]
I'd say you should do both.

2015-04-27 23:48 GMT+06:00 ThermX <notifications@github.com>:

**Comment by Adaptivity** [comment]
It just unlocalized name guys... it's not an OreDict entry or something.

**Comment by TheQuadShot** [comment]
My 2cents (fwiw) It should be consistent, If  you have an aluminum ore/ingot/block you should have molten aluminum

**Comment by bonii-xx** [comment]
So that's where it went.. thanks Adaptivity!

**Comment by Adaptivity** [comment]
Also, a question, when Pig Iron recipe was changed? It's now 16 mb of iron, 640 mb of emerald and 80 mb of blood for... 16 mb of Pig Iron? Is it intentional? Or some mod messed this up? (I have no ITT installed) The book still suggest an old recipe then...

**Comment by TheVikingWarrior** [comment]
The books are a bit outdated, for example in the book "materials.xml" you still have the description of bow and arrows, and the black one says that the smeltery can only be 3x3
