### ISSUE TITLE
Chisel should "cycle" in case of client/server de-sync

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1576]
It would nice if the chisel would "cycle" (or something), to undo a change if there's some client/sever de-sync.

**Comment by squeek502** [comment]
The desync is actually an issue with vanilla item usage. [More info can be found here](https://github.com/SlimeKnights/TinkersConstruct/issues/545#issuecomment-40641978). Just thought I'd mention that.

**Comment by TheQuadShot** [comment]
Thanks! that was very helpful. I think the “work around” is that the chisel does cycle. Thus giving me a chance to fix the block and not have to remove/replace the block or have to make more brown stone to fix it.
