### ISSUE TITLE
Not an issue, asking a question (again)

### ISSUE THREAD

**Issue by SgtPunishment** [SlimeKnights/TinkersConstruct#1578]
I've added tinkers compatibility to soul shards, this includes melting and casting of soulium, as well as enabling tinkers tools getting the soul stealer enchantment, but I am at a loss where to put the effect textures, I'm hoping someone can shed some light on this for me.

**Comment by bonii-xx** [comment]
You have to register it with the TConsttructClientRegistry: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/client/TConstructClientRegistry.java#L51-L79
Basically you have to tell each tool "use *this* to render effect X". Best check its usage in the source.

Close this issue once you got it please.

**Comment by SgtPunishment** [comment]
Thanks, I will once I've got it working!

Sent from my Fire

On 29 April 2015, at 09:08, boni <notifications@github.com> wrote:

You have to register it with the TConsttructClientRegistry: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/client/TConstructClientRegistry.java#L51-L79
Basically you have to tell each tool "use this to render effect X". Best check its usage in the source.

Close this issue once you got it please.
