### ISSUE TITLE
[Request] Register berry bushes/berries in the ore dictionary

### ISSUE THREAD

**Issue by ganymedes01** [SlimeKnights/TinkersConstruct#1580]
How about something like: bushX and berryX
"X" being the material it's made of.
e.g. bushCopper and berryCopper

**Comment by bonii-xx** [comment]
Hm, I thought we had that once. Must've been in Steelworks. The berries should also be oredicted as ingots.

**Comment by laz2727** [comment]
They are already nuggets iirc.

2015-04-29 14:03 GMT+06:00 boni <notifications@github.com>:

**Comment by bonii-xx** [comment]
67ed8f4fc4afa132c69d46ff6a029cf633a8b96a and fb3b662128364052a39f20ecba276267cb5679cd
