### ISSUE TITLE
Bug with heart canister.

### ISSUE THREAD

**Issue by yetshadow** [SlimeKnights/TinkersConstruct#1581]
Hi I recently added the mod to my server and I've found a bug.

If you are equiped with some heart canister, and then you change the world, your hp who came from heart canister will been added one more time, so you will have (2x) the amount that you have earned with those canister.

Ex; You have 10 red & green canister, they give you 40HP.
      Then you go on an other world.
      You feed up.
      And now you'll have more HP.

My players have 3000+HP right now.

**Comment by bonii-xx** [comment]
Aether2's fault.
