### ISSUE TITLE
Forge Dependency

### ISSUE THREAD

**Issue by khionu** [SlimeKnights/TinkersConstruct#1583]
TC requires Forge 10.13.3.1384, and I have 10.13.3.1395, but it's still giving an issue.... shouldn't such a minor version difference not matter?

Screenshot: http://gyazo.com/276df5e85f569405617f96812c643f55
FML Log: http://pastebin.com/KLM9Hpkj

**Comment by squeek502** [comment]
From the log:
> `[19:21:31] [Client thread/INFO] [FML/]: MinecraftForge v10.13.3.1378 Initialized`

**Comment by khionu** [comment]
I apologize..... this is very strange. I downloaded a fresh copy of the Forge Installer just yesterday.... Thank you for your help.

**Comment by khionu** [comment]
Oh, xD I just realized my issue. I downloaded the Forge Installer for the Server, but then I copied the "bin" folder from one modpack to another. Just absentmindedness xD
