### ISSUE TITLE
Crash with vanilla comparator on smeltery

### ISSUE THREAD

**Issue by mazze84** [SlimeKnights/TinkersConstruct#1586]
When a vanilla comparator is attached to a smeltery drain and you break the controller the game crashes with a nullpointer exception. Makes the world unusable because the same error happens again if the world is reloaded.

Happend on AS2 with Version 1.8.4a

Full crashlog:
http://pastebin.com/Wq1TCnzN

**Comment by TherminatorX** [comment]
Remove the drain with a world editing tool (MCEdit) and it should be playable again.
This is only a post-fix, an ounce of prevention is worth a pound of cure.
