### ISSUE TITLE
Travelers glove will accept  redstone upgrade forever

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1588]
I surround  the glove with blocks of redstone in a crafting station, it will then give the haste buff and stop accepting blocks, however if I surround it with redstone (not blocks) it will continue to accept it.

**Comment by TherminatorX** [comment]
Screenshot please?

**Comment by TheQuadShot** [comment]
![2015-04-30_16 26 59](https://cloud.githubusercontent.com/assets/11265900/7424442/dd999a90-ef55-11e4-9a60-ea0ead153044.png)

**Comment by TheQuadShot** [comment]
![2015-04-30_16 29 18](https://cloud.githubusercontent.com/assets/11265900/7424457/15295aa4-ef56-11e4-82f5-bbfef918ebce.png)

**Comment by TherminatorX** [comment]
Can we see it in a tool forge, to check the upgrades?

**Comment by Adaptivity** [comment]
Second screenshot even doesn't have the result item... Also, which Tcon version?

**Comment by TheQuadShot** [comment]
Cannot reproduce after re-log

**Comment by bonii-xx** [comment]
Put it in a tool forge and you'll see that it has in fact a limit and modifiers. :P

**Comment by TheQuadShot** [comment]
I do try to make sure I re-pro on a version that only has TC installed (and any dependencies). This only happened on this install (which is the only one with this version installed).

Mantle-1.7.10-0.3.2.jar
TConstruct-1.7.10-1.8.4a.jar
Forge Mod Loader version 7.10.130.1395 for Minecraft 1.7.10

Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, 
installed at <Dir>\.minecraft\Install\runtime\jre-x64\1.8.0_25


btw the screenshots show exactly what I said was happening. I went through 4 stacks of redstone blocks, and 16 stacks of redstone. When I re-logged and dropped the glove into a toolforge it showed 186/200 redstone. So I must have had some weird de-sync thing happening.

**Comment by bonii-xx** [comment]
As I said.. put it in a tool forge/station to see the modifiers.
