### ISSUE TITLE
Smeltry becomes an invalid structure

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1589]
I have a valid smeltry, however if snow gets into the smeltry it becomes an invalid structure, even if it has molten material in it.

**Comment by SamRaven2** [comment]
That's probably intended behavior. Try putting a roof on the smeltery.

**Comment by TheQuadShot** [comment]
If it were empty I would agree, however if it has molten material in it, it shouldn’t

**Comment by bonii-xx** [comment]
The internal blocks of a smeltery have to be free, and also have to be kept free. Usually the light from the lava tanks prevents it anyway. You'll have to fix this manually.
