### ISSUE TITLE
Entering "End Dimension" causes crash.

### ISSUE THREAD

**Issue by SalmonSays** [SlimeKnights/TinkersConstruct#1590]
A player entered an End portal and caused a server crash- while the server can be restarted successfully to be played on in other dimensions, any attempts of the same player to log in or any other players to enter the End cause a similar crash. I am assuming this is associated with a similar TConstruct hiccup I saw connected to a Nether portal on a different issue ticket, but I figure it's worthwhile to post this along with my crash report to be safe. It's my hope there's a way to fix this without wiping the dimension- any help would be greatly appreciated.

I figure this has something to do with a TConstruct arrow:
"at tconstruct.library.entity.ProjectileBase.onHitEntity(ProjectileBase.java:223)
  at tconstruct.library.entity.ProjectileBase.updateInAir(ProjectileBase.java:468)"

Full Crash Report: http://pastebin.com/raw.php?i=hbb9gKaB

Thanks Kindly

**Comment by TherminatorX** [comment]
2 things: 
1) Why the heck is cofh trying to put fishing stuff on an arrow!?
2) You can remove the arrow entity with a world editor, and it should work fine.

**Comment by bonii-xx** [comment]
Looks like something remapped IDs incorrectly in your world. Remove the entity with a wold editor.
