### ISSUE TITLE
obtaining glass arrow suggestion.

### ISSUE THREAD

**Issue by HardInk** [SlimeKnights/TinkersConstruct#1591]
from the moment I read the tool tip I liked the idea of a rare arrow type that could only be obtained by a master glass maker. I read in another issue that you never found a good way to create or supply the arrows in survival that was interesting. Well I thought maybe I could make a suggestion. My suggestion is this; What if you made a villager work bench, specifically for certain weapons and arrows. You could make the table and put it under a faucet, like a casting bench, and a tinkers villager would have to be near by to craft the arrows. You could even script it so that the villager would sit at the faucet and pour the glass himself, kind of how in bibliocraft named entities are forced to sit in chairs to type at typewriters.

I like glass arrows and do not wish to see them perish as the mod develops. Thank you for reading.

**Comment by bonii-xx** [comment]
There were a few more problems with it. They wont be obtainable because of those.

**Comment by HardInk** [comment]
Darn
