### ISSUE TITLE
1x1x1 smeltery dosent form

### ISSUE THREAD

**Issue by simsonmeno** [SlimeKnights/TinkersConstruct#1593]
Im using version mc1.7.10_1.6.0d40.1
picture of setup: http://tinypic.com/r/x5c8z5/8
the bottom one is seard brick.

**Comment by laz2727** [comment]
The square hole of the drain should be inside iirc.

2015-05-02 16:46 GMT+06:00 simsonmeno <notifications@github.com>:

**Comment by bonii-xx** [comment]
1.6.0d40 doesn't have 1x1x1 smelteries.
