### ISSUE TITLE
Copper, Aluminum and Tin do not generate in Superflat underground

### ISSUE THREAD

**Issue by donqixot** [SlimeKnights/TinkersConstruct#1596]
Copper, Aluminum and Tin do not seem to generate in Superflat world underground. Confirmed using latest version 1.7.10-1.8.4a or version 1.7.10-1.8.3b. Once I use default or large biomes type, ore generation is normal. Are there any config setting which can be changed?

**Comment by laz2727** [comment]
Do vanilla ores generate in the superflat? I'm pretty sure they don't.

2015-05-03 17:05 GMT+06:00 donqixot <notifications@github.com>:

**Comment by donqixot** [comment]
Yes, vanilla ores (coal, iron, gold, diamonds, lapis, redstone) are all there. I use standard "overworld" settings "2;7,59x1,3x3,2;1;village,biome_1,decoration,stronghold,mineshaft,dungeon", I only removed lakes and lava lakes from settings.

**Comment by laz2727** [comment]
Do other modded ores spawn?

**Comment by donqixot** [comment]
To test just Tinkers Construct, I removed all other mods. But yes, when I added Minechem, it generates Uranium underground.

**Comment by donqixot** [comment]
When I add Metallurgy4, it creates it's own Copper and Tin, but no Aluminum as it doesn't exist in Metallurgy. Other mods generate their ores too, MagicCrops generates essence ore, biome'o'plenty generates amethyst etc. TiC's gravel ores on the surface are generated normally.

**Comment by bonii-xx** [comment]
Indeed, the worldgen is exempt from superflat. I suppose this should be a config option.
