### ISSUE TITLE
[request for a Minor build] Can you do a Release with Thaumcraft aspects on TiCon nuggets?

### ISSUE THREAD

**Issue by Azutte** [SlimeKnights/TinkersConstruct#1597]
I've got a weird crash in [another mod](https://github.com/BluSunrize/WitchingGadgets/issues/6) that MIGHT be fixed by this happening? I believe the dev said so, anyway; and the only other possible fix is Azanor "completely rewriting" a system in Thaumcraft, which I'm told isn't going to happen.

**Comment by bonii-xx** [comment]
Tcon currently doesn't support aspects.
