### ISSUE TITLE
Feature Request - Destabilized Redstone and Energized Glowstone

### ISSUE THREAD

**Issue by CroComeT** [SlimeKnights/TinkersConstruct#1600]
I wanna if you can add to from destabilized redstone in casting basin you get redstone block and from energized glowstone you get glowstone.
And same for casting table like type of cast and than energized glowstone or destabilized redstone.
I'm playing on direwolf20 and on forum they sayed to i request it here.

**Comment by bonii-xx** [comment]
No real point in doing that.

**Comment by SamRaven2** [comment]
Also as a note @CroComeT, that feature would be something team CoFH would need to add since the liquids are from their mod.
