### ISSUE TITLE
Need [Help!] TiCon Server with several other mods + plugins error

### ISSUE THREAD

**Issue by ItsMeCrazy** [SlimeKnights/TinkersConstruct#1602]
I used bukkit GUI and here is all my error log.
I would like to know what might fix this error or is this just okay, or etc.

8:31:37 PM [warning]  [ForgeModLoader] The coremod worldcore.asm.WCFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
8:31:37 PM [warning]  [ForgeModLoader] The coremod biomesoplenty.asm.BOPFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
8:31:37 PM [warning]  [ForgeModLoader] The coremod tconstruct.preloader.TConstructLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
8:31:42 PM [warning]  Mod BiomesOPlenty is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.1
8:31:44 PM [warning]  The mod id FlansMod attempted to register channels without specifying a packet handler
8:31:51 PM [javastacktrace] 	at tconstruct.util.player.TPlayerHandler.buildStickURLDatabase(TPlayerHandler.java:420)
8:31:51 PM [javastacktrace] 	at tconstruct.util.player.TPlayerHandler.<init>(TPlayerHandler.java:403)
8:31:51 PM [javastacktrace] 	at tconstruct.TConstruct.preInit(TConstruct.java:161)
8:31:51 PM [javastacktrace] 	at java.lang.reflect.Method.invoke(Unknown Source)
8:31:51 PM [javastacktrace] 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
8:31:51 PM [javastacktrace] 	at java.lang.reflect.Method.invoke(Unknown Source)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
8:31:51 PM [javastacktrace] 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
8:31:51 PM [javastacktrace] 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
8:31:51 PM [javastacktrace] 	at java.lang.reflect.Method.invoke(Unknown Source)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
8:31:51 PM [javastacktrace] 	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
8:31:51 PM [javastacktrace] 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
8:31:51 PM [javastacktrace] 	at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
8:31:51 PM [javastacktrace] 	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
8:31:51 PM [javastacktrace] 	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
8:31:51 PM [javastacktrace] 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:92)
8:31:51 PM [javastacktrace] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
8:31:51 PM [javastacktrace] 	at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
8:31:52 PM [warning]  **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
8:31:52 PM [warning]  The server will make no attempt to authenticate usernames. Beware.
8:31:52 PM [warning]  While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
8:31:52 PM [warning]  To change this, set "online-mode" to "true" in the server.properties file.
8:31:55 PM [warning]  Could not find itemResource
8:31:55 PM [warning]  Thaumcraft not detected.
8:32:02 PM [warning]  [WorldEdit] 
8:32:02 PM [warning]  [NoCheatPlus]  Check for updates and support at BukkitDev: http://dev.bukkit.org/server-mods/nocheatplus/
8:32:02 PM [warning]  [NoCheatPlus]  Development builds (unsupported by the Bukkit Staff, at your own risk): http://ci.md-5.net/job/NoCheatPlus/changes
8:32:02 PM [warning]  [NoCheatPlus] Could not set up native access for the server-mod (git-MCPC-Plus-jenkins-MCPC-Plus-164-243 (MC: 1.6.4)). Please check for updates and consider to request support.
8:32:02 PM [warning]  [NoCheatPlus] Bukkit-API-only access: Some features will likely not function properly, performance might suffer.
8:32:03 PM [warning]  [Lockette] Craftbukkit build unrecognized, please be sure you have build [2502] or greater.
8:32:03 PM [warning]  [ClearLag] mob-range requires you to use bukkit v1.7_r4 (1.7.10)
8:32:09 PM [warning]  [NoCheatPlus] The block breaking data is incomplete, default to allow instant breaking:
8:32:09 PM [warning]  --- Missing entries -------------------------------
8:32:09 PM [warning]  * MISSING 160(X160 / IGN_PASSABLE) 
8:32:09 PM [warning]  * MISSING 161(X161 / IGN_PASSABLE) 
8:32:09 PM [warning]  * MISSING 162(X162 / IGN_PASSABLE) 
8:32:09 PM [warning]  * MISSING 163(X163 / IGN_PASSABLE) 
8:32:09 PM [warning]  * MISSING 164(X164 / IGN_PASSABLE) 
8:32:09 PM [warning]  * MISSING 165(X165 / IGN_PASSABLE) 
8:32:09 PM [warning]  * MISSING 166(X166 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 167(X167 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 168(X168 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 169(X169 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 174(X174 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 176(X176 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 177(X177 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 178(X178 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 179(X179 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 180(X180 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 200(X200 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 201(X201 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 202(X202 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 252(X252 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 253(X253 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 254(X254 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 255(X255 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 700(X700 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 701(X701 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 702(X702 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 703(X703 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1467(X1467 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1468(X1468 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1469(X1469 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1470(X1470 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1471(X1471 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1472(X1472 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1473(X1473 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1474(X1474 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1475(X1475 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1476(X1476 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1477(X1477 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1478(X1478 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1479(X1479 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1481(X1481 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1482(X1482 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1483(X1483 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1484(X1484 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1485(X1485 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1486(X1486 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1487(X1487 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1488(X1488 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1489(X1489 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1725(X1725 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1726(X1726 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1727(X1727 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1728(X1728 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1729(X1729 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1920(X1920 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1921(X1921 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1922(X1922 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1923(X1923 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1924(X1924 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1925(X1925 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1926(X1926 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1927(X1927 / IGN_PASSABLE) 
8:32:10 PM [warning]  * MISSING 1928(X1928 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1940(X1940 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1941(X1941 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1942(X1942 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1943(X1943 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1950(X1950 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1951(X1951 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1952(X1952 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1953(X1953 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1955(X1955 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1956(X1956 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1960(X1960 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1961(X1961 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1962(X1962 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1970(X1970 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1971(X1971 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1972(X1972 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1973(X1973 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1974(X1974 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1975(X1975 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1976(X1976 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1977(X1977 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1978(X1978 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1979(X1979 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1980(X1980 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1981(X1981 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1982(X1982 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1983(X1983 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1984(X1984 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1985(X1985 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1986(X1986 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1987(X1987 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1988(X1988 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1989(X1989 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1990(X1990 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1991(X1991 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1992(X1992 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1996(X1996 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1997(X1997 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1998(X1998 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 1999(X1999 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2000(X2000 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2001(X2001 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2006(X2006 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2008(X2008 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2009(X2009 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2013(X2013 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2014(X2014 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2015(X2015 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2016(X2016 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2017(X2017 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2018(X2018 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2025(X2025 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2026(X2026 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2027(X2027 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2028(X2028 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2030(X2030 / IGN_PASSABLE) 
8:32:11 PM [warning]  * MISSING 2032(X2032 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2034(X2034 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2242(X2242 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2243(X2243 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2244(X2244 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2245(X2245 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2246(X2246 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2247(X2247 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2248(X2248 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2249(X2249 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2250(X2250 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2251(X2251 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2252(X2252 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2253(X2253 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2254(X2254 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2255(X2255 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2290(X2290 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2291(X2291 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2401(X2401 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2402(X2402 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2403(X2403 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2404(X2404 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2405(X2405 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2406(X2406 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2407(X2407 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2408(X2408 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2409(X2409 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2410(X2410 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2411(X2411 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2412(X2412 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2413(X2413 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2414(X2414 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2415(X2415 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2416(X2416 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 2417(X2417 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3186(X3186 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3187(X3187 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3188(X3188 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3189(X3189 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3190(X3190 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3191(X3191 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3192(X3192 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3195(X3195 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3196(X3196 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3197(X3197 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3198(X3198 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3199(X3199 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3200(X3200 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3201(X3201 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3202(X3202 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3203(X3203 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3204(X3204 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3205(X3205 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3206(X3206 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3207(X3207 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3208(X3208 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3209(X3209 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3210(X3210 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3211(X3211 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3212(X3212 / IGN_PASSABLE) 
8:32:12 PM [warning]  * MISSING 3213(X3213 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3214(X3214 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3215(X3215 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3216(X3216 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3217(X3217 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3218(X3218 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3219(X3219 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3220(X3220 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3223(X3223 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3225(X3225 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3227(X3227 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3228(X3228 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3229(X3229 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3230(X3230 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3231(X3231 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3232(X3232 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3233(X3233 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3235(X3235 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3237(X3237 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3238(X3238 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3239(X3239 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3240(X3240 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3241(X3241 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3242(X3242 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3243(X3243 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3244(X3244 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3245(X3245 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3246(X3246 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3247(X3247 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3249(X3249 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 3250(X3250 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 4093(X4093 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 4094(X4094 / IGN_PASSABLE) 
8:32:13 PM [warning]  * MISSING 4095(X4095 / IGN_PASSABLE) 
8:33:10 PM [warning]  DSCT: socket closed

**Comment by TherminatorX** [comment]
If you don't have any problems playing, it's likely fine.

**Comment by bonii-xx** [comment]
a) We don't support bukkit
b) This looks like a pretty old version, which we don't support either
c) The error listed there is nothing to worry about

**Comment by ItsMeCrazy** [comment]
Thanks for the info.
I almost lose my mind because of that error. :3 Especially TiCon was included.
Thank you very much everyone :)
