### ISSUE TITLE
[Feature Suggestion] Added utility buttons for crafting station.

### ISSUE THREAD

**Issue by SamRaven2** [SlimeKnights/TinkersConstruct#1603]
So I had an idea for two extra "buttons" that could be added to the crafting station. 

The first would be a clear button, which would simply send all the items in the crafting grid back to the player inventory (or as many as can fit). 

The second is a rotate button. Clicking it would rotate the outer 8 items in the crafting grid 1 space clockwise. This would help significantly if you mix up the corners and sides of recipes (such as machine frames from Thermal Expansion or blast furnace bricks from Railcraft).

It this sounds like a good idea, I would be willing to code it myself. I just figured it would be best to check if it was a worthwhile addition before starting.

**Comment by TherminatorX** [comment]
I know I have been annoyed when I've forgotten an ingredient that needs additional crafting, and the current crafting GUI is being used. AE has this feature in their crafting terminals, and I enjoy it.
I don't think any mod has ever done a "rotate" thing, though. Would be interesting to see.

:+1: the "clear," but a hesitant :+1: on the rotation

**Comment by bonii-xx** [comment]
Sounds OK overall, however I'm currently having a feature-freeze and am only fixing major things anymore. I can only accept things if they are sure to cause no problems down the road, aka being side effect free.

**Comment by SamRaven2** [comment]
I doubt it should cause any problem, both features would only be moving itemstacks around in already existing inventory slots. I don't plan to add or remove any slots, so the slotIDs won't change from what they are. Unless there's some other issue that it might cause that I'm unaware of (entirely possible) I'll go ahead and start working on adding it.
