### ISSUE TITLE
Client running out of Memory during startup

### ISSUE THREAD

**Issue by ajthemacboy** [SlimeKnights/TinkersConstruct#1606]
Here's the part of the log with the memory error: http://pastebin.com/aVkqb8EC

I've allocated up to 5 gigabytes with no success. My only guess is that it's Tinker's Construct since that's what's in the log.

Here is my modlist: http://pastebin.com/j2u2uWBp

I've tried with Forge 1395 through 1403 and they all have the same error.

Thanks for your help!

**Comment by TherminatorX** [comment]
Does everything work when you remove, say, 5 other mods?

**Comment by ajthemacboy** [comment]
You mean binary testing? I haven't tried that yet, but I assume this isn't a known issue then?

**Comment by TherminatorX** [comment]
Oh no, clients running out of memory has been an issue since forever. It's not any modder's fault, though, it's players bogging down their computers with too many "heavy" mods.

However, if you are getting this issue with only a handful of mods, well within the 1 gig limit, then there could be an error.

**Comment by bonii-xx** [comment]
You need more permgen, not memory.

**Comment by ajthemacboy** [comment]
I'm using Java 8... permgen was removed, right? And so there's no way to allocate more? I have 8GBs of ram, I tried allocating 6 and it still didn't work.

**Comment by bonii-xx** [comment]
No you're not. :)

**Comment by ajthemacboy** [comment]
Well I feel dumb...

No matter how hard I try, Java 7 just will not uninstall on linux! I blame Canonical. 

Thanks for your help!

**Comment by bonii-xx** [comment]
You're welcome. Just leave the permgen parameter in by default. If it's using J8 it will simply be ignored.
