### ISSUE TITLE
NullPointerException rendering TinkersConstruct armour

### ISSUE THREAD

**Issue by AtomicBlom** [SlimeKnights/TinkersConstruct#1608]
Not too sure where to post this to so I'll cross post.

Issue: The following error gets repeated every frame rendered on the title screen when a certain entity is selected. (I'm not sure which one, it didn't render at all)

https://gist.github.com/AtomicBlom/f5aaa8e466cc709cb934

Full startup log including the first two exceptions are available here: https://gist.github.com/AtomicBlom/b65974bf22ad849bc302

Also posted on bspkrsCore here: https://github.com/bspkrs/bspkrsCore/issues/19

**Comment by mDiyo** [comment]
To be very clear: This happens on the title screen before any world loading or server joining has happened.

**Comment by bonii-xx** [comment]
Alex prevented the error with 1a818f6698f24515aea55a49022001c79b0f2fe4
