### ISSUE TITLE
Crash when viewing material stats in NEI

### ISSUE THREAD

**Issue by Simon04090** [SlimeKnights/TinkersConstruct#1611]
If I want to view the material stats of a single item in NEI it doesn't crash but if you click on the pickaxe to view the stats of all available materials it crashes: http://pastebin.com/N03JabA1

**Comment by bonii-xx** [comment]
One of your mods adds a material that is not getting registered correctly.

**Comment by Simon04090** [comment]
That's probably ExtraTiC then, I will test if it still happens without it and then report it there. Closing this for now...
