### ISSUE TITLE
Crash when checking Lava amount inside Smeltery Controller

### ISSUE THREAD

**Issue by Elvarion** [SlimeKnights/TinkersConstruct#1614]
Well the topic says it all :p
Crash report
http://pastebin.com/dN8Bq33d

**Comment by Adaptivity** [comment]
Update Tinkers

**Comment by Elvarion** [comment]
A new version literately came like 40 min ago lol
I always check my mods every day in the morning and in the evening after closing the server.
Will update, thanks :)

**Comment by Adaptivity** [comment]
1.8.4 is out in April 19. You have 1.8.3b

**Comment by Elvarion** [comment]
Must have placed the wrong version when creating the new server pack >.<
