### ISSUE TITLE
1.8 TODO, Adaptivity Edition

### ISSUE THREAD

**Issue by Adaptivity** [SlimeKnights/TinkersConstruct#1615]
1) Tool Station/Forge should have own (independent, unique, custom) strings for tools.
2) Modifier names should be splitted from data tags(?). Allowing less hacky translation.
3) Everything should be reloadable on the fly. If user changed MC language in-game books, ability names (when modifier applied on tool), mining levels should change their localization to this language if available.
At this point, tool localization should be more dynamic since if you apply modifier with English language chosen, ability name (*Durability +500* etc) will never change its localization.
4) Stuff made from different wood (Barricade, Part Builder etc) should be easy-to-add. 1.7 woods support should be added too.

**Comment by mDiyo** [comment]
This is not a TODO, this is a suggestion.
