### ISSUE TITLE
Crashes galore

### ISSUE THREAD

**Issue by ghostrider2539** [SlimeKnights/TinkersConstruct#1617]
Just installed the mod and when i loaded up the game it just crashed said that the compatibility patch was missing for a mod i didn't have and kept doing it so i went back and i managed to get i n the first time and when i opened the book. after 3 pages it crashed saying that it was render window issue 

Could it be my mods i have installed. i have
Damage Indicator
Archimedes ships
Biblio Craft
Carpenters blocks
Chisel
Codechickencore (for NEI)
Coroutil (for tropicraft)
Flans mod
Fossils and Archeology revival
Galacticraft
Galacticraft Planets
micdoodlcore
NEI
Zans minimap

So could it be any of these or have i just got a bad download

**Comment by laz2727** [comment]
Log?

**Comment by ghostrider2539** [comment]
nevermind i fixed it i had my profile on the wrong forge version
