### ISSUE TITLE
Issue on Fresh Spawn Into New World

### ISSUE THREAD

**Issue by stephen-netu** [SlimeKnights/TinkersConstruct#1618]
On a server, Forge 1.7.10 (forge-1.7.10-10.13.3.1403-1.7.10-universal.jar).  No items other than the Tinkers' start book.  User tries to break a block and is kicked from Minecraft outright back to the launcher.  This is his crash log:

http://pastebin.com/Jzux2m68

Let me know what other information I can provide, thank you!

**Comment by TherminatorX** [comment]
The Forge version you gave does not match the one in the crash log. Have the user update Forge to at least the version you gave.

**Comment by stephen-netu** [comment]
I bet that would do it.  ;)  Thanks a lot!
