### ISSUE TITLE
[Addon developping] Strange item behaviour

### ISSUE THREAD

**Issue by elix-x** [SlimeKnights/TinkersConstruct#1619]
I hope this is not wrong place to ask this, sorry if it is...

Ok, so i'm doing an addon for tinkers construct, and i met strange behaviour:
If i for example set TinkerTools.chisel to new instance of another class that extends Chisel (original class), item is untextured and has -1 and nulls in description... Even if i copy all code from Chisel to this class, same thing happens...

Thanks for help, if you have any questions - just ask...

**Comment by mDiyo** [comment]
You are violating the property of encapsulation that TConstruct depends on to do its work. You can't just go around replacing tools with extended copies of themselves because the system wants the original. You'll need to replace them with something else.
