### ISSUE TITLE
[Minor] smeltery issue with tanks (annoying) 

### ISSUE THREAD

**Issue by Ianaver** [SlimeKnights/TinkersConstruct#1620]
This issue is more of a nuisance and annoying than a major bug, smeltery only extracts/reads from one tank at a time. It would be nice if two or more tanks could be known by the smeltery at a time so you can see the true stats of lava combined and have full utilization of tanks. Then again, this probably won't ever be fixed because of the "Feature Freeze"....

version of the mod used: 1.8.5*

*This issue existed since mod versions from minecraft 1.6.4

**Comment by bonii-xx** [comment]
Not a bug.

**Comment by Ianaver** [comment]
@bonii-xx oh....

**Comment by bonii-xx** [comment]
No/Yes. The smeltery always works on 1 tank, it will however switch to the next tank in the structure once the current one is empty. The GUI always only displays the current tank.

**Comment by laz2727** [comment]
Smeltery is in need of another rewrite tbh. It's mostly hardcoded, so this
will take about as much time as making a good one in the rework branch, and
i prefer that.
