### ISSUE TITLE
Seared Bricks and Applied Energistics 2 Spatial IO

### ISSUE THREAD

**Issue by JigglesTheFett** [SlimeKnights/TinkersConstruct#1621]
Hello!

I recently discovered that the seared bricks as part of a smeltery would not be moved by the spatial IO system in Applied Energistics 2. It'll take the controller, the tanks, the drains, etc. Just not the bricks. I didn't test it with the 'brown' bricks, just the 'black' ones.

I originally posted this issue on the AE2 tracker, but was told it is most likely an issue on your end:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1455#issuecomment-102339426

**Comment by laz2727** [comment]
Bricks weren't TEs last time i checked.

2015-05-15 23:54 GMT+06:00 JigglesTheFett <notifications@github.com>:

**Comment by TherminatorX** [comment]
@laz2727 MC Edit says otherwise.
![capture](https://cloud.githubusercontent.com/assets/7256249/7664577/1ad5cbb8-fb54-11e4-93ad-f3bb994b401d.JPG)
Besides, the issue still remains that the bricks would be left behind.
