### ISSUE TITLE
Cant Rename Tools

### ISSUE THREAD

**Issue by WindFreaker** [SlimeKnights/TinkersConstruct#1624]
Say im repairing or adding a modifier to an existing tool, but then i decide to change its name, I cant.
It behaves like i could, and i remember being able to at one point (i think)

**Comment by MrKunji** [comment]
Put a Name Tag in a modifier slot, then apply the name in the Tool Forge's text box.

**Comment by WindFreaker** [comment]
Hahaha thanks.
