### ISSUE TITLE
Client side crash. I have most recent tinkers and forge

### ISSUE THREAD

**Issue by Syndicate1259** [SlimeKnights/TinkersConstruct#1625]
http://pastebin.com/eRqUNduA

**Comment by Syndicate1259** [comment]
I tried looking for a solution but no luck.

**Comment by bonii-xx** [comment]
You got a problem. You'll have to fix it.

**Comment by TherminatorX** [comment]
AKA not a TiC issue

**Comment by MrKunji** [comment]
By the look of it, the version of Tinkers' Defense you use is outdated.

**Comment by Syndicate1259** [comment]
Yea it was a me problem. I fixed it

**Comment by Syndicate1259** [comment]
Thanks for the help
