### ISSUE TITLE
Stone Ladders have 0 hardness

### ISSUE THREAD

**Issue by ProgrammerHero** [SlimeKnights/TinkersConstruct#1626]
Stone ladders have 0 hardness and as a result will break immediately if punched.  If you set the hardness manually in the constructor then it will behave properly, but when I tried that the ladder dropped nothing when broken.  Part of the problem may be caused by StoneLadder defining its own blockMaterial which is masking the value it inherited, so the material may not be properly set/used (unknown).

**Comment by bonii-xx** [comment]
I actually like them that way.
