### ISSUE TITLE
inventory tweaks+tool forge crash

### ISSUE THREAD

**Issue by Ianaver** [SlimeKnights/TinkersConstruct#1629]
when testing some stuff I have found that after placing a TCon tool forge, opening the GUI and shift clicking the goggles in caused immediate render crash.... worked earlier without mods not sure why it does it when other mods are installed... could be inv tweaks but I am not entirely sure, will test to see...

pastebin: http://pastebin.com/6dxiHmNq

(version of TCon; 1.8.5)

Edit 1: strangely enough, the issue disappears if the GUI is opened and the item is shift clicked without the incompatible mods in a different world making this one a tough one to diagnose...

Edit 2: upon further examinination I have determined that inventory tweaks is part of the problem as it is a combination of that mod and another unknown that produces the issue...

The following is a picture with all of the mods I have tested and found to work without crashing:
![working mod set](https://cloud.githubusercontent.com/assets/8153290/7742145/e8293eda-ff3f-11e4-9fc2-39597cab62e0.PNG)

If needed, I can provide the full mods folder to make diagnosis easier (maybe)

**Comment by bonii-xx** [comment]
The item is missing its NBT. You either didn't obtain the goggles through a proper way, or something killed its NBT.

**Comment by Ianaver** [comment]
oh ok.... I will obtain it normally and see if I can reproduce it if not, I will close this

**Comment by Ianaver** [comment]
so I guess that if you try to give your self "Infinity" amount of the goggles it breaks the NBT making it crash the game because minecraft doesn't know what to show! That also means that inventory tweaks is NOT the culprit!
