### ISSUE TITLE
Molten liquids got stuck in a dead end of Casting Channel.

### ISSUE THREAD

**Issue by AnrDaemon** [SlimeKnights/TinkersConstruct#1630]
Please consider the following setup:
![2015-05-21_16 35 45](https://cloud.githubusercontent.com/assets/6532485/7748740/cc88776e-ffcf-11e4-947f-c245345192e6.png)

When you pour liquids from central faucet, all 3 basins are filled… as long as you have more than 3 blocks worth of liquid in the shaft.

When you have exactly 3 blocks of liquid, you will never be able to cast all 3 basins at once, because, quite surprising, the Casting Channel is, in fact, represent 4 different, unconnected volumes. When liquid got into one of them, you can't get it back to any other, even if you disconnect the relevant end of a channel. Only way to finish smelting is to sink the liquid into something like portable tank and carry it over the the basin that missing last bit of material to finish casting.

The problem is exactly these four separate volumes. Why four? Why not one? the problem would have been nonexistent, if there were only one volume. Or at least redirect the material into some other end, when the end with material is disconnected from whatever it was attached to.

**Comment by bonii-xx** [comment]
Casting channels are a derp. Don't use them if you can avoid it.

**Comment by AnrDaemon** [comment]
I appreciate your acknowledgement, but it hardly helping the issue. Is there any other way to multiplex the casting channel?

**Comment by bonii-xx** [comment]
Not really. Using any pipe thath can transport liquid usually works.
I guess you could potentially try making a circle, but I doubt that'd work any better.

**Comment by AnrDaemon** [comment]
That kind of limiting my options then... :/
