### ISSUE TITLE
Switching between games with different games mess the mod

### ISSUE THREAD

**Issue by AnrDaemon** [SlimeKnights/TinkersConstruct#1632]
Switching between different games with different tinker equipment available to character mess the UI and keys until you reequip the items/click relevant tabs.

I.e. in one (remote, in my case) game character have belt(active at the time of logoff), in another (local) - knapsack.
Switching from "Knapsack" game to "Belt" game:
* the ability to change hotbar slots is blocked. Have to re-equip the belt to fix it;
* the knapsack tab is present in the inventory UI until you click it (then it go away).

**Comment by TherminatorX** [comment]
Versions?

**Comment by AnrDaemon** [comment]
TCon 1.8.3b, I can reproduce the effect.
With 1.8.5 I can only test between local games, but it seems to be gone.
Can you please check with network game too?

**Comment by bonii-xx** [comment]
Everything in the armor tab is not getting synced with the server, or at least only on a very basic level. That's why you experience that behaviour.
However armor stuff wont get fixed.

**Comment by AnrDaemon** [comment]
Can you please explain "won't get fixed"? A link would suffice.

**Comment by bonii-xx** [comment]
Current version is final. 1.8 is getting a nearly complete rework. Armor stuff is experimental.
