### ISSUE TITLE
Occasional client crash when casting after using a Modtweaker script

### ISSUE THREAD

**Issue by tgstyle** [SlimeKnights/TinkersConstruct#1633]
Here is the crash
https://gist.github.com/tgstyle/7152d1d170ceef09a9df

The script can be found on this link

https://github.com/jaredlll08/ModTweaker2/issues/144

Using latest 1.8.5 of the mod.

**Comment by mDiyo** [comment]
This is entirely the fault of Mine/ModTweaker. The scripts do not always load properly.
