### ISSUE TITLE
Javelin Moss upgrade not repairing

### ISSUE THREAD

**Issue by Watchful1** [SlimeKnights/TinkersConstruct#1636]
If you make a javelin, add some moss and melee attack a mob, it does not auto repair. If you throw one of the javelins, it does replenish the ammo as expected.

Tinkers Construct: 1.8.5

I did not attempt to replicate the issue in isolation, but it seems fairly straightforward. Here are the tinkers addons installed if it might be useful.
ExtraTiC: 1.4.4
Iguana Tinkers Tweaks: 2.1.5

**Comment by bonii-xx** [comment]
Everything working as intended.
