### ISSUE TITLE
Smeltery Inventory Crash

### ISSUE THREAD

**Issue by MrNation12** [SlimeKnights/TinkersConstruct#1638]
When using the smeltery, if you shift click items in the game crashes or if the items finish smeling while you have the GUI open, the game crashes. 

Log: https://drive.google.com/file/d/0B2fprUXOfjyCWWVpZ01ib1hnZjQ/view?usp=sharing

**Comment by TherminatorX** [comment]
And it doesn't leave a crash log?
(BTW, put the logs on pastebin or use Gist, Drive doesn't allow online viewing)
