### ISSUE TITLE
BaneOfPigs(question)

### ISSUE THREAD

**Issue by expendableminer** [SlimeKnights/TinkersConstruct#1639]
i was searching through the code but nowhere could i find anything about bane of pigs, except for 2 references in the lang file, it went to tool.baneofpigs but nowhere in the tools class can i find it. so i was wondering excactly where it is then and whether you can edit its damage

**Comment by bonii-xx** [comment]
The Bane of pigs is a hardcoded creative items. It is neither obtainable nor editable. It does not use material stats for its damage.
