### ISSUE TITLE
Arrows will not break when shot.

### ISSUE THREAD

**Issue by talonos2** [SlimeKnights/TinkersConstruct#1641]
I cannot seem to get arrows to break when hitting terrain.

To reproduce:

-Pull most recent build from github, Gradlew setupdecompworkspace, Gradlew runclient.
-Singleplayer world, survival mode, cheats on (for NEI)
-Make an arrow from paper arrowhead, sugarcane body, leaf fletching. Break chance will be listed as 660%.
-Fire it at the ground with a slime longbow. The arrow will not break, and can be collected freely.
-Also works with bronze arrowhead, sugarcane body, leaf fletching. (79% break chance, but 10/10 arrows fired can be collected)
-Also works with paper arrowhead, sugarcane body, feather fletching.
-Also works with paper arrowhead, stick body, leaf fletching (150% break chance)
-I have never seen an arrow break without hitting a mob.

Arrows breaking when hitting mobs seems to work as intended.

**Comment by talonos2** [comment]
Found the issue: 

 - Arrow hits terrain: goes into ArrowEntity.onHitBlock
 - Line 52 of ArrowEntity.onHitBlock: Calls super.onHitBlock
 - Line 172 of ProjectileBase.onHitBlock: defused is set to true.
 - Line 55 of ArrowEntity.onHitBlock: If defused is true, return without calling the arrow break code.

Any idea what the correct fix would be? I'm not sure what the purpose of the defused flag is for.

**Comment by Amaxter** [comment]
pls fix soon m8

**Comment by bochen415** [comment]
feex it pls

**Comment by Amaxter** [comment]
https://youtu.be/nuHfVn_cfHU

**Comment by bonii-xx** [comment]
Not relevant anymore in TiC2
