### ISSUE TITLE
Minecraft Crashes upon Interaction with the Smeltery

### ISSUE THREAD

**Issue by FluffyGT** [SlimeKnights/TinkersConstruct#1642]
I have been using Tinkers Construct for a while in a small, private modpack with no issues. I have then succeded in building a functioning smeltery and upon interaction with the controller, the game crashes.
My sibling has also tried the smeltery, and it worked up till the point where he placed an ore/object inside to smelt.
The only fix is to destroy the controller so that the player can log in again and move freely.
I am using MC Version 1.7.10, Forge Version 10.13.3.1403, with Tinkers Construct version 1.6.0d40.1 and Mantel Version 0.3.1.
I have included an image if the first lines of the crash report (I couldnt upload the entire thing...)
I hope this helps, and I hope you continue creating the great mods that you create! 
Thanks.
![crash report 4 tinkers construct](https://cloud.githubusercontent.com/assets/12647477/7866481/bc811cb6-0567-11e5-89b0-3d5c38470706.png)

**Comment by TherminatorX** [comment]
Update Tinkers. In case you haven't heard, @bonii-xx is the new dev and he has his own forums page here:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638-tinkers-construct

**Comment by FluffyGT** [comment]
Thanks SOOO Much!
I did not know that the Dev had changed forums and I greatly apreciate the quick response!
Kind Regards!
