### ISSUE TITLE
Clear glass pane's have visual inconsistency at top and bottem

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1645]
![2015-06-03_06 17 21](https://cloud.githubusercontent.com/assets/11265900/7961400/393e8dda-09bc-11e5-9b33-42d434b41dff.png)

**Comment by TheQuadShot** [comment]
This may be related. my cursor is on the same piece of glass from each side, the first one I'm facing west. The string of glass is 17 blocks long and does the same thing on the other end.
![2015-06-03_19 26 30](https://cloud.githubusercontent.com/assets/11265900/7975747/8f5a586a-0a26-11e5-8925-e1cffb92b2ea.png)
![2015-06-03_19 26 37](https://cloud.githubusercontent.com/assets/11265900/7975751/99ed2866-0a26-11e5-918a-015db57d8e3d.png)

**Comment by bonii-xx** [comment]
That issue is as old as the glass panes themselves and nobody wants to touch that rendering code. No plans on fixing it.
