### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by Asiangamer125** [SlimeKnights/TinkersConstruct#1646]
All of my tools, no matter what material they're made of, be it wood or manyullyn, have 100 durability. It's not a glitch with the durability counter on minecraft. I know this because everything breaks after 100 uses. It's nothing more than an inconvenience, but I'd like it to be fixed regardless. Any help is appreciated. Thank you

**Comment by MrKunji** [comment]
Which version of TCon are you using?

**Comment by Asiangamer125** [comment]
1.7.2

**Comment by MrKunji** [comment]
Test in 1.8.5, for Minecraft 1.7.10, that's the current version, if you can't reproduce, the issue is not valid.
http://www.curse.com/mc-mods/minecraft/tinkers-construct#t1:other-downloads

**Comment by Asiangamer125** [comment]
If I can't reproduce? What? Sorry I'm new to github

**Comment by Asiangamer125** [comment]
I'll try it in 1.7.10

**Comment by Asiangamer125** [comment]
The problem persists in this version as well

**Comment by mDiyo** [comment]
The tools do not have 100 durability. You're viewing vanilla tooltips which show a percentage of the durability.

**Comment by Asiangamer125** [comment]
Then explain why every tool breaks when used 101 times

**Comment by Asiangamer125** [comment]
Ok so I feel like an arse. I decided to delete everything minecraft
related(except my saves) and reinstalled it. The tools have the correct
durability. I apologize for wasting your time. You're mod is fantastic and
I was upset because I thought my computer was causing a bug or something.
