### ISSUE TITLE
Crash client report

### ISSUE THREAD

**Issue by MrHelp** [SlimeKnights/TinkersConstruct#1648]
When we open "materials and you volume 2" and see book in last page (or click "next" , "next", "next", "next", etc) we will see crash :( 
http://pastebin.com/xPWwruVr

**Comment by MrHelp** [comment]
i don't know wich  is the mod use this crash, but in other server when mods is more easy this mistake is have not.

**Comment by TherminatorX** [comment]
Does it crash if you remove OptiFine?
