### ISSUE TITLE
Rework upgrades display for Quartz/Redstone in the tooltip

### ISSUE THREAD

**Issue by AnrDaemon** [SlimeKnights/TinkersConstruct#1650]
Instead of just showing "Haste" or "Sharpness" in the tooltip, which may also be confused with enchants, show complete ranks of upgrade as roman number, similar to, say, Reinforced. Add a "+" to indicate that enchant is above complete rank, if it is higher than rank I.
I.e. `Haste (means, Redstone 5/50)` => `Redstone`, `Sharpness (from Quartz 72/96)` => `Quartz I+`.

**Comment by TherminatorX** [comment]
-1, as the current design tells people what effect the modifier has on the tool.

**Comment by AnrDaemon** [comment]
Fine, keep effect names. But currently they are rather vague unless you are looking at them in tool forge.

**Comment by TherminatorX** [comment]
The Tool Forge is where it actually counts, since that's where you need to know what materials to use for modifications.

**Comment by AnrDaemon** [comment]
I care not about modification, I want to know their effects. No, I don't want to know.
I want to clearly show them to my users. I want them to see at a glance that this item has better enchantment than that. And tool forge may not be available at all to begin with. (I.e. Adventure mode map.)
