### ISSUE TITLE
Battlesigns lose text on log-out(diff rules for SMP, I guess)

### ISSUE THREAD

**Issue by TherminatorX** [SlimeKnights/TinkersConstruct#1653]
To reproduce:
1. Create a singleplayer world
2. Place a fancy battlesign
3. Write something important and lengthy on it
4. Log out (close the world)
5. Log back in (reopen the world)
6. Get confused
7. Forget what was so important and lengthy

They seem to keep their text when the chunk is unloaded.

Update: this seems to only happen in the spawn chunks. I don't even.

**Comment by CombatZAK** [comment]
Not sure I have anything super useful to add, but is spawn protection turned on for that SMP server? I could very easily see some weird issue where stuff gets reverted in protected chunks.

**Comment by TherminatorX** [comment]
This was only tested in singleplayer, I don't have a server to test this on.

**Comment by DrZed** [comment]
"important and lengthy"
I don't know about that...
Nothing is ever really important in games, but if it was important to remember, and it's in singleplayer why didn't you just [write, screenshot, leave, return, realize it's gone, open screenshot] screenshots save useful stuff ya know.

**Comment by DrZed** [comment]
Anyway not a game breaking bug so I'm sure bonii won't fix unless bored, it doesn't affect gameplay it's just aesthetic. (that is if this is 1.7)

**Comment by TherminatorX** [comment]
@DrZed I was using attempting to be humorous with that phrase. :P 
If text is lost, what is the point of them being able to write on in the first place? Imagine if vanilla signs had this problem.

Additionally, all official versions of TiC are 1.7.10, since 1.8 versions aren't out yet.

**Comment by DrZed** [comment]
I know they're 1.7 but 1.8 is the only version actually being worked on atm, It's heavily WIP that's why there is no builds out for the public. he said himself "We're not doing anything else to 1.7.x unless it's a major bug" Paraphrasing ofc since I forgot what the exact words are and really don't care.
