### ISSUE TITLE
world gen'ed crafting station can't be made into slab version

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1654]

**Comment by TheQuadShot** [comment]
(^sorry don't know how that happened^) 
All of the other items found in the village can be crafted into the slab versions.
found this in older version and confirmed on latest version (1.8.5)

**Comment by MyDeloreanWontStart** [comment]
Just place it back down and break it again, then it should be normal.

**Comment by bonii-xx** [comment]
...that's one weird issue. Especially since the ones created by worldgen have to be broken to be obtained too. However, considering the state of tcon it's not worth fixing currently.
