### ISSUE TITLE
Client crash on server login

### ISSUE THREAD

**Issue by Shourn** [SlimeKnights/TinkersConstruct#1655]
First occured after breaking an OpenBlocks gravestone and the items spilling out. My guess is that TConstruct is trying to do rendering on a Chisel2 Diamond Chisel.

https://pastee.org/mgh9j

**Comment by TherminatorX** [comment]
Well, you can likely delete the item via an NBT editor. Are you using the latest version of Chisel 2?
(Additionally, are you using MultiMC?)

**Comment by Shourn** [comment]
I am indeed using the latest version of Chisel2 as well as MultiMC.
I forgot to mention that I am running the FTB Infinity modpack in the latest recommended version (1.6.2).
Crash happens independent of the method of launching the game.

**Comment by aekigescraft218** [comment]
my tinkers construct1.7.10 - 1.8.5 is unloaded and erroredand i dont know why

**Comment by Shourn** [comment]
After further research it appears that the contents of the gravestone got corrupted somehow.
Closing this.
