### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by epicskymi** [SlimeKnights/TinkersConstruct#1658]
http://pastebin.com/kPYMrZUd
tried to craft stonebrick got this crash

**Comment by bonii-xx** [comment]
...okay?

**Comment by TherminatorX** [comment]
How did you get that CCC version? @Chicken-Bones is still on 1.0.5.xxx, not 1.0.6.xxx.
Most of the errors in the log are from CCC, so that should be fixed by getting a legitimate version.
