### ISSUE TITLE
IC2 Classic

### ISSUE THREAD

**Issue by Speiger** [SlimeKnights/TinkersConstruct#1659]
I got the request to add Support between IC2 Classic and Tinkers Construct (simply use EU on Tinkers Tools), i know you removed it and i know the reasons, i talked a long time ago with some old devs which are maybe not working on it anymore (Tinkers Consturct)...

But i ask anyways. Would you read IC2 Energy to tools. IC2 Classic is like the Old IC2 (for what you added the Compatiblity)?

And if you need help then ask me...

**Comment by bonii-xx** [comment]
Nope.

**Comment by Carbon-Ghost** [comment]
Why ;( 

Also why did you removed IC2 compat in the first place ;(

**Comment by Speiger** [comment]
@Carbon-Ghost do not open this story agan -.-" believe me it is not worth of asking

**Comment by Carbon-Ghost** [comment]
Well, not gonna talk here I guess, sad that they removed compat though ;(

**Comment by laz2727** [comment]
IC2 compat was removed when IC2 died. Problem with that?

2015-06-28 16:30 GMT+06:00 Carbon-Ghost <notifications@github.com>:

**Comment by Speiger** [comment]
Well then you can not see the difference between a dead mod and a mod that is called dead...
Only for saying: IC2 is not dead... It is not perfect has his problems but it is not dead!
Also what happend to my help that allows the smeltery to access it from any block without TileEntity Need? i gave it now to 3 people and it did not came  though?

**Comment by Carbon-Ghost** [comment]
Well first thing first, IC2 never died, it became unstable and experimental, and because of that became very unpopular ( and I agree that was a bit annoying ) BUT It's not dead at ALL, and if you want old  voltage back, there is an addon for this that you can go download, just saying ;P

AND if you want the whole old IC2 back, go check out IC2 classic ;P
