### ISSUE TITLE
Still Need Help

### ISSUE THREAD

**Issue by Arcoite** [SlimeKnights/TinkersConstruct#1663]
I tried to download forge again but it said it encountered an error with the language. I also tried to look for a proper release of forge but I don't know where to look. Can you give me link to a website? The new forge website confuses me.

**Comment by Arcoite** [comment]
I've tried download forge from its own website and when I try to install it an error report pops up. It says something about the language. But when i go in game and go to change the language, all of the languages show up now. So, i don't know what to do anymore. Please help.

**Comment by SamRaven2** [comment]
This is not a problem relating to Tinkers Construct, so it should not be reported here. Please take this to either the Forge github, the IRC, or the Reddit.
