### ISSUE TITLE
Resource Pack texture bug/glitch

### ISSUE THREAD

**Issue by roscuro82** [SlimeKnights/TinkersConstruct#1664]
I've been trying out various resource packs and I noticed that some of them replaced the texture for lava in the Seared Tank. Another resource pack did the same for the seared window and glass.

Its definitely related to connected textures and optifine. The texture for lava is replaced with stone1 in the seared tank. As for the seared window and glass..it was using conquest that these started showing up and then they were changed to some kind of mossy stone block. I can't even find it in the game  :(

I'm not sure if this is an issue that can be fixed in TinkersConstruct or maybe its 100% contained within optifine.
tConstruce v1.8.5
Optifine  1.7.10 HD U B7
Forge 10.13.3.1424

![searedglass](https://cloud.githubusercontent.com/assets/12991484/8273336/d15c3ab2-181d-11e5-9fbd-507a2c89e6b0.jpg)
![searedtanks](https://cloud.githubusercontent.com/assets/12991484/8273337/d1607438-181d-11e5-89e8-0649d3ba8d32.jpg)

**Comment by bonii-xx** [comment]
Funny, but

>optifine

**Comment by roscuro82** [comment]
Just curious, do you know of a better mod that adds connected textures? I
assume that is whats causing it and I'd rather keep using fancy resource
packs  :D  anyways thanks for commenting so quickly on my issue.

**Comment by TherminatorX** [comment]
And just what block are you so desperate to have connected textures for? Most mods add their own CT blocks and code by themselves, with no need for Optifine, such as with TiC clear glass.

**Comment by roscuro82** [comment]
Sorry if I gave you the wrong impression, I'm not desperate for anything I
was just wondering if this was something the developers of optifine should
be told about.

I stopped using the resource pack that was causing the problem anyways. The
color pallet it uses makes the sequoia biome (biomesOplenty) purple :)

Do you have a favorite resource Pack? Mine has been werien
