### ISSUE TITLE
Crash when opening inventory

### ISSUE THREAD

**Issue by devryb** [SlimeKnights/TinkersConstruct#1665]
Opening your inventory on a vanilla server will crash your client.
This used to not be an issue in previous versions.

http://pastebin.com/Rrf1QTKk

**Comment by TherminatorX** [comment]
The fix is simple: don't use Forge to connect to vanilla servers :)

**Comment by bonii-xx** [comment]
Pretty much what TherminatorX said.

**Comment by devryb** [comment]
Uh can I ask why??  No other mods have issues when connecting to Vanilla and even support it.....

**Comment by bonii-xx** [comment]
Why would you connect to a vanilla server with Tcon in your instance? There simply is no reason to support it.

**Comment by devryb** [comment]
Most larger servers use a Bungeecord network with a hub server running Vanilla...
Unless you have another idea for a hub server which multiple different modpacks can connect to that is our only option.

**Comment by TherminatorX** [comment]
Ah, there's the use. While I'll admit it's a nice idea, it highly impractical. The client must have a whole slew of various mods at-the-ready, taking up space in their folders.
And by slew, I mean:
![gravity-falls-gnome-o](https://cloud.githubusercontent.com/assets/7256249/8315720/38edc5b0-19b8-11e5-96db-d9dcf16c2b5a.gif)
