### ISSUE TITLE
Problem with Crossbows on PVP-Disabled servers

### ISSUE THREAD

**Issue by MrLast98** [SlimeKnights/TinkersConstruct#1666]
Hello!
I've seen that in every server that have PVP disabled, crossbows does damage. Now, what about adding a line that checks if it is on a server, and checks if the PVP is disabled? And in that case he doesn't do damage to players?

**Comment by bonii-xx** [comment]
Curious. I'll see if I can reproduce that.

**Comment by bonii-xx** [comment]
Can't reproduce. Just tested this by having 2 people in the same team and disabling friendlyfire. Bolts go through teammates and don't hit them, as expected.
