### ISSUE TITLE
This is a very weird problem I've been trying to track down for about a week...crash to launcher.

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1667]
The common denominator is that I'm right clicking with a tinkers tool. It first happened with an RFTools Dialer with a pickax, and now it's a power monitor, The reason I'm filing a bug here is that the log say's that I'm placing a block, and I can reproduce it now by right clicking with a mattock on the power monitor (Ender's).
http://pastebin.com/pKQ0ZFqR
Here's the one from the other day
http://pastebin.com/WdqtWXis

**Comment by roboliutas** [comment]
Is the block are near your tools? Because if so then its not a bug because tinkers tools will place blocks bearby the tools

**Comment by roboliutas** [comment]
Nearby*

**Comment by TheQuadShot** [comment]
No, in both cases I'm clicking the block to open the ui

**Comment by TheQuadShot** [comment]
Oh, btw the mattock doesn't place a block, (I know it "tries" (from what mDiyo told me)but the  right click with mattock hoe's the ground)

**Comment by bonii-xx** [comment]
I think this is a desync between client and server. However nobody has been able to reproduce this bug.

**Comment by TheQuadShot** [comment]
Hmmm, I just tried it again, and it's not happening, but I did it 3 times in a row before I filed this....

**Comment by bonii-xx** [comment]
Yup, now you know why we couldn't track it down so far.

**Comment by TheQuadShot** [comment]
I knew this was going to be a tough one to track down, cause there were no mods listed in any of the crash logs, they all pointed at the network (like the older log in the report) and it wasn't consistent, when I had the crash 3 times and the log said I was placing a block, I thought I had it... maybe it's just java or mc ;-)

**Comment by TheQuadShot** [comment]
This time I right clicked on my reactor's controller... and the only thing I can see in the dump, is I'm "placing block" ... I don't get it, but may you can find something I'm missing.

http://pastebin.com/juB6S9Nx
