### ISSUE TITLE
Smeltery Won't Smelt

### ISSUE THREAD

**Issue by Bitenshi** [SlimeKnights/TinkersConstruct#1670]
So I've set up multiple smelteries on different worlds. The controller starts to glow and flicker meaning I set it up correctly, I go into the controller's interface put in the ore and nothing happens. I've tried breaking the controller and replacing it. I've tried different sized smelteries. I've tried uninstalling and reinstalling it. I've even tried updating to a newer version and just nothing. And yes there is lava in my seared tank.
![smeltery 2](https://cloud.githubusercontent.com/assets/13036993/8336482/ee0bda94-1a72-11e5-806f-2d0fd241e70a.PNG)
![smeltery 3](https://cloud.githubusercontent.com/assets/13036993/8336484/f12d61fc-1a72-11e5-9cc4-7a7d7a967f33.PNG)

**Comment by MrKunji** [comment]
Diamonds can't be smelted there. Test with metals or emeralds to see.

**Comment by Bitenshi** [comment]
I have tried with others but I'll try again on my other worlds. Since I only did it on my main world. One moment.

**Comment by Bitenshi** [comment]
Okay I figured it out with my first world mixed up the emerald ores from a different mod that looked a lot like the vanilla minecraft emerald ore. But when did they stop being able to smelt diamonds? I've used earlier versions that you use to be able to. Hm... Oh well thank you anyways, much appreciated for the things you guys do. ^-^

**Comment by MrKunji** [comment]
They never smelted diamonds even back on 1.5.2.

**Comment by bonii-xx** [comment]
Diamonds never were smeltable, only emeralds. I guess nobody ever expected another mod adding emeralds so the emerald smelting registration is not oredicted.

**Comment by laz2727** [comment]
Despite RC having dank emeralds for years.

**Comment by bonii-xx** [comment]
Right. I'm surprised nobody complained about that.. ever. At least I'd assume it doesn't melt.

**Comment by laz2727** [comment]
Most likely because there are not much of people who know about RC spheres,
people who know about smeltery doubling them, people who smelt stuff in the
smeltery and even less people who are all of the above. Assuming they don't
actually smelt, of course.
