### ISSUE TITLE
(1.7.10) Invisible and unusable tool stations, part builders, tool forges, etc. [jenkins build 961]

### ISSUE THREAD

**Issue by ate0ate** [SlimeKnights/TinkersConstruct#1675]
Just a heads up, but it seems that commit 54d8bbcc028e504d0d2717473f0876328407200d broke all of the various tinkering tables and tool forges causing them to be invisible and unclickable in world. Breaking them gives an item stating what the object is, but placing them in world just leaves an invisible useless block.

**Comment by TherminatorX** [comment]
Remove Optifine

**Comment by bonii-xx** [comment]
That commit had no impact on any rendering at all. Or on blocks. Or on items. Or on anything besides recipies.

**Comment by ate0ate** [comment]
I don't use optifine, never have, and reverting to the prior jenkins build 961, fixes the problem. Its not something to do with rendering, the invisibility is a side effect. For some reason it cannot draw the different variants of the tables.

**Comment by laz2727** [comment]
There's literally nothing changed except recipes. Are you sure 960 works?
Maybe the jenkins is porken instead.

2015-06-27 19:19 GMT+06:00 ate0ate <notifications@github.com>:

**Comment by ate0ate** [comment]
I'm sure build 960 works perfectly. Here's some screens taken minuts apart. Only difference is build 960 versus 961...

Build 960 in world...
http://i.imgur.com/uiXuXP7.png
Build 960 NEI appearance...
http://i.imgur.com/PIBBNq5.png
http://i.imgur.com/7D8RLjm.png

And here's invisible build 961 in world...
http://i.imgur.com/xGJ5PFY.png
Build 961 NEI appearance...
http://i.imgur.com/JuEC3F9.png
http://i.imgur.com/i267App.png

**Comment by ate0ate** [comment]
Is anyone going to even see this now that its closed? Should I reopen the issue?

**Comment by bonii-xx** [comment]
Mmhm, gany messed it up and it throws errors.. CHECK YOUR PRs @ganymedes01 :P

**Comment by srs-bsns** [comment]
Yes, Please reopen this. I've experience this issue as well with build 961.
The rendering problems aren't exclusive to the tables, but also to all of the tools.
None of the tool icons render in NEI or in the inventory. For in-world tools, only the tool rod renders, but not the tool head (though they still work properly).
Slab versions of the tables render fine, but they can't be accessed as per ate0ate's description

After having tested with only NEI, WAILA, and TC, both 960 and 961, I discovered this with 961: http://pastebin.com/cRMs8eEp

**Comment by srs-bsns** [comment]
Cheers. \o/

**Comment by ganymedes01** [comment]
whoops... sorry XD
