### ISSUE TITLE
invisible broadsword, but toon renders with rainbow square in hand

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1676]
I don't know how I got the thing, I just started new world and was starting to collect resources. I noticed no items were going into hot bar open space, When I switch to that slot a rainbow kind of square appears in my hand, and if I mouse over hot bar, it's say's broadsword. it doesn't do anything, not even break dirt. I'm running TCon V 1.8.5, and Mantle 0.3.2 and Forge V .1481
![what](https://cloud.githubusercontent.com/assets/11265900/8394092/2f3bcc78-1cde-11e5-9c8f-dfe86a96df11.png)
![2015-06-27_15 07 57](https://cloud.githubusercontent.com/assets/11265900/8394097/4dfe180a-1cde-11e5-9bbd-349194f224f9.png)

**Comment by TherminatorX** [comment]
It's likely a broken item. Kill it with TNT and never look back.

**Comment by TheQuadShot** [comment]
I dropped it into deep ocean about 80 chunks back ;-)

**Comment by laz2727** [comment]
Implying TiC item entities aren't immortal. Use something that works, like
ExU trash can, RC void chest or end's void.

2015-06-28 6:26 GMT+06:00 James <notifications@github.com>:
