### ISSUE TITLE
Smelting iron nuggets is inefficient

### ISSUE THREAD

**Issue by bulldog98** [SlimeKnights/TinkersConstruct#1679]
After testing I found, that smelting 9 iron ingot uses less lava than smelting one block of iron, I thought let's try nuggest too. And to my suprise it was even more inefficient to smelt 81 nuggest than it was to smelt one block of iron. Since smelting 81 nuggest is needs a better smeltery infrastucture than smelting 1 block of iron, I find that quite unrevarding and had hope that smelting nuggest was more efficient, since they are smaller and therefore smelt faster.

**Comment by laz2727** [comment]
You need to smelt them at once. Using smeltery for small amounts of stuff
is very ineffective.

2015-06-29 17:55 GMT+06:00 Jonathan Kolberg <notifications@github.com>:

**Comment by larrythemodder** [comment]
Is this really an issue? Efficiency is going to depend on the size of your smeltery. If you're putting in 3 nuggets at a time, then yeah, 27 separate batches is probably going to be more inefficient than just a single block.
