### ISSUE TITLE
Request Moss Change

### ISSUE THREAD

**Issue by Cooolaid** [SlimeKnights/TinkersConstruct#1681]
I am requesting that the Moss texture be changed so it does not completely cover my tools
in a ugly green glob. I would like to see a small round circle of dark green on the bottom side of handles
next to the Lapis Lazuli 'fortune' blue circle.

Its a bit silly, but to me as well as many others,
we would like to keep our tools looking nice from the upgrades and not covered by
the Moss green glop when moss is added for repair upgrade.

Thank you for reading.

**Comment by bonii-xx** [comment]
Resource Pack. The thing you're looking for is a resource pack.

**Comment by Cooolaid** [comment]
Nope resource pack is not what I am looking for.

**Comment by Voxel-Friend** [comment]
I actually agree with this, due to the aesthetic of the layering I never use mossy, and I don't much care for resource packs. Though in your defense Bonii I can understand why you would want to take time out of RL and 1.8 to address such a seemingly trivial matter.

**Comment by bonii-xx** [comment]
You're probably confusing resource packs with complete texture packs like Soartex. Resource packs simply allow you to exchange resources like the textures. They're quite literally designed to allow you to change the graphics of moss. :P
