### ISSUE TITLE
Calculation Bug with Bow Limb Crafting

### ISSUE THREAD

**Issue by oitsjustjose** [SlimeKnights/TinkersConstruct#1687]
Hard to summarize the issue, but using 3 shards / chunks of a material (equaling 1.5 "material") on a bow limb (whose material cost is 1.5) yields the limb, and an extra shard....

![ss 2015-07-05 at 05 25 19](https://cloud.githubusercontent.com/assets/3887324/8513790/9798d0ac-233e-11e5-8c6e-37e68c08606b.png)

**Comment by TherminatorX** [comment]
Confirmed in 1.8.5

**Comment by bonii-xx** [comment]
Not relevant anymore in TiC2
