### ISSUE TITLE
[SUGGESTION] ON/OFF tools config

### ISSUE THREAD

**Issue by Neodark7** [SlimeKnights/TinkersConstruct#1688]
Hi :).
Please can you edit the :

    B:"Enable mod blue slime tools"=true
    B:"Enable mod bone tools"=true
    B:"Enable mod cactus tools"=true
    B:"Enable mod flint tools"=true
    B:"Enable mod netherrack tools"=true
    B:"Enable mod paper tools"=true
    B:"Enable mod slime tools"=true
    B:"Enable mod stone tools"=false
    B:"Enable mod wooden tools"=false

configs to hide in NEI or simply not load the tools rather than just disable the recipes cause for NEI it's almost 500 items in total, so... many pages. :/

**Comment by laz2727** [comment]
That's why nei search exists.

**Comment by bonii-xx** [comment]
Not possible. You can use InpureCore to group all the materials into one respective entry, if it bothers you that much.

**Comment by Neodark7** [comment]
ok thank you anyway...
