### ISSUE TITLE
travellers gear googles bug

### ISSUE THREAD

**Issue by LuanCenation** [SlimeKnights/TinkersConstruct#1689]
I can not activate the zoom and night vision. already removed all key conflicts and not worked.
version 1.8.5

**Comment by TherminatorX** [comment]
I can use them just fine, version 1.8.5. Unable to replicate.
Does this happen when just TiC and Mantle are used?

**Comment by LuanCenation** [comment]
thank you removed the TIC and returned to normal.

**Comment by TherminatorX** [comment]
I said nothing about removing TiC...

**Comment by Ianaver** [comment]
@LuanCenation did you craft them or cheat them in using NEI? sometimes cheating them in especially if you try to make an infinite stack can break the NBT data and cause some issues. Also you know that night vision has to be added with a recipe right?
