### ISSUE TITLE
FMLIndexedMessageCodec exception caught

### ISSUE THREAD

**Issue by EpicMan2** [SlimeKnights/TinkersConstruct#1691]
Well, i have that error when connect to server.
Client gets: Fatally missing blocks and items.
Server gets: http://pastebin.com/c0CtyzRP

Mods: Divine RPG, Armor Status HUD, Direction HUD, Bibliocraft, Biomes o'plenty, CustomNPCs, MoCreatures, DungeonPack, iChunUtil, Ironchests, Mantle, Morph, Optifine, Rei's minimap, Tinker's Construct, Thaumcraft, Thaumic Tinker, Twilight Forest, Yalter-utils.

**Comment by TherminatorX** [comment]
Why are you posting this to the TiC issues? The only mod referenced is Divine RPG.

"at net.divinerpg.utils.events.ArcanaHelper.setBarValue(ArcanaHelper.java:91) [ArcanaHelper.class:?]"

**Comment by EpicMan2** [comment]
Well. When i remove Divine RPG i still get "fatally missing blocks and items" from client, and get nothing (really, no error) from server. But when i remove TiC i can connect.
