### ISSUE TITLE
Client crash when opening inventory on server

### ISSUE THREAD

**Issue by Antillar** [SlimeKnights/TinkersConstruct#1693]
Running TiC v1.8.5 for Minecraft 1.7.10. The problem only happens when I open inventory on the server, in singleplayer it works fine. Immediately after I open inventory, my client crashes with the following crash report:
http://pastebin.com/nVXXVXFz
Please help! This is a fatal problem for me.

**Comment by bonii-xx** [comment]
#1668

**Comment by bonii-xx** [comment]
You can test the alpha version, it should fix it but so far nobody has reported back.

**Comment by Antillar** [comment]
Somehow the bug was fixed when I installed IGW mod for ExtraCells, which I am also using. I have no idea how this can be connected to inventory rendering, but I am satisfied.

**Comment by Antillar** [comment]
I have spent the whole day gathering required information and programms, 1.8.6a installed, and the problem is fixed there. So, there is a report you have been looking for :wink:

**Comment by bonii-xx** [comment]
Perfect! Many thanks.
