### ISSUE TITLE
possible 1% error on beheading

### ISSUE THREAD

**Issue by buglord** [SlimeKnights/TinkersConstruct#1695]
have not looked up the implementation for the random number generator, but I have had times where a tool with 100% beheading has failed to provide a skull, it is rare, but may be due to checking for less than (<) instead of less than or equal (<=) when deciding to drop skulls. this is an issue if nextInt(100) has a range including 100.

the latest instance has been on agrarian skies 2 with a pan which has beheading 10, 100% chance to behead according to tooltip.

if it turns out not to be a bug in tinkers, any mod interactions that could cause it?

**Comment by buglord** [comment]
after some additional research, tinkers tweaks modifies beheading modifier to only give 2% chance per level by default. where do I complain to possibly have the tooltips/tool info be shown correctly?

**Comment by bonii-xx** [comment]
Tinkers does not show any chance to the user, iirc?

**Comment by buglord** [comment]
vanilla tinkers does not, unsure if it is tinkers tweaks, NEI, waila or some other random mod that does it. which is why I'm asking where.
