### ISSUE TITLE
Test Dummy in Smeltery + smelt something = Infinite blood

### ISSUE THREAD

**Issue by axzxc1236** [SlimeKnights/TinkersConstruct#1697]
[picture](http://i.imgur.com/rFxx4L4.png)

**Comment by TherminatorX** [comment]
Confirmed in 1.8.6a

**Comment by axzxc1236** [comment]
I have to remove testdummy for now
I turned off NaturalRegen in server pack and this will stupidly break the balance.

**Comment by bonii-xx** [comment]
Blood is not really that powerful, how does it break balance?

**Comment by axzxc1236** [comment]
When you eat Coagulated Blood, it gives health boost effect.

**Comment by laz2727** [comment]
It can also be converted into pink slime. But i see nothing gamebreaking.
Health boost isn't a big deal with TiC.

2015-07-18 15:52 GMT+06:00 axzxc1236 <notifications@github.com>:

**Comment by axzxc1236** [comment]
@laz2727 It is a big deal with my modpack balance.

**Comment by bonii-xx** [comment]
You can also melt a few zombie flesh to get the same blood.

**Comment by axzxc1236** [comment]
a few = 32
it is not easy to get when you just started playing, also I have mods that makes monsters hard to kill.

**Comment by TherminatorX** [comment]
Besides, it's made of wool and straw. Not a lot of blood if any should come out, and definitely not infinite.

**Comment by bonii-xx** [comment]
ad4822465b26dc3724b35f1034cf2fc06a9a4792
