### ISSUE TITLE
GUI Smeltery and InfiniteInvo

### ISSUE THREAD

**Issue by Labna** [SlimeKnights/TinkersConstruct#1699]
Hey,
I have a huge problem, did you ever try to play with InfinteInvo ?
It's work ! amazing, but not all.
open an Smeltery controler UI and hover the quantity of lava (if not empty), the game crash like penguins who parachute jump without a parachute!

I will send that [same issue](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2336005-infiniteinvo-all-the-inventory-space-a-player?page=7) to InfiniteInvo team. And I hope you will be able to find a solution as sooner as possible.

Thanks for that useful mod !!

**Comment by TherminatorX** [comment]
Can you post the crash log?

**Comment by Labna** [comment]
###the Minecraft log :
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 7/25/15 11:24 AM
Description: Rendering screen

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at tconstruct.smeltery.gui.SmelteryGui.func_146979_b(SmelteryGui.java:151)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:64)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at tconstruct.smeltery.gui.SmelteryGui.func_146979_b(SmelteryGui.java:151)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:64)

-- Screen render details --
Details:
	Screen name: tconstruct.smeltery.gui.SmelteryGui
	Mouse location: Scaled: (240, 99). Absolute: (481, 280)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Labna'/223, l='MpServer', x=44.57, y=87.50, z=-11.76]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (38,64,-13), Chunk: (at 6,4,3 in 2,-1; contains blocks 32,0,-16 to 47,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1903 game time, 1903 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 75 total; [EntitySquid['Squid'/137, l='MpServer', x=31.09, y=60.34, z=-42.09], EntitySquid['Squid'/136, l='MpServer', x=33.22, y=45.34, z=-58.81], EntitySquid['Squid'/139, l='MpServer', x=36.53, y=60.28, z=42.75], EntityItem['item.tile.flower2.poppy'/138, l='MpServer', x=42.34, y=64.13, z=-28.41], EntitySquid['Squid'/129, l='MpServer', x=25.03, y=58.38, z=32.31], EntitySquid['Squid'/128, l='MpServer', x=29.91, y=59.31, z=34.31], EntitySquid['Squid'/130, l='MpServer', x=28.78, y=57.03, z=35.16], EntityZombie['Zombie'/287, l='MpServer', x=-4.50, y=37.00, z=-66.50], EntityZombie['Zombie'/566, l='MpServer', x=92.50, y=27.00, z=-80.50], EntitySkeleton['Skeleton'/157, l='MpServer', x=77.44, y=21.00, z=-65.91], EntityCreeper['Creeper'/158, l='MpServer', x=75.50, y=21.00, z=-62.50], EntityBat['Bat'/159, l='MpServer', x=84.75, y=22.17, z=-66.38], EntityCreeper['Creeper'/38, l='MpServer', x=-33.50, y=36.00, z=-48.50], EntityZombie['Zombie'/36, l='MpServer', x=-33.50, y=26.00, z=-48.50], EntitySheep['Sheep'/163, l='MpServer', x=76.50, y=67.00, z=11.50], EntityZombie['Zombie'/313, l='MpServer', x=107.50, y=64.00, z=16.50], EntitySheep['Sheep'/162, l='MpServer', x=74.50, y=63.00, z=15.63], EntityCow['Cow'/161, l='MpServer', x=77.50, y=93.00, z=-11.50], EntityCow['Cow'/160, l='MpServer', x=78.50, y=93.00, z=-7.50], EntitySheep['Sheep'/165, l='MpServer', x=78.56, y=63.00, z=25.06], EntitySheep['Sheep'/164, l='MpServer', x=77.50, y=81.00, z=8.50], EntitySpider['Spider'/288, l='MpServer', x=-5.03, y=37.00, z=-67.75], EntityCreeper['Creeper'/186, l='MpServer', x=100.50, y=71.00, z=58.50], EntityCreeper['Creeper'/184, l='MpServer', x=109.50, y=64.00, z=-30.50], EntityZombie['Zombie'/185, l='MpServer', x=110.50, y=58.00, z=-7.50], EntityZombie['Zombie'/190, l='MpServer', x=115.63, y=47.00, z=-16.66], EntityZombie['Zombie'/191, l='MpServer', x=112.50, y=52.00, z=-30.50], EntitySpider['Spider'/63, l='MpServer', x=-30.03, y=22.00, z=-63.63], EntityCreeper['Creeper'/182, l='MpServer', x=97.97, y=56.00, z=-43.44], EntityCreeper['Creeper'/62, l='MpServer', x=-18.50, y=23.00, z=-81.50], EntityZombie['Zombie'/183, l='MpServer', x=110.50, y=58.00, z=-29.50], EntityZombie['Zombie'/180, l='MpServer', x=92.50, y=23.00, z=-64.50], EntitySkeleton['Skeleton'/538, l='MpServer', x=100.16, y=32.00, z=-72.31], EntityZombie['Zombie'/181, l='MpServer', x=81.50, y=16.00, z=-49.50], EntityZombie['Zombie'/68, l='MpServer', x=-20.06, y=24.00, z=8.72], EntityCreeper['Creeper'/64, l='MpServer', x=-20.50, y=23.00, z=-79.50], EntityZombie['Zombie'/65, l='MpServer', x=-17.13, y=37.00, z=-64.50], EntityZombie['Zombie'/66, l='MpServer', x=-16.50, y=36.00, z=-58.50], EntityZombie['Zombie'/67, l='MpServer', x=-17.50, y=36.00, z=-58.50], EntityCreeper['Creeper'/76, l='MpServer', x=-3.50, y=28.00, z=-68.50], EntityCreeper['Creeper'/77, l='MpServer', x=-1.50, y=28.00, z=-67.50], EntityBat['Bat'/78, l='MpServer', x=-5.25, y=36.00, z=-44.25], EntityBat['Bat'/79, l='MpServer', x=-3.16, y=36.85, z=-57.53], EntityZombie['Zombie'/193, l='MpServer', x=116.41, y=49.00, z=-11.94], EntityZombie['Zombie'/192, l='MpServer', x=115.50, y=49.00, z=-21.50], EntityCreeper['Creeper'/74, l='MpServer', x=-13.50, y=27.00, z=-85.50], EntityBat['Bat'/75, l='MpServer', x=-7.97, y=27.24, z=-88.69], EntitySquid['Squid'/85, l='MpServer', x=-15.66, y=49.81, z=-44.25], EntityBat['Bat'/84, l='MpServer', x=-1.35, y=38.92, z=-54.56], EntitySquid['Squid'/87, l='MpServer', x=-7.19, y=48.28, z=-33.06], EntitySquid['Squid'/86, l='MpServer', x=-8.84, y=58.38, z=-23.66], EntityZombie['Zombie'/81, l='MpServer', x=-9.31, y=34.16, z=-58.69], EntityBat['Bat'/80, l='MpServer', x=-3.00, y=35.89, z=-55.91], EntityBat['Bat'/83, l='MpServer', x=-8.63, y=37.57, z=-56.28], EntityBat['Bat'/82, l='MpServer', x=-8.03, y=36.85, z=-37.78], EntitySquid['Squid'/92, l='MpServer', x=-5.72, y=48.34, z=16.75], EntityBat['Bat'/89, l='MpServer', x=-0.47, y=33.35, z=-1.50], EntityCreeper['Creeper'/88, l='MpServer', x=-2.19, y=19.48, z=-4.58], EntityBat['Bat'/91, l='MpServer', x=-4.84, y=21.01, z=-5.00], EntityZombie['Zombie'/90, l='MpServer', x=-2.66, y=21.00, z=1.34], EntitySquid['Squid'/103, l='MpServer', x=6.66, y=57.16, z=-56.53], EntityCreeper['Creeper'/104, l='MpServer', x=12.50, y=24.00, z=8.50], EntityClientPlayerMP['Labna'/223, l='MpServer', x=44.57, y=87.50, z=-11.76], EntityWitch['Witch'/493, l='MpServer', x=-34.50, y=38.00, z=-75.50], EntitySquid['Squid'/119, l='MpServer', x=24.97, y=46.19, z=-68.97], EntitySquid['Squid'/118, l='MpServer', x=25.81, y=46.03, z=-70.53], EntityBat['Bat'/127, l='MpServer', x=21.56, y=30.17, z=35.75], EntityCreeper['Creeper'/126, l='MpServer', x=23.50, y=37.00, z=34.50], EntityZombie['Zombie'/125, l='MpServer', x=27.50, y=37.00, z=36.50], EntitySkeleton['Skeleton'/124, l='MpServer', x=18.50, y=25.00, z=34.50], EntitySquid['Squid'/123, l='MpServer', x=32.50, y=57.84, z=-34.75], EntitySquid['Squid'/122, l='MpServer', x=20.84, y=60.34, z=-52.34], EntityZombie['Zombie'/607, l='MpServer', x=-33.50, y=29.00, z=66.50], EntitySquid['Squid'/121, l='MpServer', x=26.22, y=59.03, z=-71.06], EntitySquid['Squid'/120, l='MpServer', x=24.72, y=43.97, z=-70.59]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 683869112 bytes (652 MB) / 908591104 bytes (866 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	infiniteinvo{1.0.41} [InfiniteInvo] (InfiniteInvo-1.0.41.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b-13.03.15.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 770M/PCIe/SSE2'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 770M/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.30, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Faithful.zip, ressource by labna]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by bonii-xx** [comment]
Update your forge or use the old tcon version.

**Comment by Labna** [comment]
Sorry it's an bug in the 1.8.3 of TConstruct, but it's fixed in the 1.8.5  
thanks anyway
