### ISSUE TITLE
Wool Slabs have incorrect names

### ISSUE THREAD

**Issue by gabor6505** [SlimeKnights/TinkersConstruct#1700]
Any wool slab have incorrect names, and every slab in the "TConstruct:WoolSlab2" ID (8 slab) have "Gray Wool Slab" names. I use OptiFine, but I don't think that can do anything with this. I also noticed this issue in Agrarian Skies 2.

Versions I tested:
1.8.5

Screenshots:
![2015-07-22_12 12 41](https://cloud.githubusercontent.com/assets/12859334/8823178/165b2c44-306b-11e5-9084-091c93a8139b.png)
![2015-07-22_12 12 46](https://cloud.githubusercontent.com/assets/12859334/8823179/165db9aa-306b-11e5-9f2b-a64dda1cc93b.png)
![2015-07-22_12 12 55](https://cloud.githubusercontent.com/assets/12859334/8823181/165e428a-306b-11e5-9cf9-63c9b7ca45ba.png)
![2015-07-22_12 12 57](https://cloud.githubusercontent.com/assets/12859334/8823177/165af710-306b-11e5-8a38-0244e5d2228e.png)
![2015-07-22_12 12 58](https://cloud.githubusercontent.com/assets/12859334/8823180/165e055e-306b-11e5-8763-e6406c5b9501.png)

If you need anymore info, logs, or other things, tell me.

**Comment by TherminatorX** [comment]
Reproduced with 1.8.6a

**Comment by Adaptivity** [comment]
Can confirm this too.
