### ISSUE TITLE
[CRASH] Smeltery created with WorldEdit odd inventory behaviour and crash

### ISSUE THREAD

**Issue by LyraelRayne** [SlimeKnights/TinkersConstruct#1701]
I created a smeltery structure with a 7x7 base and a 9x9 wall using worldedit. I then replaced two blocks with a smeltery tank and a smeltery controller. The smeltery detected the structure... kind of.

![2015-07-23_20 38 45](https://cloud.githubusercontent.com/assets/11632412/8848507/2a50a04c-317b-11e5-8289-818b6b1c5cfd.png)

Opening the smeltery GUI shows the items in my hotbar as being inside the smeltery.

![2015-07-23_20 40 40](https://cloud.githubusercontent.com/assets/11632412/8848522/48585800-317b-11e5-8696-2b67bf58916c.png)

If I attempt to move one of my hotbar items while this is happening I get a crash. FML-Latest.log: http://pastebin.com/zar9gCcw

The smeltery remains broken if I restart my client without Worldedit.

Minecraft: 1.7.10
Forge 10.13.4.1490 
Mods installed: 
- Tinker's Construct 1.8.5
- Mantle 0.3.2.jenkins184
- (mod_worldeditwrapper_1.2.0_we5.6.2_mc1.7.10.litemod)
- (mod_worldeditcui_1.7.10_00_mc1.7.10.litemod)
- (liteloader-1.7.10_04)

Probably not a huge deal considering that most players won't be building their smeltery using WorldEdit, but I figured it was worth reporting as clearly *something* isn't working right and it might affect other things too. 

Otherwise, fair warning to anyone using WorldEdit. Don't use it to build your smeltery!

**Comment by TherminatorX** [comment]
I reference #1148 for this situation.

**Comment by LyraelRayne** [comment]
Oh cool, I did a search but did not find that one. 

You're correct that WorldEdit is probably causing the behaviour. The WorldEdited seared bricks appear to be being created with the tile entity data of a Smeltery Controller.

This is a worldedit placed brick
![image](https://cloud.githubusercontent.com/assets/11632412/8888735/71d14b64-32fd-11e5-8d8d-2ed23865e0fc.png)

This is a normal (creative mode) placed brick:
![image](https://cloud.githubusercontent.com/assets/11632412/8888740/8b23879e-32fd-11e5-8ca7-a4316100d065.png)

This is a normal (creative mode) placed controller:
![image](https://cloud.githubusercontent.com/assets/11632412/8888764/866f6c8a-32fe-11e5-9f7b-1c7e71fd3db5.png)

**Comment by bonii-xx** [comment]
Yup. Incorrect placement behaviour of the blocks. Doesn't happen if you build it manually.
