### ISSUE TITLE
Crash while mod loading in client

### ISSUE THREAD

**Issue by Antillar** [SlimeKnights/TinkersConstruct#1702]
I use TiC 1.8.6a and Mantle 0.3.2.
After I have updated ExtraUtilities from prehistoric 1.2.2 to newest 1.2.8 client started to crash several seconds after launch. The crash happens on the first stage of mod loading by Forge while TiC is loading.
Crash-report here: http://pastebin.com/1Vs32V5B
And no, I do not use any mods by TeamCoFH.
I have also reported to RWTema, the author of ExtraUtilities, about this problem.

**Comment by bonii-xx** [comment]
Add CofhCore, load order messes up.

**Comment by Antillar** [comment]
It worked, thank you.
