### ISSUE TITLE
Chunks

### ISSUE THREAD

**Issue by lightning02** [SlimeKnights/TinkersConstruct#1703]
Matierials and stuff of your mod will generate only in new chunks? Or even in old chunks of my world?

**Comment by AgentK9** [comment]
Only in new chunks. please post questions on the BC forum: http://mod-buildcraft.com/forums/forumdisplay.php?fid=8

**Comment by bonii-xx** [comment]
Only new chunks, yes.

**Comment by AgentK9** [comment]
ummmmmmmmmmmmmmmm... I'm sorry. TOTAL derp on my part. again, sorry
