### ISSUE TITLE
Tinker's stone blocks behave incorrectly with redstone

### ISSUE THREAD

**Issue by Zyin055** [SlimeKnights/TinkersConstruct#1704]
Screenshots:
http://i.imgur.com/x9Fqvcy.jpg - misbehaving Stone Road
http://i.imgur.com/CacLaWj.jpg - behaves correctly with vanilla Stone

As you can see in the screenshots, the Stone Road block does not conduct redstone the way it should (like a normal Stone block would). The redstone dust attempts to connect to it when it shouldn't, and it doesn't allow redstone on top of it to connect to other redstone dust (at least in this particular setup). I think this also occurs with other blocks like Fancy Polished Stone Brick and Polished Stone Brick and potentially others as these are the only ones I'm using for my build.

It should be noted that I used Chisel 2 to acquire these blocks instead of using Tinker's chisel item.

Modpack: BlastOff! 1.3.3
TConstruct-1.7.10-1.8.2a.jar
Chisel2-2.4.1.40.jar (I manually updated Chisel 2 for this pack)

**Comment by DrZed** [comment]
That's a funny bug, doesn't even look normal at all...

**Comment by C1ffisme** [comment]
> TConstruct-1.7.10-1.8.2a.jar

Does this still affect newer versions?

**Comment by simpson409** [comment]
TConstruct-1.7.10-1.8.8.jar
still happening for me, this is a "Polished Stone Brick"
![2016-08-25_20 59 33](https://cloud.githubusercontent.com/assets/21246918/17982258/60ef753a-6b07-11e6-95ea-54ab3e9ee76e.png)

**Comment by bonii-xx** [comment]
Polished stone bricks aren't from tic2. I guess this can be closed, just open a new one if it happens in TiC2 with some blocks.

**Comment by DrZed** [comment]
TConstruct-1.7.10-1.8.8.jar
AKA 1.7.10 AKA Not supported, lol this was already pointed out
