### ISSUE TITLE
Infinite Seared Stone

### ISSUE THREAD

**Issue by Chefbarbie** [SlimeKnights/TinkersConstruct#1705]
I've seen all the posts about inconsistencies between NEI and TiCon, but this is a straight up duplication. 

http://i.imgur.com/hTP77bM.png 

I started with 32 bricks. I have a conduit from the casting table to the controller. I get about 2.5 bricks per brick.

**Comment by bonii-xx** [comment]
Sounds like a bug in EIO

**Comment by Chefbarbie** [comment]
I can reproduce it with just a smeltery.

**Comment by bonii-xx** [comment]
Wait, seared brick. If I remember correctly TCon does not add smelting for seared brick, but steamworks or mechworks does. Might be the numbers changed and never got updated.
