### ISSUE TITLE
Wrong Crossbow description

### ISSUE THREAD

**Issue by zclimber** [SlimeKnights/TinkersConstruct#1707]
Description of Crossbow in Tool Forge claims "Special ability: Reduced reload time with harder materials", but this is not true: reload time depends only on material of "Crossbow Limb", and the fastest reload times pelong to paper, wood and cactus parts.
Also, comparing Crossbows and Longbows made from same materials, reload time of Crossbow is 0.05-0.15 s bigger that one of a corresponding Longbow, thus "Reload time is bigger with harder materials, but not as big as in other bows" is also false.

**Comment by laz2727** [comment]
It's a small bonus reload speed increase with slow mats like steel, not a
material tip.

**Comment by zclimber** [comment]
@laz2727, "bonus reload speed" means that crossbow's reload is faster then...then what? If comparing to bows: Steel Longbow reloads in 5.4s, Steel Crossbow - in 5.6

**Comment by laz2727** [comment]
Faster than it would if it didn't have it.

**Comment by zclimber** [comment]
The point is that a Longbow reloading speed/material relation is pretty much the same for Crossbows, Longbows and Shortbows, but the latter don't have "Reduced reload time with harder materials" part in description.

**Comment by bonii-xx** [comment]
As already said, it means slower materials get bonus scaling, while all other bows scale linearly.
