### ISSUE TITLE
Custom Modifiers do not work. (Tool Forge does not call functions)

### ISSUE THREAD

**Issue by Speiger** [SlimeKnights/TinkersConstruct#1708]
Fox explaining i did everything how it should be and the Modifier does not get accepted.
Through Testing i figured out that the Tool Forge does not call the Second function at all (validType function in the ItemModifier class)

Here is my modifier class:

https://www.dropbox.com/s/ay58bz7rpk5wbgx/EUMofifier.java?dl=0

The question is, is that a TC error because i return true when it should be right and it still does not give me a result in the tool forge.. And yeah i checked everything in my class if it could be wrong (5 times)

I am using Tinkers Construct 1.8.6a build 790

Thanks for reading

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/crafting/ModifyBuilder.java#L25

Then matches returns false.

**Comment by Speiger** [comment]
Nope i did check if it return true.
The logger did print always Test1 which is directly before the Return true...
So nope...

**Comment by Speiger** [comment]
I did put all the items multible times in and here you see the log...
The function validType would print Test2 (and the canModify if it is returning true prints Test1)
So the question is? What the hell?
```
[19:01:32] [Server thread/INFO] [FML]: Test1
[19:01:32] [Server thread/INFO] [FML]: Test1
[19:01:34] [Client thread/INFO] [FML]: Test1
[19:01:34] [Client thread/INFO] [FML]: Test1
[19:01:34] [Server thread/INFO] [FML]: Test1
[19:01:34] [Server thread/INFO] [FML]: Test1
[19:01:35] [Client thread/INFO] [FML]: Test1
[19:01:35] [Client thread/INFO] [FML]: Test1
[19:01:36] [Server thread/INFO] [FML]: Test1
[19:01:36] [Server thread/INFO] [FML]: Test1
```

**Comment by Speiger** [comment]
And even if i simply return true only (without checking what tool i am modifying only return true) it still says... Nope...

**Comment by bonii-xx** [comment]
I said [matches](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/modifier/ItemModifier.java#L38-L74), not canModify.

**Comment by Speiger** [comment]
my fault... Sry^^ Thanks
