### ISSUE TITLE
Wrong Crossbow accuracy

### ISSUE THREAD

**Issue by zclimber** [SlimeKnights/TinkersConstruct#1709]
The Crossbow is TOO accurate.To be exact, bolts land exactly into the same place, even thought ones used have leave fletching(87.5% accurate). Even a Shortbow arrows with Slime fletching (100% accuracy) land differently.
Series of 5 shoots without cursor moving:
![Crossbow 5 shots, view from distance](https://cloud.githubusercontent.com/assets/13508223/8943781/271522a0-3585-11e5-9fd4-6cf7923c17af.png)
![Crossbow 5 shots, view near target](https://cloud.githubusercontent.com/assets/13508223/8943782/27151eb8-3585-11e5-8a8b-0b0867337069.png)
(What seems to be one bolt is really 5)
![Shortbow 5 shots, view from distance](https://cloud.githubusercontent.com/assets/13508223/8943902/0453decc-3586-11e5-8df0-df2d5310bd0c.png)
![Shortbow 5 shots, view near target](https://cloud.githubusercontent.com/assets/13508223/8943903/0454f0d2-3586-11e5-83f8-fdd7a78ba8da.png)

Distance is 25 blocks. Bolts: iron rod, iron head, leaf fletching
Arrows: wooden rod, steel head, slime fletching
Crossbow, shortbow: iron parts, string bowstring

**Comment by bonii-xx** [comment]
Working as intended.
