### ISSUE TITLE
Some Stone parts cannot be melted

### ISSUE THREAD

**Issue by zclimber** [SlimeKnights/TinkersConstruct#1712]
In Smeltery Stone parts can be smelted yielding 8 mB of Seared Stone per Stone spent, but Stone Crossbow Limb, Stone Crossbow Body, Stone Shuriken, Stone Bow Limb and Stone Arrowhead cannot be melted down in Smeltery.

**Comment by Adaptivity** [comment]
@bonii-xx maybe because these items [missing from here](https://github.com/SlimeKnights/TinkersConstruct/blob/95bb4556a553bf7233d47ae54f48b540a5bf9212/src/main/java/tconstruct/smeltery/TinkerSmeltery.java#L404)? I'm not sure but maybe...

**Comment by bonii-xx** [comment]
Can confirm it's missing. Might be the whole thing was overlooked and it's not only stone parts.

No it's not there, Adaptivity.
