### ISSUE TITLE
Slime islands spawn with purple slime blocks

### ISSUE THREAD

**Issue by RCXcrafter** [SlimeKnights/TinkersConstruct#1718]
Slime islands spawn with purple slime blocks instead of blue like they used to. I did't see anything in the changelog about it so I think it's a bug, sorry if it isn't.
[Image](https://cloud.githubusercontent.com/assets/10962454/9068898/79a91484-3ae6-11e5-9126-90ea5b0b6400.png)

**Comment by laz2727** [comment]
It's not.

**Comment by bonii-xx** [comment]
You're correct that they used to be blue. It was a bug, but we liked it enough to keep it. ;)
