### ISSUE TITLE
Missing Forge?

### ISSUE THREAD

**Issue by PheonixLord27** [SlimeKnights/TinkersConstruct#1719]
I tried to install the mod into a modpack i am creating for my friends and i but when ever i start minecraft it gives me this issue. 
![issue](https://cloud.githubusercontent.com/assets/13680603/9115370/bd6607a8-3c2c-11e5-8de0-9806e2af728a.png)

I am running 1.7.10-Forge10.13.2.1347-1.7.10 and any help someone could offer would be appreciated.

**Comment by MrKunji** [comment]
Forge's Recommend version is already 1448, you really should update.

**Comment by bonii-xx** [comment]
This should be no surprise, but 1347 is less than 1384.

**Comment by PheonixLord27** [comment]
Welp xD apparently MC doesn't auto select the forge when i install it...

**Comment by PheonixLord27** [comment]
I feel like an idiot...

**Comment by bonii-xx** [comment]
It happens ;P

**Comment by PheonixLord27** [comment]
On the bright side i finally get to use tinkers again
