### ISSUE TITLE
Modifier not applying

### ISSUE THREAD

**Issue by Elvarion** [SlimeKnights/TinkersConstruct#1721]
Not sure if this is Tinkers, Iguana or ExtraUtilities fault. But ill post it here since the main mod is after all Tinkers Construct

ExtraUtilities now adds Magical Wood, This material gives alot of modifiers. However it doesn't work if you want to replace something on an already complete tool to get the added modifier. (Using IguanaTweaks to replace parts)

Example: Pick made of the following parts
Wood PickHead, Wooden Binding, Wooden Toolrod > 1 Modifier
Wood PickHead, Wooden Binding, Magical Woodrod > 2 Modifiers

If I replace the Binding with paper I get +1 modifier

However If I replace the normal wooden toolrod with a Magical Wood rod I wont get the addition modifier.

So If you dont use Magical wood when making the actual tool you loose out on modifiers

(Said Thermal instead of ExtraUtilities)

**Comment by laz2727** [comment]
That's either Iguana(if paper/thamium does that) or ExU. Oh, and Magical
Wood is vanilla ExU.

2015-08-08 23:53 GMT+06:00 Elvarion <notifications@github.com>:

**Comment by Elvarion** [comment]
(Yea ofc its ExtraUtilities, bit tired it seems xD)
Thaumium work as intended on an already crafted tool, It will add another modifier.

**Comment by bonii-xx** [comment]
ITT doesn't support any 3rd party materials/traits.
