### ISSUE TITLE
NullPointerException when using getSubItems() on certain items

### ISSUE THREAD

**Issue by wesserboy** [SlimeKnights/TinkersConstruct#1724]
I am working on a new mod, and since it was reaching the point of a first release i wanted to test it's interaction with other mods. But in combination with tinker's construct it crashed because of a nullPointer.
crashlog:
http://pastebin.com/zSL6yxwg
(I was using Minecraft version 1.7.10, Forge version 10.13.4.1492 and Tconstruct version 1.8.5)

I decided to load Tconstruct into my dev environment to further investigate the problem. After surrounding my code which called the getSubItems() in a try catch i found out that there were only two items in tinkers which caused this problem, the frying pan and the hammer.
try-catch stacktraces can be found here:
http://pastebin.com/edRtEXbq
(in my dev environment I am using forge version 10.13.4.1448, the other versions are the same as in the previous case)
Since the stacktraces are the same as in the test instance I don't think the forge version is related.

When i browsed through the Tcon source code i found out that it was the exact same line of code causing the crash in both cases: NBTTagCompound tags = tool.getTagCompound().getCompoundTag("InfiTool");

I decided to look in which case 'tool' would be null, but there were a lot of cases so i wasn't able to pin down the problem further from here. But you are probably more familiar with how that code works than i am ;)

Because of the fact that all the other mods I tested with worked fine and that all other items in Tcon worked fine, I am assuming that the problem is on Tcon's end rather than mine, and this is why i decided to submit an issue.

My mod's source code is not on github. (because i have no idea how to set it up :P)
But i can copy any part of it into a pastebin if you need it.
It's also not released yet, but if you need a jar to test with i can quickly upload the one i tested with to dropbox. So just ask if you need anything.

For now i can work around the crash by putting these items in the blacklist by default, but if we can fix the problem it would of course be better :)

-wesserboy

**Comment by bonii-xx** [comment]
I hope you realize that getSubItems is a ClientSide only (aka it'll crash if you call it on a server) function that's only used by the creative menu/NEI and that's only called after the game has been loaded. Calling it anytime before (like you're doing during Init? PostInit? apparently) is invalid and bound to cause undefined behaviour.

**Comment by wesserboy** [comment]
Thank you so much for pointing that out, I am a massive derp and completely forgot to check if any methods are ClientSide only, and i have only tested my mod in singleplayer, which is the reason I didn't realize my terrible mistake...

I am sorry for bothering you with my 'relatively-new-to-minecraft-modding' problems.
I will rewrite my system that constructs the item list to only be run on the client, I think this will also make sure it will not be called before the game has been loaded (before i was calling it during init).

When I'm done I will test it with tinkers again, do you want me to report wether it fixed the issue?
if not, you can close the issue ;) .

**Comment by bonii-xx** [comment]
I'll just close it, you can always make a new one. And yes, that's a typical newcomer mistake ,which is why I pointed it out. ;)
