### ISSUE TITLE
game crashes when i try to use smeltery

### ISSUE THREAD

**Issue by Iv4npr** [SlimeKnights/TinkersConstruct#1725]
Whenever i try to smelt an ore in the smeltery, my game crashes, it has never happened before but now i cant play this mod to its full extent. 

This is the crash report

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/10/15 5:06 PM
Description: Updating screen events

java.lang.NoClassDefFoundError: mantle/utils/ItemMetaWrapper
	at tconstruct.library.crafting.Smeltery.getLiquifyTemperature(Smeltery.java:139)
	at tconstruct.smeltery.logic.SmelteryLogic.updateTemperatures(SmelteryLogic.java:566)
	at tconstruct.smeltery.logic.SmelteryLogic.func_70296_d(SmelteryLogic.java:704)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at tconstruct.smeltery.inventory.SmelteryContainer.func_75135_a(SmelteryContainer.java:270)
	at tconstruct.smeltery.inventory.SmelteryContainer.func_82846_b(SmelteryContainer.java:159)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at tconstruct.smeltery.gui.SmelteryGui.func_73864_a(SmelteryGui.java:528)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.library.crafting.Smeltery.getLiquifyTemperature(Smeltery.java:139)
	at tconstruct.smeltery.logic.SmelteryLogic.updateTemperatures(SmelteryLogic.java:566)
	at tconstruct.smeltery.logic.SmelteryLogic.func_70296_d(SmelteryLogic.java:704)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at tconstruct.smeltery.inventory.SmelteryContainer.func_75135_a(SmelteryContainer.java:270)
	at tconstruct.smeltery.inventory.SmelteryContainer.func_82846_b(SmelteryContainer.java:159)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at tconstruct.smeltery.gui.SmelteryGui.func_73864_a(SmelteryGui.java:528)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: tconstruct.smeltery.gui.SmelteryGui

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Iv4npr'/3974, l='MpServer', x=-260.77, y=64.62, z=239.36]]
	Chunk stats: MultiplayerChunkCache: 690, 690
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-248,64,252), Chunk: (at 8,4,12 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7916 game time, 7916 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 100 total; [EntityDryad['Dryad'/86051, l='MpServer', x=-267.50, y=23.00, z=237.50], EntityDryad['Dryad'/86052, l='MpServer', x=-307.50, y=67.00, z=216.50], EntityItem['item.item.slimeball'/38986, l='MpServer', x=-226.28, y=25.13, z=244.72], EntityCreeper['Creeper'/92237, l='MpServer', x=-298.50, y=15.00, z=259.50], EntityWolf['Wolf'/63565, l='MpServer', x=-314.50, y=67.00, z=215.50], EntityCreeper['Creeper'/92236, l='MpServer', x=-296.50, y=15.00, z=260.50], EntityWolf['Wolf'/63567, l='MpServer', x=-317.50, y=67.00, z=213.50], EntityWolf['Wolf'/63569, l='MpServer', x=-319.50, y=67.00, z=213.50], EntityWolf['Wolf'/63570, l='MpServer', x=-319.50, y=67.00, z=215.50], EntityBat['Bat'/94291, l='MpServer', x=-213.23, y=11.76, z=270.75], EntityWolf['Wolf'/63571, l='MpServer', x=-310.59, y=66.00, z=219.00], EntityBat['Bat'/94294, l='MpServer', x=-221.03, y=15.00, z=272.55], EntityCreeper['Creeper'/98471, l='MpServer', x=-253.50, y=17.00, z=286.50], EntitySkeleton['Skeleton'/98473, l='MpServer', x=-248.93, y=17.00, z=295.42], EntityCreeper['Creeper'/98472, l='MpServer', x=-259.50, y=17.00, z=285.50], EntityCreeper['Creeper'/92341, l='MpServer', x=-224.50, y=31.00, z=267.50], EntityCreeper['Creeper'/92340, l='MpServer', x=-224.50, y=31.00, z=265.50], EntityCreeper['Creeper'/71889, l='MpServer', x=-290.50, y=22.00, z=304.50], EntityItem['item.item.ninjaDagger'/73937, l='MpServer', x=-270.94, y=40.13, z=248.97], EntityZombie['Zombie'/94443, l='MpServer', x=-279.06, y=17.00, z=252.50], EntityBat['Bat'/51478, l='MpServer', x=-323.59, y=20.10, z=293.53], EntityCreeper['Creeper'/94522, l='MpServer', x=-196.22, y=11.00, z=214.91], EntityCreeper['Creeper'/94524, l='MpServer', x=-191.34, y=11.00, z=220.09], EntityCow['Cow'/92509, l='MpServer', x=-317.50, y=67.00, z=204.50], EntitySheep['Sheep'/92511, l='MpServer', x=-323.78, y=64.00, z=194.53], EntityCow['Cow'/92510, l='MpServer', x=-312.50, y=67.00, z=204.50], EntityPig['Pig'/92513, l='MpServer', x=-322.50, y=64.00, z=193.78], EntityPig['Pig'/92515, l='MpServer', x=-330.75, y=64.00, z=198.91], EntityPig['Pig'/92514, l='MpServer', x=-326.78, y=64.00, z=195.72], EntityDryad['Dryad'/92517, l='MpServer', x=-316.91, y=66.00, z=197.47], EntityPig['Pig'/92516, l='MpServer', x=-334.09, y=64.00, z=203.06], EntityZombie['Zombie'/88425, l='MpServer', x=-300.97, y=54.00, z=215.50], EntityZombie['Zombie'/88427, l='MpServer', x=-307.50, y=58.00, z=204.50], EntityZombie['Zombie'/98779, l='MpServer', x=-225.50, y=18.00, z=175.50], EntityItem['item.item.ninjaDagger'/74202, l='MpServer', x=-270.72, y=40.13, z=248.53], EntityZombie['Zombie'/98780, l='MpServer', x=-227.84, y=18.00, z=174.34], EntityZombie['Zombie'/78380, l='MpServer', x=-253.50, y=13.00, z=185.50], EntityDryad['Dryad'/27219, l='MpServer', x=-268.50, y=12.00, z=239.50], EntityDryad['Dryad'/27220, l='MpServer', x=-292.50, y=63.00, z=211.50], EntityDryad['Dryad'/39519, l='MpServer', x=-297.50, y=19.00, z=233.50], EntityDryad['Dryad'/39520, l='MpServer', x=-303.50, y=17.00, z=239.22], EntityDryad['Dryad'/39521, l='MpServer', x=-295.44, y=19.00, z=235.69], EntityItem['item.item.walkerSword'/35456, l='MpServer', x=-256.81, y=60.13, z=254.28], EntityZombie['Zombie'/35462, l='MpServer', x=-207.50, y=16.00, z=309.50], EntityCreeper['Creeper'/92821, l='MpServer', x=-298.50, y=53.00, z=216.50], EntityCreeper['Creeper'/92822, l='MpServer', x=-301.50, y=53.00, z=219.50], EntityZombie['Zombie'/94937, l='MpServer', x=-228.31, y=16.00, z=256.09], EntitySkeleton['Skeleton'/90859, l='MpServer', x=-281.50, y=12.00, z=193.50], EntitySkeleton['Skeleton'/90858, l='MpServer', x=-281.50, y=12.00, z=194.50], EntitySkeleton['Skeleton'/94954, l='MpServer', x=-288.50, y=15.00, z=246.50], EntityZombie['Zombie'/94957, l='MpServer', x=-288.50, y=15.00, z=245.50], EntityBat['Bat'/90870, l='MpServer', x=-322.61, y=21.82, z=180.78], EntitySkeleton['Skeleton'/99107, l='MpServer', x=-238.50, y=16.00, z=290.50], EntitySkeleton['Skeleton'/99109, l='MpServer', x=-240.71, y=16.00, z=294.69], EntitySkeleton['Skeleton'/99108, l='MpServer', x=-239.50, y=16.00, z=290.50], EntityBat['Bat'/95043, l='MpServer', x=-243.48, y=28.01, z=229.52], EntitySquid['Squid'/41816, l='MpServer', x=-278.66, y=53.34, z=182.19], EntityItem['item.item.emerald'/43904, l='MpServer', x=-256.59, y=55.13, z=258.03], EntityBat['Bat'/68481, l='MpServer', x=-244.25, y=27.10, z=234.25], EntityItem['item.item.goldNugget'/43905, l='MpServer', x=-257.72, y=58.13, z=254.41], EntityItem['item.item.arrow'/27576, l='MpServer', x=-218.13, y=16.13, z=178.47], EntityItem['item.item.bone'/27577, l='MpServer', x=-218.25, y=16.13, z=178.72], EntityZombie['Zombie'/95225, l='MpServer', x=-294.50, y=14.00, z=257.50], EntityEnderman['Enderman'/80897, l='MpServer', x=-294.50, y=11.00, z=261.50], EntitySkeleton['Skeleton'/89155, l='MpServer', x=-243.22, y=21.00, z=260.75], EntitySkeleton['Skeleton'/89158, l='MpServer', x=-236.50, y=22.00, z=260.50], EntityCreeper['Creeper'/87146, l='MpServer', x=-276.50, y=14.00, z=262.50], EntityBat['Bat'/97419, l='MpServer', x=-262.14, y=17.15, z=296.25], EntityBat['Bat'/97418, l='MpServer', x=-223.51, y=15.60, z=279.57], EntityBat['Bat'/97420, l='MpServer', x=-242.43, y=17.00, z=296.34], EntityCreeper['Creeper'/97433, l='MpServer', x=-275.50, y=14.00, z=261.50], EntitySkeleton['Skeleton'/72856, l='MpServer', x=-197.50, y=19.00, z=315.31], EntityCreeper['Creeper'/97432, l='MpServer', x=-276.50, y=14.00, z=263.50], EntityZombie['Zombie'/97436, l='MpServer', x=-235.50, y=16.00, z=256.50], EntitySquid['Squid'/42156, l='MpServer', x=-319.50, y=49.31, z=224.88], EntityDryad['Dryad'/72906, l='MpServer', x=-311.34, y=63.00, z=297.63], EntityCreeper['Creeper'/77002, l='MpServer', x=-282.50, y=13.00, z=261.50], EntityDryad['Dryad'/72910, l='MpServer', x=-299.53, y=63.00, z=300.56], EntityBat['Bat'/95477, l='MpServer', x=-279.53, y=17.49, z=253.47], EntitySquid['Squid'/42237, l='MpServer', x=-223.16, y=52.31, z=273.63], EntityCreeper['Creeper'/91466, l='MpServer', x=-192.50, y=15.00, z=249.50], EntityZombie['Zombie'/93529, l='MpServer', x=-289.50, y=26.00, z=316.50], EntityCreeper['Creeper'/93564, l='MpServer', x=-300.50, y=16.00, z=159.50], EntityEnderman['Enderman'/91568, l='MpServer', x=-318.00, y=18.00, z=302.50], EntitySkeleton['Skeleton'/89557, l='MpServer', x=-292.50, y=26.00, z=318.50], EntityCreeper['Creeper'/89560, l='MpServer', x=-296.50, y=26.00, z=317.50], EntityZombie['Zombie'/71158, l='MpServer', x=-239.50, y=15.00, z=175.50], EntitySquid['Squid'/42547, l='MpServer', x=-321.22, y=62.38, z=235.50], EntitySquid['Squid'/42565, l='MpServer', x=-252.28, y=59.25, z=294.97], EntitySkeleton['Skeleton'/97911, l='MpServer', x=-279.50, y=40.00, z=222.50], EntityBat['Bat'/71328, l='MpServer', x=-292.25, y=25.10, z=306.25], EntityCreeper['Creeper'/69335, l='MpServer', x=-285.50, y=13.00, z=250.50], EntitySkeleton['Skeleton'/91953, l='MpServer', x=-308.50, y=57.00, z=214.50], EntityZombie['Zombie'/91954, l='MpServer', x=-292.41, y=27.00, z=252.94], EntityCreeper['Creeper'/79679, l='MpServer', x=-234.50, y=17.00, z=173.50], EntityZombie['Zombie'/98167, l='MpServer', x=-320.99, y=30.00, z=315.04], EntityClientPlayerMP['Iv4npr'/3974, l='MpServer', x=-260.77, y=64.62, z=239.36], EntityTrail['unknown'/3977, l='MpServer', x=-260.77, y=64.62, z=239.36], EntitySkeleton['Skeleton'/92097, l='MpServer', x=-326.78, y=21.00, z=183.25], EntityCreeper['Creeper'/92100, l='MpServer', x=-336.50, y=23.00, z=183.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 136408864 bytes (130 MB) / 912101376 bytes (869 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAAAAAAA	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAAAAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAAAAAAA	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAAAAAAA	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
	UCHIJAAAAAAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAAAAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102(1).jar) 
	UCHIJAAAAAAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAAAAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAAAAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-11.jar) 
	UCHIJAAAAAAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHIJAAAAAAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAAAAAAA	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) 
	UCHIJAAAAAAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAAAAAAA	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	Mantle{1.7.10-165.4bc3343} [Mantle] (Mantle_mc1.7.10_0.3.0.jar) 
	UCHIJAAAAAAAAA	minechem{5.0.5.108} [Minechem] (Minechem-5-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	TwilightForest{2.2.3} [The Twilight Forest] (Twilight-Forest-Mod-1.7.2.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) 
	UCHIJAAAAAAAAA	Morph{0.9.1} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAAAAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAAAAAAA	PortalGun{4.0.0-beta-5} [PortalGun] (PortalGun-4.0.0-beta-5.jar) 
	UCHIJAAAAAAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (ReiMinimap-1.7.10-3.6.jar) 
	UCHIJAAAAAAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAAAAAAA	TConstruct{1.7.10-1.8.2.build857} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2.jar) 
	UCHIJAAAAAAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAAAAAAA	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJAAAAAAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3(1).jar) 
	UCHIJAAAAAAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3325' Renderer: 'Intel(R) HD Graphics 2500'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	MineFactoryReloaded: Lacking version information.
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.1.0-161
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1492-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 2500 GL version 4.0.0 - Build 10.18.10.3325, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Cherry** [comment]
Your Mantle version is outdated. Update it and the issues should go away.

**Comment by bonii-xx** [comment]
Update tinkers and mantle.

**Comment by Iv4npr** [comment]
Thanks

2015-08-10 22:41 GMT-07:00 boni <notifications@github.com>:
