### ISSUE TITLE
Crafting on a server

### ISSUE THREAD

**Issue by lordkeg** [SlimeKnights/TinkersConstruct#1727]
Hello all.

So, fresh server, freshly downloaded Mods, no crashes, but when i try to craft a tinker's table it will not allow it to be placed in an inventory. I can create a regular table, put it in and try to craft the tinker's one and it wont allow it to be placed in an inventory.. any ideas?

**Comment by lordkeg** [comment]
Have tested this in single player and it works fine btw

**Comment by bonii-xx** [comment]
Check your mods on the server. It's not a tinkers problem for sure.
