### ISSUE TITLE
Swords don't sheat as swords with Battlegear

### ISSUE THREAD

**Issue by AlterAkima** [SlimeKnights/TinkersConstruct#1730]
I assume applying one more interface form the Battlegear's API can make swords sheat on the player's hip, because at the moment they sheat at the back, behind the shields.

**Comment by DrZed** [comment]
" because at the moment they sheat at the back, behind the shields."
IMO that's not actually bad nor an issue at all. Hell I love it, it makes sense, and looks nice :D
