### ISSUE TITLE
i found this between mob amuptation andthis mod i will give openeye  link i have 

### ISSUE THREAD

**Issue by dragun108** [SlimeKnights/TinkersConstruct#1733]
http://openeye.openmods.info/crashes/d3a85851b3e50e572669a03bf5aa21b6

please reveiw link tell is it you or the ichun i need contact i probably will submit this to him as well ^^

**Comment by dragun108** [comment]
http://pastebin.com/WjE6dG1D
 a pastebin incase anything is ever missing from openeye?

**Comment by bonii-xx** [comment]
#1153
