### ISSUE TITLE
Gravel Ores make grass render with snow

### ISSUE THREAD

**Issue by AlterAkima** [SlimeKnights/TinkersConstruct#1734]
![](http://i.imgur.com/o8OCqzy.png)

Confirmed by a friend in a clean instance:

![](http://i.imgur.com/jT9Gf3H.png)

**Comment by TherminatorX** [comment]
What the heck?
Definitely confirmed in the latest...

**Comment by bonii-xx** [comment]
Plot twist: Gravel ores are actually snow

**Comment by TherminatorX** [comment]
@bonii-xx I saw that comment coming.

......

Wait, I'm actually looking at the code now and it uses Material.craftedSnow. WTH. Why are we doing that again?

**Comment by mDiyo** [comment]
This is a workaround to make vanilla and other modded shovel harvesting levels work on them.
