### ISSUE TITLE
Font size of ammo looks too small for Unicode

### ISSUE THREAD

**Issue by oldjunyi** [SlimeKnights/TinkersConstruct#1735]
Tested under 1600 x 900 Fullscreen, GUI Scale: Large (same as auto)
Maybe set the GL scale ratio to 1.0 will make it looks better
![uff-tic](https://cloud.githubusercontent.com/assets/641817/9501552/8f9ca704-4c5e-11e5-9d00-0d57060a3da4.png)

**Comment by bonii-xx** [comment]
Oh jeez, that's an old ticket. Anyway we don't display text on those anymore.
