### ISSUE TITLE
Hearts broken when more health+dragonAPI+TiC are loaded

### ISSUE THREAD

**Issue by Ianaver** [SlimeKnights/TinkersConstruct#1739]
Normally there are no colored hearts when using the More Health Enchanted mod even with TiC as it has a different HUD that uses Row # and hearts, however after updating TiC to v1.8.7 and running those two mods in conjunction to dragonAPI (v7f) things get weird... v1.8.5 of TiC worked. Also, when I ran with 1.8.5 I had to remove an image from dragonAPI under DragonAPI/resources/gui.png which caused the original issue

DragonAPI is the main culprit however TiC is also involved this time

Take a look at the original issue here
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/189#issuecomment-135624069

**Comment by DrZed** [comment]
lol, but this won't be fixed for 1.7 unless one of the devs get bored or wanna prove me wrong...
This isn't a bug that is game breaking, is it? So it probably isn't worth spending time on when a rewrite is underway.

**Comment by Ianaver** [comment]
true.. I actually forgot that the rewrite was going on :P oh well...

**Comment by DrZed** [comment]
That was a quick response xD.

**Comment by Ianaver** [comment]
yeah... I will leave it closed for now unless for some reason one of them gets bored and wants to fix this or this happens in 1.8
