### ISSUE TITLE
[Feature Request]IGW (In-Game Wiki) support

### ISSUE THREAD

**Issue by soulgriever** [SlimeKnights/TinkersConstruct#1741]
![2015-08-28_21 23 41](https://cloud.githubusercontent.com/assets/2360198/9559882/2321693e-4dcb-11e5-8a45-0422c23e0dea.png)
![2015-08-28_21 23 58](https://cloud.githubusercontent.com/assets/2360198/9559883/2323a6ea-4dcb-11e5-88d9-5d5948837c5d.png)
Wiki in game you can press I and view description of block you are looking at also good for explaining on how to use machines or tools such as book press
https://github.com/MineMaarten/IGW-mod

**Comment by Techokami** [comment]
...why? Tinker's Construct already has an in-game wiki, in the form of the guidebooks.

**Comment by laz2727** [comment]
Which breaks after every change...

2015-08-29 20:22 GMT+06:00 Christopher Trumbour <notifications@github.com>:

**Comment by ShadowDrakken** [comment]
Please don't change to IGW. At least not until the author fixes how ugly and clunky it is. The current TCon solution is MUCH nicer.

If anything, implementing Botania's library would make much more sense.
