### ISSUE TITLE
[Feature Request] A way to disable a modifier, for example the Flux Capacitor Modifier

### ISSUE THREAD

**Issue by ExDomino** [SlimeKnights/TinkersConstruct#1742]
On my server, we need to disable flux capacitor modifiers to prevent tinker's tool to being powered by a powerful resonant flux capacitor that make tools to last almost forever. But there is no option to disable them completely and the only way to do that at this moment is removing the crafting receipe of all flux capacitors with minetweaker. The ability of recharging a tinker's tool is really a big problem!

**Comment by MrKunji** [comment]
There's a config option called 'Balanced Flux modifier' that limits tools to a Hardened Capacitor.

**Comment by ExDomino** [comment]
But you can have an enabled Resonant Flux Capacitor in your inventory and even if your tools only have a Leadstone Flux Capacitor as modifier, they will last almost forever with the large amount of power given by the Resonant Flux Capacitor in your hands.

**Comment by laz2727** [comment]
Leadstone doesn't really have the charge speed big enough to properly work
with high-speed broad tools.

2015-09-04 15:14 GMT+06:00 ExDomino <notifications@github.com>:

**Comment by ExDomino** [comment]
But hardened and redstone have. Could you just add an option please? ^^

**Comment by bonii-xx** [comment]
No plans to add any additional configs.

**Comment by ExDomino** [comment]
Really nice, thanks you. =ironic=
