### ISSUE TITLE
Scythe only fires a break event on the block it breaks and not the adjacent ones

### ISSUE THREAD

**Issue by AfterWind** [SlimeKnights/TinkersConstruct#1744]
If a block is broken in the world an event should be fired. With this implemented the protection check is much faster and there shouldn't be anyone that is affected by this. Please implement it or at least consider.

The event is either fired or the cancel of it is not handled properly

**Comment by bonii-xx** [comment]
Requires updating of the Scythe blockbreak code. Should be the same as the ones for regular blocks/other AOE tools.
