### ISSUE TITLE
Crash while making smeltery

### ISSUE THREAD

**Issue by giuseppeM99** [SlimeKnights/TinkersConstruct#1745]
I will crashed by placing a block of smeltery
http://openeye.openmods.info/crashes/167c1ba19a0658bcaf70f1b2c1b3094d

**Comment by TherminatorX** [comment]
Were you using two TiC versions at the same time?
A problem with OpenEye is that it doesn't list mod versions, like vanilla logs do. Post a normal crash log as well, please.

**Comment by giuseppeM99** [comment]
Here is the crash report: http://pastebin.com/vXTvSW6v
I've installed the 1.7.10-1.8.7 version on clients and server

**Comment by alexbegt** [comment]
What block do you place, and do you have a smeltery already built or?
