### ISSUE TITLE
Permission Request

### ISSUE THREAD

**Issue by Speiger** [SlimeKnights/TinkersConstruct#1749]
I am making a Mod and add a little feature to it.
Custom Decorative Signs, and my texturer made also a Tinkers Construct one.
And what i want to ask can i use that in my mod?
(Just permission wise i want to be sure that i can put it in)
If you want to see one then just ask. I am not showing it here just permission wise^^

**Comment by bonii-xx** [comment]
All textures are licensed under the [CC3.0](http://creativecommons.org/licenses/by/3.0/)

**Comment by Speiger** [comment]
@bonii-xx https://twitter.com/SpeigerCut/status/645081110456717312

**Comment by Speiger** [comment]
Did you see it @bonii-xx ?. How do you like it?
