### ISSUE TITLE
inventoy bug?

### ISSUE THREAD

**Issue by stclaus4** [SlimeKnights/TinkersConstruct#1750]
so the problem is when I open my world every button activates the bug. and the Tc inventory is all ways open I need to hold down esc to leave it and if I release the button the gui opens again so I need to simple close the game to get out of it.

**Comment by MrKunji** [comment]
Are you using Not Enough Keys?

**Comment by stclaus4** [comment]
yes is that a bug with it?

**Comment by stclaus4** [comment]
I'm tring to get a log as we speek

**Comment by MrKunji** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/1748

**Comment by stclaus4** [comment]
ok thanks do I need to roll back not enough keys or Tc?

**Comment by stclaus4** [comment]
nvm I got it
