### ISSUE TITLE
TC Armor Tab

### ISSUE THREAD

**Issue by funman300** [SlimeKnights/TinkersConstruct#1753]
Whenever I enter my world and press any button whether it be to move or open an inventory, the game forcibly opens TC armor tab. I changed the keys binds to see if that would work, to no success. I removed all addons for TC. That didn't work either. Whats really odd is there is no log on this event happening.

**Comment by MrKunji** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/1748

**Comment by funman300** [comment]
Thanks for helping me....
