### ISSUE TITLE
[Rework]RGB Fluids?

### ISSUE THREAD

**Issue by DrZed** [SlimeKnights/TinkersConstruct#1757]
Could you make a grayscale fluid that is colored via RGB?
Similar to the way I do my ores/blocks/ingots/everything in HxCWorldGen?
Also Make the smeltery internal rendering capable of such things my blocks render gray in your smeltery.

If I make it capable in the old TiC and submit a PR would you release the update?

**Comment by bonii-xx** [comment]
The rework will contain whatever makes sense API wise or is needed for TCon. Chances are good for general colorable liquid textures. No I'd not accept such a PR, I'm not accepting any PRs for 1.7.10 unless they're severe.

**Comment by DrZed** [comment]
Well thank you at least for giving me a response. :P
