### ISSUE TITLE
bug with pattern chest's texture

### ISSUE THREAD

**Issue by djm78** [SlimeKnights/TinkersConstruct#1761]
Hi ! I have a bug with, as say in the title, the pattern chest. The texture is not loading right (see the screenshot).  The Minecraft version is 1.7.10, the version of Forge is 10.13.4.1492 and the Tinkers' Construct one is 1.6.0d40.1. Hope you can help me !
![2015-09-26_14 27 50](https://cloud.githubusercontent.com/assets/10297897/10117581/69478ebe-645c-11e5-8a7b-d57e9e9755e4.png)

**Comment by MrKunji** [comment]
Update Tinkers', the chest model was changed some time ago.
http://www.curse.com/mc-mods/minecraft/tinkers-construct/2253057

**Comment by djm78** [comment]
ok, thank you !
