### ISSUE TITLE
Alumite smeltery issue

### ISSUE THREAD

**Issue by EfficiencyVI** [SlimeKnights/TinkersConstruct#1762]
When you put 5 aluminum and 2 iron in the smeltery and add a bucket of water and lava you get obsidian, but this obsidion does not mix to alumite. When you cast the obsidian to ingots and smelt it again, it works fine.

Tested with TConstruct-1.7.10-1.8.7 and IguanaTinkerTweaks-1.7.10-2.1.5.

**Comment by bonii-xx** [comment]
Fixed in 1.8
