### ISSUE TITLE
Silver Hammer won't repair

### ISSUE THREAD

**Issue by DeathCorps69** [SlimeKnights/TinkersConstruct#1767]
I've tested this on both single and multiplayer. I've crated a silver hammer and there is no way to repair it, i've tried ingots and suggest. I've also tried using the /repair command which didn't work either. Making other tools out of silver work perfectly fine. 
Mods directly related to TiC:
TConstruct 1.8.7
IguanaTinkerTweaks 2.1.4 DEV 0edeedd
TiCTooltips 1.2.5
TMechworks 0.2.14.100
Forge 10.13.4.1448
Mantle 0.3.2

I have some images show the problem, i've also tried both silver's i have as well.
http://prntscr.com/8mejld
http://prntscr.com/8mek6o
http://prntscr.com/8mekob
http://prntscr.com/8mekui

Let me know if there is anything else that will help.

**Comment by bonii-xx** [comment]
Update whatever mod adds silver tool parts.

**Comment by DeathCorps69** [comment]
I think that would be ExtraTiC - 1.4.5 which i am at. Should I be posting this bug to them instead?

**Comment by UndeadZeratul** [comment]
Thermal Foundation adds a silver material as well, maybe they conflict?

**Comment by DeathCorps69** [comment]
I've tried both versions of the material, i still find it weird that the hammer is the only tool (that i've found) affected by this. Because i'm using both thermal foundation and matallurgy.

**Comment by DeathCorps69** [comment]
Also thermal foundation and matallurgy and the material but ExtraTiC adds the actual mod support.

**Comment by bonii-xx** [comment]
Thermal Foundation is adding the silver. Make sure you're up to date.

**Comment by DeathCorps69** [comment]
thermal foundation is already up-to-date, i also updated metallurgy but no change.
