### ISSUE TITLE
Bugs with RotaryCraft integration.

### ISSUE THREAD

**Issue by OneEyeMaker** [SlimeKnights/TinkersConstruct#1768]
Hello.
I found some bugs with RotaryCraft integration. I don't know, on which side problems are. I've already reported this issue to @ReikaKalseki .
You can find all information here: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/293

**Comment by ReikaKalseki** [comment]
In essence, it appears my handlers are incomplete, and I need to know where and how.

**Comment by bonii-xx** [comment]
Are you [adding stats for the ranged weapons](https://gist.github.com/bonii-xx/e46f9d9e81e29d796b1b#file-toolmaterials-L16-L25)?

For the crash it seems like [the check in CraftingItem](https://github.com/SlimeKnights/Mantle/blob/master/src/mantle/items/abstracts/CraftingItem.java#L49) is faulty. Where the metadata comes from is probably on your side though.

**Comment by ReikaKalseki** [comment]
The `>` should probably be `>=`. But as for the metadata, am I not correct in that metadatas of all TiC parts are the material ID?

**Comment by bonii-xx** [comment]
Yup, they should be. But as you can see in the crashreport it was 5.. on an item that has less than 5 set. I'd say it was not a toolpart that caused the crash. Also the log only shows NEI there.

**Comment by ReikaKalseki** [comment]
I have replicated the crash, and it is on 3, not 5, and the metadata of the parts I create is all either 80 or 81 (bedrock and HSLA IDs):

> Also, the crash is a crash from Mantle on index 3, not 81, so I am not convinced it is related to this.

**Comment by bonii-xx** [comment]
Fixed the array access in https://dvs1.progwml6.com/jenkins/job/Mantle_Gradle/191/artifact/build/libs/Mantle-1.7.10-0.3.2.jenkins191.jar
Maybe that lets us find out what item is broken. All I can tell you is that it's trying to display a Fletchling that doesn't exist.

**Comment by ReikaKalseki** [comment]
Material ID 3 is flint, something I never interact with.

**Comment by bonii-xx** [comment]
Not for fletchlings. https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/items/Fletching.java

**Comment by ReikaKalseki** [comment]
I take it fletchings are a different sort of item, not really a normal tool part?

**Comment by bonii-xx** [comment]
They are normal toolparts, but they use a different set of materials.

**Comment by ReikaKalseki** [comment]
I will exclude the fletchings from both of my materials and see if this fixes the issue. As it happens, a v9c is coming.

**Comment by bonii-xx** [comment]
[Bowstring](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/items/Bowstring.java) underlies the same restrictions. Also the shafts for arrows, but those don't exist as items and should therefore not create any problems.

**Comment by ReikaKalseki** [comment]
OK, this should be fixed in v9c. Hopefully.

**Comment by ReikaKalseki** [comment]
So...what NBT tags do I need to manually add?

**Comment by bonii-xx** [comment]
What NBT tags? The parts don't have any NBT, only the tools themselves.

**Comment by ReikaKalseki** [comment]
@OneEyeMaker reported certain parts missing "required features" and linked an image of incomplete tooltips, implying missing NBT.

> And I noticed, that parts (from Bedrock Alloy/HSLA Steel) haven't all required features.
> Compare this:
> http://i.imgur.com/4ElKqNn.png
> and this:
> http://i.imgur.com/r8SwZnY.png

Additionally, the missing elements correspond to material properties, which I know are part of the InfiTool tag. But if the parts have no NBT, what else would cause this?

**Comment by squeek502** [comment]
@ReikaKalseki those tooltips come from my [TiC Tooltips mod](https://github.com/squeek502/TiC-Tooltips). Here's [the relevant code](https://github.com/squeek502/TiC-Tooltips/blob/1.7.10/java/squeek/tictooltips/TooltipHandler.java#L323-L332) that it uses:

```
toolTip.add(StringHelper.getLocalizedString("gui.toolstation2") + ToolPartHelper.getDurabilityString(mat.durability()));
BowMaterial bowMat = TConstructRegistry.getBowMaterial(matID);
if (bowMat != null)
{
	toolTip.add(StringHelper.getLocalizedString("gui.toolstation6") + ToolPartHelper.getBowDrawSpeedString(bowMat.drawspeed));
	toolTip.add(StringHelper.getLocalizedString("gui.toolstation7") + ToolPartHelper.getArrowSpeedString(bowMat.flightSpeedMax));
}
```

So it looks like your material ID is not being registered as a bow material, so those stats can't be retrieved.

**Comment by ReikaKalseki** [comment]
Except they are...

**Comment by squeek502** [comment]
The only reason that tooltip would appear as it does in that screenshot is for TConstructRegistry.getBowMaterial(matID) to return null.

Note that in your code [this line is commented out](https://github.com/ReikaKalseki/RotaryCraft/blob/master/RotaryCraft.java#L558) which would execute [this line](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModInteract/DeepInteract/TinkerMaterialHelper.java#L449) which should register the bow material.

**Comment by ReikaKalseki** [comment]
I commented it out because neither uses the pattern builder: HSLA uses the smeltery and bedrock uses the Blast Furnace.

**Comment by ReikaKalseki** [comment]
OK, this can be closed.

**Comment by bonii-xx** [comment]
Just look at the IMCs already, they literally contain all the answers :P
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/util/IMCHandler.java#L222-L263
