### ISSUE TITLE
Question - Giving tools by commands

### ISSUE THREAD

**Issue by Bloodmorphed** [SlimeKnights/TinkersConstruct#1769]
I'm using a mod that gives starting items, however it does this through the name of the item so in this case it would be TConstruct:pickaxe and obviously that doesn't work.

Is there a way to give this data to give a tool? There has to be a way as the starting chest has some tools in it.

**Comment by laz2727** [comment]
Find another mod for that.

2015-10-01 23:20 GMT+06:00 Bloodmorphed <notifications@github.com>:

**Comment by Bloodmorphed** [comment]
Pretty sure all starting inventory mods do it like this.

**Comment by laz2727** [comment]
Nope, i've seen good ones.

You can give tool parts. Or make an item and let it craft into tools you
need. It's harder, though.

2015-10-01 23:23 GMT+06:00 Bloodmorphed <notifications@github.com>:

**Comment by Bloodmorphed** [comment]
"Nope, I've seen good ones" Please enlighten me because no matter how many searches I do all I can find is "StartingInventory" by the treecapitators guy.

**Comment by laz2727** [comment]
Have you tried the easy method?


I'm not sure. But i've seen it in some FTB pack.

You can also make a HQM quest. The rewards keep NBT.

**Comment by Bloodmorphed** [comment]
The easy method? I have yet to find that with this mod lol. Don't get me wrong, I love it with a passion, but sometimes it irritates me.

The only thing I've seen spawning of tinker's tools is the Starting Chest (Again I don't know how that's done either)

That requires me to install a pretty useless mod if you only use it for that one thing.

**Comment by bonii-xx** [comment]
You can.. if you specify all the NBT. TCon tools need NBT. Everything else depends on how the mod handles it.
