### ISSUE TITLE
foresty/MFR Tconstruct milk conflicts

### ISSUE THREAD

**Issue by Bloodmorphed** [SlimeKnights/TinkersConstruct#1770]
So I can run all the mods for this:

forestry
Thermal foundation/expansion/dynamics
Minefactory reloaded

However when I add Mantle and Tinkers' Construct I get a 
"Fatally Missing Block and Item" error for Forestry:fluid:milk However I only get this problem with Tinkers' construct.

**Comment by bonii-xx** [comment]
No, I'm pretty sure you don't.

**Comment by Bloodmorphed** [comment]
Actually I do, but if you need proof I can give it to you. I spent two days making sure of this before posting this. If I remove tinkers' construct the error stops, if I add it, it picks up again.

Granted I can remove the fluids for forestry so it isn't a big deal, though.

I have tested this with 150+ plus mods, for some reason tinkers' triggers the conflict between MFR and Forestry.

Thanks for insulting my intelligence though, nice job buddy.

**Comment by bookerthegeek** [comment]
Do you get the error with mantle but not tinkers?

**Comment by Bloodmorphed** [comment]
Hmmm, actually that probably is the case as core mods load first. I'll test it later today, I'm taking a break messing with building modpacks for now. Finally got mine worked perfectly, I need a break lol.

I feel for these coders those, their job(hobby) is much more taxing.

**Comment by bonii-xx** [comment]
>Thanks for insulting my intelligence though, nice job buddy.
You have no idea about the amount of stupid and lazy that comes my way ;P

There are tons of modpacks who all contain those mods and have no problems though. And Tinkers does nothing with milk specifically. And nothing with liquids in general.

The only possible way it could affect something like that was if tinkers requires a different loading order, which then causes this issue. And then it's on those mods again. My best guess would be that both Forestry and MFR have something in place to not add milk if the other exists.. and then get called in reverse order through changed loading order. Which would mean it's implemented incorrectly either way.

Which, then again, has nothing to do with Tinkers. Why does nobody ever believe me? :P

**Comment by Bloodmorphed** [comment]
You've ignored everything I said. 

"The only possible way it could affect something like that was if tinkers requires a different loading order, which then causes this issue. And then it's on those mods again."

Regardless of it being those mods instead of yours is irrelevant. I was pointing out that your mod caused them to conflict, it doesn't matter why it does, it just does. In this case for some reason tinkers' changed the way those two mods load together. Not that it matters as it's a extremely easy fix.

They play nice together, until tinkers' comes in, then I have to disable milk for forestry. It is simple as that, it is what it is, nothing more.

(it could be mantle as well, but I don't feel like testing it as it matters not.)

**Comment by bonii-xx** [comment]
> I was pointing out that your mod caused them to conflict, it doesn't matter why it does, it just does. In this case for some reason tinkers' changed the way those two mods load together.

Oh, it's not for *some* reason, [Tinkers requires MFR, TF and TE to load before it](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/TConstruct.java#L76-L77).


The real question is why those mods behave like that, and why it only happens for you. In either case, I literally have no clue what you actually want from me. ¯\_(ツ)_/¯
