### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by RustyKnightmare** [SlimeKnights/TinkersConstruct#1772]
I've run into an issue that seems to plague me- upon initializing my minecraft, the client crashes once it reaches a certain point, time and again.  Here's the issue I run into, from what I can tell it's a texture mess up of some kind: http://pastebin.com/7Qt5huu7

Backdating, removing any other form of mod, and anything else your forum faithfuls have come up with has failed, I'm sad to say.

**Comment by bonii-xx** [comment]
This is 99.9% not a tcon issue. Might be a broken file.

**Comment by RustyKnightmare** [comment]
I've redownloaded both files at least 30 times, and none of them (the new downloads) changed a thing- could my actual minecraft be broken in some way that causes this?

**Comment by bonii-xx** [comment]
Does it happen with only tcon and mantle, no other mods?

**Comment by RustyKnightmare** [comment]
Yes, I've tried launching with nothing but TiC and mantle and it has the same error

**Comment by bonii-xx** [comment]
Really weird. I hazily remember somebody mentioning problems with a specific java version.. might be it's that. I'm using 1.8.0_40, and it seems the latest one is 1.8.0_60. Try updating/downgrading and see if it fixes it.

**Comment by RustyKnightmare** [comment]
I went to java's latest update, 60, and it still came out the same.  How can I get a backdated java installation..?

**Comment by bonii-xx** [comment]
Since 60 didn't fix it it's probably not that, sorry forgot to answer.
Closing this since it's not a tcon issue.
