### ISSUE TITLE
Support all Tiers of Energy Cell for Flux Modifier

### ISSUE THREAD

**Issue by mikeloeven** [SlimeKnights/TinkersConstruct#1774]
The flux upgrade is limited to leadstone energy cells and the upgrade will not function with higher capacity cells. could you please add support for all tiers of RF containers for higher energy capacities

**Comment by AlterAkima** [comment]
It's limited due to a config option:
"Balanced Flux Modifier"
Disabling it allows the use of the bigger capacitors.

**Comment by bonii-xx** [comment]
Flux supports all tiers, the durability of your tool just sucks. :P

**Comment by mikeloeven** [comment]
Considering the tool was alumite it should support at least hardened cells i assume the issue is what Alter Akima mentioned ill ask the Admins about the config setting

**Comment by bonii-xx** [comment]
There is no config that accepts which modifiers are applicable. Only the conditions under which.
