### ISSUE TITLE
Question:What do I place in the top-left of the Armour GUI?

### ISSUE THREAD

**Issue by AshenFlames** [SlimeKnights/TinkersConstruct#1776]
I am having trouble figuring out what you put in one of the Armour GUI slots in the inventory. I know the  Knapsack goes in top right, Travelers belt goes in the bottom right, and the gloves go in the bottom left.
However, I have no clue what goes into the top left part and I can't find it on the wiki. Could someone please let me know?

**Comment by bonii-xx** [comment]
Nothing. It never got implemented.
