### ISSUE TITLE
DragonAPI + TiCon breaks certain Extra Utilities crafting recipes

### ISSUE THREAD

**Issue by EyeDeck** [SlimeKnights/TinkersConstruct#1777]
There's a cross-mod interaction somewhere between DragonAPI and Tinkers' Construct that breaks NBT crafting recipes:

With DragonAPI or Tinkers' Construct disabled:
![1_50pct](https://cloud.githubusercontent.com/assets/2722970/10416504/90fbfada-6fe7-11e5-8a5a-699250675180.png)
![2_50pct](https://cloud.githubusercontent.com/assets/2722970/10416505/9332847c-6fe7-11e5-8ddc-03f08977d95a.png)

With DragonAPI and Tinkers' Construct enabled:
![3_50pct](https://cloud.githubusercontent.com/assets/2722970/10416506/9a9273e4-6fe7-11e5-9285-8122a61025be.png)
![4_50pct](https://cloud.githubusercontent.com/assets/2722970/10416507/9c44e55a-6fe7-11e5-98db-e24dc03d5810.png)

This probably also affects other mods that use similar methods for some of their crafting recipes; Extra Utilities specifically breaking is only a symptom. In the past this has been caused by certain errant Ore Dictionary calls.

Also reported at https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/323
@ReikaKalseki
>Which means it is in code in TiC that only runs with DragonAPI, or code of mine that only loads with TiC. There is little of either.
> 
>Ask boni to look for all calls to OreDictionary.initialize().

See also these older, resolved issues likely triggered by the same bug:
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/73
https://github.com/rwtema/extrautilities/issues/525
https://github.com/McJty/RFTools/issues/91

**Comment by bonii-xx** [comment]
I'd wager it's more likely that XUs TCon integration does stuff

**Comment by bonii-xx** [comment]
Yeah, looking at the OreDictionary usage in TCon I'd wager it's not something TCon does, but something of the other mods when TCon is present.

**Comment by EyeDeck** [comment]
Looks like this did indeed turn out to be the same old Forge bug, which is usually harmless but causes problems with the atypical way ExU adds some recipes. DragonAPI called `OreDictionary.initVanillaEntries();` after ExU added its recipes, because ExU is forcing itself to load immediately after TiCon for some reason instead of further down the load order like it's supposed to, which triggers a Forge bug that replaces several ExU recipes with broken versions.
