### ISSUE TITLE
[Issue] Smeltry Damage Bypasses Fire Immunity

### ISSUE THREAD

**Issue by mikeloeven** [SlimeKnights/TinkersConstruct#1779]
Considering the nature of the smeltry it cannot be hotter than the lava which is used to fuel it however after attempting to enter a smeltry under the effects of a fire immunity potion and a second attempt wearing the IC2 Hazmat Suit i find that the smeltry is dealing direct damage to the player bypassing all forms of fire resistance where the smelty and any fluids contained within should be dealing pure fire damage such as when immersed in lava. 

Please adjust the smeltry to deal only fire damage so that it will properly handle players under the effects of fire immunity.

if this is not possible for technical reasons than please add a check to see if the player is under a potion or armor effect and skip the damage tick

**Comment by bonii-xx** [comment]
Nah. If you jump into a smeltery you deserve to take damage. ;P

**Comment by mikeloeven** [comment]
I disagree fire immunity is a vanilla effect that should be respected

**Comment by bonii-xx** [comment]
I understand that you disagree, and your point is valid. From a logical standpoint fire immunity should help against it. However I see no reason or benefit from actually doing it and I much prefer hurting players who are stupid/brave enough to walk inside a running smeltery. ;)
