### ISSUE TITLE
[Issue] Smeltry Progress Bars Either Hang at 100% or are not Display Correct Smelting Progress

### ISSUE THREAD

**Issue by mikeloeven** [SlimeKnights/TinkersConstruct#1782]
This has kinda been an issue from day one however the most current FTB seems to have exacerbated the issue dramatically. There appears to be a major hang between an ingots progress bar reaching 100% and the ingot actually being converterted into a molten metal. this hang can sometimes last for upwards of 5-10 minutes past when the ingot should have melted. 

So one of two things is happening 

A: the progress bars are not syncing to the proper smelting time
B: there is some flaw in the loop that is causing a long delay between reaching 100% progress and the conversion of the ingot into a molten metal

**Comment by bonii-xx** [comment]
Sounds like your TPS have dropped drastically then.
The bar progresses clientside, but if the Server lags they don't match up.
