### ISSUE TITLE
[issue] Smeltry Drain Will Not Respond to Logistic Pipes Fluid Requests

### ISSUE THREAD

**Issue by mikeloeven** [SlimeKnights/TinkersConstruct#1785]
I was troubleshooting an issue where my logistic pipes were failing to pull the selected liquids out of the smelt on request. after extensive testing i found that the logi pipes were sending the proper requests to the fluid provider however the smeltry drain would not allow the provider to extract the selected fluids unless the player manually selected it in the smeltry controller. this causes my automated casting system to be constantly babysat and prevents me from storing more than on molten metal in the smeltry at all time as the drains do not properly accept specific fluid requests.

Please look into this issue so that the smeltry drain allows logi fluid providers to properly extract the selected fluids without manual intervention. 

You can see a video Demonstration of the problem here.

https://www.youtube.com/watch?v=5J7In4XQ3CQ&feature=youtu.be

**Comment by bonii-xx** [comment]
Smelteries do not support that kind of behaviour. Smelteries only support taking out the bottom most liquid.

**Comment by mikeloeven** [comment]
Why close it why not convert it to an enhancement since this behavior would be much more useful and desirable for automation why keep using a bad design ??

**Comment by bonii-xx** [comment]
Having to think to automate something does not automatically mean bad it's bad design. Smelteries are meant to only be automateable with effort.
