### ISSUE TITLE
[feature request] Solving ExtraTiC arrowmaking incompatibility (easy fix)

### ISSUE THREAD

**Issue by Darkos333** [SlimeKnights/TinkersConstruct#1786]
Problem: ExtraTiC is incompatible with latest versions of TC on Arrowmaking (causes crash)
Solution: Please, bring back old arrowmaking as a config option.

**Comment by bonii-xx** [comment]
No it's not?

**Comment by Darkos333** [comment]
Are you kidding me?
Okay then, take Steel Arrowhead, Steel Tool Rod and Slime Crystal. Put them into Arowmaking TF tab and see what happens.

**Comment by Darkos333** [comment]
Just in case you still feel unconvinced:
Take a look at this:
https://www.reddit.com/r/crackpack/comments/2xf57h/why_the_hell_cant_i_make_arrows/

**Comment by bonii-xx** [comment]
Yes. That's not how you make arrows.

**Comment by Darkos333** [comment]
Yet it causes crash, doesnt it?
Dont take me wrong, I am not saying new design is bad - but personally I would love to be able to use it "the old way". Belive it or not, I am not the only one.
So, just for this reason, couldnt you make it possible as a config option (disabled by default)?
Since you are (obviously) using Git, getting back the old code is not a problem.

**Comment by bonii-xx** [comment]
No.

**Comment by Darkos333** [comment]
Okay then.
