### ISSUE TITLE
[bug] chisel have eating animation

### ISSUE THREAD

**Issue by NoX-programer** [SlimeKnights/TinkersConstruct#1788]
I think, chisel is not food, but it have eating animation. It is only for me or it is global?

Versions: 1.7.10-Forge10.13.4.1448-1.7.10, TConstruct-1.7.10-1.8.7, IguanaTinkerTweaks-1.7.10-2.1.5

**Comment by AlterAkima** [comment]
It's been this way since 1.5.2.

**Comment by NoX-programer** [comment]
And nobody care? Hm...

**Comment by DPxKnightxZero** [comment]
Not really XD

**Comment by Wulfson** [comment]
Working as intended. See: #52, #59, #1046, and #1572...

**Comment by NoX-programer** [comment]
Okay, if mod developers think this is intended, let them close this one (but I presume, somebody someday will report it again).

**Comment by Wulfson** [comment]
Yeah, there's always people who don't search the existing tickets before making new ones...

**Comment by mDiyo** [comment]
This is not a bug. The bug is Mojang using a chisel sound for food.
