### ISSUE TITLE
Food dropped by animals killed by using weapons that have the Auto-smelt or the Fiery modifier is not cooked.

### ISSUE THREAD

**Issue by Rukachan** [SlimeKnights/TinkersConstruct#1789]
Title explains everything.
In Vanilla if a animal gets killed by a tool that has Fire Aspect, the dropped food will be cooked.

**Comment by AlterAkima** [comment]
They do drop cooked food if killed by the fire (any source).

**Comment by Rukachan** [comment]
@AlterAkima, I am well aware of that, but I am talking in the case they have been killed by the tool itself. Not by the fire.

**Comment by bonii-xx** [comment]
They probably are ignited after the damage has already been dealt. But anyway..
