### ISSUE TITLE
After last update I am crashing every time using belt hotkey

### ISSUE THREAD

**Issue by Spazzze** [SlimeKnights/TinkersConstruct#1791]
Hello!
Before the update I was using belt from your mod very often, I love this feature very much.
But after I updated your mod from TConstruct-1.7.10-1.8.7.jar to TConstruct-1.7.10-1.8.8.jar I begin to get this crash every time I am trying to use Belt's hotkey
http://pastebin.com/HMBAGf29

**Comment by bonii-xx** [comment]
Update NEK

**Comment by Spazzze** [comment]
I am sorry, what is "NEK"?

**Comment by AlterAkima** [comment]
NEK stands for Not Enough Keys.

**Comment by Spazzze** [comment]
Thanks guys! Issue is solved after I updated NEK from NotEnoughKeys-1.7.10-1.0.0b30 to NotEnoughKeys-1.7.10-3.0.0b43-universal
