### ISSUE TITLE
Arrow Accuracy discrepancy

### ISSUE THREAD

**Issue by LoralaiAya** [SlimeKnights/TinkersConstruct#1793]
There seems to be a discrepancy between the stats shown for arrows when crafting and when they are in the users inventory. For example someone on my FTB server crafted a set off arrows with Alumite head, blaze rod shaft, and blue slime fletching. In the tool table the arrows show up as 100% accurate, however out of the table they show up as only 96% accurate.

We are running FTB Infinity with the following versions: 

Minecraft: 1.7.10
Forge: 7.10.99.99
Tinkers' Construct: 1.8.7

Screenshots: 
![2015-10-30_18 59 30](https://cloud.githubusercontent.com/assets/15483823/10860098/4b834ce4-7f3a-11e5-85d0-609f297f35bf.png)
*While the arrows are in the tool table*

![2015-10-30_18 59 48](https://cloud.githubusercontent.com/assets/15483823/10860102/4ebc5a5e-7f3a-11e5-9a74-2392ae210671.png)
*When the arrows are in a users inventory*

**Comment by squeek502** [comment]
The tooltips come from my mod [TiC Tooltips](https://github.com/squeek502/TiC-Tooltips). Unsure which % is incorrect.

**Comment by squeek502** [comment]
Looks like TiC Tooltips [subtracts 4 from the accuracy](https://github.com/squeek502/TiC-Tooltips/blob/c2fe0c1d4d5b30577ba39260bac1ec20ab4899c3/java/squeek/tictooltips/helpers/StringHelper.java#L83) when displaying it. I would assume I had good reason for this, but will need to double check.

**Comment by squeek502** [comment]
Looks like the `- 4` is from some time ago and doesn't apply anymore. Here's the `- 4` in the 1.6.4 version: https://github.com/SlimeKnights/TinkersConstruct/blob/1.6.4/src/main/java/tconstruct/client/gui/ToolStationGui.java#L283

Will fix this in TiC Tooltips. This can be closed.

**Comment by LoralaiAya** [comment]
Okay however the issue is that we have seen the arrow proc that 96% accuracy shown in the tool tip, so the arrows are not 100% accurate as described in the table.

**Comment by squeek502** [comment]
How did you test the accuracy?
