### ISSUE TITLE
setThrowableHeading parameter order mismatch

### ISSUE THREAD

**Issue by squeek502** [SlimeKnights/TinkersConstruct#1794]
In investigating #1793, I noticed while searching for `setThrowableHeading`, the speed and accuracy parameters swap positions in different calls.

For example:

* [BehaviorProjectileBaseDispense](https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/library/util/BehaviorProjectileBaseDispense.java#L42)
* [ProjectileBase](https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/library/entity/ProjectileBase.java#L64)

All instances: https://github.com/SlimeKnights/TinkersConstruct/search?utf8=%E2%9C%93&q=setThrowableHeading

I would assume the dispenser behavior is the one that has it backwards.

**Comment by bonii-xx** [comment]
Fixed in TiC2. Too lazy to do dispensers behaviour for now. :I
