### ISSUE TITLE
Can't use wooden/stone tools!

### ISSUE THREAD

**Issue by TotallyDerp** [SlimeKnights/TinkersConstruct#1796]
When I make a wooden/stone tool in a crafting table it tells me in red text: 'This tool cannot mine anything! It can only be used for crafting'.
I've done a lot of research but I couldn't find a solution.
Is this normal, should I be concerned, and can I fix it ?
I'm using TC 1.7.10-1.8.8 with Iguana TinkerTweeks 1.7.10-2.1.5.

**Comment by AlterAkima** [comment]
It's not a bug, nor Tinkers' fault.
It can be changed on Iguana Tweaks' configurations.

**Comment by TotallyDerp** [comment]
Thank you so much AlterAkima!

**Comment by TotallyDerp** [comment]
AlterAkima, where can I change the setting in the config exactly ?

**Comment by TotallyDerp** [comment]
Where (exactly) can I find the config for the issue that I have ?

**Comment by NoX-programer** [comment]
%APPDATA%\.minecraft\config\IguanaTinkerTweaks\main.cfg
option B:disableStoneTools

**Comment by TotallyDerp** [comment]
Thank you so much NoX-programer!
