### ISSUE TITLE
access transformers

### ISSUE THREAD

**Issue by mightydanp** [SlimeKnights/TinkersConstruct#1799]
I am a modder myself and i made it where i can use part of your code in my mod. No non of your code is changed or anything it still is located in tinkers.client.tabs, Non of your code is located in any part of my mod. i am trying to access buttonList, but i couldn't figure out how to do so with a access transformers and i'm on a forum and they are saying for me to use Reflection. Can i edit that class for it to be able to work with a Reflection ?

**Comment by bonii-xx** [comment]
Copy the tinkers AT into your dev environment, so it gets applied on setup.
