### ISSUE TITLE
Crash when open the page 6 of the manual

### ISSUE THREAD

**Issue by siriulx** [SlimeKnights/TinkersConstruct#1801]
I got a crush after I disabled the Tinkers' Armory:
```
 # Modifyable armors, such as the traveller's gear.
 B:"Tinkers' Armory"=false
```
and opened the page 6 of the manual *Materials and you: Volume 1*
Crush report: http://pastebin.com/EYH0tZM7

Forge version: 10.13.4.1541
Mantle version: 1.7.10-0.3.2b
TConstruct version: 1.7.10-1.8.8

**Comment by bonii-xx** [comment]
Yes, manuals are unsupported if parts of the mod is disabled.
