### ISSUE TITLE
Some Modifiers don't have a key

### ISSUE THREAD

**Issue by Voidi** [SlimeKnights/TinkersConstruct#1803]
Some Modifiers don't have a key like https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/modifiers/tools/ModToolRepair.java#L15

This become an Issue, if a some want to disable a Modifier with Modtweaker, because it's retrieve the to deleting Modifiers via the key.

**Comment by bonii-xx** [comment]
..why would you ever want to disable tool repairing?

**Comment by Voidi** [comment]
it's not just the tool repair modifier, but as is seems that a player just would see only the repair one that seems ok.

tconstruct.modifiers.tools.ModToolRepair@189a398
tconstruct.modifiers.tools.ModCreativeToolModifier@4a82585d
tconstruct.modifiers.armor.TravelModRepair@eceafa2
tconstruct.modifiers.tools.ModAmmoRestock@229a3499
