### ISSUE TITLE
Rendering ToolStation with dmg 16 crashes client

### ISSUE THREAD

**Issue by HashtagShell** [SlimeKnights/TinkersConstruct#1804]
Giving a player a tool station with damage 16 crashes the client (supposedly, the stacktrace has to do with rendering). The world gets "corrupted", crashing the client every time it's loaded. (Can be resolved by deleting the item with 3rd party nbt editors)

Command: /give @p TConstruct:ToolStationBlock 1 16
StackTrace: http://pastebin.com/gyQTn010
Inst. mods: [Read StackTrace]
Environment: GradleStart from IntelliJ Idea, testing one of my mods (and getting carried away playing with TiC) (My mod does not integrate with TiC or rendering at all)

**Comment by bonii-xx** [comment]
Don't use /give, much less with invalid metadata since anything >15 will always be invalid for blocks.
