### ISSUE TITLE
Bug with heart canisters

### ISSUE THREAD

**Issue by nicknewlin** [SlimeKnights/TinkersConstruct#1805]
In dimensions other than the overworld, nether, and end, heart canisters regenerate more heath than the amount of canisters.
<img width="846" alt="screen shot 2015-11-12 at 7 20 46 pm" src="https://cloud.githubusercontent.com/assets/15825293/11135404/b63b5666-8972-11e5-8fd5-5a3b36992751.png">
<img width="556" alt="screen shot 2015-11-12 at 7 21 08 pm" src="https://cloud.githubusercontent.com/assets/15825293/11135405/b63ec7e2-8972-11e5-8902-da8f3872ec9d.png">

**Comment by Zsashas** [comment]
What other mods do you have? Do any others affect health?

**Comment by nicknewlin** [comment]
I have a lot of mods, but there are not any that I think would affect health. Side note: I have experienced this bug while playing previous versions of Tinker's Construct with other mods rather than these.

Tinker's Construct, Tree Capitator, Jammy Furniture, Aether II, AE2, BiblioCraft, Biomes OP, BuildCraft, ExtrabiomesXL, Extra Cells, Galacticraft, Improving Minecraft, IC2, Iron Chest, Minefactory Reloaded, More Planets, MrCrayfish Furniture, OpenBlocks, Thermal Expansion, and Twilight Forest.

**Comment by Zsashas** [comment]
Perhaps try without Aether or Galacticraft, those would be the two suspects for this, to me.

**Comment by bonii-xx** [comment]
Aether2s fault.

**Comment by Zsashas** [comment]
Called it xD
