### ISSUE TITLE
not an issue, just a question about 1.8.x progress

### ISSUE THREAD

**Issue by Prophious** [SlimeKnights/TinkersConstruct#1806]
i dont mean to be rude in asking, but i know a lot of ppl are waiting for the update so i ask

how is the update to 1.8.x going? 
is there any major issues that seem to be very problematic?
if you were to get help on something what would it be?
is it possible to list the progress milestones here or in a new issue thread?(i know this is asking a lot)

if you haven't noticed by now tinkers construct is in mostly all modpacks, that being said, there are a lot of other mod devs that are not updating their mods until this mod gets to be in 1.8.x 

so please dont take this issue here as an insult or anything negative, i only really want to know not just for myself but for all the other ppl that want to know as well

thanks 
    -- Prophious

**Comment by bonii-xx** [comment]
>how is the update to 1.8.x going? 

It's progressing.

>is there any major issues that seem to be very problematic?

Time. ;P

>if you were to get help on something what would it be?

Hardly, nothing is ported 1:1. Renaming tons of files and adjusting graphics would be the only thing.

>is it possible to list the progress milestones here or in a new issue thread?(i know this is asking a lot)

No.

>there are a lot of other mod devs that are not updating their mods until this mod gets to be in 1.8.x

TCon updating wont change that. 1.9 probably will.

**Comment by Prophious** [comment]
thanks for taking the time to answer, and i hope that not too many troubles come to doing the update, and most of all... good luck
