### ISSUE TITLE
Longswords not registered as swords?

### ISSUE THREAD

**Issue by Zsashas** [SlimeKnights/TinkersConstruct#1807]
Using Zelda Sword Skills, Longswords are unable to break clay jars, which can only be broken by swords or ZSS hammers. Rapiers, Cutlasses, and Broadswords work fine, have not yet tested Cleavers, Daggers, or Javelins.

**Comment by Zsashas** [comment]
https://github.com/coolAlias/ZeldaSwordSkills/issues/51

Should be easier to add compatibility now.

**Comment by coolAlias** [comment]
The clay jar issue was fixed on my end by allowing any Item with a damage modifier to break them.

As far as weapon compatibility for other things, such as skills, anyone can add that for any mod using FML's Inter-Mod Communication system, so long as the mod Item does not rely on ItemStack NBT or damage when determining what sort of weapon it is. In such cases, the mod author(s) will need to implement my IWeapon interface if they wish to support ZSS skill use with their items (unless said item extends ItemSword already).

It would be awesome if there was some kind of weapon registry system built in to Forge, but with the huge variety of requirements from different mods, I doubt we'll ever see such a thing.

**Comment by coolAlias** [comment]
@Zsashas With the latest [commits](https://github.com/coolAlias/ZeldaSwordSkills/commit/9231b875b8aeca40027932d2777d16ad762a46ea), you can add items from other mods via the ZSS config.

@bonii-xx You guys probably won't need to do anything now unless you specifically want to control your items behavior with respect to my mod. Users should be able to handle most cases on their own.

**Comment by bonii-xx** [comment]
Perfect, thanks! o/

**Comment by coolAlias** [comment]
So... since I changed the API, there is no longer an ISword interface for Zelda Sword Skills, but instead an IWeapon interface with a few methods.

At least [one of your classes](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/tools/Weapon.java#L19) implements the old ISword interface and will now crash with the latest ZSS.

I can put the ISword interface back in and mark it with @Deprecated, but if you guys are nearing a release and can change the reference on your end, that would be preferable, imo, since I already took it out... sorry about that :\

**Comment by bonii-xx** [comment]
1.7.10 wont get updated anymore. Please put it back in, yes. Breaking updates are always a bad idea, at least leave things in and have them not work/supported anymore.

**Comment by coolAlias** [comment]
Yeah, I know - just didn't think anyone was using it... oops. Cheers.

**Comment by Zsashas** [comment]
What about that final 1.7.10 update you were planning? Is that not happening anymore?

**Comment by bonii-xx** [comment]
That's already out since October.

**Comment by Blue64** [comment]
@coolAlias
```
It would be awesome if there was some kind of weapon registry system built in to Forge, but with the huge variety of requirements from different mods, I doubt we'll ever see such a thing.
```
I just use MineTweaker to add ```toolSword``` in the OreDict for that kind of stuff lol  I also have 
```
toolHoe
toolPickaxe
toolShovel
toolShears (m-ore mod adds more shears)
toolAxe
toolFishingRod (m-ore mod adds more rods)
toolBucket (because I got tired of wondering if it could scoop fluids or would be placed as a block and delete the fluids lol)
