### ISSUE TITLE
FTB Infinity Evolved Expert: Traveller's Armor crash

### ISSUE THREAD

**Issue by thecybermind** [SlimeKnights/TinkersConstruct#1808]
Whenever you try to place a Traveller's Glove (edit: and other Traveller's armor) into the item-to-be-upgraded slot in a Tool Station, Tool Forge, or Crafting Station (adjacent to a tool station), the game crashes when attempting to show the stats of the resulting item.

Crash log:
http://pastebin.com/fMwuktL3

The most recent line referred to in the stacktrace ([tconstruct/tools/gui/ToolStationGuiHelper.java:64](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/gui/ToolStationGuiHelper.java#L64)) is:

    tags = tags.getCompoundTag(modifyable.getBaseTagName());

It is likely that due to the recipe changes invoked by Expert mode of Infinity Evolved, the item is not crafted with some default NBT tags that Tinkers Construct is expecting, causing line 54 near the top of drawToolStats to result in a null reference for `tags`:

    NBTTagCompound tags = stack.getTagCompound();

Perhaps this should be checked for null and if so, have a default NBTTagCompound (similar to [AccessoryCore.getDefaultItem()](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/accessory/AccessoryCore.java#L69)) added before continuing.

More info:

* If I craft Traveller's Gloves in Normal mode, and then switch to Expert mode, the gloves are modifable just fine. It is only gloves that are crafted while Expert mode is enabled that cause a crash.

* It only crashes with actual crafted items in Expert mode. Creative-given items out of NEI, even while in Expert mode, are fine.

* If you rename the gloves in an anvil, a root NBTTagCompound is created on the item, so Minecraft no longer crashes when trying to modify the gloves. However, there is no standard AccessoryCore-related NBT tags so you are unable to actually modify them.

* Similarly, Traveller's items with durability (such as the Goggles) display "Broken" once renamed in the anvil, but are not able to be repaired in the Tool Forge/Station.

Admittedly, this is a problem with how the MineTweaker scripts for Expert mode handle new recipes for specific items, but being null-safe never hurt anyone!

**Comment by bonii-xx** [comment]
Yup, Traveller's Gear requires its NBT just like any Tinkers' tool. The recipe added by us and the ones available in NEI/Creative all have the NBT. The ones with the changed recipe don't, it's on them to fix that.

**Comment by bookerthegeek** [comment]
@bonii-xx would you happen to have the default nbt data so we can fix this recipe on our server?

**Comment by thecybermind** [comment]
Here is an updated MineTweaker script for TinkersConstruct (goes into Curse\Instances\FTB Infinity Evolved\modpack\expert\scripts\):

https://gist.github.com/thecybermind/4a1f3fc820abcf75f338
