### ISSUE TITLE
disable generate Aluminum 

### ISSUE THREAD

**Issue by LexAndersen** [SlimeKnights/TinkersConstruct#1809]
In config B:"Generate Aluminum"=false not work. Aluminum still generated.

**Comment by Robijnvogel** [comment]
Are you sure that this is Tinkers' Construct Aluminum Ore?
Some other mods add their own Aluminum or Aliminium Ore as well.

And if this does happen to be TiC Aluminum Ore, please make sure that you haven't handed over your "oregen-handling" to some other mod like Thermal Foundation. If these have a specific rule that says that TiC Aluminum ore should be generated, then it does not matter whether you set this to true or false in the TiC config.
