### ISSUE TITLE
Crash with Traveller's Gear keys

### ISSUE THREAD

**Issue by Baggytrousers27** [SlimeKnights/TinkersConstruct#1810]
An issue I've had across the board with most versions of TiC (currently with 1.8.8) is that after a while toggling and abilities with the traveller's gear (Goggles; zoom and nighyt vision, belt switch etc.) causes a crash back to launcher. Not entirely sure why because I've mapped them to several other, unused, keys and it yields the same result.
I have the crashlog here:
http://pastebin.com/N3jUi0Ky
and it says at the beginning that it's a keybind problem. I'm unfortunately not savvy enough to infer from the logs what the issue is and any assistance would be greatly appreciated ... I miss my goggles and switching hotbar.

**Comment by bonii-xx** [comment]
Update NotEnoughKeys.
