### ISSUE TITLE
Crash when Tinkers Armor is not actually Tinker's Armor

### ISSUE THREAD

**Issue by thor12022** [SlimeKnights/TinkersConstruct#1816]
If a mod tries to fake Tinkers Armor (in this case Tombenpotter's Icarus) it can result in a crash from onArmorTicking.

[Crashlog](http://cryptb.in/BMm#aa92ba033810147dd419be99e5dfc890)

Cross-reference Issue Tombenpotter/Icarus#72

**Comment by bonii-xx** [comment]
Mod integration on his part.
