### ISSUE TITLE
Blank fluids in the Smeltery

### ISSUE THREAD

**Issue by darkhax** [SlimeKnights/TinkersConstruct#1817]
When a fluid which lacks an Icon is rendered, the water texture is used as a placeholder. If that same fluid is rendered in the Smeltery GUI, it shows up as a blank texture. While not a major priority, I think that the water texture should also be used in the GUI, to tie everything together. Perhaps you could even use the color of the linked material as a modifier for the water texture. 

Edit: After further testing, it seems the lack of a texture in the GUI will actually mess up the positioning of the liquids. For example if you bring the unnamed fluid to the bottom of the smeltery list, the other textures will not shift position. This can cause the texture used, and the name to become misaligned. 

Edit 2: I have tried to upload some screenshots, however both have failed to record my mouse, making them not so useful. I have switched to a GIF to better demonstrate the issue. 
![animation](https://cloud.githubusercontent.com/assets/2250798/11353088/63563b80-91fd-11e5-952e-ffe62933e92f.gif)

**Comment by Blue64** [comment]
Lol what exactly would Liquid Bookshelfium be used for, and how can I get some? I want to play around with it in conjunction with MystCraft lol

**Comment by darkhax** [comment]
Bookshelfium was just a test fluid I created while testing the Tinkers Construct IMC Wrapper utility class in the Bookshelf mod. It doesn't actually do anything and can't be obtained unless you have the Bookshelf Debug mod installed, however that is not public.

**Comment by bonii-xx** [comment]
It's actually quite simple. The fluid shouldn't lack an icon.
