### ISSUE TITLE
Ex Nihilo Hammer does not work on any of the ores

### ISSUE THREAD

**Issue by malice936** [SlimeKnights/TinkersConstruct#1818]
Built a new pack, and added support for cobalt and ardite to be hammered. It natively supports copper, tin, and alumin(i)um. However none of the tinkers ores will work with it. There are no errors, and it just destroys the block when an Ex Nihilo hammer is used. 

Edit: Also the recipe is showing up and registered, which is why I believe it's a tinkers issue.

**Comment by bonii-xx** [comment]
Most likely not TCons fault, ores do nothing special, they're just boring old blocks.
