### ISSUE TITLE
[Issue] Smeltry Will Not Load Higher than 29 Blocks

### ISSUE THREAD

**Issue by mikeloeven** [SlimeKnights/TinkersConstruct#1819]
edit: incorrectly measured the height was 29 not 32
For some reason an automated smeltry will not load any ore higher than 29 blocks the smeltry it's self is 52 blocks in height. Ore is routed to a chest via logistic pipes and a impulse duct with resonant servo loads the ore into the controller. This pipe can transfer a stack of ore multiple times per second so i ruled out the ore being smelted faster than the smeltry can be loaded. 

when looking through the seared glass you can see that the smeltry is loaded fully up to 28 blocks however when the height reaches 29 blocks it will only load four blocks into that level and stop. due to this behavior ore and dusts are backing up in the buffer chest and the smeltry is not performing at it's maximum capacity

I find this odd since the smelt is not supposed to have any height limits. 

interior dimensions are 3x3x52

**Comment by bonii-xx** [comment]
Check for rogue invisible blocks inside the smeltery at that layer.

**Comment by mikeloeven** [comment]
I filled the broken layer as well as the layer below and above with cobble and than mined it out. no change in behavior

**Comment by mikeloeven** [comment]
still waiting on a solution for this

**Comment by bonii-xx** [comment]
Could be anything from problems accessing blocks over chunks to other mods messing with it to a very rare occurence.

Current solution: Make the smeltery bigger instead of higher.

**Comment by mikeloeven** [comment]
I think i figured out what triggers the issue. I rebuilt the smeltry completely by hand and the issue resolved. Prior to that i had been using the builders wand from Extra Utilities to construct it faster. it looks like the issue may have to do with the multi-block detection script not registering blocks placed by this item

**Comment by bonii-xx** [comment]
Hm, curious. Maybe it did something weird and the TEs were missing. Impossible to tell from the outside.
