### ISSUE TITLE
Silver doesn't work with the smeltery without Thermal Expansion

### ISSUE THREAD

**Issue by Zsashas** [SlimeKnights/TinkersConstruct#1821]
I have Immersive Engineering which adds silver, but silver and gold won't mix to form electrum in the smeltery.

https://i.gyazo.com/19c2a2f7a2cd1b055761ff5d208db2cc.mp4

Also for some reason, it won't let me pour the silver into an ingot cast either.

Other mods that I have that add silver: RotaryCraft, DeeperCaves, ProjectRed. Thaumcraft also adds silver nuggets. Mariculture Vat shows support for Silver and Electrum, but not the Smeltery.

**Comment by bonii-xx** [comment]
We only have inherit Thermal Foundation compat.

**Comment by Zsashas** [comment]
Molten Silver still exists in NEI, though. Shouldn't it work with any silver as long as it's in the ore dictionary?

**Comment by bonii-xx** [comment]
All liquids always exist.

**Comment by Blue64** [comment]
I believe the problem isn't the existence of it, but rather the lack of the standard conversion of it from solid item into molten liquid.
