### ISSUE TITLE
Make Smeltery able to do at least 8 wide

### ISSUE THREAD

**Issue by LexManos** [SlimeKnights/TinkersConstruct#1823]
I DEMAND IT AS YOUR FORGE GOD!
No seriously, 8 per side means we can easily do things divisible by 8, you know.. like a stack... Right now you do 7x9 = 63, with 1 left over, eww.

**Comment by Zsashas** [comment]
Why not increase it to 9x9? 9 ingots in a block/nuggets in an ingot, etc.
