### ISSUE TITLE
Rendering Crash when putting the Traveler's Glove in a Tool Forge

### ISSUE THREAD

**Issue by AuricPolaris** [SlimeKnights/TinkersConstruct#1824]
Hello there,

Not entirely sure this is gamebreaking but at least worth mentioning. Title says it all, log is below. Let me know if you need any further information. Played on Infinity 2.1.3, expert mode enabled, on a KCauldron server. No optifine but BetterFPS and Fastcraft are installed, no indication in the log if they are having an effect. :)

http://pastebin.com/d39RDqVh

**Comment by bonii-xx** [comment]
#1808
