### ISSUE TITLE
Can you please create a 1.8 branch for TinkersConstruct

### ISSUE THREAD

**Issue by LOLDERP** [SlimeKnights/TinkersConstruct#1827]
can you create a 1.8 branch of this mod plz 
because all the mods haven't updated to 1.8.8
plus 1.8.8 forge is still unstable and 1.8 is stable.sure 1.8 has a lot of bugs but 1.8.8 forge is too unstable

**Comment by liach** [comment]
https://github.com/SlimeKnights/TinkersConstruct/tree/rework

**Comment by LOLDERP** [comment]
thats 1.8.8 not 1.8

**Comment by liach** [comment]
it was 1.8 before... checkout a random commit and build and play
