### ISSUE TITLE
tconstruct.armor.player.TPlayerHandler#buildStickURLDatabase causes java.io.IOException

### ISSUE THREAD

**Issue by kratz74** [SlimeKnights/TinkersConstruct#1830]
Problem seems to be in
private final String serverLocation = "https://dl.dropboxusercontent.com/u/42769935/sticks.txt";
Response to this URL is
Error (429)
This account's links are generating too much traffic and have been temporarily disabled!
so mod throws an exception when being started.

I'm currently using old 1.5.5.7 version for 1.6.4 but the same URL is in master too. Please move this to some location that works and update the code. I'll be glad to get this fixed in old 1.6.4 version too (to avoid patching and building it myself).

**Comment by bonii-xx** [comment]
The exception has no impact. No need to fix.

**Comment by kratz74** [comment]
You're right, it just looks bad. :) Maybye try/catch and print a single message instead of full stack trace?

**Comment by bonii-xx** [comment]
Sadly I'm not a time wizard.

**Comment by kratz74** [comment]
It's yours code so it's up to you. :)  I would fix even such a stupid thing in projects that I'm working on (EclipseLink, Glassfish, etc.) if I'm changing the same class for some other reason because customers would keep complaining otherwise.

**Comment by bonii-xx** [comment]
I'm not getting paid to support obsolete code, though. ;P
The codebase it's in is dead.
