### ISSUE TITLE
Toggle button for alloying in the smeltery [Enhancement]

### ISSUE THREAD

**Issue by kd8lvt** [SlimeKnights/TinkersConstruct#1831]
This isn't my original idea, its choobtastic's (on twitch), however, he is streaming at the moment, so I'm passing it on. Basically, in some convenient spot, there would be a button, when you hover over it when the smeltery is alloying, it would say "Currently alloying! Click to disable alloying." and when you click it, it turns off alloying, and it then says, "Not currently alloying! Click to begin alloying." Just a cool little idea that I thought I would pass on to you guys.
Thanks!
-Kd

**Comment by kd8lvt** [comment]
Errr... thats a strange thing you did there github... how do I fix that? Did NOT want the code tag to enable lol

**Comment by bonii-xx** [comment]
Nope.
