### ISSUE TITLE
Crashing with Traveller's gear head and chestplate

### ISSUE THREAD

**Issue by Stephenator0316** [SlimeKnights/TinkersConstruct#1832]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/10/15 3:50 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at tconstruct.tools.gui.ToolStationGuiHelper.drawToolStats(ToolStationGuiHelper.java:64)
	at tconstruct.tools.gui.ToolStationGui.func_146979_b(ToolStationGui.java:182)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.tools.gui.ToolStationGuiHelper.drawToolStats(ToolStationGuiHelper.java:64)
	at tconstruct.tools.gui.ToolStationGui.func_146979_b(ToolStationGui.java:182)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)

-- Screen render details --
Details:
	Screen name: tconstruct.tools.gui.ToolStationGui
	Mouse location: Scaled: (282, 149). Absolute: (846, 431)
	Screen size: Scaled: (534, 293). Absolute: (1600, 877). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Turtlenator'/326, l='MpServer', x=-207.09, y=65.62, z=195.53]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-219,63,193), Chunk: (at 5,3,1 in -14,12; contains blocks -224,0,192 to -209,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2052446 game time, 1240994 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 59 total; [EntityCreeper['Creeper'/5250, l='MpServer', x=-193.50, y=20.00, z=203.50], EntityCreeper['Creeper'/5251, l='MpServer', x=-200.50, y=20.00, z=199.50], EntityZombie['Zombie'/132, l='MpServer', x=-253.56, y=22.00, z=120.13], EntityCreeper['Creeper'/5252, l='MpServer', x=-197.50, y=20.00, z=199.50], EntityZombie['Zombie'/5253, l='MpServer', x=-193.50, y=20.00, z=204.50], EntityCreeper['Creeper'/134, l='MpServer', x=-250.50, y=17.00, z=188.50], EntityItem['item.item.tconstruct.strangefood.edibleslime'/135, l='MpServer', x=-243.97, y=29.13, z=176.25], EntityCreeper['Creeper'/136, l='MpServer', x=-255.41, y=14.00, z=193.00], EntityBat['Bat'/137, l='MpServer', x=-240.50, y=18.10, z=201.75], EntityZombie['Zombie'/5258, l='MpServer', x=-195.50, y=20.00, z=204.50], EntityZombie['Zombie'/5259, l='MpServer', x=-194.50, y=20.00, z=204.50], EntitySpider['Spider'/5262, l='MpServer', x=-246.50, y=72.00, z=255.91], EntityCreeper['Creeper'/145, l='MpServer', x=-236.09, y=13.00, z=128.28], EntitySkeleton['Skeleton'/146, l='MpServer', x=-231.91, y=13.00, z=132.59], EntitySkeleton['Skeleton'/147, l='MpServer', x=-234.50, y=13.00, z=132.00], EntitySheep['Sheep'/148, l='MpServer', x=-227.38, y=70.00, z=131.47], EntitySheep['Sheep'/149, l='MpServer', x=-229.47, y=69.00, z=125.47], EntityPig['Pig'/155, l='MpServer', x=-230.13, y=63.00, z=169.88], EntityPig['Pig'/156, l='MpServer', x=-230.16, y=63.00, z=174.50], EntityPig['Pig'/157, l='MpServer', x=-230.13, y=63.00, z=173.16], EntityPig['Pig'/158, l='MpServer', x=-230.13, y=63.00, z=170.50], EntityPig['Pig'/159, l='MpServer', x=-229.91, y=63.00, z=175.13], EntityPig['Pig'/160, l='MpServer', x=-229.31, y=63.00, z=173.75], EntityPig['Pig'/161, l='MpServer', x=-228.88, y=63.00, z=174.81], EntityXPOrb['Experience Orb'/39, l='MpServer', x=-322.88, y=41.25, z=210.34], EntitySheep['Sheep'/170, l='MpServer', x=-208.53, y=63.00, z=123.53], EntitySkeleton['Skeleton'/184, l='MpServer', x=-196.50, y=20.00, z=205.91], EntitySquid['Squid'/186, l='MpServer', x=-191.53, y=61.00, z=195.76], EntitySquid['Squid'/187, l='MpServer', x=-187.50, y=61.00, z=195.50], EntitySquid['Squid'/188, l='MpServer', x=-199.50, y=61.01, z=194.50], EntityCreeper['Creeper'/190, l='MpServer', x=-195.50, y=73.00, z=230.06], EntitySkeleton['Skeleton'/194, l='MpServer', x=-183.78, y=63.00, z=161.59], EntitySquid['Squid'/195, l='MpServer', x=-196.18, y=61.00, z=198.55], EntityCreeper['Creeper'/196, l='MpServer', x=-189.50, y=49.00, z=264.50], EntityPig['Pig'/197, l='MpServer', x=-178.47, y=64.00, z=258.31], EntityPig['Pig'/205, l='MpServer', x=-160.88, y=63.00, z=261.94], EntityCreeper['Creeper'/217, l='MpServer', x=-156.03, y=48.00, z=128.66], EntitySquid['Squid'/220, l='MpServer', x=-153.19, y=60.00, z=194.66], EntityClientPlayerMP['Turtlenator'/326, l='MpServer', x=-207.09, y=65.62, z=195.53], EntitySheep['Sheep'/222, l='MpServer', x=-153.31, y=63.00, z=223.06], EntityCreeper['Creeper'/94, l='MpServer', x=-279.50, y=69.00, z=129.50], EntitySpider['Spider'/99, l='MpServer', x=-272.53, y=59.00, z=268.72], EntitySheep['Sheep'/100, l='MpServer', x=-272.13, y=75.00, z=265.06], EntitySkeleton['Skeleton'/229, l='MpServer', x=-136.50, y=64.00, z=117.50], EntityCreeper['Creeper'/5477, l='MpServer', x=-211.50, y=74.00, z=249.50], EntityBat['Bat'/6117, l='MpServer', x=-257.31, y=22.00, z=263.55], EntityCreeper['Creeper'/230, l='MpServer', x=-132.59, y=51.00, z=135.00], EntityCreeper['Creeper'/231, l='MpServer', x=-137.44, y=51.00, z=136.97], EntityWitch['Witch'/232, l='MpServer', x=-137.06, y=50.00, z=138.28], EntityWitch['Witch'/233, l='MpServer', x=-130.88, y=51.00, z=137.53], EntitySkeleton['Skeleton'/234, l='MpServer', x=-140.50, y=50.00, z=139.50], EntitySquid['Squid'/235, l='MpServer', x=-144.69, y=61.34, z=184.53], EntitySheep['Sheep'/237, l='MpServer', x=-128.78, y=63.00, z=240.16], EntityCreeper['Creeper'/110, l='MpServer', x=-260.03, y=21.00, z=124.31], EntitySkeleton['Skeleton'/111, l='MpServer', x=-254.47, y=17.00, z=167.91], EntitySkeleton['Skeleton'/112, l='MpServer', x=-257.72, y=15.00, z=169.88], EntitySkeleton['Skeleton'/113, l='MpServer', x=-252.30, y=11.00, z=214.70], EntitySkeleton['Skeleton'/115, l='MpServer', x=-262.50, y=75.00, z=255.50], EntitySpider['Spider'/6905, l='MpServer', x=-253.28, y=76.19, z=194.39]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 493857264 bytes (470 MB) / 2102919168 bytes (2005 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.4.5} [AgriCraft] (AgriCraft-1.7.10-1.4.5.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	Calculator{1.8.9} [Calculator] (Calculator-1.7.10-1.8.9.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	craftingtweaks{1.0.49} [Crafting Tweaks] (craftingtweaks-mc1.7.10-1.0.49.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAA	origin{7.1.0} [Origin] (Origin-1.7.10-7.1.0.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10La.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.9.4} [ProjectE] (ProjectE-1.7.10-PE1.9.4.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	RefinedRelocation{1.1.12} [Refined Relocation] (RefinedRelocation-mc1.7.10-1.1.12.jar) 
	UCHIJAAAA	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHIJAAAA	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAAAA	thaumicexpansion{4.1.1} [Thaumic Expansion] (ThaumicExpansion-1.7.10-4.1.1.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	ThermalScience{1.7.10} [Thermal Science] (ThermalScience-1.7.10-1.1d.f3.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.5} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.5.jar) 
	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHIJAAAA	recycling{1.0.3.6} [Thermal Recycling] (ThermalRecycling-1.7.10-1.0.3.6.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4256' Renderer: 'Intel(R) HD Graphics 4600'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.2.0-102
	Mantle Environment: Environment healthy.
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	ThermalDynamics: -[1.7.10]1.1.0-161
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: forge-10.13.4.1566
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [ClassicProjectE1.2.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by KnightMiner** [comment]
#1808
