### ISSUE TITLE
[Suggestion] Quiver

### ISSUE THREAD

**Issue by xenoflot** [SlimeKnights/TinkersConstruct#1834]
Hi,
I'd like to suggest a Quiver be added to TC. Perhaps it could be implemented by allowing TiCo arrows and bolts to be added directly to the TiCo "vest" slot, or a single-slot container that goes into that same slot.

Cheers,
Xeno

**Comment by bonii-xx** [comment]
Nope.

**Comment by Blue64** [comment]
It'd be more suggestable to request it as an individual item, similar to a portable chest, but specifically for the TiCon compatible arrows (similar to how Forestry Mod has their Backpack collection for example).

Quiver Mobs Mod has a similar thing, they have a bunch of ranged weapons they add, one of which is actually a ```Bow with Quiver``` (3 sticks, 3 string, 3 leather) and you can craft arrow bundles (8 arrows, 1 string) into it (1~8 bundles at a time, it holds a LOT) to reload it, this of course prevents your bow from breaking though as it uses the damage bar, so a separate Quiver would be preferable.

@bonii-xx why so quick to dismiss it if I may ask? It's not exactly all that far fetched of a request, a tinkerer who is creating his own custom arrows would naturally realize eventually "I need somewhere to hold all of these for easy organized access!" (Similar to the lore behind some of the other storage methods).

**Comment by xenoflot** [comment]
> similar to how Forestry Mod has their Backpack collection for example
That's what I was getting at when I said a single-slot container. However, I'm not sure about how others play the game, but I never carry more than a single stack of arrows or bolts. I don't feel it would be necessary or logical for the quiver to hold more than a single stack so adding a quiver item would be in theme but unnecessary.

My intention for this suggestion was twofold. To free up one inventory slot and to give the highly under-loved tico / traveller's gear vest slot some use. I'm disappointed with the abrupt and unexplained shut down of this suggestion but I didn't care to argue it. /shrug

**Comment by Tommy0607** [comment]
Oh, I also think it would be fine if there is a quiver because my bag is always full of different arrows and bolts. Disappointed too.
