### ISSUE TITLE
HungerOverhaul + cutlass + wither crash

### ISSUE THREAD

**Issue by Aeroxia** [SlimeKnights/TinkersConstruct#1839]
With tinkers construct and hunger overhaul, if you have the well fed buff from eating and block while taking wither damage with a cutlass (specifically a cutlass), the game will crash in single player or "Internal server error" boot you in multiplayer.

That was a mouthful. Hunting down the source was not easy.

Crash log: http://pastebin.com/SGaTB5xa

Minecraft 1.7.10
Forge 10.13.4.1558
TConstruct-1.7.10-1.8.5
HungerOverhaul-1.7.10-1.0.0

----- Edit 2 ----- (Sorry, got dependencies mixed up)

Crash log 3: http://pastebin.com/LAtKk10T

With only these mods:

TConstruct-1.7.10-1.8.5
Mantle-1.7.10-0.3.2

**Comment by bonii-xx** [comment]
I doubt this is related to TCon in any way. The cutlass doesn't touch potion effects.

**Comment by Aeroxia** [comment]
Actually the cutlass applies the Speed II potion effect when you block damage with it, and the crash only happens with the cutlass, not any other swords. Without TCon, there is no cutlass, and cannot be any crash. I don't know whether it's on TCon's side or not, but it's obviously part of the equation.

**Comment by Aeroxia** [comment]
Update: This happens with just TCon, with regeneration or fire resistance in place of "well fed".

**Comment by bonii-xx** [comment]
I see, any potion effect that changes health, or rather hurts the player, causes it.
That causes the event to add the movespeed if you're blocking with a cutlass.
There isn't really an easy way to fix that, not to mention that 1.7.10 is done.

**Comment by squeek502** [comment]
Yep, bonii-xx is right. It should be caused when holding a Cutlass and being damaged by any potion effect that causes periodic damage.

Here's what's happening: The wither effect calls `EntityLivingBase.attackEntityFrom` from within its `PotionEffect.onUpdate` method, which is called when iterating the `activePotionEffects` map in `EntityLivingBase.updatePotionEffects`. `EntityLivingBase.attackEntityFrom` fires Forge's `LivingHurtEvent` which Tinkers Construct uses [here](https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/world/TinkerWorldEvents.java#L76-L79) to add the Cutlass speed effect.

This means that TiC is manipulating the `activePotionEffects` map while it is being iterated, leading to the `ConcurrentModificationException` crash.

A simple but incomplete fix would be to not add the Cutlass speed effect if the `DamageSource` is `DamageSource.wither`.

**Comment by bonii-xx** [comment]
Wouldn't prevent it from poison or any other potioneffect that does it

**Comment by squeek502** [comment]
Yep, that's why I said incomplete. Poison uses `DamageSource.magic`

**Comment by Aeroxia** [comment]
Update: Fire Resistance also does it.  Poison does not do it on its own, but will do it with wither also (like the others).

IE:
Poison + Block = No Crash
Fire Resist + Wither + Block = Crash
Poison + Wither + Block = Crash

**Comment by squeek502** [comment]
@Aeroxia, that might be down to how the iterator functions / how the Exception is triggered. With only one potion effect, it might not get the chance to crash, as it needs a second iteration to detect the problem.

At this point, though, we know the cause of the bug. @bonii-xx, do you accept 1.7.10 PRs or are you completely done with supporting 1.7.10?

**Comment by bonii-xx** [comment]
I'm done, but I accept PRs because the jenkins still builds 1.7.10 versions.
