### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by HandGrenade** [SlimeKnights/TinkersConstruct#1842]
Hello,

My console seems to be getting repeatedly spammed whenever a player crafts an item.

Log: http://pastebin.com/WR6Sd3PN

Versions:
Forge - 1541
Tinkers Construct - 1.7.10-1.8.8

I am willing to provide other information if needed.

Thanks

**Comment by Blue64** [comment]
They'll probably also want your Mantle version, as this depends upon that.

**Comment by Blue64** [comment]
And your Java version (I use Java 8 for example)
