### ISSUE TITLE
NoSuchFieldError Crash

### ISSUE THREAD

**Issue by XFactHD** [SlimeKnights/TinkersConstruct#1844]
I am getting a NoSuchFieldError when pressing certain buttons on the keyboard.
http://pastebin.com/DhEWznw2

MC: 1.7.10
Tinkers' Construct: 1.7.10-1.8.8
NEK: not installed

**Comment by bonii-xx** [comment]
notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar)
You were saying? Update it.

**Comment by XFactHD** [comment]
I am not using NotEnoughKeys, that's the problem. The method that is missing the field is an @Optional method from NotEnoughKeys.

**Comment by bonii-xx** [comment]
NotEnoughKeys-1.7.10-1.0.0b29.jar

**Comment by XFactHD** [comment]
Oh, nevermind, I overlooked that. Thanks for pointing it out.
