### ISSUE TITLE
1.8.8-2.0.1 breaks resource pack loading on forge 11.15.0.1650

### ISSUE THREAD

**Issue by ebeneezersquid** [SlimeKnights/TinkersConstruct#1846]
May be a compatability issue between forge and TC versions, or bug in either:
Any resource pack loaded prior to adding TC 1.8.8-2.0.1 (adding mantle is fine) is unloaded, and no resourcepacks can be successfully loaded. 

FML-Client log here: http://pastebin.com/XwGyEyjB
"Latest" log file here: http://pastebin.com/rz2MTvEi

Whatever it is appears to be in the "Latest" log at 22:31:32, but is greek to me. If more info is needed, let me know.

**Comment by bonii-xx** [comment]
Ah, good good. Looks like something goes wrong when reloading the textures. Good catch.

**Comment by bonii-xx** [comment]
Can you provide a link to the resource packs you used?

**Comment by ebeneezersquid** [comment]
First found with John Smith that I had been running on 1.8: https://www.johnsmithlegacy.co.uk/


Attempted again with Pumpkin Patch I downloaded for testing purposes: http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/2372771-pumpkin-patch-resource-pack

**Comment by bonii-xx** [comment]
Try https://dvs1.progwml6.com/jenkins/job/TConstruct_1.8.x/11/artifact/build/libs/TConstruct-1.8.8-2.0.1.jenkins11.jar

**Comment by ebeneezersquid** [comment]
First attempt, crash: http://pastebin.com/skgeX2uV
Removed everything but TC for second attempt: http://pastebin.com/ue7nTKKC

**Comment by bonii-xx** [comment]
Update forge to 1654, there was a compatibility problem.

**Comment by ebeneezersquid** [comment]
Loaded With both PumpkinPatch and JohnSmith 1.8.8 . 
Did experiance a CDT when I added in a a custom resource pack that I had thrown together over the years, but it hasn't been updated for 1.8 yet, so  cannot blame TC for that. 
Generated a world and then added the lastest 1.7 build of JSTR (there is no 1.8 build yet) and had no problems. 
Looks like you fixed it. 
Thank you kindly, sir.

**Comment by bonii-xx** [comment]
Perfect.

**Comment by Renadarain** [comment]
I too, have this problem with http://soartex.net fanver resource pack.  Is there a download for the fix?

regards,

**Comment by bonii-xx** [comment]
Only dev versions.

**Comment by Renadarain** [comment]
Hi Boni,

Thanks, I found one :)

Regards,

**Comment by Renadarain** [comment]
Boni,

Using https://dvs1.progwml6.com/jenkins/job/TConstruct_1.8.x/35/artifact/build/libs/TConstruct-1.8.9-2.0.1.jenkins35.jar - the graphics are invisible on the server but not on single player.

**Comment by bonii-xx** [comment]
I doubt soartex has any compatible version.

**Comment by Renadarain** [comment]
Boni,

I wasn't specific, sorry.  They were invisible even with the default texture pack but I've just updated to .38 version and it's fixed :)

Thank you very much.
