### ISSUE TITLE
Traveller's Glove Crashes Game when put into Tinker's Table, Crafting Station, Tool Forge, etc.

### ISSUE THREAD

**Issue by Electrophobic** [SlimeKnights/TinkersConstruct#1847]
I was trying to add redstone to my Traveller's Glove when the game crashed. I have tried this on many Tinker's table/forges/stations and it always crashes the game. Crash report below.

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 12/26/15 1:56 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at tconstruct.tools.gui.ToolStationGuiHelper.drawToolStats(ToolStationGuiHelper.java:64)
	at tconstruct.tools.gui.ToolStationGui.func_146979_b(ToolStationGui.java:182)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.tools.gui.ToolStationGuiHelper.drawToolStats(ToolStationGuiHelper.java:64)
	at tconstruct.tools.gui.ToolStationGui.func_146979_b(ToolStationGui.java:182)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)

-- Screen render details --
Details:
	Screen name: tconstruct.tools.gui.ToolForgeGui
	Mouse location: Scaled: (219, 196). Absolute: (658, 156)
	Screen size: Scaled: (435, 249). Absolute: (1304, 745). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['MinerLink'/3537, l='MpServer', x=204.50, y=76.62, z=184.64]]
	Chunk stats: MultiplayerChunkCache: 81, 90
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-112,64,256), Chunk: (at 0,4,0 in -7,16; contains blocks -112,0,256 to -97,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1030909 game time, 551067 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 30 total; [EntityBat['Bat'/4291, l='MpServer', x=265.50, y=43.00, z=254.50], EntitySquid['Squid'/4232, l='MpServer', x=141.66, y=62.09, z=224.13], EntitySquid['Squid'/4234, l='MpServer', x=153.28, y=62.34, z=222.50], EntitySheep['Sheep'/3538, l='MpServer', x=130.47, y=64.00, z=115.63], EntitySheep['Sheep'/3539, l='MpServer', x=134.84, y=64.00, z=182.81], EntitySheep['Sheep'/3540, l='MpServer', x=133.13, y=63.00, z=198.94], EntitySheep['Sheep'/3542, l='MpServer', x=154.38, y=64.00, z=175.53], EntitySpider['Spider'/3543, l='MpServer', x=147.88, y=66.00, z=174.44], EntitySpider['Spider'/3544, l='MpServer', x=150.50, y=66.00, z=174.34], EntitySpider['Spider'/3545, l='MpServer', x=147.06, y=66.00, z=180.13], EntityZombie['Zombie'/3546, l='MpServer', x=148.31, y=66.00, z=177.53], EntityCow['Cow'/3547, l='MpServer', x=147.31, y=64.00, z=236.28], EntitySheep['Sheep'/3548, l='MpServer', x=173.25, y=63.00, z=142.28], EntitySheep['Sheep'/3549, l='MpServer', x=180.22, y=63.00, z=112.28], EntityCow['Cow'/3550, l='MpServer', x=191.28, y=74.00, z=236.50], EntitySkeleton['Skeleton'/3551, l='MpServer', x=186.13, y=72.00, z=251.50], EntityCow['Cow'/3552, l='MpServer', x=254.47, y=80.00, z=120.22], EntitySpider['Spider'/3553, l='MpServer', x=253.78, y=86.00, z=137.34], EntityCow['Cow'/3554, l='MpServer', x=267.53, y=83.00, z=112.13], EntityCow['Cow'/3555, l='MpServer', x=264.34, y=83.00, z=119.69], EntitySpider['Grim Spider'/3556, l='MpServer', x=252.38, y=85.00, z=128.84], EntitySpider['Spider'/3557, l='MpServer', x=263.72, y=86.00, z=128.94], EntityClientPlayerMP['MinerLink'/3537, l='MpServer', x=204.50, y=76.62, z=184.64], EntityZombie['Zombie'/3559, l='MpServer', x=266.50, y=80.00, z=170.50], EntityTrail['unknown'/3560, l='MpServer', x=204.50, y=76.62, z=184.64], EntitySheep['Sheep'/3561, l='MpServer', x=271.53, y=86.00, z=238.56], EntitySkeleton['Skeleton'/3564, l='MpServer', x=262.50, y=45.00, z=247.50], EntitySheep['Sheep'/3565, l='MpServer', x=260.47, y=82.00, z=253.59], EntityBat['Bat'/4276, l='MpServer', x=258.22, y=13.00, z=183.53], EntityBat['Bat'/4277, l='MpServer', x=262.00, y=42.76, z=242.13]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 324335504 bytes (309 MB) / 957845504 bytes (913 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_C1 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) 
	UCHIJAAAAAAAAA	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAAAAAAA	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (Gilded-Games-Util-1.7.10.jar) 
	UCHIJAAAAAAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) 
	UCHIJAAAAAAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAAAAAAAAA	BiblioCraft{1.10.3} [BiblioCraft] (BiblioCraft[v1.10.3][MC1.7.10].jar) 
	UCHIJAAAAAAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Core{7.0.11} [BuildCraft] (buildcraft-7.0.11.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Energy{7.0.11} [BC Energy] (buildcraft-7.0.11.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Factory{7.0.11} [BC Factory] (buildcraft-7.0.11.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Robotics{7.0.11} [BC Robotics] (buildcraft-7.0.11.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Silicon{7.0.11} [BC Silicon] (buildcraft-7.0.11.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Transport{7.0.11} [BC Transport] (buildcraft-7.0.11.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Builders{7.0.11} [BC Builders] (buildcraft-7.0.11.jar) 
	UCHIJAAAAAAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.7.10-2.2.8.349} [Ender IO] (EnderIO-1.7.10-2.2.8.349.jar) 
	UCHIJAAAAAAAAA	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) 
	UCHIJAAAAAAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJAAAAAAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAAAAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAAAAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAAAAAAA	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
	UCHIJAAAAAAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAAAAAAA	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJAAAAAAAAA	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UCHIJAAAAAAAAA	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) 
	UCHIJAAAAAAAAA	ExtraUtilities{1.2.2} [Extra Utilities] (extrautilities-1.2.2.jar) 
	UCHIJAAAAAAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAAAAAAA	GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) 
	UCHIJAAAAAAAAA	iChunUtil{4.1.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAAAAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAAAAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited (1).jar) 
	UCHIJAAAAAAAAA	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) 
	UCHIJAAAAAAAAA	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) 
	UCHIJAAAAAAAAA	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) 
	UCHIJAAAAAAAAA	JotatosPracticalities{0.6.2} [Practicalities] (practicalities-1.7.10-0.6.2.jar) 
	UCHIJAAAAAAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJAAAAAAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAAAAAAA	TiCTooltips{1.2.3} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.3.jar) 
	UCHIJAAAAAAAAA	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJAAAAAAAAA	wawla{1.1.1} [What Are We Looking At] (Wawla-1.1.1_1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics'
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	CoFHCore: -[1.7.10]3.0.3-303
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.1-182
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.1.0-161
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.4229, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [F32-1.7.10.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Rakinare** [comment]
This bug is STILL concurrent in the newest 1.7.10 Version.
