### ISSUE TITLE
Outdated NEI API

### ISSUE THREAD

**Issue by Bogdan-G** [SlimeKnights/TinkersConstruct#1848]
Hello. MC 1.7.10, TiC 1.8.8build989, CCC 1.0.7.46, CClib 140, NEI 1.0.5.118
Delving into the log I discovered that CCC swears (the creation and entry into the world):
https://gist.github.com/Bogdan-G/49818619b78dc5ff154c
This means that part of the code is outdated on the side of the TiC?

**Comment by Blue64** [comment]
* [NEITConstructConfig.java](https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/plugins/nei/NEITConstructConfig.java#L11-#L19)
* [RecipeHandlerAlloying.java](https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/plugins/nei/RecipeHandlerAlloying.java#L89-#L92) this appears to be where it throws the error. (It's the only "name" in the entire page)
