### ISSUE TITLE
[MC 1.8.8] Server crash on sword blocking.

### ISSUE THREAD

**Issue by GirafiStudios** [SlimeKnights/TinkersConstruct#1849]
When you use a Tinkers Construct weapon to block a attack from another player on a server, the server crashes.

Crashlog: https://gist.github.com/GirafiStudios/50146ebd214d242dd996

**Comment by bonii-xx** [comment]
Argh. The good old why-is-this-method-clientside-only. Thanks!

**Comment by GirafiStudios** [comment]
Indeed ^^
Just another thing, which I thought didn't have to be in a separate issue. Slime Islands is VERY common. I assume it's because of the new type of island.
Screenshot (With Journeymap): https://gyazo.com/843533cbfdb5638d3ac9fe262e3e6d6f

**Comment by bonii-xx** [comment]
Might be RNG. You can set the rarity in the configs.

**Comment by GirafiStudios** [comment]
I have done a few test worlds, and they have been everywhere everytime. But thanks I will use the config ^^

**Comment by bonii-xx** [comment]
I already increased it, they shouldn't be that common. What does your config say? Maybe you can play around with it to see if it works properly.

**Comment by GirafiStudios** [comment]
It's on 430 by default, which seems like a good number to me. Okay, i'm gonna play around with it for a bit ^^

**Comment by GirafiStudios** [comment]
How many different kinds of islands is there?

**Comment by GirafiStudios** [comment]
It looks like to me when a slime island spawn, another one always spawn nearby.
Also I just noticed that some non-slimy trees can generate on the islands: http://prntscr.com/9j4sq0

**Comment by GirafiStudios** [comment]
Hmm the config option seems to make it more rare, although it seems that 9 out of 10 times a slime island generate another one generate within 100-200 blocks of it.

**Comment by bonii-xx** [comment]
There is no correlation between islands or types, as long as MC itself doesn't recall the stuff with different seeds that's just "bad" RNG.

If you have a better value for rarity, I'm open for suggestions.

**Comment by GirafiStudios** [comment]
I bumped it up to 900 and that seems to make it a lot better :)
But yeah sure the RNG have a say in this too, I have just done a lot of test worlds with pretty much the same results (15+)
Btw. do you care about bug reports for jenkins builds?

**Comment by bonii-xx** [comment]
Depends on whether it's an actual bug or something I'm currently working on ;o

**Comment by GirafiStudios** [comment]
Well TiCon is crashing with the latest 1.8.8 Jenkins version, Mantle version & Forge version :3 
Crashlog: https://gist.github.com/GirafiStudios/73ed73e2ee9f52043307

**Comment by bonii-xx** [comment]
Needs Forge 1654

**Comment by GirafiStudios** [comment]
Yeah I noticed :3 The build failed at first tho, when the PR got merged ;)
