### ISSUE TITLE
[1.8.8] Crash when mining stone with hammer - java.lang.ArrayIndexOutOfBoundsException: 16 	at net.minecraft.block.Block.getHarvestTool(Block.java:2021)

### ISSUE THREAD

**Issue by BBoldt** [SlimeKnights/TinkersConstruct#1850]
https://gist.github.com/b5c335554868cfe83c50

Similar issue with buildcraft:
https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues/79

**Comment by bonii-xx** [comment]
You have a block in your world that is implemented incorrectly. Neither TCons nor Buildcrafts fault, but the mod that adds the block. It'll crash with everything.
