### ISSUE TITLE
Crafting Station sometimes deletes items after leaving/entering the game. (v1.8.8)

### ISSUE THREAD

**Issue by ariosos** [SlimeKnights/TinkersConstruct#1851]
This one is intermittent, and I'm sure is more of a single player issue.

Steps to Reproduce - 

1. Place any item into a crafting station (standard or compact). Multiple items seem to make the bug happen more often. (best to fill up the entire grid with items). It almost seems like vanilla items have a less chance of being deleted.

2. Take note of what is in the grid and leave the game.

3. Open up the world and look at the inventory of the crafting grid.

Sometimes items will be deleted, or only some items will show, and removing others. It's almost as though it reverts back to a previous state.

using a private modpack (will make a list soon)

**Comment by ariosos** [comment]
Here's the modlist -

![modlist2](https://cloud.githubusercontent.com/assets/7917753/12043990/83558e82-ae58-11e5-80ab-c5197ba75b4d.jpg)
![modlist3](https://cloud.githubusercontent.com/assets/7917753/12043989/835369ae-ae58-11e5-82ef-df3178407b64.jpg)
![modlist1](https://cloud.githubusercontent.com/assets/7917753/12043991/8355a728-ae58-11e5-9830-fdcea7d9f53a.jpg)

**Comment by bonii-xx** [comment]
Sounds more like something is preventing your chunks from saving properly.
