### ISSUE TITLE
Thaumcraft Wand Focus: Excavation can mine cobalt and ardite

### ISSUE THREAD

**Issue by CaelTheColher** [SlimeKnights/TinkersConstruct#1852]
**Tinkers Construct version**: *1.7.10-1.8.8*
**Thaumcraft version**: *1.7.10-4.2.3.5*
**Video**: *https://youtu.be/o2LaMB8oZuQ*

**Comment by laz2727** [comment]
Excavation focus can mine *anything*. That's normal.

**Comment by Blue64** [comment]
Except bedrock due to -1 hardness.

**Comment by bonii-xx** [comment]
I will allow it.
