### ISSUE TITLE
Extreme unplayable lag on nvidia geforce 940m

### ISSUE THREAD

**Issue by TemperedChrome** [SlimeKnights/TinkersConstruct#1854]
When I load up the game, it loads just fine with no other mods installed other than Mantle and TC for 1.7.10. Then when I reach the title screen it becomes unplayable and tanks at like 3 frames.
when I load into a game and it opens up, it is still the same framerape at like literally 3-7 frames per second. Please help me fix this and you may ask for any logs you like ;D
(BTW it runs fine on my sister's laptop with the same mods except that laptop is a thinkpad from like 3 years ago)

**Comment by bonii-xx** [comment]
Get your laptop to actually use your dedicated graphic card instead of the bulitin intel one.
