### ISSUE TITLE
Swords use up 5-10 durability per hit - 1.8.8/1.8.9

### ISSUE THREAD

**Issue by Imnuts7** [SlimeKnights/TinkersConstruct#1858]
Not sure if this is intended or not, a simple strike uses up a lot of my swords durability

**Comment by Imnuts7** [comment]
Broadsword also has the issue

**Comment by bonii-xx** [comment]
Durability used depends on damage dealt.

**Comment by Imnuts7** [comment]
I think that is a rather unfair change. It makes endgame swords have about only 30 uses before they are broken
