### ISSUE TITLE
[Enhancement] Add more tools to tool rack

### ISSUE THREAD

**Issue by hron84** [SlimeKnights/TinkersConstruct#1860]
I started playing with Project Ozone, and I tried to hang on some tools to the Tool rack, but I wasn't too successful.

The following stuffs should be whitelisted:

 - [ExtraUtilities] Builder's Wand (this should be whitelisted for Drying racks too
 - [ThermalExpansion] Flux Transfuser
 - [ThermalExpansion] FluiVac

Affected versions:
 - Thermal Expansion: 4.0.3B1-218
 - ExtraUtilities 1.2.12
 - Tinker's Construct 1.8.8

**Comment by bonii-xx** [comment]
I assume you mean Bibliocraft tool racks? TCon doesn't add any.

**Comment by hron84** [comment]
@bonii-xx ohh, really, sorry.

**Comment by bonii-xx** [comment]
You can add items to the toolrack and stuff in the bibliocraft config btw.

**Comment by hron84** [comment]
@bonii-xx thanks. btw, Drying racks are not allow Builder's Wand too.
