### ISSUE TITLE
materialtraits.stonebound bug

### ISSUE THREAD

**Issue by shader301202** [SlimeKnights/TinkersConstruct#1863]
Hi. When my Pickaxe has been upgraded (I'm using Iguanas Tinker Tweaks), I get this: http://i.imgur.com/MH3frQe.jpg
Forge version: 10.13.4.1566
Tinkers Construct: 1.8.8
Mantle: 0.3.2b

**Comment by shader301202** [comment]
I have this bug only in multiplayer.

**Comment by bonii-xx** [comment]
Looks like a missing localization
