### ISSUE TITLE
Being hit by a Twilight Forest Hydra fireball crashes the game.

### ISSUE THREAD

**Issue by ikkonoishi** [SlimeKnights/TinkersConstruct#1865]
https://gist.github.com/ikkonoishi/5243ca63d7bfd67030d5

After restarting the game crashed again.

https://gist.github.com/ikkonoishi/60a7a4500695776baa2f

**Comment by bonii-xx** [comment]
Hm, looks like Benimatic forgot to pass in the actual projectile while dealing damage. Should probably be fixed on his side.
