### ISSUE TITLE
[1.8] Resource Pack Loading Issue

### ISSUE THREAD

**Issue by Shadows-of-Fire** [SlimeKnights/TinkersConstruct#1866]
Testing using ONLY:  
Forge 11.15.0.1691  
TConstruct1.8.8-2.0.1  
Mantle0.6.jenkins60  
John Smith Legacy JSC v1.1.24

Attempting to load a resource pack with this version of TiC/Mantle results in http://pastebin.com/X7dpAXdw as an error. (Full fml-client-latest.log provided for anything it could help provide)

**Comment by bonii-xx** [comment]
#1846
