### ISSUE TITLE
[Enhancement] The Sharpening Kits

### ISSUE THREAD

**Issue by Eneitilyn** [SlimeKnights/TinkersConstruct#1869]
Hello I have been following streams and videos and I am loving the new tinker's construct versions for 1.8.9! But I have a suggestion or enhancement if you will... for the new sharpening kits they should really be multiple time use things instead of you use it once on a wood tool for example and BOOM you get a obsidian mining level permanently. I am not saying they are broken or anything it just makes sense to do so for example what if they were temporary for like 50% of the durability of the tool allows it to mine higher level mining and then it reverts back after you use it up and need to upgrade it again what if for example after you use that upgrade it lowers your durability of the tool by percentage for the time being while it's active and to get the original durability and mining level of the tool you need to upgrade it with the old original tool part to fix it's durability and that also removes the mining level upgrade ? Just couple of ideas I thought about after seeing those because i love the concept!

**Comment by KnightMiner** [comment]
The point of them is so you can have higher mining levels without losing the earlier traits. If an obsidian sharpening kit are not going to be as useful as a obsidian tool head, you might as well just make the head out of obsidian.

Also, mining levels are hardly overpowered, it is just a forced requirement for tools to mine better materials. You might as well not force users to only use the highest tier, especially with Boni's plan of having no "top tier" tool that is the best without a doubt
