### ISSUE TITLE
[1.8.8-2.0.1] Crash: Compatibility issue with Buildcraft (7.2.0-pre6)?

### ISSUE THREAD

**Issue by Xiaminou** [SlimeKnights/TinkersConstruct#1871]
Crashed when I placed a Golden Transport pipe in a Tcon Crafting Table. I tried removing the rendering but that didn't fix it.
(reported on both githubs)
Edit: as expected, disabling Buildcraft fixed it. However it seems like the option to disable render on of Tcon's table does not work. They still render items even when the option is set to false. Which means my first theory might be right.

Crash Report: http://pastebin.com/q4hMaaiL

**Comment by bonii-xx** [comment]
Already fixed indev.

**Comment by Xiaminou** [comment]
Got this once again with Botania, when are you going to release the latest build?

**Comment by bonii-xx** [comment]
If you don't want bugs you probably shouldn't be playing with an alpha version. :P
I will release some build at some point.

**Comment by Xiaminou** [comment]
Well I don't mind bugs, anyhow I built the latest myself and that fixed the bug, problem solved.

**Comment by Gaelan** [comment]
Don't know if this needs to be fixed on a per-mod basis, but Chisels & Bits has the same problem (chiseled blocks).
