### ISSUE TITLE
1.8.9 build 2.0.1.jenkins41 mining gold

### ISSUE THREAD

**Issue by kurokuno** [SlimeKnights/TinkersConstruct#1872]
right now you need gold to make casts however you need at least iron tools to mine gold so its impossible with the smeltery on to make casts using purely tinkers just felt i should drop this up here incase its an oversight

**Comment by bonii-xx** [comment]
I am aware.

**Comment by laz2727** [comment]
You technically can still do it by farming some gold in the nether.

2016-01-13 16:52 GMT+05:00 boni <notifications@github.com>:

**Comment by jengeld4** [comment]
Or you can just use a vanilla iron pick to mine the gold. No need to over think it

**Comment by oitsjustjose** [comment]
Or, find Gold Ore and use TNT / a creeper to gather it. I did this on my world, never made a vanilla pickaxe, and just sacrificed a few pieces of gold :P

**Comment by topisani** [comment]
Do you plan to readd the ores? aluminum/copper/tin

**Comment by laz2727** [comment]
It would be better to add zinc instead(there's a gh issue about that). You
probably won't be able to smelt aluminium ore into ingots with just heat
irl :D


2016-01-29 23:46 GMT+05:00 topisani <notifications@github.com>:
