### ISSUE TITLE
[1.8.9] Ingot Cast don't go into the pattern chest

### ISSUE THREAD

**Issue by GirafiStudios** [SlimeKnights/TinkersConstruct#1873]
Using build: TConstruct-1.8.9-2.0.1.jenkins41

**Comment by bonii-xx** [comment]
Casts don't go into pattern chests together with patterns.

**Comment by laz2727** [comment]
They did in 1.7.10.

2016-01-13 16:36 GMT+05:00 boni <notifications@github.com>:

**Comment by bonii-xx** [comment]
Turns out he was correct, he just described the wrong problem. Fixed either way.
