### ISSUE TITLE
[1.8.9] Mod Compatibility: Vein Miner (Minor)

### ISSUE THREAD

**Issue by claws61821** [SlimeKnights/TinkersConstruct#1874]
Minecraft 1.8.9
Forge 1.8.9-11.15.0.1695
Mantle 1.8.8-0.6
Tinker's Construct 1.8.8-2.0.1
Vein Miner 1.8.9-0.31.2

I'm running the above mods (and others) in default configuration, except for having added several TCon tools to Vein Miner using the "TConstruct:[tool]" ID format.

My testing has not been extensive, but I can confirm that Vein Miner works with Vanilla tools.

Preliminary testing concludes that Vein Miner currently does not work with the following Tinker's Construct tools:
Shovel
Pickaxe
Hatchet
Excavator
Hammer

I recognize that this is a minor issue, and that it might be sourced in the other relevant mod, but I thought it would be appropriate to bring this to developer attention at this time while this mod is being actively rewritten.

**Comment by bonii-xx** [comment]
Probably on VeinMiners side, since it does the blockbreaking.

**Comment by claws61821** [comment]
From Vein Miner's MCF thread, opening post.
"Actually uses the tool to mine, so drops are correct."

This seems to me to imply that Vein Miner calls on the tool to break each block, but I don't know enough about deobfuscation or javascript to personally look into it. I will post to PortableJim's hub shortly to see whether he has any recommendation of action for me regarding the issue posted above.

Thank you for your time.

**Comment by squeek502** [comment]
@claws61821, what does "Vein Miner currently does not work with the following Tinker's Construct tools" mean, exactly?

**Comment by claws61821** [comment]
@squeek502 Vein Miner, when properly configured and activated, is supposed to allow a player to aim a compatible tool at a given block and break all connected blocks of that type at the expense of durability and hunger. When I say that "Vein Miner does not work--", what I mean is that I have configured it to work with a particular tool and activated it, but that it only breaks the singular block at which I am aiming.

**Comment by squeek502** [comment]
The only way this problem could be on Tinkers' Construct's end would be if TiC tools did not trigger Forge's BlockEvent.BreakEvent, which seems extremely unlikely. As @bonii-xx said, it's probably on VeinMiners side.

**Comment by bonii-xx** [comment]
I bet he uses instanceof instead of actually checking harvest capabilities. :P

**Comment by bonii-xx** [comment]
The blockbreak event did indeed not survive the change to 1.8.9 for AOE-Tools like hammers. Pickaxes break blocks like any other tool. I doubt it's related.

**Comment by portablejim** [comment]
I am using a test for the InfiTool NBT tag. Normally Veinminer works of whether you can harvest the block, and works with the BlockBreak event. I have special support for Tinkers because I noticed all the tinkers tools can return false even when mining is successful.

I need to investigate further.

**Comment by claws61821** [comment]
My thanks to all of you for your clarifications to date, @bonii-xx, @squeek502, and @portablejim. I look forward to following your progress.

**Comment by bonii-xx** [comment]
They should behave just like regular tools when it comes to blockbreaking, what returns false?

**Comment by portablejim** [comment]
Sometimes (i think when modifiers like autosmelt are on the tools) tryHarvestBlock returns false.

Anyway, testing it out, everything worked, so this can be closed.

**Comment by bonii-xx** [comment]
Autosmelt would return false because it doesn't actually break the block, but manually drops the item and sets the block to air (since otherwise you'd get both, the block and the smelted block). Everything else should work fine though, glad to hear.
