### ISSUE TITLE
repeating sound file locking up world 1.8.9 jenkins 41

### ISSUE THREAD

**Issue by kurokuno** [SlimeKnights/TinkersConstruct#1875]
ok so real big bug this time i was on a purple slime island and i broke some slime and killed some blue slimes then out of nowhere the world FPS dropped to 0-1 and so i reload and after about 5-10 seconds it tanks again to 0-1 fps 

notice the constant annoying sound of slime bouncing almost like the blocks do when you jump on them turn off my sound fps instantly jumps back up to 60 tps is still horrible so i blow the island up in creative then the entire world instantly fixes its self no more tps issues turn back up my sound no more issues

**Comment by bonii-xx** [comment]
Probably caused by the item getting stuck and playing sounds every tick. I don't think Minecraft has a way to prevent/limit sound events.
