### ISSUE TITLE
Multiple Bugs/May not be Inplemented (1.8)

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [SlimeKnights/TinkersConstruct#1879]
1. I bucketed some blue slime, i'm pretty sure that's not supposed to happen.
2. I put Blue Slime Liquid into the smelter, and now i'm unable to get it out.
3. I made some obsidian in the smelter, also unable to get it out.
4.  Unknown if Bug- After putting Lapis on my Tcon pickaxe, the name turned blue, I'm not sure this was intended or not. (Exactly fortune one)
5. A slime island I came across had snow on it, while below it it was raining. Not sure this is of fault of TCON, but you would think it would be snowing lower down when I was in a Tundra biome. 

6. (This may just not be implemented.) None of the liquids are able to be drawn out with a bucket when right clicking on the Smeltery drain, it also won't fill the bucket when it's in the casting table itself. This results with bugs 2 and 3, being unable to get liquids out.

**Comment by bonii-xx** [comment]
4-5: Vanilla Minecraft
Rest: You're looking for tanks.
