### ISSUE TITLE
Material/modifier/tool/recipe editing/removal APIs

### ISSUE THREAD

**Issue by asiekierka** [SlimeKnights/TinkersConstruct#1883]
This will be useful both for my pack and for future ModTweaker-esque mods.

I'm willing to help out, I just need a general idea of what you want the APIs to be like. I saw you have an event-based one for materials (a similar concept could probably do for removing/overwriting modifiers and tools and etc), but that probably won't do for things changed dynamically like recipes.

**Comment by bonii-xx** [comment]
Yep, that's what the events are for. Recipes are recipes, there's no api to provide there.

**Comment by YaibaToKen** [comment]
Hello, not wanting to hijack someone else's issue but being sure this small question doesn't warrant a new one, I'm currently writing some MineTweaker/ModTweaker scripts and needed help finding the name of some items and blocks, more specifically, where to find the names of your nuggets, ingots and ores.

Thanks for the time and sorry if I'm out of place.

**Comment by KnightMiner** [comment]
All the internal names can be viewed in game using `F3` + `H`. Note that most items also require metadata and not just an ID name, which can be viewed at the top after the data value.

**Comment by YaibaToKen** [comment]
Thanks, wish I knew that sooner. Though I have a question. In the case of the Iron Nugget, all it shows is: TConstruct:materials. I assume that entry contains multiple materials. Any idea or tip on how to get the specific entry for the Iron Nugget? Apologies if I sound dumb.

**Comment by KnightMiner** [comment]
Like I said above, you need the metadata. The top after the name is says something like `(#40/8)`, just take the number after the slash for the metadata (minetweaker format for metadata is a second colon after the name, e.g. `<tconstruct:materials:8>`)

**Comment by YaibaToKen** [comment]
Thanks, I feel so dumb now, didn't understand what you had said at first. Got everything to work now. I guess reading stuff like this at 2am ain't my smartest move. Just a reminder to anyone else who might see this: Capitalization matters!
