### ISSUE TITLE
Crash when Attempting to block with Sword

### ISSUE THREAD

**Issue by kingofrunes** [SlimeKnights/TinkersConstruct#1891]
Java 8
Tinkerer's Construct 1.8.8-2.0.1

Here is the full crash report: http://pastebin.com/AX3xtFTC

How to replicate:
1) Craft Vanilla Wooden Sword (Probably effects most swords you can make, vanilla or Tinkerer's alike)
2) Attempt to block creeper explosion or skeleton arrow attack with sword
3) Game Crashes

This crash also crashes the server if it's on a server.

**Comment by bonii-xx** [comment]
#1849
