### ISSUE TITLE
Texture packs unusable

### ISSUE THREAD

**Issue by xhiyikfkox** [SlimeKnights/TinkersConstruct#1893]
Using the Tinkers Construct 1.8.8-2.0.1 and once added to my mods folder I am unable to use texture packs. Upon removing the mod texture packs work. With Tinkers in the mods folder you can select your texture but when brought back to options screen no changes to texture are made. Upon clicking resources button no texture pack is set to be used. You can re add the one you want but it never changes it over. Once removed from the mods folder all texture packs work fine.

**Comment by xhiyikfkox** [comment]
sorry if it was a duplicate but didn't see mention of this bug in the titles of any of the listed bugs.

**Comment by bonii-xx** [comment]
#1866 and #1846
They're closed, you probably didn't look there. ;)

**Comment by xhiyikfkox** [comment]
Good Point, I didn't check there. I am guessing something like this might happen when your working on the alpha build for next version then somewhat regularly? Either way great mod, love it and can't imagine minecraft without it in a mod pack, even if its just a pack for myself to enjoy LOL.
