### ISSUE TITLE
1.7.10 - Disenchanting tools with Draconic Evolution

### ISSUE THREAD

**Issue by mtmollen** [SlimeKnights/TinkersConstruct#1895]
MC: 1.7.10
Mod Pack: FTB Infinity Evolved (hard mode) 2.2.2
Mod versions:
Tinkers' Construct 1.8.8
Draconic Evolution: 1.0.2-snapshot_8-MC1.7.10
ExtraTiC: 1.4.5

With the Draconic Evolution Disenchanter I am am to remove the "enchantments" that are on my tools, however this does not remove the labels on the tools so my pickaxe is still showing the relevant modifiers.

In my particular case, the pickaxe is: Ardite Tools Rod, Ardite Binding, Enderium Pickaxe Head.

The modifiers added were: Lapis (450/450), Redstone (200/200), Flux. I also had applied the nether Star, Diamond/Gold & Apple/Diamond sets for more modifiers.

As a test I placed the pickaxe into the DE Disenchanter and was able to remove the Luck/Fortune III enchantment, however the tool still shows Luck on it's tooltip (minus the Fortune III/Looting III). The tool however does not show that a new Modifier is available despite losing the enchantment.

I would assume this isn't intended behavior however I am unsure if this is from the DE or TC side.

EmptyM

**Comment by bonii-xx** [comment]
Can't be prevented because vanilla. :(
