### ISSUE TITLE
another crafting station crash

### ISSUE THREAD

**Issue by LlubNek** [SlimeKnights/TinkersConstruct#1896]
TConstruct crashed while I was adding cobble to the crafting grid to construct a vanilla pickaxe.

Here's the crash report:
http://pastebin.com/5wfgEFCq

**Comment by bonii-xx** [comment]
That's a really weird crash. Most likely caused by some of the other mods. Is it reproduceable? If yes, does it go away if you remove ChunkAnimator?

**Comment by LlubNek** [comment]
So far I've only seen it happen once.  If it happens again, I'll post another crash report under this issue.  I doubt it's ChunkAnimator though; as I understand it ChunkAnimator actually does very little, though the results are fairly dramatic.

**Comment by bonii-xx** [comment]
It does rendering things though, and it has a coremod, and the crash happens in vanilla rendering where there shouldn't be a crash, so it's still quite likely.
