### ISSUE TITLE
[1.8.9] Crafting Station Crash with NeoTech

### ISSUE THREAD

**Issue by Dyonovan** [SlimeKnights/TinkersConstruct#1897]
Getting a crafting station crash with my Tanks.

CrashLog: http://pastebin.com/ArpB7eHb
ModelTank Class: https://github.com/TeamBR-Modding/NeoTech/blob/1.8.9/src/main/scala/com/dyonovan/neotech/client/modelfactory/models/ModelTank.scala

Let me know if there is anything else you need.

https://github.com/TeamBR-Modding/NeoTech/issues/45

**Comment by bonii-xx** [comment]
Nothing wrong on your side, fixed indev. Rendering was missing a check for the old vanilla style models.
