### ISSUE TITLE
Smeltery Items are not added to the game

### ISSUE THREAD

**Issue by ThomasRules2000** [SlimeKnights/TinkersConstruct#1899]
In version 2.0.2 of the rewrite, none of the smeltery related items are available in the game (at least to jei or the creative menu). The smeltery tab still appears, but is empty of items and blocks.
This happens on both forge 11.15.0.1710 and 11.15.0.1715
![2016-01-23_00 12 13](https://cloud.githubusercontent.com/assets/9560650/12526515/138558aa-c166-11e5-873b-58bcadcf6363.png)

**Comment by ThomasRules2000** [comment]
My Mod List (excludes core mods e.g: mantle):
Bagginses - LordDusk
Baubles - Azanor
Baubles-HUD - Gigabit101
Better Achievements - way2muchnoise
Biomes O' Plenty - Adubbz, Amnet, Cheeserolls, Forstride, ted80
Blood Magic - WayofTime
Botania - Vaskii & williewillius
Buildcraft - SpaceToad, BuildCraft Team
Chisel - tterrag1098
Chisels & Bits - AlgorithmX2
ComputerCraft - Dan200
Ender Zoo - CrazyPants
Flat Coloured Blocks - AlgorithmX2
Fluxed Solars	Primetoxins
FluxedRedstone - AlgorithmX2
HelpFixer - matthewprenger
In-Game Wiki Mod - MineMaarten
Inventory Tweaks - Kobata
Iron Chest - cpw
JEI Addons - mezz
JourneyMap - techbrew, mysticdrew
Just Enough Items - mezz
Just Enough Resources - way2muchnoise
MCMultiPart - amadornes
MmmMmmMmmMmm - boni
Open Computers - sangar
Optifine - sp614x
PneumaticCraft - MineMaarten
RFTools - McJty
Similsax Transtructors	Vorquel
Simple Inventory Sorting - cpw
Simple Retrogen - cpw
Storage Drawers - jaquadro
Thaumcraft 5 - Azanor
Tinkers Construct - boni
Waila - ProfMobius
WAWLA - Darkhax

**Comment by Imnuts7** [comment]
Oh I think you have to enable it in the config files, go look for the option to enable smeltery

**Comment by ThomasRules2000** [comment]
There doesn't appear to be one, and B:registerAllItems=true only enables seared bricks

**Comment by Imnuts7** [comment]
I have a TinkerModules config that enables the smeltery

**Comment by ThomasRules2000** [comment]
My config file: http://pastebin.com/qdUc4aGX

**Comment by ThomasRules2000** [comment]
And in tinkermodules.cfg all the values are set to true

**Comment by ThomasRules2000** [comment]
Seems to have fixed itself (idk how)
