### ISSUE TITLE
[1.8.9] Smeltery GUI crash

### ISSUE THREAD

**Issue by Arcaratus** [SlimeKnights/TinkersConstruct#1900]
TConstruct: 1.8.9-2.0.1-jenkins138
Forge: 11.15.0.1705

Crashes game when hovering over molten fluids (in this case it was molten gold) within the smeltery
LOG: http://pastebin.com/b4vQW9Tc

EDIT: How do you register liquid names/amounts within the smeltery? My guess is that gold and other metals are not being registered properly

**Comment by bonii-xx** [comment]
That's not a version of ours.
