### ISSUE TITLE
1.8.9 - 2.0.2 - Render Issue

### ISSUE THREAD

**Issue by TotalHamman** [SlimeKnights/TinkersConstruct#1901]
Updated Unstable to 3.0.15 and my server is not rendering any placed Tinker's Construct blocks or the slime islands.  However I can open the world in single player and render everything as well as create new world with the same seed and render everything.

I know that the blocks are present because I am unable to occupy the block space after placing.  

I can upload logs, screenshots, or part of the world (did a 6000x6000 pregen on the world) to aid in troubleshooting.

**Comment by bonii-xx** [comment]
Were there already Tcon blocks in the world from previous modpack versions?

**Comment by TotalHamman** [comment]
Actually yes, I pregenned on a version with TCon.  Then they removed the mod and now that it is back I'm seeing this issue.

So unless there is a magic flag that restores TCon blocks I'm guessing this world is a loss?

**Comment by bonii-xx** [comment]
@cpw ^ Looks like we got a new test case for the block registry

**Comment by TotalHamman** [comment]
Let me know if you need the world folder uploaded.  I did add a couple mods that unstable did not have - Better Rain, Neat, Roguelike Dungeons.  I also have BoP, Fast Leaf Decay and Thaumic Infusion disabled.

If you need the world just let me know, or I can enable whitelist access for either of you to poke around in the world.

Let me know what you both need to troubleshoot this best.

**Comment by bonii-xx** [comment]
What Forge version was the world generated with? (including Tcon)

**Comment by TotalHamman** [comment]
About 90% sure I pregened using Unstable 3.0.7 which would be forge-11.15.0.1697 and Tcon 1.8.9-2.0.1.jenkins42.  I know that after the pregen was complete I updated the server to Unstable 3.0.9 before playing.

**Comment by TotalHamman** [comment]
I then updated the server as soon as a new version on Unstable was out and I could update it.  Currently the server is me and me only :/

**Comment by Aelar-Nailo** [comment]
Can i join in the fun?

**Comment by Cleardragonf** [comment]
i found if you start up your world without tconstruct those 'invisibilble' blocks go away as you've removed them when forge starts up this is bye the fml confirm.  I don't even see smelteries in the creative tab :( but when i tried placing a cralfting station down i found that invicisible block bug too.  just a heads up

**Comment by bonii-xx** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/ecfb9accaae8102856cc1a4faff083a4d4a491fd
