### ISSUE TITLE
1.8.9-2.0.2 Test Alpha build bug

### ISSUE THREAD

**Issue by tecroach** [SlimeKnights/TinkersConstruct#1904]
when using a chest and hopper, there a way to delete and make new stuff but it's like one to one.

when the hopper have at least it's 1st slot filled and a bit left over there is a Unknow % that it deletes any "New" block or item when it draws them from the chest to input in to the smeltery and any deleted blocks or item turn into the 1st slot block or item.

So far I gotten it to turn gold and iron into cobblestone.

I cant say when it will happen but it seem once in a while when you overload the hopper that when it seem to happens the most.

**Comment by bonii-xx** [comment]
Can you reproduce that in 2.1.0, and if so, a screenshot of the setup?
