### ISSUE TITLE
NullPointerException in  crafting station

### ISSUE THREAD

**Issue by LlubNek** [SlimeKnights/TinkersConstruct#1905]
Minecraft crashed when crafting a seeds block from EverythingBlocks.

Here's the crash report:
http://pastebin.com/44REwgGx

**Comment by LlubNek** [comment]
Here's a second crash report (definitely repeatable):
http://pastebin.com/MBTtw09K

**Comment by bonii-xx** [comment]
EverythingBlocks issue.
