### ISSUE TITLE
1.8.9 Smeltery Looses all Items melting on structure break

### ISSUE THREAD

**Issue by pauljoda** [SlimeKnights/TinkersConstruct#1907]
I'm not sure if intentional, but it seems like all items are removed. I can understand removing those relevant to that layer but I'm not sure this was intentional.

I had a two layer smeltery, all slots were full of cobblestone that were at full heat but had no space to melt, broke a block on the second layer so I could hop on top to add the third layer to make space and when it reformed all items that were melting were gone. Also, when reduced to one layer it still didn't activate. I assume because it was trying to fit all fluids from two layers into one and if so I that makes sense. Just letting you know a behavior that seemed a little off.

**Comment by tecroach** [comment]
It seem it like the bug i found too, Maybe the two bugs we found are the same one, here the link to my https://github.com/SlimeKnights/TinkersConstruct/issues/1904

But i think your and my report of a bug is the same one.

**Comment by bonii-xx** [comment]
TCon and Forge version? Are you playing in singleplayer or multiplayer?
Items whose slots don't exist anymore when the smeltery resizes are dropped out of the front of the smeltery controller.

**Comment by pauljoda** [comment]
Forge 1715, Tinkers 1.8.9-2.0.1 jenkins build 138. It was on a multiplayer server. I only broke a block on the second level, not the bottom and still all items were gone and not dropped out the front. If you can no replicate it perhaps something else was at play here but that is what I have observed. Hope this helps

**Comment by bonii-xx** [comment]
That's not even one of our builds. update to 2.0.2
