### ISSUE TITLE
[Bug] Pattern Chest not keeping items

### ISSUE THREAD

**Issue by DrZed** [SlimeKnights/TinkersConstruct#1908]
IGNORE

**Comment by bonii-xx** [comment]
No I will not support IGNORE, IGNORE is overpowered!

**Comment by DrZed** [comment]
xD, I grabbed latest build from jenkins not thinking of checking curse, curse's version didn't have the bug.

**Comment by DrZed** [comment]
On a side note, did you disable range changing on hammers? If not how to do so? Item? Key?

**Comment by bonii-xx** [comment]
Range changing..? The expanders?

**Comment by DrZed** [comment]
Ah, Expanders, thanks :D. now if only you would make it not centered xD Like draconic ranged mining.

**Comment by codewarrior0** [comment]
Agree. With the vertical expander on, digging tunnels makes me go "Ouch! My neck!"
