### ISSUE TITLE
[1.8.9-2.0.2] Inconsistency between 1.7.10/1.8.9 HarvestTool block placing

### ISSUE THREAD

**Issue by 61352151511** [SlimeKnights/TinkersConstruct#1910]
In 1.7.10 right clicking with a harvest tool would place the "block" to the right of it in the hotbar, except if the selected slot was 0, in the case it would go to slot 8. [1.7.10 Code](https://github.com/SlimeKnights/TinkersConstruct/blob/1.7.10/src/main/java/tconstruct/library/tools/HarvestTool.java#L157) In 1.8.9 HarvestTool getSecondaryItem acts differently, it will only look for a block/item to the right of it. [1.8.9 Code](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/utils/ToolHelper.java#L720)

This isn't a big issue, however it is a nuisance because the way my hotbar is always laid out, I have my pickaxe in the first slot, shovel in the second, anything else in 3-8, and torches in the last slot. I used to be able to place torches via right clicking with the pickaxe but no longer can. Maybe make the functionality what it used to be or make it configurable of "look in right direction" or "look in left direction" for what the secondary item is.

**Comment by bonii-xx** [comment]
Functionality will remain as is for now.
