### ISSUE TITLE
Feature Request: Glass Bottle Mold

### ISSUE THREAD

**Issue by Alatyami** [SlimeKnights/TinkersConstruct#1912]
It would be awesome to be able to pour molten glass into a glass bottle mold.

**Comment by laz2727** [comment]
A new mold for literally one recipe?

**Comment by Techokami** [comment]
Isn't there a way to add new molds via an addon mod? Like, an API? If so, then you would be better off suggesting another mod that uses lots of glass bottles to interop with TiCon to add that mold. Like, GrowthCraft or something. Or make your own mini-mod that adds the molds.
