### ISSUE TITLE
Materials and You

### ISSUE THREAD

**Issue by Mthvarisa** [SlimeKnights/TinkersConstruct#1914]
I am using the latest version. I can not craft Materials and You vol1 by any means. It did not show up in my inventory when I first loaded my world, too. Tried several times with all other mods disabled. Help would be appreciated.

**Comment by KnightMiner** [comment]
You mean the version for 1.8? Materials and You has not yet been added in 1.8, its still in Alpha.

**Comment by Jabaroo** [comment]
Same issue. Latest version of TContruct, 2.2.2, for 1.9 Minecraft. Have appropriate support mods:
Forge, Mantle. Updated lasted Java, down graded to JDK 7, because I thought I read JDK 8 didn't work for Tink, but can't find that reference. But It didn't work for JDK 7 or 8. Still No intial book in inventory. I get the achievement for having first item in inventory, it even shows the book in the
achievement notification, but NO book in inventory.

**Comment by TherminatorX** [comment]
See previous comment, and assume it applies.

**Comment by Jabaroo** [comment]
Thanks Therminator X,
But that's confusing, as every guide or getting started page for Tinker's Construct refer to the first book
spawning when you log into new world. And I've never seen an alternate method to get started. Just 
tried with fresh install of MC 1.8.9 ; although I still get the Inventory achievement, but no book.

**Comment by jikuja** [comment]
No books in 1.8.9 or 1.9 mods. This issue is part of `Features, Todo` like seen in Milestone. Something for books is already in the code repo but not released.

**Comment by SoullessWaffle** [comment]
@Jabaroo Even though the books haven't been added yet, the rest of the mod does work.
You can look up the crafting recipes using [JEI](http://minecraft.curseforge.com/projects/just-enough-items-jei) or [a wiki](http://ftbwiki.org/Tinkers'_Construct) to get started.
Someone on reddit also made a spreadsheet breaking down the new material traits:
[reddit: Tinkers Construct 2.0.1 (Minecraft 1.8.9) Material Traits Table w/ Descriptions and Some Math](https://www.reddit.com/r/feedthebeast/comments/416aie/tinkers_construct_201_minecraft_189_material/)

**Comment by Jabaroo** [comment]
Thanks SoulessWaffle,
   Those links help a lot. I'm settled in with 1.7.10 for now, or some if the other mods might not work. First time modding. Lots to learn.
*saaaaaalute* : )
