### ISSUE TITLE
[Suggestion] Add support for Ingot casts in Pattern Chests

### ISSUE THREAD

**Issue by 016Nojr** [SlimeKnights/TinkersConstruct#1915]
Basically what title says. Im pretty sure this was in previous versions and It's something I miss being able to do now :/

**Comment by GirafiStudios** [comment]
You can only put the ingot casts in the pattern chest if it's empty. You can then put other kinds of casts in the pattern chest after, but the ingot cast have to go first for some weird reason.

**Comment by 016Nojr** [comment]
So it's a bug then?

**Comment by bonii-xx** [comment]
#1906
