### ISSUE TITLE
[1.8.9] Tool names use default font when unicode font is ON

### ISSUE THREAD

**Issue by laz2727** [SlimeKnights/TinkersConstruct#1916]
Tool names and tooltips use the default font even when the unicode font is enabled.
![2016-02-06 21 29 22](https://cloud.githubusercontent.com/assets/2369751/12867782/cc7d337e-cd18-11e5-8aff-76b9d68f6413.png)
![2016-02-06 21 30 24](https://cloud.githubusercontent.com/assets/2369751/12867784/dcd7e75a-cd18-11e5-9f83-639e5bfeb93d.png)

**Comment by bonii-xx** [comment]
This is due to the tools using a custom font renderer. Looks like some flag from the original one is not used.
