### ISSUE TITLE
Obsidian Sharpening Kit error

### ISSUE THREAD

**Issue by KaseiFR** [SlimeKnights/TinkersConstruct#1917]
Hello,

Using TiCon 2.0.2, I can't upgrade my tools using Obsidian Sharpening Kits. When putting it with Flint on a tool station, [this]( http://imgur.com/a/XteOd) is what I get. The pickaxe was already sharpened using an Iron kit, but not the shovel.

**Comment by bonii-xx** [comment]
It's a bug with applying modifier. It tries to use both sharpening kits. Put only 1 in and it'll work.
