### ISSUE TITLE
My Minecraft Keeps on crashing everytime i open my world pls tell me how to fix this problem thx!!

### ISSUE THREAD

**Issue by Phantom-Diblo** [SlimeKnights/TinkersConstruct#1920]
[crash-2016-02-16_09.54.42-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/131760/crash-2016-02-16_09.54.42-client.txt)

**Comment by fuj1n** [comment]
Sorry, we do not support 1.7.10 anymore, however, this seems to be a conflict with CJB's MoreInfo mod.
