### ISSUE TITLE
Slime Island entities seem to have some kind of leak

### ISSUE THREAD

**Issue by charlesbevans** [SlimeKnights/TinkersConstruct#1921]
I'm testing with FTB Unstable 1.8 and after fighting a group of slime in a slime island lake I began to have a resource leak that dropped my fps to 0 within a couple of minutes.

There were 3 large slime and a few other sizes, I dropped into the water and turned them all into resources. During the fight I noticed my system slowing down and I was bouncing Slightly on the grass. Somewhere between starting the game and dropping to 0 fps a minute or so later, I became unable to pick up items or collect xp orbs that floated to me.

This didn't happen anywhere else on the map. It seemed to be related to rendering the island. I played with the profiler and debug mode to track it to tick.entities.regular.tick.move.
Plugging up the slime water on the island seemed to make a difference, but I destroyed the entire island to be safe.

The problem seems gone. It should be noted that some slime water that leaked out is taking forever to fall and disperse. I'm not having any problems from it.

I think that something in the fight didn't get released. i.e, a block of slime thought a dead slime was still bouncing or something.

It's not much, but it wasn't immediately obvious and took a long time to fix. (Fine I got distracted flying around for a bit.) If you want, I'll see if I can recreate the problem in controlled circumstances.

**Comment by VoilaTada** [comment]
I have this issue as well. When attempting to gather purple slime from a purple island, my frame rate dropped to 0 within moments, but only while I'm up on top of the island. When below the island, frame rates seem okay. There's definitely a leak of some kind that's chewing up memory when a player goes up on an island.

**Comment by bonii-xx** [comment]
Probably #1875

**Comment by charlesbevans** [comment]
Maybe. I had so many of the little buggers that the fps dropped before it was clear what was going on. However, the fps problem did continue/return when I was on the surface, and it hasn't happened when I was nearby on a beanstalk or when I was passing islands I didn't go on.

**Comment by seanamor** [comment]
I hope this will be addressed and fixed up, it seems to be the only main issue in this mod. I am so happy to see the progress in this mod.

**Comment by bonii-xx** [comment]
Wasn't easy, but I finally found it \o/

**Comment by seanamor** [comment]
YESSS Now I will feel good running this on the server! Congrats and Thanks!

**Comment by bonii-xx** [comment]
Possibly, if everything else works out just fine. But soonish for sure.

**Comment by seanamor** [comment]
Thanks again!

**Comment by charlesbevans** [comment]
Great. Thanks for the hard work!
