### ISSUE TITLE
Crashing smeltery

### ISSUE THREAD

**Issue by carlobon** [SlimeKnights/TinkersConstruct#1922]
I crash when I access the smeltery and I look at the fluids amount

**Comment by TherminatorX** [comment]
Can we have a link to the crash log on pastebin?

**Comment by carlobon** [comment]
Just a second

**Comment by AuricPolaris** [comment]
I have had the same crash. Here is the crash report: http://pastebin.com/iYzkuj2R

**Comment by bonii-xx** [comment]
You have a broken fluid there.

**Comment by AuricPolaris** [comment]
Your profile image exemplifies everything perfectly. Someone was able to look inside and found it was blood from a mob dying inside. Unsure of how to proceed.

**Comment by StanWinchester** [comment]
I too am experiencing this crash. It happened with earlier versions of the 1.8.9 rewrite, but  was too lazy to report it. All I have to do for MC to crash is put my mouse pointer over the Smeltery fluid level window in the GUI (metals or lava). I can add metals and smelt them, but not switch metals. Also, I disabled all other mods and texture packs so I only have Tinkers Construct and Mantle running.

BTW: I Love Tinkers Construct - I it Wonderful!

Thanks for the Great Mod!
Here is the report: https://paste.ee/p/Sefzr

**Comment by bonii-xx** [comment]
Ah yes. Good old Java. Update to Java 8 or wait for a tcon update.

**Comment by StanWinchester** [comment]
Java 8 fixed it. Thanks!

**Comment by bonii-xx** [comment]
2.2.0b should also fix it. But you're better off with J8 for the future for sure. Some mods even require it.
