### ISSUE TITLE
1.8.9 - 2.10 - Server crashes on launch

### ISSUE THREAD

**Issue by SPMoo66** [SlimeKnights/TinkersConstruct#1926]
Using Forge 11.15.1.1760, the server crashes with TC 2.1.0 and Mantle 0.8, but not with TC 2.0.2 and Mantle 0.7.
I can get it to run with the same MC, Forge, and TC versions with a Windows server, but not this Debian server.

[crash-2016-02-22_15.24.51-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/141440/crash-2016-02-22_15.24.51-server.txt)

**Comment by bonii-xx** [comment]
Curious, that constructor is Java 8 only. You should probably update to Java 8.

**Comment by bonii-xx** [comment]
Fixed in https://github.com/SlimeKnights/Mantle/commit/5cb45200ac7c670328a83b9442df12fcc34dbc9c
Update Mantle to 0.8.1
