### ISSUE TITLE
Crash on intialization

### ISSUE THREAD

**Issue by sblectric** [SlimeKnights/TinkersConstruct#1927]
This crash occurs while the mod is initializing. http://pastebin.com/gt2SDcpv

TC version: 1.8.9-2.1.0
Mantle version: 1.8.9-0.8.1
Forge 11.15.1.1761

EDIT: It works fine when using Mantle 0.8.

**Comment by bonii-xx** [comment]
Yes, made a mistake when changing the constructor. Fixed in https://github.com/SlimeKnights/Mantle/commit/d044409a5d39a301bd008b2380380ac166771e16
Mantle 0.8.2 should work with both Java7 and Java8, you only need it if you're using Java 7.

**Comment by sblectric** [comment]
cool thanks
