### ISSUE TITLE
Why is our log's top texture being used for part builder?

### ISSUE THREAD

**Issue by ProfessorProspector** [SlimeKnights/TinkersConstruct#1928]
So during development I noticed the top of rubber logs are being used for the part builder. Why is this happening? Also, how is the log texture decided?

![2016-02-23_19 37 57](https://cloud.githubusercontent.com/assets/6166773/13275058/bd36454a-da65-11e5-94c1-e4daf7378ed7.png)

EDIT: Would it have anything to do with the fact that the log isn't rotatable?

**Comment by bonii-xx** [comment]
It uses the particle texture

**Comment by ProfessorProspector** [comment]
Hmm would there be any way to change which texture it uses? Like could there be an api method for it?
