### ISSUE TITLE
[ Request ] : Config to disable dimensions that slimes spawn in

### ISSUE THREAD

**Issue by DraksterAU** [SlimeKnights/TinkersConstruct#1933]
Hi There,

Tinkers slimes are the only thing that I have (out of 100 mods) that respect no boundaries when it comes to spawning. Never have, so nothing new there.

This means that my territory claiming mods / plugins that normally are able to block spawning of mobs in certain areas are failing though...

Can we get a config similar to the one for slime islands please? Or make it so islands not spawning means slimes not spawning? So we can at least block it on spawn worlds?

I Run Forge 1614 1.7.10 and TConstruct 1.8.8 & Thermos 1614 (Forgebukkit hybrid) 1.7.10 with 1.8.8 also. No diff between them.

**Comment by DraksterAU** [comment]
@bonii-xx You don't support 1.7 anymore? :( 
Most decent mods haven't even updated to 1.8 yet..... lol.
All good.

**Comment by AlterAkima** [comment]
"# Add dimension ID's to prevent slime islands from generating in them
    I:SlimeIslandDimBlacklist <
     >"
Just read the file more carefully :p

**Comment by DraksterAU** [comment]
@alterakima Read my issue more carefully...

**Comment by bonii-xx** [comment]
2.1.0 should already behave better, 2.1.1 should behave even better in that aspect. 1.7.10 will never behave any better.
