### ISSUE TITLE
Server Crash (Natura?)

### ISSUE THREAD

**Issue by sharkck** [SlimeKnights/TinkersConstruct#1934]
We just had a crash.  I have included the log files and crash report.  It seems it may have something to do with Natura?  Also I'm seeing a TON of other errors from mobs being in the wrong location and chunk files that are being detected as not being where they should be.

The server is running Infinity Evolved version 2.4.1.
Crash log: https://www.dropbox.com/s/corctsx4p6erok4/crash-2016-03-02_21.55.57-server.txt?dl=0
Server log: https://www.dropbox.com/s/zlkjptda6n9j49x/2016-03-02-1.log?dl=0

**Comment by sharkck** [comment]
Just realized I can attach logfiles to the post... adding this way as well. 

[crash-2016-03-02_21.55.57-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/155680/crash-2016-03-02_21.55.57-server.txt)

**Comment by sharkck** [comment]
Also, I just realized that this is not the FTB Infinity Evolved Github as it said when I clicked on it through Google!   Sorry.  I'll try to find the correct place to post this.

**Comment by bonii-xx** [comment]
You, can confirm, looks bad. Looks like your world got a little bit corrupted there though.
