### ISSUE TITLE
Slime Boots do not respect holding jump key

### ISSUE THREAD

**Issue by TherminatorX** [SlimeKnights/TinkersConstruct#1936]
Under the assumption that Slime Boots are supposed to be a wearable version of the slime block, which allows users to negate their rebound velocity by holding the jump key during impact, this feature is missing, and would make the boots far more convenient to have.

Everything else is assumed to be working fine, and _man_ are these things fun to use. _Boing!_

Edit: Additionally, mobs wearing these boots do not bounce, but merely do not take fall damage.

**Comment by bonii-xx** [comment]
They are not. Hold shift to not bounce.

Not sure about the mob one, will check.

**Comment by TherminatorX** [comment]
Holding shift also removes the ability to negate the fall damage, which is not as useful.
Slime blocks get away with spacebar negating both rebound and fall damage by the fact that you're going to jump when you touch the ground, which balances it out a bit.

As for testing the mob thing:
-Put MC on Hard mode
-Place a block 22+ meters off the ground
-Drop some slime boots on it
-Spam zombies/skeletons on that block until one picks it up
-Destroy the block
-Observe

**Comment by bonii-xx** [comment]
You are correct, and that's intentional. ;)

Regarding the mobs, the special logic required to achieve the custom physics has quite a bit of overhead. I like to keep the impact as low as possible, which requires to use player-only events. Let's pretend zombies are too dumb to use them.
