### ISSUE TITLE
1.8.9-2.1.0 Tool Station not giving the correct amount when shift click crafting

### ISSUE THREAD

**Issue by dcaster19** [SlimeKnights/TinkersConstruct#1937]
Noticed this bug when crafting gold nuggets, when you craft 8 gold ingots into nuggets it only gives you a stack of nuggets when it should give you 72, further testing resulted in some weird behavior when you craft 16 ingots worth it only gives you 2 stacks worth (14 ingots + 2 nuggets) and when you do 17 ingots it gives you 15 ingots + 2 nuggets worth. I figure that its using a craft to get up to the stack size limit and then crafting normally.

**Comment by bonii-xx** [comment]
You are correct, it discarded remaining items after filling up a stack, resulting in the carry-over being lost due to execution order.
Fixed in https://github.com/SlimeKnights/Mantle/commit/8461f768d79ea28776011ab65eb5d7006f52a1d3
