### ISSUE TITLE
Glass pane texture different from front to back

### ISSUE THREAD

**Issue by InuYasha86000** [SlimeKnights/TinkersConstruct#1941]
I have only noticed this with smooth glass, but when you place smooth glass in an east/west direction (meaning the flat faces facing the east and west), the connections of the texture on both sides are different, I have pictures
![2016-03-06_12 56 53](https://cloud.githubusercontent.com/assets/15805183/13556977/877c8222-e39b-11e5-809e-16f2e2b3d389.png)
![2016-03-06_12 56 59](https://cloud.githubusercontent.com/assets/15805183/13556976/877c570c-e39b-11e5-8889-26797ace6938.png)
 as you can see from the first pic the glass texture looks like it's half connected to itself, same as the window behind it when facing west, but from picture 2 facing east the glass windows look normal.

as I stated earlier I have only seen this with smooth glass panes as i'm in a survival world.
version TConstruct-1.7.10-1.8.7 as part of my own modpack here: http://www.technicpack.net/modpack/the-valley-testing-phase.797682

[EDIT] I placed smooth glass panes in a south/north facing direction and when looking through them facing south the lines appear but north is clear.

**Comment by AlterAkima** [comment]
It's a long-running visual issue, the devs are aware of it.
