### ISSUE TITLE
[1.8.9] Tinkers' Ores giving experience

### ISSUE THREAD

**Issue by Robijnvogel** [SlimeKnights/TinkersConstruct#1942]
See:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638?comment=4027
and
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638?comment=4030

**Comment by Periphera** [comment]
That they drop xp when originally mined isn't a problem, but mined ores can be placed again and again and mined over and over for xp farming. Pretty simple to abuse, and just as easy to automate.

**Comment by bonii-xx** [comment]
6b552b5ac5e9afff13b4355436f6b9a272a307e4
