### ISSUE TITLE
Breaking a smeltery does not dispose of excess fluids, this crashes clients.

### ISSUE THREAD

**Issue by KJ4IPS** [SlimeKnights/TinkersConstruct#1943]
Version: 1.8.9-2.1.0.DEV.661bd31

When a smeltery is broken such that the new fluid capacity is less than the currently held fluid, the controller will still retain the excess fluids, which will cause a rendering-related crash for any client that attempts to render the fluid will crash.

Reproduction:
1. Build a 2-high smeltery.
2. Melt ores until the smelteryis over half full
3. Destroy one of the wall blocks on the 2nd layer
4. Crash in a fire...

Client Crash Report:
[crash-2016-03-10_19.28.11-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/168308/crash-2016-03-10_19.28.11-client.txt)

Client log from crashed session.
[2016-03-10-2.log.txt](https://github.com/SlimeKnights/TinkersConstruct/files/168309/2016-03-10-2.log.txt)

**Comment by TherminatorX** [comment]
I am not getting a crash from this. I have a 9-high smeltery with 64 blocks worth of iron inside, and removing a block from the third layer does not crash my game or remove any liquid.

This is using the 2.1.0 release.

**Comment by KJ4IPS** [comment]
Seems my reproduction is bad. I've started downloading the archive I made of the world that exhibits the crash. (600mb world on a slow connection) I will post NBT and (hopefully) and updated reproduction.

**Comment by bonii-xx** [comment]
Hm, I can see this possibly happening through a race condition when it renders during a network update. Should be preventable by some sanity checks.
