### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by Teslakoyal** [SlimeKnights/TinkersConstruct#1944]
I think this is a bug in the 1.8.9-2.1.0, its either that or I am messing something up. I can change all the texture from 16x to 64x as I please except for the ones in the main directory such as the cast and pattern textures. If I change these from the base 16 to anything else the texture pack is auto kicked out and can not be reapplied, if it is a design of the mod to keep these few texture to 16x I understand. if it is something I am somehow doing wrong I would like to know that as well.

**Comment by bonii-xx** [comment]
#1929
