### ISSUE TITLE
Flowing slime from Slime Islands causing massive lag v1.8.9-2.1.0

### ISSUE THREAD

**Issue by shortybsd** [SlimeKnights/TinkersConstruct#1945]
Version: 1.8.9-2.1.0

If you break a block on a floating slime island and the slime water pours down it will lag the server. TPS goes from 20tps down to 0.3 within 2 seconds. When the player in the area logs off or leaves that area the TPS goes back to 20.

**Comment by bonii-xx** [comment]
Can't reproduce. You might've unknowingly encountered #1921

**Comment by shortybsd** [comment]
Maybe something is conflicting, here is my modpack mod list:

ArchitectureCraft-1.3.1-mc1.8.9 
BaseMetals-1.7.3 
BiomesOPlenty-1.8.9-3.0.0.1894-universal 
BloodMagic-1.8.9-2.0.0-19 
Bookshelf-API-1.8.9-2.3.6 
Botania.r1.8-unofficial-0.6.3 
buildcraft-7.2.0-pre12 
CandyCraft-1.3.1 
Chisel-MC1.8.9-0.0.2.7 
chiselsandbits-mc1.8.9-v1.8.10 
CustomNpcs_1.8.9_beta(21feb16) 
EnderTanks-1.8.9-1.2.1 
enderutilities-1.8.9-0.5.0 
EnderZoo-1.8.9-1.1.3.35 
fastTravel-1.8.8-1.0.4-universal 
Harvest-1.8.9-1.0.0-2 
HydCraft-1.8.9-3.1.65-universal 
IGW-Mod-1.8.9-1.2.4-4-universal 
intangible-1.8.9-0.0.22 
InventoryTweaks-1.60-beta-30 
IronBackpacks-1.8.9-2.0.5 
ironchest-1.8.9-6.0.125.770 
jei_1.8.9-2.28.6.173 
journeymap-1.8.8-5.1.3-unlimited 
k4lib-1.8.9-1.0.16-universal 
LLOverlayReloaded-1.0.5-mc1.8.9 
Mantle-1.8.9-0.8.2 
mcjtylib-1.8.9-1.8.1beta6 
MCMultiPart-1.0.7-universal 
MrCrayfishFurntiureModv3.6.1(1.8.9) 
NeoTech-1.8.9-2.4.1 
NetherEssence-4.0.1.1 
OpenComputers-MC1.8.9-1.6.0.8-dev 
OpenGrave-1.8.9-2.0 
PowerAdvantage-1.5.0 
ProgressiveAutomation-1.8.9-1.6.35 
RandomThings-MC1.8.9-3.6.4 
rftools-1.8.9-4.22beta25 
RoguelikeDungeons-1.8.9-1.4.5 
ShetiPhianCore-1.8.9-3.1.0 
simplefluidtanks-1.8.9-1.3.0.2 
sodacanutils-2.0.4 
SteamAdvantage-1.5.1 
storagesilo-1.8.9-1.2.2b 
TConstruct-1.8.9-2.1.0 
Thaumcraft-1.8.9-5.2.1 
Waila-1.6.0-B3_1.8.8

**Comment by shortybsd** [comment]
Has nothing to do with sound or entities. It is the flowing of the water itself, it glitches and makes a new source for every block it hits or falls on.

**Comment by bonii-xx** [comment]
Nope, it does not. It behaves just like water.
![2016-03-13_11 00 00](https://cloud.githubusercontent.com/assets/722449/13728052/d670bb7c-e90a-11e5-935b-3d5c9c6efd05.png)

**Comment by GirafiStudios** [comment]
I have seen similiar behaviour to what @shortybsd is describing. It was on a server tho. Seemed to mostly be a client desync from what I could tell.

**Comment by bonii-xx** [comment]
Do you have any ways of reproducing it? It doesn't really do anything different than any other liquid.

**Comment by shortybsd** [comment]
Go to any slime island, place any block blocking one of the slime water blocks. Poof instant lag, server ended up saying it is crashed with the following error http://pastebin.com/3gqLK0sc
After you wait in the area the lag will go away once the flowing slime water gets done going away. One bucket placed on ground then picked up takes about 2 minutes before it goes away.

**Comment by shortybsd** [comment]
The crazy thing is there is no floating XP orbs that I can visually see. Any time you change any slime water is when the lag arises. It has something to do with the extremely slow flowing slime water. The slime water flowing state doesn't update properly.

**Comment by bonii-xx** [comment]
The crashlog points towards #1921

As for flowing slime.. see screenshot above, and placing a bucket of it works perfectly fine without issues too. I haven't gotten any other reports of such an issue either.. it might be related to #1921 or some other mod causing it.

**Comment by bonii-xx** [comment]
Try TCon 2.2.0a and it still happens there.
