### ISSUE TITLE
[1.8.9-2.1.0] No way to get gold ore for casts.

### ISSUE THREAD

**Issue by DyrePlus** [SlimeKnights/TinkersConstruct#1947]
If you are following Tinkers' progression _only_, not using vanilla/mod tools, there is no way to get gold ore to make your first cast. The only high mining level material that doesn't require a smeltery/cast is obsidian, which requires a material made in a smeltery (knightslime/steel) to mine.

In previous versions of Tinkers', this wasn't a problem because aluminum and copper could be mined with Iron level tools and could then be used to make casts. We need a return of the aluminum brass or another material to make a pickaxe head out of (Redstone level?) --unless I'm missing something within new mechanics (those hidden stats leveling up the mining level, maybe?).

**Comment by laz2727** [comment]
Gold from chests? Pigmen from nether? There are a lot of ways.

2016-03-15 21:36 GMT+05:00 Dyre Raydrick <notifications@github.com>:

**Comment by DyrePlus** [comment]
Yes, you can go exploring (no pigmen because no obsidian, though), but game play and progression wise, it seems like a really strange choice. We're talking about a really basic aspect of the mod, not something really equivalent to the purple slime required for knightslime/obsidian level mining. It's really obvious where you'd probably get that stuff, even if you're unfamiliar with the mod. Not the same thing as wandering aimlessly, hoping for dungeon chests that have gold in them. With other mods (thaumcraft, rougelike dungeons), it might be easier to find these chests, but Tinkers' shouldn't need other mods to do its own progression.

**Comment by laz2727** [comment]
You can cast the portal with a bucket.

Alubrass just isn't done yet.

2016-03-15 21:54 GMT+05:00 Dyre Raydrick <notifications@github.com>:

**Comment by laz2727** [comment]
j/k it's in

2016-03-15 21:55 GMT+05:00 Caroline Johnson <laz2727@gmail.com>:

**Comment by DyrePlus** [comment]
Forgot about the bucket portal, but still....

Is it in that 2.2.0 alpha build that just ninja'd its way in while I wasn't looking? :T

**Comment by laz2727** [comment]
Yep.

2016-03-15 22:00 GMT+05:00 Dyre Raydrick <notifications@github.com>:

**Comment by DyrePlus** [comment]
That's not aluminum brass! That's even better! Clay casts. <3

**Comment by bonii-xx** [comment]
Aluminium brass also is in there. You just need a mod that adds copper and aluminium.
