### ISSUE TITLE
TConstruct-1.8.9-2.2.0a does not make clear glass from sand

### ISSUE THREAD

**Issue by kwpugh** [SlimeKnights/TinkersConstruct#1948]
I'm not sure if this feature was removed, but we just noticed it.

Using:
- Forge-1.8.9-11.15.1.1763
- TConstruct-1.8.9-2.2.0a.jar
- Mantle-1.8.9-0.9.0.jar

Putting sand in a functional smeltery does nothing.

**Comment by bonii-xx** [comment]
You also wont find clear glass in JEI either. ;o

It's not in yet.

**Comment by kwpugh** [comment]
ok, thanks.

We love the clear glass.

**Comment by bonii-xx** [comment]
We do.

**Comment by KnightMiner** [comment]
Added in 2.3.2
