### ISSUE TITLE
Tool Forge - rename crash

### ISSUE THREAD

**Issue by gamecraft45** [SlimeKnights/TinkersConstruct#1949]
When I put something block/item (no Tinkers Construct) in to Tool Forge, rename it and click with shift game crash

[crash-2016-03-16_19.06.36-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/176614/crash-2016-03-16_19.06.36-client.txt)

**Comment by matthew57778** [comment]
Same issue 1.7.10.
