### ISSUE TITLE
Smeltery Controller ticking block entity crash

### ISSUE THREAD

**Issue by BeyJohn** [SlimeKnights/TinkersConstruct#1950]
Using alpha version 2.2.0a.
Every time I complete a smeltery I get the same ticking block entity error.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-39.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  TweaksLoadingPlugin (CCTweaks-1.8.9-0.3.1.jar)
  EnderCorePlugin (EnderCore-1.8.9-0.3.0.1-beta.jar)
  CoreXU2 (extrautils2-1.8.9-alpha--0.0.0.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.3.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/16/16 2:45 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockSmeltery.isValidBlock(MultiblockSmeltery.java:61)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockSmeltery.isFloorBlock(MultiblockSmeltery.java:67)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockCuboid.detectPlaneXZ(MultiblockCuboid.java:155)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockCuboid.detectFloor(MultiblockCuboid.java:110)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockCuboid.detectMultiblock(MultiblockCuboid.java:61)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockSmeltery.detectMultiblock(MultiblockSmeltery.java:28)
	at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.checkSmelteryStructure(TileSmeltery.java:368)
	at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.func_73660_a(TileSmeltery.java:104)
	at net.minecraft.world.World.func_72939_s(World.java:1718)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockSmeltery.isValidBlock(MultiblockSmeltery.java:61)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockSmeltery.isFloorBlock(MultiblockSmeltery.java:67)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockCuboid.detectPlaneXZ(MultiblockCuboid.java:155)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockCuboid.detectFloor(MultiblockCuboid.java:110)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockCuboid.detectMultiblock(MultiblockCuboid.java:61)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockSmeltery.detectMultiblock(MultiblockSmeltery.java:28)
	at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.checkSmelteryStructure(TileSmeltery.java:368)
	at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.func_73660_a(TileSmeltery.java:104)

-- Block entity being ticked --
Details:
	Name: tconstruct.smeltery_controller // slimeknights.tconstruct.smeltery.tileentity.TileSmeltery
	Block type: ID #1003 (tile.tconstruct.smeltery_controller // slimeknights.tconstruct.smeltery.block.BlockSmelteryController)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-382,64,167), Chunk: (at 2,4,7 in -24,10; contains blocks -384,0,160 to -369,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #1003 (tile.tconstruct.smeltery_controller // slimeknights.tconstruct.smeltery.block.BlockSmelteryController)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1718)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['beyjohn'/1707, l='New World', x=-385.31, y=64.00, z=167.61]]
	Chunk stats: ServerChunkCache: 555 Drop: 0
	Level seed: 1875068731215616974
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 248.00,64.00,252.00 - World: (248,64,252), Chunk: (at 8,4,12 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 175824 game time, 198664 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 134166 (now: false), thunder time: 81279 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1019956760 bytes (972 MB) / 2248671232 bytes (2144 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 Optifine OptiFine_1.8.9_HD_U_H5 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAAAA	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.2-beta.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	<CCTweaks ASM>{0.3.1} [<CCTweaks ASM>] (minecraft.jar) 
	UCHIJAAAA	CoreXU2{1} [CoreXU2] (minecraft.jar) 
	UCHIJAAAA	bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
	UCHIJAAAA	basemetals{1.7.4} [Base Metals] (BaseMetals-1.7.4.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha--0.0.0.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
	UCHIJAAAA	JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
	UCHIJAAAA	BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-19.jar) 
	UCHIJAAAA	Thaumcraft{5.2.3} [Thaumcraft] (Thaumcraft-1.8.9-5.2.3.jar) 
	UCHIJAAAA	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.0-pre12} [BuildCraft] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.0-pre12} [BC Transport] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.0-pre12} [BC Energy] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.0-pre12} [BC Factory] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.2.0-pre12} [BC Silicon] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.2.0-pre12} [BC Robotics] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.0-pre12} [BC Builders] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
	UCHIJAAAA	CCTweaks{0.3.1} [CCTweaks] (CCTweaks-1.8.9-0.3.1.jar) 
	UCHIJAAAA	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCHIJAAAA	mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
	UCHIJAAAA	CharsetLib{0.2.1} [â€½] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetTweaks{0.2.1} [*] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetWires{0.2.1} [+] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetAudio{0.2.1} [â™«] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetStorage{0.2.1} [#] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetPipes{0.2.1} [|] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetGates{0.2.1} [&] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.8.9-v2c} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v2c.jar) 
	UCHIJAAAA	ElecCore{1.4.247} [ElecCore] (ElecCore-1.8.9-1.4.247.jar) 
	UCHIJAAAA	deepresonance{1.1.4beta17} [DeepResonance] (deepresonance-1.8.9-1.1.4beta17.jar) 
	UCHIJAAAA	endercore{1.8.9-0.3.0.1-beta} [EnderCore] (EnderCore-1.8.9-0.3.0.1-beta.jar) 
	UCHIJAAAA	ExtraBitManipulation{1.8.9-1.4.0} [Extra Bit Manipulation] (ExtraBitManipulation-1.8.9-1.4.0.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAA	reborncore{1.4.3.20} [RebornCore] (RebornCore-1.8.9-1.4.3.20-universal.jar) 
	UCHIJAAAA	fluxedredstone{1.3.0.31} [FluxedRedstone] (Fluxed Redstone-1.3.0.31.jar) 
	UCHIJAAAA	fluxedsolars{$GRADLEVERSION} [Fluxed Solars] (fluxedsolars-1.9.jar) 
	UCHIJAAAA	samsfooddetails{1.0.0} [Food Details] (FoodDetails-1.8.9-1.0.0.jar) 
	UCHIJAAAA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJAAAA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJAAAA	Harvest{1.8.9-1.0.0-2} [Harvest] (Harvest-1.8.9-1.0.0-2.jar) 
	UCHIJAAAA	inventorytweaks{1.60-beta-39-eae6253} [Inventory Tweaks] (InventoryTweaks-1.60-beta-39.jar) 
	UCHIJAAAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAAAA	itemscroller{0.2.0} [Item Scroller] (itemscroller-1.8.9-0.2.0.jar) 
	UCHIJAAAA	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCHIJAAAA	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
	UCHIJAAAA	llor{1.0.5-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.5-mc1.8.9.jar) 
	UCHIJAAAA	mantle{1.8.9-0.9.0.jenkins97} [Mantle] (Mantle-1.8.9-0.9.0.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.2-beta.1} [OpenComputers] (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar) 
	UCHIJAAAA	openradio{0.7.0} [OpenRadio] (OpenRadio-0.7.0-beta-MC1.8.9.jar) 
	UCHIJAAAA	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCHIJAAAA	ProjectE{1.8.9-PE1.1.4} [ProjectE] (ProjectE-1.8.9-PE1.1.4.jar) 
	UCHIJAAAA	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UCHIJAAAA	quantumflux{2.0.1} [QuantumFlux] (quantumflux-1.8.9-2.0.1.jar) 
	UCHIJAAAA	RecipeTooltips{1.1.24} [RecipeTooltips] (RecipeTooltips-1.8.9-1.1.24.jar) 
	UCHIJAAAA	xreliquary{1.3.1.212} [Reliquary] (Reliquary-1.3.1.212.jar) 
	UCHIJAAAA	rftools{4.23beta32} [RFTools] (rftools-1.8.9-4.23beta32.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.8.8.16} [Similsax Transtructors] (SimilsaxTranstructors-1.8.8.16.jar) 
	UCHIJAAAA	StorageDrawers{1.8.9-2.4.4} [Storage Drawers] (StorageDrawers-1.8.9-2.4.4.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct] (TConstruct-1.8.9-2.1.0.jar) 
	UCHIJAAAA	thaumicinfusion{4.82} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.82.jar) 
	UCHIJAAAA	VeinMiner{0.31.4_build.unknown} [Vein Miner] (VeinMiner-1.8.9_0.31.4.unknown.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.31.4_build.unknown} [Mod Support] (VeinMiner-1.8.9_0.31.4.unknown.jar) 
	UCHIJAAAA	wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  li.cil.oc.common.asm.ClassTransformer
CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  
thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
FMLPlugin (InventoryTweaks-1.60-beta-39.jar)
  invtweaks.forge.asm.ContainerTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
TweaksLoadingPlugin (CCTweaks-1.8.9-0.3.1.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
EnderCorePlugin (EnderCore-1.8.9-0.3.0.1-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.EnderCoreTransformerClient
CoreXU2 (extrautils2-1.8.9-alpha--0.0.0.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.3.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['beyjohn'/1707, l='New World', x=-385.31, y=64.00, z=167.61]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'``

**Comment by bonii-xx** [comment]
Full log?

**Comment by BeyJohn** [comment]
[full log ticking block entity crash.zip](https://github.com/SlimeKnights/TinkersConstruct/files/176975/full.log.ticking.block.entity.crash.zip)

**Comment by bonii-xx** [comment]
Update your tcon.
