### ISSUE TITLE
TConstruct-1.8.9-2.2.0b Crashes on startup with OptiFine_1.8.9_HD_U_H5

### ISSUE THREAD

**Issue by hoseja** [SlimeKnights/TinkersConstruct#1951]
Here's the MultiMC log: http://paste.ee/p/Akkwr

**Comment by bonii-xx** [comment]
Just Optifine things.

**Comment by hoseja** [comment]
Hey, so, uh, when I deleted the Optifine config file it worked alright... sorry false alert my bad...

**Comment by bonii-xx** [comment]
Don't worry, those are just typical Optifine things. ;o
