### ISSUE TITLE
Tinker's construct ore's not spawning

### ISSUE THREAD

**Issue by notblackjack** [SlimeKnights/TinkersConstruct#1955]
Hello,

I have recently installed Tinker's construct for my single-player survival. It loads fine, but I have 1 problem. Unfortunately, the Tinker's construct ores do not spawn, nor do they appear in Just enough items (NEI equivalent for 1.8.9). All other blocks seem to have loaded fine, but the ores will not. Any idea how to fix this? Is this an ID bug of sorts? I also get no errors or crashes at any time...
Picture of my current mods:
https://gyazo.com/8d8437b3a1feb174a8ec7ac39cf604d6

Thanks for your help!

**Comment by bonii-xx** [comment]
It only adds ardite and cobalt ore.

**Comment by notblackjack** [comment]
According to this page, Aluminum is also supposed to spawn in the overworld. So how would I get aluminum now?

**Comment by notblackjack** [comment]
Sorry [here is the link](http://tinkers-construct.wikia.com/wiki/Aluminum_Ore)

**Comment by notblackjack** [comment]
Also, crafting recipes seem to not work properly. [See this image.](https://gyazo.com/79213bfdb2c865a7eebc361399fdd011)

**Comment by bonii-xx** [comment]
Update your mantle and ticon. And you get aluminium by having a mod that uses aluminium.
