### ISSUE TITLE
Tinkers' construct ores not spawning (take 2)

### ISSUE THREAD

**Issue by notblackjack** [SlimeKnights/TinkersConstruct#1956]
Hello,

I have recently installed Tinker's construct for my single-player survival. It loads fine, but I have 1 problem. Unfortunately, the Tinker's construct ores do not spawn, nor do they appear in Just enough items (NEI equivalent for 1.8.9). All other blocks seem to have loaded fine, but the ores will not. Any idea how to fix this? Is this an ID bug of sorts? I also get no errors or crashes at any time...
Picture of my current mods:
https://gyazo.com/8d8437b3a1feb174a8ec7ac39cf604d6

2 ores are in the game: this is the nether version of cobalt and ardite. Overworld ores will not spawn. Also, as you can see in [this picture](https://gyazo.com/79213bfdb2c865a7eebc361399fdd011), some crafting recipes don't seem to work properly, and as you can see in [this picture](https://gyazo.com/e3fb4e102fe3da2e1c4f3ee8ad975125), and [this picture](https://gyazo.com/b3e4f8b09ad84199839993d9268a4d57) a lot of item graphics are gone.

Thanks for your help! Please do not close this issue as fast as you did the previous one. I am certain that I am experiencing a bug of sorts.

~notblackjack

**Comment by bonii-xx** [comment]
Have you played with Tinkers before, or are you completely new to the mod?

**Comment by laz2727** [comment]
Spoiler: they aren't in the mod yet.

**Comment by bonii-xx** [comment]
What makes you think they'll ever return? :P

**Comment by laz2727** [comment]
Nothing, i'm okay with current balance, especially if gravel ores will return :D

**Comment by xrmzfanatic54x** [comment]
Did you fix it is have the same problem but in minecraft 1.10.2

**Comment by xrmzfanatic54x** [comment]
Help please

**Comment by ArukaAlter** [comment]
Read the contribution guidelines, it's working as intended, only Cobalt and Ardite are present as ores in 1.10
