### ISSUE TITLE
Using the tooltables can open others chest

### ISSUE THREAD

**Issue by bunSakurAing** [SlimeKnights/TinkersConstruct#1960]
In the server,I using the lock chest plug-in.But I put a tooltable. the chest next to him. He can get something what's in the box.
I would like to be able to set up only to open my own chest,Can't open someone else's chest from tooltable

**Comment by bonii-xx** [comment]
The crafting station uses IItemHandlers in 1.9 and forward. This is literally all I can do access-wise, and everything else can't be handled by me.
