### ISSUE TITLE
TConstruct crash the client

### ISSUE THREAD

**Issue by bunSakurAing** [SlimeKnights/TinkersConstruct#1961]
`12:13:42] [Client thread/ERROR] [tconstruct-Pulsar-Flightpath]: Exception caught from a pulse on flightpath for mod ID tconstruct:   java.lang.reflect.InvocationTargetException     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]     at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89) [Flightpath.class:?]     at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:202) [PulseManager.class:?]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]     at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]     at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) [LoadController.class:?]     at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) [LoadController.class:?]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]     at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]     at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]     at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]     at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417) [ave.class:?]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329) [ave.class:?]     at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] Caused by: java.lang.NullPointerException     at net.minecraft.client.resources.model.ModelBakery.registerItemVariants(ModelBakery.java:759) ~[bot.class:?]     at slimeknights.tconstruct.shared.FluidsClientProxy.registerFluidModels(FluidsClientProxy.java:45) ~[FluidsClientProxy.class:?]     at slimeknights.tconstruct.shared.FluidsClientProxy.registerModels(FluidsClientProxy.java:28) ~[FluidsClientProxy.class:?]     at slimeknights.tconstruct.common.CommonProxy.preInit(CommonProxy.java:27) ~[CommonProxy.class:?]     at slimeknights.tconstruct.shared.TinkerFluids.preInit(TinkerFluids.java:236) ~[TinkerFluids.class:?]     ... 38 more [12:13:43] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----  WARNING: coremods are present:   ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)   DLFMLCorePlugin (DynamicLights-1.8.8.jar)   InputFix (InputFix-1.8.x-v2.jar)   FMLPlugin (InventoryTweaks-1.60-40.jar)   AppleCore (AppleCore-mc1.8.9-1.3.0.jar)   dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar) Contact their authors BEFORE contacting forge  // This doesn't make any sense!  Time: 16-3-20 下午12:13 Description: Initializing game  java.lang.Error: java.lang.reflect.InvocationTargetException      at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)      at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)      at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:202)      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)      at java.lang.reflect.Method.invoke(Unknown Source)      at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)      at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)      at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)      at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)      at com.google.common.eventbus.EventBus.post(EventBus.java:275)      at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)      at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)      at java.lang.reflect.Method.invoke(Unknown Source)      at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)      at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)      at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)      at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)      at com.google.common.eventbus.EventBus.post(EventBus.java:275)      at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)      at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)      at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)      at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)      at net.minecraft.client.main.Main.main(SourceFile:124)      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)      at java.lang.reflect.Method.invoke(Unknown Source)      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)  Caused by: java.lang.reflect.InvocationTargetException      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)      at java.lang.reflect.Method.invoke(Unknown Source)      at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89)      ... 33 more  Caused by: java.lang.NullPointerException      at net.minecraft.client.resources.model.ModelBakery.registerItemVariants(ModelBakery.java:759)      at slimeknights.tconstruct.shared.FluidsClientProxy.registerFluidModels(FluidsClientProxy.java:45)      at slimeknights.tconstruct.shared.FluidsClientProxy.registerModels(FluidsClientProxy.java:28)      at slimeknights.tconstruct.common.CommonProxy.preInit(CommonProxy.java:27)      at slimeknights.tconstruct.shared.TinkerFluids.preInit(TinkerFluids.java:236)      ... 38 more    A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Stacktrace:     at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)     at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)     at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:202)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)     at java.lang.reflect.Method.invoke(Unknown Source)     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)     at com.google.common.eventbus.EventBus.post(EventBus.java:275)     at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)     at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)     at java.lang.reflect.Method.invoke(Unknown Source)     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)     at com.google.common.eventbus.EventBus.post(EventBus.java:275)     at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)     at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)     at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)  -- Initialization -- Details: Stacktrace:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)     at net.minecraft.client.main.Main.main(SourceFile:124)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)     at java.lang.reflect.Method.invoke(Unknown Source)     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)  -- System Details -- Details:     Minecraft Version: 1.8.9     Operating System: Windows 10 (amd64) version 10.0     CPU: 4x AMD Athlon(tm) X4 760K Quad Core Processor      Java Version: 1.8.0_73, Oracle Corporation     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation     Memory: 52953080 bytes (50 MB) / 362807296 bytes (346 MB) up to 2147483648 bytes (2048 MB)     JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m     IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0     FML: MCP 9.19 Powered by Forge 11.15.1.1765 Optifine OptiFine_1.8.9_HD_U_H5 41 mods loaded, 41 mods active     States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored     UCH    mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)      UCH    FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1765.jar)      UCH    Forge{11.15.1.1765} [Minecraft Forge] (forge-1.8.9-11.15.1.1765.jar)      UCH    InputFix{1.8.x-v2} [InputFix] (minecraft.jar)      UCH    Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar)      UCH    Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar)      UCH    Botania{r1.8-299} [Botania] ([核心mod]植物魔法.r1.8-299.jar)      UCH    Ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.0-4.jar)      UCH    AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar)      UCH    ArchitectureCraft{1.4.0} [ArchitectureCraft] (ArchitectureCraft-1.4.0-mc1.8.9.jar)      UCH    BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1935-universal.jar)      UCH    chiselsandbits{8.5} [Chisels & Bits] (chiselsandbits-8.5.jar)      UCH    customnpcs{1.8.9_beta} [CustomNPCs] (CustomNpcs_1.8.9_beta(21feb16).jar)      UCH    DurabilityShow{2.1.2} [Durability Show] (Durability Show-1.8.9-2.1.2.jar)      UCH    DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.8.8.jar)      UCH    DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.8.8.jar)      UCH    DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.8.8.jar)      UCH    DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.8.8.jar)      UCH    DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.8.8.jar)      UCH    DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.8.8.jar)      UCH    DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.8.8.jar)      UCH    DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.8.8.jar)      UCH    DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.8.8.jar)      UCH    DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.8.8.jar)      UCH    dsurround{2.0.4.10} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.4.10.jar)      UCH    foodcraft{1.2.0} [FoodCraft] (FoodCraft-16.2.4-1.2.2-1.8.9.jar)      UCH    IngameAccountSwitcher{3.0.0.1} [In-Game Account Switcher] (In-Game Account Switcher- 1.8.8-3.0.0.1.jar)      UCH    IngameAccountSwitchervc{1.2} [In-game Account Switcher Version Checker] (In-Game Account Switcher- 1.8.8-3.0.0.1.jar)      UCH    inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar)      UCH    JEI{2.28.7.174} [Just Enough Items] (JEI_1.8.9-2.28.7.174.jar)      UCH    JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar)      UCH    mantle{1.8.9-0.9.1.jenkins99} [Mantle] (Mantle-1.8.9-0.9.1.jar)      UCH    MoreFurnaces{1.5.0} [More Furnaces] (morefurnaces-1.5.0-MC1.8.9.jar)      UCH    MouseTweaks{2.6.0} [Mouse Tweaks] (MouseTweaks-2.6.0-mc1.8.9.jar)      UCH    Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.1-2.jar)      UC    tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0b.jar)      UC    AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.8.8.jar)      UC    WIT{1.0.7} [WIT] (WIT-1.8.9-1.0.7-19.jar)      UC    worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar)      UC    XaeroMinimap{1.8.5} [Xaero's Minimap] (Xaeros_Minimap_1.8.5_Forge_1.8.9.jar)      UC    yarrmateys_cutemobmodels{1.0.11} [Yarr Cute Mob Models - Remake] (YarrCuteMobModelsRemake-1.0.11-1.8.9.jar)      Loaded coremods (and transformers):  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)    DLFMLCorePlugin (DynamicLights-1.8.8.jar)   atomicstryker.dynamiclights.common.DLTransformer InputFix (InputFix-1.8.x-v2.jar)   lain.mods.inputfix.InputFixTransformer FMLPlugin (InventoryTweaks-1.60-40.jar)   invtweaks.forge.asm.ContainerTransformer AppleCore (AppleCore-mc1.8.9-1.3.0.jar)   squeek.applecore.asm.TransformerModuleHandler dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)   org.blockartistry.mod.DynSurround.asm.Transformer     GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.0' Renderer: 'AMD Radeon R7 200 Series'     Pulsar/tconstruct loaded Pulses:          - TinkerCommons (Enabled/Forced)         - TinkerWorld (Enabled/Not Forced)         - TinkerTools (Enabled/Not Forced)         - TinkerGadgets (Enabled/Not Forced)         - TinkerOredict (Enabled/Forced)         - TinkerIntegration (Enabled/Forced)         - TinkerFluids (Enabled/Forced)         - TinkerMaterials (Enabled/Forced)         - chiselsandbitsIntegration (Enabled/Not Forced)         - TinkerDebug (Enabled/Not Forced)      Launched Version: HMCL 2.4.1.10     LWJGL: 2.9.4     OpenGL: AMD Radeon R7 200 Series GL version 4.5.13416 Compatibility Profile Context 15.300.1025.0, ATI Technologies Inc.     GL Caps: Using GL 1.3 multitexturing. Using GL 1.3 texture combiners. Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported. Shaders are available because OpenGL 2.1 is supported. VBOs are available because OpenGL 1.5 is supported.      Using VBOs: Yes     Is Modded: Definitely; Client brand changed to 'fml,forge'     Type: Client (map_client.txt)     Resource Packs: [拓展]五边形更多生物群系 64x.zip, [拓展]五边形小地图.zip, [材质]方块概念.zip, [音效]BDCraft Sounds.zip, [贴图]木星.zip     Current Language: 简体中文 (中国)     Profiler Position: N/A (disabled)     CPU: 4x AMD Athlon(tm) X4 760K Quad Core Processor      OptiFine Version: OptiFine_1.8.9_HD_U_H5     Render Distance Chunks: 8     Mipmaps: 4     Anisotropic Filtering: 1     Antialiasing: 0     Multitexture: false     Shaders: null     OpenGlVersion: 4.5.13416 Compatibility Profile Context 15.300.1025.0     OpenGlRenderer: AMD Radeon R7 200 Series     OpenGlVendor: ATI Technologies Inc.     CpuCount: 4  [12:13:43] [Client thread/INFO] [STDOUT]: [net.minecraft.in`

Game loading interface is loaded into the 2/17 crashed, please help me

**Comment by bonii-xx** [comment]
#1954
