### ISSUE TITLE
Tanks keep pulling lava if full

### ISSUE THREAD

**Issue by ThePsionic** [SlimeKnights/TinkersConstruct#1968]
I have a setup that connects a MFR lava generator to a smeltery tank via an OpenBlocks tank and Thermal Expansion 4 fluiducts. However, the OpenBlocks tank stays empty, as the seared tank is constantly seen as needing lava. I'm not sure whether this is a bug with Tinkers' not letting know that the tank is full or with TE not noticing that it is, and if the issue isn't in here I won't hesitate to make a report of this on the Thermal Expansion issue tracker (wherever that may be).

**Comment by ThePsionic** [comment]
Maybe worth noting btw, FTB Infinity Evolved 1.7.10 w/ Tinkers' 1.7.10-1.8.8build988.

**Comment by codewarrior0** [comment]
In Infinity Evolved, I've used EnderIO conduits to fill seared tanks with lava without observing any lava loss. This might be a TE4 issue.
