### ISSUE TITLE
[1.8.9] "Dense" effect bug

### ISSUE THREAD

**Issue by Xiaminou** [SlimeKnights/TinkersConstruct#1969]
Bug 1:When breaking block intended for another tool, the effect "Dense" from bronze will work.
It is a problem when using in combination with "Crumbling" for a multi-purpose tool.
Example: breaking wood logs with a pickaxe will use 1 durability each time, breaking stone will use 1 durability every 5 at lower durability.

Bug 2: additionally it would seem that in some cases my tool gains durability from this trait.

Working as intended or bug?

**Comment by bonii-xx** [comment]
I don't think it's a problem, since it's smart use of traits. Let's call it a feature. Will be fixed if it becomes a problem, maybe Dense also simply is too strong. We'll see :)

**Comment by Xiaminou** [comment]
Edited with a second bug, and yes I would agree that dense is too strong, especially when compared with reinforced.

**Comment by codewarrior0** [comment]
Dense is absurdly strong. I took a 1,200 durability excavator (no bronze) and dug 1,200 sand, breaking the tool. I came home, repaired the shovel, replaced its copper handle with bronze (increasing dura to 1,440 or so), and dug another 25,000 sand - and the tool didn't even completely break! I was getting about 500 sand to the durability point at the end.

**Comment by Xiaminou** [comment]
I made an unbreakable hammer with, Dense, Reinforced, Petramor and Momentum, tools heals itself as long as you mine stone:
![2016-03-25_15 55 55](https://cloud.githubusercontent.com/assets/8670392/14046479/1b9f393a-f2a2-11e5-882b-446de34fc771.png)

**Comment by bonii-xx** [comment]
Hm, yeah. it might be a bit on the strong side. Will probably need to reduce the numbers quite a bit.

**Comment by bonii-xx** [comment]
Found the reason, the chance for it was inverted, resulting in those ridiculous numbers.
