### ISSUE TITLE
1.7.10 - 1.8.8 - Different Quarts Effects Damage Output (Quartz, Blocks of Quartz, AE Quartz)

### ISSUE THREAD

**Issue by KaneHart** [SlimeKnights/TinkersConstruct#1975]
So this has been an issue for a while I sort of forgot I had the issue was going ask on IRC but I been removed from it a year/2 ago.

This issue is when you use Quartz, Block of Quartz, or AE2 Quarts you get different damage attack output on tinkers weapons (maybe tools). The best one is nether quarts but nether quartz blocks will drop the attack more even if applied 72/72 and AE2 almost in half difference. 

**Here is a video example of it in action:**
https://www.youtube.com/watch?v=EzktENE1tTM

**Screenshots:**
http://i.imgur.com/tX7rpHu.png - AE2 Quartz
http://i.imgur.com/PCWhRu0.png - Nether Quartz Block
http://i.imgur.com/LFM4IML.png - Nether Quartz

**Comment by laz2727** [comment]
Known, wontfix.
