### ISSUE TITLE
Server crash with Neotech Centrifuge auto-outputting to TConstruct casting table without cast

### ISSUE THREAD

**Issue by tod** [SlimeKnights/TinkersConstruct#1983]
This crash happened as soon as I placed a Tinker's Construct casting table below a Neotech Centrifuge that was set to auto output molten iron to that side. I didn't have time to place the ingot cast before the server crashed. The world would then crash on startup. I had to go into mcedit and delete the casting table to get the world to launch again. Sorry if this is an older version, but it's what is in the FTB Unstable pack. I tried searching the issues and didn't see anything like this reported before so I was unsure if it has been fixed already.

Versions in use:
FTB Unstable 1.8 3.0.41 (yes I know unstable/unsupported)
TConstruct-1.8.9-2.2.0b
NeoTech-1.8.9-2.4.1
forge-1.8.9-11.15.1.1764

I tried upgrading to FTB Unstable 3.0.42, but it still crashed. (I use 3.0.41 because it's a server with friends and .42 has a login timed out bug) 

Crash Log:
http://pastebin.com/w6P68Wyr

**Comment by bonii-xx** [comment]
Looks like it's trying to fill with a null. Should probably be fixed on their side.

**Comment by tod** [comment]
Do you know if there's a way I can confirm which mod is responsible? I had originally submitted this to Neotech, but they closed it saying it was a tinker's issue. 

https://github.com/TeamBR-Modding/NeoTech/issues/255#issuecomment-202922278

**Comment by bonii-xx** [comment]
I should catch the case when that happens. Nontheless they should prevent it from ever getting that far.
