### ISSUE TITLE
[1.8.9] Mattock doing more damage than swords

### ISSUE THREAD

**Issue by Trixtrox** [SlimeKnights/TinkersConstruct#1985]
Not sure if this is a bug or i'm missing something, but it seems mattocks actually do more damage than broadswords and a lot more than longswords. Did longswords get nerfed to be less damage than broadswords? And why does a mattock of the same type do more damage than either?

Forge - 1.8.9-11.15.1.1808
TC - 1.8.9-2.2.0b
Mantle - 1.8.9-0.9.2

![2016-03-29_19 19 17](https://cloud.githubusercontent.com/assets/17035158/14129078/e9efbfa0-f5e3-11e5-9274-11acc6429e19.png)
![2016-03-29_19 19 22](https://cloud.githubusercontent.com/assets/17035158/14129079/ed64ae48-f5e3-11e5-953a-085f4bbef15e.png)
![2016-03-29_19 19 24](https://cloud.githubusercontent.com/assets/17035158/14129080/ef9f0d0c-f5e3-11e5-8ff8-221733329b91.png)

![2016-03-29_19 19 25](https://cloud.githubusercontent.com/assets/17035158/14129090/088a2018-f5e4-11e5-9b9e-e17f72035ba3.png)
![2016-03-29_19 19 26](https://cloud.githubusercontent.com/assets/17035158/14129094/0e9bb3fe-f5e4-11e5-9dd2-144c0de9635a.png)
![2016-03-29_19 19 27](https://cloud.githubusercontent.com/assets/17035158/14129095/10c1dc08-f5e4-11e5-863b-a56083ce75be.png)

![2016-03-29_19 19 28](https://cloud.githubusercontent.com/assets/17035158/14129098/13b0fa7a-f5e4-11e5-98b9-11813f4f0069.png)
![2016-03-29_19 19 29](https://cloud.githubusercontent.com/assets/17035158/14129100/177721ca-f5e4-11e5-9601-f4f66aadc345.png)
![2016-03-29_19 19 30](https://cloud.githubusercontent.com/assets/17035158/14129101/19f3d394-f5e4-11e5-82f6-5cb021105b57.png)

**Comment by bonii-xx** [comment]
They scale differently. Mattocks always had high base damage. Longswords are indeed a bug, because of a sign derp.
3cea1efd9f02c564b10f4aab15931b41cbaa6399
