### ISSUE TITLE
Change tool naming to clientside processing only

### ISSUE THREAD

**Issue by bonii-xx** [SlimeKnights/TinkersConstruct#1986]
Don't sync the text field with the server and other clients for fluid typing. Only send name to server when actually building the tool, and name serverside.

Fixes the incredible lag when typing in the text field, but other people wont see what you type anymore.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. 1.16 currently has no tool naming, but when I bring it back in 1.18 my plan is to keep one copy per player and whichever player takes the item wins the name
