### ISSUE TITLE
[1.9] Client kicked to main menu when accessing Stencil Table/Part Builder GUI on Server

### ISSUE THREAD

**Issue by dirtyfargo** [SlimeKnights/TinkersConstruct#1987]
Description: When right clicking into the Stencil Table or Part Builder on a server, my client is forcibly disconnected to the main menu. This also happens when clicking certain buttons in the Tool Station, and doesn't seem to occur in a singleplayer world. 
The client log didn't have any relevant information, but here's the [fml-server-latest.log](https://gist.github.com/dirtyfargo/6c18c6e854a6cbcd23cc1e87275f120e)
Forge Version: 12.16.0.1813
TCon: 1.9-2.2.1
Mantle: 1.9-0.9.3
I realize it's in Alpha so server stuff might just not be implemented yet, but thought Id mention the issue just in case :)

**Comment by dirtyfargo** [comment]
Fixed in Mantle 1.9-0.9.3a

**Comment by bonii-xx** [comment]
Yup. :)
