### ISSUE TITLE
Tinkers' Frames when harvested are Vanilla Frames

### ISSUE THREAD

**Issue by VallenFrostweaver** [SlimeKnights/TinkersConstruct#1990]
When you try to pick up any of the Tinkers' frames (i.e. Fancy, Aluminum Brass, etc) you get a Vanilla Minecraft Item Frame instead of the Tinkers' frame.

Minecraft Version 1.8.9
Tinkers' Version 2.2.0

**Comment by laz2727** [comment]
Iirc fixed already.

**Comment by VallenFrostweaver** [comment]
Dang. Missed the new version that just came out. Thanks. Please close.Tested and this is indeed fixed now.
