### ISSUE TITLE
Crashed when place item on crafting table 

### ISSUE THREAD

**Issue by StanWinchester** [SlimeKnights/TinkersConstruct#1991]
I was being a little sloppy when I placed a pattern on a crafting table to create a tool station. I tried to restart MC, but it still crashed. This is an existing world I was working on and then installed the new alpha TConstruct-1.9-2.2.1.jar

Please see: https://paste.ee/p/CIzON

Also look at lines 157-171; 200-214 where some sound files are not loading
And line: 222 where the modifier soulbound does not load.

The same sound files and soulbound errors also occur in TConstruct-1.8.9-2.2.1.jar, though I am not having stability issues with TConstruct-1.8.9-2.2.1.jar

Do you want me to post separate crash reports for these other two issues?

Thanks again for a very fun mod!
Stan

**Comment by bonii-xx** [comment]
#1988 

Sounds are bugged in Forge currently, soulbound simply is still missing.

**Comment by StanWinchester** [comment]
Thanks, this fixed it
