### ISSUE TITLE
{1.9} Tinkers Construct Alpha 1.9 fluid issue

### ISSUE THREAD

**Issue by RedBullSlurpie** [SlimeKnights/TinkersConstruct#1992]
Upon finding a slime island, I found that I was able to walk on the water, as if it were a block.. can't swim in it. Wasn't sure if there was a bug report already submitted on this or not, I checked and didn't see one, maybe I didn't look hard enough, but just incase going to submit this one also. So yeah, liquid from Tinkers seems to allow me to walk on it as if it were a block, it flows normally, but it treats each block area as a block. No crash at all.

**Comment by bonii-xx** [comment]
Forge issue from the 1.9 port. Should get fixed sometime soon in Forge.

**Comment by bonii-xx** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/2680
