### ISSUE TITLE
{1.9} Issue with smeltery

### ISSUE THREAD

**Issue by RedBullSlurpie** [SlimeKnights/TinkersConstruct#1993]
Build a smeltery in 1.9 Tinkers, can't seem to pour anything out of the smeltery into a basin, or table, tried making a blank cast to double ingots, but can't seem to pour anything out of it.. no crash, just doesn't work.. Also here is another bug you might want to know about, the Ores inside the smeltery are like triple the size, here is a screen shot.

http://imgur.com/a/5MwLc

**Comment by RedBullSlurpie** [comment]
Never mind about the smeltery not working, I placed the faucets on the wrong blocks! But there still is the issue of the huge blocks in smeltery. :P

**Comment by bonii-xx** [comment]
Vanilla rendering changed between 1.8.9 and 1.9, but it's a simple fix.
