### ISSUE TITLE
Tool durability Fortify/Upgrade...?

### ISSUE THREAD

**Issue by Celeblang** [SlimeKnights/TinkersConstruct#1995]
Hello!

My question is: can I fortify or upgrade my stone mattock's (or any other T-item's) durability in some way? t's not the best I only can dig 8 blocks and after I've to repair it again. I upgraded it's mining lvl to iron with flint, but it's durability still 8/8. Yeah, I know the mattock's mining lvl is not important :D

Thanks for your help and for your work! :)

**Comment by laz2727** [comment]
Change the handle/binding. Stone handles suck.

**Comment by bonii-xx** [comment]
Experiment around with different materials for the parts, otherwise you can add durability with a diamond/emerald or increase effective durability with different material traits/reinforced modifier.

**Comment by Celeblang** [comment]
Thank you!

2016-04-02 13:30 GMT+02:00 boni <notifications@github.com>:
