### ISSUE TITLE
Crash with Latest Forge (anything after 1817)

### ISSUE THREAD

**Issue by krelios** [SlimeKnights/TinkersConstruct#1997]
When using any version of Forge past 1817, TiC crashes on startup (Exception caught from a pulse on flightpath for mod ID tconstruct).

Full crash log here: [http://paste.ee/p/GiYER](http://paste.ee/p/GiYER)

**Comment by bonii-xx** [comment]
Don't use anything after 1817 for now. No mod that's setup properly will work without update.

**Comment by SpaneBoswell** [comment]
Wow! I was just about to update forge. Thank heaven I saw this.

**Comment by 4rz0** [comment]
Why is this marked as resolved?
This should be in open issues so that people find it there.

**Comment by bonii-xx** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/722449/14358182/22dcd942-fcec-11e5-8e89-41cdbf9d5ef6.png)

**Comment by 4rz0** [comment]
Oh.
Interesting, thanks for pointing that out.
I'm getting closer to understand how github works ;D

**Comment by bonii-xx** [comment]
The closed message there might've been confusing. That's from another issue that was closed and referenced here though.
