### ISSUE TITLE
Dangerous alternative prefix thaumcraft for name molten_brass

### ISSUE THREAD

**Issue by bunSakurAing** [SlimeKnights/TinkersConstruct#1999]
http://pastebin.com/Tv7iHcAV
This is someone else's error when using
I use the same client has no such problem
Start loading half the game suddenly shut down
I hope to have a solution

**Comment by bonii-xx** [comment]
It's not an error, just a warning. It's nothing to worry about, working as intended.

**Comment by bunSakurAing** [comment]
but the game was shut down, he did not continue to load

**Comment by bonii-xx** [comment]
As I said, that did not cause the crash.
