### ISSUE TITLE
1.8.9 Smeltery Snow Issue

### ISSUE THREAD

**Issue by DemoXinMC** [SlimeKnights/TinkersConstruct#2003]
In 1.8.9, it appears that the fake blocks placed inside the smeltery aren't functioning properly and can be replaced?  In the Curse pack I'm building, we discovered an issue where some biomes are placing snow arbitrarily inside the smeltery, causing the multiblock to be non-functional until those snow blocks are broken.

Before:
https://i.gyazo.com/07753fdb24ee4e6f48d41dbc70ae9700.png
https://i.gyazo.com/4e8cff7a3dc08876d750022eb33ae1b2.png

After:
https://i.gyazo.com/d9b552f6f2684dab279c4d52336444e4.png
https://i.gyazo.com/5b98157abb5945a956e1382d56eac8ad.png

**Comment by bonii-xx** [comment]
That's because there are no fake blocks inside the smeltery. If there's a block in the smeltery it's not valid, simple as that. Just put a roof on it to prevent snow from falling in.
