### ISSUE TITLE
Severe FPS degradation with JEI

### ISSUE THREAD

**Issue by Cherry** [SlimeKnights/TinkersConstruct#2007]
Tinkers' Construct version: 1.9-2.2.2
Mantle version: 1.9-0.9.4
JEI version: 1.9-3.2.8.185
Forge version: 12.16.0.1863

Very similar to issue https://github.com/TeamBR-Modding/NeoTech/issues/280

Replication steps:

- Startup any world with JEI + Tinkers' Construct installed, and navigate to the page in JEI with Tinkers' Construct items. Note the drastic FPS drop. Screenshot: https://jross.me/l/6g2si

The FPS drop can also be noted when just having a lot of Tinkers' items in one's inventory: https://jross.me/l/gakfi, just not to the extreme of the amount of items that JEI is rendering.

If any further information is required, please let me know.

**Comment by laz2727** [comment]
TiC items are heavy on render, what else is new.

**Comment by Cherry** [comment]
Of course, however dropping from ~150fps to <3fps seems a little drastic.

**Comment by whitestarx0312** [comment]
Yeah I have this issue too. I can run an ultra shader pack at 100FPS but not Tinkers' tools lol. I suggest using the "hide" feature in JEI to remove all tools. Tool parts and other parts of Tinkers' don't seem to have this issue.

**Comment by bonii-xx** [comment]
Hm, looks like FluentIterable has some performance issues.
