### ISSUE TITLE
[Crash] MC 1.9 - TiC 2.2.2 - forge 1862 - storage drawers 3.1.5

### ISSUE THREAD

**Issue by goosezilla** [SlimeKnights/TinkersConstruct#2010]
Crafting storage drawers in a TiC crafting bench causes some kind of render/GUI crash.

crash log http://pastebin.com/zxCvv0AY

**Comment by pjfranke** [comment]
This is a client side crash.  You can change the first option in tconstruct.cfg to disable the on-table item rendering, and let this work:

clientside {
    # If true all of Tinkers' tables will render their contents on top of the table
    B:renderTableItems=true

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/Mantle/issues/59
