### ISSUE TITLE
Worldgen ore disable flag appears to not work in foreign dimensions?

### ISSUE THREAD

**Issue by landaro** [SlimeKnights/TinkersConstruct#2011]
See the follwoing issue for details

[https://github.com/McJty/RFTools/issues/502](https://github.com/McJty/RFTools/issues/502)

in short:
I am getting TCon Copper Ore in RFTools Dimensions that ask for default (= overworld ore generation), which in the overworld is handled by CoFH. Copper generation is disabled in the TCon config, which works for the overworld, but apparently not in the dimensions with ids 2, 3 and 4.

Is this a TCon Issue?

**Comment by bonii-xx** [comment]
If copper generation is disabled then no copper should generate in any dimension. Most likely a cofh/rftools thing.

**Comment by landaro** [comment]
Hmm, I cannot see how it could be cofh's fault, as there is no mention of the TCon Copper Ore block anywhere in the cofh world generation config (you say what you want, possibly restricted to certain biomes/dimensions -- but not what you don't want). And McJty pointed here ...

I am not too familiar with minecraft mod code and haven't looked at java in a while, but from my coding experience I could imagine that there are multiple code paths leading to the fragment that is responsible for the TCon ore generation and not all of those actually check the configured options. Then RFTools might be choosing such a non-standard code path somehow while generating chunks for its dimensions (it has to hook into the generation process somehow to incorporate the features requested for that particular dimension).

I can try to compose an MWE-modpack to replicate the issue later this week, maybe.

**Comment by bonii-xx** [comment]
Don't bother, considering it's 1.7.10
