### ISSUE TITLE
TC1.8.8 not working on server (KCauldron incompatibility issue?)

### ISSUE THREAD

**Issue by PONYFOX** [SlimeKnights/TinkersConstruct#2012]
Hello,
I want to use TC in a server but when I use TC tools, the mining speed isn't modified. No error log.

Did KCauldron or a plugin can broke TC? If it, can I repair the error with a config or something?

**Comment by KnightMiner** [comment]
Try it without cauldron, and if it does not happen try to find which plugin caused it. It is very hard to fix an issue without knowing what caused it
