### ISSUE TITLE
{1.9} Combat balance problem, not just weapons

### ISSUE THREAD

**Issue by werff** [SlimeKnights/TinkersConstruct#2016]
Well, currently the weapons had this speeds:

Broadsword: 1.6 (Of the sword weapons, the best)
Longsword: 1.3 (less damange on the weapon)
Cleaver: 0.7 (very por damange, who doesn't compensate cost and time per hit)

Now, the not so weapons, but they are "weapons"

Friyng pan: 4
Battlesing: 5

They only have some less damange, but nearly the same as the broadsword.

The tools attack speed now.
Except hatchets (1.1) They all have 4 of speed.

The mattock, having the same base damange as the Cleaver, with a speed of 4, and the 3 modifier slots (the cleaver only has 2, it should have the same but, this is not our problema now XD) it's now the best weapon, and a tool too, so...

Please, make the speeds and damange to a decent place, or just copy the 1.9 vanilla attackspeed from axes, pickaxes, and shovels, and lower the damange formula for them.

I will use my "[Shovel Knight](http://i.imgur.com/iVwDx7W.pngurl)" combat shovel, until then XD

**Comment by bonii-xx** [comment]
Too late 6f753f1b877bbd5e39b6cfa0cb271acfa82ee96c
