### ISSUE TITLE
{1.9} Crafting Station Bug

### ISSUE THREAD

**Issue by EndermanParty** [SlimeKnights/TinkersConstruct#2019]
This is most likely posted elsewhere but I will put it here.
I am using the crafting station to craft Compacting Drawers from Storage Drawers and from what I read, when the crafting table tries to render the normal oak 2x2 drawer - minecraft crashes. This keeps happening as I load the world. I assume that this is also happening to other mods as well when put in the crafting station. - I was correct, disabling the rendering in the config fixed the issue so I can actually load my world.
http://paste.ee/p/F5vx4

**Comment by laz2727** [comment]
Okay. I did some research, and it just looks stupid. How exactly table
expects other objects to render using its own metadata?

2016-04-17 9:01 GMT+05:00 EndermanParty <notifications@github.com>:

**Comment by Myknakryu** [comment]
Okay that bug was reported week or two ago. To fix it you must change config in TConstruct renderTableItems to false.
#1988

**Comment by bonii-xx** [comment]
#2010
