### ISSUE TITLE
Not able to add modifiers

### ISSUE THREAD

**Issue by Harith163** [SlimeKnights/TinkersConstruct#2020]
Why aren't additional modifiers a thing from 1.8.9? They made tinkers tools worth it.

**Comment by AlterAkima** [comment]
Because the materials now have a lot more traits.

**Comment by Harith163** [comment]
I want to make my enderium pick have speed like 85 or something crazy like that and that isn't just possible with 3 modifers remaining

**Comment by Harith163** [comment]
or atleast iguana tweaks could bring back the 1.7.10 ways of TConstructs.

**Comment by bonii-xx** [comment]
Use creative modifiers.

**Comment by laz2727** [comment]
You can't expand your tools infinitely anyway, all mods are capped.
