### ISSUE TITLE
[FREQ, 1.9] Brass Alloy smelting recipe configurable?

### ISSUE THREAD

**Issue by Syndaryl** [SlimeKnights/TinkersConstruct#2022]
I can pour smeltery casts out of brass, but I can't actually alloy to make brass in the smeltery (or at least Zinc + Copper isn't doing it, which is the BaseMetals recipe). A registry or configuration to pick the recipe for brass would help a lot.

**Comment by bonii-xx** [comment]
That an alloy is missing is an oversight (same as dusts ;)). I'll use the 2:1 ratio for now, maybe add a config option later should some other mods use something different, but I expect it to be more or less standard.
