### ISSUE TITLE
[1.9-2.2.2.jenkins150] Client crash on startup

### ISSUE THREAD

**Issue by dirtyfargo** [SlimeKnights/TinkersConstruct#2023]
Description: Client crashes while loading textures on startup.
[Client Crash Report](https://gist.github.com/dirtyfargo/5de69ffe15f3c1c72215404d9053ebb7)
TConstruct-1.9-2.2.2.jenkins150
Mantle-1.9-0.9.4.jenkins125
Forge 12.16.0.1865

**Comment by bonii-xx** [comment]
Got the log somewhere? Also were you using a resource pack?

**Comment by dirtyfargo** [comment]
I get the crash with just Mantle and TCon installed no resource pack, here's the [Full Log](https://gist.github.com/dirtyfargo/f38dd4bdb1778e0ddbc2af2995c29b8f)

**Comment by bonii-xx** [comment]
Not one of our tcon versions.

**Comment by dirtyfargo** [comment]
Oh alright, sorry! I guess I'm on the wrong [jenkins](https://dvs1.progwml6.com/jenkins/) or something :P
Anyways I rolled back and will wait for the new features to be released on curseforge :)

**Comment by bonii-xx** [comment]
That jenkins doesn't have any 1.9 versions for you :P
