### ISSUE TITLE
Glowball glowing blocks need a placement check

### ISSUE THREAD

**Issue by bonii-xx** [SlimeKnights/TinkersConstruct#2024]
Glowballs can be attached anywhere, they need to remove themselves if the block they're connected to is not solid on their side.

They also need to check when a neighbor is broken, to see if they have to remove themselves. Think torches/ladders.

**Comment by KnightMiner** [comment]
I looked into the vanilla code and it looks fairly straight forward, so I can have something ready later today. I think I'll have it check if the placement is valid both when the entity places the block and on block update.

**Comment by bonii-xx** [comment]
Yes, the block can just check it itself on placement. The torches etc. do that too iirc. Please do, I already wanted to forward it to you actually. ;)
