### ISSUE TITLE
Items are sometimes flipped in the smeltery table

### ISSUE THREAD

**Issue by C1ffisme** [SlimeKnights/TinkersConstruct#2025]
![2016-04-19_19 00 43](https://cloud.githubusercontent.com/assets/9893266/14659693/c58236f8-0663-11e6-8e3a-e329fa8953dd.png)

I need to test this to see if it depends on direction, though.

EDIT: It seems that they are all pointing in 1 direction...
![2016-04-20_11 00 21](https://cloud.githubusercontent.com/assets/9893266/14681560/38166bfc-06e7-11e6-9984-910d9439619e.png)

Should be an easy-ish bug to fix, I think...

**Comment by bonii-xx** [comment]
What TiC version?

**Comment by C1ffisme** [comment]
1.9-2.2.2
