### ISSUE TITLE
Items rendered on a tool forge INCREASE frames.

### ISSUE THREAD

**Issue by Harith163** [SlimeKnights/TinkersConstruct#2030]

**Comment by Harith163** [comment]
Let me be clear, I get 300 frames in a void world, now I get 40 odd frames, with a tool forge rendering a pick and cobalt, I get 73- 83 frames! I am not complaining, but thought I should just let you know..
![2016-04-21_11 25 47](https://cloud.githubusercontent.com/assets/18382195/14699300/50d608dc-07b4-11e6-9f91-f22515fbf19d.png)
![2016-04-21_11 25 38](https://cloud.githubusercontent.com/assets/18382195/14699301/50da1ada-07b4-11e6-84ff-e34aee520c80.png)
![2016-04-21_11 25 36](https://cloud.githubusercontent.com/assets/18382195/14699302/50ddcd42-07b4-11e6-98f6-b78be544d529.png)
![2016-04-21_11 24 35](https://cloud.githubusercontent.com/assets/18382195/14699303/50e128ac-07b4-11e6-9355-f9aa067a482c.png)
![2016-04-21_11 23 51](https://cloud.githubusercontent.com/assets/18382195/14699305/51c6777c-07b4-11e6-9c82-176566acfc54.png)
![2016-04-21_11 23 39](https://cloud.githubusercontent.com/assets/18382195/14699304/519f7b2c-07b4-11e6-98e4-866df30f1298.png)

**Comment by bonii-xx** [comment]
Guess I should start telling people to put tool forges with tools on them everywhere.

**Comment by jriwanek** [comment]
Not everywhere, just one per chunk. (:

**Comment by ThatGamerBlue** [comment]
@Harith163 also nice xray mod m8
