### ISSUE TITLE
Smeltery Material Rates per Cast Discrepancy  1.8.9-2.2.1.jenkins1005

### ISSUE THREAD

**Issue by LuminaDragon** [SlimeKnights/TinkersConstruct#2032]
Good afternoon! I apologize if this is already addressed.

On our server, we're finding that casts are taking more materials that needed (often 1.5 or double what is stated on the cast) and in some cases the part builder is doing likewise.  Are there known mod conflicts that cause this or are there configs we can use to adjust this?

**Comment by bonii-xx** [comment]
No known conflicts and no configs. Are you sure you aren't simply experiencing the cost changes from 1.7 to 1.8?

**Comment by LuminaDragon** [comment]
If I have "5 ingots" or "3 ingots" worth left, should I be getting only one ingot?  That's the variable I've seen.

**Comment by LuminaDragon** [comment]
ok, realized I need to clarify further, this seems to be the cast if you are trying to use leftovers out of the casting basin and pour it out into ingots as opposed to leaving it in the basic when you have different ore to use.

**Comment by bonii-xx** [comment]
Ok there seems to be an issue with taking liquids out of the casting basin. It always returns 1 ingot, it seems.

**Comment by LuminaDragon** [comment]
and it means making casts or using casts from the liquid in the casting basin is a tweeked :)

Sorry for missing the most important data scenario there!
