### ISSUE TITLE
Instant crash in 1.9

### ISSUE THREAD

**Issue by RaduAnthonyBlacksmith** [SlimeKnights/TinkersConstruct#2033]
I will leave the crash report.The same thing happend with and with-out Optifine.

"---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 22.04.2016 13:22
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:793)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1961)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:156)
	at net.minecraft.world.World.func_72866_a(World.java:1934)
	at net.minecraft.world.World.func_72870_g(World.java:1903)
	at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1783)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:793)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1961)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:156)
	at net.minecraft.world.World.func_72866_a(World.java:1934)
	at net.minecraft.world.World.func_72870_g(World.java:1903)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 268
	Entity Name: Radu
	Entity's Exact location: -264,50, 64,00, -49,50
	Entity's Block location: World: (-265,64,-50), Chunk: (at 7,4,14 in -17,-4; contains blocks -272,0,-64 to -257,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1737)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Radu'/268, l='MpServer', x=-264,50, y=64,00, z=-49,50]]
	Chunk stats: MultiplayerChunkCache: 164, 164
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,-44), Chunk: (at 0,4,4 in -16,-3; contains blocks -256,0,-48 to -241,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 48 game time, 48 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntityPig['Pig'/136, l='MpServer', x=-230,50, y=69,00, z=-76,50], EntityFallingBlock['Falling Block'/204, l='MpServer', x=-408,50, y=34,00, z=-179,50], EntityFallingBlock['Falling Block'/202, l='MpServer', x=-408,50, y=34,00, z=-178,50], EntityPig['Pig'/133, l='MpServer', x=-228,50, y=69,00, z=-77,50], EntityPig['Pig'/135, l='MpServer', x=-227,50, y=69,00, z=-76,50], EntityPig['Pig'/134, l='MpServer', x=-226,50, y=70,00, z=-75,50], EntitySheep['Sheep'/93, l='MpServer', x=-306,50, y=87,00, z=10,50], EntitySheep['Sheep'/92, l='MpServer', x=-309,50, y=87,00, z=11,50], EntitySheep['Sheep'/94, l='MpServer', x=-304,50, y=88,00, z=9,50], EntityFallingBlock['Falling Block'/209, l='MpServer', x=-408,50, y=34,00, z=-180,50], EntitySheep['Sheep'/91, l='MpServer', x=-308,50, y=90,00, z=11,50], EntitySheep['Sheep'/103, l='MpServer', x=-278,50, y=64,00, z=-52,50], EntitySheep['Sheep'/110, l='MpServer', x=-268,39, y=63,00, z=20,55], EntitySheep['Sheep'/108, l='MpServer', x=-266,67, y=64,00, z=22,26], EntitySheep['Sheep'/109, l='MpServer', x=-267,45, y=63,00, z=20,50], EntitySheep['Sheep'/106, l='MpServer', x=-278,50, y=64,00, z=-53,50], EntitySheep['Sheep'/107, l='MpServer', x=-270,50, y=64,00, z=21,50], EntitySheep['Sheep'/104, l='MpServer', x=-279,50, y=64,00, z=-53,50], EntitySheep['Sheep'/105, l='MpServer', x=-278,50, y=64,00, z=-55,50], EntityPig['Pig'/119, l='MpServer', x=-252,50, y=70,00, z=-96,50], EntitySheep['Sheep'/126, l='MpServer', x=-250,50, y=71,00, z=-99,50], EntitySheep['Sheep'/125, l='MpServer', x=-250,50, y=71,00, z=-98,50], EntitySheep['Sheep'/124, l='MpServer', x=-250,50, y=71,00, z=-98,50], EntitySheep['Sheep'/123, l='MpServer', x=-251,50, y=70,00, z=-97,50], EntityPig['Pig'/122, l='MpServer', x=-249,50, y=70,00, z=-96,50], EntityPig['Pig'/121, l='MpServer', x=-251,50, y=70,00, z=-95,50], EntityPig['Pig'/120, l='MpServer', x=-251,50, y=70,00, z=-96,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_76, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 371942056 bytes (354 MB) / 852373504 bytes (812 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	JEI{3.1.2.172} [Just Enough Items] (jei_1.9-3.1.2.172.jar) 
	UCHIJAAAA	llor{1.0.7-mc1.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.9.jar) 
	UCHIJAAAA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJAAAA	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	Loaded coremods (and transformers): 
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
	****	- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerDebug (Enabled/Not Forced)**
**
	Launched Version: 1.9-forge1.9-12.16.0.1865-1.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 2.1.0 - Build 8.15.10.2900, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Canadian English (Canada)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU M 370 @ 2.40GHz"

**Comment by laz2727** [comment]
>jenkins

I'm pretty sure jenkins builds are unsupported.

2016-04-22 15:35 GMT+05:00 RaduAnthonyBlacksmith <notifications@github.com>:

**Comment by RaduAnthonyBlacksmith** [comment]
Unsupported by other mods ? 
What do you mean ?

**Comment by laz2727** [comment]
Unsupported by the slimeknights. I mean, they were crashing all last week
because of a missing item.

2016-04-22 15:40 GMT+05:00 RaduAnthonyBlacksmith <notifications@github.com>:

**Comment by RaduAnthonyBlacksmith** [comment]
Should I expect a fix soonish ?

**Comment by jriwanek** [comment]
No, you shouldn't be using jenkins builds, use the releases on curseforge instead.

Long version: If you're using the jenkins builds you should be able to provide fixes yourself.

**Comment by bonii-xx** [comment]
Plot twist: That's actually the latest Curseforge release.

However nothing hints at a tcon related crash there. I'd say it's either a corrupt file (redownload Forge) or some issue with the Forge version.

**Comment by RaduAnthonyBlacksmith** [comment]
Progress update: 
1.Removed all the mods. 
2.Put them back one by one to see which of them crashed
3.Updated JEI
4.Removed LLI
5.Added BloodMagic
6.Added Optifine
7.Added TC and Mantle latest versions.
----------------------------------------------------------
It works

**Comment by bonii-xx** [comment]
There you have it /o\

Probably some internal changes since then. I guess LLI did some ASM stuff that didn't work anymore, since the crash itself was in vanilla code.
