### ISSUE TITLE
Model Bake Broken -- MC 1.9, Forge 12.16.0.1865, TC <custom><f1865 snapshot20160418 gradle2.9>

### ISSUE THREAD

**Issue by JonnyBrando** [SlimeKnights/TinkersConstruct#2034]
Hey, I tried to rebuild Tinkers for F1865, but it appears that they must have changed some of the mappings. Works fine for 1863.

I had to bump the Gradle from 2.7 to 2.9. Also bumped the snapshot while I was at it (snapshot 20160419 doesn't work -- will not build). 3 Warnings during build, but it was successful.

It loaded into MC once without RPs. I added Chromahills, and it crashed. Removed all RPs through INI, will not load again. Deleted the tinkers CFG files, let rebuild, same error.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  MalisisCorePlugin (malisiscore-1.9-3.0.5.jar)
  MMFMLCorePlugin (MultiMine-1.9.jar)
  BetterFoliageLoader (BetterFoliage-MC1.9-2.0.9.jar)
  MalisisSwitchesPlugin (malisisswitches-1.9-2.0.0.jar)
  DLFMLCorePlugin (DynamicLights-1.9.jar)
  SCFMLCorePlugin (StalkerCreepers-1.9.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 4/22/16 8:50 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bake(MaterialModel.java:51)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:323)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bake(MaterialModel.java:51)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:323)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 727926672 bytes (694 MB) / 1602592768 bytes (1528 MB) up to 4268163072 bytes (4070 MB)
	Mod Pack: 1.9-SNAPSHOT-r47D63A1-b7-2016-04-19_22-30-16
	LiteLoader Mods: 1 loaded mod(s)
          - Presence Footsteps version u9 for 1.9
	LaunchWrapper: 34 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.mods.betterfoliage.loader.BetterFoliageTransformer
          - Transformer: $wrapper.atomicstryker.dynamiclights.common.DLTransformer
          - Transformer: $wrapper.invtweaks.forge.asm.ContainerTransformer
          - Transformer: $wrapper.atomicstryker.multimine.common.fmlmagic.MMTransformer
          - Transformer: $wrapper.atomicstryker.stalkercreepers.common.SCTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: $wrapper.net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
          - Transformer: $wrapper.net.malisis.core.util.chunkblock.ChunkBlockTransformer
          - Transformer: $wrapper.net.malisis.core.renderer.transformer.MalisisRendererTransformer
          - Transformer: $wrapper.net.malisis.core.renderer.icon.asm.TextureMapTransformer
          - Transformer: $wrapper.net.malisis.switches.asm.MalisisSwitchesTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms350M -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:+AggressiveOpts -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 Optifine OptiFine_1.9_HD_U_B2_pre 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJA	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJA	Baubles{1.2.0.1} [Baubles] (Baubles-1.9-1.2.0.1.jar) 
	UCHIJA	BetterAchievements{0.2.2} [Better Achievements] (BetterAchievements-1.9-0.2.2.jar) 
	UCHIJA	BetterFoliage{2.0.9} [Better Foliage] (BetterFoliage-MC1.9-2.0.9.jar) 
	UCHIJA	BiomesOPlenty{4.0.2.2012} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2012-universal.jar) 
	UCHIJA	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UCHIJA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCHIJA	DynamicLights{1.4.1} [Dynamic Lights] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	graves{1.9-b8-universal} [Graves Mod] (graves-1.9-b8-universal.jar) 
	UCHIJA	LunatriusCore{1.1.2.34} [LunatriusCore] (LunatriusCore-1.9-1.1.2.34-universal.jar) 
	UCHIJA	InGameInfoXML{2.8.1.82} [InGame Info XML] (InGameInfoXML-1.9-2.8.1.82-universal.jar) 
	UCHIJA	inventorysorter{0.7.10+29} [Simple Inventory sorting] (inventorysorter-1.9-0.7.10+29.jar) 
	UCHIJA	inventorytweaks{1.61-dev-45-29e0ed5} [Inventory Tweaks] (InventoryTweaks-1.61-dev-45.jar) 
	UCHIJA	JEI{3.2.10.185} [Just Enough Items] (jei_1.9-3.2.10.185.jar) 
	UCHIJA	journeymap{1.9-5.1.6b2} [JourneyMap] (journeymap-1.9-5.1.6b2-unlimited.jar) 
	UCHIJA	malisiscore{1.9-3.0.5} [MalisisCore] (malisiscore-1.9-3.0.5.jar) 
	UCHIJA	malisisblocks{1.9-3.0.0} [Malisis Blocks] (malisisblocks-1.9-3.0.0.jar) 
	UCHIJA	malisisdoors{1.9-4.0.1} [MalisisDoors] (malisisdoors-1.9-4.0.1.jar) 
	UCHIJA	malisisswitches{1.9-2.0.0} [Malisis Switches] (malisisswitches-1.9-2.0.0.jar) 
	UCHIJA	mantle{1.9-0.9.4.DEV.6ea7e05} [Mantle] (Mantle-1.9-0.9.4.DEV.6ea7e05.jar) 
	UCHIJA	RadixCore{1.9-2.1.0} [RadixCore] (RadixCore-1.9-2.1.0-BETA-universal.jar) 
	UCHIJA	MCA{1.9-5.1.2} [Minecraft Comes Alive] (MCA-1.9-5.1.2-BETA-universal.jar) 
	UCHIJA	AS_MultiMine{1.5.2} [Multi Mine] (MultiMine-1.9.jar) 
	UCHIJA	parachutemod{1.4.1} [Parachute Mod] (parachutemod-ng-1.9-1.4.1-395.jar) 
	UCHIJA	progressiveautomation{1.6.38} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.38.jar) 
	UCHIJA	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar) 
	UCHIJA	AS_Ruins{15.8} [Ruins Spawning System] (Ruins-1.9.jar) 
	UCHIJA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.jar) 
	UCHIJA	StorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar) 
	UCHIJA	tconstruct{1.9-2.2.2.DEV.44f5951} [Tinkers' Construct] (TConstruct-1.9-2.2.2.DEV.44f5951.jar) 
	UCHIJA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.9-3.0.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
MMFMLCorePlugin (MultiMine-1.9.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
BetterFoliageLoader (BetterFoliage-MC1.9-2.0.9.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
MalisisSwitchesPlugin (malisisswitches-1.9-2.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
DLFMLCorePlugin (DynamicLights-1.9.jar)
  atomicstryker.dynamiclights.common.DLTransformer
SCFMLCorePlugin (StalkerCreepers-1.9.jar)
  atomicstryker.stalkercreepers.common.SCTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.72' Renderer: 'GeForce GTX 780 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.9-forge1.9-12.16.0.1865-1.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 780 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.72, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ChromaHills128x-1.9_v0.1.zip, ChromaHillsMods-128x1.9_v1.0.zip, PF.Resources.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.9_HD_U_B2_pre
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: 'Sildurs Vibrant Shaders v1.141 Extreme.zip
	OpenGlVersion: 4.5.0 NVIDIA 364.72
	OpenGlRenderer: GeForce GTX 780 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by bonii-xx** [comment]
Ours work fine.

**Comment by jgwath** [comment]
I got a similar code with the most current files from curse web site. I am attempting to run Minecraft 1.9 - Forge 12.16.1.1898 with TC 2.2.2 and Mantle 0.9.4

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  ItemPatchingLoader (ItemPhysic-Mod-Lite-1.9.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  CCCDeobfPlugin (unknown)
  LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 5/11/16 12:28 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bake(MaterialModel.java:51)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:332)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bake(MaterialModel.java:51)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:332)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 495937408 bytes (472 MB) / 1187688448 bytes (1132 MB) up to 1597243392 bytes (1523 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1536M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1898 Optifine OptiFine_1.9_HD_U_B2 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1898.jar) 
	UCHIJA	Forge{12.16.1.1898} [Minecraft Forge] (forge-1.9-12.16.1.1898.jar) 
	UCHIJA	CodeChickenCore{2.0.1.53} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	UCHIJA	actuallyadditions{1.9-r31} [Actually Additions] (ActuallyAdditions-1.9-r31.jar) 
	UCHIJA	armorplus{1.9.3-1.9} [ArmorPlus] (ArmorPlus1.9.3(1.9).jar) 
	UCHIJA	bagginses{2.3.0b} [Bagginses] (Bagginses-1.9-2.3.0b.jar) 
	UCHIJA	basemetals{2.2.2} [Base Metals] (BaseMetals_1.9-2.2.2.jar) 
	UCHIJA	Batty's Coordinates PLUS{1.9_1.9.02} [Batty's Coordinates PLUS Mod for Forge] (Batty's Coordinates PLUS Mod for Forge-1.9_1.9.02.jar) 
	UCHIJA	Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar) 
	UCHIJA	BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
	UCHIJA	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9-1.4.1.jar) 
	UCHIJA	chameleoncreepers{1.3} [Chameleon Creepers] (Chameleon-Creepers-Mod-1.9.jar) 
	UCHIJA	Chameleon{1.9-2.0.0} [Chameleon] (Chameleon-Library-1.9.jar) 
	UCHIJA	ChickenChunks{2.0.1.26} [ChickenChunks] (ChickenChunks-1.9-2.0.1.26-universal.jar) 
	UCHIJA	chiselsandbits{9.15} [Chisels & Bits] (chiselsandbits-9.15.jar) 
	UCHIJA	ColorfulStars{2.0.1} [Colorful Stars] (Colorful Stars-1.9-2.0.1.jar) 
	UCHIJA	craftelytra{1.0} [Craftable Elytra] (CraftableElytra-1.0.jar) 
	UCHIJA	craftablehorsearmour{1.0} [Craftable Horse Armour [CHA&S]] (CraftableHorseArmourAndSaddle-1.0.jar) 
	UCHIJA	craftablenametags{1.2} [Craftable Name Tags] (craftablenametags-1.2.jar) 
	UCHIJA	lootablebodies{2.0.0} [DrCyano's Lootable Bodies] (CyanosLootableBodies_1.9-2.0.0.jar) 
	UCHIJA	logicaldrops{0.9.4} [Logical Drops] (EM3R50N-LogicalDrops.1.9-0.9.4.jar) 
	UCHIJA	em{1.0} [Emerald Items Mod] (EmeraldItems v1.9-1.0.1.jar) 
	UCHIJA	eternalitems{1.9-0.2.1.17} [Eternal Items] (EternalItems-1.9-0.2.1.17.jar) 
	UCHIJA	k4lib{1.9-1.0.4} [K4Lib] (k4lib-1.9-1.0.4-universal.jar) 
	UCHIJA	FastTravel{1.9-1.0.1} [Fast Travel] (fastTravel-1.9-1.0.1-universal.jar) 
	UCHIJA	flatcoloredblocks{mc1.9-v2.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.9-v2.2.jar) 
	UCHIJA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9-1.4.7.jar) 
	UCHIJA	IronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
	UCHIJA	JEI{3.2.14.190} [Just Enough Items] (jei_1.9-3.2.14.190.jar) 
	UCHIJA	llor{1.0.7-mc1.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.9.jar) 
	UCHIJA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJA	mineralogy{3.0.1} [Mineralogy] (Mineralogy_1.9.0-3.0.1.jar) 
	UCHIJA	modifiable_armor{2.0.1} [Modifiable Armor 2] (Modifiable-Armor-1.0.1.jar) 
	UCHIJA	ModLister{1.9-1.0.4} [ModLister] (ModLister-1.9-1.0.4.jar) 
	UCHIJA	moreoverlays{1.3.1} [MoreOverlays] (moreoverlays-1.3.1-mc1.9.jar) 
	UCHIJA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-5.jar) 
	UCHIJA	ObsidianPlates{1.1.0} [Obsidian Plates] (ObsidianPlates-1.1.0_1.9.jar) 
	UCHIJA	harvestcraft{1.9a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9a.jar) 
	UCHIJA	pedestal{1.9-0.1.5-alpha} [§cPedestal] (pedestal-1.9-0.1.5-alpha.jar) 
	UCHIJA	PigManure{1.0.2} [Pig Manure] (Pig-Manure-Mod-1.9.jar) 
	UCHIJA	portablecrafting{1.9-1.0} [Portable Crafting] (PortableCrafting-1.9-1.0.jar) 
	UCHIJA	Psi{beta-31} [Psi] (Psi-beta-31.jar) 
	UCHIJA	randomthings{3.7} [Random Things] (RandomThings-MC1.9-3.7.jar) 
	UCHIJA	reborncore{2.1.0.53} [RebornCore] (RebornCore-1.9-2.1.0.53-universal.jar) 
	UCHIJA	rftools{4.46} [RFTools] (rftools-1.9.0-4.46.jar) 
	UCHIJA	SaltMod{1.8.c} [Salty Mod] (SaltyMod-1.9-1.8.c_beta-1.jar) 
	UCHIJA	ShieldHider{1.0.0} [Shield Hider] (ShieldHider-1.0.0_1.9.jar) 
	UCHIJA	simpleharvest{1.01} [simpleharvest] (simpleharvest-1.9-1854-1.01.jar) 
	UCHIJA	slimecompendium{1.2} [Slime Compendium] (SlimeCompendium1.3.jar) 
	UCHIJA	soulshardstow{1.9-2.3.9-25} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9-2.3.9-25.jar) 
	UCHIJA	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	UCHIJA	techreborn{1.0.6.197} [TechReborn] (TechReborn-1.9-1.0.6.197-universal.jar) 
	UCHIJA	Trashcans{2.0.2} [Trashcans] (Trashcans-1.9-2.0.2.jar) 
	UCHIJA	usefulrecipes{1.2} [UsefulRecipes] (UsefulRecipes-1.2.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	Loaded coremods (and transformers): 
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
ItemPatchingLoader (ItemPhysic-Mod-Lite-1.9.jar)
  com.creativemd.itemphysic.ItemTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
CCCDeobfPlugin (unknown)
  
LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2993' Renderer: 'Intel(R) HD Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: 1.9-forge1.9-12.16.1.1898
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 2.1.0 - Build 8.15.10.2993, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz

I am stuck in a heads up and g locked state.  Any assistance would be helpful  8^)
