### ISSUE TITLE
Elytra + Slimesling provides exponential(?) speed

### ISSUE THREAD

**Issue by MRebhan** [SlimeKnights/TinkersConstruct#2035]
If you equip the elytra and then fling yourself into the air with the slimesling the elytra will pick up incredible speed that cannot be stopped.

Video: https://youtu.be/BPtySrn83Vc

**Comment by bonii-xx** [comment]
Yeah I still need to stop the movement effect when the player is flying.

**Comment by Alexismachina** [comment]
Heh, i feel like this should've have been a feature :3

**Comment by bonii-xx** [comment]
You might think that, but once you travel so fast that chunk generation can't keep up you'll think otherwise. :P

**Comment by C1ffisme** [comment]
If only Minecraft's chunk generation wasn't so slow...

**Comment by TherminatorX** [comment]
If there was some way to have an elytra-specific behavior where each use of the sling added some velocity up to a maximum....

**Comment by MRebhan** [comment]
@Alexismachina If you travel at 300 blocks/sec you will think otherwise :D

**Comment by Alexismachina** [comment]
Still amazingly fun xD
