### ISSUE TITLE
Part builder not working

### ISSUE THREAD

**Issue by InkedMommyMC** [SlimeKnights/TinkersConstruct#2039]
I am playing with Tinkers via Cloud 9 mod pack. All of a sudden, the part builder stopped working but everything else is fine. I tried breaking it and putting back and also creating a new one but still nothing. I put in the materials and tool template and it gives me the stats but no output. Also, every now and then, drains will stop working and I have to exit the game and then go back in for it to work again.

**Comment by bonii-xx** [comment]
Check your logs

**Comment by InkedMommyMC** [comment]
I have since backed up all my FTB files onto my external hard drive and the deleted any related folders and files off my computer. I reinstalled FTB Launcher and Cloud 9 and now when I put that saved world back into the saves folder it gives errors that all the mods are missing. 

What logs specifically should I look for?

**Comment by bonii-xx** [comment]
Sounds like your modpack got issues. And the log probably was swarmed with exceptions. Anyway, there's nothing going on on my side here.

**Comment by InkedMommyMC** [comment]
Yeah. The log has tons of errors. I guess I am gonna have to start over from scratch :( Thanks for getting back to me anyway!
