### ISSUE TITLE
GUI loop issue with Tinker's Construct & NEI

### ISSUE THREAD

**Issue by skywalker3271** [SlimeKnights/TinkersConstruct#2040]
Hello,
I'm playing the Meatypack on Curse for Minecraft 1.7.10
I'm experiencing an issue where I get stuck in the Inventory gui when I accidently press keys simultaneously. Specifically for me Caps Lock & A. Every attempt to escape it just puts me back in. Re-logging does not correct the problem. My client must be fully restarted. I have attached my game output log. please advise. Thank you for your time.

[MeatyPack Game output log 160424.txt](https://github.com/SlimeKnights/TinkersConstruct/files/233729/MeatyPack.Game.output.log.160424.txt)

**Comment by C1ffisme** [comment]
I'm not sure if 1.7.10 is supported anymore. Development is focused on the 1.9 version now.

**Comment by bonii-xx** [comment]
Sounds like something that could be caused by a ton of things, outside of TiC as well. Luckily there is no real reason to press Capslock and A at the same time, unless you rebound them to something.

**Comment by TherminatorX** [comment]
Caps Lock and A are right next to each other on QWERTY keyboards, and I have been known to press both if I'm not paying enough attention.

**Comment by skywalker3271** [comment]
First thank you all for your assistance. Indeed my typing skills are horrid & the simultaneous pressing of keys I spoke of is accidental. But what is especially strange is that my Caps Lock key isn't bound to anything in game. Also, except for the trigger, this is reminiscent of a similar of perhaps the same bug reported fixed. I refer to the following thread: 
https://github.com/mod-warriors/NotEnoughKeys/issues/34
As a test I obtained a copy of the NotEnoughKeys-1.7.10-1.0.0b30.jar file mentioned. It crashed my client outright. Testing further,  I removed both mods from the pack & performed the key-flub once more. No menu loops or crashes, but it did render my WASD keys non functional. So it is definitively something outside TiC that is "awakening" that menu bug.

**Comment by bonii-xx** [comment]
I guess it's the NotEnoughKeys thing, there are/were some weird issues with its integration. Make sure you're on the latest 1.7 version for both mods.

**Comment by skywalker3271** [comment]
Hello. Sorry for the late reply. IRL stuff :) I've tried removing the options file, resetting keys in game, removing possible offending mods including NEK, etc. I can change the symptoms, but in each case some sort of keyboard issue persists. The only winning strat for me seems to be not messing up my key strikes. If I ever solve this. I'll let you know. Thank you so much for helping me with this :)
