### ISSUE TITLE
NBT effect ids (1.7.10)

### ISSUE THREAD

**Issue by DTM450** [SlimeKnights/TinkersConstruct#2041]
Not really an issue but I cant seem to find documentation on the nbt effect ids for tico if you could point me in the right direction that would be great

**Comment by bonii-xx** [comment]
There is none, you can look them up through the [code](https://github.com/SlimeKnights/TinkersConstruct/blob/1.7.10/src/main/java/tconstruct/tools/TinkerTools.java#L502-L536) though.
