### ISSUE TITLE
[1.9] Weird issue with certain mods, causes crash

### ISSUE THREAD

**Issue by squirrelkiller** [SlimeKnights/TinkersConstruct#2042]
So I THINK this is related to you. I might be wrong. If not PLEASE I beg you to tell me who I need to yell at. This has been... Tedious to get to the bottom of.

So here are 3 reports, that lead me here:

[crash-2016-04-25_19.02.07-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/235648/crash-2016-04-25_19.02.07-server.txt)
[crash-2016-04-25_19.06.55-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/235650/crash-2016-04-25_19.06.55-server.txt)
[crash-2016-04-25_19.55.05-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/235649/crash-2016-04-25_19.55.05-server.txt)

The exact portion that lead me here, rather than BoP (which this happens without) is found here:

```
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
```

The mods added to the instance that lead to this frustration are Evilcraft, AbyssalCraft, AbyssalCraft Integration, and Cyclops Core. With any of those + TiCon I am having this issue.

**Comment by bonii-xx** [comment]
Still BoP though. The crash info is found in every crash if TCon is present, and has nothing to do with the crash itself.

Try removing BoP and creating a new world, then it should work. Otherwise remove mods until you find the offender.
