### ISSUE TITLE
Slime island intersects with terrain in RTG

### ISSUE THREAD

**Issue by scribbler957** [SlimeKnights/TinkersConstruct#2043]
I was playing FTB Unstable for 1.8.9 with Realistic Terrain Generation and a blue slime island intersected a high mountain at around y 204. It would have been cool except the slime water escaped, ran down the mountain, turning all the snow into piles of snowballs, and spread out into a largish lake. The lag was unbelievable. Fortunately, I just started the game and it was easily abandoned. It looked like TiCon overwrote the RTG terrain so I'm posting here.

**Comment by KnightMiner** [comment]
Same issue as #3677. Fixed in 1.16, not fixing for 1.12
