### ISSUE TITLE
Item IDs

### ISSUE THREAD

**Issue by Chemiefreak2006** [SlimeKnights/TinkersConstruct#2045]
Good Evening from Germany

At the moment I'm trying to add a custom AgriCraft crop that produces Cobalt Nuggets. For this I need the Item name for Nuggets, but all I can found is "TConstruct:materials" which gives me a paper stack. 

Please can you help me?

Greetings
Chemie

**Comment by AlterAkima** [comment]
Metadata values, usually the :[number] or /[number] after the id.

**Comment by bookerthegeek** [comment]
Use mod tweaker and use "/mt hand"

**Comment by Chemiefreak2006** [comment]
Thank you

Just forgot about the Metadata....Derp...
