### ISSUE TITLE
Agrarian Skies T-con Bug

### ISSUE THREAD

**Issue by Shoganx** [SlimeKnights/TinkersConstruct#2049]
I have found that whenever I scroll to place items into the smeltery, the heat bar on the items inside the smeltery increases. Seems to work with item that can be placed into the smeltery via scrolling. I am playing on the latest AG2 build, using the version on T-con 1.8.7.build979.
Apologies if this is not in the correct area on the website.

**Comment by bonii-xx** [comment]
No, you're at the right place. :)
