### ISSUE TITLE
MC1.9 JEI-Tinkers fragging

### ISSUE THREAD

**Issue by LimeTheOn** [SlimeKnights/TinkersConstruct#2053]
Forge 1868
JEI 3.3.2.196
Tinkers 2.2.2
When  using JEI @tinkers first page gives me huge fps drops and it seems to eat up my memory according to F3 but second page or any other mods @*mod doesn't, thought I would mention it, not a huge problem but still :)
Great work on the new tinkers! Any info if iguana, steelworks or mechworks will make an appearance in 1.9? <3

**Comment by LimeTheOn** [comment]
Sorry, dupe of #2007

**Comment by Harith163** [comment]
I wish that iguana tweaks would bring back the old tinkers mechanics. That way Boni and his followers can use the new Tinkers mechanics and old schoolers can use the old mechs.

**Comment by LimeTheOn** [comment]
What do ya mean friend? 7+ modifiers were kinda broken(altho fun). If they need something to add that would be an auto caster so i dont need a redstone clock...just a lever on the auto caster.
New tables are handy af! New material traits are fun to play with altho very - how to put it - sparse? underpowered? I guess its due to 1.9 not having to much to play with yet and im sure tinkers isnt fully implemented either since i havent seen any ranged weaponry or documentation but its heading the good way i believe. Iguanas "mechanics" are implemented into tc itself. Im thinking very hard to find problems with it please enlighten me! :D
