### ISSUE TITLE
Glowballs sometimes don't update lighting in other chunks

### ISSUE THREAD

**Issue by WardBenjamin** [SlimeKnights/TinkersConstruct#2054]
Glowballs sometimes take several seconds to update lighting in chunks that are not the one they are placed in. Other times, there is a very small, but noticeable, delay.

TiCon version: 1.9-2.3.0
Forge version: 1887

**Comment by KnightMiner** [comment]
I can reproduce this with normal torches, so it might be a Forge issue. Glowballs seem to do it a bit more frequently though.
