### ISSUE TITLE
Seared Gauge Graphical Bug

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2056]
Will show liquids through the lava.
![2016-05-04_22 42 01](https://cloud.githubusercontent.com/assets/14182009/15034963/e8c0abe4-1249-11e6-8abe-f808289be398.png)
![2016-05-04_22 42 06](https://cloud.githubusercontent.com/assets/14182009/15034965/e8c25624-1249-11e6-9beb-97069bfffc8f.png)
![2016-05-04_22 41 10](https://cloud.githubusercontent.com/assets/14182009/15034964/e8c215f6-1249-11e6-8fe4-09848698c152.png)

**Comment by bonii-xx** [comment]
Optifine?

**Comment by OSM-Cait** [comment]
1.9-2.2.2
Optifine is installed

**Comment by KnightMiner** [comment]
Try reproducing it without Optifine. Optifine really messed with graphics

**Comment by ktole1999** [comment]
its just giving it a more rugged look lol
