### ISSUE TITLE
Cast Chest Problem

### ISSUE THREAD

**Issue by OSM-Cait** [SlimeKnights/TinkersConstruct#2057]
![2016-05-04_22 51 04](https://cloud.githubusercontent.com/assets/14182009/15035035/c2e34d4a-124a-11e6-9f8e-89c49b79981b.png)
You're able to put clay casts in, but not regular casts?

**Comment by KnightMiner** [comment]
I think the chest currently limits to one type, be it clay cast, gold cast, or pattern. I would assume this is intended as the main balance for the pattern chest's "unlimited" size is the fact that there are only so many patterns.

**Comment by OSM-Cait** [comment]
Oh nevermind haha
