### ISSUE TITLE
Mismatched drops 1.7.10

### ISSUE THREAD

**Issue by FerretPL** [SlimeKnights/TinkersConstruct#2063]
Every time i mine iron or sand with TiC tool it either drops nothing(80%) or drops processed one(20% e.g. glass instead of sand or ingot instead of ore). I tried removing config files and changing versions but it's still there on every 1.7.10 version

**Comment by Techokami** [comment]
The developers have abandoned 1.7.x, sadly. We're in that weird period of the mod scene where the popular version for Minecraft modding is considered obsolete, but the latest version doesn't have parity with available mods.

**Comment by bonii-xx** [comment]
Also this is definitively not tcons fault. ;o
