### ISSUE TITLE
[1.8.9] Unable to create Seared Cobblestone

### ISSUE THREAD

**Issue by Aimay** [SlimeKnights/TinkersConstruct#2067]
I've tried breaking seared stone, pouring molten seared stone on cobble, I even tried replacing the lava in a cobblestone generator works and nothing. Is it broken?
Using latest forge version and Tinkers.

**Comment by OSM-Cait** [comment]
It's happening in 1.9-2.2.2 as well.

**Comment by bonii-xx** [comment]
Yup, they don't have a recipe yet.
