### ISSUE TITLE
Game Crashes Upon Placing ANY Item in the crafting station

### ISSUE THREAD

**Issue by TCBPlays** [SlimeKnights/TinkersConstruct#2068]
hey, the game crashed whenever i place an item in the crafting station and i have to use mcedit to remove it heres the log

http://pastebin.com/sBSaC5Eh

**Comment by KnightMiner** [comment]
Update Tinkers. The version of Mantle you are using does not support the older Tinkers version

**Comment by TCBPlays** [comment]
I have the latest version of Tinkers 2 and mantle i just checked.
