### ISSUE TITLE
Graphics Issue

### ISSUE THREAD

**Issue by draconyc** [SlimeKnights/TinkersConstruct#2069]
I'm not sure what kind of glitch it is or how it is being generated, but it is purely visual and shifts/changes constantly while looking around with the mouse. I'm only running TiCon2, Mantle, and Biomes-O-Plenty.  The visual persists Without BoP in play, when it is just TiCon2 and Mantle. It persists through new world generation and shutting down minecraft entirely and restarting it.  It does not happen under vanilla 1.9 or any other mods I use in 1.8 (I don't have any other mods for 1.9 yet).
Here is a screen shot.
![image](https://cloud.githubusercontent.com/assets/19276937/15133494/dc222966-1628-11e6-8251-9a063ea3becf.png)

**Comment by TherminatorX** [comment]
Seems to be Forge, fixed by turning on VBOs. Had the same problem.
