### ISSUE TITLE
{1.9} Rapier

### ISSUE THREAD

**Issue by werff** [SlimeKnights/TinkersConstruct#2070]
Well, i must say, i love that weapon, and the fac that he doesn't pierce armor, but this damange is too high for it's speed.
Speed from 4-5 hits per second (base) and the same damange as a broadsword of the same material.

So, i'm just putting this here because i think it's simply a bug (the same one of the tools with high damange and high speed)

Also, but this is just a thing I personaly feel, could yo increase the base speed of the cleaver to 0.8??? because 0.7 makes it too slow for it's damange.

**Comment by laz2727** [comment]
I'm pretty sure balance isn't final. Gimmick weapons had 4 times sword's
DPS last time i checked.

**Comment by bonii-xx** [comment]
This is why we have alpha releases ;)
Rapiers have 50% armor piercing btw.
