### ISSUE TITLE
NetherOreGenerator explicitly checks for ChunkProviderHell

### ISSUE THREAD

**Issue by gabizou** [SlimeKnights/TinkersConstruct#2071]
From [NetherOreGenerator](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/shared/worldgen/NetherOreGenerator.java#L38), it's impossible to use such a generator on any other type of `ChunkProvider` that may exist on the server, and in Sponge's case, it's impossible to get the `NetherOreGenerator` to populate in our nether environments.

The SpongeForge related issue: https://github.com/SpongePowered/SpongeForge/issues/628

What I'm curious though is why it's an explicit check?

**Comment by bloodmc** [comment]
To fix the bug with us, instead of checking the generator, you could check the world provider
so
``` java
if (world.provider instanceof ChunkProviderHell)
```

**Comment by bonii-xx** [comment]
I used an explicit check so it doesn't randomly generate in other generations that happen to use hell too, since mods that allow to do that usually also have a way to control ores to some extent (basically keep the nether ores to the nether). It's not a hard requirement though, I can change it.

**Comment by bonii-xx** [comment]
Ok, looked at it again and what I said was actually the opposite, I guess i wanted it to generate in all instances.
Anyway, world.getChunkProvider does not return a ChunkProviderHell. The only other option would be a hardcode to dimension ID -1, which is not an option either.

**Comment by bloodmc** [comment]
@bonii-xx oops, I made a mistake in previous check. You should be able to do exactly what you want with

``` java
if (world.provider instanceof WorldProviderHell)
```

**Comment by jpiermarini** [comment]
@bonii-xx If this does get fixed will it be applied to the 1.8.9 version as well?

**Comment by bonii-xx** [comment]
Ah, that would probably work, regarding the worldprovider.

I generally don't touch 1.8.9 anymore since I see it as obsolete, all development is on 1.9 (even though Forge isn't fully there yet, but it wont take long overall). I can push a hotfix though if it's really necessary.

**Comment by jpiermarini** [comment]
I figured 1.8.9 wasn't being developed for anymore. A hotfix would be awesome though, we had just spun up our 1.8.9 server.

**Comment by bonii-xx** [comment]
Just as a reminder, this is in all 1.9.4 versions
