### ISSUE TITLE
World Crashing upon loading 1.9

### ISSUE THREAD

**Issue by AcidGames** [SlimeKnights/TinkersConstruct#2072]
Not Sure Why this is happening i've read through the code many times and cant figure out what could have gone wrong my pack was working before my latest update and i never even touched tinkers. 
http://pastebin.com/U1FtZxqf

**Comment by KnightMiner** [comment]
That is an issue with Pam's Harvestcraft, not Tinkers fault. Looks like you are using the wrong forge version for it

**Comment by AcidGames** [comment]
Ok ill take a look at that thank you i am not the best at reading reports :p

**Comment by bonii-xx** [comment]
Neither nor actually. Forge changed something regarding loot tables (for the better) but it's either currently bugged or mods need to update their loot table handling. Downgrade your forge a few versions for a temporary fix.
