### ISSUE TITLE
Pick block issue (1.9, 2.2.2)

### ISSUE THREAD

**Issue by OSM-Cait** [SlimeKnights/TinkersConstruct#2076]
![2016-05-12_22 17 44](https://cloud.githubusercontent.com/assets/14182009/15236130/9018f3f6-188f-11e6-938c-382381cc9045.png)
![2016-05-12_22 20 42](https://cloud.githubusercontent.com/assets/14182009/15236141/c7805c26-188f-11e6-99ab-485995dd8656.png)
When you hit the pick block key while looking at the Glowball block that is produced when thrown, you get a missing texture of the Glowball block.  You should either not be able to pick block them at all, or when you do, you get the actual Glowball item.

**Comment by KnightMiner** [comment]
Please update Tinkers, this is fixed in 2.3.0
