### ISSUE TITLE
Crash with Storage Drawers.

### ISSUE THREAD

**Issue by FusionLord** [SlimeKnights/TinkersConstruct#2078]
There is a crash when the Tinkers' Construct Workbench table tries to render the drawer.
Log: http://pastebin.com/xNS5aKGm
Issue on Storage Drawers: [Here](https://github.com/jaquadro/StorageDrawers/issues/285)

**Comment by KnightMiner** [comment]
Duplicate of #2010. Updating Mantle should fix it, though you may need to update Tinkers as well to be compatible with the new Mantle.
