### ISSUE TITLE
[1.8.9]-[Visual Bug] Tinkers Construct/Immersive Engineering Compatability

### ISSUE THREAD

**Issue by Voxel-Friend** [SlimeKnights/TinkersConstruct#2079]
Not sure who to report to, so I am posting this to both github issue trackers.
TCon Version:	1.8.9-2.2.1
IE Version:	0.8-26

When melting down non-Tinkers metals in the smeltery, the graphics for the molten metals are invisible. Note that in the provided screenshots that they are functionally still there. This phenomenon also occurs when pouring out of a faucet. There is no issue with the "Cooling" fade animation, the block just appears to phase into existence.

So far only IE metals have been tested, and the phenomenon has appeared using IE Uranium and IE Constantan.

![2016-05-13_17 29 20](https://cloud.githubusercontent.com/assets/12395262/15263517/63665744-1930-11e6-8f28-9eeca0e7b8b3.png)

![2016-05-13_16 54 14](https://cloud.githubusercontent.com/assets/12395262/15263416/665b6b02-192f-11e6-8717-f3fa7b25cf9e.png)

**Comment by Voxel-Friend** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1126

**Comment by C1ffisme** [comment]
Are you using Optifine? (This isn't always the problem, but removing it can help.)

**Comment by SpartanSamuel** [comment]
I'm hosting a 1.8.9 server with both of these mods installed and am receiving an error regarding the compatability between the two that I think is relevant to this issue (may be the cause, I have no idea).

http://pastebin.com/KuK7DzkU.

Hopefully this helps fix your issue.

**Comment by bonii-xx** [comment]
No that's just a harmless warning.

**Comment by Voxel-Friend** [comment]
Nope I avoid Optifine like the plague for this very reason.

On Sat, May 14, 2016 at 9:25 AM, C1ffisme <notifications@github.com> wrote:

> Are you using Optifine? (This isn't always the problem, but removing it
> can help.)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SlimeKnights/TinkersConstruct/issues/2079#issuecomment-219223081>
>



-- 
She is my life.

**Comment by malte0811** [comment]
@bonii-xx this is on IE's side, the fluid color was incorrect/missing alpha.

**Comment by Voxel-Friend** [comment]
Thanks malte0811, I'll go aheah and close this on tinkers side.
