### ISSUE TITLE
Trying to get the Dev environment for 1.7.10

### ISSUE THREAD

**Issue by x-j0nnay-x** [SlimeKnights/TinkersConstruct#2081]
Hello im trying to Get my mod to work with tinkers for my server. I want to get it so my ore will work with your mod. if you could send me a link to direct me in the correct area i would really appreciate it, i really love your mod

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/IMC
https://github.com/SlimeKnights/TinkersConstruct/wiki/Building-an-addon

**Comment by x-j0nnay-x** [comment]
Thank you i was a little confused. this is new to me

**Comment by x-j0nnay-x** [comment]
![capture](https://cloud.githubusercontent.com/assets/19367292/15272570/3fec20e8-1a32-11e6-9207-3dc233ee9ba9.PNG)

this is what i get when add those in.

**Comment by bonii-xx** [comment]
Because you're doing 1.7.10, but the instructions are for 1.9 ;o

**Comment by x-j0nnay-x** [comment]
Im trying to do it for 1.7.10, im doing this for a server as well as updating my mod. if worse comes to worse ill just wait tell 1.9 and add it on. thank you again. you really have helped i got it for 1.9 now

**Comment by bonii-xx** [comment]
For 1.7.10 you can look at other mods that use TiC, like [Iguana Tinker Tweaks](https://github.com/SlimeKnights/IguanaTweaksTConstruct)

**Comment by x-j0nnay-x** [comment]
okay thank you
