### ISSUE TITLE
[Suggestion] Liquid Hopper

### ISSUE THREAD

**Issue by BeardlessBrady** [SlimeKnights/TinkersConstruct#2082]
Just a suggestion: A liquid hopper you can add to the bottom part of a smeltry that can obviously pull out liquid metals. It could be apart of the smeltry or just a hopper under it.

**Comment by KnightMiner** [comment]
You can do that by placing a faucet on the bottom of a drain on the bottom.

**Comment by bookerthegeek** [comment]
Does that automatically drain the tank or does it still require activation?

**Comment by KnightMiner** [comment]
Right click or redstone
