### ISSUE TITLE
TC 1.8.8 - MC 1.7.10 Being able to speed up the smelt times in smeltery

### ISSUE THREAD

**Issue by MarcoV1980** [SlimeKnights/TinkersConstruct#2083]
So sorry of this has been fixed in the newer versions, since i am on the FTB modpack Infinity Evolved Skyblock, but i've noticed i was able to 'fasten' the smelt times of items.

I can smelt 64 items at the same time, when i put 64 items in there to be smelted and hover my mouse over another item in my inventory and use the mouse wheel up (the default minecraft way to put more items in) it seems to speed up the smelting process of the items currently in the smeltery.

It might be a FTB pack specific bug, if so i'm sorry, but just wanted to inform you, in case it wasn't.

It concerns tinkers for MC 1.7.10 Tinkers 1.8.8

**Comment by laz2727** [comment]
Known, fixed in 1.9.

2016-05-15 21:22 GMT+05:00 MarcoV1980 <notifications@github.com>:

**Comment by bonii-xx** [comment]
#1740
