### ISSUE TITLE
Chunk glitch with Smeltery controller.

### ISSUE THREAD

**Issue by Jilixi** [SlimeKnights/TinkersConstruct#2085]
Running a Infinity Evolved Skyblock Server that has Tinkers 1.8.8 and we have a problem with certain chunks where any container like chests and tables that can hold items clear out themselves, every item goes missing. We've been able to establish that it happens with any chunk where the smeltery controller is present by doing an "odd man out" type thing. 

The smeltery controller, drains and faucets render as Seared bricks or go invisible and have to be broken and replaced to fix the problem, the whole smeltery shows up as invalid structure even though it worked fine a few minutes before. 

Now we dont have any logs of what could be causing this so its more of a question if this has happened to anyone else or if this is a known issue?

**Comment by bonii-xx** [comment]
Are you running a clean forge server?

**Comment by Jilixi** [comment]
Nope, Running Kcauldron 1.7.10-R0.1-Snapshot

**Comment by bonii-xx** [comment]
I'd start looking there.
