### ISSUE TITLE
[1.8.9, maybe 1.9 soon] Uranium is invisible in the smeltery?

### ISSUE THREAD

**Issue by Insufficient-Charge** [SlimeKnights/TinkersConstruct#2087]
Using the latest version, 2.2.1, and I also have Immersive Engineering as the most updated version.
I'm mentioning IE because it seems like the "molten uranium" is based off of the uranium block from IE. I saw in JEI that there are two types of molten uranium. One that is greenish, I assume is based off of Ic2, and one that is...well...invisible, because of the color choices of the uranium block from IE.
I can't seem to get the green one.
Picture of molten uranium in smeltery:
![2016-05-16_16 28 54](https://cloud.githubusercontent.com/assets/13188566/15304498/510f47b8-1b83-11e6-9e8c-6fd8672cce96.png)

This can be poured into a casting basin (except you can't see it, but eventually it will start showing up) and turn into a uranium block, from IE.
Please let me know if I should contact the author of IE, or the author of Ic2.

**Comment by AlterAkima** [comment]
The IE devs are aware of this.
This has nothing to do with IC2.

**Comment by TherminatorX** [comment]
Over here:
https://github.com/BluSunrize/ImmersiveEngineering/issues/1126

Issue can be closed

**Comment by bonii-xx** [comment]
#2079
