### ISSUE TITLE
[1.9] [Idea] Shields

### ISSUE THREAD

**Issue by Dijkstra1** [SlimeKnights/TinkersConstruct#2093]
I would like to shields for TConstruct, my idea is that you would make an handle put in the middle of two casting tables, at this point the tables should render as one long one, now the player has pour metal in to both parts of the long table from two faucets at about the same time the longer different between, starting the pouring will make the shield less durable and more likely break, when a shield breaks it should not be seen in the off hand.

**Comment by Techokami** [comment]
Better idea: Use a Tool Forge to create a Shield with existing part types. A regular shield can be done with two sign plates and a tool rod. A Heavy Shield (better damage reduction, more durable, but gives a speed penalty while equipped) can be done with two large plates and a tough tool rod.

Merged casting tables is just... wat
