### ISSUE TITLE
Tools reset to default display data when other display tags are set

### ISSUE THREAD

**Issue by KnightMiner** [SlimeKnights/TinkersConstruct#2096]
Using vanilla item models, if you set just one part of a tools display tags, it simply overrides that part. This does not work with Tinkers tool models, it just overwrites the entire tag. For example if you set just GUI or hand displays, it resets all other tags that Tinkers' sets internally. Essentially, this means that the item entity displays very large on the ground and a few other cases don't act as expected (unless you manually add all unchanged tags). This currently only affects the battle sign and rapier [as shown here](http://i.imgur.com/yZ8L9yT.png), but other tools will likely be affected in the future.

**Comment by bonii-xx** [comment]
Hm, looks like something changed that it now loads the identity-matrix for missing entries instead of skipping them.
