### ISSUE TITLE
slimeknights.tconstruct.world.WorldEvents.extraSlimeSpawn(WorldEvents.java:71)

### ISSUE THREAD

**Issue by cauliflower69** [SlimeKnights/TinkersConstruct#2097]
Server crash report. (I can't say what happened as this is from last nights logs)

http://pastebin.com/UsgWgeUD

**Comment by bonii-xx** [comment]
Hard to tell with all those coremonds and CodeChickenLib/Core. Either an issue with loading world data (possible) or an issue with one of the coremods messing with multithreading (more likely).

**Comment by cauliflower69** [comment]
Thanks for looking
