### ISSUE TITLE
Drying rack completely gone??

### ISSUE THREAD

**Issue by realflow100** [SlimeKnights/TinkersConstruct#2098]
Can't craft it. no recipe. not even any textures or models for it in the jar file!
Where did the drying rack go for 1.8.9 ??

**Comment by LovelyFlare** [comment]
Update TiC and Mantle to latest version...
http://minecraft.curseforge.com/projects/tinkers-construct
http://minecraft.curseforge.com/projects/mantle

Also read the [FAQ](https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ) in the future
