### ISSUE TITLE
BlueSlime Loot Table

### ISSUE THREAD

**Issue by MrSapient** [SlimeKnights/TinkersConstruct#2100]
http://pastebin.com/RdsmtsZT

TConstruct-1.9-2.3.0.jar
Forge 12.16.1.1907
Mantle 0.10.0

Only in server console not in client.

**Comment by KnightMiner** [comment]
Forge changed some things in loot tables to allow modders to more easily modify vanilla ones. That Boeing said, this error will be fixed in the next release. See 320d37a.
