### ISSUE TITLE
Materials and You Issues (1.9, 2.3.0)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2102]
Opening the book in other languages will cause an additional arrow to appear
![2016-05-20_22 26 16](https://cloud.githubusercontent.com/assets/14182009/15445909/1c8a041a-1eda-11e6-9056-4d218fcf23d6.png)

(With modpack)
![2016-05-20_22 22 12](https://cloud.githubusercontent.com/assets/14182009/15445893/69b7734a-1ed9-11e6-8518-0a0362967fb1.png)

**Comment by bonii-xx** [comment]
Probably also https://github.com/SlimeKnights/Mantle/commit/f62cb735976a50bd131ebb06c6a6e8b121be0d83
