### ISSUE TITLE
I'm crashing and I have no idea why

### ISSUE THREAD

**Issue by KRDarnell** [SlimeKnights/TinkersConstruct#2105]
My game crashes during the forge setup and I don't know why. Is there anyone who can help me resolve this issue? I've tried with both of the versions available of both mantle and Tinkers Construct and I get the same result.

Here is the link to the pastebin: http://pastebin.com/zGbnj2fh

**Comment by LovelyFlare** [comment]
Why are you trying to load TiC in 1.9.4?  TiC is a 1.9 mod (as well as mantle)

**Comment by KRDarnell** [comment]
Is the 2.3.0 version not made for 1.9.4, because I used that version as well? I wasn't aware that 1.9 and 1.9.4 mods were not compatible.

**Comment by KRDarnell** [comment]
Just so people are aware the latest version of mantle works for me, just not the latest version of Tinkers Construct.

**Comment by LovelyFlare** [comment]
They clearly say they are for 1.9, just because Mantle loads in 1.9.4, doesn't mean it is meant for it.

**Comment by KRDarnell** [comment]
Ah, I see. Thank you for enlightening me. I guess I'll wait for the release for 1.9.4.
