### ISSUE TITLE
Stencil Table - Tesselating block model crash

### ISSUE THREAD

**Issue by jlbrewer** [SlimeKnights/TinkersConstruct#2109]
Hardware: Core i3, 4GB RAM, integrated laptop graphics, yeah I know it sucks for Minecraft.

OS: Win 7, Java 8.

Minecraft: 1.9 with Jaded's Roulette alpha pack (minus questing mods and Journey Map, plus Quark, Redstone Paste, Chisel and Chisels + Bits). Graphics set to Fast.

New world, nothing built but crafting station, stencil table and tool forge. Game crashed with error shown in attached log while I was opening the stencil table to load patterns in. On reloading the world, crashed again immediately with the same error.

[crash-2016-05-23_10.43.00-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/277721/crash-2016-05-23_10.43.00-client.txt)

**Comment by TherminatorX** [comment]
Dupe issue. Please close this one.

You can edit your original issue if you think additional info is needed.

**Comment by jlbrewer** [comment]
Sorry, Github gave me a server error when I posted and I didn't see the original in the list.
