### ISSUE TITLE
Blocks Missing!! HELP!

### ISSUE THREAD

**Issue by WAC02mc** [SlimeKnights/TinkersConstruct#2110]
I cannot find the Stencil Tables, or any tables that makes the tools. I have looked through configs and couldn't find anything. Please help!

**Comment by TherminatorX** [comment]
Use the self-crashing feature (holding F3+C for 6 seconds) to get a crashlog, then put that on Pastebin.
Link the paste here.

**Comment by WAC02mc** [comment]
http://pastebin.com/xZ33SdiA
