### ISSUE TITLE
1.9 texture errors

### ISSUE THREAD

**Issue by tyler489** [SlimeKnights/TinkersConstruct#2111]
placing a chest in the casting basin results in the purple and black missing texture error nothing major

**Comment by LovelyFlare** [comment]
Duplicate of #2066

**Comment by bonii-xx** [comment]
Nope, not a duplicate. Simply mojang not having models for their chests. Blame mojang for not using their own system. :P

**Comment by LovelyFlare** [comment]
Well it does happen on item racks as well since they use the same rendering .~.

**Comment by KnightMiner** [comment]
Its not a duplicate, but it is related, as both "builtin/entity" and "tintindex" require data from outside the model to work.
