### ISSUE TITLE
Broadsword Balance (1.9, 2.3.1)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2113]
The broadsword right now is the most useless tool.  The AoE does very little damage (about 1/2 or 1 heart maybe) and you cannot run to use it (meaning you cannot charge-run the enemy for more hearts and apply the AoE at the same time).  Also it does less damage than the longsword anyway
![2016-05-27_01 03 02](https://cloud.githubusercontent.com/assets/14182009/15623429/629a5bbe-2441-11e6-840c-a082c6b35166.png)
![2016-05-27_01 03 04](https://cloud.githubusercontent.com/assets/14182009/15623430/62a0ca6c-2441-11e6-8386-f28ddd28fd71.png)

**Comment by KnightMiner** [comment]
It can use a shield without being rather slow though.

**Comment by LovelyFlare** [comment]
True... but even so... I'm trying to compare them without the shield

**Comment by KnightMiner** [comment]
Yeah, it's a bit more useful when comparing to the axes special ability. In Tinkers it's a bit more useful for its midrange stats

**Comment by LovelyFlare** [comment]
Get on IRC .~.

**Comment by LovelyFlare** [comment]
Well the thing is, even if you have a maxed out broadsword, it still will do the same low AoE damage.

**Comment by AlterAkima** [comment]
The sweep atack does half a heart of damage even with vanilla swords.

**Comment by LovelyFlare** [comment]
@AlterAkima That's not the point, the point is the ability isn't worth it when you can just use a longsword instead (with the jumping and all).

**Comment by bonii-xx** [comment]
This is highly subjective. Both have their pros and cons: The broadsword is much more versatile and also faster, they are pretty even in terms of DPS on an unmodified weapon.
