### ISSUE TITLE
Equipment Problems (1.9, 2.3.1)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2114]
When other mobs try to use Tinkers' weapons, they will not apply the effects (whether attacking the player or another entity).

Below is a zombie holding a Frying Pan with Fiery on it.
![2016-05-27_00 31 16](https://cloud.githubusercontent.com/assets/14182009/15623497/3b5e98ac-2442-11e6-8d91-286010cc7dd5.png)

**Comment by TherminatorX** [comment]
It maaaaaaay be the fact that you have Fire Resistance on?

**Comment by LovelyFlare** [comment]
Fire resistance just makes sure you don't take damage... it doesn't prevent you from being set on fire (I've been forced through enough "gapple" pvp to know this)

Anyway same thing:
![2016-05-28_01 59 26](https://cloud.githubusercontent.com/assets/14182009/15625537/dac87cc0-2477-11e6-8930-6a84fb2da72e.png)

**Comment by LovelyFlare** [comment]
Double checked...
![2016-05-28_02 04 47](https://cloud.githubusercontent.com/assets/14182009/15625561/96670028-2478-11e6-87dd-214494a9321d.png)

**Comment by bonii-xx** [comment]
Zombies don't actually attack with items. They just deal damage according to their attribute and check if the item has a fire aspect enchantment.
