### ISSUE TITLE
Materials and You Graphical Bug (1.9, 2.3.1)

### ISSUE THREAD

**Issue by SweetSugarSugar** [SlimeKnights/TinkersConstruct#2115]
;~;
![2016-05-27_00 42 39](https://cloud.githubusercontent.com/assets/14182009/15623532/bbd2c21a-2442-11e6-98a5-481bb165173f.png)

No OptiFine this time ^~^;

**Comment by bonii-xx** [comment]
Yes I know, this is due to how these tooltips are rendered, hard to fix.

**Comment by bonii-xx** [comment]
It's actually fixed!
