### ISSUE TITLE
Knockback Caps to 99 (1.9, 2.3.1)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2116]
It is impossible to get to 99 without additional modifiers, but it should be capped to something... like 10.
![2016-05-27_00 23 42](https://cloud.githubusercontent.com/assets/14182009/15623544/e099ca44-2442-11e6-9153-b4ea5a947b0a.png)

**Comment by TherminatorX** [comment]
mDiyo was always a fan of ridiculous knockback, I say keep it :P

**Comment by bonii-xx** [comment]
Working as intended ;o
