### ISSUE TITLE
Jerky Issue (1.9, 2.3.1)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2117]
You're able to eat jerky even when your hunger bar is full.
![2016-05-27_22 19 15](https://cloud.githubusercontent.com/assets/14182009/15624588/351302a0-2459-11e6-88e6-81a9ddd4dc19.png)

**Comment by bonii-xx** [comment]
Side effect of food with effects that needs to be eatable even at full saturation. MC doesn't support that on a per-metadata-basis.

**Comment by LovelyFlare** [comment]
Jerky has effects?

**Comment by KnightMiner** [comment]
No, but the slimeballs and slime drops do, and jerky and slimeballs use the same item (just different meta).

**Comment by ThatGamerBlue** [comment]
Just change the jerky to a different item ID?
