### ISSUE TITLE
[1.9] Server Crash using steel-bronze lumber axe

### ISSUE THREAD

**Issue by DragonMorkeleb** [SlimeKnights/TinkersConstruct#2119]
Hi.

We are running a server on our local network that uses tinkers construct 2.3.1 for minecraft 1.9 using forge 1.9-12.16.1.1923. It ran fine at first but one of us then used a steel-bronze lumber axe on a Chicken, which caused the server to crash.
Since then it continues to crash as soon as anyone logs in.

I have attached the crash log.

Please let me know on what you can tell me on this issue, and if there is an easy fix since currently our world is not usable anymore.

Thanks!

[crash-2016-05-28_18.13.39-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/287799/crash-2016-05-28_18.13.39-server.txt)

**Comment by laz2727** [comment]
Looks like a simple client-server mixup.

**Comment by DragonMorkeleb** [comment]
Yes, it tries to run code that is meant for the client on the server.

Line 101 here:
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/common/CommonProxy.java#L101

**Comment by bonii-xx** [comment]
http://minecraft.curseforge.com/projects/tinkers-construct/files/2303662

**Comment by DragonMorkeleb** [comment]
Thanx for the hotfix, I will try it right away :)
