### ISSUE TITLE
Fiery modifier nullifies base sword damage

### ISSUE THREAD

**Issue by xenanthropy** [SlimeKnights/TinkersConstruct#2120]
Tested with multiple broadswords: Sword does normal damage, but when any tier of fiery is added, it nullifies all of the actual sword's damage, and only does the fire damage specified. 
IE: Manyullen broadsword has about 10.5 damage base, but when you add 1 tier of fiery to it, it still says that it does 10.5 plus the 1.5 fire damage, but when you actually attack anything, it only does the 1.5 or whatever fire damage and nothing else, even if you continue to swing.

**Comment by xenanthropy** [comment]
To try to add information: When adding the fiery "modifier" to a sword (through the method of adding blaze powder to a tool in the tool station), the sword no longer does it's own damage plus the fire damage on swing, it only does the fire damage (plus the tick damage of fire, of course) on swing. It sets the mob on fire and does the normal tick damage that being on fire does, but when you swing a sword at an enemy, when there is the fiery modifier on the sword, it no longer does swordDamage + fireDamage, just fireDamage. so with level 1 fiery on a sword, when you swing and hit an enemy, it only does 1.5 damage per swing, instead of swordDamage + 1.5 on swing. I can make a video showing the effects, if needed.

**Comment by bonii-xx** [comment]
I need your MC and TiC versions.

**Comment by xenanthropy** [comment]
Lol oh yeah, duh. Mantle is 1.9-0.10.1 and TiC is 1.9-2.3.1

**Comment by bonii-xx** [comment]
Did you test this on a server or in local singleplayer? How did you test the damage done?

**Comment by ikarosixteen** [comment]
I have have the same issue. When you apply it to a weapon, the bast damage = 2 instead of the damage it had before you added it.

**Comment by bonii-xx** [comment]
Again, did you test this on a server or in local singleplayer.

**Comment by ikarosixteen** [comment]
yes in both

**Comment by bonii-xx** [comment]
And what did you hit to test it?

**Comment by ikarosixteen** [comment]
all the mobs :/

**Comment by ikarosixteen** [comment]
like zombies for an example

**Comment by bonii-xx** [comment]
Well, I can't reproduce it locally. Hitting a horse with a slime sword with 1 full fiery modifier deals 5.4666... damage, as it should. On a server you'll probably only get the fire damage because of #2119 (and some errors in the log)

**Comment by bonii-xx** [comment]
I'm relatively confident that the actual cause for this is #2119, which needs a hotfix anyway. Try to reproduce in the hotfixed version then.

**Comment by bonii-xx** [comment]
http://minecraft.curseforge.com/projects/tinkers-construct/files/2303662

**Comment by ikarosixteen** [comment]
I used a Manyullyn long sword with sharp and fiery on it to test.
Thank you for fixing it <3

**Comment by bonii-xx** [comment]
So does it work in 2.3.1a now?

**Comment by ikarosixteen** [comment]
yes <3
