### ISSUE TITLE
MAJOR BUG (1.9 and 1.9.4) : Catched unhandled exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by Hypsellis** [SlimeKnights/TinkersConstruct#2121]
IMPORTANT : THIS BUG IS GENERAL TO MANY MODS OF MINECRAFT 1.9 and 1.9.4

A strange bug happens when a tile entity is destroyed, Almost all the time an exception is thrown when the bug happens : Catched unhandled exception  [name of the tile entity] java.lang.NullPointerException 
For some particular blocks, Minecraft totally freezes and finished to crash with the error code -805306369 without any crash report. Here is the list of all the blocks wich are confirmed to provocate Minecraft to freeze and crashs with this error.

- Building Brick : all the glass, ice and packed ice blocks
- Deep Resonance : resonant crystal
- Biomes O Plenty : celestial crystal
- Botania : mana prism
- Blood Arsenal : blood stained glass block and pane
- Evilcraft : darktank
- EnderIO : killer joe, zombie generator, all the fused quartz glasses
- Random Things : lapis lamp, quartz lamp, rainbow lamp, biome glass, spectre block, fluid display

All these blocks follow the same error, only the name of the tile entity between the [ ] changes. Here is an example of how the error happens. The example is made with the resonant crystal of deep resonance. This is a full log and contains the launching of minecraft and the loading of a world, the moment where I brick the block and the bug happens is the moment where the exception [class com.hea3ven.buildingbricks.core.tileentity.TileMaterial] java.lang.NullPointerException is thrown : http://pastebin.com/KhwV1WKg

-------------------------------------------------------------------------------------------------------------------------------

Moreover some tile entities wich has brokner provocates Minecraft to totally crash with a crash report. Here is the list of all the block concerned and their crash report

- EvilCraft : box of eternal closure http://pastebin.com/JzRYf5Ex
- Cooking for block heads : fridge and oven http://pastebin.com/vcmx49qn http://pastebin.com/6zd4qq5w
- Storage Drawers : framing table http://pastebin.com/3077W3Wz

-------------------------------------------------------------------------------------------------------------------------------

I let you know that all the tests possible has already been made before I create this general issue and post it. I already tried to :
- Test the mod one by one only by installing them and forge without any other mods
- Change of Forge Version
- Change between the 1.9 and 1.9.4 version
- Change of mod version
- Play without optifine and any shaders
- Switch between the creative and survival mode
Nothing of all that change anything, the bug still happens in the same way for the same blocks listed at the top. 

-------------------------------------------------------------------------------------------------------------------------------

I precise that almost all the mods in Minecraft 1.9.4 and 1.9 are touched by this bug, because even if they don't provocate Minecraft to freeze or crash, almost always at each time a tile entity is broken, the exception Catched unhandled exception  [name of the tile entity] java.lang.NullPointerException is thrown.
I precise too that the list of all the tile entities listed at the top can be incomplete. I want you know that I tried to break block by block all the blocks of almost all the most popular mods on 1.9.4 and 1.9, so for summarizing something like 50 mods with more than 2000 blocks. So it's possible that I missed some blocks.
It's why I send this issue to all the mods even if no ones of their block are concerned by the bug.
I invite all the mod developpers to try by themselves to break all the tile entities of their mod for seeing they provocate the throwing of the exception, and maybe causes Minecraft to freeze.

**Comment by LovelyFlare** [comment]
That's great, but it didn't have to be in caps ._.

**Comment by Hypsellis** [comment]
Yeah sorry, I can modify it. ;)

**Comment by KnightMiner** [comment]
Tinkers Construct is no where in any of those crash logs, so tihis crash in no way belongs on this tracker. If the issue really affects Tinkers, post the crash log that uses Tinkers and **no others**

----

On to specific details of your error, the fact that so many mods with tile entity is causing the error makes me believe it is not every mod's fault, rather something is modifying vanilla classes and grabbing the blockstate after it is deleted (or deleting it before it can be grabbed), so even vanilla tile entities are likely affected. I personally cannot reproduce this with any of those mod I have installed, so I doubt it is a Forge issue. Find the mod that is causing it and report it to that tracker and no others.

**Comment by Hypsellis** [comment]
I ask me too if it's not an error causes by Minecraft itself, I get this error when I break an ender portal frame with an eye inside, and that in vanilla without forge and any mods.

**Comment by border999** [comment]
dude, report this to Lex Manos over at forge if this is such a massive issue that affects so many mods.
