### ISSUE TITLE
version for MC 1.9.4

### ISSUE THREAD

**Issue by Kubikx** [SlimeKnights/TinkersConstruct#2122]
When you planing 1.9.4 version?
Why you think 1.9 version of TC is incompatible with 1.9.4 MC?

Thanks in advace for answer.

**Comment by bonii-xx** [comment]
When It's done.
I don't think it is, I know.

**Comment by Kubikx** [comment]
Version 1.9 is unplayable for many peoples including me because of bug in pathfinder.
I found no API changes changelog, only http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.9.4-12.17.0.1936-1.9.4/forge-1.9.4-12.17.0.1936-1.9.4-changelog.txt
The bug in 1.9 drops my average FPS to 3, average of 0´s and 60´s.
Sorry for the question.

**Comment by bonii-xx** [comment]
This might surprise you, but changes in Minecraft are not changes in Forge itself.

**Comment by Kubikx** [comment]
May you be more specific?
Only notable change( that can can affect compatibility with TC ) I see in changelog of Minecraft are
`New armor attribute: generic.armorToughness`
`Shields no longer take damage when blocking weak attacks (less than 3 (Heart.svgHalf Heart.svg) damage).`
This are only about the damage values, so you still must update all values for 1.9, because of shields and other offhand items.

Sorry but I still can not understand what is the problem.

Thanks in advance for the answer.

**Comment by GirafiStudios** [comment]
There is not that many changes in MINECRAFT itself, but there is a good amount of changes in FORGE, as Boni states in his previous message.

**Comment by Kubikx** [comment]
from build.properties
`mod_version=2.3.1
minecraft_version=1.9
forge_version=12.16.1.1907
mappings=snapshot_20160418

mantle_version=0.10.1.jenkins140
jei_version=3.3.+`

forge changelog from 12.16.1.1907 to now http://pastebin.com/jrJkTn89

what exactly is compatibility problem?
`Build 1.9.4-12.17.0.1909-1.9.4:
	LexManos: Update example mod for new mappings.`
I have no idea where the example mod is, but the rest are mostly fixes of bugs.
