### ISSUE TITLE
Tcon TConstruct-1.9-2.3.1a.jar not loading in MC1.9.4

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [SlimeKnights/TinkersConstruct#2123]
attempting to load Tcon in minecraft 1.9.4 fails.

quote from Tcon curseforge: 

> Q: _Anything regarding old Minecraft versions_

A: Active development always focuses on the **current** version of Minecraft. There will be no backports to older/previous versions.

**Comment by AlterAkima** [comment]
It's not intended to load on 1.9.4, not yet.

**Comment by GirafiStudios** [comment]
Forge haven't been out for 1.9.4 for that long, calm down..

**Comment by Rumpelstiltskinny** [comment]
...and that is focusing on the **CURRENT** version of minecraft, how?

calm down?   CALM DOWN?!?!   Now who is being rude?

**Comment by Rumpelstiltskinny** [comment]
...yeah, I don't see either of you @ https://github.com/orgs/SlimeKnights/people so I'll wait to hear from a Tcon dev, thanks all the same.

**Comment by AlterAkima** [comment]
https://github.com/SlimeKnights/TinkersConstruct/commit/2c4df189e85f031f420c955c2e4fff67b299c738

**Comment by GirafiStudios** [comment]
Boni already responded yesterday on the exact same question on https://github.com/SlimeKnights/TinkersConstruct/issues/2122

**Comment by KnightMiner** [comment]
boni will release a 1.9.4 build when it is ready, be patient until then. Remember, this mod is written in spare time of the developers, they are not making money from it and you are not paying for it, so don't act like you are entitled to the next version

**Comment by bonii-xx** [comment]
There's a reason the 1.9 version tells you it doesn't run in 1.9.4. ;P
