### ISSUE TITLE
liquefied slime strange behaviour (1.9.4)

### ISSUE THREAD

**Issue by Hypsellis** [SlimeKnights/TinkersConstruct#2124]
The liquefied slime (blue or purple) behaves it in very strange way in the 1.9.4. I can walk on it like if it was a solid blocks, and when I remove the source of a slime cascade, the cascade still stays here (not sure if I'm clear).
I didn't try the other Tinkers Construct liquids, but it could be the same for all the liquids.

**Comment by KnightMiner** [comment]
The issue with colliding appears to be a Forge issue as it affects any liquid that extends Forge's fluid class (such as Forestry). I reported it at MinecraftForge/MinecraftForge#2932.

The issue with the slowness sounds like the really slow speed at which slime water flows, which is intentional.

**Comment by KnightMiner** [comment]
Collision is fixed in the latest Forge build.
