### ISSUE TITLE
Power Tool in Power Suits and TinkersConstruct 1.7.10 issue

### ISSUE THREAD

**Issue by seijinshu** [SlimeKnights/TinkersConstruct#2126]
The power tool no longer has proper mining attributes (the overclocking upgrade on the mining modules don't work) and mines slowly. I've pin-pointed this down to Tinkers Construct version 1.7.10-1.8.8. It worked previously with an older version (can not find which one though. It was the last version available on the original forum thread).
I've also pin-pointed the cause. It is due to the tool re-balancing.

Help would be appreciated!

I do know 1.7.10 isn't supported anymore. But many mods I rely on are only 1.7.10 and some have no plans for 1.8+

Is there a config option or something? I see nothing in config files.

This is a TiC issue. Mantle doesn't do this, nor do any other mods I have loaded.

**Comment by bonii-xx** [comment]
Sounds more like Iguana Tinker Tweaks.

**Comment by seijinshu** [comment]
That isn't part of my pack.

**Comment by seijinshu** [comment]
I have only one add-on, and it is mechworks

**Comment by bonii-xx** [comment]
>I've also pin-pointed the cause. It is due to the tool re-balancing.
TiC doesn't have any of that. There was a config option that set all the vanilla tools to 1 durability (disabled by default), but that's it.

**Comment by seijinshu** [comment]
I guess idk what TiC is doing then.

**Comment by seijinshu** [comment]
I should mention that I tried enabling/disabling that, and nothing happened. I am already planning to push out an update for my pack to remove it, as I personally don't use TiC, my server host doesn't, we have no use for it when we have power suits and projecte. I still want to fix this. The newest version not showing this bug us 1.8.4a
