### ISSUE TITLE
Faucet has no texture [1.9.4]

### ISSUE THREAD

**Issue by eriico39hi** [SlimeKnights/TinkersConstruct#2127]
Exactly as title says. Faucet has no texture in inventory. Still has texture in block form once placed.

**Comment by JCMais** [comment]
To add to that.

The gold ingot cast has no texture when placed in the casting table. I didn't tested any other casting, so idk if it's for every one of them.

**Comment by KnightMiner** [comment]
I cannot reproduce the issue with the cast being invisible, though that would be a different issue as the cause of the faucets being invisible does not apply to casts.

**Comment by JCMais** [comment]
@KnightMiner I will create a new issue when I get the time to test it again.
Could have been optifine/shaders.
