### ISSUE TITLE
(feature suggestion) support for new ores

### ISSUE THREAD

**Issue by Hypsellis** [SlimeKnights/TinkersConstruct#2128]
I ask if it's possible to add a support for some ores.
- The tin, zinc, chrome, nickel, platinium, iridium, invar, brass, refined iron, cupronickel, signalum, lumium, titanium, tungsten, tungstensteel and avanced alloy from TechReborn and Substratum.
- The electrical steel, energetic alloy, vibrant alloy, redstone alloy, conductive iron, pulsating iron, dark steel and soularium of EnderIO.
- The abyssalnite, corialium, dreadium and ethaxium from abyssalcraft. 
- The mythrilium and armandium of Simple Ores.
- The manasteel, terrasteel, elementium and gaia spirit ore from Botania.
- The psimetal, ebony and invory from Psi.
- The spectre ore of Random Things.

**Comment by AlterAkima** [comment]
Ask the devs of those mods to add the materials, you will probably get a 'no' from some of them.

**Comment by C1ffisme** [comment]
> It's just a suggestion.

Yeah, and suggestions get locked...
