### ISSUE TITLE
[1.9.4] java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Xiaminou** [SlimeKnights/TinkersConstruct#2129]
Crash Report: http://pastebin.com/rPMvfgcm

**Comment by bonii-xx** [comment]
Some other mod is doing a dumb and putting null entries into the oredict.

**Comment by Xiaminou** [comment]
does it say which one?

**Comment by bonii-xx** [comment]
It's XU2

**Comment by Xiaminou** [comment]
alright, should I post the crash report over there?

**Comment by bonii-xx** [comment]
No need, he already fixed it.
