### ISSUE TITLE
TConstruct-1.9.4-2.3.1.jenkins229 client crash on startup in modpack

### ISSUE THREAD

**Issue by IchigoGames** [SlimeKnights/TinkersConstruct#2130]
here is the fml-client-latest and crash report 

[crash-2016-06-01_12.48.30-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/294028/crash-2016-06-01_12.48.30-client.txt)
[fml-client-latest.txt](https://github.com/SlimeKnights/TinkersConstruct/files/294031/fml-client-latest.txt)

**Comment by IchigoGames** [comment]
oh nvm nvm turns out extrautils2-1.9.4-alpha-1.0.0 makes everthing crash

**Comment by Hypsellis** [comment]
Yeah I get the same crash, it's caused by extrautils. I don't know wich one crashs relative to the other.

**Comment by GirafiStudios** [comment]
Update to Extra Utilities v. 1.0.0a
