### ISSUE TITLE
[Suggestion] Add Material Trait Descriptions in Materials & You

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#2133]
If it hasn't been brought up already, please add descriptions of what each material trait does in the materials and you book.

**Comment by KnightMiner** [comment]
It exists as a tooltip

**Comment by MokahTGS** [comment]
??  I'll take a look tonight, but I didn't see it...I must be blind.

**Comment by bonii-xx** [comment]
Yes, what's missing is a tooltip indication, not the actual descriptions.

**Comment by MokahTGS** [comment]
So after playing around more with the 1.9.4 version I would definitely want better descriptions of what  the materials actually do.  Some of the materials have good info, other do not.  I don't mind the humor and encourage you to keep it up, but more info is needed for players.  For example the Slimy trait only says that it's slimy and will wash off.  What does that mean??  It certainly doesn't mean that slimy tools will spawn a small slime randomly on use.  Players should have that info.

The best place for this is not the tooltip...it's in the book.

**Comment by Deshiba** [comment]
This seems to be fixed in the 1.10 version, it seems fine on TiCon 2.6.1, do you agree MokahTGS?

**Comment by bonii-xx** [comment]
It has always been fixed. It's open because some indicator or instructions are still missing.

**Comment by KnightMiner** [comment]
There are plans in 1.16 to add an encyclopedia description of traits and modifiers with exact numbers. 1.12 will not get any more changes, so I suggest consulting the tutorials for exact details.

**Comment by MokahTGS** [comment]
Holy Necro Batman!  Glad to see this getting looked at for 1.16...I of course have long since moved on from 1.12, since I made this request in 2016. :)
