### ISSUE TITLE
Rotated parts of tool models cause Z-fighting with modifiers

### ISSUE THREAD

**Issue by KnightMiner** [SlimeKnights/TinkersConstruct#2135]
On tool parts that are rotated, the texture will Z-fight with the modifier texture (except in the inventory it seems), which currently only affects shurikens, as shown [here](http://i.imgur.com/n7NiUVZ.png) and [here](http://i.imgur.com/oqAiuqg.png).

Oddly, when placed on an item rack, only the 90 and 270 degree rotated ones Z-fight though.

**Comment by LovelyFlare** [comment]
2099?

**Comment by KnightMiner** [comment]
Possibly a regression of that, it now affects more than just running

**Comment by bonii-xx** [comment]
It's simply what happens when you render multiple quads over each other at the same position that are not absolutely perfectly aligned (through rotation in this case). It works with layers because the front quads are perfectly aligned there. Hard to fix, not perfectly fixable and a lot of work.
