### ISSUE TITLE
Cobwebs & Tinkers' Swords

### ISSUE THREAD

**Issue by Mohron** [SlimeKnights/TinkersConstruct#2137]
Version: TConstruct-1.9-2.3.1a.jar

Tinkers' Constuct Swords do not allow you to collect cobwebs like vanilla and most other modded swords.  I personally only run around with Tinkers' tools/weapons on me which leaves me unable to harvest or break cobwebs in a reasonable amount of time. Personally I don't care if I get the drop or not, perhaps Tinkers' swords are too sharp to leave any viable string, but a significant increase of breaking speed would be greatly appreciated.

**Comment by bonii-xx** [comment]
Silktouch or shears are the magical words you're missing.

**Comment by TherminatorX** [comment]
I believe this was just meant as breaking the cobwebs fast, as most swords do, dropping string. Currently, it takes them a long time to be broken with the TiC swords.

**Comment by Mohron** [comment]
Yes, that was the intent, to at least quickly destroy the cobwebs even if they don't drop string like vanilla swords. Was just hoping they would share this behavior with the rest of the swords of Minecraft.

**Comment by bonii-xx** [comment]
Nope, TiC swords break cobwebs fast perfectly fine.

**Comment by laz2727** [comment]
Can confirm.

**Comment by TheOldOne822** [comment]
I have tested with only Tinkers Construct 2.3.3a (latest on curse) installed and the Broad Sword will not break webs. I have tested the jenkins build and it does break webs.
