### ISSUE TITLE
194 found bugs

### ISSUE THREAD

**Issue by 5kedone** [SlimeKnights/TinkersConstruct#2139]
1 fosset is missing item texture.

2 tinkers crafting table next to double chest messes up your crafting inventory I can provide pictures to show what I mean if needed.

3. If pattern chest is exploded by a creeper (not tested other ways) it drops patterns but also keeps them in pattern chest (dupe bug) 

That's some I have found so far will post as I find them

**Comment by LovelyFlare** [comment]
1. Already reported in #2127

2. Yes, some screenshots would be very helpful

  1. Reproduced with TNT, yeah that's a problem O.o

If you find new issues, just open up a new one but please make sure it's not already reported

**Comment by laz2727** [comment]
2) Will post a video in a sec

**Comment by laz2727** [comment]
https://youtu.be/c5grFSrDVi4

**Comment by bonii-xx** [comment]
Chest thing is a forge bug. Happens only if you open the crafting station with a single chest and then place the 2nd chest. If both are present from the start it works.

**Comment by 5kedone** [comment]
Thanks for info on chest bug I'm guessing there aware of issue
