### ISSUE TITLE
TiC Dependencies (1.9.4, 2.3.1.jenkins229)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2140]
I was loading the new 1.9.4 version and forgot Mantle when I came across this.
Tinkers' Construct still asks for outdated dependencies when loading.
![2016-06-03_12 40 45](https://cloud.githubusercontent.com/assets/14182009/15786191/64defba8-2989-11e6-89fc-e5a5a66832ed.png)

**Comment by bonii-xx** [comment]
Not really worth to fix since the next update will most likely require new deps anyway, but meh.
