### ISSUE TITLE
1.9.4 issue

### ISSUE THREAD

**Issue by RedBullSlurpie** [SlimeKnights/TinkersConstruct#2142]
Some have told me this issue is with Vanilla and not modded, but i just want to submit it to make sure.. So upon sleeping in a bed, with a Tinker's Construct Pickaxe in my hand, After day has come, i can't leave the bed, it will put me out of the bed, but leave the "Leave bed" button there, and chat, I can't move, or leave bed, only way to fix is to ALT F4 and re-open it. Now i've only noticed this issue when holding a Tinker's Construct pickaxe, it doesn't seem to happen with any other Tinker's tools, or anything else, that i've noticied, only a Tinkers Construct custom Pickaxe. Let me know if you need any other info, or if this is infact a vanilla bug. Thanks.

**Comment by laz2727** [comment]
Can't reproduce.

**Comment by LovelyFlare** [comment]
This is definitely not a TiC issue... or even possibly a vanilla issue.

**Comment by bonii-xx** [comment]
Not TiC.
