### ISSUE TITLE
[1.9.4] Materials and you crash

### ISSUE THREAD

**Issue by imdutch21** [SlimeKnights/TinkersConstruct#2143]
While scrolling to the materials and you book I crashed when I came to a certain page, I am unable to reproduce it, but I thought you would still like the crash report. http://pastebin.com/XP1f3ATL

**Comment by bonii-xx** [comment]
Should be prevented by https://github.com/SlimeKnights/Mantle/commit/7e2b6b046495ead163b6f6d3fbde5c997a9c18ca
