### ISSUE TITLE
1.9.4 Villages not spawning smeltery

### ISSUE THREAD

**Issue by Lazarix** [SlimeKnights/TinkersConstruct#2146]
I've created a new world and visited three seperate villages. None of them had any Smeltery components. No seared bricks, or anything.
Is this by design or could it be a bug?

**Comment by KnightMiner** [comment]
There currently is no village generation in Tinkers Construct 2. It might make a comeback later.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. Not sure if we will bring this back in 1.18 or not.
