### ISSUE TITLE
Unable to create "tier 2" tool parts out of paper

### ISSUE THREAD

**Issue by SlackerDao** [SlimeKnights/TinkersConstruct#2147]
Using version 1.9.4-2.3.1.jenkins229, I find that I can can create any of the basic tool parts (shovel, axe, pick head, basic tool rod, etc) out of paper, but none of the parts that require a tool forge to assemble (tested on tough tool rod, large plate, large sword, tough binding).

Wasn't sure if this was a bug, or undocumented design decision, but wanted to pass it along either way.

**Comment by bonii-xx** [comment]
Use more paper. 1 Paper is worth 1/4 material.
