### ISSUE TITLE
(1.9.4) Crafting Slimy Magma Mud Crashes Client

### ISSUE THREAD

**Issue by drewbit** [SlimeKnights/TinkersConstruct#2150]
Filling in the recipe in a crafting station causes a straight crash, here's a log:

http://paste.ee/p/5N8sW

**Comment by bonii-xx** [comment]
There's so many things going wrong in your log it's not even fun anymore. Anyway, not TiCs fault, some other mod messes up/registers invalid things. Reopen if you can reproduce with only TiC and Mantle.
