### ISSUE TITLE
[1.9.4] No aluminium?

### ISSUE THREAD

**Issue by Xiaminou** [SlimeKnights/TinkersConstruct#2151]
I tried smelting Aluminium from Substratum to make Aluminum brass but it doesn't recognize it, and it seems that there is no Molten Aluminum.
Is it not recognizing Substratum Aluminum or is Aluminum not implemented in 1.9.4?

**Comment by AlterAkima** [comment]
They are probably registering the wrong ore name.

**Comment by Xiaminou** [comment]
That was my first thought too, it was ingotAluminium so I added ingotAluminum with crafttweaker which I believe is the right one but it still doesn't work.

**Comment by KnightMiner** [comment]
CraftTweaker loads after initialization, so anything that adds features based on if the OreDictionary contains a name will not detect entries added by it.

**Comment by Xiaminou** [comment]
Didn't know that. Well Substratum updated the ore dictionaries and it now works, issue closed.
