### ISSUE TITLE
[Suggestion] On the fly Repair

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#2152]
Wondering if you ever intend to bring repairing of tools with relevant materials in your personal crafting grid instead of requiring the Tool Station for repairs.  This feature was added I think by Iguanna's Tweaks but would love to see it just be a core mechanic.

Maybe as a material trait?

**Comment by jriwanek** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ

See "Suggestions"
