### ISSUE TITLE
Smeltery ore return config option

### ISSUE THREAD

**Issue by WolfieWaffle** [SlimeKnights/TinkersConstruct#2153]
In previous versions, you could give an amount of metal the smeltery gave you for each ore. I assume that it just hasn't been added yet, is this the case?

**Comment by KnightMiner** [comment]
I don't recall this feature existing before, I know Tinkers Steelworks had such an option though.

In any case, this would be useful to have.

**Comment by bonii-xx** [comment]
It did exist before. Ingots per ore is doable, general liquid amounts not.

**Comment by WolfieWaffle** [comment]
What do you mean by this? That you could add a config for how many total ingots is returned in liquid form but not amounts of liquid that do not divide evenly into ingots, or that you cannot add a config for how much molten metal is returned at all?

**Comment by KnightMiner** [comment]
Changing the amount of liquid per ore is not practical considering the amount of things that depend on a single ingot being 144, plus not all ores produce a single ingot (see dense ores and poor ores).
