### ISSUE TITLE
[1.8.9] Gold & Clay Cast

### ISSUE THREAD

**Issue by XieEDeHeiShou** [SlimeKnights/TinkersConstruct#2160]
MC : 1.8.9
Liteloader with Forge : 1.8.9-11.15.1.1902-1.8.9
TiC : 1.8.9-2.2.1

Well, I see this in JEI : 
![qq 20160610225506](https://cloud.githubusercontent.com/assets/16363180/15968498/b4a9767e-2f5e-11e6-9021-99f129faf7d8.png)
Both of the recipes show Gold Cast ...

And another promble : 
My Tool Rod Cast (the gold one) disappered after i made a Obsidian Tool Rod...and a Binding Pattern Cast (gold) disappered too...
Was it designed or just a bug ...

**Comment by KnightMiner** [comment]
Clay casts actually recolor the gold cast for the texture, so some mod might be preventing the rendering from working right. Are you using Optifine by any chance?
