### ISSUE TITLE
[1.9.4] java.lang.NullPointerException: Tesselating block in world

### ISSUE THREAD

**Issue by Xiaminou** [SlimeKnights/TinkersConstruct#2163]
Crashed when crafting an EnderIO's vaccum chest in a Tcon's crafting table with enabled item rendering on top of the tables.

Crash Report: http://pastebin.com/k4mcZqJZ

**Comment by Severance213** [comment]
I have something similar for a crash report too. Except instead of a vacuum chest, it's at any crafting function.

**Comment by bonii-xx** [comment]
That crashlog looks... very unlikely. Can you reproduce it with only EIO and tcon+mantle?

**Comment by Xiaminou** [comment]
I can't

**Comment by bonii-xx** [comment]
Then it's probably not initially caused on our side. Let's just blame optifine, that always works.

**Comment by miuirussia** [comment]
Same error with Mekanism:
https://github.com/aidancbrady/Mekanism/issues/3351

**Comment by bonii-xx** [comment]
Nope, that's a completely different thing.

**Comment by Xiaminou** [comment]
I haven't had a single render issue with Optifine post 1.7.10. I think some mod's items/blocks just render badly on top of crafting tables.
I have had a couple more crash with ExtraUtils' items.
Crash Report: http://pastebin.com/44s33fZ2

**Comment by bonii-xx** [comment]
Yup, that's on XU2s side. Known bug.

**Comment by kamyflouge** [comment]
try disabling  the item render on tinkers crafting bench (in configs). i fixed my problem with that method.

**Comment by miuirussia** [comment]
I can't disable render only in crafting bench
