### ISSUE TITLE
 crash report 1.7.10

### ISSUE THREAD

**Issue by runescapejon** [SlimeKnights/TinkersConstruct#2164]
i tried using the tinkers construct traveller's belt ability swap hotbar and i crashed 
http://pastebin.com/QE1YBZwt

**Comment by KnightMiner** [comment]
Looks like the toolbelt is missing its NBT, not sure what could be causing it unless some mod is replacing the default recipe.

In any case, 1.7.10 is no longer supported, new releases are aimed at 1.9.4.

**Comment by runescapejon** [comment]
dang

**Comment by bonii-xx** [comment]
Don't use /give to get items.
