### ISSUE TITLE
Drying racks render rotated

### ISSUE THREAD

**Issue by bonii-xx** [SlimeKnights/TinkersConstruct#2166]
For some reason drying racks now don't render correctly anymore. Not sure which commit caused it, probably either the comparator PR or one of the fixes afterwards. Delegating this to you @KnightMiner ;o

**Comment by KnightMiner** [comment]
I know they will break their rotation if no custom texture is added (as they then no longer ignore the blockstate). I'll look into this more.

**Comment by bonii-xx** [comment]
For now it should suffice if it works again. I also got a report that drying racks lose their texture and return to oak (default) when broken. So either some forge bug in that version that breaks our interaction, or dropping the block returns an incorrect result.

**Comment by bonii-xx** [comment]
Caused by f73755c354785c4c777a1e82d018c7561b32fdb6
Fixed through de37581d918878d75d40c587203fd8642252b499
