### ISSUE TITLE
[1.9.4] Materials and You no spaces between words

### ISSUE THREAD

**Issue by Xiaminou** [SlimeKnights/TinkersConstruct#2168]
Materials and You have no spaces between words:
My windows is in french, don't know if that has anything to do with it, but I haven't seen anyone else reporting this bug so I'm asuming it's kind of unique.

![2016-06-14_14 09 06](https://cloud.githubusercontent.com/assets/8670392/16042141/9462abb4-3239-11e6-88e0-ad0782f6b108.png)
![2016-06-14_14 09 09](https://cloud.githubusercontent.com/assets/8670392/16042140/94626528-3239-11e6-9c9b-393db5829d98.png)

**Comment by jriwanek** [comment]
Can confirm.

**Comment by bonii-xx** [comment]
Does it happen without resource pack? Does it happen with only TiC and Mantle?

**Comment by jriwanek** [comment]
Will check without other mods later today, but I can say I'm not using a resourcepack.

**Comment by FusionLord** [comment]
> Will check without other mods later today, but I can say I'm not using a resourcepack.
Sure seems like your grass, dirt and glowstone are higher resolution than vanilla, you sure you don't have a resourcepack?

**Comment by jriwanek** [comment]
No longer occurring as of Tinkers Construct 2.3.3/Mantle 0.10.2.
Tested on forge for 1.9.4 12.17.0.1976 (English US)

**Comment by bonii-xx** [comment]
Interesting. If it happens again, see if you can isolate when it happens so I can debug it. But let's hope it just doesn't come back ;)

**Comment by jriwanek** [comment]
Will keep an eye out.
