### ISSUE TITLE
[1.9.4] Crashes without WAILA

### ISSUE THREAD

**Issue by mezz** [SlimeKnights/TinkersConstruct#2169]
When WAILA is not installed, Tinker's crashes.
I want to use The One Probe instead of WAILA.

Crash log: 
https://gist.github.com/mezz/28ffb952b3f8a3763832d172989d7d6e

**Comment by KnightMiner** [comment]
Hmm, it seems the Waila plugin object is created even if the required mod is not loaded (as the Waila pulse object is passed into the manager after being created). Relevant code is [here](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/plugin/waila/Waila.java#L33).

The easiest solution I can think of without changing how the pulseloader works is simply moving that method to a different class.

**Comment by mezz** [comment]
Alternatively you can mark that function `@Optional`

**Comment by KnightMiner** [comment]
Oh yeah, I forgot that annotation existed...
