### ISSUE TITLE
[1.9.4] The explosive EFLN

### ISSUE THREAD

**Issue by Karra11** [SlimeKnights/TinkersConstruct#2171]
There is an explosive item that can be crafted in Tinker's construct by the version 1.9.4, but I can't find the source of this explosive in any wiki, and I haven't found it anyway in the mod file/config file. Where is the source so I can change the way it works on the game?

**Comment by AlterAkima** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/gadgets/entity/ExplosionEFLN.java

**Comment by Karra11** [comment]
thank you a lot
