### ISSUE TITLE
[Suggestion] Access part chest from adjacent part builders and tool stations/forges

### ISSUE THREAD

**Issue by qwertyasdef** [SlimeKnights/TinkersConstruct#2172]
Like the title says. It would be nice to be able to access the part chest from part builders and tool stations/forges. This will allow us to make a bunch of large plates, tool rods, or any other frequently used part, and dump them in the part chest for later. When we actually go to make a tool, the parts are accessible from the tool station/forge instead of having to switch tabs to grab parts. Also, put the part chest tab between the tool station/forge and part builder tabs, instead of to the right of the part builder tab to reflect that you should put them next to each other. This change would also make it more consistent with the pattern chest, which can be accessed from the stencil table and part builder.

**Comment by TherminatorX** [comment]
Was a thing at one point, I tested it myself.

**Comment by bonii-xx** [comment]
No UI space.
