### ISSUE TITLE
Longsword allows infinite flight with Elytra

### ISSUE THREAD

**Issue by Drullkus** [SlimeKnights/TinkersConstruct#2176]
Slightly similar to #2035.

Modpack - FTB Unstable 4.0.7

Mod Jar Filename - TConstruct-1.9.4-2.3.1.jenkins229.jar

Normally, by right-clicking and holding for a bit, then letting go, you jump forward with the longsword. This, combined with the Elytra, allows infinite motions of jumping upwards, to the point that you never touch the ground.

Suggested fix 1: Only allow players to jump up with the Longsword if they are standing on the ground.

Suggested fix 2: Only allow players to use the Longsword's jump once until they touch the ground again. (Thanks for [pointing that out](https://github.com/SlimeKnights/TinkersConstruct/issues/2176#issuecomment-226905444), @KnightMiner!)

**Comment by OrionDevelopment** [comment]
It has to be noted that this is also possible in Vanilla using a Punch 2 Bow.
However in Vanilla both the bow and armor (including the elytra) take damage, so a mending enchant is used to repair it again.

**Comment by KnightMiner** [comment]
The suggested fix would make the super cool longsword double jump be lost, so maybe attempt to detect the elytra or go based on current air time?

It is pretty fun to fly with elytra and a longsword though :)

**Comment by Drullkus** [comment]
Ah, updated the original post, @KnightMiner :D

**Comment by TherminatorX** [comment]
Also recall that elytra take damage, so flight will not be infinite. :p

**Comment by Drullkus** [comment]
Mending.

**Comment by laz2727** [comment]
You can't reliably get exp midflight with TiC only.

**Comment by Drullkus** [comment]
Never assume that a player comes preloaded with 600 levels of exp

**Comment by Drullkus** [comment]
This is just turning into a semantic argument. I'm guessing boni never intended this, end of story. Waiting for feedback from boni or another TCon dev. @alexbegt?

**Comment by LovelyFlare** [comment]
I've already talked to boni about it before this issue was reported, and he said he'd try it out in his spare time.  Anyhow, the Elytra in 1.9 is a creative only item anyway so this shouldn't be a problem for now.

**Comment by OrionDevelopment** [comment]
@LovelyFlare No it is not Creative only, it can be retrieved from the End, or am i mistaken?

**Comment by Drullkus** [comment]
You can get it from the End.

**Comment by bonii-xx** [comment]
I personally don't think it's a great deal. It doesn't really cause any harm, just a fun interaction. But we'll see.

**Comment by TherminatorX** [comment]
@Drullkus Unless a player can shower themselves with EXP midflight, Mending will not apply.

**Comment by KnightMiner** [comment]
With the new vanilla mechanic for elytra boosting, I revisted this issue and pushed a fix. Longswords will no longer boost when elytra flying, instead passing action to the offhand.

**Comment by xenxero1** [comment]
if it passes action to the offhand, wouldn't holding 2 longswords still function?

**Comment by KnightMiner** [comment]
No, offhand longsword passes as well. Its generic vanilla mechanics, nothing specially coded.
