### ISSUE TITLE
[1.9.4] Ticking Memory Exception

### ISSUE THREAD

**Issue by Alaberti** [SlimeKnights/TinkersConstruct#2177]
Brief explanation of problem:
After updating Tinker's Construct, there is a ticking memory connection crash which states:

java.lang.ClassCastException: slimeknights.tconstruct.library.capability.TinkerPiggybackHandler cannot be cast to matteroverdrive.entity.android_player.AndroidPlayer

and causes a crash to desktop.

Steps to reproduce:
Launch with TConstruct-1.9.4-2.3.2/Mantle-1.9.4-0.10.2 and MatterOverdrive-1.9.4-0.4.4-build-55, create/load a world.

Crash report paste (if any) on [gist](gist.github.com):
https://gist.github.com/Alaberti/ff55fdd5d202d29e5e061601362660b8

Minecraft version:
1.9.4

https://github.com/simeonradivoev/MatterOverdrive/issues/550

**Comment by bonii-xx** [comment]
Looks like matter overdrive is missing a check in its capability provider. Easy to fix, but one of those things that only turns up with multiple mods.
