### ISSUE TITLE
[Suggestion] EnderIO Intergration

### ISSUE THREAD

**Issue by yepidoodles** [SlimeKnights/TinkersConstruct#2178]
EnderIO is still in Alpha for 1.9.4 but adding the alloys from it would be amazing

Thanks

- Alice
DragonTechMC

**Comment by jriwanek** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ

Your best bet is actually to ask the EnderIO devs to add support.

**Comment by bonii-xx** [comment]
TiC only adds support for general metals.
