### ISSUE TITLE
Durability mistake?

### ISSUE THREAD

**Issue by ConCon2** [SlimeKnights/TinkersConstruct#2179]
Manullyn tools have only a 680 durability for a pickaxe wile cobolt and aradit have over 1,000.

**Comment by LovelyFlare** [comment]
Which version is this in?

**Comment by ConCon2** [comment]
For 1.9.4 sorry.

**Comment by ConCon2** [comment]
We are playing on a LAN game.  If you open the tinkers book as a multi player logged into the game the book also opens up on the hosts screen.

**Comment by LovelyFlare** [comment]
Separate issue, next time try opening it as another issue.

**Comment by bonii-xx** [comment]
Regarding durability: Sounds like you need to get tinkering.
Regarding book: Shouldn't happen in 2.3.2
