### ISSUE TITLE
Can't upgrade all parts of the shuriken

### ISSUE THREAD

**Issue by Stabington** [SlimeKnights/TinkersConstruct#2180]
Some parts of the shuriken can't be replaced in the tool forge.

**Comment by LovelyFlare** [comment]
Version?  Assuming it's 1.7.10 with Iguana's Tinker Tweaks, it's unsupported.

**Comment by Stabington** [comment]
Mantle 0.12.2
Tinkers' 2.3.2
Forge 12.17.0.1965

**Comment by bonii-xx** [comment]
Which part is that supposed to be?
![2016-06-19_10 17 02](https://cloud.githubusercontent.com/assets/722449/16176166/0116272e-3607-11e6-80f7-5ef2142ef90a.png)

**Comment by Stabington** [comment]
Huh? I couldn't change the upper right one.
But I tried just upgrading one side at a time.

**Comment by bonii-xx** [comment]
Then the detection is off

**Comment by bonii-xx** [comment]
Found the issue, the check was actually inverted. Thanks for reporting!
