### ISSUE TITLE
Smeltery Injures Player Without Any Lava Source, or Molten Metal in the Smeltery 1.9.4

### ISSUE THREAD

**Issue by lilmoefow** [SlimeKnights/TinkersConstruct#2183]
The smeltery is 2 tall with any size base, and it injures the player without and lava or molten metal in the smelter.

See video here for a "demonstration" 

https://www.dropbox.com/s/wq26lev1mvxwxcp/2016-06-18%2019-50-23.flv?dl=0

Forge 12.17.0.1962
TConstruct-1.9.4-2.3.1.jenkins229

Sorry if this is not a bug, and in fact a new "feature".

**Comment by KnightMiner** [comment]
This was fixed in 2.3.2, which was released just recently. See 92db6f7.

**Comment by lilmoefow** [comment]
cool thanks, will update when I can.
