### ISSUE TITLE
[1.9.4] Placing an item from SlashBlade in a crafting station causes crash

### ISSUE THREAD

**Issue by patrickclank9** [SlimeKnights/TinkersConstruct#2188]
Slashblade: http://minecraft.curseforge.com/projects/slashblade
Crashlog: http://paste.ee/p/KFsQ2
And it keeps crashing it upon loading the world. Removal of the station with mc edit fixed it.
I also tried disabling the table rendering. Didn't work.

**Comment by bonii-xx** [comment]
They're fucking with rendering in their models. Tell them to do models properly instead of weird hacks.
