### ISSUE TITLE
[1.9.4][BaseMetals] Smeltery not alloying nickel and iron

### ISSUE THREAD

**Issue by Syndaryl** [SlimeKnights/TinkersConstruct#2189]
The Smeltery is melting nickel dust correctly, but it only produces molten nickel and molten iron, rather than the alloy. It should also produce cupronickel (copper/nickel)

**Comment by jriwanek** [comment]
This is not a bug in Tinkers construct, they don't provide support for other mods metals and we already have a bug open for this: https://github.com/cyanobacterium/BaseMetals/issues/41
