### ISSUE TITLE
1.7.10 Constant crashing in smeltery

### ISSUE THREAD

**Issue by ProMCredstone** [SlimeKnights/TinkersConstruct#2191]
Hello, i love this mod, but there is a issue that is extreamly annoying and with alot of mods it can take forever to loadup minecraft again. It happens in the smeltery every single time you hover your mouse over the lava bar in the smeltery. Heres the crash report, Email me at 22aaronholdaway@gmail.com if another author needs to be consulted about this issue.

Crash report:
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 6/21/16 4:36 PM
Description: Rendering screen

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at tconstruct.smeltery.gui.SmelteryGui.drawGuiContainerForegroundLayer(SmelteryGui.java:160)
	at tconstruct.client.gui.NewContainerGui.func_73863_a(NewContainerGui.java:165)
	at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:60)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1397)
	at weather2.weathersystem.EntityRendererProxyWeather2Mini.func_78480_b(EntityRendererProxyWeather2Mini.java:50)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at tconstruct.smeltery.gui.SmelteryGui.drawGuiContainerForegroundLayer(SmelteryGui.java:160)
	at tconstruct.client.gui.NewContainerGui.func_73863_a(NewContainerGui.java:165)
	at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:60)

-- Screen render details --
Details:
	Screen name: tconstruct.smeltery.gui.SmelteryGui
	Mouse location: Scaled: (380, 144). Absolute: (760, 417)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1397)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Spirit300'/574, l='MpServer', x=211.89, y=65.62, z=269.25]]
	Chunk stats: MultiplayerChunkCache: 41, 50
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (252,64,248), Chunk: (at 12,4,8 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1414357 game time, 492615 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 34 total; [EntitySheep['Sheep'/256, l='MpServer', x=201.50, y=70.00, z=306.47], EntitySkeleton['Skeleton'/124928, l='MpServer', x=-31.67, y=-29.93, z=-35.70], EntitySkeleton['Skeleton'/5509, l='MpServer', x=-31.04, y=-30.62, z=-34.71], EntityTrail['unknown'/807, l='MpServer', x=211.89, y=65.62, z=269.25], EntitySkeleton['Skeleton'/301742, l='MpServer', x=-19.89, y=-46.62, z=12.75], EntitySpider['Spider'/303033, l='MpServer', x=193.16, y=31.81, z=321.34], EntityClientPlayerMP['Spirit300'/574, l='MpServer', x=211.89, y=65.62, z=269.25], EntitySheep['Sheep'/204, l='MpServer', x=153.16, y=72.00, z=284.19], EntitySkeleton['Skeleton'/107084, l='MpServer', x=-26.84, y=-50.62, z=6.84], EntitySheep['Sheep'/205, l='MpServer', x=155.41, y=72.00, z=285.72], EntitySheep['Sheep'/206, l='MpServer', x=156.63, y=73.00, z=295.13], EntityBat['Bat'/309584, l='MpServer', x=186.09, y=15.89, z=321.67], EntityZombie['Zombie'/309330, l='MpServer', x=193.91, y=52.00, z=282.63], EntitySheep['Sheep'/220, l='MpServer', x=166.06, y=60.00, z=261.91], EntitySheep['Sheep'/221, l='MpServer', x=161.25, y=65.00, z=260.53], EntityZombie['Zombie'/300889, l='MpServer', x=199.50, y=10.16, z=326.97], EntitySheep['Sheep'/222, l='MpServer', x=173.22, y=67.00, z=268.19], EntitySheep['Sheep'/223, l='MpServer', x=156.50, y=72.00, z=277.72], EntitySheep['Sheep'/224, l='MpServer', x=159.50, y=68.00, z=261.66], EntitySheep['Sheep'/225, l='MpServer', x=161.13, y=64.00, z=259.13], EntityCreeper['Creeper'/312165, l='MpServer', x=200.50, y=29.00, z=273.50], EntitySheep['Sheep'/226, l='MpServer', x=167.22, y=69.00, z=283.53], EntitySheep['Sheep'/227, l='MpServer', x=175.47, y=77.00, z=277.34], EntitySheep['Sheep'/228, l='MpServer', x=160.06, y=72.00, z=287.88], EntitySheep['Sheep'/229, l='MpServer', x=166.97, y=72.00, z=285.94], EntitySheep['Sheep'/230, l='MpServer', x=159.34, y=80.00, z=283.50], EntitySheep['Sheep'/231, l='MpServer', x=172.53, y=69.00, z=302.53], EntitySheep['Sheep'/232, l='MpServer', x=165.16, y=72.00, z=288.66], EntitySheep['Sheep'/233, l='MpServer', x=161.72, y=72.00, z=290.84], EntitySheep['Sheep'/234, l='MpServer', x=164.25, y=72.00, z=292.50], EntitySheep['Sheep'/235, l='MpServer', x=170.47, y=72.00, z=291.75], EntityZombie['Zombie'/237, l='MpServer', x=162.53, y=55.35, z=311.60], EntityChicken['Chicken'/238, l='MpServer', x=162.50, y=55.00, z=311.50], EntityPig['Pig'/240, l='MpServer', x=169.38, y=74.06, z=326.88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 84389624 bytes (80 MB) / 924348416 bytes (881 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 Optifine OptiFine_1.7.10_HD_U_D4 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
	UCHIJAAAA	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCHIJAAAA	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.98.jar) 
	UCHIJAAAA	factorization.dimensionalSlice{0.8.98} [Factorization Dimensional Slices] (Factorization-1.7.10-0.8.98.jar) 
	UCHIJAAAA	factorization{0.8.98} [Factorization] (Factorization-1.7.10-0.8.98.jar) 
	UCHIJAAAA	factorization.misc{0.8.98} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.98.jar) 
	UCHIJAAAA	Growthcraft{1.7.10-2.4.0} [Growthcraft] (growthcraft-1.7.10-2.4.0-complete-core.jar) 
	UCHIJAAAA	Growthcraft|Cellar{1.7.10-2.4.0} [Growthcraft Cellar] (growthcraft-1.7.10-2.4.0-complete-cellar.jar) 
	UCHIJAAAA	Growthcraft|Apples{1.7.10-2.4.0} [Growthcraft Apples] (growthcraft-1.7.10-2.4.0-complete-apples.jar) 
	UCHIJAAAA	Growthcraft|Bamboo{1.7.10-2.4.0} [Growthcraft Bamboo] (growthcraft-1.7.10-2.4.0-complete-bamboo.jar) 
	UCHIJAAAA	Growthcraft|Bees{1.7.10-2.4.0} [Growthcraft Bees] (growthcraft-1.7.10-2.4.0-complete-bees.jar) 
	UCHIJAAAA	Growthcraft|Fishtrap{1.7.10-2.4.0} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.4.0-complete-fishtrap.jar) 
	UCHIJAAAA	Growthcraft|Grapes{1.7.10-2.4.0} [Growthcraft Grapes] (growthcraft-1.7.10-2.4.0-complete-grapes.jar) 
	UCHIJAAAA	Growthcraft|Hops{1.7.10-2.4.0} [Growthcraft Hops] (growthcraft-1.7.10-2.4.0-complete-hops.jar) 
	UCHIJAAAA	Growthcraft|Rice{1.7.10-2.4.0} [Growthcraft Rice] (growthcraft-1.7.10-2.4.0-complete-rice.jar) 
	UCHIJAAAA	herdCraft{1.1} [HerdCraft] (HerdCraft-1.7.10-1.1.1.jar) 
	UCHIJAAAA	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UCHIJAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle-mc1.7.10-0.3.1.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	Mekanism{9.0.2} [Mekanism] (Mekanism-1.7.10-9.0.2.271.jar) 
	UCHIJAAAA	MekanismGenerators{9.0.2} [MekanismGenerators] (MekanismGenerators-1.7.10-9.0.2.271.jar) 
	UCHIJAAAA	MekanismTools{9.0.2} [MekanismTools] (MekanismTools-1.7.10-9.0.2.271.jar) 
	UCHIJAAAA	minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAAAA	OpenComputers{1.5.12.26} [OpenComputers] (OpenComputers-MC1.7.10-1.5.12.26-universal.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
	UCHIJAAAA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	jordy141minecraftmagicwrench{0.5 Alpha} [Magic Wrench] (UncraftingTable-1.7.10-alpha1.jar) 
	UCHIJAAAA	uncraftingTable{1.7.10 Alpha 1} [Uncrafting Table] (UncraftingTable-1.7.10-alpha1.jar) 
	UCHIJAAAA	weather2{v2.3.11} [Localized Weather & Storms] (weather2-1.7.10-2.3.10.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.0.8.16} [MrTJPCore] (MrTJPCore-1.7.10-1.0.8.16-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.3.12683 Compatibility Profile Context 13.302.1904.0' Renderer: 'AMD Radeon(TM) R4 Graphics'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.2-325
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.2.3-112
	ThermalExpansion: -[1.7.10]4.1.2-240
	RedstoneArsenal: -[1.7.10]1.1.1-89
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.1.0-161
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:ON, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1517-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.3.12683 Compatibility Profile Context 13.302.1904.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithful64pack-v1.4.0.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D4
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.3.12683 Compatibility Profile Context 13.302.1904.0
	OpenGlRenderer: AMD Radeon(TM) R4 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by KnightMiner** [comment]
1.7.10 is no longer supported, and even if it was you are using an ancient version of 1.7.10 TConstruct (like, 2 years old, I cannot even find an older 1.7.10 build).

 I personally do not have this issue, so it is either your usage of a very old version or a mod conflict, so update to the latest version, and if that does not fix it try removing mods until it works (such as Optifine).

**Comment by bonii-xx** [comment]
Update your Tinkers' Construct. And Minecraft Version, while we're at it.

**Comment by ProMCredstone** [comment]
1 1.7.10 version of Tconstruct is not ancient, its the latest 1.7.10 build. Its even on the mod post. And 1.7.10 isnt even 2 years old. It was released like last year. Not 2 years. And that alot of mods have 1.7.10 builds and are still using 1.7.10 as a primary version. 1.7.10 is the mod treasure trove. 1.7.10 is supported by T construct. I have to use 1.7.10 because key mods in my modpack i am working on only go up to 1.7.10 And you werent specific. It even crashes on the mod by itself without all the other mods. Its Tconstruct thats causing it. And i doubt you even read the crash report. I have the latest 1.7.10 supported version so, you bettered be helpful instead of making the problem continue. It crashed on the mod by itself, and with the modpack. And when i read the crash report it has to do with a null fluid stack.

**Comment by ProMCredstone** [comment]
Sorry i have to have it 1.7.10, i am to make a modpack and alot of the mods that are needed only support 1.7.10, If i update my minecraft version it will get rid of like 30 of the mods. So i guess Tinkers isnt a golden mod for modpacks. I guess i cant use the mod. (if i were a mod delevoper, i would take account on the versions, I do not like mods that go "oh hey look, 1.8 came out, lets ditch the majority of mods and ignore the majority of modpack developers and make them unhappy that they cant use my mod that is a great mod." Its this thinking that kills modpacks that thousands of people play. And sometimes millions.)

**Comment by jriwanek** [comment]
@ProMCredstone He didn't say you had to move from 1.7.10, just that they don't *support* 1.7.10 any more, what he did say was that you should update to the latest build of Tinkers *for 1.7.10:
UCHIJAAAA TConstruct{1.7.10-1.6.0.build611} Tinkers' Construct <-- Your current version

See: http://minecraft.curseforge.com/projects/tinkers-construct/files/2264246

Current version is 1.8.8 for 1.7.10

**Comment by mixilester009** [comment]
You can make a whitelist for the mobs who will milk the fluid when they inflict damage from the smelter.
