### ISSUE TITLE
Tinkers fluids cull strangely

### ISSUE THREAD

**Issue by yrsegal** [SlimeKnights/TinkersConstruct#2192]
![2016-06-22_13 38 36](https://cloud.githubusercontent.com/assets/6596492/16276989/e46b0e12-387e-11e6-9af2-bc57c0d5f11a.png)

Version 1.9.4-2.3.2.jenkins260

**Comment by Wulfson** [comment]
related to https://github.com/MinecraftForge/MinecraftForge/issues/2993 ?

**Comment by yrsegal** [comment]
Probably. It's not a TC issue, sorry!
