### ISSUE TITLE
Cant use the casting table with any kinda of cast (or liquid) but the Casting Basin Works

### ISSUE THREAD

**Issue by vrork** [SlimeKnights/TinkersConstruct#2194]
Game Version : 1.9.4
Mod Version: TConstruct-1.9.4-2.3.2

**Comment by bonii-xx** [comment]
Then you're either trying to cast things that don't exist or some other mod messed it up.

**Comment by vrork** [comment]
No. I trying to cast gold ingots (but any ore, vanilla or not, doesnt work
with any cast). And it got messed up on the last update of TC, because
before it, it was working without any problem.
Em 23/06/2016 14:30, "boni" <notifications@github.com> escreveu:

**Comment by vrork** [comment]
Alright, fixed. It was a mod that i have no idea wich one was. Sorry for making you loose your time.

**Comment by bonii-xx** [comment]
If you happen to stumble upon the mod that causes it, please tell me, so I can keep it in mind for future reference.

**Comment by vrork** [comment]
I have no idea wich mod caused it. But i will keep this in mind
Em 25/06/2016 13:39, "boni" <notifications@github.com> escreveu:

**Comment by bookerthegeek** [comment]
A before and after mod list would help narrow it down.

**Comment by vrork** [comment]
I dont have a before the problem mod list.

2016-06-26 16:52 GMT-03:00 BookerTheGeek <notifications@github.com>:
