### ISSUE TITLE
Issue with items dropped into a smeltery

### ISSUE THREAD

**Issue by mattk926** [SlimeKnights/TinkersConstruct#2195]
Original thread here: https://github.com/FireBall1725/Graves/issues/45

When dying in a smeltery and creating a grave in the smeltery. you break the grave and it then crashed with the following crashlog: http://pastebin.com/6AgWxE8x

**Comment by FusionLord** [comment]
Unlike the title implies it isn't an issue with Graves as I was able to reproduce by just throwing a stick into the smeltery without Graves installed.

**Comment by mattk926** [comment]
@FusionLord I wasn't able to reproduce with throwing an item into the smeltery... items that can be melted down get melted down and items that cant just sit in the smeltery. I'm tossing items into the smeltery similar to how if you were to break a gravestone and the items would land in the world.

**Comment by FusionLord** [comment]
It looks like when I was testing that my assistant broke up a grave that was in a smeltery when i dropped the stick, and I fixed that the graves are dropping null items.

**Comment by mattk926** [comment]
Sounds good, I noticed that you fixed the rendering issue with the latest commit from today. Just waiting for you to commit this change to verify. Will close this issue as it appears to not be a TCon issue after all! Thank you for the quick replies!

**Comment by FusionLord** [comment]
So it seems that the issue is that when I replace the controller the info variable is null and hasn't been repopulated even though i read and write the NBTData. Because I checked and the Items I'm dropping are not null.
