### ISSUE TITLE
Molten aluminum glitch.

### ISSUE THREAD

**Issue by Aelar-Nailo** [SlimeKnights/TinkersConstruct#2197]
In the ftb unstable 1.9 pack, putting an acacia boat in a smeltery yields 144 mb of aluminum. I don't know if this is a bug involving tinker's directly, but i felt it should come to your attention.

**Comment by GirafiStudios** [comment]
Duplicate of https://github.com/SlimeKnights/TinkersConstruct/issues/2185

**Comment by bonii-xx** [comment]
Fixed in 2.3.3
