### ISSUE TITLE
Crafting station 

### ISSUE THREAD

**Issue by Caleb-Ardern** [SlimeKnights/TinkersConstruct#2198]
Hey,
I heard someone ask Direwolf20 for a list of invalid textures on the crafting station and i am starting a list here. Is this the right place?
Version: Minecraft 1.9.4
Forge: 12.17.0.1968
Tinkers: 1.9.6-2.3.2

- [ ] Skulls [Minecraft]

- [ ] Inventory panel [EnderIO 1.9.4-3.0.0.43_alpha]: Backwards

**Comment by KnightMiner** [comment]
This is a known issue, and is not entirely fixable, see #2111. Essentially, it happens with anything that uses builtin/entity for rendering, as those do not have a model we can practically load outside of a TESR (which would decrease performance)
