### ISSUE TITLE
[1.9.4] Regarding the Cleaver (Sugestion/question)

### ISSUE THREAD

**Issue by werff** [SlimeKnights/TinkersConstruct#2200]
Ok, the cleaver was a defensive sword right?
But now it's just a "hard" and slow hotting sword, right? (And now big, wich i love :D)

But, will it get any rightclick uses?
Because i think will be good to give it back the block (the shieldo ne) but with like 5 dura lost per hit blocked, and no damage reflection (just that).

Because rightnow it's just the other sword with more damage and slower attack speed.

Just that, thanks for reading

**Comment by KnightMiner** [comment]
The battle sign already has the block ability, sobadding it to the already powerful cleaver is not only redundant, but removes usefulness of the battle sign.

By not having a right click ability, the cleaver can actually use that of another tool or item, so it can use an actual shield or a battle sign in the offhand.

**Comment by werff** [comment]
> so adding it to the already powerful cleaver is not only redundant, but removes usefulness of the battle sign.

Sorry, but it's now such a powerfull weapon, let me explain why:

Rapier ATK SPD 3
Broadsword ATK SPD 1.6
Longsword ATK SPD 1.4
Battlesing ATK SPD 1.2
Cleaver ATK SPD 0.7
Now, taking Flint weapons as an example of DMG

Rapier DMG 2.54
Broadsword DMG 4.8
Longsword DMG 4.63
Battlesing DMG 3.41
Cleaver DMG 8.1 (nearly the doublé fot he broadsword)
Ok, rightnow most dmg is cleaver, but is also the slowest. Now taking DPS

Rapier  DPS=7.62 Real DPS= 5.08 (Considering it goes througth a bit of armor, and the jump back skill, ot's pretty good, but no shield)

Broadsword DPS= 7.68 Real DPS=7.68 (Current best weapon in terms of DPS, and you can use a shield with it)

Longsword DPS= 6.482 Real DPS= 6.482 (BUT it has the jump skill :P wich makes it pretty good)

Battlesing DPS=4.092 Real DPS= 4.092  (It's main use it's blickng, in wich he sends back half the damage to the dealer, but in terms of "weapon" it's not so great, better combine with broadsword, and your dps are still the best, and sending half the dmg to the dealer)

Cleaver DPS= 5.67 Real DPS=5.67 (Doesn't have the weapons lowest REAL DPS, because it is with the rapier, but thanks to the armor pierce skill of the rapier it's rightnow a pretty bag weapon and one miss equals a high loss :/ I'm using it because i love the concept XD but it's a pretty bad weapon)

Now speaking of the cleaver

Even using a sign/shield with it doesn't make it decent at all. That's why i was asking/wondering if it will get it's block back, nothing more. Also The cleaver should get an attack speed of 0.8-0.9 base for being a decent weapon because, using Flint as an exaple the dps will go from 6.48 to 7.29, and if we add a normal "block" who doesn't reflect the dmg, or some rightclick use it will be a decent trully usable weapon, at least in terms of material inversion. Because for the price of a cleaver you could make 5 and a half other-swords wich is better than that one... Just that XD

**Comment by bonii-xx** [comment]
The cleaver just is a big huge sword that hits hard. If you want more DPS get a faster weapon. If you want to hit harder at once, use a cleaver. Also you're not taking damage scaling into account.

>By not having a right click ability, the cleaver can actually use that of another tool or item, so it can use an actual shield or a battle sign in the offhand.

Nop, it's twohanded, no offhand.

**Comment by KnightMiner** [comment]
Hmm, I guess I have not used the cleaver a much to not notice that.

**Comment by werff** [comment]
Sorry but...

> Nop, it's twohanded, no offhand

In 1.9.4 doesn't wrok, i'm using in the off hand shurikens ._.
Also, if you will make it two-handed only, increase the attack a bit, i use it because i love it, but the damange it can do it's pretty low...

**Comment by bonii-xx** [comment]
I'll take a look, but flint is not really a good material to take as a measurement. Try something with more damage.

**Comment by werff** [comment]
Well, it's a decent one, but i have done a test with iron, and recorded it.

Take a look https://youtu.be/fNtrHJ3NFlI

But also think the dmg, and if it will get no offhand, won't compesate the slowness :/
I will be the only one using it, because it costs 22 mats, nearly a full set of armor (if that material has armor asociated) or the cost of 2 blocks and 4 ingots (of iron for example, if the material works on the metal shape bases of exponential of 9)-

**Comment by bonii-xx** [comment]
You know I have [test dummies](http://minecraft.curseforge.com/projects/mmmmmmmmmmmm) for proper DPS testing, right?

**Comment by werff** [comment]
I didn't ._.
That he only thing will you say? XD

But well, if you are going to make it two handed, at least make it hit decent, because rightnow you can use, for more effect in combat, any of the other weapons.

**Comment by laz2727** [comment]
Sometimes, you just need to oneshot. 33% less dps is not that bad.

**Comment by bonii-xx** [comment]
They do. The iron cleaver left the zombie with 1/2 heart, so you needed one more hit. But you overkilled it by about 1/3 of its hp. Also cleavers and broadswords scale differently. Try building a tool that actually hurts.

**Comment by werff** [comment]
I maked and iron one, but ok, will test it later.

**Comment by werff** [comment]
Ok, here, for th dps chat i forgot the manlyum increased dmg XD my bad.

https://youtu.be/hYbhoAMOtlY

Still, cleaver required more time than the broadsword :/

**Comment by bonii-xx** [comment]
Well, you didn't use any of your modifiers. That's what they're for. But I agree that Cleavers are a bit on the lower end for weak materials, hence they'll get a small buff for less damaging materials.

**Comment by werff** [comment]
Thanks then, also, will you make them two handed, or will you the cleaver stay with the off hand uses?

Because if it's the first, a bit more of enchance won't d any damange :P

But overall, thanks. Also, i consider the modifiers like the "enchants" of the vanilla, they increase the effectiveness of a weapon/tool, so i won't consider it at first, because they can change the stats of the base weapon.

You could get with a beast like 12-16 dmg on an iron broadsword XD wich will best/nearly best, in pure damage a basic iron cleaver, and you can get a (shitty but interssting) .88 attack speed iron cleaver.
(I use cobalt whenever i can for cleaver handles, then it gots like 1.05 or so attack speed, but it's better to give all to quarzt, except one, for necrotic :D)

**Comment by bonii-xx** [comment]
No point in trying to compare things if you leave out half the balance equation :P

**Comment by werff** [comment]
It's not half the balance, it's the customization part, and a custom weapons doesn't really need to be balanced XD
