### ISSUE TITLE
Shift Clicking Crafting Result can Delete Items.

### ISSUE THREAD

**Issue by AlgorithmX2** [SlimeKnights/TinkersConstruct#2201]
Shift Clicking the result of a crafting pattern puts them in the output stack of the crafting station,

Start with,
![Step1](https://dl.dropboxusercontent.com/u/9117298/tset/tic_1.png)
Shift Click Sticks.
![Step1](https://dl.dropboxusercontent.com/u/9117298/tset/tic_2.png)
Close and reopen,
![Step1](https://dl.dropboxusercontent.com/u/9117298/tset/tic_3.png)

Ahh my sticks are gone!

**Comment by OrionDevelopment** [comment]
Seems like a desync to me

**Comment by bonii-xx** [comment]
Looks like something ate the canMerge slot. I wonder if this already was in 1.8.

**Comment by bonii-xx** [comment]
1ed59156af2a029b08a3b8890123c11fdf395ebd
