### ISSUE TITLE
Compatibility between TC Crafting Stations and IC chests

### ISSUE THREAD

**Issue by SpartanSamuel** [SlimeKnights/TinkersConstruct#2202]
Feature Request: The feature of the Crafting Station from Tinkers' Construct that enables it to view adjacent chests is incompatible with any upgrade level of Iron Chest chests.

I'm not sure if I need to talk to the Iron Chest team or the Tinkers' Construct team so I'm posting this in both.

MC: 1.8.9
Forge: 11.15.1.1875
TC: 2.2.1
IC: 6.0.125.770

TC Issue: https://github.com/SlimeKnights/TinkersConstruct/issues/2202
IC Issue: https://github.com/progwml6/ironchest/issues/74

**Comment by bonii-xx** [comment]
Is a thing in 1.9

**Comment by SpartanSamuel** [comment]
Not to be rude, but could you please elaborate? Is 1.8.9 no longer a supported version?

**Comment by KnightMiner** [comment]
Basically, yes. The latest TConstruct version is for 1.9 where that feature was added, and developing for multiple minecraft versions is a pain

**Comment by bonii-xx** [comment]
No, 1.8.9 is dead. We're staying up to date, and will always develop for the current version. Major gamebreaking bugs might get hotfixed if the last release for the previous version was recently, but otherwise everything is developed for current version.
