### ISSUE TITLE
Redstone modifier on rapier (cosmetic suggestion)

### ISSUE THREAD

**Issue by AgentA1cr** [SlimeKnights/TinkersConstruct#2203]
The redstone modifier on the rapier creates a large bulge in the middle of the blade, which looks very odd. Would you consider tweaking it? Maybe shrink it, or move it towards the hand-guard, or both?

**Comment by KnightMiner** [comment]
The reason it's like that is so multiple modifiers make it look like a kabob :)

**Comment by AgentA1cr** [comment]
Still, if it were slightly less bulky, it could achieve the same effect without making a combination like quartz, redstone, and necrotic look so weirdly out of balance.
