### ISSUE TITLE
1.9.4-2.3.3 Stencil Table doesn't Make Stencils.

### ISSUE THREAD

**Issue by kreezxil** [SlimeKnights/TinkersConstruct#2205]
My game isn't crashing, there are no errors reported in the server or client console.

I put a stack of stencils in the stencil table. I click a button on the left side, I hear the button click, you can see it depress, but no stencil with the pattern is made.

This holds true with SSP mode as well.

We're using the FORGE 1.9.4-12.17.0.1987

**Comment by bonii-xx** [comment]
Check if it happens with only TiC and Mantle, and no other mod present.

**Comment by kreezxil** [comment]
yep, it works. Now for the hard part finding the mod that is causing the issue.

**Comment by Ezelberoth** [comment]
Apparently this was being caused by Cyclic, at least for me.
