### ISSUE TITLE
No heart canisters, 1.9.4?

### ISSUE THREAD

**Issue by fahlur** [SlimeKnights/TinkersConstruct#2209]
IDK if I missed something but I dont have the armor tab, even checked controls and the control isnt there and even hit "o" as well as theres no canisters, or hearts in the creative menu or the jeweled apple, now I have necrotic bones. thats about it. for that part :/

**Comment by GirafiStudios** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ

**Comment by fahlur** [comment]
thanks for the link

**Comment by LovelyFlare** [comment]
@GirafiStudios Ninja'ed me, but anyway, that isn't at the top of the list to be re-implemented, so don't expect them soon.

**Comment by fahlur** [comment]
Thanks for the link, just asking since I couldnt find any information about it other than standard tinkers. Whats the latest version with all the stuff includng but not limited to materals and you 2, and might smelting? 1.8?

**Comment by LovelyFlare** [comment]
That will all be in one book most likely.

**Comment by TheRoyalReaper** [comment]
so the armor we were used to use in 1.7.10 isn't coming back in the next versions?

**Comment by bonii-xx** [comment]
Nope.

**Comment by KnightMiner** [comment]
As an update on this, while there is nothing from the TiC team for heart canisters, [Baubley Heart Canisters](https://minecraft.curseforge.com/projects/baubley-heart-canisters) now exists.
