### ISSUE TITLE
Bronze "dense" trait is working opposite to its description.

### ISSUE THREAD

**Issue by sniarb** [SlimeKnights/TinkersConstruct#2212]
I was testing some tool parts in creative, and was trying to see how well the 'dense' trait from bronze worked. Based on its description, it is supposed to decrease the amount of durability damage the tool takes, the lower the durability is. However, I found that the opposite is true: the higher the durability, the less durability damage the tool takes. I had identical hammers with bronze large plates, except one I lowered the durability quickly by mining lots of glass. The hammer with the low durability then expended its remaining durability quickly while mining stone, while the hammer with full durability barely expended any durability while mining stone. I don't have any numbers, but its behavior is very clearly opposite what it is supposed to be. Not a big issue, but I thought it should be mentioned :). Thanks for the great mod!

**Comment by bonii-xx** [comment]
Version?

**Comment by sniarb** [comment]
Sorry, this was on 1.9.4 and 1.10, version 2.3.3a.
