### ISSUE TITLE
[1.10-2.3.3a] Drying Rack not rendering full blocks when renderTableItems is false

### ISSUE THREAD

**Issue by Paletuna** [SlimeKnights/TinkersConstruct#2213]
I had rendering table items set to false, and when I tried to put a clay block on a drying rack, it did not render. With it true, it does

**Comment by KnightMiner** [comment]
Drying racks are tables.

More specifically, the same rendering method is used on tables, casting tables/basins, and drying/item racks. The main reason for the config is to fix crashes should another mod break item models rather than to disable an aesthetic effect.

**Comment by bonii-xx** [comment]
The config option is for compatibility. If something crashes with the tables, it also crashes with the drying racks. And the casting basins. And everything else that displays items in the world. Tables were just the first thing to use it, hence the misleading name.

We should probably rename that.
