### ISSUE TITLE
[1.7.10] v1.8.8 Tinker armor Double jump not working

### ISSUE THREAD

**Issue by AnActualMoose** [SlimeKnights/TinkersConstruct#2215]
I understand that this has been fixed once before in a previous version, but it's happened again.

I can apply the modifiers to the wings and boots. But the double/triple/quad jumps never register.
Tested with just Forge 10.13.4.1558. I have Mantle 0.3.2b; Tinkers' Contruct 1.8.8 build 988; and Not Enough Keys 3.0.0b45. All the most up to date/recommended versions.

EDIT: further testing with modifying boots/wings with a tool forge or tinkers' table as opposed to just a crafting station gives the same results. No extra jumps.

Is there something I'm doing wrong?

Side note: Tinker's goggles can't have the night vision effect applied to them either.

**Comment by Techokami** [comment]
FYI, this issue is gonna be closed because 1.7.10 isn't supported by the dev team anymore. And I don't think the Tinker's Armor is even present anymore in the newer builds?

**Comment by AnActualMoose** [comment]
Yeah, I kind of figured it isn't supported anymore. Still though, it was fixed once before, so how did it break again?  Plus it could be an easy fix. No harm in asking right?

**Comment by LovelyFlare** [comment]
I'm playing a 1.7.10 modpack and I'm able to double jump and use night vision just fine...  The only problem is that the double jump doesn't register for me sometimes.

**Comment by AnActualMoose** [comment]
I didn't try using a potion brewed. I used vanilla creative. I'm not to concerned about the glasses.
I would very much like to figure out how to get the extra jumps working. Like I said, this problem was actually fixed in a previous update. It may actually work, but I still can't figure out HOW to get it to work even though I tried removing all the variables. Hence my OP saying "is there something I'm doing wrong?" :(

**Comment by bonii-xx** [comment]
I think it broke when some armor stuff changed. It has been broken for quite a while, last I remember it working was 1.6.4. But the armor stuff was so convoluted that nobody ever bothered to fix it. It may work sporadically, only in SSP, or depending on NotEnoughKeys. I don't remember exactly.

Anyway, closing the issue for organisational reasons, feel free to keep discussing in here though.

**Comment by AnActualMoose** [comment]
Hey, bonii, Thanks for the reply! Just thought I'd try my luck with seeing if there was a fix/workaround or that perhaps it was easy to patch. Hearing from you that it's not an easy fix means I guess I'll be on my way.

Thanks to you and all the others for developing such a fantastic mod!

**Comment by LovelyFlare** [comment]
@AnActualMoose 
![2016-07-02_20 49 24](https://cloud.githubusercontent.com/assets/14182009/16540414/92fc6a60-4096-11e6-956f-821e948268d0.png)
![Uploading 2016-07-02_20.50.56.png…]()

Double Jump
![2016-07-02_20 51 23](https://cloud.githubusercontent.com/assets/14182009/16540420/c56e81a4-4096-11e6-8e72-5dd19d6dd72f.png)

**Comment by AnActualMoose** [comment]
@LovelyFlare, Thank you! I wonder what I'm doing wrong? :|
