### ISSUE TITLE
[1.10-2.3.3a] Ardite Petramor trait not working 

### ISSUE THREAD

**Issue by Crazy-KSK** [SlimeKnights/TinkersConstruct#2216]
When using a mining tool with Petramor, Cobble-/stone is dropped and no durability is added to the tool

**Comment by bonii-xx** [comment]
Bad RNG. Petramor works.

**Comment by SquidNeko** [comment]
Doesnt work in FTB Revelation. Minecraft 1.12.2
If you are going to say bad RNG. Its extremely bad RNG. Been going for half an hour, mining only stone in my mine, counting how much i mined each time and it does not absorb any stone what so ever for durability.
