### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by NightWng120** [SlimeKnights/TinkersConstruct#2221]
When ever I try to use my forge profile to play tinkers construct, my game crashes even though I have the correct forge version and tinkers construct version which are both 1.7.10.

These are the screenshots of the crash report.

![screenshot 22](https://cloud.githubusercontent.com/assets/20262569/16543679/dbe8b238-40af-11e6-968d-5dce79ac5a97.png)

![screenshot 23](https://cloud.githubusercontent.com/assets/20262569/16543680/e79ce46e-40af-11e6-91ab-8660877c8212.png)

**Comment by AlterAkima** [comment]
No mods were loaded according to the log, there's no indication that it's Tinkers' fault.
Also, 1.7.10 is not supported anymore.

**Comment by bonii-xx** [comment]
Yeah, this is not related to Tinkers. Might be some of your files are corrupt, or your setup simply is incorrect.
