### ISSUE TITLE
MC1.10 / TC2.3.3a - Lapis does not apply Looting to Shuriken

### ISSUE THREAD

**Issue by Sarethor** [SlimeKnights/TinkersConstruct#2222]
Unsure if this is a design decision so I figured I'd post it.   Haven't found any other issues with Shuriken thusfar.  Thanks.

![shuriken-looting](https://cloud.githubusercontent.com/assets/20263752/16544152/310fad3a-40af-11e6-8a89-2a48aa00813a.PNG)

**Comment by bonii-xx** [comment]
As of yet, a technical limitation in Minecraft. Might get fixed soon through forge.
