### ISSUE TITLE
Disabling the spawning of the Materials and You book

### ISSUE THREAD

**Issue by xbony2** [SlimeKnights/TinkersConstruct#2223]
It would be great if there was a way to disable the spawning of the "Materials and You" book from spawning in a player's inventory when they join the game. Some users might prefer it in its craftable form, and additionally it would be unimmersive if used in a map-based modpack where a player might not have access to TIC's tools and utilities.

**Comment by bonii-xx** [comment]
Guess we can do that for custom startingitems packs.

**Comment by xbony2** [comment]
you have wide eyes

stop stealing my name btw

**Comment by bonii-xx** [comment]
I've had mine longer, wanna bet? ;)

**Comment by xbony2** [comment]
[o_O](https://i.imgur.com/wwbR36D.png)

I've used since 2nd grade \o/

**Comment by bonii-xx** [comment]
I'm boni. The bonii-xx just is the automatic suffix from github because the name was taken ;P

**Comment by xbony2** [comment]
Sort of the same thing with "bony".
