### ISSUE TITLE
[1.9.4] Server crash

### ISSUE THREAD

**Issue by drewbit** [SlimeKnights/TinkersConstruct#2226]
Happened randomly, here's the log:

http://pastebin.com/BA4LhSUv

Tinkers Version: TConstruct-1.9.4-2.3.3
Forge Version: forge-1.9.4-12.17.0.1976-universal

Let me know if any more information is required.

**Comment by bonii-xx** [comment]
You got an invalid fluid. Probably caused by your minetweaker.
