### ISSUE TITLE
Materials and you part 2 doesn't exist? (1.10.2, 2.3.3)

### ISSUE THREAD

**Issue by J-Dude** [SlimeKnights/TinkersConstruct#2227]
The recipe doesn't work and it isn't in the creative inventory. And the wiki is outdated so I'm missing A LOT of info

**Comment by KnightMiner** [comment]
Its all one book now, though the book is a little WIP (though it does have the important information on the new materials, and many other mechanics are similar to TiC1)

**Comment by J-Dude** [comment]
Not really. I get no info on smelting or tier 2 tools, and none of the recipes for anything are in the book.

**Comment by LovelyFlare** [comment]
@J-Dude Use JEI

**Comment by m1zark** [comment]
Luckily I remembered most of the recipes from before... but it probably would be helpful to have more smelting info in there. Like how to get Manyullyn, etc.

**Comment by KnightMiner** [comment]
Use JEI. Its a lot easier to add all the recipes there as you will then be able to look at them if the recipes change (a book would not be so dynamic) and the interface is easier for recipes than a book could be. Also, with the amount of recipes updating the book would be a pain.

**Comment by draconyc** [comment]
Might I suggest giving the new TC2 a dependency on JEI if that is going to be the case?  Most people do not use JEI as a matter of rote.

**Comment by bonii-xx** [comment]
Feel free to supplement additional book pages via PR

**Comment by draconyc** [comment]
I'm not sure how to do that, but if you can tell me how or point me at a tutorial or something and my doing so would actually help, I would be willing to try.

**Comment by bonii-xx** [comment]
[The book is defined in json](https://github.com/SlimeKnights/TinkersConstruct/tree/master/resources/assets/tconstruct/book), and can be extended by extending the index/sections with more pages. There is no tutorial or documentation, but there's a few examples in there and [in Mantle](https://github.com/SlimeKnights/Mantle/tree/master/src/main/resources/assets/mantle/books/TestBook)

**Comment by KnightMiner** [comment]
Closing from lack of response. To anyone in the future asking about part 2: we only have one book now, but feel free to PR in additional pages into the current book.
