### ISSUE TITLE
TCon and TechReborn Crash

### ISSUE THREAD

**Issue by Peach774** [SlimeKnights/TinkersConstruct#2229]
1.10.2 LAN - Scrolling through the tinkers construct creative menu and reachieved this crash, since it mentions both tech reborn and tinkers construct I will also be posting this on tech reborn's github.
http://pastebin.com/8mg4bckf

**Comment by KnightMiner** [comment]
Looks like its TechReborn's fault, they are registering an invalid metadata for their block to the oredictionary and failing to catch the error in `getStateFromMeta()`.

**Comment by bonii-xx** [comment]
Might be worth to enable the debug module in TiC, that does a sanity check on startup for such things. Then you can tell them all the things that might cause problems ;)
