### ISSUE TITLE
Suggestion - rapiers can back-pedal left & right, from pesky skeletons.

### ISSUE THREAD

**Issue by eggyplantsu** [SlimeKnights/TinkersConstruct#2230]
One doesn't simply dodge backwards to avoid bullets and arrows.

**Comment by LovelyFlare** [comment]
Read the [FAQ](https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ).

Also, just turn 90 degrees one direction and use the rapier...

**Comment by bonii-xx** [comment]
You also don't fight bullets and arrows when swordfighting :P
