### ISSUE TITLE
Blasting III causes blocks with a hardness of 0 to be unbreakable

### ISSUE THREAD

**Issue by KnightMiner** [SlimeKnights/TinkersConstruct#2232]
Any tool  with Blasting III cannot break blocks with a hardness of 0. This is due to having a hardness of 0 multiplying the speed by 0 causing no speed. The reason it only happens on Blasting III is due to [this line](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/modifiers/ModBlasting.java#L68), as the original speed is removed at max level but added at lower ones.

**Comment by bonii-xx** [comment]
Heh, there are blocks with hardness 0?

**Comment by laz2727** [comment]
Most plants are.
minecraft.gamepedia.com/Breaking#Blocks_by_hardness

**Comment by C1ffisme** [comment]
Not exactly sure how well this would work, or if it's balanced, but you could do:
```
if (speed == 0) {
    float totalSpeed = (speed + 1) * weight1 + event.getOriginalSpeed() * weight2;
} else {
    float totalSpeed = speed * weight1 + event.getOriginalSpeed() * weight2;
}
```

**Comment by KnightMiner** [comment]
It doesn't need to be that complicated. Blocks with a hardness of 0 break instantly, so you could just entirely skip the blasting code for them.

There is already a check in place to stop the AOE from breaking a block with a larger hardness than the center one, so it should work just fine.

**Comment by C1ffisme** [comment]
> It doesn't need to be that complicated. Blocks with a hardness of 0 break instantly, so you could just entirely skip the blasting code for them as instant is instant.

Ah, okay. I didn't check the code very closely.
