### ISSUE TITLE
1.8.9 bug (Can't Place Tinkers Construct Blocks/Items)

### ISSUE THREAD

**Issue by SamuelDancing** [SlimeKnights/TinkersConstruct#2235]
so i tried to place a block from Tinkers Construct for 1.8.9 and it disappeared as well as the one in my inventory now i am on a server with bukkit and it is creative spawned any same with the tool parts if i try to open a chest same with all the other items from the mod any way to fix this?

(i tried it in a single player world and the items worked just fine)

**Comment by bonii-xx** [comment]
Ask your server owner/bukkit plugin/don't place blocks in spawn protection.
