### ISSUE TITLE
(1.10.2) - Pickaxe with Well-Established gives xp when mining any block

### ISSUE THREAD

**Issue by RyanP1991** [SlimeKnights/TinkersConstruct#2236]
Pickaxe with the trait Well-Established gives xp when mining any block even blocks which shouldn't give it for example machines or chisel blocks not sure if this is a bug or not but thought I would still report it.

Minecraft Version - 1.10.2
Using Forge - 12.18.0.2007
Tinkers Version - 1.10-2.3.3a

**Comment by bonii-xx** [comment]
Working as intended, has a small chance to do that.
