### ISSUE TITLE
[Issue] 1.10-2.3.3a - Magma Cubes and Magma Islands

### ISSUE THREAD

**Issue by WhatThePuckPT** [SlimeKnights/TinkersConstruct#2237]
In the latest version, Magma Cubes seem to be spawning excessively in Magma Islands.
![2016-07-08_23 30 29](https://cloud.githubusercontent.com/assets/20363269/16703414/241a9eb8-4565-11e6-963b-f86cdbf057b9.png)
I've tried to kill them off with a killing item I've made (the book), killing them with the /kill command, but as much as I spam the command, once I get away, they respawn in mass numbers.
Had to change to creative to stop getting mobbed.
I am sure that none of the other mods I have installed are causing this issue.

**Comment by bonii-xx** [comment]
Happens due some vanilla spawn behaviour. But should be better in the next version.
