### ISSUE TITLE
Using the hammer

### ISSUE THREAD

**Issue by TheRoyalReaper** [SlimeKnights/TinkersConstruct#2238]
When I'm using a cobalt hammer in the nether(Survival)
I don't break a 3x3 area, I break only one block.
I don't know if it's tinkers' fault or minecraft not fast enough to update the block destruction.
I were using a cobalt hammer head, 2 large cobalt plates and an ardite tough rod

**Comment by KnightMiner** [comment]
What version are you using? If you are on 1.10, make sure you use the version built for 1.10, as the 1.9.4 version has that issue when used in 1.10

**Comment by TheRoyalReaper** [comment]
I use 1.10 for 1.10

**Comment by bonii-xx** [comment]
Reproduce it with only tic and mantle, with the latest versions. I guarantee you it'll work.

**Comment by TheRoyalReaper** [comment]
you're saying it's other mods fault? because I'm using the latest versions for 1.10.2

**Comment by bonii-xx** [comment]
Yes, that's exactly what I'm saying. Such a bug wouldn't survive 2 weeks undetected.
