### ISSUE TITLE
Crash when displaying Tinker's construct tool forge in JEI

### ISSUE THREAD

**Issue by InsaneJ** [SlimeKnights/TinkersConstruct#2239]
Not sure if this is a JEI issue or a Tinker's issue. Also posted here: https://github.com/mezz/JustEnoughItems/issues/351

Using jei_1.10.2-3.7.5.227 and TConstruct-1.10-2.3.3a the game crashes when displaying Tinker's tool forge.

Crash report: http://paste2.org/KPfzZkNV

**Comment by bonii-xx** [comment]
Same as #2229
Techreborns fault.
