### ISSUE TITLE
hammer on tool station

### ISSUE THREAD

**Issue by raalpe** [SlimeKnights/TinkersConstruct#2240]
when i right click with a hammer on a tool station it crash

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-39.jar)
  LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  EnderCorePlugin (EnderCore-1.10-0.4.0.33-alpha.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
  LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 09-07-16 22:05
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.util.ResourceLocation.func_177516_a(SourceFile:30)
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:21)
	at net.minecraft.item.Item.func_111206_d(Item.java:126)
	at xreliquary.util.RegistryHelper.getItemFromName(RegistryHelper.java:11)
	at xreliquary.items.ItemSojournerStaff.func_77624_a(ItemSojournerStaff.java:327)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:610)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:136)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.util.ResourceLocation.func_177516_a(SourceFile:30)
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:21)
	at net.minecraft.item.Item.func_111206_d(Item.java:126)
	at xreliquary.util.RegistryHelper.getItemFromName(RegistryHelper.java:11)
	at xreliquary.items.ItemSojournerStaff.func_77624_a(ItemSojournerStaff.java:327)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:610)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:136)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)

-- Screen render details --
Details:
	Screen name: slimeknights.tconstruct.tools.client.GuiToolStation
	Mouse location: Scaled: (407, 336). Absolute: (814, 376)
	Screen size: Scaled: (840, 525). Absolute: (1680, 1050). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['eyz43nqc'/133, l='MpServer', x=166,22, y=5,00, z=-45,77]]
	Chunk stats: MultiplayerChunkCache: 622, 622
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-104,64,256), Chunk: (at 8,4,0 in -7,16; contains blocks -112,0,256 to -97,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 378106 game time, 378106 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 49 total; [EntityItem['item.tile.stone.stone'/134, l='MpServer', x=167,74, y=5,00, z=-45,90], EntityPig['Pig'/168, l='MpServer', x=86,26, y=64,00, z=-4,56], EntityPig['Pig'/427, l='MpServer', x=121,30, y=63,00, z=-89,52], EntityPig['Pig'/428, l='MpServer', x=125,72, y=63,00, z=-90,74], EntityPig['Pig'/429, l='MpServer', x=116,20, y=64,00, z=-95,96], EntityPig['Pig'/430, l='MpServer', x=120,34, y=63,00, z=-90,56], EntitySheep['Sheep'/431, l='MpServer', x=128,77, y=63,00, z=-122,36], EntityPlayerSP['eyz43nqc'/133, l='MpServer', x=166,22, y=5,00, z=-45,77], EntityPig['Pig'/185, l='MpServer', x=104,60, y=63,00, z=-4,76], EntitySheep['Sheep'/441, l='MpServer', x=121,03, y=63,00, z=-126,93], EntitySheep['Sheep'/442, l='MpServer', x=126,52, y=62,00, z=-109,73], EntityPig['Pig'/444, l='MpServer', x=188,76, y=64,00, z=-115,19], EntityPig['Pig'/189, l='MpServer', x=111,23, y=63,00, z=-18,46], EntityPig['Pig'/190, l='MpServer', x=106,47, y=63,00, z=-30,21], EntityItem['item.tile.gravel'/323, l='MpServer', x=167,50, y=6,00, z=6,84], EntityBat['Bat'/324, l='MpServer', x=175,25, y=28,10, z=13,20], EntityBat['Bat'/325, l='MpServer', x=174,52, y=28,10, z=14,84], EntityBat['Bat'/327, l='MpServer', x=183,68, y=17,10, z=-5,81], EntityPig['Pig'/455, l='MpServer', x=114,19, y=63,00, z=-6,24], EntitySquid['Squid'/456, l='MpServer', x=158,15, y=56,00, z=-68,09], EntitySquid['Squid'/457, l='MpServer', x=161,85, y=58,25, z=-69,06], EntityPig['Pig'/459, l='MpServer', x=201,31, y=63,00, z=-108,43], EntityPig['Pig'/460, l='MpServer', x=192,44, y=64,00, z=-105,19], EntityPig['Pig'/461, l='MpServer', x=194,28, y=64,00, z=-108,35], EntityPig['Pig'/462, l='MpServer', x=197,49, y=64,00, z=-113,34], EntityPig['Pig'/463, l='MpServer', x=205,66, y=66,01, z=-120,86], EntityPig['Pig'/464, l='MpServer', x=201,22, y=65,00, z=-119,76], EntityPig['Pig'/465, l='MpServer', x=206,22, y=66,00, z=-122,53], EntitySquid['Squid'/467, l='MpServer', x=169,31, y=61,28, z=-25,40], EntityBat['Bat'/339, l='MpServer', x=166,29, y=23,10, z=-11,37], EntityBat['Bat'/340, l='MpServer', x=163,25, y=26,10, z=-2,75], EntitySquid['Squid'/468, l='MpServer', x=152,08, y=60,76, z=-9,87], EntityBat['Bat'/469, l='MpServer', x=190,43, y=22,96, z=-58,52], EntityBat['Bat'/341, l='MpServer', x=168,69, y=24,10, z=-8,20], EntityBat['Bat'/470, l='MpServer', x=190,38, y=22,91, z=-65,57], EntityBat['Bat'/342, l='MpServer', x=165,48, y=26,10, z=-9,25], EntityBat['Bat'/471, l='MpServer', x=183,07, y=21,78, z=-59,04], EntityBat['Bat'/343, l='MpServer', x=171,46, y=23,10, z=-11,47], EntityBat['Bat'/472, l='MpServer', x=208,45, y=32,85, z=-56,64], EntityBat['Bat'/344, l='MpServer', x=234,10, y=44,07, z=-83,32], EntityBat['Bat'/345, l='MpServer', x=202,75, y=28,86, z=-63,49], EntitySquid['Squid'/473, l='MpServer', x=143,38, y=60,63, z=-1,00], EntityBat['Bat'/346, l='MpServer', x=200,77, y=34,26, z=-71,26], EntityBat['Bat'/347, l='MpServer', x=181,79, y=30,10, z=24,51], EntityBat['Bat'/359, l='MpServer', x=186,25, y=32,10, z=3,25], EntityPig['Pig'/365, l='MpServer', x=230,50, y=66,00, z=-44,50], EntityPig['Pig'/366, l='MpServer', x=230,50, y=66,00, z=-44,50], EntityPig['Pig'/367, l='MpServer', x=230,50, y=67,00, z=-42,50], EntityPig['Pig'/368, l='MpServer', x=231,50, y=67,00, z=-40,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 540627672 bytes (515 MB) / 2348285952 bytes (2239 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.0.2000 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10-12.18.0.2000-1.10.0.jar) 
	UCHIJAAAA	Forge{12.18.0.2000} [Minecraft Forge] (forge-1.10-12.18.0.2000-1.10.0.jar) 
	UCHIJAAAA	autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3.jar) 
	UCHIJAAAA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10-3.0.1a.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	bdlib{1.12.0.2} [BD Lib] (bdlib-1.12.0.2-mc1.9.4.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10-alpha-1.0.0.jar) 
	UCHIJAAAA	JEI{3.7.1.219} [Just Enough Items] (jei_1.10-3.7.1.219.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.2-48} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-48.jar) 
	UCHIJAAAA	Botania{r1.8-311} [Botania] (Botania-unofficial.r1.8-311.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.5} [Chameleon] (Chameleon-1.9.4-2.1.5.jar) 
	UCHIJAAAA	mcmultipart{1.2.0} [MCMultiPart] (MCMultiPart-1.2.0-universal.jar) 
	UCHIJAAAA	CharsetLib{0.3.0-pre12} [â€½] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetAudio{0.3.0-pre12} [â™«] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetCarts{0.3.0-pre12} [U] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetDecoration{0.3.0-pre12} [âš?] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetDrama{0.3.0-pre12} [!] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetFarming{0.3.0-pre12} [;] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetGates{0.3.0-pre12} [&] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetPipes{0.3.0-pre12} [|] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetStorage{0.3.0-pre12} [#] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetTweaks{0.3.0-pre12} [*] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetWires{0.3.0-pre12} [+] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetWrench{0.3.0-pre12} [/] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	ChestTransporter{2.5.0} [Chest Transporter] (ChestTransporter-1.10-2.5.0.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9.4-0.0.5.29.jar) 
	UCHIJAAAA	chiselsandbits{11.5} [Chisels & Bits] (chiselsandbits-11.5.jar) 
	UCHIJAAAA	combathelp{1.0.3} [Combat Help] (combathelp-1.9.4-1.0.3.jar) 
	UCHIJAAAA	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9.4.jar) 
	UCHIJAAAA	compasscoords{1.10-3.1.6} [Compass Co-ords] (CompassCoords-1.10-3.1.6.jar) 
	UCHIJAAAA	ComputerCraft{1.80pr0} [ComputerCraft] (ComputerCraft1.80pr0.jar) 
	UCHIJAAAA	cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar) 
	UCHIJAAAA	CustomMainMenu{2.0.1} [Custom Main Menu] (CustomMainMenu-MC1.9.4-2.0.1.jar) 
	UCHIJAAAA	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UCHIJAAAA	deepresonance{1.2.0beta35} [DeepResonance] (deepresonance-1.9.4-1.2.0beta35.jar) 
	UCHIJAAAA	endercore{1.10-0.4.0.33-alpha} [EnderCore] (EnderCore-1.10-0.4.0.33-alpha.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10-3.0.0.57_alpha} [Ender IO] (EnderIO-1.10-3.0.0.57_alpha.jar) 
	UCHIJAAAA	shetiphiancore{3.2.6} [ShetiPhian-Core] (shetiphiancore-1.9.4-3.2.6.jar) 
	UCHIJAAAA	endertanks{1.3.6} [EnderTanks] (endertanks-1.9.4-1.3.6.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.1.jar) 
	UCHIJAAAA	forestry{5.1.7.188} [Forestry] (forestry_1.10-5.1.7.188.jar) 
	UCHIJAAAA	forgeanalytics{0.0.0.13} [Forge Analytics] (ForgeAnalytics-1.10-0.0.0.19.jar) 
	UCHIJAAAA	ftbl{2.1.0} [FTBLib] (FTBLib-1.9.4-2.1.0-pre2.jar) 
	UCHIJAAAA	ftbu{2.1.0} [FTBUtilities] (FTBUtilities-1.9.4-2.1.0-pre2.jar) 
	UCHIJAAAA	IC2{2.6.1-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.1-ex110.jar) 
	UCHIJAAAA	advgenerators{0.9.20.2} [Advanced Generators] (generators-0.9.20.2-mc1.9.4.jar) 
	UCHIJAAAA	gravestone{1.4.2} [Gravestone] (Gravestone Mod 1.4.2.jar) 
	UCHIJAAAA	inventorytweaks{1.61-beta-57-c028bbc} [Inventory Tweaks] (InventoryTweaks-1.61-beta-57.jar) 
	UCHIJAAAA	IronChest{7.0.5.793} [Iron Chest] (ironchest-1.10-7.0.5.793.jar) 
	UCHIJAAAA	itemscroller{0.5.1} [Item Scroller] (itemscroller-1.10.2-0.5.1.jar) 
	UCHIJAAAA	journeymap{1.9.4-5.2.3} [JourneyMap] (journeymap-1.9.4-5.2.3-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.6.40} [Just Enough Resources] (JustEnoughResources-1.10-0.4.6.40.jar) 
	UCHIJAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	Morpheus{1.10-3.1.6} [Morpheus] (Morpheus-1.10-3.1.6.jar) 
	UCHIJAAAA	MouseTweaks{2.6.3} [Mouse Tweaks] (MouseTweaks-2.6.3-mc1.9.4.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar) 
	UCHIJAAAA	progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar) 
	UCHIJAAAA	Psi{r1.0-36} [Psi] (Psi-r1.0-36.jar) 
	UCHIJAAAA	Quark{beta-39} [Quark] (Quark-beta-39.jar) 
	UCHIJAAAA	randomthings{3.7.4} [Random Things] (RandomThings-MC1.10-3.7.4.jar) 
	UCHIJAAAA	StorageDrawers{1.9.4-3.1.11} [Storage Drawers] (StorageDrawers-1.9.4-3.1.11.jar) 
	UCHIJAAAA	refinedstorage{0.8.5} [Refined Storage] (refinedstorage-0.8.5.jar) 
	UCHIJAAAA	xreliquary{1.10-1.3.2.416} [Reliquary] (Reliquary-1.10-1.3.2.416.jar) 
	UCHIJAAAA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJAAAA	rftools{5.01} [RFTools] (rftools-1.10-5.01.jar) 
	UCHIJAAAA	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCHIJAAAA	soulshardstow{1.10-2.5.0-34} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10-2.5.0-34.jar) 
	UCHIJAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UCHIJAAAA	theoneprobe{1.0.12} [The One Probe] (theoneprobe-1.10-1.0.12.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UCHIJAAAA	ICSE{1.1.0.0} [I Can See Everything] (Wawla-1.10-2.3.0.193.jar) 
	UCHIJAAAA	wawla{2.3.0.193} [What Are We Looking At] (Wawla-1.10-2.3.0.193.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-39.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10-0.4.0.33-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)
  
LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  lumien.custommainmenu.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.69' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.0.2-48.jar
		* BotaniaAPI (79) from Botania-unofficial.r1.8-311.jar
		* CharsetAPI (0.1) from Charset-0.3.0-pre12.jar
		* CharsetAPI|Audio (0.0) from Charset-0.3.0-pre12.jar
		* CharsetAPI|Lib (0.2) from Charset-0.3.0-pre12.jar
		* CharsetAPI|Pipes (0.3) from Charset-0.3.0-pre12.jar
		* CharsetAPI|Storage (0.1) from Charset-0.3.0-pre12.jar
		* CharsetAPI|Tape (0.0) from Charset-0.3.0-pre12.jar
		* CharsetAPI|Wires (0.3) from Charset-0.3.0-pre12.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.5.29.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.5.29.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-11.5.jar
		* CoFHAPI (1.8.9R1.2.0B1) from forestry_1.10-5.1.7.188.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from theoneprobe-1.10-1.0.12.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
		* compactstorage (v2.0.0a) from compactstorage-2.1-1.9.4.jar
		* ComputerCraft|API (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Lua (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Media (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Permissions (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Redstone (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Turtle (1.80pr0) from ComputerCraft1.80pr0.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.4-1.2.0beta35.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.292.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10-3.0.0.57_alpha.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10-3.0.0.57_alpha.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10-3.0.0.57_alpha.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10-3.0.0.57_alpha.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|core (5.0.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|greenhouse (5.0.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.10-5.1.7.188.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10-5.1.7.188.jar
		* IC2API (1.0) from industrialcraft-2-2.6.1-ex110.jar
		* jeresources|API (0.4.6.40) from JustEnoughResources-1.10-0.4.6.40.jar
		* journeymap|client-api (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
		* journeymap|client-api-display (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
		* journeymap|client-api-event (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
		* journeymap|client-api-model (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
		* journeymap|client-api-util (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
		* JustEnoughItemsAPI (4.0.0) from jei_1.10-3.7.1.219.jar
		* McJtyLib (1.10-1.9.5) from mcjtylib-1.10-1.9.5.jar
		* PsiAPI (2) from Psi-r1.0-36.jar
		* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.10-2.5.0-34.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-0.8.5.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.11.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.11.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.11.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.11.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-0.8.5.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-0.8.5.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-0.8.5.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.11.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Rasmus/Documents/Curse/Minecraft/Instances/FTB%20Unstable%201.10/mods/mcjtylib-1.10-1.9.5.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Rasmus/Documents/Curse/Minecraft/Instances/FTB%20Unstable%201.10/mods/mcjtylib-1.10-1.9.5.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Rasmus/Documents/Curse/Minecraft/Instances/FTB%20Unstable%201.10/mods/mcjtylib-1.10-1.9.5.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Rasmus/Documents/Curse/Minecraft/Instances/FTB%20Unstable%201.10/mods/mcjtylib-1.10-1.9.5.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider.class' could not be loaded (see strack trace above)
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Rasmus/Documents/Curse/Minecraft/Instances/FTB%20Unstable%201.10/mods/mcjtylib-1.10-1.9.5.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Rasmus/Documents/Curse/Minecraft/Instances/FTB%20Unstable%201.10/mods/mcjtylib-1.10-1.9.5.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Rasmus/Documents/Curse/Minecraft/Instances/FTB%20Unstable%201.10/mods/mcjtylib-1.10-1.9.5.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Rasmus/Documents/Curse/Minecraft/Instances/FTB%20Unstable%201.10/mods/mcjtylib-1.10-1.9.5.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Rasmus/Documents/Curse/Minecraft/Instances/FTB%20Unstable%201.10/mods/mcjtylib-1.10-1.9.5.jar!/cofh/api/energy/TileEnergyHandler.class

	Launched Version: forge-12.18.0.2000
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.69, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

**Comment by bonii-xx** [comment]
Seems to be an issue with Reliquary. Paging @P3pp3rF1y

**Comment by P3pp3rF1y** [comment]
I have no idea why sojourner staff tooltip code is called as part of this stack trace, but yes there's apparently an issue with tooltip in some cases. i am going to track this on my side
