### ISSUE TITLE
Smeltery server crash. [1.9.4]

### ISSUE THREAD

**Issue by Claycorp** [SlimeKnights/TinkersConstruct#2241]
http://pastebin.com/AL3m0Yu5

**Comment by bonii-xx** [comment]
Invalid fluid from another mod. Do you remember what was in the smeltery or what you were melting down?

**Comment by Claycorp** [comment]
The person who had it happen said he was melting down an iron binding and standing in the smeltery. It crashed after about 10 ticks of damage.
Was tested again today and it wasn't reproducible.

You can see it happen here https://www.twitch.tv/deadpine/v/77093655 at 4:10:50

**Comment by bonii-xx** [comment]
Ok, so it's blood related, suddenly things make much more sense. Does the pack have BloodMagic? I wonder if it's using the wrong fluid.

**Comment by Claycorp** [comment]
`    UCHIJAAAA   BloodMagic{1.9.4-2.0.2-48} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-48.jar)
    UCHIJAAAA   BloodArsenal{1.9.4-2.0.0-10} [Blood Arsenal] (BloodArsenal-1.9.4-2.0.0-10.jar)`
Yes according to the crash. If it is using the wrong fluid it should be reproducible but it has been tried multiple times with no resulting crash. So something really funky must be going on. If you have anything that needs to be tested you can find the pack here http://minecraft.curseforge.com/projects/pinefresh-1-9?gameCategorySlug=modpacks&projectID=238846 
Else it will need to wait till tomorrow when I can get someone else as I don't have a working GPU.

**Comment by bonii-xx** [comment]
I found one potential case where a wrong fluid could get into the smeltery like in the stream.. however blood is the only liquid where it shouldn't be possible. Do you know if this was a server or a client crash?

**Comment by Claycorp** [comment]
Server.

**Comment by x3n0ph0b3** [comment]
Again, blood related crash. Was attempting to push blood to a basin: http://pastebin.com/RHb0zjRX

**Comment by bonii-xx** [comment]
I wonder if Way is doing weird things, or if I'm using cached liquids somewhere
