### ISSUE TITLE
[Solved] Client crash after swaping the hotbar over the belt on 1.7.10

### ISSUE THREAD

**Issue by davedavee** [SlimeKnights/TinkersConstruct#2242]
Hey, I remember that I've had this issue before, but updating to the newer version helped.

I've add two new mods to my modpack (Magical Crops and Pneumatic Craft) and updated Magical Bees what caused a chain reaction of issues with old version of depending mods. I've slowly updated necessary mods (Forestry to 4.2.14.62, Forge to 1614, Gendustry to 1.6.3.132, bdlib to 1.9.4.109 and after some problems caused by Forestry (client crash when attempting to show any recipe in NEI) even NEI to 1.0.5.120 and NEIIntegration  to 1.1.2). Everything seems to be fine until I tried to switch hotbars, what caused a crash (everything else seems to be working just fine). When I loaded the game again, the hotbars were swapped and after attempt to swap crash again. So I've updated TiC to 1.8.8 (from 1.8.7) and now after restarting the game I've still got the same hotbar.

Not sure what causing it, but thing it might be Forestry as it caused problem in other mods as well. Could you confirm that? Or have I made a mistake elsewhere? Thx

Here's pastebin of the error: [http://pastebin.com/iLprnmRU]

edit: I've also tried it without OptiFine and still same results.

**Comment by davedavee** [comment]
PROBLEM SOLVED!

After pressing Y what was bind for Changing Yeta wrench mode and Pneumatic Helmet Debugging Drone the game crashed again with totally same error output (tconstruct error on the first line). That obviously has nothing to do with TiC! I started to be suspicios about PneumaticCraft. When I checked their Issue tracker I found the answer: Update NotEnoughKeys. Woala ...

**Comment by LovelyFlare** [comment]
Please close the issue in order to keep the issue tracker clean.
