### ISSUE TITLE
Glowing can cause the tool's durability to drop rapidly client side

### ISSUE THREAD

**Issue by KnightMiner** [SlimeKnights/TinkersConstruct#2243]
For some odd reason, `world.getLight(pos)` returns different values on client and server based on the current sky light (which seems related to the current entity position), causing the client side to constantly drop the tools durability when the server side thinks no block is needed (as the client thinks its constantly placing more glow blocks, but they are never actually placed by the client there).

A quick test shows that wrapping the whole `onUpdate()` event in a `!world.isRemote` check fixes this while still updating the durability/block placing on the client, but I don't want to make a PR until double checking that there isn't something else needing to be run client side.

Edit: nope, never mind. Its not skylight, its the entity position that's different across the two. If you are too close to an edge the X or Z coordinate can be off by 1. This might officially come down to a Forge or vanilla issue, but it does seem fixable on our side simply by not running the code on the client side at all

**Comment by bonii-xx** [comment]
Right, that's only checked clientside because I wanted some sort of effect for it, but I scrapped that. Should be easy enough to fix.
