### ISSUE TITLE
[1.10.2] Crash upon placing a cloud block from Chisel onto slimy grass

### ISSUE THREAD

**Issue by Zaweri** [SlimeKnights/TinkersConstruct#2244]
http://pastebin.com/GaAFm2HD

The server keeps crashing when the chunk that contains said block is loaded. A player on our server placed a cloud block onto slimy grass, and this occurred. I will report this to the Chisel mod authors as well.

**Comment by alexbegt** [comment]
It seems that the release version of Tinkers Construct is a old build, because this crash was fixed with 37cf0b2, @bonii-xx has to release a new release build for it to be fixed completely.

**Comment by bonii-xx** [comment]
What are you talking about alex, that's a bug in chisel :P
Contact the chisel devs.

**Comment by tterrag1098** [comment]
Um, no? You pass your own state into our block's getLightOpacity method. This is completely invalid.

**Comment by bonii-xx** [comment]
Ah, the good old 1.9 update.

**Comment by slidingmike** [comment]
Was this not included in the alpha release for today? I'm still experiencing the error on our server. Player logs in, and the crash happens with the above crash reports.

**Comment by alexbegt** [comment]
Are you running TConstruct-1.10.2-2.4.0.jenkins312.jar @slidingmike

**Comment by slidingmike** [comment]
Yes. The one from just a few hours ago.

**Comment by KnightMiner** [comment]
Seems there still is the wrong state being passed along [here](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/world/block/BlockSlimeGrass.java#L111). Its using the current state for opacity checking instead of the one above the location being spread to.

**Comment by slidingmike** [comment]
Any chance we could get hotfix for this?

**Comment by bonii-xx** [comment]
It'll be in the next release, be it dev build or full release.
