### ISSUE TITLE
Fluid distruction using pipes/tanks on Smeltery (1.10.2)

### ISSUE THREAD

**Issue by Karmacopper** [SlimeKnights/TinkersConstruct#2250]
Using an EnderIO tank to help automate metal block production I found the last run would be short although my smeltery is 3x3 and I'm hoppering in a number of ore blocks divisible by 9. Spoke briefly with EIO devs on IRC and they feel this bug is at this end.

Reproduction of issue: Melt 9 ore blocks, place EIO tank (back face; pull, bottom face; push) instead of a faucet, hopper below the casting basin. I end up 4mb short when casting the second block.

TiCon version: 2,3,3a
EIO version: 3.0.1.67_bet
FOrge version: 12.18.1.2011

**Comment by HenryLoenwind** [comment]
fixed in EnderCore 0.4.1.56
