### ISSUE TITLE
Tinkers construct for 1.10.2 but no mantle for 1.10.2

### ISSUE THREAD

**Issue by dwaindibbly** [SlimeKnights/TinkersConstruct#2251]
How can you have Tinkers Construct on minecraft 1.10.2 when Mantle for 1.10.2 hasn't been released yet? ( or has it been released? ) if there is Mantle for 1.10.2 please show me where it is.

**Comment by ArukaAlter** [comment]
http://minecraft.curseforge.com/projects/mantle/files/2311098
This file loads.

**Comment by dwaindibbly** [comment]
oh.

**Comment by bonii-xx** [comment]
Added 1.10.2 as supported version to the file.
