### ISSUE TITLE
Crash trying to create whitelist in item pipe interface

### ISSUE THREAD

**Issue by garath77** [SlimeKnights/TinkersConstruct#2253]
Trying to add Copper Ore(Substratum) to an Item Interface pipe's whitelist. Tried a Tin Ore(NeoTech) as well. Instant crash both times. 

http://pastebin.com/weKt0bFd copper ore crash

http://pastebin.com/50dwXR6q Tin ore crash

Any ideas?

**Comment by KnightMiner** [comment]
This issue is either NeoTech or Bookshelf, I have no idea why you posted it here considering Tinkers does not even have a "item interface pipe"

**Comment by garath77** [comment]
LOL, because I'm in the wrong Github! lol sorry about that

**Comment by KnightMiner** [comment]
That's okay. You should be able to close this issue yourself then.
