### ISSUE TITLE
Crash while crafting Slimy Magma Mud

### ISSUE THREAD

**Issue by MrRiegel** [SlimeKnights/TinkersConstruct#2254]
I tried to craft magma mud but used blue slime ball instead of orange.

http://pastebin.com/cPZXhget

Edit: I occurs also when I just put an orange slime ball into the top left slot in the crafting grid

**Comment by bonii-xx** [comment]
Looks like something is messing with your crafting recipes. Try reproducing with only TiC. Add mods until it happens, complain about offending mod. ;o
