### ISSUE TITLE
Mending on TiC tools

### ISSUE THREAD

**Issue by Tenebris11** [SlimeKnights/TinkersConstruct#2255]
Are you supposed to be able to put Mending on tools from TiC?  I'm asking because it works until after you leave the world, which causes the enchantment to disappear.  

In my opinion, a mending-type repair modifier would be cool, and as far as I can tell, there aren't any, so this would be a nice feature.  Sadly, It seems this is unintended and is kinda not in the "spirit" of TiC, so it must be a bug.

**Comment by ArukaAlter** [comment]
Mending Moss is WIP, look at the recent commits.

**Comment by 1Enderman10** [comment]
There's still the issue with the original problem :P

**Comment by ArukaAlter** [comment]
Oh, yes, you aren't supposed to be able to apply book enchantments, is it only Mending that is being applied?

**Comment by 1Enderman10** [comment]
Seems like it.  Maybe boni forgot to make it so the new enchantments can't be applied?  To be honest, even I forgot Mending existed until I found the book, which is when I got the idea to test it with TiC tools and Botania's band of mana.
