### ISSUE TITLE
Piggyback

### ISSUE THREAD

**Issue by rogue21503** [SlimeKnights/TinkersConstruct#2257]
Me and some friends were playing around with the Piggyback and noticed that if the person using the piggyback (1st player) picks up a 2nd player and the 2nd player logs out while in the piggyback the 1st player goes invisible to everyone and the 2nd player cant be seen by the 1st player until the 1st player logs out and back in.

ETA: I have never submitted a bug report so if you need any logs or screenshots just let me know. We recreated it to make sure it was not a fluke.

ETA: we are using tinkers construct 1.10-2.3.3a

**Comment by bonii-xx** [comment]
Yes, piggybacking other players is a bit wonky, but this is due to minecraft not properly updating state across players since it doesn't really handle that case. It's pretty hard to catch all cases.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. Might be worth double checking this on 1.16, but I believe riding logic is cleaner. If not I have a blacklist now
