### ISSUE TITLE
Minor sound bug with slimesling (1.10.2 using tcon 2.3.3a)

### ISSUE THREAD

**Issue by Gayanfalor** [SlimeKnights/TinkersConstruct#2258]
Hello, 

We have noticed with a friend when using the slimesling, its doing the sound like someone was repairing a tool in the tool station.

I'm hearing this sound when he's using his slimesling and vice versa, when i'm using mine i hear the normal "slimish" sound from the item.

**Comment by bonii-xx** [comment]
Ah, the omnious "sounds are messed up accross clients" things. I've experienced before. I'll need to do some double checking on this.

**Comment by dooms247** [comment]
I've been getting a similar issue with shock imbued weapons. The shock charge up sound is the frying pan hit, and the shock discharge sounds like a squeaky toy.

**Comment by KnightMiner** [comment]
Closing as a duplicate of #2258, seems to not be an issue anymore.
