### ISSUE TITLE
Texture bug in library.client

### ISSUE THREAD

**Issue by Zkaface** [SlimeKnights/TinkersConstruct#2264]
When I use AbstractMaterialRenderInfo in combination with a pre made png texture file and return a new MetalTexture, it causes yellow pixels to render violet (or maybe transparent).

All other colors work as expected.

**Comment by bonii-xx** [comment]
Well, do you use a pre-made texture file or are you using a metaltexture? Templates are grayscale, it sounds like you're mixing them up.

**Comment by Zkaface** [comment]
Okay, then this is caused by my png file

**Comment by Zkaface** [comment]
Reopened, because you also use a colored texture for a metal rendering:

ardite.setRenderInfo(new MaterialRenderInfo.AbstractMaterialRenderInfo() { 
      @Override
      public TextureAtlasSprite getTexture(TextureAtlasSprite baseTexture, String location) {
        return new MetalTextureTexture(Util.resource("items/materials/ardite_rust"), baseTexture, location, 0xf97217, 0.6f, 0.4f, 0.1f);


if I - for the same intending - use also a colored (more yellowish) texture, it is rendered violet.

How can I prevent this?

**Comment by bonii-xx** [comment]
Passing in the correct parameters for the correct result ;o

**Comment by Zkaface** [comment]
Hmm seems that there is no solution for this. I will upload Screenshots of the input variables, the input png and what I get out of it tomorrow, to show it to you.

Erstmal jute Nacht bis dahin ;-)

**Comment by Zkaface** [comment]
So - here is the input image, the input data and the output result.

![unbenannt-1](https://cloud.githubusercontent.com/assets/3511223/17092947/4ab280c0-5246-11e6-8603-4461f3c134f0.png)

Input data: http://hastebin.com/uxalufodep.java (as an example, it doesn't matter a lot which hex code I use)
