### ISSUE TITLE
Modifier Silktouch cannot be combined with enchantment Silk Touch

### ISSUE THREAD

**Issue by laz2727** [SlimeKnights/TinkersConstruct#2266]
I'm sorry, what?
![2016-07-25 14 34 34](https://cloud.githubusercontent.com/assets/2369751/17096947/b62ed2d8-526c-11e6-962a-b61494037849.png)
Latest build.

**Comment by bonii-xx** [comment]
Modifiers on the hammer?

**Comment by laz2727** [comment]
Tons. Most should be compatible, though:
![2016-07-25 14 39 13](https://cloud.githubusercontent.com/assets/2369751/17097071/357c1f64-526d-11e6-9d3d-209f96a1f106.png)
