### ISSUE TITLE
Sharpening kits not working

### ISSUE THREAD

**Issue by vrork** [SlimeKnights/TinkersConstruct#2267]
I dont know if the is TiC problem or it is a incompatibility with one of my mods, but no sharpening kits work for me.

Here is the modlist:
http://pastebin.com/bEw6wFzE

**Comment by laz2727** [comment]
Are you sure you're using them with flint? I have a similar modpack and
they WFM,

**Comment by vrork** [comment]
Yes i am sure of it.

**Comment by laz2727** [comment]
Certainly seems to be working for me:
![2016-07-25 20 01 28](https://cloud.githubusercontent.com/assets/2369751/17105902/362a6812-529a-11e6-86e5-394d586d4085.png)
Can you make a screenshot?

**Comment by vrork** [comment]
Here:
https://ibin.co/2pI5dbaMZ2hH.png

**Comment by bonii-xx** [comment]
>I dont know if the is TiC problem or it is a incompatibility with one of my mods

Easy enough to test, try with only TiC and see what happens

**Comment by vrork** [comment]
Tested with only TiC and it worked fine. I just cant seem to find wich mod is causing this problem with TiC (its neither of the TiC related mods i have). Any sugestions of wich mods can be causing that?

**Comment by KnightMiner** [comment]
I am not sure what would cause it really, most likely something that modifies inventories. You could try a binary search, a.k.a remove half the list and test if it happens, if it does test again with half that list (or otherwise test again with the other list).

**Comment by vrork** [comment]
I have over 160 mods... can the logs help?

Logs:
fml-client-latest.log
https://gist.github.com/vrork/6617b0802fc256497b95672bc7f7f878

latest.log
https://gist.github.com/vrork/91c128147f9a720ac2ca80329c06431d

**Comment by KnightMiner** [comment]
The log mentions an issue with Cyclic button casting to TConstruct ones (as apparently it adds inventory tabs), try removing that mod and seeing if that's the problem

If it is, it should be a pretty easy fix by adding an instance of check [here]https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/client/module/GuiButtonsToolStation.java#L67).

**Comment by vrork** [comment]
Nope. Didnt fixed. Any other thing you can see on the logs?

**Comment by bonii-xx** [comment]
You most likely wont find anything in the logs, you wont get around systematically removing/adding mods. Start with coremods and everything that modifiers things.
