### ISSUE TITLE
Barebones Configs for TC 2

### ISSUE THREAD

**Issue by Amaxter** [SlimeKnights/TinkersConstruct#2270]
In the latest 1.10 version the configs don't seem to support disabling starting with the materials and you and I don't see an option to force Tinker's tools a la classic Iguana Tweaks style, are there plans to re-implement both of these options?

**Comment by KnightMiner** [comment]
The config to disable spawning of the book on login is returning in the next release, [see here](https://github.com/SlimeKnights/TinkersConstruct/commit/9a6b8860df9f9c27497a050390c04c264d8c9a3a).

I am unsure of the plans for other features from Iguana Tinker Tweaks, though I would guess the plan is to keep them a part of that mod and just update it to 1.10

**Comment by bonii-xx** [comment]
There will be no option to force TiC tools in TiC itself.

**Comment by Amaxter** [comment]
So is there a plan then to update Iguana TiC?
