### ISSUE TITLE
Inventories visually disappearing when near Smelteries

### ISSUE THREAD

**Issue by Ellpeck** [SlimeKnights/TinkersConstruct#2272]
I'm the dev of a mod this problem is partially occuring to, but I noticed it happening with other type of chest-storage type things from other mods.

The problem is the following: Whenever near a smeltery, the GUI of the Actually Additions Storage Crate will appear to completely empty out after a short time of leaving it open, but closing and reopening the GUI will reveal that all of the items are still there.

When removing the smeltery near the crate, this effect is not present anymore.
I have no idea what could cause this as I feel this is a very weird and unusual issue.

For more information and a somewhat more in-depth explanation of this, look at the following issue:
https://github.com/Ellpeck/ActuallyAdditions/issues/177

**Comment by bonii-xx** [comment]
Got a screenshot? I have no idea what that actually looks like.

Anyway, from the sound of it it looks like one of us is doing incorrect things when rendering. In case of doubt I'd say you're not setting up everything you need for rendering context. Or you're using TESRs where you shouldn't. ;o

**Comment by Ellpeck** [comment]
Maybe I didn't really explain it well enough :D 
1. I'm not using a TESR, it's just a normal JSON-rendered block with a TileEntitiy.
2. Basically, when having the GUI open, it displays the container just like a normal chest would.
At random intervals, for some reason, if you leave the container open for ~20 seconds or so, all of the items inside the slots will just disappear altogether. You can't take them out even though they're invisible or still see their tooltip or whatever, it basically acts as if all of the slots just got wiped.
However, that is not the case, as closing and reopening the GUI will cause all of the items to reapper.

So it couldn't possibly be anything about rendering, because rendering in the world and rendering inside of a GUI don't really have anthing to do with each other - or do they?
Additionally, I didn't do any additional packet sending or otherwise updating work for the crate, instead they just use the vanilla way of automatically syncing slots to the TileEntity.
So.. yea.. I have no idea what causes this and how to fix it :v

**Comment by Gayanfalor** [comment]
Tell me if you need me to do something, i can try to do a video if you want

**Comment by Ellpeck** [comment]
Well.. then never mind I guess. I'll try to report this to the TinkerIO guys - or do you have any idea on what this is, @bonii-xx? :v
