### ISSUE TITLE
Version 2.4.0 Jenkins312 bug

### ISSUE THREAD

**Issue by TheRoyalReaper** [SlimeKnights/TinkersConstruct#2273]
I know it's still Alpha and maybe it's a problem at my side but it seems that I can't activate the Blasting modifier, the others seem to work just fine

**Comment by TheRoyalReaper** [comment]
has no effect, I've made it blasting III and nothing is happening

**Comment by KnightMiner** [comment]
What do you expect to happen? Its supposed to cause any block to break quicker with the tool, but be less likely to drop.

At blasting III, there should be no block drops of it works right

**Comment by TheRoyalReaper** [comment]
ok well I didn't understand it then, I though it would "Blast" but nevermind, I guess it does work

**Comment by bonii-xx** [comment]
I feared something like that would happen, but if I added an actual explosion sound your ears would start bleeding. Maybe I need to invest into some particles for that.

**Comment by TheRoyalReaper** [comment]
I understand your fear of making a sound for it but the name suggests an
explosion so I was confused
