### ISSUE TITLE
Rejecting connection SERVER

### ISSUE THREAD

**Issue by knoxhack** [SlimeKnights/TinkersConstruct#2274]
I trying to connect to a server with no mods but with Tinkers Construct installed on client but I get rejections.

I am using BungeeCord for my network, thats why I need to connect to a server with no mods to be able to go to my modded server

[18:16:12] [Netty Client IO #1/INFO] [FML/]: Attempting connection with missing mods [JEI, mantle, tconstruct] at SERVER
[18:16:12] [Netty Client IO #1/INFO] [FML/]: Rejecting connection SERVER: [FMLMod:tconstruct{1.10-2.3.3a.jenkins271}]

**Comment by KnightMiner** [comment]
Does the server have Tinkers Construct?

**Comment by knoxhack** [comment]
The lobby server doesn't have Tinker's Construct. And the modpack I'm using for the server has around 130 mods and only Tinkers Construct is causing this issue

**Comment by knoxhack** [comment]
If you know about Bungeecord, the lobby server is just a bridge to connect to other servers

**Comment by knoxhack** [comment]
And yeah most mods can connect to server that don't have the mods installed, including, well all of them. My modpack has Ender IO, Biomesop, Blood Magic  etc... All the mainstream mods

**Comment by knoxhack** [comment]
Sometimes when a mod crash my servers I just remove it from the server and clients can
still connect even with the mod missing from the server

**Comment by KnightMiner** [comment]
Mods shouldnt work at all if removed from the server. I have never really used BungeeCord, but I can say that sounds a little odd for server connection.

In any case if other mods are still logging in than this is likely due to this is due to Tinkers Construct verifying the server mod version on login, having different versions or a missing one would cause crashes.

**Comment by knoxhack** [comment]
yeah, well the mods don't work until I get teleported to the server that has the mods installed. but they still allow me to pass through the server (bungeecord-lobby) with the mods missing.

**Comment by bonii-xx** [comment]
I know Bungeecord, I remember that issue before. TiC will always check that the version matches server and client side. Maybe we will allow to connect if it's not on the server for compatibility. We'll see.

**Comment by knoxhack** [comment]
Thanks, that would be awesome. I am currently working on 3 modpacks/servers for my Network, and my players really want Tinkers Construct. I know other networks will start using Bungeecord/SpongeForge soon now that its looking more stable. Even more when we get 1.10.2 mainstream modpacks like FTB Infinity 1.10.2. I host many servers for my network and using Bungeecord makes it a hell more easier to manage them. Also thanks for all you guys good work on the mod and continuing on 1.10.2 :)
