### ISSUE TITLE
Possible issue - Beheading V not working properly(?)

### ISSUE THREAD

**Issue by Jesperson** [SlimeKnights/TinkersConstruct#2275]
I've killed about 30-40 endermen now and they've not dropped a single head with my Beheading V cleaver - am I just unlucky, is there a conflict or is something broken?

Edit: Running TConstruct-1.10-2.3.3a

**Comment by KnightMiner** [comment]
Alderman heads are not added by TConstruct, and the API for other mods to add their heads to use for beheading is not currently complete.

**Comment by bonii-xx** [comment]
Endermen don't have heads. ;o
As for cross mod integration, that's still missing.

**Comment by Jesperson** [comment]
I understand, thanks! :)

**Comment by bonii-xx** [comment]
#2282
