### ISSUE TITLE
[1.10.2] Frying pan doesn't cook stuff anymore?

### ISSUE THREAD

**Issue by acanady** [SlimeKnights/TinkersConstruct#2276]
So yeah, i'm using Tinkers' Construct in 1.10.2 of minecraft and I can't for the life of me find out how to place the pan. It used to be shift right click. Has this feature been  removed, is it planning to be brought back, am I just derping majorly?

**Comment by bonii-xx** [comment]
Pans are not placeable anymore. If you hit things really hard (rightclick) their drops will be cooked. Because friction. And stuff.
