### ISSUE TITLE
Crash when breaking crafting station

### ISSUE THREAD

**Issue by Myknakryu** [SlimeKnights/TinkersConstruct#2279]
Java version: JRE 1.8.0_u102
Minecraft version: 1.10.2
Forge version: 1.10.2-12.18.1.2039
Mantle version: 1.10.2-0.10.4
TConstruct version: 1.10.2-2.4.0.jenkins312 (from curse)

So when i was playing on a new world i made a crafting station, then i placed it. After i done, i tried to break crafting station to move it onto another place, then the crash happen. I was playing on a localhost server with 60 mods but to check if it isn't any compability problem i loaded up only Mantle and TConstruct. Still crashing. I will also try with other blocks soon if it crashes with them.

Logs from only Mantle and TConstruct:
http://pastebin.com/uYi2i6gv

Log from modpack:
http://pastebin.com/mSQ2F8jT

**Comment by Myknakryu** [comment]
Well it seems that all model blocks are crashing. I tested it and last thing to test is normal blocks.

**Comment by Myknakryu** [comment]
Only breaking model blocks like casting table, crafting station, tool station. Ores, metal blocks, slime sand, clear glass etc. does not crash

**Comment by MokahTGS** [comment]
Confirmed:

http://pastebin.com/H3KDTeVz

**Comment by MokahTGS** [comment]
This is crashing even with old versions of TiC and Mantle:

http://pastebin.com/95jAnbLF

**Comment by bonii-xx** [comment]
Can you test an older version of Forge?

**Comment by ArukaAlter** [comment]
Does not crash with older versions of Forge, I assume Forge 2023 broke this.

**Comment by KnightMiner** [comment]
Can you try this on Forge build 2031? I have a feeling this is related to MinecraftForge/MinecraftForge#3086

**Comment by EPIICTHUNDERCAT** [comment]
Yep, just was about to look if someone had reported this, seems like just punching the table crashes.

**Comment by Teduce** [comment]
I can confirm it does work with 2031.  It was failing for me too on 2039.

**Comment by Myknakryu** [comment]
Yep it seems to be change in forge.

**Comment by HellishINC** [comment]
Just want to add that I too get the crash breaking the stencil table using a vanilla stone axe. Same error, happens with 2042.

**Comment by KnightMiner** [comment]
The crash would happen with any of the tables and racks, along with either of the two casting blocks. They all use the same rendering code.

**Comment by bonii-xx** [comment]
All hail lord Algo, the fixer of things he broke.

**Comment by Daihok75** [comment]
Also happens in forge 2043 Was trying to break some faucets and keep getting crash.

**Comment by ArukaAlter** [comment]
We are still waiting to Algo's fix to be merged, wait until it's listed in Forge's changelog.

**Comment by ericcotelnu** [comment]
Installing 2039, as it's reported as working. Thank you everyone.

**Comment by Orange1861** [comment]
I noticed that it doesn't crash when breaking it in creative mode.

**Comment by KnightMiner** [comment]
It's caused by the breaking animation. Creative mode does not display that.

**Comment by Orange1861** [comment]
Yup, I agree.

**Comment by Larky2k** [comment]
on latest Forge 2045 and latest TC breaking any Stations crashes client and anyone nearby.

**Comment by bonii-xx** [comment]
Yo everybody, I know you want it fixed, but reporting it to me is of no use. It's a forge issue. The fix is pending. It'll be fixed once there is a forge version with the fix.

**Comment by Dexan** [comment]
The same thing happens to me, left clicking any tile entity from TC causes a crash.
At least I can use "break block" spell from PSI to work around it.

**Comment by LovelyFlare** [comment]
@Dexan Did you not read what boni just said?

**Comment by MokahTGS** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.1.2046/forge-1.10.2-12.18.1.2046-changelog.txt

Changelog:
Build 2046:
	AlgorithmX2:
		Fix Vertex Transformer for breaking models (#3132)
		* Add setTexture to IVertexConsumer and propagate it.

Is this the fix we've been waiting for?

**Comment by kwpugh** [comment]
I did some testing on my server and I am able to break the Tinker's tables and such.

**Comment by HellishINC** [comment]
As of Forge 2046, this is no longer an issue.
