### ISSUE TITLE
[1.10.2] Broadsword not able to break cobwebs.

### ISSUE THREAD

**Issue by SharkIceCream** [SlimeKnights/TinkersConstruct#2281]
The broadsword in the 1.10.2 version does not count as a sword for breaking cobwebs found in mineshafts, and isn't even breaking them at all...

(I could use a vanilla sword but why would I do that??)

I have not checked the other swords from the mod.

**Comment by TheOldOne822** [comment]
This is already reported #2137 and fixed in alpha build

**Comment by SharkIceCream** [comment]
Oh didn't see that. so any news on when it will fully release?

FTB 1.10 Unstable has the older version still I guess...

**Comment by bonii-xx** [comment]
I don't know what you people are doing but no. They break them just fine.

**Comment by TheOldOne822** [comment]
Not in 2.3.3a
