### ISSUE TITLE
FPS-Lag when holding cleaver

### ISSUE THREAD

**Issue by ThexXTURBOXx** [SlimeKnights/TinkersConstruct#2283]
Version: 1.10.2-2.4.0.jenkins312
Forge-Version: 1.10.2-12.18.1.2039
Log: https://gist.github.com/ThexXTURBOXx/7bd2f01b8193b4b9ada431748f472b3a

I have a Manyullyn-cleaver with MUCH modifiers (about 25).
When I hold it in my hand, I get a huge FPS-drop.
See screenshots: http://imgur.com/a/bfCPF

Could it be, that the modifiers are ResourceLocations, which just get stacked on each other and because there are so much of them, it starts to lag?

**Comment by bonii-xx** [comment]
It's a bit more complicated than that but in general: Yes, more different modifiers = more overhead for rendering. In a regular case there are only 3 modifiers on a tool, so it's not an issue there.

How many different modifiers are on that cleaver? It's probably the putting together of the model that takes up too much time in such cases. If it becomes an actual problem we can always try to cache that stuff.

**Comment by ThexXTURBOXx** [comment]
Everytime, when it is visible (on the ground/in the hotbar/in inventory/in chest...) the FPS are not much affected (only 2 FPS).
I don't know, if "writable" counts as a modifier...
If it doesn't, there are 9 different modifiers (I have Tinkers Addons installed, so there is the modifier "Amelioration", but this one doesn't add show on the cleaver yet, because the mod is WIP).

**Comment by bonii-xx** [comment]
You could check how much impact each additional modifier has. So FPS drop with 0 modifiers vs 1 modifier vs 2 modifiers,...

**Comment by ThexXTURBOXx** [comment]
I will check

**Comment by ThexXTURBOXx** [comment]
Here is a little list:

No Cleaver: 65 FPS
Can't test with 0 Modifiers
Can't test with 1 Modifiers
Can't test with 2 Modifiers
Cleaver (3 Modifiers): 40
Cleaver (4 Modifiers): 36
Cleaver (5 Modifiers): 33
Cleaver (6 Modifiers): 30
Cleaver (7 Modifiers): 29
Cleaver (8 Modifiers): 28
Cleaver (9 Modifiers): 26

**Comment by bonii-xx** [comment]
Well, runs a smooth 60fps with all modifiers here. The problem is on your side. Probably Optifine.

**Comment by ThexXTURBOXx** [comment]
At least, I have OptiFine installed... I will test it without OptiFine soon

**Comment by bonii-xx** [comment]
Yes. Having Optifine usually opens up a whole can of problems. You're always better off without in 1.8+, unless you need a specific config it provides.

**Comment by Orange1861** [comment]
The config that many people need from Optifine is setting terrain animated to off. I went from 1 fps to a stable 19 fps.

**Comment by vidaj** [comment]
I'm having similar issues in 1.10.2. One of the cleavers tool rods are made from electrum, thus giving it the "shocking" attribute. Everything is dandy until the shocking charges, then the whole game stutters. Discharge (if I can hit anything) and everything is fine again.
