### ISSUE TITLE
Crash when trying to break a casting table

### ISSUE THREAD

**Issue by ericcotelnu** [SlimeKnights/TinkersConstruct#2285]
[crash-2016-08-01_02.04.23-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/393046/crash-2016-08-01_02.04.23-client.txt)

Minecraft: 1.10.2
Forge: 1.10.2-12.18.1.2044
TiCo: 2.3.3a

I have a bronze and iron pickaxe, upgraded with an obsidian sharpening kit. Twice now the server has crashed with me trying to break the casting table. It has nothing on/in it. I tried breaking it with a sharpening kit cast on it. It also crashed.

Only thing in the smeltery is 72 mb of obsidian, which I'm trying to "void" via dumping it into the table and breaking the table. I have a faucet attached to a drain, usual set up. Nothing fancy except a hopper under the table, with a hopper outlet attached the the hopper, with an EIO conduit on the hopper outlet.

__List of installed and enabled mods:__ http://pastie.org/10925638

**Comment by bonii-xx** [comment]
Same as #2279

**Comment by ericcotelnu** [comment]
Thanks. I looked through the issues, I hadn't seen it.
