### ISSUE TITLE
Breaking witchery items using lumber axe.

### ISSUE THREAD

**Issue by Lordicon** [SlimeKnights/TinkersConstruct#2287]
When placing a scarecrow (shrieking) witchery item down and then trying to use a lumber axe to break the item. Instead of the item dropping on the ground like a normal axe would cause this item is deleted completely, Could happen with other items as further testing would need done.

**Comment by KnightMiner** [comment]
What Minecraft, Tinkers Construct, Forge, and Witchery version are you using?

**Comment by bonii-xx** [comment]
1.7.10 is no longer supported.
