### ISSUE TITLE
Crash on breaking tool stations

### ISSUE THREAD

**Issue by Zilvynrae** [SlimeKnights/TinkersConstruct#2288]
I started a new world after updating to your newest 1.10 update and after making all of the blocks needed to create tools I placed them and then broke one in order to move it(the part chest) and the client crashed. I then logged back in and tried to break a different block (I cant recall which part of the station it was but it was not the chest) and the game crashed again. When I logged back in all of them simply ceased to exist. (I had the stencil table, part builder, tool station and part chest). I went and looked at my crash reports and I have 3 two client crash reports and 1 server crash report.
[crash-2016-08-01_23.07.56-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/395273/crash-2016-08-01_23.07.56-client.txt)
[crash-2016-08-01_23.06.28-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/395274/crash-2016-08-01_23.06.28-server.txt)
[crash-2016-08-01_23.06.27-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/395275/crash-2016-08-01_23.06.27-client.txt)

**Comment by CorvusUrro** [comment]
It's likely a forge issue.

https://github.com/SlimeKnights/TinkersConstruct/issues/2279

**Comment by KristjanKr** [comment]
Can confirm with forge build 2039 and using TConstruct-1.10.2-2.4.0.jenkins312 and Mantle-1.10.2-0.10.4

Crash log: https://paste.ee/p/PJ4vG

**Comment by MrBadd** [comment]
I can also confirm this bug, I am using forge 2043 with latest tinkers build.

**Comment by ArukaAlter** [comment]
Read past issues, it's a Forge bug and not Tinkers' fault, wait until the fix is listed in Forge's changelog, "can also confirm" won't help.
