### ISSUE TITLE
Fluid Expansion Bug When Leaving Chunk and Returning/Logging Out and Back Into A World. 

### ISSUE THREAD

**Issue by offlain** [SlimeKnights/TinkersConstruct#2289]
yeah the same closed issue is actually real, broken slime islands are taking over the world.

reproduce:
place 1 liquid slime down, relog, it has expanded multiple times.
**it seems the flowing blocks are converted to source blocs**

forge: forge-1.10.2-12.18.1.2044
TConstruct-1.10-2.3.3a
Mantle-1.10.2-0.10.4

**Comment by offlain** [comment]
It's causing massive lag on my server.

with crashes:
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]

**Comment by bonii-xx** [comment]
Sounds like a forge bug. All fluids? Maybe you can check with other mods fluids as well?

**Comment by offlain** [comment]
ok tested, it is forge, tested with substrantum added, forge 2034 and 2044 both have the issue, went back to 2014 (didn't have time to try in between - so issue starts somewhere between forge 2014 and 2043) - curious is that when going back to 2014 mod liguids in world will be removed upon loading... 

don't have time now to report to forge, so feel free to link/report this

**Comment by offlain** [comment]
ok I still managed to report there

**Comment by Orange1861** [comment]
Can you post the link of the report?

**Comment by KnightMiner** [comment]
#3152. Already fixed in a commit on Forge's end
