### ISSUE TITLE
Unknown  EXCEPTION_ACCESS_VIOLATION Crash

### ISSUE THREAD

**Issue by samiscool51** [SlimeKnights/TinkersConstruct#2292]
when loading up version 1.10.2-2.4.0.jenkins312 the game crashes when it tries to render the world

a log is provided both the java crash log and the client crash log
[client crash crash-2016-08-04_19.10.31-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/401402/client.crash.crash-2016-08-04_19.10.31-client.txt)
[java crash hs_err_pid9192.txt](https://github.com/SlimeKnights/TinkersConstruct/files/401403/java.crash.hs_err_pid9192.txt)

**Comment by KnightMiner** [comment]
Your crash report does not contain Tinkers Construct. It also looks like it's AutoPackager's fault.

**Comment by bonii-xx** [comment]
Autopackager needs an RF api, it seems. Anyway, not TiC related.
