### ISSUE TITLE
[Suggestion] Config option to disable block damage of the explosion item or the item itself

### ISSUE THREAD

**Issue by Nentify** [SlimeKnights/TinkersConstruct#2293]

**Comment by Nentify** [comment]
What does FAQ mean? I can't find an FAQ/any similar questions/answers. I meant the EFLN by the way.

Thanks!

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ

**Comment by Nentify** [comment]
Oh, my bad. That seems fair enough, hope it's considered. Thanks again!
