### ISSUE TITLE
game crashes when treing to brake casting table

### ISSUE THREAD

**Issue by JJ48** [SlimeKnights/TinkersConstruct#2294]
first crash log ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/4/16 5:06 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:38)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:25)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2685)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1765)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:38)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:25)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2685)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1765)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MineMax48'/56338, l='MpServer', x=-402.71, y=64.00, z=544.95]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-92,64,252), Chunk: (at 4,4,12 in -6,15; contains blocks -96,0,240 to -81,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 167073 game time, 245502 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 109 total; [EntitySkeleton['Skeleton'/307715, l='MpServer', x=-475.50, y=44.00, z=611.50], EntityZombie['Zombie'/311304, l='MpServer', x=-393.50, y=21.00, z=496.50], EntityZombie['Zombie'/311305, l='MpServer', x=-429.52, y=27.00, z=521.99], EntityZombie['Zombie'/308246, l='MpServer', x=-461.50, y=31.00, z=584.50], EntityPlayerSP['MineMax48'/56338, l='MpServer', x=-420.03, y=59.00, z=532.70], EntityWitch['Witch'/311324, l='MpServer', x=-439.50, y=22.00, z=517.50], EntityZombie['Zombie'/311325, l='MpServer', x=-442.50, y=22.00, z=492.50], EntityCreeper['Creeper'/310808, l='MpServer', x=-472.50, y=19.00, z=555.50], EntitySkeleton['Skeleton'/310298, l='MpServer', x=-476.50, y=49.00, z=620.50], EntityZombie['entity.Zombie.name'/310816, l='MpServer', x=-443.50, y=26.00, z=510.50], EntityCreeper['Creeper'/308270, l='MpServer', x=-481.83, y=47.00, z=606.54], EntityCreeper['Creeper'/309823, l='MpServer', x=-473.50, y=20.00, z=553.50], EntityCreeper['Creeper'/309329, l='MpServer', x=-460.78, y=35.00, z=592.45], EntitySkeleton['Skeleton'/311386, l='MpServer', x=-452.30, y=56.00, z=521.30], EntityItem['item.item.egg'/298081, l='MpServer', x=-389.74, y=62.00, z=484.29], EntityPig['Pig'/56423, l='MpServer', x=-385.86, y=62.18, z=488.68], EntityPig['Pig'/56424, l='MpServer', x=-414.17, y=67.00, z=477.55], EntityChicken['Chicken'/56425, l='MpServer', x=-413.29, y=66.00, z=474.81], EntityChicken['Chicken'/56426, l='MpServer', x=-417.11, y=67.00, z=476.93], EntityChicken['Chicken'/56427, l='MpServer', x=-389.20, y=62.75, z=483.43], EntityChicken['Chicken'/56428, l='MpServer', x=-379.92, y=62.68, z=511.66], EntityPig['Pig'/56429, l='MpServer', x=-375.72, y=63.00, z=493.63], EntityPig['Pig'/56430, l='MpServer', x=-393.22, y=64.00, z=467.65], EntitySheep['Sheep'/56437, l='MpServer', x=-395.82, y=63.00, z=488.71], EntityBat['Bat'/310386, l='MpServer', x=-466.73, y=20.28, z=543.82], EntityPig['Pig'/56440, l='MpServer', x=-398.15, y=62.48, z=507.40], EntityCreeper['Creeper'/310908, l='MpServer', x=-406.50, y=19.00, z=505.50], EntityPig['Pig'/56441, l='MpServer', x=-370.89, y=62.40, z=518.43], EntityPig['Pig'/56442, l='MpServer', x=-356.32, y=66.00, z=530.22], EntityBat['Bat'/308351, l='MpServer', x=-452.25, y=56.00, z=521.25], EntityZombie['Zombie'/311928, l='MpServer', x=-455.65, y=21.00, z=541.35], EntityPig['Pig'/56445, l='MpServer', x=-377.02, y=62.58, z=502.56], EntityBat['Bat'/309881, l='MpServer', x=-474.04, y=21.01, z=556.73], EntityPig['Pig'/56446, l='MpServer', x=-393.67, y=62.32, z=505.10], EntityPig['Pig'/56447, l='MpServer', x=-357.52, y=63.00, z=498.24], EntityPig['Pig'/56448, l='MpServer', x=-358.48, y=65.00, z=488.73], EntityPig['Pig'/56449, l='MpServer', x=-384.82, y=63.00, z=499.68], EntityBat['Bat'/310913, l='MpServer', x=-419.43, y=25.31, z=510.55], EntityPlayerSP['MineMax48'/56338, l='MpServer', x=-404.80, y=61.00, z=531.34], EntityPlayerSP['MineMax48'/56338, l='MpServer', x=-445.90, y=55.00, z=517.28], EntitySquid['Squid'/308877, l='MpServer', x=-415.26, y=56.21, z=519.25], EntityZombie['Zombie'/310946, l='MpServer', x=-375.50, y=22.00, z=509.50], EntityPig['Pig'/56489, l='MpServer', x=-356.89, y=63.00, z=503.96], EntityPig['Pig'/56490, l='MpServer', x=-353.78, y=64.00, z=514.64], EntityPig['Pig'/56491, l='MpServer', x=-356.59, y=63.00, z=508.28], EntitySquid['Squid'/310440, l='MpServer', x=-389.45, y=62.54, z=521.38], EntityPig['Pig'/56492, l='MpServer', x=-388.76, y=63.00, z=494.72], EntitySquid['Squid'/310455, l='MpServer', x=-394.13, y=62.57, z=533.94], EntitySkeleton['Skeleton'/310962, l='MpServer', x=-459.50, y=56.00, z=513.50], EntityZombie['Zombie'/310457, l='MpServer', x=-483.80, y=57.00, z=601.49], EntitySkeleton['Skeleton'/309966, l='MpServer', x=-438.50, y=20.00, z=537.50], EntitySkeleton['Skeleton'/311498, l='MpServer', x=-423.50, y=26.00, z=516.50], EntityCow['Cow'/57043, l='MpServer', x=-477.82, y=68.00, z=613.55], EntityBat['Bat'/310992, l='MpServer', x=-414.62, y=43.10, z=495.75], EntityZombie['Zombie'/309968, l='MpServer', x=-452.50, y=52.00, z=621.50], EntitySkeleton['Skeleton'/312019, l='MpServer', x=-462.50, y=34.00, z=587.50], EntityZombie['Zombie'/312031, l='MpServer', x=-473.50, y=32.00, z=472.50], EntitySkeleton['Skeleton'/312034, l='MpServer', x=-462.50, y=22.00, z=541.50], EntityBat['Bat'/312046, l='MpServer', x=-428.75, y=26.00, z=518.47], EntityBat['Bat'/311037, l='MpServer', x=-465.15, y=31.04, z=562.66], EntityCreeper['Creeper'/308998, l='MpServer', x=-448.50, y=27.00, z=501.50], EntityPlayerSP['MineMax48'/56338, l='MpServer', x=-402.71, y=64.00, z=544.95], EntityZombie['Zombie'/308490, l='MpServer', x=-443.50, y=55.00, z=513.50], EntityPig['Pig'/57107, l='MpServer', x=-428.53, y=67.00, z=596.66], EntityPig['Pig'/57108, l='MpServer', x=-445.24, y=64.00, z=604.50], EntityPig['Pig'/57109, l='MpServer', x=-431.73, y=64.00, z=589.54], EntityPig['Pig'/57110, l='MpServer', x=-434.68, y=65.00, z=594.36], EntityPig['Pig'/57111, l='MpServer', x=-451.49, y=64.00, z=567.75], EntityPig['Pig'/57112, l='MpServer', x=-351.74, y=67.00, z=540.22], EntityPig['Pig'/57114, l='MpServer', x=-410.58, y=66.00, z=611.30], EntityZombie['Zombie'/312094, l='MpServer', x=-471.50, y=40.00, z=562.50], EntityPig['Pig'/57115, l='MpServer', x=-425.33, y=67.00, z=609.26], EntitySheep['Sheep'/57116, l='MpServer', x=-416.79, y=67.00, z=608.18], EntitySheep['Sheep'/57117, l='MpServer', x=-432.30, y=67.00, z=602.20], EntitySheep['Sheep'/57118, l='MpServer', x=-420.11, y=67.00, z=606.85], EntityPig['Pig'/57119, l='MpServer', x=-407.55, y=62.00, z=534.50], EntityPig['Pig'/57125, l='MpServer', x=-413.70, y=67.00, z=603.59], EntitySheep['Sheep'/57126, l='MpServer', x=-444.28, y=64.00, z=608.52], EntityPig['Pig'/57127, l='MpServer', x=-422.17, y=67.00, z=607.88], EntitySkeleton['Skeleton'/311093, l='MpServer', x=-476.50, y=57.00, z=606.50], EntitySkeleton['Skeleton'/310577, l='MpServer', x=-469.50, y=28.00, z=519.50], EntityItem['item.item.egg'/307004, l='MpServer', x=-380.47, y=62.00, z=511.88], EntitySkeleton['Skeleton'/311615, l='MpServer', x=-432.22, y=27.00, z=523.23], EntityCreeper['Creeper'/310085, l='MpServer', x=-433.50, y=27.00, z=518.50], EntityZombie['Zombie'/311111, l='MpServer', x=-417.50, y=42.00, z=496.50], EntityZombie['Zombie'/311118, l='MpServer', x=-478.50, y=48.00, z=617.50], EntityZombie['Zombie'/308047, l='MpServer', x=-409.50, y=18.00, z=506.50], EntityCreeper['Creeper'/311638, l='MpServer', x=-481.50, y=32.00, z=476.50], EntityZombie['Zombie'/312145, l='MpServer', x=-452.50, y=52.00, z=621.50], EntitySpider['Spider'/311145, l='MpServer', x=-422.50, y=22.00, z=497.50], EntityBat['Bat'/310132, l='MpServer', x=-436.54, y=25.10, z=517.49], EntitySquid['Squid'/288625, l='MpServer', x=-412.18, y=60.18, z=527.03], EntityBat['Bat'/311687, l='MpServer', x=-465.29, y=37.29, z=483.38], EntityZombie['Zombie'/300949, l='MpServer', x=-461.50, y=33.00, z=588.50], EntityZombie['Zombie'/310172, l='MpServer', x=-483.50, y=36.00, z=533.50], EntitySkeleton['Skeleton'/311704, l='MpServer', x=-437.79, y=18.00, z=525.49], EntityCreeper['Creeper'/312219, l='MpServer', x=-450.50, y=14.00, z=522.50], EntityCreeper['Creeper'/310181, l='MpServer', x=-450.50, y=27.00, z=500.50], EntitySquid['Squid'/292798, l='MpServer', x=-425.84, y=58.05, z=524.66], EntityEnderman['Enderman'/311234, l='MpServer', x=-480.50, y=16.00, z=469.50], EntitySpider['Spider'/307148, l='MpServer', x=-403.50, y=20.00, z=501.50], EntitySkeleton['Skeleton'/310735, l='MpServer', x=-385.50, y=22.00, z=479.50], EntitySkeleton['Skeleton'/303560, l='MpServer', x=-465.50, y=40.00, z=588.50], EntityPlayerSP['MineMax48'/56338, l='MpServer', x=-446.60, y=55.00, z=498.25], EntityZombie['Zombie'/311788, l='MpServer', x=-437.50, y=14.00, z=508.50], EntitySpider['Spider'/311790, l='MpServer', x=-416.50, y=42.00, z=516.50], EntitySkeleton['Skeleton'/311272, l='MpServer', x=-466.50, y=40.00, z=591.50], EntitySkeleton['Skeleton'/309747, l='MpServer', x=-448.50, y=62.00, z=487.50], EntityZombie['entity.Zombie.name'/310259, l='MpServer', x=-484.50, y=40.00, z=529.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 115105976 bytes (109 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.32 Powered by Forge 12.18.1.2045 Optifine OptiFine_1.10.2_HD_U_C2 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2045.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.1.2045} [Minecraft Forge] (forge-1.10.2-12.18.1.2045.jar) 
	UCHIJAAAAAAAAA	BiomesOPlenty{4.1.0.2049} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2049-universal.jar) 
	UCHIJAAAAAAAAA	guideBook{1.6.1} [Guide Book] (Guide-Book-Mod-1.10.2.jar) 
	UCHIJAAAAAAAAA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UCHIJAAAAAAAAA	tconstruct{1.10.2-2.4.0.jenkins312} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jenkins312.jar) 
	UCHIJAAAAAAAAA	XaeroMinimap{1.10} [Xaero's Minimap] (Xaeros_Minimap_1.10_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 15.200.1046.0' Renderer: 'ASUS R7 370 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2045
	LWJGL: 2.9.4
	OpenGL: ASUS R7 370 Series GL version 4.5.13397 Compatibility Profile Context 15.200.1046.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4300 Quad-Core Processor 
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Robobo1221s Shaders V6.1 Ultra.zip
	OpenGlVersion: 4.5.13397 Compatibility Profile Context 15.200.1046.0
	OpenGlRenderer: ASUS R7 370 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

tellme if you want the secound

**Comment by ArukaAlter** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/2279

**Comment by Orange1861** [comment]
It has been fixed, use forge 2046.
