### ISSUE TITLE
Stencil Table

### ISSUE THREAD

**Issue by Ezelberoth** [SlimeKnights/TinkersConstruct#2297]
I'm trying to use the "TConstruct-1.10-2.3.3a.jar" version, which is listed as release in Curse for Minecraft V 1.10.2.

I made my workstation, consisting of Crafting Station, Tool Station, Part Builder, Stencil Table, and Pattern Chest. I made a stack of 12 blank patterns, put on in the stencil table, and click on various patterns, axe head, shovel head, tool rod, hammer head... None of the stencils will create. Nothing comes up in the "Output" slot.

**Comment by LovelyFlare** [comment]
Doesn't sound like a Tinkers' problem.  Are you using it with any other mods?

**Comment by bonii-xx** [comment]
#2205
Not a tinkers issue

**Comment by Ezelberoth** [comment]
Apparently this was being caused by Cyclic, at least for me.

**Comment by MineProjectZ** [comment]
i have the same error but i dont have cyclic installed
