### ISSUE TITLE
Shurikens not Affected by Attack Speed Limit (1.10.2, 2.4.0)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2300]
Shurikens are not affected by the attack speed system when used as a melee weapon in 1.9+ which gives them ridiculous attack speed.  This bug allows you to combo enemies.  Other TiC tools/weapons do not have this issue.

**Comment by LovelyFlare** [comment]
Not a TiC issue, whoops...

**Comment by KnightMiner** [comment]
Well, they are not supposed to do extra melee damage. Might need to hook something into the `NO_MELEE` tool category

**Comment by LovelyFlare** [comment]
They do 1/2 a heart but you can spam that.

**Comment by bonii-xx** [comment]
Just like any vanilla item. Like cobblestone. Or a stick. ;P

**Comment by LovelyFlare** [comment]
Not correct.  You don't inflict damage/knockback every click with cobblestone or sticks while with shurikens you can.

**Comment by bonii-xx** [comment]
Hm, I wonder if the attackspeed compensation is taking them into account.
