### ISSUE TITLE
Crafting station & Casting basin - client crash - break execution

### ISSUE THREAD

**Issue by Tessellry** [SlimeKnights/TinkersConstruct#2301]
MC: 1.10.2
Forge: 12.18.1.2011
Tconstruct 1.10.2-2.4.0.jenkins312
AT DonutCraft Version 1.10.2/0.0.9b
http://pastebin.com/4sjq0ijf

Breaking crafting station and casting basin. Used different pickaxes and materials: minecraft/ TechReborn/Tinkers with the same result - immediate crash. Consequently "breaking execution".
First happend to a player from another country (working station) at least 1 hour before me (basin).
Also casting BASIN registers as a TABLE when placed.

**Comment by bonii-xx** [comment]
#2279
