### ISSUE TITLE
Blue Slime (liquid) duplication

### ISSUE THREAD

**Issue by nzhook** [SlimeKnights/TinkersConstruct#2304]
The Blue slime liquid in Tinkers Construct 1.10.2 2.4.0.jenkins312 allows for a serious duplication issue.

It appears that on server restart/User login/loading of the chunk (I suspect loading of the chunk) any existing flowing blue slime is converted into blue slime source blocks. This then flows some more. When the issue occurs again (chunk reloaded?) the new flowing blocks are turned into source blocks which causes an exponential growth of slime.

eg. This is the slime island on the FTOG Youtube server:
![2016-08-06_14 05 09](https://cloud.githubusercontent.com/assets/4828036/17461674/afdc474a-5ce8-11e6-9e92-5b118de94321.png)

As this was over an ocean it also converted the water source blocks to slime and flowed into any caves (and mineshafts) in the area eg.
![2016-08-07_17 05 53](https://cloud.githubusercontent.com/assets/4828036/17461945/1de8f088-5cf0-11e6-8910-4a4ed0fbf57f.png)

I've uploaded a video, showing what happens and how to reproduce: https://youtu.be/qKe7ndgH8xo

Environment:
Minecraft 1.10.2
Java 64 bit 1.8.0_71
forge-12.18.1.2042
Avant 3 Modpack (on Curse)
TConstruct-1.10.2-2.4.0.jenkins312.jar
Multi (FTOG) and Single player

**Comment by bonii-xx** [comment]
#2289
Forge issue, update forge.
