### ISSUE TITLE
EFLN does not respect NBT in block drops

### ISSUE THREAD

**Issue by williewillus** [SlimeKnights/TinkersConstruct#2305]
Title, offending code here:

https://github.com/SlimeKnights/TinkersConstruct/blob/a4b35fca30ac308c13f151f3df9e2f42882086fc/src/main/java/slimeknights/tconstruct/gadgets/Exploder.java#L227

This affects for example Botania magic flowers, whose `getDrops` are all the same item with different NBT tags

**Comment by williewillus** [comment]
Personally, I would stuff all the stacks into a list and combine/sort them before spawning, instead of using the map-count approach here, it's too inflexible considering the possible combinations you get with NBT

**Comment by bonii-xx** [comment]
WTB map reduce
