### ISSUE TITLE
Is there any mod used to help players to play?

### ISSUE THREAD

**Issue by 5igm** [SlimeKnights/TinkersConstruct#2307]
Such as JEI addons, NEI addons?

**Comment by ArukaAlter** [comment]
Read the in-game manual, it lists material traits and stats, JEI has the alloying recipes.

**Comment by bonii-xx** [comment]
There used to be more comprehensive manuals but they are incompatible with the last few MC versions. The current book gives you a lot of info on materials/modifiers, but for an actual introduction best check some youtube videos.
