### ISSUE TITLE
Power Advantage/Tinkers Construct fluid containers/transport not compatible

### ISSUE THREAD

**Issue by Syndaryl** [SlimeKnights/TinkersConstruct#2309]
Tests:

- Place PA Metal Fluid Tank beneath TC Seared Faucet. Attach TC Seared Tank containing e.g. water to other side of Seared Faucet. Activate Seared Faucet - nothing happens, TC does not detect PA Metal Fluid Tank as a valid container.
- Swap positions of PA Metal Fluid Tank and TC Seared Tank, move fluid to Metal Fluid Tank. Activate Seared Faucet - nothing happens.
- Remove Seared Faucet, replace with PA Pipe. Fluid is not transferred from Metal Fluid Tank to TC Seared Tank.
- Remove Pipe and Seared Tank. Put Pipe under the Metal Fluid Tank, put Seared Tank under Pipe. Fluid is not transferred from Metal Fluid Tank to TC Seared Tank.
- Create a TC Smeltery. Put a Smeltery Drain on the top edge. Put PA Pipe on top of  Smeltery Drain, put Metal Fluid Tank on top of PA Pipe, put water in Metal Fluid Tank, water does not transfer.
- Smelt something. Put a pipe on the side of Smeltery Drain. Put Metal Fluid Tank under Pipe. Smeltery does not drain into Metal Fluid Tank.

I've cross posted this to the Power Advantage issue list: https://github.com/cyanobacterium/PowerAdvantageAPI/issues/30

**Comment by KnightMiner** [comment]
This is PowerAdvantages's fault. They are still using the old Forge fluid transfer system and Tinkers Construct only supports the new one.

**Comment by bonii-xx** [comment]
As has been said above, we only support fluid capabilities.
