### ISSUE TITLE
Not working at ALL for Forge 1.8

### ISSUE THREAD

**Issue by O-M-3-G-A** [SlimeKnights/TinkersConstruct#2310]
![minecraft](https://cloud.githubusercontent.com/assets/20985577/17615223/e37fae04-60ab-11e6-9cdb-e3e5f7f914a4.PNG)
When opening tinker's construct, I am presented with a blank white screen, but if Optifine is also installed, I get a grey screen with white boxes, appearing to be text, but is unreadable.
This may be due to me using the 1.8.9 version in 1.8 forge, but anyone's guess is as good as mine.

**Comment by LovelyFlare** [comment]
1.8.9 TiC can't be used in 1.8 forge.  This isn't an issue...

**Comment by bonii-xx** [comment]
Sadly we don't support that version of minecraft anymore. Or optifine. As LovelyFlare said, you can't use the version for 1.8.9 version with MC 1.8
