### ISSUE TITLE
[JEI Support] ISubtypeRegistry

### ISSUE THREAD

**Issue by Dijkstra1** [SlimeKnights/TinkersConstruct#2311]
Are you aware of ISubtypeRegistry in JEI, it lets you tell JEI about NTB tags that define an item as being being different though they have same ID, then when looking up recipes of tool parts it will only show the one you click and not all of that type of tool part that can crafted.

**Comment by bonii-xx** [comment]
I am not, since @mezz probably added that recently AND DID NOT TELL ME ABOUT IT >:(
