### ISSUE TITLE
FTB Unstable 1.10 Tinkers Construct Graphics issues on Mac

### ISSUE THREAD

**Issue by LightDefiant** [SlimeKnights/TinkersConstruct#2314]
_(repost from FTB Support Forum)_

FTB Unstable 1.10*:

(v4.2.6)*:

Launcher Version v1.4.12*:

No log required for reporting of issue*:

no edits to pack made

**System Specs**:
OS X El Capitan
Version 10.11.6

iMac:  (27-inch, late 2013)
Processor:  3.2 GHz Intel Core i5
Memory:  16GB 1600 MHz DDR3
Graphics:  NVIDIA GeForce GT 755M 1024 MB 

**While I am aware that Unstable packs generally are not supported, Im also aware that the FTB team does not have a MAC to test on. Therefore Im creating this thread to inform you of the graphical bug that appears only on my mac with the 'Stencil Table from Tinkers Construct', as watching DW20s LP's make it clear that it is no happening on most PC's. (See attached photo)

Thank you for your time in reading this report, and thank you all for your effort in continued creation of fantastic Forge content.

![2016-08-12_17 24 53](https://cloud.githubusercontent.com/assets/21005064/17642060/3f5630fe-60d4-11e6-9c5f-7dbca0941fbd.png)
![2016-08-12_17 25 05](https://cloud.githubusercontent.com/assets/21005064/17642061/475c0e86-60d4-11e6-8a93-d2b8050ea88e.png)
![2016-08-12_17 25 09](https://cloud.githubusercontent.com/assets/21005064/17642063/4fc0a03c-60d4-11e6-9172-0fd6d2844967.png)

**Comment by Orange1861** [comment]
Can you try this with only tinkers and mantle?

**Comment by bonii-xx** [comment]
Definitively not Tinkers' fault, looks more like a mod that messes with the texture map... or optifine.

**Comment by xbony2** [comment]
@LightDefiant do F3 + T ;)
