### ISSUE TITLE
Compatibility with structure blocks

### ISSUE THREAD

**Issue by Lythom** [SlimeKnights/TinkersConstruct#2315]
Hi,

Using minecraft 1.10.2 and TConstruct 1.10-2.3.3a, I got the game to crash when spawning a smeltery using structure blocks.

steps to reproduce :

1. Place a structure block named "smeltery" in save mode, configured with -1 1 -1 as relative position, and 3 3 3 as size.
2. build a minimal 3x3x2 smeltry on top of it
3. Use the save button on the structure block
4. Place another structureblock elsewhere in "load" mode named "smeltery". Click "load".

When the structure appears, on first next tick, the game crash and the following stacktrace appears in logs : http://pastebin.com/sQWTupyj. On reboot, the game doesn't crash anymore but the smeltery is "broken" (nothing works).

Reasons why you might consider compatibility with structure block :

- It's a vanilla mechanic builders and map makers might use to build their worlds / maps.
- It grants automatic compatibility with the 1.10.2+ versions of the [Capsule mod](http://imgur.com/gallery/xCWCX) (which relies on the structure block system).

Additional informations :

- I developped some tools to inspect tiles entities (it print a "give" command that would spawn a conform copy). I got a comparison between the initial and loaded smeltry : http://pastebin.com/raw/hQaZtPeQ. I highlight that most but not all coordinates are updated correctly after move : all {x,y,z,minPos,maxPos} looks ok, but all {xCenter, yCenter, zCenter} are wrong.
- With some instructions on how the problem should be solved (use relative coordinate ? recalculate smeltry integrity on load ?) I can come with some PR. I don't know much the codebase so any info that could help me take that try is welcome !

**Comment by bonii-xx** [comment]
Does it also happen with https://minecraft.curseforge.com/projects/tinkers-construct/files/2319366 ?

**Comment by Lythom** [comment]
Yes, this is reproductible as well with TConstruct-1.10.2-2.4.0.jenkins312.jar (+ Mantle-1.10.2-0.10.4.jar)

**Comment by bonii-xx** [comment]
Looks like the parts still detect the original smeltery as valid (I assume it still exists?) and hence can't be reassigned to the new smeltery. Usually the smeltery will just rebuild its data if it's not valid anymore.

**Comment by bonii-xx** [comment]
I don't think there is a way in Minecraft or Forge to detect structure block loading. I'd suggest you simply fill in the internals of the smeltery with void structure blocks so the smeltery rebuilds itself on loading. It is important that all blocks part of it never were in a valid smeltery, so best replace them with new ones.
