### ISSUE TITLE
[1.10.2] Subtle glitch causing lightning reset and possibly lag every 13~ seconds

### ISSUE THREAD

**Issue by C0rn3j** [SlimeKnights/TinkersConstruct#2316]
Original thread here as I originally thought it's an AA issue
https://github.com/Ellpeck/ActuallyAdditions/issues/203

Forge 2056; Mantle-1.10.2-0.10.4.jar; TConstruct-1.10.2-2.4.0.jenkins312.jar

Using only these and creating a forge(looks like it needs to have minimum height too) and possibly something else, since I tested this on an old world, there's a glitch that happens approx every 13~ seconds. It resets the lightning, breaks AA GUI(check issue above) and causes the game to freeze for a few frames(might or might not be related to the GUI glitching out).

https://www.youtube.com/watch?v=oN6i79hdbO4

**Comment by bonii-xx** [comment]
Looks like forge is redoing all the lighting in that frame. See related ticket. The question is why the smeltery updates though.

**Comment by c0rn3j** [comment]
AA fixed the GUI issue on their side, lag/lightning issues remain.

**Comment by bonii-xx** [comment]
Never managed to reproduce the issue to debug.
