### ISSUE TITLE
Translation doesn't appear

### ISSUE THREAD

**Issue by 5igm** [SlimeKnights/TinkersConstruct#2317]
My minecraft's language is chinese, but Tinker still shows English. Does TConstruct-1.8.9-2.2.1 has chinese translation in it? How can I show it?
TConstruct-1.8.9-2.2.1
forge-1.8.9-11.15.1.1902-1.8.9-universal

**Comment by 5igm** [comment]
In addition, it seems no manual in the mod. : (

**Comment by bonii-xx** [comment]
That release does not have a chinese translation yet. One has been contributed in the meantime, and it will be in the next (1.10.2) release as well as the current alpha.

The manual is partially present in the newer versions, at least all the data stuff.
