### ISSUE TITLE
Destroying crafting station crashes

### ISSUE THREAD

**Issue by aryel-gois** [SlimeKnights/TinkersConstruct#2322]
I built a crafting station and decided do move it somewhere else, but when I start to break, the game crashes.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 15/08/16 12:41
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:26)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:17)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1907)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1343)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:26)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:17)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1907)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1343)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Ary_'/176, l='MpServer', x=224,33, y=67,00, z=251,20]]
	Chunk stats: MultiplayerChunkCache: 623, 623
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (232,64,256), Chunk: (at 8,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 53837 game time, 53837 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 70 total; [EntityZombie['Zumbi'/128, l='MpServer', x=281,50, y=51,00, z=202,50], EntityZombie['Zumbi'/385, l='MpServer', x=205,50, y=37,00, z=208,50], EntityZombie['Zumbi'/133, l='MpServer', x=303,50, y=20,00, z=184,50], EntityZombie['Zumbi'/397, l='MpServer', x=203,50, y=53,00, z=234,50], EntityCreeper['Creeper'/399, l='MpServer', x=267,50, y=12,00, z=232,50], EntityDroneBaby['Baby Drone'/17, l='MpServer', x=51,38, y=60,00, z=321,59], EntityCreeper['Creeper'/407, l='MpServer', x=202,50, y=32,00, z=291,50], EntityDroneBaby['Baby Drone'/153, l='MpServer', x=334,00, y=70,47, z=273,94], EntityDroneBaby['Baby Drone'/154, l='MpServer', x=341,93, y=70,99, z=174,93], EntityDroneBaby['Baby Drone'/31, l='MpServer', x=85,75, y=51,00, z=331,75], EntityDroneBaby['Baby Drone'/162, l='MpServer', x=400,00, y=49,59, z=163,19], EntityDroneBaby['Baby Drone'/164, l='MpServer', x=400,08, y=73,26, z=198,22], EntityBat['Morcego'/548, l='MpServer', x=170,44, y=33,76, z=279,51], EntityDroneBaby['Baby Drone'/165, l='MpServer', x=400,01, y=67,30, z=218,70], EntityDroneBaby['Baby Drone'/167, l='MpServer', x=400,10, y=57,00, z=329,90], EntityBat['Morcego'/552, l='MpServer', x=243,10, y=52,05, z=223,98], EntityDroneBaby['Baby Drone'/169, l='MpServer', x=400,01, y=70,98, z=414,67], EntityCreeper['Creeper'/557, l='MpServer', x=253,50, y=21,00, z=197,50], EntityCreeper['Creeper'/50, l='MpServer', x=147,16, y=25,00, z=225,45], EntitySkeleton['Esqueleto'/52, l='MpServer', x=152,50, y=25,00, z=240,50], EntityPlayerSP['Ary_'/176, l='MpServer', x=224,33, y=67,00, z=251,20], EntityItem['item.item.sulphur'/56, l='MpServer', x=160,61, y=21,00, z=266,32], EntityCreeper['Creeper'/568, l='MpServer', x=207,79, y=13,00, z=311,59], EntitySquid['Lula'/62, l='MpServer', x=170,91, y=56,45, z=310,10], EntityZombie['Zumbi'/65, l='MpServer', x=183,50, y=62,00, z=174,50], EntitySheep['Ovelha'/66, l='MpServer', x=182,57, y=65,00, z=242,87], EntitySpider['Aranha'/322, l='MpServer', x=267,50, y=12,00, z=230,50], EntityItem['item.item.rottenFlesh'/67, l='MpServer', x=183,75, y=63,00, z=285,99], EntityCreeper['Creeper'/451, l='MpServer', x=199,50, y=14,00, z=306,50], EntityDroneBaby['Baby Drone'/68, l='MpServer', x=203,25, y=61,71, z=87,03], EntitySkeleton['Esqueleto'/326, l='MpServer', x=150,50, y=26,00, z=225,50], EntitySheep['Ovelha'/72, l='MpServer', x=208,39, y=69,00, z=198,60], EntityBat['Morcego'/458, l='MpServer', x=292,86, y=49,83, z=214,00], EntitySheep['Ovelha'/75, l='MpServer', x=203,16, y=69,00, z=208,72], EntityCreeper['Creeper'/331, l='MpServer', x=167,50, y=42,00, z=266,50], EntityBat['Morcego'/76, l='MpServer', x=199,49, y=58,10, z=233,45], EntityCreeper['Creeper'/77, l='MpServer', x=204,95, y=49,06, z=239,70], EntityCreeper['Creeper'/78, l='MpServer', x=206,07, y=49,00, z=239,30], EntityCreeper['Creeper'/79, l='MpServer', x=208,20, y=49,00, z=241,44], EntitySheep['Ovelha'/80, l='MpServer', x=193,27, y=66,00, z=280,46], EntityBat['Morcego'/592, l='MpServer', x=264,23, y=30,92, z=209,77], EntityZombie['Zumbi'/81, l='MpServer', x=205,50, y=21,00, z=290,50], EntitySkeleton['Esqueleto'/82, l='MpServer', x=203,50, y=14,00, z=310,50], EntitySkeleton['Esqueleto'/338, l='MpServer', x=282,50, y=51,00, z=205,50], EntitySkeleton['Esqueleto'/83, l='MpServer', x=209,07, y=14,00, z=313,51], EntitySkeleton['Esqueleto'/469, l='MpServer', x=171,50, y=25,00, z=287,50], EntitySheep['Ovelha'/89, l='MpServer', x=221,18, y=69,00, z=200,42], EntityItem['item.item.bone'/90, l='MpServer', x=208,03, y=68,50, z=207,13], EntitySheep['Ovelha'/91, l='MpServer', x=222,17, y=69,00, z=205,85], EntityCreeper['Creeper'/92, l='MpServer', x=206,56, y=60,00, z=238,80], EntitySheep['Ovelha'/97, l='MpServer', x=225,26, y=69,00, z=216,46], EntitySkeleton['Esqueleto'/99, l='MpServer', x=239,50, y=50,00, z=228,50], EntityEnderman['Enderman'/355, l='MpServer', x=265,50, y=38,00, z=198,50], EntityBat['Morcego'/102, l='MpServer', x=253,16, y=16,02, z=208,52], EntityCreeper['Creeper'/359, l='MpServer', x=276,50, y=54,00, z=201,50], EntitySheep['Ovelha'/106, l='MpServer', x=250,26, y=65,00, z=218,19], EntitySkeleton['Esqueleto'/107, l='MpServer', x=243,47, y=59,00, z=225,50], EntitySheep['Ovelha'/108, l='MpServer', x=248,44, y=66,00, z=224,24], EntitySquid['Lula'/110, l='MpServer', x=248,62, y=59,23, z=305,42], EntitySquid['Lula'/111, l='MpServer', x=244,61, y=49,44, z=300,09], EntityZombie['Zumbi'/369, l='MpServer', x=179,50, y=32,00, z=282,50], EntityCreeper['Creeper'/116, l='MpServer', x=267,49, y=46,00, z=221,17], EntitySkeleton['Esqueleto'/117, l='MpServer', x=263,50, y=47,00, z=211,50], EntityZombie['Zumbi'/373, l='MpServer', x=181,81, y=27,00, z=206,49], EntityBat['Morcego'/119, l='MpServer', x=256,75, y=50,10, z=215,75], EntitySquid['Lula'/122, l='MpServer', x=259,97, y=50,74, z=268,79], EntityBat['Morcego'/125, l='MpServer', x=281,72, y=31,10, z=204,70], EntityCreeper['Creeper'/126, l='MpServer', x=274,50, y=44,00, z=204,50], EntityBat['Morcego'/510, l='MpServer', x=265,35, y=45,65, z=216,87], EntityCreeper['Creeper'/127, l='MpServer', x=287,50, y=37,00, z=194,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.19.0-66-generic
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 183409560 bytes (174 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.1.2043 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2043.jar) 
	UCHIJAAAA	Forge{12.18.1.2043} [Minecraft Forge] (forge-1.10.2-12.18.1.2043.jar) 
	UCHIJAAAA	buildingbrickshooks{1.10.2-2.0.12} [Building Bricks Hooks] (minecraft.jar) 
	UCHIJAAAA	BBG{5.0.0} [BetterBedrockGen] (BetterBedrockGen-1.9.4-5.0.0.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAA	BiomesOPlenty{4.1.0.2052} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2052-universal.jar) 
	UCHIJAAAA	buildingbricks{1.10.2-2.0.12} [Building Bricks] (BuildingBricks-1.10.2-2.0.12.jar) 
	UCHIJAAAA	ChunkAnimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.9.4-1.2.jar) 
	UCHIJAAAA	drones{1.10.2-1.4.0} [CustomDrones] (CustomDrones-1.4.0-mc1.10.2.jar) 
	UCHIJAAAA	EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.9.4-1.2.1.jar) 
	UCHIJAAAA	ftfloocraft{1.7.5} [Floocraft] (Floocraft-1.7.5.jar) 
	UCHIJAAAA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCHIJAAAA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7.jar) 
	UCHIJAAAA	JEI{3.7.3.221} [Just Enough Items] (jei_1.10.2-3.7.3.221.jar) 
	UCHIJAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCHIJAAAA	packingtape{0.5.2} [Packing Tape] (PackingTape-1.9.4-0.5.2.jar) 
	UCHIJAAAA	placementpreview{0.3.0} [Placement Preview] (placementpreview-1.10.2-0.3.0.jar) 
	UCHIJAAAA	RealisticTorches{1.5.6} [Realistic Torches] (RealisticTorches-1.10.2-1.5.6.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UCHIJAAAA	thirdpersonelytra{1.0} [Third Person Elytra] (thirdpersonelytra-110.2-1.0.jar) 
	UCHIJAAAA	trashslot{6.3.2} [TrashSlot] (TrashSlot_1.10.2-6.3.2.jar) 
	Loaded coremods (and transformers): 
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 10.5.9' Renderer: 'Mesa DRI Intel(R) Haswell Desktop '
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2043
	LWJGL: 2.9.4
	OpenGL: Mesa DRI Intel(R) Haswell Desktop  GL version 3.0 Mesa 10.5.9, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Português (Brasil)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

**Comment by laz2727** [comment]
Update Forge.

2016-08-15 20:46 GMT+05:00 aryel-gois <notifications@github.com>:
