### ISSUE TITLE
Error feedback: infinity items

### ISSUE THREAD

**Issue by 5igm** [SlimeKnights/TinkersConstruct#2324]
TConstruct-1.8.9-2.2.1
forge-1.8.9-11.15.1.1902-1.8.9-universal
Although a player only have one tconstruct weapon, he/she can drop infinit same items.
My meaning is if you drop one like hatchet, there will be one hatchet on the ground, but the original one is still in your inventory.

**Comment by 5igm** [comment]
This happened in multiple-player not single player.

**Comment by 5igm** [comment]
https://youtu.be/t9Iy3Mm49OY

**Comment by bonii-xx** [comment]
1.8.9 is out of date, create a new issue if it happens with 1.10 versions
