### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by CookieHunteRRR** [SlimeKnights/TinkersConstruct#2325]
https://www.youtube.com/watch?v=d4RFOZCOA4E

When i'm deleting TCon this bug is gone. Recorded it with 2.4.0 version (2.3.3 have this bug too)
Sry for bad english :c

**Comment by CookieHunteRRR** [comment]
Nope, that was because of HQM, because when i'm deleted it this bug is gone...

**Comment by LovelyFlare** [comment]
Feel free to close this issue

**Comment by bonii-xx** [comment]
Yes, this looks like an issue in some other mod that hooks into that stuff. Probably a ton of serverside errors too.
