### ISSUE TITLE
seared furnace vs. enderio binder / recipes with greater output

### ISSUE THREAD

**Issue by 4Magma** [SlimeKnights/TinkersConstruct#2327]
- furnace slot allow 16 enderio binder composite
- recipe gives 2 enderio conduit binder for each composite
- result: furnace stops slot and alert to much items

1) include recipe output quantity in slot limit calculation
2) is there a way to extract items from furnace?
3) give seared furnace xp like vanilla furnace?

**Comment by bonii-xx** [comment]
1) Sounds like it's working perfectly fine? Maybe for shiftclicking.
2) The GUI. You can also put a hopper below the furnace controller, but that requires timing.
3) Maybe

**Comment by 4Magma** [comment]
1) shiftclicking and drag a stack over slots fills each with 16 
    (if not more than 4 slots)
    better: slot would only accept 8 or slot could store 32 output items
2) timing? oh i tried! item conduit or comparable with filter should work
3) hope in future! test with stack of logs didn't give some
