### ISSUE TITLE
Seared Furnace not working

### ISSUE THREAD

**Issue by the-creamster** [SlimeKnights/TinkersConstruct#2328]
How is one meant to build the seared furnace?? I built the max size(11x11x11) using the picture in the book as a 'guide' and the controller isn't lighting up. So i then built a 3x3x3 and it still didn't work.

Is it a complete cuboid structure?? if so its not working for me.

**Comment by KnightMiner** [comment]
Are you building it hollow or solid on the inside?

**Comment by the-creamster** [comment]
![2016-08-19_11 18 36](https://cloud.githubusercontent.com/assets/2037833/17795947/0c2797fa-6600-11e6-803a-3141d0da6022.png)
![2016-08-19_11 19 04](https://cloud.githubusercontent.com/assets/2037833/17795950/119fef48-6600-11e6-81b8-f38bfda20968.png)

**Comment by KnightMiner** [comment]
The tanks must be in the frame (a.k.a the borders of the cube), the specific location or count is not relevant.

**Comment by the-creamster** [comment]
i shall try that, just doing some other bug testing/confirming atm (yay for live testing)

**Comment by the-creamster** [comment]
Yep that worked; i re-looked at the section of the book that covered it and it showed the tanks on the very edges and i thought they were relative positions to the controller. Maybe specify in the relevant section of the manual that the tanks have to be in the 'vertical side frame corners' for the multiblock to function.

Thanks for the pointer.

**Comment by bookerthegeek** [comment]
@the-creamster those look suspiciously like GT advanced machine casings in your picture.

**Comment by KnightMiner** [comment]
The book specifics that you are allowed tanks as long as they are in the frame. It also does not have to be the vertical frame, horizontal frame works too. Just anywhere not directly touching the inside area.

**Comment by the-creamster** [comment]
GT machines, what you talking about?? try Tech Reborn(GT2 & pre-experimental IC2 rolled into one); its on 1.8+(using 1.10.2). I am currently very active on there github reporting a largish number of broad range issues.

**Comment by bookerthegeek** [comment]
Gotcha... I'll need to look into that.
