### ISSUE TITLE
tinkers tools not working

### ISSUE THREAD

**Issue by captainbrtiain** [SlimeKnights/TinkersConstruct#2331]
i am building a 1.10.2 server the version of forge i am using is 12.18.1.2066 the issue i am having is none of lumberaxe's work  to reproduce make a lumberaxe they where working kind of in creative 
when trying to use the tool it brake's the block and instantly replaces them as i am making a server pack it also does the same in single player for me 1.10.2-4.0.jar 

i have also included a video unedited 
https://youtu.be/jh5wq0155yA

**Comment by captainbrtiain** [comment]
the lumber axe is the only one that is not working other tools work

**Comment by captainbrtiain** [comment]
should note that breaking one block of wood works

**Comment by bonii-xx** [comment]
Sounds like you're in spawn protection.

**Comment by captainbrtiain** [comment]
spawn protection is off and i am op on the server as well i even moved more than 100 blocks to test it out

**Comment by bonii-xx** [comment]
Try reproducing with only tic, mantle and forge.

**Comment by captainbrtiain** [comment]
i will have to do more testing one by one with removing the mods but it looks like another mod may be causing this issue

**Comment by DMIL421** [comment]
Identical issue playing on a server. In SSP, if I break the bottom tree block twice, it drops the tree as normal. On the server, it does not. 

On the server, the following things work:
Breaking wood items that are not trees. 
Breaking a single tree block that is not connected to any other wood block.

**Comment by bonii-xx** [comment]
Try reproducing with only tic, mantle and forge.

**Comment by DMIL421** [comment]
So I don't have a server capable of testing in that way, but some more info for you... Lumber axe was working fine this morning (PST), but as of a few minutes ago, it had stopped working again. Did a server restart, and now it is working fine.

I don't even know how to begin to help with that... ???

**Comment by bonii-xx** [comment]
Sounds like it's your servers fault. Or whatever is running on it. Don't use bukkit/spigot/cauldron.

**Comment by DMIL421** [comment]
Not using any of those. Just a Minecraft server instance  running on a Linux server.

Gonna try updating forge today and see if that fixes it. Could be a problem with 2066?

**Comment by bonii-xx** [comment]
Shouldn't be. It's working fine on ForgeCraft too. Have you tried it on the server without any other mods?

**Comment by DMIL421** [comment]
Nope, no ChickenChunks or ChickenCodeCore.

I will talk to the guy who hosts our server... see if i can get him to back it up, and then wipe it for a test period. I have the ability to update it, but not back up and restore.

I will let you know if I get any more info.

**Comment by jeanflo125** [comment]
I have a similar problem in one of my singleplayer worlds, in my 'testing' world (survival mode, but JEI cheat mode) lumberaxes work fine, but in my 'survival' world, lumberaxes just can't break any trees. 

The game plays the animation of the blocks breaking, but when the blocks should drop, it just starts breaking the blocks again.

**Comment by DMIL421** [comment]
I updated forge to 2075, and lumber axes worked all day yesterday. Will have to see if it continues.

**Comment by DMIL421** [comment]
I'm still getting reports from people on my server that lumber axes still keep working then not working.

Crash report should have most of the relevant details for the server.

[crash-2016-09-06_12.35.38-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/460798/crash-2016-09-06_12.35.38-client.txt)

**Comment by bonii-xx** [comment]
>UCHIJA	mychunkloader{1.9.4-1.10.2-03} [My Chunk Loader] (Mychunkloader-1.9.4-1.10.2-03.jar) 

I haven't seen that before. Are the chunks where it happens chunkloaded, possibly?

**Comment by DMIL421** [comment]
It occurs in areas that are and are not chunkloaded, no difference. If it is working anywhere, it is working. If not, it is not.

Mod is on CurseForge here: https://minecraft.curseforge.com/projects/chunkloader-simple

It's seemed stable as far as I've noticed. Fewer issues than with ChickenChunks in previous versions.

**Comment by bonii-xx** [comment]
I think I found the issue that caused the lumber axe to behave incorrectly sometimes. Should hopefully be fixed next version.
