### ISSUE TITLE
Cleaver creation weirdness

### ISSUE THREAD

**Issue by DarkLight66** [SlimeKnights/TinkersConstruct#2333]
Using v2.4.0, the durability of a cleaver changes depending on which tool rod you put on each slot

![1](https://cloud.githubusercontent.com/assets/2170330/17835765/2581968e-6749-11e6-9db0-8caf3979012d.png)
![2](https://cloud.githubusercontent.com/assets/2170330/17835772/4231f580-6749-11e6-920b-4c6c0401fa92.png)

**Comment by bonii-xx** [comment]
Yes. It's called a handle. ;P

**Comment by laz2727** [comment]
Think of one as a handle and other as a binding.

**Comment by DarkLight66** [comment]
Well i know one is working as a handle and the other one is working as a binding, the tool forge UI and the cleaver sprite both hint this, i guess the only problem is people that don't get this and make a cleaver that could've been better by switching the tool rods around.

**Comment by laz2727** [comment]
Yeah, we can't fix people being dumb.

**Comment by bonii-xx** [comment]
That's why it's called Tinkers' Construct. ;o
