### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by PandaFrog** [SlimeKnights/TinkersConstruct#2335]
on my Minecraft version 1.10.2 server running forge 12.18.1.2070 with tinkers construct version 1.10.2-2.4.0 i crashed while walking around the world and looked at the crash report and it was knightslime from tinkers now when i log in the server crashes instantly. I add the crash report
[crash-2016-08-21_20.55.49-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/428812/crash-2016-08-21_20.55.49-server.txt)

**Comment by bonii-xx** [comment]
Were you alone on the server? Were you using an EFLN or a Glowball?

**Comment by PandaFrog** [comment]
One of my friends and my girlfriend was on. i have no i didnt and my friend and gf didnt use one

**Comment by bonii-xx** [comment]
Well, you somehow managed to get an entity with invalid/missing data. There is no real way of getting that normally, the only way I can imagine is getting a crash during saving. Also if none of you ever threw a glowball/efln than it can only be a data corruption. Your only choice there is to remove the entities in the save. I"m sure google knows a way.

**Comment by bonii-xx** [comment]
At least the crash shouldn't happen anymore next version.
