### ISSUE TITLE
Oreberry bushes are not generated anymore, were they lost in 129dbbe84db272a131f962442d58dadd72ff786b?

### ISSUE THREAD

**Issue by martinp26** [SlimeKnights/TinkersConstruct#2337]

**Comment by laz2727** [comment]
They don't *exist* anymore.

**Comment by martinp26** [comment]
Have they been move to some external mod?  All the existing documentation that I could find still mentions them.

**Comment by laz2727** [comment]
Yeah, and people still play 1.7.10. Not as far as i know.
