### ISSUE TITLE
[Suggestion] seared lights, seared chest

### ISSUE THREAD

**Issue by 4Magma** [SlimeKnights/TinkersConstruct#2341]
seared lights:
- style: like a brick block with a porthole alike integrated lamp
- different light styles (quark:blaze_lantern, minecraft:sea_lantern)
- recipe: 4 seared bricks, 2 glas, 2 glowstone, 1 dye|blaze powder|..
- portholes on all sides!!! (for floor montage)

seared chest:
- like a tresor 
- holds up to a vanilla chest
- recipe: bricks around vanilla chest
- smeltery controller: as input (any position)
- furnace controller: as input (above, left) and as output (below, right)
- casting table, casting basin: as output (all but above)

**Comment by LovelyFlare** [comment]
Read the FAQ please... https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ

**Comment by bonii-xx** [comment]
As said above, see FAQ.
Seared Light might make some sense for decorative purposes to fit in, we'll see.
