### ISSUE TITLE
[1.10.2] There was a critical exception handling a packet on channel tconstruct

### ISSUE THREAD

**Issue by FiveEYZ** [SlimeKnights/TinkersConstruct#2343]
Some times when a player tries to access a crafting station he will get thrown out of the server, it happens randomly but the error is always the same.

![f7721f11140d249f1465dbe10bbbfd67](https://cloud.githubusercontent.com/assets/9557442/17922303/94f10314-69de-11e6-9174-351d930acb5e.png)

at the same time this will appear in the server console:
https://gist.github.com/FiveEYZ/dabe8f3b8d617611a396d6db97168898

Using:
TConstruct-1.10.2-2.4.0
Mantle-1.10.2-0.10.4
forge-1.10.2-12.18.1.2073-universal
spongeforge-1.10.2-2073-5.0.0-BETA-1684

these were mentioned in the error:
EnderIO-1.10.2-3.0.1.95_beta
EnderCore-1.10.2-0.4.1.51-beta

**Comment by bonii-xx** [comment]
That's an issue with enderIO farming stations using TiC tools, when they break. It's known, but I have to doublecheck if it has been fixed so far.

Paging @CrazyPants

**Comment by utoc** [comment]
I am running:
FML 2073
TiCo 1.10.2-2.4.0
Mantle 1.10.2-0.10.4
EIO 1.10.2-3.0.1.95_beta
EnderCore 1.10.2-0.4.1.51-beta

This issue sprouted up for us when FML 2068 broke binary compatibility and users were forced to use TiCo tools in harming stations rather than vanilla tools.

https://gist.github.com/utoc/ca94adce8bbd1c40c7a32fe87c1055b2

**Comment by bonii-xx** [comment]
Update to 2069 which restores binary compatibility ;)

**Comment by CrazyPants** [comment]
Oops. I forgot to fix this one. I will try and get it done tonight

**Comment by CrazyPants** [comment]
This is fixed in latest release. Not sure which exact build had the fix but anything post 3.0.1.96 definately has it.

**Comment by utoc** [comment]
Can confirm its been fixed, thanks crazypants
