### ISSUE TITLE
EFLN causing world breaking crash

### ISSUE THREAD

**Issue by Zygus42** [SlimeKnights/TinkersConstruct#2344]
[crash-2016-08-24_23.47.44-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/435094/crash-2016-08-24_23.47.44-server.txt)

Can't log back in as it keeps crashing back to desktop with ticking entity.  

Doesn't matter in this case as it's only a test world.

**Comment by bonii-xx** [comment]
Steps to reproduce?

**Comment by Zygus42** [comment]
Hmmmm.......not sure - I was flying over the ocean and blew up a pirate ship from Quark with EFLN and then proceeded onwards.  A large schematic from Placemod got spawned and the crash happened.  I would guess that some of the EFLN hadn't exploded yet when the server got bogged down with the spawning, but only a guess.

I'm planning to remove the recipe for EFLN from my build anyway, as it's ridiculously overpowered and destructive.

**Comment by bonii-xx** [comment]
Thus is the nature of exploding things.

**Comment by bonii-xx** [comment]
Crash shouldn't happen anymore next version
