### ISSUE TITLE
Blank Cast no smeltable?

### ISSUE THREAD

**Issue by cyberpunkbln** [SlimeKnights/TinkersConstruct#2346]
Hi,
i have tried to smelt some blank casts out of brass, and the progress don't start?
thx

**Comment by KnightMiner** [comment]
Um, first off what version are you using?

Secondly, the blank cast is made by pouring molten brass or gold on a casting table, not in a furnace.

**Comment by cyberpunkbln** [comment]
Hi,

i use the Beta 2.4.0 for Minecraft 1.10.2.

I have melted molten brass in the Smeltery on a casting table and cast some useful casts, but i have a redstone clock activated and he has molten the rest of the molten brass into blank casts. Okay i have say me, no problem i smelt this late back to other useful casts.

When i put back the blank casts in the smeltery, the smeltery say it cannot be molten.

???

thx

**Comment by GirafiStudios** [comment]
It probably can't be smelted back into a liquid, because it can be made of two diffrent metals I assume :)

**Comment by cyberpunkbln** [comment]
In older versions blank casts can be molten back in aluminum-brass. I doesn't matter if the material are be made of two different materials or metals. Alloys can molten back, too in the actual version.

**Comment by cyberpunkbln** [comment]
Is this a Bug or a Feature in the newest TC-Version? I mean why is it possible to make blank casts? In older version blank casts can be resmelted into aluminum-brass. At the moment blank casts don't have any function and are useles.

**Comment by KnightMiner** [comment]
If you look in JEI, blank casts are used in crafting recipes, reinforcements for example. Being able to melt them back into brass would cause issues simply because it can be made out of three different metals (gold, brass (if another mod adds it), and aluminum brass (if another mod adds copper and aluminum)), which would be inconsistent and cause issues if other mods value brass more than gold.

**Comment by cyberpunkbln** [comment]
Hi,

thx for you answer. Okay i understand the value problem, but is Aluminum Brass not the one and only metal from TC to smelt some casts? I don't wan't smelt it back to brass i want to smelt it back to reuse it as a cast. In my mod-constellation it gives 1 metal for casts: gold and 2 alloys for casts: aluminum brass and brass.

When i make a blank cast with Molten Brass or Molten Gold then i have a blank cast and i all older versions this blank cast only can be resmelt to Molten Aluminum Brass the one and only Alloy for making casts in TC.

I dont want Molten Brass or Gold backsmelted, only Molten Aluminum Brass  back.

Or can it be that other Mods use Aluminum Brass as ordinary Brass? At Jei i see in my Modpack only the use for making casts? At the oreDict say Aluminum Brass are not Brass.

Sorry i have over 20 blank casts that i cannot use at the moment and i must search clay for casts:).

**Comment by ArukaAlter** [comment]
In older versions, Alu-brass casts and gold casts were separated, in current versions, they are the same product.

**Comment by cyberpunkbln** [comment]
Yes thats right, i only want describe that it gives no reason to not smelt back a blank cast to Alu-Brass, why i can use only Alu-Brass for blank casts. I think Alu-Brass is only usable for blank casts. When other Mods use Alu-Brass for Brass receipts, then is this cheating. The oreDict makes a difference between Alu-Brass and Brass. I want to say in older versions i can smelt it back to Alu-Brass and reuse Casts and Blank Casts.

I don't understand why i cannot smelt blank casts back to Molten Alu-Brass. When i use Molten Gold and Molten Brass for blank casts, whats the problem that i can only smelt it back to Molten Alu-Brass? Alu-Brass the one and only from TC:). And it gives no value Problem.

Blank Casts and Casts from Alu-Brass, Gold and Brass back to Alu-Brass its not cheating and people that use mods thats give Alu-Brass more Value as Gold or Brass its cheating. But i don't know any mod that uses Alu-Brass for that value.

**Comment by bonii-xx** [comment]
Blank casts are treated the same, no matter what they're cast from. They don't save what they're created from, hence they can't melt back to what they're created from.
