### ISSUE TITLE
Tinker's Sword/Cleaver doesn't break cobwebs

### ISSUE THREAD

**Issue by choekstr** [SlimeKnights/TinkersConstruct#2347]
Cobwebs aren't breakable/harvestable with Tinker's sword or cleaver and waila states not harvestable and needs a sword.  The Tinker's pickaxe does work but waila states not harvestable yet is the normal very slow to break.  Using a vanilla sword of any type works perfectly.

TiC2 Versions:  2.3.3 (FTB Unstable default), 2.4.0
Minecraft: 1.10.2
TiC2 Sword/Cleaver material tried: Manyullyn, Bone, Iron

**Comment by bonii-xx** [comment]
Only the cleaver

**Comment by ariosos** [comment]
I'm using Tinkers 2.5.6b, and I still can't break cobweb with a Tinkers sword. (steel broadsword)

Tool traits are:
Well-Established
Sharp
Cold-Blooded
Luck I
Unbreakable
(The tool leveling mod is also installed)

Material - Steel (Blade), Copper (Binding), Manyullyn (Handle)

WAILA says I need a sword

**Comment by KnightMiner** [comment]
Try with the latest Alpha, should be fixed there

**Comment by choekstr** [comment]
I was wondering when this would get revisited.  I did sufficient testing to include the sword in my initial bug report as it absolutely was an issue along with the cleaver.  Both created and given swords could not mine cobwebs.  Glad to see you guys have fixed the sword now as well in the latest revision.

**Comment by bonii-xx** [comment]
No, the bug was waila harvestability breaking cobweb harvesting.

**Comment by choekstr** [comment]
Wow, that is crazy that waila harvestability could actually limit harvesting based on it's interpretation of what is the right tool.  I figured that was handled more on the Tinker's or even vanilla side and your weapons are instantiating a vanilla weapon model/template.  Glad the Tinker's team is on top of these type of issues.
