### ISSUE TITLE
World Crashing Bug

### ISSUE THREAD

**Issue by Pkr1345** [SlimeKnights/TinkersConstruct#2348]
Not sure If this is a Mekanism or Tinker's error but, I was upgrading a Mekanism basic tank to an advanced tank, shift clicked the recipe into a TC crafting station and the world crashed. The world now crashes every time upon entry.

Here's the crash log.
http://pastebin.com/HT9dk27V

**Comment by bonii-xx** [comment]
On Mekanisms side. Looks like they're misusing the models.
