### ISSUE TITLE
All Blocks Converted to Slimy Vines

### ISSUE THREAD

**Issue by JaRyCu** [SlimeKnights/TinkersConstruct#2349]
Modpack: FTB Unstable 4.2.7 (downloaded today via the Curse launcher)

I've attached before & after pix to this report.  I had 2 of the Tinkers tables, a 3x3x1 smeltery (could do 9 ore blocks at a time), tool forge, and all the tool tables to make tools with.  I logged out and back in later and all of the tinkers items had converted into blue and purple slimy vines.  The smeltery drain converted into an iron tool forge.  From what I could tell, no other mods were affected as I hadn't really done anything with any of the others except for Chisel, which I used to build my buildings.

![2016-08-28_18 47 11](https://cloud.githubusercontent.com/assets/15949393/18037863/a1cb69c8-6d5b-11e6-8c9d-09d621056ba3.png)
![2016-08-28_20 07 44](https://cloud.githubusercontent.com/assets/15949393/18037864/a1ce1542-6d5b-11e6-9ef0-af21a60153e4.png)

**Comment by bonii-xx** [comment]
Sounds like a world loading/saving issue. If you start a new world and do the same thing again it probably wont happen again.

**Comment by Fokson** [comment]
This happened to me, as well as a number of blocks from other mods turning into various molten metals from TiC, and other blocks from other mods as well.  Not sure what caused it precisely, but it WAS caused by the Minecraft SSP server experiencing an exception that it couldn't catch during Save-Quit and ending before the world had fully saved.  It's not a TiC bug.

**Comment by JaRyCu** [comment]
I'm playing SMP with the new FTB Hermitpack now, and another player had her tool forge completely disappear from the game in a similar manner to what happened to me here over the weekend, except nothing was left in its place.

**Comment by KnightMiner** [comment]
As stated above, it has been reproduced with other mods blocks, so it is unlikely just Tinkers fault. Reproduce with just Tinkers Construct and it might be a valid issue.

**Comment by spike11302000** [comment]
did the modpack update?

**Comment by JaRyCu** [comment]
no
