### ISSUE TITLE
Crash whenever I use the Stencil Table

### ISSUE THREAD

**Issue by aquagirl555** [SlimeKnights/TinkersConstruct#2353]
Everytime I try to use the stencil Table it crashes. I'm using many mods so I'm not sure if they are causing it, but the game was working just fine until I tried to use the Stencil Table, even the other tables worked just fine.
Crash report has the list of all the mods in it.
Here is the Crash report, not sure how to compress or put under a spoiler tag of some sort:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  SimpleCore (Simple Quarry-1.9.4_1.0.0.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 8/30/16 5:24 PM
XRay version: 38
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Grid size too big to traverse.
	at zornco.bedcraftbeyond.core.util.items.ItemHandlerGridHelper.doChecks(ItemHandlerGridHelper.java:26)
	at zornco.bedcraftbeyond.core.util.items.ItemHandlerGridHelper.getGridItems(ItemHandlerGridHelper.java:54)
	at zornco.bedcraftbeyond.core.util.items.ItemHandlerGridHelper.getItemsWrapped(ItemHandlerGridHelper.java:67)
	at zornco.bedcraftbeyond.frames.stone.RecipeBedFrameStone.func_77569_a(RecipeBedFrameStone.java:31)
	at assets.recipehandler.CraftingHandler.getCraftResult(CraftingHandler.java:107)
	at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:142)
	at assets.recipehandler.GuiEventHandler$CreativeButton.func_146112_a(GuiEventHandler.java:49)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:71)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:81)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at zornco.bedcraftbeyond.core.util.items.ItemHandlerGridHelper.doChecks(ItemHandlerGridHelper.java:26)
	at zornco.bedcraftbeyond.core.util.items.ItemHandlerGridHelper.getGridItems(ItemHandlerGridHelper.java:54)
	at zornco.bedcraftbeyond.core.util.items.ItemHandlerGridHelper.getItemsWrapped(ItemHandlerGridHelper.java:67)
	at zornco.bedcraftbeyond.frames.stone.RecipeBedFrameStone.func_77569_a(RecipeBedFrameStone.java:31)
	at assets.recipehandler.CraftingHandler.getCraftResult(CraftingHandler.java:107)
	at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:142)
	at assets.recipehandler.GuiEventHandler$CreativeButton.func_146112_a(GuiEventHandler.java:49)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:71)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:81)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: slimeknights.tconstruct.tools.client.GuiStencilTable
	Mouse location: Scaled: (340, 177). Absolute: (680, 351)
	Screen size: Scaled: (683, 353). Absolute: (1366, 706). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['AquaChick555'/235, l='MpServer', x=-316.12, y=66.00, z=247.63]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-224,64,244), Chunk: (at 0,4,4 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 116020 game time, 182607 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 30 total; [EntityCreeper['Creeper'/74, l='MpServer', x=-288.50, y=21.00, z=188.50], EntityBat['Bat'/75, l='MpServer', x=-300.25, y=20.10, z=200.25], EntityCreeper['Creeper'/76, l='MpServer', x=-290.50, y=54.00, z=204.50], EntityBat['Bat'/77, l='MpServer', x=-303.60, y=60.10, z=254.71], EntityPlayerSP['AquaChick555'/235, l='MpServer', x=-316.12, y=66.00, z=247.63], EntitySkeleton['Skeleton'/26, l='MpServer', x=-389.50, y=65.00, z=181.50], EntityPolarBear['Polar Bear'/28, l='MpServer', x=-396.01, y=64.00, z=282.98], EntitySkeleton['Skeleton'/29, l='MpServer', x=-384.78, y=64.00, z=297.20], EntitySkeleton['Skeleton'/93, l='MpServer', x=-272.50, y=69.00, z=197.50], EntityBat['Bat'/94, l='MpServer', x=-285.31, y=50.10, z=295.40], EntityPolarBear['Polar Bear'/32, l='MpServer', x=-383.91, y=64.00, z=167.69], EntityItem['item.item.itemCookedBatWing'/33, l='MpServer', x=-370.70, y=42.00, z=195.70], EntityPolarBear['Polar Bear'/34, l='MpServer', x=-366.86, y=70.00, z=206.92], EntitySkeleton['Skeleton'/35, l='MpServer', x=-354.50, y=69.00, z=230.50], EntityZombie['Zombie'/42, l='MpServer', x=-340.50, y=68.00, z=178.50], EntitySkeleton['Skeleton'/43, l='MpServer', x=-342.50, y=55.00, z=210.50], EntityPolarBear['Polar Bear'/44, l='MpServer', x=-342.06, y=71.00, z=214.93], EntitySheep['Sheep'/108, l='MpServer', x=-267.48, y=68.00, z=196.81], EntityPolarBear['Polar Bear'/45, l='MpServer', x=-342.55, y=71.00, z=216.32], EntitySheep['Sheep'/109, l='MpServer', x=-259.19, y=73.00, z=228.49], EntitySkeleton['Skeleton'/110, l='MpServer', x=-257.50, y=67.00, z=318.50], EntityPolarBear['Polar Bear'/52, l='MpServer', x=-321.90, y=69.00, z=184.07], EntitySkeleton['Skeleton'/116, l='MpServer', x=-255.50, y=31.00, z=207.50], EntityZombie['Zombie'/117, l='MpServer', x=-247.50, y=29.00, z=227.50], EntitySheep['Sheep'/118, l='MpServer', x=-239.76, y=77.00, z=227.49], EntityCreeper['Creeper'/119, l='MpServer', x=-254.57, y=12.00, z=264.20], EntitySkeleton['Skeleton'/56, l='MpServer', x=-309.51, y=40.00, z=226.72], EntitySkeleton['Skeleton'/120, l='MpServer', x=-244.50, y=26.00, z=294.50], EntityCreeper['Creeper'/121, l='MpServer', x=-252.50, y=33.00, z=309.50], EntityBat['Bat'/381, l='MpServer', x=-299.25, y=18.10, z=187.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 816410424 bytes (778 MB) / 1682055168 bytes (1604 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: Minecraft 1.10.2 MCP 9.32 Powered by Forge 12.18.1.2069 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2069.jar) 
	UCHIJAAAA	Forge{12.18.1.2069} [Minecraft Forge] (forge-1.10.2-12.18.1.2069.jar) 
	UCHIJAAAA	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
	UCHIJAAAA	bedcraftbeyond{2.4.0} [BedCraft and Beyond] (BedCraftAndBeyond-1.10.2-2.4.0.jar) 
	UCHIJAAAA	BetterAchievements{0.3.0.29} [Better Achievements] (BetterAchievements-1.10.2-0.3.0.29.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2068} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2068-universal.jar) 
	UCHIJAAAA	cavern{1.1.1} [Cavern] (Cavern_1.10-v1.1.1.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAA	cs{1.0.2} [Configurable Villager to Door Ratio] (cs-1.0.2.jar) 
	UCHIJAAAA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJAAAA	DimensionalResources{1.0.3} [DimensionalResources] (Dimensional Resources v1.0.3.jar) 
	UCHIJAAAA	emeraldobsidianmod{1.5} [Emerald & Obsidian tools/armor mod] (emeraldobsidianmod-1.5-1.10.2.jar) 
	UCHIJAAAA	EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
	UCHIJAAAA	modernmetals{0.11.0} [Modern Metals] (ModernMetals-0.11.0.jar) 
	UCHIJAAAA	endmetals{1.0.4} [End Metals] (EndMetals_1.9-1.0.4.jar) 
	UCHIJAAAA	excore{1.6.1} [EXCore] (Excore-1.6.1-1.10.2.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.9.4-1.2.1.jar) 
	UCHIJAAAA	fe{1.2.1} [Food Expansion] (FoodExpansion1.2.4-1.10.2.jar) 
	UCHIJAAAA	JEI{3.9.0.246} [Just Enough Items] (jei_1.10.2-3.9.0.246.jar) 
	UCHIJAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJAAAA	FEI{1.0.15} [Forever Enough Items] (ForeverEnoughItems-1.0.15-1.10.2.jar) 
	UCHIJAAAA	fruits{1.0} [Fruits] (Fruits-1.0.jar) 
	UCHIJAAAA	gemsplus{1.7} [Gems+] (gemsplus-1.7-mc1.10.2.jar) 
	UCHIJAAAA	fishing{1.4.3} [Fishing Net Mod] (GiacomosFishingNet1.10.2-1.4.3.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	fyberbackpack{1.0.2} [Just Backpacks] (justbackpacks-mc1.9.4-1.0.2.jar) 
	UCHIJAAAA	justenoughbuttons{1.10.2-1.5.1} [Just Enough Buttons] (justenoughbuttons-1.10.2-1.5.1.jar) 
	UCHIJAAAA	jeresources{0.4.8.48} [Just Enough Resources] (JustEnoughResources-1.10.2-0.4.8.48.jar) 
	UCHIJAAAA	kitchensink{RKS1.00} [Rainbeau's Kitchen Sink] (KitchenSink-RKS1.00-MC1.10.2.jar) 
	UCHIJAAAA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.36} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
	UCHIJAAAA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UCHIJAAAA	middletorch{4.0.4} [The Middle Torch] (middletorch-4.0.4.jar) 
	UCHIJAAAA	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJAAAA	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCHIJAAAA	shear{1.1.2} [More Shearables] (MoreShearables1.2.1-1.10.2.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCHIJAAAA	nethercore{1.10.2-2.0.2} [Nether Core] (nethercore-1.10.2-2.0.2.jar) 
	UCHIJAAAA	nethermetals{1.1.2} [Nether Metals] (NetherMetals_1.9-1.1.2.jar) 
	UCHIJAAAA	ninjagear{1.10.2-0.0.3} [NinjaGear] (ninjagear-0.0.3.jar) 
	UCHIJAAAA	recipehandler{0.5} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.5(1.10.2).jar) 
	UCHIJAAAA	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCHIJAAAA	prefab{1.1.0.5} [Prefab] (prefab-1.1.0.5.jar) 
	UCHIJAAAA	reptilemod{3.5.2} [Reptile Mod] (reptilemod-1.10.2-3.5.2-56.jar) 
	UCHIJAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAA	simplequarry{1.9.4_1.0.0} [Simple Quarry] (Simple Quarry-1.9.4_1.0.0.jar) 
	UCHIJAAAA	simplebarrels{1.25g} [Simple Barrels] (simplebarrels-1.10.2-2002-1.25g.jar) 
	UCHIJAAAA	spawnercraft{3.1} [SpawnerCraft] (SpawnerCraft 1.10.2-3.1.0.jar) 
	UCHIJAAAA	Stackie{1.6.0.44} [Stackie] (Stackie-1.10.2-1.6.0.44-universal.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.2.6} [Storage Drawers] (StorageDrawers-1.10.2-3.2.6.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jar) 
	UCHIJAAAA	lteleporters{1.1.3} [Lemon's Simple Teleporters] (teleporters-1.1.3.jar) 
	UCHIJAAAA	VeinMiner{0.34.0_1.9-58ffb13} [Vein Miner] (VeinMiner-0.34.0-1.9r565+58ffb13.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.34.0_1.9-58ffb13} [Mod Support] (VeinMiner-0.34.0-1.9r565+58ffb13.jar) 
	UCHIJAAAA	wuestutilities{1.10.2.7} [Wuest Utilities] (wuestUtilities-1.10.2.7.jar) 
	UCHIJAAAA	XaeroMinimap{1.10.4} [Xaero's Minimap] (Xaeros_Minimap_1.10.4_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
SimpleCore (Simple Quarry-1.9.4_1.0.0.jar)
  com.mrdimka.simplequarry.core.SimpleClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2069
	LWJGL: 2.9.4
	OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.1855, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU T6570 @ 2.10GHz

**Comment by bonii-xx** [comment]
>at zornco.bedcraftbeyond.frames.stone.RecipeBedFrameStone.func_77569_a(RecipeBedFrameStone.java:31)
Some other mods fault

**Comment by TherminatorX** [comment]
Ping @ZornTaov

**Comment by ZornTaov** [comment]
Already fixed with BCB 2.4.1 for minecraft 1.10.2, please update

**Comment by ostenvighx** [comment]
Yes, this is a known issue and I believe it's already been fixed. Think we need to do a build with it still. You'll crash with any non-vanilla benches, if I recall.

**Comment by aquagirl555** [comment]
Thank you all for your help :)
