### ISSUE TITLE
Smeltery Contents Vanished

### ISSUE THREAD

**Issue by DatGurney** [SlimeKnights/TinkersConstruct#2356]
i tried to craft some obsidian in the smeltery. I placed in 1 bucket of water and 4 lava buckets. nothing happens and then after a few seconds the whole contents vanish. 1 block of clay was in there also

edit: Now whenever i try to put fluid into the smeltery it disappears 

edit 2: breaking and replacing the smeltery controller and putting more fluid in via the drain makes the fluid come back for a second but then vanishes if you try to re-arrange the order

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge. Also what version.

**Comment by DatGurney** [comment]
couldnt reproduce with just TiC. was using latest version

**Comment by DatGurney** [comment]
appears that it only happens when molten clay is present in the smeltery

**Comment by KnightMiner** [comment]
Issue number 3 is fixed by #2338, a temporary fix is to either break and replace the drain you used or to restart the game.

**Comment by bonii-xx** [comment]
Assuming this'll be fixed either way thanks to the changes.
