### ISSUE TITLE
Drying racks rendering orientation different from layout box

### ISSUE THREAD

**Issue by gunboy001** [SlimeKnights/TinkersConstruct#2358]

**Comment by bonii-xx** [comment]
...what?

**Comment by gunboy001** [comment]
I mean that when you place a drying rack it seems like it is oriented one way but when you point it the layout box is placed another way (the right way)

**Comment by KnightMiner** [comment]
Screenshot? And how did you obtain the rack? Crafting? Commands?

**Comment by bonii-xx** [comment]
Iirc that usually happens when the drying rack is missing its data.
