### ISSUE TITLE
I had a crash and I suppose its Tinkers Construct [1.10.2].

### ISSUE THREAD

**Issue by fullforceofpower** [SlimeKnights/TinkersConstruct#2363]
My crash is as follows:

http://pastebin.com/tT0xmeTs

Other Details:

Tinkers version: 2.4.0
Forge Build: release 1.10.2-forge1.10.2-12.18.1.2076
Possible Mods Causing Crash: Mekanism, Ender IO, Immersive Engineering and Tinkers.
Could anyone please tell me which mod is crashing it or anything about the crash.

Fullforceofpower.

**Comment by bonii-xx** [comment]
>java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects

You ran out of memory, no mod crashed.
