### ISSUE TITLE
[1.10.2-2.3.3a] Unable to create casts from Aluminum Brass

### ISSUE THREAD

**Issue by iou1name** [SlimeKnights/TinkersConstruct#2364]
I have been unable to create any kind of cast from Aluminum Brass. Gold and clay work fine, but Aluminum Brass refuses to leave the faucet when there is a casting table beneath it (the basin works fine though). The copper and aluminum are obtained from Immersive Engineering, though Mekanism also has a copper entity in my game. The problem persists in multiplayer survival and creative single player.

I am using:
Minecraft 1.10.2
TConstruct 2.3.3a
Forge 12.18.1.2076
Immersive Engineering 0.10-38
Mekanism 9.1.1.290
MultiMC 5 v0.4.11-751

Screenshots:
http://i.imgur.com/cZlGHUB.png
http://i.imgur.com/zA96KHk.png

**Comment by KnightMiner** [comment]
Known bug, already fixed in the latest Beta. If you want the fix, update to 2.4.0.
