### ISSUE TITLE
[Request] Equivalent Version for 1.7.10

### ISSUE THREAD

**Issue by chaos234** [SlimeKnights/TinkersConstruct#2366]
Hey together,

since there are many mods currently not merged to the latest MC ersion like 1.9/1.10 (I wanna skip 1.8) I am still on 1.7.10 with the Infinity Evolved MP and want to ask u how time intensive it would be to port  some fetaures from versions above MC 1.8 into the latest 1.7.10 version.

My main interest is the new GUI style and how it handles all the stations/pattern chests and so far.
Also it will be glad if some of those new effects like Width++ can be included as well.

In fact I hope that you can release a new 1.7.10 Version with a little amount of features from the latest version.

I hope that this is possible.

**Comment by bonii-xx** [comment]
No, we're not putting time into a version that has been outdated for over a year.
