### ISSUE TITLE
crash between tinkers and mekanism

### ISSUE THREAD

**Issue by scalda** [SlimeKnights/TinkersConstruct#2368]
Hi i am haveing client crashes when crafting mekinisms items in tinkers crafting table. 

i have posted on there issues aswell

crash report http://paste.ee/p/7AsET

regards

scalda

**Comment by bonii-xx** [comment]
Yes. Mekanism is breaking rendering. I wouldn't be surprised if it wrecks your FPS too. Go complain to them about it.

**Comment by scalda** [comment]
no fps is fine for me lol
