### ISSUE TITLE
Strange cross-mod interaction between TiCo and Mekanism

### ISSUE THREAD

**Issue by utoc** [SlimeKnights/TinkersConstruct#2369]
Heres a weird one, let me know if I need to send it to Aidencbrady/Mekanism instead of you.

The setup:  Make a smeltery.  3x3x10 seems to be consistent.  Now place any non-basic energy cube block from Mekanism in the same chunk.  Advanced energy Cube.  Elite, Ultimate.  Place a few of the MCMultiPart universal cables too if you like. Whatever, etc.  Now, wait.  Its a bit random but eventually (within 20-40 seconds) the advanced/elite/ultimate tiers will be stripped down and show basic in TOP (the one probe) as well as the basic textures in-game looking at the item.  All the multipart cables flash in and out of existence briefly.  I think this has to do with the smeltery establishing and reestablishing itself as a multiblock but I'm not entirely sure.  If you right click the energy block to open the GUI, it shows its proper form again (advanced, elite etc) but during the next few seconds it'll go back to being a basic.

Seen here: http://i.imgur.com/0IEy1ed.gifv

Running TiCo 2.4.0 w Mantle 0.10.4, FML 2076 and Mekanism Dev build

And heres a crash for mod versions: http://pastebin.com/thFtXNm5

**Comment by bonii-xx** [comment]
Mekanisms models are broken. They're possibly also not handling their tiles correctly if they reset on the bulk tile update event. In both cases it has to be fixed on their side.
