### ISSUE TITLE
[1.10.2] 11x11 smeltery dosent work

### ISSUE THREAD

**Issue by Morpheus1101** [SlimeKnights/TinkersConstruct#2371]
So i built an 11x11 smeltery to test out on the MMD Server and it dosent work. I built it like i do the 7x7 which i make a 7x7 base an then add the things around outside .. same with the 11x11 .. 11x11 base add things around outside

**Comment by KnightMiner** [comment]
Does 9x9 work? And are you building the inside to be 11x11, or the whole structure?

**Comment by Morpheus1101** [comment]
9x9 works .. but i thought 11x11 meant that the base itself is 11x11 blocks then add the outside blocks, drains etc

**Comment by bonii-xx** [comment]
That's 13x13. 9x9 is internal. Relict from the old 3x3 smelteries.
