### ISSUE TITLE
[1.10.2] Can't Remelt Blank Casts

### ISSUE THREAD

**Issue by DFliyerz** [SlimeKnights/TinkersConstruct#2378]
Aluminum brass blank casts can no longer be remelted in the smeltery to make more casts, making them essentially useless.

**Comment by ArukaAlter** [comment]
Brass, alu-brass and gold now make a single type of cast now, it has been discussed before.

**Comment by KnightMiner** [comment]
Press "U" over the blank cast in JEI. Useless you say?

**Comment by DFliyerz** [comment]
Well, I'm used to being able to make a bunch of blank casts and re-melt them when I need to make a certain cast, as you were able to do in 1.7.10.

**Comment by KnightMiner** [comment]
Just keep it in ingots. There are reasons it does not melt and being used to the old way is not more important
