### ISSUE TITLE
Crash of some kind (java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by jensz12** [SlimeKnights/TinkersConstruct#2379]
This might be a Mantle bug!
But i have a strange crash, after i updated my server with the lastest Tinkers and Mantle 1.10.2 versions.
Seems to be related to Realms for some strange reason

Caused by: java.lang.NoClassDefFoundError: com/mojang/realmsclient/util/Pair

[crash-2016-09-12_14.45.13-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/467333/crash-2016-09-12_14.45.13-server.txt)

**Comment by bonii-xx** [comment]
Oh my. looks like an incorrect import.

**Comment by jensz12** [comment]
When can we expect a release with this fix in

**Comment by bonii-xx** [comment]
Now.
