### ISSUE TITLE
Crafting station to check below first, preferably work with trapped chests

### ISSUE THREAD

**Issue by borg286** [SlimeKnights/TinkersConstruct#2380]
I'd like to be able to have adjacent rows of large crafting chests (alternating trapped chests and normal chests), and have a crafting station hooked up to each row.

The bug is that a crafting station first checks its own elevation, and disregards what type of chest it finds if it finds 2 chests 1 block away. It even mixes up inventories by grabbing 1/2 of a normal large chest, and 1/2 of a large trapped chest kitty-corner to the chest.
S=Station
T=Trapped Chest
C=Normal Chest

STT
SCC

This lower Station(S) sees the first T and first C instead of CC.

The crafting slab has the same problem. The slab encourages players to place them on top of chests, but if there happens to be a chest at the same elevation then the crafting station/slab chooses that one instead of the one it is on top of.

This bug is to track progress on supporting only attaching to chests that the chest is attached to. This should be easily done by first checking below, then continuing with the normal sweep afterwards.
Second to match on not only it being attached to a chest, but that a second chest also matches the specific type that was first matched, trapped or normal.

Thus you could have a large normal chest with a trapped chest on one top and a crafting slab on the other, and have the crafting slab's inventory correspond to the normal large chest, and not attach to the trapped chest. If the player wanted a the crafting ability on the trapped chest he should use a crafting 
he player wanted a the crafting ability on the trapped chest he should use a crafting slab instead of a station and place it on top.

**Comment by bonii-xx** [comment]
You're talking about 1.7.10, aren't you

**Comment by borg286** [comment]
Yes. Is this fixed in later versions?

**Comment by bonii-xx** [comment]
Basically. The 1.8+ version doesn't check vertically at all :P
