### ISSUE TITLE
[Bug] Missing Sharpening Kit Pattern

### ISSUE THREAD

**Issue by 4Magma** [SlimeKnights/TinkersConstruct#2383]
use 2.5.1
- stencil table has no sharpening kit pattern option on the left side
- cheated one in with JEI in and put it in pattern chest
- but part crafter still does not show the pattern

**Comment by Morpheus1101** [comment]
I can confirm that the sharpening kit has indeed gone MIA and only way to obtain it atm is to cheat one in.

**Comment by KnightMiner** [comment]
This should already be fixed in 2.5.2 via 2dd9982. Boni just forgot to link the issue in the commit.
