### ISSUE TITLE
1.10.2 - Constant server crashing "Cannot get property PropertyAnyInteger"

### ISSUE THREAD

**Issue by viper2g1** [SlimeKnights/TinkersConstruct#2385]
Minecraft: 1.10.2
Forge: 12.18.1.2086
TConstruct: 1.10-2.3.3a.jenkins271

Seems that the slime grass is causing a crash constantly on my server.  The server can stay alive for about 5-10 minutes before a crash. 

The crash: 

java.lang.IllegalArgumentException: Cannot get property PropertyAnyInteger{name=variation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateContainer{block=tconstruct:slime_grass, properties=[foliage, snowy, type]}

Here is the log:
https://gist.github.com/viper2g1/4befed30401b158f0e470ebc0e71d331

**Comment by LovelyFlare** [comment]
You're using an outdated version...

**Comment by viper2g1** [comment]
Very much so. Odd that Curse didn't notify me of the updates available.

**Comment by viper2g1** [comment]
I'll close this and reopen if the error continues.
