### ISSUE TITLE
45k fletchings

### ISSUE THREAD

**Issue by Badcholo** [SlimeKnights/TinkersConstruct#2386]
i use ender io and created a simple tree farm. 1 day later i have 45k in my refined storage computer. I can't destroy the fletchings fast enough. A config to change the chance of dropping from decaying or broken leaves would be nice. Thank you. Version TConstruct-1.10.2-2.4.0

**Comment by bonii-xx** [comment]
...what fletchings?

**Comment by Badcholo** [comment]
Fletching that drop from the trees to make arrows. I thought it was this mod that added that to the world. It seems to be a replacement for feathers.

**Comment by LovelyFlare** [comment]
There's no fletchings from Tinkers' Construct from that version...

**Comment by bonii-xx** [comment]
Nope, that's not from TiC, must be some other mod

**Comment by Badcholo** [comment]
Sorry, i had just created the server and i hadn't added the waila mod yet, it is from feldins homstead mod. Sorry and thank you.

**Comment by bonii-xx** [comment]
As LovelyFlage said, you can always enable the extended tooltips in Minecraft, it'll show you more details in the tooltip too.
