### ISSUE TITLE
[JEI] FPS dropping looking up complete tools

### ISSUE THREAD

**Issue by ChrisCrisis** [SlimeKnights/TinkersConstruct#2388]
Hi there, 
I noticed that when you open the inventory and look up prismarine for example the FPS drop from 60 down to 15 - 20. 
I narrowed it down by looking up TiCon stuff and noticed that with "@Tinkers" everything is fine until you get to the whole tools, than the FPS drop again.
I had the problem with and without Optifine.

Not sure so sure if that was an TiCon issue or JEI one.

**Comment by KnightMiner** [comment]
Tinkers Construct version?

**Comment by bonii-xx** [comment]
Also CPU, Graphic card and RAM allocated?

**Comment by ChrisCrisis** [comment]
It was the latest Beta from CurseForge, so TConstruct-1.10.2-2.4.0.
Ram is at 4GB and my GraphicCard is the NVidia NVS 5400M.
The Processor is the Intel i5 3210M with 2,5GHz

**Comment by kellixon** [comment]
The same problem, ChrisCrisis.
Java 8u102-Windows-x64, MC1.10.2, Forge 12.18.1.2092. JEI 3.9.5.257, Tinkers'Construct2 2.5.2, Mantle 1.0.0. Large drawdown fps on page JEI, where tools and weapons - 3-5fps, in game - over 90.
Intel  i3-3220 with 3,3GHz, Ram is at 8GB, GraphicCard is the NVidia GTX 550.
Original my message on TiC2 on forum - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638-tinkers-construct-2?comment=4960

**Comment by bonii-xx** [comment]
TiC tools are relatively complex compared to standard vanilla tools. Displaying a full page on your GUI size might simply be too much for your hardware. You can try hiding the TiC tools using JEIs filter stuff.

> -My custom font (mod Better Fonts) don`t working at prompting in JEI for these items.

TiC uses a custom fontrenderer for its items (see Item.getFontRenderer) for the colors. The font is currently hardcoded to vanillas font location (since that's what resource packs use).

> -Mod WailaHarvestability 1.1.8 - working is unstable, message "< ERROR >" at prompting on the items

Fixed next version

**Comment by GirafiStudios** [comment]
The issue with Waila Harvestability is already fixed on their side too in version 1.1.9 :)

**Comment by kellixon** [comment]
I watch for updates regularly and 1.1.9 was installed 10 minutes after the release version. But from TiC had to be abandoned((

**Comment by bonii-xx** [comment]
I just put in a small cache for the tool models, we'll see where it goes from there. It should speed up situations like this a lot. Keep an eye out for it in 2.5.6

**Comment by bonii-xx** [comment]
2.5.6 is live already if you want to check. Should be much better now.
