### ISSUE TITLE
[Crash] java.lang.IllegalStateException: Already tesselating!

### ISSUE THREAD

**Issue by piousminion** [SlimeKnights/TinkersConstruct#2389]
[crash-2016-09-16_03.32.16-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/476311/crash-2016-09-16_03.32.16-client.txt)

**Comment by bonii-xx** [comment]
What did you put into the casting table?

**Comment by piousminion** [comment]
I wasn't using a casting table at all.

I found a "solution" though in tinkering. Setting Optifine's "chunk loading" from smooth to default eliminates the crash. Not sure which mod is at fault, but glad it's now documented in case someone else has the issue.

**Comment by bonii-xx** [comment]
Optifines fault, usually
