### ISSUE TITLE
NoClassDef Found referencing cleaver

### ISSUE THREAD

**Issue by GreatOrator** [SlimeKnights/TinkersConstruct#2390]
http://pastebin.com/QbkiPB1v

Get's about to the third phase of mod loading and this crash happens

**Comment by zackeezy** [comment]
It's a problem with Reliquary, and was a known bug.  The mod dev fixed it in the latest version, so just upgrade your Reliquary version. It was a problem with how the pedestal interacted with the tinkers tools. It's fixed now, though.

**Comment by GreatOrator** [comment]
Sigh...I honestly thought I had grabbed the latest version and tested before this post...sorry about that.

**Comment by bonii-xx** [comment]
This is exactly the reason why it's an alpha ;)
