### ISSUE TITLE
(Stupid question) Are crossbows going to be added to 1.10.2?

### ISSUE THREAD

**Issue by LordHellscream** [SlimeKnights/TinkersConstruct#2392]
Really new to tinker, and noticed some of the tools (like the crossbows) I kept reading about are not available in 1.10.2, are those going to be added?

Thanks!

**Comment by bonii-xx** [comment]
yes

**Comment by LovelyFlare** [comment]
Read the [FAQ](https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ)...

Also... you wouldn't ask this question in the first place if you didn't ignore this...
![really](https://cloud.githubusercontent.com/assets/14182009/18617836/ae1e62d2-7da7-11e6-9759-6ce23bb73772.PNG)
