### ISSUE TITLE
some items will not craft

### ISSUE THREAD

**Issue by WayneFrancis** [SlimeKnights/TinkersConstruct#2393]
So far these items I have not been able to craft
Materials and You: Volume 1 (1 blank pattern + 1 piece of paper)
1 Ball of Moss: Crafted with 9x Mossy Cobblestone/Mossy Stone Brick
Other recipes so far are working like quartz block, tables, making smeltery, etc

![matandyou](https://cloud.githubusercontent.com/assets/1401131/18615713/8a628662-7dec-11e6-8e08-27d589e3d5c9.png)

![mossball](https://cloud.githubusercontent.com/assets/1401131/18615702/2f438fba-7dec-11e6-8e98-88a203bc3fdd.png)

**Comment by ArukaAlter** [comment]
What version are you using? Have you checked if JEI shows if those recipes exist?

**Comment by bonii-xx** [comment]
Try reproducing with only tic and mantle, latest versions

**Comment by WayneFrancis** [comment]
It is a 1.8.9 server.  Stripped it back down to just 
TConstruct-1.8.9-2.2.1 
and Mantle-1.8.9-0.9.2 
nothing  else still nothing for those 2 items.

I tried using and older Mantle-1.8.9-0.9.1 and TConstruct-1.8.9-2.2.0b 
still nothing in creative mod or survival mode for the book or the ball of moss
Everything else they are doing works so far.

**Comment by bonii-xx** [comment]
You're on 1.8.9, that's why. Those items don't exist. Update to 1.10.2.
