### ISSUE TITLE
Pixelmon+Tinkers 1.7.10 Blue Slimes spawn everywhere!

### ISSUE THREAD

**Issue by Ender2Squid** [SlimeKnights/TinkersConstruct#2395]
I'm not sure why, it might be a bug with my version of Tinkers Construct maybe? but blue slimes are spawning everywhere, whenever there is enough space. In caves when I'm mining, when I'm exploring, when I just wanna go home they are in my house, it kinda sucks. I haven't been able to find anything online to help. mods----Technic launcher:: Pixelmon+ with Tinkers Construct added

**Comment by LovelyFlare** [comment]
Doesn't sound like a Tinkers' issue...

1.7.10 is not supported anyway.

**Comment by Ender2Squid** [comment]
I just went to the nether, and they are in there too.
