### ISSUE TITLE
[1.10.2] [Bug] Tinkers' Construct Crafting Station's attached Chest inventory doesn't let you exchange stacks in hand

### ISSUE THREAD

**Issue by SnowShock35** [SlimeKnights/TinkersConstruct#2396]
Hello,

I believe to have found a bug for Tinkers' Construct. Here are the details. . . 
### Important Information
- Minecraft 1.10.2
- Minecraft Forge 12.18.1.2092
- Mantle 1.0.0
- Tinkers' Construct 1.10.2-252
### Issue Description

When a Crafting Station is placed next to a chest, you're unable to stack exchange items within the chest's inventory (via the Crafting Station) which you usually are able to do within the normal inventory. 

The below .GIF better explains the issue. (Found at the bottom of the issue under Media) 
### Steps to Reproduce
1. Boot Minecraft with the above listed mods installed
2. Create a new world
3. Obtain a Minecraft chest and a Tinkers' Construct Crafting Station
4. Place one down then place the other adjacent to it on one of the six sides of the block
5. Place an item stack inside the chest then open up the Crafting Station (Make sure to have some items in your own inventory)
6. Pick up the items so they're attached to the cursor within the inventory
7. Click one of the item stacks that are in the adjacent chest via the Crafting Station window 

You should find that the two stacks do not swap when left clicking on them. 
### Media

https://gfycat.com/OldfashionedBasicAmericanquarterhorse

**Comment by bonii-xx** [comment]
Hm, I suspect this broke when the IItemHandler change happened in Forge. Should be fixable.

**Comment by SnowShock35** [comment]
Cool. Thanks boni :+1:

**Comment by bonii-xx** [comment]
Yup, this probably never worked since capabilities were introduced. And it's technically a forge bug.

**Comment by SnowShock35** [comment]
> technically a forge bug

Should I forward this to https://github.com/MinecraftForge/MinecraftForge or is it something you'll bring up with them?

**Comment by bonii-xx** [comment]
I'll probably just fix it myself.

**Comment by SnowShock35** [comment]
Okay thank you boni. I appreciate it lots  :heart:

**Comment by bonii-xx** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/3273

**Comment by KnightMiner** [comment]
Closing this issue, since it appears fixed in the latest Forge build (and MinecraftForge/MinecraftForge#3273 was merged)
