### ISSUE TITLE
[1.7.10-1.8.8.jar] Ghost Blocks appearing over the Smeltery if smth. is processed in it.

### ISSUE THREAD

**Issue by chaos234** [SlimeKnights/TinkersConstruct#2398]
Hey,

since the last 24h I recognized ghost block creation up to 4/5 layers if you put in some smeltable ore/dust/... - This happens to me and two other Players playing on a MP Server with TC installed.

Img from the Ghost Blocks: http://www.directupload.net/file/d/4482/ix92r8v5_png.htm
Error Log from the Client: http://pastebin.com/raw/K5rn2p4W

Only one player does not get this error but nothing hase changed to the MP-Servers config nor the mods so what can cause this problem?

Restarting the Server, rebuilding the Smetlery with different dimensions and also restarting the Server nor compleatly unloading and reloading the chunk solved this issue.

MCV: 1.7.10
TCV: stated in the title
Optifine: 1.7.10 HD U D6
MCP: v9.05
FML: v7.10.99.99
MF: 10.13.4.1614

MP is a modified FTB Infinity Evolved Pack and until this day it worked fine and without any issue.
So what can cause this problem?

**Comment by chaos234** [comment]
I found the issue.

Pls don't update from OF U4 to U6 otherwise you will get the error above.
I'll reporting it to the OF team now.

**Comment by LovelyFlare** [comment]
You should probably know that OptiFine isn't supported due to graphical glitches such as these.

**Comment by chaos234** [comment]
This was my first experience having an issue related to OF.

**Comment by KnightMiner** [comment]
You are going to find many more, especially in 1.7.

We also have officially dropped support for the 1.7.10 version of Tinkers in favor of the 1.10.2 version

**Comment by chaos234** [comment]
Oh, ok.

But because it was an OF bug this shouldn't be matter. It is reported to them and they must fix it now ^^.

However, does this mean that you won't release any minor bugfixes to the 1.7.10 version? Releasing no new content for it is ok since 1.7.10 is rly old (like XP ^^) but collecting a few issus and fixing them with one push should be ok or not?

I know working on two kinds of versions can be hard but if the support was fully dropped then ok and thanks for that information.
