### ISSUE TITLE
Mending moss not working on shuriken

### ISSUE THREAD

**Issue by thomscott** [SlimeKnights/TinkersConstruct#2399]
mod version
TC 1.10.2-2.4.0
Forge 12.18.2088
Mantle 0.10.4
journey map 1.10.2-5.2.4

I made a shuriken out of bone and manyullyn when i applied the moss it didn't repair it once used

**Comment by KnightMiner** [comment]
Did you collect XP to "fuel" the moss? You need to be holding it when the XP is collected.

**Comment by bonii-xx** [comment]
As KnightMiner said, your shurikens probably don't have any XP stored. You can check at a tool station/forge.

**Comment by thomscott** [comment]
I did have xp at one point. i know how that works. though when ever you
would kill an entity with the shurikens they would not drop exp. This i
assume is because killing them with a shuriken doesn't count as a player
kill.

**Comment by bonii-xx** [comment]
That's fixed in the latest versions. Update your TiC.
