### ISSUE TITLE
Tool Forge Selection Issue

### ISSUE THREAD

**Issue by SiocMacTire** [SlimeKnights/TinkersConstruct#2401]
Trying to craft a hammer. Upgraded tool station to tool forge, but can't select the Hammer or Excavator pattern, and sometimes not the Lumber axe pattern either. I right click Forge, then try to click hammer in left hand menu, and nothing happens. If I click any tool pattern besides those 2(3) then the proper slots appear in main window. 

Only mods should be tinkers construct and JEI/FEI. Latest updates on all.

**Comment by bonii-xx** [comment]
That sounds really weird. Make sure you're there's only TiC and Mantle present. When it happens, check your log for errors.

**Comment by SiocMacTire** [comment]
Resolved itself? Reloading didn't work at first, but left minecraft off for a couple hours and now everything works.....No idea why.

**Comment by SiocMacTire** [comment]
And now I can't select those three icons anymore. Disabling FEI/JEI. WIll post if it works.

**Comment by SiocMacTire** [comment]
Seems to appear after I break a block with a tinkers tool when FEI/JEI is enabled.

**Comment by bonii-xx** [comment]
What if there's only TiC, Mantle and JEI? That shouldn't cause any problems. As for FEI.. never heard of that.

**Comment by KnightMiner** [comment]
FEI is an addon for JEI which is known to cause issues with JEI, last I checked reports on the JEI tracker are banned if it is installed. JEI alone shouldn't cause problems with Tinkers, if it does without FEI this issue might be valid.

**Comment by ByeByeTurtle** [comment]
Hi! I have this problem too, I'm in the tool forge and it will not let me click on the hammer pattern choice. Any ideas of what I'm suppose to do???

**Comment by KnightMiner** [comment]
Did you try it with just Tinkers and Mantle (and possibly JEI)?
