### ISSUE TITLE
WARN console spam

### ISSUE THREAD

**Issue by C0rn3j** [SlimeKnights/TinkersConstruct#2403]
Not sure whether this is your problem or IE and Forestry problem.

---

I got tired of spammy console output. I've noted every single WARN and STDERR(just a single one, from Lootbags) during server startup. I've decided that I will not be making 63 separate issue descriptions, so I've added line numbers to each mod name which correspond to the server startup log line numbers. 

Some mods have more problems, so there will be numbers separated by a comma. 

I do realize that a lot of those are warnings when transitioning to 1.11, but it still throws a WARN now.

Forge 2092
Modlist: http://pastebin.com/aXWf0Cuq
Server launch: http://pastebin.com/gsyQ3YSb

Actually Additions: 1324
aroma1997 Core: 7, 86
Aroma1997sDimension: 96, 947
AromaBackup: 105
AutoRegLib: 126
AutoSapling: 135
AppleCore: 75-84
Baubles: 145
BetterAchievements: 163
BetterBedrockGen: 154
BetterFoliage: 8, 172
BetterSprinting: 182
BiomesOPlenty: 192
BloodMagic: 201
Botania: 210
Calculator: 219
Chameleon: 228
ChickenChunks: 237
Chisel: 1182
codechicken.core, codechicken.lib: 10 - 13
EnderIO: 249, 696, 1368, 1575
EnderStorage: 258
enchiridion: 1972
Evilcraft: 1179, 1382, 1970(actually cyclops core)
ExtraUtils2: 268
FloodLights: 278
Fluxed Redstone: 14
Forestry: 743 - might be TC fault
HoloInventory: 288
immersiveengineering: 578 - might be TC fault
Inventory Tweaks: 15
IngameAccountSwitcher: 298
InGameInfoXML: 308
IvToolkit: 16
JEI: 318
jurassicraft: 1969
LootBags: 1710 - STDERR - xxxKB of error logs, 1973
LunatriusCore: 328
MCA: 337
Morphtool: 348
Morpheus: 357
Neat: 366
nethercore: 375
OfflineSkins: 17, 376
OpenComputers: 378
OpenFM: 18
powerinventory: 386
Psi: 388
Quark: 19, 397
RadixCore: 406
Random Things: 20
roots: 1980
Roguelike: 415
SonarCore: 424, 980, 984
StorageDrawers: 433
Tconstruct: 578, 743 - might be IE or/and Forestry fault
TechReborn: 904
TinkersAddons: 442
trashslot: 450
UniDict: 452
VeinMiner: 461
Waila: 479, 1598
WailaHarvestability: 488
waystones: 497

**Comment by bonii-xx** [comment]
Don't worry, those are well known and not dangerous at all. They happen because of how TiC handles its dynamic integration with other mods, there's no way to prevent Forge from posting the warnings. They're there to warn modders that they're doing something at the wrong time, but in TiC's case it's correct.

**Comment by bonii-xx** [comment]
I see you also have a lot of modid warnings in there. Modders wont be able to change those before MC 1.11, since all other mods relying on the mod would fail then.

**Comment by C0rn3j** [comment]
Ah, god dammit, I knew I shouldn't have bothered with the modIDs. Thanks for the info, now I don't need to spam tons of trackers with unfixable issues.

>They're there to warn modders that they're doing something at the wrong time, but in TiC's case it's correct.

Oh well, thanks for responding so quickly.

**Comment by bonii-xx** [comment]
Just FYI, the modid is the thing that uniquely identifies a mod. So when you have an addon, or something that interacts with another mod, or that needs to load after another mod, then you tell it to do so via modid. If you change it.. well then everything goes boom, so you can't do it mid version.
