### ISSUE TITLE
[1.10.2] [Visual Bug] Inside of molten metals placed in world always look like lava

### ISSUE THREAD

**Issue by starg09** [SlimeKnights/TinkersConstruct#2404]
This is pretty minor, but as someone reported it, probably better to let you know :)

Video: https://gfycat.com/SarcasticFrequentAlaskankleekai

Version is 1.10.2-2.5.2, Forge build 2092

**Comment by bonii-xx** [comment]
Heh. That's actually minecraft adding the lava overlay to your screen (or lava "fog"), similar to how everything is blue underwater. There only is water and lava in MC, so it uses the standard lava one.

**Comment by starg09** [comment]
Oh, all right then! so it will probably stay like that for now, thanks :P
