### ISSUE TITLE
[Needed Suggestion]Iguanna leveling system

### ISSUE THREAD

**Issue by mightydanp** [SlimeKnights/TinkersConstruct#2408]
I was hoping you would a few futures via config for you mod.
IguanaLeveling- Basically means that it would have the tool leveling of igurana tweaks. In eclipse I Changed a bit of code and got it possible via config.
HarvestLevel Changing of blocks and pickaxes via config. I have also done this via config in one of the mods i am working on.

I have made a tiar system

stone-basic or soft materials such as slime, paper, cactus, ...ect
tin- should plain and simple be copper or other soft metals-
iron- should be bronze or other medium hard ended alloys such as knightmetal
obsidian-plainly be steel or any other mediam to high end material
aridite- should be aluminium or any high end material
cobalt- ardite.

**Comment by bonii-xx** [comment]
No, this is not iguana tweaks.
