### ISSUE TITLE
Calling ForgeHooks.canToolHarvestBlock with a "shouldUseOffhand" tool in the main hand throws NPE

### ISSUE THREAD

**Issue by squeek502** [SlimeKnights/TinkersConstruct#2409]
See squeek502/WailaHarvestability#49

Relevant code:

https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/tools/TinkerToolCore.java#L56

From what I can tell, TiC should be checking whether or not the input itemstack is the mainhand/offhand instead of assuming it is the offhand.

**Comment by bonii-xx** [comment]
You find the weirdest things, heh.

**Comment by bonii-xx** [comment]
I'm trying to figure out where it errors out, but I can't seem to find it? The logs in your linked issue also don't show any NPE in TiC itself.

**Comment by squeek502** [comment]
Oh, it's actually much simpler than I thought. ForgeHooks.canToolHarvestBlock passes a null player object to getHarvestLevel, which DualToolHarvestUtils.shouldUseOffhand is assuming to be non-null. Just need to throw in a null check there somewhere.
