### ISSUE TITLE
Inconsistency with the function and description of Expander Modules

### ISSUE THREAD

**Issue by Fokson** [SlimeKnights/TinkersConstruct#2411]
Width++ and Height++ are stated by the book to be "Multiple Level", as seen here:
![](http://puu.sh/rmTPG/74a9240fdb.jpg)

But when attempting to apply more than one to a tool, you're greeted with this:
![](http://puu.sh/rmTUf/5980e1d334.jpg)

TConstruct-1.10.2-2.5.1
Forge 12.18.1.2093

**Comment by bonii-xx** [comment]
It should state that both can be applied, not multiple levels, right.
