### ISSUE TITLE
[1.10.2] [Suggestion] Ability to dismiss patterns from part builder

### ISSUE THREAD

**Issue by SnowShock35** [SlimeKnights/TinkersConstruct#2415]
Within the part builder, if adjacent to a pattern chest with patterns in it you're able to click on the patterns via the buttons on the left hand side. However, once a pattern is in your table there's no way to place it back other than to switch tabs and then do it manually. Although this is minor it would be awesome to have a small `x` or dismiss button that you could click to put it back.

A minor and yet unworthy suggestion however a suggestion none the less.

**Comment by bonii-xx** [comment]
..the solution is to click another button. You just click another button. You don't put it back manually.

**Comment by laz2727** [comment]
When you place it at you base, maybe. But not when on the move.

**Comment by KnightMiner** [comment]
How often do you move? Its not that much harder to manually place it in the slot then for such a rare occurance

**Comment by SnowShock35** [comment]
Like I mentioned in the original description of this issue post it was a minor suggestion and tbh boni is probably right. It's not important
