### ISSUE TITLE
"Unbreakable" Mattocks are still breakable when using the hoe function

### ISSUE THREAD

**Issue by BillboardEric** [SlimeKnights/TinkersConstruct#2416]
Title. The axe and shovel function remove no durability, while the hoe function does.

**Comment by bonii-xx** [comment]
Version?

**Comment by BillboardEric** [comment]
Latest. 2.5.2

**Comment by bonii-xx** [comment]
Screenshot of the mattock and what it's made of please

**Comment by BillboardEric** [comment]
After some testing for a few minutes, happens with multiple of them.
![2016-09-27_15 25 42](https://cloud.githubusercontent.com/assets/8685981/18888544/ca0ead1e-84c6-11e6-9a60-c42df4a9a86e.png)
![2016-09-27_15 25 45](https://cloud.githubusercontent.com/assets/8685981/18888545/ca20696e-84c6-11e6-99f3-99cf05ff7737.png)

**Comment by bonii-xx** [comment]
Hm, what exactly did you do to reproduce it?

**Comment by BillboardEric** [comment]
Kept crafting different mattocks by spawning them in as pieces and constructing it in the Tool Forge, applied 5 levels of reinforced, and finally tested on dirt. I used Tinkers' Addons to easily add modifies when needed.

**Comment by bonii-xx** [comment]
You can just use creative modifiers :P
I meant how did you test if it uses durability sometimes. I wonder if it's a rounding error

**Comment by BillboardEric** [comment]
I tested it on some dirt, as well as logs. It took durability on tilling dirt but not for breaking dirt and logs.

**Comment by BillboardEric** [comment]
Do you need a mod list, as in could it be something conflicting?

**Comment by bonii-xx** [comment]
Found it.

**Comment by BillboardEric** [comment]
:)
