### ISSUE TITLE
[1.10] World crashes while trying to craft an Armored Jetpack (Mekanism) on a TConstruct crafting station

### ISSUE THREAD

**Issue by cryptrol** [SlimeKnights/TinkersConstruct#2417]
Ways to reproduce :
* Add a Crafting station from TConstruct
* Add items needed to craft an Armored Jetpack
* The game crashes

Using latest Forge (2093), Mekanism 292 and TConstruct-1.10.2-2.5.1

The world crashes and it's not possible to (reliably) start it again until you remove the items from the crafting station (I did it with NBTexplorer).

I don't know if this is a TConstruct or Mekanism issue and the debug messages are far from informative (to me anyway).

**Comment by bonii-xx** [comment]
Mekanism issue.
