### ISSUE TITLE
1.10.2 Vanilla Enchantment Disappears after exit the game and back in

### ISSUE THREAD

**Issue by LordHellscream** [SlimeKnights/TinkersConstruct#2418]
Pretty new to tinker so I am sure if this is expected, I added mending to a tool today and later found out it was gone. After some testing i noticed when I exit the game and come back the enchantment is gone!

Using version 2.3.3a

**Comment by ArukaAlter** [comment]
Mending can be applied via Mending Moss, no enchantments are supposed to be applied on TCon tools.

**Comment by bonii-xx** [comment]
The real question is... how did you get mending onto the tool in the first place?

**Comment by LordHellscream** [comment]
not sure, i just do. I was still using 2.3.3a (its the release version from June), I just updated to 2.5.2 but it crashed to desktop. I created a new bug for that one.

**Comment by McBossKiller** [comment]
I had the same problem, I put efficiency V on a golden pick made with Tinkers and redstone modifiers, Made a super fast pick that i loved, next day it was gone, My backup didn't even bring it back. As a side topic, I do believe that tinker's modifiers do take away the use of an enchantment table.

**Comment by bonii-xx** [comment]
So.. how did you get the enchantments on it? :P

**Comment by C1ffisme** [comment]
@bonii-xx Probably through the /enchant command, or with an enchanted book. (Is it possible to combine an Enchanted Book with a Tinkers' Construct item in survival mode?)

**Comment by LordHellscream** [comment]
it was actually possible to enchant it normally using enchanted book on an anvil at least with 2.3.3a version, the newer version its not possible anymore (which is good)

**Comment by bonii-xx** [comment]
Yeah, there was an old bug, but that has been fixed long ago. K, closing this then since it's not possible anymore.
