### ISSUE TITLE
(1.10.2) Crash on game start after updating from 2.3.3a to 2.5.2 

### ISSUE THREAD

**Issue by LordHellscream** [SlimeKnights/TinkersConstruct#2419]
http://pastebin.com/Prs0mwCX

TConstruct Version : Updating from 2.3.3a to 2.5.2
Game CTD on launch.

**Comment by bonii-xx** [comment]
Update your mods, read the changelog.

**Comment by LordHellscream** [comment]
Apologize I am new to tinker. May I ask dupe to which bug? kindly point me to the changelog (or which mod to update)?

**Comment by bonii-xx** [comment]
https://minecraft.curseforge.com/projects/tinkers-construct/files/2330969
