### ISSUE TITLE
ranged weapons not loading into game

### ISSUE THREAD

**Issue by ansiliden** [SlimeKnights/TinkersConstruct#2421]
The ranged weapons are not loading into the game the only one loading is the shuriken. i had a problem with crashing that i sorted and in the info it said they were being loading but as you can see they are not and were not since i installed the mod. 

![2016-09-29_10 23 54](https://cloud.githubusercontent.com/assets/20793504/18936938/bb9917a8-85a0-11e6-9a98-db1cd6e33d06.png)
![2016-09-29_10 24 35](https://cloud.githubusercontent.com/assets/20793504/18936942/bbc37bba-85a0-11e6-863d-bb8affefe92a.png)
![2016-09-29_10 24 44](https://cloud.githubusercontent.com/assets/20793504/18936941/bba199e6-85a0-11e6-92d9-b91b4eb39040.png)
![2016-09-29_10 23 43](https://cloud.githubusercontent.com/assets/20793504/18936939/bb9ec266-85a0-11e6-9ed3-17aeca27a413.png)
![2016-09-29_10 23 52](https://cloud.githubusercontent.com/assets/20793504/18936940/bba0ccf0-85a0-11e6-8f73-d5136366a546.png)

**Comment by ArukaAlter** [comment]
They don't exist since 1.8, and are still being worked on.

**Comment by bonii-xx** [comment]
Yup.
