### ISSUE TITLE
Question regarding localization

### ISSUE THREAD

**Issue by ArukaAlter** [SlimeKnights/TinkersConstruct#2423]
Adjectives behave different in portuguese, spanish and similar languages, they aren't put in the same order as in english, it was quite strange back on 1.5~1.7 and with so I can't push the pt_BR localization.
So, is it possible to use "material.[material].prefix=" for every material?

**Comment by bonii-xx** [comment]
Yes, see https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tconstruct/lang/en_US.lang#L500

**Comment by ArukaAlter** [comment]
That will do, thanks.
