### ISSUE TITLE
Shift right-clicking hoppers on a drying rack

### ISSUE THREAD

**Issue by McBossKiller** [SlimeKnights/TinkersConstruct#2426]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  IC2core (industrialcraft-2-2.6.81-ex110.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 9/29/16 6:09 PM
Description: Tesselating block in world

java.lang.NullPointerException: Tesselating block in world
    at slimeknights.tconstruct.gadgets.tileentity.TileItemRack.setInventoryDisplay(TileItemRack.java:35)
    at slimeknights.tconstruct.shared.tileentity.TileTable.writeExtendedBlockState(TileTable.java:71)
    at slimeknights.tconstruct.shared.block.BlockTable.getExtendedState(BlockTable.java:108)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:278)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at slimeknights.tconstruct.gadgets.tileentity.TileItemRack.setInventoryDisplay(TileItemRack.java:35)
    at slimeknights.tconstruct.shared.tileentity.TileTable.writeExtendedBlockState(TileTable.java:71)
    at slimeknights.tconstruct.shared.block.BlockTable.getExtendedState(BlockTable.java:108)

-- Block being tesselated --
Details:
    Block type: ID #856 (tile.tconstruct.rack // slimeknights.tconstruct.gadgets.block.BlockRack)
    Block data value: 7 / 0x7 / 0b0111
    Block location: World: (210,57,1314), Chunk: (at 2,3,2 in 13,82; contains blocks 208,0,1312 to 223,255,1327), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['coolbuilder65'/6, l='MpServer', x=210.19, y=59.82, z=1314.69]]
    Chunk stats: MultiplayerChunkCache: 599, 599
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (224,4,1325), Chunk: (at 0,0,13 in 14,82; contains blocks 224,0,1312 to 239,255,1327), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
    Level time: 12811 game time, 12811 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 34 total; [EntityItem['item.item.rottenFlesh'/576456, l='MpServer', x=204.13, y=58.00, z=1317.79], EntityZombie['Husk'/557129, l='MpServer', x=205.64, y=58.00, z=1319.82], EntityZombie['Husk'/559049, l='MpServer', x=205.79, y=58.00, z=1317.72], EntityItem['item.item.rottenFlesh'/577929, l='MpServer', x=209.83, y=58.00, z=1316.66], EntityZombie['Husk'/561162, l='MpServer', x=204.30, y=58.00, z=1319.82], EntityZombie['Husk'/559053, l='MpServer', x=204.30, y=58.00, z=1320.61], EntityZombie['Husk'/578253, l='MpServer', x=204.99, y=58.00, z=1320.28], EntityZombie['Husk'/559054, l='MpServer', x=205.56, y=58.00, z=1317.02], EntityZombie['Husk'/561166, l='MpServer', x=208.93, y=58.00, z=1316.30], EntityPlayerSP['coolbuilder65'/6, l='MpServer', x=210.17, y=59.73, z=1314.69], EntityZombie['Husk'/557121, l='MpServer', x=210.70, y=58.00, z=1316.77], EntityZombie['Husk'/563201, l='MpServer', x=208.38, y=58.00, z=1321.45], EntityZombie['Husk'/580354, l='MpServer', x=209.10, y=58.00, z=1321.83], EntityZombie['Husk'/565187, l='MpServer', x=206.82, y=58.00, z=1322.70], EntityZombie['Husk'/559044, l='MpServer', x=204.68, y=58.00, z=1317.05], EntityZombie['Husk'/559045, l='MpServer', x=209.73, y=58.00, z=1317.61], EntityZombie['Husk'/557126, l='MpServer', x=204.94, y=58.00, z=1319.23], EntityZombie['Husk'/559046, l='MpServer', x=204.30, y=58.00, z=1318.54], EntityZombie['Husk'/561176, l='MpServer', x=210.02, y=58.00, z=1316.30], EntityZombie['Husk'/561168, l='MpServer', x=210.70, y=58.00, z=1319.07], EntityZombie['Husk'/561173, l='MpServer', x=204.30, y=58.00, z=1316.40], EntityZombie['Husk'/584488, l='MpServer', x=206.12, y=58.00, z=1322.30], EntityZombie['Husk'/554922, l='MpServer', x=205.03, y=58.00, z=1316.30], EntityZombie['Husk'/557116, l='MpServer', x=208.55, y=58.00, z=1316.99], EntityZombie['Husk'/563196, l='MpServer', x=207.70, y=58.00, z=1320.69], EntityZombie['Husk'/563197, l='MpServer', x=210.01, y=58.00, z=1320.25], EntityItem['item.item.rottenFlesh'/580157, l='MpServer', x=204.28, y=58.00, z=1318.73], EntityZombie['Husk'/563198, l='MpServer', x=210.03, y=58.00, z=1316.93], EntityZombie['Husk'/563199, l='MpServer', x=210.70, y=58.00, z=1320.52], EntityZombie['Husk'/554928, l='MpServer', x=209.19, y=58.00, z=1316.98], EntityZombie['Husk'/582450, l='MpServer', x=206.78, y=58.00, z=1317.57], EntityZombie['Husk'/554931, l='MpServer', x=209.57, y=58.00, z=1320.90], EntityZombie['Husk'/554933, l='MpServer', x=208.75, y=58.00, z=1322.54], EntityZombie['Husk'/554934, l='MpServer', x=210.70, y=58.00, z=1319.80]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 135800928 bytes (129 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2094 Optifine OptiFine_1.10.2_HD_U_C3 24 mods loaded, 24 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2094.jar) 
    UCHIJAAAA   Forge{12.18.1.2094} [Minecraft Forge](forge-1.10.2-12.18.1.2094.jar) 
    UCHIJAAAA   Psi{r1.0-39} [Psi](Psi-r1.0-39.jar) 
    UCHIJAAAA   Quark{r1.0-56} [Quark](Quark-r1.0-56.jar) 
    UCHIJAAAA   AutoRegLib{1.0-2} [AutoRegLib](AutoRegLib-1.0-2.jar) 
    UCHIJAAAA   Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7.jar) 
    UCHIJAAAA   IC2{2.6.81-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.81-ex110.jar) 
    UCHIJAAAA   JEI{3.12.0.286} [Just Enough Items](jei_1.10.2-3.12.0.286.jar) 
    UCHIJAAAA   forestry{5.2.12.260} [Forestry](forestry_1.10.2-5.2.12.260.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   ironchest{1.10.2-7.0.11.797} [Iron Chest](ironchest-1.10.2-7.0.11.797.jar) 
    UCHIJAAAA   jeibees{0.9.0.2} [JEI Bees](jeibees-0.9.0.2-mc1.10.2.jar) 
    UCHIJAAAA   jeresources{0.5.3.59} [Just Enough Resources](JustEnoughResources-1.10.2-0.5.3.59.jar) 
    UCHIJAAAA   mantle{1.10.2-1.0.0.jenkins170} [Mantle](Mantle-1.10.2-1.0.0.jar) 
    UCHIJAAAA   mcmultipart{1.2.1} [MCMultiPart](MCMultiPart-1.2.1-universal.jar) 
    UCHIJAAAA   morebees{1.10.2-1.1.3} [More Bees](morebees-1.10.2-1.1.3.jar) 
    UCHIJAAAA   roots{0.203} [Roots](roots-1.10.2-0.203.0.jar) 
    UCHIJAAAA   soulshardstow{1.10.2-2.6.3-43} [Soul Shards - The Old Ways](SoulShards-TOW-1.10.2-2.6.3-43.jar) 
    UCHIJAAAA   StorageDrawers{1.10.2-3.2.7} [Storage Drawers](StorageDrawers-1.10.2-3.2.7.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.5.2.jenkins352} [Tinkers' Construct](TConstruct-1.10.2-2.5.2.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.9} [Waila Harvestability](WailaHarvestability-mc1.10.2-1.1.9.jar) 
    UCHIJAAAA   Zoology{1.0} [Zoology](zoology-1.10-alpha-1.0.1.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
IC2core (industrialcraft-2-2.6.81-ex110.jar)

```
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
Pulsar/tconstruct loaded Pulses: 
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerHarvestTools (Enabled/Forced)
    - TinkerMeleeWeapons (Enabled/Forced)
    - TinkerRangedWeapons (Enabled/Forced)
    - TinkerModifiers (Enabled/Forced)
    - TinkerSmeltery (Enabled/Not Forced)
    - TinkerGadgets (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerIntegration (Enabled/Forced)
    - TinkerFluids (Enabled/Forced)
    - TinkerMaterials (Enabled/Forced)
    - TinkerModelRegister (Enabled/Forced)
    - WailaIntegration (Enabled/Not Forced)

Launched Version: 1.10.2-forge1.10.2-12.18.1.2094
LWJGL: 2.9.4
OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x AMD A6-5200 APU with Radeon(TM) HD Graphics 
OptiFine Version: OptiFine_1.10.2_HD_U_C3
Render Distance Chunks: 12
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.13416 Compatibility Profile Context 15.300.1025.1001
OpenGlRenderer: AMD Radeon HD 8400 / R3 Series
OpenGlVendor: ATI Technologies Inc.
CpuCount: 4
```

**Comment by McBossKiller** [comment]
I messaged you first because I had the issue messing around with tinker's blocks

**Comment by KnightMiner** [comment]
Does this happen in just Tinkers? Because the place where it crashes already contains a check before it if the stack exists

**Comment by bonii-xx** [comment]
Remove optifine.

**Comment by McBossKiller** [comment]
I removed optifine, I found that the crash no longer happens, but I had a duplication bug, the hopper was both placed above the drying rack and in the drying rack, the more drying racks i used with hoppers above them, the more times this happened, this is while items are flowing through the hoppers i placed.

**Comment by KnightMiner** [comment]
Cannot reproduce in just Tinkers and Mantle. Try removing more mods until you find the cause for the issue

**Comment by KnightMiner** [comment]
Closing for lack of response as the issue could not be reproduced
