### ISSUE TITLE
[1.10.2] Server Startup Crash

### ISSUE THREAD

**Issue by jules552** [SlimeKnights/TinkersConstruct#2430]
Hi,

When I start my server, the server crash :/
If you can fix this problems (I'm on the last version of Tinker)
Crash-Report:
http://pastebin.com/VSBKK6uW

Thanks for your work and have a nice day ;)

**Comment by bonii-xx** [comment]
>    at co.aikar.timings.TimingIdentifier.<init>(TimingIdentifier.java:54)
>    at co.aikar.timings.TimingsManager.getHandler(TimingsManager.java:140)
>    at co.aikar.timings.SpongeTimingsFactory.ofSafe(SpongeTimingsFactory.java:198)
>    at co.aikar.timings.SpongeTimings.getModTimings(SpongeTimings.java:122)

That's not tiC. That looks like... SpongePowered?

**Comment by jules552** [comment]
Maybe but the last version of TiC works and this version not. If you are sure it's sponge answer me and I will report this crash report to them. 

Sorry for the inconvenience.

**Comment by bonii-xx** [comment]
Nothing changed there, and the place where it happens is nothing special either. In fact it's completely unrelated to where the error happens. Redownload TiC, check if it still happens. Try reproducing with only mantle and tic (it might be caused by another mod, quite likely).

**Comment by jules552** [comment]
The mod works with only sponge, it's now sure it's not sponge. I will search the mod that does that. 
Thank you for your helping and Thank you for your work ^^

**Comment by bonii-xx** [comment]
Might be one of the plugins or a combination of mods. BuildingBricks is a coremod I haven't seen in combinations yet.

**Comment by jules552** [comment]
Okay i will check in this direction. Thank you ;)

**Comment by hunter688** [comment]
Outdated SpongeForge...

**Comment by jules552** [comment]
Yes... but when I report the problem I was on the latest update, sorry the problem is fixed now and Thank you everybody for your helping ;)

**Comment by jules552** [comment]
With the new version of SpongeForge the problem is not fixed... it's maybe one's of my plugins or mods does crash my server with the new version of Tinker, The mod works alone with SpongeForge but not with my others mods, that is the problem

**Comment by LemADEC** [comment]
Is it different from the BuildingBricks issue?
