### ISSUE TITLE
[1.7.10] molten tritanium has no texture, and does not merge into molds.

### ISSUE THREAD

**Issue by DasIstVoltone** [SlimeKnights/TinkersConstruct#2432]
![2016-10-02_11 46 54](https://cloud.githubusercontent.com/assets/13628862/19018057/c514322e-8896-11e6-9aa2-2aa6cd0e88b7.png)

**Comment by ArukaAlter** [comment]
1.7.10 is a dead version and is no longer maintened.

**Comment by DasIstVoltone** [comment]
But you can prevent a meltdown of the metal?

**Comment by KnightMiner** [comment]
Tinkers Construct does not add support for tritanium, that is on whichever mod added that fluid

**Comment by bonii-xx** [comment]
TiC has nothing to do with molten titanium.

**Comment by Zsashas** [comment]
Ah, but it isn't Titanium, it's Tritanium. Important distinction.
