### ISSUE TITLE
"Unbreakable" Mattocks are still breakable when treated as hoes in machines

### ISSUE THREAD

**Issue by BillboardEric** [SlimeKnights/TinkersConstruct#2433]
I hate to be back with another Mattock hoeing issue but when using it in an EnderIO or Progressive Automation machine while having the "Unbreakable" modifier, it still takes durability
This was all on the latest version of Tinkers, EnderIO, and Progressive Automation as of this post

Shown here in a EnderIO Farming Station
*sorry for the GIF being sloppy*
![2016-10-02_00-38-29](https://cloud.githubusercontent.com/assets/8685981/19018644/f9241984-8838-11e6-8d4d-3320ea21b066.gif)

**Comment by KnightMiner** [comment]
Versions?

**Comment by bonii-xx** [comment]
Probably fixed in 2.5.3 yeah. Since it's getting XP I assume it's the same bug as #2416

**Comment by BillboardEric** [comment]
No, I said this was on the latest versions, it is the 3rd line of the post
So: TConstruct-1.10.2-2.5.3, EnderIO-1.10.2-3.0.1.116_beta

**Comment by bonii-xx** [comment]
"Lastest" is pretty subjective. Just because you *think* it's the latest, doesn't mean it actually is the newest version. Always include the actual version.

**Comment by bonii-xx** [comment]
I fixed the unbreakable thing. However it wont work with lower levels of reinforced, due to how vanilla does this stuff.
