### ISSUE TITLE
Last shuriken in stack does no damage

### ISSUE THREAD

**Issue by empiricist** [SlimeKnights/TinkersConstruct#2435]
If a shuriken hits a mob and the stack it came from is broken/empty, it just disappears without doing any damage.  Generally this will only happen to the last one in the stack, but it can also happen, for example, when you throw one shuriken straight up in the air and then use up the rest of the stack before it actually hits something.  This does not seem to apply to melee weapons, probably because their durability use and hit happen at the same time.

**Comment by bonii-xx** [comment]
Version?

**Comment by empiricist** [comment]
TiC 1.10.2-2.5.3
Mantle 1.10.2-1.0.0

It looks like the problem may have to do with [entityProjectileBase.onHitEntity](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/entity/EntityProjectileBase.java#L203), which calls getProjectileAttributeModifier() on the item.  Eventually that calls [ToolCore.getAttributeModifiers](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/tools/ToolCore.java#L227), which only adds any damage if the tool stack is not currently broken.

**Comment by bonii-xx** [comment]
I know I fixed that.. maybe it was only in the other branch.
