### ISSUE TITLE
[1.7.10] Why Tinker Construct crash the server and how to solve the problem?

### ISSUE THREAD

**Issue by DasIstVoltone** [SlimeKnights/TinkersConstruct#2437]
[crash-2016-10-02_13.24.57-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/507635/crash-2016-10-02_13.24.57-server.txt)

**Comment by TherminatorX** [comment]
Entity being ticked --
Details:
	Entity Type: rogue_android

Entity's Block location: World: (322,13,180)

Remove the entity at that location via MCEdit or some such, and it should work again. The mob has stuff it really shouldn't. Other than that, 1.7.10 TiC is unsupported, bug fix/content wise.

**Comment by bonii-xx** [comment]
Looks like it can't work out the android, which seems to be some sort of player, although it isn't. Deleting the entity probably is your only chance, yes.
