### ISSUE TITLE
[1.10.2] [BUG] Cool timer reset.

### ISSUE THREAD

**Issue by OscarXcore** [SlimeKnights/TinkersConstruct#2438]
Good day developers!
I have found a bug with the wait cycle on items that have been casted into a mold or basin and are cooling off.
I found this bug while pouring out an Iron block into the casting basin. In the cooling stages, it would get to 35-45% done and would then reset back to 0% and start over, in which would continuously do this loop and not stop. I noticed that the bug is based on server TPS as it was at 40 at the time and I did a server restart, which brought it down to 10, and it fixed the issue. I am able to continue messing with the bug and figure out more but I will have to wait as the server was up for a few days without reboots and raised the TPS as time went on. I have checked the client console, and the server console at the time and nothing was being said about the situation. I was also getting quite a bit of client lag at the time when I was building the smeltery (at the time of high TPS). I would place a Seared Brick and it would lag my client for a second or so. I also noticed that when the smeltery was built, and functioning, I took the tanks out and filled them with lava, put them back into the smeltery, and then the controller wasnt working right, so I broke the controller and put it back down in the same place and the issues started to happen. So it might be TPS, might be the controller causing an issue. I will be trying to reproduce the issue and post updates if something happens.

Forge V. 12.18.1.2094

**Comment by OscarXcore** [comment]
The tank was a Seared Gauge if that helps.

**Comment by OscarXcore** [comment]
Ok. Looks like it is a TPS based issue. I will have to wait for the TPS to rise before I can continue.

**Comment by bonii-xx** [comment]
Sounds more like it's a desync with the client. The server having the real state. The jump back is when it's correct again.

**Comment by bonii-xx** [comment]
By your description it sounds like other things messing with it. 40 TPS is not even possible normally. Try reproducing with only TiC and Mantle. Also TPS getting worse after a restart isn't normal either.

**Comment by OscarXcore** [comment]
The TPS was getting worse over 4 days of no reboots. I also just rebuilt the identical smeltery to the one on the server and did the same thing (putting it together, then breaking the tanks, filling them, putting them back in and seeing if the controller doesnt reset on its own, if it doesnt reset it, then see if there are issues) and the controller validated the structure and worked when the tanks were put back in so there wasnt an issue there.

**Comment by OscarXcore** [comment]
I will try without anything else though. Just TiC and Mantle.

**Comment by OscarXcore** [comment]
Do you know off hand of something I can do to the game to raise the TPS? (For testing purposes of course)

**Comment by OscarXcore** [comment]
With only TiC and Mantle, the issue is not there. I do in fact want to test with a high TPS though. Again, I will wait for the server to reach a high TPS after a few days and see what happens.

**Comment by bookerthegeek** [comment]
@OscarXcore I think you think TPS means something it does not mean. Minecraft runs at 20 TPS and goes down, not up. 

May I ask where you are getting the number 40 from?

**Comment by OscarXcore** [comment]
I should have been saying the Mean Tick Time. When the command `/forge tps` is done on a server/client, I am going by the Mean Tick. Sorry.

**Comment by OscarXcore** [comment]
Turns out it was a one off issue. Thanks for the help anyways!
