### ISSUE TITLE
possible memory leak in newst update for 1.10.2

### ISSUE THREAD

**Issue by redo6565** [SlimeKnights/TinkersConstruct#2440]

**Comment by KnightMiner** [comment]
First off, there is no such thing as the newest update. Give a version. For example, you might think the newest is 2.5.2 without knowing 2.5.3 released. In addition, what version of Mantle and Forge is affected?

Secondly, what makes you think there is a memory leak? Is memory usage increasing drastically over time? Is it beyond what happens without Tinkers? Does it still happen with only Tinkers? Is there a line of code you saw when checking the commits that you think can cause issues?

**Comment by bonii-xx** [comment]
Nondescriptive issue. If yuo have a bug, report it properly.
