### ISSUE TITLE
Crash on initialization

### ISSUE THREAD

**Issue by vrork** [SlimeKnights/TinkersConstruct#2441]
Crash on initialization

http://pastebin.com/BvhF2AxC

**Comment by bonii-xx** [comment]
Check for errors in the log

**Comment by vrork** [comment]
here, take a look

https://gist.github.com/vrork/51bbf9bd2e1380b7c86611f082e7add8

**Comment by bonii-xx** [comment]
Remove optifine and all resource packs, if that doesn't help try again with only TiC and mantle, if it still happens redownload TiC.

**Comment by vrork** [comment]
Yep, optfine did the trick, what is shame due the fact i use a mod that add dynamic lights and it runs much better with optfine
