### ISSUE TITLE
1.10.2 Silk touch hammer sometimes break the ore in the offhand

### ISSUE THREAD

**Issue by LordHellscream** [SlimeKnights/TinkersConstruct#2443]
using 2.5.3 version.

Repro:
Off-hand: 
Hammer (Netherrack plate, slime hammer head, plate, bone tough rod)
Modifier: Haste, Silk touch, Emerald

Main hand:
Excavator ( Netherrack head, slime plate, bone rod, slime binding)
Modifier: Haste, Glow, Emerald

Reason I used hammer in offhand is for glow effect to work (it doesn't work in offhand unless the main hand is a weapon)

The block I am hitting is a 3x3 grid where redstone or lapis is 2x2 and rest is smooth stone. such as below: (R= redstone or lapis, and S = stone)
S R R
S R R
S S S

When I do this. the hammer is used automatically, but one or more of the redstone/lapis gets broken (instead of silk-touched).

**Comment by LordHellscream** [comment]
in addition, it looks like hammer in the offhand doesn't work properly in a couple other cases:
1. when the hammer is in offhand, it won't break any ore from mods (copper, tin, lead etc from IE and mekanism) unless the ore itself is the target of the hammer
2. when the custom ore is the target, the hammer break them extremely slowly.

**Comment by bonii-xx** [comment]
Can confirm that the center block, which the player aims at, is not silktouched. The others sound a lot like your hammer is simply missing the corresponding harvest level.

**Comment by LordHellscream** [comment]
The comment about my hammer not having the harvest level is not true, since
1. its sharpened by obsidian kit.
2. the hammer works perfectly fine when wielded in main hand.

**Comment by bonii-xx** [comment]
Does it work on vanilla blocks? At least redstone behaves exactly the same, no matter which hand the hammer is in.

**Comment by LordHellscream** [comment]
It works for vanilla blocks, and only seems to work for vanilla blocks, any mod ore (tin, copper lead etc from IE, and/or mekanism) would not work properly (hammer in the offhand).

**Comment by bonii-xx** [comment]
Sounds more like an issue with the mod ores. IE too? I can check that in dev.

**Comment by bonii-xx** [comment]
At least for IE ores they behave exactly the same, no matter if I target stone or the ore. Might have been a side effect of the original issue and fixed with the fix.

**Comment by LordHellscream** [comment]
is the fix available? i will try and let you know.

**Comment by LordHellscream** [comment]
is the fix available? i will try and let you know.
