### ISSUE TITLE
[1.10.2] Readds?

### ISSUE THREAD

**Issue by BLSK** [SlimeKnights/TinkersConstruct#2447]
Hello,

Since mods have been finally going into full swing of updating I have been updating things myself and I found a few things I was a little surprised about.

**1.7.10**
![2016-10-06_06 49 53](https://cloud.githubusercontent.com/assets/8443396/19149748/7e233704-8b91-11e6-90bb-ee33f42c312a.png)
![2016-10-06_06 47 22](https://cloud.githubusercontent.com/assets/8443396/19149755/819039f0-8b91-11e6-89dd-06d11f3df68d.png)

**1.10.2**
![2016-10-06_06 35 31](https://cloud.githubusercontent.com/assets/8443396/19149793/a0e7000e-8b91-11e6-94bf-96976c425e95.png)
- In 1.7 we had Locked Creatives and I focused those highly(and sorta painful recipes) for the mobs I was working with that could have HP of Insane amounts as high as 2m by the end but it was still only just a start.  The creative modifier Target locks were brilliant and maybe I can figure out there nbt if they are still available.
- Same thing went for another thing:  Infinite Potential Modifiers.  Seeing some of the weapons could be fearful.  At the least I was hoping perhaps Sharpening and Efficiency of the Tools and weapons could be given a config setting?  Say Infinite to a number specified?  Default of 5 like it is now?

I hope it a thing you're willing to readd?

**Comment by bonii-xx** [comment]
Locked creative modifiers are currently not implemented. While they would be doable, I don't think they're used much, so they have a pretty low priority. Don't expect them anytime soon.

Infinite potential modifiers wont come back, we want diversity. Use different modifiers.

**Comment by BLSK** [comment]
So if i understand you right:
Creative modifier Locks may be a thing sometime.

2nd:  You speak of diversity?  Not sure how adding it as an option isn't diversity?
You mean other modifiers.  I use them all actually.  My pick was just a quick made.
But I wonder... in suggesting the mod is more diverse does it not actually limit creativity?

**Comment by BLSK** [comment]
Having given the Level mod a few minutes I see its not like Iguana(and perhaps that's been updated too... will have to look)

In case you say 'no' definitively.  Might you give me a chance to persuade you.  May not amount to a change but I feel I would like to justify the request.  If you're willing to.  Maybe you would still say no.  A few of my friends will be on tomorrow and I'll see what we can do.

**Comment by Garonne** [comment]
Sort of similar question so I'm rather add it here than start a new 'issue' with the same topic...

I see there are a bunch of tools still missing in 1.10.2 which were fun to use in 1.7.10, namely throwing knifes and javelins (at least those are the two I mainly remember right now). Are those going to come back for 1.10.2 as well or have they been dropped for some reason?

Just curious. I liked the knives a lot, Though shuriken are fun as well... so don't hurry.

**Comment by LovelyFlare** [comment]
@Garonne Read [FAQ](https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ)

**Comment by Garonne** [comment]
Sorry, didn't know the "Bow" part in the FAQ was valid for other tools as well... At least I suppose that's what you refer to.
