### ISSUE TITLE
1.10.2 Unbreakable doesn't seem to work (scythe, suriken tested)

### ISSUE THREAD

**Issue by LordHellscream** [SlimeKnights/TinkersConstruct#2449]
V 2.5.3

Made a unbreakable paper scythe (paper head, slime binding, bone rod) to deal with the weed and grass, but it doesn't do anything at all, durability decreases every single hit 

Same thing for a unbreakable paper suriken, rapid fire decreases durability(ammo) rapidly.

**Comment by bonii-xx** [comment]
It's a bit more complicated than that, but basically it doesn't show you that it works, and when the tool breaks it really breaks. Should already be fixed in dev.
