### ISSUE TITLE
"Materials and You" book does not properly wrap text (with OptiFine installed)

### ISSUE THREAD

**Issue by NiSiSuinegEht** [SlimeKnights/TinkersConstruct#2451]
When looking through the current state of the book, there are many instances, especially in the sections dealing with multiblock structures, where the word wrapping does not match the actual page size, and either goes off the page, or underneath the image depicted on the opposing page.  This can hide critical information about how to build a structure, and currently the only way to read the directions properly is by going into the mod .jar and opening the relevant asset file.

This is still present in 1.10.2-2.5.3

**Comment by LovelyFlare** [comment]
You are using the mod alone with Mantle?

**Comment by bonii-xx** [comment]
Screenshot?

**Comment by NiSiSuinegEht** [comment]
Sorry about that, I should have checked for mod interference first.  It seems this is being caused by some interaction with OptiFine.

![2016-10-07_21 19 01](https://cloud.githubusercontent.com/assets/22671678/19209239/044f3cc2-8cd4-11e6-9abe-e6d2aa287bc4.png)

**Comment by mDiyo** [comment]
OptiFine effectively makes the game a different platform to mod on. It's similar to bukkit in that respect.

**Comment by LovelyFlare** [comment]
Nothing can be done if it's an OptiFine issue.

**Comment by PapiDimmi** [comment]
I have the same issue. I wish the developer, @SlimeKnights, would bother to fix this…

http://i.imgur.com/nCT7sEU.png

**Comment by ArukaAlter** [comment]
Simple fix or not, Optifine is not supported.

**Comment by PapiDimmi** [comment]
Then the developer should support it. Almost everyone uses OptiFine; I can’t play the game without it, and I am not alone. Why did the dev add support for lots of mods but ignored the biggest mod out there?

**Comment by garath77** [comment]
The developers don't support Optifine because of how much Optifine changes the rendering process. If you look into most other mods that have a lot of visuals, I think you'll find that most of them do not support Optifine

**Comment by ArukaAlter** [comment]
It's rare for a developer to support Optifine or any server software that isn't pure Forge.

**Comment by KnightMiner** [comment]
Optifine changes things with closed source code and little documentation. Adding support is more effort than it is worth when it breaks the simplest of rendering (including calls to vanilla rendering code at times)
