### ISSUE TITLE
What can transport liquid smelt stuff back to smeltery drain?

### ISSUE THREAD

**Issue by Lion4K** [SlimeKnights/TinkersConstruct#2452]
Like, faucets can be used to drain a tank back to the smelter, but it requires the faucet be over the drain, is there any mod that add a pipe or something (or if there is some known mod) that can be attached to the drain and it will accept its liquid vertically?

The image bellow can speak better then me.

[http://image.prntscr.com/image/4d0a582f054f43269cc44e931cd39143.png](url)

**Comment by KnightMiner** [comment]
Literally any mod that adds liquid pipes will work for this, for example Immersive Engineering.

If you want a solution from Tinkers Construct, you can either right click with buckets or wait for casting channels to be re-implemented (which is not likely to be soon, they are quite complex)

**Comment by Lion4K** [comment]
Yes because i'ves tested a mod pressure pipes or something that had integration with extrautils2's drum and it didn't worked.

now, happens that extrautils2 does have some piping too, and that works. i've figured out hours later i posted the issue.

Thanks!!
