### ISSUE TITLE
Slime Boots cause incompatibility with Squake Mod

### ISSUE THREAD

**Issue by Compegen** [SlimeKnights/TinkersConstruct#2453]
The new slime boots cause the Squake movement system to freak out.

[What Squake should look like.](https://gfycat.com/AliveMadEft)

[What it looks like with the boots equipped.](https://gfycat.com/ElatedPrestigiousKittiwake)

---

I'm also reporting this problem to the maker of Squake, but I don't really know whose mod's at fault...

**Comment by bonii-xx** [comment]
Neither mod is at "fault" per se. That simply always happens when two things modify acceleration.
