### ISSUE TITLE
Crash on startup (MalformedJsonException)

### ISSUE THREAD

**Issue by BrisingrAerowing** [SlimeKnights/TinkersConstruct#2454]
[Crash Report](https://gist.github.com/BrisingrAerowing/b99a3bc0ca51cb88c5e78a827bf26654)

I got this after solving my issues with BuildingBricks crashing by simply logging the exception and continuing.

Shouldn't the value 'rock' be 'stone'?

**Comment by bonii-xx** [comment]
TiC is trying to load one of building bricks files, it seems. That's because of a fallback where it tries to load the files from the minecraft domain, if they're not found in the mods or tics domain. It shouldn't crash because of that, hm

**Comment by bonii-xx** [comment]
To clarify, that it crashes on an invalid file is a bug. That building bricks is crashing is their fault. I can throw you a version with the fix if you need it for your SSP world.

**Comment by BrisingrAerowing** [comment]
I use TConstruct quite a bit in SSP (although I keep storage blocks out of chunks where smelteries are, as the disappearing items bug seems to happen quite a bit with most mods storage systems when they are in the same chunks), so a fixed version would be nice.

**Comment by BrisingrAerowing** [comment]
I just went ahead and built the latest code from the repo, and all seems to be working.

**Comment by bonii-xx** [comment]
K, great, then that's done ;o
