### ISSUE TITLE
Update 2.5.4 makes TC a non mod file. (1.10.2)

### ISSUE THREAD

**Issue by jensz12** [SlimeKnights/TinkersConstruct#2458]
When starting my test server, i got this error:

[13:55:37] [Server thread/INFO] [FML/]: FML has found a non-mod file TConstruct-1.10.2-2.5.4.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.

Followed by these 500 lines of missing block information
https://static.jensz12.com/tcmissingid.txt

**Comment by bonii-xx** [comment]
https://twitter.com/bonusboni/status/784729074753298433
Delete it immediately. It's not from us, an account got hacked.

**Comment by jensz12** [comment]
Ohhh thanks!

**Comment by bonii-xx** [comment]
From the looks of it it doesn't execute anything when used as a mod file.. can't be sure though. As long as you didn't try to execute the jar itself you're probably fine.

**Comment by jensz12** [comment]
I only tried to start it on a local server. So no harm hopefully :-)
