### ISSUE TITLE
Game Crash with Tinkers 12.55/2.53

### ISSUE THREAD

**Issue by Medusalem** [SlimeKnights/TinkersConstruct#2459]
Our Modpack is crashing when Updating from 2.5.2 to newer versions!

Removing Optifine is not changing something!

The Crash log is here!
With optifine
http://pastebin.com/spjkPZnV
without optifine
http://pastebin.com/PTznDBhf

If i can give you any more information i will give you what i can

**Comment by ArukaAlter** [comment]
https://github.com/hea3ven/BuildingBricks/issues/95

**Comment by Medusalem** [comment]
just saw it is maybe linked to this https://github.com/SlimeKnights/TinkersConstruct/issues/2436

**Comment by bonii-xx** [comment]
Yup. As you can see the building bricks guy is working on a fix this weekend. After that 2.5.5 will work.
