### ISSUE TITLE
Duplicating items on throwing them

### ISSUE THREAD

**Issue by Kostronor** [SlimeKnights/TinkersConstruct#2460]
We are using Minecraft 1.10.2
with forge 12.18.1.2092 
and on the server 1.10.2-2092-5.0.0-BETA-1753
And Tinkers Construct TConstruct-1.10.2-2.5.3.jar (will now update to .5 to see if it is still a problem)

When a player on our server takes a tool out of his inventory (gamemode 0) and throws it on the groud, a copy appears and you can pick up both items.

It seems after dropping the item it reappears in your "cursor-hand" so you can click multiple times to clone it as often as you like.

Screenshots:

Starting with this:
![2016-10-08_19 44 28](https://cloud.githubusercontent.com/assets/644950/19214910/f39b00e8-8d8f-11e6-801d-f628c64b1801.png)

I pick up the InfiMiner and pull him out of the inventory:
![2016-10-08_19 44 31](https://cloud.githubusercontent.com/assets/644950/19214911/03f3227c-8d90-11e6-84ed-80244e04e747.png)

Then I leftclick to drop it but it keeps in my inventory:
![2016-10-08_19 44 36](https://cloud.githubusercontent.com/assets/644950/19214914/0bb9efa4-8d90-11e6-8672-b2e78b693085.png)

After that I press escape so my hand gets dropped by minecraft, duplicated:
![2016-10-08_19 44 41](https://cloud.githubusercontent.com/assets/644950/19214915/207a84d0-8d90-11e6-9438-64d9bf004540.png)

If you click multiple times, you drop as many as you want:
![2016-10-08_19 45 00](https://cloud.githubusercontent.com/assets/644950/19214919/39c9fd30-8d90-11e6-82ab-99fe3c9bb97d.png)

If you need any additional info, please tell.

**Comment by bonii-xx** [comment]
Update Sponge

**Comment by Kostronor** [comment]
Thanks that fixed it!
