### ISSUE TITLE
[1.10.2] Server crash with latest Forge 2097

### ISSUE THREAD

**Issue by kwpugh** [SlimeKnights/TinkersConstruct#2461]
Forge: 2097
Mods: Mantle-1.10.2-1.0.0.jar & TConstruct-1.10.2-2.5.3.jar

Crash report: https://gist.githubusercontent.com/kwpugh/6de94a4e2b8fc39cca6f007ade642cab/raw/bab100d3308ee9228f8df55cbc23aee133f38124/Tinkers

**Comment by creeperraper1337** [comment]
ya same for me, but i downgraded forge to 2090 and it seems to work with that.

**Comment by KnightMiner** [comment]
Seems to be the same issue as #2464, except the report you linked actually came from Natura. Something in Forge changed which broke Mantle's method for proxy loading. Use an older version of Forge for now

**Comment by trabpukcip** [comment]
It is mentioned in the changelog for Forge 2096:

Build 1.10.2-12.18.1.2096:
	LexManos: Small Cleanup in example build.gradle.
	LexManos:
		Filter out proxy injectors for incorrect mods. Prevents mod classes
		being initialized early when multiple mods are in the same source.
	LexManos:
		Introduce IContextSetter for events. This will set the active mod
		container for events using the normal EventBus. Fixes improper warnings
		from initializing mods using the new Registry events. Modders, you
		should not use this as it has many performance implementations and if
		abused will slow down the event bus A LOT. ActiveModContainer is not
		thread safe.

http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.2.2097/forge-1.10.2-12.18.2.2097-changelog.txt

2097 is now recommended so this might come up a fair bit until Mantle is fixed.

**Comment by bonii-xx** [comment]
Try 2098, that seems to contain a fix
