### ISSUE TITLE
[1.10.2] tconstruct:cast_custom and all variants are unresponsive in smeltery casting.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [SlimeKnights/TinkersConstruct#2462]
TConstruct Version: 2.5.3
Mantle Version: 1.0.0
This only happens with that specific item, and not with the tconstruct:cast or tconstruct:clay_cast NBT based cast variants, but any and all casting attempts using the cast_custom (ingot, nugget, gem, plate, gear) are all as unresponsive as can be.  
It might be worth noting in the instance the stencil table isn't working, which seemed to be a longstanding issue that is resolved in a myriad of ways (usually another mod's end)
I might add that the cast_custom doesn't use NBT, but the cast and clay_cast items do, as does tconstruct:pattern.  (Which, by adding recipes for them, all work as intended in the part builder).

**Comment by Shadows-of-Fire** [comment]
Might I also add that you just cannot put fluids in a casting table containing a cast_custom item at all.  I'm going to try re-adding those recipes with modtweaker if it still support tic and see if that gives me a response.

**Comment by Shadows-of-Fire** [comment]
Okay, re-adding your recipes using cast_custom in modtweaker makes them work again, but the recipes also show up in JEI like they are registering properly.

**Comment by KnightMiner** [comment]
They work fine both with Tinkers by itself and in the mod pack I am playing, so it woulda like some mod is breaking things. Try updating to 2.5.5 first, and if that does not resolve anything try removing mods to find the conflict.

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions. If it doesn't happen, try to find the mod that causes it.

**Comment by Shadows-of-Fire** [comment]
It seems to have been modular machines.  Didn't that mod also conflict with the Stencil Table (it also happens to be working again)
