### ISSUE TITLE
Smeltery Contents Lost when Rotated with a Wrench

### ISSUE THREAD

**Issue by Flexico** [SlimeKnights/TinkersConstruct#2463]
I had an EnderIO Yeta Wrench in my hand when I tried to access my Tinkers Construct smeltery, and the wrench rotated the Smeltery Controller block. When I rotated it back and opened it up, all my molten metals had been cleared.

I'm not totally sure which mod I should report this to, so I'm doing both to be safe.

MC 1.10.2
Forge 12.18.1.2094
TC 2.5.3
EIO 3.0.1.117

**Comment by KnightMiner** [comment]
The tile entity is deleted if the blockstate is changed by default. There is no reason it should change, plus if it did the structure would become invalid/cause a crash, so no reason to have it.

I would say this is Ender IO's fault as the block shouldn't rotate in the first place as it is part of a structre

**Comment by tterrag1098** [comment]
EIO has no way of knowing what a "structure" is. We just call `rotateBlock()`, it's on TiC to NOT rotate if it can't handle it.

**Comment by KnightMiner** [comment]
Hmm, apparently Forge automatically adds rotation logic for generic facing properties even though we never implemented `withRotation()`, I assumed that was the only method related to rotation thus us not implementing it means no rotation.

**Comment by MrNinja93** [comment]
Also happens with forestry wrench (on shift click) and Ic2 wrenches so not an EIO specific problem.

**Comment by Flexico** [comment]
Wat, has Forestry updated to 1.10? Or does this happen in 1.7 as well?

**Comment by bonii-xx** [comment]
Oh yeah, I remember the rotate function. The default implementation must be new, heh.

@Flexico Forestry has been on 1.10 forever.

**Comment by bonii-xx** [comment]
https://gfycat.com/WanBitterAlaskanhusky weeeeeee

**Comment by Flexico** [comment]
I'm still accustomed to Forestry relying on Buildcraft, which I know hasn't updated. D'oh!
