### ISSUE TITLE
Crash on client startup

### ISSUE THREAD

**Issue by Flibio** [SlimeKnights/TinkersConstruct#2464]
Hello, I am trying to use this mod, but it crashes on startup. It looks like Tinkers is throwing a NPE. Any ideas as to how I can resolve this?

[**Log**](http://hastebin.com/raw/kuperinuko)

**Comment by KnightMiner** [comment]
For some reason, the proxy is no longer being innitialized for that crash. No idea why it would no longer be working unless another mod is breaking things or something changed internally in Forge

**Comment by Flibio** [comment]
If I was to guess something with Forge changed as older Forge versions seem to work good.

**Comment by KnightMiner** [comment]
Yeah, apparently Forge changed the conditions for the sided proxy in build 2096. Using something before that should work fine until a fix can be worked out in Mantles/Forges side

**Comment by CatMe0w** [comment]
same problem

**Comment by bonii-xx** [comment]
Update to Forge 2098
