### ISSUE TITLE
NPE with Optifine installed?

### ISSUE THREAD

**Issue by Tkdmaster** [SlimeKnights/TinkersConstruct#2466]
So, after doing an update of a few of the mods I was using, I found that the 1.10.2-2.5.2/2.5.3/2.5.5 updates to tinkers have broke compatibility with Optifine on launch.

Here's the error itself...
http://pastebin.com/jaDiFpq9

I know several developers don't care about Optifine compatibility, but I'd really appreciate it if some sort of fix can be done for this, as with my bad eyesight I pretty much rely on a few of its features to play.

**Comment by bonii-xx** [comment]
We can't fix the shit optifine does.
