### ISSUE TITLE
Dupe - unlimeted tools and weapons

### ISSUE THREAD

**Issue by Copy27** [SlimeKnights/TinkersConstruct#2467]
hi,

i have the problem that i can dupe weapons and tools. I open the inventory and take the tool to the hand and shift left click and it will drop but remain in my hand.

following plugins were present

spongeforge-1.10.2-2092-5.0.0-BETA-1773
TConstruct-1.10.2-2.5.3
forge-1.10.2-12.18.1.2094
Mantle-1.10.2-1.0.0
jei_1.10.2-3.10.0.261

**Comment by bonii-xx** [comment]
Update sponge.

**Comment by Copy27** [comment]
wow i am that stupid i gues.......

thank you very much this resolved the whole thing
