### ISSUE TITLE
NullPointerException - Model Bake (1.10.2) (Optifine incompatibility)

### ISSUE THREAD

**Issue by JonathanxD** [SlimeKnights/TinkersConstruct#2468]
Crash Report:
http://pastebin.com/Ssvjusef

TinkersConstruct: 2.5.5-1.10.2

Works fine without Optifine.

**Comment by JonathanxD** [comment]
I have looked at the code and it's already fixed in current branch.

https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/client/model/MaterialModel.java#L75

**Comment by LovelyFlare** [comment]
Regardless, it's an OptiFine issue and it's not a Tinkers' Construct problem that they aren't compatible.

**Comment by JonathanxD** [comment]
@LovelyFlare not, it's an TConstruct issue: sp614x/optifine#286
