### ISSUE TITLE
Fluid temperatures

### ISSUE THREAD

**Issue by LemADEC** [SlimeKnights/TinkersConstruct#2469]
Currently, TC registers milk at 320, while the real thing is more like 311 K.
Similarly:
- iron is registered at 769, instead of 1811 K.
- gold is registered at 532, instead of 1337 K.
- cobalt is registered at 950, instead of 1768 K.
- etc.

Is there any reason we aren't using realistic temperatures here?

**Comment by LovelyFlare** [comment]
This is an issue?

**Comment by LovelyFlare** [comment]
Because this is Tinkers' Construct.  A mod for Minecraft.

**Comment by bonii-xx** [comment]
For gameplay reasons and internal mechanics. Also good luck melting iron with a melting point of 1811 when lava only has a temperature of 1300.

**Comment by ArukaAlter** [comment]
Mariculture uses temperatures next to real values, but it takes far more effort to melt iron than gold in their Crucible Furnace.

**Comment by LemADEC** [comment]
Yes, vanilla is a bit messed up on that logic.
