### ISSUE TITLE
Tinkers/optifine interaction?

### ISSUE THREAD

**Issue by popps73x** [SlimeKnights/TinkersConstruct#2471]
https://github.com/sp614x/optifine/issues/286

**Comment by KnightMiner** [comment]
Optifine randomly breaks anything we do with rendering due to how much it changes vanilla rendering. If the crash only happens with Optifine it is not supported.

**Comment by popps73x** [comment]
ok.  thanks.  but i cant play without it.  stupid potato of a pc.  :)  lol
