### ISSUE TITLE
[MC 1.10.2][TiCon 2.5.3][IE 0.10-44][Forge 2094] Updating Screen Events crash

### ISSUE THREAD

**Issue by Alaberti** [SlimeKnights/TinkersConstruct#2472]
http://pastebin.com/mbjru9hj

Had a player attempt to make IE wire cutters in a TiCon crafting station. Reported on their tracker: https://github.com/BluSunrize/ImmersiveEngineering/issues/1562

**Comment by bonii-xx** [comment]
Blu is aware, one of their recipes has a derp.
