### ISSUE TITLE
Tinkers crash on loading

### ISSUE THREAD

**Issue by popps73x** [SlimeKnights/TinkersConstruct#2473]
https://github.com/sp614x/optifine/issues/286#issuecomment-252659104

As he commented the crash is tinkers not optifine.  please take a look thanks.

**Comment by KnightMiner** [comment]
My point from before stands of test it without Optifine, the location of the stack trace is not the only clue to fault, and from the looks of things Optifine is causing one of the material textures to return a different location for the texture than it did when we generated the material textures

In this case though, d6ffb6a added a null check on the same line as the crash so this shouldn't happen in later builds at least, but based on what Optifine changes is what the resulting tool will look like (but at least no crash)

**Comment by popps73x** [comment]
i know some things like this can be very frustrating.  thank you for all you guys do to make minecraft and the modding of it better.  looking forward to 2.5.6?  i am guessing?  thanks again.
