### ISSUE TITLE
Tinkers construct is not generating items in the world

### ISSUE THREAD

**Issue by JeffMCxS** [SlimeKnights/TinkersConstruct#2474]
I installed the mod Tinkers Contruct, but it is not working properly. no ore is being generated in my world, I'm sure it was installed because when I go in the world I get the tutorial book, and when I put in a creative way, I can see the list of all menu items, and can use them.
I tried already reinstall and install another version of the mod, but nothing solved the problem, I do not know what to do. :(

Version 1.10 and 1.9

Edit: also I wanted to know if the tinkers is heavy because I am having a bit of lag.

Thank you.

**Comment by ArukaAlter** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/master/CONTRIBUTING.md

**Comment by bonii-xx** [comment]
TiC doesn't generate standard ores anymore.

**Comment by JeffMCxS** [comment]
but is not being generated any ore, none block related to mod is being spawned in my world

**Comment by ArukaAlter** [comment]
The only thing that the mod generates is slime islands and cobalt/ardite, there's no more overworld ores or metal bushes.
If you are seeing the items, you can craft the rest.

**Comment by bonii-xx** [comment]
There is a config option that adds all toolparts and materials and stuff, even when it's not obtainable. Check if it's enabled.
