### ISSUE TITLE
Slime island StructureBoundingBox is saved incorrectly 

### ISSUE THREAD

**Issue by Noodep** [SlimeKnights/TinkersConstruct#2475]
As of commit [2f72a91c1c68f08e036e907a503fa64d32a2fd81](https://github.com/SlimeKnights/TinkersConstruct/commit/2f72a91c1c68f08e036e907a503fa64d32a2fd81), the structure bounding box of the slime island uses yRange as its depth instead of zRange.

See code below :
`data.islands.add(new StructureBoundingBox(start.getX(), start.getY(), start.getZ(),
                                              start.getX() + xRange, start.getY() + yRange, start.getZ() + yRange));
`

Expected maxZ value would be `start.getZ() + zRange`.

Let me know if you have questions.
Cheers.

**Comment by bonii-xx** [comment]
You are correct that the wrong range is there, but where do you see any correlation to the commit mentioned..?

**Comment by Noodep** [comment]
The commit number is a reference to a version where the bug is still present. This is just in case, so  we can discuss about the same code if needed. Sorry if that wasn't clear.
