### ISSUE TITLE
Disable Vanilla Tools Effects MC 1.10.2

### ISSUE THREAD

**Issue by Luke159** [SlimeKnights/TinkersConstruct#2476]
Is it possible to have the option in the config back so we can disable the vanilla tools please, not sure why it was removed.

**Comment by KnightMiner** [comment]
That was Iguana Tinker Tweaks which had the option

**Comment by bonii-xx** [comment]
All the option did was to set the durability of vanilla tools to 1. Considering that there usually are at least two times as many other tools from other mods in a modpack, not really a useful thing to do. It's simply not TiCs job.
