### ISSUE TITLE
Bug: disabling modifiers in the config doesn't work

### ISSUE THREAD

**Issue by darklordwonton** [SlimeKnights/TinkersConstruct#2479]
Turning off the the TinkersModifiers module in the config doesn't seem to actually disable any of the modifiers or restrict a players ability to add modifiers.

**Comment by KnightMiner** [comment]
That module is forced, technically it shouldn't appear in the config at all

**Comment by darklordwonton** [comment]
I'm using the latest version. It didn't always show the tinkers modifiers module but when I disabled tinker's tools it showed up (btw why is the module forced?).

**Comment by KnightMiner** [comment]
Module is forced because it is required by the tools module, it is just better organization. It also really doesn't do anything if tools is disabled anyways

**Comment by darklordwonton** [comment]
tinkers construct: 2.5.5
mantle: 1.0.0
both for 1.10.2

**Comment by bonii-xx** [comment]
Modifier module wont able to be disabled.
