### ISSUE TITLE
[1.10.2] Game crash on start up

### ISSUE THREAD

**Issue by Xamxas** [SlimeKnights/TinkersConstruct#2480]
Minecraft: 1.10.2
Forge: 12.18.2.2099
Tink const: 2.5.5

Sorry if this is a duplicate. Couldnt find the other threads.

Crashes when game tries to load. Crash report says: java.lang.RuntimeException: Could not load material from tconstruct:materials/vine.json

http://paste.ee/p/n5ZUt

if that one is wierd then this one:
[crash-2016-10-11_23.40.45-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/523527/crash-2016-10-11_23.40.45-client.txt)

**Comment by LovelyFlare** [comment]
Have you tried updating Building Bricks?

**Comment by KnightMiner** [comment]
Yeah, its Building Bricks fault, and was reported here before as #2436

**Comment by LovelyFlare** [comment]
Just so you know, you already reported the same exact problem here...  #2465

**Comment by Xamxas** [comment]
my bad, I am new here and did not know the way the system works I did not see that closed threads get taken out to another location. Sorry about that

**Comment by Xamxas** [comment]
Thought that my thread was deleted
