### ISSUE TITLE
Optifine Causing crash again (TC 2.5.5, Mantle 1.0)

### ISSUE THREAD

**Issue by Drakonas** [SlimeKnights/TinkersConstruct#2483]
Duplicate of https://github.com/SlimeKnights/TinkersConstruct/issues/2036
But I'm not using Better Foliage.

EnderIO seems to be referenced, but removing it does not prevent the crash.

[Here's my log](http://pastebin.com/HAZT50kx)

EDIT: Well apparently I didn't double check after updating Tinker's. Now Mantle is causing the crash instead of the [previous log](http://pastebin.com/753993Sx)

Mainly wondering who I should be contacting for a fix. I will make an Optifine ticket if necessary.

On a side note, why does Optifine crash things so much? I mean, @sp614x updates it often. I can't believe hefty code can do this much damage, but I guess it IS Java we're talking about. lol

**Comment by LovelyFlare** [comment]
OptiFine crashes clients a lot in modpacks due to the way it alters rendering.  Because of this, mod developers often ignore or even refuse bug reports with OptiFine in them.  This happens to be the case here :P

**Comment by Drakonas** [comment]
![Curse you, Red Baron](https://c2.staticflickr.com/8/7321/9917466223_b0ffba6727_z.jpg)

**Comment by KnightMiner** [comment]
Yeah, Optifine changes a lot of rendering code, but is closed source so we do not know what they changed. Sending the report Optifines way is your best bet, or removing Optifine entirely (as plenty of other mods have incompatibilities as well)

**Comment by Drakonas** [comment]
I forgot Optifine was closed source.. could've saved you the trouble. lol. I'll make sure to forward all issues to the Optifine github from now on for Optifine issues. No point posting elsewhere.

**Comment by sp614x** [comment]
Updated preview OptiFine C4 with a bugfix.
The delayed sprite initialization was broken.
