### ISSUE TITLE
Crashing with Optifine but No IE Installed

### ISSUE THREAD

**Issue by Stratzh** [SlimeKnights/TinkersConstruct#2484]
I've spent the last half hour looking around TConstruct configs and several other mod configs trying to find the solution to this issue. I can't seem to find one, the closest I've found with a Google search is that it's an issue between TC and IE w/ Optifine installed. The pack I'm trying this on is the HermitPack which doesn't have IE in it.

Here's my crash log.

http://pastebin.com/tkG87BBd

**EDIT:**
I'm not 100% sure it's to do with Tinkers, but the modpack maker is blaming it on Tinkers Conflicting, but my continued research is showing a conflict with other mods.

I'd just like to apologise if this has nothing to do with this mod.

**Comment by bonii-xx** [comment]
>    at mod.flatcoloredblocks.model.BakedVarientBlock.<init>(BakedVarientBlock.java:133)

Flat colored blocks. Tell your modpack maker that he has no clue. :P
