### ISSUE TITLE
Why is my report about crashing gone?

### ISSUE THREAD

**Issue by Villfuk02** [SlimeKnights/TinkersConstruct#2486]
like 3 hours ago, i posted issue and now the post is gone!!!

Like WTF?

**Comment by GirafiStudios** [comment]
It is not gone, it is just closed?.. https://github.com/SlimeKnights/TinkersConstruct/issues/2485

**Comment by bonii-xx** [comment]
Because you obviously didn't check your notifications! But you know what they say, practice makes perfect. Attempt number 2

**Comment by Villfuk02** [comment]
Where do i find notifications?

**Comment by KnightMiner** [comment]
The bell icon, top right corner. Should have a blue circle for new notifications.

**Comment by bonii-xx** [comment]
Don't the default settings even send you emails? But maybe that's on a daily basis.
