### ISSUE TITLE
issue baking parts

### ISSUE THREAD

**Issue by caligator** [SlimeKnights/TinkersConstruct#2487]
cant seem to figure out whats causing this-- tinkers will run on its own, but it wont run in  the current environment I set up. It was working fine up until the recent update :T 

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-0.8.5.jar)
  llibrary (llibrary-1.7.0-1.10.2.jar)
  IC2core (industrialcraft-2-2.6.69-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  IvToolkit (IvToolkit-1.2.8.5.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.51.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 10/12/16 10:04 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bake(MaterialModel.java:51)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bake(MaterialModel.java:51)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1017833640 bytes (970 MB) / 2941779968 bytes (2805 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2093 Optifine OptiFine_1.10.2_HD_U_C3 81 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2093.jar) 
	UCHIJA	Forge{12.18.1.2093} [Minecraft Forge] (forge-1.10.2-12.18.1.2093.jar) 
	UCHIJA	AdvancedRocketry{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJA	ivtoolkit{1.2.8.5} [IvToolkit] (minecraft.jar) 
	UCHIJA	OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	cei{1.3} [Chunk Edge Indicator] (1.10-chunkedgeindicator-1.3.jar) 
	UCHIJA	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCHIJA	tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct] (TConstruct-1.10.2-2.5.5.jar) 
	UCHIJA	immersiveengineering{0.10-44} [Immersive Engineering] (ImmersiveEngineering-0.10-44.jar) 
	UCHIJA	JEI{3.12.7.315} [Just Enough Items] (jei_1.10.2-3.12.7.315.jar) 
	UCHIJA	abyssalcraft{1.9.3-pre-1} [AbyssalCraft] (AbyssalCraft-1.10.2-1.9.3-pre-1.jar) 
	UCHIJA	libVulpes{0.1.3.20161004220423} [libVulpes] (LibVulpes-1.10.2-0.1.3-universal.jar) 
	UCHIJA	advancedRocketry{1.10.2-0.8.5} [Advanced Rocketry] (AdvancedRocketry-1.10.2-0.8.5.jar) 
	UCHIJA	aquaculture{1.4.0} [Aquaculture] (Aquaculture-1.10.2-1.4.0.28.jar) 
	UCHIJA	ArmourReborn{r1.0-18} [ArmourReborn] (ArmourReborn-r1.0-18.jar) 
	UCHIJA	Psi{r1.0-41} [Psi] (Psi-r1.0-41.jar) 
	UCHIJA	Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	Baubles{1.3.BETA9} [Baubles] (Baubles-1.10.2-1.3.BETA9.jar) 
	UCHIJA	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2087} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2087-universal.jar) 
	UCHIJA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJA	BloodMagic{1.9.4-2.1.0-65} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-65.jar) 
	UCHIJA	infinitylib{1.10.2-@MAJOR@.@MINOR@.@REVIS@} [InfinityLib] (infinityLib-0.1.jar) 
	UCHIJA	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.1.jar) 
	UCHIJA	Botania{r1.9-330} [Botania] (Botania r1.9-330.jar) 
	UCHIJA	Bullseye{1.0.3} [Bullseye] (Bullseye-1.9.4-1.0.3.jar) 
	UCHIJA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJA	chisel{MC1.9.4-0.0.6.51} [Chisel] (Chisel-MC1.9.4-0.0.6.51.jar) 
	UCHIJA	chiselsandbits{12.5} [Chisels & Bits] (chiselsandbits-12.5.jar) 
	UCHIJA	cookingforblockheads{4.2.16} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.16.jar) 
	UCHIJA	coralreef{1.0} [Coral Reef] (CoralReef-1.2.jar) 
	UCHIJA	cyberware{beta-0.2.3} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.3.jar) 
	UCHIJA	DungeonTactics{DT0.9.9} [DungeonTactics] (DungeonTactics-1.10.2-0.9.9.jar) 
	UCHIJA	IC2{2.6.69-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.69-ex110.jar) 
	UCHIJA	forestry{5.2.14.270} [Forestry] (forestry_1.10.2-5.2.14.270.jar) 
	UCHIJA	ElecCore{1.6.326} [ElecCore] (ElecCore-1.10.2-1.6.326.jar) 
	UCHIJA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta.jar) 
	UCHIJA	EnderIO{1.10.2-3.0.1.120_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.120_beta.jar) 
	UCHIJA	extraalchemy{0.3.0.2-release} [Extra Alchemy] (extraalchemy-0.3.0.2-release.jar) 
	UCHIJA	golems{6.02} [Extra Golems] (ExtraGolems[1.10.2]-6.02.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.1.0c.jar) 
	UCHIJA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJA	goetia{0.1} [Goetia] (goetia-1.10.2-0.002.0.jar) 
	UCHIJA	grapplemod{1.10-v7} [Grappling hook mod] (grapplemod-1.10.2-v7.jar) 
	UCHIJA	gravestone{1.5.7} [Gravestone] (GraveStone Mod 1.5.7.jar) 
	UCHIJA	helpertools{v3.0c} [HelperTools] (HelperTools-1.10.2-v3.0c.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	journeymap{1.10.2-5.3.0b1} [JourneyMap] (journeymap-1.10.2-5.3.0b1-unlimited.jar) 
	UCHIJA	llibrary{1.7.0} [LLibrary] (llibrary-1.7.0-1.10.2.jar) 
	UCHIJA	jurassicraft{2.0.4} [JurassiCraft] (JurassiCraft-2.0.4.jar) 
	UCHIJA	jeresources{0.5.2.57} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.2.57.jar) 
	UCHIJA	levelup{${version}} [Level Up!] (LevelUp!-0.12.2-1.10.2.jar) 
	UCHIJA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJA	LunatriusCore{1.1.2.36} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
	UCHIJA	minecolonies{1.10.2-0.4.1042} [MineColonies] (minecolonies-universal-1.10.2-0.4.1042.jar) 
	UCHIJA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJA	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	UCHIJA	netheressence{6.0.1.5} [Nether Essence] (NetherEssence-Forge-6.0.1.5.jar) 
	UCHIJA	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCHIJA	OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
	UCHIJA	overlord{1.1.6} [Overlord] (Overlord-1.1.6.jar) 
	UCHIJA	packingtape{0.6.0} [Packing Tape] (PackingTape-1.10.2-0.6.0.jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
	UCHIJA	shetiphiancore{3.3.1} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.1.jar) 
	UCHIJA	platforms{1.2.0} [Platforms] (platforms-1.10.0-1.2.0.jar) 
	UCHIJA	ProjectE{1.10.2-PE1.0.6B} [ProjectE] (ProjectE-1.10.2-PE1.0.6B.jar) 
	UCHIJA	reccomplex{1.2.1} [Recurrent Complex] (RecurrentComplex-1.2.1.jar) 
	UCHIJA	xreliquary{1.10.2-1.3.3.571} [Reliquary] (Reliquary-1.10.2-1.3.3.571.jar) 
	UCHIJA	reptilemod{3.5.2} [Reptile Mod] (reptilemod-1.10.2-3.5.2-58.jar) 
	UCHIJA	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJA	Stackie{1.6.0.44} [Stackie] (Stackie-1.10.2-1.6.0.44-universal.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCHIJA	tails{1.10.2-1.8.3} [Tails] (Tails-1.10.2-1.8.3.jar) 
	UCHIJA	golems_tcon{6.02.1} [Tinkers' Golems Addon] (TinkersGolemsAddon[1.10.2]-6.02.1.jar) 
	UCHIJA	totemic{1.9.4-0.7.8.1} [Totemic] (Totemic-1.9.4-0.7.8.1.jar) 
	UCHIJA	underphangables{1.0.2} [Underp Hangables] (underphangables-1.10.2-1.0.2.jar) 
	UCHIJA	vc{v2.5.0a-mc1.10.2} [ViesCraft] (ViesCraft-2.5.0a-mc1.10.2.jar) 
	UCHIJA	yarrmateys_cutemobmodels{1.0.13} [Yarr Cute Mob Models - Remake] (YarrCuteMobModelsRemake-1.0.13-1.10.2.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  shetiphian.core.asm.ClassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-0.8.5.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
llibrary (llibrary-1.7.0-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IC2core (industrialcraft-2-2.6.69-ex110.jar)
  
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IvToolkit (IvToolkit-1.2.8.5.jar)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.51.jar)
  team.chisel.common.asm.ChiselTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/butch/Documents/Curse/Minecraft/Instances/Cut%20the%20Sky/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/butch/Documents/Curse/Minecraft/Instances/Cut%20the%20Sky/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/butch/Documents/Curse/Minecraft/Instances/Cut%20the%20Sky/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/butch/Documents/Curse/Minecraft/Instances/Cut%20the%20Sky/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/butch/Documents/Curse/Minecraft/Instances/Cut%20the%20Sky/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/butch/Documents/Curse/Minecraft/Instances/Cut%20the%20Sky/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/butch/Documents/Curse/Minecraft/Instances/Cut%20the%20Sky/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/butch/Documents/Curse/Minecraft/Instances/Cut%20the%20Sky/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/butch/Documents/Curse/Minecraft/Instances/Cut%20the%20Sky/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: forge-12.18.1.2093
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Excalibur_V1.0.zip, [1.10.2]Dramatic Skys [v1.7].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4276
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by LovelyFlare** [comment]
Update OptiFine to the C4 pre-release.
