### ISSUE TITLE
[IDEA] More RF storage

### ISSUE THREAD

**Issue by ExcitedPlayer** [SlimeKnights/TinkersConstruct#2488]
Add Resonant and Quantum capacitor banks
RESONANT: 80MRF Capacity
QUANTUM: 5.12GRF Capacity (5120MRF)
Both should have normal maximum IO (Capacity divided by 1000)

If you don't like it, then thanks for anything, and also it would be nice to also add to 1.7.10 version, or ill have to download all mods to latest MC version, ane there is about 10 of my 66 mods for 1.9, so for 1.10 its impossible now :D

**Comment by ExcitedPlayer** [comment]
Wait, this is not ender IO page? my web browser somehow switched mods :(

**Comment by bonii-xx** [comment]
You'd be surprised how often I get issues that people mean to post on other repos. :P
