### ISSUE TITLE
Start up crash

### ISSUE THREAD

**Issue by amderrsom** [SlimeKnights/TinkersConstruct#2489]
[crash-2016-10-13_20.13.45-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/528380/crash-2016-10-13_20.13.45-client.txt)
i was playing just fine with the mod,and suddenly while i added some minor mods it started giving me this crash,im assuming its tinkers since the first lines say its name

**Comment by KnightMiner** [comment]
Optifines fault, not supported. Said to be fixed in Optifine C4.
