### ISSUE TITLE
Bug ?: Chest content in crafting station invisible

### ISSUE THREAD

**Issue by Ash70** [SlimeKnights/TinkersConstruct#2490]
mc 1.10.2
forge build 2099
TConstruct 2.5.5
other mods: EnderIO, Extra Utilities

When opening the crafting station any chest or double chest placed next to it has its contents turn invisible sometimes (and sometimes it becomes visible again after clicking inside it)

**Comment by bonii-xx** [comment]
Sounds like something is messing with GUI rendering. Most likely some other mod. Could also be certain items displayed in JEI, because *some* mod authors still don't know how to do models properly.
