### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by mightydanp** [SlimeKnights/TinkersConstruct#2491]
I know that tinkers is in 1.10 but i am having a problem in 1.7.10.
For some odd reason 1 nugget from tinkers turns into 1 ingot. I looked at other mods nuggets and this doesnt seem to apply on there mod just tinkers. I tried to disable the recipe via Minetweaker but it will not disable it throw it.

![2016-10-14_16 54 00](https://cloud.githubusercontent.com/assets/4637469/19403764/e032f36e-922e-11e6-9ec2-fe4d2c2240a7.png)

**Comment by ArukaAlter** [comment]
1.7 is not supported in the slightest.
It looks like some weird mod interaction, not something directly from Tinkers'.

**Comment by KnightMiner** [comment]
I have never seen that issue in my playing of the 1.7 version, so it sounds like some other mod is breaking things.

In any case, 1.7 is no longer supported and that issue does not happen in the latest release.
