### ISSUE TITLE
Change matches(ItemStack[]) to matches(ItemStack...) in IModifier

### ISSUE THREAD

**Issue by SnakeFang** [SlimeKnights/TinkersConstruct#2492]
Please? It makes a warning that I can't even suppress so now I'm sad and therefore it should be fixed.
But seriously though it should probably be changed since it is technically a warning.

**Comment by bonii-xx** [comment]
Then fix the warning....?

**Comment by KnightMiner** [comment]
The warning is in our own code because we are using the recipe match method `matches(ItemStack...)` to implement the modifier method `matches(ItemStack[])`. In Eclipse at least this causes a warning to appear on almost every modifier class.

**Comment by bonii-xx** [comment]
Hm, must've forgotten to adjust the interface then. Semantically they're equal.

**Comment by bonii-xx** [comment]
Ah yes, I see where it comes together. Because the implementation actually comes from another class. Since they're just two notations for the same thing we should be able to change it without breaking compatibility.
