### ISSUE TITLE
[1.7.10] Crash when reflecting Twilight Forest Hydra's mortar fireball with Battlesign

### ISSUE THREAD

**Issue by Zsashas** [SlimeKnights/TinkersConstruct#2493]
https://github.com/Benimatic/twilightforest/issues/58

Not so much expecting a fix, as simply bringing it to your attention in case it happens elsewhere. However, some way to un-stick myself would be appreciated, as I cannot log in until it is fixed.

**Comment by bonii-xx** [comment]
Looks like a missing check in the 1.7 implementation. Will see that the 1.10 version doesn't have the issue.

**Comment by Zsashas** [comment]
So I restored a backup of everything (player, modlist, save) and when I rejoined, in a plains biome in the overworld from two days before, the first thing I saw was a reflected hydra mortar flying away from me and exploding, despite the fact that it shouldn't have even been created yet.
