### ISSUE TITLE
Bug (i think) with mending moss

### ISSUE THREAD

**Issue by vrork** [SlimeKnights/TinkersConstruct#2495]
Hello, i have the latest version of TiC (TConstruct-1.10.2-2.5.5.jar) and mending moss only works on my weapon, not on the pickaxe. Is that a bug or i am doing something wrong? (i tried having only one of them in my iventory/hotbar) and the pickaxe still didnt repaired with xp

**Comment by ArukaAlter** [comment]
Can't reproduce.

**Comment by KnightMiner** [comment]
First off, were you holding the pickaxe in your main/off hand when you collect XP? If not, it has no XP stored to repair from.

Secondly, was the pickaxe in your hotbar/offhand after you collected XP while holding it? Repair only runs in those slots.

**Comment by vrork** [comment]
I think so, but i will try it again. And yes, it was in my hotbar

Em 16/10/2016 02:47, "KnightMiner" <notifications@github.com> escreveu:

**Comment by vrork** [comment]
How fast it is supposed to fix? i get 3 points of durability fixed every 7 seconds. But dont know if that can be the wooden parts of the tool.

**Comment by LordHellscream** [comment]
well sword is constantly getting the xp, while the pickaxe rarely do. It may just be a impression thing. I think mending moss isn't a good modifier for pickaxe/hammer (IMO), if you really want an undestrutible pickaxe may be getting the tinker leveling and max your pickaxe with reinforcement modifier.

**Comment by laz2727** [comment]
3 every 7 seconds is moss, yes.
