### ISSUE TITLE
[2.5.6] Smeltery contents disappear periodically

### ISSUE THREAD

**Issue by C0rn3j** [SlimeKnights/TinkersConstruct#2497]
Forge: 2107
Modlist: http://pastebin.com/hEMvVjJd

This video will say more than I can.

https://www.youtube.com/watch?v=PAQ_Op2bqtA&feature=youtu.be

**Comment by bonii-xx** [comment]
Reproduce with only TiC and Mantle

**Comment by C0rn3j** [comment]
I've copied the world and used it in SP(on the video is MP) and I can't reproduce it at all now even with all the mods.

**Comment by bonii-xx** [comment]
What are you running on the server?

**Comment by C0rn3j** [comment]
Different player save and we're 2 on the server.

That's the only difference I can think of, mods and forge version are identical.
