### ISSUE TITLE
1.10.2 (TC v2.5.6) Unbreakable (Insatiable) Shuriken still loses ammo when fired rapidly

### ISSUE THREAD

**Issue by LordHellscream** [SlimeKnights/TinkersConstruct#2499]
Just updated to the latest (v2.5.6), still noticing this issue, even tho the durability Bar doesn't change the ammo still goes down (when fired rapidly)
Repro:

Make a paper shuriken (or any shuriken with 5+ modifier), add 5x reinforcement modifier.

Fired rapidly, watch the ammo deplete (it won't show as durability bar is not changed, but if you mouse over the item it will show ammo decreasing), i noticed this when it suddenly broke (showing as empty) after a large battle.
If you fired slowly it doesn't seen to deplete (or may be it has a small chance to deplete and i simply don't notice unless fire many times)

**Comment by bonii-xx** [comment]
Try firing a few shurikens, then relogging. Is the missing ammo gone then?

**Comment by LordHellscream** [comment]
Relogging doesn't seem to have any effect, the ammo count is unchanged before and after relogging.

However, I think this LIKELY have something to do with Manyulyn, since the test shuriken is partially made of manyullyn which has the insatiable modifier. 
I just retested it, this time exactly same setup but replacing the manyullyn parts with steel and so far the ammo have not depleted

**Comment by KnightMiner** [comment]
That does seem likely, given [this line](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/traits/TraitInsatiable.java#L38). Sounds like unbreakable is setting the tool damage to nothing before manyullyn adds its damage.

**Comment by bonii-xx** [comment]
Needs to be testet in the other branch, some of that stuff is fixed there

**Comment by luckdemon** [comment]
This issue still persists in 2.6.0

**Comment by MarkSzita** [comment]
The problem is not a bug, it's Manyullyn. it's material effect is to lose durability. change to a different material.
