### ISSUE TITLE
[1.10.2] 2.5.6 Crash Slime Boots/Sling

### ISSUE THREAD

**Issue by kiwifails** [SlimeKnights/TinkersConstruct#2500]
I was wearing the boots and using the slime sling when this crash happened, so I can't quite tell which one caused it. Something about a duplicate EventHandler and Minecraft not liking that? :P

https://gist.github.com/kiwifails/0b110dd87253b9e3580afdc921878a81

**Comment by bonii-xx** [comment]
#2470
