### ISSUE TITLE
Remove Modifiers?

### ISSUE THREAD

**Issue by Ruok2bu** [SlimeKnights/TinkersConstruct#2501]
I have a grand master level pickaxe and auto smelt was added to it (with a new level).  Is there any way to remove a modifier that's added to a tool?

**Comment by ArukaAlter** [comment]
I assume this is 1.7 you're talking about, it's no longer supported and the feature you mention is from Iguana Tinkers' Tweaks.
The random modifiers are by far one of the biggest downsides of the addon, they cannot be removed.

**Comment by Ruok2bu** [comment]
Ooops, sorry.
