### ISSUE TITLE
Add mouse wheel support to the Crafting Station when linked to a chest

### ISSUE THREAD

**Issue by KamranMackey** [SlimeKnights/TinkersConstruct#2505]
When a chest is next to a Crafting Station, I would really like it if I had the ability to scroll through the items in the chest when you're looking at the items through the Crafting Station.

**Comment by bonii-xx** [comment]
That actually was a thing in 1.8. Not sure what broke it.

**Comment by bonii-xx** [comment]
Ah yes. It still works. But it doesn't work if you're over a stack with an item in it, because inventorytweaks.
