### ISSUE TITLE
use zh-cn crashed

### ISSUE THREAD

**Issue by subtank** [SlimeKnights/TinkersConstruct#2506]
when i use the chinese lang to playing this mod,it didnt complate translation and crash when i use the book.

**Comment by subtank** [comment]
by the way,i have enough time next year and i can help to translation this mod to chinese~

**Comment by subtank** [comment]
i just delete the document about the chinese trans and it didnt crash.

**Comment by subtank** [comment]
TConstruct-1.10.2-2.5.6 this version

**Comment by KnightMiner** [comment]
Crash report or it did not happen.

Please paste it on a site like gist.github.com or paste in.com and link it here.

**Comment by subtank** [comment]
just start the game,change language to chinese simplified,run a game ,open the book,crazy click next page button,until 53 page.crashed.(no change jar file)
if i delete the language file,it works well.
i think there is some code was trans by mistake.
i dont know how to upload a file in git,so here is a link for my changed jar.
link：http://pan.baidu.com/s/1i5uM3o5 code：a74y (sorry to use chinese)
i think it must some code translated to chinese by error.

**Comment by subtank** [comment]
by the way,some translate was a ? instead, i am sure it is the encoding was wrong.(i just repaired it)

**Comment by subtank** [comment]
i just fixing this bug by retranslate your mods.i will upload the fix one and the change log on the above link(may be needs an hours)

**Comment by subtank** [comment]
finished~all bug fixed and translate all words

**Comment by subtank** [comment]
need more time to translate

**Comment by subtank** [comment]
finfished

**Comment by KnightMiner** [comment]
You never gave the original crash report, thus this report remains invalid. Go to pastebin.com, and paste the text of you crash report into the text field. Then paste the link to it here.

Once that is done, if you want to contribute a "fixed" version of the file, we are not going to extract it from a custom made jar, submit a pull request properly. Just go to [this page](https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tconstruct/lang/zh_CN.lang), click the edit button (pencil) and when you are done find the compare and pull request button to allow us to review the changes.

**Comment by subtank** [comment]
Ok i try to fixed it.

**Comment by subtank** [comment]
I am a new guy to use git,thank you for link

**Comment by subtank** [comment]
Bug fixed, how can i upload my language file? I want help you to translation completed.

**Comment by KnightMiner** [comment]
> click the edit button (pencil) and when you are done find the compare and pull request button to allow us to review the changes.

You have the repository, yes, but actually make changes and save them if you want us to be able to use them (a commit with your changes should appear). If you are unfamiliar with github, there are plenty of tutorials you can find using google that can help you edit a file and create a pull request.

Also, don't forget the crash report link I mentioned twice above.

**Comment by subtank** [comment]
later to the crash report. Tired.

**Comment by subtank** [comment]
it is midnight to me.

**Comment by subtank** [comment]
No need crash report?

**Comment by bonii-xx** [comment]
Well, the PR you made was a pretty obvious error. I just assumed it'd be fixed with that?

**Comment by subtank** [comment]
Yeah, i run it very well to change this line. and i just translation you wrok, can you upload my file to complete the chinese version?

**Comment by bonii-xx** [comment]
The fix is already pulled in. We got it in our code now.

**Comment by subtank** [comment]
Though i can read English, but it is comfortable to read the mother language.

**Comment by bonii-xx** [comment]
You can make a resourcepack with the fix, to use it with the old version. We wont release an update for quite a while now, too much untested stuff. You could even upload it somewhere for people to use, I'm not really familiar with the chinese community.

**Comment by subtank** [comment]
actually the Chinese community just link your work to your website. No restore your work, and my translation was tested.works well, didn't change your coding, just the translation files.

**Comment by bonii-xx** [comment]
Can you test if https://minecraft.curseforge.com/projects/tinkers-construct/files/2338124 works?

**Comment by subtank** [comment]
did you change the language. Lang Encoding from ACSII toUTF-8? if no, not actually fixed all bugs

**Comment by subtank** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tconstruct/book/zh_CN/language.lang

**Comment by subtank** [comment]
This file Encoding was wrong

**Comment by 3TUSK** [comment]
Ok let me get this clear: 
Is the fact that the manual translation is missing some pages causing the crash (i.e. a NullPointerException cause the corresponding Simp. Chinese translation does not exist)? @TartaricAcid

**Comment by TartaricAcid** [comment]
I'm going to fix the error right now.

**Comment by subtank** [comment]
@3TUSK nope,this crash happen was the coding line was translated(not suppose)

**Comment by subtank** [comment]
@bonii-xx crash bug fixed but here other question messy code was worth,check your file encoding and change all of them to UTF-8

**Comment by 3TUSK** [comment]
@subtank This is @TartaricAcid's fault IIRC. To be specific, [this file is encoded with GB-18030](https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tconstruct/book/zh_CN/language.lang). Last time I checked, everything else is fine.

**Comment by TartaricAcid** [comment]
Ok, it seem that you have already fixed the error, sorry for my careless.

**Comment by subtank** [comment]
the fix version  https://minecraft.curseforge.com/projects/tinkers-construct/files/2338124 have a lot of wrong encoding to show more messy code than before. @TartaricAcid @3TUSK if you want to fix it, try to replace those files

**Comment by subtank** [comment]
link：https://pan.baidu.com/s/1i5uM3o5#list/path=%2Fgit%20file%2Fchanged
if needs code here the code：a74y

**Comment by TartaricAcid** [comment]
Thank you a lot.  : )

**Comment by subtank** [comment]
link：https://pan.baidu.com/s/1i5uM3o5#list/path=%2Fgit%20file%2Fchanged
if needs code here the code：a74y

**Comment by subtank** [comment]
complate translation and fix all messy(test pass)

**Comment by subtank** [comment]
a lot of file was wrong and added,tired to check one by one,so i just put all of the translate file.

**Comment by subtank** [comment]
@TartaricAcid i think we can use QQ to make the translation faster,

**Comment by TartaricAcid** [comment]
Do you have gitter?

**Comment by 3TUSK** [comment]
GitHub shall have a pm function. @TartaricAcid try roman numeral.

**Comment by TartaricAcid** [comment]
@subtank Here is my e-mails: 568248266@qq.com

**Comment by subtank** [comment]
yes, i need go out now. Response not ASAP

**Comment by subtank** [comment]
直接加你好友了。

**Comment by bonii-xx** [comment]
Hence the fix on Curseforge. I just don't really have the ability to check if it works.

**Comment by subtank** [comment]
you didnt change any code at all....

**Comment by subtank** [comment]
https://minecraft.curseforge.com/projects/tinkers-construct/files/2338124 this file just work well if ignore the messy code.

**Comment by subtank** [comment]
no bug because translation

**Comment by subtank** [comment]
i think you just upload a wrong file.

**Comment by bonii-xx** [comment]
So what you're saying is that it doesn't LOOK correct, but at least it doesn't crash?

**Comment by subtank** [comment]
sorry , i just download wrong file.i find i download wrong file (the old version),the new version 2-2.5.6a works well

**Comment by subtank** [comment]
my fault.

**Comment by bonii-xx** [comment]
Okay, thanks for confirming it. Then I'll bump 2.5.6a to a full release so people don't download the broken version anymore.

**Comment by subtank** [comment]
doesn't look good becaust the file encoding was anisii and the chinese need the encoding about UTF-8

**Comment by subtank** [comment]
solve it:
you just needs change the encoding and all bug was gone except uncomplate translate,needs time to decide how to translate more localization and more funny.\(^o^)/

**Comment by bonii-xx** [comment]
I fixed it but some dependencies are unavailable currently, so I can't make a new build right now. We'll have one later.

**Comment by subtank** [comment]
nice.i can use the offcial one finally.

**Comment by bonii-xx** [comment]
Fixed encoding: https://minecraft.curseforge.com/projects/tinkers-construct/files/2338518

**Comment by subtank** [comment]
good job.fixed messy code
