### ISSUE TITLE
Tooltip bug

### ISSUE THREAD

**Issue by sscards55** [SlimeKnights/TinkersConstruct#2507]
Simply put if an item finishes melting and there is no space in the inventory it will display the no space tooltip, make space and it converts into liquid.

However, if something else starts smelting and the fuel in the tank is completely depleted the item will continue to say not enough space in the smeltery.
![Imgur](http://i.imgur.com/tv1lLTc.png)
![Imgur](http://i.imgur.com/meXgAvb.png)
![Imgur](http://i.imgur.com/FSaQMah.png)

**Comment by Karill** [comment]
Why should it change? Technically, as far as i understood TiC, the item is already smelted completely, just doesn't have enough space to be finally converted. So even without any fuel left, once there is enough space in the smeltery, the item should convert automatically. The smelting process itself is finished on that one ore. (If that is not the case, please someone correct me.)

**Comment by sscards55** [comment]
One thing I just realize i forgot to mention is that i completely drained the smeltery after this, but the ore wouldn't convert to liquid.
I'm assuming that the smelting code only runs if there is fuel in the tank and since there is no fuel in the tank there shouldn't be any need to convert items into fluids, which is why the ore is still an item.

**Comment by sscards55** [comment]
I think I found it [here](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/smeltery/tileentity/TileHeatingStructure.java#L87)

**Comment by YasminEndusa** [comment]
True, at least because hasFuel() is a requirement. So, technically, if at one point the last bit of fuel would be used to bring the temp of a heated item up to the required temp it wouldn't melt too (because that would be checked on the next call of heatItems() and hasFuel() would return false at that point). Question is if that is intended behavior (technically, the item is finished melting, so i'd say no).

**Comment by bonii-xx** [comment]
That is indeed correct and intended behaviour. The status doesn't change when the smeltery doesn't "run", and that's how it should be. Technically speaking the temperature/melting progress on every item would have to go back when there's no fuel, but there's no real benefit in doing that.

**Comment by sscards55** [comment]
Since the smeltery behavior is indeed intended, then it mean that the tooltip is unintended. Checking if the smeltery needs fuel before rendering the tooltip should correct this.

That is what my issue was originally.

**Comment by bonii-xx** [comment]
The tooltip just displays the status. The status doesn't change when the smeltery doesn't "run".

**Comment by sscards55** [comment]
It's almost that.

There are 3 prerequisites for melting an item:
1. fuel
2. temperature
3. space

The smeltery logic basically goes like this:
```
if (hasFuel){
   if (heat > requiredHeat){
     if (checkSpace){
       meltItem()
       sufficientSpace = true   <-- this only changes here
     }else{
       sufficientSpace = false  <--and here
   }else{
     heatItems()
     consumeFuel()
   }
}else{
   needsFuel = true
}
```
However the tooltip only checks the sufficientSpace flag, it does not bother to check if the smeltery needs fuel or not. So if there is no space for the item to melt and the fuel runs out, the tooltip continues to say no space in the smeltery even when you clear the entire smeltery.
