### ISSUE TITLE
Scythe component mis-order when building the tool? Might be intentional.. might not. 

### ISSUE THREAD

**Issue by smithnc07** [SlimeKnights/TinkersConstruct#2509]
Per the comments the order should be Head > Extra > Handle. 
How ever the current order is Head > Handle > Extra. As such the extra durability isn't being modified by the tool modifier(Aka you end up with slightly higher tool durability). 

ToolNBT data = new ToolNBT();
    data.head(head);
    data.handle(handle, handle2);
    data.extra(extra);

**Comment by KnightMiner** [comment]
You are correct, just me being dumb. Fixed with 6cd30d3.

**Comment by smithnc07** [comment]
Awesome, thanks!
