### ISSUE TITLE
[1.10.2] null Items

### ISSUE THREAD

**Issue by YOYOK9** [SlimeKnights/TinkersConstruct#2511]
So Ive noticed in my client log many lines that say null items. 

MC: 1.10.2
TConstruct-1.10.2-2.5.6
https://gist.github.com/YOYOK9/a0e7131d7139d79c53b4fd96e18def8b

**Comment by KnightMiner** [comment]
Please explain what you mean, I see nothing in the log related to null items or to a Tinkers Construct error.

**Comment by spike11302000** [comment]
try updating opifine

**Comment by bonii-xx** [comment]
There's nothing TiC related there.
