### ISSUE TITLE
Paper cleaver upgraded to unbreakable, Add Manyullyn blade now takes durability.

### ISSUE THREAD

**Issue by RubikMonat** [SlimeKnights/TinkersConstruct#2512]
I made an all paper cleaver in HermitPack (MC1.10.2 / ticon 2.3.5)
I leveled it as paper, added redstone and obsidian plate things to make it Hastestest and Unbreakable (max on both)
Added one sharpness and some Beheading modifiers.
Then I changed blade to Manyullyn and one tool rod to Cobalt.
Now it does Damage as you expect with one shotting blazes, but it takes durability. 
It will repair with paper, I haven't tried repairing with Manyullyn ingots yet.

So now the tool: 
states Unbreakable but it has durability, and not much of it either. 
Deals Manyullyn damage but repairs with paper (is this because of the paper plate?)
Is this as expected? 
If I lose modifiers by removing paper parts that is reasonable, but it would be great if the modifiers list updated. 

Suggested solutions: 
A: Update the modifiers list to reflect which are lost when parts are replaced. 
B: Retain the modifiers when parts are replaced. 

If A: Then please list what order the modifiers will be lost in before replacing the part. 

Thinking about it: I probably slowed the tool down if I put the cobalt rod on it (+10%) and it displaced one level of redstone (-20%) 

Edit: replaced the metal parts with paper again and the tool is no longer taking damage. So removing paper parts inhibits modifiers doesnt remove them. Seems to be working as intended, but would definitely be good to have some mention in the book on the paper/magic wood pages warning you not to try to cheat by changing parts later.

**Comment by bonii-xx** [comment]
You cannot exchange toolparts if you don't have enough modifiers to do so.

What causes you to lose durability is Manyullyns trait.

**Comment by laz2727** [comment]
I think the main issue there is Insatiable bypassing Unbreakable.

**Comment by HeavyDeception** [comment]
@bonii-xx @laz2727  May I asked in which update that this is resolved in?
I have a sword that has unbreakable on it and Insatiable. (another mod adds it so you can lvl your tool and unlock modifiers) but its still using durability. 

I have TC 2.5.6b

**Comment by LovelyFlare** [comment]
@HeavyDeception 2.5.6b was released on October 22nd.  The resolved tag for this issue was just added 3 days ago.  Do the math.

**Comment by HeavyDeception** [comment]
@LovelyFlare Ok for one I did not know that is was released then and it could have been just a quick fix or something like that. this was also put up 10 days ago so he could have waited after he updated the pack to change it to resolved.

**Comment by HeavyDeception** [comment]
@LovelyFlare Its sounds mean when you say it like that. I ain't that bright some times.

**Comment by KnightMiner** [comment]
If an issue is marked resolved but not closed, it means it is fixed in a future release/only fixed in am alpha release.

**Comment by LovelyFlare** [comment]
@HeavyDeception I did not mean that in a mean way.  I simply meant to say that one should try looking around a bit more before asking.  Though I was in a bit of a cranky mood as well.  I apologize for that.

**Comment by HeavyDeception** [comment]
@LovelyFlare Ya its ok I know that, Thank you for the Info you were very help full.
