### ISSUE TITLE
Undocumented Block: Seared Furnance Controller

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#2513]
Important Stuff:

MC 1.10.2
Forge 12.18.2.2099
Mantle 1.0.0
TC 1.10.2-2.5.6

The Seared Furnance Controller is crafted with a vanilla furnance surrounded by 8 seared bricks.
It's not identical with the smeltery controller and without any GUI or documented use.

**Comment by SharkSheaker** [comment]
i did and tried for like 30mins.

As you said i tooked again a look into the book and was still confused as before.

1h later: found out the problem: the book says "any size frome 3x3 to 11x11" ... the furnance must be a cube and not a wall... missing 3th coord in the description

**Comment by KnightMiner** [comment]
From the book:

> The Seared Furnace can be any size from 3x3 to 11x11, and with any height from a minimum of 3

The base must be a rectangle, the height is stated
