### ISSUE TITLE
[1.10.2][Suggestion] Config option to disable in world rendering on a per mod basis.

### ISSUE THREAD

**Issue by MrNinja93** [SlimeKnights/TinkersConstruct#2514]
Seeing all the issues regarding Mekanism and its broken rendering problems might it make sense given the mekanism devs reluctance to change the way they render to the standard used to instead tinkers side add the ability to disable rendering in world on a per mod basis with a default of Mekanism added (until such time they fix it) which also leaves the option open to blacklist other mods from rendering in world if they too break. 

The current fix to that rendering issue is to disable rendering in world which has the annoying side effect of disabling all rendering including ingots/blocks being cast from a tinkers table which are invisible (very jarring effect when you've always had them visible)

Would help pack makers too as we then don't have to break all rendering in world just because of Mekanism crashing players. (Plus less Mekanism issues/crashes spamming yours/ours issues feeds)

**Comment by bonii-xx** [comment]
No we're not encouraging hacking the rendering system. Mekanism has to fix its models. If you want it fixed, take it up with them.
