### ISSUE TITLE
VeinMiner and Tinkers crash

### ISSUE THREAD

**Issue by PretoAlbino** [SlimeKnights/TinkersConstruct#2515]
Idk what mod is the responsible for crash

http://pastebin.com/Q3HJ8nXM

**Comment by bonii-xx** [comment]
1.7.10 is not supported anymore

**Comment by PretoAlbino** [comment]
What I can do to resolve this??

**Comment by Eufranio** [comment]
Any tool that breaks more than one block + Vein miner = crash. Report to them.

**Comment by PretoAlbino** [comment]
Yeah, the only way is removing Vein
