### ISSUE TITLE
Seared furnance not so effective like the smeltery

### ISSUE THREAD

**Issue by SharkSheaker** [SlimeKnights/TinkersConstruct#2516]
In the .cfg you can set the ratio for the gathering out of ores in the smeltery, standard is 2, but it seems like the seared furnance is unaffected by this...

**Comment by KnightMiner** [comment]
Yes, it is. Its a furnace, thus it acts like a furnace.

The point of the furnace is being able to cook many items at once, primarily food (though also odd items like cactus). It is not designed to replace the smeltery, which is still the prefered choice for ores (as shown by ore doubling)
