### ISSUE TITLE
Crash while replacing tool head

### ISSUE THREAD

**Issue by Chupp4-Jo3** [SlimeKnights/TinkersConstruct#2517]
Tried replacing a pickaxe's head with a steel one when my client crashed out.

http://paste.atlauncher.com/view/9e64ef8b  <--- Log at time of crash (CR starts at line 61)

http://paste.atlauncher.com/view/b76eeb7a <--- Log at boot (probably nothing of note here but put it up just in case)

**Comment by bonii-xx** [comment]
And here I thought I cought all occurences where buttons where added. The first part is that there's an unexpected button from (https://minecraft.curseforge.com/projects/buttonz)[Buttonz], even though it's not in your modlist?

The weirder part is that the tool seems to have a modifier or trait that doesn't exist? But that's probably some really weird effect of the thing above. Try if it still crashes if you remove whatever mod adds extra buttons

**Comment by Chupp4-Jo3** [comment]
Just tried again with buttonz disabled (had to test in single player as I don't have access to the server settings but I'll ask for a copy of the world file to test with)

No issues now but I just noticed (amazingly long after it first appeared) that the UI for the tool forge get's screwed up when I'm on the server and isn't when buttonz is disabled so I guess whatever it's doing it's conflicting with TiC.

I'm about to get a copy of my log when I repeat this in SP and see if that can shed some light on it (I'll also get a copy of all this sent to the Buttonz dev's)

**Comment by Chupp4-Jo3** [comment]
Log of me trying in SP (with some screenshots I forgot to copy the log of the without buttons attempt also note that it works this time leading me to think the server side of the mod is causing issues, we also used to have TiC tool levelling which might be where the modifier is coming from and explain everything)

http://paste.atlauncher.com/view/915c5869

![2016-10-23_16 26 15](https://cloud.githubusercontent.com/assets/13005453/19627397/f57fc614-993d-11e6-8bdd-343c19f3a4d3.png) <---- screenshot of UI error which I'm guessing is buttonz

**Comment by bonii-xx** [comment]
The bug is on my side
