### ISSUE TITLE
Broadsword not effective on coweb

### ISSUE THREAD

**Issue by Tomash667** [SlimeKnights/TinkersConstruct#2518]
It is as fast as doing it without weapon.
Broadsword with iron head and bone other parts:
![2016-10-23_12 45 13](https://cloud.githubusercontent.com/assets/260290/19625676/5f3d464a-991f-11e6-8b83-9d5dbc018b92.jpg)
Normal stone sword:
![2016-10-23_12 45 21](https://cloud.githubusercontent.com/assets/260290/19625683/8b4a2b0e-991f-11e6-9584-537a66f3ac75.jpg)

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by Tomash667** [comment]
Looks like the problem is with WailaHarvestablity. I reported it there.
