### ISSUE TITLE
[Request] Excess Fluid Repository

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [SlimeKnights/TinkersConstruct#2521]
I've found my self getting stuck with an amount of fluid that is small enough that I do not want to waste it, yet it cannot be turned into nuggets. So it ends up sitting in my smelter and getting in the way occasionally. 
This is probably the stupidest request you've gotten (Seriously, this is a milestone here for the human race), But would it be possible to add a block that stores 8 (Or some other amount that's useful) fluid types up to 144 mb, aka an Ingot's worth?

**Comment by KnightMiner** [comment]
Why do we need a new block to store 8 to 144? Pour it in the tank that holds 1 to 4000

**Comment by UnstableCodeScarlet** [comment]
You're right, it barely effects capacity. That is the point
Wasting multiple blocks of tanks on something that could be as simple as dividing up a single tank into different segments of lesser storage is the point.
Tanks can only store one fluid type, so why not make one that can store a lesser amount of multiple?

**Comment by KnightMiner** [comment]
The tinker tank is the multiblock tank that holds any liquids you want, that is my point. Multiblock tanks are for multiliquid storage and large quanity storage, smaller tanks are for dedicated storage

**Comment by UnstableCodeScarlet** [comment]
I.. Have never heard of a "Tinker Tank", was that added recently? This point of this tank is completely different. It's Low quantity storage with high variation. Basically it's a single block tinker tank with low storage. I imagine this tinker tank would be useful in certain scenarios, but it's meant for a different thing, Tinker tanks sound like they would be used in scenarios where you needed to store a large amount of liquids from similar sources with similar uses. Ie Oil and Ethanol, or for simply storing a large amount of fluid you do not feel like using quite yet, but do not want to dedicate another tank towards. The point of the tank I am suggesting is minor fluid storage compressed, basically a side tank meant for pouring those few mb that never leave the smelter, or a similar alternative to dealing with said mb. Say, a new use for seared tanks in a smelter to lock multiple fluids off to avoid getting in the way. Making a 15 block mutliblock (Or whatever it is) for a tiny amount of fluid would be inefficient, and a waste of space.

**Comment by laz2727** [comment]
Or in a tank that holds 108k of 108k.

**Comment by bonii-xx** [comment]
Not really planning on adding anything like that. Managing the fluids is part of working with the smeltery. There's several tools for dealing with this, like the tinker tanks.

Also no, I've gotten much worse requests. ;)
