### ISSUE TITLE
Ore information request.

### ISSUE THREAD

**Issue by draconyc** [SlimeKnights/TinkersConstruct#2522]
I attempted to use TC2 with the Fun Ores mod, just so I could have the ores without a lot of extra stuff I'm not likely to want.  Those metal ores didn't work, meaning I put them in the smelter and they do nothing.  What I am asking for is one of two things, or both if you feel like it:
1. Why don't those ores work with TC2?
2. Do you know of any specific mods that include the aluminum, brass, etc, that TC2 can use properly?  Is there maybe a list somewhere that I haven't found yet?

**Comment by bonii-xx** [comment]
> 1. Why don't those ores work with TC2?

He probably doesn't register them correctly.. or you're trying to melt ores that can't be molten.

> 2.

Base Metals

**Comment by draconyc** [comment]
I was wondering about Base Metals but after the misfire with Fun Ores I was reluctant to try a new one without asking first, so thank you!
