### ISSUE TITLE
Lag spike when placing/breaking a block next to many crafting stations

### ISSUE THREAD

**Issue by Hallo89** [SlimeKnights/TinkersConstruct#2523]
TiC version: 1.10.2-2.5.6b
Forge version: 12.18.2.2113
Minecraft version: 1.10.2

When I place about 20 crafting stations filled with recipes and then place or break a block in a pretty much 9 block radius I get a pretty large lagspike which drops my fps by about 50 in the second I place or break the block next to them. The fps itself when standing next to the crafting stations or looking at them is totally fine.
When the stations aren't filled with recipes, no lagspike happens
Tested with and without optifine, optifine doesn't affect it

**Comment by bonii-xx** [comment]
That's because breaking a block in a chunk causes it to re-render. Which means that all the crafting stations have to rebuild their models. If it's a lot of stuff.. well then it takes a while.

**Comment by Hallo89** [comment]
Didn't think of that :D
