### ISSUE TITLE
Launching with slimesling stops player mid-air, console shows "player moved too fast"

### ISSUE THREAD

**Issue by randomdude999** [SlimeKnights/TinkersConstruct#2526]
This only happens when i align the sling good enough to get moving _really fast_. Then it just stops me in mid-air and I fall down. Nothing really deadly (wearing slime boots is kind of necessary for using the sling anyway), but it gets really annoying when I try to get from one end of a forest to another to reach my base before it goes dark outside.
(Btw, I'm on a private server with a few friends.)

**Comment by bonii-xx** [comment]
That's a vanilla change. You can disable it by setting the "disableElytraMovementCheck" gamerule to true.

**Comment by randomdude999** [comment]
I tried. Didn't really work.

**Comment by randomdude999** [comment]
if (!this.playerEntity.isInvulnerableDimensionChange() && (!this.playerEntity.getServerWorld().getGameRules().getBoolean("disableElytraMovementCheck") || !this.playerEntity.isElytraFlying()))
    {
        // log about speedhax and reset player speed
    }

is the part of the code that does this. The isInvulnerableDimensionChange probably returns false, so we can remove that part:

    if (!this.playerEntity.getServerWorld().getGameRules().getBoolean("disableElytraMovementCheck") || !this.playerEntity.isElytraFlying())

The disableElytraMovementCheck is true now, so

    if (!true || !this.playerEntity.isElytraFlying())

~You~ I don't have elytra when slimeslinging, so

    if(!true || !false)

Which just happens to be true.

**Comment by bonii-xx** [comment]
Yeah, blame vanilla. :I

**Comment by randomdude999** [comment]
Vazkii managed to edit like 4 vanilla classes is Quark, maybe you can too?

**Comment by bonii-xx** [comment]
We're not doing ASM.

**Comment by randomdude999** [comment]
well then I'll just close this.
