### ISSUE TITLE
Strange issue with Bow Aim Animation

### ISSUE THREAD

**Issue by Blunderblast** [SlimeKnights/TinkersConstruct#2528]
I'm away traveler's gear is gone from the newer versions, and 1.7.10 is no longer supported. So I totally understand if this is removed and would appreciate the closure of a "No" answer. I'm not asking you to fix it, I'm asking if you could explain to me how to fix it myself, or if it's even possible for me to do. Worst case I'll simply remove the texture so it won't be an eyesore, but the gloves are super cute, so I'd like to keep them.

Anyway.. The gloves stay in the walking animation position while aiming a bow. If possible.

Thanks a bunch! Love your work! I'm playing it for the first time and it's super fun!

**Comment by LovelyFlare** [comment]
Well... hi there.  You most likely won't be able to fix it on your own.  Actually, you aren't happening to use OptiFine with it are you?

**Comment by bonii-xx** [comment]
Simply put, you can't fix it. Anything player/mob related is hardcoded rendering stuff. Plus the rendering code for that stuff is not exactly... friendly. You'd have to tell the the thing that draws the gloves to use the same animation as the player model.
