### ISSUE TITLE
Ender Dragon Immunity to Shurikens (1.10.2, 2.5.6b)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2531]
I'm not sure if this is intended, but none of the shurikens seem to work on the Dragon while it is in any state (flying or whatnot) whilst bows seem to work fine while it is flying.

**Comment by LordHellscream** [comment]
I can confirm this.

**Comment by LovelyFlare** [comment]
Not sure where the duplicate issue is, that's what I'd like to know.

**Comment by KnightMiner** [comment]
Not sure if it is on the tracker, but I reported it directly to boni when testing bows and he fixed it in a later commit.

**Comment by LovelyFlare** [comment]
Ah, that makes more sense.
