### ISSUE TITLE
GUI Scale Setting (1.10.2, 2.5.6b)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2532]
Having the GUI Scale set to small makes the book unreadable and also will cause the tool forge info to overlap a bit.
![2016-10-30_19 25 04](https://cloud.githubusercontent.com/assets/14182009/19841149/0090feb2-9edc-11e6-8a5c-ea7912e64368.png)
![2016-10-30_19 27 29](https://cloud.githubusercontent.com/assets/14182009/19841150/009f9116-9edc-11e6-93aa-9739720c6dda.png)

**Comment by bonii-xx** [comment]
Not really a bug. That's simply what happens when things get too small.
