### ISSUE TITLE
Comparator reading smeltery drain doesn't give an output

### ISSUE THREAD

**Issue by Yadokingu** [SlimeKnights/TinkersConstruct#2534]
In the 1.7 version of Tinkers Construct a comparator reading the smeltery drain would give an output corresponding to the fluid level in the smeltery. This is no longer the case, which is sad, since it was extremely usefull when smelting mobs, to always keep some fluid in the smeltery.

version 1.10.2-2.5.6b

**Comment by TherminatorX** [comment]
Are you sure it wasn't the Smeltery Controller?

**Comment by KnightMiner** [comment]
Neither do it as of 1.10, its one of those features that we want to decide the best way to re-implement if it is coming back, as comparators require block updates to change values, and block updates cause the smeltery to check for rebuilding.

**Comment by TherminatorX** [comment]
Just tried to do this in 1.10 to get some automation done, forgot it hadn't been reimplemented yet. Any updates?

**Comment by BrisingrAerowing** [comment]
I saw this and had an idea. Maybe a special seared block that acts like a comparator, but monitors the fluid level in a smeltery and outputs a redstone signal based on that? I'm not sure how the smeltery is implemented, but it could listen for an event when the liquid level changes and waits for a small amount of time, reset if the level keeps changing, and then changes the output when the level stops changing.

Having this work with a Tinker Tank would be quite useful as well.

**Comment by RossComputerGuy** [comment]
Is this why I can't create molds in 1.10 with FTB Beyond?

**Comment by KnightMiner** [comment]
> Is this why I can't create molds in 1.10 with FTB Beyond?

You could try reading the issue description. I have no clue why you think a feature to give drains a comparator output is related to you being able to create casts. And 1.10 is not supported.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. 1.16 will eventually have smeltery comparator support once I decide exactly what I want. Likely the drains will be in charge.
