### ISSUE TITLE
# Allows to repair your tool in a crafting grid, without tool station [default: true] B:easyToolRepair=false

### ISSUE THREAD

**Issue by Quizer9O8** [SlimeKnights/TinkersConstruct#2537]
The title says it all.
Bring back this wonderful config from the 1.7.10 TC please.

**Comment by bonii-xx** [comment]
No. Use a sharpening kit.

**Comment by Quizer9O8** [comment]
How does a sharpening kit helps me with repairing my tool?
Can you give me some information about that?

**Comment by ArukaAlter** [comment]
Sharpening Kit and the tool in the grid.

**Comment by Quizer9O8** [comment]
Thanks for shining some more light on my question.
Now I don't feel left in the dark. ;)

**Comment by bonii-xx** [comment]
We really need to get the book updated sometime. So much work, so little time.
