### ISSUE TITLE
Game Crash on Load

### ISSUE THREAD

**Issue by Gengi0927** [SlimeKnights/TinkersConstruct#2538]
I fixed the no-load problem, but, the game now crashes when i load the game, it crashes, I have provided a log, i am using forge to run minecraft 1.10.2, i have java, and mantle is present.

COPY AND PASTE IN SEARCHBAR: http://pastebin.com/eY5KLcuG

**Comment by KnightMiner** [comment]
You are running out of memory, modded Minecraft uses quite a bit more RAM than vanilla, so having more is expected. Allocate more RAM to Minecraft if possible (your log says you have just 1GB, normally 3 to 4 is expected for modded, if not more). If you cannot allocate enough memory, your only choice is to remove mods to reduce memory.

**Comment by Gengi0927** [comment]
Thank you, I just needed to know so i could fix it.
