### ISSUE TITLE
Table recipes do not load, causing errors in the log

### ISSUE THREAD

**Issue by 63502** [SlimeKnights/TinkersConstruct#2539]
For some reason, my 1.10.2 modded instance refuses to load with TiC installed. I believe that this problem may be related to #2519 , but I can't be sure, as I cannot actually code or understand the game output to any extent. the only thing I am certain of is that the behavior is exactly the same as described in #2519 . This issue does not cause a crash, so I have included the full uncut latest.log file from my current instance. I hope it provides enough information to find and/or fix the issue.

Java Version: Version 8 update 111 (build1.8.0_111-b14)
Forge Version: 12.18.2.2120
TiC Version: 2.5.6b
Game log: [latest.log](https://gist.github.com/63502/fef1217dc91ab6b10c88384709142683)

**Comment by TheQuantumGeneral** [comment]
Maybe related - https://github.com/mezz/JustEnoughItems/issues/570

**Comment by KnightMiner** [comment]
Does the problem persist if you remove JustEnoughResources? That is the only mod (other than JEI's tooltips) that has significant errors in the log.

**Comment by mezz** [comment]
@63502 You have old versions of JEI and JustEnoughResources. 
Try updating them both, it should cut down on the log spam and make solving this issue easier.

**Comment by Joshwoo70** [comment]
cross post from mezz:
Full gist log : https://gist.github.com/Joshwoo70/50e5b03d845e6bed7d3e1763dfce8487
shortened log : https://gist.github.com/Joshwoo70/7a2431045d35a119912e98ee18bf2729

**Comment by mezz** [comment]
`ShapedOreRecipeWrapper` is not in the API and has changed in a recent JEI version. TiC is trying to use it and crashes.

**Comment by 63502** [comment]
I updated to the latest JEI, and my game just straight up crashed. :P 
I think its something to do with the latest JEI not liking Just Enough Tooltips.

Crash log: [JEI/JET crash](https://gist.github.com/63502/85882d61a6d568fe1aa53827852a9704)

When I uninstalled JET and ran the game again, this is the log I got.

Game log: [latest.log](https://gist.github.com/63502/76abfb3ddb47c36b1191bfda6cb6d1fb)

**Comment by bonii-xx** [comment]
Don't use beta releases if you want stability, duh. Works fine with latest release version.

**Comment by Tsukiumy** [comment]
it seems that minetweaker(crafttweaker) is doing something, try without it, on my tests, when i removed the minetweaker it loaded instantly, even using all the betas and alphas from the mods

**Comment by mezz** [comment]
The crash was actually from JEI when it was being reloaded by Minetweaker.
With the latest JEI version, this TiC issue only results in the recipes missing from JEI, not a crash.

**Comment by 63502** [comment]
I tested the game with both the beta JEI and the stable build after removing crafttweaker. The game still freezes on the final forge loading screen for the latest JEI beta, but the stable release actually works and loads the game.

**Comment by 63502** [comment]
> `ShapedOreRecipeWrapper` is not in the API and has changed in a recent JEI version. TiC is trying to use it and crashes.
-mezz

I absolutely do not mean to sound pushy or rude, but Is it possible to fix this issue soon? Being unable to update past jei_1.10.2-3.12.8.323 is starting to affect my ability to update other mods (namely extra utils and Refined Storage atm, but others may begin to follow). It would be nice to not have to choose between using an outdated TiC and reverting to older versions of JEI and other mods, losing features and fixes there instead.

**Comment by KnightMiner** [comment]
The fix is WIP on Tinkers side, just waiting on me finding time to implement it. I was able to load up the latest JEI with Tinkers without a crash if you want to try that, you just cannot view the table recipes (simply missing)

**Comment by bonii-xx** [comment]
The fix will be in the next version we release. This is still some time off.

**Comment by 63502** [comment]
Ok, thats good to know.

**Comment by P3rf3ctXZer0** [comment]
https://gist.github.com/P3rf3ctXZer0/33db22d760035f611a6c95376eeea7b2

**Comment by KnightMiner** [comment]
I've changed the title of this issue to hopefully reduce duplicates, as what formerly caused a crash now just causes things to not load in later JEI versions
