### ISSUE TITLE
[BUG] Severe block lag with tinkers tools on nearby drying racks

### ISSUE THREAD

**Issue by M1nistry** [SlimeKnights/TinkersConstruct#2540]
Java: 1.8.0_112
Forge: 12.18.2.2120
Minecraft: 1.10.2
Tinkers: TConstruct-1.10.2-2.5.6b

Situation: Drying racks (any wood, about 5) with tinkers tools on them then try place blocks nearby quickly : FPS drops dramatically on each block place and break.

Reproduced in a new world with nothing but: Minecraft Coder Pack, Forge Mod Loader, Forge, Mantle and TC loaded.

**Comment by bonii-xx** [comment]
Addressed by 58d0c056639ab1c9452362ed3b7fcf19e09c1cef. This will hopefully greatly improve performance of the models overall.
