### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by Gengi0927** [SlimeKnights/TinkersConstruct#2542]
Thank you for helping with the space issue, however now the game truly crashes, i will provide a crash log.

Copy and Paste in Searchbar: http://pastebin.com/Su5FbSS1
WARNING: there is a lrge amount of text showing details of entity blocks, like sand falling in different places.

**Comment by ArukaAlter** [comment]
I would take it to the Chisel dev, Tinkers' is even mentioned in the stacktrace.

**Comment by Gengi0927** [comment]
thanks!

**Comment by Gengi0927** [comment]
I fixed the main crash issue, however, if i open my inventory, the game crashes again, i have another log .

LOG:http://pastebin.com/kfS3cCB1

**Comment by KnightMiner** [comment]
NEI's fault seems. Please, try the issue without Tinkers and with just Tinkers before reporting.

**Comment by Gengi0927** [comment]
Thank you, should i get rid of NEI, and then reinstall it? or just keep if deleted?

**Comment by KnightMiner** [comment]
I personally don't use NEI as JEI is enough of a recipe viewer, and the JEI dev gets a lot of issues caused by it reported, so personally I would just remove it.

If the crash still happens after doubling checking that you have compatible mod versions, it might be worth reporting to the current NEI devs.

**Comment by Gengi0927** [comment]
Well, i did remove NEI, but the game crashed again, so i just got rid of JEI too, and that fixed the problem entirely.

**Comment by KnightMiner** [comment]
If it's crashing with just JEI and no NEI, it's possible you don't have the latest version, as 3.13 made some API changes and I think a later version prevented the crash with the changes. If that does not work, 3.12.8 should work fine.

**Comment by Gengi0927** [comment]
Ok, thank you for being patient, and for helping so much!
