### ISSUE TITLE
[1.10.2 / Request] Hunger Persistence Upon Death

### ISSUE THREAD

**Issue by Endgineer** [SlimeKnights/TinkersConstruct#2545]
Upon moving into 1.10.2, my friends began to kill themselves to avoid the repercussions of "not eating", which basically removes purpose from all of those farms and stuff. This was a very decent side-feature of TConstruct in 1.7.10 and I would love to see it come back. :3

**Comment by LovelyFlare** [comment]
TiC does add foods, but it doesn't have anything to do with hunger.

**Comment by bookerthegeek** [comment]
Iguana Tinker Tweaks is the mod you are looking for.

**Comment by KnightMiner** [comment]
I recall this was in 1.7 Tinkers as one of mDiyos vanilla tweaks actually. Ido not know anything about the plans for this in TiC2, but I feel it is out of scope.

**Comment by Endgineer** [comment]
It was 100% in Tinkers Construct; looks like some peeps didn't spend time in Configs much. :3
The line was something like "KeepHungerOnDeath=true" and was also followed by a similar line that kept XP on death. It was 100% part of TCon and NOT Iguana Tweaks.

**Comment by bookerthegeek** [comment]
My apologies

**Comment by luckyu19** [comment]
Spice of Life already adds it (I assume you have added it since you said your modpack is based around food and farm, and considering one would kill themselves to reset hunger bar) so it's a bit redundant to add that config.

**Comment by LovelyFlare** [comment]
@Endgineer I never noticed that before.  Strange.

Anyhow, I don't believe it will be re-implemented in Tinkers' Construct 2 since it's more focused on tools and such rather than miscellaneous stuff such as altering gameplay configs.

**Comment by bonii-xx** [comment]
Indeed, TiC had that, mostly because diyo added a lot of nice things to it. However I feel this woudl be a good point to get it out of TiC into a separate thing. Imo that'd be a cood candidate for Quark. @Vazkii?

**Comment by Endgineer** [comment]
That would be a good addition into Quark indeed; if Vazkii sees fit. ;D

@luckyu19, I do have Spice of Life, but I'm 100% sure that mod does not add such a feature. The closest thing it does add is "B:food.history.persists.through.death=true", which I already have set to true. But if players keep killing themselves, there's really no point to food history anymore since they don't even get to eat at all (it's much easier to kill yourself than to manage multiple farms to counter the Spice of Life DR effect).

**Comment by luckyu19** [comment]
@Endgineer I thought that also keep hunger level, my bad

**Comment by KlutzLament** [comment]
It sounds like a good suggestion for Spice of Life.

**Comment by Endgineer** [comment]
Yep; I think I'll open up something on Spice of Life and see what happens.
