### ISSUE TITLE
Crash trying to render screen of Tool Station/Forge Gui

### ISSUE THREAD

**Issue by ryanl40** [SlimeKnights/TinkersConstruct#2546]
I spawned in a Traveller's Glove using command /give [username] 5287 1. When placing said item into the tool slot of Tool Station, game would shut down internal server and close. Resulting in a crash message of it cannot render screen. This also occurs when using Tool Forge as well. Was able to recreate multiple times in both without fail each time. Most recent crash report of each Gui is listed below. Any other information needed can be provided

Crash Report when using Tool Station: [crash-2016-11-07_15.29.24-client (TC Spawned TG in TS tool slot).txt](https://github.com/SlimeKnights/TinkersConstruct/files/576633/crash-2016-11-07_15.29.24-client.TC.Spawned.TG.in.TS.tool.slot.txt)
Crash Report when using Tool Forge: [crash-2016-11-07_15.29.24-client (TC Spawned TG in TF tool slot).txt](https://github.com/SlimeKnights/TinkersConstruct/files/576615/crash-2016-11-07_15.29.24-client.TC.Spawned.TG.in.TF.tool.slot.txt)

**Comment by ArukaAlter** [comment]
1.7 is no longer supported.

**Comment by KnightMiner** [comment]
All Tinkers tools and armor require specific NBT to function in 1.7.10, if it is missing the game will ultimately crash. Since 1.7.10 is no longer supported and this is fixed in 1.8+, this issue is no longer valid.

**Comment by bonii-xx** [comment]
Don't use /give.
