### ISSUE TITLE
Unknown crash when opening inventory with JEI installed

### ISSUE THREAD

**Issue by samiscool51** [SlimeKnights/TinkersConstruct#2549]
originally i thought it was a different mod but that mod dev said it was something to do with Tinkers
so i'm reporting it, i can't even play on my survival world because of this problem
tinkers version: 1.10.2-2.5.6b
Mantel version: 1.10.2-1.1.1
Jei version: 1.10.2-3.13.2.360
Forge version: 12.18.2.2122
crash log:  [crash-2016-11-08_14.16.45-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/577279/crash-2016-11-08_14.16.45-client.txt)
i hope you can fix it... please?....

**Comment by bonii-xx** [comment]
This has nothing to do with TiC at all. I'd start by removing optifine though.
