### ISSUE TITLE
Slime Islands

### ISSUE THREAD

**Issue by brodycas3** [SlimeKnights/TinkersConstruct#2550]
Slime islands seem to love spawning in other dimensions added by mods such as the aether. http://i.imgur.com/86pkP5W.png

**Comment by bonii-xx** [comment]
Slime islands spawn in all open world dimensions by default. You can blacklist dimensions in the config.

**Comment by brodycas3** [comment]
Yeah but the devs think it's ugly and say that doesn't belong there since it doesn't go with the lore of the aether. Can't you blacklist that dimension? 3 and 4? They really don't belong in that dimension. Please look over this again and think about it

**Comment by ArukaAlter** [comment]
Depending on the server, they may be on dimensions of different id.
And what about every other mod? There ought to be at least one wich uses ids 3 or 4.

**Comment by brodycas3** [comment]
I'm sorry, that's just what they told me it uses.

**Comment by LovelyFlare** [comment]
@brodycas3 "You can blacklist dimensions in the config."

**Comment by bonii-xx** [comment]
So go and blacklist it in the config....?
