### ISSUE TITLE
Another aether issue

### ISSUE THREAD

**Issue by brodycas3** [SlimeKnights/TinkersConstruct#2551]
When aether II rewrite (master branch) is installed alongside tinkers construct 2.5.5 or lower, several things don't work such as the stencil table, and the smeltery drain. It only happens when the aether is installed.

**Comment by bonii-xx** [comment]
Well, then tell the Aether guys not to break things? :I

**Comment by brodycas3** [comment]
here is a screenshot in case you don't understand what's going on. The aether dev says he has no idea whats breaking it.
http://i.imgur.com/vefmbQ8.gifv

**Comment by bonii-xx** [comment]
Check your log.

**Comment by brodycas3** [comment]
ill show you the same thing i showed them. http://i.imgur.com/pXcihMz.png

**Comment by brodycas3** [comment]
Its also confirmed by two other people.

**Comment by KnightMiner** [comment]
That is not helpful. Find the game log in your .minecraft folder and copy it onto a site like pastebin. The error you found is not something that can causes the GUI to stop working.

I recall a similar report related to this in the past that somehow involved a greedy capabilities attaching event, that could be the issue, but logs will definitely help more than randomly guessing.

**Comment by brodycas3** [comment]
Here are my log files.
[Logs.zip](https://github.com/SlimeKnights/TinkersConstruct/files/584018/Logs.zip)

**Comment by bonii-xx** [comment]
What happens if you remove liteloader?

**Comment by brodycas3** [comment]
Same result.

**Comment by brodycas3** [comment]
I know it's an issue with JUST aether and tinkers.

**Comment by bonii-xx** [comment]
Have you tried putting only Forge, TiC, Mantle and Aether2 into an instance and see if it still happens, to exclude weird cross-mod interactions from other mods? Just because it happens when you add either one of the two to the mix doesn't necessarily mean they're at fault.

**Comment by brodycas3** [comment]
Still broken with only those 3 mods

**Comment by bonii-xx** [comment]
Then there is some weird interaction that needs to be fixed on Aether2's side. The button just sends a packet, that can't really break on TiCs side. Maybe Aether2 does something to prevent the packet processing or screws with the buttons. Anyway, nothing we can do here.

**Comment by jellysquid3** [comment]
This is very likely an issue on our side (the Aether) and not with TCon.

**Comment by KnightMiner** [comment]
Closing as this appears to be just an issue with the Aether.
