### ISSUE TITLE
Remove internal JEI dependencies

### ISSUE THREAD

**Issue by bonii-xx** [SlimeKnights/TinkersConstruct#2553]
We currently have a dependency on the vanilla recipe implementation of JEI (for the tool tables). We gotta get rid of it and change the JEI dependency to the API only. Might also be worth to look into the sub-registry stuff for the tables since they're all the same.

JEI api dependency: https://github.com/mezz/JustEnoughItems/wiki/Getting-Started

Can you update the build.gradle and recipe @KnightMiner?

**Comment by KnightMiner** [comment]
Fixed in 55cff42 and 0a68f0c
