### ISSUE TITLE
[1.10.2] Shuriken small bug sound+ material repair missing ?

### ISSUE THREAD

**Issue by Gayanfalor** [SlimeKnights/TinkersConstruct#2555]
Hello guys,

i'm having a bug sound with my just crafted shurikens, when i throw them on something like stone it makes the sound like we are repairing something in the tool station, it seems to make the good sound for gravel dirt or wood things.

I have spotted to when looking into your weapon or tools there is no the repair material shown to see wich material we need to repair the tool.

Using java 8u111
forge 2122
Tconstruct 1.10.2-2.5.6

EDIT: I just reconected to the server and now its not doing it anymore :/, i'm dumb sorry for the post then ^^

**Comment by bonii-xx** [comment]
The sounds is a weird sync issue with servers. The repair material is fixed in the next version.
