### ISSUE TITLE
Height++/Width++

### ISSUE THREAD

**Issue by Sekkys** [SlimeKnights/TinkersConstruct#2557]
Not exactly sure when it happened, but I assume the last update, but my Height++/Width++ Endstone Pick stopped mining a 3x3 and now only mines a 2x2. Not sure if intended or not, but it kind of bums me out a bit since my pickaxe perfectly upgraded to a huge mining speed because of Alien, and now it's kind of stuck with two almost useless modifiers on it

**Comment by bonii-xx** [comment]
Width++/Height++ Picks always only mined 2x2, 3x3 is a hammer. It never was possible to get them to mine 3x3.
