### ISSUE TITLE
Crash with Tinker

### ISSUE THREAD

**Issue by TheDeadLotus** [SlimeKnights/TinkersConstruct#2558]
I've tried everything except uninstalling Tinker. 

Forge, Optifine, and all of the mods are up to date. The crash started after playing for about 5 hours today. Now when ever I load my game, it crashes with the error below.

Can you take a look and see if it's something that I missed? 

Thank you very much!

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.2.334.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.3.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 11/12/16 4:36 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Don't know how to add class net.silentchaos512.gems.entity.packet.EntityPacketAttack!
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:632)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:371)
	at net.minecraft.entity.EntityTrackerEntry.func_73125_b(EntityTrackerEntry.java:471)
	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:134)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 822814240 bytes (784 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.2.2125 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2125.jar) 
	UCHIJAAAA	Forge{12.18.2.2125} [Minecraft Forge] (forge-1.10.2-12.18.2.2125.jar) 
	UCHIJAAAA	Baubles{1.3.2} [Baubles] (Baubles-1.10.2-1.3.2.jar) 
	UCHIJAAAA	baublesstuff{2.0.11} [Baubles Stuff] ([1.10.2] baublesstuff-2.0.11.jar) 
	UCHIJAAAA	BaublesHud{3.2.0} [Baubles-Hud] (BaublesHud-1.10.2-3.2.0.jar) 
	UCHIJAAAA	bookshelf{1.4.2.334} [Bookshelf] (Bookshelf-1.10.2-1.4.2.334.jar) 
	UCHIJAAAA	JEI{3.12.8.323} [Just Enough Items] (jei_1.10.2-3.12.8.323.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCHIJAAAA	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJAAAA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJAAAA	emeraldobsidianmod{1.5} [Emerald & Obsidian tools/armor mod] (emeraldobsidianmod-1.5-1.10.2.jar) 
	UCHIJAAAA	enchiridion{3.1.12} [Enchiridion] (Enchiridion-1.10.2-3.1.12.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	hempfarmer{1.7.2} [HempFarmer] (hempfarmer-1.9.4-1.10.2-1.7.3.jar) 
	UCHIJAAAA	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHIJAAAA	jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJAAAA	MultiPageChest{1.7.0} [Multi Page Chest] (MultiPageChest-1.10-1.7.0.jar) 
	UCHIJAAAA	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	UCHIJAAAA	nmsot{1.1.7-mc[1.9.4-1.10.2]} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.7-mc[1.9.4-1.10.2].jar) 
	UCHIJAAAA	powerinventory{2.3.0} [Overpowered Inventory] (OverpoweredInventory-1.10.2-2.3.0.jar) 
	UCHIJAAAA	getalltheseeds{1.9.4-1.10.2a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds! 1.9.4-1.10.2a.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.585} [Reliquary] (Reliquary-1.10.2-1.3.3.585.jar) 
	UCHIJAAAA	Schematica{1.7.8.152} [Schematica] (Schematica-1.10.2-1.7.8.152-universal.jar) 
	UCHIJAAAA	shetiphiancore{3.3.3} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.3.jar) 
	UCHIJAAAA	SilentLib{1.0.12} [Silent Lib] (SilentLib-1.9.4-1.0.12-20.jar) 
	UCHIJAAAA	SilentGems{2.1.1} [Silent's Gems] (SilentsGems-1.10.2-2.1.1-77.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAA	terraqueous{1.2.8} [Terraqueous] (terraqueous-1.10.0-1.2.8.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJAAAA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.4-mf-1.10.2-12.18.1.2026.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.2.334.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.3.jar)
  shetiphian.core.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['The_Dead_Lotus'/242, l='Dead Lotus 2.0', x=-616.84, y=69.00, z=-1314.51]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ArukaAlter** [comment]
Just take a brief look at the start of the log, then report to the right place.

**Comment by TheDeadLotus** [comment]
Yeah, I fixed it. The newest version of Forge is the culprit. I reverted
back to the one before and it fixed the problem.
