### ISSUE TITLE
Game Crashing (mod to mod compatibility)

### ISSUE THREAD

**Issue by jsanders91** [SlimeKnights/TinkersConstruct#2559]
[Minecraft (from tinkers construct) crash-2016-11-12_18.18.56-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/587571/Minecraft.from.tinkers.construct.crash-2016-11-12_18.18.56-client.txt)

**Comment by ArukaAlter** [comment]
Reliquary is trying to load a non existent field, not directly caused by Tinkers'.

**Comment by bonii-xx** [comment]
Update Reliquary
