### ISSUE TITLE
Luck III<Fortune III (Potential issue, or just dumb RNG)

### ISSUE THREAD

**Issue by luckyu19** [SlimeKnights/TinkersConstruct#2560]
I thought my Luck III pickaxe wasn't as good as my Fortune III pickaxe, so I did some mythbusting, and it turns out that Fortune III diamond pickaxe is giving me more ore drops than my Luck III cobalt pickaxe (all test items were pulled from creative, 300 ores were mined by both pickaxe, the remaining modifier slot was occupied with redstone, efficiency V on the diamond pick). Test was not conducted with Fortune III+Autosmelt pickaxe, do tell me if said interaction was taken into account during the creation of Luck modifier.

**Comment by bonii-xx** [comment]
No, you're just having bad RNG.
