### ISSUE TITLE
[1.10.2] Client crash IndexOutOfBoundsException RenderUtil.putTexturedQuad

### ISSUE THREAD

**Issue by ProsperCraft** [SlimeKnights/TinkersConstruct#2561]
https://gist.github.com/ProsperCraft/7827fd233b23fe5fef515eadc2f6a3a4

I was flying through a town, and the client crashed.

**Comment by bonii-xx** [comment]
Weird crash, but nothing suspicious there. Can you reproduce it? The rendering code of the smeltery doesn't have anything that could cause this by itself, it might've been a hickup in MC.

**Comment by ProsperCraft** [comment]
I have moved around in the town and have not been able to reproduce it, will let you know if it happens again.

**Comment by bonii-xx** [comment]
Open a new ticket if you can manage to reproduce it.
