### ISSUE TITLE
Can't add obsidian plates modfier to any tool

### ISSUE THREAD

**Issue by dabigmoose** [SlimeKnights/TinkersConstruct#2562]
So I had a problem with latest version 2.5.6b where when I make any tool pickaxe, hatchet, lumber axe I can't add large obsidian plates despite have 3 modifiers available. Originally I was in Hermitpack, but I have tried it in a couple of other packs that have 2.5.6b and same in those packs. Single player or Multiplayer.

**Comment by bonii-xx** [comment]
There's a book. The book contains the modifiers. The modifiers tell you how to apply them. Read up ;o
