### ISSUE TITLE
Crash Caused by Tconstruct

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SlimeKnights/TinkersConstruct#2566]
Crashlog
https://gist.github.com/P3rf3ctXZer0/fdcb3da10774dc8db76b52d67791d31a

Full Log
https://gist.github.com/P3rf3ctXZer0/8bdb38a694c178f447ceadb77f4417aa

**Comment by LovelyFlare** [comment]
Can you reproduce it without OptiFine?

**Comment by P3rf3ctXZer0** [comment]
I can check ... I don't plan on not using Optifine though.

**Comment by bonii-xx** [comment]
#2569

**Comment by darkhax** [comment]
The crash happens when you look at the tooltip, so I can't really tell what material it is. It looks like just the black outline of a tool part. Not really sure how players are getting them either.
