### ISSUE TITLE
Shuriken has "random" sound effects

### ISSUE THREAD

**Issue by Jomik** [SlimeKnights/TinkersConstruct#2567]
After removing ExtremeReactors and ZeroCore, and adding DeepResonance, ElecCore and MjctyLib our shurikens on our server now make "random" noises, including the "sawing" noise made when crafting, and also the "metal hit" noise when using an anvil. 
Seems like sound IDs got messed up somehow?
I believe I can fix this by creating a new world, but we'd lose all our progress, and it seems to be something that should be guarded against anyhow?

**Comment by bonii-xx** [comment]
It's a server sync issue. Restart the client and reconnect, see if it still happens.

**Comment by Jomik** [comment]
Server and client has both been restarted, still happens. :(

**Comment by Jomik** [comment]
forge-1.10.2-12.18.2.2122-universal
TConstruct-1.10.2-2.5.6b
Mantle-1.10.2-1.1.1

**Comment by KnightMiner** [comment]
Does this happen on a fresh world? Additionally, does this happen with just Tinkers, Mantle, and Forge?

**Comment by KnightMiner** [comment]
Does this still happen on the latest Forge and Tinkers? I read of a couple Forge commits fixing a similar issue.

**Comment by Jomik** [comment]
Still happens on forge-1.10.2-12.18.3.2185-universal and TConstruct-1.10.2-2.6.0
Haven't updated since. What forge ver?

**Comment by KnightMiner** [comment]
By latest, I mean 1.12 version of Minecraft. 1.10 is no longer supported.

**Comment by KnightMiner** [comment]
Closing for lack of response, as its been about a year and no one has reproduced it in 1.12.
