### ISSUE TITLE
Mending moss auto-repair doesn't work (with pickaxe)

### ISSUE THREAD

**Issue by mvlabat** [SlimeKnights/TinkersConstruct#2568]
Greetings!
I have a pickaxe (obsidian head, iron binding, bronze tool rod) with the following modifiers:
`Luck I`
`Mending moss`

I'm not sure, maybe I've obtained `Luck (0)` before `Mending moss` and `Luck I` after `Mending moss`, if it can matter. I also have TiC Tweaks mode installed.

I have also an obsidian longsword with Mending moss in the inventory too, but this tool is repairing and the pickaxe does not.
I'm sure the pickaxe is equipped, it has something about 300/1000 of XP, I tried to throw it away and pick up back (I've also died), but nothing have helped: it doesn't repair at all.

**Comment by bonii-xx** [comment]
You can check the XP saved in the tool in a tool station, make sure it actually has XP stored. If it has xp and is damaged, it'll repair when it's somewhere in your hotbar.

**Comment by mvlabat** [comment]
@bonii-xx, yeah, I looked at TiC Tweaks XP.. So actually I've managed to get some xp to my pickaxe. I had to swap it with my sword, so pickaxe appeared in the first slot in the hotbar and the sword in the second one. However it's unclear how tools get XP if they are both in my hotbar. As a player I can say that the most intuitive way would be to divide experience between all the tools in the hotbar.

**Comment by ArukaAlter** [comment]
The tool you are holding is the one wich gets the xp.

**Comment by mvlabat** [comment]
Oh, so simple.. It seemed to me it didn't work this way. Ok, sorry for posting yet another one issue about "not working" mending moss. I think it's solved now
