### ISSUE TITLE
Tool Forge Missing Recipe

### ISSUE THREAD

**Issue by RobertLSnead** [SlimeKnights/TinkersConstruct#2574]
I was unable to craft the Tool Forge as normal, there is also no recipe in jei/nei!
Did the recipe change?

ver.TConstruct-1.10.2-2.5.6b

**Comment by KnightMiner** [comment]
Dupe of #2539. Recipe has not changed, our neighborhood I teg ration just broke and we have enough not had time to release a fix. The recipe is still three seared blocks on top, 4 metal blocks on the sidesame, and a tool station in the middle
