### ISSUE TITLE
[Suggestion] Allow liquid lookups in JEI from gui tanks

### ISSUE THREAD

**Issue by mezz** [SlimeKnights/TinkersConstruct#2576]
A relatively recent JEI API addition allows mods to define what ingredient is under the mouse. You can use this to let JEI know when there is a tank of some fluid under the mouse, for recipe lookups. It is defined in `IAdvancedGuiHandler`.

I think it would be great to look up uses of fluids in the smeltery gui, for example.

Forestry's implementation: https://github.com/ForestryMC/ForestryMC/commit/2ae52451b23bc01550939cd1f9603de225fe7c3d
EnderIO's implementation:  https://github.com/SleepyTrousers/EnderIO/commit/853e62fa917ffd39fc249d9757ea946920c8de5a

**Comment by KnightMiner** [comment]
I'll try and add this when I get around to fixing our table wrapper

**Comment by KnightMiner** [comment]
Added in 0a68f0c
