### ISSUE TITLE
Tinkers not reading mantle 

### ISSUE THREAD

**Issue by darkensoles** [SlimeKnights/TinkersConstruct#2577]
ok do i downloaded tinkers and mantle for 1.10.2 and when i launch forge it complains about not having mantle any help?

**Comment by ArukaAlter** [comment]
Make sure you grabbed the latest or the recommended versions of both at Curse.

**Comment by darkensoles** [comment]
um i dont use curse i manually do it... any other way to fix it i grabbed them from minecraft yard

**Comment by ArukaAlter** [comment]
CurseForge is the official site for most of the mods, the one you mentioned is kinda suspicious.

**Comment by darkensoles** [comment]
oh ok 
well am i able to avoid curse? ive had a lot of isses with it in the past i dont like it.

**Comment by ArukaAlter** [comment]
https://minecraft.curseforge.com/projects/tinkers-construct/files
https://minecraft.curseforge.com/projects/mantle/files
It's not that hard.

**Comment by darkensoles** [comment]
ok

**Comment by darkensoles** [comment]
thanks i thought i needed the launcher
