### ISSUE TITLE
Tinkers related crash on launch

### ISSUE THREAD

**Issue by Oharaicaine** [SlimeKnights/TinkersConstruct#2578]
http://pastebin.com/TRFzw0Bk

**Comment by KnightMiner** [comment]
This is BluSunrize/ImmersiveEngineering#1697. Essentially, @BluSunrize released a build for Immersive Engineering that references some unreleased code from the next release of Tinkers Construct. Either downgrade to Immersive Engineering 0.10-48 or wait for the next Tinkers release with the bows (which should be soon).
