### ISSUE TITLE
[BUG] Crash bug in while in smeltery controller

### ISSUE THREAD

**Issue by koyetsu** [SlimeKnights/TinkersConstruct#2580]
Ran into an apparent crash bug last night.
Situation: 
Seared stone in smeltery. Melted iron and copper. Tried to change from seared stone to iron for use, Crash.
Multiple crash and multiple client experienced. 
Work around:
Pour seared stone into basin, break and then get all the metals out (not sure if getting the metals out is needed. but once i got the smeltery empty i was able to use it as normal.)

Tinkers version: 1.10.2-2.5.6b
Pack: Direwolf20 1.10 pack

**Comment by ArukaAlter** [comment]
No log, no confirmation.

**Comment by HyperBlueCore** [comment]
http://pastebin.com/xx0nS9ZE
I got same issue here is my log
http://pastebin.com/xx0nS9ZE

**Comment by KnightMiner** [comment]
Does this happen with just Tinkers Construct and Mantle? Specifically, does it still happen without Optifine?

**Comment by HyperBlueCore** [comment]
the mudpack crashes without optifine that's what keeps it alive

**Comment by KnightMiner** [comment]
That does not answer the question. Remove ALL other mods and it shouldn't crash, if it still does post the report.

**Comment by HyperBlueCore** [comment]
it does with the server but no issue if singleplayer it also add more issues with missing molten metals form other mods but whatever it even shows that the error is from TiC

**Comment by bonii-xx** [comment]
As I've already told you [in your closed issue](https://github.com/SlimeKnights/TinkersConstruct/issues/2588), your log has absolutely nothing to do with TiC.

**Comment by HyperBlueCore** [comment]
ok sorry I'm new to using GitHub so I was unable to find my thread
