### ISSUE TITLE
Tool Forge crash if we leave an item on it and try to get back on it

### ISSUE THREAD

**Issue by mcdodge34** [SlimeKnights/TinkersConstruct#2581]
Here's the crash log, latest version of everything including Forge 2151 it happens on server, the client crash and I can get back on server fine if I break the tool forge, I get the item back and can use the forge back without issues, except if I leave something on it.

http://pastebin.com/tWgirWpa

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.
