### ISSUE TITLE
quick question <3

### ISSUE THREAD

**Issue by kurokuno** [SlimeKnights/TinkersConstruct#2582]
so i have been building off the git for some time using the gradlew build script but little bit back week or 2 ago it started refusing to build the current git not sure if that's on my end or your end just asking so i can work out if i need to re-do all of my git installs as i have already cleaned the caches and all of the dependency with no luck ty for any answers and sorry to bug you with a silly question like this here

**Comment by bonii-xx** [comment]
The problem is on your side.
