### ISSUE TITLE
[1.10.2] "No Such Method: BowMaterialsStats" 

### ISSUE THREAD

**Issue by Drakoflame** [SlimeKnights/TinkersConstruct#2584]
I'm not entirely sure whats happening, or what I'm doing wrong, all that I know, is that it has something to do with "bow materials". here's a copy of the crash log, if someone could let me know what I did wrong and if/how I can fix it! [s]http://pastebin.com/NdT6qghw [/s] nvm, that was an old version, updated to a newer one and still got the same crash http://pastebin.com/ZHBarMij

**Comment by KnightMiner** [comment]
BluSunrize/ImmersiveEngineering#1697 and #2578

**Comment by Drakoflame** [comment]
thanks @KnightMiner wasn't aware that it was an IE issue
