### ISSUE TITLE
Crash on modpack load

### ISSUE THREAD

**Issue by the-creamster** [SlimeKnights/TinkersConstruct#2585]
Ok to begin with i'm getting the following crashes at different stages of pack loading(normally around stage 2/3) with my one which is tweaked off the previous working build. The strange thing about it is that i can launch the pack by the other admin which has identical mod versions and it doesn't crash on me.

The order in which they were crashing seem to correspond to the mod loading order:

Draconic Evolution
Ender Storage
Immersive Engineering
Translocators
CodeChicken Lib
Crash Reports
Draconic Evolution: https://gist.github.com/the-creamster/f61988d0bd1ec74a0d7f3012649cce99
CodeChicken Lib: https://gist.github.com/the-creamster/125991568c9fa3cf3681ee58a470d777
Translocators: https://gist.github.com/the-creamster/2cb3fe5103e13f50497319952dc749fb
Immersive Engineering: https://gist.github.com/the-creamster/f168aba00ebe944ef86645abd0768ee4
Ender Storage: https://gist.github.com/the-creamster/da52b6bbeb67637a62ecf4b27a8e7c6f

Any thoughts as to why my tweaked pack crashes and the other one with identical version isn't???
Cheers, The_Creamster.

**Comment by the-creamster** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1706
as per the latest dev comment

**Comment by BluSunrize** [comment]
TCon is not involved in your crashes, reporting it here is pointless. The issue is that you are using IE Build 49 instead of 50. No point to report it here.
