### ISSUE TITLE
Shift-clicking ores into the smeltery resets melting progress of equal ores

### ISSUE THREAD

**Issue by eswortmaler** [SlimeKnights/TinkersConstruct#2586]
using TinkersConstruct version 1.10.2-2.5.6b.jenkins424 in the Direwolf20 1.10 modpack.
when an ore is in the progress of smelting in the smeltery (for example ardite ore), after shift-clicking more of the same ore into the smeltery, the smelting progress of all ores equal to the one shift-clicked in (all other ardite ores) gets reset. this doesn't happen to different ores (in the example given cobalt would not be reset) and drag and drop also doesn't seem to reset the progress (dragging a piece of ardite into the smeltery would not reset the smelting progress of other ardite ores)

**Comment by TH3GOD88** [comment]
I have had it do it with more than one type of ore inside it. Like say I put iron in and then shift+clicked in copper or tin; it resets everything.

**Comment by piks** [comment]
This issue still exists in 2.7.0.26

**Comment by KnightMiner** [comment]
Reopening since there were a couple of reports about this

**Comment by KnightMiner** [comment]
I cannot reproduce this in recent versions, and have not heard anything about it still happening. Going to close.

If it happens again in a modern version comment and we can look at it again.
