### ISSUE TITLE
Crafting Harmonics compatibility - allow forcing tool stats to be recalculated, sharpening kits.

### ISSUE THREAD

**Issue by MaciejJaromin** [SlimeKnights/TinkersConstruct#2587]
Minecraft version: 1.10.2
TC version: 2.5.6b
Forge version: 12.18.2.2151

Crafting Harmonics is a MineTweaker-style mod that allows recipe tweaking and similar customization. It supports modifying Tinkers' Construct recipes and material properties. However, there are currently two problems with using Crafting Harmonics with Tinkers' Construct.
First, CH supports modifying recipes dynamically, with sets of changes tied to the game difficulty and an option to invoke a set of changes using a command. However, any changes to TC material properties won't apply to already made tools until a part is swapped out. This is particularly noticable when loading a game - tools revert to unmodified stats because they're calculated before Crafting Harmonics changes are applied. This could be fixed by implementing a command to recalculate tool stats that could be called by CH or some similar solution.

The other issue is with sharpening kits - the Fortified modifier seems to apply the original harvest level of the material, rather than the modified one.

**Comment by bonii-xx** [comment]
We support changes to material via the [Register Events](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/events/MaterialEvent.java#L45), which you're obviously not using, or the Fortify Modifier would work correctly.

We wont support any other way of changing things or changes at runtime.
