### ISSUE TITLE
Player can trick the furnace into cooking stacks of 16 as fast as a stack of 1

### ISSUE THREAD

**Issue by codetaylor** [SlimeKnights/TinkersConstruct#2591]
Forge: forge-12.18.2.2123
TiCon: TConstruct-1.10.2-25.6b

If one item is placed in a furnace slot, it will smelt faster than if sixteen items are placed in a furnace slot. That behavior is expected.

If one item is placed in a furnace slot, then the remaining fifteen items are placed in the same furnace slot, it will smelt all sixteen items at the same speed it would smelt one item. That behavior feels like a bug.

**Comment by LovelyFlare** [comment]
Sounds like it does an item count check only when it starts to smelt it.

**Comment by codetaylor** [comment]
Yeah, it looks like it does use less fuel as well as cooking faster.

**Comment by bonii-xx** [comment]
Vanilla sometimes doesn't update when the stacksize changes. Vanilla bug sadly, maybe we can work around it.

**Comment by KnightMiner** [comment]
Fixed alongside #3733 with f5d7b2a, technically the same issue.
