### ISSUE TITLE
any idea whats causing this error ?

### ISSUE THREAD

**Issue by blacksblade** [SlimeKnights/TinkersConstruct#2592]
http://imgur.com/a/NbrLT

**Comment by LovelyFlare** [comment]
Is Java in the path?  Did you give it enough RAM to compile etc.?

**Comment by LovelyFlare** [comment]
It doesn't look like you coded whatever you're doing correctly.  This doesn't give much information other than that.

**Comment by bonii-xx** [comment]
From the looks of it? Hard to tell. Your environment isn't set up correctly probably.

**Comment by blacksblade** [comment]
hmm thats really odd i followed the same lines as i would with other gits and this is un-edited straight clone i was trying to build for testing on another project

**Comment by bonii-xx** [comment]
Tried a fresh clean install?

**Comment by blacksblade** [comment]
was a clean install everything even tried it on a second pc same result

**Comment by bonii-xx** [comment]
I assume you are using Java 8?

**Comment by blacksblade** [comment]
my current JAVA_HOME is jdk 1.8.0_25

**Comment by bonii-xx** [comment]
Upload the full gradle log somewhere

**Comment by blacksblade** [comment]
http://pastebin.com/a4Yhq6NC there we go mr boni =D

**Comment by bonii-xx** [comment]
Are you using openjdk by chance? It looks like your compiler simply sucks at resolving generics.

**Comment by blacksblade** [comment]
and boni with the gold medal ty <3 it was indeed a change in java that was messing with it updating to the latest jdk fixed it my own stupid fault the one thing that skipped my mind <3
