### ISSUE TITLE
[Suggestion] Implement Drain substitute for the Seared furnace

### ISSUE THREAD

**Issue by patr4547** [SlimeKnights/TinkersConstruct#2596]
The Seared furnace can be impossible to automate with many mods without the existance of a Drain block for the Seared furnace. The drain could be made compatible with the Seared furnace.

**Comment by KnightMiner** [comment]
The seared furnace is not designed to be automated. It is designed to allow the player to easily smelt a lot of items in a non-automated system. If you want to automate it, vanilla furnaces are so much easier to do so.
