### ISSUE TITLE
Mod Compatibility: Ecological

### ISSUE THREAD

**Issue by Kostronor** [SlimeKnights/TinkersConstruct#2600]
I'm a developer from tge minecolonies mod, trying to get our citizens to support Tinkers Construct tools. 

We found that when a Tool with the ecological trait is in a citizen inventory, it won't regenerate. Is there something we can do to allow that to happen? 

Also what do we have to do so tinkers tool leveling gets called when a tool is used? Do we have to fake a player or can we avoid that? 

Regards, 
Kostronor

**Comment by bonii-xx** [comment]
Call onUpdate on the itemstacks, like the player does. If you want player behaviour you should use a (fake) player. However I think tool leveling has a bug with fake players currently.
