### ISSUE TITLE
[Request] Melting ores generate small amount of seared stone

### ISSUE THREAD

**Issue by Waisse** [SlimeKnights/TinkersConstruct#2601]
I'm currently making a pack and minetweaking it to make tiers of ore processing. The reason behind my request is to give players incentive to step up their ore processing by making the smeltery harder to automate.

I'm just proposing this as an option to the config file.

**Comment by bonii-xx** [comment]
No, I've specifically decided against allowing melting into multiple liquids when reimplementing the smeltery.
