### ISSUE TITLE
[1.10.2-2.6.0] All Cobalt bow types have slower listed default attack speed

### ISSUE THREAD

**Issue by VallenFrostweaver** [SlimeKnights/TinkersConstruct#2602]
In the tool tips of JEI only Cobalt bows (and both short, long, & cross) have a higher default draw speed listing in the main hand. Short/Long is 3.3 (vs all others 3) and Cross is 2.2 (vs all others 2). This may be as intended but I see no documentation listing it.

**Comment by bonii-xx** [comment]
That's faster, not slower, and it's because of cobalts trait. If you're talking about the displayed melee attack speed.

**Comment by VallenFrostweaver** [comment]
Ok, Just making sure it wasn't entered in error since they all have the same default speed. Is this the effect of it being Lightweight I take it since it can't really get faster with repetition like a melee weapon?

**Comment by bonii-xx** [comment]
Yes. It's actually weird that it's not used like a melee weapon though, when rightclicking. That should probably be fixed. I wonder if the damage is correct.
