### ISSUE TITLE
Modifiers are limited (1.10.2)

### ISSUE THREAD

**Issue by GhostlyGamer17** [SlimeKnights/TinkersConstruct#2604]
There is NO WAY to get new modifiers besides losing all your durability. BRING BACK THE LEVELING SYSTEM. OR ANYTHING TO GET MODS BESIDE CHANGING YOUR TOOLS TO PAPER.

**Comment by GhostlyGamer17** [comment]
ITS STUPID really

WAKE UP DEVELOPERS!

**Comment by KnightMiner** [comment]
No

**Comment by mezz** [comment]
the developers ARE ASLEEP to the TRUTH about MODIFIERS
oh wait
https://minecraft.curseforge.com/projects/tinkers-tool-leveling
