### ISSUE TITLE
When installed SpongeForge , EFLN does not work

### ISSUE THREAD

**Issue by flier268** [SlimeKnights/TinkersConstruct#2605]
Forge  : 1.10.2-12.18.2.2151
MC : 1.10.2
SpongeForge : 1.10.2-2123

EFLN will break block ,but i can't get any block

**Comment by bonii-xx** [comment]
Out of curiousity, does the lumber axe work? Also please report this to spongeforge, it's some interaction with how they handle things.. the question just is which part exactly.

**Comment by flier268** [comment]
Yes,the lumber axe work,but EFLN can not work.

**Comment by KnightMiner** [comment]
Closing as this issue is ancient and most likely fixed. Feel free to comment if it happens in the latest Sponge Forge, but I'm pretty sure I remember a similar issue being fixed.
