### ISSUE TITLE
[1.10.2 v2.6.0] Immersive Engineering (v0.10-50) Electrum Short Bow glitch

### ISSUE THREAD

**Issue by VallenFrostweaver** [SlimeKnights/TinkersConstruct#2606]
The Electrum Shortbow (either or both limbs can be electrum) has a "stutter" animation when firing. I can't get any other bow type to reproduce this. When pulling back the string on the shortbow it starts the animation then starts again about 1/4 way through the animation.

**Comment by bonii-xx** [comment]
That's a really hard to fix thing due to how Minecraft updates its state. I'm not sure if it's even possible.

**Comment by VallenFrostweaver** [comment]
Something I noticed (if it helps at all) is that this seems to be caused by the "charge up" of the shocking ability.  Even once the electrum cross/short/long-bows are charged up it still does it though. Can the charging of the shocking ability be turned off while the r+click is being held or after the charge is achieved?

**Comment by KnightMiner** [comment]
Electrum does not exist in 1.16 right now, but I have a good idea of how to deal with this if we bring it back. Fixing on 1.12 is more effort than I have time to fix.
