### ISSUE TITLE
[2.6.0] Issue Reports

### ISSUE THREAD

**Issue by Elvarion** [SlimeKnights/TinkersConstruct#2608]
TConstruct-1.10.2-2.6.0
Mantle-1.10.2-1.1.2

- Shortbow,  Longbow, Arrow, Crossbow & Bolt have their Unlocalized names in the Tool Forge.
Bolt has its component names Unlocalized in the Tool Forge.

- _Bolts not always consuming ammo when fired from Crossbow if spawned in from JEI_(Not really important, just to notify about it)

- Picture for Hemp Fiber is basically just a pixel (Immersive Engineering Bowstring)

- Page 118 is empty

- Strange sound when breaking blocks while dual wielding Pick+Shovel (Pick must be in Shield slot)

- Most End tools are listed twice in JEI (Might be an issue with JEI since  they are only listed once in the creative menu)

- Adding Cobalt binding / tool rod to a crossbow will display "Bonus speed +10%" but will not decrease drawspeed

- Crossbow made out of End Material will start loading, then the loading animation restarts. The crossbow will still load given enough time to do so. Seems to only happen if the Limb is made out of End Material.

---

This is more of a request since its an issue with Vanilla Minecraft and Mojang wont really fix it since its only present when mods are added that has values over 1000.
Items that has over 1000 durability will display NBSP instead of its localized symbol such as , or a space depending on language localization. 

![](https://i.gyazo.com/7cfe5975d03877a084cbf7348cb768cd.png)

EnderIO has made a workaround for this when they fixed the French localization and that fixed the Swedish version also. Not sure if its a easy fix or not, but it would be awesome to get rid of all these NBSP's that some mods have.
Dont know if linking to other githubs are appreciated, but going to the github for EnderIO and just checking the most recent issues there is one called "NBSP Issue" where its talked about and that they made their own fix for it.

---
Also thanks for adding bows & crossbows back to the mod, they have been missed! :)

**Comment by bonii-xx** [comment]
> Bolts not always consuming ammo when fired from Crossbow if spawned in from JEI(Not really important, just to notify about it)

They do, you sure you weren't in creative or were using bolts with traits/modifiers preventing it?

> Blasting Modifiers description is somewhat confusing. Can be confused that it increases tool speed for all blocks. When it really only increases harvest speed for uneffective blocks. (Unless it is ment to increase overall tool speed, then it does not do that)

But it does, in fact it normalizes breakspeed for ALL blocks. Try breaking some obsidian then you'll see what I mean.

**Comment by Elvarion** [comment]
> But it does, in fact it normalizes breakspeed for ALL blocks. Try breaking some obsidian then you'll see what I mean.
I withdraw my report about the break speed. Tried breaking obsidian with max Blasting. It sure does increase the speed! Should have done more testing.
