### ISSUE TITLE
Minecraft Not working

### ISSUE THREAD

**Issue by LegomasterWill** [SlimeKnights/TinkersConstruct#2609]
i open minecraft with the latest 1.7.10 version of this but it keeps saying i need a different version of mantle and i don't know what that even is

**Comment by LovelyFlare** [comment]
1.7.10 is no longer supported.  Mantle is the dependency mod that Tinkers' Construct requires to run.

**Comment by KnightMiner** [comment]
Install the latest 1.7 Mantle.

**Comment by bonii-xx** [comment]
https://mods.curse.com/mc-mods/minecraft/mantle
