### ISSUE TITLE
Chests in Crafting Station Render as Broken Texture

### ISSUE THREAD

**Issue by Darkosto** [SlimeKnights/TinkersConstruct#2612]
Hello,

When placing a chest inside the crafting station show as a broken texture when rendering in the world:

https://sx.artdude.uk/hotlink-ok/darkosto/1Ijr-e6d31-1480791629.png

TC Version: 2.6.0
Mantle Version: 1.1.2
MC Version: 1.10.2
Forge: 2171

Thanks for checking this out!
Darkosto

**Comment by ArukaAlter** [comment]
Search for closed issues, this has been reported several times, blame Mojang.

**Comment by Darkosto** [comment]
Okay, then can we have an option to disable item rendering for crafting stations only?

**Comment by ArukaAlter** [comment]
There's no much sense in disabling rendering only in the table, really the only model broken is of the chest.

**Comment by Darkosto** [comment]
That's not the only reason I'd like to disable it, but I'd rather not bring in other issues to this thread.

**Comment by KnightMiner** [comment]
The option to disable rendering is simply a work around in case some mod messes up rendering, thus is not provided on a per block basis. Use a vanilla crafting table if you want to not see items on top.

**Comment by LovelyFlare** [comment]
Set "B:renderInventoryInWorld=false" in the config file.

**Comment by Xuerian** [comment]
"B:renderInventoryInWorld=false" is nice, but only the tool bench causes massive block update lag in my experience, it would be nice to be able to disable separately.

I've had to resort to using vanilla crafting tables or similar if I still want the other items that option changes to work.

**Comment by Darkosto** [comment]
Yeah @Xuerian That's what I've been experiencing in SkyFactory and was hoping to turn that single feature off since the "B:renderInventoryInWorld=false" disables everything including the smeltery pouring.

**Comment by Xuerian** [comment]
@Darkosto Not to hijack this thread but since I can't find PMs on here, you can get around it by using OptiFine, the spikes are a lot smoother. Normal caveats about using OptiFine and reporting bugs with it apply.

Also Portable Crafting is great.

But yeah, the lag spikes from the tool bench/crafting bench are pretty terrible.
