### ISSUE TITLE
Recipe Re-Enable

### ISSUE THREAD

**Issue by EZEILL** [SlimeKnights/TinkersConstruct#2613]
Using most recent versions of everything in 1.10.2
How do I make it so that when I install Tinkers Construct it doesn't disable vanilla and other mod crafting recipes for weapons and tools? I went through my mods and it is specifically Tinkers Mods that are causing this issue to happen.
![2016-12-03_14 15 11](https://cloud.githubusercontent.com/assets/24310562/20861646/14c5ac42-b963-11e6-9276-da609cc7bcfe.png)
.

**Comment by LovelyFlare** [comment]
Tinkers' Construct doesn't disable tools in 1.10.2 even in config options.

**Comment by KnightMiner** [comment]
Tinkers Construct does nothing with removing vanilla recipes, look through the many other mods in your pack.

**Comment by EZEILL** [comment]
I removed all tinkers mods, reinstalled ONLY tinkers construct for 1.10.2 and it disabled the crafting recipes for all other weapons and tools in vanilla and other mods. yall need to stop closing my issues when you clearly dont know what youre talking about.

**Comment by ArukaAlter** [comment]
They made the mod, they know what goes on, you won't find any reference to recipe removal in the code.

**Comment by EZEILL** [comment]
Just because there might not be any reference doesn't mean the mod isn't causing it to happen.
