### ISSUE TITLE
Recipe Re-Enable

### ISSUE THREAD

**Issue by EZEILL** [SlimeKnights/TinkersConstruct#2614]
Third time posting this because people who don't know what they're talking about have closed the issue. Do not close this because you do not know why or how Tinkers Construct is causing this issue to happen, I am trying to get this fixed and that won't happen if y'all keep closing the issue.

I have uninstalled ALL Tinkers based mods, tested crafting for vanilla and other mod weapons/tools, reinstalled ONLY Tinkers Construct, RETESTED THE CRAFTING, and Tinkers Construct is making it so that I cannot craft vanilla weapons and tools as well as similar recipes from other mods that add weapons and tools.

This picture is me trying to craft a diamond sword with TC installed.
![2016-12-03_14 15 11](https://cloud.githubusercontent.com/assets/24310562/20862294/a4933de2-b974-11e6-86a0-d05378632830.png)

This picture is me trying to craft a Kitana from one of the other mods I am using with TC installed.
![2016-12-03_16 38 01](https://cloud.githubusercontent.com/assets/24310562/20862393/f42f60ea-b976-11e6-9e83-833a69b79702.png)

**Comment by EZEILL** [comment]
I guess I'm going to have to trouble shoot this issue myself. Ran into a bug that is only coming up when I install Tinker's Construct, that nobody seems to think is there. Maybe it's a compatibility issue.

**Comment by ArukaAlter** [comment]
You are certainly experience a weird corner case, I asked at least three people to test and none of us could reproduce.

**Comment by bonii-xx** [comment]
And, for the 3rd time, we have to tell you that it's not Tinkers. Go ahead. Make a new instance. Install Forge and put in only Mantle and TiC.

**Comment by EZEILL** [comment]
Which is why I said that MAYBE it is a compatibility issue. You don't think I tested out only having TC and Mantle installed?

**Comment by LovelyFlare** [comment]
It might be the forge version.  I've heard this happen before on the forums...

**Comment by bonii-xx** [comment]
Even if that's the case, it wouldn't be on our side, so there's nothing for us to do. Also if you ask me that's not a bug, but an intentional feature of some mod/your modpack there.

**Comment by EZEILL** [comment]
I figured out the problem which sucks because it wasn't an option listed on the mods page, one of the mods I'm using disables vanilla recipes when TC is installed. I apologize for the annoyance.
