### ISSUE TITLE
[2.6.0] Replacing bolt cores on bolts only replaces shaft trait

### ISSUE THREAD

**Issue by Xuerian** [SlimeKnights/TinkersConstruct#2615]
See: ![Before](http://i.imgur.com/yaFxv7Q.png)
Then: ![After](http://i.imgur.com/XpIq0qx.png)

Bolt core used (Ice and Steel) ![Core](http://i.imgur.com/jENZfC9.png)

It's also worth noting that it was a Wood-Silver bolt core to start with.

**Comment by bonii-xx** [comment]
Heh, interesting. Bolt core replacement wasn't possible at first, I guess some code cleanup of mine fixed it. It's not really a useful thing to replace anyway since all you keep are the fletchings.

**Comment by Xuerian** [comment]
Granted, but it's very useful when combined with your tool leveling addition. It does seem a grudgingly added thing, but still.

And I have a friend who I can't get to play unless they have numbers that keep going up, so there's that 😐

**Comment by bonii-xx** [comment]
It's a bug for sure.
