### ISSUE TITLE
Errors triggering in JEI

### ISSUE THREAD

**Issue by dshadowwolf** [SlimeKnights/TinkersConstruct#2616]
JEI API being used is causing non-fatal errors (JEI 3.13.6.387 - Tinker's Construct 2.5.6b)

java.lang.NoSuchMethodError: mezz.jei.plugins.vanilla.crafting.ShapedOreRecipeWrapper.<init>(Lnet/minecraftforge/oredict/ShapedOreRecipe;)V

I've attached the log-file containing this issue for your perusal. I'm not sure if its a load-order thing or if the API is just not functioning correctly - I lack the knowledge of Forge and Java to be able to tell.

[latest.log.txt](https://github.com/SlimeKnights/TinkersConstruct/files/629220/latest.log.txt)

**Comment by KnightMiner** [comment]
This is already fixed in the latest Alpha on CurseForge, just waiting for further testing before a release

**Comment by dshadowwolf** [comment]
Ah, okay - I try not to run Alpha's because of bugs. Good to know, thanks!
