### ISSUE TITLE
Breaking an Unbreakable item

### ISSUE THREAD

**Issue by luckdemon** [SlimeKnights/TinkersConstruct#2623]
Here's a picture for reference, I think it has to do with the fact that manyullyn adds increased damage for increased durability. However, I upgraded this rapier with 5 reinforcement modifiers to be invincible.
http://puu.sh/sEmib/7d8000399c.jpg
Tool still breaks as normal when it should not.

**Comment by TherminatorX** [comment]
Duplicate issue, see #2499

**Comment by luckdemon** [comment]
I should have added that this bug still occurs in 2.6.0 even though it was marked resolved in the other issue.

**Comment by bonii-xx** [comment]
Was that in SSP or on a server?

**Comment by luckdemon** [comment]
Yes I can reproduce this with 2.6.1 in SSP and in a server, However now I've reduced the problem to what seems to be the cause of it. When I let the weapon reach full charge (max damage per swing) it does not take durability damage anymore. However when I spam the weapon before letting it fully charge, they take durability damage sometimes.
Hope the extra info helps, if you need any more testing from me, just let me know!

**Comment by luckdemon** [comment]
Not sure if it helps, but it appears to take more damage if you swing before the weapon fully charges it's damage bar.

**Comment by MarkSzita** [comment]
The problem is not a bug, it's Manyullyn. it's material effect is to lose durability. change to a different material.

**Comment by TherminatorX** [comment]
@MarkSzita The developer said it's a bug. It's a bug.

**Comment by Janitor53** [comment]
@MarkSzita The same problem with different materials.

**Comment by Bennyboy1695** [comment]
Same issue occurs with obsidian tool part, just had an unbreakable pickaxe break :(

**Comment by bonii-xx** [comment]
Tried reproducing this again with an unbreakable manyullun rapier. Killed a lot of zombies, with spamclicking and only full charge. Can't get the rapier to take any damage

**Comment by mainframecn** [comment]
i have a similar issue with an unbreakable axe. Placing it a tree farm machine will just consume durability, completely ignoring the "unbreakable" attribute.

**Comment by bonii-xx** [comment]
Different issue.

**Comment by Elvarion** [comment]
Also have had this happen with my broadsword.
https://gyazo.com/066a33eba64b810e6e2066de6d6ee316
Its broken twice on me now, Not sure if this was because the last Reinforced was applied when the broadsword was not at full durability?

Since my Pick is also Unbreakable and ive mined 'Over 9000' blocks with it and its not broken on me.
And I am 99% sure I applied the final Reinforced when it was at max durability.

**Comment by mainframecn** [comment]
Try not using manyullyn or obsidian. Those materials can consume durability even with the unbreakable attribute. I made that same mistake.

**Comment by Flabort** [comment]
Same with Dense from bronze.

**Comment by bonii-xx** [comment]
Should be fine in 2.6.2 either way.

**Comment by Bob74** [comment]
Had the issue with Obsidian pickaxe + Reinforcement V (Unbreakable) on 2.6.1 (Minecraft 1.10.2).
Beta 2.6.2 fixed it!

I've just repaired my pickaxe after installing beta 2.6.2 and now its durability stay at its max value.

**Comment by bonii-xx** [comment]
Thanks for the confirmation
