### ISSUE TITLE
[2.6.0] Crash with the error "Rendering item  java.lang.IllegalStateException: Not building!"

### ISSUE THREAD

**Issue by Wubbbi** [SlimeKnights/TinkersConstruct#2624]
Hey =)

I dont know if this is related to TConstruct, but the only error Method I can find in this crash report is by you Sir.

Here is the crash log: http://pastebin.com/YL9tpCYB

This is the Item beeing rendert:

"Item Type: slimeknights.tconstruct.tools.tools.Excavator@75d6dc0b"

If you need any help, just write me. I dont know what to say at this point.

The Excavator is on my Hotbar, having 1 modifier (ToolLeveling mod by you is installed). The modifier is Diamond.

Also I think this is related to this issue here: https://github.com/Darkhax-Minecraft/Bookshelf/issues/56

Seems like other people have that problem too!

Greetings

(Und Servus nach Österreich ;D)

**Comment by Wubbbi** [comment]
I think I have an Idea what the issue could be:

I put a Makanism Item into the TConstruct Workbench, which is an 3D model (Solar Panel). As soon as the Workbench tries to render this on top of it, my game crashes. Seems like the TConstruct Workbench cant handle 3D Models? :/ Is it even possible to fix that? My Chunk is broken now because as soon as I log in, my game crashes. -_-

I can reproduce this over and oven. Try it yourself.

**Comment by KnightMiner** [comment]
The issue is Mekenism is doing very bad things in rendering their item models (they should either be using a TESR or an entirely static model). Completely their fault and nothing we can do about it, so go yell at the people on the Mekenism issue tracker.

**Comment by Bluexin** [comment]
@KnightMiner the second message he posted is about a vastly different issue than the first one.
I have patched (or rather, put some band-aid) on our version of mekanism to prevent the issue he was referring from happening (and it did indeed fix that issue), but this issue is something that has nothing to do with that.
http://pastebin.com/yeYwCbkr since I've had this happening only with TCons items so far I guess that's what causes it.

**Comment by KnightMiner** [comment]
You have three different mods in that stack trace that are not Tinkers, and I have never seen such a crash, so I would try removing one of those three one by one to see if that fixes it.
