### ISSUE TITLE
[enhancement] Add new block to use Power (RF) as fuel

### ISSUE THREAD

**Issue by winsrp** [SlimeKnights/TinkersConstruct#2625]
Hi I can't seem to find a fuel that will smelt me something like diamond or some other materials, from what I heard I need to install a different mod that adds some compatible fuel to get the required heat level, so I was thinking why not add like an electric interface that will electro charge lava (you could even add your own liquid at this point, electro-lava), maybe add a different multiblock structure to electro charge lava first and then the player has to move it to the smelter, and it will raise it's heat level to max, so that way lava is still required, and people don't need other mods to make full utilization of your mod. Also this makes it a creative solution that does not discards the basics, and could be a second step level progression of your mod!!.

Thanks

**Comment by LovelyFlare** [comment]
Tinkers' Construct isn't a tech mod.

**Comment by bonii-xx** [comment]
No, smelteries don't use RF. As for the heat levels, everything in TiC can be molten with lava, if a mods add things that can't be molten with lava then its that mods responsibility to add proper fuel as well.

**Comment by winsrp** [comment]
fine I get that... so let put the example of bonii-xx here, tinkers allow to have diamond and emerald tool/weapons, but the smelter needs more heat to melt those, which is not currently available in the tinkers mod, then how do I melt those? Don't you think is tinkers responsibility as you put it to add a proper fuel as well?

**Comment by winsrp** [comment]
seems like emerald can be, but diamond cannot be melted (gray line), blocks of both diamond (gray line) and block emerald (blue line) are both non melt-able. So avoiding blocks of... since yeah we all can live without melting a block, at least the diamond should have a way to be melt.

**Comment by bonii-xx** [comment]
Tinkers doesn't have meltable diamonds, emeralds can't be used as tools. You cannot melt the blocks, yes, because it's based around the emerald gems themselves. You need to melt the gems.

**Comment by winsrp** [comment]
I see, so how about maybe a config file option to specify the heat of some liquids, for example I have Immersive engineering that adds uranium and liquid uranium which should be a very powerful heat source but putting it in tinkers mod states 300 heat level. Is that something that could be added?

**Comment by KnightMiner** [comment]
That would be on Immersive Engineering or a recipe mod to adjust, dynamically generating overrides for all fuels added in the API would be a pain to keep updated, hence why mods like MineTweaker exist.
