### ISSUE TITLE
smeltery drain/faucent won't pour contents into casting table

### ISSUE THREAD

**Issue by wylderhoads1809** [SlimeKnights/TinkersConstruct#2628]
Versions: TConstruct-1.10.2-2.6.0
1.10.2-forge1.10.2-12.18.2.2166

when pouring into casting basin everything works, but pouring into a casting table won't output any liquids. This happens with  or without a cast on the table and I tried with many different metals and even clay. Breaking and replacing the drain/faucet/table/cast doesn't fix the problem.

**Comment by oitsjustjose** [comment]
Can we get pictures of your setup? Are you running any other mods?

Have you tried completely re-locating your smeltery?

**Comment by wylderhoads1809** [comment]
I think the problem is with Quark (I posted on reddit about this), and I've
updated quark and am doing some testing now.

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by wylderhoads1809** [comment]
I could not recreate under those conditions. I think it was a problem with
quark. You can close the post.
thanks for the help!

**Comment by ArukaAlter** [comment]
This has nothing to do with Quark either.
