### ISSUE TITLE
Sharpening kit not improving tool's mining level

### ISSUE THREAD

**Issue by FallenEagle1** [SlimeKnights/TinkersConstruct#2630]
Modpack: All the Mods v. 1.49
Tinkers: v. 2.6.0

In a tool forge, it was noticed that trying to add a sharpening kit and a piece of flint to a tool will not improve the tools mining level, as it was in previous versions.

 I noticed that the tinkers book had a change to it talking about the sharpening kit, saying that you can repair you tools without a station/forge. Is this now the functionality of a sharpening kit? If so, the tooltip for the sharpening kit is outdated.

![2016-12-07_09 10 10](https://cloud.githubusercontent.com/assets/22630113/20975589/2cc4b3ea-bc5d-11e6-9239-9e803acfee7c.png)

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by FallenEagle1** [comment]
it works with just those three, and I did more testing also. Im thinking it comes down to weird mod interaction.

I took the pack that the bug was found in, and just disabled most of the mods. It started working. Slowly added back all of the mods, and still worked even once they were all back in. Probably will spend some time tomorrow slowly removing them and see if i can find it that way.

**Comment by FallenEagle1** [comment]
Got to this way later than expected, but I'm unable to pinpoint this down. If i had to guess, it would be a weird mod interaction with substratum, since there are a bunch of ore dict changes through that mod for All the Mods. The pack has been updated and it is working again, so I'll just leave it to unforeseen mod interaction and leave it alone.

**Comment by staviq** [comment]
#https://github.com/NillerMedDild/Enigmatica2Expert/issues/1849

Hi, could you take look at this ? I found a reproducible way of causing a problem like described here.
