### ISSUE TITLE
How to make a Bolt Core

### ISSUE THREAD

**Issue by fcportasio** [SlimeKnights/TinkersConstruct#2631]
Hi guys

I'm trying to make a wooden bolt core by placing a wooden tool rod into the casting table, and when i try to pour any type of molten metal over it, the molten metal don't move out the smeltery! 
Is this the wrong way to do bolt cores?

**Comment by ArukaAlter** [comment]
If you are asking 1.10, no, there aren't crossbows or bolts yet.

**Comment by fcportasio** [comment]
I'm using 1.10.2,!
They just add crossbows(few days ago i think), bows, longbows, to this version. I can see them at tool forge. I made a crossbow, but when i tried to make bolts.. It doesn't work! I can see bolts and bolt cores at JEI too..

**Comment by bonii-xx** [comment]
It's in the book.

**Comment by Ricket** [comment]
I am in Direwolf20's 1.10 pack (pack version 1.2.1) with TConstruct-1.10.2-2.6.1.jar. Also cannot make bolt cores even though they show up in JEI. Just as it says in [the wiki](http://tinkers-construct.wikia.com/wiki/Bolt), I placed a Wooden Tool Rod (not a stick) into a Casting Table, and then I try to pour molten iron onto it (to create a Wood-Iron Bolt Core). But the Faucet will not pour, it does nothing. I ensured I have a lot of iron ready in the smeltery and it is selected (I'm not new to tinkers).

How do I create the bolt core then?

Why was this issue closed anyway? Was it actually resolved? I have looked all through the Materials and You book and it doesn't help.

**Comment by ArukaAlter** [comment]
You need to use Arrow Shaft, not Tool Rod now.

**Comment by Ricket** [comment]
Thanks, that worked. Does it say this anywhere?

**Comment by bonii-xx** [comment]
The book. Where else?

**Comment by Ricket** [comment]
You could have stated where in the book. I found it in Tools > Bolt Crafting, I did not notice that page before, I only saw the Bolt page which does not explain about the bolt core. Perhaps the Bolt Crafting page could be moved next to the Bolt page, I think it makes more sense there versus its current location.

> Where else?

The wiki as I linked before (and therefore, [Google -- here's a screenshot of the search result](http://imgur.com/a/NpqxK)). I edited the wiki page, hopefully my edit will be saved/accepted.

**Comment by KnightMiner** [comment]
The wikis all use the 1.7 version last I checked, not official documentation in any case. If the wiki proves to be wrong, the book should be checked first to verify.
