### ISSUE TITLE
Tinkers not working?

### ISSUE THREAD

**Issue by luke0fluke0** [SlimeKnights/TinkersConstruct#2632]
A mate and I have been trying to change our server to 1.9.4 after not playing for a while and were just running forge 1.9.4 and the server folder with tconstruct 1.9.4-2.3.3 and mantle 1.9.4-0.10.3 and when we spawn in we dont have either of the books and then when we try to create the crafting table into the tconstruct crafting table it doesnt allow us to pick it up it just spits it back into the box u click to take the item youve made.

probs sounded a little confusing but any help would be appreciated

**Comment by ArukaAlter** [comment]
Update to 1.10

**Comment by luke0fluke0** [comment]
Im running on 1.9.4 tho and it was actually happening in the 1.7.10 world we were about to launch but changed to 1.9.4 last minute. 

I think it must be like an issue with the server setup or something

**Comment by ArukaAlter** [comment]
The thing is: issues regarding old versions are considered invalid.

**Comment by bonii-xx** [comment]
You also need the mod on the server, sounds like your server doesn't have the mod.
