### ISSUE TITLE
Which mods does Tinkers Construct support? or TC 1.10.2 does not work with Mekanism

### ISSUE THREAD

**Issue by FlyingScoots** [SlimeKnights/TinkersConstruct#2633]
Hello!
Frustratingly enough, I couldn't find any information regarding this anywhere. Unless I've failed to search hard enough.
Which mods for materials such as Copper, Aluminum, etc., does Tinkers Construct for 1.10.2 support? On the Forge page it claims to now not add those to generation, but instead automatically support mods that add such materials. I've installed Mekanism which worked just fine in a pack I had for 1.6.4 thanks to ExtraTiC - and, well, I can't melt Mekanism ores in the smeltery, nor can I use ingots with a Tool Station/Tool Forge - and obviously there's no ExtraTiC for 1.10.2.
So which mods do I need? I really need my fix of more workable metals.

**Comment by ArukaAlter** [comment]
If the materials are properly registered in the ore dictionary, they should work.

**Comment by FlyingScoots** [comment]
Considering I have not encountered that... uuuh... anywhere I can read up on that?

**Comment by FlyingScoots** [comment]
Well, after a little bit of googling...
So, what does that entail? Do I need to find a way to modify ore dictionary somehow?

**Comment by ArukaAlter** [comment]
No, it's something on Forge that every mod uses.
Say, you have a recipe that should use copper ore, for example, regardless form wich mod it comes from, it should be registered in the oreDict as oreCopper, so any mod can use it.
If none of the Mekanism ores melts I'd take it to Aidan, because it may be on his side.

**Comment by FlyingScoots** [comment]
Will do. Thanks. Although it would help to know if there's an alternative to using Mekanism's metals that is confirmed to work.

**Comment by LovelyFlare** [comment]
@FlyingScoots Try looking at Substratum

**Comment by FlyingScoots** [comment]
PERFECT! Even my Mekanism stuff now works with it! THANK YOU SO MUCH!
