### ISSUE TITLE
Can not insert part patterns into the part builder.

### ISSUE THREAD

**Issue by Kuktar** [SlimeKnights/TinkersConstruct#2634]
I love tinkers and i cant live without it please help. Ok so the issue is my part builder wont accept any patterns other than a blank one. I have a video to illistrate the issue, and i have the versions i am using. there is not crash log but i can put the forge mod loader logs if needed just in case. The link is to the youtube video i captured were my problem can be recreated. THANKS IN ADVANCE LONG LIVE TINKERS

https://youtu.be/MPordp5dST0

TConstruct-1.10.2-2.6.1
Mantle-1.10.2-1.1.3

i updated today because i thought it might help the issue but it's still persistent. in the config's I also enabled the allow all parts even ones that need to be cast in part builder and it still didn't help. The part builder just does not accept patterns....

**Comment by LovelyFlare** [comment]
What other mods do you have?  Can you reproduce this issue with just Tinkers' Construct, Mantle, and Forge?

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by ShdwDrgnVIIv2** [comment]
Did you ever get this issue resolved?  I have tried everything that I can think of, same results.  Moderators, I have loaded forge with only mantle and TiC, and still get the same results.  everything else is good, but the part builder will not accept patterns.

**Comment by bonii-xx** [comment]
Broken Forge version or something...? Or something on your server is breaking it.

**Comment by Kuktar** [comment]
Honestly everything i try with the newer versions of forge and tinkers does not work. even with just tinkers installed along with mantle. Also i tried other modpacks (ftb presents hermitcraft and direworlf 20) with older versions of forge and it seems to work fine. for instance with forge version 1.10.2 - 12.18.3.2185 and the newest tinkers stuff it dosent work. if i go back to 12.18.2.2171 forge and any version of tinkers that loads with it seems to work fine. I really have to have the newest forge because journeymap and a couple other mods ( even with the tinkers issue i run 240 mods) complain when i update them and have older forge. I have just been going into creative to get my parts built and throwing the materials in the trash lol. Sucks if your not an OP.

Also thank the heavens for good backup software :P

**Comment by Kuktar** [comment]
Ok so i just for the first time was able to actualy use the part builder.... I have just wrote this off as a bug for the longest time but i forgot to use creative to give myself patterns and parts for tools. Anyways the only change i made recently was update forge to the most recent one. 

1.10.2 - 12.18.3.2202

It does not even list any fixes for anything remotely related to tinkers construct, BUT HEY IT WORKS NOW :P OK i am going to close my own issue and the other 9 people who had the same issue i highly suggest updating to yesterdays released forge :PPP

**Comment by ViperZeroOne** [comment]
Actually updating to Forge 1.10.2-12.18.3.2202 didn't solve the issue on our end.  We still can't place any items into the Parts Builder.
