### ISSUE TITLE
[1.10.2-2.6.1] Endrod arrows can cause suicide with movement

### ISSUE THREAD

**Issue by VallenFrostweaver** [SlimeKnights/TinkersConstruct#2635]
When walking forward with a bow drawn back and shooting arrows with endrod shafts the arrow can hit the player firing the arrow.

From another perspective I can see the endrod arrow hang for a split second before actually going to the target. Due to the arrow hanging there the player can run into it with the movement they get when releasing the arrow meanign they are walking into the back of the hanging arrow and taking damage (sometimes fatal).

Try using F5 for reproduction and best single player visibility of the endrod arrow hang or switch between non-endrod arrow and endrod arrows and it's very noticeable. More noticeable with shortbows than longbows as you can move faster and are more likely to walk into the arrow with more speed, etc.

**Comment by bonii-xx** [comment]
The arrow "hanging" is intended, however I think I know where the issue lies. Hm.

**Comment by VallenFrostweaver** [comment]
I'm pretty sure of the exact effect you are going for here and I do love it. Perhaps have the arrow either start further away from the player or have it move normally for a block then do the animation? Just some thoughts.

As a side note, I just wanted to say thank you for a great and fun redesign. <3

**Comment by 0xdade** [comment]
I actually just updated HermitPack tonight and got Tinker's 1.10.2-2.6.1 but am unable to craft endrod arrow shafts, and can't find any details on how to do so. Using an arrow shaft pattern w/ end stone doesn't work, nor does an arrow shaft cast. I looked in server config settings and couldn't find anything suggesting they were possibly disabled. Am I doing it wrong or is there maybe some compatibility issue?

**Comment by ArukaAlter** [comment]
Isn't the End Rod arrow shaft made with... End Rods?

**Comment by 0xdade** [comment]
@ArukaAlter Thanks for some reason I just totally derped. Hard time updating the server today so I guess I was just looking for something to be broken :)

**Comment by bonii-xx** [comment]
You know you can just... open the books and look there, right? :P
