### ISSUE TITLE
[1.10.2-2.6.1] Sharpening kits only being used 1 at a time

### ISSUE THREAD

**Issue by VallenFrostweaver** [SlimeKnights/TinkersConstruct#2636]
When using a stack of sharpening kits on a compatible item (for best example use a partly paper tool and repair with paper sharpening kit) it will only use one at a time unlike using the tool station where it will use all of the compatible material available.

**Comment by ArukaAlter** [comment]
But that's how the crafting grid works.

**Comment by VallenFrostweaver** [comment]
So then it's less hassle to bring a Tool Station and stack of paper and the sharpening kits are useless again except for changing the mining level of a tool.  This is the point I'm making is that the sharpening kits should be more used as I think this was the whole intention.

**Comment by LWnellA** [comment]
Bringing a sharpening kit frees a spot in your inventory, and is much quicker than using a tool station.
This is very useful when you're doing things like mining where you want plenty of inventory space, or during combat when you might just not have the time to plop down a tool station, open it up, and repair the weapon.

Also, it really depends on the person as to whether they think crafting a tool multiple times with a sharpening kit is more of a hassle than bring along a tool station and placing it down every time you need to repair your tool.

**Comment by bonii-xx** [comment]
If your tool has a much higher durability than the material you're using to repair, then yes it's a hassle. But you can always use another material to repair in case of multi-head-material tools like hammers. Everything working as intended.
