### ISSUE TITLE
Tinkers Construct 1.8.8 & GregTech 5.09.26 Glue

### ISSUE THREAD

**Issue by motangish** [SlimeKnights/TinkersConstruct#2639]
Glue from **G**reg**T**ech will be replaced to Glue from **T**inkers **C**onstruct and I can not use a Glue from **TC** for a Assembling Machine from **GT**. 

If I will remove **TC** from my modpack then I can use Glue from **GT** for Assembling Machine.

**Can I disable a TC Glue?**
**Whether there are any other solutions?**

**Comment by KnightMiner** [comment]
I don't see why it would replace it at all, it is simply oredicted as slimeball last I checked. I would blame this on GregTech.

In any case, 1.7.10 is no longer supported, so I am closing this issue.
