### ISSUE TITLE
not sure if caused by ae2 rv4 or tinkers and/or JEI (Direwolf20 1.10.2 modpack) but

### ISSUE THREAD

**Issue by snacdaws** [SlimeKnights/TinkersConstruct#2642]
When using appliedenergistics2-rv4-alpha-8.jar , Mantle-1.10.2-1.1.3.jar, TConstruct-1.10.2-2.6.1.jar and jei_1.10.2-3.13.6.387.jar (when searching in the ae2 terminal @tinker) it crashes minecraft completely
[crash-2016-12-10_12.26.46-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/643931/crash-2016-12-10_12.26.46-client.txt)

if anyone can figure out what mod is causing it (if not tinker's)

**Comment by KnightMiner** [comment]
If I had to guess from the stack trace, Quark. I see nothing that points to a Tinkers error

**Comment by snacdaws** [comment]
ok trying an older release of quark
