### ISSUE TITLE
[1.10.2, v.2.6.1] Entirely White Tool's and Broken Patterns and Casts.

### ISSUE THREAD

**Issue by lurker500** [SlimeKnights/TinkersConstruct#2644]
Minecraft version: v1.10.2
Tinkers' Construct version: v2.6.1
Forge version/build: Build 2185

![](https://cdn.discordapp.com/attachments/239177367338221569/257305121413660672/unknown.png)

Every tool in Tinker's Construct is entirely white along with shards and pieces of the actual tool. Pattern's and Casts are also broken with Patterns being the generic missing texture purple while clay casts are a slightly darker version.

**Comment by KnightMiner** [comment]
Can you give us a mod list? Does it happen with just Tinkers? Specifically, optimization mods such as Optifine are likely to be the cause.

**Comment by lurker500** [comment]
Modlist:
Actually Additions r90
Better FPS 1.3.3
BiomesOPlenty 5.0.0.2068
Chisels and bits 12.7
Compact Storage 2.1
Draconic Evolution 2.0.3.137
DrawersBits 0.34
EnderIO 3.0.1.139beta
ExtraUtils2 1.10.2 1.1.2
Immersive Engineering 0.10-52
Inventory Tweaks 1.61-58
JEI 3.13.6.387
Just Enough Calculation 2.1.4
Just Enough Resources 0.5.7.87
Mantle 1.1.3
Mekanism, Generators and Tools all 9.2.1.295
Optifine HD_U_C3
Progressive Automation 1.6.51
Psi r1.0-42
Refined Storage 1.1.3
Reliquary 1.3.3.585
RFTools 5.62
RFTools Dimensions 4.45
Storage Drawers 3.4.4
Waila 1.70-B3_1.9.4
Waila Harvestability 1.1.9
Xaeros Minimap 1.11.6

The blank white tools only happens with Tinkers but as this error occured i also submitted a report to the extra utils 2 github because there was an error in that mod too. Optifine is unfortunately necessary for me because my computer wasnt entirely meant for gaming.

**Comment by KnightMiner** [comment]
You misunderstood my second question, does the white tool issue still happen if you uninstall all other mods, specifically Optifine. If it only works without Optifine, we cannot help you so you are best off reporting to the Optifine tracker.

**Comment by LovelyFlare** [comment]
You should include the coremods.  There are quite a bit that mess with rendering and color.

**Comment by lurker500** [comment]
I can now confirm that it is one of my other mods that is causing the issue. 

![image](https://cloud.githubusercontent.com/assets/23016573/21078139/d862987a-bf32-11e6-8028-9572a8636e9e.png)

**Comment by KnightMiner** [comment]
So, the best way to determine which mod is causing it is to add back half the mods at once, and if that works still, try the other half. By constantly cutting the list in half you should be able to find the conflict fairly quickly.

**Comment by lurker500** [comment]
I have managed to figure the problem out. Unfortunately it was OptiFine paired with Extra Utils 2 that caused the white tools, purple casts and the broken extra utils.
