### ISSUE TITLE
[2.6.1] unable to break many blocks without the proper tool when Harvest Tweaks is installed

### ISSUE THREAD

**Issue by belathus** [SlimeKnights/TinkersConstruct#2645]
I just started a new world in 2.6.1. I am completely unable to break logs, grass, dirt, gravel, sand, etc. without the proper tool. The only mods I have installed when performing this test were AppleSkin, BetterFPS, CookingForBlockheads, FoamFix, HarvestTweaks, JEI, JER, Mantle, NoFOV, Surge, TConstruct, and Waila.

Removing Harvest Tweaks or reverting to TConstruct 2.5.6b fixes this issue.

**Comment by TherminatorX** [comment]
"You **can** set a tool for blocks that usually don't require a tool to harvest, like wooden logs or planks. Those blocks simply wont get any break progress when trying to be broken without the tool."

https://minecraft.curseforge.com/projects/harvest-tweaks

**Comment by belathus** [comment]
I removed the references to dirt, grass, gravel, etc. in the harvesttweaks config and still could not break dirt et al with the latest version of TCon.

Totally a bug.

**Comment by bonii-xx** [comment]
Not a TiC bug though, HarvestTweaks bug.
