### ISSUE TITLE
Stencil Table not making patterns!

### ISSUE THREAD

**Issue by supertommyhd** [SlimeKnights/TinkersConstruct#2646]
What???

Whenever I try to make a pattern, nothing happens. I click everywhere, nothing happens. and Patterns are essential to starting the game. Please fix.

As you see here, I've tried to make a frying pan pattern. No success.
![2016-12-10_20 19 47](https://cloud.githubusercontent.com/assets/22721170/21078069/68e92cc8-bf16-11e6-87d7-1c4702b10dfa.png)

**Comment by LovelyFlare** [comment]
Version?  What other mods are you using?  Can you reproduce this with just TiC, Mantle, and Forge?

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by supertommyhd** [comment]
1.10.2, and I used 

[1.9.4]myBiomes - Version 2.3.3.jar
ActuallyAdditions-1.10.2-r67.jar
AetherII-1.10.2-r1-build1.jar
AutoRegLib-1.0-2.jar
Baubles-1.10.2-1.3.BETA11.jar
BiomesOPlenty-1.10.2-5.0.0.2091-universal.jar
Botania r1.9-335.jar
Cavern-Mod-1.10.2.jar
Chisel-Mod-1.10.2.jar
chiselsandbits-11.3.jar
cnoapm-mcv1.10.2.jar
Craftable_Waypoints_1.3.1_Forge_1.10.2.jar
Cyclic-1.10.2-1.7.13.jar
druidry(2016.8.10.2)(1.9.9).jar
EJML-core-0.26.jar
EnderCore-1.10.2-0.4.1.58-beta.jar
EnderIO-1.10.2-3.0.1.124_beta.jar
Excore-1.6.2-1.10.2.jar
ExtrabiomesXL-universal-1.7.10-3.16.RC2.jar
extrautils2-1.10.2-alpha-1.2.1.jar
FastLeafDecay-v11.jar
Flan's Mod-1.8-5.1.jar
flatcoloredblocks-mc1.10-v4.2.jar
forestry_1.10.2-5.2.16.301.jar
GraveStone Mod 1.5.8.jar
hermitquest-1.10.2-1.1.22.jar
inventorypets-1.10-1.4.8.2.jar
JustEnoughResources-1.10.2-0.5.4.68.jar
M-Ore 7.6 1.10.2.jar
mcjtylib-1.10-2.2.0.jar
MCMultiPart-1.3.0-universal.jar
Mekanism-1.10.2-9.2.0.292.jar
MekanismGenerators-1.10.2-9.2.0.292.jar
MekanismTools-1.10.2-9.2.0.292.jar
natura-1.10.2-4.0.0.86.jar
Pam's HarvestCraft 1.9.4-1.10.2g.jar
Quark-r1.0-56.jar
refinedstorage-1.0.5.jar
Reliquary-1.10.2-1.3.3.581.jar
rftools-1.10-5.56.jar
rftoolsdim-1.10-4.43.jar
RTG-1.10.2-4.1.1.6.jar
ShadowMC-1.10.2-3.4.8.jar
SleepingBag-1.10.2-1.3.0.jar
SpawnerCraft 1.10.2-3.2.0.jar
taiga-1.10.2-1.1.4.jar
TinkerToolLeveling-1.10.2-1.0.1.jar
Torcherino-4.2s.jar
Waila-1.7.0-B3_1.9.4.jar
Waypoints-Mod-1.9.4.jar


It works with just Tinkers Construct, Mantle, and JEI

**Comment by supertommyhd** [comment]
Okay, I took away aether. works perfectly.

**Comment by spikespaz** [comment]
This shouldn't be a thing we need to do. These two great mods should be worked together to be compatible. I propose we reopen the issue, I have contacted the developers of Aether II and they look into it. I suggest Tinkers Construct do the same.

**Comment by LovelyFlare** [comment]
@spikespaz The thing is it's not Tinkers' Construct's fault.  It's the Aether II somehow disabling the functionality of the stencil table...  therefore nothing can be done on our side.

**Comment by bonii-xx** [comment]
@spikespaz Tinkers' is doing everything "cleanly", and has the highest possible compatibility (except one place with the side inventory of the crafting station). I can guarantee you that nearly every time you encounter such problem it's other mods breaking things with stupid hacks. I wouldn't be so quick to call mods "great" unless you know what they're actually doing.

**Comment by spikespaz** [comment]
I call a mod "great" by the features they add. I talked with Jellysquid (Developer of Aether) and he said he knows what the problem is and is looking into it. He says it's based on the way they handle the crafting recipes.

**Comment by halloweenkid9** [comment]
On an extra note I cant seem to be able to create any form of ingot in a cast except for making a block in the casting basin, I know I can make several different types of parts including a sword blade and pick head but ingots simply aren't capable of casting even though i can make the ingot cast and melt ingots in the smeltery. P.S thanks for finding the mod that's causing the problem Supertommyhd, so I didn't have to :P
