### ISSUE TITLE
keeps crashing since a newer version on 1.10.2

### ISSUE THREAD

**Issue by Weskerr** [SlimeKnights/TinkersConstruct#2648]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingHook (Mekanism-1.10.2-9.2.0.294.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BCModPlugin (Backpacks-Mod-by-Brad16840-1.10.2.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.0.3.jar)
  IC2core (industrialcraft-2-2.6.105-ex110.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 11.12.16 12:06
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Building Bricks (buildingbricks)
Caused by: java.lang.RuntimeException: Could not load material from tconstruct:materials/vine.json
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialResourceLoader.loadResources(MaterialResourceLoader.java:30)
	at com.hea3ven.buildingbricks.core.ProxyCommonBuildingBricks.onPreInitEvent(ProxyCommonBuildingBricks.java:86)
	at com.hea3ven.buildingbricks.core.ModBuildingBricks.preInit(ModBuildingBricks.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.JsonParseException: material does not have an id
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialParser$MaterialDeserializer.deserialize(MaterialParser.java:46)
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialParser$MaterialDeserializer.deserialize(MaterialParser.java:37)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialParser.loadMaterialFromStream(MaterialParser.java:34)
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialResourceLoader.loadResources(MaterialResourceLoader.java:26)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 735074520 bytes (701 MB) / 2382364672 bytes (2272 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.0.3.jar) 
	UCH	backpacks16840{3.1.1} [Backpacks!] (Backpacks-Mod-by-Brad16840-1.10.2.jar) 
	UCH	buildingbrickshooks{1.10.2-2.0.12} [Building Bricks Hooks] (minecraft.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	actuallyadditions{1.10.2-r88} [Actually Additions] (ActuallyAdditions-1.10.2-r88.jar) 
	UCH	armorplus{1.9.4-4.1.9.1} [ArmorPlus] (armorplus-1.9.4-4.1.9.1.jar) 
	UCH	Aroma1997CoreHelper{1.1.0.3} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.0.3.jar) 
	UCE	buildingbricks{1.10.2-2.0.12} [Building Bricks] (BuildingBricks-1.10.2-2.0.12.jar) 
	UCH	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCH	IC2{2.6.105-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.105-ex110.jar) 
	UCH	CompactSolars{5.0.4.328} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.4.328-universal.jar) 
	UCH	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCH	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCH	torohealthmod{1.10.2-1} [ToroHealth Damage Indicators] (Damage-Indicators-1.10.2.jar) 
	UCH	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod-10.0.6.jar) 
	UCH	elevatorid{1.2.0} [Elevator Mod] (ElevatorMod[V.1.2.0][MC.1.10.2].jar) 
	UCH	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCH	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCH	EnderIO{1.10.2-3.0.1.138_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.138_beta.jar) 
	UCH	enderutilities{0.6.5} [Ender Utilities] (enderutilities-1.10.2-0.6.5.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.2.jar) 
	UCH	fe{1.2.1} [Food Expansion] (FoodExpansion1.2.3-1.10.2.jar) 
	UCH	SilentLib{1.0.12} [Silent Lib] (SilentLib-1.9.4-1.0.12-20.jar) 
	UCH	FunOres{1.2.7} [Fun Ores] (FunOres-1.10-1.2.7-68.jar) 
	UCH	simplecore{1.3.15.1} [SimpleCore API] (simplecore-1.10.2-1.3.15.1.jar) 
	UCH	simpleores{1.8.6.8} [SimpleOres 2] (simpleores-1.10.2-1.8.6.8.jar) 
	UCH	netherrocks{1.4.7.2} [Netherrocks] (netherrocks-1.10.2-1.4.7.2.jar) 
	UCH	fusion{2.1.7.2} [Fusion] (fusion-1.10.2-2.1.7.2.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	IronChest{7.0.7.795} [Iron Chest] (ironchest-1.10.2-7.0.7.795.jar) 
	UCH	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCH	am{1.5.5} [Marines Armor and Weapons] (Marines Armor and Weapons 1.5.7.jar) 
	UCH	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCH	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCH	mcmultipart{2.0.0_88} [MCMultiPart] (MCMultiPart-experimental-2.0.0_88-universal.jar) 
	UCH	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.294.jar) 
	UCH	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.294.jar) 
	UCH	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.294.jar) 
	UCH	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCH	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.10.2-1.9.20160723.0.jar) 
	UCH	natura{1.10.2-4.0.0.93} [Natura] (natura-1.10.2-4.0.0.93.jar) 
	UCH	reinforcedTools{1.4.1} [ReinforcedTools] (ReinforcedTools-1.5.0-1.10.2.jar) 
	UCH	rftools{5.08} [RFTools] (rftools-1.10-5.08.jar) 
	UCH	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.3-1.10.2.jar) 
	UCH	RTG{1.10.2} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.2-snapshot-4.jar) 
	UCH	solarvillage{1.1.0.15} [Solar Village] (SolarVillage-1.10.2-1.1.0.19.jar) 
	UCH	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCH	trashslot{6.3.2} [TrashSlot] (TrashSlot_1.10.2-6.3.2.jar) 
	UCH	tumat{1.6.0} [TUMAT] (TUMAT-1.6.0.jar) 
	UCH	weaponsplus{1.9.4-2.0.1.0} [WeaponsPlus] (WeaponsPlus1.9.4-2.0.1.0.jar) 
	UCH	xlfoodmod{1.10.2-0.1.1} [XL Food Mod] (XL Food Mod-1.10.2-0.1.1.jar) 
	Loaded coremods (and transformers): 
LoadingHook (Mekanism-1.10.2-9.2.0.294.jar)
  
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
BCModPlugin (Backpacks-Mod-by-Brad16840-1.10.2.jar)
  brad16840.common.asm.ClassTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.0.3.jar)
  
IC2core (industrialcraft-2-2.6.105-ex110.jar)
  
LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.90' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Tobi/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Tobi/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Tobi/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Tobi/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Tobi/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Tobi/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Tobi/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Tobi/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Tobi/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

as soon as i take tconstruct out of my mod folder my game starts without problems

**Comment by bonii-xx** [comment]
That's an oooold building bricks issue, has been around for quite a while. You sure you're on the last version of building bricks? Not TiC related at all though.
