### ISSUE TITLE
Cannot repair draconic evolution tools with draconium 1.7.10

### ISSUE THREAD

**Issue by SpazzMods** [SlimeKnights/TinkersConstruct#2649]
Mantle 0.3.2b
t-construct 1.8.8
DraconicEvolution 1.0.2h

![image](https://cloud.githubusercontent.com/assets/20545982/21082614/1eda0228-bfad-11e6-956b-6de85ad37b8f.png)

As you can see, nothing wants to work(even a block)
This is for a custom, public modpack, if you have any questions let me know I'll have the info

**Comment by ArukaAlter** [comment]
You can't repair tools that have full durability.
ExtraTiC is the one that adds Draconium based tools.
The tools are made and repaired with Cores, not ingots.
1.7 is no longer supported.

**Comment by SpazzMods** [comment]
The tool is currently broken, as you can see from the blunt end of the head
However I will try the Draconium core next.
