### ISSUE TITLE
Slime Islands placed before BoP surface decoration

### ISSUE THREAD

**Issue by Exsolutus** [SlimeKnights/TinkersConstruct#2650]
I found this funny little issue while inspecting my world gen setup. Attached is an image of the result. Seems to me that Slime Islands are being generated prior to BoP surface decorations, resulting in all the trees and other blocks that would have been on the ground end up on the slime island.

![2016-12-11_18 23 24](https://cloud.githubusercontent.com/assets/23705866/21084436/7d7ffaca-bfd1-11e6-86ef-689f9529b9a5.png)

**Comment by bonii-xx** [comment]
Yes, the same happens with vanilla trees. That's simply how worldgen works

**Comment by Rhuunin** [comment]
I don't want to make a redundant topic, but I feel bad for necro'ing a topic that's from last year. I'm experiencing similar world gen, except my slimy trees are not spawning whatsoever, even in the nether. I uninstalled BoP to see if the world gen noise that it makes on the slime islands was interfering to no effect. Are there any known mods that cause issues with TiC world gen?

![2017-05-18_19 45 54](https://cloud.githubusercontent.com/assets/28795527/26230011/690521b8-3c0b-11e7-9877-c58334a5c9cb.png)
![2017-05-18_20 02 26](https://cloud.githubusercontent.com/assets/28795527/26230017/7a5320a0-3c0b-11e7-9ed7-e10c1e8fcd0f.png)

**Comment by KnightMiner** [comment]
This should hopefully be fixed in 1.16 as islands now are structures, generating at the proper time. If not we can look into it again. No plans to rewrite island generation in 1.12.
