### ISSUE TITLE
[1.10.2-2.6.1] Crash when killing zombie with bolts

### ISSUE THREAD

**Issue by tgstyle** [SlimeKnights/TinkersConstruct#2652]
This has come up a couple of times, I think it was steel bolts the player used in SMP.

https://gist.github.com/tgstyle/626730749ce2751e5ce65680c40c1724

**Comment by VallenFrostweaver** [comment]
Can you provide more specific data?  What were the crossbow parts and bolt parts? Was the zombie under any effects at the time or special circumstances (poisoned/fire/drowning/etc.)?

**Comment by tgstyle** [comment]
Steel bolt, used sugar cane for shaft, and feather fletching. The crossbow was bronze, with hastest. They were in the water, the already had their life down.

**Comment by VallenFrostweaver** [comment]
I cannot reproduce this.

**Comment by tgstyle** [comment]
I finally got to do some good troubleshooting with the player this seems to happen with the most. It turned out to be any weapon not just a cross bow. So I ended up pulling mob rebirth from the server and it appears to have stopped the crashing. Thanks for your help!
