### ISSUE TITLE
I want to be able to choose how my modifiers/materials appear on the tool. I want to choose its looks!

### ISSUE THREAD

**Issue by Axiom1999** [SlimeKnights/TinkersConstruct#2654]
I'd suggest allowing us to move the modifiers around, this will allow me to have a nice silver blade but keep the beheading (beheading is ugly in my opinion). I believe the order of the modifiers does count as to how the overall weapon looks?

I realise you don't take suggestions, but you may consider it...

**Comment by bonii-xx** [comment]
Order of modifier matters, yes. You can use resource packs to modify looks. Having ingame options to change the order is not feasible on our side.

**Comment by bookerthegeek** [comment]
Wait....

So their is a difference between looting 3 then beheading vs beheading then looting 3?

**Comment by KnightMiner** [comment]
Aesthetically: yes. Functionally: no.

**Comment by bookerthegeek** [comment]
Gotcha
