### ISSUE TITLE
Crafting Station AE2 Grindstone improper access

### ISSUE THREAD

**Issue by gr8pefish** [SlimeKnights/TinkersConstruct#2656]
Minor thing.

The automatic addition of nearby inventories doesn't work quite right with AE2's grindstone.

Pictures:
http://i.imgur.com/H8V4TfO.png
http://i.imgur.com/LjzReE6.png

The localization isn't correct, and it allows you to place items inside the grindstone (which is typically impossible). Not a large deal, as there is no duping/etc, but you might want to blacklist this item from connecting (if possible).

If you have any more questions please ask and I'll clarify.

**Comment by bonii-xx** [comment]
All of the things done there are handled the same for every block. The things you're seeing are not fully/incorrectly implemented in the corresponding mod, in this case actually addition. The grindstone exposes its inventory, hence it's accessible.
