### ISSUE TITLE
extra utilities 2  and tinkers construct

### ISSUE THREAD

**Issue by gavinrobertkemp** [SlimeKnights/TinkersConstruct#2657]
hello their seem t be a bug preventing the game from ating when i use tinker contruct and extrautilities on the garden of glass.
[crash-2016-12-16_16.09.41-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/657528/crash-2016-12-16_16.09.41-client.txt)

**Comment by KnightMiner** [comment]
This is an Extra Utilities crash, I see nothing related to Tinkers there.
