### ISSUE TITLE
Crash when craft Bow limb pattern

### ISSUE THREAD

**Issue by Serico86** [SlimeKnights/TinkersConstruct#2660]
I got this crash log when i tried to craft bow limb pattern

[crash-2016-12-18_02.19.10-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/659188/crash-2016-12-18_02.19.10-client.txt)

**Comment by KnightMiner** [comment]
Does this happen without NEI?

**Comment by Serico86** [comment]
It was the latest NEI update ... I deleted it .. Now it works :) Thanks

**Comment by KnightMiner** [comment]
Closing this as NEI's fault, as it does not normally happen and NEI is known to cause issues with JEI.
