### ISSUE TITLE
Right click to place torch no longer functioning

### ISSUE THREAD

**Issue by SpartanSamuel** [SlimeKnights/TinkersConstruct#2661]
As the subject reads. I've tried a vanilla iron pickaxe and a TC full iron pickaxe. (I know the feature didn't exist for vanilla, but just to test.) To be clear, I had torches in my hotbar directly to the right of my pick as I should've.

MC: 1.10.2
Forge: 12.18.3.2185
Mantle: 1.1.3
TC: 2.6.1

**Comment by KnightMiner** [comment]
This was removed back in the update to 1.9, use the vanilla offhand.
