### ISSUE TITLE
Gases don't render correctly (in tanks and smeltery)

### ISSUE THREAD

**Issue by HenryLoenwind** [SlimeKnights/TinkersConstruct#2662]
All three tanks and the smeltery render gases the same way as liquids, i.e. neither texture nor position is flipped.

**Comment by bonii-xx** [comment]
Oh, is that default behaviour now? I suppose it makes sense.. smelteries wont support the position of course, since I'd have them automatically escape the smeltery otherwise ;P

**Comment by HenryLoenwind** [comment]
Yes, fluid blocks with isGaseous() and density < 0 do that, and it actually seems to work nicely. If really both isGaseous() and density are set, otherwise...um, not so great. ;)

Yeah, escaping gasses might be funny, but people might be upset by it *g*...
