### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Bence6** [SlimeKnights/TinkersConstruct#2663]
I Tried to Play with Minecraft but i Crashed!
Crash Report:
[crash-2016-12-19_19.09.18-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/661793/crash-2016-12-19_19.09.18-client.txt)

**Comment by ArukaAlter** [comment]
Allocate more memory to the game.

**Comment by bonii-xx** [comment]
Yup, you need more memory. You're only giving it 512MB, that's way too little for modded minecraft.

**Comment by Bence6** [comment]
It's Because of Registering Texture in The Crash Report!

**Comment by garath77** [comment]
Yes, and that happened because it ran out of memory. Edit your profile; find the Java arguments line at the bottom; change the -Xmx512M to at least -Xmx1G or half your system memory if you have at least 4GB. The more you can safely allocate, the better it will run.
