### ISSUE TITLE
Parts Builder Issue

### ISSUE THREAD

**Issue by ShdwDrgnVIIv2** [SlimeKnights/TinkersConstruct#2665]
So I am having a slight issue with TC.  I have it loaded fine, all the dependencies are in place, and it all loads up with no issue.  I go to start constructing everything; get the smelter running, build the stencil table, pattern chest, parts chest, and parts builder/table, and the tool table (or whatever it is called, but not the tool forge).  Get blank patterns, make patterns, and get ready to craft parts.  Here is where my issue starts.  The parts builder recognizes all of the materials you can use to craft.  Iron, wood, stone, etc.  However, I go to insert a pattern, and it will not let it place.  I can place a blank pattern in the pattern spot, but it will not accept any other patterns.  Is there something that I am missing or is there an issue that I don't know of since I am using 1.10.2 with the latest files for each of the components?

**Comment by TherminatorX** [comment]
Duplicate issue, see #2634
