### ISSUE TITLE
Luck hammer only works if main block can be be lucked

### ISSUE THREAD

**Issue by Xuerian** [SlimeKnights/TinkersConstruct#2666]
Hit stone beside coal, always one coal.

This seems connected to hammers calculating break speed off the central block's hardness, which is a nice side effect but I'd rather not have to mine at 1/4 hammer speed so as to not waste diamonds/etc.

**Comment by TherminatorX** [comment]
Versions?

**Comment by Xuerian** [comment]
Sorry, 1.10.2-2.6.1

Though this behavior seems to have been around for a while IIRC

**Comment by bonii-xx** [comment]
Seems to work perfectly fine, maybe you just got bad RNG.
