### ISSUE TITLE
Conflicting Potion ID's with Vanilla Minecraft

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [SlimeKnights/TinkersConstruct#2668]
Hello all I have been running into an issue of conflicting Potion ID's with Vanilla Minecraft. The only mods I have loaded are Tinkers Construct and Anti ID conflict (and the neccessary forge and mantle components) on the latest version of Forge, 2185 (might I mention that I've been getting this issue on every version of Forge ive tried) 

[crash-2016-12-20_14.05.24-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/664431/crash-2016-12-20_14.05.24-client.txt)

While Im aware that Anti ID conflict is crashing the game, playing the game for about 30 seconds results in a Concurrent entity tick exception and it crashes on its own. I honestly have no idea what is causing this and I have tried many things. The "conflicting" ID's also seem to change around every launch.  Any help would be appreciated. 

PS. This also comes up on Immersive Engineering, Hermit Quest, Natural Absorption, and Future Pack. I only posted here because Tinkers is the one I want most :(

**Comment by bonii-xx** [comment]
Potion IDs are managed by forge, just like block and item ids. Remove the anti id thingie, there are hardly any things left that can have conflicting IDs.
