### ISSUE TITLE
Alternative for Aluminum / Aluminum Brass

### ISSUE THREAD

**Issue by AlHollandiyah** [SlimeKnights/TinkersConstruct#2669]
This is more of a feature request but I didn't know a better place to post this:

As it currently stands I totally understand the decision to cut down on ores in the mod and add support for them, as it is probably a whole lot less work to update and ores are found plentiful in other mods. Especially copper and tin is usually available in a handful of variations if you play with bigger modpack.

However, to get aluminum the options are VERY limited. There is no smaller mod that adds it, you have to resort to something huge like Immersive Engineering, which will add a big load to an already big modpack. Besides that to me personally it feels too much off for minecraft.

Therefore I would like to ask for a feature where either only aluminum is added back (because it is so rare) or there is an alternative receipe to aluminum brass, maybe something with tin instead? Because among others I always used aluminum brass for casts so I could use the gold I found for other important purposes.

I hope that this is something you guys can consider, however I totally understand if you decide not to as you probably have a clear vision of where you want the mod to go. I just wanted to suggest it and the rest is up to your team! Thank you very much for taking the time to read this!

**Comment by KnightMiner** [comment]
We have already stated several times that aluminum will not return. A lack of mods using it is exactly the reason you don't need it in Tinkers, as an ore for the rare creation of casts is useless. An alternative recipe would also not work as it is no longer aluminum brass then, tin and copper is bronze.

Clay is available as an option, use that. Or if you must have aluminum ore, install one of the many generic ores mods that simply add ores.
