### ISSUE TITLE
EFLN dropping original block, not proper "drop"

### ISSUE THREAD

**Issue by WesCook** [SlimeKnights/TinkersConstruct#2670]
In some cases this works correctly, such as the EFLN getting cobble from stone, or gems from Diamond/Lapis ore blocks.  In others however it seems to not respect the proper block drop.

Specifically the dense ores from WTFExpedition seem to have this problem.  Dense ore are special blocks can be be mined multiple times, and drop their corresponding ore.  eg. Dense iron can drop up to three vanilla iron ore.

Dense ore is normally mined with a pickaxe, and works the same way with silk touch.  EFLN however drops the original "dense ore" block, which isn't supposed to be obtainable.

I'm assuming this is a result of the way EFLNs do ore drops as other modded explosions (eg. mining charges, or mining TNT) seem to work with this block correctly.

**Comment by bonii-xx** [comment]
They don't do any of that sorts, they just tell the block to drop, like other explosions: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/gadgets/entity/ExplosionEFLN.java#L111

**Comment by WesCook** [comment]
I'll talk to WhiskeyTangoFox about it then, thanks.

**Comment by WesCook** [comment]
The issue was semi-fixed on WTF's end.  It doesn't look like there's any further changes planned, so I'll close the bug on this end as well.

It's worth noting that the EFLN still has different behavior than other modded TNTs (eg. Mining Charge from BetterWithMods, or Mining TNT from ImprovingMinecraft).  So that might be of interest later on.

This particular quirky behavior appears to be on Expedition's side though, so I'll close this for now.
