### ISSUE TITLE
Copper's well-established modifier applying to blocks broken by another tool

### ISSUE THREAD

**Issue by timotree3** [SlimeKnights/TinkersConstruct#2671]
Modpack:direwolf20 1.10.2
During a Livestream the steamer switched to a copper tool after mining something with the lumber axe and it dropped XP when it shouldn't have.
Recording:
https://clips.twitch.tv/bacon_donut/RealYakPanicBasket

**Comment by Elvarion** [comment]
Starting to cut down a tree with a Lumber Axe that does not have the Well-Established modifier and then switching to any other tool that does have the Well-Established modifier will apply the modifier to the blocks being broken by the lumber axe effect.

- TConstruct-1.10.2-2.6.1
- Mantle-1.10.2-1.1.3

**Comment by timotree3** [comment]
Is this intentional?

**Comment by MightyCupcakes** [comment]
Don't think so. The modifier uses the block break event to drop exp so if you switch to a tool with the modifier while a block is being broken will trigger the drop.

**Comment by bonii-xx** [comment]
It's not intentional, but it's also highly nontrivial to fix, since it basically goes against everything events rely on. We'll just have to live with it I guess ;)
