### ISSUE TITLE
Opinion & Bug report

### ISSUE THREAD

**Issue by MrConfy** [SlimeKnights/TinkersConstruct#2672]
Minecraft Forge v. 1.10.2 - 12.18.3.2185
Mantel v. 1.10.2 - 1.1.3
TConstruct v. 1.10.2 - 2.6.1

Cleaver Not blocking. Makes action loop but doesn't block damage.

Also vanilla shield has no effect in offhand with weapons that have special abilities. Special abilities overwrite shield block. It would be better if offhand shield overwrites special ability making the weapons abilities only usable with no offhand shield.

**Comment by ArukaAlter** [comment]
The Cleaver making you not block damage is intended, it is listed in the weapon's description.
Minecraft tries to use whatever is in your main hand before using the offhand, it's just how it works.

**Comment by KnightMiner** [comment]
The cleaver blocks the offhand ability, it is intended

We are not going to override vanilla mechanics, if you want the offhand ability, use a weapon such as a hatchet or broadsword that has no right click action.

**Comment by MrConfy** [comment]
cleaver doesn't block even if used alone. previous version 1.7.10 had blocking ability. I disregard offhand overwrite (my mistake in that part)

**Comment by LovelyFlare** [comment]
It's not supposed to at all.  This is intended.

**Comment by MrConfy** [comment]
ok got it.

**Comment by KnightMiner** [comment]
The cleaver and the broadsword both lost the blocking from 1.7 as the vanilla sword lost blocking. The battle sign only kept it as it made it a more unique weapon (as before it was primarily a weaker broadsword)

**Comment by MrConfy** [comment]
ok, just as a final. Is there a way to disable the loop for when you right click with it?

**Comment by KnightMiner** [comment]
Loop when you right click it?

**Comment by bonii-xx** [comment]
That'd be vanilla minecraft being vanilla minecraft.

**Comment by MrConfy** [comment]
trying to make a gif but gyazo is a little rascal and doesn't want to cooperate.

**Comment by bonii-xx** [comment]
I know what you mean. But as I said, that's simply how vanilla minecraft handles it.
