### ISSUE TITLE
[BUG] Tools duping Pistons

### ISSUE THREAD

**Issue by MrZantag** [SlimeKnights/TinkersConstruct#2673]
Modpack: Direwolf20 1.10.2 version 1.1.4
Tinkers' version: TConstruct-1.10.2-2.5.6b

https://gfycat.com/BraveMedicalGannet

When breaking pistons with a Tinkers' tool for the second time, The pistons broken are duped. As seen in the gif, I broke 9 pistons and got 9 back. Then I broke them again and got 18 back. 

Specs of Hammer:
![image](https://cloud.githubusercontent.com/assets/17109494/21468540/b1f9e8d4-c9e4-11e6-912e-ea9d409de347.png)

in the gif I use my hammer but I can do the same thing with my pickaxe. 
Specs of Pick I used: 
![image](https://cloud.githubusercontent.com/assets/17109494/21468542/e08eae14-c9e4-11e6-8d0c-ccfc37978f48.png)

**Comment by LovelyFlare** [comment]
Can you reproduce this with just Tinkers', Forge and Mantle?

**Comment by MrZantag** [comment]
With just those mods I couldn't in a single player world. I also learned after posting this that other players on my server couldn't see the duped pistons if they were built. 

I originally noticed this after I put accidentally put a piston up next to an Immersive Engineering Metal Press. Specifically I put it next to where the piston goes in the multi-block. After testing in a Single Player world with only Tinkers', Forge, Mantle, and IE I was unable to replicate the bug. 

The only thing I can think is that it's something with multiplayer or Tinkers' isn't the root cause. Sorry posting a seemingly unreplicable bug.

**Comment by bonii-xx** [comment]
Sounds like something is manipulating the dropped itemstacks clientside. I can pretty much rule out that it is caused by TiC itself.
