### ISSUE TITLE
crash on  Rendering screen (AbstractTab.java:39) while using tinkers tools with Custom NPCs mod

### ISSUE THREAD

**Issue by PrinceOfAmber** [SlimeKnights/TinkersConstruct#2674]
http://pastebin.com/6qXgByje

I was testing out the new CustomNPCs_1.10.2(20nov16).jar and this happened

Problem seems to be in at tconstruct.client.tabs.AbstractTab.func_146112_a(AbstractTab.java:39)

**Comment by KnightMiner** [comment]
You do not have Tinkers Construct installed according to the log, or if you do its an unofficial build. Also, that crash is coming from the wrong package for 1.10.2 Tinkers, so it's definitely not our issue as we no longer have that class. Some other mod is shipping classes in the old Tinkers package, so I guess uninstall whatever mod is giving you Tinkers tools and download the official build from curseforge.

**Comment by bonii-xx** [comment]
There were some mods that used (and shipped) TiCs inventory tabs for compatibility purposes. We don't use them anymore in 1.10. Also yes you don't even have TiC in that pack.
