### ISSUE TITLE
Problems With Crossbow Bolts

### ISSUE THREAD

**Issue by thebagelgod** [SlimeKnights/TinkersConstruct#2675]
When trying to make a bolt, putting a tool rod onto the casting table does not allow me to pour any kinds of metal onto the tool rod. Nothing pours. Id really not like to cheat them in to get my ammo

**Comment by Elvarion** [comment]
In the newer versions of Tinkers Construct there is a new item called Arrow Shaft. You use these instead of the Tool Rods to craft bolts. For more information id suggest you check the book provided by the Mod ingame.

**Comment by bonii-xx** [comment]
Read the book.

**Comment by killerjerick** [comment]
Cannot figure out bolts for the life of me, book says absolutely nothing example here:
http://i.imgur.com/2aqAWG4.png
http://i.imgur.com/bCG8f8A.png

**Comment by Elvarion** [comment]
Could have sworn there was a page that explains this, But I cant seem to find it.

But you craft an Arrow shaft, then place it in the casting table and pour metal on it to create a bolt. Then you give it a fletching.

**Comment by killerjerick** [comment]
Thanks finally figured it out through trial and error, nothing in the book, read it from cover to cover.

**Comment by laz2727** [comment]
That's because it's near the beginning. Makes a lot of sense, i know.
