### ISSUE TITLE
Unable to open any gui

### ISSUE THREAD

**Issue by XenoStone1009** [SlimeKnights/TinkersConstruct#2676]
Attempting to open any tinkers construct gui (tool station/crafting station/etc) doesn't yield any gui.
I am unsure what is causing this, but here is the modlist:
http://pastebin.com/CpJ1XS5N

**Comment by XenoStone1009** [comment]
Edit: Tinkers was just the first mod i noticed, but now i see that its any modded gui i cannot open. And idea which mod might be causing this?

**Comment by bonii-xx** [comment]
Check your log if something throws errors when you try to open a GUI, that's usually the cause as well as the culprit. Anyway, definitively not TiC.
