### ISSUE TITLE
Diamond does not work on green slime pickaxe 

### ISSUE THREAD

**Issue by malakai97** [SlimeKnights/TinkersConstruct#2679]
Reproducible with just curse/forge, MC 1.10.2, and TC.  Is this intentional?

**Comment by bonii-xx** [comment]
You're probably missing a free modifier. Diamonds can be put onto any pickaxe.

**Comment by malakai97** [comment]
I should have been more specific; I an apply the modifier, it just doesn't change the mining level.  This is consistent with what the Tool Station shows.

**Comment by bonii-xx** [comment]
Screenshot

**Comment by malakai97** [comment]
![tc_slime_diamond_bug](https://cloud.githubusercontent.com/assets/3486429/21518461/38506c90-ccac-11e6-9e7c-35e3176058d5.png)

So the finished tool is the same as what the tooltip shows.  This also occurs with magma slime and blue slime.
