### ISSUE TITLE
Crafting Station Internal Excpetion

### ISSUE THREAD

**Issue by checkium** [SlimeKnights/TinkersConstruct#2683]
Minecraft: 1.7.10
TConstruct: 1.7.10-1.8.7
![image](https://cloud.githubusercontent.com/assets/9268058/21524926/90bf82b6-cd11-11e6-8616-17edc4db7153.png)

**Comment by KnightMiner** [comment]
Sorry, 1.7.10 is no longer supported. Looks like something sent an invalid packet, but it's hard to tell.

**Comment by checkium** [comment]
@KnightMiner It happens when you try to craft a piston, other items works well. You can put the items with no problem, but when you remove the piston from the crafting result, it crashes everyone on the server.

**Comment by LovelyFlare** [comment]
I've crafted pistons in the 1.7.10 versions fine in crafting stations without any crashes.

**Comment by checkium** [comment]
I just found the problem, it was caused by a conflict between OC and MorePistons, that broke MorePistons oredict, wich broke the crafts.
