### ISSUE TITLE
[Question] Is the door really a thing ?

### ISSUE THREAD

**Issue by Bennyboy1695** [SlimeKnights/TinkersConstruct#2684]
So on quite a few streams where tinkers is used, alot of the streamers will put a door infront of the controller and say that the door speeds it up because it keeps the heat in. My question is, is this really a thing ? And if it isnt is there anyway to make it a thing as i actually really like the idea of if the "heat" particles can't escape then it stays hotter and therefor faster.

**Comment by ArukaAlter** [comment]
What? No

**Comment by bonii-xx** [comment]
That is.. hilarious. I need to write that down somewhere

**Comment by Bennyboy1695** [comment]
It is funny when people fall for it, i've made my friends fall for it a few times. It seems like quite a cool feature though, anyway it could actually be added to the coding ?

**Comment by Elvarion** [comment]
Would have been an awesome aprils fool patch, shame its so far away :smile: 

TConstruct-1.10.2-2.6.2
- Added several new metal doors. Can be crafted as regular doors.
- New heat mechanic. Placing a door in front of the Smeltery Controller will speed up smelting. Different doors give different speeds.
- Creating a 2x2 Smeltery with trapdoors placed at the top will create a new type of Smeltery that boils ores at a slower speed but will yield thrice the amount of ores.

**Comment by bonii-xx** [comment]
Gonna close this since it's not actually an issue and we're not gonna implement anything like that anytime soon ;)
