### ISSUE TITLE
1.10.2 Crash when tinkerstools are disabled

### ISSUE THREAD

**Issue by darklordwonton** [SlimeKnights/TinkersConstruct#2685]
Crash report: http://pastebin.com/NqVQJRLn

**Comment by KnightMiner** [comment]
I can confirm the crash happens. It is luckily a pretty easy fix, though I want to double check how much of the method that causes the crash shouldn't run if the module is not loaded.

**Comment by bonii-xx** [comment]
The real question is.. do we really want to allow the deactivation of that module? While things where written with that in mind.. it still opens up a huge can of worms and we can't really support it.

**Comment by Myzoni** [comment]
@bonii-xx I feel as if you should make it configurable. Some players/modpack makers like to use tinkers not for the actual tools but for the smelter.

**Comment by KnightMiner** [comment]
This specific case has been patched to no longer crash, but there are no guarantees that there will not be other issues with disabling the tools module, since it is kinda the core of the mod.

**Comment by bonii-xx** [comment]
To make it clear: We'll leave the option to disable them, but it's basically "use at your own risk".
