### ISSUE TITLE
[1.10.2] WorldEvents.extraSlimeSpawn Lag

### ISSUE THREAD

**Issue by Tencao** [SlimeKnights/TinkersConstruct#2686]
So I've noticed on my server that a large amount of lag is been produced, and after taking some timings, it appears that alot of it is coming from WorldEvents.extraSlimeSpawn. I'm not sure what part of this code causes so much lag, but it does.

Timing for reference
https://timings.aikar.co/v2/?id=4cac868571414726aad2eaa2442de47d&section=all

Sponge version used
1.10.2-2171-5.1.0-BETA-2010

Forge version
1.10.2-12.18.3.2185

Tinkers version
1.10.2-2.6.1

**Comment by LovelyFlare** [comment]
Can you reproduce this on a normal forge server?

**Comment by bonii-xx** [comment]
Do you have a world save + coordinates which chunks need to be loaded for it to happen?

**Comment by Tencao** [comment]
I'm currently debugging this myself too, if I find anything worth pointing out I'll report my findings here

**Comment by bonii-xx** [comment]
Hm, when I wrote that I checked that stuff and I think the world data was cached. Maybe sponge does something with it that causes it to not be cashed, because then the lookup would probably become pretty slow.

**Comment by bonii-xx** [comment]
Try loading the world on a plain forge server and see if it still happens
