### ISSUE TITLE
1.10.2 [Suggestion/Mod Compatability] Substratum liquid redstone/glowstone/enderpearl

### ISSUE THREAD

**Issue by Dragnier** [SlimeKnights/TinkersConstruct#2688]
Allow these items to be smelted into their Substratum liquid counterparts and alloying for the various alloys they can be used to create. Especially since Extreme Reactors now recognizes these liquids as coolants.

**Comment by bonii-xx** [comment]
We only support the basic common molten metals that TiC makes use of. It's on the mods to integrate.
