### ISSUE TITLE
1.10.2 In Game Crash (Client) due to Lycanites and Tconstruct!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SlimeKnights/TinkersConstruct#2690]
https://github.com/Lycanite/LycanitesMobs/issues/194

**Comment by KnightMiner** [comment]
What were you doing before the crash?

**Comment by P3rf3ctXZer0** [comment]
Breaking a tree and and Lycanites called the "ent" mob.

**Comment by bonii-xx** [comment]
Looks like it's a known issue of the mod, the erroring call is in their code either way, gonna close this therefore.
