### ISSUE TITLE
Crafting Station doesn't return empty buckets

### ISSUE THREAD

**Issue by BloodWorkXGaming** [SlimeKnights/TinkersConstruct#2691]
* MC Version: 1.10.2
* Forge Version: 12.18.3.2185
* Tinkers Version: 2.6.1
* Description:
Crafting something in the Crafting Station that would normally return an empty bucket, like mystical agriculture water seeds or actually additions slime voids the bucket and uses it up.
However other recipes like pam's juicer won't get used up.

[Video showing it](https://youtu.be/FFet48GPwAM)
[Another video](https://youtu.be/-NS-Gm-tPrc)

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and such a recipe/mod with such a recipe. No other mods, especially not clientside.

**Comment by BloodWorkXGaming** [comment]
Mhh you are right, with all other mods removed I am getting the empty bucket back.
Any idea what other mod could be causing that?

**Comment by bonii-xx** [comment]
Another mod ;o
I'd try one of the clientside mods, like the one that adds all those buttons etc.

**Comment by BloodWorkXGaming** [comment]
So I tested around a bit, it was none of the Client Mods, that added the crafting Buttons, nor was it JEI...
The modpack I tested it with All The Mods 1. Don't really wanna go though all 160 mods one by one and test it out, sorry.

**Comment by KnightMiner** [comment]
You don't have to, remove half the mods and test it. If it still happens, you just eliminated 80 mods that are not the problem, if not the half you removed likely contains the issue. You can keep doing this until you isolate the mod.

**Comment by BloodWorkXGaming** [comment]
Found it...
It is the calculator mod:
[https://github.com/SonarSonic/Calculator](https://github.com/SonarSonic/Calculator)

I don't even know why it should have anything to do with the crafting station...

**Comment by bonii-xx** [comment]
It has caused several problems with different TiC things already. I don't wanna know how much coremodding that thing does.
