### ISSUE TITLE
Add info about number of items required for modifiers to the manual

### ISSUE THREAD

**Issue by aradian** [SlimeKnights/TinkersConstruct#2693]
It would be nice if the modifier pages in the manual displayed the number of items required (if more than one).

For example, I was confused as to why I couldn't add the "fins" modifier to some arrows until I found the commit here which changed it to two fish required.

**Comment by KnightMiner** [comment]
In most cases, such as with blasting, we have simply used separate slots for multi-item, single use modifiers, so I guess we never noticed it did not display stack sizes properly.

**Comment by bonii-xx** [comment]
If the manual doesn't display 2 fish then the modifiers items aren't registered correctly. It's intentional that a modifier only requires a stacksize of max. 1 per slot.

**Comment by aradian** [comment]
This is the commit I mentioned above related to the fins modifier:
a778b112aacb2f8b3526a272533f062e24a303f4

**Comment by bonii-xx** [comment]
It's actually a bug in how the data structure returns its data. Fixed in the next mantle release with https://github.com/SlimeKnights/Mantle/commit/f77a8cdd6d5bf788781a9a8d207f7341de726043
