### ISSUE TITLE
[Crash] Ticking Arrow

### ISSUE THREAD

**Issue by Dragnier** [SlimeKnights/TinkersConstruct#2694]
Here is the crash log:
https://gist.github.com/Dragnier/6c82c53378fecdd665e71bec20db5fb4

**Comment by bonii-xx** [comment]
>	at com.thexfactor117.levels.leveling.AbilitySelection.getRandomizedAbilities(AbilitySelection.java:38)

Not TiC.

**Comment by Dragnier** [comment]
Ok, didn't see that. Will post for them.
