### ISSUE TITLE
[Enhancement] Make Crafting Station work more like Table

### ISSUE THREAD

**Issue by copyyy** [SlimeKnights/TinkersConstruct#2695]
I think it would make more sense if the Crafting Station was working more like the vanilla Crafting Table.
If you shift-click an itemstack in your inventory while having the Table GUI open, the stack moves into the hotbar. If you hold W and then press on the itemstack, it moves into the Crafting Table. Same counts for the Inventory GUI: Shift-Clicking only moves itemstacks between inventory and hotbar, w+click to the "inventory" above it, s+click to the inventory below it (2x2 crafting top, inventory, hotbar).

Wouldn't it be better to have the same keys working in the Crafting Station so new people don't get confused?
I cannot use the W-click and S-click in the Crafting Station and shift-clicking moves the itemstack into the Station which is way different from what people are used to from the Crafting Table.
Of course, I can understand if you say that this is an improvement, but I'd prefer shift-clicking between inventory/hotbar and W-/S-Click to move the stacks between crafting grid, inventory and hotbar.
Just because I'm used to do so from the Crafting Table and the vanilla Inventory with its 2x2 crafting grid.
(As a quick side note: The missing W-/S-Clicking funtionality has been bugging me for years, sadly I've always been too lazy to report it lol)
Hope there isn't an issue about this already, didn't manage to find one.

**Comment by bonii-xx** [comment]
W/S click....?

**Comment by copyyy** [comment]
Literally the second I edited that you commented...
Sorry about that, I just got too used to using InvTweaks, didn't know that wasn't a vanilla feature lol
Just dump this into the closed section...

**Comment by bonii-xx** [comment]
Kay
