### ISSUE TITLE
Part Builder Not Accepting Stencil Patterns

### ISSUE THREAD

**Issue by ViperZeroOne** [SlimeKnights/TinkersConstruct#2696]
When attempting to build a part in the Part Builder, completed stencils (ex. tool rod pattern) can not be placed in the stencil slot.  They can be placed in the "material" slots above/below the inserted material, but you get no output that way.  The stencil slot of the Part Builder does, however, accept blank stencil paper.  There is no error in either the client or server logs when you attempt to place the stencil in the Part Builder.

Forge-1.10.2-12.18.3.2185
TConstruct-1.10.2-2.6.1

Let me know if there's any other info you might need.

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by lonissa** [comment]
I can confirm that this is an issue with the only the following mods installed:

TConstruct-1.10.2-2.6.1
Mantle-1.10.2-1.1.3

Forge 12.18.3.2185

Unable to place a pattern in the part builder.

**Comment by bonii-xx** [comment]
Update forge, see #2634

**Comment by lonissa** [comment]
I updated forge to 12.18.3.2202 and the part builder will still not accept any patterns.

**Comment by ViperZeroOne** [comment]
Yea, closed a little prematurely.  We're still experiencing the same issue with the latest Forge.
