### ISSUE TITLE
Stone Sharpening Kits to Seared Stone

### ISSUE THREAD

**Issue by Zedrimar** [SlimeKnights/TinkersConstruct#2700]
Not sure if this is a bug or intended feature but stone and cobble only converts to 72 Mb like it should but a stone sharpening kit which costs 2 stone or cobble to make turns into 288 Mb or one whole seared stone in the smeltery. This is not really a problem though as stone is cheap anyway but I am wondering though.

**Comment by bonii-xx** [comment]
Hm, I wonder if the same is true for other stone parts then

**Comment by Zedrimar** [comment]
@bonii-xx it is true, all of the parts aside from the raw materials give twice as much as they are worth.. (just went and looked a few minutes ago)

**Comment by Zedrimar** [comment]
probably because the amount of material required per ingot being 144 mB it calculates that with the stone parts as well... Was it supposed to be 2 stone per seared stone or 4?
