### ISSUE TITLE
Smeltery Controller has maximum height restriction ?

### ISSUE THREAD

**Issue by Etheras** [SlimeKnights/TinkersConstruct#2701]
In a modded world i'm playing, if the smeltery is placed more than 10 blocks above the "base" it doesn't detect a valid structure. Dimension is the deep dark. When the structure is valid it detects the complete 100 block height. Wondering if intended. Tried turning on debugging module, console doesn't show anything.
![2017-01-05_00 44 18](https://cloud.githubusercontent.com/assets/3217595/21662066/659e5736-d2e0-11e6-841e-84780bc58a51.png)
![2017-01-05_00 44 25](https://cloud.githubusercontent.com/assets/3217595/21662064/6598b344-d2e0-11e6-813b-6d7e9cf601fb.png)
![2017-01-05_00 44 48](https://cloud.githubusercontent.com/assets/3217595/21662065/659a765c-d2e0-11e6-88e0-81f46e968050.png)
![2017-01-05_00 45 04](https://cloud.githubusercontent.com/assets/3217595/21662067/65a24792-d2e0-11e6-90cf-1ecb114630d0.png)

**Comment by bonii-xx** [comment]
Could potentially be due to how the check is done, but it's hard to tell from your screenshots. How exactly is the build set up? In general for big smelteries you probably want to make them bigger than 3x3 rather than higher, due to how Minecraft works.

**Comment by Garonne** [comment]
I usually upgrade to 5x5 smelteries or even 7x7 being 3-5 blocks high.

**Comment by everseeking** [comment]
I just had a 3x3, 3 high (interior) with the controller at the top level - worked fine. Added a bit of height making the interior 14 high - controller no longer works on top level. Works 5 levels down with 14 height.

* [Does not work](http://i.imgur.com/5ImNr19.png)
* [Works](http://i.imgur.com/u6bxlWx.png)

**Comment by KnightMiner** [comment]
Appears to be the same as #3024, so closing since that one is the one linked with the commit improving this.
