### ISSUE TITLE
Bow / Longbow Animation bugged

### ISSUE THREAD

**Issue by ikarosixteen** [SlimeKnights/TinkersConstruct#2702]
The bows animations are look strange here are some screenshots to show you what I mean.
[https://goo.gl/photos/EVh1coTazqEvkkXM8] 
[https://goo.gl/photos/HiPDyAox64aK8mif9]

**Comment by KnightMiner** [comment]
Does this happen without a resource pack? Also, what exactly is the issue you are pointing out? All I see is an issue with your resource pack rotating the arrow.

**Comment by ikarosixteen** [comment]
yes without resource pack as well

**Comment by KnightMiner** [comment]
Then answer my second question

**Comment by ikarosixteen** [comment]
I guess I have to rotate the default & resourcepacks arrow to get them to work with the mod.
thank you for the advise.
