### ISSUE TITLE
Part Builder not Accepting Patterns

### ISSUE THREAD

**Issue by ViperZeroOne** [SlimeKnights/TinkersConstruct#2703]
Refer to issues #2696 (closed) and #2634 (closed).  Utilizing the information provided, we've tested this issue with the following versions;

TConstruct 1.10.2-2.6.1
Mantle 1.10.2-1.1.3
Forge 1.10.2-12.18.3.2202

The problem is still occurring.  We're not sure why the problem suddenly resolved itself for another individual, but updating Forge didn't fix the identical problem on our end.  Supposedly using an earlier version of Forge also fixes the problem, however that isn't a compatible work-around for the mod pack we intend to build.

Please take a closer look at this problem.  There has to be a reason the slot accepts blank pattern pages but won't accept completed patterns.

**Comment by bonii-xx** [comment]
Works perfectly fine, using those versions. It also seems to work perfectly fine for pretty much everybody else, save for a few exceptions. Maybe it's your java version or something? OpenJDK?

**Comment by ViperZeroOne** [comment]
Our dedicated server is running Java 1.8.0_71 on Windows Server 2008.  We've also got a test machine running Java 1.8.0_45 on Windows 10 that had the same issue.  We updated that test system to 1.8.0_111 and it's still not working.  Blank pattern can be inserted but other's can't be added.

What are you referring to when you say "partbuilder buttons"?  Our partbuilder interface doesn't have any buttons on it.

**Comment by bonii-xx** [comment]
I can confirm that it happens in your modpack, however it's definitively not TiCs fault. It works fine with the buttons though. Place a pattern chest so that it touches both the partbuilder and stenciltable and add a crafting station somewhere.

**Comment by ViperZeroOne** [comment]
That's really interesting.  I wonder what's causing the same issue to occur in our test build with just TiC and Mantle.  Anyway, the buttons did show up after arranging the tables in a cross (pattern chest center, crafting table & TiC tables surrounding).  It will function that way, so we're good until whatever conflicting mod is causing the issue gets their act together.  Thanks for taking a look at the problem, I really appreciate it.

**Comment by Garonne** [comment]
The crafting table doesn't have to touch the chest. Only needs to be connected to the row of tinkers blocks. Only the chest needs to touch the part builder. I usually place the blocks in a row from stencil table, part builder, tool station/forge with the chest behind the part builder. Works as well though placing the chest actually in between the stencil table and the part builder might have its uses... I tend to remove the stencil table as soon as I do have all stencils done though...

**Comment by KnightMiner** [comment]
@ViperZeroOne can you still reproduce this in the latest TiC build? I have never personally seen the issue.

**Comment by KnightMiner** [comment]
Closing for lack of response
