### ISSUE TITLE
Server crash when flying through RFTools generated dimension

### ISSUE THREAD

**Issue by SythsGod** [SlimeKnights/TinkersConstruct#2704]
Case:
Player flying through RFTools generated dimension.

Dimlets:
Void, Nether Fortress

Crash Log: https://hastebin.com/kokovuyoxe.scala

It mentioned the Tinker's Construct Slime Dirt block, so I figured I should be posting it here.
If not, please tell me where I should have posted it instead.

**Comment by KnightMiner** [comment]
Yep, we seem to be passing the wrong blockstate to isOpaqueCube, and chisel expects its own blockstate (a valid expectation).
