### ISSUE TITLE
Firewood Lumber axe and mechanical user extra utils 2

### ISSUE THREAD

**Issue by knubbis93** [SlimeKnights/TinkersConstruct#2705]
when i use a firewood lumberaxe in a mehcanical user from extra utils 2 it dosnt smelt the wood it just drops it as normal wood but when i do it by hand it does drop charcoal so why is this happening?

im using latest tinkers construct

**Comment by bonii-xx** [comment]
Looks like XU2s mechanical user doesn't use a player. It requires a player to work since otherwise the item that was used to harvest isn't known, hence no autosmelt there.
