### ISSUE TITLE
Crash when pulling from side of casting table

### ISSUE THREAD

**Issue by xSparky911x** [SlimeKnights/TinkersConstruct#2706]
Forge 2202
Tinkers Construct 2.6.1
Integrated Tunnels 1.0.3
Integrated Dynamics 0.6.6

I set up an Importer from the Integrated Tunnels mod between a Tinkers smeltry casting table (with ingot cast) and a Crystal Chest. As soon as I added a variable card to the importer connector that was attached to the side of the casting table the game crashed.

I was asked to also post this bug here from here https://github.com/CyclopsMC/IntegratedTunnels/issues/10

http://pastebin.com/QzRpnKdz

**Comment by KnightMiner** [comment]
Yep, I can confirm we are sending null as a side for the inventory wrapper, I wonder what should be used instead since we use the same wrapper for all sides. Maybe we just need to extend SidedInvWrapper to respect hopper logic but not NPE for the hashcode.
