### ISSUE TITLE
Crash when adding Tinkers Construct with Extra Utilities 2

### ISSUE THREAD

**Issue by Malus-Lupo** [SlimeKnights/TinkersConstruct#2709]
Happens only when I enable tinkers construct with extra utilities 2 already enabled and try to run the game.
[crash-2017-01-08_11.08.54-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/692263/crash-2017-01-08_11.08.54-client.txt)
Reported to both extra utilities and tinkers construct.

**Comment by KnightMiner** [comment]
Duplicate of #2680.
