### ISSUE TITLE
Tinkers Construct 1.8.1S for minecraft 1.7.10 crashing when opening smeltery controler GUI

### ISSUE THREAD

**Issue by The-Unnamed-Engineer** [SlimeKnights/TinkersConstruct#2710]
Whenever I open the Tinkers construct smeltery my game crashes and has comething about an issue creating a fluidstack for null fluid. I have pasted my crash report here. I am not sure what is causing this or if this issue has already been reported. but here it is. http://paste.ee/p/8nFPm

**Comment by ArukaAlter** [comment]
If it can't be reproduced in 1.10, it's not valid.

**Comment by KnightMiner** [comment]
First off, why are using such an old version? The latest for 1.7.10 is 1.8.8, use that and I'll bet your crash was already fixed.

Secondly, 1.7.10 in general is no longer supported.
