### ISSUE TITLE
improper block math on smelting obsidian parts

### ISSUE THREAD

**Issue by jdratlif** [SlimeKnights/TinkersConstruct#2712]
I made some obsidian large plates by mistake (two of them). I went to melt them back in the smeltery, but ended up with only 8 blocks of obsidian rather than the 16 it took to make them. Is this an expected penalty?

MC 1.10.2
Forge 2185
Tinkers 2.6.1
Mantle 1.1.3

Thanks.

**Comment by ArukaAlter** [comment]
Obsidian in the smeltery counts as two pieces of material per block, in the part crafter it counts only as one.

**Comment by jdratlif** [comment]
So, yes, it is an expected penalty? A tool part that costs 8 obsidian blocks to craft should yield back only 4 in the smeltery?

I'm fine if this is expected and desired behavior by the development team; I just want to be clear.

**Comment by ArukaAlter** [comment]
The efficient way to craft obsidian parts is to smelt the obsidian blocks then cast them, the part builder is simply inefficient.

**Comment by bonii-xx** [comment]
Yes, this is intended. Casting obsidian parts is more efficient than crafting them.
