### ISSUE TITLE
[Suggestion] 1.10.2 Boats?

### ISSUE THREAD

**Issue by VallenFrostweaver** [SlimeKnights/TinkersConstruct#2714]
A few thoughts on how to make Tinkers' even better with boats:

1. When a player (or 2) in a boat land on a slime block they are as slippery as ice and cause the boat to bounce with it's occupants.

2. If hit with a Tinkers' weapon while in a boat with either the 'Shulking' or 'Knockback' effect it effects the boat and all players/mobs in it causing a float or knockback effect.

3. Slime blocks can be used as a super lubricant for boats and players can even jump with the boat while on them - perhaps making a special slime boat to allow this?  I'm thinking like you can jump in Mario Kart style.

The slime boots and slime sling along with boats on ice in 1.10.2 are an extreme amount of fun. Combining them would only ensure a massive increase in fun factor for Tinkers' Construct modpacks and I can see a ton of mini games from it as well. I can only hope that this is even feasible and not a huge undertaking as I fear it would be.  Either way, these are only suggestions.  Thanks for a great mod. :)

**Comment by LovelyFlare** [comment]
Suggestions are rarely accepted and also there are other things on focus at the moment.

**Comment by Garonne** [comment]
Though I do like the idea of adding some tinkers-stuff, I'm not sure about the stuff mentioned above.

I would not mind having tinkers boats though. Would definitely add some style. Though I'd prefer getting the still missing stuff from 1.7 back into 1.10 (throwing knives, javelins, ...) and adding some more stuff from the tools section (like shears maybe) before adding boats.

**Comment by bonii-xx** [comment]
What you're suggesting are not boats, but interaction with boats. Wording is important ;P

Sounds like a few fun things, but I'm not even sure if they're doable considering how vanilla movement works. Maybe I'll do some fitting boat interactions when I'm bored and want something fun, no plans however. Gonna close it since I can always dig it back up when I need to.
