### ISSUE TITLE
"Reposting" the Tinkers' Construct mod on a Chinese Forum

### ISSUE THREAD

**Issue by Robijnvogel** [SlimeKnights/TinkersConstruct#2715]
As requested by [on the Minecraft Forum](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638?comment=5405) by Meitangdehulu.

**Comment by 3TUSK** [comment]
...Doesn't MIT license allow redistribution of compiled binary file? 

> This... again.

**Comment by liach** [comment]
Yes, it does allow if you specify the original author.

**Comment by bonii-xx** [comment]
It does, but we prefer to have one central official place for multiple reasons (reliability, newest versions, security, download counts,....). He also sent me a PM on the MC forums, I responded there.

**Comment by Robijnvogel** [comment]
Well, what if he links the MC Forum Page, the CurseForge download and the Github issue tracker?

**Comment by 3TUSK** [comment]
@Robijnvogel He said "repost", which has *already* indicated that he wants to *redistribute*. Considering the speed of downloading something from curseforge in China, it is kinda of unavoidable.

**Comment by Robijnvogel** [comment]
Considering he is translating from Chinese to English, the word "repost" could have many meanings, but I see your point.

**Comment by 3TUSK** [comment]
In fact, "repost" is the most accurate word here... think about a mirror or somethings like that. Also search hashtag #stopmodreposts

**Comment by Robijnvogel** [comment]
I'm quite aware of that hashtag, thank you.
