### ISSUE TITLE
EntityBlueSlime ticking cause server crash

### ISSUE THREAD

**Issue by krishaman** [SlimeKnights/TinkersConstruct#2719]
Recent server crash looks to be from a ticking EntityBlueSlime. 

- MineCraft 1.10.2
- Forge 12.18.3.2185
- tconstruct 2.6.1.464

Attached crash log.

...

[crash-2017-01-12_18.24.01-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/703315/crash-2017-01-12_18.24.01-server.txt)

**Comment by KnightMiner** [comment]
Blue slimes do nothing special on ticking, they literally are just slimes with different drops and a different colored model. This appears to be a DarkUtilities issue with his anti-slime feature, as apparently [the tile entity map is changing](https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/master/src/main/java/net/darkhax/darkutils/features/antislime/FeatureAntiSlime.java#L71) while he is attempting to block the slime spawn. Report it [here](/Darkhax-Minecraft/Dark-Utilities/issues).
