### ISSUE TITLE
Tinker makes Client insta-crash on rendering

### ISSUE THREAD

**Issue by Dorfinger** [SlimeKnights/TinkersConstruct#2721]
Currently playing on Hermitpack.

Everyone on the server is crashing now upon loading ; here's my log :
http://pastebin.com/dNY2MmbJ

Disabling Tinker prevented the crashes .

**Comment by bonii-xx** [comment]
Remove optifine

**Comment by Dorfinger** [comment]
I was the only one of us 3 to use optifine, we all crashed, 
I did remove optifine for testing purpose and I was still crashing ,
Figured something that stopped us from crashing by removing the tinker crafting table where someone had an ultimate energy cube  in it .

**Comment by bonii-xx** [comment]
Ah yes. Mekanism models do that. Because Mekanism doesn't have models for those, they rather break the game than having proper models.

**Comment by Eufranio** [comment]
```
Item Type: slimeknights.tconstruct.tools.tools.Hammer@2b4e3144
```
Sure? lol

**Comment by Dorfinger** [comment]
Yeah tinker is the biggest part of that problem It looks like .

**Comment by KnightMiner** [comment]
Can you reproduce it without the Mekenism model? Crash reports can often point to the wrong location, especially when a mod is breaking things causing later code to no longer run properly. Plus the user above literally stated the Mekenism model was the issue.

**Comment by bonii-xx** [comment]
Also it's a well known issue with Mekanisms since it first set its foot on 1.8+.

>Sure? lol

Feel free to invest some time into it, if you think I'm wrong. :P
