### ISSUE TITLE
1.10.2  The Fins Modifier On Arrows - is its crafting recipe incorrect or does documentation need clarified?

### ISSUE THREAD

**Issue by Econniff** [SlimeKnights/TinkersConstruct#2722]
I almost opened an issue that the Fins modifier doesn't work at all, but after going back and experimenting a bit, I discovered what you really need to do.  In order to successfully apply the Fins modifier to an arrow, you need to add _two_ raw fish to the tool station, rather than one.  Many Tinkers items ask for more than one of a type of material, so that in itself isn't a problem, but unlike parts, modifiers don't tell you there isn't enough of that item (because that's usually not a thing we need to worry about).

Trouble is, the book implies you only need one fish.  So this could be a source of confusion for players hoping to deliver some sweet underwater death

**Comment by bonii-xx** [comment]
Update your mantle and TiC.
