### ISSUE TITLE
Drying Rack Progress Reset(1.10.2)

### ISSUE THREAD

**Issue by echohunter221** [SlimeKnights/TinkersConstruct#2723]
Anytime a drying rack is unloaded, the current progress on whatever item is drying is reset.

Minecraft: 1.10.2
Forge: 12.18.3.2202
TConstruct: 1.10.2-2.6.2
Mantle: 1.10.2-1.1.4

**Comment by KnightMiner** [comment]
That was an issue that evaded for quite a long time. The drying time was being loaded before the item stack was, so it deleted it as adding an item stack to the rack changes the time as well.

**Comment by LovelyFlare** [comment]
Didn't even realize that counted as one

**Comment by KnightMiner** [comment]
In general, if blocks lose any data on reload, it is an issue
