### ISSUE TITLE
Compatibility with minecraft 1.11.2 version

### ISSUE THREAD

**Issue by metabuddy** [SlimeKnights/TinkersConstruct#2724]
Hello,
Is the current tinker's construct version compatible with minecraft 1.11.2 ?
If it's not, are there any estimates when you might release it for 1.11.2?

Thank you.

**Comment by bonii-xx** [comment]
No it's not compatible currently. We want to get it compatible of course, but we're simply lacking the time. So no ETA.

**Comment by Ristovski** [comment]
Is there any progress/TODO/ETA on this?

**Comment by C1ffisme** [comment]
From a technical perspective, what would it take to get the mod to work with McJty's [compatlayer](https://mods.curse.com/mc-mods/minecraft/253729-compatlayer)?

**Comment by ArukaAlter** [comment]
It would require rewriting most of the mod from the ground using the lib.

**Comment by KnightMiner** [comment]
The work to port to compatlayer is roughly as much as the work to port to 1.11, and given we already require Mantle I doubt another lib will be added just for the mod to load on both versions.

**Comment by Ristovski** [comment]
Don't lose hope - https://github.com/SlimeKnights/TinkersConstruct/commit/46f1b9cfd058a3455f24c9c8fac7c92dea8777b2

**Comment by Landmaster** [comment]
This can be closed now, as there is already TiC for both 1.11.x and 1.12.x.
