### ISSUE TITLE
[1.10.2] Dupe with Crafting Station 

### ISSUE THREAD

**Issue by Eufranio** [SlimeKnights/TinkersConstruct#2727]
In multiplayer, put items in order to craft something, like a wooden shovel. Both players click in the output slot at the same time: dupped item.

**Comment by LovelyFlare** [comment]
Are you sure this isn't just a client desync?  Also, what Tinkers' Version?  Is this on a regular forge or spongeforge server?  Are there other mods that could affect this?  Please give more information.

**Comment by Eufranio** [comment]
I'm sure it really dupes the items. I'm on TiC 2.6.2, Mantle 1.1.4, on a SpongeForge environment (SF 5.1.0-BETA-2037), Forge 12.18.3.2221, my modlist is [here](http://www.technicpack.net/modpack/magibeta-pack.940049/mods)

**Comment by LovelyFlare** [comment]
Can reproduce this with a normal forge server?  Otherwise, report to the spongeforge GitHub.

**Comment by Eufranio** [comment]
Okay, looks like it only happens with SpongeForge. Thanks for your help!
