### ISSUE TITLE
crossbow multihit(?) glitch

### ISSUE THREAD

**Issue by syrun97** [SlimeKnights/TinkersConstruct#2728]
![2017-01-19_15 56 38](https://cloud.githubusercontent.com/assets/19798397/22096683/4b8d4d12-de60-11e6-9a6d-120c61d86626.png)
![2017-01-19_15 53 15](https://cloud.githubusercontent.com/assets/19798397/22096684/4b8ffb7a-de60-11e6-8cba-e89b11f1d8d8.png)
like this sometime bolts from crossbow can hit many mobs in once. is this intended?
used crossbow/bolt
![2017-01-19_16 01 35](https://cloud.githubusercontent.com/assets/19798397/22096746/9b453bbc-de60-11e6-8a1b-332708c347d3.png)
![2017-01-19_16 01 38](https://cloud.githubusercontent.com/assets/19798397/22096747/9b4d0496-de60-11e6-9557-d43b084f2c1f.png)

**Comment by syrun97** [comment]
cf) im cruntly using sky factory 3 3.0.4

**Comment by LovelyFlare** [comment]
Are you using bone for the bolt?  If so, its trait allows it to split into multiple bolts sometimes.

**Comment by Flabort** [comment]
@LovelyFlare As you can see in the screenshot of his bolts, they do NOT have the splitting property. So no, he is not using bone. 
I do think that Endspeed possibly causes piercing sometimes, but I'm not sure.

**Comment by LovelyFlare** [comment]
Well, that's weird.  The other two screenshots didn't load for me when I posted that.  My bad.

**Comment by bonii-xx** [comment]
Hm, could possibly be endspeeds fault, yes.

**Comment by KnightMiner** [comment]
Same bug as #3982 I think. Going to close this one as the other report has more information
