### ISSUE TITLE
Smeltery causing render-update loop

### ISSUE THREAD

**Issue by Rudolpher** [SlimeKnights/TinkersConstruct#2729]
Not 100%, but have not been able to reproduce after taking down the smeltery.

When entering at or around chunk containing smeltery, I sometimes got a [huge lag spike](http://imgur.com/a/3CyJO). This lag spike goes away if I leave the chunk(not outside render distance) and return. After a lot of troubleshooting and process of elimination I decided to take down the smeltery structure, and have not been able to reproduce it since. It is not related to smeltery working on anything, and not sure why it sometimes happens and sometimes don't.
Thought until last night that this was just a quirk on my end, but saw in @Darkosto 's stream that the same thing happened, so decide to report it on to here.

[Stall reports from Sampler](http://www.filedropper.com/stall-reports)
[Samples(.nps)](http://www.filedropper.com/2sampler)

I have more samples if needed.

MC - 1.10.2
Mod pack - Sky Factory 3.0.5
Tinkers - 2.6.2
Forge - 12.18.3.2215

**Comment by OliverDudgeon** [comment]
I believe I have the same issue. 
Only around chunks containing smeltery controllers does this occur. Breaking the smeltery such taht it not longer valid (breaking the tank or controller) or moving away from it, stops the lag.
It is periodic with a period of 15 seconds. This is very reproducible on my instance. I.e I can place the smeltery wait for the first spike then time 15 seconds and I will see the next spike.
This happens on my custom pack (skyblock style) with modlist: 
- http://pastebin.com/DtvEU1Mx

I have run a profile of my world with the vanilla profiler:
- http://pastebin.com/FVBz2SHB

**Comment by KnightMiner** [comment]
Probably fixed by 93f7802. If not, you are probably seeing garbage collector lag, which means you need to adjust your Java settings.
