### ISSUE TITLE
reuseStencils=false makes Part builder unusable

### ISSUE THREAD

**Issue by SamGunGraven** [SlimeKnights/TinkersConstruct#2732]
After changing reuseStencils to false in config you can no longer put stencils in the Part builder - not from Pattern Chest or Player Inventory - manually or right click both fail.

**Comment by Gunner76th** [comment]
Seeing as this was resolved 18 days ago, but that the latest update on Curse is now 30 days old, do we have a projection as to when this update will be pushed to Curse?

**Comment by LovelyFlare** [comment]
@Gunner76th The update will be pushed when boni has some time.
