### ISSUE TITLE
Landmine Server Crash 1.7.10

### ISSUE THREAD

**Issue by andro299** [SlimeKnights/TinkersConstruct#2733]
So i decided to start playing with my friend some sky factory 1.5.6. I just updated the server, since i had the server before and it was working. But this time, my sevrver loaded just fine until it finished loading. At the point where i would be able to join(when it unloads the chunks), it crashed. I will paste the crash report soon, if anyone knows the problem, I would be thankful for the help.

**Comment by ArukaAlter** [comment]
1.7 isn't supported anymore.

**Comment by KnightMiner** [comment]
Always post the crash report if there is a crash. It is next to impossible in most cases to debug otherwise.

Secondly, we no longer support 1.7.10, no new updates are being made.

Thirdly, that is an old version of SkyFactory, use the latest (2.5.6) and I'll bet the issue was already fixed.
