### ISSUE TITLE
Weird Pattern Chest thing

### ISSUE THREAD

**Issue by ProxyPlayerHD** [SlimeKnights/TinkersConstruct#2734]
![grafik](https://i.gyazo.com/beeca6bf51ae536a2f75ccd72100aaa0.gif)

It is Funny, but nothing else really.

**Comment by bonii-xx** [comment]
Yup, I know. I specifically tested that case. It doesn't bring you anything though ;)

**Comment by LovelyFlare** [comment]
How many spaces can you extend the part builder to?  The world may never know...

**Comment by bonii-xx** [comment]
256
