### ISSUE TITLE
Can't repair Demon Ingot tools in SF3

### ISSUE THREAD

**Issue by Harystolho** [SlimeKnights/TinkersConstruct#2735]
I made a full demon ingot sword in SkyFactory3 and I can't repair it using demon ingots

**Comment by laz2727** [comment]
Iirc ExU in SF3 is ancient.

**Comment by KnightMiner** [comment]
Demon Ingot tools are added by an addon (Extra Utilities specifically, it could even be intentional). Report the issue to that tracker.

**Comment by ldeluigi** [comment]
Use the demonic shards instead
