### ISSUE TITLE
[Suggestion] Smeltery Interface and Seared Furnace Interface

### ISSUE THREAD

**Issue by ToadsworthLP** [SlimeKnights/TinkersConstruct#2736]
To put it simple, these blocks can be used as smeltery/seared furnace building blocks. When you right-click one of them, they allow you to not only view the inventory of said smeltery/seared furnace like a controller, but also enables you to put in and take out items! This makes it possible to to access a smeltery from, say, multiple floors of your house instead of requiring you to run down to your controller to smelt something because you can only have one controller per smeltery/seared furnace. This would also allow the seared furnace to be fully automated, which is also a huge benefit :D
PS: I only used the name "Interface" for easier understanding. If you don't like it, replace it with something like "Smeltery Hatch" ;D

**Comment by bonii-xx** [comment]
No, the smeltery only having one in/output is intentional.

**Comment by LovelyFlare** [comment]
Tinkers' Construct isn't meant to be automated.

**Comment by Flabort** [comment]
If you want to automate tinker's, there are addons for that. Tinkers I/O comes to mind. Having base Tinkers not be automated like that is perfectly fine.

**Comment by bonii-xx** [comment]
Tinkers can be automated. Just not easily :P

**Comment by ToadsworthLP** [comment]
@boni-xx The smeltery: yes, even with vanilla fully automatable. The seared furnace isn't, however, as you would need to insert and extract from the same block, which isn't possible with vanilla or typical pipes. The exception is Refined Storage, but that really doesn't fit with Tinker's, and that's why I initially asked. Please add something like a port from where you can extract the cooked items <3

**Comment by bonii-xx** [comment]
The searned furnace is not meant to be automated. It's an alternative to a wall of furnaces. Vanilla furnaces are automatable ;o

**Comment by Jsec42** [comment]
The smeltery is generally easy to automate - just make sure you don't get your metals unintentionally mixed and you'll be fine(you can even do it with vanilla resources there, as hoppers will automatically extract from a casting table/basin and seared faucets can be activated with redstone. The seared furnace is more tricky as it requires mods to be fully automated. If you have thermal dynamics installed it can be done with servos and retrievers operating in whitelist mode(i.e. they only pull the blocks that you specify), and even in vanilla it can be done if you have only one item type you wish to smelt.
