### ISSUE TITLE
Stencil Table Crash

### ISSUE THREAD

**Issue by slimeboy77** [SlimeKnights/TinkersConstruct#2737]
I'm not sure why but whenever i open the Stencil Table the game crashes. I really wish i could fix it myself  but i can't. i found this glitch in my modpack slimecraft i really hope you can get back to me and help me.
And heres the madpack https://minecraft.curseforge.com/projects/slimecraft-pack

**Comment by LovelyFlare** [comment]
Crash log?

**Comment by slimeboy77** [comment]
@LovelyFlare do you want me to copy and paste it all in to the chat or is there a way that I can message you it on here? I'm so sorry I'm new to this website.

**Comment by LovelyFlare** [comment]
Use pastebin.com preferably.

**Comment by slimeboy77** [comment]
@LovelyFlare i would have gotten back to you last night but i fell asleep here is the website http://pastebin.com/mJRjKyzM

**Comment by KnightMiner** [comment]
Looks like a Redstonic issue, they are rendering things where they shouldnt if I had to guess. Not a Tinkers issue.
