### ISSUE TITLE
High mining speed glitches block breaking

### ISSUE THREAD

**Issue by chimericdream** [SlimeKnights/TinkersConstruct#2738]
**MC Version:** 1.10.2
**Forge Version:** 12.18.3.2202

**Relevant (I think) mod versions:**
 * **Tinkers Construct:** 2.6.2
 * **TAIGA:** 1.2.6
 * **Tinker I/O:** 2.4.2
 * **Tinkers' Addons:** 1.0.3
 * **Tinkers' Tool Leveling:** 1.0.1

I'll start by saying that I don't know if this stems from "vanilla" TiC or the addons, but I will start here.

I am using TiC with a few of the addons (TAIGA, Tinker I/O, Tinkers' Addons, and Tinkers' Tool Leveling), and when my tools reach a certain mining speed (around 20-25), they break some blocks so fast that the game doesn't register the block as broken. This causes the old behavior of a missing block that is still present. Trying to walk through the space glitches the player out, and right clicking or otherwise triggering a block update makes the invisible block reappear.

I suspect that what's happening is the tool registers the block as broken before the client or server, and the event never gets sent.

I only notice this (right now) with blocks that break quickly under more normal circumstances: nettherrack, sand, etc.

**Comment by LovelyFlare** [comment]
It's simply just vanilla.  That's just happens when any tool has too high of a mining speed regardless whether it's modded or not.  Reloading the world or F3+A will show the blocks again.

**Comment by bonii-xx** [comment]
Vanilla issue. TiC already has countermeasures for the AOE tools, but I don't think it can be prevented for the block that's being broken. You just need to relog when that happens

**Comment by chimericdream** [comment]
I understand that it's a vanilla issue, so I can't argue with closing the ticket. But was there some regression between 1.7.10 and 1.10.2 that exacerbated the problem? In a 1.7.10 pack, we had Iguana Tweaks on, and some users had tools with speeds well over 100 without running into this. Just trying to figure out where to go next.

**Comment by Insane-96** [comment]
It will be fixed in MC 1.13 if anyone's intrested

**Comment by bonii-xx** [comment]
I'll believe that when I see it ;P
