### ISSUE TITLE
Additional Modifier Slots

### ISSUE THREAD

**Issue by noswanson1982** [SlimeKnights/TinkersConstruct#2741]
Attempting to use Gold Block + Diamond to create an additional modifier slot on weapons yields an "Error: No modifier found for Block of Gold."  Was the ability to add modifier slots removed or is this an error?

**Comment by ArukaAlter** [comment]
This feature was removed due to the better stats of some materials.

**Comment by laz2727** [comment]
Yes.

2017-01-25 14:37 GMT+05:00 noswanson1982 <notifications@github.com>:

**Comment by Flabort** [comment]
If you really want that feature back, there is already an addon called "Tinkers Addons" which adds in most of the features that were changed or removed in the jump from 1.7 to 1.10

**Comment by noswanson1982** [comment]
Just thought I'd ask being as the wiki still shows that they work.

**Comment by bonii-xx** [comment]
The wiki is a 3rd party page, severely outdated and has no association with us.

**Comment by Flabort** [comment]
That being said, you can always update the wiki yourself now that you know @noswanson1982

**Comment by noswanson1982** [comment]
Thanks for helping out.

**Comment by noswanson1982** [comment]
I modified the wiki to reflect those changes as well.

**Comment by noswanson1982** [comment]
And someone went and undid the changes I made.  Kind of defeats the purpose.  Someone must really prefer it outdated.

**Comment by EPSIL0N** [comment]
I actually came here to try and find some info as all the wiki's i have seen appear to be dedicated to TC1 only, and I take it that there is not an official wiki for either TC1 or 2 but has anyone made a fan wiki for TC2?

**Comment by LovelyFlare** [comment]
@EPSIL0N Materials and You and JEI are good sources of information themselves.

**Comment by EPSIL0N** [comment]
@LovelyFlare I acknowledge that and I've read the book cover to cover but I was asking as a lot of my questions are related to spoiling the fun and wanting the raw formulas and deobfuscated descriptions of traits after getting fed up that my assumptions within the lore can be so drastically wrong at times.

**Comment by noswanson1982** [comment]
My only issue is the fact that transitioning from TC1 to TC2 means that I have to somehow treat TC2 as a mod I have absolutely no prior knowledge of because nowhere does anything list features that are different from TC1.  JEI and Materials And You are great if you are new to the mod.   But for those of us who know TC1, those changes can throw people off.  Now, if there was a wiki page that listed all of the features changed (stats, removed features, etc) then I would be content.  At least until a wiki for TC2 is made.

**Comment by bonii-xx** [comment]
Feel free to compile a list
