### ISSUE TITLE
Stencil Table Crash Bug

### ISSUE THREAD

**Issue by SpartanNinja223** [SlimeKnights/TinkersConstruct#2742]
So, today I was playing a modified version of FTB Hermitpack and I tried to make a stencil table and all the other tables, chests or what have you. I have everything set up and when I went to click on the stencil table my game displays the ui and then freezes before crashing out. I have never had this issue before, and as it stands I have to cheat in patterns every time i want to start tinkers, I'm not sure if this is tinkers or Cyclic like I have heard is causing problems with other people. None the less this is an annoying bug and would love to see it fixed. I have enclosed the crash report in this post as i know if its tinkers it will help. As a note all the mods are at the latest version that I can download from curse.
[crash-2017-01-26_23.34.08-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/734652/crash-2017-01-26_23.34.08-client.txt)

**Comment by bonii-xx** [comment]
>	at com.raizu.redstonic.Recipe.IRecipe.EnergeticBattery.func_77572_b(EnergeticBattery.java:31)

A Redstonic recipe is crashing your game. Check for Redstonic updates and/or report to its author. Not TiC related.

**Comment by SpartanNinja223** [comment]
Thanks for the clearing that up. I'l just remove the mod, never use it anyways.
