### ISSUE TITLE
Smeltery on 2 floors?

### ISSUE THREAD

**Issue by Rye2511** [SlimeKnights/TinkersConstruct#2743]
I have downloaded the tinkers mod, but i have a q. 
I have builded a house that are 2 floors high, is it possible to have 2 smeltery controller that show the same on both floors ( is one high tinkers that going up from the 1. floor, to the next floor.) ? hope u understand.
best regards.
ME.

Pic 1(first floor) https://gyazo.com/bd45b1f8a3aa1809973fff1733851624
Pic 2(sec. floor) https://gyazo.com/b1844ebcd5f3b7867ac5d3fba0c3feb2

**Comment by LovelyFlare** [comment]
No it isn't.

**Comment by bonii-xx** [comment]
No, you can only have one controller per smeltery. Think of it as the brain of the smeltery.
