### ISSUE TITLE
Materials From Other Mods Not Working

### ISSUE THREAD

**Issue by FitmoGamingMC** [SlimeKnights/TinkersConstruct#2744]
I tried to make magical wood tool parts and it doesn't work

**Comment by KnightMiner** [comment]
Do you want to describe your issue? What version are you in, and what makes you assume there are magical wood parts?

**Comment by FitmoGamingMC** [comment]
i'am in 1.10  i wanted to make magical wood tool parts from other mod because in other modpacks that i played i was able to make them 1.7.10 and 1.8 modpacks

**Comment by KnightMiner** [comment]
Magical wood was added by Extra TiC, not Extra Utilities. Thus, it does not exist in 1.10. And no, we will not be adding it, it is up to Extra Utilities or an addon to add the material.
