### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by PisicaAlbaneza** [SlimeKnights/TinkersConstruct#2745]
So I was loading the recommended version of forge 1.9.4 with some mods and this popped on the minecraft screen when I launched the minecraft but it got through the level 1 of the forge and got to the stage 2 

![need](https://cloud.githubusercontent.com/assets/24756618/22405370/87cff514-e639-11e6-9566-d21770c145e4.png)

This was the first Error and I had to remove Bibliocraft and so i did

[2017.txt](https://github.com/SlimeKnights/TinkersConstruct/files/737612/2017.txt)

and then this was the next error that is on the first photo

[2017-01-29-2.txt](https://github.com/SlimeKnights/TinkersConstruct/files/737616/2017-01-29-2.txt)
 

so please help

**Comment by ArukaAlter** [comment]
1.9 is no longer supported.

**Comment by GirafiStudios** [comment]
You most likely don't have Mantle installed.

**Comment by KnightMiner** [comment]
1.9 is no longer supported and it looks like you have a broken install of Forge. Plus this issue seems completely unrelated to Tinkers. Try the latest Forge and make sure you have all the dependencies for installed mods.

**Comment by PisicaAlbaneza** [comment]
ok
