### ISSUE TITLE
Error message.

### ISSUE THREAD

**Issue by leekodot** [SlimeKnights/TinkersConstruct#2746]
Hey, now, I know, you are not working on this version, but that has nothing to do about what I am currently going to say. I have Minecraft 1.7.10 and I can't play with this mod. I have these mods: 1.7.10 Better Furnaces mod v4.3, Buildcraft-7.1.18, Chisel 2.9.5.11, Dyeable Beds mod 1.7.10, Fastcraft 1.23, Iron Chests mod 1.7.10 Tconstruct (this mod) 1.7.10-1.8.8, Too Many Items mod (TMI for short) 1.7.10, and the Too Much TNT mod 1.7.10, and I can't play with this mod. you don't have to work on 1.7.10, especially since you won't, but I don't know what I need and don't want to make the Tconstruct mod work. but if you can tell me what I need to put on and take off, then please let me know. Also, here is the error message: (starts minecraft, and waits for that error message) Forge Mod Loader has found a problem with your minecraft installation. The Mods and versions listed below could not be found: Mantle : minimum version required is 1.7.10-0.3.2. The file 'logs/fml-client-latest.log' contains more information. (end of message) Please help me.

**Comment by leekodot** [comment]
also, I know you can help me with this issue without even doing anything to the mod itself, and if I can't get on, and there is nothing I can do to play with the Tcon mod on, then no one with minecraft 1.7.10 can.

**Comment by KillShow** [comment]
you have to add the 1.7.10 version of mantle to your mods folder.

**Comment by KnightMiner** [comment]
The error message is probably self explanatory, but you failed to add any such logs. You are probably missing Mantle or another dependency for a different mod. In any case, it is unsupported and for issues like this you are better off on the forums.

**Comment by leekodot** [comment]
There was not really any logs that I could give you, I mean, I looked at the latest log, but I did not see much, no help what so ever. I have no idea what I need to do, and minecraft is the one who didn't give ME enough info to give to you. I literally have no idea what I need to do, and I... I... You know what? I am going to delete your mod from my computer and never download it again unless I can get enough information to know how I can get it running! And I am going to delete it right out of my mods folder! I hate this!!! 

    On Monday, January 30, 2017 5:17 AM, KnightMiner <notifications@github.com> wrote:
 

 The error message is probably self explanatory, but you failed to add any such logs. You are probably missing Mantle or another dependency for a different mod. In any case, it is unsupported and for issues like this you are better off on the forums.—

**Comment by leekodot** [comment]
sorry about what I said to you about your mod, I didn't know that I needed the mantle you use, but you should have known about the mantle, but if you did, then you should have told me, and I gave you every single thing in my mods folder, but I did not know anything about the mantle, until around now, but now I know that I need the mantle to make your mod work, but if you told me that I needed the mantle, then I would not have said everything that I said before, and I am sorry, but now I know that I need the mantle, and I know how to get your mod to work, so I am happy now, (I am kind of unhappy that you didn't tell me about the mantle though) but yeah. 

    On Monday, January 30, 2017 5:17 AM, KnightMiner <notifications@github.com> wrote:
 

 The error message is probably self explanatory, but you failed to add any such logs. You are probably missing Mantle or another dependency for a different mod. In any case, it is unsupported and for issues like this you are better off on the forums.—

**Comment by leekodot** [comment]
Correction, you did tell me that I needed mantle, but I did not see it until now. Sorry. 

    On Monday, January 30, 2017 5:17 AM, KnightMiner <notifications@github.com> wrote:
 

 The error message is probably self explanatory, but you failed to add any such logs. You are probably missing Mantle or another dependency for a different mod. In any case, it is unsupported and for issues like this you are better off on the forums.—

**Comment by leekodot** [comment]
Killshow also told me that - omg I didn't even - I am so dumb. I am so dumb. Or blond as its called. 

    On Wednesday, February 8, 2017 5:42 PM, Sean Moore <leekodot@yahoo.com> wrote:
 

 Correction, you did tell me that I needed mantle, but I did not see it until now. Sorry. 

    On Monday, January 30, 2017 5:17 AM, KnightMiner <notifications@github.com> wrote:
 

 The error message is probably self explanatory, but you failed to add any such logs. You are probably missing Mantle or another dependency for a different mod. In any case, it is unsupported and for issues like this you are better off on the forums.—

**Comment by leekodot** [comment]
(facepalms) 

    On Wednesday, February 8, 2017 5:45 PM, Sean Moore <leekodot@yahoo.com> wrote:
 

 Killshow also told me that - omg I didn't even - I am so dumb. I am so dumb. Or blond as its called. 

    On Wednesday, February 8, 2017 5:42 PM, Sean Moore <leekodot@yahoo.com> wrote:
 

 Correction, you did tell me that I needed mantle, but I did not see it until now. Sorry. 

    On Monday, January 30, 2017 5:17 AM, KnightMiner <notifications@github.com> wrote:
 

 The error message is probably self explanatory, but you failed to add any such logs. You are probably missing Mantle or another dependency for a different mod. In any case, it is unsupported and for issues like this you are better off on the forums.—
