### ISSUE TITLE
[1.10.2] Feature Request

### ISSUE THREAD

**Issue by XvSkItZvX** [SlimeKnights/TinkersConstruct#2748]
After reading the "Guidelines for Contributing" link above I expect that this issue will be closed, understandably as it's not an actual 'issue' I'm simply at a loss for where to make such a post.

I have been working on compiling a mod pack, privately at the moment, which incorporates another mod, "Primal Core", which provides the ability to disable vanilla tools. The primary purpose for this is to disable wood tools and possibly stone tools to use their flint tools for early game.

The possibility to disable all vanilla tools and weapons is possible and a feature I intended to use so that players continue into Tinkers Construct for the next stage of progression. 

However, with that being the case I find it contradictory to be able to make wood and stone tools as soon as they get the appropriate work tables built in TiC. 

This brings me to this feature which I feel would be beneficial to not only me but future modpackers looking to implement Tinkers Construct in interesting ways. 

A per part, material black list.

I personally am only interested in disabling wood and cobble stone heads for the tools but for completeness and flexibility other users may want to disable other part/material combinations.

Thanks you for your time and work on a staple mod in nearly any modpack.

**Comment by LovelyFlare** [comment]
I think you might be able to disable part making with a tweaking mod...

Also, you could instead make wood or stone head ineffective or such with something like HarvestTweaks.

**Comment by XvSkItZvX** [comment]
I have recently become aware of the "Tweaker" mods, and as a personal preference wish to minimize their usage as much as possible, making the majority of possible changes to what is possible through config files. 

The project I'm currently working on is in all truth my first endeavor and being inexperienced I'd like to introduce as few opportunities for errors as possible, while at the same time only asking for changes to mods from devs that may benefit more than just my own project.

I haven't visited the FTB forums or reddit yet. I'll try to make it by there sometime in the future. Thank you for your consideration and prompt response.

**Comment by C1ffisme** [comment]
> I have recently become aware of the "Tweaker" mods, and as a personal preference wish to minimize their usage as much as possible, making the majority of possible changes to what is possible through config files.

This may or may not be inside your definition of 'tweaker' mods, (depending on whether that means "no mods that do one specific tweak" or "mods who's purpose is only to tweak certain settings") but if you need a mod for general purpose tweaking using only config files, I commonly make use of [Minetweaker](https://mods.curse.com/mc-mods/minecraft/224029-minetweaker3) for 1.7.10, or [Crafttweaker](https://minecraft.curseforge.com/projects/crafttweaker), for 1.10.2. (I haven't tried out Crafttweaker at all yet, though, since I mostly play modded 1.7.10.)

(This isn't my mod, I just thought I'd give possibly helpful advice in case you didn't know about this.)

**Comment by XvSkItZvX** [comment]
Those are actually the two key mods I referred to, more specifically "CraftTweaker" as I am working in 1.10.2, and I believe that the add-on mod for Mine/Craft Tweaker, ["ModTweaker"](https://minecraft.curseforge.com/projects/modtweaker) does have compatibility for Tinkers' Construct. It's just a personal preference to limit using those mods.

**Comment by LovelyFlare** [comment]
Unfortunately, the closest thing to what you're looking for was Iguana Tinker Tweaks (an addon specifically for Tinkers' Construct that allowed disabling of any part with the config) which is only available for the unsupported 1.7.10 version.  Right now, the only thing I know of that you can do is use tweaker mods.  I don't see part disabling being able to be added in the near future or at all (as a config option in native Tinkers').  Perhaps in some time and someone will make an addon that serves that purpose that ITT did.

**Comment by XvSkItZvX** [comment]
I was afraid of that lol. I have already been in communication with the devs of the "Primal Core" mod that I mentioned in my first post. I felt I should throw the idea to you guys since it'd serve a broader player base than being done with a third party mod.

**Comment by bonii-xx** [comment]
First off: Tinkers' Construct itself will never provide configs to remove materials. It's counter-intuitive for players, and only leads to unforseen problems.

That said, it does provide an API to prevent the registration of materials, so it is possible to deactivate or modify materials through other mods. You can change the harvest levels of TiC materials using [HarvestTweaks](https://github.com/SlimeKnights/HarvestTweaks). From my experience with Iguana Tinker Tweaks I can tell you that you'll want to avoid blacklisting certain part-material-combinations. You don't have a way to communicate your changes to the players, and the whole point of Tinkers' is to be able to build everything from everything, violating one of its core principles. Hence why there only is an API to disable a material alltogether.
