### ISSUE TITLE
Ardite trait not working?

### ISSUE THREAD

**Issue by JODAxDK** [SlimeKnights/TinkersConstruct#2752]
so i made a pickaxe with the ardite trait pertamor, and by the decripsion it sounds like that when i mine stone it will consume it for durability but nothing happends.
i have no other idea of how this is suppost to work if its not that

**Comment by bonii-xx** [comment]
Ardite is working like intended, it doesn't actually affect drops, only durability. So no, it will not consume the stone but yes you'll sometimes get durability when mining stone.

**Comment by JODAxDK** [comment]
dont you think the decripsion should be changed, and also whats the chance and how much durability does it get
