### ISSUE TITLE
Mod conflict

### ISSUE THREAD

**Issue by Coolio1337** [SlimeKnights/TinkersConstruct#2753]
I know this doesn't concern your mod specifically, but in the latest versions of your mod (1.10.2 - 2.x.x) it doesn't work with Extra Utilities2, the entire extra utilities tab in creative mode is bugged, and not only that all the items lose their textures. Not only does Extra Utilities bug out, but a few of the textures from TConstruct also glitch as well when used in combination with Extra utilities, mainly casting plates, and stencils. I don't know if there's anything you can do, but I hope you can I love both the mods, but not being able to use them in conjunction with one another kinda sucks.

**Comment by LovelyFlare** [comment]
I'm able to use the latest version of the mod just fine with ExU2...

**Comment by Coolio1337** [comment]
Yea sorry about that one, apparently whenever you use optifine (or at least the version I was using) with Extrautilities2 this happens
![2017-02-03_16 00 14](https://cloud.githubusercontent.com/assets/25522318/22611903/7b281ea0-ea2a-11e6-9127-aca9868b9287.png)
![2017-02-03_16 01 49](https://cloud.githubusercontent.com/assets/25522318/22611908/7ee33782-ea2a-11e6-86d4-f312588a5754.png)
It never occurred to me that it might be optifine because that mod never has conflicted with any other mod before.

**Comment by bonii-xx** [comment]
Optifine literally is the mother of all graphic conflicts in minecraft.
