### ISSUE TITLE
Casting table no longer working.

### ISSUE THREAD

**Issue by zZSandManZz** [SlimeKnights/TinkersConstruct#2756]
**I have no idea what is causing this. I've reinstalled tinkers. rebuilt the smeltery. Crafted a new casting table.  Broke the controller. Any help would be great o/**

https://www.youtube.com/watch?v=ZUNf4oII5cE

**Comment by bonii-xx** [comment]
You've got a mod that breaks it. Find out which one does it and remove said mod.

**Comment by zZSandManZz** [comment]
Found it. It was the quantum flux mod. Dont know what would be conflicting there. Quantum flux is for energy
