### ISSUE TITLE
bug with optifine

### ISSUE THREAD

**Issue by popcorn9499** [SlimeKnights/TinkersConstruct#2757]
When i login to a server running tinkers construct everything seems to work fine. Problem is im running a bungee server so i have a vanilla server in between and with optifine that causes a weird glitch where none of the world loads. Its like you would if you walked on a chunk error. the link to the [log](http://paste.ee/p/MbUYb)

Versions:
Minecraft 1.10.2
forge: 12.18.3.2202
mantle: 1.10.2-1.1.4
Tinkers construct: 1.10.2-2.6.2
optifine ultra: D6

I hope this can be solved

**Comment by bonii-xx** [comment]
We don't support Optifine.
