### ISSUE TITLE
Problem with Crafting Station in 1.10.2

### ISSUE THREAD

**Issue by Golgatron** [SlimeKnights/TinkersConstruct#2762]
Hello we have a Problem. We have a Hexacord server with Bungeecord for 2 Server is all fine but, we place a crafting station we disconectet from server with  fatal error has occurred, this connection is terminated.

I have no Idea what a problem is.

Here all Logs

Server Fml log
http://pastebin.com/Cn6AhSpF

Hexacrod Log
http://pastebin.com/X3MVeav0

i Hope i become help here

**Comment by Golgatron** [comment]
Need help plz

**Comment by bonii-xx** [comment]
Client crashlog? I have no idea what Hexacrod is, but either that or another mod on your server breaks it (and as far as I know Bungeecord doesn't have problems with it)

**Comment by Golgatron** [comment]
moment

**Comment by Golgatron** [comment]
i dont have crash report for client i have only the last log and last fml log

**Comment by Golgatron** [comment]
last log
http://pastebin.com/xk3xMkfB

and last fml log
https://www.file-upload.net/download-12294248/fml-client-latest.log.html

**Comment by bonii-xx** [comment]
Well, all I can tell you is that something messes with the networking.

**Comment by Golgatron** [comment]
hmm okay will check this

**Comment by Golgatron** [comment]
Also we have try a lokal server on my Pc make here is the same problem

**Comment by Golgatron** [comment]
can close we have the problem

**Comment by bonii-xx** [comment]
What is the problem? It's always helpful to post the solution/cause so other people can find it too when they encounter the same problem.

**Comment by Golgatron** [comment]
the problem was the ip_forward this must be true
