### ISSUE TITLE
Rendering Problem

### ISSUE THREAD

**Issue by SavageKiller13** [SlimeKnights/TinkersConstruct#2764]
I am trying to play on my modded 1.10.2 survival world I am making/using tinkers construct tools as one of my mods. I have a problem where my textures won't render (stencils are the unknown texture and tools/casts). This started happening today. I also have the required 1.10.2 mods (and had them for a while) and have never had these problems (as in the picture to the right (of my inventory), if you can see it).
![2017-02-07_15 02 22](https://cloud.githubusercontent.com/assets/25129480/22713622/79b743e2-ed46-11e6-9f7c-149807047694.png). This really confuses me so I need a fix. And to add this is a great mod.

**Comment by LovelyFlare** [comment]
Can you reproduce this without OptiFine?

**Comment by SavageKiller13** [comment]
Also when I open up a menu or the bit bag it crashes me

**Comment by SavageKiller13** [comment]
Is there any fix with optifine?

**Comment by LovelyFlare** [comment]
OptiFine messes with rendering for many mods which can cause crashes.  It would have to be up to them to fix the issue.

**Comment by bonii-xx** [comment]
Remove optifine.
