### ISSUE TITLE
Coke oven from IE getting duped with fortune applied.

### ISSUE THREAD

**Issue by tenten8401** [SlimeKnights/TinkersConstruct#2765]
Coke ovens from Immersive Engineering are getting duped with the fortune enchantment applied to a tinkers pick. It does not happen on vanilla pickaxes.

**Comment by LovelyFlare** [comment]
Are you using Sponge?

**Comment by tenten8401** [comment]
@LovelyFlare I am.

**Comment by LovelyFlare** [comment]
Can you reproduce this with only a normal forge server?  Otherwise, report this issue to Sponge.

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1281

couldn't reproduce this even with Sponge with latest 1.11 versions

**Comment by tenten8401** [comment]
This was so long ago, it might not even be an issue anymore.
