### ISSUE TITLE
Possible API bug

### ISSUE THREAD

**Issue by dshadowwolf** [SlimeKnights/TinkersConstruct#2766]
When adding a material with custom traits via the TinkerRegistry API it managed to get through the entire registration process - indeed through the entire phase of the mods load - and then a TCon API error shows up, claiming an attempted double-registration of the material.

As the material was registered - according to the error message - by Base Metals, and the error went through an entire stack of calls inside TiC code before apparently causing Pulsar to crap out - I'm going to assume that this means that TiC attempted to register a mod-integration material and that material had already been registered.

The custom trait on the material is not, actually, needed but is part of the "This is something that would be good to have" list and I was working on that chunk of code. I can easily re-generate the error if you'd like a log of it.

If there is any data needed, all you need to do is ask.

**Comment by KnightMiner** [comment]
Versions, logs, and maybe the code you used to register it?

**Comment by dshadowwolf** [comment]
hrm... I can link to the code - the current version is the same, just has the bit where Lead was being sent in to be registered commented out.  Starting here [on line 121](https://github.com/dshadowwolf/BaseMetals/blob/master/src/main/java/com/mcmoddev/lib/integration/plugins/TinkersConstruct.java#L121) is the routine used to register the mods materials with TCon (those that don't conflict).

The versions are Mantle 1.1.4 and TCon 2.6.2 - the BaseMetals version is built from that repository and it's on Forge 12.18.3.2221 - Minecraft 1.10.2

And give me a couple minutes to find the right archived log file and I'll have it available.

**Comment by KnightMiner** [comment]
What specific materials are you trying to register?

**Comment by dshadowwolf** [comment]
I was actually trying to register Lead with a custom trait that isn't
"Poisonous"

I was just surprised when the check I have against double-registration in
my code wasn't triggering and I was seeing an error. Just seems to me that
this is a race condition of sorts...

**Comment by KnightMiner** [comment]
If you are registering a material called lead at all that is your problem as Tinkers adds it itself. The reason your check likely fails is Tinkers registers it upon finding another mod that ads lead, so it's not always a normal time.

If you want to replace lead, there is an event fired when the material is registered which you can cancel so only yours registers, but just adding it without stopping the normal o e from registering will cause this error.

**Comment by dshadowwolf** [comment]
Did not know about the event! Thank you for that information!

**Comment by bonii-xx** [comment]
I suppose this can be closed then
