### ISSUE TITLE
When i placed Pattern it dont has anything in its

### ISSUE THREAD

**Issue by Ilkin0095** [SlimeKnights/TinkersConstruct#2772]
![screenshot_20170214201449](https://cloud.githubusercontent.com/assets/25773803/22937569/5d445108-f2f2-11e6-936d-06c057acb854.png)
![screenshot_20170214201501](https://cloud.githubusercontent.com/assets/25773803/22937568/5d420e66-f2f2-11e6-8d70-285f491ab803.png)
![screenshot_20170214201509](https://cloud.githubusercontent.com/assets/25773803/22937570/5d49246c-f2f2-11e6-85a7-90b907be5595.png)

When i placed Pattern it dont has anything on its . but in 1.7.10 and other versions it has pattern shovel head pattern pickaxe head etc. but now it dont has  

Tested with:
Mantle **1.1.4**
Tinkers' Construct **2.6.1**
Forge **Last**

- [ ] **Fixed**
- [ ] **Cannot be fixed**

**Comment by Ilkin0095** [comment]
Help plz i am playing survival but it dont have anything

**Comment by bonii-xx** [comment]
There was a 1.7.10 config where you'd get a full pattern chest. It doesn't exist anymore. You'll have to craft the pattern yourself in a stencil table, it's really easy. You can then put them into the pattern chest. Be sure to have the pattern chest placed between the stencil table and part builder for maximum effect.
