### ISSUE TITLE
Some things are gone...?

### ISSUE THREAD

**Issue by torsken7** [SlimeKnights/TinkersConstruct#2773]
Hi i just discovered Tinkers Construct and im playing on TConstruct-1.10.2-2.6.3 and there is several items that i cannot craft like the Traveler Armor and the hammers etc. Ive been looking around the internet looking for a reason for this but cannot seem to find any. Is there something wrong with my forge or anything or have they been removed from the mod?

Ty

**Comment by ArukaAlter** [comment]
The mod was rewritten between 1.7 and 1.8+, removed.

**Comment by KnightMiner** [comment]
If it's missing, it probably was never ported. Some features won't be ported, others take time, check out the FAQ
