### ISSUE TITLE
Damage being dealt clientside

### ISSUE THREAD

**Issue by HellFirePvP** [SlimeKnights/TinkersConstruct#2774]
Good day,

i received an issue that reports TinkersConstruct entities dealing damage on clientside. Link to issue & crash report: [https://github.com/HellFirePvP/AstralSorcery/issues/20](https://github.com/HellFirePvP/AstralSorcery/issues/20)

This issue is _not really_ originating on my end, i am merely experiencing the result of damage being dealt on the client as well as on the server. This will most likely result in desync problems between server & client when experiencing some lag - which is not a rarity. In the server-client model, it's usually intended to only _modify and control_ data, such as entity health and damage, _server-side_ and sync it afterwards to the client, which is done automatically in minecraft. Otherwise you might end up with an entity getting killed by your weaponry clientside but still being alive serverside since collision checks might not be the same due to different entity positions caused by potential network or other forms lag.

I have certainly ways to avoid further issues being caused by this, however as suggestion, i'd ask you to correct this.

**Comment by bonii-xx** [comment]
TiC doesn't, but the target dummy calls the forge event since it needs it for its damage calculations. You can probably hit them with a stick and the same would happen. Maybe you can confirm that?

**Comment by HellFirePvP** [comment]
If you hit someone "vanilla-like" - aka stick, weapon, fist, etc. - it's only fired serverside.

**Comment by bonii-xx** [comment]
That thing was never intended for widespread use, it was simply a tool to do testing.

**Comment by KnightMiner** [comment]
Is this actually a Tinkers Construct issue or just an issue with MmmMmmMmmMmm? If the latter this can be closed as we agree that MmmMmmMmmMmm is doing things wrong, but was never intended to be used in packs.

**Comment by HellFirePvP** [comment]
(12x)M calculates the damage being done on clientside whereas it's normally a subject of something that's only done serverside. Since this reply was done, i basically just specifically exclude client-side calculations from my calculations as i have basically all data only serverside that might add to the player's damage output.

It's not a bug per'se, it's more of bad practice as damage-calculation is nothing a client needs or should do (Much like entity AI or food, breath, health, [...] calculations) and parts my fault for not already excluding the client from these calculations.

**Comment by KnightMiner** [comment]
In that case, closing this as a MmmMmmMmmMmm issue
