### ISSUE TITLE
Smeltery Controller Ghost Block Replicating

### ISSUE THREAD

**Issue by CraftMinerKyle** [SlimeKnights/TinkersConstruct#2775]
For some odd reason, when I was playing on a survival world with a lot of other compatible mods, I noticed some oddly floating blocks that are about 15 to 20 blocks away from the front of my smeltery that were somehow replicated. WAILA did not show them as normal smeltery rains or seared bricks, but I could walk through them and could not break them. When I placed a normal block about 2 blocks away from any of them, they disappeared, but reappeared as soon as I removed that block. I tried draining my smeltery and moving it around, but just got a rotated result of my previous smeltery. But, as soon as I removed the real mirrored block from the smelter, that reflected ghost block disappeared.
![2017-01-24_17 02 47](https://cloud.githubusercontent.com/assets/22898072/23096202/ebc208fc-f5dc-11e6-9cf8-e1fead9034e4.png)
![2017-01-24_17 02 51](https://cloud.githubusercontent.com/assets/22898072/23096203/ebc6d8be-f5dc-11e6-96b6-93a847e8e7e0.png)
![2017-01-24_17 02 59](https://cloud.githubusercontent.com/assets/22898072/23096204/ebc98938-f5dc-11e6-9ebe-d525ab4edc8b.png)

**Comment by CraftMinerKyle** [comment]
Also, the crazy glitched blocks did not show up on my MiniMap, further convincing me that these blocks were not actually normal blocks. I have never seen this before on ANY other instance or world, so I think there might be a conflicting mod. I can upload the list of mods and the world for anyone to see and possibly resolve.

**Comment by CraftMinerKyle** [comment]
Here is the list of mods:
Waila (by ProfMobius)
Mantle (by mDiyo)
Tinkers Construct (by mDiyo)
Inventory Tweaks (by Kobata)
Waila Harvestability (by squeek502)
Iron Chests (by progwml6)
Extra Utilities (by RWTema)
CodeChickenCore (by chicken_bones)
Thermal Expansion (by TeamCoFH)
Chisel (by tterrag1098)
Applied Energistics 2 (by AlgorithmX2)
Minefactory Reloaded (by skyboy026)
Ender Storage (by chicken_bones)
FastCraft (by Player)
ExtraCells2 (by DrummerMC)
Another One Bites the Dust (by ganymedes01)
VeinMiner (by Portablejim)
BdLib (by bdew)
Ex Nihilo (by Erasmus_Crowley)
Progressive Automation (by VanhalMinecraft)
Advanced Generators (by bdew)
CoFH Core (by TeamCoFH)
Big Reactors (by ErogenousBeef)
BetterBedrockGen (by Gigabit1011)
WorldEdit (by sk89q)
MovingWorld (by darkevilmac)
Davincis Vessels (by darkevilmac)
Fun Ores (by SilentChaos512)
Thermal Foundation (by TeamCoFH)
Jabba (by ProfMobius)
Brandon's Core (by brandon3055)
Draconic Evolution (by brandon3055)
Buildcraft (by CovertJaguar)
TiC Tooltips (by squeek502)
Logistics Pipes (by RS485)
Thermal Dynamics (by TeamCoFH)
Industrial Craft (by Player)
Nuclear Control 2 (by Xbony2)
NEI Addons (by bdew)
Hardcore Questing Mode (by lorddusk)
ChickenChunks (by chicken_bones)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
Iguanas Tinker Tweaks (by bonusboni)
Better Builder's Wands (by Portablejim)
NotEnoughItems (by chicken_bones)
Magical Crops: Core (by Mark719)
Magical Crops: Armoury (by Mark719)
Magical Crops Compat - Minefactory Reloaded (by Streuner91)
EnderCore (by tterrag1098)
Ender IO (by CrazyPants_MC)
Pam's HarvestCraft (by MatrexsVigil)
Carpenter's Blocks (by Syntaxial)
McJtyLib (by McJty)
RFTools (by McJty)
Better Title Screen (by Girafi)

**Comment by LovelyFlare** [comment]
Don't use OptiFine.

**Comment by KnightMiner** [comment]
Smeltery controllers are a normal block. There is no special rendering going on with the model, so some other mod is breaking rendering.

Please try and find the minimal mods to reproduce this. Mods that affect client side rendering, notably Optifine, could be a major cause. (also, if it is caused by Optifine that makes this issue unsupported)

**Comment by LovelyFlare** [comment]
Also, this is an unsupported version anyway.

**Comment by CraftMinerKyle** [comment]
OK. I will remove OptiFine. It has been causing some visual problems with Chisel 2 anyway. Also, is the version outdated? I launched this from Curse Vioce and Curse Forge launcher, so it auto-updates all the supported mods and there has not been any new updates lately soo... Manual update I guess?

**Comment by CraftMinerKyle** [comment]
What I mean with the ghost block thing is that whatever the level of the fluids inside the smeltery would for some reason make some wierd ghost replica of the blocks around the level of the fluids, even the cobblestone I put around the smeltery because I cannot stand an undecorated workspace. : )

**Comment by LovelyFlare** [comment]
@CraftMinerKyle All 1.7.10 versions are no longer supported.

**Comment by bonii-xx** [comment]
Some other mod is causing this, and as has been said, 1.7.10 is unsupported.
