### ISSUE TITLE
Material colour change parameters

### ISSUE THREAD

**Issue by zubzubby** [SlimeKnights/TinkersConstruct#2777]
Hi,

I've been working on changing textures for the various tool parts (aiming towards support of Tinkers' Construct in the pixel perfection resource pack) but I'm finding it difficult to get my head around the different values in the materials folder and what they do. It all feels a bit too trial and error right now playing with the .json files and I don't have any real control of my palette when editing the textures, which is frustrating when I'm trying to get them looking as good as possible. I have very little experience with coding (I am trying to learn) so any help would be much appreciated!

For now, do you have more exact information as to what each parameter does to the texture?
ie: for type "metal" - how does this affect how each brightness value is changed, and how does it choose whether to make a colour darker or brighter?
for type "multicolour" - how are colours chosen to be "dark",  "mid" or "bright"? If it's from brightness level, where are the boundaries between dark, mid and bright?

I did read the FAQ which says no suggestions - BUT I believe this is one change that would be a great help for anyone who wanted to change the textures - a simple colour swap system for each material based on a set grayscale ramp for the base texture - and each shade on this ramp would be numbered and could be swapped out directly for another colour using hex colour codes. This would allow for much better control over the textures without having to add a new custom texture for each tool part.

ie:
white = 1
light grey = 2
medium light grey = 3
medium grey = 4
medium dark grey = 5
dark grey = 6

and then set each value to be a different hex number.

Thanks in advance

**Comment by bonii-xx** [comment]
>It all feels a bit too trial and error right now playing with the .json files and I don't have any real control of my palette when editing the textures

But that's how it is, it's your best bet. Remember you can reload resource packs at runtime.

>For now, do you have more exact information as to what each parameter does to the texture?

Depends on the type, in general it's derivable from the name, for exact details you'll have to look at the implementation, but mostly that wont help you much because it's a lot of magic. For example there are no fixed brightness values for multicolor, but it depends on the brightest and darkest pixel in the texture. Simple color/texture should be self explanatory. Metal has a hue and brightness modifier depending on pixel brightness, which results in a more shiny texture.

> a simple colour swap system for each material based on a set grayscale ramp for the base texture

But that wouldn't allow arbitrary texture generation like I'm using now. Like for the texture based textures. ;P

Otherwise that's already exactly what we have, except with more numbers.

**Comment by zubzubby** [comment]
thanks for the reply. So, I did a bit of testing with multicolor tonight as that seemed the most promising. The results were not as good as I hoped, but workable, I suppose. Won't allow for a nice colour ramp, as it would look wierd with the middle all the same hue and saturation and then changing to another set hue/saturation at the top and bottom. I'm sure you know all this already but it might help someone else who can't look at the code:
![testsheet](https://cloud.githubusercontent.com/assets/25750610/23107384/5cac3084-f6f4-11e6-8ce4-02cf278c2a24.png)

> Otherwise that's already exactly what we have, except with more numbers.
by this you mean that what I'm asking is what you already have here, except with 3 choices instead of 6? would adding a couple more levels be feasible? tell me if i misunderstood.

> But that wouldn't allow arbitrary texture generation like I'm using now. Like for the texture based textures. ;P
By this do you mean with "block"? How does the block parameter work? Would this be a possible way towards choosing a certain number of exact colours?

i hope you can bear with me on this! I understand that the functionality probably comes first for you guys, TiC is my favourite mod, it works really well, but I'd love for it to fit in and look good with the rest of the resource pack.

**Comment by Drullkus** [comment]
Looks like I designed a gradient map json deserializer. Is this what you’re talking about?
![8748bca1-7096-4399-8549-4b02f821b9e0](https://user-images.githubusercontent.com/5010174/35748076-961aab10-0801-11e8-8120-643016126515.jpeg)

**Comment by Drullkus** [comment]
<img width="935" alt="screen shot 2018-02-02 at 10 16 56 am" src="https://user-images.githubusercontent.com/5010174/35748846-507ff936-0804-11e8-9d49-4589ffa425ad.png">

The implementation is that I take the average value of a pixel on the texture and I turn it into the gray value (r 0, g 0, b 0 -> gray 0) (r 255, g 0, b 0 -> gray 85) (r 255, g 255, b 255 -> gray 255) then I use that value to find placement on the top gradient in the above image. The bottom gradient in the image would be created in the place of the top gradient with the following json below. Is this what you're asking for?

```{
  "type": "gradient_map_colors",
  "parameters": {
    "gradient_map" : [
      {
        "node"  : "1.0",
        "color" : "000000"
      },
      {
        "node"  : "0.50",
        "color" : "ffffff"
      },
      {
        "node"  : "0.0",
        "color" : "000000"
      }
    ]
  }
}```

**Comment by KnightMiner** [comment]
I'm going to close this issue due to too few responses. Drullkus's code sounds like it does what you are looking for. If so we could look into getting it pulled into the main mod, but for now this issue is pretty old without response.
