### ISSUE TITLE
SlimeBounceHandler crash

### ISSUE THREAD

**Issue by p455w0rd** [SlimeKnights/TinkersConstruct#2778]
Ok, so looking at the code, I don't know why this would happen, but this report is from Jax_Macky. He was using the Slime Sling and crashed. It happened on right-click. Click can be found @ https://clips.twitch.tv/jax_macky/MushyJaguarCoolCat

MC: 1.10.2
TiC: 2.6.2.487
Forge: 12.18.3.2221

**Comment by bonii-xx** [comment]
Crashlog?

**Comment by p455w0rd** [comment]
wow...total derp..i put it on gist and forgot to include it..sry about that: https://gist.github.com/p455w0rd/3280e6b4f80ccf69c6f4087b9564bac2

**Comment by KnightMiner** [comment]
@p455w0rd this issue has been around for awhile...

Can you still reproduce this in the latest Tinkers Construct? This is one of those issues that is really hard to tell what caused it. Also reproduce this specifically with as few mods as possible.

**Comment by p455w0rd** [comment]
I'd say go ahead and close it.
