### ISSUE TITLE
Tinkers Armoury [Suggestion]

### ISSUE THREAD

**Issue by Quizer9O8** [SlimeKnights/TinkersConstruct#2779]
Tinkers Construct always learned me that there is more than just your average diamond tool/weapon and that you should create, improve and try out new things. At this point I know what kind of material and modifier are useful in early-, mid-, and late-game or certain situations. Tinkering with tools/weapons was fun for a long time but I always wondered why you couldn't customize armor and shields too.

That's why I think it is time for TC to approach the defensive section.
Give us the ability to modify the standard Leather, Chainmail, Gold, Diamond armor and heck even Aradite, Cobalt and Manyullyn.

For example you could create an iron chestplate with trimmed Redstone on the shoulder pads for a quicker movement, an iron shield with spikes that may inflict thorn when touching them.
The possibilities are endless.

This would bring a lot of life into Minecraft's current PVP:
-Allowing a wide variety of options for the player to choose from
-Customizing armor/shields to it's fullest potential
-Taking combat to a whole new level, strategic wise

**Comment by LovelyFlare** [comment]
Please read [this](https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ)

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ

**Comment by Flabort** [comment]
It would be cool to have an official addon by the authors/maintainers of the mainstream Tinkers mod though. If I were to make such a tinkers armor mod, I'd make it like [this](http://pastebin.com/qpwcTibJ). But I'm not skilled enough at programming to make anything other than ideas at the moment.

I know it's highly unlikely, but I figured I'd drop the idea here anyways since it's relevant.

**Comment by LovelyFlare** [comment]
@Flabort There's simply not enough time for an addon to be made as well as it not fitting into the Tinkers' mod at all even as an addon.  It's also listed in the FAQ that it won't be made.  If there was ever plans, it'd already be made by now as this is an extremely common request.

**Comment by Flabort** [comment]
Yeah... I figured it was mainly a time issue.
