### ISSUE TITLE
Are the Infi* tools supposed to give the player Nausea?

### ISSUE THREAD

**Issue by BrisingrAerowing** [SlimeKnights/TinkersConstruct#2781]
Whenever I pull one of the Infi* tools (e.g. the InfiHarvester) out of the creative menu and put it in my inventory, I get the nausea effect applied. Is that intended or a bug?

I also have Tinker's Tool Leveling installed, FYI.

**Comment by BrisingrAerowing** [comment]
It appears to happen with all tools, actually. 😕

**Comment by bonii-xx** [comment]
Sounds like something is using potion effects incorrectly, causing ID's to scramble. In short: some other mod doing things the wrong way.

**Comment by C1ffisme** [comment]
Do cleavers still give mining fatigue? I feel like this could have something to do with it.

**Comment by ArukaAlter** [comment]
They don't give the Fatigue effect since 1.9 due to the new combat mechanics.

**Comment by C1ffisme** [comment]
@ArukaAlter Ah, I thought so. I haven't been playing a lot of Modded 1.10.
