### ISSUE TITLE
Way to disable entity melting

### ISSUE THREAD

**Issue by JasonMcRay** [SlimeKnights/TinkersConstruct#2783]
I am making a modpack and I would love to be able to disable certain entities from smelting (mainly villagers and enderman). I remember seeing it in past versions of TiCo, but seems it is not in 1.10.

Would it be possible to add it? Thanks

**Comment by bonii-xx** [comment]
We have events to allow other mods to influence this, however we don't provide the means to ourselves, nor do we plan to in the near future. We leave all that stuff to crafttweaker and whatnot they're called.

**Comment by CraftMinerKyle** [comment]
An Idea to complete your Idea though could be make an addon that allows a config of the smeltery. I am just giving a stupid and probobly ignored Idea....
