### ISSUE TITLE
Having Iron and Gold blocks entered in oreDict as "blockMetal" lets them be used interchangeably across mods.

### ISSUE THREAD

**Issue by JaSpr** [SlimeKnights/TinkersConstruct#2785]
Many mods will use the ore dictionary to find matches between various ores, ingots, blocks, dusts, etc for different implementations of the same metal.  Tinkers' introduces blockMetal ore dict entry, which includes the gold block and iron block, and can cause the two to become interchangeable. (e.g. crafting an iron block into 9 gold ingots).  Is there some specific purpose for this ore dict entry?

https://github.com/raoulvdberge/refinedstorage/issues/1029

**Comment by bogger33** [comment]
It doesn't seem to get used at all, I tried grepping for it in the codebase. I thought at first maybe for the tool forge or something, but nope.

**Comment by JaSpr** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/f709f4085206c81d602f2f003b383db16163dc58/src/main/java/slimeknights/tconstruct/common/TinkerOredict.java
lines 162-164

**Comment by bogger33** [comment]
Sorry, what I meant was it doesn't seem to get used in any of the tinkers recipes. I glanced over TinkersTools.java as well to make sure it wasn't in there

**Comment by JaSpr** [comment]
Yep! I knew that's what you meant, I just wanted to link where it was getting added, in case they wanted to remove it.

**Comment by JaSpr** [comment]
Any update on this?

**Comment by bonii-xx** [comment]
See https://github.com/raoulvdberge/refinedstorage/issues/1029#issuecomment-283611212
The issue is not really TiC related at all, it's a bug in the autocrafting.
