### ISSUE TITLE
[1.10.2] Crash using hatchet on chopping block

### ISSUE THREAD

**Issue by Silvrus** [SlimeKnights/TinkersConstruct#2787]
Hello, Survivalist adds a chopping block that you use to chop logs into planks. However I'm getting CTD when trying to use a hatchet on it. Gigaherz indicated [here](https://github.com/gigaherz/Survivalist/issues/36) the problem was on your side and asked me to open a ticket. Whenever you get a chance can you check out the crash log and let us know? Thanks! 

[Gist Crashlog](https://gist.github.com/Silvrus/4adeb5082011a9fe6f9bf7e82cde8032)

**Comment by bonii-xx** [comment]
This actually is a bug in Survivalist. They pass in a null blockstate instead of Air. I guess using Air isn't that common in 1.10 though.

**Comment by Silvrus** [comment]
Awesome, thank you!
