### ISSUE TITLE
Infinite Smeltery fluid

### ISSUE THREAD

**Issue by bsamsom** [SlimeKnights/TinkersConstruct#2788]
Playing on a Direwolf 1.10.2 server running Tinkers' Construct 1.10.2-2.6.1, I encounterd an odd bug. I had some molten Manyullyn(a few ingots) in my smeltery and walked by with a piece of Railcraft Firestone ore in my hand. The inside of the smeltery set on fire and when I put the fire out it had 500+ blocks of molten Manyullyn in it. No matter how much I drained out of the smeltery(200+ blocks) it still had the maximum amount of blocks in it for its size(Note: I tried adding a few layers of seared bricks to make the smeltery size go up and it auto filled to the new max size).  Upon breaking the smeltery controller and placing it back down it was still full of the Manyullyn. The only way I found to fix the infinite Manyullyn was to place a different smeltery controller block in its place.

**Comment by bonii-xx** [comment]
That sounds really weird. By your description the TileEntity of the smeltery block was somehow corrupted. Have you tried relogging/restarting the server? It might've been a clientside bug/interaction.

**Comment by bsamsom** [comment]
I ended up fixing it by replacing the block but it did persist past reloggs and a few server restarts. One of the server admins told me to tell you about it as there was nothing they could do.

**Comment by KnightMiner** [comment]
Placing a different controller should have no difference than the same controller unless the location changed, so this does sound quite odd. Out of curosity, are you running a regular Forge server, or something like Sponge?

**Comment by bsamsom** [comment]
I am just a player on this server(Mym direwolf 1.10 server) so im not 100% sure, but the mod list on the server shows Forge Mod loader, and Minecraft Forge.

**Comment by bsamsom** [comment]
Just got a response from the server admins, they are in fact running a Sponge server.

**Comment by KnightMiner** [comment]
Are you able to reproduce this on a regular Forge server?

**Comment by KnightMiner** [comment]
Closing due to lack of response as a SpongeForge issue.
