### ISSUE TITLE
[1.7.10] Haste on Traveller's Gloves not working

### ISSUE THREAD

**Issue by MJRLegends** [SlimeKnights/TinkersConstruct#2789]
Really not sure anything can be done about this or if its even fixed already because its a old ticket that someone made but i thought i'd post it here to see if anything can be done at all for the issue 

See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/453 (Issue reported to me by one of players of my mod pack)

**Comment by ArukaAlter** [comment]
1.7 isn't supported anymore

**Comment by MJRLegends** [comment]
Fair enough

**Comment by MJRLegends** [comment]
Do you know if it was fixed already though?

**Comment by LovelyFlare** [comment]
In every instance of 1.7.10 I've played with Tinkers', haste has worked fine.

**Comment by MJRLegends** [comment]
Ok i will give it a test in the current version of my mod pack

**Comment by MJRLegends** [comment]
Hopefully it has fixed itself
