### ISSUE TITLE
Reskins causing issues with tool cast textures.

### ISSUE THREAD

**Issue by SiNevesh** [SlimeKnights/TinkersConstruct#2790]
I've been retexturing some of the TiC tools to match my vanilla retextures, so I have been working with textures 32x in size. I believe I have set up everything fine, as the actual tools display with no issues. However, I assume the casts are auto-generated as I cannot find textures for them, and the casts of tools I have reskinned have glitched out visually. 
![Example.](https://cloud.githubusercontent.com/assets/26200472/23590492/febc7d06-0195-11e7-9451-bf189a186824.png)

I have to assume it's because of the textures being double the normal size, however I have not done extensive testing as of yet due to my computer being a bit slow for constantly restarting mods or textures.

I apologise if I should have posted this elsewhere, but I am unsure where else to go to bring this up. If this isn't considered important, feel free to close this.

**Comment by bonii-xx** [comment]
I remember this issue coming up before.. I think it was when the cast and the toolpart textures don't match in size. Or maybe it was that it used to crash in that situtaion. Anyway, from the looks of it it can't associate the lines correctly with each other, so I'm pretty sure that having both of the same size fixes the issue.

And don't  worry, this is the correct place ;)

**Comment by SiNevesh** [comment]
Turns out that's what it was, I just had to upscale _cast.png_ (and also _pattern.png_) to be the same resolution. Strangely enough, it seems that the default 16x textures work fine with the 32x _cast.png_.

Anyway, thanks a bunch for the help! I'm glad to have that resolved. :3
