### ISSUE TITLE
Crash after tool durability expires

### ISSUE THREAD

**Issue by jwatsonCSSA** [SlimeKnights/TinkersConstruct#2791]
I am experiencing a crash whenever my tools run out of durability. A cursory glance at the crash report shows an index out of bounds exception. It looks like tinkers does not play nice with the Auto-refill feature in FTB. I have attached the crash report. I am playing FTB Infinity Evolved, with minecraft launcher 1.6.76.

[crash-2017-03-06_08.57.38-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/821537/crash-2017-03-06_08.57.38-client.txt)

**Comment by KnightMiner** [comment]
This issue is on inventory tweaks side by the looks of it, no Tinkers Construct code is referenced.

Additionally, 1.7.10 is no longer supported even if it was a Tinkers Construct issue.
