### ISSUE TITLE
Can't cast custom materials

### ISSUE THREAD

**Issue by FirEmerald** [SlimeKnights/TinkersConstruct#2792]
I'm trying to re-implement my 1.7.10 TC toolparts in 1.10.2, and everything is working EXCEPT I can't cast anything.
My code for adding a tool material is as follows:
```
Material mat = new Material("mc3_phazon", TextFormatting.DARK_AQUA);
mat.setRepresentativeItem(new ItemStack(MC3Blocks.phazon));
mat.addTrait(new TraitPhazon());
mat.setFluid(MC3Fluids.liquidPhazon);
mat.setCastable(true);
if (FMLCommonHandler.instance().getSide().isClient()) mat.setRenderInfo(new MaterialRenderInfo.BlockTexture("mc3:blocks/blockphazonore"));
TinkerRegistry.addMaterialStats(mat, new HandleMaterialStats(1f, 100));
TinkerRegistry.addMaterialStats(mat, new HeadMaterialStats(750, 6f, 8f, 4));
TinkerRegistry.addMaterialStats(mat, new ExtraMaterialStats(60));
TinkerRegistry.addMaterial(mat);
```

I don't think it's an issue as much as it is something I'm missing

**Comment by bonii-xx** [comment]
When are you registering the material?

**Comment by FirEmerald** [comment]
Pre-init

**Comment by FirEmerald** [comment]
I can see how that might be an issue
thanks

**Comment by FirEmerald** [comment]
Nevermind, changing it to post-init didn't change a thing.

**Comment by FirEmerald** [comment]
Found the fix. I needed to replace "TinkerRegistry.addMaterial(mat)" with "TinkerIntegration.integrate(mat, MC3Fluids.liquidPhazon)" and still run it during pre-init. You should probably add this to the wiki or something, since there's pretty much nowhere to find this information.

**Comment by FirEmerald** [comment]
I do still have a bug: the manual doesn't show an item/block for the material

**Comment by FirEmerald** [comment]
nevermind found the issue again.
