### ISSUE TITLE
Crossbow XP stays at 0, Doesn't level up

### ISSUE THREAD

**Issue by FalloutBe** [SlimeKnights/TinkersConstruct#2793]
When killing mobs with the crossbow, only the bolts level up, but the crossbow itself stays at 0XP?!

**Comment by robertquitt** [comment]
I've also noticed this, the XP on ranged weapons only goes up with melee kills.

**Comment by FalloutBe** [comment]
XP of the bolts on the other hand does go up.

**Comment by ArukaAlter** [comment]
Report this to the addon repo, not here.

**Comment by FalloutBe** [comment]
addon repo?

**Comment by ArukaAlter** [comment]
https://github.com/SlimeKnights/TinkersToolLeveling

**Comment by FalloutBe** [comment]
Ok, thanks. I posted it there.

**Comment by ArukaAlter** [comment]
There is a similiar issue already open there.

**Comment by KnightMiner** [comment]
Yep, this is an issue with Tinkers Tool Leveling, not Tinkers Construct itself
