### ISSUE TITLE
Stencil Table not outputting selected stencil

### ISSUE THREAD

**Issue by Fogrits** [SlimeKnights/TinkersConstruct#2794]
[What's happening](http://i.imgur.com/bUTWe3T.png)

Tinkers' Version - 2.6.3 (Latest 1.10)
As you can see in the picture, I've selected a sword blade stencil, but whatever stencil I choose doesn't appear on the right slot

**Comment by KnightMiner** [comment]
Can you give a mod list? A few mods are known to cause issues like this and one of them is likely the cause.

Also, is this single player or multiplayer/a server?

**Comment by Fogrits** [comment]
[Singleplayer](http://i.imgur.com/LCRhzGt.png)

**Comment by bonii-xx** [comment]
#2646

**Comment by Fogrits** [comment]
But I don't have Aether on my modpack

**Comment by bonii-xx** [comment]
Some other mod causing it then. Try a clean install with only mantle and TiC, add mods until you find the culprit.

**Comment by Flabort** [comment]
Two mods in your mod list I would look into testing the compatibility of first is Uncrafting Table, and Optifine. 
Optifine is known to be the mother of all rendering errors, and while I doubt it's the direct cause of this particular issue, is known to cause a lot of problems with Tinkers.
Uncrafting Table, like the issue Bonii referenced, messes with crafting handling. 
I would also look at Cyclic, FoamFix, META, No More Recipe Conflict, Mysterious Miscellany, Akashic Tome, and/or Tesla as potential culprits.
Do what Bonii said, just use Mantle and TiC, then add in these mods until one of them, or none of them, causes TiC to break this way. Then, if none of the mods I identified here were the culprit, then continue with the rest of the mods on your list until one finally reveals itself.

**Comment by Fogrits** [comment]
Funny that I always used the mods from this list, and the only exceptions is M.E.T.A, Astral Sorcery, Minecraft Flux, HWYLA, BotaniaVisualizer, Soul Shards TOW and AR2B (Angel Ring to Bauble). I'll look after them for any incompatibilities

**Comment by Fogrits** [comment]
Found the culprit, was Minecraft Flux (weird, MCFlux only adds energy compatibility and some other blocks).
