### ISSUE TITLE
Lumberaxes not chopping down an entire large oak tree.

### ISSUE THREAD

**Issue by ariosos** [SlimeKnights/TinkersConstruct#2797]
1 - Make a lumberaxe with any material.
2 - Find a giant oak tree.
3 - Chop it down. (best seen with Fast Leaf Decay)

- Not sure if vanilla tree growth mechanics have changed, but sometimes, some high up logs won't be cleared, leaving part of the tree 10 blocks in the air.

**Comment by bonii-xx** [comment]
That is normal, it has always been like that. The lumber axe fells the "trunk", but not disconnected log blocks. If the logs aren't connected to the trunk, they're not gonna get chopped.
