### ISSUE TITLE
Minecraft does not boot with tinkersconstruct

### ISSUE THREAD

**Issue by TheMrCaveman** [SlimeKnights/TinkersConstruct#2798]
Minecraft 1.10.2
Forge 12.18.3.2254
Tconstruct 1.10.2-2.6.3

See crash report:

http://pastebin.com/EkZTwUKA

**Comment by KnightMiner** [comment]
Your resource packs textures are much to large for you to be able to load them all. Try a lower resolution (honestly, can you really see the difference between a 128x and a 64x pack anyways?)

**Comment by TheMrCaveman** [comment]
That has nothing to do with it. Have 32GB ram, and never had an issue with it.

**Comment by KnightMiner** [comment]
Did you read the crash report? It says that is the issue. Tinkers Construct uses a lot of textures for the sake of all the tools, there is nothing we can do if you are maxing the texture sheet size

**Comment by Flabort** [comment]
This line here (line 30 of your crash report, not that far in)
`net.minecraft.client.renderer.StitcherException: Unable to fit: tconstruct:items/hatchet/head_contrast, size: 128x128, atlas: 4096x4096, atlasMax: 4096x4096 - Maybe try a lower resolution resourcepack?`
tells you all you need to know. Literally that your texture pack and mods are incompatible.

**Comment by TheMrCaveman** [comment]
Yes i read the crash report, Not an %T#$%;)

I reinstalled curse/minecraft and issue is gone. So something fishy happened.
