### ISSUE TITLE
OpenGL error 1283 (Not Crash) when equiping Custom NPCs with TConstruct Items

### ISSUE THREAD

**Issue by thefirstgamemaster** [SlimeKnights/TinkersConstruct#2800]
There is no crash to report, but rather a huge bug that makes Minecraft unplayable for me. It appears that I have found the issue to occur when a Custom NPC (using "CustomNPCs_1.10.2(20nov16)") is saved with items from the Tinker's Construct mod (using "TConstruct-1.10.2-2.6.2"). I am unaware if this is expected or not. I have already informed the creator of the CustomNPCs mod.
 
Please see my [Screenshots of Issue](https://minecraft.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.dropbox.com%252fsh%252fr2qus0682zo6tx8%252fAADr8MfzBdDD1okhP6UP_sc-a%253fdl%253d0) (dropbox URL).
 
Minecraft details: running FML 12.18.3.2185 on MC 1.10.2 with Optifine (HD U D6).
 
Thanks in advance for checking up on this..
 
Very Respectfully,
thefirstgamemaster

**Comment by KnightMiner** [comment]
I am not an expert on how the Tinkers tools rendering works, but as I recall they use normal models like a block or item, so they should not be able to cause issues like that since all the code is static.

There are a few things I would say to try to narrow down the cause of the issue, such as removing Optifine (which is largely unsupported) and updating to the latest Tinkers build. I would also make sure this happens with just Tinkers Construct and Custom NPCs, as you seem to have quite a few client side mods loaded based on all the stuff in the GUI.

**Comment by bonii-xx** [comment]
As KnightMiner said, Tinkers is just using regular item models. They're more complex than your average stick, but they work the same. Either Custom NPCs is missing something when rendering the items in the NPCs hand, but it's more likely that it's optifines fault. Also you can be sure that no mod author will ever give you support for any rendering-related issues as long as you have optifine.

**Comment by thefirstgamemaster** [comment]
I have done as you suggested, starting with a clean install of Forge, then customNPCs (without the problem), then adding TConstruct. No further mods were added. After adding TConstuct and using it to equip the test subject (a custom NPC), the same error occurred.

Optifine can no longer be faulted, as it was not installed. Please, let me know if you need pics for proof.

Thank you!

**Comment by bonii-xx** [comment]
Good to know, have you reported it to the custom NPCs developer?

**Comment by thefirstgamemaster** [comment]
Yes... In fact, I notified you after already having done a Forge/customNPC's/TConstruct only build and posting the troubleshooting process to Noppes before you. I suppose should have crosslinked it - I was hopping you would work together to solve the problem anyway. Link is for [CustomNPCs issue #1818](https://minecraft.curseforge.com/projects/custom-npcs/issues/1818).
