### ISSUE TITLE
Recipes 

### ISSUE THREAD

**Issue by ElectricBlue1** [SlimeKnights/TinkersConstruct#2802]
Is it possible to make patterns from the stencil table useless (remove the way to get patterns)? And like use CraftTweaker/ModTweaker to add the recipe?

**Comment by bonii-xx** [comment]
No, there is no way to remove a patterns, and we also don't plan to add one.

**Comment by laz2727** [comment]
You can disable the recipes leading to the patterns, like the empty pattern
or the tables.
