### ISSUE TITLE
[1.10.2] Slime boots should reset fallen blocks on bounce

### ISSUE THREAD

**Issue by Drazuam** [SlimeKnights/TinkersConstruct#2803]
It's kind of silly that they don't; you can bounce and bounce and bounce, but if you then hit shift to stop bouncing while you're close to the ground, you get hit with a bunch of fall damage.  I realize this is somewhat taken care of with setting the damage multiplier to 0.1 when you sneak, but it's still a jarring experience.

I think the appropriate thing to do would be to set entity.fallDistance to zero upon hitting the ground, currently ~line 120 of ItemSlimeBoots.java, and remove the sneaking behavior.

**Comment by bonii-xx** [comment]
..only after rereading it now I realize that you totally wanted something different than I thought. The fall damage is there as a counterbalance point, it's not getting removed.

**Comment by Drazuam** [comment]
I don't think I got my point across; I don't think the slime boots should cancel all fall damage even when holding shift.  Current implementation (or at least at the time when I wrote this), would cause the following situation to happen:

1) user jumps from 100m high
2) user bounces several times off the ground, with the last bounce being 3 blocks high
3) user holds sneak to stop bouncing, striking ground
4) user takes 10% of  the original 100m fall damage (event.setDamageMultiplier(0.1f);), much higher than 3m fall damage that seems like it should take

This happens because the entity.fallDistance isn't zeroed when the boots bounce.  If it was, the user would take the fall damage of the last bounce height, not the first jump.  Playing around with them right now is a little jarring, because you can take heaps of damage from what seems like a 2-3m drop.  The only way to use them is to either have flying or to wait it out until you stop bouncing altogether.

Is this intended behavior?  If it is, the sneaking behavior seems _almost_ pointless.

For reference, my line number suggestion has changed to line #142.  You would also have to omit line 165 event.setDamageMultiplier(0.1f);

**Comment by bonii-xx** [comment]
Ah, yes. I remember something like that, and thought it was addressed. Yeah the damage should only be relative to the actual distance fallen since the last bounce.

**Comment by bonii-xx** [comment]
Finally got time to look into this. The issue actually was that the server didn't even know when you bounced.

**Comment by Drazuam** [comment]
Thanks!  Works perfectly now.
