### ISSUE TITLE
New fuels added by minetweaker dont cook anything

### ISSUE THREAD

**Issue by Saereth** [SlimeKnights/TinkersConstruct#2806]
originally posted this issue with modtweaker but it seems to be a tinker's issue since the fluid does register properly:
https://github.com/jaredlll08/ModTweaker/issues/439#issuecomment-286302029

Basically I added pyrotheum as a fuel, it showed the heat as 4000C but wouldn't melt anything claiming it was too cold. 
 
images of the issues: http://imgur.com/a/Lduu3

MC: 1.10.2
Tinkers: TConstruct-1.10.2-2.6.3
Forge: 12.18.3.2254

**Comment by adiyasaU** [comment]
I'm experiencing the same issue right now, as I can't really melt down Minecraft's Emerald Block with just lava, and I can't repurpose EnderIo's Dark Steel out since it needs 1800C to melt

**Comment by Hexus-One** [comment]
Same deal here - trying to melt snowballs and literally only lava works.
tinker.zs looks like this, I've edited it ingame and then used 

> /mt reload

to reload the scripts.

`
mods.tconstruct.Smeltery.addFuel(<liquid:ic2steam>);
mods.tconstruct.Smeltery.addFuel(<liquid:ic2superheated_steam>);
mods.tconstruct.Smeltery.addFuel(<liquid:pyrotheum>);
mods.tconstruct.Smeltery.addFuel(<liquid:xu_demonic_metal>);
mods.tconstruct.Smeltery.addFuel(<liquid:steam>);
`

**Comment by KnightMiner** [comment]
Reading the modtweaker code, I am having trouble finding where it actually adds the fuels. They are simply pulling a copy of the fuel list and adding to that copy, so it is never registered.

The temperature is shown regardless of the fluid IIRC, try seared stone to see what I mean.

**Comment by bonii-xx** [comment]
Sounds like modtweaker doing things wrong, yeah. We need to check if we display non-fluids in the Fuel thing, that's pretty confusing. Should at least have a "NOT A FUEL" tooltip.

**Comment by PapiDimmi** [comment]
@bonii-xx Since this has been resolved, shouldn’t this issue be closed?

**Comment by KnightMiner** [comment]
No, it has not been released yet.

**Comment by PapiDimmi** [comment]
Oh, I see.

**Comment by Ben64** [comment]
So this will not make pyrotheum usable still, just show an error? Can it be added as a fuel again?

**Comment by bonii-xx** [comment]
Yes and Yes. This will just show you when you have something that is not a fuel. Anything can be added as fuel via the proper api, has always been able to. If minetweakers stuff doesn't work then that's because they're not doing it over the proper API.

**Comment by Ben64** [comment]
Wish I saw your comment before diving into java. I came to the same conclusion as you did. Thanks
