### ISSUE TITLE
Can't progress because flint tools only mine stone (Iguana Tinker Tweaks)

### ISSUE THREAD

**Issue by patrickdrken** [SlimeKnights/TinkersConstruct#2807]
Hello, my problem is that i can't progress because i cannot mine anything other than stone using the TiC pickaxes. I have figured out that it is Iguana Tinker Tweaks that is doing this but i don't know how to fix it.
here's all the info:

minecraft 1.7.10
forge 1.7.10 1614
iguanaTT 1.7.10-2.1.6

tell me if you need any more info
And i know that someone is just gonna tell me to uninstall iguanaTT but i'm not doing that cuz i'm starting to get bored of the normal TiC

edit: i checked the config files and the only thing i found was a thing the the Modules.cfg:

  # Modify tool and item mining levels to create a tiered-ish progression B:HarvestLevelTweaks=

so i tried using both =true and =false but the tools still only has a mining level of stone (not all the TiC have a stone mining level only the starting ones, wood, flint, bone and so on

**Comment by border999** [comment]
I might recommend dungeon crawling until you find a diamond. Add it to a pickaxe and you'll be able to mine materials for better picks.

**Comment by patrickdrken** [comment]
yeah but how am i supposed to mine the diamond?

**Comment by patrickdrken** [comment]
good idea but i don't wanna have to go through all of that trouble so if no one answers i'll try that but i would prefer a fix in the config or something

**Comment by KnightMiner** [comment]
You need to upgrade your tools mining level by using it enough. Check the mining XP stat (install TiC tooltips if it is not already installed to help with that)

In any case, Iguana Tinker Tweaks is an add-on with its own issue tracker and 1.7.10 is no longer supported, so closing this issue.
