### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Tenchu98** [SlimeKnights/TinkersConstruct#2808]
I would like to see a little more integration:
Molten Nether Star for making tools and weapons.
Armor casting, instead of waiting for another mod to add it.
Coolant creation in smeltery for extreme reactors.
For skyblock I would like to see things like copper and nickel getting more uses, maybe modifiers for xp boost or illumination on tools.

I always thought a casted book would be the perfect manual for tinkers as well, make a cast with gold and a book and then use brass to make the manual in the cast.

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ
