### ISSUE TITLE
1.10.2 Blood Locking Casting Basins

### ISSUE THREAD

**Issue by ArkavianX** [SlimeKnights/TinkersConstruct#2809]
When using EnderIO Ender Fluid conduits to pull liquids from the smeltery, everything is fine until the fluids fall to some random blood. When it tries to place blood into the casting basin it will stall as just stall out listing "blood 0mb" unable to remove until you break the casting basin. 

As well, can we get an oven light block to prevent mobs spawning in large smelteries?

SkyFactory 3 pack from Curse

**Comment by ArkavianX** [comment]
Blood indicator appears to vanish when only fluid left in the smeltery when EnderIO Fluid conduits are in use too.

**Comment by bonii-xx** [comment]
Should be fixed in the 1.12 casting fixes.
