### ISSUE TITLE
Fluid switching bug when using enderio fluid conduits instead of smeltery drain

### ISSUE THREAD

**Issue by brian91292** [SlimeKnights/TinkersConstruct#2810]
As described in the title, when using a fluid conduit which constantly pulls from the smeltery without user interaction, the fluid does not correctly switch when you change the order in the smeltery controller GUI. For instance, I had selected seared stone in my smeltery, and started up my auto-casting system which is just an ender-io fluid conduit (pressurized), with both sides set to input/extract, and one set to redstone on, the other set to redstone off (essentially when you flip the switch if theres any excess in the basin or table, it's reinserted into the smeltery when you flip the switch). If I turn on the system, then change the order of fluids in the controller GUI, the result is that the smeltery continues to pull seared stone even if I selected say, iron, until the seared stone is completely used up.

Not a huge bug, but still something that should be addressed. This is in the modpack FTB Beyond 1.1.0 BTW, which includes Tinkers Construct 2.6.3.

**Comment by brian91292** [comment]
To add a bit more info about the bug, when I attach the fluid conduit in the configuration I described, I have to initially switch the mode on the end of the conduit which is attached to the casting table to "insert" in order to get it to insert fluid into the table at all, then afterwords I can switch back to in/out and it works as I described above. Haven't tried with any other type of conduits/pipes yet, but I will post back here with results after I do. This could be an issue on enderio's end, but until I do some further testing I'm not quite sure.

**Comment by brian91292** [comment]
Whatever is happening in this interaction seems to completely break the casting table until I break it and replace it (it only detects fluids that were in the smeltery prior to the glitch occurring I believe). After the glitch occurs, if I melt down another metal in the smeltery and attempt to pour it into a casting table using enderio conduits, nothing happens. The liquid shows up visually in the conduit but nothing happens. This issue continues even after relogging.

Also, when the glitch occurs if I try to break the enderio conduit and pour from the smeltery using a seared faucet instead, the faucet will pour infinitely as if it was dumping the fluid into the void. The only way to fix it is breaking the casting table, at which point everything is back to normal.

Still not sure if this is an issue on enderio's end or tinkers... but with the casting table becoming unusable, my bet is it's a tinkers bug.

Hopefully this information helps :)

**Comment by brian91292** [comment]
Also just to be clear- the infinitely pouring liquid is not a client-side bug; the liquid is actually being deleted from the game (I relogged to confirm this). From what I've gathered, there doesn't seem to be any issue relating to client-server desync occurring in this case

**Comment by CraftMinerKyle** [comment]
Perhaps the pipes aren't recognizing the Casting Basin as a proper inventory? Or they attempt to continue to fill it even after it is full and cooled?

**Comment by KnightMiner** [comment]
Sounds like an issue on Ender IO's end or another mod is conflicting, as Immersive Engineering pipes work on the tables without issue. Try it with just Ender IO and Tinkers Construct installed and see if the issue persists.

**Comment by bonii-xx** [comment]
Should've fixed caught by the 1.12 bugfixes.
