### ISSUE TITLE
[1.10.2] Knightslime Large Plate doesn't give Unnatural trait

### ISSUE THREAD

**Issue by Hirsu** [SlimeKnights/TinkersConstruct#2811]
Hi there,

I'm currently trying to put together a hammer made out of the following components:

- Head: Cobalt (for mining speed, durability and Momentum)
- Large Plate 1: Cobalt (for mining speed, durability and Lightweight)
- Large Plate 2: Knightslime (for Unnatural)
- Tought Tool Rod: Ardite (for 1.4 modifier and Petramor)

I went with Knightslime for my second plate due to the Unnatural trait. Since mostly stone blocks will be mined, having a trait like Unnatural to speed up mining these blocks would be great!

However, when I put all these components together in a Tool Forge, I noticed my hammer got Crumbling instead of Unnatural. A quick look at the in-game materials manual and JEI led me to believe Knightslime was still supposed to give Unnatural when used on an extra component (and according to the manual, a large plate is considered to be an extra component). Only when used as a head should I be getting Crumbling on this hammer.

So, am I missing something obvious here (very likely), am I dealing with outdated in-game documentation or is this a genuine bug?

Relevant version information:
- Minecraft 1.10.2
- Forge 1.10.2-12.18.3.2254
- Tinker's Construct 1.10.2-2.6.3
(Modpack: FTB Beyond 1.2.1)

Please let me know if you require further information!

Thanks

**Comment by bonii-xx** [comment]
Large plates are head components for the hammer, hence they give the head trait. You'll have to use a Knightslime handle.

**Comment by Hirsu** [comment]
Ah, that explains alot! My confusion came from seeing the large plate pop up as an Extra in the manual, but now I noitced the plate popping up under the Head section as well.

My bad! Thanks for the quick reply.

**Comment by bonii-xx** [comment]
In general the tooltip on the part displays all that's that are used in some tool. Only the ones that actually get used are displayed on there, it just doesn't display which tool uses it as which. That's part of the tinkering (and tool balance ;))
