### ISSUE TITLE
Crafting Table Render Crash

### ISSUE THREAD

**Issue by phit** [SlimeKnights/TinkersConstruct#2812]
Reported by a player on my server, modpack is FTB Beyond 1.1.0
They put a ArchitectureCraft Railing inside the table, I also reported this to the ArchitectureCraft developer.

[crash-2017-03-18_19.08.18-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/852851/crash-2017-03-18_19.08.18-client.txt)

**Comment by LovelyFlare** [comment]
That would be a problem on architecturecraft's side for not doing proper models.  Same exact thing happens with Mekanism items when put into Crafting Stations.  Change the config to not render things on top of Crafting Stations etc. if you don't wish to deal with this.

**Comment by bonii-xx** [comment]
Yup, broken models.
