### ISSUE TITLE
Invar doesn't alloy in smeltry.

### ISSUE THREAD

**Issue by andyglover** [SlimeKnights/TinkersConstruct#2813]
Molten nickel and iron do not combine to make invar in the smeltry.

**Comment by ArukaAlter** [comment]
If a mod registers ingotInvar in the ore dictionary it does alloy, your instance probably doesn't have a mod that includes invar.

**Comment by andyglover** [comment]
I can combine nickel and iron dust in crafting table to make invar. 

I'm using the FTB Beyond mod pack, smelting a vanilla minecraft iron ingot, and a thermal foundation nickel ingot. I noticed molten invar does not appear in JEI. Maybe this is an issue with the modpack?

**Comment by bonii-xx** [comment]
There is no invar support in 1.8+

**Comment by ArukaAlter** [comment]
It makes sense as there's no invar as material, but when Tech Reborn is present the alloy is possible in the Smeltery.

**Comment by bonii-xx** [comment]
Then Tech Reborn adds support for it ;o

**Comment by Utildayael** [comment]
King Lemming still hasn't done his TIC integration piece for TE 5 which is why it isn't working. He has open issues on it and it is on the to-do list last I read.
