### ISSUE TITLE
Alumite part Linked chest issue

### ISSUE THREAD

**Issue by CriticalMole** [SlimeKnights/TinkersConstruct#2814]
When having a pick linked to a chest via the alumite ability and the chest is full we are finding that while ores and the like are dropping on the ground, other items like ExU2 generators are poofing out of existence when broken.
Not sure if there is anything I can do to reolve this or if it is a full on bug for you guys

**Comment by ArukaAlter** [comment]
There's no longer alumite in the mod.

**Comment by KnightMiner** [comment]
What do you mean by "linked to a chest via the alumite ability"? Alumite in 1.7.10 had no special abilities, and it does not exist at all in 1..8+ when traits were added.

**Comment by bonii-xx** [comment]
I literally have no idea what you're talking about, and I'm pretty sure it's also completely unrelated to the mod itself.

**Comment by CriticalMole** [comment]
Sorry my bad, added by an addon, thought it was still one of the base alloys :)
