### ISSUE TITLE
Question about cast textures

### ISSUE THREAD

**Issue by StefanTT** [SlimeKnights/TinkersConstruct#2815]
Hello!

I am doing the textures for Tinker's for the Faithful32 texture pack. Unfortunately we have a little problem here. When creating e.g. a hatchet head in the smeltery, the iron head is not aligned with the cast.
Please have a look at this picture: [http://i.imgur.com/noE8kmC.png](http://i.imgur.com/noE8kmC.png)

Unfortunately I have not found how the cast textures are created so that I can fix it in the texture pack. Can you please give me a hint?

Edit: sorry, I forgot to say, I am talking of the version for Minecraft 1.10.2

**Comment by Flabort** [comment]
I get a 404 error clicking on your image. Copy and paste works fine though. [Here, this link should work for you](http://i.imgur.com/noE8kmC.png) - the URL goes in the rounded brackets and the text in the square brackets `[text](url)` Like so

**Comment by StefanTT** [comment]
Oh ... yes, thanks, I updated the link.

**Comment by PapiDimmi** [comment]
You can also attach images by clicking the “selecting them” link or dragging and dropping.

**Comment by bonii-xx** [comment]
Curious. I assume you have multiple textures for hatchet heads, are they by chance not aligned with the base texture?

**Comment by StefanTT** [comment]
I have loaded the 32x32 texture into GIMP and overlayed it with the original 16x16 texture which was zoomed to 32x32. The transparent part is the original texture (head.png #1):

[hatchet head comparison](http://storage8.static.itmages.com/i/17/0323/h_1490289191_3999873_29c896be23.png)

I assume that assets/tconstruct/textures/items/hatchet/head.png is the texture that is used for the iron head. Which texture is used for creating the cast? Is it the blank assets/tconstruct/textures/items/cast.png with the head.png punched out?

**Comment by bonii-xx** [comment]
Yes, they're generated from the item and the blank cast. And the texture is whatever is defined in the model for the axe head.

Out of curiousity, is it gone if you remove the pattern/cast offset from the axe head model in the resource pack? (https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tconstruct/models/item/parts/axe_head.tmat.json)

**Comment by StefanTT** [comment]
Indeed, setting the values to zero fixes it. In contrast, duplicating the values (as the textures are also 32x32 - duplicated) makes it worse:
[hatchet head with duplicated offsets](http://storage6.static.itmages.com/i/17/0323/h_1490292104_5007262_8deaaf8296.png)

**Comment by bonii-xx** [comment]
Are blank cast and axe head the same resolution? Seems to me like the cast might still be 16x16

**Comment by StefanTT** [comment]
cast.png is 32x32

If you want to investigate it directly, feel free to download the texture pack from [http://www.f32.me/F32-1.10.2.zip](http://www.f32.me/F32-1.10.2.zip), but I am happy to test whatever you want me to test :-)

**Comment by StefanTT** [comment]
Do you plan to fix it in tconstruct, or shall I set the offset to 0;0 in all affected casts?
I would love to solve this issue somehow, both versions are fine for me.

**Comment by bonii-xx** [comment]
I want to look into it a bit once I find time.. I suppose the offset is somehow being added incorrectly. But it'll take longer, so I suggest you just go with the no-offset-solution even though it's suboptimal. You're independent of our fixes that way.

**Comment by StefanTT** [comment]
I will do so, thank you very much for your help!
