### ISSUE TITLE
JEI says that gold casts are consumed, even though they aren’t consumed when used

### ISSUE THREAD

**Issue by PapiDimmi** [SlimeKnights/TinkersConstruct#2816]
![2017-03-23_14 10 42](https://cloud.githubusercontent.com/assets/25916106/24249182/9389219c-0fd2-11e7-84dd-6146c78530d2.png)

**Comment by KnightMiner** [comment]
That is on cast creation, the tool part (the cast) is consumed when pouring molten gold on it.

**Comment by PapiDimmi** [comment]
Oh, I understand. Thanks.
