### ISSUE TITLE
When I start the game it's show me this

### ISSUE THREAD

**Issue by RonghaoLuo** [SlimeKnights/TinkersConstruct#2817]
Tinkers Construct lacks one or more Mods on which it depends. Please install the following version of Mod, or choose to remove Tinkers Construct.Mantle 1.10.2-1.1.4 or later.

**Comment by KnightMiner** [comment]
Install or update Mantle, it is a required dependency.

**Comment by laz2727** [comment]
Gotta love it when people copy errors without reading them first.
