### ISSUE TITLE
Tinker's Glass should affect Beacon Beam color and Tinker's Blocks of Metal should be usable as Beacon Base blocks

### ISSUE THREAD

**Issue by Drullkus** [SlimeKnights/TinkersConstruct#2819]
![2017-03-26_12 31 32](https://cloud.githubusercontent.com/assets/5010174/24334820/69f05f48-1226-11e7-8352-04b5d56ba793.png)

You can use method `public float[] getBeaconColorMultiplier(IBlockState, World, BlockPos, BlockPos)` from the `Block` class and return `float[]` the size of 3 containing values between `0.0` and `1.0` defining the RGB multiplier for beacon colors in the class for Glass. To quickly get dye color floats you can use `EntitySheep.getDyeRgb(EnumDyeColor.byMetadata(int))` since your Clear Stained Glasses are ordered from White to Black.

And then there is the `public boolean isBeaconBase(IBlockAccess, BlockPos, BlockPos)` for making a block usable as a Beacon base block or not.

**Comment by bonii-xx** [comment]
Riiiight. Beacons are a thing.

**Comment by bonii-xx** [comment]
I went with the actual stained glass color. No idea how far it deviates, but it seems more in line and is less error prone.
