### ISSUE TITLE
[Suggestion] A way to rename Tinkers’ Construct weapons and tools without repairing, adding a modifier, or changing parts?

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#2820]
I always forget to rename my Tinkers’ Construct tools and weapons when I create them. In order to rename a tool, I _have_ to add a modifier, repair the tool, or change one of the parts, which is mildly annoying.

**Comment by laz2727** [comment]
Nametag modifier is free. Apart from the tag itself :P

**Comment by PapiDimmi** [comment]
@laz2727 What do you mean by “nametag modifier”?

**Comment by laz2727** [comment]
You can change a tool's name at any time by applying a name tag to it. It's
entirely cosmetic so it's free.

**Comment by PapiDimmi** [comment]
It’s not free, since you’re wasting a name tag.

**Comment by bookerthegeek** [comment]
@PapiDimmi please read the full response before replying.

> Nametag modifier is free. Apart from the tag itself :P
> - laz2727

**Comment by CraftMinerKyle** [comment]
You can also rename it in an anvil.

**Comment by PapiDimmi** [comment]
@CraftMinerKyle Then you’re wasting XP.

I don’t get why you can’t name your tool in a tool station or tool forge unless you make some sort of change to it.

**Comment by LuigiHutch** [comment]
GitHub is for bug reports, not complaining about design decisions. Take your complaints to Reddit or IRC etc.

**Comment by PapiDimmi** [comment]
This is a minor feature suggestion, not a complaint about design decisions.

**Comment by PapiDimmi** [comment]
This is a minor feature suggestion, not a complaint about design decisions.

GitHub isn’t just for bug reports. It’s for questions, suggestions, and discussions as well, depending on what the contributors of a repository want.

**Comment by LuigiHutch** [comment]
'I don’t get why you can’t name your tool in a tool station or tool forge unless you make some sort of change to it.' Sounds like a complaint to me.

If you actually read the FAQ, you would see that this repo does not take suggestions and will be closed without a warning.

**Comment by PapiDimmi** [comment]
>'I don’t get why you can’t name your tool in a tool station or tool forge unless you make some sort of change to it.' Sounds like a complaint to me.

Sure. This is more of a question as to whether this is an oversight or intentional than an actual suggestion, but you can take it both ways.

>If you actually read the FAQ, you would see that this repo does not take suggestions and will be closed without a warning.

The [guidelines](https://github.com/SlimeKnights/TinkersConstruct/blob/master/CONTRIBUTING.md) state that _generally_, suggestions will be closed. It doesn’t say not to post suggestions.

Besides, this is just a minor tweak that I’m suggestion, and like I said, it may even be an oversight. I’m not suggesting a major feature, a new weapon, a new block, or anything of the sort.

**Comment by bookerthegeek** [comment]
@PapiDimmi once again I see you are causing issues.

The fact that you find it annoying, that you feel it could be better a different way, makes this not a bug report but a thread about your opinion. Yes you had a question but that does not change the fact that this is not an issue or a bug. And the question was already answered. At this point the thread is you once again being argumentative with people who make mods.

Please take a moment to think about how what you post will be taken by others that read you posts. If you keep this up you will find youself blocked from another repository.

To everyone else, name tags work wonderfully for renaming tools.
