### ISSUE TITLE
incompatible with liteloader ?

### ISSUE THREAD

**Issue by ToserBan** [SlimeKnights/TinkersConstruct#2821]
Hello, i installed TinkersConstruct together with forge and liteloader, but it doesnt work. Is this a known problem ? Second problem is when i start SEUS shader mod together with my Tinkers profile. The game is unplayable slow then ( 0-1 fps ).

**Comment by Flabort** [comment]
Let's go through the checklist.
Which version of minecraft and which version of Tinkers? Legacy versions are no longer supported.
Do you have mantle installed? It's a prerequisite, so install it.
Do you have Optifine installed? It's a mess of problems if you do, so uninstall it.
Finally, if you just have mantle, tinkers, and the cross-mod interaction mods (in your case liteloader and SEUS), does the problem persist?

**Comment by ToserBan** [comment]
Hi SlimeKnights,thank you for you answer, here is my config:
minecraft version 1.10.2Tinkers construct version 1.10.2-2.6.3
yes, i have mantle installed 1.10.2-1.1.5forge version 1.10.2-12.18.3.2185 (plus spawnchecker-2.5.1.134 and XRay-43)
liteloader 1.10.2-00 (and voxelmap 1.6.5 for 1.10.2)

it runs if i delete the optifine jar file out of the \mods\1.10.2 folder  orif i leave the optifine jar file where it is but deactivate the shader.So i get everything running together except shaders. Is there a possibility to get a shader mod running together with this configuration ?The problem is if i deactivate optifine, i cant choose a shaderpack to run. After deleting optifine.jar, the related option disappears under grafics



      Von: Flabort <notifications@github.com>
 An: SlimeKnights/TinkersConstruct <TinkersConstruct@noreply.github.com> 
CC: ToserBan <toser_ban@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 2:22 Dienstag, 28.März 2017
 Betreff: Re: [SlimeKnights/TinkersConstruct] incompatible with liteloader ? (#2821)
   
Let's go through the checklist.
Which version of minecraft and which version of Tinkers? Legacy versions are no longer supported.
Do you have mantle installed? It's a prerequisite, so install it.
Do you have Optifine installed? It's a mess of problems if you do, so uninstall it.
Finally, if you just have mantle, tinkers, and the cross-mod interaction mods (in your case liteloader and SEUS), does the problem persist?—

**Comment by Flabort** [comment]
I'm afraid as long as you have optifine, the mod authors of Tinkers won't provide support to your issue, due to what hacks optifine does to rendering and textures, and due to optifine being closed source and nearly impossible to code compatibility for as a result. If optifine is the only way to get your shaders running, I'm afraid you're out of luck. 
As for ideas for replacements to get your shaders working, I have no clue. Personally, I don't use them.

**Comment by bonii-xx** [comment]
We don't have specific support for liteloader, but as war as I'm aware there are no incompatibilities with it. Optifine and shaders change how minecraft rendering works, this is not something any modder can and will support, but I know that there are many people using both, so you're probably just using a wrong optifine version or something. Other than that you're on your own.
