### ISSUE TITLE
Lag Caused When Tinkers Construct Shows Up In JEI

### ISSUE THREAD

**Issue by BigFriendlyJakey** [SlimeKnights/TinkersConstruct#2823]
I'll keep it short and sweet; anytime anything related to Tinkers shows up in JEI, my FPS goes from 100-120 to 10-20. Any specific mods known to cause this?

JEI Version: jei_1.10.2-3.13.6.388
Tinkers Version: TConstruct-1.10.2-2.6.1
Mantle Version: Mantle-1.10.2-1.1.3
Forge Version: 1.10.2forge-1.10.2-12.18.3.2221

**Comment by Flabort** [comment]
Let's go through the checklist. (I am not a developer, I just see them ask these every time)
- [ x ] Which version of minecraft and which version of Tinkers? Legacy versions are no longer supported.
- [ x ] Do you have mantle installed? It's a prerequisite, so install it.
- [ ] Do you have Optifine installed? It's a mess of problems if you do, so uninstall it.
- [ ] Finally, if you just have mantle, tinkers, and the cross-mod interaction mods, does the problem persist?

**Comment by Flabort** [comment]
I see the mod devs ask these questions all the time, so here goes.
A) Do you have optifine, liteloader, etc which might be causing rendering issues?
B) Does the problem persist with **just** Forge, Tinkers, Mantle, and JEI?

There's two other questions in the default question list, but you already answered them, so I won't repeat them here.

**Comment by BigFriendlyJakey** [comment]
Have Optifine, and not sure, so I'll test those

**Comment by bonii-xx** [comment]
JEI and Tinkers already have optimizations in place for minimal performance impact. Keep in mind that opening JEI requires your PC to render *a lot* of items, it might simply be too much. Increasing GUI size usually helps in that case. Other than that, Optifine is not supported and it might as well be that ruining your FPS.
