### ISSUE TITLE
Repairing metal tools with nuggets?

### ISSUE THREAD

**Issue by SHIuSH** [SlimeKnights/TinkersConstruct#2824]
why not?

**Comment by bonii-xx** [comment]
Good question. Apparently neither the nuggets nor the blocks are associated with the materials. That it took nearly 1 1/2 years to notice shows how often it's used, I guess, heh.

**Comment by bookerthegeek** [comment]
Noticed, just figured that ingots were required. Lol.

**Comment by laz2727** [comment]
Considering the massive rebalance and "don't ask stupid questions" policy,
it was inevitable.
