### ISSUE TITLE
[Mod (In)comatibility] Arrows from "Bullseye" mod don't work with Tinker's construct bows

### ISSUE THREAD

**Issue by Burgersim** [SlimeKnights/TinkersConstruct#2825]
Well, exactly what it says in the title. According to the mod author from the Bullseye Mod, the Arrows should work like Vanilla Arrows, but TInker's Bows don't seem to recognize them.

**Comment by KnightMiner** [comment]
Yeah, we know. Its on the todo list. Problem is we have a list of arrow items stored for the sake of the model rendering and need to work on a way to dynamically add other arrows to the list cleanly.

**Comment by bonii-xx** [comment]
I remember I wanted to dynamically construct the list based on registered items on post-init at some point. Or something along those lines. I never implemented it though. :D
