### ISSUE TITLE
Natura Error Caused by TConstruct

### ISSUE THREAD

**Issue by TheCandiedHat** [SlimeKnights/TinkersConstruct#2826]
Natura's lang file is fine. So is the code that's fetching the lang info. The problem is  TinkerersConstruct. Natura requires Tinkerers Construct in order to work properly, and the only known version of Tinkerers Construct that works right with Natura is the 1.8.9 version. This is fine, of course, unless you want all the features of the newer Tinkerers Construct.

**Comment by KnightMiner** [comment]
I'm sorry, what is going on in this issue report?

* First off, what is the error
* Second off what do you mean by the only version what works right is the 1.8.9 version? Natura had no 1.8.9 version.
* Thirdly, I use both and have no issues.

**Comment by LovelyFlare** [comment]
Maybe it is an April Fools joke?

**Comment by CraftMinerKyle** [comment]
The problem could be (This has happened to me with other mods, IDK how) that an addon for another mod is conflicting somehow. Just throwing that in there if that could be the case.

**Comment by KnightMiner** [comment]
Closing this because I have received no response, and progwml6/Natura#328 seems to imply this is a known Natura issue which was fixed.
