### ISSUE TITLE
Projectiles act funky when moving

### ISSUE THREAD

**Issue by SHIuSH** [SlimeKnights/TinkersConstruct#2827]
Can't really explain how it glitches  [so here's record](https://www.youtube.com/watch?v=Kfg-5NfwwOY)
[list of mods](https://paste.ee/p/mRpHd)

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

Also, when shooting really fast, keep in mind that mobs have an invulnerability period after being hit.

**Comment by TheUnhackedPro** [comment]
It

**Comment by SHIuSH** [comment]
works good with only TiC and Mantle. But what could cause this behaviour in my modpack? Arrows seem to hit something(prob. player) seconds after fired.

**Comment by SHIuSH** [comment]
apparently i'm having troubles with not only TiC projectiles. Skeletons' arrows sometimes just bounce off of me or don't even appear when they shoot. What could cause this?

**Comment by SHIuSH** [comment]
After testing each mod in modpack: Chiseled-Me mod was causing major bugs with player hitbox and projectiles

**Comment by KnightMiner** [comment]
I'm closing this as caused by another mod, both because it is affecting non-Tinkers projectiles (which we do not modify in any way) and because the mod Chiseled-Me is known to be a bit unstable (the mod does some extreme core-modding to make shrinking and growing work)
