### ISSUE TITLE
Sky factory 2.5 bug?

### ISSUE THREAD

**Issue by RABB1DTURTLE2** [SlimeKnights/TinkersConstruct#2828]
I'm sure this issue has been covered before but I cannot seem to find any topics about it. If I die my tinkers tools turn into stone. Is this a bug with tinkers construct tools? I'm playing on the latest version of Sky Factory 2.5 (MC version 1.7.10). Any help would be greatly appreciated!

**Comment by KnightMiner** [comment]
Sounds like some mod is deleting NBT on death. I have never heard of this issue before and it is almost certainly not a Tinkers Construct issue since it does not happen with just Tinkers.

Additionally, 1.7.10 is no longer supported, so closing.
