### ISSUE TITLE
Can't Unlink Global Traveler

### ISSUE THREAD

**Issue by twjolson** [SlimeKnights/TinkersConstruct#2832]
Not sure if a bug, or just it just isn't documented : 

I linked a global traveler pickaxe with a chest, and now i want to unlink it so that blocks mined just fall to the ground.

How do I unlink a global traveler pickaxe without creating a second pickaxe or swapping out parts?

**Comment by ArukaAlter** [comment]
This is definitely not a Tinkers' issue.

**Comment by KnightMiner** [comment]
There is no global traveler's pickaxe in Tinkers Construct, sounds like an addon. The material/modifier that adds it should say in the tooltip which mod added it.

**Comment by Landmaster** [comment]
@twjolson Press the "toggle gui" key (default "I") to open a gui to disable Global Traveler. (Global Traveler is from my mod, PlusTiC.)
