### ISSUE TITLE
crash with forge essentials 1.10.2

### ISSUE THREAD

**Issue by Ryudragon2** [SlimeKnights/TinkersConstruct#2833]
when i use a crafting station with forge essentials installed the game crashes

https://pastebin.com/2vQZCv6D

**Comment by KnightMiner** [comment]
Okay, first off, that is only about half of the crash report, you are missing the entire first half which tends to have the most useful information. You do not need to copy it from the game logs, there is a crash reports folder.

Secondly, you are using Optifine, don't do that. Recreate the crash without Optifine to verify it is not an Optifine error, or preferably with just Forge, Forge Essentials, and Tinkers Construct (by extension Mantle)

**Comment by Ryudragon2** [comment]
hey knightminer made a forge with just tinkers and forge essentials and mantle here is the crash report

https://pastebin.com/11ev4wKb

**Comment by bonii-xx** [comment]
Closing due to age and lost stacktraces :(
