### ISSUE TITLE
1.10.2 crash with mods (no idea why)

### ISSUE THREAD

**Issue by hansmc1** [SlimeKnights/TinkersConstruct#2835]
[crash-2017-04-09_16.16.02-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/908067/crash-2017-04-09_16.16.02-client.txt)

**Comment by bonii-xx** [comment]
You're running out of memory, you need to give the game more RAM. Looks like you're running with the default java 512mb, you'll need to give it at least 2GB. How that's done depends on what launcher you're using, but google is your friend there.
