### ISSUE TITLE
1.10.2 Tinkers Construct Ingot case/Nugget case not working with Aether 2

### ISSUE THREAD

**Issue by Zeusanite** [SlimeKnights/TinkersConstruct#2836]
when i have Aether 2 installed everything on tinkers works other then the stencil table, Ingot cast/nugget
does not pour

**Comment by KnightMiner** [comment]
Aether 2 is known to cause issues with the stencil table. It is there fault as our GUI's are done properly and don't break with most other mods. Look for this issue on their tracker.

Ingots and nuggets is likely the same thing we already know Aether 2 is doing something wrong.
