### ISSUE TITLE
The texture of this cleaver does not change when it’s broken

### ISSUE THREAD

**Issue by PapiDimmi** [SlimeKnights/TinkersConstruct#2838]
![tinkers construct texture bug](https://cloud.githubusercontent.com/assets/25916106/24838893/2ff671ac-1d51-11e7-8bd6-5afe6c59bee5.png)

That’s a broken cleaver, but it looks like it’s not broken at all. Isn’t the texture support to change when it’s broken?

**Comment by KnightMiner** [comment]
Looks like the beheading modifier is covering the part of the blade that is broken. If you make a cleaner without beheading it should appear broke as expected, thus this is working as intended (it might be

**Comment by PapiDimmi** [comment]
Well, it’s intended to appear as being broken, right? Maybe you should make it so that the beheading modifier part of the texture doesn’t appear when the weapon is broken.

**Comment by bonii-xx** [comment]
Yup, the textures are simply layered on top of each other, tool first and then modifiers in the order of application. The beheading modifier has historically always looked like that, and nobody came up with a non-covering variant yet.
Switching up the order would be inconsistent and more confusing for players. It's not worth putting in the work for broken modifier textures, too complex. So unless we get better textures someday it'll stay like that. Someday. Maybe.

**Comment by PapiDimmi** [comment]
>Switching up the order would be inconsistent and more confusing for players.

Players know what kind of modifiers they have on their weapons and weapons. It’s more confusing _not_ to have the broken texture, as players don’t know when their weapon or tool is broken unless they read its tooltip. I sure was confused, at least, since my cleaver in a mechanical user stopped working, even though it appeared not to be broken.

>It's not worth putting in the work for broken modifier textures, too complex.

I don’t understand how adding an ”x” to an item texture is complex.

**Comment by bonii-xx** [comment]
>I don’t understand how adding an ”x” to an item texture is complex.

Which is why you have us, the devs, tell you that it is.

**Comment by PapiDimmi** [comment]
Can you elaborate? I’m not a Minecraft mod developer, so I’m not sure about the details, but I’d assume that adding an “x” to a texture wouldn’t be too complex.

Maybe I would understand it better if you were to explain _why_ it’s complex. That would be very helpful.

**Comment by BrianEdmonds** [comment]
As someone who is also not a mod dev, but with a long programming 
background, and who is thinking of getting into writing mods, I also 
find this sort of detail interesting, if you have the time and insight 
to share.

**Comment by bonii-xx** [comment]
Simply put: Minecrafts code is.. somewhat suboptimal. For this specific issue it'd require adding another abstraction layer in the already very heavy model code to support multiple possible textures for that scenario as well as the code to chose/generate the right model from that information at runtime.

It's probably easiest to just link this package: https://github.com/SlimeKnights/TinkersConstruct/tree/master/src/main/java/slimeknights/tconstruct/library/client/model

**Comment by CraftMinerKyle** [comment]
Long story short: Lots of painstaking code, errors, and possible increased lag, model exceptions, Days of living off of Starbucks and Ramen Noodles staring at a screen all day and night, only to fix a hard to notice texture glitch.
