### ISSUE TITLE
Tinkers' Construct Font error, help me

### ISSUE THREAD

**Issue by blueirole** [SlimeKnights/TinkersConstruct#2839]
Singleplay, no error

But, my server has font error... help me..

image link
1. [Click](http://imgur.com/n43WzpT)
2. [Click](http://imgur.com/N2Njbvz)

**Comment by PapiDimmi** [comment]
Which version of Minecraft, Tinkers’ Construct, and Forge are you using?

Which resource pack are you using? Have you tried without it?

**Comment by blueirole** [comment]
Server Forge : 2185
Tinkers' Construct : 2.6.3

No resource pack..

**Comment by bonii-xx** [comment]
You either have a mod that changes the Font (look for CustomFont or something along those lines), or you have Optifine. Remove whatever changes your fonts and everything will work.

**Comment by PapiDimmi** [comment]
OptiFine does not change the font. I use OptiFine with Tinkers’ Construct and have no problems.

@blueirole 12.18.3.2185 is outdated. Maybe you should install the latest version of Minecraft Forge, which is 12.18.3.2281; however, that might not solve your problem.

Like @bonii-xx, you probably have a mod that changes fonts.

**Comment by bonii-xx** [comment]
It does not do it by default, no. But it changes font rendering (or at least it has the option to), which is also why tinkers books break with it.

**Comment by PapiDimmi** [comment]
OptiFine has no option to change fonts. It does have a “custom fonts” option, but that’s for resource packs, and OP does not use a resource pack, and neither do I.

OptiFine _does_ break the Tinkers’ Construct book in terms of rendering text (which is annoying), but it doesn’t change any fonts, unless you’ve got a resource pack installed and the “custom fonts” option enabled.

**Comment by bonii-xx** [comment]
"Font rendering" refers to how the font is rendered, not necessarily that it changes the font that is rendered. But yes, it is as you said. And as I said. ;o

**Comment by PapiDimmi** [comment]
You can’t change how the font is rendered using OptiFine, as far as I’m aware.

**Comment by bonii-xx** [comment]
That's right. You can't. Because OptiFine simply does.

**Comment by PapiDimmi** [comment]
If it does, why are the fonts fine for me? I’m using OptiFine with Tinkers’ Construct.

**Comment by KnightMiner** [comment]
Optifine is inconsistant with how it breaks our stuff. It can be based on graphics cards and other system information, but the point is Optifine changes internal rendering code and it almost never is fully compatible with anything built for vanilla rendering.

The point is, we don't support things that change the internals of rendering. If it can be reproduced without Optifine (or any other mod that changes rendering internals), it will be taken as an issue

**Comment by PapiDimmi** [comment]
All right, then.

OptiFine is designed for vanilla Minecraft, so it tends to break when other mods are used, unfortunately.

**Comment by bonii-xx** [comment]
>OptiFine does break the Tinkers’ Construct book in terms of rendering text (which is annoying)

>If it does, why are the fonts fine for me? I’m using OptiFine with Tinkers’ Construct.

Now that you're done contradicting yourself, I'll have to ask you to stop posting unconstructive stuff on the issuetracker. We're not interested in your bickering/comments. If you have a bug to report then do so, but otherwise please refrain from posting.

**Comment by PapiDimmi** [comment]
I didn’t contradict myself. I said that OptiFine breaks the rendering of text in Tinkers’ Construct’s books, but it doesn’t change any fonts, and it doesn’t break the tooltips for me. Those are two different issues.

**Comment by laz2727** [comment]
Open language options and switch unicode fonts off.
