### ISSUE TITLE
[1.10.2-2.6.3.500] Crash while filling smeltery from IE's barrel

### ISSUE THREAD

**Issue by berinhardt** [SlimeKnights/TinkersConstruct#2842]
on a 1x1x1 smeltery after adding a bucket of water and with an ore being smelted, if you put an IE's barrel with some lava on top of the drain causes a null pointer exception on fill (resource seems to be null)

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
>   Brandon's Core (BrandonsCore-1.10.2-2.1.6.98-universal.jar)
>   LoadingPlugin (Quark-r1.1-70.jar)
>   TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
> Contact their authors BEFORE contacting forge
> 
> // Would you like a cupcake?
> 
> Time: 4/14/17 1:37 AM
> Description: Ticking block entity
> 
> java.lang.NullPointerException: Ticking block entity
> 	at slimeknights.tconstruct.library.smeltery.SmelteryTank.fill(SmelteryTank.java:104)
> 	at blusunrize.immersiveengineering.common.blocks.wooden.TileEntityWoodenBarrel.func_73660_a(TileEntityWoodenBarrel.java:58)
> 	at net.minecraft.world.World.func_72939_s(World.java:1804)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at slimeknights.tconstruct.library.smeltery.SmelteryTank.fill(SmelteryTank.java:104)
> 	at blusunrize.immersiveengineering.common.blocks.wooden.TileEntityWoodenBarrel.func_73660_a(TileEntityWoodenBarrel.java:58)
> 
> -- Block entity being ticked --
> Details:
> 	Name: immersiveengineering:MetalBarrel // blusunrize.immersiveengineering.common.blocks.metal.TileEntityMetalBarrel
> 	Block type: ID #996 (tile.immersiveengineering.metalDevice0 // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevice0)
> 	Block data value: 4 / 0x4 / 0b0100
> 	Block location: World: (-205,60,245), Chunk: (at 3,3,5 in -13,15; contains blocks -208,0,240 to -193,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Actual block type: ID #996 (tile.immersiveengineering.metalDevice0 // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevice0)
> 	Actual block data value: 4 / 0x4 / 0b0100
> Stacktrace:
> 	at net.minecraft.world.World.func_72939_s(World.java:1804)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
> 
> -- Affected level --
> Details:
> 	Level name: Masita
> 	All players: 1 total; [EntityPlayerMP['BerinHardt'/1067, l='Masita', x=-203.51, y=59.00, z=247.10]]
> 	Chunk stats: ServerChunkCache: 625 Drop: 0
> 	Level seed: -7640550751252996010
> 	Level generator: ID 00 - default, ver 1. Features enabled: true
> 	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
> 	Level spawn location: World: (-224,64,256), Chunk: (at 0,4,0 in -14,16; contains blocks -224,0,256 to -209,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 143487 game time, 246763 day time
> 	Level dimension: 0
> 	Level storage version: 0x04ABD - Anvil
> 	Level weather: Rain time: 147905 (now: false), thunder time: 60540 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.10.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_73, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 353828648 bytes (337 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
> 	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms128m -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC
> 	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
> 	FML: MCP 9.32 Powered by Forge 12.18.3.2281 43 mods loaded, 43 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) 
> 	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) 
> 	UCHIJAAAA	OpenComputers|Core{1.6.2.7} [OpenComputers (Core)] (minecraft.jar) 
> 	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
> 	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
> 	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
> 	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
> 	UCHIJAAAA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
> 	UCHIJAAAA	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
> 	UCHIJAAAA	BiomesOPlenty{5.0.0.2155} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar) 
> 	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
> 	UCHIJAAAA	CodeChickenLib{2.5.7.241} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
> 	UCHIJAAAA	brandonscore{2.1.6} [Brandon's Core] (BrandonsCore-1.10.2-2.1.6.98-universal.jar) 
> 	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
> 	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.24.jar) 
> 	UCHIJAAAA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
> 	UCHIJAAAA	MineTweaker3{3.0.24} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.24.jar) 
> 	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.24.jar) 
> 	UCHIJAAAA	draconicevolution{2.0.10} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.10.199-universal.jar) 
> 	UCHIJAAAA	zerocore{1.10.2-0.1.0.5} [Zero CORE] (zerocore-1.10.2-0.1.0.5.jar) 
> 	UCHIJAAAA	bigreactors{1.10.2-0.4.5.28} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.28.jar) 
> 	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
> 	UCHIJAAAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
> 	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
> 	UCHIJAAAA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
> 	UCHIJAAAA	immersiveengineering{0.10-57} [Immersive Engineering] (ImmersiveEngineering-0.10-57.jar) 
> 	UCHIJAAAA	ironbackpacks{1.10.2-2.2.25} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.25.jar) 
> 	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
> 	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
> 	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
> 	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
> 	UCHIJAAAA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
> 	UCHIJAAAA	OpenComputers{1.6.2.7} [OpenComputers] (OpenComputers-MC1.10.2-1.6.2.7.jar) 
> 	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
> 	UCHIJAAAA	StorageDrawers{1.10.2-3.7.1} [Storage Drawers] (StorageDrawers-1.10.2-3.7.1.jar) 
> 	UCHIJAAAA	refinedstorage{1.2.25} [Refined Storage] (refinedstorage-1.2.25.jar) 
> 	UCHIJAAAA	storagedrawersextra{1.10-1.1.0} [Storage Drawers Extras] (StorageDrawersExtras-1.10-1.1.0.jar) 
> 	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
> 	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
> 	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
> 	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
> 	UCHIJAAAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
> 	Loaded coremods (and transformers): 
> CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
>   codechicken.lib.asm.ClassHeirachyManager
>   codechicken.lib.asm.CCL_ASMTransformer
> Brandon's Core (BrandonsCore-1.10.2-2.1.6.98-universal.jar)
>   com.brandon3055.brandonscore.asm.ClassTransformer
> LoadingPlugin (Quark-r1.1-70.jar)
>   vazkii.quark.base.asm.ClassTransformer
> TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
>   li.cil.oc.common.asm.ClassTransformer
> 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> 	Pulsar/tconstruct loaded Pulses: 
> 		- TinkerCommons (Enabled/Forced)
> 		- TinkerWorld (Enabled/Not Forced)
> 		- TinkerTools (Enabled/Not Forced)
> 		- TinkerHarvestTools (Enabled/Forced)
> 		- TinkerMeleeWeapons (Enabled/Forced)
> 		- TinkerRangedWeapons (Enabled/Forced)
> 		- TinkerModifiers (Enabled/Forced)
> 		- TinkerSmeltery (Enabled/Not Forced)
> 		- TinkerGadgets (Enabled/Not Forced)
> 		- TinkerOredict (Enabled/Forced)
> 		- TinkerIntegration (Enabled/Forced)
> 		- TinkerFluids (Enabled/Forced)
> 		- TinkerMaterials (Enabled/Forced)
> 		- TinkerModelRegister (Enabled/Forced)
> 		- WailaIntegration (Enabled/Not Forced)
> 
> 	List of loaded APIs: 
> 		* Baubles|API (1.3.1.3) from Baubles-1.10.2-1.3.9.jar
> 		* bigreactors|API (4.0.1) from ExtremeReactors-1.10.2-0.4.5.28.jar
> 		* BotaniaAPI (85) from Botania r1.9-341.jar
> 		* CoFHAPI (1.7.10R1.3.1) from BrandonsCore-1.10.2-2.1.6.98-universal.jar
> 		* cofhapi (1.6.0) from zerocore-1.10.2-0.1.0.5.jar
> 		* cofhapi|block (1.6.0) from zerocore-1.10.2-0.1.0.5.jar
> 		* cofhapi|core (1.6.0) from zerocore-1.10.2-0.1.0.5.jar
> 		* CoFHAPI|energy (1.8.9R1.2.0B1) from refinedstorage-1.2.25.jar
> 		* cofhapi|energy (1.6.0) from zerocore-1.10.2-0.1.0.5.jar
> 		* cofhapi|item (1.6.0) from zerocore-1.10.2-0.1.0.5.jar
> 		* cofhapi|tileentity (1.6.0) from zerocore-1.10.2-0.1.0.5.jar
> 		* cofhapi|util (1.6.0) from zerocore-1.10.2-0.1.0.5.jar
> 		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.1.0.5.jar
> 		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.1.0.5.jar
> 		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.1.0.5.jar
> 		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.1.0.5.jar
> 		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.1.0.5.jar
> 		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.1.0.5.jar
> 		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.1.0.5.jar
> 		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.1.0.5.jar
> 		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.10.2-2.0.10.199-universal.jar
> 		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-57.jar
> 		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-57.jar
> 		* IronBackpacks|API (0.5) from IronBackpacks-1.10.2-2.2.25.jar
> 		* jeresources|API (0.5.8.98) from JustEnoughResources-1.10.2-0.5.8.98.jar
> 		* journeymap|client-api (1.3) from journeymap-1.10.2-5.4.6.jar
> 		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.4.6.jar
> 		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.4.6.jar
> 		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.4.6.jar
> 		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.4.6.jar
> 		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.7.416.jar
> 		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
> 		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.1.jar
> 		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.2.25.jar
> 		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.2.25.jar
> 		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from refinedstorage-1.2.25.jar
> 		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.1.jar
> 		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.1.jar
> 		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.1.jar
> 		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.1.jar
> 		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.1.jar
> 		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
> 		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.5.jar
> 		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.5.jar
> 		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.5.jar
> 	CodeChickenLib Invalid Fingerprint Reports: 
> 	Profiler Position: N/A (disabled)
> 	Player Count: 1 / 8; [EntityPlayerMP['BerinHardt'/1067, l='Masita', x=-203.51, y=59.00, z=247.10]]
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by bonii-xx** [comment]
There were several fixes regarding nullpointers in 1.12, should be fixed by now.
