### ISSUE TITLE
[1.10.2] Blank Casts can't smelt

### ISSUE THREAD

**Issue by Hodel1** [SlimeKnights/TinkersConstruct#2846]
Hi,

it is not possible to smelt a Blank Cast to recasting it to Gold.

Tested in FTB Beyond 1.5.3 with Tinkers Construct Version 1.10.2-2.6.3.500

**Comment by ArukaAlter** [comment]
This is because of the fact that casts can be made either of gold, aluminum-brass or brass.

**Comment by Hodel1** [comment]
It could be annoying if you forgot to place the casting before you mold gold on a casting table.
the blank cast is useless now.

I mean to remember that this was possible in 1.7.10. The Blank Castings had a subid like X:1, X:2 to known, for reuse the castings in the smeltery.

**Comment by ArukaAlter** [comment]
It was possible before because there were two types of cast, one for gold and one for aluminum-brass. You can always use the empty cast to craft a Reinforced modifier.

**Comment by Hodel1** [comment]
It will be great, when it can be resmelt it in the future :)
