### ISSUE TITLE
TIC Ranged Weapons and HQM

### ISSUE THREAD

**Issue by Utildayael** [SlimeKnights/TinkersConstruct#2847]
Got a weird one for ya. Crossposting from HQM issue as I'm not sure which side it is on.
---
I'm not sure if this is a Tinkers issue or a HQM issue so I apologize in advance.

Testing out the pack I'm working on last night and I have a section with all the kill x quests, for example, kill 10 zombies.

I spawn the zombies with mob eggs and then shot them with a Tinkers longbow. Looked at my quest book and said my kill count for the quest was still 0. Ok figured it didn't like me being in creative so I tried again in survival. Same deal. 0 kills. On a whim I grabbed a sword and proceeded to stab the zombies to death and THAT worked fine.

So... for some reason ranged kills with TIC weapons aren't registering as kills in HQM yet they register with FTB Utils and the vanilla Minecraft statistics.

Workaround of course is to just use a vanilla bow or a sword so it isn't game-breaking but something I'll have to note on the quest chapter for the players.

MC 1.10.2
Forge 12.18.3.2281
HQM 1.10.2-5.1.0alpha4
Tinkers 1.10.2-2.6.3

https://github.com/lorddusk/HQM/issues/314

Thanks!
---

Since MC stats update as well as FTB Utils and others I'm inclined to think it somehow is HQM but wanted to check here just in case. Do the TIC ranged weapons do anything special that say... a vanilla bow doesn't? 

Thanks

**Comment by bonii-xx** [comment]
Hard to say, depends on what HQM uses to track that. Best enquire there. TiC bows do a lot of things, being TiC bows and all, but as long as they don't check specifically for the vanilla arrow entity it shouldn't matter.

**Comment by Utildayael** [comment]
Thanks Boni. I'll see what HQM dev comes back with. :)

**Comment by bonii-xx** [comment]
Closing to age and TiC provides enough API stuff to achieve all the ranged stuff by now.
