### ISSUE TITLE
Smeltery bug

### ISSUE THREAD

**Issue by KanGouRoux6** [SlimeKnights/TinkersConstruct#2848]
Hello , i play on Restart modpacks (Curse) and i'm having a bug with the smeltery, i can only craft ingots cast or ingots, it is impossible to activate faucet when a stone part like a pickaxe head or any other part or any other cast (other than ingots cast) , there are enough gold and lava in the smeltery , I really can't undestand why i can only craft ingots or ingots cast with the smeltery ? (really sorry for my bad english) here is a screen 
![image](https://cloud.githubusercontent.com/assets/27772346/25182841/2d8bb4aa-2516-11e7-8d3f-da2220314812.png)

**Comment by bonii-xx** [comment]
Probably something they did in the Restart modpack.

**Comment by bonii-xx** [comment]
Closing due to age
