### ISSUE TITLE
Cross-mod crash after attempting to put molten emerald into a casting basin.

### ISSUE THREAD

**Issue by MechanosG** [SlimeKnights/TinkersConstruct#2849]
Basically..  I made some pig iron, had left over emerald, felt like saving it, so I poured it into a Mekanism basic fluid tank.  Later I realized I couldn't remove it from the tank via dumping it on the ground (less than 1 bucket), so I attempted to dump it into an empty casting basin.  Shortly after, my game crashed with this error.

`java.lang.RuntimeException: No OpenGL context found in the current thread.`
This is the full crash log.
[crash-2017-04-19_13.30.56-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/938237/crash-2017-04-19_13.30.56-client.txt)

I am unable to rejoin the server this happened on, as every time the casting basin loads, it crashes me with the same error.  I'm not sure how to remove the bugged basin either.

MC. 1.10.2
Tinkers Construct 2.6.3
Mekanism 9.2.1.298 (including in case I need to show them this report)
Forge 12.18.3.2254

**Comment by KnightMiner** [comment]
Did you right click the basin to "dump" it in? According to the crash you have a mekenism item/block (which does very very wrong things in their rendering code) within one of our tables/basins.

In the Tinkers Consturct config, disable the option to display table/basin items and you will be able to load your world to remove the item from the basin before enabling the config again.

----

Officially, this is a Mekenism issue and has been reported before, so I am closing this as a duplicate.

**Comment by MechanosG** [comment]
Yep, that's what I did, I right clicked a basin with the mekanism basic fluid tank to put the emerald in it.  Then crash city.  Thanks for the workaround.
