### ISSUE TITLE
Pickaxe with smashing modifier can't break Colossal Chest blocks

### ISSUE THREAD

**Issue by chimericdream** [SlimeKnights/TinkersConstruct#2850]
I posted this in the [Colossal Chests repo](https://github.com/CyclopsMC/ColossalChests/issues/79), but they suggested it might be a bug in TiCon, so I am cross-posting here.

In Sky Factory 3, if I add a diamond hammer to my Tinker's pickaxe, it can no longer break Colossal Chest blocks.

**Comment by KnightMiner** [comment]
We do not have a smashing modifier, try and determine which mod adds it (I would guess either Ex Nihilo or Ex Compressum)
