### ISSUE TITLE
Massive FPS drop with an Electrum Longbow (sometimes)

### ISSUE THREAD

**Issue by MechanosG** [SlimeKnights/TinkersConstruct#2851]
Last night I made a Longbow out of 2 Electrum bow parts, a wood plate, and web string.  Right away, anytime I select it on my hotbar, my FPS tanks.  If the "zap" charges up fully, the lag gets worse, floating around 5-10 FPS.  If I draw back an arrow, the lag gets worse too.  Switching to any other item on my hotbar returns the FPS to normal.  The bow also seemed to function properly despite the lag making it difficult to aim.  The game was unplayable with the bow out though.

Restarting my game however, seems to have fixed it.  I don't know if it will continue to not lag from here on, or what.  I'll post more if it starts doing it again.

MC. 1.10.2
Tinkers Construct 2.6.3
Forge 12.18.3.2254

**Comment by bonii-xx** [comment]
Are you using Optifine?

**Comment by MechanosG** [comment]
Yes I am using Optifine.

I also figured out how to reproduce the bug.  First, run any large modpack that has the usual memory leakage.  Memory should balloon out to 1GB over the max you set Java to use, then GC will start going into overdrive and hold it there.  Once you're in this memory stalemate, switch to an Electrum tool.  You will suddenly get massive FPS drops, I assume due to either a spike in memory usage or extra CPU usage.  Select any other tool and the lag goes away.

I haven't tested to see if electrum tools contribute to memory ballooning out or anything.  But they don't lag until you hit your memory limit.

**Comment by bonii-xx** [comment]
Try without Optifine.

**Comment by KnightMiner** [comment]
Closing since it was likely the same issue as #2968, meaning it was fixed by #3182
