### ISSUE TITLE
In MAC OS part of texture has lost

### ISSUE THREAD

**Issue by yuan1238y** [SlimeKnights/TinkersConstruct#2852]
Game\Forge version: 1.10.2-forge1.10.2-12.18.3.2185
Mod version: TConstruct-1.10.2-2.6.3
OS version: Sierra 10.12.4
Screenshot:
![image](https://cloud.githubusercontent.com/assets/1049629/25302450/f83f29fa-2770-11e7-999a-e7466bc1bf32.png)
![image](https://cloud.githubusercontent.com/assets/1049629/25302454/044e7520-2771-11e7-964f-912a6ed05e7e.png)
![image](https://cloud.githubusercontent.com/assets/1049629/25302455/09789300-2771-11e7-96dc-de2b11287557.png)
![image](https://cloud.githubusercontent.com/assets/1049629/25302457/0d01d4dc-2771-11e7-8051-71919c2bab2e.png)

**Comment by bonii-xx** [comment]
Wow, that's really weird. Are there any errors in the log?

**Comment by yuan1238y** [comment]
I got some debug log from fml-client-latest.log
that's looked has problem!
[logs.zip](https://github.com/SlimeKnights/TinkersConstruct/files/948833/logs.zip)

**Comment by bonii-xx** [comment]
The log looks ok. Might be the texture files in your jar are corrupt, try redownloading from curseforge.

**Comment by yuan1238y** [comment]
I'm checked texture files in jar.
Files is looked ok.
And jar md5 sum is same
![image](https://cloud.githubusercontent.com/assets/1049629/25304765/4fd94130-27a0-11e7-903e-77008712ec19.png)

**Comment by luckyu19** [comment]
Couldn't replicate this with the same forge, Mantle and TiC version.
The only difference is I'm using Mac Sierra 10.12.5 and there is no mercurius_updater in mine.
I also tried to change the language to SImplified Chinese but it is still working fine for me.
Try and remove mercurius_updater or update your Mac OS version and see if it works.

**Comment by yuan1238y** [comment]
Thank you @luckyu19 
I'll try it when I get home.

**Comment by yuan1238y** [comment]
I'm remove .minecraft/config directory.
This issue has fixed!
I think this issue may be other mod config file causing.
