### ISSUE TITLE
Consider moving Drying Rack out of Gadgets?

### ISSUE THREAD

**Issue by D3nnis3n** [SlimeKnights/TinkersConstruct#2854]
Hey, just a suggestion on my behalf - i really like the drying rack but not a single other block of the gadgets. Unfortunatley i can only disable all or nothing. :(

If you don't like that, just close, and sorry!

**Comment by bonii-xx** [comment]
Gadgets simply contains everything that's neither smeltery nor tools. Like drying racks. You don't have to use the blocks in the gadgets ;P
