### ISSUE TITLE
[1.10.2][Bug] Inconsistent Smeltery fuel behavior

### ISSUE THREAD

**Issue by Compegen** [SlimeKnights/TinkersConstruct#2857]
Using version `1.10.2-2.6.3`
Running only JEI, TConstruct, & Mantle
Was able to reproduce thrice, but not again yet, due to it being random when it happens
_________
After a valid smeltery has been built, there are two different things that can happen when you place lava into a seared tank:
1. The smeltery lists the tank as a valid fuel source of **1B of lava @ 1300K**
2. The smeltery lists the tank as a valid fuel source of **1B 900mB of lava @ 1000K**

When the second event happens, two more events happen because of it:
1. After about 3 seconds, the smeltery lists the tank as a valid fuel source, but now its of **950mB of lava @ 1000k**
2. When the tank is broken and replaced with an empty tank, the smeltery lists the tank as a valid fuel source of **lava @ 1000K (no bucket amount)**

![0_initial](https://cloud.githubusercontent.com/assets/8009507/25363848/837ad204-2923-11e7-99af-4f9ef3eb7d69.PNG)
![1_run1](https://cloud.githubusercontent.com/assets/8009507/25363852/8382b442-2923-11e7-9afd-80e51d1ed405.PNG)
![2_run2](https://cloud.githubusercontent.com/assets/8009507/25363849/837ad1aa-2923-11e7-8753-6d99f4585571.png)
![3_run2_wait](https://cloud.githubusercontent.com/assets/8009507/25363851/837f769c-2923-11e7-8cf2-a659465c7872.PNG)
![4_run2_breaktank](https://cloud.githubusercontent.com/assets/8009507/25363850/837deb24-2923-11e7-854c-9af2f270c54c.PNG)

**Comment by KnightMiner** [comment]
Fixed by 019fa70
