### ISSUE TITLE
Casting basins turning into casting tables?

### ISSUE THREAD

**Issue by jeviuss** [SlimeKnights/TinkersConstruct#2858]
![image](https://cloud.githubusercontent.com/assets/12577484/25457579/cbd72228-2aa4-11e7-8514-17620d0f6fca.png)
I place casting basins and they changed their name to casting tables, and I cannot pour anything into them!

**Comment by ArukaAlter** [comment]
Missing informations such as mod version and mods present in the environment.

**Comment by bonii-xx** [comment]
Probably just WAILA displaying the wrong metadata.

**Comment by Tukanen** [comment]
I've seen this too, and it still works like a basin.
pretty sure it's waila, as it also show all thermal expansion machines to be red stone furnaces

**Comment by KnightMiner** [comment]
Closing due to lack of information and response.
