### ISSUE TITLE
Make EFLN start public void on(final ExplosionEvent.Start event)

### ISSUE THREAD

**Issue by Raycoms** [SlimeKnights/TinkersConstruct#2859]
We are trying to protect our anti griefing system of EFLN explosions but since it isn't calling ExplosionEvent.Start we are not able to cancel it.

**Comment by Raycoms** [comment]
Or at least allow to clear the affected blocks list =D

**Comment by Raycoms** [comment]
It would be kind of important to be able to protect the players against this.

**Comment by CraftMinerKyle** [comment]
You could just ban the placement of explosive or destructive blocks.

**Comment by Raycoms** [comment]
Yes we do that, but the efln doesn't follow normal rules of explosives. because its not a block etc

**Comment by CraftMinerKyle** [comment]
Ohhh.. It's the mining Explosive! (ImA dErP) Does it ignore FTB Utilities Player Claimed Chunks?

**Comment by bonii-xx** [comment]
Fun, right, I changed that during development because the original method (which had the event calls.. albeit ignored the results) didn't work. Yes, events are missing.

**Comment by CraftMinerKyle** [comment]
Maybe you could have it that where the object, when thrown, will test for FTB Claimed Chunks and wherever the explosion occurs, potentially affected blocks inside those chunks are opted out of the explosion. Just an idea.

**Comment by Raycoms** [comment]
Yeah I bet that FTB claimed chunks won't project us as well. And we have
our own protection for that as well. Own system of claiming and I would
just like to be able to cancel the event, or if that doesn't work just
empty the list of affected blocks to negate the effect

2017-05-10 15:06 GMT-03:00 CraftMinerKyle <notifications@github.com>:
