### ISSUE TITLE
[Bug] Endrod arrow shaft suiciding

### ISSUE THREAD

**Issue by 145ProMY** [SlimeKnights/TinkersConstruct#2860]
The arrows which contain endrod as the material of arrow shaft, has a bug of hitting the user himself if the user shoots the arrow and moving forward at the same time. I'm not sure if this happens to everyone.

**Comment by bonii-xx** [comment]
Which TiC version?

**Comment by 145ProMY** [comment]
TConstruct-1.10.2.-2.6.1.jar

**Comment by bonii-xx** [comment]
That issue got fixed long ago :P

**Comment by 145ProMY** [comment]
Thanks
