### ISSUE TITLE
[1.10.2] Crossbow can't hit Enderdragen

### ISSUE THREAD

**Issue by Hodel1** [SlimeKnights/TinkersConstruct#2861]
Hi,

i have a Cobald Crossbow with Manyullyn Bolts and can't hit a Enderdragen with it.
With a Cleaver isn't a problem. 

I'm sure, that it has works for MC 1.7.10.

Tested in FTB Beyond 1.5.3 with TC 1.10.2-2.6.3.500 and TinkersToolLeveling 1.10.2-1.0.1.DEVf5def58

**Comment by ArukaAlter** [comment]
Is the dragon hovering over the center platform when you shoot it?

**Comment by Hodel1** [comment]
i tried multiple times to shot him whilst he flies around the island and where he hovering over the bedrock pool. Both situations had failed

**Comment by Techokami** [comment]
Yeah, Enderdragon does not like collisions with mod-based projectiles it seems. I couldn't directly hurt it with Immersive Engineering's revolver, nor with Reliquary's Hunter's Handgun. I was only able to do damage by using exploding shots, but it was taking damage from the blast and not the projectile.

If this can be solved in Tinker's, that would be a godsend.

**Comment by bonii-xx** [comment]
I remember that there used to be an issue when hitting things that are not EntityLiving, however that was fixed ages ago. Can only be that something got changed in 1.10+ or a newer forge version. Might also be another mod, can somebody reproduce it with only tic and mantle?

**Comment by Hodel1** [comment]
I had tested a little bit.
I have this issue on a SpongeForge based Server. In Singleplayermode is it no problem.
Is it a issue on Spongeforge or on TC Mod?

**Comment by KnightMiner** [comment]
Almost certainly SpongeForge, try it on a normal Forge server as Sponge has been recently known to break many mods.

**Comment by KnightMiner** [comment]
Closing due to lack of response as a SpongeForge issue.

**Comment by OneEyeMaker** [comment]
Please, reopen this issue.
Similar issue occurs without Sponge with TiC and its addons, which add range weapon.
https://github.com/Landmaster/PlusTiC/issues/110

**Comment by KnightMiner** [comment]
That issue is on PlusTic's side, we do not handle the code for the laser. If you want a reopen reproduce using crossbows or bows.
