### ISSUE TITLE
[1.11.2] Build fails due to use of internal com.sun packages

### ISSUE THREAD

**Issue by Ristovski** [SlimeKnights/TinkersConstruct#2862]
Compiling from `1.11.2` branch fails with the error 
`TinkersConstruct/build/sources/main/java/slimeknights/tconstruct/library/tools/IAmmoUser.java:3: error: package com.sun.istack.internal does not exist`. This is due to importing an internal package which isn't provided when building with gradle.

**Comment by Ristovski** [comment]
I seem to have found a workaround for now which gets rid of the importing error:

```
compileJava {
	options.fork = true
	options.forkOptions.executable = 'javac'
	options.compilerArgs << "-XDignore.symbol.file"
}
```

**Comment by bonii-xx** [comment]
Yes. That's what happens when you're trying to build work in progress before it works on the build server. ;P
