### ISSUE TITLE
Unable to add Lapis to Katana

### ISSUE THREAD

**Issue by NillerUdenDild** [SlimeKnights/TinkersConstruct#2864]
As the title says, I can't add lapis to the Katana - I assume it's not intended?

Minecraft 1.10.2
Forge 12.18.3.2281
Tconstruct-1.10.2-2.6.3

**Comment by ArukaAlter** [comment]
There are no katanas in Tinkers'.

**Comment by Landmaster** [comment]
The katanas are from my addon mod, PlusTiC.

**Comment by bonii-xx** [comment]
Report to whatever mod adds the Katana. Lapis has no limitations as long as the tool is correctly implemented.

**Comment by NillerUdenDild** [comment]
Oh, my bad, sorry :)
