### ISSUE TITLE
[1.11] NPE w/ Book

### ISSUE THREAD

**Issue by SnowShock35** [SlimeKnights/TinkersConstruct#2865]
### Important Info

- Minecraft 1.11.2
- Minecraft Forge 13.20.0.2285
- Mantle 1.2.0.26
- TConstruct 2.7.0.4

### Issue Description

Null Pointer Exception that causes a crash to desktop when turning to page 8 inside the Materials and You guide book in game. 

### Issue Media

- [Crash Log](https://pastebin.com/i7tiPHSZ)

**Comment by bonii-xx** [comment]
Turns out it's because of the missing data. Fixed the crash anyway.
