### ISSUE TITLE
[1.11] Broken Localisation in Materials & You Book

### ISSUE THREAD

**Issue by SnowShock35** [SlimeKnights/TinkersConstruct#2866]
### Important Info

- Minecraft 1.11.2
- Minecraft Forge 13.20.0.2285
- Mantle 1.2.0.26
- TConstruct 2.7.0.4

### Issue Description

Tl;Dr: Book has broken localisation on the pages u can view and question marks where the images should be. I assume perhaps due to the lower-casing of mod id's and textures. 

### Issue Media

![Issue Screenshot #1](https://ss.blamesnow.co.uk/2017/04/1493499624-afcaca3e.png)
![Issue Screenshot #2](https://ss.blamesnow.co.uk/2017/04/1493499648-37a9aacf.png)

**Comment by bonii-xx** [comment]
Yeah the book is still quite broken and crashes in some places. I forgot to mention that. :)

**Comment by bonii-xx** [comment]
Now that's nice, it was only because the book language folder wasn't lowercase. Stupid change.. or rather stupid that it didn't work before.
