### ISSUE TITLE
[1.11] Tool Forge / Station GUI Weirdness

### ISSUE THREAD

**Issue by SnowShock35** [SlimeKnights/TinkersConstruct#2867]
### Important Info

- Minecraft 1.11.2
- Minecraft Forge 13.20.0.2285
- Mantle 1.2.0.26
- TConstruct 2.7.0.4

### Issue Description

The Tool Forge (assuming the same error with tool station too) has weird behaviour when switching too and from different tabs when items have been placed into slots in different tabs. See images for further clarification. 

### Issue Media

![Issue Screenshot #1](https://ss.blamesnow.co.uk/2017/04/1493502500-fc07d0a3.png)

**Comment by bonii-xx** [comment]
Are you referring to the spare-part-slots? That's where Items in slots that aren't used for a newly selected tools go. That has been there since 1.8 ;)

**Comment by SnowShock35** [comment]
Ah yes I do remember it being a thing even in previous versions to 1.8. However I don't recall seeing it in 1.10 so I assumed it was 'fixed'. My bad. :Smile:

**Comment by bonii-xx** [comment]
It's a feature ;P
