### ISSUE TITLE
[1.11] Unable to Craft Tools (Just Pickaxe)

### ISSUE THREAD

**Issue by SnowShock35** [SlimeKnights/TinkersConstruct#2868]
### Important Info

- Minecraft 1.11.2
- Minecraft Forge 13.20.0.2285
- Mantle 1.2.0.26
- TConstruct 2.7.0.4

### Issue Description

Self explanatory. Only able to craft pickaxes. 

### Issue Media

![Issue Screenshot #1](https://ss.blamesnow.co.uk/2017/04/1493503249-ad191570.png)
![Issue Screenshot #2](https://ss.blamesnow.co.uk/2017/04/1493503262-6f2c0677.png)
![Issue Screenshot #3](https://ss.blamesnow.co.uk/2017/04/1493503276-8c85da57.png)

**Comment by bonii-xx** [comment]
Of course the pickaxe was the only thing I tried. heh.

**Comment by bonii-xx** [comment]
Yup, more Itemstack == null checks, yay

**Comment by SnowShock35** [comment]
Haha everyone's favourite right? 😛

**Comment by bonii-xx** [comment]
Yup. But I think I got most of them now. Latest build has all the fixes. I'll probably throw out an alpha build soon to get mor etesting in ;)
