### ISSUE TITLE
[1.11.2] JEI Alloying Not Working

### ISSUE THREAD

**Issue by EmosewaGamer** [SlimeKnights/TinkersConstruct#2869]
Simply the alloying tab in JEI doesn't show the liquids. 
![image](https://cloud.githubusercontent.com/assets/25333164/25566534/c483a7ce-2dda-11e7-87a7-4062f8c3c2f4.png)

**Comment by EmosewaGamer** [comment]
There also seems to be random brackets and symbols on the Traits Part of the Tool Station and Tool Forge's GUI when there's no tool in it. 
![image](https://cloud.githubusercontent.com/assets/25333164/25566494/fa82ddbe-2dd9-11e7-9eb9-7597f513a14c.png)

**Comment by EmosewaGamer** [comment]
You also get Patterns without putting Stencils in the Stencil Table.
![image](https://cloud.githubusercontent.com/assets/25333164/25566515/65fa2106-2dda-11e7-8089-6a06c49a0461.png)

**Comment by EmosewaGamer** [comment]
The lighting from the Tank and Smeltery Controller (as I think it had lighting) is broken.
![image](https://cloud.githubusercontent.com/assets/25333164/25566613/b97b9222-2ddc-11e7-99cb-8beff133fed1.png)

**Comment by KnightMiner** [comment]
Please, make separately reports for each issue. It is very hard to manage fixing three separate issues in one spot.

Also, the second one is intentional, that is a little hammer.

**Comment by EmosewaGamer** [comment]
Oh. Anyways I was going to make different issues, but didn't want to overcrowd the issue page.

**Comment by KnightMiner** [comment]
Better to be crowded than unmanageble. We can always close indivual issues but closing three as a group requires all being fixed.

**Comment by EmosewaGamer** [comment]
Ok.

**Comment by bonii-xx** [comment]
I KNEW there was a second JEI recipe that I needed to fix up, but I didn't find it anymore when checking through it. :smile:
