### ISSUE TITLE
[1.11.2] Tank Lighting Issue

### ISSUE THREAD

**Issue by EmosewaGamer** [SlimeKnights/TinkersConstruct#2871]
The lighting from the Tank and Smeltery Controller (as I think it had lighting) is broken.
![image](https://cloud.githubusercontent.com/assets/25333164/25566613/b97b9222-2ddc-11e7-99cb-8beff133fed1.png)

**Comment by bonii-xx** [comment]
Not sure but IIRC it has always been similar to that, to prevent constant lighting updates. If you place a block/torch nearby does it recalculate correctly?

**Comment by EmosewaGamer** [comment]
Yeah, I tried and it doesn't get fixed with block updates around it.

**Comment by bonii-xx** [comment]
Looked at it again, it's as I said, the block doesn't cause the lighting in the surrounding blocks to recalculate. However that's intentional since it might cause severe fps lag otherwise. Other light-updating stuff like torches etc. will cause it to stay at the correct state.
