### ISSUE TITLE
[1.11.2] Crashing on Startup

### ISSUE THREAD

**Issue by Knighthawker1** [SlimeKnights/TinkersConstruct#2872]
Minecraft crashes on startup with TConstruct-1.11.2-2.7.0.6 installed. The crash report is included below.

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Construct (tconstruct)

**Comment by KnightMiner** [comment]
Please include the *full* crash report. Since it is long, put it on a site like [Pastebin](//pastebin.com) and link it here.

**Comment by Knighthawker1** [comment]
False alarm. Turns out the problem is that I didn't have Mantle installed. Works fine now.
