### ISSUE TITLE
1.11.2 - The game crashes whenever I try opening it.

### ISSUE THREAD

**Issue by InquisWiz** [SlimeKnights/TinkersConstruct#2874]
Here's my crashlog:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Construct (tconstruct)

**Comment by bonii-xx** [comment]
That doesn't tell us anything. But you're probably missing Mantle.

**Comment by ziocho** [comment]
> But you're probably missing Mantle.

Not the original poster but I also had this issue! I just missed that Mantle is a dependency when looking at the Curse Forge project page.

**Comment by KnightMiner** [comment]
Shouldn't forge be printing an error if Mantle is missing? Maybe something we need to look into.

**Comment by bonii-xx** [comment]
@KnightMiner I didn't put the required mods back in yet because they were somewhat broken during porting. Also I assumed people who use 1.11 alphas would be conditioned enough to know that Mantle is required.
