### ISSUE TITLE
[1.11] Unable to craft hammers

### ISSUE THREAD

**Issue by luckyu19** [SlimeKnights/TinkersConstruct#2875]
Minecraft 1.11.2
Minecraft Forge 13.20.0.2285
Mantle 1.2.0.26
TConstruct 2.7.0.6

Wasn't able to craft hammer. Bug replicated with just Mantle and TConstruct.
I also tested shurikens, and they didn't work either.
Pickaxes and shovels worked fine. (I didn't test others because reasons >.>)

![2017-05-01_15 50 23](https://cloud.githubusercontent.com/assets/19247442/25575260/44676fd6-2e88-11e7-8d9e-f0fad252fbec.png)

Probably related to #2868.

**Comment by bonii-xx** [comment]
Click on the hammer button. Ensure that all parts are in their correct place.

**Comment by CmdrFluffy** [comment]
I'm having the same issue on all advanced tools

**Comment by luckyu19** [comment]
I made sure it was the correct orientation, I'll check again though.

**Comment by luckyu19** [comment]
@bonii-xx I got out of my lazy mode and made a screenshot of everything.
Might have made a mistake with the bolt, but I never learned how to properly do that. *shrug*
Here are the list of tools that didn't work:
Excavator
Lumberaxe
Scythe
Frypan
Battle Sign
Cleaver
Longbow
Crossbow
Bolt
Hammer
Attached are screenshot proof.
![Uploading 2017-05-02_20.22.00.png…]()
![2017-05-02_20 28 42](https://cloud.githubusercontent.com/assets/19247442/25617734/50d9289c-2f76-11e7-8932-e31f36920050.png)
![2017-05-02_20 28 22](https://cloud.githubusercontent.com/assets/19247442/25617735/50dedb5c-2f76-11e7-98b9-423d24995cae.png)
![2017-05-02_20 27 56](https://cloud.githubusercontent.com/assets/19247442/25617736/50e3e516-2f76-11e7-86cb-7d38ef771556.png)
![2017-05-02_20 27 27](https://cloud.githubusercontent.com/assets/19247442/25617737/50eb4572-2f76-11e7-8453-dffa3b2628de.png)
![2017-05-02_20 26 20](https://cloud.githubusercontent.com/assets/19247442/25617738/50f012b4-2f76-11e7-9ebd-db6126987194.png)
![Uploading 2017-05-02_20.26.04.png…]()
![Uploading 2017-05-02_20.25.42.png…]()
![Uploading 2017-05-02_20.25.02.png…]()
![Uploading 2017-05-02_20.23.49.png…]()
![Uploading 2017-05-02_20.23.11.png…]()

**Comment by bonii-xx** [comment]
Thanks for checking, must be some specific check in the toolbuild logic.

**Comment by TheGooblyGoob** [comment]
I am having the same exact issue and I see the stuff that you're doing in those files but I don't know how to fix it. I really want a hammer :(

**Comment by bonii-xx** [comment]
Update.
