### ISSUE TITLE
Blocks from casting basins coming out as chiselled versions

### ISSUE THREAD

**Issue by Tukanen** [SlimeKnights/TinkersConstruct#2878]
more specifically the "causion"-type from chisel
now this may stem from the chisel-mod, and it only seems to happen to non-vanilla blocks.

further checking seems to indicate that the first type of chiselled block, is the one chosen for the casting basin.

**Comment by KnightMiner** [comment]
The first variant in the oredictionary is chosen, if that happens to be chisel's version it happens to be, but chisel's version should be fully compatible as the metal.

**Comment by bonii-xx** [comment]
Yup, not a bug, it simply takes whatever is there.
