### ISSUE TITLE
Minecraft crashing during initialization.

### ISSUE THREAD

**Issue by AbysmalDream** [SlimeKnights/TinkersConstruct#2879]
The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Failed to set the frozen variant of tconstruct:blocks/fluids/molten_metal! 

I also can not get a crash report pulled at all.

**Comment by bonii-xx** [comment]
Sounds like something is very wrong with your setup.

**Comment by bonii-xx** [comment]
Looks like somebody found the culprit, it's a buildcraft issue #2881
