### ISSUE TITLE
Forge launcher freezes and crashes on startup with Immersive Engineering.

### ISSUE THREAD

**Issue by ExAdventurer** [SlimeKnights/TinkersConstruct#2885]
[fml-client-latest.txt](https://github.com/SlimeKnights/TinkersConstruct/files/973498/fml-client-latest.txt)

[fml-junk-earlystartup.txt](https://github.com/SlimeKnights/TinkersConstruct/files/973499/fml-junk-earlystartup.txt)

[latest.txt](https://github.com/SlimeKnights/TinkersConstruct/files/973500/latest.txt)

**Comment by bonii-xx** [comment]
It works for everybody else though. Corrupt files?

**Comment by fin444** [comment]
From the first text document, it appears as though some files somehow have been deleted. I suggest redownloading Tinkers' Construct.

**Comment by KnightMiner** [comment]
Those debug outputs in the first one are expected, it is using the Forge blockstate system to load item models from the blockstate. You typically just don't see that output in the console as it is expected behavior in many mods.
