### ISSUE TITLE
[1.11.2] Missing items in recipes

### ISSUE THREAD

**Issue by EmosewaGamer** [SlimeKnights/TinkersConstruct#2886]
It seems that 2 of the Slimy Mud blocks are missing the respected Congealed Slime Block in their recipe:
![image](https://cloud.githubusercontent.com/assets/25333164/25719570/272c5592-310a-11e7-8fd7-b87b3e708df8.png)
![image](https://cloud.githubusercontent.com/assets/25333164/25719576/2d48d4be-310a-11e7-952d-80e6dcc8cee4.png)

**Comment by KnightMiner** [comment]
2201690
