### ISSUE TITLE
turn off certain things...? (just read the issue thingy first)

### ISSUE THREAD

**Issue by scigeotech** [SlimeKnights/TinkersConstruct#2887]
i know this isn't really an actual issue, but i strongly dislike the bucket textures and i want to remove them. after resetting my MC folder about twice, the problem still persists. is there a way to get rid of them?

**Comment by scigeotech** [comment]
nevermind

**Comment by scigeotech** [comment]
ugh. it still happens, but not with vanilla MC.

**Comment by KnightMiner** [comment]
The bucket textures are Forge, not Tinkers Construct. Reason being they needed to modify the texture for the universal bucket and did not want to redistribute Mojang's textures. Make a resource pack if you dislike them, because Forge is not going to switch to the vanilla textures.

**Comment by bonii-xx** [comment]
> because Forge **cannot** switch to the vanilla textures due to legal reasons

FTFY
