### ISSUE TITLE
[1.11.2] Issue with CraftTweaker

### ISSUE THREAD

**Issue by billybricker** [SlimeKnights/TinkersConstruct#2889]
It seems Tinkers' is completely breaking CraftTweaker recipes somehow. After some testing it seems that recipes can be removed without issue but recipes created with CT can't be crafted. I made a new instance with Twitch, latest version of Forge and only CT, JEI, Tinkers', and Mantle installed and tweaked the vanilla piston recipe to be sure. 

http://imgur.com/a/1XXd7

Edit: After downgrading to 1.11.2-2.7.0.6 I can craft the piston. I'll try with the other pack I was testing to see if those recipes work as well.

Edit2: My recipes work with the older version. Something in the 2.7.0.9 update is breaking CraftTweaker somehow.

**Comment by bonii-xx** [comment]
Have you tried if they work in a vanilla crafting table? Might be the TiC table still has some bugs to iron out in 1.11

**Comment by billybricker** [comment]
Sorry I forgot to mention that the recipe didn't work in a vanilla table either.. I have a shapeless recipe in the other pack I was testing that wasn't working in the 2x2 either until I downgraded.

**Comment by bonii-xx** [comment]
Sounds more like a craftTweaker issue then. Check for errors in your log.

**Comment by billybricker** [comment]
I created another Instance to check, same as before only JEI CraftTweaker, Tinkers' and Mantle. I'm getting the same issue. Simple recipe tweaks aren't crafting at all with 2.7.0.9 but they work again after downgrading to 2.7.0.6 There aren't any errors in the minetweaker.log

https://pastebin.com/s2CtXLRa

http://imgur.com/a/iaUaI

**Comment by bonii-xx** [comment]
Minecraft log...

**Comment by billybricker** [comment]
With 2.7.0.9:

https://pastebin.com/aZgZGApw

With 2.7.0.6:

https://pastebin.com/TUhfMbaA

**Comment by bonii-xx** [comment]
K, no idea what's going on then, TiC doesn't do anything special to recipes.. and it doesn't do anything with recipes in general. Report it to the crafttweaker guys and see what they can find out.

**Comment by billybricker** [comment]
I'm not sure either :/ I'm about to head to work so I'll open an issue with CraftTweaker when I get home.

**Comment by billybricker** [comment]
This appears to be fixed in 2.7.0.12.

**Comment by bonii-xx** [comment]
¯\_(ツ)_/¯
