### ISSUE TITLE
[1.11.2] Crash report (with a modpack)

### ISSUE THREAD

**Issue by Migmag789** [SlimeKnights/TinkersConstruct#2891]
Hello, my game crashed while it is seamless. Tinkers' Construct is my favorite mod and I wanted that for my modpack to be updated with, to share my favorite installers mods, I wanted that this mod is available to everyone, and the best is always in 1.11...

Thank you.

[crash-2017-05-05_20.57.31-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/980055/crash-2017-05-05_20.57.31-client.txt)

**Comment by bonii-xx** [comment]
#2881
