### ISSUE TITLE
Can't craft certain tools

### ISSUE THREAD

**Issue by TheCoolGuy937** [SlimeKnights/TinkersConstruct#2893]
First of all I apologize if this issue has already been fixed..first time playing this mod and it made a good impression on me. 
I can't seem to craft an iron hammer and flint battlesign......I assembled them correctly in the right crafting stations.........I don't know whether they work with other materials.
Also patterns can be crafted without needing blanks...
One last thing......I can only craft one book, the recepies for the other books from fandom wiki don't work........sorry if I'm making a noobie mistake.

**Comment by laz2727** [comment]
Update.

**Comment by TheCoolGuy937** [comment]
Thanks
