### ISSUE TITLE
[1.11.2 - 2.7.0.6] No output out of the tool forge

### ISSUE THREAD

**Issue by Elsopeen** [SlimeKnights/TinkersConstruct#2894]
Hello,
I just had a problem with the crafting principle of TC : I want to craft a hammer full of iron, but nothing came into the output slot, with or without a name. It does the same for the crossbow and the bolts.
![2017-05-06_21 38 33](https://cloud.githubusercontent.com/assets/16364961/25775472/ff73fdd2-32a5-11e7-8820-e7294dbb292b.png)
![2017-05-06_21 41 17](https://cloud.githubusercontent.com/assets/16364961/25775471/ff7206d0-32a5-11e7-832f-d4834660207a.png)
I check the logs, but there was no error messages... I tried it with other materials, nothing, and into an other tool forge (I used the Iron one and the manyullyn one) and nothing too.
The server's running with forge 1.11.2-13.20.0.2228.

**Comment by KnightMiner** [comment]
Use the latest Tinkers Construct build, this was already fixed
