### ISSUE TITLE
[1.11.2] Crash when opening the smeltery controller gui

### ISSUE THREAD

**Issue by sblectric** [SlimeKnights/TinkersConstruct#2895]
When I open the smeltery controller gui, the game crashes.

https://pastebin.com/GNYcZVNQ

Forge 13.20.0.2294
TCon 1.11.2-2.7.0.10
Mantle 1.11.2-1.2.0.27

This is in a dev environment by the way, with dependencies in the build.gradle as follows:
`deobfCompile "slimeknights.mantle:Mantle:1.11.2-1.2.0.27"`
`deobfCompile "slimeknights:TConstruct:1.11.2-2.7.0.10"`

**Comment by bonii-xx** [comment]
Your mappings aren't compatible it seems. Although deobfcompile should take care of that.

**Comment by sblectric** [comment]
the `fontRenderer` field should be named `fontRendererObj` in 1.11.2 afaik

**Comment by sblectric** [comment]
At any rate, a workaround for this issue is to just include the obfuscated jars in one's development environment.

**Comment by bonii-xx** [comment]
Your. Mappings. Are. Incompatible. Update your mappings.

**Comment by sblectric** [comment]
ah heck, didn't realize there were newer ones, got em now 👍
