### ISSUE TITLE
Smeltery Accepts Blazing Pyrotheum As Fuel But Cannot Melt Anything

### ISSUE THREAD

**Issue by Gamemaster2198** [SlimeKnights/TinkersConstruct#2897]
This is confusing me, if you would see this image(s) down there, it says the fuel is blazing pyrotheum (from version ThermalExpansion-1.10.2-5.0.4.90-universal and using TConstruct-1.10.2-2.6.3), temperature of 4000, it can't even melt down ALUMINUM
![2017-05-07_16 00 56](https://cloud.githubusercontent.com/assets/28332429/25785836/80b424b0-333e-11e7-8e7c-4cc3b12fac29.png)
![2017-05-07_16 00 59](https://cloud.githubusercontent.com/assets/28332429/25785837/86ed1760-333e-11e7-83f6-96fcb64e33d9.png)

**Comment by KnightMiner** [comment]
Any liquid will show in that area, even non-fuels. The latest versions displays on the tooltip if it is not a fuel.

**Comment by Gamemaster2198** [comment]
Well yes but it's 1.10.2, it says Fuel, IT SAYS TEMPERATURE OF 4000, ITS BLAZING PYROTHEUM AND IT CANNOT MELT ANYTHING.

**Comment by bookerthegeek** [comment]
Currently the only girl that works is lava.

**Comment by KnightMiner** [comment]
If it says it is a fuel and it is not melting, that is likely another mod's fault, as the API exists to register a fuel and we use it for lava, so they are likely registering it wrong.

Determine the mod that adds the fuel to the smeltery (may be different from the one that adds the fuel) and we can determine if they are doing things correctly.

**Comment by Gamemaster2198** [comment]
Ohhh, now I get it. alright xD

**Comment by Gamemaster2198** [comment]
BTW KnightMiner, it's Thermal Foundation. However, the main mod is Thermal Expansion and Thermal Foundation is a sub mod for it. Requirements for Thermal Expansion: CoFH Core, CodeChicken Lib 1.8+ and Thermal Foundation.

**Comment by Gamemaster2198** [comment]
Link to my GitHub report at CoFH's Thermal Foundation Issue page: https://github.com/CoFH/Feedback/issues/188

**Comment by Gamemaster2198** [comment]
![image](https://cloud.githubusercontent.com/assets/28332429/25875950/188ce6c8-34cf-11e7-927d-615aec160daf.png)
Response from the CoFH Team

**Comment by KnightMiner** [comment]
There is a good chance it is simply not registered as a fuel. We have a tooltip that displays when a non-fuel is in the area in the latest commits, but it seems it was never pushed to a 1.10.2 build.

So yeah, the "bug" is the fuel is not registered at all, but it does not tell you it does not work as a fuel.

**Comment by Morpheus1101** [comment]
Im experiencing this in 1.12.2 and from what i've read im gathering id have to manually add in the Blazing Pyrotheum as a valid fuel source?

**Comment by bonii-xx** [comment]
KL has done some TiC integration. If it's not there he probably didn't want it or forgot. Either way, they should add it or you need to add it manually.
