### ISSUE TITLE
1.11.2 Cascading worldgen lag

### ISSUE THREAD

**Issue by Endmateria** [SlimeKnights/TinkersConstruct#2898]
Your mod is getting constant hits in my server log for "cascading worldgen lag".  The log really doesn't go into much more detail, other than issuing a warning.  If you're sure your worldgen is set up correctly then please disregard, if not then here's a link that I've been sending around to different modders who are having similar issues.  It has many sublinks describing the problem and how to solve it...  https://github.com/Vazkii/Quark/issues/412

MC 1.11.2
Forge 2294
TC 2.7.0.12
Mantle 1.2.0.26

**Comment by CraftMinerKyle** [comment]
Do you have any other mods installed? 3rd Party mods? etc.

**Comment by bonii-xx** [comment]
No, TiC has this problem. I've wanted to fix it for a while, but forgot.

**Comment by bonii-xx** [comment]
Posting this here for myself so I don't forget where it is: https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

**Comment by bonii-xx** [comment]
I have a fix.. just needs enough people using it to determine if it fully works now >_>

**Comment by Endmateria** [comment]
A pre-generator is the quickest way of checking.  I used the Structpro generator (without installing the structure files) to quickly find out which mods where getting hit with worldgen lag in the server console while it generated.  Structpro isn't the best though, it eats up memory until it crashes... there's probably best pre-generators out there.  Here's a new one that might work better...  https://minecraft.curseforge.com/projects/chunkpregenerator?gameCategorySlug=mc-mods&projectID=267193.  I got my server hosting players rights now so I can't run any tests at the moment, but if you're too busy, I can load up a pregenerator later to check for worldgen lag hits.

**Comment by mezz** [comment]
I wouldn't trust pre-generators, they tend to add optimizations for speed that make them potentially unreliable for this kind of test. I just load up a creative world and fly in a straight line.

**Comment by Endmateria** [comment]
Good to know hahaha

**Comment by Endmateria** [comment]
@bonii-xx  Thanks for the fix, sorry I didn't get around to testing it... been busy.
