### ISSUE TITLE
Projectile rendering: 1.11.2 build

### ISSUE THREAD

**Issue by kragnoth** [SlimeKnights/TinkersConstruct#2902]
Build: 1.11.2-2.7.0.14

Shuriken projectiles (have not tested other ranged items yet) that can't be picked up render as purple and black polygons.  If it can be picked up it renders properly.  I have 3 levels of re-inforced modifier installed on the shuriken.

**Comment by CraftMinerKyle** [comment]
Oh. The purple and black means there is a texture error. A polygon you say? (Also, this has nothing to do with the error: If you don't want to have to waste resources and time picking up lost arrows and shurikens, try adding moss to regenerate the stacks.)

**Comment by bonii-xx** [comment]
Probably a stacksize issue.

**Comment by kragnoth** [comment]
Sorry, I mean cube when I said polygon.  Was tired at the time I typed that up.

**Comment by kragnoth** [comment]
Grabbed using git clone, compiled, and works quite well.

Thanks!
