### ISSUE TITLE
Crossbow Crash

### ISSUE THREAD

**Issue by tyopoyt** [SlimeKnights/TinkersConstruct#2904]
Using 1.10.2 - 2.6.1 the game crashes when opening inventory with a crossbow in hand.

**Comment by KnightMiner** [comment]
Crash report or it did not happen.

**Comment by bonii-xx** [comment]
Also you're running on an old version.

**Comment by KnightMiner** [comment]
Closing for a lack of a response. If you want to reopen, try with the latest Tinkers Construct for that version and link a crash report.
