### ISSUE TITLE
Screen goes White entering slime island water

### ISSUE THREAD

**Issue by tortmancomith** [SlimeKnights/TinkersConstruct#2905]
when i enter the water on slime islands my screen goes white and cannot be removed until i reload the game. This is very game breaking since i love grabbing my slime early game and leaving it blind is very dangerous. this happens every time i enter the water so is 100% repeatable.
Thanks for the amazing changes to the mod i cannot go back to 1.7 now :)

**Comment by KnightMiner** [comment]
Please give versions of Forge, Tinkers Construct, and Mantle.

**Comment by bonii-xx** [comment]
Remove Optifine.

**Comment by KnightMiner** [comment]
Closing for lack of information. If you want to reopen this issue, give required versions of Tinkers Construct, Mantle, and Forge, and ensure no client side mods such as Optifine are installed.
