### ISSUE TITLE
Crafting Station Destroys Items During Craft If Inventory Full

### ISSUE THREAD

**Issue by Micah333** [SlimeKnights/TinkersConstruct#2906]
The Crafting Station destroys items/resources used to craft items, if a player's inventory is full.

To replicate:
--Fill inventory inventory slots (for example, with a single cobblestone)
--Prepare a crafting recipe in the Crafting Station (for example, cobblestone stairs)
--Fill the last inventory slot / return any mouse-held items to player inventory (all inventory slots must be full)
--Make note of how many raw resources you have (for example, how many cobblestone you have if any stacks have more than one)
--Shift+Click on the crafting recipe, which would normally craft the item into your inventory
--Note that the items in the Crafting Station are lost, and that the raw materials were not added back to your inventory, and that the finished product is nowhere to be found

TConstruct-1.10.2-2.6.3.jar
FTB Beyond 1.5.3

**Comment by KnightMiner** [comment]
Cannot reproduce, most likely is some other mod causing issues. Try and reproduce with the minimal mods required.
