### ISSUE TITLE
[1.10.2]Materials and You Text Glitch

### ISSUE THREAD

**Issue by fin444** [SlimeKnights/TinkersConstruct#2908]
When reading Materials and You, I noticed that a lot of the text gets put outside of the book. This happens at all GUI scales, on most pages. You can see an image of it here: http://imgur.com/a/aQMSx Most likely this happens on all other versions on all other books, but I haven't checked.

**Comment by KnightMiner** [comment]
Versions? And do you use Optifine or any other client side "performance enhancing" mods?

**Comment by bonii-xx** [comment]
Remove Optifine.
