### ISSUE TITLE
[Compatibility Fix] How do I a get the tool's efficiency (speed) on a certain material?

### ISSUE THREAD

**Issue by Psycho-Ray** [SlimeKnights/TinkersConstruct#2912]
Hi o/

I'm doing a small compatibility fix with Progressive Automation (on PA side). Basically, their machines can use TiC tools, but it doesn't get the proper speed from it, which means ultra slow mining. Well, before anything, I don't know if should be asking about it in here, but I couldn't send any private message using git. I'm sorry if I shouldn't.

I managed to input the correct tool speed with:

> 
> NBTTagCompound tags = itemStack.getTagCompound().getCompoundTag("Stats");
> float tinkersSpeed = (float) tags.getInteger("MiningSpeed");
> return tinkersSpeed / 100;

But the code above does not consider the material on which the tool is being used. I need something akin to:

> function (ItemStack itemStack)
>         ItemTool tool = (ItemTool) itemStack.getItem();
>         Item.ToolMaterial mat = tool.getToolMaterial();
>         return mat.getEfficiencyOnProperMaterial()

However, Tinkers items are not an instance of ItemTool. What can I do?

Thanks in advance,
Psycho

**Comment by KnightMiner** [comment]
Why can't you just call getStrVsBlock? Pretty sure that is the vanilla method we use that applies the tool speeds.

getHarvestLevel should be the one you want to determine if the block cam be mined, but basically just find the vanilla methods that are not part of ItemTool.

**Comment by bonii-xx** [comment]
Just use the same calls vanilla uses to determine speed, rather than relying on the underlying implementation of speed calculation.

**Comment by Psycho-Ray** [comment]
Thanks for swift response! This is my first attempt on anything minecraft related, and, gods, I'm such a newbie right now xD

Would it maybe work? I had to dig into minecraft and PA codes for a while just to get this one line, haha

> function (ItemStack itemStack, IBlockState state)
>     return itemStack.getStrVsBlock(state.getBlock());

I'm using the function on line 138 from [https://github.com/denizyuret/minecraft/blob/master/src/main/java/net/minecraft/item/ItemStack.java](url), which I assumed would be a reliable source for just this, in case you want need to check something.

Again, thanks!

**Comment by KnightMiner** [comment]
Yes, that is the function, though I question why someone is distributing Minecraft's code given that is against [Mojang's license](https://account.mojang.com/documents/minecraft_eula)
