### ISSUE TITLE
[1.11.2] Crash when attempting to use modifier on a bronze tool

### ISSUE THREAD

**Issue by kwpugh** [SlimeKnights/TinkersConstruct#2913]
TConstruct-1.11.2-2.7.0.12.jar
Mantle-1.11.2-1.2.0.26.jar
Forge 2298

Placing a bronze tool and a modifier (diamond, emerald, etc.) into a tool station or tool forge causes the game to crash.   

report: https://gist.github.com/kwpugh/42927d774a144f28dbea7bb977af0e13

**Comment by bonii-xx** [comment]
Update ArmorPlus.
