### ISSUE TITLE
Shurikens have purple block textures when thrown and pass through mobs without damaging

### ISSUE THREAD

**Issue by Vyraal1** [SlimeKnights/TinkersConstruct#2915]
Version: 1.11.2-2.7.0.12
Pack: All the Mods 2

Made a Shuriken with 3 Manyulln and one paper knife blades with 5 reinforced modifiers. After being thrown, the texture model is the default purple checkboard box and passes through mobs without damaging them.

**Comment by bonii-xx** [comment]
#2902
