### ISSUE TITLE
1.11.2 Slimy Trees Not Spawning

### ISSUE THREAD

**Issue by Rhuunin** [SlimeKnights/TinkersConstruct#2916]
MC ver: 1.11.2
Forge ver: 13.20.0.2282
TiC ver: 2.70.0.12
Mantle ver: 1.2.0.26

So I'm running a small modlist using the twitch client: pastebin.com/2beXVvWf

I discovered in my playthrough that after six islands I wasn't getting any slimy trees of any color. So I make a creative world to discover that they're not even spawning in the nether anymore, either. I begin to strip my mod list to find that even with nothing but TiC and Mantle by themselves, my world still isn't spawning slimy trees on slime islands. I even tried to create a new MC profile and reinstalled the mods by themselves to see if it was just something that had gotten corrupted with no change.

I looked in the changelogs on the twitch client and didn't see anything about slimy tree spawns changing, any idea what's going on here?

![2017-05-18_19 45 54](https://cloud.githubusercontent.com/assets/28795527/26251447/e870fc62-3c72-11e7-8ba3-2f3bbd7840dd.png)
![2017-05-18_19 53 00](https://cloud.githubusercontent.com/assets/28795527/26251452/ef4df09e-3c72-11e7-9808-bf3d641daf8e.png)
![2017-05-18_20 02 26](https://cloud.githubusercontent.com/assets/28795527/26251472/f99d6188-3c72-11e7-855b-9e5052b3c063.png)

**Comment by WillBuik** [comment]
I can confirm that I have run into this problem too.  It repros with no other mods (except Mantle) installed.

Versions:
forge-1.11.2-13.20.0.2296
TConstruct-1.11.2-2.7.0.12
Mantle-1.11.2-1.2.0.26

With other mods installed, I sometimes see other mod worldgen trees on the islands, but never any slime trees.

**Comment by scorpion421** [comment]
Confirmed too. Same setup like WillBuik.
Flew over 20.000 blocks to see, if it's changed from common to a rare chance to get a tree. But every floating island is empty like in the screens from Rhuunin.

But no complaining here. We know, it's still in Alpha state and thanks for porting it over to 1.11.2. Really missed it.

**Comment by bonii-xx** [comment]
Yup, a bugfix broke the tree generation.
