### ISSUE TITLE
Can't use Off-Hand (Shield) with Cleaver

### ISSUE THREAD

**Issue by JPH-Systems** [SlimeKnights/TinkersConstruct#2919]
I'm using the Version 2.6.3 for 1.10.2
Only with the Cleaver I cant use my Off-Hand. Maybe it's a feature because you must use both hands. It only makes a weird animation with the sword (like I'm equipping the sword again). 
When it's a feature, it's nice to know when.

**Comment by ArukaAlter** [comment]
It's intended

**Comment by KnightMiner** [comment]
This is intended, the cleaver is a two handed weapon.

**Comment by Dimentive** [comment]
@KnightMiner Could a config option to change this be added? That’d be highly appreciated.

This also affects placing torches from one’s off-hand while holding a cleaver, which I do, for instance, in Extra Utilities 2’s Deep Dark dimension, where I have to fight off mobs while also lighting up the place to avoid dying.

**Comment by SweetSugarSugar** [comment]
@Dimentive It's a two-handed weapon, meaning that you should not be able to use anything in the other hand...

**Comment by Dimentive** [comment]
I don’t like that and would like to have a config option to disable it, but it’s all right. It probably won’t be added, so I’ll just accept it.
