### ISSUE TITLE
Crash when using Slime Sling

### ISSUE THREAD

**Issue by davqvist** [SlimeKnights/TinkersConstruct#2922]
MC 1.10.2
Forge 2281
TC 2.6.3

Someone using Age of Engineering gets sometime crashes when using the Slime Sling. It doesn't happen everytime, only on random ocassions.

https://pastebin.com/s43p8TAF

If you need more info, let me know and I ask him.

**Comment by KnightMiner** [comment]
Duplicate of #2778.

**Comment by davqvist** [comment]
Oops, sorry, I looked, but must have missed it.
