### ISSUE TITLE
Crash when seeing the luck modifier in the book

### ISSUE THREAD

**Issue by AsmodeiXIII** [SlimeKnights/TinkersConstruct#2927]
As simple as the title implies, this crash happens when i look up the luck modifier in the book
[crash-2017-05-26_08.22.59-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1031809/crash-2017-05-26_08.22.59-client.txt)

**Comment by ArukaAlter** [comment]
Remove Optfine and try again.

**Comment by bonii-xx** [comment]
Try again with only TiC and Mantle. Also what language are you using ingame? Might be it's localization dependant.

**Comment by AsmodeiXIII** [comment]
Removed Optifine and tried again. Problem Persists.
Since my resource pack seems to change some Localizations, removed that
too. Problem Persists
Relevant Pastebin <https://pastebin.com/2t39ryCM>

Removed every mod except Mantle and TiCon. Problem Disappears.
Added Mods that add materials to TiCon: Natural Pledge, Blood Arsenal,
Extra Utilities 2: Problem does not reappear.

Im out of ideas...

2017-05-26 9:43 GMT-04:00 boni <notifications@github.com>:

**Comment by KnightMiner** [comment]
You want to try mods that add modifiers, it is one of those that is broken

**Comment by AsmodeiXIII** [comment]
As far as i know, none of the mods i play with add modifiers, they just add
materials.

Do tell me if you spot any out of place: https://i.imgur.com/wpR1Jpp.png


2017-05-26 19:09 GMT-04:00 KnightMiner <notifications@github.com>:

**Comment by AsmodeiXIII** [comment]
Noticed today that i had an old version of the mod. After updating, this bug is gone. Thanks for the help, devs.

CASE CLOSED
