### ISSUE TITLE
Armor creation seemingly impossible with current api

### ISSUE THREAD

**Issue by Lance5057** [SlimeKnights/TinkersConstruct#2928]
Hi I'm the Tinkers Defense dev. So according to mezz mc now requires all armor to extend itemArmor, I guess the way I pulled it off in 1.7 was a fluke thing. Problem with that is though now I can't extend ToolCore. So I tried creating a toolcore specifically for armor stuff but immediately ran into the issue that almost everything in the api only wants toolcore and none of the related interfaces. So at least as it seems now I'm unable to create my armors again. Is it possible that the api could be changed to allow for items that only implement an interface instead of using an extension?
Thanks,
Lance5057

**Comment by bonii-xx** [comment]
What part of the api are you trying to use, that requires you to use ToolCore..?

**Comment by Lance5057** [comment]
TinkerRegistry is the big one. ToolBuildGuiInfo also requires a TinkersItem which requires an extension.

**Comment by bonii-xx** [comment]
ToolBuildGuiInfo is for Tools. If you're making armor you should have your own block with its own GUI. Might be that ToolBuildGuiInfo is missing an abstraction layer, but I don't remember what it's used for ad-hoc. Code-wise everything else should be separated accordingly.

**Comment by bonii-xx** [comment]
I suggest you take all the stuff needed and pull it into the ITinkerable interface, and send me a PR with that.
