### ISSUE TITLE
Can't Stop The Server (amazing bug)

### ISSUE THREAD

**Issue by kenijey** [SlimeKnights/TinkersConstruct#2929]
![stop](https://cloud.githubusercontent.com/assets/24831406/26504438/46768d56-424d-11e7-864b-c260bdad4185.PNG)
latest fml server log is 68 megabytes, i can zip and upload it if anyone wants.

**Comment by kenijey** [comment]
[list.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1032532/list.txt)
here is the list of the installed mods, sorry if it's not TC's fault.

**Comment by TherminatorX** [comment]
Tinker I/O is a separate mod.
https://github.com/gkbm2013/tinker-IO

**Comment by laz2727** [comment]
Looks like tinker io forgot to differentiate between server and client,
probably their bug.

**Comment by kenijey** [comment]
OH i'm so sorry, please forgive me for i didn't notice that.
