### ISSUE TITLE
[1.10.2] [Info] Where can I find the API?

### ISSUE THREAD

**Issue by sipes42** [SlimeKnights/TinkersConstruct#2931]
I have seen one or two references to the API. I was hoping to find it and/or a guide on adding custom materials and fluids. I have looked for a bit, and was hesitant to post this under 'issues,' but I could not think of anywhere else to go. 

I have taken a look at CraftTweaker and its associated addons, but the information is either outdated or minimal...

If you could point me in the right direction, I'd appreciate it.

**Comment by laz2727** [comment]
Fliuds: https://github.com/SlimeKnights/TinkersConstruct/wiki/IMC

Materials are a bit harder because TiC2 expects traits.

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/tree/master/src/main/java/slimeknights/tconstruct/library

Everything in there is the API.

**Comment by sipes42** [comment]
Thanks very much, this should help a lot.

**Comment by bonii-xx** [comment]
Feel free to post questions here or ask in IRC.

**Comment by NightKosh** [comment]
Hello. I'm looking for a way to get items from additional slots. There were few methods for it in the API  in previous versions of your mod: "TConstructAPI.getInventoryWrapper". But I can't find something similar to it. Could you please explain how it can be done?
This is an example of how I used it: 
https://github.com/NightKosh/Gravestone-mod-Graves/blob/master/src/main/java/nightkosh/gravestone/core/compatibility/CompatibilityTinkerConstruct.java

**Comment by laz2727** [comment]
TiC has no extra slots anymore.

**Comment by NightKosh** [comment]
Oh.. I'm not played a lot after all those Minecraft updates. Nevermind it could changed. Is it a temporal decision to remove those slots  or not?

**Comment by laz2727** [comment]
No, it's a spatial one.

j/k it's most likely to be permament

**Comment by bonii-xx** [comment]
Yes, TiC doesn't have the extra slots for hearts etc. anymore
