### ISSUE TITLE
[1.11.2]Bolt embossment crash

### ISSUE THREAD

**Issue by Myknakryu** [SlimeKnights/TinkersConstruct#2935]
Minecraft version: 1.11.2
Forge version: 2310
TConstruct version: 2.7.0.26
Mantle version: 1.2.0.26

What happened:
While trying to make stronger bolts for crossbow using new embossment modifier game crashes when you try to use bolt core as embossment.

Logs:
https://pastebin.com/47JDaNp8

**Comment by bonii-xx** [comment]
Looks like a more general bug with part replacement in 1.11.

What items did you have in the tool forge?

**Comment by Myknakryu** [comment]
Well i used slime crystals, gold block and random bolt core to test embossment on crossbow bolts.
http://i.imgur.com/mpcUIgH.png

**Comment by luckyu19** [comment]
Tested with forge version 2311.
Bug replicated without embossment modifier.
https://pastebin.com/K8G1xrxM

**Comment by luckyu19** [comment]
FYI, bug not replicable in 1.10.

**Comment by CanoLathra** [comment]
Embossment bug still occurring in MC1.11.2, TiCon Version 2.7.0.26. Tested with no other mods installed. Replacement works just fine.

**Comment by KnightMiner** [comment]
It has not been released yet, wait for a release

**Comment by CanoLathra** [comment]
> It has not been released yet, wait for a release

Ok, ty.

**Comment by bonii-xx** [comment]
Right, that reminds me, we should probably release the last fixes before 1.12

**Comment by 016Nojr** [comment]
> Right, that reminds me, we should probably release the last fixes before 1.12

When you say "before 1.12", does that mean: "Start developing TiCon for 1.12", or "Release a 1.12 TiCon version"? @bonii-xx
