### ISSUE TITLE
Furnace cook times reset in 2.7.0.26

### ISSUE THREAD

**Issue by piks** [SlimeKnights/TinkersConstruct#2936]
If you shift click an item in inventory while cooking in bulk and there is items that are already cooking of that item it will reset the cooking timer on that item but whatever lava used during the time of cooking is lost.

**Comment by bonii-xx** [comment]
Hm, sounds a lot like #2586

**Comment by piks** [comment]
yes, sorry I missed that issue. It's the same thing, it still exists I'll move this over to that issue
