### ISSUE TITLE
Molten Metal Interacts Badly with Water

### ISSUE THREAD

**Issue by fin444** [SlimeKnights/TinkersConstruct#2937]
When molten metal flows into water, it just replaces the water. Despite the temperature differences, this still happens, and it's annoying to remove afterwards.

**Comment by KnightMiner** [comment]
What do you expect to happen? It cannot cool down as a metal block is worth 1296mb and a bucket is just 1000mb, the flows cannot cool as that would produce free, unlimited metal, and making cobblestone with the flows does not make sense as there is no rock involved.

**Comment by fin444** [comment]
Create a solid version of the metal, such as "cooled cobalt" or "cooled emerald" which is worth 1000 mb in the smeltery. I know it would be a pain to add all the new blocks, but it's really annoying to deal with when you accidentally place a bunch of molten metal underwater in creative.

**Comment by bonii-xx** [comment]
No.
