### ISSUE TITLE
NoSuchMethodError: MathHelper.clamp

### ISSUE THREAD

**Issue by MidnightsFX** [SlimeKnights/TinkersConstruct#2938]
When trying to include

**`deobfCompile "slimeknights.mantle:Mantle:1.10.2-1.1.5.+:deobf"`**
**`deobfCompile "slimeknights:TConstruct:1.10.2-2.6.+:deobf"`**

On Forge
version = "1.10.2-12.18.3.2297"
mappings = "snapshot_20161111"

I get _`java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.clamp`_

looking at the file, _`import net.minecraft.util.math.MathHelper;`_ is imported properly,

looking at MathHelper, it has a clamp_int, clamp_float, clamp_double but no plain clamp method.

Maybe this is just me being crazy, but I can't seem to find any api-docs that state there is a simple clamp method.

**Comment by MidnightsFX** [comment]
Changing the following fixed this for me:
mapping _`mappings = "stable_29"`_
version _`version = "1.10.2-12.18.3.2202"`_
mantle **`deobfCompile "slimeknights.mantle:Mantle:1.10.2-1.1.4.+:deobf"`**

I'm gunna close this, hopefully it helps others.

**Comment by KnightMiner** [comment]
You are using different mappings that what Tinkers Construct uses. I have been told deobfCompile is supposed to correct that, but @alexbegt was having some issues with that in Natura as well.

For now the easiest fix is to just use the "stable_29" mappings.

**Comment by MidnightsFX** [comment]
Yeah I was reading into it and that seemed like it was the single thing which fixed this issue, thanks for confirming that!

**Comment by bonii-xx** [comment]
You're using the deobf build for deobfCompile. You want to use either the regular build and have it deobCompiled, or use the deobf build and have it as a regular compile dependency (in the first case mappings don't matter, in the latter case they need to match)
