### ISSUE TITLE
forge update

### ISSUE THREAD

**Issue by Kyfigrigas** [SlimeKnights/TinkersConstruct#2940]
im having trouble with opening the game with the mod downloaded each time i do it says i need the update of forge 13.20.00.2282 or something similar which i have ive checked it over several times and i cant figure it out

**Comment by liach** [comment]
#2932

**Comment by Kyfigrigas** [comment]
ok i have it downloaded i put it in my folder but for some reason when i open minecraft and i cant find it when i open minecraft

**Comment by KnightMiner** [comment]
You do not download Forge into the folder, download the installer for your version from [here](http://files.minecraftforge.net/) then run it to add the new version to your Minecraft launcher.

**Comment by bonii-xx** [comment]
Best use some kind of Launcher (Twitch(Curse) or MultiMC) for handling your Minecraft Instances, then you can do all that stuff directly
