### ISSUE TITLE
Help my game crashes and says Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

### ISSUE THREAD

**Issue by Azejma** [SlimeKnights/TinkersConstruct#2943]
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

I have a total of 3.9 Ram  on my pc 
I have a 64 bit PC im using 2G for mincraft and i keep on getting this message  I tried to reinstall Java  100 times but it just doesnt work.
any ideas ??

My mods 
CodeChickenCore-1.10.2-2.4.1.102-universal
CodeChickenLib-1.10.2-2.5.7.241-universal
jei_1.10.2-3.14.7.419
journeymap-1.10.2-5.4.6
Mantle-1.10.2-1.1.5
MCMultiPart-1.4.0-universal
NotEnoughItems-1.10.2-2.1.3.219-universal
refinedstorage-1.2.25
TConstruct-1.10.2-2.6.5
TinkerToolLeveling-1.10.2-1.0.1
torchmaster_1.10.2-1.2.3.27
VeinMiner-1.9-0.35.3.595+a46c1b0

**Comment by bonii-xx** [comment]
Usually I'd probably answer something, but considering you're trying to hijack other issues for your problems AND your issue having absolutely nothing to do with TiC I don't feel motivated to do so. :P

**Comment by Azejma** [comment]
Im sorry i never relised it is hijacking , i am new and i still dont know the rules 
+
this started happening when i downloaded tinker and mantle 
So please help

**Comment by Azejma** [comment]
@bonii-xx If it has nothing to do with TiC what is it about 
and if i open a diffrent issue will u close it ??

**Comment by bonii-xx** [comment]
>I have a 64 bit PC im using 2G for mincraft

You don't have 2 GB free memory though.

**Comment by Azejma** [comment]
Available Physical Memory	2.03 GB

So it is  not enough ??

**Comment by KnightMiner** [comment]
If your available memory is that close to what is being used, there is a chance Java will just not allocate it. Closing other programs is your best bet (things like Google Chrome and iTunes also use a lot of RAM). I would advise you to try the [Minecraft Forge forums](http://www.minecraftforge.net/forum/) for more advise on dealing with RAM, as there is nothing we can change in the mods code to make it work if you do not have enough RAM.
