### ISSUE TITLE
[1.10.2] Casts are not working

### ISSUE THREAD

**Issue by milano1110** [SlimeKnights/TinkersConstruct#2944]
When I try to right click on a faucet with any cast in the casting table, the liquid metal won't pour out. I tried it with iron and gold. But when I remove the cast from the casting table and try to pour gold in it, it works and I get a blank cast.
If you need more information just say it and I'll post it.

Greetings Milano

**Comment by bonii-xx** [comment]
You can't create gold tools. The liquid on the bottom is poured out. Put iron at the bottom of the smeltery by clicking on it and it'll pour out into the cast. Otherwise some other mod is breaking your instance.

**Comment by milano1110** [comment]
I know I can't create gold tools, I was trying to make gold ingots, and when I tried it with the tools cast the iron was on the bottom. I'll try to identify what mod is causing this and if I find out I'll post it here.

**Comment by bonii-xx** [comment]
Try reproducing with only TiC and Mantle first then. If that doesn't work something is really wonky.

**Comment by milano1110** [comment]
So after testing I found out that the Aether II is causing the casts to stop working, after I took the mod out, the casts started to work again. I don't know why this is a problem, but apparently it was.

**Comment by bonii-xx** [comment]
Aether 2 causes a lot of problems in general.
