### ISSUE TITLE
Spaghetti Tool Table Crash

### ISSUE THREAD

**Issue by ewsmith** [SlimeKnights/TinkersConstruct#2945]
Bringing the Mom's Spaghetti (tier 1) and the Tool Station/Forge together makes them angry and they kill minecraft. :c 

[https://pastebin.com/6368e1tm](https://pastebin.com/6368e1tm)

**Comment by ArukaAlter** [comment]
Confirmed with only Tinkers' 1.11.2-2.7.0.26.

**Comment by ewsmith** [comment]
right. forgot to mention it was latest 1.11.2 tico

**Comment by ArukaAlter** [comment]
The log mentions an earlier build, not the latest, but it's still confirmed.

**Comment by KnightMiner** [comment]
Yep, missed a case of a null ItemStack during the 1.11 transition.
