### ISSUE TITLE
[1.11.2] Cobblestone and fish cannot be smelted in the Seared Furnace

### ISSUE THREAD

**Issue by gryttr** [SlimeKnights/TinkersConstruct#2946]
![](http://i.imgur.com/mGiL1iE.png)
Also applies to salmon. Other smelting recipes (beef, cactus, netherrack, stone bricks) work fine.

Tinker's version 1.11.2-2.7.0.26
Mantle version 1.11.2-1.2.0.26
Forge version 13.20.0.2299

**Comment by KnightMiner** [comment]
![2017-06-02_23 19 43](https://cloud.githubusercontent.com/assets/12155288/26750501/02650c3a-47ea-11e7-9581-8251c23d6244.png)
I cannot reproduce in dev. Can you please verify that this happens only with the seared furnace and not other mod added furnaces/the vanilla furnace? It is highly possible some mod removed/broke the recipe. Also, does this happen with just Tinkers Construct and Mantle?

**Comment by gryttr** [comment]
After further investigation I've discovered that this is caused by another mod I have.

**Comment by bonii-xx** [comment]
Which one was it?
