### ISSUE TITLE
Game crashes on load if Smeltery module is disabled

### ISSUE THREAD

**Issue by Serifina** [SlimeKnights/TinkersConstruct#2947]
Crashlog here: https://paste.ee/p/anXlc

If Smeltery module is enabled, game loads without issue. If disabled, it crashes as stated. Crashlog appears to reference XU2, so I'm cross-posting it there, as well.

**Comment by bonii-xx** [comment]
Tema seems to be using some fluid. Fluids are not there if you don't have the smeltery module. Don't disable the smeltery module with XU2 I guess, or Tema needs a check/config. In general it's dangerous to disable the modules, and should only be used for very specific packs.
