### ISSUE TITLE
Game crashes while starting when using TiC and Galacticraft for 1.11.2

### ISSUE THREAD

**Issue by ottmiche** [SlimeKnights/TinkersConstruct#2948]
Hi,
like seen above, my game crashes when I'm adding TiC to Galacticraft and a few other mods on 1.11.2

this is the log: https://paste.ee/p/c9Qff

I ontly post this here because it only crashes when Tic is added, so what can I do to solve this (if there is anything I can do)?

Thanks in advance!

**Comment by luckyu19** [comment]
Was able to launch game with Galacticraft + TiC.
Was able to launch game with mods listed in the crashlog.
Running Forge version 2312, with JEI 4.4.0.283, on Twitch App launcher.

Troubleshoot by doing the following:
Try and replicate the crash by only adding Galacticraft and TiC.
Try building a fresh instance, and update all the mods and forge.
Try removing other mods and see if which mods conflicted.

**Comment by ottmiche** [comment]
Thanks
The instance must have been broken because I've created a new one with all mods I've had before and didn't get any trouble

**Comment by KnightMiner** [comment]
In that case, I am closing this issue. Was probably a broken forge install based on the crash log.
