### ISSUE TITLE
[1.10.2] Tinker's Table Crash - Mekanism (Fluid Tank)

### ISSUE THREAD

**Issue by huwcbjones** [SlimeKnights/TinkersConstruct#2950]
**Cause:** When placing a Mekanism Basic Fluid Tank (with fluid) into a tinker's table, Minecraft crashes.
[Crash Report/Stacktrace](https://pastebin.com/pKyS70K2)

**Work Around:** Disable item rendering on Crafting Table.

**Software Versions:**
* Windows 10 (1703, 15063.296)
* Java 8 x64 (1.8.0 u131)
* Minecraft 1.10.2

If there's any more info I've missed, I'll add it as soon as I can!

**Comment by ArukaAlter** [comment]
It has been reported before, not Tinkers' fault.

**Comment by huwcbjones** [comment]
@ArukaAlter Ok, shall I put an issue in with Mekanism then?

**Comment by huwcbjones** [comment]
Might be a good idea to make this bug a little more known?
Perhaps putting a note in the FAQ about the crash and the workaround might reduce the number of duplicate issues?
