### ISSUE TITLE
{1.11.2} it says there are mods missing but ive downloaded all the dependent mods!

### ISSUE THREAD

**Issue by KiraMalice** [SlimeKnights/TinkersConstruct#2951]
![image](https://cloud.githubusercontent.com/assets/29174088/26760482/ba529ddc-494b-11e7-8ca8-c4b3793b8118.png)

HELP MEH PLS. WHAT AM I MISSING

**Comment by KnightMiner** [comment]
Looks like there is an issue with your version of forge causing it to not display the missing mods. Update Forge and make sure you install the latest Mantle.

**Comment by bonii-xx** [comment]
Also there obviously is no Mantle in your directory.

**Comment by KiraMalice** [comment]
thanks

**Comment by KiraMalice** [comment]
but what about abyssal craft?

**Comment by KnightMiner** [comment]
Our mod has nothing to do with Abyssal Craft. If it is claiming missing dependencies and won't say what, go to the mods description page and it should tell you there.
