### ISSUE TITLE
[1.11.2] Can't find magma slimelands

### ISSUE THREAD

**Issue by Mach12** [SlimeKnights/TinkersConstruct#2952]
Forge 13.20.0.2282
TiC 2.7.0.26 (Latest according to curseforge)
Minecraft 1.11.2

Other mods influencing the Nether generation:
* TechReborn (ores)
* Mystical agriculture (soulstone embedded in netherrack)
* Natura (I don't think I need to elaborate on that one)
* Biomes'O'Plenty (We all know this one)

My settings are at default (magma islands enabled, one in 100 chunks), and despite a week of scavenging I can't find a single magma slime island. I just want to make a magma slime sword blade...
Also I probably went far enough, because in my time playing I have found 5 overworld slime islands (which are at 1 every 700+ chunks), yet I explored at least twice more nether than overworld. In fact, enabling overworld islands in the nether has let me found one before a magma island. I'm baboozled by how tough finding one is.

Rambling aside, here's the seed for my world if you wish to test for yourself. I'd be happy if someone could find an insland, or confirm the lack thereof.
Seed: `1301717609`

**Edit :** Forgot to mention BOP

**Comment by KnightMiner** [comment]
Any chance you can test without Natura? Since it is your main mod with nether changes (other two sound like normal ores), it would be nice to see if we have a conflict or if it was a 1.11 change that caused this.

**Comment by Mach12** [comment]
Alright, I tested without Natura and here's what I got:
* Biomes'O'Plenty traits of the Nether, which didn't show up when I had Natura on, suddenly took over. (Yes I forgot to mention that I had BOP, but BOP has an entirely new generator that has let overworld slimelands spawn, so I expect no less for lava ones).
* Still no magma islands with Natura down.

I expect one to ask me to try without the BOP worldgen, which I did:
* Still nothing if the mod is enabled but I generate a Default world (BOP biomes are still in, but with Default gen shapes).
* Disabling BOP *and* Natura *finally* gives me slimelands.

I also tried enabling Natura and not BOP, no islands.

So this is a... double mod conflict preventing magma islands I guess? With both BOP and Natura? I looked up the [code for magma islands](https://github.com/SlimeKnights/TinkersConstruct/blob/25a03943276b131e4dcbc74907c887491de343a8/src/main/java/slimeknights/tconstruct/world/worldgen/MagmaSlimeIslandGenerator.java) and I'm not sure what's wrong in there. Only suspicion I have is line 61 but I do not know what `ChunkProviedHell` does.

**Comment by KnightMiner** [comment]
Actually, you are exactly right it seems. Awhile ago we had #2071 which pointed out an issue with our generator in overridden Nethers and it seems the fix never got added to Magma Slime Islands.

For the record, if you want the Biomes O Plenty Nether with Natura installed, there is a config to disable Natura overriding the Nether. I am not sure how much of there world gen depends on that, but there is a chance it will play smoothly.

**Comment by bonii-xx** [comment]
I think old versions had a nice and simple "isHell" callback in the generation stuff, but either that got removed or there is no proper access to it from our generation code. It's stupid that we have to use instanceof :L

**Comment by Mach12** [comment]
I'm not sure isHell does it? I mean maybe it does, again I'm not familiar with MCP of the Forge API, but BOP adds way more biomes to the Nether, so I hope isHell doesn't simply account for the biome.

**Comment by KnightMiner** [comment]
I think Natura uses a world provider method called something like `doesWaterEvaporate` to check for the nether. I just used the instance of for consistency.

**Comment by Mach12** [comment]
Actually, I just checked the [code for nether trees](https://github.com/progwml6/Natura/blob/b7e6708fdf3ae1daeba1f37851d1d0506192e375/src/main/java/com/progwml6/natura/world/worldgen/NetherTreesGenerator.java) as an example, and they just seem to do biome checking (see line 83). That would explain why natura hijacks the Nether into having only its base biome.

**Comment by KnightMiner** [comment]
[You found a very specific example](https://github.com/progwml6/Natura/blob/b7e6708fdf3ae1daeba1f37851d1d0506192e375/src/main/java/com/progwml6/natura/world/worldgen/NetherBerryBushesGenerator.java#L58).

In the case of flora, I would go with biome for that as all Nether biomes should use that biome type. But as certain mods add Nether biomes outside of the Nether (where you would want Nether flora, but not Nether structures), checking dimension provider is better for our case.

**Comment by MUSE-iC** [comment]
Is the 1.10 ver. of Tinkers still supported? Bcs this bug is present there too it seems.
