### ISSUE TITLE
[Request] Tool Repair cost 

### ISSUE THREAD

**Issue by bookerthegeek** [SlimeKnights/TinkersConstruct#2955]
## Heyo ##

Hello again! I have a simple request (simple I hope). Can you add a config to make all tools require the vanilla repair mechanic? This would include;
 - Only repairable in an anvil.
 - Repair requires Experience.
 - Repair cost increases with each repair.
 - Not repairable in a tool forge.

Thank you for considering my request. Have a great day!

**Comment by bonii-xx** [comment]
No, we have no intentions to allow that.
