### ISSUE TITLE
Wheat Sticks de-spawn when soaking in water

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#2956]
Minecraft 1.10.2
Forge-12.18.3.2281
Mantle 1.10.2-1.1.5.jar
Tinkers Construct 1.10.2-2.6.5.jar
ModList:
https://pastebin.com/fXnVJLyR

LatestLog:
https://pastebin.com/9wYFXb2T

I toss the sticks in water and wait, after 5 minutes they de-spawn.

**Comment by ArukaAlter** [comment]
By "soaking in water" it means put it in a Casting Table then pour water (3 buckets worth) with a Seared Faucet or anything that transfer fluids, it is listed in JEI

**Comment by TheQuadShot** [comment]
OHHHHH.... Sorry, I went by the tool tip that says "They should probably soak in some water for a while" and didn't think about looking at use in JEI.

**Comment by KnightMiner** [comment]
Yes, they need to soak in a casting table,, not the actual water block.
