### ISSUE TITLE
[1.11.2] Crafting Stations using each other as side inventory

### ISSUE THREAD

**Issue by SimonMeskens** [SlimeKnights/TinkersConstruct#2958]
![Crafting Stations](http://i.imgur.com/ggp7uSb.png)

I always use that setup in tinkers to get four crafting stations sharing a single inventory. I'm playing 1.11 however and it seems like this is broken now, as instead, the crafting stations pick up each other's inventory. I assume this is not intended behavior?

On an unrelated note, I was also expecting the Storage Drawers controller to work as a side inventory as it claims to be just a simple inventory that gets picked up by everything. I assume this is not as simple and working as intended?

**Comment by bonii-xx** [comment]
Crafting stations just pick the first inventory they find, checking directions in a fixed order. And yes, crafting stations have inventories, so they also count. Everything working as intended.

Storage drawers are blacklisted because they crashed iirc. Or something like that.
