### ISSUE TITLE
Ingot Cast Unusale 1.10.2

### ISSUE THREAD

**Issue by Dinmagol** [SlimeKnights/TinkersConstruct#2959]
I'm using a singleplayer Modpack on Minecraft 1.10.2.
My only issue is, that I can't pour any Metals out of the smeltry onto an ingot cast.
Every other cast works fine. And it works with the casting basin.
I didnt find a config option, hopfully I did not miss anything obvious.

**Tinkers Construct Version**
TConstruct-1.10.2-2.6.5.jar

**Forge Verison**
1.10.12-12.18.3.2297

Other Mods:
![grafik](https://user-images.githubusercontent.com/10667676/26942485-860ef4c8-4c82-11e7-88e7-1e6fe92b1188.png)

**Comment by laz2727** [comment]
It's probably Aether.

2017-06-08 22:43 GMT+05:00 Dinmagol <notifications@github.com>:

**Comment by KnightMiner** [comment]
Remove Aether II, it has broken so many features that have no reason to break, so they are probably doing some quite bad stuff on their side.

**Comment by Dinmagol** [comment]
confirmed
Aether II is disabled and it works.
Actually the stencil table wasn't working either.
thanks for the help
