### ISSUE TITLE
Events to prevent creating new tools

### ISSUE THREAD

**Issue by darkhax** [SlimeKnights/TinkersConstruct#2960]
Hi there!

I am looking for an event, or hook, or something similar, which will allow me to prevent a player from making tools under certain conditions. For my specific use case, I am making a tweaker mod which will allow a modpack to group materials into stages, and if the player doesn't have a tier for that stage they will not be able to make tools with those parts. It would also be cool if I could group modifiers into these groups as well. 

I had a brief look through all of the tcon events and it looks like you can do quite a lot, however I didn't see anything that would work for my specific use case. Would it be possible to get something like a ToolCraftedEvent, and a Modifier Applied event, with both being possible to cancel? 

Edit: Some other things which would be helpful, is an event for when a part is created in the part builder. And maybe even a pattern creation event.

**Comment by Darkosto** [comment]
Yes please! I offer cookies, puppies, kittens, and any other thing that may persuade you! Plus! As many cups of coffee that you would like!

**Comment by bonii-xx** [comment]
I was under the impression that we actually have that. Looks like we only have it for part replacement though.

**Comment by bonii-xx** [comment]
Looking at this, modification and tool crafting is easy.
Pattern creation is hard because it doesn't have an inherent way of showing the player what's going on.
Part creation also is hard because toolpart casting exists.

**Comment by bonii-xx** [comment]
Be sure to use the localized cancellation methods. The message will show up in the GUI. Tell the user what's going on.

**Comment by KnightMiner** [comment]
Would we be able to add a cancelable event to casting as well as part building? We don't add any special handling for parts, just leave it up to them to implement. It also opens up flexibility with their system to work with other casting recipes.

**Comment by bonii-xx** [comment]
Hm, potentially yes.
