### ISSUE TITLE
Ores Not Spawning

### ISSUE THREAD

**Issue by IWizard619** [SlimeKnights/TinkersConstruct#2963]
I Got The Right Mods TConstruct 1.11.2 And Mantle 1.11.2 And All The Items For TConstruct Are In Game But Ores Wont Spawn In World And Other Mods Are Working So Its Not My Forge That Is Problem

**Comment by ArukaAlter** [comment]
The only ores existing are cobalt and ardite.

**Comment by KnightMiner** [comment]
Read the in game manual, or the description on just about any "Whats changed in Tinkers Construct 2", or the contributing guideline FAQ maybe
