### ISSUE TITLE
Mom's Spaghetti Crash

### ISSUE THREAD

**Issue by OromisElf** [SlimeKnights/TinkersConstruct#2965]
I have the same issue as #2945 with the most recent (I think) version of Tinkers Construct.
I thought it might be because of TinkerToolLeveling but testing it in a fresh save without it crashed it too.

https://pastebin.com/Pt4Pj63i

**Comment by KnightMiner** [comment]
The issue is marked as resolved but not closed, which means it has not been released yet. It will be fixed in the next release.
