### ISSUE TITLE
If you have 0 tick lag at all times, you may use crossbows.

### ISSUE THREAD

**Issue by Chinthor** [SlimeKnights/TinkersConstruct#2969]
I've found that on SMP, crossbows are nearly unusable. Even after being loaded, they randomly unload. A single r-click unloads them instead of firing, r-click has to be held until it realizes it should shoot. This is not always within the reload time. And I haven't made a very fast drawing crossbow yet. So instead of hitting the target, you have unloaded it and reloaded. I can accept that I may miss because server lag causes the target to not be there. With the old crossbow mechanics, I've had that happen. I can't use this weapon at all if lag is going to affect how it acts in my very hands.

**Comment by OromisElf** [comment]
I can recommend the shortbow with either two iron limbs or an iron and a cobalt limb
got all three modifiers full of redstone, made some manyullyn arrows and oneshot most normal mobs (except witches) with a drawspeed of 0.67
it's really good

**Comment by KnightMiner** [comment]
Sorry for the late response, this issue got buried. Please ensure you are testing in the latest version for 1.12 and if so, try reproducing with a minimal mod set. Its a bit difficult as it may be the other mods causing the additional lag, but its hard to tell whether this is a conflict or an actual issue.

**Comment by KnightMiner** [comment]
Closing for lack of response.
