### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by robertmaxton42** [SlimeKnights/TinkersConstruct#2974]
Is there a changelog for TiCon I can view somewhere? I'm kind of curious about the differences between the version I've got (which is a few points out of date) and the current one, but the closest thing I found is the Changes tab on Curse that seems to only show the last set.

Thanks!

**Comment by Landmaster** [comment]
@robertmaxton42 There are changelogs for each version on CurseForge.

**Comment by bonii-xx** [comment]
The only changelog thing you'll find is on the curse files, yes. There also is some reddit thread with the biggest changes somewhere. Just play with it a but, you'll see the changes quickly.

**Comment by bonii-xx** [comment]
Also note that the mod has been completely rewritten with 1.8, so it's hard to actually provide changes.
