### ISSUE TITLE
Library mod for fluids

### ISSUE THREAD

**Issue by wizard1399** [SlimeKnights/TinkersConstruct#2976]
Could you release a library mod that adds and registers all the fluids from TC so that packmakers can have access t

**Comment by wizard1399** [comment]
o them. I have looked through curseforge and the only thing close is Foundry, but that gets the amounts wrong and has not been updated in over 2 months.

**Comment by wizard1399** [comment]
Minecraft vers 1.10.2 please

**Comment by bonii-xx** [comment]
No. If you have stuff that's usable for the liquids TiC will register them. If you want the liquids without TiC.. well then use some of the weird json mods or make your own simple mod adding the liquids you need.
