### ISSUE TITLE
Adding more items to the furnace via shift-click resets them all

### ISSUE THREAD

**Issue by Tesserex** [SlimeKnights/TinkersConstruct#2978]
If I have several slots filled in my furnace, and they have some progress, when I add more of the same item to the furnace, using shift click in my inventory, all progress on all the slots is reset to 0. Adding by dragging does not do this.

**Comment by KnightMiner** [comment]
Pretty sure this is the same as #2586 as both use the same slot handler. Not sure if there is an easy way to fix it though.
