### ISSUE TITLE
[1.11.2] Tool forge will not allow you to take item

### ISSUE THREAD

**Issue by twistersage** [SlimeKnights/TinkersConstruct#2979]
Using forge-1.11.2-13.20.0.2345-universal.jar and Tinkers-Construct-Mod-1.11.2.jar
Here is a screenshot of the behavior:
http://prntscr.com/fnq22i
I'm unable to pull the tool from the table.  The tool station appears to function correctly. This behavior is only seen with the tool forge.  As a workaround, I've been pulling things out of creative, but this doesn't allow you to create the very custom tools I've seen before.

**Comment by KnightMiner** [comment]
Please download the latest version from CurseForge, from the name I can garentee it was not built by us.

**Comment by twistersage** [comment]
Thank you very much for the advice, I updated to the most recent version available on CurseForge and it is working perfectly. :D
