### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ArtElleys** [SlimeKnights/TinkersConstruct#2980]
I did not find:
1) option to turn on and off the default tool (picks, shovels, hoes, etc.)
2) turn off or turn on a variety of mods, by adding different tools (from cacti, from bone, etc.)

And just a question off topic, in the furnace, as well as earlier it is possible to do alloys, from the resources of other mods ???

**Comment by bonii-xx** [comment]
> option to turn on and off the default tool (picks, shovels, hoes, etc.)

Didn't get reimplemented in the rewrite. Use any Whatever-Tweaker mod

>turn off or turn on a variety of mods, by adding different tools (from cacti, from bone, etc.)

There's no config for that

> Furnace

No, only regular furnaces that the vanilla furnace can do.

**Comment by ArtElleys** [comment]
Or you can add a configuration that would disable the standard tools. But with the possibility of crafting them (for example, a diamond pick is needed in the Buildcraft fashion) with a 0m score.
At one time, it was added by the Iguanas Tinker Tweaks mod. Maud, as I understand, has died, but the fans of your symbiosis have remained. By the way it's strange that you did not want to add this option yourself. Well, just think, you yourself created a new mechanics for creating tools, but at the same time leave the old version.

 I follow the development of fashion, for a very long time, I liked that it was possible to make the game more hardcore. With or without mods (optional), there was a kind of archetype of creating tools. Namely, the increase in production stages. Usually wood, stone, iron and diamond. And with your modification, it all started with silicon, one of the unnecessary resources. But now, when almost all add-ons die, the mod itself removes some of its content, the mod becomes gray. And I just want to play this mod. As always, as on 1.7.10

**Comment by KnightMiner** [comment]
Disabling the standard tools is not something Tinkers Construct is going to do. It is designed to add additional tools for you to play with, not force a progression through itself. The tools are neither designed to be more powerful than vanilla ones or to be more balanced, they are just a more creative alternative.

Tinkers Construct is not a hardcore mod, so hardcore features like that do not fit in the mod. If you want such features, an addon is the best choice, or you are perfectly free to continue playing 1.7.10.
