### ISSUE TITLE
[1.7.10] Both M&You books crash when trying to show tool forge recepis after iron block

### ISSUE THREAD

**Issue by ivan-petrovic-soprex** [SlimeKnights/TinkersConstruct#2981]
Both M&You books crash when trying to show tool forge recipes after the iron block one. crash consistently happens when clicking the next page button.
TC and IC2 are only large mods that i have at the moment.

https://pastebin.com/fFyr4n1D

**Comment by KnightMiner** [comment]
1.7.10 is no longer supported. If I recall, this crash was caused by disabling modules as the book only supports the whole mod being enabled, but its been a year and a half since the last 1.7.10 version was released so I could be mistaken.

**Comment by ivan-petrovic-soprex** [comment]
i tried it and i can confirm that it's the drying rack - when armory module is disabled, books crash the game when trying to render the drying rack.

oh well - at least i can work around the issue...
thanks.
