### ISSUE TITLE
[Suggestion] Config for Edible Slimeballs

### ISSUE THREAD

**Issue by officialMECH** [SlimeKnights/TinkersConstruct#2982]
I like the idea of having bacon as an edible food source, but I feel like slimeballs and coagulated blood feels out of place as edible items, considering the vanilla slimeball is not edible by default. I would suggest including an option, preferably a configuration, to disable the ability to consume slimeballs as food.

**Comment by bonii-xx** [comment]
No. If you don't want to eat them.. just don't eat them.
