### ISSUE TITLE
[1.10.2, 1.11.2, 1.12] Material page icon links in the front of the materials section of “Materials and You” are skipping the material between one page and the next

### ISSUE THREAD

**Issue by Landmaster** [SlimeKnights/TinkersConstruct#2986]
In all of 1.10.2, 1.11.2, and 1.12, whenever the material icon links at the start of the materials section span more than one page, a material icon link is skipped between one page and the next.

Peeking at the source code of both the [1.10.2](https://github.com/SlimeKnights/TinkersConstruct/blob/1.10.2/src/main/java/slimeknights/tconstruct/library/book/sectiontransformer/AbstractMaterialSectionTransformer.java#L65) and [1.11.2](https://github.com/SlimeKnights/TinkersConstruct/blob/1.11.2/src/main/java/slimeknights/tconstruct/library/book/sectiontransformer/AbstractMaterialSectionTransformer.java#L67) versions of Tinkers Construct, it appears that this is definitely a Tinkers issue, and is caused by the fact that whenever `overview.addLink(icon, material.getLocalizedNameColored(), page)` in the linked line(s) is `false` (i.e. a new page is needed), the code fails to call `overview.addLink(icon, material.getLocalizedNameColored(), page)` again (to add the link to the new page) after advancing the iterator for the overview pages.

I noticed this issue while testing my mod [PlusTiC](https://github.com/Landmaster/PlusTiC), which adds several materials to TiC.

**Comment by Landmaster** [comment]
@bonii-xx Is it fine if I make a pull request for this?

**Comment by bonii-xx** [comment]
Oh yeah, please do.
