### ISSUE TITLE
[1.11.2] Cannot Emboss Bowlimbs

### ISSUE THREAD

**Issue by CanoLathra** [SlimeKnights/TinkersConstruct#2988]
Bowlimbs seem to be the only parts you cannot emboss. This places Shortbows at a serious disadvantage.

Is it a bug? Or working as intended?

Tested with just TiCon and Forge.

**Comment by bonii-xx** [comment]
![2017-07-29_15 55 51](https://user-images.githubusercontent.com/722449/28745315-713fd85c-7476-11e7-9b35-e75bb551847b.png)

**Comment by bonii-xx** [comment]
Possibly only fixed in 1.12, but definitively works there.
