### ISSUE TITLE
[1.11.2] My TC ores vanished?

### ISSUE THREAD

**Issue by TsudoUmeko** [SlimeKnights/TinkersConstruct#2991]
I'll start with information about my Minecraft first.

Minecraft Version: 1.11.2
Forge Version: 13.20.0.2366
Tinkers Construct Version: 1.11.2-2.7.026
All other Mods installed(I have never been told or have never seen issues with mods i have. I am new to playing minecraft with mods so i do all the looking i can about compatibility, and yes, alll my mods are installed correct):

Baubles
Better Builders Wands
Bookshelf
Chameleon
Chisels and Bits
CraftTweaker JEI Support
Just Enough Items
CraftTweaker
CT-GUI
Crystal Caves
Waila
Dark Utilities
Extra Utilities 2
Inventory Tweaks
Levels
Mantle
Rope Bridge
Storage Drawers
Tinkers Add-Ons
Tinkers Tool-Leveling
Vein Miner
Waila Harvest-ability
Wearable Backpacks
Xaero's MiniMap and World Map

(I think those are all the extra mods i have that i actually added. Not just files and "mods" in my in-game Mod list GUI that are added with other mods for the coding support)

PS: I have looked everywhere in my game and even tried an X-Ray. Cobalt and Aridite are 100% not spawning in my game. 

Correction: Looks as if they just are't spawning in my main world. Made a new world and they were there.

**Comment by bonii-xx** [comment]
Other mods changes to nether worldgen can mess with it. If it's not generated it's due to some incompatibility (or screwup) with another mod.

**Comment by TsudoUmeko** [comment]
Whoops. Forgot about this thread. haha my bad. I actually figured it out. and reloaded all my world chunks with MCEdit (never used before but it's cool) and now it's all fixed. They we not loaded because of the world being made with my friend and I before me or him had the mod installed.
