### ISSUE TITLE
[1.10.2] No support for other mod bookshelves.

### ISSUE THREAD

**Issue by llloyd4** [SlimeKnights/TinkersConstruct#2995]
Was trying to make mending moss, so I made a bookshelf with the only wood I had on hand, birch, and MC automatically made it a birch bookshelf from Bookshelf. I right clicked the moss ball on the bookshelf and no go, would not convert to a mending moss ball. I had to go hunting a bit to find some plain jane oak to make a proper MC bookshelf before it would work.

**Comment by ArukaAlter** [comment]
The bookshelves from Quark work, it isn't lack of support.

**Comment by Landmaster** [comment]
@llloyd4 What version of Tinkers Construct are you using?

**Comment by xenxero1** [comment]
I had a similar issue and I figured out that i needed 10 levels for it to work. Make sure you have the XP required or else it wont work. Could probably be made abit more obvious in the tooltip though.

**Comment by KnightMiner** [comment]
In the 1.11.2 version and latrr it works on any block that can be used with an enchantment table. That feature was added after 1.10 stopped receiving builds, so unfortunately you have to use the vanilla  bookshelves only in if you are using 1.10.

**Comment by llloyd4** [comment]
Tconstruct 1.10.2 2.6.5 and Bookshelf 1.20.2 1.4.4.347 

Oh, so 1.10.2 stopped receiving support? Ok...

**Comment by KnightMiner** [comment]
With how much time there is between builds, how stable 1.10 is, and how close 1.12 is, it makes sense to stop developing for 1.10.
