### ISSUE TITLE
Question: Best mod for tinker's ore generation?

### ISSUE THREAD

**Issue by chokoth** [SlimeKnights/TinkersConstruct#2996]
My apologies for placing this here, I didn't see anywhere on the curse site to post questions. If you could direct me there, I'll make sure not to clog up your issue tracker in the future.

I'm playing 1.12, and would like to generate a new tinker's ready world for the (likely distant) time when it is updated for 1.12, but I'm not sure what the best mod to use for ore generation would be. I would like, if possible, to go as light as possible on the mod and get basically just ore generation. Is there a recommendation, I looked at all the documentation I could find, but couldn't find any recommendations.

Again, I apologize for putting this question here.

Thanks.

**Comment by KnightMiner** [comment]
The only ore generation Tinkers Construct has is cobalt and ardite, both of which are absent from most other mods. In addition there are slime islands that are quite important, again unique to Tinkers.

You are better off waiting, which I can say it is coming soon (TM) (most of the annoying work is done, there are just a few things that broke in 1.12 that need rewriting)
