### ISSUE TITLE
Stuff missing for 1.12

### ISSUE THREAD

**Issue by bonii-xx** [SlimeKnights/TinkersConstruct#2997]
Things neded for a proper/full 1.12 release. Already done things are checked

- [ ] Recipebook integration for the Crafting Station <- requires forge patch
- [x] Gui-Materials not working (tool station etc.)
- [x] books.
- [x] Material Integration <- Need to hide materials that are not integrated
- [x] Tool Forge recipe <- In code recipes are handled differently
- [x] Test tools, recipes, smeltery on a server instance
- [x] Tool/part creative tabs are missing their icons
- [x] Smeltery recipe discovery
- [ ] Recipebook recipes are shapeless for some reason <- Requires forge patch, Issue [4088](https://github.com/MinecraftForge/MinecraftForge/issues/4088)
- [ ] Open Recipebook + side inventory in crafting station = broken
- [ ] Determine the best place to run `preInit()` on material integrations to avoid addons needing to run it themselves
- [x] Fix "Materials and You" not properly displaying items, switch items to fallback to a shard part before nothing.

**Comment by PBGgamer** [comment]
Can't wait! Currently playing 1.12 modded but looking forward to having those tools ^_^

**Comment by Landmaster** [comment]
Same here—this also means that I will be able to update my TiC addon mod, [PlusTiC](https://github.com/Landmaster/PlusTiC), for 1.12!

**Comment by chickenbouillon** [comment]
Multiple issues. I cannot access any stencils but the large plate pattern. The first guide book has text going off the pages and it will not let me craft the second or third book. I also did not get any other guides after creating any parts. Do I just delete this mod or can someone PALEASE help me.

**Comment by KnightMiner** [comment]
@chickenbouillon: do not hijack another issue to post yours, and seriously search before posting.

**Comment by KnightMiner** [comment]
@bonii-xx do we still need this open? All that is left is recipe book stuff which might make more sense separated out to a new issue.

**Comment by PBGgamer** [comment]
I think this can be closed, it's not really needed any more?
