### ISSUE TITLE
missing all the ores 

### ISSUE THREAD

**Issue by eatdacookie566** [SlimeKnights/TinkersConstruct#2998]
plz help me i am missing most if not all the TC ores from my game

**Comment by xenxero1** [comment]
Version? other mods installed?

**Comment by ArukaAlter** [comment]
If this is 1.8+, there's nothing wrong.

**Comment by eatdacookie566** [comment]
MC version 1.11.2 TC version 2.7.0.6 
mods 
vein miner
lucky block
journey maps
JEI
iron chest
extra utilities 2
and build craft

**Comment by ArukaAlter** [comment]
The only ores present are cobalt and ardite, anything else is done by outside mods now.

**Comment by eatdacookie566** [comment]
what mods do i need then coz i only have the vanilla ores and cobalt and ardite

**Comment by KnightMiner** [comment]
Any mod that adds those ores, normally tech mods. We removed ores that we do not use so they will only be used if another mod adds then
