### ISSUE TITLE
1.11.2

### ISSUE THREAD

**Issue by DanTheAssassin** [SlimeKnights/TinkersConstruct#3001]
This version of tconstruct won't work whatever I do. It's not because of other mods, as I checked it without any other mods. It says a file is missing or something like that. help?

**Comment by DanTheAssassin** [comment]
Update : Partially solved the problem by including "Mantle". Now it says it needs a certain version of forge or higher but I already have higher than what the message says. help?

**Comment by Landmaster** [comment]
@DanTheAssassin Go to the [Forge](https://files.minecraftforge.net/) downloads website, go to the 1.11(.2) tab, find the latest version of Forge, and download it.

**Comment by bonii-xx** [comment]
You need Mantle, Tinkers and run it with an up to date version of Forge for 1.11.2. Check your versions.

**Comment by DanTheAssassin** [comment]
Nope. I already Have Mantle, Tinkers and latest version of Forge for 1.11.2. It isn't that.

**Comment by DanTheAssassin** [comment]
Nevermind. Seems the problem solved itself for some reason.
