### ISSUE TITLE
failed to start server in 1.12

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [SlimeKnights/TinkersConstruct#3004]
[crash-2017-07-17_22.01.38-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1153845/crash-2017-07-17_22.01.38-server.txt)

**Comment by trilexcom** [comment]
i am getting the same thing too, https://pastebin.com/PiuGUxnm

**Comment by Landmaster** [comment]
@5t0rmr1d3r @trilexcom @bonii-xx From the code and crash reports, it looks like [this line](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/TConstruct.java#L117) is responsible. That line was placed in common server/client code, but it should have been in the client-side code only.

**Comment by tiarnia** [comment]
nice to see it fixed so fast how long till we see a new jar on curse?

**Comment by bonii-xx** [comment]
Hours? Days? Weeks? Who knows.  It's an alpha. It's not done. Treat it as such.

**Comment by tiarnia** [comment]
I understand that but currently it doesn't work at all I thought with this simple fix that it might at least launch so we can do some more testing I understand that it's a slow process

**Comment by 5t0rmr1d3r** [comment]
server launches now, i see this error as fixed...
