### ISSUE TITLE
Mending Moss not absorbing xp

### ISSUE THREAD

**Issue by ArchUltimate** [SlimeKnights/TinkersConstruct#3005]
I put mending moss on my arrow but whenever i pick up xp it does not absorb it (I have it in my hot bar btw).

**Comment by KnightMiner** [comment]
Thats not how mending moss works, or even vanilla mending. It must be in your main hand or off hand.

**Comment by ArchUltimate** [comment]
yes i tried this too

**Comment by KnightMiner** [comment]
Give more details. First off, it does not instantly repair the tool, its a gradual thing, you should be able to check in a tool station.

If that does not work, give versions, etc. so we can properly debug this.
