### ISSUE TITLE
[1.12] Failed To Load On Startup

### ISSUE THREAD

**Issue by ElectricBlue1** [SlimeKnights/TinkersConstruct#3006]
Crashed on startup before the game could finish loading to create a test world. Crash Report : [crash-2017-07-17_22.53.04-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1154545/crash-2017-07-17_22.53.04-client.txt)

**Comment by KnightMiner** [comment]
So, someone is adding a recipe with a stack size of 0 on the output. We can probably catch that on our side, but it was an unexpected result.

**Comment by ElectricBlue1** [comment]
Is a mod in my pack causing this error?

**Comment by KnightMiner** [comment]
Possibly, not sure if that's technically invalid or not so I'll just patch it on our side

**Comment by TandJ21** [comment]
i have  exactly the same issue in my modpack 
[crash-2017-07-18_09.25.57-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1155438/crash-2017-07-18_09.25.57-client.txt)

**Comment by TandJ21** [comment]
so its not just electricblue1

**Comment by ElectricBlue1** [comment]
Thank you!! Hope to see the update soon :)

**Comment by Akzyra** [comment]
From the Chisel tracker: 
Mod that caused it: https://minecraft.curseforge.com/projects/block-armor

For me it was the one of the "Extreme Reactors" Block-Armours. I disabled them all.
