### ISSUE TITLE
[1.12] Can't make Aluminum brass alloy

### ISSUE THREAD

**Issue by winnetrie83** [SlimeKnights/TinkersConstruct#3007]
The mod adds aluminum brass to the game, but i was unable to create it.
Here pictures:
![2017-07-18_13 44 08](https://user-images.githubusercontent.com/29025144/28315604-6eaadcbe-6bbf-11e7-8450-3103bacd93d1.png)
![2017-07-18_13 44 11](https://user-images.githubusercontent.com/29025144/28315605-6facf692-6bbf-11e7-9eee-3f2ac47d7f68.png)

**Comment by KnightMiner** [comment]
Mod versions?

**Comment by winnetrie83** [comment]
@KnightMiner 
The titel says 1.12.

**Comment by Jkiller175** [comment]
This is still a problem, using version 2.7.1.9 (in Unstable Pack)

**Comment by KnightMiner** [comment]
That's because it has not yet released. If it is still open, there is no released build.
