### ISSUE TITLE
SMELTERY NOT WORKING!!!! (1.12) *FIXED*

### ISSUE THREAD

**Issue by flyingpickle** [SlimeKnights/TinkersConstruct#3009]
So today i saw that tinkers construct is to 1.12, im happy and i dowload it, i watch some tutorials how to begin and things like dat, but when i decide to make a smeltery, it wont work, and i dont know if its normal the smeltery controler is different than other that i've seen in the book, remodel? HELP!!1!

**Comment by xenxero1** [comment]
Make sure you're using a SMELTRY CONTROLLER and not a tank or furnace controller. Also make sure the important pieces arent on the corner blocks. And that it has drains, and a tank.
 Other than that, more information is needed.

**Comment by flyingpickle** [comment]
thank im just so fucking stupid. -_-
