### ISSUE TITLE
[1.12] Client Crash with opend recipe book

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [SlimeKnights/TinkersConstruct#3010]
Mod Version is 2.7.1.DEV.53da004
[crash-2017-07-18_21.07.13-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1157021/crash-2017-07-18_21.07.13-client.txt)

**Comment by alexbegt** [comment]
Can you try with TConstruct-1.12-2.7.1.7, and did you make any changes to your source or just built a build with the fixed server crash?

**Comment by 5t0rmr1d3r** [comment]
it was just the build with the servercrash fix

**Comment by KnightMiner** [comment]
> Can you try with TConstruct-1.12-2.7.1.7

**Comment by sofifreak** [comment]
It also chrashed with a vanilla crafting table. Only in the inventory crafting it works. 

[crash-2017-07-19_21.57.56-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1161308/crash-2017-07-19_21.57.56-client.txt)

**Comment by KnightMiner** [comment]
That is a different crash (not sure if its our fault), but you are still using an unsupported build. Do the following:

* First, update to the official build from Curse
* Next, try the crafting station again and if it crashes I'd like that crash report
* After that, try the table again and we can see if its the same

**Comment by sofifreak** [comment]
It crashed again.
[crash-2017-07-20_18.05.47-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1162946/crash-2017-07-20_18.05.47-client.txt)

And with vanilla table too
[crash-2017-07-20_18.09.03-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1162954/crash-2017-07-20_18.09.03-client.txt)

**Comment by KnightMiner** [comment]
@sofifreak: your crash is definitely different than this thread if you'd like to make a new issue. As far as I can tell something is not registering properly with the integration tool forge recipes but that should not be possible. We also don't have enderium integration so I want to blame MoarTinkers as they are probably doing things wrong (none of our recipes have this issue). Hard to tell since they are missing their 1.12 source

**Comment by bonii-xx** [comment]
Keep in mind that some things in forge changed, hence some things in TiC changed, which addon authors will have to react to. They should be minimal, but whatever TiC addon you're using, chances are they're doing it wrong currently.

**Comment by KnightMiner** [comment]
Closing for lack of response using a proper build. I will assume the issue was an improper build as no one has had the same issue in a proper one.
