### ISSUE TITLE
Crash on Server Startup

### ISSUE THREAD

**Issue by krelios** [SlimeKnights/TinkersConstruct#3011]
Getting a crash when attempting to start the server--this doesn't happen when launching the same pack as a client. This looks similar to [https://github.com/SlimeKnights/TinkersConstruct/issues/3004](url) but not identical.

[crash-2017-07-18_21.29.30-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1157352/crash-2017-07-18_21.29.30-server.txt)

**Comment by KnightMiner** [comment]
This is identical to #3004.

**Comment by krelios** [comment]
Hmm. That one's marked as resolved but the latest version still crashes.

**Comment by KnightMiner** [comment]
It's resolved because we fixed it, but still open as it's not released.
