### ISSUE TITLE
Necrotic Bone Dictionary Name

### ISSUE THREAD

**Issue by An-Sar** [SlimeKnights/TinkersConstruct#3012]
I did a brief search of the code to see if the necrotic bone already had an ore dictionary name and it didn't appear too, although I could have missed it.

Would it be possible to add a name, such as boneWithered or boneNecrotic? I have a similar item in one of my mods and dictionary compatibility would be quite useful.

Thank You

**Comment by bonii-xx** [comment]
I don't think it has one yet. Which one would be better?

**Comment by xenxero1** [comment]
I would probably recommend something closer to boneWithered, as it seems more universally applicable.

**Comment by An-Sar** [comment]
boneWithered is also what I am currently using for my version of the item
