### ISSUE TITLE
Congealed Slime Blocks not Cancelling Fall Damage (1.11.2, 2.7.0.26)

### ISSUE THREAD

**Issue by SweetSugarSugar** [SlimeKnights/TinkersConstruct#3013]
If you fall onto the edge of any of the Congealed Slime Block, it will not cancel the fall damage and instead deal damage to you.

Standing on the edge of the block (The player does not bounce up as well):
![2017-07-19_01 59 03](https://user-images.githubusercontent.com/14182009/28352720-13be216e-6c26-11e7-9729-e6d808374dfa.png)

Falling onto the edge of the block:
![2017-07-19_02 02 06](https://user-images.githubusercontent.com/14182009/28352762-490212fe-6c26-11e7-822e-8cf5a3f9cac5.png)

**Comment by bonii-xx** [comment]
Related: #2803

**Comment by LovelyFlare** [comment]
It doesn't damage you if you fall onto the center though.

**Comment by bonii-xx** [comment]
I'm not sure this is fixable at all. It's simply minecraft not calling the callbacks on the blocks, because technically your position isn't on the block.. but the hitbox is larger so it still stops.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. Likely not fixable.
