### ISSUE TITLE
[1.11.2][Dev] There is no way to get CastingRecipeWrapper for an existing CastingRecipe

### ISSUE THREAD

**Issue by rinart73** [SlimeKnights/TinkersConstruct#3016]
(Give me a few minutes, I'll format it)

So, for example, I'm making a mod, that makes some changes in TConstruct. And I want to delete some casting recipes. I modify `TinkerRegistry.tableCastRegistry, finding a recipe and deleting it from registry.
But when it comes to the JEI integration, I can't delete a `CastingRecipe` from JEI Registry. Why? Because for `CastingRecipe` TConstruct uses wrapper. 

Let's look at the code in JEI [RecipeRegistry.java](https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/recipes/RecipeRegistry.java#L328):
`public void removeRecipe(IRecipeWrapper recipe, String recipeCategoryUid) {
	...
	removeRecipe((Object) recipe, recipeCategoryUid);
}`

So, we need pass a wrapper of the recipe and category. I asked on the JEI IRC and was told that JEI does '==' comparison checks for wrappers. So I need to pass the **exact same** wrapper, that was used for the recipe.

No, problems, I can just use JEI [method ](https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/recipes/RecipeRegistry.java#L432)`RecipeRegistry.getRecipeWrapper(Object recipe, String recipeCategoryUid)` to get the wrapper for the existing recipe. Easy, right? No. Because:

`getRecipeWrapper(Object recipe, String recipeCategoryUid)` calls `getRecipeWrapper(recipe, recipe.getClass(), recipeCategoryUid)`

The [method](https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/recipes/RecipeRegistry.java#L439) `getRecipeWrapper(T recipe, Class<? extends T> recipeClass, String recipeCategoryUid)` calls
`getRecipeHandler(recipeClass, recipeCategoryUid)` to get the recipe handler.

And this [method](https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/recipes/RecipeRegistry.java#L476) iterates through the handlers, doing something like [this](https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/recipes/RecipeRegistry.java#L495) `recipeHandler.getRecipeClass().equals(recipeClass)`

Sorry, it may be hard to understand me, but I'll try to explain. Also, I'm not talking about `recipeCategoryUid` right now, because it's fine:

1. We're passing an instance of `CastingRecipe` to the `getRecipeWrapper()` method.
2. Then it calls internal `getRecipeWrapper()` method, passing `CastingRecipe` and `CastingRecipe.class` to it.
3. Then internal method calls `getRecipeHandler` with argument: `CastingRecipe.class`
4. When it comes to the `CastingRecipeHandler`, it gives you `CastingRecipeWrapper.class` as a result of `getRecipeClass()`. So, we're trying to check if `CastingRecipeWrapper.class` equals `CastingRecipe.class`. Of course, it's not.

And because it can't find a handler, we're not getting a wrapper for that recipe.
But this is more like a problem on JEI side, right?

Okay, for example we solved this problem (which I did by doing terrible things in the code).
JEI found a CastingRecipeHandler and we're back to the internal `getRecipeWrapper` method:
`IRecipeHandler<T> recipeHandler = getRecipeHandler(recipeClass, recipeCategoryUid);`
...
`IRecipeWrapper recipeWrapper = recipeHandler.getRecipeWrapper(recipe);`

And here we have another problem. `CastingRecipeHandler.getRecipeWrapper`. Here is the code of [this method](https://github.com/SlimeKnights/TinkersConstruct/blob/82d6fa81af5599dae14e2fd06a7eb3b9d6404c8e/src/main/java/slimeknights/tconstruct/plugin/jei/CastingRecipeHandler.java#L24):
`getRecipeWrapper(@Nonnull CastingRecipeWrapper recipe) {
        return recipe;
 }`

So, we want to get a `CastingRecipeWrapper` from `CastingRecipe`. And.. we're getting `CastingRecipeWrapper`  from `CastingRecipeWrapper`?

I really hope that I'm wrong and there is a good way to get `CastingRecipeWrapper` for an existing `CastingRecipe`. But if I'm right, currently, there is only one way to get it.
Iterate though the JEI registry, using Reflection to get a recipe for each `CastingRecipeWrapper` and the perform an equality check. That's just wrong. But it works.

**Comment by KnightMiner** [comment]
We do not support removing items from registries. Ideally they would just never be registered, but that would be handled by events to cancel them (see also #2960). Since they cannot be removed, no point in removing them from JEI as they are valid recipes.

Feel free to make a PR to add events to cancel the casting recipes, otherwise just wait for them to be added as that will be the proper way to prevent a recipe from being added.

**Comment by bonii-xx** [comment]
Yup, as Knightminer said, we don't allow modification of our registries, only event based cancellation of adding things.
