### ISSUE TITLE
[1.12] Corner of smeltery counts as inside?

### ISSUE THREAD

**Issue by billybricker** [SlimeKnights/TinkersConstruct#3018]
I was trying to light the top of my smeltery to prevent spawns and took damage when I stood in the north west corner of the smeltery. I created a test world with a few different smelteries (sp?) and it seems it's always, and only, the NW corner no matter what side the controller is on.

Forge: 14.21.1.2415
Mantle: 1.12-1.3.0.15
TiC: 1.12-2.7.1.9

**Comment by bonii-xx** [comment]
Possible, might be an off by one error with calculating the "inside" hitbox. It's hard to do since there is no way of visualizing it ;)

Can you give us a 3rd person screenshot of where you were standing?

**Comment by billybricker** [comment]
![2017-07-21_13 09 14](https://user-images.githubusercontent.com/26291936/28478513-ee7ec56a-6e15-11e7-9591-573e4959e255.png)

Let me know if there's anything else you need from me.
