### ISSUE TITLE
Forge

### ISSUE THREAD

**Issue by CharlesBladen** [SlimeKnights/TinkersConstruct#3019]
Everytime I try and load minecraft it says I need forge even though i have it. I've tried uninstalling then reinstalling the version and everything but it just doesn't work. Here's the fml log and a screenshot of what is occuring.      ![javaw 2017-07-20 00-00-58-06](https://user-images.githubusercontent.com/30307697/28400000-8b440ef2-6cde-11e7-83e0-764595606512.jpg)

[fml-client-latest.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1161102/fml-client-latest.txt)

**Comment by KnightMiner** [comment]
Install the version the log says it needs. You have Forge 13.20.0.2228. You need Forge 13.20.0.2282. Note the order of the 2 and 8
