### ISSUE TITLE
[1.12] Some casts aren't craftable

### ISSUE THREAD

**Issue by billybricker** [SlimeKnights/TinkersConstruct#3020]
Looks like gold casts can be made for ingots, nuggets, gears, plates, gems (from an emerald only, not sure if you're supposed to be able to use any other gems or not), and blank. Aluminum brass can't be made into a cast at all.

Forge: 14.21.1.2415
Mantle: 1.12-1.3.0.15
TiC: 1.12-2.7.1.9

**Comment by KnightMiner** [comment]
Yep, just noticed this when fixing #3007. Should be fixed with 069ce6c which will be part of the next build

**Comment by billybricker** [comment]
Oddly enough I didn't have any issues creating alloys in the smeltery. (aluminum brass and bronze at least, haven't tried any others yet) I already had the aluminum brass made so I just cheated in the casts and deleted the ingots for now.

**Comment by KnightMiner** [comment]
Huh, weird. I have no idea why it would work unless events are fired out of order, but its definitely going to work in the next build.
