### ISSUE TITLE
Casting tables cause stuttering FPS

### ISSUE THREAD

**Issue by LokIsLoki** [SlimeKnights/TinkersConstruct#3021]
On a modded SMP server

Casting tables making ingots from fluids are giving me and other players FPS drops and general FPS stuttering. This issue is reproducible. Minecraft 1.10.2 - TConstruct 1.10.2-2.6.5

**Comment by Landmaster** [comment]
@LokIsLoki If I recall correctly, 1.10.2 is no longer supported.

**Comment by bonii-xx** [comment]
If that gives you a stutter, then so does placing a block anywhere near there. You can try reproducing it with only TiC and Mantle and no other mods, could also be some other mod doing weird things, or optifine.
