### ISSUE TITLE
Question : No flux capacitor on tools anymore ?

### ISSUE THREAD

**Issue by ExDomino** [SlimeKnights/TinkersConstruct#3022]
I'm using the version 2.7.1.9 and I'm unable to set a flux capacitor on my tools. It is disabled anymore? Or there is an option to enable in the configs?

**Comment by KnightMiner** [comment]
It was removed. Durability has a bit of value in Tinkers and we have several options to manage it. RF was basically free durability as RF is trivial to obtain. It won't be coming back to the main Tinkers.
