### ISSUE TITLE
Maximum y-Controller position

### ISSUE THREAD

**Issue by JulianSchutsch** [SlimeKnights/TinkersConstruct#3024]
I build a tinker smeltery deep into the mountain just to notice, that the smeltery controller posiition is limited to a bottom area (estimate is 9 blocks up). Would be nice to be able to control the smeltery from the top.

Possible solution (works in singleplayer):
in MultiblockCuboid.java, detectMultiBlock, pass a large number (e.g. 256) instead of limit+1 to the first getOuterPos call.

Minecraft Version: 1.10.2
Tinkers Construct: 1.10.2-2.6.5 (or 1.10.2 Branch Head)
Forge: 1.10.2-12.18.3.2316
Several other mods are installed, but I don't see a connection.

During compile I had to change "http://mobiusstrip.eu" to "http://default.mobiusstrip.eu" (Signature error)

**Comment by KnightMiner** [comment]
The reason for the limit is for efficiency as we need to locate the floor of the structure iteratively (check every block for air). I am not sure what the specific impact of allowing full world height for the controller would be, boni would have to answer that as he wrote most of the multiblock code.

In any case, even if we do not set it to allow a larger height by default, it might be worth making it configurable so players have the option of making it bigger while servers can still leave it small for performance.

**Comment by bonii-xx** [comment]
A config will only lead to a lot of "X did Y, why doesn't it work?!?!"
I wonder if we can rework the check to only check farther if everything so far has been seared brick stuff. Smeltery controllers should be placed rarely enough.

**Comment by JulianSchutsch** [comment]
I am not that deep into the code, but from what I know, the cost of iterating down only is small in comparison to check the entire structure. There  has been not limit to the height of the structure so far and it is fully recognized when I place the controller near the bottom.

Similar to Big/Extreme-Reactors I would suggest a configuration option valid for both the maximum height of the smeltery and the controller position. Therefore the controller position would not matter from the users point of view, but the maximum height of the smeltery can still be limited.

Similar options may apply to the other multi blocks.

**Comment by securitywyrm** [comment]
Makes sense from an efficiency standpoint. Might I suggest including that the controller has to be in the bottom 10 layers in the "Materials and you" guide for the seared furnace? That would have resolved the issue for me.
