### ISSUE TITLE
GUI for 1.12 is not compatible with the Recipe Book

### ISSUE THREAD

**Issue by Tenebris11** [SlimeKnights/TinkersConstruct#3031]
![2017-07-23 1](https://user-images.githubusercontent.com/11930600/28496589-f5081008-6f3c-11e7-9aa7-43c84b1e2c0d.png) With JEI
![2017-07-23 4](https://user-images.githubusercontent.com/11930600/28496591-05f6ccce-6f3d-11e7-875a-60635900aae2.png) Without JEI

**Comment by KnightMiner** [comment]
Yes, it's on the list of things to fix in #2997. I think we need a forge patch to properly fix this issue.

To fix this for now so you can continue playing, you either need to open a crafting station that is not next to an inventory or a vanilla one and close the book.

**Comment by bonii-xx** [comment]
As a temporary fix, the crafting book gui will be hidden if there's a side inventory.
