### ISSUE TITLE
Latest Tinkers' does'nt work with latest Immersive Engineering

### ISSUE THREAD

**Issue by Hitel98** [SlimeKnights/TinkersConstruct#3032]
I don't have crash log, 'cause the game did'nt crash, but it says that IE requires the TConstructs' 2.8 version, wich is nowhere can be found on curseforge. Removing Tinkers' fixes the issue, but i would like to use your mod and IE together

**Comment by nightcipher** [comment]
This is a bad dependency on the part of Immersive Engineering. Downgrade to version 0.12-67 of Immersive Engineering until the team there pushes a fix for their dependency list.

Source: [https://github.com/BluSunrize/ImmersiveEngineering/issues/2349](url)

**Comment by Hitel98** [comment]
Thanks for the reply, i will do so :)
