### ISSUE TITLE
Crash when Crafting Tweaks is used in Craftin station.

### ISSUE THREAD

**Issue by gefailter71** [SlimeKnights/TinkersConstruct#3035]
TiC version: 1.12-2.7.1.9
CT version: 1.12-8.1.1
Forge version: 2420

When u click the "balance grid" button in the crafting station u crash.
Edit: There's the crash log https://pastebin.com/Dbkvm8tm

**Comment by KnightMiner** [comment]
Then upload a crash report to pastebin or gist.github.com and link it here

**Comment by KnightMiner** [comment]
According to the report, a recipe is incorrectly registered which is arguably the fault of the crash.

I do not see Crafting Tweaks anywhere in the report so I do not know why it would cause that crash from the recipe book.

Linking related issue: blay09/CraftingTweaks#105

**Comment by blay09** [comment]
The crash wasn't related to Crafting Tweaks, it was actually just a matter of the balance button overlapping with the recipe book button. Crafting Tweaks moves the recipe book button for vanilla crafting tables, but didn't yet for Tinkers Construct. The next version is going to move the button to the right of the GUI:
![CraftingStation](https://user-images.githubusercontent.com/1933180/28718872-1eb54802-73a8-11e7-9a7f-a382a17eaa14.png)

The crash on the recipe book remains of course, and as you said it's probably some broken recipe.

**Comment by KnightMiner** [comment]
@blay09: any changes on our side with the integration needed, or does this all happen in Crafting Tweaks?

**Comment by blay09** [comment]
It happens in Crafting Tweaks as a special case for Tinkers, I didn't see a point in APIfying it since (hopefully) not too many mods are going to implement the recipe book for their GUIs.

**Comment by KnightMiner** [comment]
Since this crash does not really related to Crafting Tweaks, plus blay09 added code to prevent the overlap on his side, I'm closing this issue
