### ISSUE TITLE
[1.11.2] Crash when trying to look up Smeltery Recipes in JEI

### ISSUE THREAD

**Issue by ProxyPlayerHD** [SlimeKnights/TinkersConstruct#3036]
Tinkers verison: 2.7.1.34
JEI Version: 4.5.0.294

I tested this with multiple mods, and only Tinkers crashes when trying to look up Fluid recipes of the Smeltery.

[Report](https://pastebin.com/fCsHTd5t)

**Comment by bonii-xx** [comment]
Does this also happen with only TiC, Mantle and JEI? Looks like it might be a specific fluid/item that causes it.

**Comment by ProxyPlayerHD** [comment]
no matter what kind of Fluid recipe i look up in the smeltery, it crashes.

Fluid Transposer, IE Refinery, etc work fine.

**Comment by bonii-xx** [comment]
Remove all other mods except TiC. Try to reproduce.

**Comment by ProxyPlayerHD** [comment]
not needed, I looked through the log again, it was linked to another issue with AR
`-- Item being rendered --
Details:
    Item Type: zmaster587.advancedRocketry.item.ItemBlockFluidTank@6e2ed439`

That crashed it, no idea why it tried to render that when viewing Smeltery Recipes, but i installed the fixed version of AR and now TC is showing recipes just fine!

soo, i can close this.
