### ISSUE TITLE
[1.12 Bug/Feature] Flux Capacitors modifier missing?

### ISSUE THREAD

**Issue by Gr8umbreon** [SlimeKnights/TinkersConstruct#3040]
Was this modifier removed in 1.12 version? If so, then ok. If not, then idk what is going on.
Screenshot Provided of TC tool and Hardened Flux Capacitor.
![2017-07-24_20 27 45](https://user-images.githubusercontent.com/24768452/28551608-a760a00e-70ae-11e7-8222-b4c03d77b0bf.png)

**Comment by Gr8umbreon** [comment]
![2017-07-24_20 30 04](https://user-images.githubusercontent.com/24768452/28551640-eee4ae3e-70ae-11e7-9b8f-f0cc8be53eef.png)

**Comment by KnightMiner** [comment]
This modifier has not existed since the rewrite. RF on Tinker tools trivializes durability, use one of the many other durability options. 

If you are ever questioning if a modifier exists, consult the in game guide book.
