### ISSUE TITLE
[1.12] Crafting station requires multiple clicks to open

### ISSUE THREAD

**Issue by Simage** [SlimeKnights/TinkersConstruct#3045]
I've noticed several times that to open the crafting station when on another tab it sometimes requires multiple clicks. Initial clicks flash the crafting station then return to the previous tab. I have only seen this behaviour when the crafting station has a connected inventory and as such may be related to #3031 and by extension #2997

Minecraft 1.12
Forge 14.21.1.2420
Mods

- ActuallyAdditions-1.12-r116.jar
- AppleSkin-mc1.12-1.0.7.jar
- BiomesOPlenty-1.12-7.0.0.2291-universal.jar
- Chameleon-1.12-4.1.3.jar
- gravestone-1.8.4.jar
- Harvest-1.12-1.2.4-16.jar
- hopperducts-mc1.12-1.5.jar
- ImmersiveEngineering-0.12-68.jar
- immersivepetroleum-1.12-1.0.12.jar
- InventoryTweaks-1.63+beta.107.jar
- jei_1.12-4.7.1.69.jar
- journeymap-1.12-5.4.9.jar
- JustEnoughResources-1.12-0.8.3.23.jar
- Mantle-1.12-1.3.0.15.jar
- mcjtylib-1.12-2.4.4.jar
- mods.lst
- QuickLeafDecay-MC1.12-1.2.3.jar
- rftools-1.12-6.12.jar
- StorageDrawers-1.12-5.2.9.jar
- TConstruct-1.12-2.7.1.9.jar
- theoneprobe-1.12-1.4.15.jar
- VeinMiner-1.12-0.36.0.623+cd640ee.jar

let me know if I can provide anything else

**Comment by bonii-xx** [comment]
Is this on a server or singleplayer? Try reproducing with only TiC and Mantle, and finding out which mod causes it.

**Comment by KnightMiner** [comment]
Closing for lack of response.
