### ISSUE TITLE
[1.7.10] Materials And You Volume 1 CTD

### ISSUE THREAD

**Issue by ThePatmann** [SlimeKnights/TinkersConstruct#3049]
If you attempt to go to the page after the Tool Forge crafting page, Minecraft crashes to desktop. 
I think this is caused by the book trying to reference a non-existent page.

**Comment by KnightMiner** [comment]
You probably have some module disabled. Hard to tell without a crash report which you did not provide, but 1.7.10 is no longer supported. Latest 1.7 version is nearly 2 years old.
