### ISSUE TITLE
1.11.2 crash at game launching, mods interference ?

### ISSUE THREAD

**Issue by Ricdan** [SlimeKnights/TinkersConstruct#3050]
Hi,
I would like to add Tinker's Construct to our modded private survival server. I waited for a full release and to have time for any bug that could happened... Well it happened...

Here's the crash report : https://pastebin.com/JZeyTZZb

I'm almost sure it's a conflict with another mod already installed but i don't know which one.

Really hope we will be able to add your mod to our server.

**Comment by bonii-xx** [comment]
Buildcraft is crashing. Update the mod or report to them if it's not fixed yet.
