### ISSUE TITLE
Colored text in item names?

### ISSUE THREAD

**Issue by sipes42** [SlimeKnights/TinkersConstruct#3051]
I have been trying (and failing) for some time now to name an item in the tool station/forge with color in the name for some time; I have not been able to find any way to do so, and I was hoping someone could either tell me how, or verify that it can't be done without the use of commands.

**Comment by bonii-xx** [comment]
I don't know how MC in itself handles that, but I doubt it's possible.

**Comment by mraof** [comment]
Minecraft supports colored item names fine with § and then the one digit hex color code, but the text field input thing doesn't let you type § and I'm not sure how hard it would be to change that
An easier solution would be formatting the entered name to add § where it needs to be, usually what I've seen is just replacing & with §

**Comment by bonii-xx** [comment]
Took a quick glance. Minecraft itself doesn't allow you to insert those items into textfields. It also doesn't work in the vanilla anvil GUI.
