### ISSUE TITLE
[1.12] Flux Modifier don't work

### ISSUE THREAD

**Issue by Symbai** [SlimeKnights/TinkersConstruct#3053]
Hi,

I've tried to read many guides, watched many tutorials but I am unable to add RF to my tools by trying to add a flux capacitor to them. They are fully repaired, have all 3 modifiers left.

Am i doing something wrong? Has the flux thing been completely removed? Or is it just missing and will be added later?

It's shame when everything works with energy except for the tools.

**Comment by xenxero1** [comment]
This was removed awhile ago, and an explanation is given here; https://github.com/SlimeKnights/TinkersConstruct/issues/3040
