### ISSUE TITLE
Add Bounce Pad back to TiC2

### ISSUE THREAD

**Issue by CatMe0w** [SlimeKnights/TinkersConstruct#3055]
Bounce Pads are really interesting, lots of people like it. And Bounce Pads can be used to build high speed 'railway' which can be instead of the true rails. Why not add it back?

**Comment by bonii-xx** [comment]
Why not make a PR adding them back?

**Comment by MrGamerTC** [comment]
I agree 100%

**Comment by Landmaster** [comment]
@bonii-xx Is it fine if I work on the PR for this?

**Comment by bonii-xx** [comment]
@Landmaster Yes, we should probably talk first what I wanted to do with them though.

**Comment by Landmaster** [comment]
@bonii-xx What changes do you want/plan to add to the new bounce pads?

**Comment by bonii-xx** [comment]
Closing this in favor of #3079. CC @Landmaster
