### ISSUE TITLE
[Minor] Smeltery info text renders under smeltery fullness lines

### ISSUE THREAD

**Issue by Kinomora** [SlimeKnights/TinkersConstruct#3057]
As demonstrated, the tooltip "There is not enough room inside the smeltery" renders behind the lines on the fluid GUI that indicate more accurate divisions of the smeltery's fullness. http://prntscr.com/g1f510
This does not happen for tooltip on name renders: http://prntscr.com/g1f5n5

TiCon version: 2.12-2.7.1.9
Forge version: 14.21.1.2423

**Comment by bonii-xx** [comment]
Yeah that's a pretty old issue. But it's hard to fix due to how the rendering of the whole GUI is set up.

**Comment by KnightMiner** [comment]
Is there any issue with drawing the scala in drawGuiContainerBackgroundLayer? I just tested it and it seems to fix the issue provided I run it after drawing the tank, so can we assume it will always render in the same order?

**Comment by KnightMiner** [comment]
![2017-08-07_12 37 47](https://user-images.githubusercontent.com/12155288/29038437-474e3a5e-7b6d-11e7-85b1-de0b58a2b794.png)
Patch has been pushed, should prevent this issue hopefully without any side effects.

**Comment by KnightMiner** [comment]
We typically leave issues open until its been released, that way we get fewer duplicates
