### ISSUE TITLE
[Suggestion] Casting table/basin output a redstone signal based on fullness

### ISSUE THREAD

**Issue by Kinomora** [SlimeKnights/TinkersConstruct#3058]
The casting basin should output a redstone signal proportional to the fullness of it, or simply a 1 if the block inside it has hardened and a 0 if there is either no block or molten fluid.
The casting table could use the same mechanic where the table outputs 1 if it has a cast and 0 if it is empty.

This would allow neat redstone signals to control auto-outputting without having to use a clock based system.

**Comment by KnightMiner** [comment]
This already exists, using a comparator will output of an output exists in the table.
