### ISSUE TITLE
WAILA integration AWOL (modid issue?)

### ISSUE THREAD

**Issue by miiichael** [SlimeKnights/TinkersConstruct#3066]
Greetings, after updating my pack to 1.11, I noticed that tconstruct-specific WAILA info (eg. casting basin contents/progress) was absent.

I also see in my logs:

`[13:27:26] [Client thread/INFO] [Pulsar-tconstruct/tconstruct]: Skipping Pulse WailaIntegration; missing dependency: Waila`

I'm therefore wondering if the problem is that it's looking for 'Waila', when (since the 1.11 lowercasening of modids) it should instead be looking for 'waila', as all my 1.10 logs contain many messages of the form:

`[13:00:49] [Client thread/WARN]: * The modid Waila is not the same as it's lowercase version. Lowercasing will be enforced in 1.11`

**Comment by miiichael** [comment]
And [here's the fml-client-latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/1185617/fml-client-latest.log.txt) for a brief play using just Forge, tconstruct and waila.

**Comment by bonii-xx** [comment]
Yes, the modid is incorrect due to capitalization. I think @alexbegt has a handle on the 1.12 alternatives, maybe he can take a look.

**Comment by DoomsDoorWay** [comment]
I'm using HWYLA and I'm having the same issue and from what I can tell from the integration implemented by other mods its a simple fix of just making it lowercase "[waila/]: Enabling mod waila"

**Comment by KnightMiner** [comment]
Yeah, I think 1.11 enforced lowercase mod IDs, but we forgot to update it here

**Comment by DoomsDoorWay** [comment]
Yeah I just took a very sledgehammer approach and modified the waila class without doing any decompiling ect using only 7zip and notepad++ to lowercase the Waila and strangely it actually worked lol and the integration is working now

**Comment by miiichael** [comment]
Thanks! Though I don't suppose there will be a 1.11.2 release for this? *looks longingly at curseforge*

**Comment by bonii-xx** [comment]
Nope.

**Comment by miiichael** [comment]
Dang.
