### ISSUE TITLE
Emeralds don't add a full 50%

### ISSUE THREAD

**Issue by Wenis30** [SlimeKnights/TinkersConstruct#3070]
While I'm upgrading my tools I generally look at both sides to see what the differences are. While I was doing so I noticed that when I'm using an emerald on my tool it isn't adding a full fifty percent.
![Image](https://image.prntscr.com/image/aVcpshgiQkGliUFibkoE1w.png)
![Image](https://image.prntscr.com/image/IdELgji-RaCjv1iDnKNwew.png)

**Comment by laz2727** [comment]
That's because emerald adds half of BASE durability.

**Comment by Wenis30** [comment]
Oooh
Thanks! I just checked and you're right.
However, the book doesn't say base durability. It says "50% durability increase".
![Image](https://image.prntscr.com/image/hNVRnE2dQTKODEzgqcyOJg.png)
I think the book should be a bit more descriptive.

**Comment by laz2727** [comment]
It did add full durability before. But right now the code is built the way so a tool can be safely rebuilt from its materials and modifiers at any time.

**Comment by Wenis30** [comment]
ok

**Comment by bonii-xx** [comment]
It also prevents surprises when you add modifiers in a different order. Maybe we should add a "base" there. And I just noticed a typo there too.
