### ISSUE TITLE
[1.12] Incorrect recipe output

### ISSUE THREAD

**Issue by EmosewaGamer** [SlimeKnights/TinkersConstruct#3071]
The recipe for the Part Chest gives a Pattern Chest.
![image](https://user-images.githubusercontent.com/25333164/28825956-7ece7ca4-76c8-11e7-9250-43958c1f9201.png)

**Comment by luckyu19** [comment]
Bug replicated with the following mod version:
Forge: 14.21.1.2443
Mantle: 1.12-1.3.1.18
Tinker's Construct: 1.12-2.7.2.15

Part chest recipe is missing (checked via JEI).
