### ISSUE TITLE
[1.12] Render Crash Breaking Smeltery

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#3074]
Getting a crash breaking the smeltery with a hammer.

Log: https://pastebin.com/tvGXL1vw

**Comment by bonii-xx** [comment]
Curious. I wonder if vanilla is causing race conditions with itself now... Does this happen every time or only sometimes?

**Comment by MokahTGS** [comment]
Not sure about with just tinkers.   It s a big mod pack

**Comment by KnightMiner** [comment]
I cannot reproduce this in dev, so we are going to need more information to determine the issue. Try reproducing this with minimal mods, there is a good chance one of your core mods is causing the issue as the line number in the crash does not match with the vanilla method.

**Comment by KnightMiner** [comment]
Closing for lack of a response. Reproduce with minimal mods for a reopen, or find the conflicting mod.
