### ISSUE TITLE
Hammer head not showing up in tool forge

### ISSUE THREAD

**Issue by gassug2** [SlimeKnights/TinkersConstruct#3076]
I was about to make a stone hammer head until I encountered this:

![2017-08-03_00 28 39](https://user-images.githubusercontent.com/30685811/28910900-6d8f8156-77e3-11e7-908f-5e3f87c699a0.png)

Any support/feedback or answer would be nice. 

Thank you, have a nice day.

**Comment by gassug2** [comment]
To add on, I'm using Minecraft version 1.7.10, and Tinkers' version 1.8.7 (I have tried updating to the latest version for 1.7.10, but that did not work)

Please note I am using this mod with (about) 60 other mods. However most of them should not make an interference with Tinkers'.

**Comment by laz2727** [comment]
Dude
You need
8
Stones

**Comment by KnightMiner** [comment]
1.7 is no longer supported. You don't have enough material; if you we're playing the most recent version for 1.8+, it would tell you that.

**Comment by LovelyFlare** [comment]
It actually does when you hover over the pattern.
