### ISSUE TITLE
v.1.12 downloaded but it says outdated mod

### ISSUE THREAD

**Issue by k0rvex** [SlimeKnights/TinkersConstruct#3078]
So I'm running minecraft on 1.12 and I've downloaded the most recent version for tinkers, but whenever I run minecraft (on forged and with mantel) it says I can't play because tinkers is outdated? Can someone help?

P.S. forged and mantel are updated and work completely fine, I don't think any other mods are interfering?.. If that can even happen.

**Comment by luckyu19** [comment]
I have no issue launching with just Tinker's Construct.
Here is my version:
Forge: 14.21.1.2443
Mantle: 1.12-1.3.1.18
Tinker's Construct: 1.12-2.7.2.15

Kindly check from Curse website to see if there is a newer version than the one you are using.

**Comment by laz2727** [comment]
"Most Recent" is not a version of TiC. Tell us exact versions of TiC, Mantle and Forge (or your log).

**Comment by k0rvex** [comment]
Forge: 1.12-14.21.1.2428
Mantle: 1.12-1.3.1.18
TiC: 1.12-2.7.2.15

**Comment by luckyu19** [comment]
Post a screenshot of the error message.
Also is this bug happen when you have a profile with just TiC?
And not to sound offensive, but did you download from Curse website?

**Comment by k0rvex** [comment]
I'll post a screenshot but it may take a few minutes
Not too sure what you mean, but all my mods go onto one profile; forge, and then I run that profile and all the mods usually work or dont, depending on the versions etc
I directly downloaded TiC from this link: https://minecraft.curseforge.com/projects/tinkers-construct

**Comment by k0rvex** [comment]
The error message:
![fffff](https://user-images.githubusercontent.com/30716107/28958535-b3f51af2-78c4-11e7-98fd-84ff109ae68d.PNG)
The one forge profile:
![ffff](https://user-images.githubusercontent.com/30716107/28958552-c69fba72-78c4-11e7-9dc4-0b1920b25ad4.PNG)

**Comment by k0rvex** [comment]
Oh I forgot to mention, whenever I download the version of TiC that says its 1.12-2.7.2.15 instead it gives me version 1.11.2-2.7.1.34
not sure why that happens but maybe its the problem?

**Comment by laz2727** [comment]
Yeah
![2017-08-04 12 31 00](https://user-images.githubusercontent.com/2369751/28958705-d1a8d57e-7910-11e7-9adc-1f7f278ca8c7.png)

**Comment by laz2727** [comment]
Since TiC 1.12 is beta you have to click it on the right.

**Comment by luckyu19** [comment]
Change your MC version to 1.12.
I am running 1.12 and has no issue.
The error suggests that the issue is not TiC, it's your MC version.

**Comment by laz2727** [comment]
No, TiC 1.12 accepts any MC version up to 1.13.

**Comment by k0rvex** [comment]
Okay, let me try that.

**Comment by Drullkus** [comment]
Make sure you are pressing the Download button next to the actual file not the Green download Button

<img width="1108" alt="screen shot 2017-08-04 at 12 36 32 am" src="https://user-images.githubusercontent.com/5010174/28958918-25b14d54-78ad-11e7-80d9-7f5803053cfb.png">

<img width="639" alt="screen shot 2017-08-04 at 12 38 20 am" src="https://user-images.githubusercontent.com/5010174/28958960-50a14db6-78ad-11e7-8e4f-cf4ab500caec.png">

**Comment by k0rvex** [comment]
I feel like a goof, I was pressing the green download button. Thanks guys, it worked
![aaaa](https://user-images.githubusercontent.com/30716107/28959117-0a32efe6-78c7-11e7-84d4-0d6d7b32540e.PNG)

**Comment by bonii-xx** [comment]
Right. That download button only does the latest release. It has been annoying for a while. Time to change the 1.12 version to release I guess. Glad you got it running.
