### ISSUE TITLE
Recipe book crash to do unknown recipe: efln

### ISSUE THREAD

**Issue by Kinomora** [SlimeKnights/TinkersConstruct#3080]
Forge: 14.21.1.2423 (1.12.0)
TiCon: 1.12-2.7.2.15

I went to go craft something and accidentally pressed the crafting guide book and I crashed.
I get a similar crash when doing it in a vanilla crafting table, in my inventory, or at a station.
https://pastebin.com/C46jnkC4

Only seems to happen on a multiplayer server, as I can do it in single player on the same pack just fine.

**Comment by KnightMiner** [comment]
Is the config the same on both the server side and the client side? Specifically, no modules are disabled on either side? Otherwise this crash is basically impossible

**Comment by Kinomora** [comment]
As far as I am aware? We use server-sync to copy the server mods and configs to the client, so I don't know how they could be different. I added one or two extra client-side ones.
I will try again with a fresh download of exactly what's on the server though.

**Comment by Kinomora** [comment]
I tested it with a completely fresh download and loaded up a single player world, tested it, and nothing happpened.
As soon as I connected to the multiplayer server and opened the guide book I crashed.
Other people on the server have noted having this issue too, but they just avoid it because JEI, but I keep clicking the stupid book :v

**Comment by KnightMiner** [comment]
The thing is, that recipe is loaded in the proper way from Forge, there really is nothing we can do differently. I'd bet some mod is messing with the recipe loading or breaking things in other ways.

Does this happen with just Tinkers on a server?

**Comment by Kinomora** [comment]
I'll throw together a local server and see if I can find the culprit and keep you updated on what I can find.

**Comment by thiakil** [comment]
@KnightMiner in single player I don't even get the button showing in the Crafting Station GUI, what could be causing that? O_o

(same server/config as Kino)

**Comment by thiakil** [comment]
@KnightMiner you do appear to have a bug related to the visibility though.

https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/tools/common/client/GuiCraftingStation.java#L72

If the Book is not open, the button will **never** show. You have to actually open it from *another crafting gui* to make it show (when no side inv, the hiding of it correctly works).

**Comment by Kinomora** [comment]
Without any mods being removed or configs being changed, running the default version of this pack caused this server stacktrace, but did not crash the server.
https://pastebin.com/zGKQC5TJ

-Some time later-

After removing half the mods, testing it, getting no crash, adding half the removed ones back, and so on, I have narrowed it down to being CraftTweaker2 as the only mod not in the pack that is causing the crash, as I am able to open the book in single player and multiplayer without the mod but now, on my local testing environment, I have added CT2 back and have not crashed. To confirm, I have added each mod back slowly and deleted the world and no longer crash in my environment where the configs were downloaded from the original source and are identical on my local server and client.

However, now that I'm not crashing on my local server, I have tried to join the hosted server (as originally) and tested it and again crashed with the same error. I guess that means this is a problem with CT2 and a config desync?

**Comment by KnightMiner** [comment]
That sounds highly pluasible. Crafttweaker is likely handling recipes in a way which Forge does not expect, specifically I think it supports removing and Forge does not yet.

I'd check their tracker for the issue and crosslink this issue.

**Comment by KnightMiner** [comment]
Closing this as it was fixed on CraftTweaker's side.
