### ISSUE TITLE
[1.12] Invar Not Possible?

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#3081]
We are not seeing invar being an alloy possible in the smeltery.  Is this a change or is it a bug?

2 Iron and 1 Nickel correct?

**Comment by Landmaster** [comment]
@MokahTGS Possible duplicate of #2813; for now, use an addon mod that supports invar alloying, such as PlusTiC.

**Comment by KnightMiner** [comment]
Duplicate of #2813
