### ISSUE TITLE
[1.10.2] Render problems (Not using optifine)

### ISSUE THREAD

**Issue by themechman** [SlimeKnights/TinkersConstruct#3082]
Having an odd rendering problem. I am unsure if this is your mod or not.

I am working in a connected tinker table to a vanilla chest. While working on the table, the UI for the chest portion goes blank as if someone is removing the contents. I thought it was someone playing tricks on me, but it occurred even when no one else is online.

![2017-08-04_23 25 29](https://user-images.githubusercontent.com/2990361/28992532-9d452e2a-796c-11e7-8e44-23d0e366ce26.png)

This is what it looks like after it happens. It just does it. I've broken and moved the table and chest. Accessing the contents of the chest directly shows everything there. I can click the blank spaces where they were and the inventory UI shows back up.

Another issue is that when I pour liquid metals from other mods, the output block from the casting basin defaults to a Chisel mod texture and renders invisible in the basin.
![2017-08-04_23 33 57](https://user-images.githubusercontent.com/2990361/28992569-06d5ad8c-796e-11e7-98f2-0a9b37f1d3a4.png)
![2017-08-04_23 35 59](https://user-images.githubusercontent.com/2990361/28992570-0d9b5a04-796e-11e7-9a6c-79c81ea8b511.png)
![2017-08-04_23 36 03](https://user-images.githubusercontent.com/2990361/28992575-3d1521de-796e-11e7-9cdf-cfdc13e6723a.png)

I am unsure if they are related. Please let me know if you would like any more information.

MC: 1.10.2
Forge: 12.18.3.2185

Mod list and versions:
1.10.2_deadly_monsters_1.5.jar
advgenerators-0.9.20.23-mc1.10.2.jar
ae2stuff-0.6.0.9-mc1.10.2.jar
appliedenergistics2-rv4-alpha-11.jar
AutoRegLib-1.0-2.jar
Baubles-1.10.2-1.3.11.jar
bdlib-1.12.4.24-mc1.10.2.jar
Botania r1.9-341.jar
Chameleon-1.10.2-2.3.0.jar
Chisel-MC1.10.2-0.0.11.26.jar
CodeChickenLib-1.10.2-2.5.9.267-universal.jar
CoFHCore-1.10.2-4.1.9.13-universal.jar
compatlayer-1.10-0.2.9.jar
CookingForBlockheads_1.10.2-4.2.45.jar
CTM-MC1.10.2-0.1.1.16.jar
cyberware-1.9.4-1.10.2-beta-0.2.10.jar
Decocraft-2.4.2_1.10.2.jar
ElevatorMod[V.1.3.0][MC.1.10.2].jar
EnderZoo-1.10-1.2.3.44.jar
Galacticraft-Planets-1.10.2-4.0.0.111.jar
GalacticraftCore-1.10.2-4.0.0.111.jar
GraveStone-1.10.2-Graves-1.0.6.jar
GraveStone-Extended-1.0.5.jar
Hwyla-1.8.17-B31_1.10.2.jar
InventoryTweaks-1.62-dev-66.jar
jei_1.10.2-3.14.7.420.jar
journeymap-1.10.2-5.4.7.jar
malisiscore-1.10.2-4.4.0.jar
malisisdoors-1.10.2-5.2.0.jar
malisisswitches-1.10.2-3.2.0.jar
Mantle-1.10.2-1.1.5.jar
MCMultiPart-1.4.0-universal.jar
Mekanism-1.10.2-9.2.2.301.jar
MekanismGenerators-1.10.2-9.2.2.301.jar
MicdoodleCore-1.10.2-4.0.0.111.jar
NetherPortalFix_1.10.2-3.3.4.jar
omlib-1.10.2-3.0.0-110.jar
ompd-1.10.2-3.0.0-22.jar
openmodularturrets-1.10.2-3.0.0-182.jar
Pam's HarvestCraft 1.10.2j.jar
PersistentBits-1.10.2-1.0.6.jar
plustic-5.2.0.0.jar
ServerTickMonitor-1.9.4-1.1.0.jar
special_ai-1.10.2-1.1.3.jar
StorageDrawers-1.10.2-3.7.10.jar
TConstruct-1.10.2-2.6.5.jar
ThermalDynamics-1.10.2-2.0.9.12-universal.jar
ThermalExpansion-1.10.2-5.1.8.16-universal.jar
ThermalFoundation-1.10.2-2.1.4.8-universal.jar
TickDynamic-1.10.2-1.0.0.jar
Tinkers Addons-1.10.x-1.0.3.jar
TinkerToolLeveling-1.10.2-1.0.1.jar
WIRED-1.7.0.jar

**Comment by laz2727** [comment]
Chisel thing is known (assuming anyone else remembers it), not much we can do.

**Comment by themechman** [comment]
Yep. Just noticed that on their repo.

**Comment by KnightMiner** [comment]
I've experienced the side inventory issue before, but never reliably enough to make an actual report. I don't think I have seen it in 1.11+ though.

Chisel issue is #2884, please keep one issue per report.

**Comment by themechman** [comment]
Sure. Didnt know if they were related.

I played a different modpack with the same versions and did not experience this problem with it. Its a visual nuisance, but something people can live with. I'll strip mods out later to see if i can eliminate it.

**Comment by bonii-xx** [comment]
Closing this since it was 1.10.2.
