### ISSUE TITLE
[1.10.2] Drying Rack not working

### ISSUE THREAD

**Issue by themechman** [SlimeKnights/TinkersConstruct#3083]
This is not a visual problem unfortunately.

JEI reports that making monster jerky should only take 5 minutes. I am assuming that this is real world minutes. I have waited 20 real world minutes for the progression to monster jerky from rotten flesh. It is not occurring. Yes, I've stood in one spot, in the same chunk.

MC: 1.10.2
Forge: 12.18.3.2185

Mod list and versions:
1.10.2_deadly_monsters_1.5.jar
advgenerators-0.9.20.23-mc1.10.2.jar
ae2stuff-0.6.0.9-mc1.10.2.jar
appliedenergistics2-rv4-alpha-11.jar
AutoRegLib-1.0-2.jar
Baubles-1.10.2-1.3.11.jar
bdlib-1.12.4.24-mc1.10.2.jar
Botania r1.9-341.jar
Chameleon-1.10.2-2.3.0.jar
Chisel-MC1.10.2-0.0.11.26.jar
CodeChickenLib-1.10.2-2.5.9.267-universal.jar
CoFHCore-1.10.2-4.1.9.13-universal.jar
compatlayer-1.10-0.2.9.jar
CookingForBlockheads_1.10.2-4.2.45.jar
CTM-MC1.10.2-0.1.1.16.jar
cyberware-1.9.4-1.10.2-beta-0.2.10.jar
Decocraft-2.4.2_1.10.2.jar
ElevatorMod[V.1.3.0][MC.1.10.2].jar
EnderZoo-1.10-1.2.3.44.jar
Galacticraft-Planets-1.10.2-4.0.0.111.jar
GalacticraftCore-1.10.2-4.0.0.111.jar
GraveStone-1.10.2-Graves-1.0.6.jar
GraveStone-Extended-1.0.5.jar
Hwyla-1.8.17-B31_1.10.2.jar
InventoryTweaks-1.62-dev-66.jar
jei_1.10.2-3.14.7.420.jar
journeymap-1.10.2-5.4.7.jar
malisiscore-1.10.2-4.4.0.jar
malisisdoors-1.10.2-5.2.0.jar
malisisswitches-1.10.2-3.2.0.jar
Mantle-1.10.2-1.1.5.jar
MCMultiPart-1.4.0-universal.jar
Mekanism-1.10.2-9.2.2.301.jar
MekanismGenerators-1.10.2-9.2.2.301.jar
MicdoodleCore-1.10.2-4.0.0.111.jar
NetherPortalFix_1.10.2-3.3.4.jar
omlib-1.10.2-3.0.0-110.jar
ompd-1.10.2-3.0.0-22.jar
openmodularturrets-1.10.2-3.0.0-182.jar
Pam's HarvestCraft 1.10.2j.jar
PersistentBits-1.10.2-1.0.6.jar
plustic-5.2.0.0.jar
ServerTickMonitor-1.9.4-1.1.0.jar
special_ai-1.10.2-1.1.3.jar
StorageDrawers-1.10.2-3.7.10.jar
TConstruct-1.10.2-2.6.5.jar
ThermalDynamics-1.10.2-2.0.9.12-universal.jar
ThermalExpansion-1.10.2-5.1.8.16-universal.jar
ThermalFoundation-1.10.2-2.1.4.8-universal.jar
TickDynamic-1.10.2-1.0.0.jar
Tinkers Addons-1.10.x-1.0.3.jar
TinkerToolLeveling-1.10.2-1.0.1.jar
WIRED-1.7.0.jar

**Comment by themechman** [comment]
I'm an idiot. there are two racks....

**Comment by bonii-xx** [comment]
Yes, Item racks are not Drying racks. However since Item racks are meant for decoration purposes they look the same. Maybe we should give them red names or something..
