### ISSUE TITLE
Can't make Pattern

### ISSUE THREAD

**Issue by tiny0mic** [SlimeKnights/TinkersConstruct#3084]
![2017-08-05_21 43 05](https://user-images.githubusercontent.com/30751864/28995993-a4f3b638-7a29-11e7-9cee-bc1f03224fce.png)
![2017-08-05_21 43 12](https://user-images.githubusercontent.com/30751864/28996032-5858650c-7a2a-11e7-8390-bbc1231bc9d8.png)

Forge: 14.21.1.2426
Mantle: 1.12-1.3.1.18
TConstruct: 1.12-2.7.2.15

**Comment by laz2727** [comment]
*sigh*

Uninstall/update Optifine.
