### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by RedBullSlurpie** [SlimeKnights/TinkersConstruct#3085]
Sorry not sure if this is the right place to post suggestion or not or if it's allowed, but my suggestion is to make a button for the stencil table that is a Craft all button, so you can craft all stencils with one click, or to have the ability to select the ones you want, and hit craft so that it crafts all the ones you want, with one click.

**Comment by Landmaster** [comment]
@RedBullSlurpie There's almost no point in creating multiple stencils for the same part; also, there are only so many parts available in TiC.

**Comment by KnightMiner** [comment]
I cannot see this being added, its way too much effort to implement and would be clunky to use, when ultimately it would save you a minute once per world.
