### ISSUE TITLE
Slime boots and sling a bit overpowered

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#3087]
Since these items are fairly easy to acquire and have no durability, they provide extremely fast travel at no cost. This makes most means of travel somewhat useless, since one can freely hop across the world.  

Also, nullifying fall damage completely on such a cheap item renders regular armor inert, where many experience levels are required just to reduce the damage.

**Comment by bonii-xx** [comment]
Ok.

**Comment by MarioSMB** [comment]
This doesn't seem to be resolved... Is there a reason for simply closing it?

**Comment by KnightMiner** [comment]
The [FAQ](/SlimeKnights/TinkersConstruct/wiki/FAQ), specifically the first point. This falls under the category of a suggestion as overpowered is up for interpretation. Changing it might be considered, but we typically don't leave suggestions open.

**Comment by bonii-xx** [comment]
You stated your opinion. I acknowledged it. Hence the ticket was resolved.
