### ISSUE TITLE
Reinforced V (5x Obsidian Large Plate) Still Consuming Ammo on Shuriken

### ISSUE THREAD

**Issue by imjusthereforthebloodmagic** [SlimeKnights/TinkersConstruct#3091]
Hello everyone, I've lurked on here for a good while but recently stumbled across an issue that I seem to require some more direct help on. I'm aware that using 5 Obsidian Large Plates on an item will give it Reinforced V, and supposedly make it unbreakable, and giving unlimited stores of ammunition. Seeing that paper shuriken have 7 modifiers by default, this seemed like a fantastic way to make an early-game minigun on my FTB Infinity Evolved (TC v1.8.8) server. After adding the 5 Large Plates, the shuriken were consumed normally. I'm aware that there is a persisting bug with the Reinforced V with Obsidian and Manyullyn pieces at least up through the 1.10 versions, and to be fair this is 1.7.10, but I've seen nothing to suggest that there should be any issue with paper components. I've already seen this [https://github.com/SlimeKnights/TinkersConstruct/issues/2499](url) thread, the ones it links to, and several others. None have answered my question. If there is a direct clone thread, I'd be happily directed to it. If anyone has any idea what's up, I'd love to hear. Thanks!

**Comment by bonii-xx** [comment]
5 Obsidian Plates give Reinforced 5, give 50%.
You're thinking about TiC 2, which is MC 1.8+, where you have a separate reinforce item which gives 20%. So in short, for MC 1.7.10 you need 10 modifiers.

**Comment by imjusthereforthebloodmagic** [comment]
Ah, thank you. I went back and checked the Materials and You book again and you're right, I had that remembered from a different version. Not looking to plug a nether star into something silly like this, so I suppose that's a bust. I know there are things like Magical Wood that give stupid broken default modifiers (11 at default, made a longsword and gave it just quartz and a mossball, maxed out it has +44 damage - better than awakened draconium by a landslide) but to be completely honest I'm not looking to make that one super public yet since it'll probably be overlooked for a while. Anyway thanks for the help, this is precisely what I was looking for!
