### ISSUE TITLE
EFLN server crash

### ISSUE THREAD

**Issue by ouroborus** [SlimeKnights/TinkersConstruct#3095]
I'm running an ATM1 server. I've found that EFLN can crash the server. Happens about 1 in 3 times. It seems like the explosion completes as the effects and drops are there when the server comes back up.

ATM1 3.01
Tinkers' Construct 1.10.2-2.6.5.10

**Comment by bonii-xx** [comment]
Crashlog.

**Comment by ouroborus** [comment]
[crash-2017-08-11_16.49.24-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1221296/crash-2017-08-11_16.49.24-server.txt)

**Comment by bonii-xx** [comment]
>at nc.handler.DropHandler.addBlockDrop(DropHandler.java:34)

Some other mod is crashing when the EFLN drops the blocks. Hard to tell if they're doing something wrong  or if the EFLN passes incorrect data. I'd wager it's the former.

**Comment by laz2727** [comment]
goo.gl/yHZew1

It actually looks like a vanilla/forge bug? getDrops, which is used in Exploder.explodeBlock, returns a NoNullList with no items in it and no default element if a dropped block has no drops, like tall grass. That being said, it is deprecated.

**Comment by KnightMiner** [comment]
Closing since this appears to have been fixed on NuclearCraft's side (though their commit history is painful to navigate as they commit full versions at once)
