### ISSUE TITLE
[1.12.1] Mobs drop nothing but XP

### ISSUE THREAD

**Issue by Endgineer** [SlimeKnights/TinkersConstruct#3096]
Note: Hopefully this isn't a duplicate of some issue; I've checked a few pages and used "search" but no issue has been posted about this yet (or maybe I'm the only one having the issue).

I've noticed that mobs drop nothing but XP (namely ANY passive mobs); I've tried checking the "client-latest" log but wasn't able to figure out which mod was causing the issue. After checking console (MultiMC), it turned out to be Tinkers Construct. The snippet included is printed in console every single time I kill any passive mob. Hopefully, this'll help with fixing the issue. If anything else is needed, pls let meh know. :/

[Snippet](https://pastebin.com/Q9hZAd1w)

**Comment by bonii-xx** [comment]
Looks like a bug, yes

**Comment by Endgineer** [comment]
Strange; can't seem to reproduce the issue on dedicated servers. Dedicated servers seem to work just fine; seems like it's only single player.

**Comment by bonii-xx** [comment]
Were you shooting the mob with stuff? The corresponding code only reacts to projectiles.. and it'd require some weird forge bug.

**Comment by Endgineer** [comment]
I was using swords, no projectiles.

**Comment by bonii-xx** [comment]
Can't reproduce in my dev environment, using Forge 14.22.0.2452

**Comment by Endgineer** [comment]
I was still able to reproduce in 2453; perhaps it's some other mod interacting with TiC and causing this? Strange... :/

Like I said though, this only seems to happen in singleplayer, not in multiplayer (dedicated servers).

**Comment by bonii-xx** [comment]
Some other mod returning invalid capabilities.
