### ISSUE TITLE
[1.12] Smelting cobald ore into a cobald block results in invisible block in the basin

### ISSUE THREAD

**Issue by DietmarKrause** [SlimeKnights/TinkersConstruct#3097]
No crashes, The cooled down cobald block gets invisible, but is there, On click it is visible in the inventory and can be placed and is visible then and can be turned into ingots. Looks a little bit chiseled as a block.... 
I am playing all the mods 3
No Optifine, no texturepack. But chisel is installed.

**Comment by bonii-xx** [comment]
#2884
