### ISSUE TITLE
ADD ore core compatibility 

### ISSUE THREAD

**Issue by CronusMaker** [SlimeKnights/TinkersConstruct#3098]
I would like to add platinum ore in the new versions I was hunting for a mod to add the silver and the tin to 1.11.2 and in the mod I found to subistitur the word of ores I found the ore core and in it has a miner called platina and the only one apparently Not usable

https://minecraft.curseforge.com/projects/ore-core

**Comment by bonii-xx** [comment]
We don't add mod specific compatibility.

**Comment by CronusMaker** [comment]
add new ores in systen
