### ISSUE TITLE
[1.12] [Feature Request] Add support for HWYLA

### ISSUE THREAD

**Issue by zackeezy** [SlimeKnights/TinkersConstruct#3100]
https://github.com/TehNut/HWYLA/issues/86

I miss seeing how cooled things are in my hud

**Comment by KnightMiner** [comment]
We fixed WAILA support in the latest 1.12 build. It should work unless HWYLA changed their mod ID.

**Comment by TehNut** [comment]
Nope, I'm still (and always will be) `waila`.

**Comment by KnightMiner** [comment]
In that case, I am closing this as already existing.
