### ISSUE TITLE
Can't Get into game, keeps crashing everytime

### ISSUE THREAD

**Issue by joshq2003** [SlimeKnights/TinkersConstruct#3101]
dear people 
i need help fixing my issues with tinker construct but keeps crash everytime 
If you can answer me so that be great.
oh yeah you might need the crash report thing.
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/library/tools/ToolCore

**Comment by KnightMiner** [comment]
1.7.10 is no longer supported. The other issue you commented on has the solution to that issue.
