### ISSUE TITLE
TC 1.11.2  Can't Select Certain Weapons to craft in the Tool Station and Tool Forges

### ISSUE THREAD

**Issue by HenryBAKAR** [SlimeKnights/TinkersConstruct#3103]
First of all, I apologize if this issue has already been reported; I looked through the issues to see if it had but I did not see it.  

I'm currently playing Minecraft 1.11.2 and I'm using your most recent version of Tinker's Construct: TConstruct-1.11.2-2.7.1.34.  I've found what appears to be a bug with the Tool Station/Forge intereface menu.  When I try and select certain weapons, I am unable to bring up their respective crafting grids.  
![2017-08-15_15 24 33](https://user-images.githubusercontent.com/31050922/29339990-b64fff2c-81d1-11e7-892e-96f6e5d044d0.png)
In this picture's case, I am unable to select the Short Bow.  You can see it being highlighted, but not selected.  

I've did some tests with each of the tool forges and found the following:  All of the tools, (Shovel, Pickaxe, hatchet, etc., and certain weapons (Broadsword, Pan, Sign, Scythe, Cleaver, Crossbow, Arrows, and bolts) ALL function just fine.  The Shortbow, Longbow, Longsword, Rapier, and Shuriken either work seldom, or don't work at all depending on the table.  Here is the complete list of what works and what doesn't:

Tool station:
Longsword WORKS
Rapier WORKS
Short bow doesn't work

Iron tool forge:
Longsword doesn't work
Rapier doesn't work
Short bow doesn't work
Long bow doesn't work
Shuriken doesn't work

Pig iron tool forge:
Longsword doesn't work
Rapier doesn't work
Short bow doesn't work
Long bow doesn't work
Shuriken doesn't work

Knightslime tool forge:
Longsword doesn't work
Rapier SOMETIMES works
Short bow doesn't work
Long bow SOMETIMES works
Shuriken doesn't work
![2017-08-15_15 28 02](https://user-images.githubusercontent.com/31050922/29340233-c3cf438c-81d2-11e7-93d9-de5895e1e032.png)
This Picture shows that the Longbow is indeed selected, however, I had to click on it MANY times before it finally decided to select it.  For the others that don't work, no amount of clicking worked.  

Cobalt tool forge:
Longsword doesn't work
Rapier RARELY works
Short bow doesn't work
Long bow RARELY works
Shuriken doesn't work

Ardite tool forge:
Longsword doesn't work
Rapier RARELY works
Short bow doesn't work
Long bow RARELY work
Shuriken doesn't work

Manyullyn tool forge:
Longsword doesn't work
Rapier doesn't works
Short bow doesn't work
Long bow VERY RARELY works.  I almost gave up on this one, but I managed to get it selected.  
Shuriken doesn't work

I don't know if this is a problem with the mod itself, or a mod conflict.  I've listed what mods I'm using and their respective versions below for you to replicate it if there is indeed a mod conflict.

Thanks for any help you can provide.  I really love this, and I was ecstatic to see the return of bows and crossbows.  

Forge Version:  1.11.2 - 13.20.1.2386
Tinker's Construct, Version: TConstruct-1.11.2-2.7.1.34
Mantle, Version: Mantle-1.11.2-1.2.0.26
Better Combat Mod, Version: [MC 1.11.X] BetterCombatMod 1.4
Forever Enough Items, Version: Forever-Enough-Items-1.1.0-beta3-1.11.2
Excore (Required For FEI), Version: EXCore-2.0.0-beta1-1.11.2
Just Enough Items (Required For FEI), Version: jei_1.11.2-4.5.0.295
Light Level Overlay Reloaded (Required For FEI), Version: LLOverlayReloaded-1.1.3-mc1.11.2
More Overlays (Required For FEI), Version: moreoverlays-1.12-mc1.11.2
Fast Leaf Decay, Version FastLeafDecay-v12
YALSM - Yet Another Leather Smelting Mod (Adds Recipies to turn Rotten Flesh into Leather), Version: yalsm-2.1.7-mc1.11
airbreathercore (Required For YALSM), Version: airbreathercore-1.0.2-mc1.11
GraveStone Mod, Version: [1.11.2] Gravestone Mod 1.7.4.1
DecoCraft2, Version: Decocraft-2.4.2_1.11.2
BiblioCraft, Version: BiblioCraft v2.3.3
Pam's HarvestCraft, Version: Pam's HarvestCraft 1.11.2h
Redstone Paste, Version Redstone Paste v1.7.4 (for Minecraft 1.11.2)
Better Builder's Wands, Version: Better Builder's Wands 0.11.1 [MC1.11,1.11.2; rev 239]
Walia, Version: Waila-1.7.1_1.11.2

**Comment by KnightMiner** [comment]
I have never seen this issue before, so there is a good chance it is a mod conflict. I personally would blame Forever Enough Items as its been known to cause GUI issues in the past with JEI.

Reproduce with minimal mods so we can determine which mod is the cause. Also ensure you can reproduce on the latest 1.12 version, as otherwise this issue will be closed as already fixed in the latest build.

**Comment by HenryBAKAR** [comment]
Ok, I have solved the problem.  You were right that FEI was at fault.  After removing the mod, I was able to select the previously unselectable weapons.  Thanks for the help, shame about FEI though, I guess I'll have to wait for it to either update out of Beta, or find something else.

**Comment by KnightMiner** [comment]
[This spreadsheet](https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w/edit#gid=0) from the JEI contribution guidelines should help you find an alternative if you need. Personally I just play with JEI by itself.

**Comment by HenryBAKAR** [comment]
Thanks!
