### ISSUE TITLE
Crafting Station simple item multiplication

### ISSUE THREAD

**Issue by Sonic2423** [SlimeKnights/TinkersConstruct#3104]
With a simple setup of 2 Hoppers and 1 Crafting Station and some redstone and 2 repeaters every craftable item can be obtained multiple times AND the ingredients restock.

Simple Setup:

Place Crafting Station
Place Hopper inputting to the SIDE Crafting Station (not top(havent tested))
Place another hopper below the crafting station facing to any side but not downwards.
now build a simple redstone clock:
R=Redstone "->"=Repeater
R->R
R<-R
now connect one end of the redstone clock to the lower hopper.
kickstart with placing a redstone torch next to the redstone and breaking it immediately again.
Block 4 slots of the lower hopper (eg. Stone or any material not used in the recipe to test)
Test with beacon recipe:
use the fifth slot of the hopper and place 1 nether star.
place the glass and the obsidian into the crafting table manually so that every item slot has half a stack and it looks like this.
O=Obsidian X=Glass +="Nothing"
XXX
X+X
OOO

Now insert 63 Nether Stars to the upper hopper.
Now Open the Crafting Table Gui and rapidly click the output slot.
If its not working collect the nether stars from lower hopper but leave one in there and reinsert to the first hopper.
Now you should get the beacon and sometimes the items in the crafting table restock.

Video on Youtube (Not listed):
https://youtu.be/wT0F3KdzPcs

What i have written in the video description:
"Running:
TinkersConstruct 1.12-2.7.2.19
Forge 1.12.1-14.22.0.2456
Tested in Single Player World

This also works with:

TinkersConstruct 1.12-2.7.2.15
Forge 1.12-14.21.1.2424
and several other mods (eg. AE2,TE,IC2,...)
Running on dedicated private server where i discovered the bug.

I came across this dupe bug while crafting signalium from TE and didnt notice that the silver and copper were constantly restocked and my Destabilized Redstone wasnt enough for clearing out the crafting station. I basically thought:"Craft until the table is empty". So i questioned my self if im going insane or this is a bug. After messing around with Applied Llamagistics 2 when i constantly imported and exported the same item (in this case clay because it is just one slot) for the grout recipe and tada! magically all items restocked.

Conclusion:
I havent lost my sanity but i can provide this video.

Have a nice day!"

Hope this helps. :)

**Comment by KnightMiner** [comment]
Does this happen with vanilla chests? This sounds like the old item dupe bug with hoppers that happens in vanilla.

**Comment by Sonic2423** [comment]
i dont think this is related to the hoppers because it also happens as i stated how i found this bug. You can try the same with AE2 exporting and importing the same item to the crafting station with the same behaivour. As to how i originally came across this bug is when the crafter was placed next to a fluid transposer which filled my buckets destabilized redstone which was set to automatically pull at the crafting station side so i thought i can use the signalium blend recipe and when i crafted it would automatically pull the empty bucket. but it also pulled the full bucket. so i thought ok place the bucket fast in the crafting grid bevor the fluid transposer pulls the bucket. and then it happend. the 3 slots copper and the single slot silver which were on 8 items per slot went to 64 and the pucked was pulled to the fluid transposer.

So there are 3 ways to reproduce this:
Vanilla with hoppers and only TC installed or
with AE2 by simultaneously importing and exporting the same item to the crafting table or
with (what i think is the cause) crafting the item the exact moment an item is exported so that the slot goes blank (eg. when the stack size for that item is just 1).

For me it sounds like this is on TCs side because it seems like it is just dependent on the item export while crafting.

**Comment by bonii-xx** [comment]
This is a very complicated bug. The crafting station is based on the vanilla workbench, which doesn't have an inventory. It looks a bit like a desync between client and server. I'll have to disable pulling out of the crafting station, since this is by far the easiest way to prevent the issue and only provides a minor inconvenience.

**Comment by evernife** [comment]
Was this fixed on 1.10.2 ?

**Comment by KnightMiner** [comment]
Nope, fixes target the latest version typically. It might get patched only if a bigger issue in 1.10 needs patching, but it is so far pretty stable.

**Comment by evernife** [comment]
Ok, for now i will just ban the crafting table :D

**Comment by KnightMiner** [comment]
Well, that is an option, though if you are going to ban any blocks with a potential dup bug you also need to ban vanilla hoppers as those had a similar bug until 1.12.2.
