### ISSUE TITLE
Tinker's Construct Incompatibility with Extra Utilities MC[1.12.1]

### ISSUE THREAD

**Issue by potatochan721** [SlimeKnights/TinkersConstruct#3107]
Running a server and received attached crash report on load. Server will load with TCon or ExtraUtils but not with both. Not sure which mod is actually causing the problem. 
[crash-2017-08-17_15.14.25-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1232385/crash-2017-08-17_15.14.25-server.txt)

**Comment by KnightMiner** [comment]
This is an Extra Utilities issue, they have a NPE in their Tinkers plugin. Cannot debug any further as that mod is closed source.

**Comment by potatochan721** [comment]
Okies. Thanks for looking into it. I'll see if I can pass along the bug report.
