### ISSUE TITLE
No item showed in the main mod menu and JEI

### ISSUE THREAD

**Issue by THEAN24** [SlimeKnights/TinkersConstruct#3109]
![2017-08-12_14 41 35](https://user-images.githubusercontent.com/31125227/29449056-2377e0e6-83ae-11e7-9591-ae2486dbd18b.png)
![2017-08-12_14 41 43](https://user-images.githubusercontent.com/31125227/29449057-237aa966-83ae-11e7-952c-c9ee507ce489.png)
![2017-08-12_14 41 46](https://user-images.githubusercontent.com/31125227/29449059-238849e0-83ae-11e7-92de-65e16017564a.png)
![2017-08-12_14 41 50](https://user-images.githubusercontent.com/31125227/29449058-2382c7b8-83ae-11e7-93ec-c1bef72b75b1.png)
![2017-08-12_14 41 52](https://user-images.githubusercontent.com/31125227/29449060-238a04ba-83ae-11e7-838a-39dc3e4affbd.png)
![2017-08-12_14 41 54](https://user-images.githubusercontent.com/31125227/29449061-238bb774-83ae-11e7-9583-d12c19fc145d.png)

This is all the result when I download the mod; there is no item showed. pls help

**Comment by bonii-xx** [comment]
#3008
