### ISSUE TITLE
Problem with "Materials and You" book [1.12.1]

### ISSUE THREAD

**Issue by Lonewolf22113** [SlimeKnights/TinkersConstruct#3111]
Text on the left page cuts off in the middle of the book and the text on the right page goes outside the book:

![2017-08-19_16 53 14](https://user-images.githubusercontent.com/13752971/29487776-10cf5ec2-84ff-11e7-8b9a-ac940b9ec2f7.png)

Current Mods:
AppleSkin-mc1.12-1.0.7
backpacks 1.12-1.5.1
Baubles-1.12-1.5.1
ClockHUD-1.12-1.4.0
cxlibrary-1.12.1-1.6.1
forestry_1.12.1-1.6.1
gigaherz.commons-1.12.1-0.6.4
gravestone-1.9.0
Hwyla-1.8.20-B32_1.12
jei_1.12.1-4.7.5.87 [soon to be swapped by nei]
journeymap-1.12.1-5.5.0b1
KleeSlabs_1.12-5.3.2
Mantle-1.12-1.3.1.18
miniheads-1.0.7a-1.12
MultiPageChest-1.12-1.9.1
notenoughwands-1.12-1.5.9
Optiine_1.12.1_HD_U_C5
OreExcavation-1.4.105
Pam's HarvestCraft 1.12c
Scannable-MC1.12-1.5.0.9
**TConstruct-1.12.2.7.2.19**
ToolBelt-1.12.0-1.7.1
WailaHarvestability-mc1.12-1.1.11

**Comment by KnightMiner** [comment]
Remove Optifine, it breaks our rendering even though we have nothing special implemented.

**Comment by laz2727** [comment]
>nothing special implemented

Apart from the whole "recoloring item sprites on the fly" thing.

**Comment by KnightMiner** [comment]
That is a normal Forge feature as part of model baking. :P I mean we are not coremodding rendering code or anything related.
