### ISSUE TITLE
Weird secret box in Tool Forge Rapier

### ISSUE THREAD

**Issue by Arkyo** [SlimeKnights/TinkersConstruct#3112]
![image](https://user-images.githubusercontent.com/25037295/29492640-6274c9d6-85b5-11e7-9e84-c72f15d54fe8.png)

**Comment by laz2727** [comment]
Gui slot removal is a bit hard, so the buttons on the left just move them.
You can see that by filling all 6 slots and switching the tool.

**Comment by KnightMiner** [comment]
Yep, those are the extra slots unused for that tool. Try leaving items in it before switching and you'll see what it's for.
