### ISSUE TITLE
[1.12] Missing clay casts for non-tool parts

### ISSUE THREAD

**Issue by Lykrast** [SlimeKnights/TinkersConstruct#3114]
Ingot, Nugget, Gem, Plate and Gear casts aren't available in clay version, unlike the tool component casts. This may be intentional but seems strange from a consistency point of view.

**Comment by bonii-xx** [comment]
Mostly due to lazyness, since those aren't autogenerated unlike the tool casts. But also because those are things where you always want more than one, making clay casts pretty useless. So I decided to simply skip them, even though it's not consistent.
