### ISSUE TITLE
Seared Furnace, Controller must be in bottom 10 layers

### ISSUE THREAD

**Issue by securitywyrm** [SlimeKnights/TinkersConstruct#3115]
For very tall seared furnace structures, the seared furnace controller has to be in the bottom 10 layers to work. 

Discovered this when I built a 11x11x63 seared furnace from bedrock to sea level, and had to place the controller down at the bottom. Reproduced in single player to identify point where controller stops working.

**Comment by bonii-xx** [comment]
Mostly due to performance reasons. See #3024

**Comment by securitywyrm** [comment]
Ah, makes sense. I suppose the "fix" would be to have the height restriction info in the "materials and you" guide to the furnace.

**Comment by bonii-xx** [comment]
We should probably put it in there. We were debating on relaxing it, though.

**Comment by securitywyrm** [comment]
I think balancing inconvenience and efficiency is the core experience of Feed the Beast :)
