### ISSUE TITLE
[1.12] Hammer with explosive modifier removes lava

### ISSUE THREAD

**Issue by DrLogiq** [SlimeKnights/TinkersConstruct#3119]
The title says it all, really. I'm working on a BIG dig at the moment in 1.12, and I have a hammer with the Blasting III modifier, and when hammering stone right above lava, the lava within the 3x3x1 area is removed. I don't know if this is an intended feature or not, but it may be worth bringing to attention.

**Comment by bonii-xx** [comment]
Not intended, but explained by blasting 3 simply destroying blocks. Quite hilarious, but a bug. Thanks for reporting :D
