### ISSUE TITLE
Is the "craftCastableMaterials" config option broken for some items?

### ISSUE THREAD

**Issue by opum2** [SlimeKnights/TinkersConstruct#3125]
When "craftCastableMaterials" is true, it still doesn't let me craft Iron tool parts that are normally required to be smelted in a smeltery, in the part builder.

Is this a bug? Or an intended feature?

Thanks!

**Comment by bonii-xx** [comment]
None that we know off. But it isn't used much either. Maybe it broke.

**Comment by KnightMiner** [comment]
Cannot reproduce in the latest 1.12 version, so it is not likely caused from 1.12 changes. Please reproduce with minimal mods for a reopen.
