### ISSUE TITLE
Battlesign putting Shield on cooldown

### ISSUE THREAD

**Issue by Lordician** [SlimeKnights/TinkersConstruct#3126]
Hey, i was testing my mod and while trying out some default tinker items in comparison i found an issue with a tinkers construct tool.
The issue is that when struck by an axe-type weapon while blocking with a battlesign, the battlesign would not go on cooldown, but the vanilla shield would.
The version of Tinkers Construct i was working with is 1.11.2-2.7.1.34, but i think this is present in every current version.
It would be a bit more fair and less buggy if this would be fixed at some point.

**Comment by bonii-xx** [comment]
Yeah, because vanilla has everything hardcoded to its own shields. Will have to revisit that and see if we can fix it properly now, now that shields aren't a new thing anymore.

**Comment by KnightMiner** [comment]
This is possible to fix by making our battle sign declare itself as a shield using the Forge method, however that means we are also stuck with vanilla logic for damaging the sign which does not respect our modifiers.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support.
