### ISSUE TITLE
BUG duplicate item 

### ISSUE THREAD

**Issue by EnergizedPhoenix** [SlimeKnights/TinkersConstruct#3130]
it where you get arrows and a longbow. click Q on the arrows then quickly click on the tool force. then arrows come back but duplicate.

**Comment by bonii-xx** [comment]
Versions?

**Comment by EnergizedPhoenix** [comment]
The version is FTB infinity 1.10.2

**Comment by bonii-xx** [comment]
1.12 is not developed further. It's also likely that it's caused due to another mod in the pack.

**Comment by KnightMiner** [comment]
Typo, 1.10 he means. 1.12 is still developed.

**Comment by EnergizedPhoenix** [comment]
Ok thank you for letting me know sorry about that.
