### ISSUE TITLE
Really Irritating Crash

### ISSUE THREAD

**Issue by WovenSpade** [SlimeKnights/TinkersConstruct#3131]
I crash every single time that I press shift while hovering over a tinkers part. I don't know if it is all parts, just know that it's the full pickaxes in creative menu and pickaxe head in creative menu. I don't really want to test as it's annoying. I'm playing with other mods aswell and it wasnt happening a while ago when i had less mods. Can't think of any that would interfere though.
Here is the report I got:
The game crashed whilst rendering item
Error: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemBlock

**Comment by KnightMiner** [comment]
Get the full crash reports uploaded to a site like pastebin and link it here

**Comment by KnightMiner** [comment]
Closing for lack of response.
