### ISSUE TITLE
whitelist dim ids for slime islands

### ISSUE THREAD

**Issue by resinate** [SlimeKnights/TinkersConstruct#3132]
i wanna make slime islands only generate in overworld. other mods like ultilty worlds create many dim ids and i dont want slime islands spawning in them.

would be nice thanks

**Comment by bonii-xx** [comment]
There already is a blacklist, you can simply blacklist a large batch of dimensions, since usually the IDs are simply increased by one for each new dimension.

**Comment by KnightMiner** [comment]
He might be referencing mods lie RF tools or Mystcraft that dynamically create dimensions. I'd argue they should keep vanilla behavior, but anyways.

**Comment by bonii-xx** [comment]
Yes, which usually create them in order. So if you blacklist 3-13 or something the first 10 dimensions wont have it. It's not like you have hundreds of dimensions.

**Comment by YaibaToKen** [comment]
One could still argue that being able to switch the blacklist into a whitelist shouldn't require a major code change whilst still allowing more fexibility in the system. Assuming one is running a server where players can create their own dimensions without a limit, blacklisting all the dimensions wouldn't exactly be feasible.

**Comment by DemonfangArun** [comment]
Another vote for this. Having to go through and ensure they don't spawn in worlds they shouldn't when adding mods and inevitably missing some is troublesome.

**Comment by TheAlchemist606** [comment]
I'd argue that not adding a whitelist option, which clearly wouldn't be that hard to do, is not only preferable but is obviously better than "just add a bunch of ids in advance lol." Come on, boni. That's lazy and you know it.

**Comment by ProxyPlayerHD** [comment]
I'm still for this idea because it makes much more sense than a blacklist

**Comment by KnightMiner** [comment]
Its also really easy for the mod adding the dimension to not get slime islands. The issue is mods are declaring their dimension as the overworld then not wanting overworld world gen. Especially in the case of RF tools, I would expect RF Tools overworlds to get slime islands

**Comment by YaibaToKen** [comment]
> Its also really easy for the mod adding the dimension to not get slime islands. The issue is mods are declaring their dimension as the overworld then not wanting overworld world gen. Especially in the case of RF tools, I would expect RF Tools overworlds to get slime islands

While I'm not trying to argue with your reasoning, and I do agree with it, this is actually not about who's doing the wrong thing but about giving more power to the user, and in that regard, allowing for a whitelist as well as a blacklist would make for quite a flexible experience.

As it is my understanding that the team does not feel worth it to invest time in this endeavor, would it be alright for me to submit a PR pertaining this request?

**Comment by bonii-xx** [comment]
The actual check is not hard to do. But it introduces unneeded complexity. It's better to have a way for mods to add their dimensions to the blacklist, but since they can be created at any time that's not so easy.

**Comment by YaibaToKen** [comment]
Is the level of complexity introduced that high or unbearable?

**Comment by bonii-xx** [comment]
It's better to not add complexity at all ;)

From a maintenance standpoint having the mods themselves take care of the blacklisting is the best option, which is why I'd chose that, if any.

**Comment by YaibaToKen** [comment]
No complexity is better than some complexity, I agree, but I have to wonder, if the trade-off, in this specific case, isn't worth it. Nonetheless, at the end of the day, it's still your call, and if you feel it's not fitting for TiC to handle it, I won't pursue the matter further :)

**Comment by ProxyPlayerHD** [comment]
>having the mods themselves take care of the blacklisting is the best option

thing is that not all mods do this, so having the ability to limit the island spawns manually is a very useful feature

>It's better to not add complexity at all

but why? especially when it seems so easy? technically you just need to invert the logic (if the conifg option has been set to whitelist instead of blacklist), doesn't seem like that much of a change/problem.

**Comment by bonii-xx** [comment]
The TL;DR would be that it creates a disproportionate amount of work in support/maintenance down the road compared to what it achieves.
