### ISSUE TITLE
Battle signs can't be placed

### ISSUE THREAD

**Issue by SlimeSignLover** [SlimeKnights/TinkersConstruct#3134]
Shift+right click does not place battle signs. I'm using AllTheMods3 3.0 Modpack, same with my friend on the same server. We made a green slime battle sign and neither of us can place it. It also wouldn't place in a single player game. I really want to have a slime sign for my slime castle 🏰 so I would like this issue to be seen to, thank you guys very much 😀

Edit: none of the battle signs can be placed, it is not just an issue with the slime.

**Comment by bonii-xx** [comment]
That is correct, the ability to place battlesigns wasn't reintroduced in the rewrite, effectively removing it. It probably wont come back either.
