### ISSUE TITLE
Smeltery output exceeds input when daisy-chaining casting tables and basins

### ISSUE THREAD

**Issue by Necrosapien** [SlimeKnights/TinkersConstruct#3137]
![2017-08-29_15 45 58](https://user-images.githubusercontent.com/31381047/29843340-48ff4e04-8cd1-11e7-88eb-406d031ee3b6.png)

When daisy-chaining casting tables, a player obtains more material than input into the smelter originally. In the example above, 1 ingot will output 6 ingots.

What appears to be happening is when the ingot is pulled out of the casting table by the hopper, it updates the drain, which is powered by the redstone block. This checks the table for the amount of material available, and begins casting it. Since the ingot has already been pulled from the table, but the casting begins before the value has been updated, it duplicates the ingot.

When done with basins, the behavior is a little different. Instead of casting an entire block, the basin only fills partially; with 1 ingot's worth of material. When using an ingot cast in one table, and a nugget cast below, a player will receive an extra nugget.

I believe the issue should be able to be fixed without affecting the way the drains update, which has been useful for automating the smelter using vanilla mechanics.

MC version: 1.11.2
Forge version: 13.20.1.2454

Edit: Confirmed the behavior still occurs in MC: 1.12.1 Forge: 14.22.0.2464

**Comment by bonii-xx** [comment]
Curious. I hope this is not a sync issue. Did you test it in singleplayer or on a server?

**Comment by Necrosapien** [comment]
This was tested in single player, originally so it doesn't seem to be a desync issue. Just ran a test on our server, which is running the 1.11.2 version, and confirmed the behavior in that environment also.

**Comment by bonii-xx** [comment]
OK, it looks like there is one frame when the casting finishes, where the casting table releases its liquid but didn't consume the fluid yet. In that frame, the faucet transfers the ingot worth of fluid out of the casting table, effectively duplicating it. Curious.

**Comment by Necrosapien** [comment]
Looks good! Trying to get a version for 1.11.2 compiled up now. :+1:

**Comment by Necrosapien** [comment]
Testing in 1.11.2 seems to yield the same behavior with the code changes. I can provide a copy of the compiled jar, as I may have done something incorrectly.

If my compiled code is not the problem, could it be something with TileFaucet since that is what is being interacted with the redstone block, or might this go back to how fluids are handled? I'm not super familiar with the interactions within Tinkers yet.

[TConstruct-1.11.2-2.7.1.DEV.GITBORK.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1271841/TConstruct-1.11.2-2.7.1.DEV.GITBORK.zip)
