### ISSUE TITLE
Tool forge issues?

### ISSUE THREAD

**Issue by HeathenScribe** [SlimeKnights/TinkersConstruct#3138]
When I place parts (smelted or otherwise) into the tool forge to create a tool, it shows that all parts are there but no model of the completed item appears in the right side of the tool forge. Is this a known issue in 1.11.2 or is it a conflict issue on my end?

**Comment by bonii-xx** [comment]
Screenshot please

**Comment by HeathenScribe** [comment]
![screenshot 12](https://user-images.githubusercontent.com/31530707/29964184-e0524154-8ece-11e7-9b8b-209c141f7a0e.png)

**Comment by HeathenScribe** [comment]
![screenshot 15](https://user-images.githubusercontent.com/31530707/29964279-292a1d02-8ecf-11e7-98e4-100d2fde15f3.png)

**Comment by bonii-xx** [comment]
Mhm, I remember an issue where another mod was interfering with that.

**Comment by KnightMiner** [comment]
Closing for lack of response.
