### ISSUE TITLE
Long/Crossbow only shoots in 45 degree increments

### ISSUE THREAD

**Issue by Magnymbus** [SlimeKnights/TinkersConstruct#3140]
Original Post @ 2:40PM MT Sept. 2nd, 2017:
For clarification, When facing a multiple of 45 degrees (N, NW, W, etc.) the long/crossbow shoots as expected, but the further away from those you face, the more off to the side the arrow flies. This does not happen with the shortbow, and may be a mod conflict. I will add more information soon after I test with just TCon. Screenshots soon.

EDIT 1 @ 2:49PM MT Sept. 2nd 2017:
New discovery: Only happens with full power shots (when you get particles) when using the longbow.

EDIT 2 @ 3:00PM MT Sept. 2nd, 2017:
Confirming that this occurs with only Forge, Mantle and TCon.

EDIT 3 @ 3:12PM MT Sept. 2nd 2017:
Added Screenshots

Normal Shot
![arrow trajectory 01](https://user-images.githubusercontent.com/14867244/29998789-1f736ac0-8ff1-11e7-977a-56f1eacdbb57.png)
Normal Shot

-33 degrees
![arrow trajectory 02](https://user-images.githubusercontent.com/14867244/29998790-1f74753c-8ff1-11e7-9951-32b8a4650e63.png)
-33 degrees

-53 degrees
![arrow trajectory 03](https://user-images.githubusercontent.com/14867244/29998792-1f7849be-8ff1-11e7-99be-4bdefe647083.png)
-53 degrees

45 degrees
![arrow trajectory 04](https://user-images.githubusercontent.com/14867244/29998791-1f780a4e-8ff1-11e7-9063-f323ddb44a55.png)
45 degrees

**Comment by Magnymbus** [comment]
New discovery: Only happens with full power shots (when you get particles) when using the longbow.

**Comment by Magnymbus** [comment]
Confirming that this occurs with only Forge, Mantle and TCon.

**Comment by KnightMiner** [comment]
Does this affect just our arrows, or also vanilla arrows? Also, please post mod versions from that test

**Comment by bonii-xx** [comment]
This only happens with vanilla arrows, due to how vanilla arrows work, TiC arrows have a fix. It's a vanilla bug that happens when arrows travel faster than when being shot by a vanilla bow.

**Comment by bonii-xx** [comment]
This is a purely visual issue, the arrows still land where you shot them, they just display incorrectly. If you check where the arrow lands you'll see that they're where you aimed. Vanilla networking issue, can't be fixed by us.
