### ISSUE TITLE
Material traits of the offhand sign are not working.

### ISSUE THREAD

**Issue by UghZug** [SlimeKnights/TinkersConstruct#3142]
Our servers build is old so this might have already been addressed but here's info

Minecraft version 1.10.2
Tinkers' Construct version 2.6.5
Forge version/build, unsure, at least 4 months if not older
Versions of any mods potentially related to the issue
tinker's tool leveling 1.0.1 ?
PlusTic 4.4.0.0

So the issue, have a sign in my offhand made of lumium sign and ardite tool rod, which gives glowing, illuminati, and petramor.  while in the offhand slot using a weapon or tool that supports offhand, or rather doesn't say otherwise, the traits of the offhand are not working... i am not invisible, and no free lights are spawning in dark areas from the offhand.  did not confirm if the petramor is working either.

**Comment by KnightMiner** [comment]
We don't add lumium as a material. Verify this is such happens with just our materials and modifiers (so remove any TiC add-ons)

**Comment by Landmaster** [comment]
@UghZug Also, you are using an outdated version of my Tinkers addon mod, PlusTiC. Update to 5.2.1.2 or later.

**Comment by KnightMiner** [comment]
Closing as a non-Tinkers Construct issue as that material is not part of TiC vanilla, and, as Landmaster mentioned, you are using an outdated version of the addon.
