### ISSUE TITLE
Crash with ArmorPlus mod

### ISSUE THREAD

**Issue by Gerudopuff119** [SlimeKnights/TinkersConstruct#3147]
[crash-2017-09-06_18.12.08-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1283187/crash-2017-09-06_18.12.08-client.txt)

Crashing with the latest update of Tinkers Construct when used with the ArmorPlus mod. still works with 2.7.2.19

**Comment by Gerudopuff119** [comment]
Crashes on game startup*

**Comment by KnightMiner** [comment]
This is on ArmorPlus's side, they were probably using something outside of the library in their Tinkers integration. Report to them.
