### ISSUE TITLE
Crash with armor+

### ISSUE THREAD

**Issue by sefldron** [SlimeKnights/TinkersConstruct#3148]
During startup armor plus and TC both have a modifier named Firestorm. Armor plus throws the exception while tcon api tries to register the conflicting modifier. Uploading the crash to paste bin. Will link in a few.

**Comment by sefldron** [comment]
https://pastebin.com/5geXtrCZ

CR on PB (a digital sandwich?)
Sorry couldn't help myself

**Comment by sefldron** [comment]
Info: turning off ap tc integration fixes the crash

**Comment by bonii-xx** [comment]
This comes from a fix in the TiC API. ArmorPlus has the same issue as TiC had. They need to fix it on their side.
