### ISSUE TITLE
[1.12.1] Server Crash: [TCon API] Trying to register

### ISSUE THREAD

**Issue by HendrikJ79** [SlimeKnights/TinkersConstruct#3149]
Not sure if it is a TConstruct crash or from Ex Nihilo Creatio

[OpenEye Log](https://openeye.openmods.info/crashes/a0f26ba7c94c0a82438ab48966a495eb)
[Total Crash Log](https://gist.github.com/HendrikJ79/9ac5efc0c1c71bd96dd0d7da9d793962)

**Comment by KnightMiner** [comment]
This is caused by Ex Nihilo Creation. They are registering the same modifier twice it seems.

**Comment by bonii-xx** [comment]
It's caused by how our modifiers work. We just fixed that you can't overwrite them. The problem is we can't change how they work without silently breaking things even more, heh.

**Comment by BloodWorkXGaming** [comment]
Alright, thanks, found the issue ^^
Was due to the modifier registering itself in the super call but also being registered by this call later `TinkerRegistry.registerModifier(smashingModifier);` I am guessing multiple mods are running into this issue with the latest version?

**Comment by bonii-xx** [comment]
Yes. It's actually quite hard to find all implicit modifier registrations, but we needed to detect all duplicate registrations. Removing the implicit registration would probably cause some modifiers to silently vanish. This way it crashes at least ;o
