### ISSUE TITLE
Smeltery Drain nomenclature

### ISSUE THREAD

**Issue by Leowbattle** [SlimeKnights/TinkersConstruct#3150]
Please tell me if this is the wrong place for a suggestion or how I can make an edit suggestion without forking.

The smeltery drain should be renamed the "seared drain" since it is now also used in the Tinker Tank. This would fit with the nomenclature of other blocks like "seared brick" and "seared guage".

**Comment by bonii-xx** [comment]
I see your point, but for the sake of new players the naming is better as is. If you search for "smeltery" in JEI all the crucial parts of the smeltery should pop up.
