### ISSUE TITLE
[1.12.1] Server crash when using lumber axe  (SpongeForge server)

### ISSUE THREAD

**Issue by kwpugh** [SlimeKnights/TinkersConstruct#3156]
Forge: 2479
SpongeForge:  2624 for forge 2479
Tinkers:  2.7.3.30
Mantle:  1.3.1.21

Server crashes as log breaks using a lumber axe on any treee

Report: https://gist.github.com/kwpugh/ad76b47e4a3628c3126b41baf513ac17

**Comment by KnightMiner** [comment]
Does this happen with a normal Forge server? We do not support sponge forge as it has caused many issues in the past, so if it only happens on sponge report to them.

**Comment by kwpugh** [comment]
ok, with sponge disabled, it does not crash.  Thanks anyway.

**Comment by kwpugh** [comment]
I opened the issue to Sponge.
