### ISSUE TITLE
[1.10.2] Crafting Station Closes on Any Block Update

### ISSUE THREAD

**Issue by Starwort** [SlimeKnights/TinkersConstruct#3158]
Pretty much as in the title. I downloaded the latest release of tinkers' construct today, and every time it gets updated (e.g. by the furnace next to it) it closes the GUI.

**Comment by Landmaster** [comment]
If I recall correctly, 1.10.2 is no longer supported. Try reproducing with only Mantle and Tinkers Construct.

**Comment by KnightMiner** [comment]
Closing for lack of response and as I have never experienced this myself.
