### ISSUE TITLE
Block Update slowed

### ISSUE THREAD

**Issue by citizen-cove** [SlimeKnights/TinkersConstruct#3160]
So one issue that I keep running into is with mining blocks. The entire game runs really slow for starters, and I can't seem to do anything about it no matter what I do. I'm running updated versions of everything. The most recent versions of forge, the most recent versions of the mods, all of that. But no matter what I do. The block updating for mined blocks doesn't take. usually after about five blocks, the game gives up and stops updating, usually followed by a crash, and it's always with just tinkers in it.

**Comment by KnightMiner** [comment]
Okay, for starters there is no "most recent version". Give exact version numbers.

If it's going slow, game logs might help (post them on a site like pastebin) and if it crashed, a crash report (post on same site and link here)

**Comment by KnightMiner** [comment]
Closing for lack of response. If would like to reopen, please give exact versions and game logs.
