### ISSUE TITLE
Refilling Bolts?

### ISSUE THREAD

**Issue by Plurp13** [SlimeKnights/TinkersConstruct#3161]
I can't seem to refill my crossbow bolts. You used to be able to and the book doesn't really say anything about so I'm unclear if you're just supposed to craft more bolts every time or I'm doing something wrong.

**Comment by KnightMiner** [comment]
How are you trying to refill them? It should work to repair them like a normal tool.

Also, while figuring this out, what version are you using, and have you tried repairing arrows as well?

**Comment by Plurp13** [comment]
I tried using the stuff I coated the stick in, I tried using the stuff the stick was made of, and I tried making a new bolt part and using that, nothing worked. Maybe it has something to do with using the demon metal from EU2? I haven't made arrows yet so I haven't tried refilling them, also I updated today so I'm guessing I'm using the most recent version.

**Comment by bonii-xx** [comment]
Then demon metal has a faulty integration and doesn't add the ingots to the material. XU2 bug.

**Comment by pie-flavor** [comment]
In case anyone cares, you can use the shard still to save on materials.
