### ISSUE TITLE
"Materials and You" page and tooltip text goes out of bounds of container

### ISSUE THREAD

**Issue by Winseven4lyf** [SlimeKnights/TinkersConstruct#3163]
The text in the guide book's pages and tooltips go outside their respective container/are offset.

Pictures here: https://imgur.com/a/YFw0S

MC 1.12.1, Optifine, Mods:
+ AppleCore 2.2.2
+ AppleSkin 1.0.8
+ AutoRegLib 1.3 13
+ Ceramics 1.3.2
+ Chameleon 4.1.3
+ CookingForBlockheads 6.3.6
+ FarmingForBlockheads 3.1.5
+ FastLeafDecay 14
+ hopperducts 1.5
+ ImmersiveEngineering 72
+ immersivepetroleum 1.1.3
+ InventoryTweaks 1.63+beta.108
+ ironchest 7.0.31.818
+ jei 4.7.8.92
+ journeymap 5.5.0b3
+ JustEnoughResources 0.8.4.25
+ Mantle 1.3.1.21
+ OpenComputers 1.7.0.4
+ OptiFine HD U C5
+ Pam's HarvestCraft 1.12.1c
+ ProjectE PE1.1.0
+ Psi r1.1 52
+ redstonepaste 1.7.5
+ SpiceOfLife 1.3.10
+ StorageDrawers 5.3.2
+ TConstruct 2.7.3.30

**Comment by KnightMiner** [comment]
Remove Optifine.

**Comment by Winseven4lyf** [comment]
It is indeed Optifine, turning Custom Fonts off doesn't fix it.

**Comment by Dimentive** [comment]
@KnightMiner Do you think that compatibility with OptiFine could ever be added to Tinkers’ Construct? I can’t play without OptiFine, as OptiFine heavily improves my frame rate and solves my stuttering and micro-stuttering.

Or is this strictly an OptiFine issue?

**Comment by SweetSugarSugar** [comment]
@Dimentive Their code is closed source.

**Comment by Dimentive** [comment]
@SweetSugarSugar I forgot about that. It’s truly a shame. I bet most of the glitches caused by other mods when OptiFine is installed could easily be fixed if OptiFine were open-source. OptiFine would also likely improve at a quicker rate since people could provide pull requests and ideas for improvements to the code in general.
