### ISSUE TITLE
Rendering issue (aesthetic)

### ISSUE THREAD

**Issue by sefldron** [SlimeKnights/TinkersConstruct#3165]
(oops submitted before typing disc) constantan fluid does not render in world when draining or inside smeltery. Drains properly and casts items fine but renders invisible. I will fill a bucket with it and check if it's only with smeltery.

**Comment by sefldron** [comment]
This is with all newest versions of 1.12.1 version of thermal and tic

**Comment by sefldron** [comment]
Could be a thermal issue. I will inform them as well. Cannot pour into the world either.

**Comment by KnightMiner** [comment]
This is not a Tinkers Construct error, though if I had to guess (which I will have to as you failed to provide screenshots of your render issue), this comes down to the Forge bug when a new mod adds a fluid formerly defaulted by another mod (you likely have IE as well).
