### ISSUE TITLE
Please Add config option for old style chest layout

### ISSUE THREAD

**Issue by LKHSogpit** [SlimeKnights/TinkersConstruct#3167]
This is pretty basic not sure why you would want to change it in the first place as it worked perfectly. But the way the crafting station and chest interaction worked in 1.7.10 is really needed as a config option. If not at the very least being able to set the chest rows and columns in the config would be very much appreciated. 

A crafting station next to a barrel from ex nihilo picks the barrel inventory up sometimes also a config to disable that would be nice along with a config to disable the stupid furnace inventory or just all other inventories besides chests. Seriously though why is there a scroll bar on a 6x9 chest. Also the way Shift clicking works in 1.10.2 and up is a pain if possible I would like to shift click into a chest that is being picked up by the CS the way we have being doing it since the beginning of time.

Please if there is anyway to add these options into the config I know I will use them and a lot of others too who I can't speak for! If there is any mods that add these features I would use them in all packs as a necessity!

**Comment by bonii-xx** [comment]
The crafting station is designed to support ALL inventories. Hence you see everything that exposes its inventory. It will not be limited to chests only. You have always been able to shift click into the crafting station, and for every request to change it from X to Y, you get just as many requesting to change it from Y to X. It is consistent as is and will stay that way.

**Comment by KnightMiner** [comment]
Also, I should mention there is a config to blacklist specific tile entities using the class names, we just don't do most of the ones you mentioned by default. You can manually remove the ones you dislike

**Comment by LKHSogpit** [comment]
@bonii-xx Hence why I am suggesting a config option for the old style chest layout. The chest has 6 columns and 9 rows when it is being picked up by the CS it should be the opposite way around 9 columns and 6 rows. You can't please every one no but you don't have to when the option is there by an editable config. It is understandable having a scroll bar on a bigger inventory like an iron chest but on a double chest it just doesn't need need to be there imo, it slows you down for early game crafting.

@KnightMiner Good to know...
