### ISSUE TITLE
Glitch with Cobalt Hammer

### ISSUE THREAD

**Issue by jka249** [SlimeKnights/TinkersConstruct#3168]
I have come across a glitch when using a cobalt hammer (momentum) on netherrack
when using a hammer on the netherrack it will only destroy 1 block at a time and not the 3x3, 3x5 etc, 

The Tool i used to create this error was cobalt hammerhead, 1 obsidian plate, Knightslime handle and knightslime plate, 
modifiers : Forified (Obsidian), Haste 1, Luck 3 and width ++

Modpack was FTB Beyond

Thank you for your time.

**Comment by bonii-xx** [comment]
Thanks for the report, try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by KnightMiner** [comment]
Closing for lack of response. If you still believe this is an error please post the required information.
