### ISSUE TITLE
IMC API for adding custom seared blocks

### ISSUE THREAD

**Issue by asiekierka** [SlimeKnights/TinkersConstruct#3169]
Would be handy for Unlimited Chisel Works.

Requires being able to define valid smeltery blocks in general (there's a Set for that), as well as defining what blocks are seared bricks specifically (for the floor; hook into MultiblockSmeltery.isFloorBlock)

**Comment by KnightMiner** [comment]
I'm not sure how feasible this is through IMC as they also need to use [TileSmelteryComponent](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/smeltery/tileentity/TileSmelteryComponent.java) to function as a multiblock component for the sake of updating.

**Comment by asiekierka** [comment]
@KnightMiner Unless the relevant multiblock data was made into a capability, but I think that's a bit of a tall order for what is essentially decorative blocks.

**Comment by bonii-xx** [comment]
Sorry asie, but we don't allow the extension of valid smeltery blocks on purpose. (And as Knightminer said, it would cause inconsistencies and sporadic bugs if they don't have the TE)

**Comment by asiekierka** [comment]
Aww.
