### ISSUE TITLE
[1.12] massive fps drops while JEI displays Tinker items

### ISSUE THREAD

**Issue by Thyriel** [SlimeKnights/TinkersConstruct#3171]
As mezz (JEI) thinks that the problem lays somewhere in Tinkers and not JEI:
I'm getting fps drops while viewing certain Tinker Construct items in JEI down from >100 fps to like 5-10 fps (so it's becoming hard to even click anything).
See Screenshot: (i tried to pin it down to which items cause it, but seems to come from a lot of different Tinker Items)
https://imgur.com/a/LztHO

On the previous JEI Page (all Tinker too) the fps drop is not as massive, but still going down to 40-50, same on the next page. This (drop to 40-50) is happening with quite some other mods too, but only the page in the screenshot is dropping the fps so much that it's becoming hard to control the mouse.
This is happening regardless if i use only the bare minimum of mods (JEI, TConstruct, Mantle, Hwyla) or with a lot more mods. No optifine or other fps related mods used.

Tinker Version: 2.7.3.3.30
MC: 1.12.1
JEI: 4.7.10.98
Mantle: 1.3.1.21
Forge: 14.22.1.2485
Link to issue i posted earlier at JEI: https://github.com/mezz/JustEnoughItems/issues/997

**Comment by bonii-xx** [comment]
Tinkers items are complex. It's neither JEI nor TiC, it's simply.. a lot of stuff to render at once while item rendering is really slow in general.

**Comment by Thyriel** [comment]
ok, but certain items reducing perfomance by 99% while most others only reduce it by 50% is a bit strange tho

**Comment by bonii-xx** [comment]
Certain items don't. 540 of them at the same time do.
