### ISSUE TITLE
Optifine makes textures invisible

### ISSUE THREAD

**Issue by xToastGhost** [SlimeKnights/TinkersConstruct#3172]
whenever i load optifine with tinkers construct it makes most of the textures invisible. please help

**Comment by AUTR1UM** [comment]
I've been having that occurrence too. I do not know what the problem is either. Could try to install a different Optifine?

**Comment by AUTR1UM** [comment]
Or I could just leave it out and deal with it? vice versa.

**Comment by KnightMiner** [comment]
Or, you could just update as this issue has been fixed for over a month in Optifine.

**Comment by Tahakk** [comment]
I can even remember it out of my head: -> there you go #3008
