### ISSUE TITLE
[1.12] Unbreakable pickaxe not able repair

### ISSUE THREAD

**Issue by GQuan1975** [SlimeKnights/TinkersConstruct#3173]
Unbreakbale pickaxe (5x reinforcement, tool rod is from magical wood) is broken. I suppose it's due to "Magical Brittle" from magical wood. But it's not possible repair this tool with any material used in this pickaxe.

**Comment by bonii-xx** [comment]
The materials used are probably missing integration then. What materials did you use for the pickaxe head?

**Comment by GQuan1975** [comment]
It's Manyullyn pickaxe, before it's full reinforced, i can repair it.

**Comment by GQuan1975** [comment]
Problem is in TinkersItem.java row 352

**
    // now do it all over again with the real items, to actually repair \o/
    ItemStack item = repairable.copy();

    while(item.getItemDamage() > 0) {
      int amount = calculateRepairAmount(materials, repairItems);

      // nothing to repair with, we're therefore done
      if(amount <= 0) {
        break;
      }

      ToolHelper.repairTool(item, calculateRepair(item, amount));
      // save that we repaired it :I
      NBTTagCompound tag = TagUtil.getExtraTag(item);
      tag.setInteger(Tags.REPAIR_COUNT, tag.getInteger(Tags.REPAIR_COUNT) + 1);
      TagUtil.setExtraTag(item, tag);
    }
**

repairing is in while, where checking only damage, but my pickaxe have no damage, only is mark broken  by Magically Brittle

**Comment by laz2727** [comment]
Well, if the mod can break a tool without actually damaging it, that's
technically their bug since it's impossible with only TiC.

**Comment by bonii-xx** [comment]
Then it's a bug in magical brittle. Tools being broken with durability is an invalid state. Please report to tema.

**Comment by laz2727** [comment]
Hmm. I wonder, is it possible to repair the tool with moss/wood trait and keep it broken? It was possible in 1.7.10.

**Comment by KnightMiner** [comment]
2230ba2 should make tools which are broken with no damage repairable again.

Extra Utilities still needs a more proper way to break the tools. The best way is probably just them calling `stack.setItemDamage(stack.getMaxDamage())`. I cannot easily make `ToolHelper.breakTool()` as `ToolCore.damageItem()` calls `breakTool()`.
