### ISSUE TITLE
Tinker's weapons have one quad per pixel and repeat them 7 times

### ISSUE THREAD

**Issue by mezz** [SlimeKnights/TinkersConstruct#3176]
Most items seem to have one quad, the face.
Tinker's seem to have one quad per pixel in the image.
Compounding this issue, the items use Mantle's `BakedSimple` which gives the same quads for all 6 sides and the null side.

This makes rendering these items extremely slow, enough to bring JEI to its knees without some aggressive optimizations. I ended up looking into this in hopes of removing some optimizations from JEI that are causing minor compatibility issues. It seems like the fixes here should be relatively straightforward and the issues were just not noticed before.

**Comment by bonii-xx** [comment]
Huh, now that's really weird. As far as I'm aware we only have one quad per face too, and I don't know what would cause them to have 1 per pixel (unless forges internal stuff does something weird). The side thing I can see, probably some simplification. Which side do vanilla items use normally?

**Comment by mezz** [comment]
When I have (for example) an ardite broadsword in my inventory and put a breakpoint in `BakedSimple#getQuads`, I see there are 120 quads and it returns them for all sides.

If I do the same with a diamond pickaxe, I get to `ItemLayerModel.BakedItemModel#getQuads` which only returns quads for the "null" side and only has 1 quad.

**Comment by mezz** [comment]
I haven't really looked into it further than that. I had kind of a hard time following your render flow since it's pretty complicated with the compound parts so I stopped there. I hope that's enough information! :)

**Comment by bonii-xx** [comment]
It's definitively a starting point for an issue I never thought would have existed. It's possible that some model things also changed between early 1.8 and 1.12. The side thing definitively sounds wonky and I can't explain the 120 quads either. Thanks for the info, at least we know why TiC tools are so slow in JEI now, even though there's optimizations in place in both mods.

**Comment by bonii-xx** [comment]
>I see there are 120 quads and it returns them for all sides.

I think that's normal, due to the items having "depth", which means each transparent<->solid edge has one quad for the depth part. TiC tools have a bit more because of overlapping models of the different parts.

The sides thing seems to have a huge impact though.

**Comment by mezz** [comment]
Hmm. Bee items are made up of 3 semi-overlapping layers and use `ItemLayerModel.BakedItemModel` defined in JSON, but I just checked and they only have 3 quads.

**Comment by bonii-xx** [comment]
Yes, the json models don't have them defined, they're generated by `ItemLayerModel.generateQuads` when the models are getting baked. All itmes have them. I don't think they're split up by side either.

**Comment by mezz** [comment]
To confirm what you said, it looks like lots of quads are generated by  `ItemLayerModel#getQuadsForSprite` because of the side quads.

Thing is, we don't need side quads for the inventory rendering at all.
If I just turn ` addSideQuad` into a no-op then I get item models for Tinker's that look right and only have around 10 quads.

Looking deeper into it, this issue was brought up here: https://github.com/MinecraftForge/MinecraftForge/issues/2326
And fixed in forge here: https://github.com/MinecraftForge/MinecraftForge/commit/f42137907e0a87adf1522fded5827086fc0b13f2

Maybe forge's baked model has an optimization here that your custom one is missing?

**Comment by mezz** [comment]
Looks like the optimization is only choosing quads with `if(quad.getFace() == EnumFacing.SOUTH)`, I guess those are the ones facing the camera.

**Comment by bonii-xx** [comment]
Hm, not sure. However that sounds really weird.. if I did that, then the model would have missing quads everywhere where it's used that's not in the inventory? (aka any block that renders items)

**Comment by mezz** [comment]
The magic is in `IBakedModel#handlePerspective`, it gives the culled model when the perspective is `type == TransformType.GUI` and the normal one otherwise.

**Comment by bonii-xx** [comment]
Ah. Yeah I don't think TiC uses that, due to having its own handling there for the different materials. I suppose that could give a noticable boost too.

Btw with the sides-issue fixed the quad count dropped so much that I don't even get any slowdown anymore in JEI. :D

**Comment by mezz** [comment]
Very nice :). 
I'll poke at this extra stuff a bit and possibly make a PR since I finally understand what's going on.

**Comment by bonii-xx** [comment]
Will probably require a fix in BakedWrapper.Perspective in Mantle

**Comment by mezz** [comment]
Alright got the PR in. It ended up being Tinker's fix since I needed to change the logic in `BakedSimpleItem`. It might be worth moving the class into Mantle some time later.

**Comment by bonii-xx** [comment]
:ok_hand: cool that you found it. Looks quite simple too. Now I can tell everybody who complains about performance in 1.10 that they, too, shall update to 1.12. Just like all the other people complaining over long fixed things. :stuck_out_tongue_winking_eye:

**Comment by KnightMiner** [comment]
Is this entirely fixed through that PR, or are we leaving this open as a reminder to move the class into Mantle?

**Comment by mezz** [comment]
This is entirely fixed. 
If this Forge PR is accepted https://github.com/MinecraftForge/MinecraftForge/pull/4435 then there will be a public `BakedItemModel` in forge you can use, instead of copying it to `BakedSimpleItem`.

**Comment by bonii-xx** [comment]
Again, <3
