### ISSUE TITLE
 [1.11.2] About the specification of Mattock [bug?]

### ISSUE THREAD

**Issue by karikusa** [SlimeKnights/TinkersConstruct#3177]
Hello!
It is one of the crafters enjoying TCON!
Recently I made Mattock,
Although logging of logs seems to be no problem,
For some reason drilling of sand, gravel and soul sand,
It seems to be the same as when it is sampled with bare hands.
Is the explanation incorrect?

Postscript: Because I am using a translation site, I hope to accurately convey it ...

**Comment by bonii-xx** [comment]
Very melodic, your translation site. The reason is that a mattock is not a shovel. It is effective against dirt, but not sand and the like.
