### ISSUE TITLE
Unable to join server

### ISSUE THREAD

**Issue by tyler489** [SlimeKnights/TinkersConstruct#3179]
seems that tconstruct is trying to send me player packets before i spawn in 100% causing me to be unable to join the server https://pastebin.com/WLpe18an

**Comment by KnightMiner** [comment]
Going to need more information than that, specifically full game logs. I have never seen this issue before, but even from your selection Tinkers is not the only mod erroring, its actually erroring the latest making me assume another mod is messing with the world load order.

**Comment by tyler489** [comment]
actually figured out what was causing me not to join the server was the beneath mod. dont know why or how.

**Comment by KnightMiner** [comment]
In that case, I would report this to the Beneath mod issue tracker with your full game log so they can hopefully figure it out. Just make sure you have the latest versions of that mod and Forge first
