### ISSUE TITLE
1.12 stencil table and part builder aren't craftable

### ISSUE THREAD

**Issue by ravensourcious** [SlimeKnights/TinkersConstruct#3181]
I am playing 1.12 using 1.12-2.7.3.30 and the stencil table and part builder are not craftable and don't show up in JEI, the are in the creative inventory but there's no way to craft then. I'm currently using FTB 1.12 Unstable and thought the mood pack read the problem, but I tried paying with a fresh install of thinkers and nothing else and had the same problem

**Comment by bonii-xx** [comment]
No, that definitively works. Try deleting your config folder and redownload TiC, Mantle (and JEI) and put only those mod in, nothing else.

**Comment by ravensourcious** [comment]
Thanks, I have it now, error with JEI.
