### ISSUE TITLE
1.11.2 overworld ores not generating

### ISSUE THREAD

**Issue by TheTobiathan** [SlimeKnights/TinkersConstruct#3183]
I recently started a modded world with just tinkers construct. I'm familiar with the mod from a few FTB mopacks, and wanted to try playing with just tconstruct. None of the ores spawning at all, and the Materials and You book doesn't update at all. They don't show up in creative mode either. Here is what I have installed modwise. 
![2017-09-30_06 38 34](https://user-images.githubusercontent.com/32414217/31045911-7533ce80-a5ab-11e7-8a93-01b12e23b0dc.png)

I've looked all over the interwebs to try and solve this exact issue to no avail. AAny help here would be hot.
Thanks :3

**Comment by KnightMiner** [comment]
There are no over world ores, read the FAQ, or maybe the contributing guidelines from the top of posting an issue.
