### ISSUE TITLE
[1.12.1] Weird texture problem missing lock icons in some positions of drawers

### ISSUE THREAD

**Issue by mcdodge34** [SlimeKnights/TinkersConstruct#3184]
I had to record a video of it since its hard to explain, the icons we can see on a drawer (lock and others) aren't showing up when I place the drawers down at a certain position, I also tested it without my texture pack and the bug is still there, so there's something going on, I have 0 idea what could cause this issue exactly, the lock is still applied, but we don't see it.

https://youtu.be/hwci5B9O8D4

**Comment by KnightMiner** [comment]
This issue tracker is for Tinkers Construct, report the issue to Storage Drawers as that is where those blocks are from.

**Comment by mcdodge34** [comment]
I'm an idiot, sorry about this, time to drink more coffee, seems I'm not awake this morning.

**Comment by bonii-xx** [comment]
We have had a few reports for other mods so far, it's rare but it happens more than one would think. ;P
