### ISSUE TITLE
Advancements for the mod ?

### ISSUE THREAD

**Issue by fflortix** [SlimeKnights/TinkersConstruct#3185]
Can you add advancements for your mod, i'ts very funny and I like your mod !!!

**Comment by bonii-xx** [comment]
It would be fun for sure, but it's not a major thing to do, and therefore has no priority. We hardly have time for things, so it sadly wont be implemented. Maybe someday somebody wants it so badly that he PRs it in.

**Comment by laz2727** [comment]
I'll try it tomorrow if I remember.

**Comment by DEViANCEVxXXxM** [comment]
we stell dont have advancements :C
