### ISSUE TITLE
1.12.2 Tinker pickaxe doesn't work on Factory Tech ore blocks

### ISSUE THREAD

**Issue by LordHellscream** [SlimeKnights/TinkersConstruct#3186]
Forge 2501
Minecraft 1.12.2
Tinker Construct  TConstruct-1.12-2.7.3.30

Tool:
stone head, green slime binding, bone rod.
modifier : haste x 1 , silk touch.

Blocks:
All ore blocks from Factory Tech mod.

Problem:
When using tinker pickaxe on a Factory Tech ore block (say Copper ore), it doesn't do anything at all.

**Comment by bonii-xx** [comment]
Then the factory tech mod blocks are not flagged correctly as being harvestable by pickaxes. PRobably an oversight in the mod. Please report it to the mod author.
