### ISSUE TITLE
[1.12] Alloying consuming metals

### ISSUE THREAD

**Issue by Zedrimar** [SlimeKnights/TinkersConstruct#3188]
Not sure how to say this but I found that when alloying, say ardite and cobalt for manyullyn, it only gives the amount of one ingredient. What I mean is, if you have one ingot of ardite and one ingot of cobalt, you only get one ingot of manyullyn rather than two like before. Is this a new thing or an actual bug?

Pics: 
![image](https://user-images.githubusercontent.com/8153290/31311170-47b1b368-ab5b-11e7-89b6-d15edc412f38.png)

![image](https://user-images.githubusercontent.com/8153290/31311166-3f11d97c-ab5b-11e7-890b-c3d4e7622990.png)

![image](https://user-images.githubusercontent.com/8153290/31311165-32f4206e-ab5b-11e7-9da4-184a79daaa31.png)

**Comment by KnightMiner** [comment]
That has been the case since 1.7. Not a bug.

**Comment by Zedrimar** [comment]
hmmm... guess I wasn't paying attention, sorry about that
