### ISSUE TITLE
[1.12.2] Scythe crashes client on attack

### ISSUE THREAD

**Issue by Thyriel** [SlimeKnights/TinkersConstruct#3189]
Only happens with scythe attacking something

pastebin: https://pastebin.com/B1NqBNXJ

**Comment by KnightMiner** [comment]
I believe this is on Mob Amputation's side as they are calling the method to attack an entity within the method atttacking an entity calls. See [this line](https://github.com/iChun/Mob-Amputation/blob/master/src/main/java/me/ichun/mods/mobamputation/client/entity/EntityGib.java#L375).

@iChun: can you share a bit of information on that line?

**Comment by iChun** [comment]
I thought I fixed this... Can you share the stack trace? It's a mob
amputation issue.

**Comment by bonii-xx** [comment]
Didn't we have the exact same issue a few versions back? :smile:

**Comment by iChun** [comment]
That's why I thought I fixed this

**Comment by KnightMiner** [comment]
Stack trace is linked in the original issue

**Comment by KnightMiner** [comment]
@iChun any update?

**Comment by iChun** [comment]
Wait, I haven't fixed this yet? Whoops!

I can only get to it in January though sadly. I think it'd be better to
make an issue over in my repo rather than here.

**Comment by KnightMiner** [comment]
I'm going to close this issue as we have determined it to be a bug with Mob Amputation and it is reported to their tracker.
