### ISSUE TITLE
Tinkers' Hammer

### ISSUE THREAD

**Issue by ANNOYEDCHERRY** [SlimeKnights/TinkersConstruct#3190]
The AOE does not affect monster eggs the bounding boxes that now show in the 1.8+ versions does not render on monster egg blocks. Tested with both AA drill and Tinker's Hammer and the AA drill breaks all blocks in 3x3 AOE hammer does not (When monster egg is present) Test occurred on my stream today at 4pm www.twitch.tv/annoyedcherry_13

**Comment by KnightMiner** [comment]
Dragon eggs cannot normally be mined with a pickaxe, the hammer only applies AOE to tools that can be mined using a pickaxe.

**Comment by ANNOYEDCHERRY** [comment]
I am not talking about dragon eggs I am talking about monster eggs you know the block that spawns silverfish when you break it.

**Comment by KnightMiner** [comment]
Sorry, misread that, but its the same case. Monster eggs do not break faster with a pickaxe so the hammer does not work on them.
