### ISSUE TITLE
[1.12.2] Possible IMC Issues

### ISSUE THREAD

**Issue by ReverseStateMonad** [SlimeKnights/TinkersConstruct#3192]
I posted this to the CoFH Issues github (https://github.com/CoFH/Feedback/issues/579), and KingLemming says that the problem may be on your end, so I'm reposting it here.

Forge Version 1.12.2 14.23.0.2491

Mod List:
CodeChickenLib 1.12 3.1.3.313
CoFHCore 1.12 4.3.5.13
CoFHWorld 1.12 1.0.1.8
Mantle 1.12 1.3.1.21
RedstoneFlux 1.12 2.0.1.2
TConstruct 1.12 2.7.3.30
ThermalDynamics 1.12 2.3.5.12
ThermalExpansion 1.12 5.3.5.19
ThermalFoundation 1.12 2.3.5.14

Additional Mods:
CraftTweaker2 1.12 4.0.8
MTLib 3.0.0
ModTweaker 4.0.3

There seem to be some issues with the Tinkers Construct plugins for Thermal Foundation/Expansion and the liquid alloys registered therein.

Reproducible with the mods in the first list:
1. Although the liquids for these alloys (Invar, Constantan, etc.) are present in the game and can be produced in the Magma Crucible, they cannot be produced in the Smeltery, either by melting (e.g. invar blend gives the "Item cannot be molten" message) or by alloying (e.g. molten iron and molten nickel do not combine into molten invar).

2. There are no casting recipes for these alloys.  Once you have acquired them (via creative mode or the Magma Crucible), they can only be stored or destroyed, not used.

With the addition of the mods in the second list:
3. Attempting to add a recipe using Craft Tweaker that involves one of these liquid alloys fails, with an error such as "Could not resolve <liquid : invar>".  Using the "/ct liquids" command to generate a list of registered liquids does show the liquid alloys in the list.  Replacing the alloy with another liquid such as <liquid:water>, or even a liquid added by Thermal Foundation outside of the Tinkers Construct plugin such as <liquid:redstone> succeeds.

**Comment by KingLemming** [comment]
Okay, did some testing and this isn't an IMC issue - it's graphical confusion.

TiCon doesn't seem to render fluids if there isn't a block form of the fluid. That's completely incorrect behavior. ;) There is absolutely no need for a block form for any fluid rendering in world or in GUIs. It wastes block IDs and is generally not a great thing.

**Comment by laz2727** [comment]
Err... Smeltery GUI uses exact same texture getter (technical term) as forge buckets.

**Comment by laz2727** [comment]
So this: https://gist.github.com/laz2727/d52f5e047deac3f94908d2f1ea7d133a
gives this:
![2017-10-10 13 56 41](https://user-images.githubusercontent.com/2369751/31377991-555dee18-adc3-11e7-9bde-2ec0f646000c.png)
Which looks 200% valid to me.

**Comment by KingLemming** [comment]
Interesting. Figured it out - had to do with coloration.

As far as the original IMC issue, apparently IMC is handled in Initialization? Which is...early. Why are you guys doing that? It'll process automatically between Init and PostInit.

I can work around it, but I'm really a bit confused as to why I apparently have to. Care to explain?

**Comment by bonii-xx** [comment]
I don't remember exactly, but I put "IMC needs to be sent during preInit" so I assume there was a reason when I wrote it. I think it has to do with how things are/were loaded in Forge. Might actually be it's not necessary anymore in 1.12.

**Comment by KnightMiner** [comment]
@bonii-xx: anything else to do for this issue, or can I close it? Seems the issue was resolved, but do you want to adjust the IMC timing?

**Comment by bonii-xx** [comment]
I'd like to if possible, but I don't have the time to do some more extensive testing if it breaks stuff. Because if it turns out to be a breaking change, then I wont.
