### ISSUE TITLE
Conflict with Project portals plugin

### ISSUE THREAD

**Issue by wanderingmage** [SlimeKnights/TinkersConstruct#3194]
Using any tinkers construct item with project portals installed on a server causes crash.

[crash-2017-10-10_20.29.46-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1376097/crash-2017-10-10_20.29.46-server.txt)

Also submitted to Project portals group.

**Comment by KnightMiner** [comment]
We do not support SpongeForge, they change way too much Forge code for it to be worth our time. This crash also appears to be purely from their project portal's code not handling something properly
