### ISSUE TITLE
1.12.2 Tinkers and JEI

### ISSUE THREAD

**Issue by Daihok41** [SlimeKnights/TinkersConstruct#3195]
For some reason in the 1.12.2 version the part builder, stencil tables, pattern chest, part chest, and the tool stations are not showing up in JEI. The version im using is 1.12-2.7.3.30

**Comment by bonii-xx** [comment]
#3181

**Comment by KnightMiner** [comment]
This is neither a Tinkers Construct or a JEI issue. JEI automatically hides items with more than 400 variants, and Tinkers Construct automatically adds variants for all wood types for each of the part builder and stencil table. You pack has a large amount of wood types.

Either change your JEI config to show more items per item type (so you can fit all your wood types), or change the Tinkers Construct config so it shows just one variant per table type.
