### ISSUE TITLE
[Config]Option to disable sharpening kits ?

### ISSUE THREAD

**Issue by Thyriel** [SlimeKnights/TinkersConstruct#3197]
Could you add a config option to disable sharpening kits ?

Background: I'm restricting access to mining levels in my modpack but as those sharpening kits can bypass this restriction it would be great if i could deactivate them somehow. As neither the kits nor the patterns for it are a normal crafting recipe i didn't found a way to deactivate them somehow. (with crafttweaker or anything like that)

**Comment by KnightMiner** [comment]
If sharpening kits are disabled, what's to stop them from using a normal pick head in that material? Sounds like it would be easier for you to restrict access to the material entirely.

**Comment by bonii-xx** [comment]
..that doesn't make sense, how do sharpening kits bypass harvest levels if you can't get the materials for sharpening kits since they're restricted by harvest levels?

**Comment by BrianEdmonds** [comment]
I don't know about the OP's setup, but pretty generally in TC I can make
an obsidian block in the smeltery and apply it to a stone pick to get
cobalt level, all with nothing better than stone.  In fact I tend to
play for a long time with that stone pick, since it's so cheap to
repair.

**Comment by Thyriel** [comment]
I'm restricting mining levels by locking Tinker Materials with Game Stages + TinkerStages (unlocked by quests), but as those can't lock a material being smelted or used in casts you can still make sharpening kits with them. All it locks in the end is combining materials in the tool station/forge.
So for example you can get copper, smelt copper but don't make a copper pickaxe that would enable you to mine iron.
But as you can just cast a copper sharpening kit and apply it on a flint pickaxe  you end up with being able to mine iron level without the quest progress.

I would deactivate them myself too if anyone knows a way to do that, but CraftTweaker can't do it as far as i've seen as no crafting is involved.

**Comment by laz2727** [comment]
Alternatively, you can cast a copper pick head. There's an other
possibility but you won't ask us then.

**Comment by Thyriel** [comment]
@laz2727
Sure you can, but u can't use that pickaxe head in the tool station nor can you wield a pickaxe with a copper material as long as the stage isn't unlocked. 
I know it's mainly a bug/oversight in the TinkerStages mod (the dev knows of). I just thought i'd ask here fof the config option as it obviously would be the smartest and simplest solution just being able to turn the kits off.

**Comment by KnightMiner** [comment]
I would argue gamestages should provide a hook to stop the sharpening kits as part of the modifier event, that is what the hook is there for.

**Comment by bonii-xx** [comment]
As Knightminer said, that's an oversight in whatever is allowing you to limit TiCs capabilities. With just TiC, there is no difference. There are many events, like the PartCraftingEvent and the CastingEvent that allow to prevent all those things. Please contact GameStages' author.

**Comment by enderger** [comment]
just turn the sharpening kits into unfamiliar items.
