### ISSUE TITLE
Mattock's shovel part digs slowly on certain blocks. 

### ISSUE THREAD

**Issue by N1ch0l2s** [SlimeKnights/TinkersConstruct#3198]
Regardless of the shovel material or mining speed, the Mattock will dig anything besides clay or dirt variants at the same speed as punching it. I don't know if this has been said before but this really bugs me.

**Comment by laz2727** [comment]
Mattock is not a shovel. It's a garden tool.

**Comment by bonii-xx** [comment]
That is correct, as has been said, it is a mattock, not a shovel. If you want to shovel things, you need a shovel.
