### ISSUE TITLE
Crafting Station Crashes 

### ISSUE THREAD

**Issue by KathrinLionguard** [SlimeKnights/TinkersConstruct#3200]
I think this is something that needs a general string for how offten it appears to happen. I liek the astetic of Tinkers and I would adore beign able to play all these mods in singleplayer with no big issues but When i open the workbench it crashes my game. I can show you a list of mods I have it may hilight the issue.

**Comment by KnightMiner** [comment]
Alternatively, you can give us the crash report, as that has the list of mods and actually tells us what crashed.

**Comment by KnightMiner** [comment]
Since there is no response with a crash report, I am closing this issue.
