### ISSUE TITLE
Both 1.12.2 version crash

### ISSUE THREAD

**Issue by xKnightGamingx** [SlimeKnights/TinkersConstruct#3201]
https://gist.github.com/xKnightGamingx/a8feb94649c9d7988a0c555d0281de68

**Comment by KnightMiner** [comment]
Can you describe what lead to this crash. Also, please try and reproduce without any core mods (those listed at the top of the report)

**Comment by KnightMiner** [comment]
Closing for lack of response and since the gist seems to be deleted.
