### ISSUE TITLE
Server crash - possible conflict BoP

### ISSUE THREAD

**Issue by jc2xs** [SlimeKnights/TinkersConstruct#3202]
Crash Report: https://pastebin.com/CXAr9hTm

Actual crash was a ticking entity (Blue Slime from TiC). But BoP is in the mix as well. 

Forge version 14.23.0.2512
BoP version 7.0.1.2297
TiC version 7.4.34

Anyway I hope this helps and I will be posting this to BoP as well.

**Comment by jc2xs** [comment]
BoP post:  https://github.com/Glitchfiend/BiomesOPlenty/issues/1114

**Comment by jc2xs** [comment]
So more testing, we added InControl to the server and denied blue slimes from spawning.  And that has fixed this issue.  But this really isn't an ideal fix either.  I would prefer to keep them spawning.

**Comment by KnightMiner** [comment]
This does not appear to be a Tinkers Construct issue, but I will leave it open until it can be resolved.

It appears somehow `getSoundType` is called with invalid parameters (non-matching blockstate and block), causing Biomes O Plenty to try getting their property from a block of another type. Hard to tell exactly why that happens, but our slimes use vanilla code for all that.

Either you have a core mod messing with things, or this is a vanilla Minecraft bug.

**Comment by jc2xs** [comment]
Thanks KnightMiner.  The pack author seems to think this is a an EvilCraft issue since it isn't supplying the extended block types for their blood stained block.  But it does look related to the BoP blocks listed this line of the crash report.  But, yes, I don't think this is your issue.

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in ExtendedBlockState{block=evilcraft:blood_stained_block, properties=[]}

**Comment by jc2xs** [comment]
So I did a strpped down test of just the basic mods needed to reproduce. So all that is in the test pack that produced this crash is:

Forge 14.23.0.2512 & 14.23.0.2517
BoP 7.0.1.2301
Cyclops Core 1.12-0.10.21
EvilCraft 1.12-0.10.37
Mantle 1.12-1.3.1.21
TiC 1.12-2.7.4.34

So no core mods installed at all and this crash still happens.

Crash report: https://pastebin.com/TuShCXg5

I'm at a little loss here unless it is forge itself. There are no core mods in this test pack and the crash still happens.

**Comment by jc2xs** [comment]
So I've been able to very reliable reproduce this crash with just EvilCraft and BoP.  I even removed TiC from the test pack I was using to reproduce this.  So I'm going to close this crash report since TiC isn't involved in the mod interaction causing this crash.

Use the link for CyclopsMC/EvilCraft that I created on this report if you want some more details.
