### ISSUE TITLE
Lumberaxe durability calculation error

### ISSUE THREAD

**Issue by madhatr** [SlimeKnights/TinkersConstruct#3203]
It seems like the calculation is a bit off for the lumberaxe in two cases I have found.  I'll first list my materials and the numbers I see in game.

- Bronze (head)430, (extra)80, (handle)70 and 1.1
- Lead (head)334, (extra)100, (handle)-50 and 0.7
- BlueSlime (head)780, (extra)200, (handle)-50 and 1.3

I make a lumberaxe BronzeHead, BronzeToughRod, BronzePlate, LeadExtra
Head = 430
Plate = 430 + 80
Extra = 100
Rod = 70 + 80
(430+430+80+100+70+80) * 1.1 = 1309

Yet in game is shows 1306.

I make the same lumberaxe but instead with a blue slime tough rod
Rod = (-50) + 200
(430+430+80+100+(-50)+200 * 1.3 = 1547

 The game shows 1278, which seems to be obtain by ignoring the +200 on the blue slime handle.

So do some rods add in the extra and some do not?  Which would account for the blue slime one but the math still seems off on the first example.

**Comment by bonii-xx** [comment]
It doesn't matter if it's a rod, a plate or whatever. It depends on what the part is used as inside the tool. Just because is a rod doesn't mean it has to be a handle, and vice versa. In general it matches the visual representation of the tool. Also the formula is not correct, but i'll leave that part of tinkering to you ;)

**Comment by madhatr** [comment]
Okay I added to many things in there.  I should have refined the info/questions.

The tough rod when bronze(on the lumberaxe) It adds both of its durabilities 70 and 80
but
The tough rod blue slime(on lumberaxe) only adds one of its durablities the (-50)  

Is this intentional or an error?  It is an 1 item swap out and the so the rods are used as handles in this case.
