### ISSUE TITLE
Items not showing in inventory - Singleplayer

### ISSUE THREAD

**Issue by DarthLilo** [SlimeKnights/TinkersConstruct#3204]
So I'm trying Tinkers Construct again and this happend
![2017-10-20_08 07 02](https://user-images.githubusercontent.com/32961940/31827993-eb6422c2-b56d-11e7-8fd1-9f198aa53408.png)
![2017-10-20_08 06 34](https://user-images.githubusercontent.com/32961940/31827995-eb852940-b56d-11e7-99a6-580230cd6b1c.png)

Any Help?

**Comment by bonii-xx** [comment]
#3008

**Comment by KnightMiner** [comment]
Remove or update Optifine.
