### ISSUE TITLE
[Request] Changing Smeltery Coordinates to be relative

### ISSUE THREAD

**Issue by JTK222** [SlimeKnights/TinkersConstruct#3205]
Heyho,
we made a new schematic format that works like a charm with most mods.
Just a small problem with TC, the smeltery coordinates aren't saved as relative coordinates in the TE's
This makes it more or less impossible to copy Smelterys over with schematics.
Would be really nice if that could be changed.

Though understandable if you don't want to

**Comment by bonii-xx** [comment]
Because there is no reason to use relative coordinates. The smeltery should just become invalid and rebuild itself in that case, if I remember the code correctly.

**Comment by JTK222** [comment]
Understand that, while I think it's sad that TC wont have schematic support I am ok with it.
(Schematic support was the only reason for this, currently it wont work for any schematic system unless they manually parse the coordinates :()

**Comment by KnightMiner** [comment]
I believe you misunderstood boni, he said if the smeltery is reloaded at a different position, it should automatically detect the structure is no longer valid and rebuild. Is that not what you are experiencing?

**Comment by JTK222** [comment]
Oh yeah.. totally misunderstood that xD Sorry.
My testers reported that the drains used the storage from the old smeltery... and they were kind of linked together.
Gonna do some tests by myself tomorrow and explain it better.

**Comment by KnightMiner** [comment]
@JTK222 did you end up doing tests verifying the issue?

**Comment by JTK222** [comment]
Oh right sorry, forgot about it.

So my tests resultet in this:
When copying a Smeltery over, the new controller doesn't work. (breaking it and placing a new one doesn't fix it)
The faucets are still linked to the old one.  (replacing them fixes it)
And you can extract molten metals with them from the old Smeltery.
Tanks don't seem to be affected by this.

**Comment by KnightMiner** [comment]
No plans to do this for 1.12, pretty big change. For 1.16, it would slow down a lot of our caches so doubt I plan to do relative offsets. Place a smeltery with no NBT and it will automatically build.
