### ISSUE TITLE
Broken "unbreakable" tool with mending moss cannot be repaired (1.12.1)

### ISSUE THREAD

**Issue by Sukasa** [SlimeKnights/TinkersConstruct#3206]
Using Tinkers' Tool Levelling and Extra Utilities 2 on a server.  Hammer was broken but I didn't get around to repairing it soon enough.  Seems that the Mending Moss on it brought it up to "full" health (but still broken), and plunking it in a tool forge no longer lets me use its repair material to repair it.  Doesn't consume any iron if I try, and stays at full health + repaired.

NBT data attached.
[1d6f3406-10e2-431a-9ed0-1866ed8bc37d.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1403497/1d6f3406-10e2-431a-9ed0-1866ed8bc37d.zip)

(As for why it broke while unbreakable, I'm going to place blame squarely on the ExU2 "magically brittle" modifier)

**Comment by KnightMiner** [comment]
Last I checked, magically brittle does not properly break tools, it just applies the broken tag. Try with just our materials.

**Comment by laz2727** [comment]
ExU bug.

**Comment by KnightMiner** [comment]
Since there has been no response, I am closing this as an Extra Utilities bug. If you  want a reopen reproduce with just our materials.
