### ISSUE TITLE
Crafting Sation Bug

### ISSUE THREAD

**Issue by CheekyBrit** [SlimeKnights/TinkersConstruct#3210]
TiC crafting station removing items when shift clicked into it and not placing in world but still in inventory when sorted using Inventory Tweaks. Was shifting in my inventory to sort, my items went into the crafting station. Once it filled up, any other shift clicking i did would delete the item. When I broke the crafting station it would appear placeable but then place and instantly disappear and reappear in my inventory.

**Comment by KnightMiner** [comment]
It sounds like you are having server/client desync, but I doubt it is related to TInkers Construct. Please post all versions of all relevant mods and try to reproduce with minimal mods.

After doing that, post game logs from that minimal mod reproduction.

**Comment by KnightMiner** [comment]
Closing for lack of response. Provide more information if you want a reopen.
