### ISSUE TITLE
Ores

### ISSUE THREAD

**Issue by IHaveAProblemHelp** [SlimeKnights/TinkersConstruct#3211]
For some reason i can not access copper ore and some other ores. they are just simply not there!
Minecraft 1.12.1
TC Version: 1.12-2.7.3.30
Forge Version: 14.22.0.2475
![2017-10-25_11 03 49](https://user-images.githubusercontent.com/33100667/32014968-7a3874a8-b974-11e7-9de8-3a9bb285fa5a.png)

**Comment by KnightMiner** [comment]
Please read the FAQ from the big yellow box when you submit an issue.
