### ISSUE TITLE
Block tinker throwables

### ISSUE THREAD

**Issue by Raycoms** [SlimeKnights/TinkersConstruct#3212]
It would be nice if the tinker throwable as "shuriken" do call the bow events so protection mods can disable them more easily.

**Comment by Raycoms** [comment]
Any update on this? Shurikens still pass our spawn protection?

**Comment by bonii-xx** [comment]
If your spawn protection relies on people not being able to draw bows, rather than people not getting hurt, I'd rather question your spawn protection.

**Comment by Raycoms** [comment]
It's not about people not getting hurt, but you can use that to shoot item
frames.

2017-11-21 17:30 GMT+00:00 boni <notifications@github.com>:

**Comment by bonii-xx** [comment]
Okay, this makes even less sense. Tell me what you're trying to achieve, and maybe we can figure something out.

**Comment by Raycoms** [comment]
Our mod adds a colony to the game (minecolonies) those colonies are
protected from griefing by an anti griefing mechanism we code ourselves.

This means all blocks are protected from explosions, all entities from
attack and interaction and all chests from plundering.
But if you throw shuriken at item frames, they drop their stuff. (All other
protection mods we tried out until now fail against shurikens).

And I didn't find a way yet to prevent that.

2017-11-21 17:40 GMT+00:00 boni <notifications@github.com>:

**Comment by bonii-xx** [comment]
Because Item Frames drop when they take damage. OK, now I understand. If shurikens fail, than surely all other modded projectiles (that aren't arrows) also fail. Sounds a bit like some general interaction/hook is missing there. Needs some debugging to check what's happening.

**Comment by Raycoms** [comment]
We already cancel out the entity attack events, but that doesn't seem to
prevent the shurikens.

2017-11-22 18:42 GMT+00:00 boni <notifications@github.com>:

**Comment by bonii-xx** [comment]
But the question is why

**Comment by Raycoms** [comment]
It actually causes a PlayerInteractEvent$RightClickItem, but manually
adding every throwable of every mod just isn't a solution. The easiest
would be all throwable weapons use the arrowLose event which makes them
easily cancelable.

2017-11-22 18:47 GMT+00:00 boni <notifications@github.com>:

**Comment by bonii-xx** [comment]
I've checked out what's happening a bit, and it looks a lot like a missing event in Forge. There is the LivingHurtEvent/LivingAttackEvent, but frames aren't living entities, hence they don't get an event. You need an event to prevent the damage dealt on hit. This doesn't concern TiC, but all mods that have any means of dealing damage to entities that aren't leftclick. Needs to be fixed there.
