### ISSUE TITLE
Javalin not repairable

### ISSUE THREAD

**Issue by Pudding01** [SlimeKnights/TinkersConstruct#3214]
So, I'm currently playing Agrarian Skies 2 and I've been using a Javalin (flint head, iron/electrum rods) and I can't use it as melee anymore as it's "broken" and I can't repair it. (it does have auto repair on it). I assume that the problem has been fixed in future versions (not in the modpack) but I was wondering if there was something on my end that I could do, like some config I could change that could help.

Thanks

**Comment by laz2727** [comment]
Have you tried throwing it?

**Comment by LoveFireAmi** [comment]
Also, 1.7.10 is no longer supported.

**Comment by Pudding01** [comment]
Yes, I have thrown it. Doesn't fix the whole "broken" thing.

And I'm not asking for a bug-fix as I assume it's already fixed in a latter version, I'm just asking if there's a way that I can fix it.

**Comment by KnightMiner** [comment]
Its hard to tell what is going on as I do not have much experience with javelin. Try updating to the latest 1.7 version and see if that helps. It could also easily be a mod conflict.

Since this does not affect the latest 1.12 editions, I am closing this issue.
