### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ibraheem650** [SlimeKnights/TinkersConstruct#3218]
When I Install TC To My Game, It Crashes.

Crash Report:
https://pastebin.com/8mNkem9c

**Comment by laz2727** [comment]
You can edit issues.

You have so many mods that Forge doesn't know what to do with them. Not really a bug.

**Comment by KnightMiner** [comment]
As @laz2727 said, not a Tinkers issue , you just have too many mods.

**Comment by Ibraheem650** [comment]
Thanks :D!
