### ISSUE TITLE
[Question] Redistributing Tinkers Construct and Mantle outside of Curse/Twitch in a modpack

### ISSUE THREAD

**Issue by bochen415** [SlimeKnights/TinkersConstruct#3220]
We (Technic team) would like to add TiCon to a new iteration of an official Technic modpack.
We checked the MIT license and saw this line on CurseForge:
"When using the mod, please use the Curse/Curseforge download and do not rehost the files."

We would like to use the mod but we would also like to be ok with the author's wishes, would it be alright if we rehost the mod using our infrastructure so the launcher could use it?

**Comment by bonii-xx** [comment]
Hi, sorry for the long delay, I was on holiday. ;)

As you already stated, in general we prefer to have a centralized download on Curseforge for security (popular mod, malware loaded rehosts, yaddayadda, you know the sites) and the modding reward program as well. We can also provide Solder files (I think that's also one of your systems?) for some packs.

I don't know your infrastructure, but as long as it's a central point under your control (aka not users uploading files, potentially using malware laden files) I'm fine with you rehosting it for Technic.

**Comment by Pyker** [comment]
Unfortunately our Solder runs on Heroku, which makes the usual setup (a `location` entry in the nginx config) impossible. We would be rehosting the mod in https://github.com/TechnicPack/Technic, which automatically deploys to http://mirror.technicpack.net/Technic/. Is this okay with you?

**Comment by bonii-xx** [comment]
Yes, that is ok.

**Comment by bochen415** [comment]
Thanks. Closing

**Comment by Pyker** [comment]
Thank you for your permission and quick response!
