### ISSUE TITLE
Silent's gem integration - Where did the colors go?

### ISSUE THREAD

**Issue by JunkynioyPH** [SlimeKnights/TinkersConstruct#3221]
![where did the colors go](https://user-images.githubusercontent.com/33281422/32270039-58d74a80-bf2f-11e7-96e2-9a1d220141f8.PNG)
the picture above will explain it,
Where did they go?
And please give me a FIX

**Comment by KnightMiner** [comment]
This sounds like a client's gem issue with their integration. Do our materials (cobalt, wood, etc.) Have color?

**Comment by JunkynioyPH** [comment]
yes they do, only the Silent's gems stuff in tinkers dont have colors, when i add modern warfare mod (adds guns) the colors are there, but downside is, the mod (modern warefare) caused some of the items in JEI and tinkers battle sign not to render waht they look like

**Comment by KnightMiner** [comment]
Report this to silents gems, if it does not happen with our materials there is nothing we can do as we do not add the integration with silents gems

**Comment by bonii-xx** [comment]
@JunkynioyPH do you know if this has been fixed by Silent in a never version?
