### ISSUE TITLE
1.7.10 Code ?

### ISSUE THREAD

**Issue by Speedst** [SlimeKnights/TinkersConstruct#3222]
Please help me,
Maybe I'm just very very stupid,
but can someone please tell me how
I can get the 1.7.10 source code to 
edit it.

Thanks

**Comment by KnightMiner** [comment]
On the main page for this repo, click branch then 1.7.10

**Comment by Speedst** [comment]
Thank you

**Comment by Speedst** [comment]
Well now I downloaded, unpacked and set up a Workspace (in Folder: gradlew setupDevWorkspace eclipse),
I set the folder(named eclipse) inside the Tinker's Construct... folder as Workspace, and launch eclipse.
I get this:
![screenshot 13](https://user-images.githubusercontent.com/33282091/32336665-293346fa-bff0-11e7-995a-53ad5c31b53c.png)

**Comment by Speedst** [comment]
I'm trying to manipulate Tinker's Construct Source Code for at least 10hours, please help me so I can get started.

**Comment by KnightMiner** [comment]
You are better off asking on the forms for this, there is nothing different about setting up tinkers over another mod so advise is easily general. We also officially no longer support 1.7, so you are on your own for issues there

**Comment by Speedst** [comment]
If it's the same for other mods,
my question is still, what did I
do wrong, I tried it in 1.12 to and
My result was the same.
