### ISSUE TITLE
[1.12.2] Gold Nuggets in Crafting Station

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#3225]
For some reason we are getting gold nuggets showing up in our crafting stations.  If you craft an item the gold nuggets disappear but as soon as you are done crafting the reappear.  You can pull the nuggets out of the table and they are real so it isn't some rendering glitch.  You pull out the 9 nuggets and they are instantly replaced by 9 more.

MC 1.12.2
Forge 2529
TiC 2.7.4.34

Just started happening today after updating to the new forge.

**Comment by MokahTGS** [comment]
Screenshot of what is happening:  https://www.dropbox.com/s/48xrml3dg4vq6ev/2017-11-04_12.55.52.png?dl=0

**Comment by KnightMiner** [comment]
Someone added a broken crafting recipe. You will see the same thing in a vanilla crafting table.

**Comment by MokahTGS** [comment]
But we don't.   I tried a vanilla table and it does not do it.   Only in the crafting station.

**Comment by KnightMiner** [comment]
We use vanilla code for that output slot.  There is a chance something is causing it to not happen in the normal crafting table, but it is definitely a broken recipe. JEI might log an error about it if you check you logs

**Comment by KnightMiner** [comment]
I've been told Unidict caused a similar issue until the latest version, so if you use that mod try updating it.

**Comment by MokahTGS** [comment]
That seems to have been the problem.   Thanks for the heads up.
