### ISSUE TITLE
Broken Tinker's Shovel Destroyed Under Certain Circumstances [1.12]

### ISSUE THREAD

**Issue by civ77** [SlimeKnights/TinkersConstruct#3227]
How to reproduce this:

1. Create a Tinker's Construct shovel (I tested with a flint head and again with a cactus head shovel)
2. Use all of the durability (Snow farming)
3. Right click on a dirt block
4. Whoa! Where'd the shovel go!? Spooky!

This probably wouldn't be a huge issue except that it is very easy to do on accident.

**Comment by LoveFireAmi** [comment]
Sounds like the right-click shovel feature doesn't get checked.

**Comment by bonii-xx** [comment]
Goddamnit vanilla code.

**Comment by bonii-xx** [comment]
I can't reproduce this in my dev environment. Clicking on a dirt block does nothing. Can you reproduce it using only tic and mantle?

**Comment by ItzMojang** [comment]
It happens when you try to make dirt paths with it and if  its about to break then once it hits 1 durability and try to make a dirt path its goes away

**Comment by carstorm** [comment]
Is it a mod compatibility issue with [Dirt2Path](https://minecraft.curseforge.com/projects/dirt2path)?

**Comment by KnightMiner** [comment]
Bringing up this old issue, can someone confirm if this is still an issue? I looked at Dirt2Path's code briefly and it appeared correct. I assume this also does not happen with vanilla grass paths?

**Comment by TherminatorX** [comment]
Checking this out in a modpack quick confirm's boni's check that TiC shovels do not have the pathmaking ability, though this was one cheated in from JEI I don't think that changes anything.

**Comment by KnightMiner** [comment]
They have pathmaking ability, its just vanilla only does it using grass blocks, which is all we add. I was asking specifically about Dirt2Path which was where the issue was cited before.

In a quick test, it seems they no longer break when calling that mod's code, so either it was fixed on their side or by fbcd6e2

**Comment by TherminatorX** [comment]
I was not able to use it on grass blocks @KnightMiner

**Comment by TherminatorX** [comment]
Huh, apparently paper shovels aren't able to make paths but others are...today I learned

**Comment by TherminatorX** [comment]
Highly possible, as it's a pack and not a standalone TiC testing instance
