### ISSUE TITLE
Not able to look up empty space in tank with many fluid types

### ISSUE THREAD

**Issue by elektronemulo** [SlimeKnights/TinkersConstruct#3228]
I have placed a large number of single buckets of different fluids (thanks, mini moos) in the max size multiblock tank. As the last several fluids entered the tank, the blank space at the top where I could hover my mouse to see the available space disappeared. The in-world (non-interface) rendering of the tank shows it to be about half full (which isn't right because I have low volumes of many types).  Now I have no way of knowing how much space is available.

Suggestions to remedy this oversight:
 - adjust interface size to available space on monitor (would still cause the same issue earlier on smaller monitors; y'all probably have other reasons that you haven't really done this on other functional block interface windows)
 - List different fluids with a scrollbar interface. (Ugh, scrollbars but this might create room for better details). This could render the fluids in something that looks like inventory slots; include an "empty space" or available space fluid inventory box at the end of the list.
 - Force a space at the top of the tank interface window a few pixels when the tank isn't completely full to allow hovering for empty space information. (That window is cramped, anyway, so this would probably work best if the tank interface window automatically adjusted it's height to the available height on the monitor).
![2017-11-06_20 58 03](https://user-images.githubusercontent.com/20167300/32473378-56911e04-c335-11e7-9310-57629c67e4b7.png)
![2017-11-06_20 58 14](https://user-images.githubusercontent.com/20167300/32473379-56aa149a-c335-11e7-8211-80a78cdbbb9e.png)

**Comment by bonii-xx** [comment]
The reason for this is that the liquids in the UI actually have a minimum height of 3 pixels (so you can click/hover them), and even without that I can't render less than 1 pixel. I'll see if we can change the code to think the height is 3 pixels less if it's not full, so there always are 3 pixels for the empty space at the top (if it's not full).
