### ISSUE TITLE
This Prob I Need Solved

### ISSUE THREAD

**Issue by Wolfmatic** [SlimeKnights/TinkersConstruct#3229]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.3-114.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.5.2.jar)
  SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  llibrary (llibrary-1.7.8-1.12.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  weaponlib (mw-1.11.5.1_mc1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.7.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 11/7/17 8:14 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:116)
	at appeng.core.Registration.registerSpatialDimension(Registration.java:222)
	at appeng.core.Registration.postInit(Registration.java:397)
	at appeng.core.AppEng.postInit(AppEng.java:250)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:724)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 690511024 bytes (658 MB) / 3934257152 bytes (3752 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2521 110 mods loaded, 109 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJ | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJ | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJ | FML                  | 8.0.99.99                | forge-1.12.2-14.23.0.2521.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | forge                | 14.23.0.2521             | forge-1.12.2-14.23.0.2521.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCHIJ | actuallyadditions    | 1.12.2-r124              | ActuallyAdditions-1.12.2-r124.jar               | None                                     |
	| UCHIE | appliedenergistics2  | rv5-stable-1             | appliedenergistics2-rv5-stable-1.jar            | None                                     |
	| UCHIJ | bdlib                | 1.14.3.10                | bdlib-1.14.3.10-mc1.12.2.jar                    | None                                     |
	| UCHIE | ae2stuff             | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                   | None                                     |
	| UCHIJ | akashictome          | 1.2-10                   | AkashicTome-1.2-10.jar                          | None                                     |
	| UCHIJ | baubles              | 1.5.1                    | Baubles-1.12-1.5.1.jar                          | None                                     |
	| UCHIJ | ctm                  | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                          | None                                     |
	| UCHIJ | chisel               | MC1.12-0.0.14.18         | Chisel-MC1.12-0.0.14.18.jar                     | None                                     |
	| UCHIJ | jei                  | 4.8.0.111                | jei_1.12.2-4.8.0.111.jar                        | None                                     |
	| UCHIJ | mantle               | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHIJ | tconstruct           | 1.12-2.7.4.34            | TConstruct-1.12-2.7.4.34.jar                    | None                                     |
	| UCHIJ | extrautils2          | 1.0                      | extrautils2-1.12-1.6.4.jar                      | None                                     |
	| UCHIJ | flyringbaublemod     | 0.3.0_1.12-306787e       | angelRingToBauble-1.12-0.3.0.46+306787e.jar     | None                                     |
	| UCHIJ | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHIJ | astralsorcery        | 1.7.2                    | astralsorcery-1.12.2-1.7.2.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJ | quark                | r1.3-114                 | Quark-r1.3-114.jar                              | None                                     |
	| UCHIJ | autoreglib           | 1.3-15                   | AutoRegLib-1.3-15.jar                           | None                                     |
	| UCHIJ | ichunutil            | 7.0.2                    | iChunUtil-1.12.2-7.0.2.jar                      | None                                     |
	| UCHIJ | beebarker            | 7.0.0                    | BeeBarker-1.12.2-7.0.0.jar                      | None                                     |
	| UCHIJ | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJ | bibliocraft          | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCHIJ | biomesoplenty        | 7.0.1.2302               | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar   | None                                     |
	| UCHIJ | bookshelf            | 2.2.468                  | Bookshelf-1.12.2-2.2.468.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ | botania              | r1.10-349                | Botania r1.10-349.jar                           | None                                     |
	| UCHIJ | codechickenlib       | 3.1.3.313                | CodeChickenLib-1.12-3.1.3.313-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | redstoneflux         | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJ | brandonscore         | 2.3.3                    | BrandonsCore-1.12-2.3.3.132-universal.jar       | None                                     |
	| UCHIJ | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJ | chancecubes          | 1.12.1-3.0.1.208         | ChanceCubes-1.12.1-3.0.1.208.jar                | None                                     |
	| UCHIJ | chesttransporter     | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                 | None                                     |
	| UCHIJ | chiselsandbits       | 14.9                     | chiselsandbits-14.9.jar                         | None                                     |
	| UCHIJ | cofhcore             | 4.3.6                    | CoFHCore-1.12-4.3.6.14-universal.jar            | None                                     |
	| UCHIJ | cofhworld            | 1.0.1                    | CoFHWorld-1.12-1.0.1.8-universal.jar            | None                                     |
	| UCHIJ | controlling          | 3.0.3                    | Controlling-3.0.3.jar                           | None                                     |
	| UCHIJ | cucumber             | 1.0.2                    | cucumber[1.12]-1.0.2.jar                        | None                                     |
	| UCHIJ | darkutils            | 1.7.176                  | DarkUtils-1.12.2-1.7.176.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ | draconicevolution    | 2.3.4                    | Draconic-Evolution-1.12-2.3.4.265-universal.jar | None                                     |
	| UCHIJ | elevatorid           | 1.3.5                    | ElevatorMod-1.12.2-1.3.5.jar                    | None                                     |
	| UCHIJ | embers               | 0.230                    | embers-0.230.jar                                | None                                     |
	| UCHIJ | enderstorage         | 2.4.0.122                | EnderStorage-1.12-2.4.0.122-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | zerocore             | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCHIJ | bigreactors          | 1.12-0.4.5.44            | ExtremeReactors-1.12-0.4.5.44.jar               | None                                     |
	| UCHIJ | mekanism             | 9.4.1                    | Mekanism-1.12.1-9.4.1.326.jar                   | None                                     |
	| UCHIJ | sonarcore            | 5.0.2                    | sonarcore-1.12.2-5.0.2.jar                      | None                                     |
	| UCHIJ | fluxnetworks         | 3.0.1                    | fluxnetworks-1.12.2-3.0.1.jar                   | None                                     |
	| UCHIJ | ftbl                 | 4.2.3                    | FTBLib-4.2.3.jar                                | None                                     |
	| UCHIJ | ftbu                 | 4.2.2                    | FTBUtilities-4.2.2.jar                          | None                                     |
	| UCHIJ | gravestone           | 1.10.0                   | gravestone-1.10.0.jar                           | None                                     |
	| UCHIJ | gravitygun           | 7.0.0                    | GravityGun-1.12.2-7.0.1.jar                     | None                                     |
	| UCHIJ | guideapi             | 1.12-2.1.4-57            | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UCHIJ | hammercore           | 1.9.5.2                  | HammerCore-1.12.2-1.9.5.2.jar                   | None                                     |
	| UCHIJ | hats                 | 7.0.0                    | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCHIJ | theoneprobe          | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                     | None                                     |
	| UCHIJ | immersiveengineering | 0.12-74                  | ImmersiveEngineering-0.12-74.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJ | immersivepetroleum   | 1.1.3                    | immersivepetroleum-1.12-1.1.3.jar               | None                                     |
	| UCHIJ | inventorypets        | 1.4.9.9a                 | inventorypets-1.12-1.4.9.9a.jar                 | None                                     |
	| UCHIJ | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJ | ironbackpacks        | @VERSION@                | IronBackpacks-1.12.2-3.0.0.jar                  | None                                     |
	| UCHIJ | ironchest            | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| UCHIJ | jeiintegration       | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar              | None                                     |
	| UCHIJ | journeymap           | 1.12.2-5.5.1             | journeymap-1.12.2-5.5.1.jar                     | None                                     |
	| UCHIJ | jeresources          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
	| UCHIJ | kagic                | 1.9.4                    | kagic-1.9.4.jar                                 | None                                     |
	| UCHIJ | llibrary             | 1.7.8                    | llibrary-1.7.8-1.12.2.jar                       | None                                     |
	| UCHIJ | lycanitesmobs        | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | arcticmobs           | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | demonmobs            | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | desertmobs           | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | forestmobs           | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | freshwatermobs       | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | infernomobs          | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | junglemobs           | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | mountainmobs         | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | plainsmobs           | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | saltwatermobs        | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | shadowmobs           | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | swampmobs            | 1.17.3.2 - MC 1.12.2     | LycanitesMobsComplete 1.17.3.2 [1.12.2].jar     | None                                     |
	| UCHIJ | mekanismgenerators   | 9.4.1                    | MekanismGenerators-1.12.1-9.4.1.326.jar         | None                                     |
	| UCHIJ | mekanismtools        | 9.4.1                    | MekanismTools-1.12.1-9.4.1.326.jar              | None                                     |
	| UCHIJ | moreoverlays         | 1.13                     | moreoverlays-1.13-mc1.12.1.jar                  | None                                     |
	| UCHIJ | mousetweaks          | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCHIJ | mw                   | 1.11.5.1                 | mw-1.11.5.1_mc1.12.2.jar                        | None                                     |
	| UCHIJ | mysticalagriculture  | 1.6.6                    | mysticalagriculture-1.12-1.6.6.jar              | None                                     |
	| UCHIJ | mysticalagradditions | 1.2.5                    | mysticalagradditions-1.12-1.2.5.jar             | None                                     |
	| UCHIJ | natura               | 1.12-4.3.0.23            | natura-1.12-4.3.0.23.jar                        | None                                     |
	| UCHIJ | neat                 | 1.4-15                   | Neat 1.4-15.jar                                 | None                                     |
	| UCHIJ | p455w0rdslib         | 2.0.23                   | p455w0rdslib-1.12-2.0.23.jar                    | None                                     |
	| UCHIJ | harvestcraft         | 1.12.2a                  | Pam's HarvestCraft 1.12.2a.jar                  | None                                     |
	| UCHIJ | randomthings         | 4.0.8                    | RandomThings-MC1.12.2-4.0.8.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJ | reccomplex           | 1.4.5                    | RecurrentComplex-1.4.5.1.jar                    | None                                     |
	| UCHIJ | xreliquary           | 1.12.2-1.3.4.719         | Reliquary-1.12.2-1.3.4.719.jar                  | None                                     |
	| UCHIJ | rftools              | 7.13                     | rftools-1.12-7.13.jar                           | None                                     |
	| UCHIJ | rftoolsdim           | 5.05                     | rftoolsdim-1.12-5.05.jar                        | None                                     |
	| UCHIJ | solarfluxreborn      | 3.42r                    | SolarFluxReborn_1.12.2-3.42r.jar                | None                                     |
	| UCHIJ | storagedrawers       | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                 | None                                     |
	| UCHIJ | thermalfoundation    | 2.3.6                    | ThermalFoundation-1.12-2.3.6.16-universal.jar   | None                                     |
	| UCHIJ | thermaldynamics      | 2.3.6                    | ThermalDynamics-1.12-2.3.6.13-universal.jar     | None                                     |
	| UCHIJ | thermalexpansion     | 5.3.6                    | ThermalExpansion-1.12-5.3.6.20-universal.jar    | None                                     |
	| UCHIJ | tp                   | 1.12                     | tinyprogressions-1.12-3.2.10 - Beta.jar         | None                                     |
	| UCHIJ | trailmix             | 7.0.0                    | TrailMix-1.12.2-7.0.0.jar                       | None                                     |
	| UCHIJ | twilightforest       | 3.3.202                  | twilightforest-1.12.2-3.3.202-universal.jar     | None                                     |
	| UCHIJ | vampirism            | 1.3.2                    | Vampirism-1.12-1.3.2.jar                        | None                                     |
	| UCHIJ | teamlapen-lib        | 1.3.2                    | Vampirism-1.12-1.3.2.jar                        | None                                     |
	| UCHIE | wct                  | 3.7.50                   | WirelessCraftingTerminal-1.12.2-3.7.50.jar      | None                                     |
	| UD    | solarfluxreborncore  | 3.42r                    | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.3-114.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
HammerCoreCore (HammerCore-1.12.2-1.9.5.2.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
llibrary (llibrary-1.7.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  lumien.randomthings.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
weaponlib (mw-1.11.5.1_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
AstralCore (astralsorcery-1.12.2-1.7.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 520'
	AE2 Version: stable rv5-stable-1 for Forge 14.23.0.2491
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12.2-r124.jar
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-1.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.1.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.3-114.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12-0.4.5.44.jar
		* BotaniaAPI (88) from Botania r1.10-349.jar
		* chesttransporter|api (2) from ChestTransporter-1.12-2.8.7.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12-0.0.14.18.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12-0.0.14.18.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-14.9.jar
		* cofhapi (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|block (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|core (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|item (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|util (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12-2.3.4.265-universal.jar
		* fluxapi (1.0) from fluxnetworks-1.12.2-3.0.1.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.4-57.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.0.2.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-74.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-74.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.1.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.1.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.1.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.1.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.1.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.0.111.jar
		* mcjtylib_ng (2.4.4) from mcjtylib-1.12-2.4.4.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.23.jar
		* QuarkAPI (1) from Quark-r1.3-114.jar
		* sonarapi (1.0.1) from sonarcore-1.12.2-5.0.2.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.19.jar
		* VampirismAPI (1.3) from Vampirism-1.12-1.3.2.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.7.50.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar

**Comment by Wolfmatic** [comment]
By the way, my modpack was working fine before I added KAGIC for 1.12.1, and I used forge 14.23.0.2521.
But 1.12.1 Mekanism works fine for 1.12.2 forge.

**Comment by KnightMiner** [comment]
This is not a Tinkers Construct issue, you have two dimensions registered with the same IS. Check the config files for any loss that ads dimensions.
