### ISSUE TITLE
Dangerous Alternative Prefix

### ISSUE THREAD

**Issue by twistedatoms** [SlimeKnights/TinkersConstruct#3230]
recently putting some mods together and I see variations of this error message several times. basically for each molten_XXXX i see this. 

currently using version 2.6.5 for MC 1.10.2 with forge 12.18.3.2511

****************************************
* Dangerous alternative prefix `tconstruct` for name `molten_brass`, expected `railcraft` invalid registry invocation/invalid name?
* at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
* at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
* at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
* at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:128)
* at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:110)
* at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
****************************************

**Comment by KnightMiner** [comment]
This is not a But, just a warning due to his things were registered in 1.10. It is no longer the case in 1.12

**Comment by LoveFireAmi** [comment]
Please read the FAQ before opening an issue next time.
