### ISSUE TITLE
Can't figure out which mod(s) aren't working with TinkersConstruct

### ISSUE THREAD

**Issue by KainZeroGaming** [SlimeKnights/TinkersConstruct#3231]
here is the crash report:
https://pastebin.com/embed_js/85shM94T

**Comment by bookerthegeek** [comment]
Tell you what. Put that mess of a wall of text on paste in or gist and link it here.

**Comment by KainZeroGaming** [comment]
ok. never heard of those. but ill look it up

**Comment by KainZeroGaming** [comment]
Thanks, hadn't heard of that site till now. makes this much easier

**Comment by KnightMiner** [comment]
This looks like an issue with BuildCraft's sprite loader. Report this issue to them and link back here so we can follow up and determine which side its on.

**Comment by KainZeroGaming** [comment]
ok, ill look into that. Going to see if an updated 1.11.2 BuildCraft changes anything then I'll report the results.

**Comment by KainZeroGaming** [comment]
ok well, even with the new BC version it still crashed. so I'm going to send them the error report i posted above on the BC github page

**Comment by KainZeroGaming** [comment]
Ok Everyone, thanks for the suggestions. got it figured out over at the bc github. https://github.com/BuildCraft/BuildCraft/issues/3840
