### ISSUE TITLE
Duping problem with thermal expansion & Tinkers

### ISSUE THREAD

**Issue by SirTwsted** [SlimeKnights/TinkersConstruct#3232]
I raised this issue with Thermal Expansion,
And was told your mod is to blame...lol
Here is the issue I posted with Thermal Expansion and I was forwarded to you.
There is a video in that post that shows the problem.
.
https://github.com/CoFH/Feedback/issues/631

**Comment by SirTwsted** [comment]
KingLemming said this can not be done with Vanilla Pickaxes... Here is a video showing it does.
.
https://www.youtube.com/watch?v=_4739c-4QSk

**Comment by KingLemming** [comment]
It's another mod altogether, it's neither TiCon nor TE. I was a bit confused initially since this never happened before.

**Comment by bonii-xx** [comment]
Thanks KL
