### ISSUE TITLE
Invisible Items on DryingRack

### ISSUE THREAD

**Issue by duncanwebb** [SlimeKnights/TinkersConstruct#3234]
I'm seeing invisible Items on DryingRack and the ToolRack, most right item in hot bar.

![lost-souls-bug](https://user-images.githubusercontent.com/4198031/32736292-5be3fc5c-c897-11e7-9514-2643026087af.gif)

Version 1.12-2.7.4.34
Forge 14.23.0.2529

I have searched for similar issues but haven't found one.

**Comment by KnightMiner** [comment]
Please give a copy of your Tinkers Construct config. There is a good chance you disabled the option which allows items to display on racks. Should get the same result with basins/casting tables.

**Comment by duncanwebb** [comment]
Hi,

Is this the file you would like? I added a .txt at the end to allow it to be dragged here.

[tconstruct.cfg.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1471162/tconstruct.cfg.txt)

**Comment by KnightMiner** [comment]
Very first config option, render inventory in world. You have it set to false, this no rendering.

**Comment by duncanwebb** [comment]
Thanks, that was it.
