### ISSUE TITLE
crossbow bolts and sharping kits

### ISSUE THREAD

**Issue by thespellslinger** [SlimeKnights/TinkersConstruct#3235]
I can't make an electrum-iron bolt for a crossbow and i'm also trying to use a sharping kit on a bolt. I'm using this list of mods to make the bolt and if possible, improve it:
AutoRegLib, Avaritia 1.1x, Baubles, Better Builder's Wands, Botania, Brandon's Core, CodeChicken Core 1.8+, CodeChicken Lib 1.8+, COFH Core, Cyberware, Draconic Evolution, Ender IO, Extra Utilities, Genetics Reborn, Guide-API, Immersive Engineering, Just Enough Items (JEI), Mantle, MineMenu, mineTunes, Moar Tinkers, Not Enough Items 1.8+, Psi, Reborn core, Reliquary v1.3, SlashBlade, Tech Reborn, Thermal Foundation, Thermal Expansion, Thermal Dynamics, Tinkers Construct, Tinker Tool Leveling, Unidict, Waila, WanionLib, Wawla - What Are We Looking At, Waystones and WIRED: More Augs. The version i'm using is 1.10.2. If anyone knows what stopping it from happing please let me know, it would be very much appreciated.

**Comment by LoveFireAmi** [comment]
Sharpening Kits don't work on weaponry.

**Comment by thespellslinger** [comment]
> Sharpening Kits don't work on weaponry
thank you LoveFireAmi for telling me that piece of information. also, any idea where can I get an API that allows blazing pyrotheum to be used as a fuel for the smeltery in Curse?
