### ISSUE TITLE
Lighting bug when I go near Smeltery

### ISSUE THREAD

**Issue by WARGOD213** [SlimeKnights/TinkersConstruct#3236]
Whenver I go near the Smeltery, the lighting glitches a lot, kinda like "xray" frequently turning on and off.
I'm actually playing a modpack called Dinoland: Evolved on Technic Launcher

This also happens when I turn on the Faucet
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33649145/32769540-444e50d6-c957-11e7-9ac3-4ba2cd077d83.gif)
Extra: Lighting bugs everywhere but not often/"Xray" bugs, assuming it's not caused by the mod since I'm far from any TC blocks. Any liquid block updates causes "Xray" bug.
Need some help here cause it's really annoying.

**Comment by LoveFireAmi** [comment]
You have OptiFine, which is known to cause rendering issues.  You are also playing on an unsupported version of TiC...

**Comment by WARGOD213** [comment]
![dddawdsd](https://user-images.githubusercontent.com/33649145/32824139-c11a5380-ca1a-11e7-982a-d7d553519341.png)
It also just suddenly crashes whenever I load into my world. I tried loading other worlds and it worked but for my world, it closes Minecraft without any error messages. I know it's not really much related to Tinkers Construct but I guess you could fix it easily too. I deleted my player data hoping that it was related to putting my character at a laggy location so it could reset the spawn point but it didn't work. 

I guess it's Optifine's fault causing the "xray" bug.

**Comment by KnightMiner** [comment]
If it crashes, we need a crash report. Paste it on a site like pastebin and link of here.

**Comment by WARGOD213** [comment]
https://pastebin.com/aqFx5axf Here's the crash report

**Comment by KnightMiner** [comment]
Can you give a copy of your game log? There is a good chance it is not a TiC issue and 1.7 is not supported, but I should be able to point you in the right direction for a fix.

**Comment by WARGOD213** [comment]
https://pastebin.com/6qzPxz9b

**Comment by KnightMiner** [comment]
Well, the log seems to be missing an important piece of information, no idea why its not there but it makes it difficult to tell where to point you because of that.

I can say it seems to be having issues finding your game profile, so ensure you are using a valid Mojang account. And as I said before, 1.7 is not supported and this is likely not a TiC issue as nothing in the stacktrace points to Tinkers.
