### ISSUE TITLE
Crashing when clicking on Tinkers table!!

### ISSUE THREAD

**Issue by wibblywobble** [SlimeKnights/TinkersConstruct#3237]
I've only got tinkers, NEI, mantle, and Pams Harvestcraft installed. Plus the coremods of course. I'm so confused, I'm not a coder, but I really need help. The error is /

The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Ticking screen

And sometimes it says whilst rendering screen.

**Comment by KnightMiner** [comment]
Please copy ypur full crash report tk a site such as pastebin and link ot here.

**Comment by KnightMiner** [comment]
Same applies to you, if it crashed, post the crash report or it is no help.

**Comment by labyrinthorgan** [comment]
I think I'm having the same problem. [Here's](https://pastebin.com/gUTMXdak) my crash report.

**Comment by KnightMiner** [comment]
@labyrinthorgan update Tinkers Construct, your version is almost 6 months old. Latest is 2.7.4

**Comment by labyrinthorgan** [comment]
Thanks, that fixed it.

**Comment by KnightMiner** [comment]
Closing since there has been no response from the original poster with a crash report
