### ISSUE TITLE
Repeater makes Shuriken sound

### ISSUE THREAD

**Issue by Schnetzi8** [SlimeKnights/TinkersConstruct#3238]
If you throw a Shuriken on a repeater the repeater does the hitting noise of the Shuriken when ever you change it`s delay or it gets powered 
MC: 1.12.2
Tinker`s Construct: TConstruct-1.12-2.7.4.34
Mantel : Mantle-1.12-1.3.1.21
I don`t know if it`s important : I`ve Tinkers tool leveling installed: TinkerToolLeveling-1.12-1.0.2b

**Comment by KnightMiner** [comment]
Please give a full mod list. This issue has been seen before, but has never been a Tic issue, typically from something else breaking sound networking.

**Comment by Schnetzi8** [comment]
Other Mods are:
AppleSkin-mc1.12-1.0.9
BetterBuildersWands-1.12-0.11.1.245+69d0d70
Ceramics-1.12-1.3.3b
Chameleon-1.12-4.1.3
CodeChickenLib-1.12-3.1.3.313-universal
CoFHCore-1.12-4.3.6.14-universal
ColossalChests-1.12-1.6.7
Controlling-3.0.4
CraftTweaker2-1.12-4.0.9
CyclopsCore-1.12.2-0.10.22
EnderStorage-1.12-2.4.0.122-universal
FastLeafDecay-v14
gravestone-1.10.0
Hwyla-1.8.22-B37_1.12
ironchest-1.12.2-7.0.34.820
jei_1.12.2-4.8.0.114
journeymap-1.12.2-5.5.2
JustEnoughResources-1.12.2-0.8.5.27
modtweaker-4.0.5
Morpheus-1.12-3.3.2
MTLib-3.0.1
OreExcavation-1.4.109
RedstoneFlux-1.12-2.0.1.2-universal
StorageDrawers-1.12.1-5.3.3
WailaHarvestability-mc1.12-1.1.12
Wawla-1.12.2-2.5.246

**Comment by Schnetzi8** [comment]
I could also export the twitch file if thats easier

**Comment by KnightMiner** [comment]
I don't see anything immediately standing out, so let's try a few things:

* first, see if you can reproduce with just Tinkers Construct (and Mantle) installed.
* If not, try just removing any core mods (you can hold F3 and C in game to force a crash, core mods are listed at the top)
* if it still hapens, try witu just half of the mods and keep halfing the part that can reproduce the issue.

Hopefully we can find if this is a conflict.

**Comment by Schnetzi8** [comment]
It also happens with just Mantel and tinkers
![unbenannt](https://user-images.githubusercontent.com/33729494/32913967-41f7e3b0-cb14-11e7-8c1c-e2a0a37abc12.png)

**Comment by KnightMiner** [comment]
That is unusual since I've never seen the issue, though I do notice you are using a resource pack. Can you try without that to see if thats the issue? Also, I assume you are not using Optifine, right?

**Comment by Schnetzi8** [comment]
I took the texturepack out and it`s still happening and I`ve tested it with a few other blocks comparator and daylight sensors do the same

**Comment by Schnetzi8** [comment]
and i`m not using OptiFine

**Comment by Schnetzi8** [comment]
Other Blocks do the same:
Droper/Dispenser: make the sound whenever they get a Redstone signal
Redstone Ore: whenever it gets activated (by steping on to it) or when it deactivates again

Other Blocks do it just once or twice:
Piston: when it gets powered the first time and when it retracts again
Furnace: when it starts/stop having the flame animation at the front
Observer: when it detects something it makes the sound twice(I think the second sound is when it stops giving a signal)
Ice: Does it when it smelts(would probably do it more than once but once its melted it water and on Water the shuroken makes no sound)

**Comment by Schnetzi8** [comment]
I have found out another thing : short/longbow do the same (crossbow doesnt)
and if you shoot (for example) the repeater with a bow and throw aShuriken on it makes both sounds when its delay is changed (0r it gets powered)

**Comment by luckyu19** [comment]
I was able to replicate this bug under one condition: the projectile has to stay on the block that's getting updated. So a repeater will produce the sound of the shuriken if the shuriken is on top of the block. It has the same behaviour as an arrow would under the same condition.

Now whether this is the bug you meant, I can't tell, because as long as I picked up the projectile, it would not do that.

**Comment by KnightMiner** [comment]
Alright, I have time to look into this issue, though it was a bit poorly explained.

It seems that whenever the block the shuriken (or Tinkers Arrow) is sitting on changes state, the projectile appears to fall on the block again, rotating it and causing the hit sound effect. Will have to see if anything can be done about it.
