### ISSUE TITLE
[1.12.2] Crash on startup, newest forge versions and mappings

### ISSUE THREAD

**Issue by sokratis12GR** [SlimeKnights/TinkersConstruct#3239]
Crash: https://pastebin.com/FtTsx08c
TConstruct Version: 1.12-2.8.0.5
Mantle Version: 1.12-1.3.1.22
How to reproduce: Launch the mod with a newer version of 1.12.2 forge.
Seems like the field no longer exists ?
![image](https://user-images.githubusercontent.com/12274096/32915364-49276e1e-cb21-11e7-848b-334af600a8bb.png)

**Comment by sokratis12GR** [comment]
Additional Note: TileEntities seem to be using outdated/deprecated interface ITileEntityProvider.
There is no need for it, because Block provides Block.hasTileEntity and Block.createTileEntity

**Comment by sokratis12GR** [comment]
I've fixed the issue/made an 1.12.2 port with the correct data (updated names, non deprecated methods etc), and also improved it a bit.
https://github.com/sokratis12GR/TinkersConstruct/tree/1.12.1 [says 1.12.1 but is for 1.12.2]

**Comment by KnightMiner** [comment]
Somehow your mappings are not matching ours, which Gradle is supposed to handle. Can you link a sample of your build.gradle you are using for your project's dependencies?

**Comment by sokratis12GR** [comment]
https://github.com/sokratis12GR/TinkersConstruct/blob/1.12.1/build.properties
You guys are using a very out mapping

**Comment by sokratis12GR** [comment]
There have been a few important mapping changes after "snapshot_20170801" (3 months old) 
newest one should be snapshot_20171116

**Comment by KnightMiner** [comment]
Does not matter. If you are using gradlew properly for the dependency management, it will automatically deobf Tinkers to whatever mappings you use.

**Comment by sokratis12GR** [comment]
Didn't automatically update the mapping names for the fields and methods when set up Tinkers' it self manually

**Comment by sokratis12GR** [comment]
btw, there are still somethings that need to be updated, and specifically a method "getTemperature" now has a parameter

**Comment by KnightMiner** [comment]
Okay, let's restart from the beginning. Explain clearly what you are attempting to do angle why the mappings are an issue.

Are you trying to set up a workspace to work on Tinkers? Are you writing a mod that uses Tinkers as a dependency? Give detail, because this still sounds like a non issue

**Comment by sokratis12GR** [comment]
Alrighty,
I've got a mod that integrates to tinkers. it worked fine for the past versions except when using new mappings and forge version (1.12.2), which made this specific "isBlockContainer" field disappear.
Question: is it a Tinkers' field, or do you get it from Forge/Mc.
- ArmorPlus i.e used to have a tinkers integration, but tinkers started crashing because of missing fields and not updated methods
- Tried to get a fresh copy of tinkers so I forked it and opened it with my IDE to see what are the issues with the 1.12.2 forge. After hitting launch many issues missing/wrong names appeared, so basically I've commited the updated name changes and corrected some functionallity (the mod was using ITileEntityProvider, which is not recommended and seems like a "don't", there are methods from the block it self adding everything required for tile entities).
Additionally there was a method in TraitAridiculous which got updated and made to use a param, I've added it.
With a few words, Tinkers' worked 100% before updating to new mapping, 1.12.2 Minecraft & newest forge versions.

**Comment by KnightMiner** [comment]
Well, the way Forge works, it automatically reaps dependencies to whatever mappings you use if it's set up right. Can you show me what your build.gradle contains so I can find which side the issue is on? I doubt 1.12.2 added new methods since its supposed to be compatible.

**Comment by sokratis12GR** [comment]
Here, https://github.com/TheDragonTeam/ArmorPlus/blob/1.12/build.gradle

**Comment by sokratis12GR** [comment]
Additional Note: Forge Updated their default mappings, which are also alot more newrer than the Tinkers' ones
https://github.com/MinecraftForge/MinecraftForge/commit/083daeb5ed8e01518132c441f68eca88e2d59800

**Comment by KnightMiner** [comment]
[Why are these commented out?](https://github.com/TheDragonTeam/ArmorPlus/blob/1.12/build.gradle#L78-L79) Am I safe to assume that you use this to add TiC into your dev space?

**Comment by sokratis12GR** [comment]
I'm, but when enabled, tinkers is broken, and I had to do some updates, becauseI can't test tinkers Integrations when Tinkers' Construct wont launch.

**Comment by sokratis12GR** [comment]
![image](https://user-images.githubusercontent.com/12274096/33230732-d3ed6892-d1f1-11e7-8fc5-3ff7108443c7.png)
I disabled it, because I can't really launch MC without having a crash from TiC's side :D. Thats why I had this issue opened at the first time.

**Comment by KnightMiner** [comment]
Wait, I think I might have figured it out. Why are you using 2.8.0.5? Our latest is 2.7.4 (you should not just be setting the version to '+', that is going to break). We must have a broken build sitting on the maven.

**Comment by sokratis12GR** [comment]
Ah, will test this, thanks for noting this out, I was suggested by other mod devs to use + for versions, but I realized that Tinkers' doesn't update *too* frequently so that wouldn't be a problem.

**Comment by KnightMiner** [comment]
I would actually say never use + for versions. Using something like 2.7.4.+ is safe, or 2.7.+, but straight + is not since you are making the assumption that the actual 2.8.0 will not have breaking changes. That sort of version bump is likely due to breaking changes.

**Comment by bonii-xx** [comment]
>but I realized that Tinkers' doesn't update too frequently so that wouldn't be a problem.

I read that as "TiC has less bugs than other mods" :D

**Comment by sokratis12GR** [comment]
Alrighty, confirming that using version like: `2.7.4.+` fixes the issue.
