### ISSUE TITLE
Unbreakable tool broken

### ISSUE THREAD

**Issue by blaziken663** [SlimeKnights/TinkersConstruct#3241]
I just made an unbreakable pickaxe via the creative modifiers, just adding reinforcement 5 times, yet my pickaxe still broke when i was mining. 
![image](https://user-images.githubusercontent.com/33751149/32944771-efa148ea-cb90-11e7-9d1a-8f4f8804bb2d.png)

**Comment by KnightMiner** [comment]
You have magically brittle from extra utilities, good chance it does not do unbreakable checks when it magically breaks the tool
