### ISSUE TITLE
Crafting Station closes when smelting finishes

### ISSUE THREAD

**Issue by bdboybr0** [SlimeKnights/TinkersConstruct#3246]
Furnace next to crafting station.  When the crafting station UI is open and everything is finished smelting the UI closes.

Using the DW20 1.12.2 pack containing TConstruct-1.12-2.7.4.34.jar.

**Comment by bonii-xx** [comment]
This is because vanilla handles the lit furnace and the non-lit furnace as 2 separate blocks. When the block changes, the crafting station closes. This is because it can't ensure consistency if the blocks it accesses change.
