### ISSUE TITLE
Bronze Axe head not craftable?

### ISSUE THREAD

**Issue by JunkynioyPH** [SlimeKnights/TinkersConstruct#3248]
[Video.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1502981/Video.zip)
Video will show more, and it works PERFECTLY fine with clay mold, not the reusable shovel head mold

**Comment by JunkynioyPH** [comment]
This also occurs on axe head. 1.12.2 btw

**Comment by JunkynioyPH** [comment]
and again it works perfectly fine with clay mold

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions. Most likely another mod interfering.

**Comment by JunkynioyPH** [comment]
[Video 2.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1503619/Video.2.zip)
It works fine, i guess its a mistake of me reporting this here?
![randomfilenamelol](https://user-images.githubusercontent.com/33281422/33237034-66c2bc52-d2a2-11e7-838f-618bbb470d40.PNG)
Mods ^^^

**Comment by JunkynioyPH** [comment]
![forge](https://user-images.githubusercontent.com/33281422/33237050-f0f57e6e-d2a2-11e7-882a-b9a1eb5535d2.PNG)

**Comment by KnightMiner** [comment]
We do want to figure out which mod causes the issue, so we can report it to them or fix it if its on our side.

Well, lets start by updating TiC, just to be on the latest version. Also remove optifine as it can cause weird issues sometimes.

After that, remove about half the mods and see if it happens. If not, try the other half. Keep cutting in half until you find the mod that causes it.

**Comment by JunkynioyPH** [comment]
i am trying my best to reply, its because i have school...

**Comment by JunkynioyPH** [comment]
1st half = Fine
2nd half = fine
all = bad
WHAT....
[mymods1.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1509544/mymods1.zip)
[mymods2.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1509545/mymods2.zip)
[mymods3.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1509546/mymods3.zip)
[mymods4.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1509547/mymods4.zip)
[mymods5.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1509548/mymods5.zip)
[REPORT420.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1509573/REPORT420.txt)

**Comment by JunkynioyPH** [comment]
i dont get it + its night time for me....

**Comment by Tahakk** [comment]
Just remove the mods one by one, suggested halfs are just for quicker detection which one mod is doing it. If putting it in halfs doesn't help, do it the old way. One by one.

btw. if it is not replicable with ONLY **TC** or different **Forge** versions it have to be one of the mods. You just need to be pacient.

**Comment by JunkynioyPH** [comment]
i will do this once i have time. right now i have some school stuff to do... ;-;

**Comment by JunkynioyPH** [comment]
i randomly came across this... i was looking for a way to mine ardite and cobalt, and i remembered, obsidian can mine them, i tried making a "obs pick head" on a reusable cast, it doesn't work... its same problem as the previous, and again it works fine with clay mold. i will try all mods one by one on saturday. at any chance, what if i cant replicate the problem? by removing mods one-by-one? IF though, IF, whats next?

**Comment by bookerthegeek** [comment]
## Heyo ##
So I tested, and can not reproduce the issue. Granted I used the most up to date version (listed below) as of 2017-11-30. All casts (Normal and Clay Version) casted correctly. 

#### Mod Versions ####
```
  [1.12] RPG-HUD-3.6.6.2
  ActuallyAdditions-1.12.2-r124
  ActuallyBaubles-1.12-1.1
  AmbientSounds v2.1.2 mc1.12.2
  appliedenergistics2-rv5-stable-3
  AutoRegLib-1.3-15
  Baubles-1.12-1.5.1
  bdlib-1.14.3.10-mc1.12.2
  blockcraftery-0.1.3
  Botania r1.10-350
  CodeChickenLib-1.12-3.1.3.313-universal
  CoFHCore-1.12.2-4.3.7.24-universal
  CoFHWorld-1.12.2-1.0.2.10-universal
  corail_pillar-4.0.0-1.12
  CraftTweaker2-1.12-4.0.10
  CyclopsCore-1.12.2-0.10.23
  DynamicSurroundings-1.12.2-3.4.7.2
  elulib-0.1.8
  embers-0.230
  environmentaltech-1.12.2-2.0.5a
  EverlastingAbilities-1.12.2-1.3.6
  fluxnetworks-1.12.2-3.0.1
  FoodExpansion1.3.2-1.12
  iChunUtil-1.12.2-7.1.2
  ImmersiveEngineering-0.12-75
  ImmersiveEngineering-0.12-75-core
  inventorypets-1.12-1.4.9.9a
  inventorysorter-1.12.2-1.12.3+51
  IronBackpacks-1.12.2-3.0.2-3
  jei_1.12.2-4.8.4.130
  journeymap-1.12.2-5.5.2
  Mantle-1.12-1.3.1.21
  modtweaker-4.0.5
  MTLib-3.0.1
  PortalGun-1.12.2-7.0.1
  pressure-1.3.1.9-mc1.12.2
  Quark-r1.3-117
  RandomThings-MC1.12.2-4.0.8
  RedstoneFlux-1.12-2.0.1.2-universal
  Reliquary-1.12.2-1.3.4.724
  SilentLib-1.12-2.2.13-94
  SilentsGems-1.12-2.5.11-250
  simpleteleporters-1.12-2.1.5
  sonarcore-1.12.2-5.0.2
  TConstruct-1.12-2.7.4.34
  theoneprobe-1.12-1.4.19
  ThermalDynamics-1.12.2-2.3.7.14-universal
  ThermalExpansion-1.12.2-5.3.7.26-universal
  ThermalFoundation-1.12.2-2.3.7.18-universal
  valkyrielib-1.12.2-2.0.5a
  Waystones_1.12.1-4.0.17
```

#### Side Notes ####
@JunkynioyPH make sure you use the the latest version and also where did you get the `Advanced-Swords-Mod-1.12.2.jar` as the only place I found it was on a rehost site? Try to only use mods from CurseForge, the Minecraft Forums or Github. Safer that way. Also, please realize that most people will not download things so [ghist](www.ghist.com) or [pastbin](www.pastebin.com) for your logs. And you can use [giphy](https://giphy.com/create/gifmaker) or [youtube](www.youtube.com) for showing actions. Just saying.

**Comment by JunkynioyPH** [comment]
https://youtu.be/Z0TwjkNfLGE
https://youtu.be/49Gf8QTGUNs
this would probably end it

**Comment by bookerthegeek** [comment]
@JunkynioyPH Update your mods. If the issue persists with all the mods updated to the latest version please post here and I will look into it again.
