### ISSUE TITLE
show whether tool component is head, extra, or handle

### ISSUE THREAD

**Issue by mabelrxu** [SlimeKnights/TinkersConstruct#3250]
On some of the tools, such as the hammer, I can never remember if the plates count as head or extra ... I only want to use ardite if I can get the petramour, not the stonebound, and the materials and you book doesn't explain so I always end up having to try making the tool in a test world to check.

**Comment by luckyu19** [comment]
Each tool part would have their modifying class labelled if you hold shift to see its stats. So a large plate would have "Head" and "Extra" labelled, along with the stats and traits they added.

Also in Material and You, in each section of the material stats, beside the title labelling their categories (head, extra, handle), all tool parts that benefits from the stats will be cycled through.

Of course it could be helpful if they are nicely explained in the book, but once you do it enough times, it shouldn't be too hard to remember. 

Oh, some tool parts can be considered two categories (such as large plates are considered both head and extra parts).

**Comment by bonii-xx** [comment]
Finding out how the tools are composed is part of the tinkering process.  If it changes miningspeed/attack it's part of the head.

**Comment by mabelrxu** [comment]
this ^ ... did not know it's only the head that changes mining speed and attack stats.
