### ISSUE TITLE
gravel and grout

### ISSUE THREAD

**Issue by Raghalin** [SlimeKnights/TinkersConstruct#3252]
TConstruct-1.12-2.7.4.34 running on server (not tried single player)
1-2 gravel +2 sand +2 clay = 2 or 4 grout

3+ gravel +3+ Sand + 3+ Clay = flint

**Comment by KnightMiner** [comment]
Please try and reproduce this in single player. If it does not work, give details about the type of server.

Also, please give a Forge version and a list of other mods.

**Comment by Raghalin** [comment]
Buildcraft 7.99.12
Journeymap 1.12.2-5.5.2
LLOverlay Reloaded-1.1.4-mc1.12
Mantle 1.12-1.3.1.21
Tconstruct  1.12-274.34
Forge 1.12.2-14.23.1.2554

new random single player map
Crafting Table will vary results of how many gravel would be accepted before grout turns to flint
#1-4, #2-23, #3-30, #4-4,#5-3, #6-2,  #7-2 
Crafting Station
all attempts 2 gravel = grout, 3+gravel =flint

took out all mods except forge and TC/Mantle recreated map same results

forge updated to 2555 after thread started
tested SP  can not reproduce with only 1 stack of 64 of ea at crafting station and crafting table
after server forge upgrade to 2555 also unable to reproduce with 1 stack of ea item in crafting station and crafting table

**Comment by bonii-xx** [comment]
Sounds like something is messing with recipes, probably serverside. Try reproducing with only TiC, Mantle and Forge version.

**Comment by KnightMiner** [comment]
Actually, this is a Forge big that was recently fixed, which is why unwanted Forge version. According to the chancellor, [2555 fixed shapeless recipes](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.1.2556/forge-1.12.2-14.23.1.2556-changelog.txt)
