### ISSUE TITLE
Configuration for material abilities/modifiers

### ISSUE THREAD

**Issue by WolfieWaffle** [SlimeKnights/TinkersConstruct#3253]
I'd like do be able to disable certain modifiers, ecological in particular. In older versions of this mod there was no such modifier, and now it messes with the balance of my pack being able to have tools you never need to repair at such an early stage. I know it's not a fast repair, but I still would like to be able to control it. It can just be a list of blacklisted modifiers or a list of booleans, I just think it would be good to have some control over the many very powerful modifiers in the mod.

**Comment by bonii-xx** [comment]
TiC does not and will not expose a config to remove things. We support removal of things on startup through the API, which can be used by other mods, however the risk is on the removing mods site there.
You'll probably need some CraftTweaker or similar that supports TiC.

**Comment by WolfieWaffle** [comment]
OK that sounds fine, is there any documentation on how to use this API?

**Comment by bonii-xx** [comment]
It's event driven, so basically anything you find in here:
https://github.com/SlimeKnights/TinkersConstruct/tree/master/src/main/java/slimeknights/tconstruct/library/events

**Comment by MJRLegends** [comment]
@WolfieWaffle Yes what your looking for is traits not modifiers and it was a register event like modifiers do
