### ISSUE TITLE
Functionality request: Re-add placing items from toolbar

### ISSUE THREAD

**Issue by kragnoth** [SlimeKnights/TinkersConstruct#3262]
Please re-add the old tool functionality of placing items from the toolbar back to tinker's construct 2 tools.  The shield slot torch placement lacks any kind of proper right click handling that tinker's construct 1 tools had.

I.e. when I used a tinker's construct 1 pickaxe to right click wheat, it harvested the wheat.  Vanilla's shield slot places a torch if there is a block nearby that wasn't clicked but was behind the wheat, in addition to harvesting the wheat.

If the functionality was removed because vanilla added a way to do it, please re-consider, as vanilla does it poorly.  

edit: I do realize this goes against bullet point one in the faq, so I do expect this to be closed summarily with no explanation, but I'd like to think that maybe you just think vanilla's behavior is 'good', and just need one more dissenting opinion before re-implementing your right click to place code. :)

**Comment by KnightMiner** [comment]
Nope, vanillas behavior is good, the hotbar interaction was awkward since the slot was reserved. If right click is placing the block in addition to harvesting the crop, it means the crop right click handler is not made properly, so make a bug report to that mod author
