### ISSUE TITLE
Rendering nukes game

### ISSUE THREAD

**Issue by darkhax** [SlimeKnights/TinkersConstruct#3263]
While playing on a server, we created a situation where looking at the smeltery would cause the client to freeze up. The smeltery was being used as a basic emerald farm, and had a few buckets worth of liquid emerald and a gold nugget. This situation was possibly created by breaking one of the drain blocks. 

MC Version: 1.12.2
Forge Version: 14.23.1.2554
Tcon Version: 2.7.4.34
Mantle Version: 1.3.1.21

Here is a log, including a stacktrace for this issue. Looks like some sort of OOM issue, however both of the systems that reproduced this issue have more than enough ram and video ram available for typical minecraft play. 

https://gist.github.com/darkhax/7c26a99c712ab1af4c154ab71073768b

**Comment by jaredlll08** [comment]
Just to add to this issue, I made a custom TiC version that didn't render the smeltery liquid, just so I could log on...
![image](https://user-images.githubusercontent.com/5553605/33737293-45d81a46-db9e-11e7-9c57-cfcf2fb0f3dd.png)
so that is the block I broke, I believe it was a drain

the smeltery is still active:
![image](https://user-images.githubusercontent.com/5553605/33737306-51e6d174-db9e-11e7-9b9d-ae37458f14d6.png)

**Comment by bonii-xx** [comment]
Hm. I wonder if it's a rounding thing where the math derps out for rendering the liquids. It definitively isn't RAM.

**Comment by jaredlll08** [comment]
well if you look, the smeltery says it is active, even though it is missing a block, so the main smeltery thinks it is active, but doesn't do anything, like the villagers are not getting smelted down

**Comment by bonii-xx** [comment]
I don't know what to do with this, you're the only case where this ever happened. There's so many mods in that log that could play into this, together with other hardware factors, it's impossible to determine what actually caused it.

**Comment by darkhax** [comment]
I think the solution in this case would be to add some checks/bounds to the rendering code to make sure it's in a valid state, instead of trying to track down what caused the invalid state.
