### ISSUE TITLE
Illogical liquid slime

### ISSUE THREAD

**Issue by 3TUSK** [SlimeKnights/TinkersConstruct#3264]
Apparently it can support snow for whatever reason. The snow is naturally generated due to weather and altitude.
MinecraftForge 14.23.1.2556, Mantle 1.3.1.21, and Tinker's Construct 1.12-2.7.4.34 are present.

![2017-12-06_18 59 50](https://user-images.githubusercontent.com/9113033/33749793-a9d3ee68-db84-11e7-9c1d-d7a8c82be995.png)

**Comment by bonii-xx** [comment]
Somethingsomething density. I wonder what's the requirement for snow to generate 🤔

**Comment by 3TUSK** [comment]
> I wonder what's the requirement for snow to generate

I guess you need this? https://minecraft.gamepedia.com/Weather#Snow

**Comment by bonii-xx** [comment]
..in code.

**Comment by bonii-xx** [comment]
Curious, that's actually a forge bug. The fluid block in forge is defined as solid. Mojang probably changed their functions up at some point.
