### ISSUE TITLE
Crossbow Bolt tooltip strangeness

### ISSUE THREAD

**Issue by Zsashas** [SlimeKnights/TinkersConstruct#3267]
These bolts have a packed ice core with manyullyn poured over them. Don't know where the wood or iron is coming from. Should just say Ice-Manyullyn.

![2017-12-08_01 49 46](https://user-images.githubusercontent.com/6917535/33760666-418bc286-dbbb-11e7-98c0-41d863fb7bc5.png)

**Comment by bonii-xx** [comment]
Ah yes. Looks like the multi-material nature of boltcores derps out. Wood and Iron are the defaults it uses if it doesn't find anything else.
