### ISSUE TITLE
Dangerous alternative prefix

### ISSUE THREAD

**Issue by trilexcom** [SlimeKnights/TinkersConstruct#3268]
hi SlimeKnights / TinkersConstruct team 

i am getting this error msg in console 

****************************************
17:02:53	FML	main	* Dangerous alternative prefix `tconstruct` for name `enderference`, expected `integrationforegoing` invalid registry invocation/invalid name?
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.traits.TraitEnderference.<clinit>(TraitEnderference.java:18)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.TinkerTraits.<clinit>(TinkerTraits.java:72)
17:02:53	FML	main	*  at me.jacky1356400.integrationforegoing.compat.TConstructCompat.preInit(TConstructCompat.java:24)...
17:02:53	FML	main	****************************************
17:02:53	FML	main	****************************************
17:02:53	FML	main	* Dangerous alternative prefix `tconstruct` for name `insatiable`, expected `integrationforegoing` invalid registry invocation/invalid name?
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.traits.TraitInsatiable.<clinit>(TraitInsatiable.java:13)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.TinkerTraits.<clinit>(TinkerTraits.java:78)...
17:02:53	FML	main	****************************************
17:02:53	FML	main	****************************************
17:02:53	FML	main	* Dangerous alternative prefix `tconstruct` for name `magnetic`, expected `integrationforegoing` invalid registry invocation/invalid name?
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.traits.TraitMagnetic$MagneticPotion.<init>(TraitMagnetic.java:46)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.traits.TraitMagnetic.<clinit>(TraitMagnetic.java:25)...
17:02:53	FML	main	****************************************
17:02:53	FML	main	****************************************
17:02:53	FML	main	* Dangerous alternative prefix `tconstruct` for name `momentum`, expected `integrationforegoing` invalid registry invocation/invalid name?
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.traits.TraitMomentum.<clinit>(TraitMomentum.java:18)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.TinkerTraits.<clinit>(TinkerTraits.java:83)...
17:02:53	FML	main	****************************************
17:02:53	FML	main	****************************************
17:02:53	FML	main	* Dangerous alternative prefix `tconstruct` for name `dot`, expected `integrationforegoing` invalid registry invocation/invalid name?
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.traits.TraitSharp$DoT.<init>(TraitSharp.java:51)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.traits.TraitSharp.<clinit>(TraitSharp.java:18)...
17:02:53	FML	main	****************************************
17:02:53	FML	main	****************************************
17:02:53	FML	main	* Dangerous alternative prefix `tconstruct` for name `splinter`, expected `integrationforegoing` invalid registry invocation/invalid name?
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53	FML	main	*  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
17:02:53	FML	main	*  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.traits.TraitSplintering.<clinit>(TraitSplintering.java:14)
17:02:53	FML	main	*  at slimeknights.tconstruct.tools.TinkerTraits.<clinit>(TinkerTraits.java:92)...
17:02:53	FML	main	****************************************

We are using Forge 2556
TinkersContruct Version : TConstruct-1.12-2.7.4.34
MC : 1.12.2
Crashlog : https://pastebin.com/NWMF4wvg

Thanks 

Mat

**Comment by LoveFireAmi** [comment]
...
Please actually read the guidelines for contributing next time...
https://github.com/SlimeKnights/TinkersConstruct/blob/master/CONTRIBUTING.md

**Comment by bookerthegeek** [comment]
This is due to Tinkers registering things under `Minecraft` instead of `Tinkers` for inter-mod compatability.

**Comment by trilexcom** [comment]
thanks just wanted to let TC  know about the stuff we are getting from console. should i close this ticket? mat

**Comment by KnightMiner** [comment]
This looks like `integrationforegoing`'s fault, they are accessing our traits before we have a chance to register the potions (thus it is reigstered during their time). Report the issue to that mod's author.

**Comment by trilexcom** [comment]
opened a ticket with Jacky thanks
