### ISSUE TITLE
Smeltery Construction issue

### ISSUE THREAD

**Issue by PTY997** [SlimeKnights/TinkersConstruct#3270]
Hi, I am playing Forever Stranded, ( Like Yogscast ) I have got to the quest of building a smeltery. I have created the seared bricks. But when i click Seared Tank it doesn't have a recipe, Same goes for anything else i search for in the NEI. The only items come up are the Seared bricks Individual and Big blocks thats all. Is this a bug or has something gone wrong?

**Comment by LoveFireAmi** [comment]
Not a Tinkers' Issue.  The Smeltery crafting is purposely disabled in that pack...

**Comment by KnightMiner** [comment]
I am going to take @LoveFireAmi's word that the recipes are disabled. In any case, its a 1.10 pack and that version is no longer supported and the recipe was working perfectly fine there.
