### ISSUE TITLE
[1.12.2] Kamas have no page

### ISSUE THREAD

**Issue by EmosewaGamer** [SlimeKnights/TinkersConstruct#3272]
I'm guessing that you simply forgot to add a page for Kamas in the Materials and You book, but I might as well mention it.
![image](https://user-images.githubusercontent.com/25333164/33804139-c1d26122-dd9e-11e7-93fb-c2372fa99875.png)

**Comment by bonii-xx** [comment]
You are correct. Derp. Thanks
