### ISSUE TITLE
Optimization issue [1.10.2]/FoolCraft

### ISSUE THREAD

**Issue by jmac460** [SlimeKnights/TinkersConstruct#3273]
I have been testing Tinker's Construct for a while and I noticed a major issue when using TC tools; when you open a fool's bag and receive "Choppy McChop Face", the frames per second drops extremely low. I usually run around 180fps max, but when I hold or hover over the tool, it drops way down to 40 fps. I noticed this on multiple different personal computers as well. Is this something that will be fixed?

**Comment by KnightMiner** [comment]
It is already fixed in the latest versions for 1.12, 1.10 is no longer supported unfortunately, so not much will be done there
