### ISSUE TITLE
Traveler's Gear removed?

### ISSUE THREAD

**Issue by VictorScrooge** [SlimeKnights/TinkersConstruct#3276]
I just downloaded the version for 1.12 and i couldn't find the Traveler's Gear, also i couldn't find something in the topics or on the wiki. :(

**Comment by Techokami** [comment]
Yeah it got removed, along with a lot of other stuff, when they jumped from 1.7.10 to newer Minecraft versions.

**Comment by LoveFireAmi** [comment]
It's not removed, rather that it wasn't re-implemented due to it being rewritten.  The Wiki is also inaccurate and heavily outdated.
