### ISSUE TITLE
Glowing doesn't work in offhand

### ISSUE THREAD

**Issue by Alex-hawks** [SlimeKnights/TinkersConstruct#3278]
I had the idea to have a tool with glowing in my offhand so that I wouldn't need torches, and didn't have to use a modifier on my hammer for when I go mining, but it isn't working.

Modpack: Direwolf20 for MC 1.12 v1.1.0
TiCon Version: 1.12-2.7.4.34
Forge: 14.23.0.2531

Steps to reproduce:
1: Put glowing on a shovel
2: Put shovel in offhand
3: Go mining with a TiCon Hammer? (I tested it with a hammer)

**Comment by KnightMiner** [comment]
This was already fixed in 2.8.0, update to the latest Beta.
