### ISSUE TITLE
Chunk Population Error

### ISSUE THREAD

**Issue by rongineering** [SlimeKnights/TinkersConstruct#3279]
Versions
Minecraft: 1.12.2
Tinker's: 2.7.4.34
Forge: the one that ends in 2556 I think (not at home cpu)
Custom modpack with 74 mods (can list if needed)

Cascading worldgen lag during chunk population. See attached screenshot of server window log. Can try to find full log if needed.

![tinkererror]: (https://user-images.githubusercontent.com/32487842/33895085-a2b36292-df2d-11e7-9eec-84fa23723c29.png)

**Comment by bonii-xx** [comment]
Thanks. So the big question is.. is that a vanilla thing because we generate nether ores the same way vanilla do, or are those magma slime islands. If it's the former, we can't do anything. And yes, that was a rhetorical question.
