### ISSUE TITLE
Crash On Start Up

### ISSUE THREAD

**Issue by Killerkat39** [SlimeKnights/TinkersConstruct#3280]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/library/tools/ToolCore

Any Solutions?

**Comment by KnightMiner** [comment]
Try giving us mod versions, maybe give us the full crash report as well (post it on a site like pastebin and link it here)

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions. You have a coremod that breaks things.

**Comment by KnightMiner** [comment]
Closing since there has been no response, plus the class name makes it look like you are using 1.7 which is no longer supported.
