### ISSUE TITLE
Can no longer access Pattern Chest slots from Part Builder UI

### ISSUE THREAD

**Issue by Zsashas** [SlimeKnights/TinkersConstruct#3281]
It was visible to the side before, until the last update. Same with the Stencil Table.

![2017-12-14_17 55 29](https://user-images.githubusercontent.com/6917535/34023152-2ed1736a-e0f8-11e7-89ce-5bd107397522.png)

**Comment by bonii-xx** [comment]
What does the stencil table UI look like? What happens if you manually put a stencil into the pattern chest?

**Comment by Zsashas** [comment]
It looks the same in all of the tabs.

**Comment by bonii-xx** [comment]
It looks like you're using a resource pack. Try removing it.

**Comment by Zsashas** [comment]
Still can't see it.

![2017-12-18_21 39 18](https://user-images.githubusercontent.com/6917535/34142441-003f661e-e43c-11e7-8e93-e677b048c689.png)

**Comment by KnightMiner** [comment]
Again, try removing the resource pack. If that does not fix it, can you give a copy of your game logs? Do a fresh start up until you open the two inventories then close the game to keep the log minimal, and put it on a site such as pastebin, linking it here

**Comment by Zsashas** [comment]
Those are the unmodified table textures that I have, not sure what others there would be.

**Comment by Zsashas** [comment]
Made a new world, chopped down a few trees and made the stations so I could take screenshots. No texture packs enabled when the screenshots were taken. 

![2017-12-27_15 09 26](https://user-images.githubusercontent.com/6917535/34395787-24c3f1c0-eb18-11e7-8c61-c1448b4bdc28.png)
![2017-12-27_15 09 27](https://user-images.githubusercontent.com/6917535/34395788-24d9f0c4-eb18-11e7-9fb9-5b77e2097032.png)
![2017-12-27_15 09 28](https://user-images.githubusercontent.com/6917535/34395789-24f009d6-eb18-11e7-8f9b-3eb4cdc1b05a.png)
![2017-12-27_15 09 30](https://user-images.githubusercontent.com/6917535/34395790-250a1970-eb18-11e7-8f06-39de5d94d260.png)
![2017-12-27_15 09 31](https://user-images.githubusercontent.com/6917535/34395791-251f0c18-eb18-11e7-88c9-b812feec9ede.png)

**Comment by KnightMiner** [comment]
Closing for lack of response and since I am unable to reproduce. If you want to reopen, find a minimal setup to reproduce. Also ensure your pattern chest is next to the part builder and stencil table.
