### ISSUE TITLE
Crashing the game before starting.

### ISSUE THREAD

**Issue by DekyYT** [SlimeKnights/TinkersConstruct#3282]
Here's the whole crash report :
https://pastebin.com/tkFpXBnf
I have absolutely no idea what might be causing it, if someone can point it out, please tell me what I can do to fix the (most probably) conflict.
List of mods : 
![image](https://user-images.githubusercontent.com/29978014/34060848-3518e374-e1ee-11e7-90e6-249c1eb79714.png)

I don't know what to do, since I really want to fix this.

**Comment by KnightMiner** [comment]
This crash is caused by FoamFix, please do not just post on a random issue tracker with a crash.
