### ISSUE TITLE
Latest Beta [1.12-2.8.0.45] breaks the Indirect Integration with UniDict

### ISSUE THREAD

**Issue by WanionCane** [SlimeKnights/TinkersConstruct#3283]
Hello.

in [TConstruct-1.12-2.8.0.45](https://minecraft.curseforge.com/projects/tinkers-construct/files/2507737) was introduced this feature:

> New ore preference config. This is a list of mod IDs to prefer for recipe outputs from the ore dictionary, such as casting recipes.

this is breaking the indirect Integration that TinkersConstruct had with UniDict, as shown in 
https://github.com/WanionCane/UniDict/issues/59

I would like to ask if this "ore preference config" could be disabled if UniDict present, and add a config to enable it again if the user really wants it.

why don't I manually override this settings like I did in 1.7.10? in UniDict for newer versions, there are several always to specify the sorting for different entries, or for different kinds "ore, dust, ingot" and so on, so, even if do this, It wouldn't be so effective, since the ordering of "S:orePreference" is applied for everything.

**Comment by KnightMiner** [comment]
What is the issue with just emptying the ore preference if you are using unidict? Its a little more complicated to disable then just adding a config since with the new system we only ever store the one stack for outputs.

It might help if you explain how you are unifying outputs so we can determine what exactly broke, as most oredict recipes come down to just a single output.

**Comment by WanionCane** [comment]
UniDict sorts the List "OreDict List" way before the mod integrations are run, previously, Tinkers was using the List as the output, right? so, the first entry were always the "default-unified" entry, thanks to this "sorting". see here [UniResourceContainer.java#L140](https://github.com/WanionCane/UniDict/blob/1.12.2/src/main/java/wanion/unidict/resource/UniResourceContainer.java#L140)

since it is now using a fixed ItemStack, this "indirect" integration don't work anymore, but, cleaning the "S:orePreference" will make it work like before? I mean, grabbing the first entry of the list to be the output?

**Comment by KnightMiner** [comment]
Yeah, if there is no stack found matching the preference (and by extension, if the preference list is empty), we fall back to the first stack. So all that would need to be done is that config list cleared if that is how you sort the output.

**Comment by WanionCane** [comment]
yay! thanks a lot! =P
you mind If I clean this list internally from my code? the users will not notice this.

**Comment by KnightMiner** [comment]
Should be fine as long as you only do it once (so the user can still fill in the list if they like later), we used to do something similar to set one of the Forge configs, where we have a config option which defaults to true and sets the forge config then sets itself to false

**Comment by WanionCane** [comment]
ok, I will see which approach I will take, thanks a lot for helping me with this =)
