### ISSUE TITLE
[1.12.2](2.8.1.49)Can't replace or emboss Bolts

### ISSUE THREAD

**Issue by bba3075** [SlimeKnights/TinkersConstruct#3285]
I'm unsure if this is a feature or not, but with the latest 1.12 version (2.8.1.49) I cannot Emboss or replace bolt cores. I'm using the DNS Techpack from the AT launcher.

**Comment by bonii-xx** [comment]
There is no version 2.1.89

**Comment by bba3075** [comment]
My fault, I misread the version number, The version is 2.8.1.49, I updated the title and comment.

**Comment by bonii-xx** [comment]
Works fine in my dev environment. Try reproducing with only tic and mantle, probably some other mod interacting with it.

**Comment by bba3075** [comment]
I can replace bolt cores, but only if both pieces, the shaft and metal, are different than the current bolt core. Embossment doesn't work at all for bolt cores. This is with TiC and Mantle only.

**Comment by bonii-xx** [comment]
What are you using to emboss? You can only emboss one trait. It's a bit unintuinive, but you can use any toolpart that's equivalent to one single toolpart with the same stats as used in the tool. The bolt technically consists of a shaft, a head, and a fletching. That means you can use a pick head or similar to emboss regular material traits.

That replacing only works if both differ sounds a bit weird, but then again, boltcores are pretty special :L

**Comment by bba3075** [comment]
Ok, So, I did not know you could use other tool parts to emboss, I was trying to use Bolt cores to emboss. I suppose I don't really have a problem then. And I get why it doesn't work, can't emboss 2 traits, and you can't replace a tool part with another of the same material. You should specify that in the book for people like me.

**Comment by bonii-xx** [comment]
The bolt cores are very special. The replacement thing is weird, and possibly a bug (albeit pretty minor). The embossment thing is mentioned in the embossment modifier description.. but it's hard your wrap your head around that. Moreso with boltcores because they're technically 2 parts in one item.
