### ISSUE TITLE
[1.12.2](2.8.1.49) Slime knight tool making the game crash during initialization ?

### ISSUE THREAD

**Issue by nigrum-dente** [SlimeKnights/TinkersConstruct#3286]
Forge version: 14.23.1.2562

Not sure what is happening but here is the crash report:
https://gist.github.com/nigrum-dente/ef8cca4918b2cc5b1139579e005773bd

Here is the full log:
https://gist.github.com/nigrum-dente/700e452c7aedf713962ce80c29b01988

**Comment by bonii-xx** [comment]
Seems to be the same as #3284

**Comment by nigrum-dente** [comment]
I would have swore I added CTM.

Tested with CTM this time and it work just fine.

**Comment by bonii-xx** [comment]
Great, thanks for the confirmation.
