### ISSUE TITLE
[1.12.2] Smeltery doesn't see more than one tank of lava

### ISSUE THREAD

**Issue by Zsashas** [SlimeKnights/TinkersConstruct#3287]
Two seared tanks, side-by-side, but it says it only has 4b of fuel.

![2017-12-20_13 19 17](https://user-images.githubusercontent.com/6917535/34229229-654dd9e4-e588-11e7-937c-71776f87549f.png)

**Comment by KnightMiner** [comment]
Can you post a screenshot of the whole smeltery? One of the tanks might not  be in tje structute.

**Comment by Zsashas** [comment]
Oh wait...it doesn't count if it's in a corner pillar, does it?

**Comment by bookerthegeek** [comment]
@Zsashas no it does not.

**Comment by Zsashas** [comment]
WELP

**Comment by bookerthegeek** [comment]
@Zsashas did it work with the tank in the structure?

**Comment by Zsashas** [comment]
It detected the one tank in the structure, and not the one in the corner pillar, probably safe to assume it's fine lol.

If there actually is a bug with this, I'll re-open the issue.
