### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by tristinytits** [SlimeKnights/TinkersConstruct#3289]
![2017-12-21_12 18 45](https://user-images.githubusercontent.com/34728300/34236573-4f870abc-e64c-11e7-8560-2f21ed64991b.png)

I'm running FTB Horizons 3 on a server and I decided to add some old school mods that have been updated. I keep running into this issue (I've downgraded a few versions of TiC to try get it to work) where the liquids within are the missing texture glitch and it won't properly pour into the basins/tables. It's either a delayed pouring with no animations or it doesn't pour at all.

Thanks,
Tris.

**Comment by KnightMiner** [comment]
Duplicate of #3037.
