### ISSUE TITLE
[1.12.2 Mantle v1.3.1.21 Tinkers' v1.12-2.8.1.49] Not sure if JEI or Tinkers' 

### ISSUE THREAD

**Issue by VallenFrostweaver** [SlimeKnights/TinkersConstruct#3292]
See the image here. An example of a lot of issues here. You can't make a cast of a fletching, you can't make pig iron fletching, and so on. There are many issues like this though like pig iron bowstring and other materials besides pig iron.  None of these are actually craftable but they show up on JEI. If it's JEI I can report there.
![pig iron](https://user-images.githubusercontent.com/13642054/34267155-c627c4aa-e673-11e7-8559-aba904cee718.png)

**Comment by bonii-xx** [comment]
Hm, must've happened in the recipe rework. You can make anything, with any material, but the jei stuff probably doesn't check if an actual valid recipe for it exists.

**Comment by VallenFrostweaver** [comment]
So is this Tinkers' then?

**Comment by bonii-xx** [comment]
Most likely tinkers. We changed stuff in the last release.

**Comment by KnightMiner** [comment]
Oh yeah, forgot about this. I noticed it while testing the ore preference but forgot to make a fix before the release. Curious if those recipes actually function or if JEI is just missing a few checks.

**Comment by laz2727** [comment]
They don't.
For the record, I've had these recipes in my dev for ages.

**Comment by bonii-xx** [comment]
Turns out we were actually registering those (impossible) recipes. Fun!
