### ISSUE TITLE
[1.10.2] Breaking Smeltery Causes a crash

### ISSUE THREAD

**Issue by MJRLegends** [SlimeKnights/TinkersConstruct#3293]
Crash log: https://pastebin.com/D7zZD4MB
TinkersConstruct Version: 1.10.2-2.6.5
Mantle: 1.10.2-1.1.5

Im going to be submitting a fix in a min through pull request, would be amazing if you could take a look at it

MJRLegends

**Comment by bonii-xx** [comment]
1.10 support has stopped quite a while ago, sorry.
