### ISSUE TITLE
Part Station not working

### ISSUE THREAD

**Issue by Sethinator28** [SlimeKnights/TinkersConstruct#3295]
Im new at this mod, when Im making a "part", I put the stencil of say a sword head, then ardite (with the amount needed), nothing shows up.  Is that supposed to happen?

**Comment by Sethinator28** [comment]
It works with knightslime, but nothin else as far as Im certen

**Comment by KnightMiner** [comment]
Part builder only works with nonmetal materials by default. You need to use a smeltery to make metal parts. Since you are so new to the mod, you are probably best off finding a tutorial online.

**Comment by Sethinator28** [comment]
Ohhhhhhhhhhhhhhhhhh thx
