### ISSUE TITLE
items

### ISSUE THREAD

**Issue by gustaff67** [SlimeKnights/TinkersConstruct#3296]
if you smelt uni dict gears you get to many ingots out of it

**Comment by KnightMiner** [comment]
Can you please add any details? Please give the following:

* versions, including Tinkers, unidict, Forge, and Minecraft 
* how much did you expect to receive from smelting?
* how much did you actualy receive
* what are some steps to reproduce? How are you obtaining the unidict gears? Is it not casting?

**Comment by gustaff67** [comment]
Version minecraft  1.12 
tinkers and uni 1.12.2
 I expect 1 ingot
i receive 4 ingots
you can reproduce  it if you  smelt gears in the smeltery.  You can craft the gear with one rod and 4 ingots you get out 4 gears . No it is not casting But you can smelt it

**Comment by KnightMiner** [comment]
Sounds like an issue on unidicts side, gears have always cost 4 ingots for as long as I can remember.

**Comment by bonii-xx** [comment]
The common cost for gears is lesser gear + 4 ingots or iron ingot + 4 ingots, hence 1 gear costs 4 ingots. If something else is using different amount it will always break the other mods. We might add a config for it, but it's definitively not a bug.
