### ISSUE TITLE
Chests Cannot Be Opened (Enderchest = Crash)

### ISSUE THREAD

**Issue by Shamil0** [SlimeKnights/TinkersConstruct#3298]
Whenever i try to open a normal or a double chest i cannot open it, but whenever i open a enderchest i crash instantly

**Comment by KnightMiner** [comment]
How is this a Tinkers Construct issue? Really? We do nothing with vanilla chests.

This is a Optifine issue caused by recernt changes in Forge. Update Optifine or downgrade Forge.
