### ISSUE TITLE
Curse modpack crashing

### ISSUE THREAD

**Issue by glenwins** [SlimeKnights/TinkersConstruct#3300]
My custom modpack I made keeps crashing when I join into my single player world.  I can't figure out the issue and would really like some help with it.
[crash-2017-12-23_18.53.26-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1584520/crash-2017-12-23_18.53.26-server.txt)

**Comment by glenwins** [comment]
Also the mods are on https://www.curseforge.com/minecraft/modpacks/francos-fun-pack

**Comment by LoveFireAmi** [comment]
Do not use the issue trackers of mods that have nothing to do with your crashes as tech support.  There are plenty of others who are willing to help you such as on the Minecraft Forums or Reddit.

**Comment by KnightMiner** [comment]
As @LoveFireAmi said, this is unrelated to Tinkers Construct. The crash log points to FTB Utilities.

**Comment by glenwins** [comment]
ok thanks

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
