### ISSUE TITLE
Ticking Tile Entity: Modifier is already applied to this attribute (server crash only)

### ISSUE THREAD

**Issue by kragnoth** [SlimeKnights/TinkersConstruct#3302]
https://pastebin.com/xRkkcvrk (pastebin link for crash)

Minecraft 1.12.2
Forge 14.23.1.2566
Tconstruct: 1.12-2.8.1.49

Crash upon attacking a guardian and having the reflection damage from guardian damage me.  Tool used was a cleaver.  Bone large tool rod.  Cactus large tool rod.  PlusTic materials used for blade (in case relevent) were palis on both parts of blade structure.

Server crashed, client stayed open for player.

**Comment by bonii-xx** [comment]
Hm, it tries to reflect the reflected damage from a guardian, but it already had everything setup because it was caused by you attacking in the first place.. or something similar. Looks like a bug.

**Comment by bonii-xx** [comment]
This actually is more severe than it looks at first.. it would crash on all reflected damage.
