### ISSUE TITLE
[1.12.2] Crafting Problem with AE2 and Thermal Dynamics

### ISSUE THREAD

**Issue by JonasCiss** [SlimeKnights/TinkersConstruct#3303]
Applied Energistics and Thermal Dynamics have way to make covers for the ducts and pipes but seared blocks cannot be used to craft any.

**Comment by KnightMiner** [comment]
This issue is technically on their side. I assume they ignore blocks which have a tile entity for cover recipes, and seared bricks have a TE. Chisel and bits solves this by having an IMC method to override that behavior, so the best fix would be a similar message in those two mods.

**Comment by JonasCiss** [comment]
Chisel is also present. And that mod works as well, that's right.

**Comment by KnightMiner** [comment]
I did not say Chisel, I said "chisel and bits", the one with the microblocks. You can make Tinkers Construct microblocks in chisel and bits since their API let's us tell them seared blocks are building blocks.

**Comment by JonasCiss** [comment]
Is this closed now ore is still something to do?

**Comment by bonii-xx** [comment]
At least on our side there's nothing to do.
