### ISSUE TITLE
Diamond modifier upgrades tool to the wrong level

### ISSUE THREAD

**Issue by benrtchai** [SlimeKnights/TinkersConstruct#3304]
Found in TConstruct-1.10.2-2.6.5

In-game documentation notes that the Diamond modifier should upgrade tool to obsidian level, however, the Diamond modifier only upgrades tool to diamond level.

**Comment by bonii-xx** [comment]
Hm, must've been copy'n'paste from the old modifier. It doesn't increase it to obsidian, it increases it by 1, up to obsidian. The book is wrong in this case.
