### ISSUE TITLE
Minecraft Control GUI Crash.

### ISSUE THREAD

**Issue by TheProBajao** [SlimeKnights/TinkersConstruct#3305]
I was downloading Minecraft Mods, i believe i download Little Tiles Mod and CreativeCore Mod. I found out, after installing and putting into mods folder, i launch the game, and then open the options, and then controls, then crashed. OMG, i need your help. I believe both of these mods are not compatible with some mods that are fit into it. Also, i installed Optifine but it can't affect those.

---- Minecraft Crash Report ----
// My bad.

Time: 12/28/17 10:37 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.client.gui.GuiListExtended.func_148181_b(SourceFile:53)
	at net.minecraft.client.gui.GuiControls.func_146286_b(SourceFile:81)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.GuiListExtended.func_148181_b(SourceFile:53)
	at net.minecraft.client.gui.GuiControls.func_146286_b(SourceFile:81)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiControls
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11.4
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1146352480 bytes (1093 MB) / 2528034816 bytes (2410 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 5 total; -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_E3 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJA	MobTest{1.0.3} [MobTest] ([1.7.10]MobTest-1.0.3.jar) 
	UCHIJA	satscapealarmcraft{1.0} [Alarmcraft] (Alarmcraft-Mod-1.7.10.jar) 
	UCHIJA	apocabuckets{1.2} [ApocaBuckets] (ApocaBuckets-Mod-1.7.10.jar) 
	UCHIJA	ArchitectureCraft{1.4.1} [ArchitectureCraft] (ArchitectureCraft-1.4.1-mc1.7.10.jar) 
	UCHIJA	BetterFoliage{2.0.14} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.14.jar) 
	UCHIJA	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	UCHIJA	CameraStudio{2.1710} [Camera Studio] (CameraStudioV2.1710(mc1.7.10).zip) 
	UCHIJA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCHIJA	CopiousDogs{${mcversion}-${version}} [Copious Dogs] (Copious-Dogs-Mod-by-wolfpupKG52-1.7.10.jar) 
	UCHIJA	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) 
	UCHIJA	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) 
	UCHIJA	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) 
	UCHIJA	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) 
	UCHIJA	creativecore{1.3.14} [CreativeCore] (CreativeCore-1.7.10.jar) 
	UCHIJA	CustomMainMenu{1.9.2} [Custom Main Menu] (Custom-Main-Menu-Mod-1.7.10.jar) 
	UCHIJA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (Custom-Mob-Spawner-Mod-1.7.10.zip) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJA	davincing{1710.1.8} [DaVincing] (DaVincing-1710.1.8.jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.1_1.7.10.jar) 
	UCHIJA	props{2.1} [Decocraft] (Decocraft-2.1_1.7.10.jar) 
	UCHIJA	jawser{1.0.0} [Decorative Videogame Systems] (Decorative Video Game Systems mod v1.5.0.jar) 
	UCHIJA	DeepSeaDiving{1.1.0} [DeepSeaDiving] (Deep-Sea-Diving-Mod-1.7.10.zip) 
	UCHIJA	Drinkcraft{v1.0} [Drinkcraft] (DrinkCraft Mod v1.0.zip) 
	UCHIJA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	Emotes{1.0} [Emotes] (Emotes-Mod-1.7.10.jar) 
	UCHIJA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.485.jar) 
	UCHIJA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.485.jar) 
	UCHIJA	ExtraPlanets{1.5.7} [ExtraPlanets] (ExtraPlanets-1.5.7.jar) 
	UCHIJA	eyemod{EyeOS4.1-1.7.10} [EyeMod] (Eyemod-Mod-1.7.10.jar) 
	UCHIJA	flansmod{4.8.0} [Flan's Mod] (Flans Mod-1.7.10-4.8.0.jar) 
	UCHIJA	howlingmoon{1.1.1} [Howling Moon] (Howling-Moon-Mod-1.7.10.jar) 
	UCHIJA	TeNNoX_KeyAndCodeLock{1.4} [KeyAndCodeLock] (Key-and-Code-Lock-Mod-1.7.10.jar) 
	UCHIJA	littletiles{0.1} [LittleTiles] (LittleTiles-Mod-1.7.10.jar) 
	UCHIJA	malisiscore{1.7.10-0.14.2} [MalisisCore] (malisiscore-1.7.10-0.14.2.jar) 
	UCHIJA	malisisadvert{1.7.10-0.4} [Malisis Advert] (malisisadvert-1.7.10-0.4.jar) 
	UCHIJA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJA	mcheli{1.0.2} [MC Helicopter] (mcheli) 
	UCHIJA	MinecraftDonalds{v6.0} [MinecraftDonalds] (MinecraftDonaldsMod v6.0.zip) 
	UCHIJA	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b.jar) 
	UCHIJA	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJA	musiccraft{2.9.9.3} [MusicCraft] (musiccraft-2.9.9.3.jar) 
	UCHIJA	NintendoSwitchMod{1.0.0} [NintendoSwitchMod] (NintendoSwitchMod_1.7.10.jar) 
	UCHIJA	Railcraft{9.12.2.0} [Railcraft] (Railcraft-Mod-1.7.10.jar) 
	UCHIJA	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2.jar) 
	UCHIJA	rivalrebels{1.7.10Y} [Rival Rebels] (Rival-Rebels-Mod-Yes-Oceans-1.7.10.jar) 
	UCHIJA	SophisticatedWolves{3.2.0} [SophisticatedWolves] (Sophisticated-Wolves-Mod-1.7.10.jar) 
	UCHIJA	tc{4.3.1_008} [Traincraft] (Traincraft-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.10.5.2 310.42.25f01' Renderer: 'NVIDIA GeForce GTX 675MX OpenGL Engine'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 675MX OpenGL Engine GL version 2.1 NVIDIA-10.10.5.2 310.42.25f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Pamplemousse-1.7.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E3
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 NVIDIA-10.10.5.2 310.42.25f01
	OpenGlRenderer: NVIDIA GeForce GTX 675MX OpenGL Engine
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by bonii-xx** [comment]
And you're posting this here because....?

**Comment by TheProBajao** [comment]
@bonii-xx , i knew i found out, i have creativecore and littlestilesblock makes control gui crashes in-game... i don't know will find out.

**Comment by bonii-xx** [comment]
And you're posting this in the Tinkers' Costruct issue tracker, specific to Tinkers' Construct issues, because?

**Comment by TheProBajao** [comment]
Oops, wrong post.
