### ISSUE TITLE
Aquadynamic isn't working

### ISSUE THREAD

**Issue by Zsashas** [SlimeKnights/TinkersConstruct#3306]
I put a Prismarine Shovel Head on my Mattock, but it's still vastly slower when underwater, trying to dig sand.

Other parts are a wooden tool rod and a pigiron axe head.

**Comment by bonii-xx** [comment]
Yes, a mattock is not a shovel. It will never dig sand fast. Use a shovel.

**Comment by Zsashas** [comment]
But it does have a shovel head, and it DOES normally dig sand faster than at least bare hands.

**Comment by bonii-xx** [comment]
No, it does not.
