### ISSUE TITLE
[1.12] MaterialEvent not working.

### ISSUE THREAD

**Issue by Mifesto** [SlimeKnights/TinkersConstruct#3307]
Hello, not working events MaterialRegisterEvent, StatRegisterEvent. 
Test example: https://pastebin.com/HVMzvsiC , registered in FMLPreInitializationEvent.
Result: https://pastebin.com/uYyu9YRU
Forge Version: 14.21.1.2443
Tinkers Construct Version: 2.8.1.515

**Comment by bonii-xx** [comment]
You need to load before TiC, or use a static handler. Since the materials are added during preinit, you need to register your handler before that.

**Comment by Mifesto** [comment]
Wow, thanks i used dependencies = "required-before: tconstruct @ [1.12-2.8,)" and earned.
