### ISSUE TITLE
Feature request: Lumber axe material blacklist

### ISSUE THREAD

**Issue by angrycloud** [SlimeKnights/TinkersConstruct#3308]
I seem to recall a previous version of TC having a blacklist config option for the lumber axe. This would be useful to disable the axe for Natura giant redwoods in particular. The list could be set to the blocks that the full felling ability would be skipped on.

Thanks

**Comment by bonii-xx** [comment]
Natura giant redwoods shouldn't cause any problems, though. They used to in old versions.

**Comment by angrycloud** [comment]
It doesn't seem to lag the server anymore but I was thinking more along the lines of protecting the trees. I have users that like to build bases in them. This eliminates intentional as well as accidentally demolishing a redwood.

Thanks

**Comment by bonii-xx** [comment]
Inconsistent behaviour of a tool is not desirable. You and your players will just have to refrain from using lumberaxes in/near their bases.
