### ISSUE TITLE
tools not destroyed when thrown to lava

### ISSUE THREAD

**Issue by hunter688** [SlimeKnights/TinkersConstruct#3309]
Tools from TC just jumping over lava instead be destroyed.

TC 1.12.2 2.8.1 49
Mantle 1.12-1.3.1.21

Forge 1.12.2 build 2559

No others mods installed.

**Comment by LoveFireAmi** [comment]
That's a feature... not a bug...

**Comment by bonii-xx** [comment]
TiC tools can't be destroyed, and they also don't despawn.
