### ISSUE TITLE
[1.12.2] About Mattocks and Gravel

### ISSUE THREAD

**Issue by Zsashas** [SlimeKnights/TinkersConstruct#3310]
I keep reading everywhere that Mattocks aren't supposed to dig sand, soul sand, or gravel, just dirt and grass. But they dig gravel faster for me. Intended? Oversight?

**Comment by bonii-xx** [comment]
No, mattocks are also not effective on gravel. They are effective on wood, plantlike materials, and ground/earth-like materials. Are you using a knightslime mattock?

**Comment by Zsashas** [comment]
Prismarine, Bone, and Netherrack. It definitely digs gravel much faster than by hand.
