### ISSUE TITLE
Wings crashed game

### ISSUE THREAD

**Issue by DarkfrostTheIceNightHybrid** [SlimeKnights/TinkersConstruct#3312]
I put on a pair of wings from the mod and it crashed my game, now, I can't use the world because I put them on, thus crashing the game when I open the world, ruining it forever...

**Comment by KnightMiner** [comment]
Crash report or it did not happen. We also don't have wings last I checked.

**Comment by TherminatorX** [comment]
Guessing the Traveller's Wings in the 1.7.10 version. If taken from NEI/JEI, tools and those armor pieces can be a bit strange.

You can access your world again by deleting your playerdata, or if you get an NBT editor, removing the item from that file

**Comment by KnightMiner** [comment]
Closing for lack of response. If you have a crash, we need a crash report to be able to do anything. The issue is probably like TherminatorX says
