### ISSUE TITLE
1.12.2 - Sword blade cast does not fit into a cast chest

### ISSUE THREAD

**Issue by Febilian** [SlimeKnights/TinkersConstruct#3313]
Every other cast I've tried will go into the cast chest, but the sword blade one specifically will not.

It also does not fit into a pattern chest, so it wasn't swapped or anything I suppose.

Using these mod versions:

TConstruct-1.12-2.8.1.49
Mantle-1.12-1.3.1.21

**Comment by bonii-xx** [comment]
That sounds really weird, there is no special treatment for that, all the tool casts are literally the same. But you can only have one of each type, so maybe you already have a sword cast in your chest? Can you give me a screenshot?

**Comment by Febilian** [comment]
Well, I'm a complete idiot. There is indeed already a sword cast in the chest. I don't remember _putting_ it in there but that's my problem, not yours. Apologies for taking your time.

**Comment by KnightMiner** [comment]
Closing as everything seems to work

**Comment by LoveFireAmi** [comment]
The confusion may have been if you played in the original TiC for 1.7.10 and below.  The cast chests worked a bit differently.
