### ISSUE TITLE
[1.12.2][2.8.1.49] Incorrect entity localization for Blue Slimes

### ISSUE THREAD

**Issue by reiyooki** [SlimeKnights/TinkersConstruct#3314]
While playing I've always seen the blue slimes with incorrect entity names and just assumed it was a bug caused by a compatibility problem on my end. Seems I was wrong. I took a look at the localization file and found that the mobs were indeed missing the correct name node, and adding it fixes the issue.

```
// TiC en_US.lang changes (Line 467-468)
entity.tconstruct.blueslime.name=Blue Slime // Original
entity.blueslime.name=Blue Slime // Fixed
```

**Comment by KnightMiner** [comment]
Please give a mod version, because I already fixed this in version 2.8.0. You should always lead issue reports with versions.

**Comment by reiyooki** [comment]
Mod version is listed in the title, sorry. 1.12-2.8.1.49

**Comment by KnightMiner** [comment]
Sorry, missed it as I was looking in the post body.

This is quite odd as we specifically localize the slime using our mod name. Can you point out where you are seeing the name? It should be correct on spawn eggs, so if is erroring in TOP or WAILA it would be good to know.

**Comment by reiyooki** [comment]
I noticed it in WAILA tips, as well as NEAT nameplates, both with and without the entity in the NEAT blacklist (Forcing it to use entityID rather than name.) I don't have TOP in my pack, so I'm not sure if it's erroring there too or not.

**Comment by bonii-xx** [comment]
I wonder if they use 2 different strings.. Maybe one is the unlocalized name, and the other the registry name. Either way they should match. Hm.

**Comment by bonii-xx** [comment]
@Vazkii what name/entry does NEAT use?

**Comment by KnightMiner** [comment]
Closing for lack of response, we can reopen if its found to still be an issue.
