### ISSUE TITLE
Reflecting arrows with battle sign causes crash.

### ISSUE THREAD

**Issue by Verlash** [SlimeKnights/TinkersConstruct#3315]
Version: TConstruct-1.12-2.8.1.49.jar

I'm not sure if the problem is with Tinker's Construct or with both HWYLA and The One Probe, but whenever I reflect a skeletons arrow with a battle sign and I am close enough to the skeleton for HWYLA or TOP to show their info the game crashes and gives this error:

```
The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraft.entity.monster.EntitySkeleton cannot be cast to net.minecraft.entity.EntityAgeable
```

However, if I am far enough away from the skeleton that HWYLA or TOP don't show the skeletons stats, then everything is fine, the arrow is reflected and I can kill skeletons with their own arrows, but as soon as their health is displayed and I reflect an arrow the game instantly crashes.

FYI I am playing using a custom modpack, no major config changes just some minor ones that can be done in-game. 

I've attached the crash report in-case that helps.

I have also uploaded video of the crash as it happens in game. Intentionally made video unlisted so that it can only be found using a direct link to the video, it cannot be found by simply browsing YouTube. I am using The One Probe with the Waila style preset in the video.

Video Link: https://youtu.be/NOrNltz7JUk

Crash Report: [crash-2018-01-01_12.10.40-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1596291/crash-2018-01-01_12.10.40-client.txt)

**Comment by bonii-xx** [comment]
>at com.pam.llamamilking.events.LlamaMilkingEvent.onEntityInteract(LlamaMilkingEvent.java:31)

llamamilking mod is making some wrong assumptions it seems, and missing safety checks. Report to mod author. Not TiC related.

**Comment by Verlash** [comment]
Oh, ok, my bad, I'll go report it to MatrexsVigil then, since llamamilking is part of the Pam's HarvestCraft addons.
