### ISSUE TITLE
Error in preinit

### ISSUE THREAD

**Issue by temp1011** [SlimeKnights/TinkersConstruct#3316]
`[14:18:44] [main/ERROR]: Compat module for tconstruct could not be preInitialized. Report this!`
Using Direwolf20-1.12.2-1.4.0 which has TC 2.7.4.34. I'm just following the logs.
EDIT:
forge 14.23.1.2566

**Comment by KnightMiner** [comment]
First off, you are using an outdated version of Tinkers Construct, update.

Secondly, for that to be useful, you need the full log. That one line is useless.

Thirdly, that is a company module for Tinkers Construct, so it's added by another mod, not us.

----

Figure out which mod adds that module, ensure you have the latest versions, the report yhebossie to them with the full log (on put the log on pastebin and link it in the issue)
