### ISSUE TITLE
[1.12.2] Dupe Bug

### ISSUE THREAD

**Issue by GWSheridan** [SlimeKnights/TinkersConstruct#3321]
When mining sea lanterns with silk touch on tinkers tools. You get lantern, Prismarine crystals an shards back. Just placing a few lanterns in off hand an high speed pickaxe you get multiple shards crystals an lanterns

Tinkers: 2.8.1.49
Forge: 14.23.1.2583
Minecraft: 1.12.2

**Comment by KnightMiner** [comment]
What happens when you break it with a normal silk touch tool? All Tinkers silktouch does is add the vanilla enchantment.

**Comment by GWSheridan** [comment]
Does it with vanilla tools
