### ISSUE TITLE
[1.12.2] [2.8.1.49] Crafting Station server hang

### ISSUE THREAD

**Issue by shortybsd** [SlimeKnights/TinkersConstruct#3322]
Forge 2582
Minecraft 1.12.2
TConstruct-1.12-2.8.1.49
Mantle-1.12-1.3.1.21

When placing multiple Crafting Stations (2 or 3) side by side and use the InventoryTweaks mod where you hit the plus and it puts the materials for the recipe in the table the server locks up. Physically locks, no response on console. Figured it might have something to do with the tables themselves looking for an adjacent inventories and bugging out or InventoryTweaks not knowing which table to place it in. I have done this same thing in the past (older 1.11 versions) with no issues.

**Comment by KnightMiner** [comment]
Please give a full server log (paste it on pastebin and link it here). Hard to tell whether this issue is on our side or not without it

**Comment by shortybsd** [comment]
See that is the problem, no errors show up under the forge logs. The server physically freezes. Commands typed in console do nothing. I have to force close the server. It might be Inventory tweaks seeing 2 or 3 different inventories and when trying to place the set pattern for recipe it breaks. I will load up a new environment and test with only your mod and Inventory tweaks, will also load in a debugger and jstatd to help find the cause.

**Comment by bonii-xx** [comment]
Sounds like your typical endless loop. This might be caused by the two crafting stations trying to find a matching recipe at the same time.

**Comment by bonii-xx** [comment]
Seems to be and issue with crafting stations interacting with each other. They really shouldn't do that.
