### ISSUE TITLE
[Suggestion] Set a cap for how much XP can mending moss'd tool store inside.

### ISSUE THREAD

**Issue by SHIuSH** [SlimeKnights/TinkersConstruct#3323]

**Comment by laz2727** [comment]
It's supposed to be capped.

**Comment by KnightMiner** [comment]
Its capped based on your mending moss level, should be 100 at level 1, 300 at level 2, and 900 at level 3. Can you verify if there is no cap?

**Comment by SHIuSH** [comment]
I just didn't find any numbers about the mending moss and thought it was capless, not in wiki's, not in configs, not in the book. I guess I never actually reached the required XP

**Comment by KnightMiner** [comment]
> Max. Amount stored increases with modifier level

You mean that sentence? We don't make the wikis, and it's not configurable for consistency.
