### ISSUE TITLE
Crossbow won't shoot bolts

### ISSUE THREAD

**Issue by TheRoyalReaper** [SlimeKnights/TinkersConstruct#3326]
While playing on a server with friends I've built a crossbow and created 2 types of bolts.
I tried shooting the bolts, I loaded them and it showed the crossbow loaded with a bolt type, when I shoot, at a friendly and hostile creatures, it unloads but doesn't hit the enemy/friend.
I tried relogging but the issue stays, the issue does not appear on single player.

TiCon Version: TConstruct-1.12-2.8.0.45
Forge version: forge-1.12.2-14.23.1.2584

**Comment by TheRoyalReaper** [comment]
I tried updating the server tinkers' version - the same as mine - TConstruct-1.12.2-2.9.0.55
the problem is still the same, can't shoot the bolt, not even at the wall

**Comment by bonii-xx** [comment]
Sounds like something is wrong with your server and/or other mods mess things up. Check if it happens in singleplayer or with only tic&mantle.

**Comment by TheRoyalReaper** [comment]
I tried it on single player with the same mods as the server and the problem isn't there, I don't know what else it could be.

**Comment by bonii-xx** [comment]
Is the server running sponge?

**Comment by TheRoyalReaper** [comment]
not that I'm aware of, I've built it like normal on a laptop.

**Comment by bonii-xx** [comment]
See if you can find any errors in the server log when shooting.

**Comment by TheRoyalReaper** [comment]
when I shoot and look at the logs, no change is appearent, the same lines are shown

**Comment by bonii-xx** [comment]
Then all you can do is identify the mod that causes it.

**Comment by TheRoyalReaper** [comment]
but when playing with same mods in single player I have no problem shooting bolts

**Comment by KnightMiner** [comment]
@TheRoyalReaper see if you can reproduce this with a minimal mod list. While it may be the same list, the issue might be caused by just one mod on the server.

**Comment by KnightMiner** [comment]
Closing for a lack of response, we need a minimal list to reproduce to do anything
