### ISSUE TITLE
Well-Established modifier only works when tool is held

### ISSUE THREAD

**Issue by Nyny2121** [SlimeKnights/TinkersConstruct#3329]
**Version info:**
`Minecraft: 1.12.2`
`Forge: 14.23.1.2586`
`Mantle: 1.3.1.21`
`Tinkers' Construct: 2.8.1.149`
**Report Information:**
Lumber axes do not give experience from the well-established modifier given by copper parts unless they are in your hand. The gif below shows this happening.

![ezgif-5-898fa13778](https://user-images.githubusercontent.com/17759774/34762124-2fd27fe8-f5ac-11e7-9692-844c1a8b4e14.gif)

**Comment by bonii-xx** [comment]
That's how block breaking works in general. The Lumberaxe is a bit special because it doesn't do it all at once for performance reasons. Probably not fixable without major hacks.
