### ISSUE TITLE
Missing mod

### ISSUE THREAD

**Issue by No-Fa** [SlimeKnights/TinkersConstruct#3330]
Every time I launch up forge it mention that I am missing a mod. I was wondering where I can download the mod.

**Comment by alexbegt** [comment]
Does it say you are missing "Mantle"? If so, download it from https://minecraft.curseforge.com/projects/mantle

**Comment by No-Fa** [comment]
No I already have that downloaded, it says that I am missing forge- when I am on forge.


On Jan 10, 2018, at 8:48 PM, Alexander (alexbegt) <notifications@github.com<mailto:notifications@github.com>> wrote:


Does it say you are missing "Mantle"? If so, download it from https://minecraft.curseforge.com/projects/mantle

**Comment by alexbegt** [comment]
Oh you need to have the latest version of Forge, 14.23.1.2587, which if you go on http://files.minecraftforge.net/ and download the latest, or if you are using the curse (twitch) launcher, view the profile, click the three dots, and select "forge-14.23.1.2587"

**Comment by No-Fa** [comment]
Ok thank you.

**Comment by KnightMiner** [comment]
Closing this since it was solved
