### ISSUE TITLE
Add support for casting time in CastingRecipe

### ISSUE THREAD

**Issue by DJJBanx** [SlimeKnights/TinkersConstruct#3332]
Currently, the CastingRecipe class has separate declarations as so:

```
public CastingRecipe(ItemStack output, RecipeMatch cast, Fluid fluid, int amount, int time) {
    this(output, cast, new FluidStack(fluid, amount), time, false, false);
  }
```
and 
```
public CastingRecipe(ItemStack output, RecipeMatch cast, Fluid fluid, int amount, boolean consumesCast, boolean switchOutputs) {
    this(output, cast, new FluidStack(fluid, amount), calcCooldownTime(fluid, amount), consumesCast, switchOutputs);
  }
```

This allows for switchOutputs and consumeCast to be set, and also allows for time and amount to be set. However, it does not allow for all four variables to be set. To allow for ModTweaker to add support for casting time, could you add a method that includes all four variables, or add support to modify casting time as well as modify consumeCast, switchOutputs, and amount, or make the variables to non-final.

Example:
```
public CastingRecipe(ItemStack output, RecipeMatch cast, Fluid fluid, int amount, boolean consumesCast, boolean switchOutputs, int time) {...}
```

jaredlll08/ModTweaker#583

**Comment by KnightMiner** [comment]
Have you maybe tried [this constructor](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/smeltery/CastingRecipe.java#L40)? All our constructors just call another one.

**Comment by DJJBanx** [comment]
Yes, You could use that and specify 
```
fluid = new FluidStack(fluid, amount);
```
Thank you for the specification, I must've missed that.
