### ISSUE TITLE
Hammer can mine irrespective of hardness on last use

### ISSUE THREAD

**Issue by ravenascendant** [SlimeKnights/TinkersConstruct#3333]
v 1.12 2.7.4.34
in modpack DW20 1.12 1.4.0
with the following added: clarity 1.1, coroutil 1.12.1-1.1.24 and weather2-1.12.1-2.5.7 

example case: D diamond ore S stone
DDD
SSS
SSS

mining that 3x3 with a stone hammer with 2 durability will break all 9 dropping 6 cobble and 3 diamonds

having the three diamonds on the bottom will instead leave just the bottom right block. mining the other two diamonds and all the stone.

I have tested this with other ores (including ardite), obsidian and unbreakable vanilla blocks, with the same behavior in all cases.
Discovered in normal play with iron headed (all three parts) wooden handeled hammer.
confirmed with all wood hammer from creative menu.
most testing done with creative menu all stone hammer because it is easy to wear down.

**Comment by KnightMiner** [comment]
Does this still happen in Tinkers Construct 2.9.1? fbcd6e2 might have addressed the issue.

**Comment by KnightMiner** [comment]
I cannot reproduce this in the current version, does it still happen for you @ravenascendant ? I tested using a paper hammer with max redstone to mine gold ore. It cannot mine the ore whether I am at full durability, 1 durability, or 1 durability mining the stone next to an ore.

**Comment by ravenascendant** [comment]
The behavior no longer occurs in version 1.12.2-2.12.0.157

it will now only mine a number of blocks equal to durability +1 and selects the blocks mine able by the tool.
