### ISSUE TITLE
a weird output that leads to a crash

### ISSUE THREAD

**Issue by TheRoyalReaper** [SlimeKnights/TinkersConstruct#3334]
when using the slimesling and slime boots on on our server we seem to have recieve a weird output in the server console:
it seems to be a repeating message non stop until the action stops- for example, when the player stops bouncing with the slime boots
pastebin: https://pastebin.com/JiaQGmq0

**Comment by bonii-xx** [comment]
This is a network issue. Probably some other mod messing with it. Try reproducing with only TiC and Mantle.

**Comment by yepidoodles** [comment]
Hello, I'm also getting this issue - Unfortunately I do not have the capacity to run a test server at the moment (Currently running a public one).
I'm running a decent size modpack on a SpongeForge server (Version 1.12.2-2555-7.1.0-BETA-2837). Hasn't caused any crashes, however. Happy to provide additional information - Error same as above.

**Comment by bonii-xx** [comment]
Yes, the packets are only for movement and shouldn't cause crashes. However THAT they happen is a sign that something is wrong with networking. Can you try without sponge? Might be there's some hickup with it.

**Comment by RedNesto** [comment]
I was able to reproduce it without Sponge:
https://gist.github.com/RedNesto/42eeb7d4320168d7f9b63a60cc98fbe7

`Mantle-1.12-1.3.1.21` and `TConstruct-1.12.2-2.9.0.55`

However it seems really hard to reproduce, totally random.

**Comment by ryantheleach** [comment]
https://www.youtube.com/watch?v=xjReCJL_40s&feature=youtu.be

**Comment by sathelate** [comment]
hi, just wanted to join in in this :)

exact same setup as RedNesto and exact same result.

does not crash or anything, just gives wrong packet thingy ;) 

So if i anyhow need to also send a log or something so i can help as well, lemme know :) 

Thanks :D

**Comment by bonii-xx** [comment]
Thanks to @RedNesto I was able to reproduce the issue, and now I also know what the actual issue is.

**Comment by Krosta8** [comment]
Hello,
I saw, that it was resolved six days ago. Is it possible to get this fixed version? The spam in console is really bad :(
Thank you

**Comment by KnightMiner** [comment]
We are not in the habit of releasing a version for every fix, especially when this one does not affect gameplay.
