### ISSUE TITLE
Using the scythe on cobweb crashes the game

### ISSUE THREAD

**Issue by Mysteroo** [SlimeKnights/TinkersConstruct#3337]
Hosting a Lan server, had a Pig-Iron Scythe in an abandoned mineshaft.

Tried using it on some cobwebs - don't remember if I attacked or right clicked, but regardless it crashed the server when I tried to do it. Then again when I tried after restarting.

**Comment by KnightMiner** [comment]
If it crashed, we need the crash report. Please post it to a site such as pastebin then link it here.

**Comment by temp1011** [comment]
I've recreated this. Just Tinker's 2.9.0.55 and Mantle 1.3.1.21
[crash report](https://github.com/SlimeKnights/TinkersConstruct/files/1637031/crash-2018-01-16_22.13.33-client.txt)

Harvest level not set?

**Comment by KnightMiner** [comment]
Seems getToolClass is being called with a null string. I assumed that was not valid, but it shouldn't hurt to avoid that.
