### ISSUE TITLE
Grout uncraftable

### ISSUE THREAD

**Issue by Creatress** [SlimeKnights/TinkersConstruct#3338]
I really like this mod but I'm running it through Feed The Beast and I can't seem to craft grout. It's really important to the mod that I am able to do this. Please help!

**Comment by LoveFireAmi** [comment]
Pack name?  Pack version?  Mods?  Mod versions?  Forge version?  Minecraft version?

Are you sure it's not just disabled by the pack?

We need more information to help you on your issue...

**Comment by Creatress** [comment]
ok let me take a look
*Pack name - Regrowth v1.0.2
*Forge- not sure because FTB downloads the mods and runs them itself
*Mods- Ok this one is long and I've tested it without any extra mods
It keeps saying that I'm not running the right version, But I'm running v1.7.10 v1.8.8 of the mod so I'm confused
*Minecraft v1.7.10
*It's not disabled and the error message is "Forge Mod Loader has found a problem with your minecraft installation. The mods and versions listed below could not be found. Mantle: minimum version required is 1.7.10-0.3.2. The file 'logs/fml-client-latest.log' contains more information"

**Comment by Creatress** [comment]
Okay quick update_
I found and reenabled Mantle and now the problem is gone. Should I spend time going through the loads of mods to find which one caused the problem?

**Comment by LoveFireAmi** [comment]
Regrowth is a custom pack that disables some recipes and alters others on purpose.  I suggest you look through a guide.

**Comment by LoveFireAmi** [comment]
I even looked it up for you...
https://forum.feed-the-beast.com/threads/cant-make-grout-regrowth.104924/

**Comment by Creatress** [comment]
Ok, thank you for the help!
