### ISSUE TITLE
[1.12.2 TC 2.9.0.55] Slime boots constantly spam server errors

### ISSUE THREAD

**Issue by shortybsd** [SlimeKnights/TinkersConstruct#3339]
Minecraft 1.12.2
Forge 2582
TC 2.9.0.55
Mantle 1.3.1.21

Constantly spams server [this error](https://pastebin.com/0dVdXep8) over and over with anyone who wears slime boots and jumps off a cliff
"FMLIndexedMessageCodec exception caught java.lang.RuntimeException: Missing" 
Take off boots and errors go away from console.

**Comment by bonii-xx** [comment]
#3334

**Comment by shortybsd** [comment]
Ahh thank you, will test soon.
