### ISSUE TITLE
Item frame tweak

### ISSUE THREAD

**Issue by Aregev2** [SlimeKnights/TinkersConstruct#3342]
It's just a tiny tiny suggestion that I hope it will make it into the mod

Make item frame be placeable on the ground and ceiling, like the upcoming 1.13. 
It's a great idea in my opinion, it will make things cooler especially with the clear item frame. 

Thanks 
Aregev2

**Comment by SweetSugarSugar** [comment]
TiC doesn't usually modify the behavior of vanilla blocks... but perhaps this could go on the Clear Item Frame...

**Comment by bonii-xx** [comment]
They're just different variants of the vanilla frame, no plans on extending behaviour, although it would be nice. There's too much hardcode in vanilla and it'd require our own implementation.

**Comment by Aregev2** [comment]
I'm using quark so I got this feature
Thanks
Aregev2

**Comment by KnightMiner** [comment]
Quark implements this separately. We just use vanilla behavior. When 1.13 cones our frames will have this behavior
