### ISSUE TITLE
Auto-Smelt and Fortune  Version 1.10.2 dosnt work

### ISSUE THREAD

**Issue by Shadow23Master** [SlimeKnights/TinkersConstruct#3344]
![image](https://user-images.githubusercontent.com/35620390/35180124-604bc8c8-fda9-11e7-82e1-164ae46885ee.png)
![image](https://user-images.githubusercontent.com/35620390/35180163-2c04eed6-fdaa-11e7-8c72-8fbcea2fc7a7.png)
![image](https://user-images.githubusercontent.com/35620390/35180166-4e0f9242-fdaa-11e7-9040-55af0e25b001.png)

**Comment by KnightMiner** [comment]
We do not add any vanilla enchantments. That config option is only for our modifier. Check which mod adds autosmelt as a vanilla enchantment.

**Comment by SweetSugarSugar** [comment]
This isn't even Tinkers' Construct related...
