### ISSUE TITLE
Chainmail armor can't be smelted into steel

### ISSUE THREAD

**Issue by SpittingBull** [SlimeKnights/TinkersConstruct#3345]
Looks like chainmail armor can not be smelted into steel. I am not using any other mod with steel recipes.

Using TConstruct-1.12.2-2.9.0.55.jar and forge-1.12.2-14.23.1.2598-installer.jar.

**Comment by KnightMiner** [comment]
Pretty sure this was intentionally removed. In 1.7 steel was simply the only material added which Tinkers did not provide a way to produce, hence the chainmail recipe. Now it only adds those materials if another mod adds them so there is no need for a workaround recipe. Just install a mod which adds a proper steel recipe.
