### ISSUE TITLE
[1.12.2] Smeltery wont smelt even after adding lava

### ISSUE THREAD

**Issue by Mexicanplayer97** [SlimeKnights/TinkersConstruct#3347]
MC 1.12.2
Forge 1.12.2-14.23.1.2577
Tinker Version 1.12.2-2.9.0.55

When having an item to smelt and there is no heat. It shows a blue bar saying not enough heat. After adding lava to the smeltery, it still shows no heat.
![before heat](https://user-images.githubusercontent.com/35642723/35189015-a7808dd8-fe07-11e7-8ed3-ae6a5be4dd77.PNG)
![after heat](https://user-images.githubusercontent.com/35642723/35189016-a9fc8b3e-fe07-11e7-8682-b35f57830ad4.PNG)

And even after walking away, and coming back it alternates between no heat and starting to smelt but it stays stuck at low level. 1min after adding lava
![after 1min of heat](https://user-images.githubusercontent.com/35642723/35189018-c36808dc-fe07-11e7-9f6c-e65305ad984e.PNG)

after taking this snip, it changed back to no heat blue bar.

**Comment by TherminatorX** [comment]
Picture of your smeltery multiblock please?

**Comment by bonii-xx** [comment]
Take the ore out and put it back in, I think there's an issue when it started with no lava.

**Comment by Mexicanplayer97** [comment]
Apologies on the late reply, I am currently out of town. 

Removing and replacing the ore does fix the issue. 

I have a 3x3 base with the next layer being a 5x5 with no corners.
B= brick
N= no block
SC= Smelt controller
D= Drain 
T= tank

N |  B  |  B  |  B | N |
B  |  N |  N |  N | B |
B  |  N |  N |  N | B |
D |  N |  N |  N | D |
N  |  B |  SC |  T | N |

Ill upload pictures when i remote in to my computer later.

**Comment by TherminatorX** [comment]
If the issue is resolved, then further images are not required.

**Comment by bonii-xx** [comment]
Leave it open, as a reminder. We'll handle it.
