### ISSUE TITLE
Latest version of TConstruct may be crashing when using custom texture packs

### ISSUE THREAD

**Issue by ScottKillen** [SlimeKnights/TinkersConstruct#3348]
See John-Smith-Modded/JSTR-Modded-1.12.x#2

**Comment by Oddface** [comment]
This seems to affect all 1.12 versions and causes the game to crash during texture stitching when using these model files: https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/commit/9d6faed71b12634f7dfbbe0d2d895cd95e780beb which only change the location of the handle textures. The same files work perfectly in 1.10 and 1.11.

**Comment by KnightMiner** [comment]
Closing as it appears to be fixed on JSTR's side. No one really knows why it crashed in the first place
