### ISSUE TITLE
Punji Stick Crash

### ISSUE THREAD

**Issue by BjoernUsw** [SlimeKnights/TinkersConstruct#3352]
my game crashes when zombies share a block with punji sticks.
MC version: 1.10.2
TC version: 2.6.5
[crash-2018-01-26_13.22.01-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1667678/crash-2018-01-26_13.22.01-server.txt)

**Comment by KnightMiner** [comment]
This crash is not a TConstruct one, it points to TTLBowAddon
