### ISSUE TITLE
Not a issue, A question 

### ISSUE THREAD

**Issue by Adarcer** [SlimeKnights/TinkersConstruct#3354]
I am making a modpack and am including some new melting recipes thro crafttweaker, but something seems off the blocks and dusts are melting too fast for my liking. I was able too find the melting temperature of copper on iron on tconstuct wiki but cannot find anything on melting temperature of common modded and vanilla ores like alum, tin. gold, coal, emerald, nickel, lead, silver. I would like too keep melting balanced

**Comment by bonii-xx** [comment]
The temperatures and hence the heat and time required to melt are balanced around real world relations (and how it makes sense). The individual recipes then depend on the output - an ingot melts faster than a block of the same material.
There is a way to manually set melting duration, but I don't know if crafttweaker supports it. The overall temperature of fluids can't be changed without replacing the fluid.
