### ISSUE TITLE
[1.12] TiC 1.10.2-2.6.5 off-hand bow not rendering issue

### ISSUE THREAD

**Issue by touhouzun** [SlimeKnights/TinkersConstruct#3355]
minecraft version:1.10.2
forge version:12.18.3.2511
mantle version:1.1.5
Tinker's Comstruct version:1.10.2-2.6.5.10
I have checked several times to confirm:It's not mantle's issue
All configs default
Using superflat world
when you hold a bow in your offhand:
![2018-01-27_18 17 06](https://user-images.githubusercontent.com/31458903/35471002-83c51db4-038e-11e8-8df1-16c3df53e186.png)
when you pull it:
![2018-01-27_18 18 26](https://user-images.githubusercontent.com/31458903/35471010-949912f8-038e-11e8-9db7-90b564613fa4.png)
mainhand:
![2018-01-27_18 18 53](https://user-images.githubusercontent.com/31458903/35471018-a5ce9534-038e-11e8-918a-62ed946a509d.png)
![2018-01-27_18 18 56](https://user-images.githubusercontent.com/31458903/35471036-e7eaf746-038e-11e8-866d-f1b08b25a4dc.png)
I know 1.10.2 branch of TiC is no longer supported.Could anyone reproduce this issue and make a fix?
emmmm......_(:з)∠)_

**Comment by touhouzun** [comment]
also
cpu:intel i7 6500u(notebook)
memory:8g
gpu:nvidia geforce 940m notebook
system:win10

**Comment by bonii-xx** [comment]
Confirmed to still be an issue in 1.12.
There will be no fix for 1.10.2, even if somebody would port it back to 1.10. We do not release new versions for unsupported versions.

**Comment by Aregev2** [comment]
Just confirmed, does not happen in 1.12

**Comment by Aregev2** [comment]
Hopefully

**Comment by Elwood0** [comment]
Tested, TConstruct-1.12.2-2.12.0.135 has the Bow issue as well, both for vanilla bows, and any of the construct bows. Crossbows are fine though at least

**Comment by KnightMiner** [comment]
Fixed by d398c58
