### ISSUE TITLE
[1.7.10] Ticking entity crash from successfully killing a mob from bolts of a crossbow

### ISSUE THREAD

**Issue by FN343** [SlimeKnights/TinkersConstruct#3357]
It tends to happen almost every time I successfully shoot a mob with my crossbow... it used to not do this all the time... I'm sorry that it's an older MC version as well (It's the latest 1.7.10 version)...

Here's the crash report...
[https://pastebin.com/7HnzFAnf](url)

**Comment by FN343** [comment]
Oh, I forgot to mention, it was happening in the Nether...

**Comment by TherminatorX** [comment]
1.7.10 is no longer a supported version. Can you reproduce the issue in 1.12?

**Comment by FN343** [comment]
Um... I haven't done that... but from what I've noticed, FastCraft was updated and that might be doing something because, before the update, this didn't happen... I'll backport and see if I can fix it but, in terms of 1.12... yeah, that'll take some time, lol, but I don't think this issue is prevalent in that new version...

**Comment by KnightMiner** [comment]
This is not a Tinkers Construct issue, it is caused by `thexfactor117.levels`. Also, as stated 1.7 is no longer supported.
