### ISSUE TITLE
[ver. 1.10.2-2.6.3]Seared Bricks are handeled as Seared Stone

### ISSUE THREAD

**Issue by RoManInv** [SlimeKnights/TinkersConstruct#3359]
As title said, the Seared Bricks are treated as Seared Stone. The item-id shows that it is the same as Seared Stone. See pictures below.

Additionally, I have used jre version 8u121, 8u151 and 9.0.4(latest), all of which can cause this problem. 
![mc1](https://user-images.githubusercontent.com/13542137/35541757-99129c58-055c-11e8-92ce-38a28ff95c24.png)
![mc2](https://user-images.githubusercontent.com/13542137/35541758-992e38be-055c-11e8-8e7e-30398f6c1a6b.png)

**Comment by KnightMiner** [comment]
Yes, they share a block ID and use metadata, vanilla does that too. As for it appearing wrong in Wails, that is a bug in Wails as we properly implement the vanilla methods for metadata.

**Comment by RoManInv** [comment]
I’d like to know how could I get rid of this bug?

**Comment by RoManInv** [comment]
I mean, I cannot create a Smeltery with this block. The structure was right. I’m wondering if the wrong item ID caused this problem. I searched a lot of possible info and I didn’t get a solution.

**Comment by KnightMiner** [comment]
You certainly can create a structure with any seared block. Please give screenshots of the smeltery so we can see the issue (normally the issue is forgetting a tank within the structure, note the corners of the smeltery is not part of the smeltery)

**Comment by RoManInv** [comment]
Thank you. The mod was not bugged. My game crashed. I didn't realise it until nearly all the plants, grass blocks and trees began to disappear and became transparent. When I moved my save file to a normal Minecraft, it automatically became a normal smeltery. 
![mc1](https://user-images.githubusercontent.com/13542137/35710237-abc28b72-07b6-11e8-9f0e-a889b96b4c27.png)
