### ISSUE TITLE
Smelter causing rendering problem

### ISSUE THREAD

**Issue by Kiritow** [SlimeKnights/TinkersConstruct#3361]
Minecraft 1.10.2
TConstruct 1.10.2-2.6.5
Forge 1.10.2-12.18.3.2511
Mantle 1.10.2-1.1.5
Problem:
Client's screen stuck when facing a smelter built by one of the players on Server. The server log and client log doesn't have any message about the stuck. The server is not down and players in other chunks act normally. And the client is not crashed but FPS drops down to nearly 1. (The scene won't move) .
We have stopped the server and checked the world file with MCEdit and found this.

![tconstructissuereport_mcedit](https://user-images.githubusercontent.com/13619158/35629483-b5c23e3e-06d9-11e8-93dc-9dda4d7178dc.jpg)

I downloaded the world and open it in single player mode. It still gets stuck while looking at it or about to looking at it. And after several minutes, the following picture is captured.

![tconstructissuereport_ingame](https://user-images.githubusercontent.com/13619158/35629656-225c4e0e-06da-11e8-88fe-5eef75dac121.png)

**Comment by bonii-xx** [comment]
This looks really weird. I assume it's caused by the liquids inside the smeltery. Does the crash-shortcut work? It might give us the NBT data of the smeltery. Otherwise see if you can extract it via MCEdit.

**Comment by KnightMiner** [comment]
@Kiritow: any update?

**Comment by Kiritow** [comment]
No liquid is found via MCEdit. Blocks in the smeltery are all air block.
The game is not crashed (only get very slowed, fps<1) so there's no available crash reports.
After a deep investigation, we found this bug was used to stuck others clients by some evil players. It is said that the problem can be reproduced by jumping into the smeltery holding some "bug" items in hand. But we still don't know what these "bug" items are.
We have banned players with malicious acts at the moment.

**Comment by KnightMiner** [comment]
Can you give a full copy of whatever NBT you found in the smeltery, even if it has no liquids? it might help determine what those "bug" items are. As for the crash, boni means force a crash by holding F3 and C (normally takes around 5 seconds, but the lag might make it take longer)

**Comment by Kiritow** [comment]
Here are some screenshots about the NBT data. I am using MCEdit-Unified.
![pic1](https://user-images.githubusercontent.com/13619158/37251752-f6b254a2-2550-11e8-82e5-f2a51ae8d1d9.png)
![pic2](https://user-images.githubusercontent.com/13619158/37251756-fc1414c6-2550-11e8-81f0-83392887ed53.png)
![pic3](https://user-images.githubusercontent.com/13619158/37251759-fe157b2a-2550-11e8-8852-b8ce128470f9.png)
![pic4](https://user-images.githubusercontent.com/13619158/37251762-ffa4a9a2-2550-11e8-97fa-94a64bad141f.png)
![pic5](https://user-images.githubusercontent.com/13619158/37251764-013b1f94-2551-11e8-88c2-cb655db6f567.png)

**Comment by bonii-xx** [comment]
Needs the NBT of the Smeltery Controller. That one has all the fluid data.

**Comment by Kiritow** [comment]
Can not find Smeltery controller... What if I send the world archive to you to help analyze the problem ... ?

**Comment by KnightMiner** [comment]
Closing for lack of response and as no one else has had a similar issue. If you can find that NBT please comment and we can reopen.
