### ISSUE TITLE
[1.12.2] Weird bug getting randomly on server.

### ISSUE THREAD

**Issue by Krosta8** [SlimeKnights/TinkersConstruct#3362]
Hello,
I don't know, if this bug is specifically caused by Tinker's Construct, but there is lines 21 and 22, where is this:
`	at slimeknights.tconstruct.common.TinkerNetwork.sendToServer(TinkerNetwork.java:98) [TinkerNetwork.class:?]
	at slimeknights.tconstruct.gadgets.item.ItemSlimeBoots.onFall(ItemSlimeBoots.java:168) [ItemSlimeBoots.class:?]`
Here is the full single error: https://hastebin.com/ubulininar.rb
Before this update to latest version was everething OK.
I'm using:
Tinker's Construct 1.12.2-2.9.0.55
Mantle 1.12-1.3.1.21
Forge 14.23.1.2586
SpongeForge 1.12.2-2586-7.1.0-BETA-2868

**Comment by bonii-xx** [comment]
#3334 Spongeforge related
