### ISSUE TITLE
[MC 1.12.2] [TiC 2.8.1.49] [CC 0.0.809.0] CubicChunks prevents slime islands from generating.

### ISSUE THREAD

**Issue by benjaminbech02** [SlimeKnights/TinkersConstruct#3363]
I've noticed that the CubicChunks mod seems to disable the generation of slime islands for overworld + nether _(Haven't tested The End)_, _(Magma islands generate normally)._ Curious to see if this truly was due to CC, i generated a new world with CC generation with a slime rate of 100 chunks, and flew around for a good 15 minutes. Nothing. I assume it's due to the way CC breaks up the chunks into 16x16x16 areas instead of 16x16x256, which seems to mess with TiC's generation. I'm not even close to being an expert though, so i might be terribly wrong.

**I'd love to see this fixed, as i'd rather not want to start over again on my survival worlds with the vanilla Y-cord limit.**

**Please tell me if you need additional information.**

**Comment by bonii-xx** [comment]
I have no idea what CubicChunks is, but from what you say: Well, if it generates 16x16x16 you'll probably need to fly high enough for the chunks with slime islands to generate. Or CubicChunks breaks checks if chunks are already generated, in which case it'll break worldgen for all mods that do it properly.

**Comment by benjaminbech02** [comment]
How foolish of me, i didn't try to check higher than the "normal" height for slime island generation. I'll try this out tomorrow.

**Comment by benjaminbech02** [comment]
Alright, i finally got around to try this out. Still nothing :/.
Do you think there is a way for me to change this myself, or would it require a major change to make it fit in with CC's generation?

**Comment by bonii-xx** [comment]
Since I don't know what CC does internally, I don't know. You'd probably need the CC dev to investigate it.

**Comment by benjaminbech02** [comment]
I'll see if i can get in touch with the guys over at CC.
I apologize if i wasted your time.

**Comment by benjaminbech02** [comment]
**Creating a world with a non-CC world type seems to reenable the slime islands. I was using one of CC's own types, so that might explain the problem.**

**Comment by bonii-xx** [comment]
Hm, they might have their world flagged incorrectly then.
