### ISSUE TITLE
Console bleeds with T.construct error

### ISSUE THREAD

**Issue by Foxgreat** [SlimeKnights/TinkersConstruct#3368]
-Forge version: 2586
- SpongeForge version:  2884
- Java version:  161
- Operating System: CentOS 7
-TConstruct: 1.12.2-2.9.0.55
------------------
Plugins (18): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, EconomyLite, GriefPrevention, Holograms, 
JdaLibraryLoader, KeepInventorySponge, LuckPerms, MCClans, MMCReboot, MMCTickets, Nucleus, PlayerShopsRPG, UltimateChat, WorldEdit
/
Mods (71): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Rocketry, Advanced Rocketry Core, Animania, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, AutoRegLib, B.A.S.E, BD Lib, Baubles, Biomes O' Plenty, Chameleon, Chunk Pregenerator, Clumps, CodeChicken Lib, ContentTweaker, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Elevator Mod, Enchiridion, Extra Cells 2, Extreme Reactors, FoamFix, Forestry, Galacticraft Core, Galacticraft Planets, Guide-API, Immersive Engineering, Industrial Wires, IndustrialCraft 2, Inventory Pets, IvToolkit, JourneyMap, Just Enough Items, LagGoggles, MTLib, Mantle, Mekanism, MekanismGenerators, MekanismTools, Micdoodle8 Core, Moar Tinkers, Mod Tweaker, NetherPortalFix, PneumaticCraft: Repressurized, Quark, Quick Leaf Decay, Redstone Flux, Spartan Shields, Storage Drawers, Storage Drawers Extras, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, UniDict, ViesCraft, Vulpes library, WanionLib, Waystones, Zero CORE, Ore Core
-------------------
This causes spam on my console, don't shure what does this affects yet but i hope it will help you do mod better
-------------------
https://pastebin.com/TbKEnrmd

**Comment by Krosta8** [comment]
This problem was already reported and as I can see, the error is repaired, just wait for release with this fix.

**Comment by Foxgreat** [comment]
ok, thanks
