### ISSUE TITLE
Smeltery not working at all. 

### ISSUE THREAD

**Issue by PinkSlapper** [SlimeKnights/TinkersConstruct#3369]
I have added tinkers construct to a modpack and after i build the smeltery (using the book) it does not turn on and i cannot open it. 
Minecraft Version 1.10.2
TC: 1.10.2-2.6.5
Mantle: 1.10.2-1.1.5

**Comment by TherminatorX** [comment]
Pictures are worth a thousand words. Why don't you add a couple images of your setup, it's not uncommon for people to misplace a block here or there.

**Comment by PinkSlapper** [comment]
![2018-02-05_17 28 04](https://user-images.githubusercontent.com/36174785/35832308-cf2482f0-0a9a-11e8-9c83-d63ca8bfed9d.png)

**Comment by bonii-xx** [comment]
Looks correct from a first glance. How does the inside and the other side look?

**Comment by KnightMiner** [comment]
@PinkSlapper: any update? We need pictures of the inside to determine if the smeltery is built correctly

**Comment by KnightMiner** [comment]
Closing for lack of response

**Comment by Aels224** [comment]
Hello, i have the same issue in 1.12.2 can you help me ? I'm used with Tinker and i don't know why i can't open it..
