### ISSUE TITLE
[Question] Mining Level Colors in Resource Pack

### ISSUE THREAD

**Issue by ElvenChaos** [SlimeKnights/TinkersConstruct#3370]
When defining custom harvest levels via `ui.mininglevel.X` in a resource pack, is there a way to get the nice custom colors TCon gives the harvest levels, or are we limited to the standard MC color code formatting`§`?

**Comment by bonii-xx** [comment]
In theory.. probably. TiC uses an UTF-8 plane reserved for private use to represent the color codes. Those don't have printable characters associated with them (hence private use), which makes it hard to use outside of code (but also makes the color codes invisible when a different font-renderer is used in MC).

The characters are between 0xE700 and 0xE7FF. Put 3 characters inside that range right after each other for RGB and it might just work.

**Comment by ElvenChaos** [comment]
I've tested this out and it certainly does work, thank you!

For anyone else who comes across this issue, you can copy the characters from this link:
http://www.utf8-chartable.de/unicode-utf8-table.pl?start=59136

If you want to mirror some of the default colors/materials, then you can find the color codes here:
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/TinkerMaterials.java

**Comment by bonii-xx** [comment]
Great, I'll put a link to this issue into the wiki.
