### ISSUE TITLE
Crash while repairing tools inside Tool Station

### ISSUE THREAD

**Issue by CobaltRealm** [SlimeKnights/TinkersConstruct#3372]
Everytime I try to put a tool inside the Tool Station the game crashes

Link to pastebin: https://pastebin.com/bBtjCR1Y

**Comment by KnightMiner** [comment]
Two issues:

* you are missing half the crash report. Get the full report, paste it on pastebin.com, then link it here
* you have Optifine installed and this is a client crash. We do not support Optifine

Try this without Optifine and give the full crash report.

**Comment by CobaltRealm** [comment]
Just updated the Issue its still with Optifine but the its the full crash report, currently I cant send the crash without Optifine right now but I will send it as soon as I can, sorry :/

**Comment by KnightMiner** [comment]
It appears you have a mod adding a broken modifier. Please try removing any Tinkers Construct addons to see if you can find out which one has the broken modifier.

**Comment by CobaltRealm** [comment]
Thanks! I will uninstalling the mods and search for the mod causing the crash

**Comment by IdleGandalf** [comment]
That's probably a TAIGA bug. You can open an issue [here](https://github.com/TeamFRM/TAIGA/issues).

**Comment by bonii-xx** [comment]
Gonna close this then, thanks everybody

**Comment by KnightMiner** [comment]
Linking TeamFRM/TAIGA#157 for future reference
