### ISSUE TITLE
[1.10.2] Bronze items missing

### ISSUE THREAD

**Issue by Mophise** [SlimeKnights/TinkersConstruct#3374]
I've triple checked. Yes, with only Tinkers and NEI, too. I'm using the Twitch/Curse launcher.

There is no bronze block or ingot added by tinkers.
You can still make molten bronze.

Please recommend a fix. I'm trying to build a modpack.

**Comment by KnightMiner** [comment]
Yes. There are none added by tinkers. If you want bronze, install another mod that adds bronze and company will be generated. There was no point adding our own ores just for tool parts.

**Comment by Mophise** [comment]
Got one to recommend?

**Comment by KnightMiner** [comment]
If all you care about are ores for tools, thermal foundation is the easiest as it's mainly base materials. If you want the ofes to have a use beyond tools, grab thermal expansion, embers, or immersive engineering. I currently am using immersive engineering as it's been my favorite tech mod for awhile.

**Comment by Mophise** [comment]
I have immersive engineering. My problem is literally just that I can't pour bronze out of the smeltery. I can't use thermal expansion without unbalancing my pack. Embers would likewise unbalance things.

Thank you for the recommendations. if you can think of anything else, I'd appreciate it. I'm still looking, too.

**Comment by KnightMiner** [comment]
You cannot pour bronze out? There is nothing special about the fluid, so if the melting recipes are working the casting ones should be too. Check in JEI to ensure the recipes actually exist.

**Comment by Mophise** [comment]
They don't. the items "bronze ingot" and "bronze block" don't exist, and from what I can find, the only way to get it is to add a mod that would also add a bunch of tech, ores, and items that I not only don't need, but would unbalance what I'm trying to make.

**Comment by Mophise** [comment]
this might drive me to attempt to make a mod just to add them.

**Comment by KnightMiner** [comment]
Sorry, I was mistaken. It seems Immersive Engineering does not add bronze. You should still be safe adding Thermal Foundation though as all it adds are ores, no machines

**Comment by Mophise** [comment]
their documentation makes no mention of that. I'll give it a try. thanks
