### ISSUE TITLE
(1.12.2) Hellish trait (Netherrack) applying to Nether mobs as well

### ISSUE THREAD

**Issue by TherminatorX** [SlimeKnights/TinkersConstruct#3378]
The bonus damage from Hellish is given to both overworld mobs and nether mobs. Using frying pans with both netherrack and stone heads (claim equal base damage) results in all mobs taking more damage from the netherrack pan than the stone one. Tested on zombies, pigmen, spiders, blazes, and both types of skeletons.

TiC 2.9.1.65, Forge 14.23.1.2583

**Comment by KnightMiner** [comment]
I can confirm blazes are affected (treated as non-nether), but I cannot reproduce with zombie pigmen. We do have a bit of a weird way of determining a mob is "nether", which could probably use some cleanup.
