### ISSUE TITLE
Materials And You Text Problem

### ISSUE THREAD

**Issue by noswanson1982** [SlimeKnights/TinkersConstruct#3380]
I notice when trying to read the Materials And You book, the text gets cut off.  The text on the left page disappears behind the right page, and the words on the right page actually go off the page.  Is there a way to adjust the font size to make it fit within the boundaries of the pages, or is this a bug?

**Comment by KnightMiner** [comment]
It all automatically adjusts, unless you have Optifine installed which breaks the formating. Can you provide a mod list so we can determine if you have Optifine or another client side mod that might break things?

**Comment by SweetSugarSugar** [comment]
It's most likely OptiFine

**Comment by KnightMiner** [comment]
@noswanson1982 can you confirm if you have Optifine installed?

**Comment by noswanson1982** [comment]
Unfortunately, I do have Optifine.  I suppose there isn't a way to adjust it while using Optifine, is there?

**Comment by KnightMiner** [comment]
There is nothing we can do since its caused by Optifine. You will have to report the issue to them.
