### ISSUE TITLE
Scythe cannot harvest Immersive Engineering hemp

### ISSUE THREAD

**Issue by ChronosWS** [SlimeKnights/TinkersConstruct#3381]
I'm not sure if this is intended, a bug, or a feature request, but I'd like to be able to use the scythe on IE hemp - currently it does nothing at all.  I don't see a configuration option to allow it either, so I am guessing it's supposed to "just work" for crops in general.

**Comment by KnightMiner** [comment]
In general, yes, it just works. We do fire an event which is fired to determine if something is a crop, which IE could use. @BluSunrize is this something you want to add as part of your Tinkers Construct compat?

**Comment by BluSunrize** [comment]
Sure.
Got an implementation example for me?

**Comment by bonii-xx** [comment]
Off the top of my head, this should be the thing: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/events/TinkerToolEvent.java#L104-L109

**Comment by KnightMiner** [comment]
@BluSunrize did you ever implement this, or did you still want more information? If needed, I am normally on the SlimeKnights discord to discuss this.

**Comment by BluSunrize** [comment]
I just plain forgot about this.
I'll put an issue on my own tracker, but it's not high priority, since I'm focusing on getting 1.14 to stable atm.

**Comment by bonii-xx** [comment]
Can we find a general solution for 1.14? That doesn't require keeping lists of stuff? 😖

**Comment by BluSunrize** [comment]
Use tags! :D
The block tag 'crops' is introduced officially in vanilla 1.15, but there's no reason we can't put it on stuff now?
Edit: We should probably use a Forge tag though, not try to claim it to be vanilla.

**Comment by bonii-xx** [comment]
Yeah, that's what we should use. ;)

**Comment by KnightMiner** [comment]
Not sure if 1.12 ever got support (issue closed but no comment if that was end of 1.12 support or added), but 1.16 is just a tag for this now. I have sent BluSunrize the relevant tag to use.

**Comment by BluSunrize** [comment]
And BluSunrize has already implemented this.
😎 👉 👉
