### ISSUE TITLE
Server crashing when shooting a mob with the Tinkers Construct crossbow

### ISSUE THREAD

**Issue by Phoenixmeowsy** [SlimeKnights/TinkersConstruct#3382]
All I see happening is the arrow flying at the mob, hitting and then reflecting off the mob, then the server crashes.

**Comment by KnightMiner** [comment]
Crash report? Mod versions? Is it a sponge forge server?

**Comment by Phoenixmeowsy** [comment]
[crash-2018-02-14_14.55.57-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1724224/crash-2018-02-14_14.55.57-server.txt)

**Comment by KnightMiner** [comment]
> at com.thexfactor117.levels.leveling.AbilitySelection.getRandomizedAbilities(AbilitySelection.java:41)

Looks like it's caused by that leveling mod, not by Tinkers. In any case, 1.7 is no longer supported.
