### ISSUE TITLE
Uhhh Wut?

### ISSUE THREAD

**Issue by stick-shift** [SlimeKnights/TinkersConstruct#3385]
I am currently creating a modpack and i was playing on a world starting out. and i got some tinkers tools built and i went mining, and needed to repair the tool, so i went back home, tossed some iron into a furnace and opened up the tool station, as soon as i put my broken tool in the spot, the game freezes and shuts down. this is the 10th times this has happened and at first i thought it was a id conflict with the buildcraft goggles, so i removed buildcraft, and reinstalled it and changed the id of the goggles, still happened so i got rid of buildcraft ;,( but now its still doing the same thing, but its somthing to do with slimeknight... idk so heres the crash log and lastest
 log file. id like to get this working... also i have Tagia, and moar senkers installed but it cuasing look like they are causing it

[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/1734029/latest.log)

[crash-2018-02-17_11.13.33-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1734030/crash-2018-02-17_11.13.33-client.txt)

**Comment by TherminatorX** [comment]
Please search for your issue in case someone has already reported it. This is a known TAIGA issue, and has already been reported several times, as per #3372
