### ISSUE TITLE
Crash to desktop when puting any tc tool into tool station/forge

### ISSUE THREAD

**Issue by zzBuilderzz** [SlimeKnights/TinkersConstruct#3388]
Every time I put a tool into a tool station or forge I get an instant crash regardless if I pulled it out of creative or built it from the tools component parts. This is affecting me across multiple mod packs including my own private one. I am using the latest versions of all mods. All mods that add or affect Tinker's Construct that I am currently are as follows: Tinker's addons, Tinker tool leveling, PlusTic, Taiga, Tinker i/o.

**Comment by bba3075** [comment]
It's Taiga. I( was having the same problem and fixed it by removing taiga.

**Comment by zzBuilderzz** [comment]
ahh thank you

**Comment by KnightMiner** [comment]
Duplicate of #3372.
