### ISSUE TITLE
Accessing MaterialRenderInfo variables

### ISSUE THREAD

**Issue by Lance5057** [SlimeKnights/TinkersConstruct#3389]
Would it be possible to create a way to access so of the info stored in some of the MaterialRenderInfo classes? Such as - [MultiColor](https://github.com/SlimeKnights/TinkersConstruct/blob/d67cc3d00074608a4283df801602f21a6ff6da32/src/main/java/slimeknights/tconstruct/library/client/MaterialRenderInfo.java#L106)

I see no way to access these normally and they would be useful for creating textures to go onto armor that fits the tool look.

**Comment by bonii-xx** [comment]
If you need to access implementation specific variables you're already having a problem anyway, since it wont work with any custom implementations.

**Comment by Lance5057** [comment]
I'm trying to load the textures for the armor model, which are loaded dynamically, so I need to either access the MaterialRenderInfo to dynamically build the textures or I'd need a way to stuff an image through the tinkers art pipeline without an item attached to it.

Is the 2nd one possible? If it is I currently cant see a way to do so.

**Comment by bonii-xx** [comment]
What do you refer to as the "Tinkers art pipeline"? [https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/client/CustomTextureCreator.java|The Texture generation] is freely accessible. As I said, accessing the internals of the MaterialRenderInfo wont work since it's a breach of abstraction, and fail terribly as soon as you have materials that use one that's not hardcoded (like Twilight Forest, etc.)

**Comment by Lance5057** [comment]
Yea that works a lot better then what I was trying to do, the sprites seem to have generated.
Problem I'm having now is I can't seem to get them back out when I need them. I tried using their resource location that was listed in the debugger but that came up blank and I can't get the TextureAtlasSprites because by the time the armor is being rendered the sprites have been cleared (I assume I'm not supposed to access them this way anyway).

How would I go about getting to the sprites once they've been generated and the world is loaded? Thanks!

**Comment by bonii-xx** [comment]
Depends on what you're doing. They're in the TextureMap and the static sprites map in the TextureCreator. You're not stitching them into the items/blocks sheet, are you....?

In general it sounds like you need to bind the correct resource first.

**Comment by KnightMiner** [comment]
Going to close this as the render info logic has greatly changed on 1.16 and I am not comfortable making significant changes to it on 1.12 in a bug fix release.
