### ISSUE TITLE
Game Crash on Draining and Filling a tank simultaneously

### ISSUE THREAD

**Issue by Omanoctoa** [SlimeKnights/TinkersConstruct#3390]
Similar issue to https://github.com/SlimeKnights/TinkersConstruct/issues/3297 but using a far simpler setup.

I have a simple smeltery with a drain that outputs to a seared gauge, with multiple Faucets connected to that window to empty onto 4 blank Casting Tables. Basically, blood from a smeltery farm can be rapidly cast into Coagulated Blood. Restone allows me to partially automate this part, but only so far as me pushing a button each time to begin casting. This part works great, unless The I attempt to fill the Gauge/Window/Tank (tried all 3) with blood as it drains. At this point, the game crashes repeatedly until I delete the Tank.

Crash also occurs using the same mechanics, if I run out of Blood to fully cast the Blood but the tables have some remaining on them. As soon as I attempt to refill the Tank that feeds the tables, the game crashes. My assumption is the Windows/Tanks/Gauges cannot handle being filled and drained simultaneously, though I'm sure I've seen and used the mechanic before. Perhaps the issue is the rate I'm draining the tank at?

My setup:
![2018-02-21_08 08 14](https://user-images.githubusercontent.com/23223068/36481663-80e1e718-16de-11e8-8e16-f3d46ac4726f.png)

Minecraft 1.12.2 (with Forge)
Mods: Tinker's Construct, Twilight Forest, Extra Utilities 2, Pam's Harvestcraft, Optifine, Roguelike Dungeons, WorldEdit...I think another mod as well but don't recall.

Crash Report: 
[crash-2018-02-21_07.54.00-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1744086/crash-2018-02-21_07.54.00-server.txt)

Game now crashes consistently even trying to fill the tank, as the faucets (which I have replaced, along with the tables and Tank) immediately attempt to cast into the tables below. Think I need to scrap this system until it can be fixed.

**Comment by Omanoctoa** [comment]
Had a thought...
Are the tanks/windows only capable of handling a single output at a time? I know Smeltery Drains can handle multiple outputs, but are tanks?

**Comment by KnightMiner** [comment]
Looking at the crash report, it should be impossible. The line that is throwing a NPE is right below the line that creates that object. Can you try reproducing with minimal mods? My only guess is some mod is using one of the Forge fluid events and nulling a fluid before it has a chance to be returned, which is an issue in that mod.

**Comment by Omanoctoa** [comment]
Only other mod I have at this time that may cause an issue is ExtraUtilities2. I agree with your diagnosis on Psymatics' thread:

> Seems to be some sort of race condition where Minecraft starts to empty the tank before it finished filling it. Not sure there is anything we can do as there is no place in the code to catch this crash, the stack is never null on the line its crashing. 

As far as I'm aware all my mods are up to date.
I'm just going with a different setup using multiple Smeltery Drains each with its own output table. This seems to solve the issue as they're drawing directly from the Smeltery and not an external reservoir.

**Comment by KnightMiner** [comment]
Just pushed a commit which should fix this, it seems the faucet was running pouring logic directly on block update, which could cause it to empty a tank in the middle of filling. I've switched it to use the same logic most redstone components do to add a slight delay on update

**Comment by KnightMiner** [comment]
Should be in the 2.12.0.156 build, so closing this.
