### ISSUE TITLE
[Feature Request] Mob Fishing Rod (From SpawnerCraft)

### ISSUE THREAD

**Issue by Lion4K** [SlimeKnights/TinkersConstruct#3391]
Is it possible to make a Modifier for weapons that adds the ability to drop Essence of <mob> when killing it?

Thanks and Sorry to bother.

**Comment by TherminatorX** [comment]
Mystical Agriculture adds Soularium as a tool material, with its own unique trait that can be used to have MA's "mob chunks" drop. I'd suggest taking it up with SpawnerCraft's developer to implement a similar system rather than try to have TCon support it by default.

**Comment by Lion4K** [comment]
Yeah I was thinking to add a Mob Cage as a modifier, since basically the tool is a Fishing rod with a mob cage. but im gonna send this to SC team too.

**Comment by KnightMiner** [comment]
We do not add native material compatibility with other mods except generic materials. If you want this feature ask the SC devs or suggest it to an addon.
