### ISSUE TITLE
Piggybackpack crashes server

### ISSUE THREAD

**Issue by Raycoms** [SlimeKnights/TinkersConstruct#3392]
Hi,

One of our player noticed that if you piggy-backpack an entity and teleport to another world it crashes the server.

**Comment by Raycoms** [comment]
> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.1.jar)
  LibLoader (# LibLoader.jar)
  SpongeCoremod (spongeforge-1.12.2-2586-7.1.0-BETA-2865.jar)
  CoreMod (TickProfiler-1.12-0.0.1.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  OpenEyePlugin (OpenEye-1.12.1-0.8.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  BCModPlugin (backpacks_1.12.2_-_3.4.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 2/21/18 5:42 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:646)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 1262
	Entity Name: chloplop
	Entity's Exact location: 3320.50, 66.00, -351.50
	Entity's Block location: World: (3320,66,-352), Chunk: (at 8,4,0 in 207,-22; contains blocks 3312,0,-352 to 3327,255,-337), Region: (6,-1; contains chunks 192,-32 to 223,-1, blocks 3072,0,-512 to 3583,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: [EntityCow['Cow'/168630, l='Mining', x=3320.50, y=67.49, z=-351.50]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:646)
	at net.minecraft.world.World.func_72939_s(World.java:7536)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2719)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

-- Affected level --
Details:
	Level name: world-minecolonies1.12
	All players: 5 total; [EntityPlayerMP['Barlock_James'/772, l='world-minecolonies1.12', x=1153.54, y=70.00, z=515.90], EntityPlayerMP['Karl4103'/90625, l='world-minecolonies1.12', x=-5485.81, y=65.00, z=-316.15], EntityPlayerMP['furzman2002'/148592, l='world-minecolonies1.12', x=1644.44, y=68.00, z=797.32], EntityPlayerMP['Zyxifrash'/154779, l='world-minecolonies1.12', x=2893.69, y=42.00, z=-4308.05], EntityPlayerMP['chloplop'/1262, l='world-minecolonies1.12', x=3320.50, y=66.00, z=-351.50]]
	Chunk stats: ServerChunkCache: 841 Drop: 0
	Level seed: 2602936902365783189
	Level generator: ID 10 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"continents","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"large","amplitude":0.515493,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":71.40845,"mainNoiseScaleZ":80.0,"coordinateScale":212.2324,"heightScale":212.2324,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (1547,104,-161), Chunk: (at 11,6,15 in 96,-11; contains blocks 1536,0,-176 to 1551,255,-161), Region: (3,-1; contains chunks 96,-32 to 127,-1, blocks 1536,0,-512 to 2047,255,-1)
	Level time: 152510948 game time, 14909266 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 16125 (now: false), thunder time: 149673 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-693.5.2.el7.x86_64
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2673024952 bytes (2549 MB) / 18183880704 bytes (17341 MB) up to 18183880704 bytes (17341 MB)
	JVM Flags: 14 total; -Xms17G -Xmx17G -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=15 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=40 -XX:GCPauseIntervalMillis=150 -XX:+AggressiveOpts -XX:+TieredCompilation -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:CompileThreshold=1000
	IntCache: cache: 11, tcache: 0, allocated: 0, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2604 126 mods loaded, 126 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                    | Version                         | Source                                               | Signature                                |
	|:--------- |:------------------------------------- |:------------------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                             | 1.12.2                          | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | mcp                                   | 9.42                            | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | FML                                   | 8.0.99.99                       | forge-1.12.2-14.23.1.2604-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                 | 14.23.1.2604                    | forge-1.12.2-14.23.1.2604-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ColorUtility                          | 1.0.4                           | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | OpenEye                               | 0.8                             | OpenEye-1.12.1-0.8.jar                               | None                                     |
	| UCHIJAAAA | spongeapi                             | 7.1.0-SNAPSHOT-b163786          | spongeforge-1.12.2-2586-7.1.0-BETA-2865.jar          | None                                     |
	| UCHIJAAAA | sponge                                | 1.12.2-2586-7.1.0-BETA-2865     | spongeforge-1.12.2-2586-7.1.0-BETA-2865.jar          | None                                     |
	| UCHIJAAAA | movillages                            | 1.5.4                           | 1.12MoVillages-1.5.4.jar                             | None                                     |
	| UCHIJAAAA | akashictome                           | 1.2-10                          | AkashicTome-1.2-10.jar                               | None                                     |
	| UCHIJAAAA | applecore                             | 3.1.1                           | AppleCore-mc1.12.2-3.1.1.jar                         | None                                     |
	| UCHIJAAAA | crafttweaker                          | 4.1.3                           | CraftTweaker2-1.12-4.1.3.jar                         | None                                     |
	| UCHIJAAAA | mtlib                                 | @VERSION@                       | MTLib-3.0.2.jar                                      | None                                     |
	| UCHIJAAAA | modtweaker                            | 4.0.7                           | modtweaker-4.0.7.jar                                 | None                                     |
	| UCHIJAAAA | jei                                   | 4.8.5.151                       | jei_1.12.2-4.8.5.151.jar                             | None                                     |
	| UCHIJAAAA | appleskin                             | 1.0.9                           | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
	| UCHIJAAAA | mantle                                | 1.12-1.3.1.21                   | Mantle-1.12-1.3.1.21.jar                             | None                                     |
	| UCHIJAAAA | chisel                                | MC1.12-0.1.1.26                 | Chisel-MC1.12-0.1.1.26.jar                           | None                                     |
	| UCHIJAAAA | tconstruct                            | 1.12.2-2.9.1.65                 | TConstruct-1.12.2-2.9.1.65.jar                       | None                                     |
	| UCHIJAAAA | thedragonlib                          | 1.12.2-5.2.0                    | thedragonlib-1.12.2-5.2.0.jar                        | None                                     |
	| UCHIJAAAA | armorplus                             | 1.12.2-11.10.1.35-beta          | armorplus-1.12.2-11.10.1.35-beta.jar                 | None                                     |
	| UCHIJAAAA | atlcraft                              | MC1.12-Ver1.9                   | ATLCraftCandlesModMC1.12-Ver1.9.jar                  | None                                     |
	| UCHIJAAAA | quark                                 | r1.4-122                        | Quark-r1.4-122.jar                                   | None                                     |
	| UCHIJAAAA | autoreglib                            | 1.3-15                          | AutoRegLib-1.3-15.jar                                | None                                     |
	| UCHIJAAAA | backpacks16840                        | 3.4.3                           | backpacks_1.12.2_-_3.4.3.jar                         | None                                     |
	| UCHIJAAAA | base                                  | 3.6.1                           | base-1.12.2-3.6.1.jar                                | None                                     |
	| UCHIJAAAA | bedbugs                               | @VERSION@                       | BedBugs-1.12-1.0.1.jar                               | None                                     |
	| UCHIJAAAA | betteradvancements                    | 0.0.5.17                        | BetterAdvancements-1.12.2-0.0.5.17.jar               | None                                     |
	| UCHIJAAAA | betterbuilderswands                   | 0.11.1                          | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar      | None                                     |
	| UCHIJAAAA | betterquesting                        | 3.5.238                         | BetterQuesting-3.5.238.jar                           | None                                     |
	| UCHIJAAAA | biometweaker                          | 3.1.311                         | BiomeTweaker-1.12.2-3.1.311.jar                      | bdea6e9d19f35da4858ffcc93210c6207dd590bd |
	| UCHIJAAAA | biomesoplenty                         | 7.0.1.2314                      | BiomesOPlenty-1.12.2-7.0.1.2314-universal.jar        | None                                     |
	| UCHIJAAAA | birdsnests                            | 2.1.0                           | BirdsNests1.12.2-2.1.0.jar                           | None                                     |
	| UCHIJAAAA | bonsaitrees                           | 1.0.1                           | bonsaitrees-1.0.1-b56.jar                            | None                                     |
	| UCHIJAAAA | ceramics                              | 1.12-1.3.3b                     | Ceramics-1.12-1.3.3b.jar                             | None                                     |
	| UCHIJAAAA | chameleon                             | 1.12-4.1.3                      | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| UCHIJAAAA | chesttransporter                      | 2.8.8                           | ChestTransporter-1.12.2-2.8.8.jar                    | None                                     |
	| UCHIJAAAA | chiselsandbits                        | 14.13                           | chiselsandbits-14.13.jar                             | None                                     |
	| UCHIJAAAA | shadowmc                              | 3.8.0                           | ShadowMC-1.12-3.8.0.jar                              | None                                     |
	| UCHIJAAAA | clipboard                             | @VERSION@                       | Clipboard-1.12-1.3.0.jar                             | None                                     |
	| UCHIJAAAA | clumps                                | 2.0.0                           | Clumps-3.0.0.jar                                     | None                                     |
	| UCHIJAAAA | morpheus                              | 1.12-3.3.2                      | Morpheus-1.12-3.3.2.jar                              | None                                     |
	| UCHIJAAAA | comforts                              | 1.1.0.1                         | comforts-1.12.2-1.1.0.1.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | cookingforblockheads                  | 6.3.17                          | CookingForBlockheads_1.12.1-6.3.17.jar               | None                                     |
	| UCHIJAAAA | corail_pillar_extension_biomesoplenty | 4.0.1                           | corail_pillar_extension_biomesoplenty-4.0.1-1.12.jar | None                                     |
	| UCHIJAAAA | corail_pillar_extension_chisel        | 4.0.0                           | corail_pillar_extension_chisel-4.0.0-1.12.jar        | None                                     |
	| UCHIJAAAA | corail_pillar_extension_quark         | 4.0.0                           | corail_pillar_extension_quark-4.0.0-1.12.jar         | None                                     |
	| UCHIJAAAA | crafttweakerjei                       | 2.0.0                           | CraftTweaker2-1.12-4.1.3.jar                         | None                                     |
	| UCHIJAAAA | customnpcs                            | 1.12                            | CustomNPCs_1.12.2(20jan18).jar                       | None                                     |
	| UCHIJAAAA | earthworks                            | 1.3.4.3                         | Earthworks-1.12-1.3.6.jar                            | None                                     |
	| UCHIJAAAA | ediblebugs                            | 1.6.0.2512                      | ediblebugs-mc1.12.2_eb1.6.0.2512.jar                 | None                                     |
	| UCHIJAAAA | elevatorid                            | 1.3.5                           | ElevatorMod-1.12.2-1.3.5.jar                         | None                                     |
	| UCHIJAAAA | csb_ench_table                        | 1.1.2                           | EnchantingTable-1.12-1.1.2.jar                       | None                                     |
	| UCHIJAAAA | enderzoo                              | 1.12.1-1.4.0.49                 | EnderZoo-1.12.1-1.4.0.49.jar                         | None                                     |
	| UCHIJAAAA | expandedbonemeal                      | 1.2.1                           | expandedbonemeal-1.11-1.2.1.jar                      | None                                     |
	| UCHIJAAAA | tschipplib                            | 1.1                             | TschippLib_MC1.12_v1.1.jar                           | None                                     |
	| UCHIJAAAA | extraambiance                         | 1.0.1                           | ExtraAmbiance_MC1.12_v1.0.1.jar                      | None                                     |
	| UCHIJAAAA | extrabitmanipulation                  | 1.12-3.2.1                      | ExtraBitManipulation-1.12-3.2.1.jar                  | None                                     |
	| UCHIJAAAA | fairylights                           | 2.1.2                           | fairylights-2.1.2-1.12.x.jar                         | None                                     |
	| UCHIJAAAA | farmingforblockheads                  | 3.1.5                           | FarmingForBlockheads_1.12-3.1.5.jar                  | None                                     |
	| UCHIJAAAA | foamflower                            | 1.12.2-1.0.0.0-beta1            | foamflower-1.12.2-1.0.0.0-beta1.jar                  | None                                     |
	| UCHIJAAAA | forgelin                              | 1.6.0                           | Forgelin-1.6.0.jar                                   | None                                     |
	| UCHIJAAAA | holoinventory                         | 2.0.2.148                       | HoloInventory-1.12.2-2.0.2.148.jar                   | None                                     |
	| UCHIJAAAA | waila                                 | 1.8.23                          | Hwyla-1.8.23-B38_1.12.jar                            | None                                     |
	| UCHIJAAAA | ironchest                             | 1.12.2-7.0.34.820               | ironchest-1.12.2-7.0.34.820.jar                      | None                                     |
	| UCHIJAAAA | itlt                                  | 1.0.0                           | itlt-1.12-1.0.0.jar                                  | None                                     |
	| UCHIJAAAA | journeymap                            | 1.12.2-5.5.2                    | journeymap-1.12.2-5.5.2.jar                          | None                                     |
	| UCHIJAAAA | jaff                                  | 1.7_for_1.12                    | JustAFewFish-1.7_for_1.12.jar                        | None                                     |
	| UCHIJAAAA | kleeslabs                             | 5.3.2                           | KleeSlabs_1.12-5.3.2.jar                             | None                                     |
	| UCHIJAAAA | laggoggles                            | FORGE-1.12.2-3.1                | LagGoggles-FORGE-1.12.2-3.1.jar                      | None                                     |
	| UCHIJAAAA | limelib                               | 1.7.9                           | limelib-1.12.2-1.7.9.jar                             | None                                     |
	| UCHIJAAAA | malisiscore                           | 1.12.2-6.4.0                    | malisiscore-1.12.2-6.4.0.jar                         | None                                     |
	| UCHIJAAAA | malisisdoors                          | 1.12.2-7.3.0                    | malisisdoors-1.12.2-7.3.0.jar                        | None                                     |
	| UCHIJAAAA | minecolonies                          | 1.12.2-0.8.7551                 | minecolonies-universal-1.12.2-0.8.7551.jar           | None                                     |
	| UCHIJAAAA | minemenu                              | 1.6.3                           | MineMenu-1.12.2-1.6.3-universal.jar                  | None                                     |
	| UCHIJAAAA | netherportalfix                       | 5.3.13                          | NetherPortalFix_1.12.1-5.3.13.jar                    | None                                     |
	| UCHIJAAAA | recipehandler                         | 0.10                            | NoMoreRecipeConflict-0.101.12.2.jar                  | None                                     |
	| UCHIJAAAA | oreexcavation                         | 1.4.113                         | OreExcavation-1.4.113.jar                            | None                                     |
	| UCHIJAAAA | getalltheseeds                        | 1.12a                           | Pams_Get_all_the_Seeds_1.12a.jar                     | None                                     |
	| UCHIJAAAA | harvestcraft                          | 1.12.2p                         | Pams_HarvestCraft_1.12.2p.jar                        | None                                     |
	| UCHIJAAAA | ping                                  | 1.4.2                           | Ping-1.12-1.4.2.jar                                  | None                                     |
	| UCHIJAAAA | placebo                               | 1.2.0                           | Placebo-1.12.2-1.2.0.jar                             | None                                     |
	| UCHIJAAAA | shetiphiancore                        | 3.5.6                           | shetiphiancore-1.12.0-3.5.6.jar                      | None                                     |
	| UCHIJAAAA | platforms                             | 1.4.3b                          | platforms-1.12.0-1.4.3b.jar                          | None                                     |
	| UCHIJAAAA | questbook                             | 3.1.0-1.12                      | questbook-3.1.0-1.12.jar                             | None                                     |
	| UCHIJAAAA | reborncore                            | 3.6.7.210                       | RebornCore-1.12.2-3.6.7.210-universal.jar            | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | redstonepaste                         | 1.7.5                           | redstonepaste-mc1.12-1.7.5.jar                       | None                                     |
	| UCHIJAAAA | woodenshears                          | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | SBM-WoodenShears-1.12-0.0.1b8.jar                    | None                                     |
	| UCHIJAAAA | shulkerbox                            | 1.3.0                           | shulkerbox-1.3.0.jar                                 | None                                     |
	| UCHIJAAAA | signpost                              | 1.07.1                          | signpost-1.12-1.07.1.jar                             | None                                     |
	| UCHIJAAAA | snad                                  | 1.12.1-1.7.09.16a               | Snad-1.12.1-1.7.09.16a.jar                           | None                                     |
	| UCHIJAAAA | sophisticatedwolves                   | 3.13.2                          | SophisticatedWolves-1.12.2-3.13.2.jar                | None                                     |
	| UCHIJAAAA | spartanshields                        | 1.4.1                           | SpartanShields-1.12.2-1.4.1.jar                      | None                                     |
	| UCHIJAAAA | bq_standard                           | 3.4.136                         | StandardExpansion-3.4.136.jar                        | None                                     |
	| UCHIJAAAA | storagedrawers                        | 1.12-5.2.5                      | StorageDrawers-1.12.2-5.3.4.jar                      | None                                     |
	| UCHIJAAAA | storagedrawersextra                   | @VERSION@                       | StorageDrawersExtras-1.12-3.1.0.jar                  | None                                     |
	| UCHIJAAAA | tickprofiler                          | 1.12-0.0.1                      | TickProfiler-1.12-0.0.1.jar                          | None                                     |
	| UCHIJAAAA | tinkersaddons                         | 1.0.7                           | Tinkers_Addons-1.12.1-1.0.7.jar                      | None                                     |
	| UCHIJAAAA | tinkertoolleveling                    | 1.12-1.0.3.DEV.56fac4f          | TinkerToolLeveling-1.12-1.0.3.jar                    | None                                     |
	| UCHIJAAAA | tp                                    | 1.12                            | tinyprogressions-1.12-3.2.10_-_Beta.jar              | None                                     |
	| UCHIJAAAA | tombmanygraves                        | @VERSION@                       | TombManyGraves-1.12-4.0.2.jar                        | None                                     |
	| UCHIJAAAA | trashslot                             | 8.4.6                           | TrashSlot_1.12.1-8.4.6.jar                           | None                                     |
	| UCHIJAAAA | vefluids                              | 0.8.0.10                        | VE-FluidHandling-1.12-0.8.0b10.jar                   | None                                     |
	| UCHIJAAAA | vending                               | 1.12.2-3.0.1.1                  | vending-1.12.2-3.0.1.1.jar                           | None                                     |
	| UCHIJAAAA | waddles                               | 0.5.6                           | Waddles-1.12.2-0.5.6.jar                             | None                                     |
	| UCHIJAAAA | wawla                                 | 2.5.251                         | Wawla-1.12.2-2.5.251.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | woodenbucket                          | 0.2.0.10                        | WoodenBuckets-1.12-0.2.0b10.jar                      | None                                     |
	| UCHIJAAAA | worldedit                             | 6.1.8                           | worldedit-forge-mc1.12-6.1.8-dist.jar                | None                                     |
	| UCHIJAAAA | xtones                                | 1.12-1.0.7-10                   | Xtones-1.12-1.0.7-10.jar                             | None                                     |
	| UCHIJAAAA | clearmob                              | 2.0.0                           | ClearMob-2.0.0.jar                                   | None                                     |
	| UCHIJAAAA | commandsigns                          | 1.3.1                           | CommandSigns-API-6.0.0-1.3.1.jar                     | None                                     |
	| UCHIJAAAA | economylite                           | 2.13.0                          | EconomyLite-7.0.0-2.13.0.jar                         | None                                     |
	| UCHIJAAAA | holograms                             | 2.3                             | holograms-2.3.jar                                    | None                                     |
	| UCHIJAAAA | latch                                 | 0.4.4                           | Latch-0.4.4-S7.0.0.jar                               | None                                     |
	| UCHIJAAAA | luckperms                             | 3.4.49                          | LuckPerms-Sponge-3.4.49.jar                          | None                                     |
	| UCHIJAAAA | nucleus                               | 1.2.2-S7.0                      | Nucleus-1.2.2-S7.0-MC1.12.2-plugin.jar               | None                                     |
	| UCHIJAAAA | magibridge                            | 2.4.1                           | MagiBridge-API7-2.4.1-all.jar                        | None                                     |
	| UCHIJAAAA | mmcreboot                             | 2.1.2                           | MMCReboot-2.1.2-API-7.jar                            | None                                     |
	| UCHIJAAAA | mmcrestrict                           | 1.3.1                           | MMCRestrict-1.3.1-API-7.jar                          | None                                     |
	| UCHIJAAAA | payday                                | 1.3.0                           | PayDay-1.3.0.jar                                     | None                                     |
	| UCHIJAAAA | pjc                                   | 0.2.0                           | projectcore-7.0.0-0.2.0.jar                          | None                                     |
	| UCHIJAAAA | pjw                                   | 0.12.0                          | projectworlds-7.0.0-0.12.0.jar                       | None                                     |
	| UCHIJAAAA | rankup                                | 5768                            | Rankup-V5768-API7-plugin.jar                         | None                                     |
	| UCHIJAAAA | redprotect                            | 7.3.1                           | RedProtect-7.3.1-b69-Universal.jar                   | None                                     |
	| UCHIJAAAA | tabmanager                            | 1.0.4                           | TabManager-1.0.4.jar                                 | None                                     |
	| UCHIJAAAA | corail_pillar                         | 4.1.0                           | corail_pillar-4.1.0-1.12.jar                         | None                                     |

	Loaded coremods (and transformers): 
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.1.jar)
  c4.comforts.asm.SleepTransformer
LibLoader (# LibLoader.jar)
  
SpongeCoremod (spongeforge-1.12.2-2586-7.1.0-BETA-2865.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
CoreMod (TickProfiler-1.12-0.0.1.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
OpenEyePlugin (OpenEye-1.12.1-0.8.jar)
  openeye.asm.MultiTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
BCModPlugin (backpacks_1.12.2_-_3.4.3.jar)
  brad16840.core.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
  com.Axeryok.ColorUtility.ColorUtilityTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 1
		RebornCore Version: 3.6.7.210
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Player Count: 5 / 40; [EntityPlayerMP['Barlock_James'/772, l='world-minecolonies1.12', x=1153.54, y=70.00, z=515.90], EntityPlayerMP['Karl4103'/90625, l='world-minecolonies1.12', x=-5485.81, y=65.00, z=-316.15], EntityPlayerMP['furzman2002'/148592, l='world-minecolonies1.12', x=1644.44, y=68.00, z=797.32], EntityPlayerMP['Zyxifrash'/154779, l='world-minecolonies1.12', x=2893.69, y=42.00, z=-4308.05], EntityPlayerMP['chloplop'/1262, l='world-minecolonies1.12', x=3320.50, y=66.00, z=-351.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'

**Comment by liach** [comment]
I believe this may be mod dependent. I've done the same thing (teleporting across world while carrying another living entity) on a sponge modded server; i was teleported while the animal was not.

**Comment by TherminatorX** [comment]
@liach For reference, what mod allowed you to do so?

**Comment by Raycoms** [comment]
In this case it's the home command of nucleus.

**Comment by Raycoms** [comment]
haven't dared to test with others yet.

**Comment by liach** [comment]
Same commands. The pack is available here: https://almura.enjin.com/home/m/10923980/article/4713576

**Comment by KnightMiner** [comment]
Sounds like an issue with their implementation of teleportation not taking into account riders. It is a bit of an odd case, but I am not sure if there is anything we can do.

Can you reproduce with just Tinkers Construct and Nucleus?

**Comment by KnightMiner** [comment]
Closing for lack of response, as I mentioned before, it sounds like the implementation of teleportation is not taking riding entities into account, which should be fixed on their side
