### ISSUE TITLE
[1.12.1] TiC vers 2.8.x arent tagged as compat for 1.12.1

### ISSUE THREAD

**Issue by Morpheus1101** [SlimeKnights/TinkersConstruct#3393]
Is there any reason the 2.8.x vers arent tagged as valid for use with 1.12.1 ?

**Comment by KnightMiner** [comment]
Because it does not work in 1.12.1. We updated to a newer forge to get newer features.

There is no reason you should still be using 1.12.1, all 1.12.1 mods should be compatible with 1.12.2.

**Comment by jriwanek** [comment]
Okay, so they probably shouldn't be tagged as 1.12 then.....

**Comment by Morpheus1101** [comment]
In this instance, im afraid they do work in 1.12.1 although you may not intend them to:

https://puu.sh/zty5e/a8cfc788d6.png - v2.8.0.45
https://puu.sh/ztyla/2d938ea371.png - 2.38.1.49

**Comment by KnightMiner** [comment]
Wait, are you talking about on Curseforge, not in game? It could not have been until 2.9 that we switched to 1.12.2, in which case its just no one bothered to tag the files 1.12.1

**Comment by Morpheus1101** [comment]
On curse it isnt tagged as 1.12.1 so if folks use the curse/twitch client it wont show up, but ive tested and used both 2.8.x versions quite fine IN-GAME and they work fine with no issues on 1.12.1 that ive come across so far

**Comment by KnightMiner** [comment]
Should be tagged now.

**Comment by Morpheus1101** [comment]
Yes, thankyou :)
