### ISSUE TITLE
Game Crash when trying to put a tool in tool forge for modifying/repair 1.12.2

### ISSUE THREAD

**Issue by RaindeerGamez** [SlimeKnights/TinkersConstruct#3394]
[crash-2018-02-23_08.53.10-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1751869/crash-2018-02-23_08.53.10-client.txt)

When I try putting any tconstruct tool in a tool forge the game crashes. I think TAIGA might have something to do with it, but I'm really not sure, Please help.

**Comment by KnightMiner** [comment]
Yes, this is TAIGA, and another duplicate of #3372.
