### ISSUE TITLE
Pattern chest can only hold 1 of each cast type

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#3396]
Minecraft: 1.10.2
Forge: 12.18.3.2511
TConstruct-1.10.2-2.6.5.jar
Mantle-1.10.2-1.1.5.jar
ModList: https://pastebin.com/ZEKJYkAA

I can't put more than 1 ingot/plate/gem/gear cast in the pattern chest, they will stack in a "normal" chest but won't in the pattern chest. And yes I usually have at least 4 each of the above listed casts.

**Comment by bonii-xx** [comment]
Yes. Pattern Chests only hold 1 of each type per design.
