### ISSUE TITLE
Dupe bug with Yabba Barrels and TC Crafting Tables

### ISSUE THREAD

**Issue by Lethann** [SlimeKnights/TinkersConstruct#3399]
As reported on FTB Revelations forum [HERE](https://forum.feed-the-beast.com/threads/dupe-bug-with-yabba-barrel-and-tc-crafting-table.271875/)
Also reported to [Yabba Github](https://github.com/LatvianModder/YABBA/issues/64)

FTB Revelations 1.5.0
Tinkers Construct 2.9.0.55
YABBA 1.0.11 

1. Create Yabba barrel. Go into settings (shift right click) and make sure it's locked and always display data)
2. Place any stackable item in the barrel.
3. Place Tinkers Construct crafting table next to barrel.
4. Go into crafting table, pull out items from barrel then place them back in. (The trick is putting them back in)
5. Exit crafting table.
6. Barrel contents should read as 0. 
7. Left click barrel like you are putting items in and amount of item will be doubled. This will happen even if contents of barrel are full and leave invisible dropped stacks on the ground.

**Comment by KnightMiner** [comment]
@LatvianModder: I noticed the issue was closed on your tracker, did you fix it?

If not, its easy enough to use the blacklist in our config to disallow the barrel from connecting

**Comment by LatvianModder** [comment]
I think I fixed it in latest released file (currently alpha 1.1.0.6) by changing barrels from `IItemHandlerModifiable` to `IItemHandler`. That should in theory fix the problem, but you can test that

**Comment by KnightMiner** [comment]
@Lethann can you confirm that this is fixed?

**Comment by KnightMiner** [comment]
Closing as LatvianModder says its fixed
