### ISSUE TITLE
Molten liquids texture issue.

### ISSUE THREAD

**Issue by Southier9** [SlimeKnights/TinkersConstruct#3402]
Was playing when I wanted to pour some Molten metals for some kind of Metal Checkpoint, then this happened, only TConstruct liquids show, the others are from Moar Tinkers and Thermal Expansion.
This kind of texture is using Optifine, without it, the textures are black and pink, with same problem.

![2018-03-02_10 19 00](https://user-images.githubusercontent.com/36991161/36900881-cf9e342a-1e03-11e8-93f8-d73419579f81.png)

**Comment by TheQuadShot** [comment]
If I understand your issue, the problem isn't with TiC, it would be the problem of the mod that provides the liquid/s. Although you may have buckets of said liquid/s in a creative menu iirc Forge provides them and can be disabled in the config.

**Comment by Southier9** [comment]
This is why I posted here, all the liquids show "tconstruct:fluid:'liquid_here'"

![2018-03-02_10 55 58](https://user-images.githubusercontent.com/36991161/36902173-4e9c3660-1e08-11e8-927f-0eb9aa4e640f.png)

**Comment by TheQuadShot** [comment]
Can you be more specific then? Cause I thought you said "only TConstruct liquids show" do you mean that only TiC Ores/Alloys don't have textures? BTW If that's signalum your showing, its a TF (Thermal Foundation) alloy and isn't "made" by TiC.

**Comment by Southier9** [comment]
I'll try to explain better.
I added some mods that said they had compatibility with TConstruct, but their molten metals just show that pink texture with "tconstruct:fluid:'liquid_here'", no matter which mod is, but only the TConstruct ones show, this image show the 3 mods Molten Metal:
1: The first from left is Molten Signalum, from Thermal Foundation, from that image above, with "tconstruct:fluid:signalum" wrote on it.
2: The middle one is Molten Osmium, from Moar Tinkers, same problem from Molten Signalum, same writing above it.
3: The right one are from TConstruct, Molten Ardite, no problems, working properly.
![2018-03-02_11 19 16](https://user-images.githubusercontent.com/36991161/36903139-8f417628-1e0b-11e8-99c9-6033ba6fbb90.png)

But there something more, this is Destabilized Redstone, either from Thermal Foundation, but it's texture works properly.
![2018-03-02_11 24 55](https://user-images.githubusercontent.com/36991161/36903396-5ff9a6e6-1e0c-11e8-8297-60956d0e8dad.png)

To fix this I need to report to the respective Mod Teams?

**Comment by TheQuadShot** [comment]
Correct, They need to provide the liquid texture for the molten ore/alloy.

**Comment by Southier9** [comment]
Thanks @TheQuadShot , I'll do it right now, cheers buddy.
