### ISSUE TITLE
Certain metals won't cast

### ISSUE THREAD

**Issue by Fenrirthviti** [SlimeKnights/TinkersConstruct#3403]
Greetings! Apologies if this is not the correct place to ask this, but I'm not sure where else to ask.

I am running tcon with a moderate amount of other mods, and am having issues with the smeltery pouring certain metals to cast them. This exhibits itself by clicking on the faucet only pouring a few mb of the metal, and then stopping. If you hold right-click on the faucet, the mold will fill, and when the mold is full the progress goes to 100% and then just stops; the item never finishes casting and cannot be extracted.

Below is the list of currently installed mods, and I'm happy to provide any configuration or other details as necessary. Some of the more common metals are casting fine (bronze, lead, etc.) where mithril, brass, and cold-iron are having issues that I have confirmed.

To complicate matters further, I have loaded the same mods into a single player map, and replicated the issue there. I then deleted all mods, and installed them one by one to see if I could identify the conflict. I was able to reinstall every mod and was then unable to replicate the problem, all metals were pouring/casting properly. I feel that there has to be some kind of config or race condition at play, but I'm at a loss how I can even begin to troubleshoot what might be going on. Any guidance or assistance is appreciated.

List of mods:

Minecraft: 1.12.2
Forge: 14.23.2.2611

- AppleCore-mc1.12.2-3.1.1.jar
- AppleSkin-mc1.12-1.0.9.jar
- AutoRegLib-1.3-15.jar
- BaseMetals-1.12-2.5.0-beta4.145.jar
- BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
- BiblioCraft[v2.4.3][MC1.12.0].jar
- BiomesOPlenty-1.12.2-7.0.1.2315-universal.jar
- Chameleon-1.12-4.1.3.jar
- chickens-6.0.3.jar
- Chisel-MC1.12-0.2.0.30.jar
- chiselsandbits-14.13.jar
- chococraft_1.12.1-0.9.1.52.jar
- CTM-MC1.12-0.2.3.12.jar
- Decocraft-2.5.4_1.12.2.jar
- DynamicSurroundings-1.12.2-3.4.9.5.jar
- extrautils2-1.12-1.7.4.jar
- fairylights-2.1.2-1.12.x.jar
- FastLeafDecay-v14.jar
- gravestone-1.10.1.jar
- hatchery-1.12.2-2.1.2.jar
- Hwyla-1.8.23-B38_1.12.jar
- InventoryTweaks-1.63.jar
- jei_1.12.2-4.8.5.147.jar
- journeymap-1.12.2-5.5.2.jar
- KleeSlabs_1.12-5.3.2.jar
- Mantle-1.12-1.3.1.21.jar
- morechickens-1.12.2-3.1.0.jar
- Morpheus-1.12-3.3.2.jar
- MouseTweaks-2.8-mc1.12.1.jar
- OpenGlider-1.12.1-1.1.0.jar
- OreSpawn-1.12-3.2.2.113.jar
- Quark-r1.4-122.jar
- RoguelikeDungeons-1.12.2-1.8.0.jar
- StorageDrawers-1.12.2-5.3.4.jar
- TConstruct-1.12.2-2.9.1.65.jar
- VeinMiner-1.12-0.38.2.647+b31535a.jar
- Waddles-1.12.2-0.5.6.jar
- Waystones_1.12.2-4.0.20.jar
- WearableBackpacks-1.12.2-3.1.2.jar

**Comment by KnightMiner** [comment]
Is this a server? If So, is it normal Forge or Sponge? Do you have any client side only mods like Optifine? 

I've seen this issue before, but the cause is normally something odd like that and not a normal mod conflict.

**Comment by Fenrirthviti** [comment]
Yes, server. Normal Forge (updated the original post with specific versions). Only mods are those listed above, so journeymap and dynamicsurrounds are the only potentially client side mods (both are installed on the server as well, however). No Optifine.

**Comment by Fenrirthviti** [comment]
Just to follow up, I reboot the server once every few days for routine maintenance, and for whatever reason, the last reboot seems to have fixed whatever was wrong. If it happens again, I'll reach out via Discord to see if I can get more info. I have debug enabled now as well, which should hopefully shed some light.
