### ISSUE TITLE
Unregistered/non-existent fuels cause a NPE

### ISSUE THREAD

**Issue by Flenix** [SlimeKnights/TinkersConstruct#3404]
http://paste.atlauncher.com/view/d2c5f109

I've been working on adding TCon support to my mod, and part of the process meant I needed a new fuel. My initial tests the fuel was temporary-named (fluidSuperFuel or something).

Later, I named it properly, which obviously removed the old fluidSuperFuel from the game. However, when I tried to interact with a smeltery that had the old fuel in, it would cause the above crash instead of just voiding the null-fuel. 

A pretty unlikely thing to happen but still worth reporting :)

**Comment by KnightMiner** [comment]
Hmm, seems attempting to read the old fluid from NBT is returning a null fluidstack, but the smeltery still technically has fuel. I'll try and find a good spot to catch it.
