### ISSUE TITLE
Crash when using tool forge

### ISSUE THREAD

**Issue by kingbenni310** [SlimeKnights/TinkersConstruct#3405]
When trying too upgrade my tools in the tool forge, I get a CTD. I'm playing All the mods 3.
[crash-2018-03-03_14.56.37-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1777519/crash-2018-03-03_14.56.37-client.txt)

**Comment by KnightMiner** [comment]
This looks like a crafttweaker issue, report it to them

**Comment by InferableCross7** [comment]
I'm not using Crafttweaker and im getting the same problem. Iv'e tried different items, and when i put them into the tool forge to upgrade them the client crashes.
[crash-2018-03-03_16.02.18-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1777903/crash-2018-03-03_16.02.18-client.txt)

**Comment by KnightMiner** [comment]
@InferableCross7 that is a completely unrelated crash, which is #3372.

**Comment by Henri1992** [comment]
I have the same issue as OP, is it maybe the way the toolstation & toolforge handle crafting and that that collides with CraftTweaker?

**Comment by kingbenni310** [comment]
Thank you for the advice. I could solve the issue by installing an older version of crafttweaker and now it works again.

**Comment by Henri1992** [comment]
I just installed the newest version, released like within the last 16 hours, and that fixed it also.

**Comment by KnightMiner** [comment]
Great. Closkng this as fixed then.
