### ISSUE TITLE
[1.10.2] Placing blocks in smeltery produces phantom items

### ISSUE THREAD

**Issue by Brandon-Gui123** [SlimeKnights/TinkersConstruct#3409]
Whenever a block that is part of a smeltery is placed in the smeltery while it is active, it will cause whatever items on and above that level to get dropped out. This will produce a duplicate of the items affected that cannot be picked up by players, along with the real set of items which can be picked up. There is no net loss in the items.

This smeltery previously had one iron ore in it. I placed a block that acts as part of the smeltery to halt its function and break the multi-block structure.
![2018-03-08_14 42 45](https://user-images.githubusercontent.com/34325463/37137110-4d36c8cc-22df-11e8-817f-20c0467fbd20.png)

The malfunctioning smeltery then drops these items. One of the iron ore cannot be picked up but the other one can.
![2018-03-08_14 42 49](https://user-images.githubusercontent.com/34325463/37137164-961db6c2-22df-11e8-9d3e-810cfba495ed.png)

The phantom items, while cannot be picked up, can still be destroyed by various means(e.g. Lava, cactus etc. except for explosions) and will still obey the physics in the game.

Forge version: 1.10.2-12.18.3.2511
**List of mods**
* Baubles - 1.10.2-1.3.13
* JEI - 1.10.2-3.14.7.419
* JEI Integration - 1.10.2-1.2.0.19
* Mantle - 1.10.2-1.1.5
* Optifine - 1.10.2 HD U E7
* TConstruct - 1.10.2-2.6.5
* Thaumcraft - 1.10.2-6.0.BETA7

**Comment by TheQuadShot** [comment]
The phantom or faux blocks are visual, they aren't really there(they are in the controller) as these images show and have been this way for as long as I can remember. 
https://imgur.com/a/lkpbO
https://imgur.com/a/gtgxY
 However breaking the multi-block should "empty" the smeltery, but the data for what was in the smeltery in still stored in the controller block, as long as that block isn't broken then re-forming the multi-block should restore the items that were in the smeltery when you "broke" it.

**Comment by KnightMiner** [comment]
Single player or server? If server, is it Sponge? Can you reproduce with the latest 1.12 version?

**Comment by Brandon-Gui123** [comment]
@KnightMiner Singleplayer.

@TheQuadShot What I meant was that when a building block for the smeltery is placed in the smeltery multi-block while it is currently smelting items, the smeltery will then drop the items it is currently smelting in front of the controller. It dropped a set of real items and phantom items. For example, if it is currently smelting an iron ore block, placing a smeltery block in the smeltery causes the smeltery to drop the iron ore block, along with another one which is a phantom item.

**Comment by TheQuadShot** [comment]
@Brandon-Gui123 Oh, sorry I did kind of misunderstand. I thought you were talking more about it becoming an invalid multi-block and loosing ore. I've have that happen to me all the time when I'm in a snow biome and I don't cover the smeltery (snow will form in it even if it has a molten liquid in it, or on the forever stranded mod pack with sand).

**Comment by KnightMiner** [comment]
Can you reproduce with the latest 1.12 version with minimal mods? Specifically, Optifine is known to cause issues.

**Comment by Brandon-Gui123** [comment]
Yes, the visual glitch is reproducible in 1.12.2, even without Optifine. I also removed Optifine in the 1.10.2 version and the visual glitch still appeared.
