### ISSUE TITLE
Crash when opening materials and you

### ISSUE THREAD

**Issue by ChiefLogan3010** [SlimeKnights/TinkersConstruct#3410]
Crash occurs when opening a materials and you book, I do have tools turned off in the config so not sure if it has something to do with that.
https://gist.github.com/ChiefLogan3010/05525b312d2703c0f227b925e8ecef0f

**Comment by bonii-xx** [comment]
Yes, the books are not compatible with a part of the mod turned off.

**Comment by ChiefLogan3010** [comment]
Is this intended? The books are still useful for some other things (especially the furnace and tanks as people are less aware of them).

**Comment by bonii-xx** [comment]
Disabling parts of the mod is something we try to keep working, but there's no broad support for it in general. Books are special because they'd require a lot of rewriting to get to work when stuff is missing. So you could say it's not intended, but not something that will be fixed either.

**Comment by KnightMiner** [comment]
This should be solved by 24b292a.
