### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by Moobien** [SlimeKnights/TinkersConstruct#3411]
Hey guys I had an idea of something you may or may not want to add to TC.

With my mob farms I end up with way too many damaged armors etc.  I was thinking that it would be cool if they could be smelted down in the smeltery.  I worked out the math of how you could do it.

As an example say you have a pair of iron leggings that have 10 durability left.  My logic  would be kinda along these lines.

1 Ingot = 144mb
1 Pair of leggings = 7 Ingots (1008mb)
Durability of Iron Leggings: 225

1008mb / 225 = 4.48mb PER Durability point.

so using these numbers. those leggings with 10 durability left would smelt down to 44mb (rounding DOWN) worth of iron.

For advanced armors such as C4's Constructs Armory I would say base the smeltdown on the base part's material and not the sum of all 3 materials unless you want to take it that little bit further.

**Comment by SweetSugarSugar** [comment]
This would be too complicated...

You could literally just combine or repair the damaged armor then melt it down...

**Comment by Moobien** [comment]
It was just an idea :)

**Comment by SweetSugarSugar** [comment]
This issue tracker is primarily for bugs/crashes/etc.

I suggest reading the [FAQ](https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ) first.

**Comment by bonii-xx** [comment]
No, you can always repair the armors by combining them together and then smelt them.
