### ISSUE TITLE
3rd party smeltery fuels not working

### ISSUE THREAD

**Issue by truehunterethan** [SlimeKnights/TinkersConstruct#3415]
If I recall correctly, Hootch, Firewater, and Molten Redstone (i think, people said to try it)  from EnderIO should work as a fuel for a smeltery, and when i tried they did not work.

Smeltery is normal 3v3 but has the corners filled in, also tried in a normal w/out corners (though I don't think it matters because it's recognized as a multiblock)

https://imgur.com/a/00uM6

**Comment by KnightMiner** [comment]
If third party fuels are not working, they are likely not registered which is on the other mod's side. Contact the authors of Ender IO to add support.

There is a chance what you sa e before was either 1.7 (before the rewrite), a Crafttweaker script, or another add-on adding it.
