### ISSUE TITLE
Suggestion-

### ISSUE THREAD

**Issue by Nacoran** [SlimeKnights/TinkersConstruct#3420]
Toggleable powers for items.  Set a key so certain powers can be turned off or even toggled to a different power- finally you could have a silk touch/fortune pickaxe... although what I really want is to be able to turn the glow off on my battle sign.  It's great for exploring underground, but less useful on a nether fortress I want to keep dark so it will keep spawning wither skellies.  If I want to use a battle sign then I have to carry a second one.

Actually, the glow power in general could be made really cool with 3 levels- the standard level lights areas mobs can spawn.  The second level lights areas mobs could spawn when it gets dark.  The third level puts the light farther out, trying to maximize the coverage while minimizing the number of lights created.  It would also be cool if you could change the color of the light it leaves.  It would let different players use different colors, and let people figure out patterns when they are lost.  (Same for the throwable version.)

One last thing... it would be great if mom's spaghetti averaged the value of any meat that you through into the sauce as a mostly hidden feature.  Me personally, I want my spaghetti with hydrachops from twilight forest... okay, I had to try to slip one op suggestion in...

I know you aren't looking for suggestions, but I'm going to give them anyway because I love the mod.

**Comment by bonii-xx** [comment]
No, we wont have toggleable powers. Modifiers/Traits are either there or not.
Spaghetti intentionally doesn't care about which meat you use exactly because of that.
