### ISSUE TITLE
Steel-Obsidian Scythe Bug

### ISSUE THREAD

**Issue by SethMcSpazz** [SlimeKnights/TinkersConstruct#3421]
I created the most BA scythe I could make with the resources I had which included:
Steel. obsidian, bone, and wood.
Then I applied 3 modifiers:
Diamond, Emerald, and Obsidian+Enderpearl
Attacking any monster crashes my local game

[crash-2018-03-17_00.45.24-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1821316/crash-2018-03-17_00.45.24-client.txt)

**Comment by SweetSugarSugar** [comment]
Can you reproduce this without OptiFine?

**Comment by bonii-xx** [comment]
#3189
