### ISSUE TITLE
[1.12.2] Crash when placing tool in tool station

### ISSUE THREAD

**Issue by YaibaToKen** [SlimeKnights/TinkersConstruct#3424]
[Crash report](https://pastebin.com/YPHBAaBZ)
Crash happens when trying to place a wooden broadsword from the creative menu in any of the tool station's slots.

It also appears to happen with a broadsword made in survival.

**Comment by SweetSugarSugar** [comment]
#3372 

Please look to see if it's been reported already next time...

**Comment by KnightMiner** [comment]
TAIGA issue, already reported 12 times to us.
