### ISSUE TITLE
1.12.2 Cactus prickly crashes server

### ISSUE THREAD

**Issue by Ozzymud** [SlimeKnights/TinkersConstruct#3425]
https://pastebin.com/L4eyZxvK

This is the EnderIO test server. Afew of us made shurikens and one a sword. Randomly it would crash the server with the log above. Looked like it pointed to the prickly modifier.

at slimeknights.tconstruct.tools.traits.TraitPrickly.causeDamage(TraitPrickly.java:33)

**Comment by bonii-xx** [comment]
Looks like #3449. Also you might want to update your TiC version.
