### ISSUE TITLE
Client freezing when coming near smeltery?

### ISSUE THREAD

**Issue by thisischrys** [SlimeKnights/TinkersConstruct#3427]
Using 2.9.1.65. 
Nobody can go near the base of someone on my server anymore.
As soon as you get too near, your minecraft stops responding.
There is no crashlog sinds the game just freezes.

The player claims it happened while he was "expanding" his TiCo Smeltery. Note that this is not verified (or verifiable AFAIK)

Just wondering if you've heard of something like this before. I have no idea how to even troubleshoot this. I guess I could download the entire world and remove the smeltery with mcedit and see if that gets rid of the problem if all else fails.

**Comment by TheQuadShot** [comment]
maybe related to this bug: https://github.com/SlimeKnights/TinkersConstruct/issues/3423
I'm presuming that this is a dedicated server, is it a sponge server? what versions are you running? do you have any logs going "upto" the lockup/freeze? This information will give the dev team much more to work with to try to help you.

**Comment by KnightMiner** [comment]
Any update? We cannot do anything without logs

**Comment by KnightMiner** [comment]
Closing for lack of response.
