### ISSUE TITLE
heart containers not providing all the hearts

### ISSUE THREAD

**Issue by nuadunuli** [SlimeKnights/TinkersConstruct#3429]
Minecraft version 1.7.10

tinkers construct version 1.8.8.build991

This is on Bevo's Tech pack but I don't know if it's another mod causing the issue or not as I only just recently noticed it happening.

Basically no matter what heart container I add 10 of, I get 8 orange hearts.. if I add 10 of either red or yellow to the other one.. I get all orange hearts and 7 yellow ones, no matter if I swap them around. I have relogged, restarted client, entered and left the nether and a RFtools dimension, died and nothing seems to fix it.. I left the area I was in as I have beacons and I cannot seem to find a way for them to regenerate. Tried checking config but I can't find a place to edit how much is added by each container

I made a new world and they work fine in that world.. so something has bugged my character.. I have taken off all items to see if it's that.. but still nothing

**Comment by SweetSugarSugar** [comment]
Did you make a Soul Fragment with ExU?

**Comment by nuadunuli** [comment]
oh.. yeah, and made a reinforced watering can with it.. is it permanent then?
