### ISSUE TITLE
[Suggestion][1.12] Bolts and arrow in bauble slots

### ISSUE THREAD

**Issue by ilhamsitok** [SlimeKnights/TinkersConstruct#3431]
I've been playing arround with tcon crossbow for a while, but keep get annoyed when i accidentally put my bolt in my chest. it will be nice if i can put bolt in my bauble slot, so that i always had my bolt on me without taking any inventory space

i know i can put my bolt in off hand slot, but its limiting my pov

**Comment by bonii-xx** [comment]
Well, the same happens if you put your crossbow into a chest. I get the idea, but no.
