### ISSUE TITLE
Crafting station very slow

### ISSUE THREAD

**Issue by purpleposeidon** [SlimeKnights/TinkersConstruct#3432]
Modern Skyblock 3 has a demure *23,400* crafting recipes. Crafting a stack of compressed stone in a crafting station (which is not adjacent to any inventory) takes about 10 seconds.

The [FastWorkbench](https://minecraft.curseforge.com/projects/fastworkbench) mod does [some stuff?](https://github.com/Shadows-of-Fire/FastWorkbench) so that the same operation takes less than a second in a vanilla crafting table. (AE2 is similarly efficient.)

TCon: 1.12.2-2.9.1.65
Forge: 14.23.2.26159

**Comment by bonii-xx** [comment]
Yeah, we need to integrate that stuff at some point.

**Comment by TheSnowyChickens** [comment]
Should we install "fastWorkbench" in case of your last changes with the newest tinkers version?

At the moment, I got some "desync", If I try to craft some stuff in the crafting station:
![2018-05-20_16 04 00](https://user-images.githubusercontent.com/29357962/40279708-761944c6-5c47-11e8-9432-e6bbb4fa80dd.png)

It is only invis, but craftable. (the first log into planks worked, but then this)
MC 1.12.2
Forge 14.23.3.2698 
TConstruct-1.12.2-2.10.0.81
Mantle-1.12-1.3.2.24

**Comment by bonii-xx** [comment]
Ah, so this is the issue with the fastworkbench stuff. Guess I can close this now, too.

**Comment by TheSnowyChickens** [comment]
Okay, I create a new issue. :)
