### ISSUE TITLE
100 durability issue.

### ISSUE THREAD

**Issue by HopeArk** [SlimeKnights/TinkersConstruct#3433]
So All my tools durability are at 100, no more, no less. I thought it was another mod I had, but when I removed all the other mods, it still was like that. Help?

**Comment by TherminatorX** [comment]
What does the durability stat in the tool forge say? That's a more accurate value than the vanilla durability metadata viewed by F3+H

**Comment by HopeArk** [comment]
That says the correct one, but it isnt a visual problem as the tool breaks after used 101 times

**Comment by HopeArk** [comment]
I think I fixed it, but do you know what I could use that is accurate in displaying the durability?

**Comment by KnightMiner** [comment]
What version are you playing In? If 1.7, use TiC Tooltips. If 1.12 this issue should not exist.

**Comment by HopeArk** [comment]
1.7.10, and thanks

**Comment by KnightMiner** [comment]
In that case closing by saying install TiC tooltips
