### ISSUE TITLE
Game Crash while Initializing

### ISSUE THREAD

**Issue by JumperK** [SlimeKnights/TinkersConstruct#3434]
While trying to initialize Minecraft, the game crashed with an error: `java.lang.NullPointerException: The validated object is null`

Full crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 3/25/18 12:33 AM
Description: Initializing game

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:35)
	at slimeknights.tconstruct.tools.ToolClientEvents.onModelBake(ToolClientEvents.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_276_ToolClientEvents_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:35)
	at slimeknights.tconstruct.tools.ToolClientEvents.onModelBake(ToolClientEvents.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_276_ToolClientEvents_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2313955592 bytes (2206 MB) / 3056599040 bytes (2915 MB) up to 3056599040 bytes (2915 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx3072m -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:PermSize=128m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2634 83 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                | Source                                          | Signature                                |
	|:----- |:--------------------- |:---------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2                 | minecraft.jar                                   | None                                     |
	| UCH   | mcp                   | 9.42                   | minecraft.jar                                   | None                                     |
	| UCH   | FML                   | 8.0.99.99              | forge-1.12.2-14.23.2.2634.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.23.2.2634           | forge-1.12.2-14.23.2.2634.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater     | 1.0                    | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCH   | actuallyadditions     | 1.12.2-r133            | ActuallyAdditions-1.12.2-r133.jar               | None                                     |
	| UCH   | baubles               | 1.5.2                  | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | actuallybaubles       | 1.1                    | ActuallyBaubles-1.12-1.1.jar                    | None                                     |
	| UCH   | alt                   | 2.0.3                  | AdditionalLootTables-1.12-2.0.3.37.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | akashictome           | 1.2-10                 | AkashicTome-1.2-10.jar                          | None                                     |
	| UCH   | autoreglib            | 1.3-16                 | AutoRegLib-1.3-16.jar                           | None                                     |
	| UCH   | crafttweaker          | 4.1.6                  | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
	| UCH   | jei                   | 4.8.5.147              | jei_1.12.2-4.8.5.147.jar                        | None                                     |
	| UCH   | base                  | 3.7.1                  | base-1.12.2-3.7.1.jar                           | None                                     |
	| UCH   | chisel                | MC1.12.2-0.2.0.31      | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCH   | mantle                | 1.12-1.3.1.21          | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | tconstruct            | 1.12.2-2.9.1.65        | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
	| UCH   | basemetals            | 2.5.0-beta5            | BaseMetals-1.12-2.5.0-beta5.214.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | baseminerals          | 2.5.0-beta5            | BaseMinerals-1.12-2.5.0-beta5.43.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | baublelicious         | 1.4.0-4                | Baublelicious-1.4.0-4.jar                       | None                                     |
	| UCH   | bedbugs               | @VERSION@              | BedBugs-1.12-1.0.1.jar                          | None                                     |
	| UCH   | betteradvancements    | 0.0.5.17               | BetterAdvancements-1.12.2-0.0.5.17.jar          | None                                     |
	| UCH   | betterbedrockgen      | 6.0.2                  | BetterBedrockGenerator-1.12-6.1.1.jar           | None                                     |
	| UCH   | betterbuilderswands   | 0.11.1                 | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | bibliotheca           | 1.2.2-1.12.2           | bibliotheca-1.2.2-1.12.2.jar                    | None                                     |
	| UCH   | blockarmor            | 2.4.11                 | BlockArmor-1.12.2-2.4.11.jar                    | None                                     |
	| UCH   | ceramics              | 1.12-1.3.3b            | Ceramics-1.12-1.3.3b.jar                        | None                                     |
	| UCH   | chameleon             | 1.12-4.1.3             | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | chesttransporter      | 2.8.8                  | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| UCH   | clumps                | 2.0.0                  | Clumps-3.0.0.jar                                | None                                     |
	| UCH   | codechickenlib        | 3.1.6.339              | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | compactmachines3      | 3.0.7                  | compactmachines3-1.12.2-3.0.7-b197.jar          | None                                     |
	| UCH   | controlling           | 3.0.6                  | Controlling-3.0.6.jar                           | None                                     |
	| UCH   | ctgui                 | 1.0.0                  | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
	| UCH   | crafttweakerjei       | 2.0.0                  | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
	| UCH   | cucumber              | 1.0.4                  | cucumber-1.12-1.0.4.jar                         | None                                     |
	| UCH   | densemetals           | 1.1.0                  | DenseMetals-1.12-1.1.0.7.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | disenchanter          | 1.6                    | disenchanter-[1.12]1.6.jar                      | None                                     |
	| UCH   | endercompass          | 1.2.6.1                | EnderCompass-1.12-1.2.6.1.jar                   | None                                     |
	| UCH   | enderstorage          | 2.4.2.126              | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | shetiphiancore        | 3.5.6                  | shetiphiancore-1.12.0-3.5.6.jar                 | None                                     |
	| UCH   | endertanks            | 1.6.5                  | endertanks-1.12.0-1.6.5.jar                     | None                                     |
	| UCH   | modernmetals          | 2.5.0-beta5            | ModernMetals-1.12-2.5.0-beta5.120.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | endmetals             | 1.2.0-beta3            | EndMetals-1.12-1.2.0-beta3.42.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | engineersworkshop     | 1.4.0-1.12.2           | EngineersWorkshop-1.4.0-1.12.2.jar              | None                                     |
	| UCH   | extrautils2           | 1.0                    | extrautils2-1.12-1.7.5.jar                      | None                                     |
	| UCH   | fastleafdecay         | v14                    | FastLeafDecay-v14.jar                           | None                                     |
	| UCH   | forgemultipartcbe     | 2.4.0.55               | ForgeMultipart-1.12.2-2.4.0.55-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | microblockcbe         | 2.4.0.55               | ForgeMultipart-1.12.2-2.4.0.55-universal.jar    | None                                     |
	| UCH   | minecraftmultipartcbe | 2.4.0.55               | ForgeMultipart-1.12.2-2.4.0.55-universal.jar    | None                                     |
	| UCH   | guideapi              | 1.12-2.1.5-60          | Guide-API-1.12-2.1.5-60.jar                     | None                                     |
	| UCH   | infinitefluids        | 1.2.0                  | infinitefluids-1.11-1.2.0.jar                   | None                                     |
	| UCH   | inventorypets         | 1.4.9.9b               | inventorypets-1.12-1.4.9.9b.jar                 | None                                     |
	| UCH   | ironbackpacks         | 1.12.2-3.0.5-6         | IronBackpacks-1.12.2-3.0.5-6.jar                | None                                     |
	| UCH   | ironchest             | 1.12.2-7.0.40.824      | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCH   | journeymap            | 1.12.2-5.5.2           | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | lootbags              | 2.5.4b                 | LootBags-1.12.2-2.5.4b.jar                      | None                                     |
	| UCH   | mousetweaks           | 2.8                    | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCH   | mysticalagriculture   | 1.6.8                  | mysticalagriculture-1.12-1.6.8.jar              | None                                     |
	| UCH   | mysticalagradditions  | 1.2.7                  | mysticalagradditions-1.12-1.2.7.jar             | None                                     |
	| UCH   | nethermetals          | 1.2.0-beta3            | NetherMetals-1.12-1.2.0-beta3.52.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | notes                 | 1.1.1                  | Notes-1.12-1.1.1.jar                            | None                                     |
	| UCH   | oreexcavation         | 1.4.113                | OreExcavation-1.4.113.jar                       | None                                     |
	| UCH   | orespawn              | 3.2.2                  | OreSpawn-1.12-3.2.2.113.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | projecte              | 1.12-PE1.0.0           | ProjectE-1.12-PE1.2.0.jar                       | None                                     |
	| UCH   | redstoneflux          | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | plustic               | 6.3.7.0                | plustic-6.3.7.0.jar                             | None                                     |
	| UCH   | silentlib             | 2.2.16                 | SilentLib-1.12-2.2.16-97.jar                    | None                                     |
	| UCH   | silentgems            | 2.6.9                  | SilentsGems-1.12-2.6.9b-265.jar                 | None                                     |
	| UCH   | snad                  | 1.12.1-1.7.09.16a      | Snad-1.12.1-1.7.09.16a.jar                      | None                                     |
	| UCH   | storagedrawers        | 1.12-5.2.5             | StorageDrawers-1.12.2-5.3.5.jar                 | None                                     |
	| UCH   | theoneprobe           | 1.4.21                 | theoneprobe-1.12-1.4.21.jar                     | None                                     |
	| UCH   | tinker_io             | release 2.6.1          | tinker_io-1.12.2-release+2.6.1.jar              | None                                     |
	| UCH   | tinkersaddons         | 1.0.7                  | Tinkers'+Addons-1.12.1-1.0.7.jar                | None                                     |
	| UCH   | tcomplement           | ${version}             | TinkersComplement-1.12.2-0.2.3.jar              | None                                     |
	| UCH   | tinkertoolleveling    | 1.12-1.0.3.DEV.56fac4f | TinkerToolLeveling-1.12-1.0.3.jar               | None                                     |
	| UCH   | topaddons             | 1.12.2-1.5.0           | topaddons-1.12.2-1.5.0.jar                      | None                                     |
	| UCH   | translocators         | 2.5.0.70               | Translocators-1.12.2-2.5.0.70-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | ts2k16                | 1.2.8                  | TS2K16-1.2.8.jar                                | None                                     |
	| UCH   | woot                  | 1.12.2-1.0.1           | woot-1.12.2-1.0.1.jar                           | None                                     |
	| UCH   | xpbook                | 0.0.3-beta             | xpbook-1.12-0.0.3-beta.jar                      | None                                     |
	| UCH   | xpfromharvest         | 1.0                    | xpfromharvest-1.12-1.0.1.jar                    | None                                     |
	| UCH   | yoyos                 | 1.12.2-1.2.2.20        | yoyos_1.12.2-1.2.2.20.jar                       | None                                     |

	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.3.12804 Compatibility Profile Context 13.352.1004.1007' Renderer: 'AMD Radeon HD 8210'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- CeramicsPlugin (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.2.2634
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 8210 GL version 4.3.12804 Compatibility Profile Context 13.352.1004.1007, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD E1-2100 APU with Radeon(TM) HD Graphics

**Comment by KnightMiner** [comment]
You have chisel installed without CTM. It produces hard to trace crash reports if you do that.

**Comment by JumperK** [comment]
Thing is, I DO have CTMLib installed. That couldn't be the problem, could it?

**Comment by KnightMiner** [comment]
No, not CTMLib, CTM. It would show up in your mod list if it were installed.
