### ISSUE TITLE
Lag when loaded with Galacticraft (1.12)

### ISSUE THREAD

**Issue by netcore10** [SlimeKnights/TinkersConstruct#3435]
After troubleshooting my personal modpack for hours i found that tinkers construct causes lag (even when moving the mouse, it moves then freezes then moves then freezes) when loaded with galacticraft. Is there a chance this can be looked into?

**Comment by KnightMiner** [comment]
Going to need more information than "lag". What kind of lag? What versions are you using? Does it happen with just Tinkers and GalacticCraft? Can you give a copy of your game logs using pastebin?

**Comment by TheQuadShot** [comment]
I can't repro this. I created a Smeltery and smelted a bunch of iron (about 50 blocks). I do run both of these mods on all of my games (each version for testing GC) and I haven't seen this on any of them here's what I got:
Minecraft 1.12.2
Forge 14.23.2.2619
Galacticraft-Planets-1.12.2-4.0.1.165.jar
GalacticraftCore-1.12.2-4.0.1.165.jar
MicdoodleCore-1.12.2-4.0.1.165.jar
Mantle-1.12-1.3.1.21.jar
TConstruct-1.12.2-2.9.1.65.jar

complete list of mods (49 total)
https://pastebin.com/b9CFaVjm

**Comment by netcore10** [comment]
Suppose its just me then, or my pc, maybe other things i'm missing. Sorry

**Comment by KnightMiner** [comment]
Closing for lack of logs or anything else to help debug the issue. If you think Tinkers is causing lag, please give more information so it can be verified
