### ISSUE TITLE
[1.12.2 - Suggestion] A config option to disable the Custom Hearts render.

### ISSUE THREAD

**Issue by Z-Tunic** [SlimeKnights/TinkersConstruct#3436]
As far as I know, at least in "TConstruct-1.12.2-2.9.1.65.jar" that I'm using... there's no option to disable the custom hearts render so you can see your rows of hearts instead of being stacked over each row.

**Comment by TherminatorX** [comment]
TCon doesn't do anything with hearts now, afaik

**Comment by laz2727** [comment]
Well, no, it doesn't. Hearts are changed by Mantle.

>

**Comment by Z-Tunic** [comment]
Huh, thought Tinkers affected hearts. So Mantle affects them?

**Comment by KnightMiner** [comment]
Yep, that's a mantle feature. Check the mantle config, and if it's not there head to mantle's issue tracker
