### ISSUE TITLE
Damaged Armor in Smeltery

### ISSUE THREAD

**Issue by Kaelthalon** [SlimeKnights/TinkersConstruct#3437]
Is it possible to grab the damage value from the armor and give a percentage of iron. For example, an iron chestplate with 60% damage would give 691.2 mB of iron out of 1,152 for a fully repaired piece.

**Comment by SweetSugarSugar** [comment]
Literally the same as #3411 

Consider reading the [FAQ](https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ) before posting.
