### ISSUE TITLE
Tool with auto-smelt not turning sand into glass.

### ISSUE THREAD

**Issue by JohnTitor95** [SlimeKnights/TinkersConstruct#3440]
For example, using a pick or mattock with auto-smelt, when i break a sand block, i do not get back glass. If this is because neither are effective against sand, then how are we supposed to make multitools capable of auto-smelting various blocks without having to juggle 3 different tools?

**Comment by TheQuadShot** [comment]
do you get charcoal when you use the Mattock on wood?

**Comment by JohnTitor95** [comment]
Yeah, i guess it is just because it's not an effective tool against sand?

**Comment by TheQuadShot** [comment]
I think so, when mDiyo created it he used it to clear land(tree's and dirt). So I'm pretty sure this is by design. I would make an excavator with autosmelt to get glass, however I do prefer clear glass over vanilla any day.
