### ISSUE TITLE
Alumite Smeltery Issue

### ISSUE THREAD

**Issue by Marvin732** [SlimeKnights/TinkersConstruct#3444]
Tried to look everywhere, in creative mode, Just enough items mod, theres not alumite, every FTB page says, 1 obsidian , 2 iron ore, 5 aluminum ore into the smeltery and you get Alumite, its entirely missing

**Comment by TherminatorX** [comment]
Alumite is not currently present in default Tinker's Construct 2.

**Comment by Marvin732** [comment]
Which mod does it include?

**Comment by KnightMiner** [comment]
Alumite was replaced with KnightSlime in TiC 2. There are some addons which include it in 1.12 (I think PlusTiC is among them), but I cannot account for the balance of any of them.
