### ISSUE TITLE
Hammer doesnt mine ores?

### ISSUE THREAD

**Issue by Marvin732** [SlimeKnights/TinkersConstruct#3445]
i made a bronze tough tool rod, slime hammer head, Obsidian large plate, electrum large plate and the problem is, when i try to farm any ore, it just says Pickaxe with a red X and i can hold left button like i want but nothing happens

**Comment by SweetSugarSugar** [comment]
You don't have the required mining level to mine the ore.  Check the modpack configuration and settings...

**Comment by laz2727** [comment]
Both slime and electrum have barely any mining level. At least sharpen your
tool first.

2018-04-01 9:28 GMT+00:00 ☆Sugar☆ <notifications@github.com>:

**Comment by bonii-xx** [comment]
You need an appropriate harvest level for your hammer. Currently you're sitting on a wooden pickaxe level.
