### ISSUE TITLE
Won't open minecraft

### ISSUE THREAD

**Issue by jjgarnett** [SlimeKnights/TinkersConstruct#3446]
When I click launch on the launcher it will load for about a half minute and then say "Tinkers' Construct is missing mods it depends on Include the following mods or remove Tinkers' Construct  
Mantle 1.12-1.3.1 or above
see 'latest.log' for technical information"

What does this mean and how do I fix it. It happens with a lot of other mods as well!!

**Comment by SweetSugarSugar** [comment]
It means that the mod has dependencies and you have to go and download those mods...

**Comment by bonii-xx** [comment]
Download Mantle/the respective mods dependencies.
