### ISSUE TITLE
Hello guys problem Tinker Construct

### ISSUE THREAD

**Issue by mixilester009** [SlimeKnights/TinkersConstruct#3447]
I have this problem

https://pp.userapi.com/c844417/v844417223/19d79/P_QgY0T3Ftc.jpg
![02-04-2018 105906](https://user-images.githubusercontent.com/25255093/38185297-f127ea2a-3666-11e8-875e-0a9187782401.png)

**Comment by TheQuadShot** [comment]
I think you need this
https://git-scm.com/download/win
Or you need to add it to you path. I would also recommend that you run Windows Power Shell (a much better scripting environment). https://docs.microsoft.com/en-us/powershell/

**Comment by bonii-xx** [comment]
Looks like it's missing git, yes. Also you should use the 1.12 branch.

**Comment by KnightMiner** [comment]
Closing for lack of response. You need Git to build the repository as listed on the README.
