### ISSUE TITLE
Tinker Bolts?

### ISSUE THREAD

**Issue by SmugAnimeFace** [SlimeKnights/TinkersConstruct#3448]
I'm sure you're aware but currently Tinker Bolts aren't currently craftable you can't make the core and it lists the core twice in the Tool Forge. Is there any information about when they might be introduced? Or why Crossbows are craftable when you can't get the bolts yet?

**Comment by bonii-xx** [comment]
You can craft bolts. There even is an entry in the book specifically dealing with that topic.
