### ISSUE TITLE
Mod won't launch, despite all other necessary mods installed

### ISSUE THREAD

**Issue by squishygamer47** [SlimeKnights/TinkersConstruct#3450]
No matter what I try, Tinkers' Construct simply isn't launching. Whenever I launch Minecraft the response is a screen responding that Minecraft Forge isn't installed.
![tconstruct-errorscreen-missingforge](https://user-images.githubusercontent.com/38144997/38446243-080f43da-39c5-11e8-8c3f-f2a0fda8f96b.PNG)
This was unexpected, considering I have downloaded the most recent Forge version, for 1.12.2, (as a version in the launcher), and have Mantle installed in my mods folder. I'll attach the files if needed.
Thanks in advance!

**Comment by squishygamer47** [comment]
EDIT: You may have to walk me through this because I have zero experience with coding.

**Comment by squishygamer47** [comment]
I'm using 14.23.0.2529. I may not actually have the most recent version, but it works with 1.12.2.
![forgebutton](https://user-images.githubusercontent.com/38144997/38446455-2775bbe0-39c6-11e8-98e0-bfd1131b6473.PNG)

**Comment by TherminatorX** [comment]
Then you will need to get 14.23.1.2577 or above
What you have is below

**Comment by squishygamer47** [comment]
Ah. I'm an idiot. Whatever the case, though, thank you for helping!
