### ISSUE TITLE
Cannot add modifiers to Travelers Armor 1.7.10

### ISSUE THREAD

**Issue by RedBlaze717** [SlimeKnights/TinkersConstruct#3451]
Playing a Revolutionized Warfare pack that has a few mods added. When attempting to add redstone to the travelers gloves for the haste buff the game crashes.

https://pastebin.com/KsePpiJg

**Comment by TherminatorX** [comment]
_at lance5057.tDefense.core.tools.modifiers.ModifierBoolExclusive.canModify_
Not TiC's fault here it would seem

**Comment by RedBlaze717** [comment]
Is there anyway to figure out what is causing it so that the offending mod can be removed?

**Comment by TheQuadShot** [comment]
It's Tinkers Defense
most of the time you get an error with the mod name in it, however it is kind of hidden here so in these cases I do a search on the first thing listed lance5057, this leads you to his github page which lists his projects and one of them is Tinker Defence hench tDefense. Hope that helps

**Comment by KnightMiner** [comment]
Yep, looks like a Tokers Defense issue. 1.7 is also no longer supported anyways, it's nearly 3 years old now
