### ISSUE TITLE
White list of mobs

### ISSUE THREAD

**Issue by mixilester009** [SlimeKnights/TinkersConstruct#3452]
Please make a white list in the config for the mobs who will milk the liquid, if they cause damage from the smelter. version of the game 1.7.10
![08-04-2018 201009](https://user-images.githubusercontent.com/25255093/38469183-f6659926-3b69-11e8-8b23-8fb44cb08c65.png)

**Comment by KnightMiner** [comment]
1.7 is no longer receiving updates, so there won't be any new config options added.
