### ISSUE TITLE
[1.12.2] Slime/Blood Boots

### ISSUE THREAD

**Issue by fandomaniac** [SlimeKnights/TinkersConstruct#3454]
Please consider adding durability to these boots. Right now, they are overpowered and are getting heavily abused on my multiplayer servers.

**Comment by bonii-xx** [comment]
No, they're fine as is.

**Comment by fandomaniac** [comment]
Thank you for responding. It was just a suggestion. I hope you will consider adding a configuration setting to disable/enable them. I'm still a fan of your mod either way.

**Comment by KnightMiner** [comment]
If you need to disable them, just remove the recipe with something like crafttweaker. Since they provide no defense value there is no real concern with unbreakable armor anyways.
