### ISSUE TITLE
Tinker tools still valid after breaking midway through Ore Excavation harvest

### ISSUE THREAD

**Issue by Funwayguy** [SlimeKnights/TinkersConstruct#3456]
**Problem:**
After being brought to my attention from a user playing SevTech Ages I did a bit of testing and found that if a Tinker tool breaks while excavating with Ore Excavation, not only does the excavation continue but items are still dropped. This appears to be caused by the fact that Tinkers tools do not revoke their harvest-ability status after being broken and only prevent the user from starting new harvests. I've tried fixing this on Ore Excavation's side but my limited options caused some noticeable side effects.

**Suggested Solution:**
Would it be possible to add an additional `ToolHelper.isBroken(stack)` to `canHarvestBlock` on this line:
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/tools/ToolCore.java#L185

**Affected Mods & Versions:**
Forge - 14.23.3.2655
Ore Excavation - 1.4.133
Tinkers' Construct - 2.9.1.65
Mantle - 1.3.2.24

**Related Notes:**
https://github.com/Darkosto/SevTech-Ages/issues/1816

**Comment by KnightMiner** [comment]
Huh, thought we caught all the cases. I know the harvest level is set to -1 after the tool breaks, so you could maybe check that until this is fixed.

**Comment by bonii-xx** [comment]
it looks like there's some interaction there that's not considered, yes. I'm not entirely convinced that it wont screw up other edge cases though. I'll change it for now and see if things go awry somewhere else.

**Comment by Insane96** [comment]
Seems like still happening as noe
