### ISSUE TITLE
Allow Crafting Station to check UP/DOWN Inventories

### ISSUE THREAD

**Issue by borg286** [SlimeKnights/TinkersConstruct#3459]
Currently the Crafting station only works with inventories placed at the same horizontal level. By changing [these](https://github.com/SlimeKnights/TinkersConstruct/blob/08f7180399ca8ad4717493dd0aa5a63b7aa14584/src/main/java/slimeknights/tconstruct/tools/common/inventory/ContainerCraftingStation.java#L51) two [references](https://github.com/SlimeKnights/TinkersConstruct/blob/08f7180399ca8ad4717493dd0aa5a63b7aa14584/src/main/java/slimeknights/tconstruct/tools/common/inventory/ContainerCraftingStation.java#L119) to [VALUES](https://github.com/nullbear/minecraft/blob/master/net/minecraft/util/EnumFacing.java#L38) we get the ability to have more ways to organize a base. 

Based on [these java docs ](https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.9.2) this will imply that the check will check UP/DOWN before getting to the horizontals.

**Comment by bonii-xx** [comment]
No. That's not how a workshop works.
