### ISSUE TITLE
Tool dupe w/ multiple players

### ISSUE THREAD

**Issue by randomlypickedname** [SlimeKnights/TinkersConstruct#3460]
Modpack: Sevtech 3.0.6
Mod ver: 2.9.1.65

If one player is not allowed to modify a tool and is using a tool forge while another player accesses it, they may modify the tool and get their unmodified tool and the upgraded one back.

Darkosto/SevTech-Ages#1962

**Comment by bonii-xx** [comment]
Most likely fixed together with #3495

**Comment by evernife** [comment]
still works

**Comment by KnightMiner** [comment]
Possibly same bug as #3997. Its probably fixed in 1.16 as part of the rewrite in any case, bit too difficult to fix in 1.12 without significant rewrites.

**Comment by EverNife** [comment]
Anyone needing a fix for this issue on 1.12.2 can use the [Dupe fix Project](https://www.curseforge.com/minecraft/mc-mods/dupefix-project)
