### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by Skronos** [SlimeKnights/TinkersConstruct#3463]
i have just enough items and tinkers, and this causes fps drop, there is a solution for this issue?

**Comment by KnightMiner** [comment]
Versions? What makes you say this is a FPS drop? What are you doing? Holding a tool? Looking at a specific type of block? Give details so we can verify if this is an issue.

**Comment by TherminatorX** [comment]
My guess is looking at all the toolparts in JEI, which I thought was fixed after a certain version of one or the other. Agreed that more info is required.

**Comment by KnightMiner** [comment]
Closing for lack of information. Please submit a report with more information if you think this mod is causing a FPS drop.
