### ISSUE TITLE
purple,blue and magma slime blocks

### ISSUE THREAD

**Issue by Anarchy079** [SlimeKnights/TinkersConstruct#3464]
i noticed there is no recipe for the tinkers slime blocks to turn them back into orbs. (the recipe for turning them into 9 piece block requires a congelled slime version and 5 orbs to make a 9 piece block) but for some reason you cant turn them back like normal slime blocks into orbs
![image](https://user-images.githubusercontent.com/30153463/39369948-9bdbb2c8-4a0b-11e8-8e10-32c2c61015ae.png)
 that slime block recipe. as in the picture.. you cant really turn them back.. into orbs
unless they were not intended to be turned back

**Comment by bonii-xx** [comment]
Hm, I think back when they were added vanilla didn't have that recipe yet. Just needs to be added. By the way you can take ingame screenshots by pressing F2.

**Comment by Anarchy079** [comment]
glad to be of help. and i find it easier to use my phone -w-
