### ISSUE TITLE
Client Desync with active smeltery

### ISSUE THREAD

**Issue by dashkal** [SlimeKnights/TinkersConstruct#3465]
Symptom is that on 15 second intervals nearby inventories if open appear to suddenly clear.
It's just a desync, as I can click on a slot I know was occupied and it will pick up.
It's definitely a desync, since I can shift-click items into the inventory and they appear alone in the upper-left.  Picking up the item in this case picks up the real item from that slot and the inventory re-synchronizes.

This doesn't happen to all inventories.  I have seen this with Immersive Engineering storage crates, and MultiStorage storage units.
I've also seen it with Enderman Heads from EnderIO.  For those, the symptom is that the head snaps back to facing north, then turns again to look at the player.
Of interest, vanilla chests are not affected.

All mods/versions installed when reproducing:
```
Minecraft: 1.12.2
MultiMC: 0.6.2-1222
Forge: 14.23.3.2655
Java: 1.8.0_171
jei_1.12.2-4.9.0.163.jar
Mantle-1.12-1.3.2.24.jar
TConstruct-1.12.2-2.9.1.65.jar

ImmersiveEngineering-0.12-80.jar
  or
shetiphiancore-1.12.0-3.5.6.jar
multistorage-1.12.0-1.4.9.jar
  or
EnderCore-1.12.2-0.5.20.jar
EnderIO-1.12.2-5.0.22.jar
```

I tested those three groups independently of one another (removed IE, added MultiStorage, removed MultiStorage, added EnderIO)

**Comment by dashkal** [comment]
Just did a quick test with two ender heads.  One in the chunk with the smeltery, one outside.  Only the smeltery one resets.

**Comment by dashkal** [comment]
Size/construction may be relevant.
https://i.imgur.com/uGrI1Rx.png
Both of these do it, and independently (15s, but not synced to each other).
The one on the left didn't start doing it until I added the third height layer

**Comment by Foxgreat** [comment]
Even simple structure causes chests inventory invision by Tinker smeltery structure more than 3x3x2 

Actual proble

**Comment by bonii-xx** [comment]
It's weird, considering the amount of modpacks that have both TiC and IE and have no problems. So far I also can't confirm it, from my perspective it's most likely something else that messes with it or the mods themselves, as I've said above.

**Comment by Lost-Ninja** [comment]
Came here to report same issue but with Iron Chests 2 (from FTB Sky Adventures).

**Comment by QBFreak** [comment]
I spent the day playing around with this. It seems to be affected by Smeltery size, but I couldn't pin down exactly what the criteria are. That said, the following Smeltery configurations will all cause the bug (WxLxH):

- 4x4x3
- 7x2x4
- 1x1x16

It only needs to be a valid Smeltery from the Controller's perspective (Seared Brick etc, Controller, Tank) things like drains and what not don't matter. Filling in the corners or leaving them empty has no effect.

I was able to reproduce this with the latest Tinkers' (`TConstruct-1.12.2-2.12.0.135`) and Mantle (`Mantle-1.12-1.3.3.55`) that were available from CurseForge. Only some modded storage is affected. Iron Chests was recently updated and is no longer affected. The Wooden Storage Crate from Immersive Engineering (ImmersiveEngineering-0.12-89) still exhibits the symptoms.

Let me know if there's any other information I can provide.

**Comment by KnightMiner** [comment]
According to @alexbegt who fixed this issue in Iron Chests, it has to do with the way vanilla handles large numbers of packets. Apparently if the number gets too high, it shoves all the data into the chunk packet which most blocks are not expecting. I don't think the size of the smeltery is your issue as much as the location.

There might be something we can do to reduce the number of block updates from an active smeltery which should reduce the chances of this issue happening, but it really is a bug in the mods code apparently that just is rarely exposed.

**Comment by QBFreak** [comment]
Awesome! Thanks for that. I'll relay this on to Immersive Engineering, as that's the one I'm interested in. I'll leave the other mods to the other participants as they desire.

**Comment by KnightMiner** [comment]
93f7802 should for the most part prevent this issue by decreasing smeltery update packets. I'll mark this as resolved for now and we can see if the issue persists after the next release.
