### ISSUE TITLE
Breaking Ores/Stones with Pickaxe/Hammer from Tinkers Construct doesnt drop any blocks (as example Cobblestone/Stone)

### ISSUE THREAD

**Issue by Paepodlun** [SlimeKnights/TinkersConstruct#3466]

**Comment by KnightMiner** [comment]
Version? Mod list? Single player or multiplayer? Does it happen with vanilla tools?

**Comment by Paepodlun** [comment]
Mod list: 
Jei (just enough items)
Conquest reforged
Tinker s construct
Apple skin + apple core
Hunger overhaul
Parms harvestcraft
Opti fine
Foamfix
Better fps
Backpacks
Mocreatures 
Custom mob spawner
Infernal mobs
Bibliocraft
Geographycraft( climatecraft)

**Comment by KnightMiner** [comment]
Does this happen with just Tinkers Construct? Does remove one of your mods fix it?

**Comment by Paepodlun** [comment]
I removed Conquest Reforged 1.12.2 mod and then it worked. So its Conquest Reforged wich causes the trouble. :/

**Comment by KnightMiner** [comment]
In that case, closing as a Conquest Reforged issue, report it to them.
