### ISSUE TITLE
Is there a plan for making Tinker's Construct 1.13 compatible?

### ISSUE THREAD

**Issue by hippietilley** [SlimeKnights/TinkersConstruct#3467]
I was wondering if there was a plan and if so, if/how I could help. I'm new to Minecraft modding, but well versed in Java and would love to help out.

**Comment by KnightMiner** [comment]
Well, first off 1.13 actually has to be released. Then Forge needs to be released for 1.13. Plans will be made after that.

**Comment by olee** [comment]
Forge for 1.14 is out already and I see there is a branch for 1.14 - is there any roadmap or something like that available?

**Comment by bonii-xx** [comment]
We're working on it as time allows, so the only roadmap we have is "When it's done"
