### ISSUE TITLE
1.12 Direwolf20 pack Tinker's tools disappearing.

### ISSUE THREAD

**Issue by rodricraft93** [SlimeKnights/TinkersConstruct#3468]
I couldn't find anyone else with the same issue or topic, I recently started playing FTB mods using the twitch app. 

When I played Direwolf 20 1.12 for a few days everything seemed fine until I died, when I went back to my body and got my stuff from the gravestone, any item related to tinker's construct was gone. All of them had been replaced for vanilla pickaxe, shovel, or equivalent to pickaxe hammer or others. 

Lost tons of materials and time, have no idea how to fix it, not even going to a different dimension or nether works, they are just gone. Just using the normal app and minecraft account with no optifine or anything weird.

Any help?

**Comment by KnightMiner** [comment]
Sounds like some mod is replacing the tools on death. Can you reproduce with a minimal set of mods?

**Comment by bonii-xx** [comment]
Definitively not TiC related, since there is no way a TiC tool can randomly turn into a vanilla tool, they're two completely different things. Some other mod screwing with your graves.
