### ISSUE TITLE
[Feature Request] Vanilla Arrows use with Tinker's Crossbows

### ISSUE THREAD

**Issue by QAngelusQ** [SlimeKnights/TinkersConstruct#3469]
I didn't know that vanilla arrows can be used with shortbows and longbows. However if I try with a crossbow, nothing fires and the crossbow goes back to being undrawn (if thats the word for it). I was wondering if crossbows and vanilla arrows could be made to be compatible? 
I mean it works in creative mode but not in survival.

**Comment by bonii-xx** [comment]
Crossbows don't shoot arrows, they shoot bolts, which resemble arrows. But vanilla arrows are not sturdy enough to withstand the force. Cheap stick manufactured arrows.

**Comment by xenxero1** [comment]
The fact that Crossbows shoot arrows in creative mode is a little confusing to me. It gives the impression that it should be compatible. Maybe change the default "creative bolt" to some standard version of a low-mid tier bolt for the sake of consistency? wood-iron core with feathers would probably be fine.

**Comment by bonii-xx** [comment]
It shoots vanilla arrows because it uses the same code base as the bows. The bows only shoot something in creative without ammo because the vanilla bow does that too (also for testing), and it doesn't matter what, since, if you're in creative you can create or spawn in any bolt anyway.
