### ISSUE TITLE
Slime Islands

### ISSUE THREAD

**Issue by Adarcer** [SlimeKnights/TinkersConstruct#3478]
I am not a fan of floating anything whether its the upper part of trees or islands in minecraft. I would like too suggest a toggle to make the islands spawn on the ground instead. this way I can still get the resources
slime, saplings etc and not have too leave ugly nerdpoles or floating OCD issues

**Comment by KnightMiner** [comment]
Remaking the slime islands to generate in the ground is a lot more difficult than just saying "island, generate on the ground". It would probably end up needing to be a biome ultimately just to integrate it into the terrain properly, which is beyond the design of the islands. You are probably better off asking for one of the addons to add a slime biome then disabling the islands here.
