### ISSUE TITLE
Frying pan knockback on players

### ISSUE THREAD

**Issue by Wiral2** [SlimeKnights/TinkersConstruct#3480]
Currently on my server the frying pan with some piston modifiers doesn't knockback players, but works on mobs. Is this a bug or intended?

**Comment by Mike-U5** [comment]
Can confirm. Tried to slam my buddy across a large cliff but it didn't work. ):

**Comment by KnightMiner** [comment]
Does it work without the modifiers? I know it used to work fine

**Comment by TherminatorX** [comment]
There was a [pull request](https://github.com/SlimeKnights/TinkersConstruct/pull/3328) that supposedly fixed this stuff, but was closed since they altered slimesling code as well. Dunno if the frying pan behavior was ever properly implemented.

**Comment by TherminatorX** [comment]
Wait, so...whose fault is it if it doesn't work then?

**Comment by TherminatorX** [comment]
Bump cus someone on the discord mentioned this, unable to currently test

**Comment by KnightMiner** [comment]
I just double checked the fix from the PR and it does appear to be correct, we need to send the packet to the the player who is being knocked back so they know to move. Should be fixed for the next release
