### ISSUE TITLE
[1.12.2][Crash/DoS] Giant tanks create malformed packets

### ISSUE THREAD

**Issue by Techokami** [SlimeKnights/TinkersConstruct#3481]
Minecraft 1.12.2
Forge 14.23.3.2678
Tinker's Construct 1.12.2-10.0.75
Mantle 1.12-1.3.2.24

I was creating some large tanks from the Smeltery module, the largest I possibly could (11x11, base at Y=2 and top at Y=254) with the controller at Y=3, 4 fluid ports at Y=4, and 8 more fluid ports at Y=70. I created the structure before adding the controller. I placed the controller on the first tank (of 9), everything worked correctly. I placed the controller on the second tank, and my client got forcibly disconnected with the following message: 
```Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2664359 is larger than protocol maximum of 2097152```

What did I do wrong? I built tanks like this in 1.10.2 without this happening.

**Comment by KnightMiner** [comment]
Please post a copy of your full game logs (using a site like Pastebin), going to need a bit more information that might be in there.

**Comment by bonii-xx** [comment]
You probably killed the network layer by requiring it to send too much at once.

**Comment by bonii-xx** [comment]
11x11 smeltery, let's say 10x1 for easier math = 4 sides of length 10 each. With a height of about 250. 4*10*250 = 10000.

As I said, you broke the network layer (aka Netty). I guess because the packet got too big. There really only are two choices: Don't build them that big or we'll have to put a limit to height. ;P

**Comment by Techokami** [comment]
Yeah, cap the height. I guess I'll have to use Thermal Expansions' tanks with hacked enchantments to hold lots of fluids for the facility then. Won't look as awesome and awe-inspiring as an array of massive dark towers going high into the sky, but it'd be a lot less TEs.

**Comment by Techokami** [comment]
Oh heck no, I don't need an unlimited *source* of fluid. I just want to store a crapload of fluid and be able to transport it all around. Like, an Immersive Petroleum oil refinery operation. Or a centralized lava storage tank that can then feed anything else that needs lava (like a smeltery). And if you're trying to make Immersive Engineering steel, good lord does that generate a lot of creosote oil from making the coal coke.

With the multiblock tanks from this mod, I can point to a bigass structure and say "that holds a crapload of gasoline" and it's awe inspiring. But it's too many tile entities, so instead I have to go with a Thermal Expansion resonant portable tank with a Holding enchantment modified to be at level 127, which would hold about... a third of the Tinker's structure? So it'd be reduced to a stack of 3 or 4 of these things, which is a lot less awe inspiring and a lot more magic block-y, but far less TEs.

**Comment by Techokami** [comment]
I don't have ExtraCells present in this pack. Maybe I should add it? Because AE2 by itself has no fluid support, and I'm not using Refined Storage (because AE2 is already present). But the idea of a facade... that would be a good idea. Too bad you can't judge how much is inside by looking at it, but hmmm... something to consider. 🤔
