### ISSUE TITLE
Can't add custom modifiers to Materials and You

### ISSUE THREAD

**Issue by ejektaflex** [SlimeKnights/TinkersConstruct#3482]
As far as I can tell, there does not seem to be a way for other mods to add their own modifiers to the book "Materials and You", making adding new modifiers a moot point since they do not know that the modifier exists.

Versions:
TCon: 1.12.2-2.10.0.72
Mantle: 1.12-1.3.2.2
Forge: 14.23.3.2681

I'd really appreciate if this were implemented! Another thing that does not seem to exist is the ability for added materials from other mods to have flavour text (Such as the extra text that shows up in the Wood and Stone material pages). A way of adding this to the book would be fantastic.

Thank you!

**Comment by fuj1n** [comment]
For all the book transformation, please check out the BookTransformer, there are some examples of it in the same class.

(BookTransformer)[https://github.com/SlimeKnights/Mantle/blob/master/src/main/java/slimeknights/mantle/client/book/BookTransformer.java]

**Comment by laz2727** [comment]
You can add them, but they're going to end up at the end of the book:
![2018-05-14 19 58 13](https://user-images.githubusercontent.com/2369751/40005361-41f9617c-5787-11e8-94bb-b0c965aac6e3.png)
You need to register a book repo with TinkerBook.INSTANCE.addRepository (just look for it in TinkerBook, it's not that hard), add index.json, a book section and modifier pages. You can look for all that in my mod, actually, it's on Github.

**Comment by bonii-xx** [comment]
Yes, because the modifier listing is not generic since I want a specific ordering. Just add your own modifier listing, you should be able to reuse everything directly.

**Comment by ejektaflex** [comment]
Alright, I'll try it. I'll reopen if anything arises.
