### ISSUE TITLE
Tinkers causing game to crash at launch

### ISSUE THREAD

**Issue by lillyleaf101** [SlimeKnights/TinkersConstruct#3483]
I recently put together a new modpack for 1.10.2 and had issues with it crashing at launch. I went through each mod in batches and eventually came to tinkers construct (and tool leveling) as the only mods causing the crash.

Is there a way to fix this? I tried taking out other mods that others have said they had conflicts with in the past and it does nothing to make tinkers work.

**Comment by KnightMiner** [comment]
If it is crashing, a crash report might be helpful. Since that says what is crashing. Copy it to pastebin and link it here.

You also should always provide mod versions in issue reports, along with a mod list.

**Comment by bonii-xx** [comment]
You simply ran out of memory. If you're using a mod launcher try increasing memory, if you start it yourself your memory parameters may be incorrectly set.
