### ISSUE TITLE
Inconsistent material requirement for casts

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#3484]
Minecraft 1.12.2
 Forge 14.23.3.2668
 TConstruct 1.12.2.10.0.65
 Mantle 1.12-1.3.1.21

I don't understand why it would take more gold to fill the same volume.
To create a cast it reqires:
288 mB Gold
144 mB Brass
144 mB Aluminum Brass

**Comment by bonii-xx** [comment]
Originally that's from the days when TiC itself added aluminium ore. Gold was only another option if you didn't have the aliminium and copper, or were too lazy. It still is that way, if you waste gold on casts when you don't have to you should feel bad ;P
It's serving its purpose and will stay that way.

**Comment by YaibaToKen** [comment]
@bonii-xx I do have to agree with TheQuadShot, it still doesn't make sense from a logical point of view, seeing as the volume to be filled is the same regardless of the material used, to use twice as much gold as compared to using brass or alubrass. But in the end, you're the developer, not us.
