### ISSUE TITLE
Just a little visual bug with the crafting station....

### ISSUE THREAD

**Issue by SniperHauss89** [SlimeKnights/TinkersConstruct#3486]
Hello! I just felt compelled to post this for a quite minor visual issue I noticed.

Issue:
**Started in TConstruct-1.12.2-2.10.0.75 then updated to 1.12.2-2.10.0.79 - the version I'm using and I understand it's an "alpha" build and bugs are to be expected.**
**forge-1.12.2-14.23.3.2691 - the version installed**

   I recently picked up modded MC again and through a bunch of the latest and greatest mods together to play with and have just started getting Tinkers' stuff going and noticed a little visual bug with the crafting station that I thought I might as well report. 
   Instead of describing the problem I will just include a picture and leave at this: what's going on is the purple and black cube is supposed to be the crafting station rendering a chest like every other block. For instance It renders an iron furnace from Tech Reborn just fine.

![2018-05-17_00 58 25](https://user-images.githubusercontent.com/9005067/40157524-89ee4334-596d-11e8-8f11-2b7564d813ed.png)

**Comment by bonii-xx** [comment]
Not a bug per se. The crafting table displays the model of the item. Some items (like the vanilla chest) don't have a conventional model. Some mods hack their way around conventional conventional models or use ItemTESRs. This is such a case, where no model for the item exists.

**Comment by SniperHauss89** [comment]
Oh ok Thanks, I just thought I remembered it rendering chests in previous versions.

**Comment by bonii-xx** [comment]
Yes there is a fix for the chest, I think forge itself fixes it.
