### ISSUE TITLE
IllegalAccessError crash, minecraft 1.12.2

### ISSUE THREAD

**Issue by ESTPlayer** [SlimeKnights/TinkersConstruct#3492]
Game crashes in last step of loading, 
using latest Tconstruct: TConstruct-1.12.2-2.10.0.81
Forge: 2698

crash link: https://paste.ee/p/VOyGx

**Comment by bonii-xx** [comment]
Curious. I suspect this has to do with a trait from another mod. Does it load with just Tic and Mantle?

**Comment by karelmikie3** [comment]
from further testing I've ascertained that the underlying cause is probably the enderIO nightly build that both @ESTPlayer and I use. Using the latest enderIO build from their curseforge resolves the crash for me.

**Comment by HenryLoenwind** [comment]
oops. My bad, I forgot to put "public" in front of getPriority()...

**Comment by karelmikie3** [comment]
using the latest 'hourly' build from the Jenkins which according to its change log incorporates the aforementioned 'fix' it still crashes with an identical crash log

**Comment by bonii-xx** [comment]
@HenryLoenwind I figured it'd be something like that. I was surprised it didn't throw a compile error though.

**Comment by border999** [comment]
This is definitely throw a wrench in me playing modded Minecraft. I need my tinkers and Ender IO!

**Comment by KnightMiner** [comment]
Closing wince it was fixed in Ender IO
