### ISSUE TITLE
1.12.2 - Crash when placing supremium clever into the tool forge

### ISSUE THREAD

**Issue by Physaliidae** [SlimeKnights/TinkersConstruct#3493]
Made a supremium (Mystical Agriculture) cleaver and attempted to upgrade it using the tool forge however the game immediately crashes when I attempt to place the cleaver in said tool forge. Have attempted several times with the same result. Crash log says it is an error in updating screen events.

Crash log: [https://paste.ee/p/8aqLY](url)

Tinkers' Construct version: 1.12.2 - 2.9.1.65
Mantle version: 1.3.2.24
Mystical Agriculture version: 1.6.9

**Comment by TheQuadShot** [comment]
FastUtil is crashing, not TiCon. TiCon isn't on the stack.

**Comment by bonii-xx** [comment]
Indeed, this is not TiC related. Not even Toolforge related, it seems to be doing something with the regular crafting recipes. Contact FastUtil dev.
