### ISSUE TITLE
java.lang.NullPointerException: Updating screen events

### ISSUE THREAD

**Issue by DaKingCartoon** [SlimeKnights/TinkersConstruct#3494]
whenever i try to place my tool into the modification menu of the tool station, i get the following crashlog: https://pastebin.com/7KrTa9YR
something else to note is that several of the icons are missing from the radial slots of the modifier menu:
![unknown](https://user-images.githubusercontent.com/10874734/40282430-30228b3a-5c3d-11e8-8b3b-099c04e3f725.png)
i do have several ticon addons installed including the following:
Tinker's Tool Leveling
Tinkers' Complement
Tinker I/O
PlusTiC
Ore excavation Integration
Moar Tinkers
Tinker's JEI
TAIGA (Tinkers alloying addon) - had removed it for troubleshooting to no avail or changes
Tinkers' Defense -  1.4.2.8a from the developement discord
more plates
Tinkered Hegemony
Pewter

**Comment by KnightMiner** [comment]
This crash is caused by TAIGA, remove it for now as I am not sure if they released the fix yet.
