### ISSUE TITLE
NullPointerException issue on Initialization phase

### ISSUE THREAD

**Issue by Ebonhunter** [SlimeKnights/TinkersConstruct#3496]
Love the mod! That's part of the issue, I can't imagine playing without it.

Finally moving to 1.12.2 and Can't get past load in with TC installed. Nullpointerexception on slime model?

Here's the crash:
https://paste.ee/p/zg305 

Cheers!
Ebon

**Comment by KnightMiner** [comment]
Something is breaking your model loading, several mods are complianing their models cannot be found for their normal models, it just so happened to have found a crash in Tinkers after the warning. I would start by reducing your mod list to try and find the culprit.

**Comment by Ebonhunter** [comment]
Thanks for the quick reply! I only went as for as the crash report so I didn't notice; I'll update if I don't find a culprit.

Cheers!

**Comment by Ebonhunter** [comment]
OK, it was an issue with the version of Chisel I was using...was messing with several mods. Thanks for the pointer! All good now.
