### ISSUE TITLE
[1.12.2] Coloured Glass Crash

### ISSUE THREAD

**Issue by artdude543** [SlimeKnights/TinkersConstruct#3497]
Hello, developer of SevTech: Ages here!

We got a crash report logged to our tracker, from reading the report given it seems the issue is related to TiC. It's an odd case crash as it does not happen all the time. But occurs when your cycling the blocks in the world coloured glass specifically.

Linked Issue: https://github.com/DarkPacks/SevTech-Ages/issues/2521
Crash Report: https://pastebin.com/Ghdfd6AD

TiC Ver: 2.10.0.75
Mantle: 1.3.2.24

Any help would be much appreciated, thanks!

**Comment by KnightMiner** [comment]
This is a chisel bug, [they are calling `getActualState`](https://github.com/Chisel-Team/Chisel/blob/1.12/dev/src/main/java/team/chisel/common/item/ChiselController.java#L148) using our block at a location after they replace it with another block. As a result it produces unexpected behavior as it tried to check the properties. I can add a check for this, but technically we shouldn't have to as they broke a contract of `getActualState`.

**Comment by artdude543** [comment]
Okay I'll log an issue with them and link back to here so we're all connected ^_^

**Comment by KnightMiner** [comment]
In this case, the state could be used, but in most cases of getActualState it is checking the TE, which no longer exists if you remove the block. In general all blockstate methods expect the block to currently exist at the position, you yelled at us about this a couple years back.

**Comment by tterrag1098** [comment]
Fair enough, I'll just move the setBlockState to the end of the method.
