### ISSUE TITLE
Smeltery with 9x9 inside recognises only 9x8 capacity

### ISSUE THREAD

**Issue by AlHollandiyah** [SlimeKnights/TinkersConstruct#3498]
As the title suggests, when I build an 11x11 smeltery (with 9x9 air inside) which should be the maximum possible size according to materials and you, it only recognises an inside potential of 9x8. For a 9x9x1 air space it should have a capacity of 729 ingots (81 blocks) but instead it has a capacity of 648 ingots (72 blocks).

I am using:

- [ ] Minecraft 1.12.2
- [ ] Forge 14.23.3.2661
- [ ] Mantle 1.3.2.24
- [ ] TConstruct 2.9.1.65

However, I tried to find information on google about the actual max smeltery size, and I found [this](https://www.reddit.com/r/feedthebeast/comments/5m9jla/max_size_tic_smeltery/) topic about MC 1.10.2 where the person says:

_Just tested in 1.10.2, it is 9x9 internal. Just for grins I went from 1 to 255... 
Will store 165240 ingots (23794.56 kb) worth._

I calculated this, and with 9x9 and 255 high it SHOULD register 185895 ingots, and his value of 165240 once again comes down to an inside of 9x8, meaning this bug was already in 1.10.2.

I hope you can find out where this goes wrong, and I hope this can be fixed in an upcoming update! Thank you very much!

**Comment by bonii-xx** [comment]
That's because 1 block inside the smeltery is worth 8 ingots of space, not 9. 9x9x8 = 648, everything working as intended.

**Comment by AlHollandiyah** [comment]
That doesn't add up, isn't a block worth 9 ingots? It turns into 9 ingots when you decraft it, and you also if you need to craft a block you need 9 and not 8 ingots to make it. So how does it calculate 8 instead of 9 in the smeltery?

**Comment by laz2727** [comment]
Thermal expansion.

**Comment by KnightMiner** [comment]
boni means each block of internal smeltery space holds 8 ingots of fluid. Ingots fluid != ingots solid.

**Comment by TheQuadShot** [comment]
![2018-05-22_17 12 51](https://user-images.githubusercontent.com/11265900/40396783-b0fe8770-5de3-11e8-96c2-2e1f9570893f.png)

**Comment by AlHollandiyah** [comment]
@KnightMiner and @TheQuadShot thanks both, I saw that after reading the answers here and checking a number of extra smeltery sizes. The only part that remains unclear is what this has to do with thermal expansion.... But at least now I know that the 9x9 smeltery functions as it should, so that makes me happy! Thanks for all the answers!

**Comment by KnightMiner** [comment]
I think he meant the [physical thermal expansion](https://en.wikipedia.org/wiki/Thermal_expansion) process, not the mod.

**Comment by AlHollandiyah** [comment]
Ah, as in that 8 ingots worth of liquid metal takes up as much space as a 9 ingot worth block. I get it. Still, it's a bit beyond minecraft, as you still need 9 to fill a casting basin lol! But hey as long as it all works I'm perfectly fine with it!

**Comment by bonii-xx** [comment]
The main reason quite literally is so that a small (like 1x1) smeltery can fit exactly a small multiple of ores. 4 Ores, to be exact. And it's good that way.
