### ISSUE TITLE
[1.12.2] Beheading X arrow not dropping guaranteed mob heads

### ISSUE THREAD

**Issue by taj1994** [SlimeKnights/TinkersConstruct#3499]
Is this intended behaviour? It seems like I'm not getting mob heads any more often than I would be with just Looting III...

My arrow is made with a Gaia Spirit head, Endrod shaft, feather fletching, embossed with an end arrow head, and has the following modifiers:

- Endspeed
- Alien
- Payback
- Unbreakable
- Luck III
- Beheading X
- Enderference
- Embossment (End)
- Sharpestest
- Fins
- Smite III
- Soulbound

I'm using:

- Forge 14.23.3.2698
- Tinkers' Construct 1.12.2-2.10.0.81
- Mantle 1.12-1.3.2.24

And the following addons for TiC:

- Moar Tinkers 0.5.4
- PlusTiC 6.4.0.0
- Tinker I/O 1.12.2-release 2.6.1
- Tinkers Tool Leveling 1.12-1.0.4
- Tinkers' Addons 1.12.1-1.0.7
- Tinkers' Complement 1.12.2-0.2.3b

**Comment by MoxieGrrl** [comment]
Last I checked, Beheading didn't work on arrows and as far as I can remember never has.

**Comment by KnightMiner** [comment]
Have you tested with beheading X on another tool to ensure it's actually the arrows not working?

**Comment by taj1994** [comment]
Not in a couple versions, but I'll make a cleaver quickly and get back to you

**Comment by taj1994** [comment]
Beheading X is working perfectly on other tools. Tested with a cleaver and a broadsword

**Comment by bonii-xx** [comment]
Potentially a damage source discrepancy when it's a ranged damage source.
