### ISSUE TITLE
I used TC w/Thermal Expansion and Forestry and the game didn't run

### ISSUE THREAD

**Issue by MisterumCraft** [SlimeKnights/TinkersConstruct#3500]
Idk if it's because of my computer or it's actually a problem with this mod, but my Minecraft, while loading, crashed using Thermal Expasion (and the core mods) and Forestry with this mod, all in 1.12.2 Minecraft version and using Forge version 13.20.1.2386. I tried using the others mods without TC and everything gone fine, so the problem might be this mod. I think this is because the game had to load too many liquids, but I'm not sure. The point is that I want to know if this is something wrong with the mod or it's just the potato I use for computer.
The Crash Report:
[crash-2018-05-20_12.18.00-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2029020/crash-2018-05-20_12.18.00-client.txt)
My computer:
Procesator: Inter(R) Core(TM i3-3110M CPU @2.40GHz 2.40GHz
RAM: 4,00 GB
OS: Windows 10 Home Single Language x64
PS: Sorry for my bad English, that's not my natal language. Anyways, I hope it's helpfull

**Comment by TheQuadShot** [comment]
log file shows your crashing loading/rendering clouds

**Comment by KnightMiner** [comment]
You need to give Minecraft more ram. half a gigabyte is way too little, I'm surprised your game ran without Tinkers.
