### ISSUE TITLE
[1.12.2] Crash when placing tool in tool station for upgrading

### ISSUE THREAD

**Issue by 1gn153n515** [SlimeKnights/TinkersConstruct#3501]
I wanted to add a slime binding to my pickaxe but when I tried to place it into the grid the game crashed
[crash-2018-05-23_20.39.48-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2032421/crash-2018-05-23_20.39.48-client.txt)

**Comment by YaibaToKen** [comment]
Remove TAIGA, it's adding a broken modifier causing the game to crash

**Comment by KnightMiner** [comment]
Duplicate of #3372, TAIGA's fault.
