### ISSUE TITLE
Firing Explosion Events

### ISSUE THREAD

**Issue by mcenderdragon** [SlimeKnights/TinkersConstruct#3502]
This is more a question as I can not confirm it but from reading the code I think the ExplosionEFLN is not firing the ExplosionEvent.Detonate event or is not listening to the BlockPos changes.

Edit: Also who implemented the EFLN and do you know the original game? (I wondered because I recently played Clonk Rage)

**Comment by TheQuadShot** [comment]
> Edit: Also who implemented the EFLN and do you know the original game? (I wondered because I recently played Clonk Rage)
iirc  mDiyo is original creator of the mod, He's still around, and sometimes he streams and you can chat with him.(could be, Clonk's been around since 94, and don't forget "I am Grout")

**Comment by bonii-xx** [comment]
Fun fact: I'm the one who gave Clonk Rage its name, that should answer your question ;)

The EFLN fires the standard forge explosion events: https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/gadgets/entity/EntityThrowball.java#L77

If there's something missing then Forge probably added a new event I'm not aware of.

**Comment by KnightMiner** [comment]
The event you mentioned is called [here](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/gadgets/Exploder.java#L113), but does not include block positions. How are you trying to change them?

**Comment by 3TUSK** [comment]
On glance, I recall SpongePowered/SpongeForge#1209 - could that be related to this?

**Comment by mcenderdragon** [comment]
@3TUSK possible but as far as I know it happened with normal forge, signelplayer. 
@KnightMiner in the Event you can get the fftected Blocks in a list: https://github.com/MinecraftForge/MinecraftForge/blob/16bfd8cef1d12ee9ca0de1122addaf9916767ae9/src/main/java/net/minecraftforge/event/world/ExplosionEvent.java#L97
I have a mod with protected areas (player build) so I listen to the explosion event and remove the effected blocks, so you can destroy all blocks around the protected area but the area iteself is unharmed.

**Comment by bonii-xx** [comment]
The detonate event WAS fired.. just never for the blocks, just for the entities. It is now fired every tick without entities and the blocks getting "mined" in that tick.

> I am honored, that increadibly cool :D

We just had a brainstorming, and it happens mine was the one that ended up being the game subtitle ;P
