### ISSUE TITLE
[Request/Help] Crafting Station ID

### ISSUE THREAD

**Issue by MrFootman** [SlimeKnights/TinkersConstruct#3503]
Hi,

We're running a server on "All the mods 3", and the crafting station is causing massive lag.
We tried to add it on a banlist. Unfortunately, we banned all the tinker's table doing so.

Is there any way to add the crafting station only ? 

(we've used  tconstruct:tooltables   as ID)

Thank you in advance,

**Comment by bonii-xx** [comment]
If you have crafting lag, update TiC. If you have ingame word lag, then you have serious problems since the crafting station doesn't cause more lag than placing a block. It has the first metadata.
