### ISSUE TITLE
Game Crashs while trying to put a tool in the tool station ...

### ISSUE THREAD

**Issue by Y1m1ko** [SlimeKnights/TinkersConstruct#3506]
Everytime i try to put a tool in the tool staion the game crashes... 
i tryed if the problem is because my axe was brocken but it actually crashes every time.

**Comment by Y1m1ko** [comment]
Yes i have

**Comment by Y1m1ko** [comment]
Do u think i have 2 deinstall it ???

**Comment by Twilix01** [comment]
Yes, currently Taiga has an issue with a broken modifier that is causing this crash. I advise removing it until a new update with a fix is released.

**Comment by Y1m1ko** [comment]
okey yes i try it and thx :D

**Comment by KnightMiner** [comment]
Duplicate of #3372, TAIGA's fault.
