### ISSUE TITLE
EnderIO conduits mined with an Autosmelt + Luck III pickaxe produces an extra piece of charcoal

### ISSUE THREAD

**Issue by pdsaio** [SlimeKnights/TinkersConstruct#3507]
Minecraft 1.12.2, All The Mods 3 v5.9.5

When mining an enderIO conduit with the Autosmelt, Luck III pickaxe it produces a piece of Charcoal out of nowhere

cfg:
gameplay {
    # Fortune increases drops after harvesting a block with autosmelt
    B:AutosmeltFortuneInteraction=true

Reproduced bug in a test world:

![bmxxpqv](https://user-images.githubusercontent.com/39674131/40589112-2483d512-61e8-11e8-8bd7-4f4bd247a256.png)

the comments below in the image are from the EnderIO discord

edit: it happens to all the conduits in EnderIO v5.0.24

**Comment by Sanofus** [comment]
I can confirm that it not haooen if have Luck III only.

**Comment by KnightMiner** [comment]
Does this happen with just Tinkers and Ender IO?

**Comment by pdsaio** [comment]
[No :o](https://imgur.com/LUjZebx)

**Comment by KnightMiner** [comment]
If it's not happening with just the two, figure out which addition mod is required for it to happen. Normally this is easiest by cutting your list in half. If it still happens half it again, if not try the other half.

**Comment by KnightMiner** [comment]
Closing for lack of response, and since you could not reproduce with just Tinkers and Ender IO. If you can find a minimal mod list and reproduce this, it can be reopened.
