### ISSUE TITLE
(Suggestion/Question):Shields?

### ISSUE THREAD

**Issue by Wotzinator** [SlimeKnights/TinkersConstruct#3508]
so ive bin playing with tinkers construct for a while now but since the combat update something feels of and that's the missing shields and yes i know that the battle-sign kinda acts like a shield but its just not the same the model i nearly as any other normal item in game and its kinda cool but real shields would be better(maybe even some variants)

**Comment by KnightMiner** [comment]
Shields are not coming, there are not enough stats to vary. The battle sign acts like a vanilla shield already anyways.

If that is not enough, there is a mod called Tinkers defense with shields.

**Comment by Wotzinator** [comment]
one question why did you add a label to this when you already closed this

**Comment by KnightMiner** [comment]
The label states why it was closed, like the duplicate label or the won't fix label. In this case, it was closed because this is discussed on the FAQ

**Comment by bonii-xx** [comment]
Labels are for us to see what the ticket is about without opening it (you see them in the issue listing) as well as for people to know what's happening.
