### ISSUE TITLE
Crafting output from Crafting Station appears in inventory crafting Grid

### ISSUE THREAD

**Issue by Schnetzi8** [SlimeKnights/TinkersConstruct#3509]
Mantle-1.12-1.3.2.24
Tinkers Construct-1.12.2-2.10.0.81
Forge 14.23.42705
If you have a recipe placed in a Crafting Station, you exit its menu,open and close it again and then open up your Inventory the output of that recipe will be in the output box of the 2x2 crafting grid (just visible, its not possible to take it from there)
![unbenannt](https://user-images.githubusercontent.com/33729494/40589398-b6cb4802-61ec-11e8-98be-b60da1d5dc71.PNG)

**Comment by TheQuadShot** [comment]
I think you will find that the last recipe you viewed or made in/on the crafting table will always show in that view. So if you craft a boat, then open your inventory it will show a boat in the output window.

**Comment by Schnetzi8** [comment]
If I don't open up the menu a second time it doesn't happen. Just tested

**Comment by TheQuadShot** [comment]
I noticed this a few day'a ago, and I think it's related to https://github.com/SlimeKnights/TinkersConstruct/issues/3495 which is why I didn't file it. So to be more precise, after crafting anything on the crafting station it's output will show you your 2x2 output window the first time you open your inventory.

**Comment by Schnetzi8** [comment]
i totally agree that it could have something to do with #3495 but it just appears for me with the double entering of the station

**Comment by bonii-xx** [comment]
Can confirm both, they're definitively from the FastWorkbench integration. We'll see if they're the same, but I'll keep both open for now.

**Comment by bonii-xx** [comment]
It is indeed a completely separate issue. It always existed, since the first version of TiC2. It just never had an impact due to minecrafts ridiculous updating of recipes. 😆
