### ISSUE TITLE
FPS Lag (60 to 0 to 60 etc) with Optifine

### ISSUE THREAD

**Issue by Loxoz** [SlimeKnights/TinkersConstruct#3511]
There is a possible config in optifine options to like remove this FPS drops when tinker's construct is with optifine?
Like disabling fast render (already done for me)?

**Comment by KnightMiner** [comment]
We don't support Optifine. It breaks our rendering in multiple places that there is no reason should break, and there is no easy way to add compatibility. I would report this issue to them (and if you are reporting lag, you are going to want game versions and logs)
