### ISSUE TITLE
[request] Option to disable blood accumulating in Smeltery

### ISSUE THREAD

**Issue by stohun01** [SlimeKnights/TinkersConstruct#3512]
I've tried using [ModTweaker](https://github.com/jaredlll08/ModTweaker/issues/646) to no avail

**Comment by KnightMiner** [comment]
Reason?

**Comment by stohun01** [comment]
The pack I'm working on uses Better with Mods hardcore water features, so you have to use pumps to move water around. Blood can be removed from the Smeltery and placed in world and it also hydrates farmland.

**Comment by bonii-xx** [comment]
But so does every other non-lavaish modded fluid?

**Comment by stohun01** [comment]
Yes, however blood is the only one that doesn't seem to be able to be disabled. It's a simple pack where the Tinkers tools are disabled and the smeltery is end game and 1 ore = 1 ingot of fluid. The only non-vanilla fluids are molten iron and gold.

**Comment by bonii-xx** [comment]
To be honest, the easiest (and least complicated) way would probably be to prevent water material blocks being placed with a bucket. Blood is needed for a few things in the smeltery.

**Comment by stohun01** [comment]
I've asked on the [BWM repo](https://github.com/BetterWithMods/BetterWithMods/issues/1005) if they could disable placement of modded water based fluids.

**Comment by bonii-xx** [comment]
Any modder can also make a small mod that does it, it's about 3 lines of code (not counting the mod setup itself). But if you have a mod that does all the water stuff that it can only be transported by pipes, then it'd probably belong in there.

**Comment by KnightMiner** [comment]
BWM adds a feature where water buckets place a water flow instead of a source, so it flows out after a bit. It makes sense for them to allow the feature on other liquid types.

**Comment by KnightMiner** [comment]
Closing as no plans to change this on 1.12. 1.16 has the option to change the fluid or blacklist certain entities from melting entirelty
