### ISSUE TITLE
[Request] Off Center/Square up expanders on hammer

### ISSUE THREAD

**Issue by mrdeadlocked** [SlimeKnights/TinkersConstruct#3514]
It would be great to have hammers expanded cut (1 vert + 1 hort) to be based off the eye level height of the character and not the center of the + shaped cut. Right now if you are mining you have to look up to dig a straight tunnel. 

It would also be great if we could have them two upgrades work off of each other and create an actual square.

Current Max Hammer ([*] is where your cut lines up):
   [ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][*][ ][ ]
[ ][ ][ ][ ][ ]
   [ ][ ][ ]

Prefered Max Hammer ([*] is where your cut lines up):
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][*][ ][ ]
[ ][ ][ ][ ][ ]

This would allow you to look straight and mine. Currently, you can easily miss mining hazard with having your view tilted up to cut on a level plane.
![image](https://user-images.githubusercontent.com/461352/40732756-f9ffd9be-6401-11e8-979d-da710180ffc6.png)

**Comment by TheQuadShot** [comment]
Are you saying you want it to work like Actually Additions Drill with modifiers?

**Comment by mrdeadlocked** [comment]
Whichever expander you put on first add another block on each side of the 3x3. It would be nice if they stacked so that it went from 3x5 (or 5x3) to 5x5 so that mining could be square. At the very least adjusting the center of fully upgrade (and 5x3) so that its level with the miner's head would allow you to see where we are walking.

I havent used AA's Drills in a long time. I can't comment on wanting it to work like it or not.

**Comment by TherminatorX** [comment]
Honestly those corners have been something quite a few people complain about with expanders. I know the heads of the hammers are rounded in the texture, but this is Minecraft. Perhaps a change or config would be something to look into.

**Comment by bonii-xx** [comment]
The offset sounds like a usability thing that makes sense. I'll think about the corners.

**Comment by KnightMiner** [comment]
This is on the list to consider for 1.16 modifiers. Not happening in 1.12
