### ISSUE TITLE
Compatibility with Conquest Reforged

### ISSUE THREAD

**Issue by Syphenion** [SlimeKnights/TinkersConstruct#3516]
Tinkers Construct Hammers and Pickaxes do not give block loot on stone blocks "cobblestone" or "stone".

minecraft:stone; // (stone variants ->) minecraft:dolomite; minecraft:granite; minecraft:diorite

**Comment by Syphenion** [comment]
Reference: https://github.com/Conquest-Reforged/ConquestReforged/issues/100

**Comment by KnightMiner** [comment]
This is on ConquestReforged's side, as they require tools to extend ItemTool and that is not something we can do. They can easily call the vanilla function `getHarvestLevel` to get the harvest level, like most other mods use.

**Comment by KnightMiner** [comment]
Closed on ConquestReforged's side, so I am assuming fixed.
