### ISSUE TITLE
1.12 Game Crash and tool loss

### ISSUE THREAD

**Issue by Turbotowns** [SlimeKnights/TinkersConstruct#3517]
In most(if not all) 1.12 mod packs, whenever I try to put a tool in the station to repair or modify it, the game crashes and I lose the tool completely!

It and gives this:
Error: java.lang.NullPointerException: Updating screen events

I don't know what to do.

**Comment by TheQuadShot** [comment]
First you need to supply them with the version numbers of TiC and Mantle, and Forge. Then post or upload your crash log. Also you should search the database to see if your crash is already listed as an issue. I believe it is, I'm just not sure which it would be without further information.

**Comment by Turbotowns** [comment]
Yeah, I know, though I think I might have found the problem. I removed a bunch of add-ons and it works, so now I'll be re-adding them one by one and testing the table til I find the offending mod.

**Comment by Turbotowns** [comment]
It was taiga, and I'm not the only one getting it, so it's not the fault of my crappy computer. Thanks for responding, but it's not a problem with the base mod. Peace!
