### ISSUE TITLE
Tinker's crashing [1.12.2]

### ISSUE THREAD

**Issue by DarkPoke** [SlimeKnights/TinkersConstruct#3518]
When I try to upgrade a tinker's tool, the game crashed. Specifically when I drag that tool to the middle of the tool station

Forge version: 14.23.4.2705

Crashlog: https://pastebin.com/Sjn2btcT

Tinkers version: 2.10.0.81

I don't know if it can be reproduced for others with the same conditions I have.

Edit: If need be, I can try to provide a gif of what is happening?

**Comment by YaibaToKen** [comment]
Remove TAIGA as it has a known bug.. An incorrectly implemented modifier is added by that mod and until the TAIGA devs upload a fix, there's nothing to be done. Also a duplicate of several other issues
