### ISSUE TITLE
Tinker Tool with Soulbound

### ISSUE THREAD

**Issue by Corail31** [SlimeKnights/TinkersConstruct#3520]
Hi, i don't really play, so i'll try to explain the bug, as i often receive messages about this, and they don't understand why the tinker completely disappears.
https://minecraft.curseforge.com/projects/corail-tombstone?comment=107
So, it's only related with the tinker tool (soulbound with a nether star) and with this line : 
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/modifiers/ModSoulbound.java#L74
The code is functional, except if another mod copy the original on the player after the tinker clone event (btw it's in high priority, and default is normal)
In this case, the tinker tool will be overwrite by an empty stack...
So, i think i would be better to keep the stack in the original too.

Also this line should keeps the same position in the main inventory, or it could break others soulbound code : 
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/modifiers/ModSoulbound.java#L73

**Comment by bonii-xx** [comment]
Sounds like the other mod is doing something wrong to me. Hard to tell without details. Also yes, the events are high priority exactly for that reason - so other mods can't fuck it up easily.

**Comment by Corail31** [comment]
to be on top of the event provoks the bug instead, it should be on lowest
For me, both are wrong, one mod because it copies completely the player.
And tinker because, he moves the slots of its existing items (so another mod like cofh, enderio, tombstone, twilight forest, ars magicka... could replace the tinker soulbound, or tinker could replaces the item of the other mod by doing this)
`evt.getEntityPlayer().inventory.addItemStackToInventory(stack);
evt.getOriginal().inventory.mainInventory.set(i, ItemStack.EMPTY);`
if you use set empty with the exact slot, you can do exactly the same in the player... with the exact slot.
because the method used by tinker, place the item in another slots

**Comment by bonii-xx** [comment]
Ah, you mean using the same slot in the dead player as it was before. That sounds doable. Most of that code is from EnderIO.

**Comment by KingLemming** [comment]
Frankly, this shouldn't be necessary. CoFH's Soulbound works the same way and offhand this only causes issues where a mod is bugged. Adding to inventory in general is the most correct way, because of the fact that other mods may also add to inventory in a general way and "block" the old slot.

**Comment by Corail31** [comment]
at least, they will be an issue on tinker about this, because this bug really happens (and for me, the lost of items is inacceptable), i think a clone is the same player, so there's no reason to change where items were.

**Comment by KingLemming** [comment]
That's the thing - any mod doing a full clone + respawn needs to be set to priority HIGHEST and should mark the event as cancelled to prevent further processing.

This is how the event system works. There is no reason for every mod to do things a certain specific way to accommodate fragile code in another mod.

**Comment by bonii-xx** [comment]
Thanks for the input KL. Yeah I know my mod handles things in a way that reduced potential mod interactions to a minimum. Considering it works fine with everything else, I'm willing to blame the other mod.
