### ISSUE TITLE
Items not showing on searchs

### ISSUE THREAD

**Issue by Loki940** [SlimeKnights/TinkersConstruct#3521]
Heyy, for some reasons, the items from Tinker's Construct doesn't show at all when I'm searching them in JEI. I though it might be related to JEI but after looking into creative mod, they doesn't show either.
I double checked, the items exists in-game, JEI crafts and infos also work, the only problem is the items not showing in JEI list and creative search list.

I have no idea if it's a mod, an option or a new feature but that's quite bothering

![2018-06-02_03 49 59](https://user-images.githubusercontent.com/30162098/40869333-8b964aac-6619-11e8-815e-2e0d04f9b20a.png)
![2018-06-02_03 51 39](https://user-images.githubusercontent.com/30162098/40869334-8bb8c794-6619-11e8-9946-22cb90a7b9fb.png)
![2018-06-02_03 59 02](https://user-images.githubusercontent.com/30162098/40869335-8bd3ef10-6619-11e8-9eb3-09d73f61d5e3.png)
![2018-06-02_03 59 54](https://user-images.githubusercontent.com/30162098/40869336-8beeb6ec-6619-11e8-973c-1afe011209f8.png)

 ?

**Comment by KnightMiner** [comment]
I've never seen this before, but it is almost certainly a mod conflict. Try to reproduce this with as few mods as possible so the conflict can be found.

**Comment by Loki940** [comment]
Well, using Curse, I tried disabling, then removing as much mod as I could, ending up deleting everything but JEI and Tinkers. The problem still persist for JEI but seems to be fixed for the creative inventory (I didn't really think about checking which mod was confliction there sorry, I must admit the JEI side was bothering me more than the creative side, here is the actual final mod list:
Just Enough Items
Just Enough Resources
Mantle
Tinkers Construct

And yep, still not appearing in JEI
I don't know what else I could test

**Comment by bonii-xx** [comment]
You have TiCblacklisted in your JEI. Or something along those lines. Deactivate item hiding mode in JEI.
