### ISSUE TITLE
Crash on Repair/Modify

### ISSUE THREAD

**Issue by Rayzilla68** [SlimeKnights/TinkersConstruct#3522]
When putting an unbroken tool or weapon in the tool station or tool forge, the game freezes and crashes. 

Thanks!

Crash report attached.
[crash-2018-05-30_23.21.42-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2065080/crash-2018-05-30_23.21.42-client.txt)

**Comment by Twilix01** [comment]
Uninstall TAIGA until it lets out a new release, it is creating a broken modifier that causing this crash.
