### ISSUE TITLE
Feature Request: Holding Shift over tool pattern or cast shows available materials

### ISSUE THREAD

**Issue by darchitect7** [SlimeKnights/TinkersConstruct#3523]
Tinker's Tweaks added this functionality to NEI, and it was so useful for quickly assessing what was available pre-smeltery. Any chance of adding this to the mod? 

And thanks for everyone's hard work! We all appreciate it!

**Comment by KnightMiner** [comment]
That was important in Iguana Tinker Tweaks as it blacklisted many materials, it was handled by assuming all casts work with everything then filtering out the blacklist. I am not sure this would be useful in the main mod, it is the same list for all casts anyways.

**Comment by bonii-xx** [comment]
You can use any pattern with anything (except arrow shafts, which are the only exceptions). There's no need for it, since there is no limitation. Which also is why 1.7.10 TiC didn't have it, but ITT added it (since it also added restrictions).

**Comment by TherminatorX** [comment]
Boni, I don't think that's what the user was asking about. It's about what materials you can use the regular wooden patterns with vs needing to be smelted and casted.

**Comment by KnightMiner** [comment]
Its still a constant list, so I don't think putting it on every pattern makes sense. This might be a spot for more JEI support at most, as tooltips are an awkward way to convey recipes.

**Comment by bonii-xx** [comment]
@TherminatorX Oh, well that makes more sense. I still wouldn't put it onto the pattern though, since it's the same for every pattern. Book or some tables GUI, but they're already pretty overloaded.
