### ISSUE TITLE
trying to connect channels while having channels in your hand crashes the client.

### ISSUE THREAD

**Issue by daAresinger** [SlimeKnights/TinkersConstruct#3524]
I tried to connect to channels while having the channel item in my hand. I suppose the game didn't know whether to try and place a new channel or try to connect the existing ones.

**Comment by bonii-xx** [comment]
Crashlog

**Comment by daAresinger** [comment]
umm..... for some reason there isn't one.
Sorry, I am also not able to recreate the crash anymore.

**Comment by bonii-xx** [comment]
Report new issue with crashlog if it happens again.
