### ISSUE TITLE
Clear Glass Evaporates From Smeltery?

### ISSUE THREAD

**Issue by TheLargeCactus** [SlimeKnights/TinkersConstruct#3529]
Using TiC version 2.10.0.81 on MC 1.12.2 and forge 14.23.4.2705. Clear glass seems to 'evaporate' or disappear from the smeltery multiblock. Is this intended or some sort of bug?

**Comment by KnightMiner** [comment]
Please explain further. Is the fluid just draining away? Is it invisible? Soundslike you are either m draining it or it's being used in an alloy

**Comment by TheLargeCactus** [comment]
I don't believe it is alloying, and the only drains hooked up to the smeltery are connected to tab;es/basins but they show no sign of containing the glass. The liquid glass does seem to drain from the smeltery though by what method I do not know.

**Comment by TheLargeCactus** [comment]
It happens no matter the order, happens in a new smeltery and it happens even if the glass is not on the bottom. I apologize for not mentioning before but I'm running TiC on ATM3.

**Comment by TheLargeCactus** [comment]
That's the peculiar thing, there is no recipe which seems to alloy by
consuming glass, at least not in JEI. I'll try digging through
configs/scripts for the answer. I don't especially think this is a TiC bug
but I wanted to ask to see whether it might be intended.

**Comment by bonii-xx** [comment]
It's definitively not intended. And so far nobody has had that behaviour either, and there have been no chnages in that region (although that doesn't guarantee that something might break, just MC things ;)).
Most likely some other mods/crafttweaker issue

**Comment by TheLargeCactus** [comment]
It appears that it was... For some reason, the pack maker created recipes such that certain alloys would simply destroy any liquid glass added to the smeltery, and removing those seemed to fix it.
