### ISSUE TITLE
Broken Unbreakeble Tool (shuriken)

### ISSUE THREAD

**Issue by KuBruC** [SlimeKnights/TinkersConstruct#3530]
Game version : 1.12.2 -> FTB Continuum
Forge version : 14.23.3.2702 
TC version : 1.12.2-2.10.0.81

Maybe Issue relevant Mods : Tinkers Tool Leveling
                                  Extra Utilities 2
                                  (Actually Aditions)

Issue discription : I've made a shuriken, with one blade Magical Wood, one blade Paper and two blades   
                           Manyllum, then i made it unbreakeble with five reinforcements and it worked very well 
                           until I changed the Manyllum baldes against to Blades out of Demonic metal. After  a 
                           few uses it is gone Broken, (probably in caused by the "Magical Brittle" effect of Magical-
                           Wood) But I'm not able to repair it like normal (No Material works) evev the "Item-
                           repairer" from Actually additins can't help me.
                            If i hold my Mouse over it in Invertory it displays "Empty" bot in tool Station It says 
                           "56/56" (full durability)

Screen shot :    
                       
![screenshot 1](https://user-images.githubusercontent.com/29373819/41039571-1e979864-699a-11e8-99f9-3a711da70a99.png)

Notice : 
             - If it matters, I upgraded it with one diamond, some lapis and some quarz
             - If you are, you probaly noticed I'm not a nativ english speaker, if I made an not undersandeble
             mistake please Aks

**Comment by anisatsr** [comment]
magical wood trait had a chance for. unbreakable tool to instantly break

**Comment by KuBruC** [comment]
I’m  sorry if that was the main Problem, I played very often with your Mod, and in this case i always was able to reapir them exept today, I‘m also  wondering why the tool statin tells me it has full durability. But thank you for your answer

Gesendet: Mittwoch, 6. Juni 2018 15:44
An: SlimeKnights/TinkersConstruct
Cc: KuBruC; Author
Betreff: Re: [SlimeKnights/TinkersConstruct] Broken Unbreakeble Tool(shuriken) (#3530)

magical wood trait had a chance for. unbreakable tool to instantly break

**Comment by KnightMiner** [comment]
It has full durability because Extra Utilities does not break the tool in the right way with their Magical Wood, they just set it broken without actually removing the durability. I patched it to be repairable in the tool station still awhile back, and it sounds like you ended up being able to repair it eventually, so I will close this issue. If you have issues repairing it reply here and we can look into the issue again.
