### ISSUE TITLE
better mom's spaghetti [Suggestion] 

### ISSUE THREAD

**Issue by ilhamsitok** [SlimeKnights/TinkersConstruct#3531]
found hardened wheat stick yesterday and decided to make mom's spaghetti. its great but hunger and Saturation this thing give is too small. maybe add a config for mom's spaghetti, or add modifier to enhance this. Just asking

**Comment by KnightMiner** [comment]
There is multiple modifiers to enhance it. You just have plain noodles, you need meat and sause.

**Comment by ilhamsitok** [comment]
i already did. but with 2 chunk of hunger and Saturation it's just not enough. but i guess thats fine. one more thing, can i repair this?

**Comment by KnightMiner** [comment]
Yes, it can be repaired using one of Minecraft's food items. If you want to know which one I can tell you, but it might be more fun to discover it on your own.

And yeah, its small, but also remember you get 100 uses out of the 1 food item, which is a lot more than a stack of food, especially considering its just 1 item.

**Comment by ilhamsitok** [comment]
nice, i'll figure it out by my self, good to know. i guess this is already become the best food in modded minecraft

**Comment by ilhamsitok** [comment]
what kind of food btw? i try using all food from minecraft but it wont work

**Comment by KnightMiner** [comment]
It might not be something you can eat directly, so produce used to craft foods is included when I say food. Think about what spaghetti is made from

**Comment by ilhamsitok** [comment]
oh, found it. just being stupid, i only put 1 pieces instead of 5. thank you. but what a about the fish problem?

**Comment by KnightMiner** [comment]
Does the same thing happen with redstone, or lapis, or another normal modifier item? (fish are an arrow modifier) Does it happen with non-modifiers items as well? It sounds like it ran out of modifiers and displayed that message before noticing the modifier could not be applied. In any case, it should not matter too much as you cannot apply it anyways.
