### ISSUE TITLE
(1.12.2) Poof! crashes

### ISSUE THREAD

**Issue by Migmag789** [SlimeKnights/TinkersConstruct#3534]
Hey ! I was launching your mod, and poof! a little crash.
[crash-2018-06-12_18.09.44-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2094825/crash-2018-06-12_18.09.44-client.txt)
That will be very nice if you was able to fix the problem :D 
Good job !

**Comment by KnightMiner** [comment]
Duplicate of #3533, update Construct's Armory.

**Comment by Migmag789** [comment]
Ok, thank you :)
