### ISSUE TITLE
[1.12.2][Issue]: Chest inventory flaps using TC workbench with connected vanilla doublechest

### ISSUE THREAD

**Issue by PearlCanopus** [SlimeKnights/TinkersConstruct#3537]
TC: TConstruct-1.12.2-2.10.1.84.jar
MC: 1.12.2

I know, it could be caused by any other mod in use. But I have to start anywhere... :)
It's no critical problem and it causes no crash. It's annoying only...
I have several TC workbenches with double vanilla chest on their side.
When I open the workbench to craft, the items in chest inventory disappear and come back independent of mouse or any else activities I know about. When it's disappeared, I have no access to the items in inventory anymore. When I craft fast and get an item out of the chest inventory it will still be there after reappearing. So I have a item dupe from time to time. But I have no losses.

When I place a vanilla furnace beside a workbench with connected chest, I only have access to the furnaces inventory and see no chest inventory anymore.

With a single IE chest beside the TC workbench I have no inventory flapping issue.
I've not checked it with a single vanilla chest yet.

**Comment by bonii-xx** [comment]
Try reproducing with only TiC. The Workbench only shows one inventory, so placing multiple around it will always only show the first one found.

**Comment by PearlCanopus** [comment]
In an empty world with only Forge and TC + Mantle installed it works well. Please close and sorry for annoying. Will checke the compatibility- and inventory mods next.
