### ISSUE TITLE
Entry has no source mod or way to be obtained, but shows still on JEI

### ISSUE THREAD

**Issue by Ashendale** [SlimeKnights/TinkersConstruct#3538]
I am testing adding and removing mods from my pack. The one I am almost 100% sure caused this was OpenBlocks - when it adds the tanks to JEI it doesn't care if the contents exist in the world, or can be obtained. That musft've triggered some TiC function and now I have entries for molten zinc and its bucket.

Where can I edit/remove this? Or is it intended?

Edit: forgot to mention it was on TiC version 2.10.1.84 for 1.12.2

**Comment by KnightMiner** [comment]
Tinkers always registers all it's fluids, even of unused, since the time we need to register them by is sooner than the time we know we will use them. You can just ignore the extra fluids, JEI should let you hide them.

**Comment by Ashendale** [comment]
Using modtweaker to hide JEI entries?
