### ISSUE TITLE
Crashing when crafting in 1.12.2 error: java.lang.IndexOutOfBoundsException: Index: 5, Size: 5

### ISSUE THREAD

**Issue by KamFitzy1996** [SlimeKnights/TinkersConstruct#3540]
I've encountered this crash with both vanilla crafting table and Tinkers Construct Crafting table and im unsure what causing it however openeye mod is telling me that mantle and Tconstuct are behind the issue. 
the crash log is located here at https://pastebin.com/bYDwdSnw.
The error im getting is java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
any help or fix would be fantastic thank you

**Comment by KnightMiner** [comment]
According to the storage, you have a broken recipe. It's difficult to tell what mod tough, it does say `assets.recipehandler` is involved, but they did not name their package well.

Try reducing your mod list until you find the causs, you will probably find removing Tinkers still causes the issue to happen of it happens with the vanilla table.

**Comment by KnightMiner** [comment]
Closing for lack of response, and since you stated specifically it is happening with the vanilla crafting table. It is caused by whatever mod `assets.recipehandler` references.
