### ISSUE TITLE
[SUGGESTION] Rename smeltery drain and faucet to seared drain and seared faucet

### ISSUE THREAD

**Issue by monodemono** [SlimeKnights/TinkersConstruct#3541]
The smeltery drain can also be used in a Tinker Tank, which itself isn't actually a smeltery, so it's a little misleading to specifically say it's a "smeltery drain" and aside from the controller, it, and the faucet are the only things that don't appear when you search seared in NEI/JEI. Also by renaming these to "seared" they'll be more uniform with the other blocks in the mod.

Also the tool tip on the faucet should be changed from:

> Drains liquids from Smelteries and other things

to

> Drains liquids from the Smeltery and other things

Doing this will 1) Make it more uniform with the other various seared block tool tips in the mod, and 2) Make it appear when searching "Smeltery" in NEI/JEI like everything else does.

Also, on top of all of that, they're made out of seared stone, so "seared drain" and "seared faucet" do make a lot of sense.

**Comment by bonii-xx** [comment]
The reason why they're all called something something smeltery is so all smeltery components show up when you enter "smeltery" in JEI. I think some change in JEI broke that some time ago. Not sure if I want them changed yet.

**Comment by monodemono** [comment]
They show up when you enter "Smeltery" in JEI anyways, because they all say "Smeltery" in their tooltips, which is exactly the problem with the faucet, because it says "Smelteries" instead. As long as the tool tips say "Smeltery" but the name is changed to "Seared" then everything will properly show up regardless of if you search for "Smeltery" or "Seared"

**Comment by KnightMiner** [comment]
Implemented in 2fd5363

**Comment by monodemono** [comment]
Thank you! <3
