### ISSUE TITLE
Crash with Croparia

### ISSUE THREAD

**Issue by DaggerTM** [SlimeKnights/TinkersConstruct#3543]
Tinkers seems to crash with the latest version of Croparia

**Minecraft 1.12.2: Forge 14.23.4.2708**
**Tinker's 2.10.1.87**
**Croparia 1.18**

> ---- Minecraft Crash Report ----
> // Why did you do that?
> 
> Time: 6/16/18 7:13 PM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.client.util.SearchTree.func_194039_a(SourceFile:48)
> 	at net.minecraft.client.util.SearchTree$$Lambda$138/1013435877.accept(Unknown Source)
> 	at java.util.ArrayList.forEach(ArrayList.java:1249)
> 	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:48)
> 	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
> 	at net.minecraft.client.Minecraft$$Lambda$152/1156040280.accept(Unknown Source)
> 	at java.util.ArrayList.forEach(ArrayList.java:1249)
> 	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:603)
> 	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1079)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:772)
> 	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:562)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
> 	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
> 	at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
> 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
> 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1068035696 bytes (1018 MB) / 1680343040 bytes (1602 MB) up to 6203899904 bytes (5916 MB)
> 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6656m -Xms256m -XX:PermSize=256m
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.4.2708 8 mods loaded, 8 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State   | ID         | Version          | Source                          | Signature                                |
> 	|:------- |:---------- |:---------------- |:------------------------------- |:---------------------------------------- |
> 	| UCHIJA  | minecraft  | 1.12.2           | minecraft.jar                   | None                                     |
> 	| UCHIJA  | mcp        | 9.42             | minecraft.jar                   | None                                     |
> 	| UCHIJA  | FML        | 8.0.99.99        | forge-1.12.2-14.23.4.2708.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAE | forge      | 14.23.4.2708     | forge-1.12.2-14.23.4.2708.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJA  | croparia   | 1.18             | Croparia-1.18.jar               | None                                     |
> 	| UCHIJA  | guideapi   | 1.12-2.1.5-60    | Guide-API-1.12-2.1.5-60.jar     | None                                     |
> 	| UCHIJA  | mantle     | 1.12-1.3.2.24    | Mantle-1.12-1.3.2.24.jar        | None                                     |
> 	| UCHIJA  | tconstruct | 1.12.2-2.10.1.87 | TConstruct-1.12.2-2.10.1.87.jar | None                                     |
> 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics'
> 	Pulsar/tconstruct loaded Pulses: 
> 		- TinkerCommons (Enabled/Forced)
> 		- TinkerWorld (Enabled/Not Forced)
> 		- TinkerTools (Enabled/Not Forced)
> 		- TinkerHarvestTools (Enabled/Forced)
> 		- TinkerMeleeWeapons (Enabled/Forced)
> 		- TinkerRangedWeapons (Enabled/Forced)
> 		- TinkerModifiers (Enabled/Forced)
> 		- TinkerSmeltery (Enabled/Not Forced)
> 		- TinkerGadgets (Enabled/Not Forced)
> 		- TinkerOredict (Enabled/Forced)
> 		- TinkerIntegration (Enabled/Forced)
> 		- TinkerFluids (Enabled/Forced)
> 		- TinkerMaterials (Enabled/Forced)
> 		- TinkerModelRegister (Enabled/Forced)

**Comment by KnightMiner** [comment]
I don't see anything in the crash pointing to Tinkers Construct. Does this happen without it? Have you reported it to the Croparia author?

**Comment by DaggerTM** [comment]
This crash doesn’t happen when Tinkers in not present. And I have reported it to Croparia but with numerous mods and not these 4 but these four seem to repeat all the times

**Comment by KnightMiner** [comment]
Is it specifically Tinkers, or Mantle? Likewise, does it happen without Croparia and just GuideAPI?

**Comment by DaggerTM** [comment]
It does happen with tinkers, but if tinkers is not installed but mantle is the crash doesn't happen. I will try without croparia, and see if its GuideAPI. 

Edit: Using the tinkers version listed, as well as the latest Mantle, and the latest of GuideAPI, the crash doesn't happen

**Comment by KnightMiner** [comment]
Okay, try this in Forge build 1.12.2-14.23.4.2704 and see if it still happens

**Comment by DaggerTM** [comment]
Nope crashed doesn't happen...

**Comment by KnightMiner** [comment]
It not happening in 2704 confirmed my suspicion. This is caused by MinecraftForge/MinecraftForge#4942 changing recipes to reload on the client. Apparently some recipes do not like that, but as you can see in the crash report its impossible to tell which ones or why. MinecraftForge/MinecraftForge#4957 will give us the ability to debug this properly and should hopefully prevent the crash. Unfortunately it means you have to use 2704 for now (you might be able to get by rolling back those other mods to an older version, 2704 is so new that the fact they require the latest so soon is odd)

**Comment by DaggerTM** [comment]
Thank you KnightMiner

**Comment by DaggerTM** [comment]
yes I will

**Comment by DaggerTM** [comment]
Log report: https://hastebin.com/ayeropucar.sql
Crash report: https://hastebin.com/ditesenodo.sql

**Comment by KnightMiner** [comment]
Well, that still is not any more information, hmm... I can say line 37 of the log is concerning, apparently Croparia is misdeclaring their dependency with GuideAPI, which has a slim chance of being related. Make sure you have the latest version of that mod.

Anyways, its still difficult to tell exactly what is causing it, I'll look into this issue a bit more when I get a chance, as it probably just needs another case for a warning in Forge.

**Comment by Dalarion** [comment]
Hi DaggerTM, I'm the mod author of Croparia. This mod has some huge bugs, a Croparia v2 need to be create by the way, and I have recently solved a bug : croparia was not compatible with the newest versions of forge like the 14.23.4.2705 (I was modding in forge 14.23.0.2491, maybe this was a problem...), I recommand you to test with Croparia 1.18.1.

**Comment by KnightMiner** [comment]
@DaggerTM have you tested with the latest Croparia yet?

**Comment by DaggerTM** [comment]
Yes it is working
