### ISSUE TITLE
Longbow Resetting

### ISSUE THREAD

**Issue by NillerMedDild** [SlimeKnights/TinkersConstruct#3544]
After shooting once, a Longbow made of any materials will reset into `Longbow`. It happens with both vanilla Arrows and TiC ones.

- TConstruct-1.12.2-2.10.1.87
- Forge 1.12.2-14.23.4.2705
Possibly relevant:
- plustic-6.5.2.0

**Comment by bonii-xx** [comment]
"will reset into longbow"...?

**Comment by NillerMedDild** [comment]
Before shooting:
![billede](https://user-images.githubusercontent.com/21295394/41507443-cf843182-7232-11e8-9fef-0d529271f3c3.png)
After shooting:
![billede](https://user-images.githubusercontent.com/21295394/41507444-db78ecf8-7232-11e8-87e1-bbee6ebf5644.png)

**Comment by NillerMedDild** [comment]
latest.log in case it'll help, I didn't spot anything relevant though
https://gist.github.com/NillerMedDild/1751548c4ba451ae8c4c0babacee58c1

**Comment by bonii-xx** [comment]
Try reproducing with only TiC and Matnle

**Comment by NillerMedDild** [comment]
I have not been able to reproduce it with only TiC & Mantle, nor TiC, Mantle, Tinkers' Tool Leveling and Cyclic. I'll keep looking for the conflict.

**Comment by NillerMedDild** [comment]
Yup, flier268 is right. It is the latest version of Cyclic.
