### ISSUE TITLE
Crash by put t-construct in the mods folder

### ISSUE THREAD

**Issue by kampfhase7** [SlimeKnights/TinkersConstruct#3545]
hay guys. 
When i put tinkers construct in my mods folder, the server will crash and ends with the following error: (Attached File)
[crash-2018-06-17_16.01.46-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2109176/crash-2018-06-17_16.01.46-server.txt)

**Comment by Twilix01** [comment]
What version of minecraft are you running? And what version of Tinkers Construct are you using?

**Comment by bonii-xx** [comment]
Your, uh, java seems broken. Looks like you're missing a part of the standard java stuff. Looks like that part is related to the XServer, which your server doesn't have (this is normal). Either you have some weird java distribution, or you're literally the first person to have a server without X (unlikely). It's weird that part of the mod is loaded on the server though.

**Comment by KnightMiner** [comment]
Closing for lack of response, somehow as boni said your Java is broken but somehow part of the mod loaded.
