### ISSUE TITLE
1.12.2-Shuriken Breaks after single use

### ISSUE THREAD

**Issue by Endmateria** [SlimeKnights/TinkersConstruct#3547]
Installed the newest TCON "TConstruct-1.12.2-2.10.1.87.jar" and now my unbreakable shuriken breaks after a single use.  I also tried crafting a fresh manyullyn shuriken without adding any modifiers, also broke after a single throw.  Downgraded to "TConstruct-1.12.2-2.10.1.84.jar" and the problem went away.

MC Version 1.12.2
Forge Version 1.12.2-14.23.4.2708 (newest)
TCON Version 1.12.2-2.10.1.87

**Comment by KnightMiner** [comment]
Does this happen with non-unbreakable shurikens? Does your specific unbreakable shuriken have a durability of 1 before making it unbreakable? Could just be unbreakable is not apply for some reason.

**Comment by Endmateria** [comment]
Yes, as I said I tried making a fresh manyullyn shuriken (non-unbreakable) that was not brought over from a previous version of TCON for testing purposes.  Added no modifiers, used all manyullyn knife blades to craft it... still broke in one throw.  As for my specific unbreakable shuriken, it got destroyed so I can't say what the durability was before losing it... though I did make two more unbreakable shurikens, both also immediately broke i.e. turned white/ran out of ammo.  So 4 different shurikens broke after a single throw.  I didn't hard core trouble shoot this though, didn't bother since downgrading immediately solved the problem, though I am using 2 mods that could possibly influence this behavior (Tinkers Tool Leveling and PlusTIC).  I can do more legwork if you like...

**Comment by KnightMiner** [comment]
Does this happen with just Tinkers Construct and Mantle installed?

**Comment by KirinFuji** [comment]
Please do not close this. I am having the exact same issue, and its all ranged tinkers weapons.
I tried removing all tinkers addons and the issue kept happening. I actually had the issue happeing on TConstruct-1.12.2-2.10.1.84.jar and i tried to upgrade to **TConstruct-1.12.2-2.10.1.87.jar** and the issue persisted. 

I have not yet tested with just mantle and Tcon.

**Comment by Endmateria** [comment]
I'm trying to isolate the conflicting mod that's causing it right now.  It doesn't have in single player with just the new TCON and Mantle.

**Comment by KirinFuji** [comment]
I do still have Ender IO and other Compat mods enabled Im guessing its one of them.

**Comment by Endmateria** [comment]
It's a mod that's updated in the last 2-4 days i think

**Comment by Endmateria** [comment]
Can't reproduce it in single player.

**Comment by PlasticPhoenix** [comment]
I am not having this issue, but I also have all the mods listed above, except for the Tinker's Tool Levelling.
I am running:
Forge 2707, Tcon 2.101.87,  Constructs Armory 1.0.0, Mantle 1.3.2.24, PlusTIC 6.5.2.0, EnderIO 5.0.26

I just made a new unbreakable shuriken tonight right after the update. It is working as expected. Can you try a new world without Tcon Levelling?

**Comment by Endmateria** [comment]
I don't know, I spent well over an hour pulling off mods trying to troubleshoot/isolate this in both SP and MP.  Eventually went back to square one with all the mods that originally triggered the conflict... and could not reproduce it.  Blah...

**Comment by KirinFuji** [comment]
So weird, I am defiantly Still having the issue. Do you know if it is world specific?

I tried removing tinker tool leveling my issue persists.

**Comment by Endmateria** [comment]
Try deleting the configs for all the TCON related mods... just for shits and giggles.  Since I can't reproduce it, I can't troubleshoot it anymore.

**Comment by jinkhya** [comment]
I believe it's Cyclic that is the issue : 
https://github.com/PrinceOfAmber/Cyclic/issues/853

**Comment by jinkhya** [comment]
Cyclic-1.12.2-1.15.12.jar fixes it according to the changelog

**Comment by KnightMiner** [comment]
Closing as a fixed Cyclic issue. To anyone in the future with this issue, update Cyclic.

**Comment by KirinFuji** [comment]
Ahh Yess Thank you! I did install that recently.

**Comment by Kuktar** [comment]
omg this was super helpful.  i was so frusterated when my shiny new bow just broke even with 1250 durability lol
