### ISSUE TITLE
[1.12.2]  TC_2.10.1.87: Cannot smelt casts again

### ISSUE THREAD

**Issue by PearlCanopus** [SlimeKnights/TinkersConstruct#3549]
I don't know whether it works as intented.
I created an empty golden cast by mistake. When I place it back to the smeltery, the progress bar greys out as it does with other incompatible items too.

Because it's only 1 or 2 bars, it's really no heavy thing. But I'd like to be able to smelt it on principle.

**Comment by KnightMiner** [comment]
This is intended. You can make casts out of gold or brass, so there is no way to know which to melt back into. This issue has been reported before, so you could easily have searched and gotten the same answer.
