### ISSUE TITLE
Change Trait/Modifier info in Tooltip to only show when pressing shift

### ISSUE THREAD

**Issue by darKpoiSon** [SlimeKnights/TinkersConstruct#3550]
I think it would look a lot cleaner, if the traits of a tool would only be shown when pressing shift.
Now I'm using Tinkerstoolleveling and have a lot of traits and modifiers to the point where the Tooltip is to big to actually read everything in it.
However I think it still applies to standard tinkers even though you might not have as many traits/modifiers to show.

Maybe it could be a config option to change this behaviour, since the extraTooltip config option only shows the stats for a given tool when pressing shift.

**Comment by bonii-xx** [comment]
Traits and modifiers should not be hidden, since they impact tool behaviour. It's fine as is. Adding tons of modifiers using other mods is not the default case.
