### ISSUE TITLE
Suggestion (maybe)

### ISSUE THREAD

**Issue by DaggerTM** [SlimeKnights/TinkersConstruct#3552]
I've been playing around with EFab on a pack I'm working on and I wanted to make getting the tinker tables a little harder to get, so I removed the recipes and used EFab's JSON to add them in... But they don't work... Of course, I removed the .NBTTAG after the tables to something like tconstruct:tinkertables:1. There is no output only the inputs and time... How would I make the recipies a little different but keep it general but only allow them in EFab.?

 **Heres the config that won't work:**

> [
>     {
>         "type": "shaped",
>         "output": 
>             {"item": "tconstruct:tooltables:1"},
>     "input": 
>     [
>       " a ",
>       " b ",
>       " a "
>     ],
>     "inputmap": 
>     {
>       "a": 
>         {"item": "tconstruct:pattern"},
>       "b": "logWood"
>     },
>     "time": 300
>     }
> ]

**Heres a picture:**

> ![capture](https://user-images.githubusercontent.com/14302401/41639007-2a1f1ab4-742a-11e8-84ad-7f3ec9ec5862.PNG)

(I'd bring this up to EFab, but I don't see an Issue page.)

**Comment by bonii-xx** [comment]
I'm severely confused by your definition of suggestion.
I'd assume that the metadata is not handled in the item, but a separate entry. Take a look at the EFab documentation. You can easily test stuff by using the /give command ingame. You don't need the NBT on the tables for them to work, that's just for the type of wood used. It will always default to oak wood without NBT.
