### ISSUE TITLE
Thaumcraft 6 thaumium cannot be used to create tool parts.

### ISSUE THREAD

**Issue by Razorfin8** [SlimeKnights/TinkersConstruct#3553]
I don't know if this is a bug or not, but you used to be able to use old thaumcraft thaumium to create tool parts.  It had a similar effect to writable and gave pretty decent stats. This is not the case anymore, is there a plan for this or is this just an oversight?

**Comment by KnightMiner** [comment]
We do not add mod support since 1.8, it is up to mods or addons to add support.
