### ISSUE TITLE
Tesselation bug with part builder

### ISSUE THREAD

**Issue by Pandemoneus** [SlimeKnights/TinkersConstruct#3556]
Playing the Enigmatica 2 Expert Skyblock pack, I shut down the game as usual. But now, once I load my world, I crash to the desktop with the following crash report:
https://hastebin.com/azubokaban.sql

From the log it seems like the game has problems tesselating the part builder, which is why I am reporting this crash here first.

**Comment by bonii-xx** [comment]
Disable the table items displayed in world config (just check the config, i forgot the exact name). This will disable rendering of items on the tables. You got some broken model in the part builder, for some reason.

**Comment by Pandemoneus** [comment]
Thanks, that worked. I will leave the issue open though.

**Comment by KnightMiner** [comment]
Do you know what item caused it? Otherwise there is nothing we can really do with this issue

**Comment by Pandemoneus** [comment]
No, there was a normal large plate pattern in the part builder.
