### ISSUE TITLE
Piggybackpack: Entity stays on head when the chestplate slot is swapped out

### ISSUE THREAD

**Issue by ZenixTheHusky** [SlimeKnights/TinkersConstruct#3557]
TiC version: 2.10.1.87
Pack: FTB Continuum 1.3.1

While holding an entity and the Piggybackpack is equipped in the chestplate slot, the Piggybackpack can be replaced with a chestplate or jetpack and the entity will still be over the player's head while allowing them to have the extra armor points or fly around if a jetpack is equipped.  

If the chestplate or jetpack is then removed, the entity still remains on the player's head until the Piggybackpack is re-equipped and unequipped.

**Comment by bonii-xx** [comment]
Sigh, what did they break now. Can you reproduce it with only TiC? Might be some other mod messing with capabilities.

**Comment by ZenixTheHusky** [comment]
Hey, sorry for the late reply - I was on holiday.

I created a vanilla 1.12.2 instance with Forge 14.23.4.2747, Mantle 1.3.2.24 and TiC 1.12.2-2.10.1.87 and the bug still occurs

**Comment by KnightMiner** [comment]
Same as #3880, marked the other issue as fixed so I'll close this as a duplicate.
