### ISSUE TITLE
Tool Forge Item Duping

### ISSUE THREAD

**Issue by RacerDelux** [SlimeKnights/TinkersConstruct#3558]
Found this one today using 2.10.1.87 in ATM modpack.
This takes two people. Person 1 puts any tool in the Tool Forge and starts to type a name. As long as they are constantly typing, person 2 can just keep taking the tool out over and over again.

![image](https://user-images.githubusercontent.com/2667344/42016249-71884b68-7a70-11e8-9e56-d70bbd3ef888.png)

As far as I can tell, this is super easy to repeat and works 100% every time. In the above picture, I was just typing "!" while somebody else on the server took them out.

**Comment by KnightMiner** [comment]
Can you reproduce with just Tinkers?

**Comment by RacerDelux** [comment]
I will have to spin up a server and check with somebody.

**Comment by RacerDelux** [comment]
Hey so this same bug can be reproduced with Construct's Armory's armor station. Does it use the same code, or would this point to a larger issue created by another mod?

**Comment by KnightMiner** [comment]
They use their own code, but it is likely largely based on ours. I get the feeling any change we make will not directly fix things on their side but that does not mean its a universal issue.

**Comment by KnightMiner** [comment]
Did you ever check if this happened with just Tinkers Construct?

**Comment by RacerDelux** [comment]
I have not be able to get another person in to test yet,

**Comment by KnightMiner** [comment]
Closing for lack of response
