### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by Elytrus** [SlimeKnights/TinkersConstruct#3560]
Note: This is a very similar issue to Issue 3239 but is occurring with different versions https://github.com/SlimeKnights/TinkersConstruct/issues/3239
Note 2: I'm very new to mod development so there are probably nuances that I have missed

Error: https://hastebin.com/oziwozebug.rb
TConstruct Version: 1.12.2-2.10.1.84
Mantle Version: 1.12-1.3.2.24
Forge Version: 1.12.2-14.23.4.2705 (Using the MDK)

My build.gradle: 
https://hastebin.com/iyehikehoq.cs

![image](https://user-images.githubusercontent.com/19026336/42079222-1b163032-7b4d-11e8-915c-21a49199ecc3.png)
Again, the NoSuchFieldError stuff that was in issue 3239

**Comment by bonii-xx** [comment]
Mappings changed. Don't use deobf dependencies, use deobfCompile with the actual code.

We should probably stop providing deobf jars.
