### ISSUE TITLE
[Request] Direct attribute working on collecting exp, and also on weapons

### ISSUE THREAD

**Issue by zhouyu47** [SlimeKnights/TinkersConstruct#3561]
The Direct attribute when harvesting mineables that also give exp, such as coal and lapis, could also transfer exp directly to the player.  If this is possible, it would be a great addition.

Also the Direct attribute only works on mined things, couldn't it also work on weapons when killing mobs to directly transfer loot to your inventory?

Thanks.

**Comment by bonii-xx** [comment]
There is no Direct attribute in TiC, you're probably thinking of an addon.
