### ISSUE TITLE
Hammer not working on netherrack

### ISSUE THREAD

**Issue by adventurerok** [SlimeKnights/TinkersConstruct#3562]
In the FTB Revelation 2.1.0 modpack (using Tinkers Construct 2.10.1.87) my friend and I, both playing on the same server, are having the issue with our hammers that they sometimes fail to mine netherrack at all, with the client seeing the middle block dissapear, but right clicking where it was confirms that it is still there.

I assume this is an issue with fast hammers breaking blocks that are fast to break. The hammer that I have been using is a cobalt hammer with a diamond and one full haste upgrade bringing its mining speed to 6.21. It has an electrum tough tool rod in addition so it has both the "shocking" and "momentum" effects. Prior to the addition of the diamond and haste upgrades the hammer would mine netherrack with no issue.

**Comment by KnightMiner** [comment]
That is likely simply server lag, you will notice the same effect with an Efficiency V diamond pickaxe. Really doubt we can do anything to fix it.

**Comment by KnightMiner** [comment]
Closing as this is just normal lag and vanilla pickaxes tend to have the same issue.
