### ISSUE TITLE
[Question] Is it possible to blacklist items for Auto Smelt

### ISSUE THREAD

**Issue by gconlon2002** [SlimeKnights/TinkersConstruct#3564]
Is this possible or is there away to use scripts.

**Comment by gconlon2002** [comment]
Yea I was wanting to stop coal from being autosmelted as it gets turned into graphite ingots form nucleurcraft and I can't find a blacklist config.

**Comment by KnightMiner** [comment]
This sounds more like an argument that you should use a different pickaxe when mining coal ore. Tinkers Construct tools were never designed to be all purpose, they were designed to be built for the task. Like how you should not mine ores with a silk touch pickaxe if you want the normal drops, you should not mine coal ore with a auto-smelt pickaxe if you don't want graphite.

**Comment by gconlon2002** [comment]
Yea thought so, that's what I done in my last pack.

**Comment by bonii-xx** [comment]
Sorry, there is no way to blacklist things. You either have autosmelt or not. As someone who also experiences that personally from time to time... I've always found it stupid that you have to smelt coal into graphite.
