### ISSUE TITLE
[1.12.2 TiC version 2.10.1.87] Fresh installation defaults with more than vanilla materials

### ISSUE THREAD

**Issue by Ashendale** [SlimeKnights/TinkersConstruct#3565]
As I was readying a custom pack I noticed a pack with PlusTiC had Invar and Nickel enabled even though I specified not to on configurations. After hours of configure tinkering, and Google-fu I decided to make a new pack with just Tinkers' Construct

Turns out invar on PlusTiC defaults itself to "on" if there is nickel present somewhere... Which there wasn't, or so I thought. TiC defaults with nickel, zinc and a crapton of other materials when they are unobtainable, or even inexistant. This is cluttering my recipe lists and JEI and making everything more complicated.

There is an option B:registerAllItems=false which I thought would keep items and recipes locked out unless a mod with the materials/ores came into play. Apprentely not (did I misinterpret what this option does?).

Is this intended, or am I missing something?

**Comment by KnightMiner** [comment]
You probably broke something somehow, I am going to need a full mod list if I am to give you any information.

Tinkers only adds common metals if another mod adds them, though note it always adds molten metals due to how the Forge fluid registry works.

**Comment by Ashendale** [comment]
I can give you the full pack as it is. I made a new pack (MultiMC), and copied all mods manually (but not the configuration files!) I had.

To double check my claim, I made a copy as stated above. I did not lanch the one I am sending - it should be mint. I will send everything except the disabled mods. Full mod list is as follows:

- Psi-r1.1-59.jar
- Quark-r1.4-125.jar
- RecurrentComplex-1.4.7.jar
- SilentLib-1.12-2.2.18-100.jar
- StorageDrawers-1.12.2-5.3.7.jar
- TConstruct-1.12.2-2.10.1.87.jar
- Thaumcraft-1.12.2-6.1.BETA17.jar
- ThaumicInventoryScanning_1.12.2-2.0.10.jar
- ThaumicJEI-1.12.2-1.4.0-14.jar
- thaumicperiphery-0.2.4.jar
- theoneprobe-1.12-1.4.23.jar
- topaddons-1.12.2-1.7.0.jar
- Waystones_1.12.2-4.0.43.jar
- AppleSkin-mc1.12-1.0.9.jar
- AutoRegLib-1.3-18.jar
- Baubles-1.12-1.5.2.jar
- BetterFps-1.4.8.jar
- BiblioCraft[v2.4.5][MC1.12.2].jar
- BloodMagic-1.12.2-2.2.12-97.jar
- Blur-1.0.4-14.jar
- Botania+r1.10-354.jar
- Chameleon-1.12-4.1.3.jar
- Chisel-MC1.12.2-0.2.0.31.jar
- CodeChickenLib-1.12.2-3.2.0.345-universal.jar
- CraftTweaker2-1.12-4.1.9.jar
- CTM-MC1.12.2-0.3.1.16.jar
- cucumber-1.12-1.1.0.jar
- DynamicSurroundings-1.12.2-3.4.9.14.jar
- EnderStorage-1.12.2-2.4.4.132-universal.jar
- FastLeafDecay-v14.jar
- foamfix-0.9.9.1-1.12.2-anarchy.jar
- FTBLib-5.2.0.23.jar
- FTBUtilities-5.2.0.28.jar
- FunOres-1.12-1.5.7-118.jar
- GraveStone-1.12.2-Graves-1.0.16.jar
- Guide-API-1.12-2.1.5-60.jar
- harvestables-1.2.1.jar
- InventoryTweaks-1.63.jar
- IronBackpacks-1.12.2-3.0.8-12.jar
- ironchest-1.12.2-7.0.42.827.jar
- IvToolkit-1.3.3-1.12.jar
- jei_1.12.2-4.11.0.202.jar
- jeiintegration_1.12.2-1.5.1.36.jar
- journeymap-1.12.2-5.5.2.jar
- JustEnoughResources-1.12.2-0.8.5.27.jar
- MagicalPsi-1.3.jar
- Mantle-1.12-1.3.2.24.jar
- modtweaker-4.0.12.jar
- MouseTweaks-2.8-mc1.12.1.jar
- MTLib-3.0.5.jar
- mysticalagriculture-1.12-1.6.12.jar
- natura-1.12.2-4.3.2.49.jar
- NaturesCompass-1.12.2-1.5.1.jar
- OpenBlocks-1.12.2-1.7.6.jar
- OpenModsLib-1.12.2-0.11.5.jar
- plustic-6.5.2.0.jar

[Support Pack.zip](https://github.com/SlimeKnights/TinkersConstruct/files/2165364/Support.Pack.zip)

**Comment by KnightMiner** [comment]
And you are sure with just Tinkers Construct installed you still see the other materials?

**Comment by Ashendale** [comment]
Loading just 

- TConstruct-1.12.2-2.10.1.87.jar
- BetterFps-1.4.8.jar
- foamfix-0.9.9.1-1.12.2-anarchy.jar
- jei_1.12.2-4.11.0.202.jar
- journeymap-1.12.2-5.5.2.jar
- Mantle-1.12-1.3.2.24.jar

and using an instance folder without a config folder it loads (aside the vanilla materials and possible alloys of those like Pigiron and Manyullyn) Aluminum Brass, Brass, Copper, Tin, Bronze, Zinc, Lead, Nickel, Silver, Electrum, Steel and Aluminum. Unless there is a config file outside the instance folder this makes no sense.

I will attach a zip with a copy of what I sent on the previous post, but after launching it once, and loading a creative world.

[Support Pack Test.zip](https://github.com/SlimeKnights/TinkersConstruct/files/2167496/Support.Pack.Test.zip)

Only other thing I can think of doing is uninstalling MultiMC and clearing any related folder to confirm if there is an outside config file of some sort...

**Comment by KnightMiner** [comment]
In the future, *just* means don't add mods such as BetterFPS or Foamfix, you don't need them to load the game and check if materials exist.

I loaded up your pack and do not see the materials at all, you are either not loading the mod pack properly or are seeing the molten fluids can calling them tool materials.

**Comment by Ashendale** [comment]
You are absolutely  correct - it is the molten metals and their buckets that I see. The materials are unavailable. I've just tested and even though they show up (invar and nickel), invar cannot be created, even while cheating buckets of the liquid in.

The only real issue I now have is that invar shows from PlusTiC becasue nickel is "available", but this can't be faulted to TiC, I think. Ideally the inexistant liquids wouldn't be registered, but I'm sure you have better things to look at.

I'm really sorry for taking your time like this.

Thank you for your attention, and bes tof luck on your endeavours.

**Comment by KnightMiner** [comment]
Well, the issue is we cannot not register them. We have to register liquids at the beginning of loading, but don't know if we need them until the end of loading. We might be able to hide them in JEI if they are unused though, I'll look into that

**Comment by Ashendale** [comment]
If you want to go ahead woth that, by all means. But if you're thinking about what I suggested, hiding doesn't solve this particular issue. I tried using Crafttweaker to hide them on JEI, and even if hidden, PlusTiC will still load the invar.

It will show, but not alloy, interestingly...

**Comment by KnightMiner** [comment]
Then that is a PlusTiC bug for them to fix
