### ISSUE TITLE
Comparator does not recognize whether casting basin/table contains fluid or items

### ISSUE THREAD

**Issue by Peach774** [SlimeKnights/TinkersConstruct#3568]
There is no signal emmited by a comparator next to a casting basin or casting table under any circumstance.  Whether it should emit a signal based on fullness, containing an item, or being empty is up to you as devs, but it should do something.

**Comment by KnightMiner** [comment]
It does emit a signal, the signal is when crafting is finished. Try casting something

**Comment by KnightMiner** [comment]
![2018-07-06_23 02 21](https://user-images.githubusercontent.com/12155288/42406608-b537be64-8170-11e8-8b74-df0d9f35e80d.png)
You sure about that?

**Comment by Peach774** [comment]
Thats very strange. Im going to go ahead and say that having a hopper beneath it breaks this then, because it isnt able to emit a signal fast enough or something. Try testing with a hopper beneath the casting table?

**Comment by KnightMiner** [comment]
It's highly likely that a hipper would break it, vanilla inventories have always been finicky in responding to comparators is there is a hopper (nothing really we can do). You are off powering the hopper until you get your signal to check it.

**Comment by TherminatorX** [comment]
If you're doing this for smeltery automation, use the comparator to read the item going through the hopper, as it keeps it long enough to pulse a signal. That's what I use in my setups.

**Comment by KnightMiner** [comment]
I literally just said I see the same behavior with vanilla. The only reason you don't see it with hoppers is because they force a cooldown with each other to prevent items moving too fast.
