### ISSUE TITLE
Support for Trajectory Preview

### ISSUE THREAD

**Issue by Wolframme** [SlimeKnights/TinkersConstruct#3570]
Hello,
If possible, I'm asking for support for [Trajectory Preview](https://minecraft.curseforge.com/projects/trajectory-preview?gameCategorySlug=mc-mods&projectID=289141#c12). The author has pointed out that with their API it will be easier to support on this end rather than on their end.

**Comment by bonii-xx** [comment]
Hm, maybe some day, I'd need to check the mod itself.

**Comment by Wolframme** [comment]
It looks like the author changed their mind and updated the mod to support Tinker's just a few hours ago. Thank you for taking it into consideration though. I'll go ahead and close this.
