### ISSUE TITLE
InventoryCraftingPersistent#isEmpty() always true

### ISSUE THREAD

**Issue by GotoLink** [SlimeKnights/TinkersConstruct#3571]
`InventoryCraftingPersistent` override `InventoryCrafting` to replace with the tile inventory, but doesn't cover the       `isEmpty()` method.
Encountered this issue while trying to add compatibility for your crafting table in my mod.
TConstruct 2.10.1.87

**Comment by bonii-xx** [comment]
Hm, you're right. I wonder if that had a reason. What are you using it for?

**Comment by GotoLink** [comment]
This is for NoMoreRecipeConflict mod.
I am using it as a simple gate before a costly recipe look-up, for optimization sake.
I don't think this method has any effect outside crafting.
You could imagine a modded recipe that first check this method of the inventory. The recipe would work in vanilla crafting table, but not yours.
As opposed to other inventory in blocks, where not implementing isEmpty() may bring issues with hoppers.

**Comment by bonii-xx** [comment]
The IInventory only exists for the GUI. It only ever is created in the container. Hoppers use IItemHandlers

**Comment by GotoLink** [comment]
Agreed, it is a minor case. Would you fix it ?

**Comment by bonii-xx** [comment]
Yup, we'll probably fix it, since it's effectively just a forward to the actual inventory. I just hope there isn't some reason why we left it out ;P
