### ISSUE TITLE
[1.12.2] sevtech ages items have default (i think) textures

### ISSUE THREAD

**Issue by ArturittuPL** [SlimeKnights/TinkersConstruct#3572]
I have been playing sevtech ages for a while but recently this I got this bug where the textures of items are not what they are supposed to be.
![image](https://user-images.githubusercontent.com/19620451/42557421-cfae3184-84ee-11e8-8440-7076f997a729.png)

![image](https://user-images.githubusercontent.com/19620451/42557533-197000a4-84ef-11e8-99fa-0f62abddd073.png)

**Comment by Tahakk** [comment]
I'm playing Sevtech and didn't have this problems, do you have any additional mods installed?

**Comment by ArturittuPL** [comment]
i have optifine idk if its there by default i dont remember

**Comment by Tahakk** [comment]
Then try removing it and see if it helps

**Comment by ArturittuPL** [comment]
removing optifine didnt really help it made me see armor but that is not the issue

**Comment by bonii-xx** [comment]
>c4.conarm.lib.client.DynamicTextureHelper$CacheKey@a999d1fb.

You got a mod breaking your rendering ;o
Not TiC related.
