### ISSUE TITLE
Breaking Unbreakable Tool

### ISSUE THREAD

**Issue by twincitygamer** [SlimeKnights/TinkersConstruct#3575]
Currently have a magical wooden pickaxe with the unbreaking affect  and it still breaks. I pretty sure its a tinkers tool leveling problem

**Comment by TherminatorX** [comment]
It's Tema
https://github.com/SlimeKnights/TinkersConstruct/issues/3530

**Comment by KnightMiner** [comment]
This is a Extra Utiluties bug reported plenty of times.

**Comment by twincitygamer** [comment]
Anyway to fix it besides deleting extra utilities

**Comment by KnightMiner** [comment]
Don't use magical wood and unbreakable. Magical wood literally says it randomly breaks tools, which apparently circumvents unbreakable
