### ISSUE TITLE
No dark backdrop at the tinker tank GUI

### ISSUE THREAD

**Issue by Hallo89** [SlimeKnights/TinkersConstruct#3579]
Hi!
I've encountered a very simple bug: The GUI of the Tinker's Construct tinker tank does not have the transparent-dark backdrop every GUI should have when opened.
Minecraft version: `1.12.2`
Forge version: `forge-14.23.4.2738`
TiC version: `TConstruct-1.12.2-2.10.1.87`
-Although it happened in earlier versions as well (forgot to report it)
Mods used: only TiC and nothing more
![image](https://user-images.githubusercontent.com/21200815/42782921-9f434952-894a-11e8-8133-85a07a642751.png)

**Comment by KnightMiner** [comment]
Dark backdrop? You mean the one added by Blur? That is not a native GUI feature. Try with just Tinkers and you will find the Tinker tank looks like any other GUI

**Comment by Hallo89** [comment]
If you open any GUI the space which is not the GUI, meaning the world in the background, turn's dark in order for the user to focus on the GUI, which is not the case for the GUI of the tinker tank, like you see in the above attached picture

**Comment by Hallo89** [comment]
If you open any GUI the space which is not the GUI, meaning the world in the background, turn's dark in order for the user to focus on the GUI, which is not the case for the GUI of the tinker tank, like you see in the above attached picture. I would at least check the issue before commenting things like those, especially when it's a very simple procedure
