### ISSUE TITLE
No more Flux Modifier?

### ISSUE THREAD

**Issue by chaos234** [SlimeKnights/TinkersConstruct#3580]
I am not sure why but there is no longer a way to add any kind of energy providing capacitors to tools.

Will this come in the future? It was very nice to have power (mainly RF) on the tools but it would be much more better to support other energy sources as well (e. g. IC2).

Would be nice :)

**Comment by KnightMiner** [comment]
It was not re-implemented because it was basically free durability at little cost, plus Tinkers no longer directly adds material/modifier mod support
