### ISSUE TITLE
Bolt Core Unreplacable with One Matching Material (1.12.2, 2.10.1.87)

### ISSUE THREAD

**Issue by SweetSugarSugar** [SlimeKnights/TinkersConstruct#3581]
If the one of the materials on the bolt core (the shaft or the metal poured onto it) matches the bolt being replaced, it will not be replaceable.

Same metal material, different shaft.
![2018-07-18_14 04 14](https://user-images.githubusercontent.com/14182009/42899708-de973c6c-8a94-11e8-864d-ead97ce51146.png)

Same shaft, different metal material.
![2018-07-18_14 13 41](https://user-images.githubusercontent.com/14182009/42899709-df050918-8a94-11e8-8d39-852697e00de8.png)

Different metal material and shaft.
![2018-07-18_14 04 45](https://user-images.githubusercontent.com/14182009/42899714-e1cd8986-8a94-11e8-9347-a3b7fd07ebb2.png)

**Comment by KnightMiner** [comment]
Fixed in 1.16 by removing bolts, they were way too complicated. Bit too complicated to fix in a bugfix 1.12 release, so closing this.
