### ISSUE TITLE
Diamond + Gold Block modifier not working after applying diamond to tool.

### ISSUE THREAD

**Issue by geniiii** [SlimeKnights/TinkersConstruct#3582]
![image](https://user-images.githubusercontent.com/24881499/42973411-b69fb702-8bbb-11e8-81d3-4cb90106056a.png)  
Using `TConstruct-1.12.2-2.10.1.87.jar`.

**Comment by KnightMiner** [comment]
Yes, it was removed over 2 years ago in the rewrite.

**Comment by geniiii** [comment]
ah, I see, sorry.
