### ISSUE TITLE
Glowball Connecting to Fences (1.12.2, 2.10.1.87)

### ISSUE THREAD

**Issue by SweetSugarSugar** [SlimeKnights/TinkersConstruct#3585]
O.o
![2018-07-20_21 15 42](https://user-images.githubusercontent.com/14182009/43030731-7aff7802-8c62-11e8-95f7-0ab7fe249ca1.png)

**Comment by KnightMiner** [comment]
Yeah, I think we need to go through a lot of our blocks and set proper fence connections. Faucets also have this behavior from what I recall, probably others
