### ISSUE TITLE
Mining Level: Diamond for pickaxes?

### ISSUE THREAD

**Issue by danikk14g** [SlimeKnights/TinkersConstruct#3586]
Hello, i am making a modpack which requires to visit the Nether before making steel and diamond tools, and one of the ways to get obsidian without diamond tools are TiC pickaxes, but i have noticed all the tools which display Mining Level: Diamond (Iron, Bronze, Constantan, Pig Iron) are not able to break obsidian. So i wonder what is the difference between iron level and diamond level.

Thanks in advance.

Minecraft 1.12.2
TConstruct-1.12.2-2.10.1.87
Forge 1.12.2-14.23.4.2739

**Comment by KnightMiner** [comment]
Mining level diamond means it can mine diamonds. You want mining level obsidian to mone obsidian. It makes no sense to name our mining levels after the vanilla tools, so we just name them after what they can mine.
