### ISSUE TITLE
Suggestion: More config options (effective material)

### ISSUE THREAD

**Issue by WGHxPERNAxBEAST** [SlimeKnights/TinkersConstruct#3587]
I suggest that you make it a config option as to what each tool's effective material is. I mainly want this as an easy way for players to opt whether or not a mattock should break sand and gravel. I think it should, but I am aware others would disagree with me. Making this configurable would make everyone happy.

**Comment by SweetSugarSugar** [comment]
If you want to dig sand and gravel faster, either use a shovel or use Knightslime for a head material.  The mattock's purpose is clearing out land and farming, hence the description of allowing it to cut down dirt, wood, and plants.

**Comment by KnightMiner** [comment]
What has been said is sufficient. The mattock is not designed to replace shovels, wont be as good as one in all cases.
