### ISSUE TITLE
Possible render glitch with casts on the casting table

### ISSUE THREAD

**Issue by TheMightyAtomNL** [SlimeKnights/TinkersConstruct#3588]
There appears to be some sort of rendering glitch with casts when placed on a casting table. Here's a screenshot of me holding a tool rod cast:
![mc_tc_toolrodcast](https://user-images.githubusercontent.com/9323025/43205303-5a394534-9023-11e8-99c2-155c17c02231.png)
Note that you can clearly see on my hotbar that this is a tool rod cast. Holding it my hand, the cast appears as if it's just an blank cast.

Upon placing it on the casting table, the cast appears as a blank cast as well:
![mc_tc_toolrodcastappearsasblank](https://user-images.githubusercontent.com/9323025/43205309-5f1317ce-9023-11e8-80c7-82f55c78b09f.png)

The tool tip at the top (provided by The One Probe) show that there's a tool rod cast on the table, but visually it shows a blank cast.

Could this be a Tinker's Construct problem or a mod conflict?

Game info:
Minecraft version: 1.12.2
Forge version: 14.23.4.2726
Tinker's Construct version: 2.10.1.87
Complete list of mods attached.

![mc1122_modlist](https://user-images.githubusercontent.com/9323025/43205268-44a27308-9023-11e8-9056-a0821b3c0b30.png)

**Comment by KnightMiner** [comment]
Remove optifine. That is known to cause issues like this.

**Comment by TheMightyAtomNL** [comment]
Just found out that even with Optifine disabled, it still happens.
Also, created tools appear flat when holding them in hand or when thrown on the ground And the colors are all white. For example, a cobalt hammer head is blue, but it looks white for some reason.

**Comment by KnightMiner** [comment]
White tools is a conflict between texfix and foamfix. That could also be causing the cast issues, but I've mainly seen optifine cause that (what do you mean by disabled? Do you remove the jar or toggle it in game?)

**Comment by TheMightyAtomNL** [comment]
I have removed the jar. I don't feel like disabling all those other performance tweaking mods, because I do think they make a difference, so I guess I'll just deal with the white looks of Tinker tools. Funny thing is that not all casts appear as blank casts though, the ingot and large plate casts render just fine on a tinker table. What gives?

**Comment by KnightMiner** [comment]
Because the textures are dynamically generated except the ingot and plate. Did you try the other thing I mentioned? Removing worker texfix or foamfix? If that fixes it then there might be a config option on one of the two to fix it.

**Comment by KnightMiner** [comment]
Closing for lack of response, as we need to know which other mods are affecting this to fix.

**Comment by DemonfangArun** [comment]
I ran into this. Texfix doesn't exactly have a config. You mentioned that both texfix and foamfix can exist with tconstruct peacefully, what configuration change would allow this?

**Comment by KnightMiner** [comment]
See [the TexFix description](https://minecraft.curseforge.com/projects/texfix). The spoiler under known incompatibility tells you how to fix the issue

**Comment by DemonfangArun** [comment]
That only applies to foamfix anarchy, the option doesn't exist in the non-anarchy version (I looked).

**Comment by KnightMiner** [comment]
If you are still experiencing a conflict then you have a different issue likely. I guess try and pin down the exact cause and open a separate issue for that (as this one was closed for lack of information, its hard to tell if yours is the same or not)

**Comment by DemonfangArun** [comment]
It's the same symptoms (casts don't render right, white tools, etc...). It's possible that it's the same root cause but being invoked by something different.

**Comment by BunCat09** [comment]
This is caused by foamfix and you can Fix it easily. Just open the config folder and find foamfix.cfg than Open it with notepad. After that you have to disable "dynamicItemModels" under the coremod header. Unfotunately you can Not do This from in-game config editor.

**Comment by KnightMiner** [comment]
Yes, that was already said earlier in the issue. No need to post on an issue that has been closed for over a year to repeat that.

**Comment by LunarLuncher** [comment]
So I notice you have a lot of the mods we have in our server. We never had this problem until I added Thermal Dynamics AND IndustrialCraft. Try removing one of those?
I will edit this comment when I do :D
