### ISSUE TITLE
Bronze from ThermalF not "ore dictionary"ed?

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [SlimeKnights/TinkersConstruct#3591]
Hello. I've been playing with TConstruct - 1.12.2 - 2.10.1.87 and with ThermalF - 1.12.2 - 2.5.0.19-universal.

I noticed that, for some reason, my TConstruct is not detecting ThermalF bronze as being a valid ore.
Bellow I'll show my config file from TConstruct and some SSs showing my problem:

Config: https://pastebin.com/huPsivej
SSs: https://imgur.com/a/aiKi31J

Thanks in advance!

**Comment by KnightMiner** [comment]
Looks perfectly valid from your screenshots, you just have no fuel in the smeltery. Hovering over the blue bar would have shown a tooltip that would have said the same thing without an issue report.

You should also note the part builder recognized bronze as it literally says bronze in the box on the right, you just cannot make metal parts in the part builder by default.

**Comment by bonii-xx** [comment]
Maybe we should make the fuel bar light up if there is no fuel at all. Hm.

**Comment by Marcelo-Petrucelli** [comment]
I'm awfully sorry about this issue raised =X
I haven't played Minecraft for some time now, so I had to get used to the progression before posting here.

If that doesn't add much trouble, a "No Fuel" sign would be pretty nice to have.
Thanks for the GREAT work. I love TC!
