### ISSUE TITLE
TC tooltip font error, help

### ISSUE THREAD

**Issue by stopcraft** [SlimeKnights/TinkersConstruct#3592]
https://github.com/SlimeKnights/TinkersConstruct/issues/2839

https://imgur.com/n43WzpT (image 1)
https://imgur.com/N2Njbvz  (image 2)

I installed FTB Beyond and I touched nothing.
my TC tooltip have same error. but different thing is I'm not using Optifine, nor unicode option.

**Comment by bonii-xx** [comment]
Are you using any resourcepacks and/or clientside mods? (Especially stuff like better fonts etc.)

**Comment by stopcraft** [comment]
I use localization chat mod so I think it can make font error, I'll remove it

**Comment by KnightMiner** [comment]
Did it still happen when you removed that mod?

**Comment by KnightMiner** [comment]
Closing for lack of response
