### ISSUE TITLE
Tinkers construct- Crash when entering a world possibly because of a bow

### ISSUE THREAD

**Issue by Danny1612** [SlimeKnights/TinkersConstruct#3593]
I confirm that the crash comes from the mod tinkers contruct. (I created a copy of the world and then remove TC, and load the copied world and it was find( everything from TC is gone ofc))

-I was messing with TC's bows and then my Minecraft crash for no reason, I think that just before I crash I was drawing/ pulling back my bow and at the same time I open my tool forge (not sure).

---- Minecraft Crash Report ----
// My bad.

Time: 18-7-30 上午1:27
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at tconstruct.library.weaponry.ProjectileWeapon.getIcon(ProjectileWeapon.java:239)
	at net.minecraft.entity.player.EntityPlayer.func_70620_b(EntityPlayer.java:1843)
	at net.minecraft.client.entity.EntityPlayerSP.localGetItemIcon(EntityPlayerSP.java)
	at api.player.client.ClientPlayerAPI.getItemIcon(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70620_b(EntityPlayerSP.java)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:100)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
	at ItemRendererOF.func_78440_a(ItemRendererOF.java:197)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1010)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:945)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1933)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1388)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.library.weaponry.ProjectileWeapon.getIcon(ProjectileWeapon.java:239)
	at net.minecraft.entity.player.EntityPlayer.func_70620_b(EntityPlayer.java:1843)
	at net.minecraft.client.entity.EntityPlayerSP.localGetItemIcon(EntityPlayerSP.java)
	at api.player.client.ClientPlayerAPI.getItemIcon(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70620_b(EntityPlayerSP.java)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:100)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
	at ItemRendererOF.func_78440_a(ItemRendererOF.java:197)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1010)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:945)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1933)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['IKiritoII'/2669, l='MpServer', x=-371.37, y=65.62, z=1139.32]]
	Chunk stats: MultiplayerChunkCache: 289, 298
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-108,64,964), Chunk: (at 4,4,4 in -7,60; contains blocks -112,0,960 to -97,255,975), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 1790620 game time, 738845 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 89 total; [EntityTFNagaSegment['unknown'/3073, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3074, l='MpServer', x=0.60, y=-0.08, z=0.60], EntitySlime['Slime'/2818, l='MpServer', x=-315.22, y=62.00, z=1062.78], EntityTFNagaSegment['unknown'/3075, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityHorse['Horse'/2819, l='MpServer', x=-310.03, y=63.00, z=1071.00], EntityTFNagaSegment['unknown'/3076, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityZombie['Zombie'/2820, l='MpServer', x=-314.41, y=48.35, z=1062.99], EntityTFNagaSegment['unknown'/3077, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityChicken['Chicken'/2821, l='MpServer', x=-314.41, y=48.00, z=1063.09], EntityTFNagaSegment['unknown'/3078, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityTFNagaSegment['unknown'/3079, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityHorse['Horse'/2823, l='MpServer', x=-312.56, y=64.00, z=1092.91], EntityTFNagaSegment['unknown'/3080, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityHorse['Donkey'/2824, l='MpServer', x=-315.25, y=62.02, z=1154.25], EntityTFNagaSegment['unknown'/3081, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityBat['Bat'/2825, l='MpServer', x=-310.58, y=27.22, z=1192.45], EntityTFNagaSegment['unknown'/3082, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityHorse['Horse'/2826, l='MpServer', x=-307.19, y=63.00, z=1208.13], EntityTFNagaSegment['unknown'/3083, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityHorse['Horse'/2827, l='MpServer', x=-308.16, y=63.00, z=1210.28], EntityTFNagaSegment['unknown'/3084, l='MpServer', x=0.60, y=-0.08, z=0.60], EntityHorse['Horse'/2837, l='MpServer', x=-295.03, y=64.00, z=1200.06], EntityMobEnderman['Enderman'/2712, l='MpServer', x=-466.08, y=58.00, z=1173.42], EntityHorse['Horse'/2586, l='MpServer', x=-293.75, y=69.00, z=1067.00], EntityHorse['Horse'/2587, l='MpServer', x=-294.00, y=67.00, z=1061.94], EntityBat['Bat'/2588, l='MpServer', x=-294.94, y=28.00, z=1085.85], EntityHorse['Horse'/2589, l='MpServer', x=-301.03, y=71.25, z=1086.61], EntityCreeper['Creeper'/2591, l='MpServer', x=-295.50, y=70.00, z=1081.50], EntityHorse['Horse'/2592, l='MpServer', x=-294.50, y=69.00, z=1073.91], EntityCreeper['Creeper'/2593, l='MpServer', x=-301.06, y=62.15, z=1132.78], EntityHorse['Horse'/2723, l='MpServer', x=-436.03, y=64.00, z=1123.44], EntityCreeper['Creeper'/2725, l='MpServer', x=-416.34, y=51.00, z=1122.97], EntitySquid['Squid'/2726, l='MpServer', x=-431.52, y=60.16, z=1164.63], EntitySquid['Squid'/2727, l='MpServer', x=-427.06, y=59.20, z=1167.38], EntitySquid['Squid'/2728, l='MpServer', x=-424.31, y=59.00, z=1168.61], EntitySquid['Squid'/2729, l='MpServer', x=-419.84, y=59.00, z=1171.52], EntityCreeper['Creeper'/2730, l='MpServer', x=-423.75, y=10.00, z=1190.84], EntitySlime['Slime'/2731, l='MpServer', x=-430.63, y=62.00, z=1198.70], EntityCreeper['Creeper'/2732, l='MpServer', x=-423.31, y=10.00, z=1203.09], EntitySpider['Spider'/2733, l='MpServer', x=-425.00, y=10.00, z=1205.00], EntityZombie['Zombie'/2734, l='MpServer', x=-420.70, y=64.26, z=1212.70], EntityMobEnderman['Enderman'/2606, l='MpServer', x=-287.57, y=66.00, z=1137.90], EntityMobEnderman['Enderman'/2607, l='MpServer', x=-266.70, y=67.00, z=1102.63], EntitySkeleton['Skeleton'/2739, l='MpServer', x=-409.72, y=69.00, z=1082.50], EntitySkeleton['Skeleton'/2740, l='MpServer', x=-405.87, y=25.16, z=1092.50], EntityHorse['Horse'/2741, l='MpServer', x=-415.20, y=70.00, z=1092.11], EntityZombie['Zombie'/2742, l='MpServer', x=-411.47, y=48.00, z=1115.03], EntityCreeper['Creeper'/2743, l='MpServer', x=-415.16, y=22.00, z=1138.38], EntitySquid['Squid'/2744, l='MpServer', x=-407.62, y=60.14, z=1169.45], EntityMinecartChest['entity.MinecartChest.name'/2745, l='MpServer', x=-415.50, y=13.50, z=1216.50], EntitySpider['Spider'/2756, l='MpServer', x=-387.53, y=63.42, z=1064.06], EntityZombie['Zombie'/2757, l='MpServer', x=-388.75, y=63.42, z=1068.00], EntityHorse['Horse'/2758, l='MpServer', x=-385.97, y=69.00, z=1070.28], EntityHorse['Donkey'/2759, l='MpServer', x=-386.06, y=69.00, z=1068.53], EntityHorse['Horse'/2760, l='MpServer', x=-393.96, y=69.00, z=1075.07], EntityHorse['Horse'/2761, l='MpServer', x=-391.00, y=65.42, z=1075.28], EntityZombie['Zombie'/2762, l='MpServer', x=-399.50, y=68.00, z=1073.09], EntityHorse['Horse'/2763, l='MpServer', x=-395.86, y=64.00, z=1095.75], EntityCreeper['Creeper'/2764, l='MpServer', x=-394.03, y=61.00, z=1122.56], EntityCreeper['Creeper'/2765, l='MpServer', x=-388.63, y=62.33, z=1164.91], EntityTrail['unknown'/3277, l='MpServer', x=-371.37, y=65.62, z=1139.32], EntitySkeleton['Skeleton'/2766, l='MpServer', x=-390.53, y=62.36, z=1185.72], EntitySpider['Spider'/2767, l='MpServer', x=-393.28, y=32.00, z=1201.41], EntityBat['Bat'/2772, l='MpServer', x=-376.00, y=57.10, z=1128.16], EntityCreeper['Creeper'/2773, l='MpServer', x=-375.06, y=37.00, z=1194.47], EntityCreeper['Creeper'/2774, l='MpServer', x=-371.30, y=41.35, z=1187.35], EntityHorse['Horse'/2778, l='MpServer', x=-364.22, y=66.00, z=1062.78], EntityZombie['Zombie'/2779, l='MpServer', x=-361.41, y=73.00, z=1077.91], EntityHorse['Horse'/2780, l='MpServer', x=-359.56, y=86.00, z=1100.59], EntitySkeleton['Skeleton'/2781, l='MpServer', x=-354.07, y=63.68, z=1165.37], EntityZombie['Zombie'/2782, l='MpServer', x=-356.63, y=44.00, z=1194.06], EntityZombie['Zombie'/2783, l='MpServer', x=-353.30, y=43.00, z=1186.13], EntityHorse['Horse'/2784, l='MpServer', x=-357.96, y=83.24, z=1214.79], EntityHorse['Horse'/2788, l='MpServer', x=-342.93, y=63.00, z=1061.22], EntityItem['item.item.wheat'/2789, l='MpServer', x=-351.88, y=64.13, z=1116.53], EntityItem['item.item.seeds'/2790, l='MpServer', x=-351.34, y=65.13, z=1115.75], EntityHorse['Horse'/2791, l='MpServer', x=-345.03, y=91.00, z=1113.66], EntityHorse['Horse'/2792, l='MpServer', x=-337.28, y=58.43, z=1166.22], EntityWitch['Witch'/2793, l='MpServer', x=-344.09, y=73.00, z=1156.56], EntityHorse['Horse'/2794, l='MpServer', x=-338.91, y=78.00, z=1183.00], EntityHorse['Horse'/2795, l='MpServer', x=-344.25, y=69.00, z=1169.03], EntityHorse['Horse'/2796, l='MpServer', x=-336.72, y=65.00, z=1173.47], EntityMinecartChest['entity.MinecartChest.name'/2797, l='MpServer', x=-350.50, y=18.50, z=1191.50], EntityClientPlayerMP['IKiritoII'/2669, l='MpServer', x=-371.37, y=65.62, z=1139.32], EntityZombie['Zombie'/2798, l='MpServer', x=-347.96, y=49.24, z=1193.52], EntityBat['Bat'/2671, l='MpServer', x=-380.25, y=41.10, z=1144.75], EntityHorse['Horse'/2807, l='MpServer', x=-326.56, y=67.00, z=1083.66], EntityCreeper['Creeper'/2808, l='MpServer', x=-321.50, y=65.00, z=1089.31], EntityHorse['Horse'/2809, l='MpServer', x=-331.00, y=81.00, z=1115.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2353851064 bytes (2244 MB) / 3674210304 bytes (3504 MB) up to 11811160064 bytes (11264 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx11G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (Not-Enough-Items-1.7.10-Latest.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	advancedgenetics{1.5.7} [Advanced Genetics] (Advanced-Genetics-Mod-1.7.10.jar) 
	UCHIJAAAA	antiqueatlas{4.4.4} [Antique Atlas] (Antique-Atlas-Mod-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (Applied-Energistics-2-Mod-1.7.10.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
	UCHIJAAAA	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.23} [BuildCraft] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.23} [BC Transport] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.23} [BC Factory] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.23} [BC Silicon] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.23} [BC Robotics] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.23} [BC Energy] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.23} [BC Builders] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-Mod-1.7.10.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenters-Blocks-Mod-1.7.10.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (DecoCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	props{2.4.1} [Decocraft] (DecoCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (Enchanting-Plus-Mod-1.7.10.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.38} [EnderStorage] (Ender-Storage-Mod-1.7.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-Mod-1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-Mod-1.7.10.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCHIJAAAA	ExtraPlanets{1.7.10-1.9.5} [Extra Planets] (Extra-Planets-Mod-1.7.10.jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion++MC-1.7.10++v1.8.6.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (HarvestCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	IGWMod{1.1.12-34} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.12-34-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.7} [?9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) 
	UCHIJAAAA	starwarsmod{1.3.3} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.3.3.jar) 
	UCHIJAAAA	PneumaticCraft{1.12.7-152} [PneumaticCraft] (PneumaticCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (Portal-Gun-Mod-1.7.10.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAAAA	SmartRender{2.1} [Smart Render] (Smart-Render-Mod-1.7.10.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (StorageDrawers-1.7.10-1.10.9.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiC-Tooltips-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 4400'
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:ON
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4531, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4531
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by KnightMiner** [comment]
We no longer support 1.7, especially with 1.7 optifine installed. Try removing that and see if it fixes your issue.

**Comment by bonii-xx** [comment]
Could also be broken metadata on the bow itself. Anyway, closing due to 1.7.10.
