### ISSUE TITLE
Tessellating Block Issue 

### ISSUE THREAD

**Issue by gconlon2002** [SlimeKnights/TinkersConstruct#3594]
A couple of times i have experienced this crash, it seems when i load up a world and teleport the tinkers tool table crashes the game.
https://hastebin.com/xazucodepu.rb

**Comment by SweetSugarSugar** [comment]
You have OptiFine installed.

**Comment by gconlon2002** [comment]
It has happened with and without optifine. I first experienced it without optifine.

**Comment by KnightMiner** [comment]
Duplicate of #3576
