### ISSUE TITLE
Clear Item Frame

### ISSUE THREAD

**Issue by UnlimatedStone9** [SlimeKnights/TinkersConstruct#3596]
The clear item frame for some odd reason has no item texture so you cannot actually see where it is in the inventory
 I know its supposed to be transparent on the wall but that's ridiculous

**Comment by SweetSugarSugar** [comment]
Um... it does have one?
![2018-07-31_13 42 36](https://user-images.githubusercontent.com/14182009/43476874-abe7959a-94c7-11e8-90af-b8b21090993e.png)

**Comment by KnightMiner** [comment]
He has quark installed, which makes the center of the glass texture clear. Not much we can do without supplying our own texture, but we could give it a better "frame" as even with the vanilla texture it's a bit hard to see.

**Comment by UnlimatedStone9** [comment]
Oh right, I realised that now, Why is It that the frame doesn't have its own anyways?

**Comment by KnightMiner** [comment]
Because then it has resource pack support, no reason to make a new texture when you almost never should see it anyways
