### ISSUE TITLE
Configure Diamond and emerald modifier levels

### ISSUE THREAD

**Issue by Anomerly** [SlimeKnights/TinkersConstruct#3598]
Hi guys,

I'm working on a mod pack that adds a stack of mining levels which has resulted in Diamond moving up from 3 to 6
Would it be possible to make the mining level that the Diamond and Emerald modifiers push a tool up to configurable? Or can you suggest a better way of achieving this?

**Comment by bonii-xx** [comment]
I think there's a Tinkers tweaks mod somewhere, maybe that can do it. We do not add such possibilities in TiC itself for support reasons. The API for those modifiers is pretty inflexible (and old) too, so as is it's pretty hard to do something like that.

Also, be aware that the diamond/emerald only increases level by 1 up to diamond/obsidian level. Most people use sharpening kits for the harvest level.

**Comment by KnightMiner** [comment]
No plans to implement this in 1.12. In 1.16 this is possible via an addon, not sure if I plan to support such configurations via datapacks or not
