### ISSUE TITLE
Chests in Crafting Station Texture Not Found

### ISSUE THREAD

**Issue by MeinKraft** [SlimeKnights/TinkersConstruct#3599]
Forge 1.12.2.....2739 and 2745
TConstruct 1.12.2-2.10.1.87
Java 1.81

No Optifine, No resource pack, No other mods (except JEI/TheOneProbe)

Placing a vanilla chest, trapped chest and ender chest into a Tinkers Crafting Station causes the pink/black texture to be drawn on the station

https://postimg.cc/image/okgt8521b/

**Comment by fuj1n** [comment]
Vanilla issue, chests don't have models to render
