### ISSUE TITLE
Crash on load up of single player

### ISSUE THREAD

**Issue by TacticalUniverse** [SlimeKnights/TinkersConstruct#3600]
https://gist.github.com/TacticalUniverse/f8d49ffe8e1563ace45e0f0ea38b7367

All I can provided is a link to the crash as I don't know what's causing the crash.

**Comment by KnightMiner** [comment]
Some mod adds a broken material which contains a null item stack, that is not valid according to Mojang. Hard to tell which one as it was just in a general material function, so try to reproduce with a smaller mod list.

**Comment by KnightMiner** [comment]
Closing for lack of response, some mod is adding a broken material, which is all the report tells us
