### ISSUE TITLE
We want to get the copyright

### ISSUE THREAD

**Issue by YingHua2** [SlimeKnights/TinkersConstruct#3603]
Hello, in order to let more people enjoy the fun of the Tinkers Construct, our team wants to transplant the Tinkers Construct to the inner_core on the mobilephones. Can we get the copyright for our team? In order to transplant better, we want to know  to deal with the textures of the parts of tools,thinks.

**Comment by Iorce** [comment]
The source code for TinkersConstruct is licensed under the MIT license as mentioned in the README.md on the main page.

It is free to use, distribute, modify... etc.

Including a copyright notice and the license should not be an issue.

**Comment by KnightMiner** [comment]
You are free to reference the code, but we ask not to use the name Tinkers Construct unless you all are us. You can call it something similar as long as you are clear you are not us, as people will send us issue reports if they see a mod called Tinkers Construct.

**Comment by bonii-xx** [comment]
As has been said, the code is licensed under MIT. The copyright for TiC stays with us, and as KnightMiner said, we will keep it java version exclusive.
