### ISSUE TITLE
Splitting Stacks doesn't Update Seared Furnace Smelting (1.12.2, 2.10.1.87)

### ISSUE THREAD

**Issue by SweetSugarSugar** [SlimeKnights/TinkersConstruct#3606]
Stack in top right cannot be smelted due to having the output higher than 16.
![2018-08-07_16 41 12](https://user-images.githubusercontent.com/14182009/43803163-11064e5a-9a66-11e8-9f49-d53e916ca9ee.png)

Splitting it will not update the first stack.
![2018-08-07_16 41 23](https://user-images.githubusercontent.com/14182009/43803164-11223f34-9a66-11e8-98ca-04f6594edd20.png)

**Comment by KnightMiner** [comment]
Because vanilla inventories are dumb. They need more proper hooks...

**Comment by bonii-xx** [comment]
Yup, sadly this can't be fixed on our side since it's a vanilla issue.
