### ISSUE TITLE
Tinkers Construct installed but not showing in game?

### ISSUE THREAD

**Issue by AllanRey1018** [SlimeKnights/TinkersConstruct#3608]
Hello, I'm currently using the FoolCraft 3 modpack on twitch, it doesn't have Tinkers in it so i added it myself, but when I search for it in my NEI it doesnt show up? Is there a config where its disabled? A mod compatibility issue or what? Here's the versions and addons I'm using, please help! I also added a screenshot of me searching the mod and only a few things showing up, not everything though! Thank you for your help!
![capture](https://user-images.githubusercontent.com/42266729/43948721-d3868d62-9c48-11e8-8598-9742e28ffd11.PNG)

TConstruct-1.12.2-2.10.1.87
tinker_io-1.12.2-release+2.6.1
Tinkers' Addons-1.12.1-1.0.7
TinkersComplement-1.12.2-0.2.3b
TinkerToolLeveling-1.12.2-1.0.5

**Comment by KnightMiner** [comment]
I have no idea what would cause this, but it's certainly nothing on our side. If it's a mod conflict it's one I've never seen.

Try enabling item hiding mode and see if the pack maker his tinkers stuff.

**Comment by TherminatorX** [comment]
Add Mantle

**Comment by KnightMiner** [comment]
Not having mantle would produce an error not only for Tinkers Construct but also for Tinkers Complement, plus would make some of the items shown on screen unable to load. Similarly, Tinkers Complement cannot load without Tinkers, depends on a lot of Tinkers stuff. It looks to me like a mod added blacklist of a mod ID

**Comment by KnightMiner** [comment]
Any update on this issue? Have you discovered what is hiding the items? As I said, nothing on our side hides them, so try getting a minimal mod list to reproduce

**Comment by KnightMiner** [comment]
Closing for lack of response.
