### ISSUE TITLE
Suggest: Processing Config

### ISSUE THREAD

**Issue by TheBox1** [SlimeKnights/TinkersConstruct#3609]
In the older versions, blocks created from the smeltery would be near enough instantaneous, taking only a moment to fully form/harden.

Changing to the new one, it seems rather tedious having to wait for the ore to not only pour but wait a long time for it to process.

Perhaps adding an option in the config file to change the amount of 'processing' time would be a good idea? For those who preferred the 'quick' way of doing things or those who wish to lengthen the time to prevent quick-gearing on servers.

**Comment by KnightMiner** [comment]
If you want to change the times, use CraftTweaker. There is no practicality to adding a config for every recipe. The old version did have processing time for the record, especially noticeable with blocks of iron.
