### ISSUE TITLE
Make blank casts re-smeltable!

### ISSUE THREAD

**Issue by SolSavvy** [SlimeKnights/TinkersConstruct#3613]
I tried making a large plate cast with 8 gold material and only ended up using 5 ingots and got three blank casts back and nothing to do with them. Cant re-smelt the to help finish making the hammer i was going to make. so just a waste of resources then.

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues?q=is%3Aissue+smelt+cast+is%3Aclosed
