### ISSUE TITLE
Provide separate flag to control rendering items on a crafting station vs casting tables/basins 

### ISSUE THREAD

**Issue by MatthiasMann** [SlimeKnights/TinkersConstruct#3614]
There are still some mods which have issues with rendering their items in world. To work around this I previously set B:renderInventoryInWorld=false. But now this also prevents rendering of casts in the casing tables or finished metal blocks in the basin.

A separate config switch for tables vs casting blocks would be really nice.

**Comment by bonii-xx** [comment]
Tables and casting tables use the same mechanics for rendering, it can't be deactivated selectively. As for some mods still having issues.. those mods are stuck in 1.7.10 times and need to finally update their stuff.
