### ISSUE TITLE
tinkers construct book doesn't load

### ISSUE THREAD

**Issue by pervysuhdude** [SlimeKnights/TinkersConstruct#3617]
i play hexxit in version 1.12.2

**If crashed, link to crash report (use a site such as pastebin):**

1.12.2
* Minecraft: hexxit
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

**Comment by rylm** [comment]
I have the same issue

**Comment by KnightMiner** [comment]
Duplicate of #3617
