### ISSUE TITLE
Suggestion: Don't disable the crafting table when tools are disabled

### ISSUE THREAD

**Issue by ChiefLogan3010** [SlimeKnights/TinkersConstruct#3619]
In a pack I am making I have the tools module disabled, however I would still like to have the tinkers crafting table, which it seems to have disabled. It makes sense to disable all the other tables with this config, as without tools there really is no use for them, whereas the crafting table has a lot of useful features that the vanilla one doesn't.

**Comment by bonii-xx** [comment]
Currently all the tables are the same block. Doing that would require splitting them up (which will happen in 1.13). Sooo.. in 1.13 ;)
