### ISSUE TITLE
Part chest don't work ??

### ISSUE THREAD

**Issue by N4TH4NOT** [SlimeKnights/TinkersConstruct#3620]
Minecraft: 1.12.2
Forge: 14.23.4.2752
Mantle: 1.3.2.24
Tinkers Construct: 2.10.1.87

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

When I try to put a pattern or cast in patern chest that don't work.
I search on Internet help for this issue but I don't found --' 
If it's a mistake of myself : What's is the utilitie of the partchest ??

Thak's,

A noob ^^'

**Comment by SweetSugarSugar** [comment]
Part Chests store parts... Pattern Chests store patterns... and can only store one type per chest (Pattern, Cast, or Clay Cast).

**Comment by N4TH4NOT** [comment]
"parts" it's that I use to make cast ??

**Comment by KnightMiner** [comment]
Parts are what you use to make casts, what you get from casts and patterns, and what you make tools from. Make sure you were using the pattern chest for your patterns and the part chest for your parts.

**Comment by N4TH4NOT** [comment]
thank's you very much ^^
