### ISSUE TITLE
Way to remove manual entries

### ISSUE THREAD

**Issue by Terrapin47** [SlimeKnights/TinkersConstruct#3621]
Hello, I'm working on an idea for a modpack that will use tinker's, but instead of utilizing the smeltery/seared furnace/tinker tank it will combine interactions from certain mods to melt/pour/mold tinker tool parts.  

However, even with the smeltery/etc controllers disabled, they are going to appear in the manual, which would be confusing for people.  Is there a way I can remove the entries?

**Comment by fuj1n** [comment]
You could modify the book in `assets/tconstruct/book`

You can remove pages by going into sections, then the section the required page belongs to, and then delete info about the page.

However the seared furnace has a section of its own, so to remove the seared furnace pages, you'd go into `assets/tconstruct/book/index.json`

And remove
```javascript
 {   
    "name": "seared_furnace",   
    "data": "sections/seared_furnace.json",   
    "icon": {   
      "item": {   
        "id": "tconstruct:seared_furnace_controller"   
      }   
    }   
  },   
```
