### ISSUE TITLE
[Server] Ghost item entity duplicate bug

### ISSUE THREAD

**Issue by Preta-Crowz** [SlimeKnights/TinkersConstruct#3624]
**Issue description:**
When user drops TiC Tools, then it duplicates to many entities. But only one entity is real item and others are not exist. Maybe issue #3615 has similar bug.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2707
* Mantle: 1.3.2.24
* Tinkers Construct: 2.10.1.84

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Used many mods and plugins. But it happens on TiC tools only.
I used many mods/plugins. [List](https://pastebin.com/UXrZY78X)

**Comment by bonii-xx** [comment]
Caused by one of the mods you're using, potentially also sponge. Isolate mod causing it and report to the corresponding mod author.

**Comment by Preta-Crowz** [comment]
Finally, I found the mod that causes this bug. It was Sponge Forge. Maybe TiC has problem on sponge compatibility.

**Comment by Preta-Crowz** [comment]
I'm using Sponge Forge 1.12.2-2705-7.1.0-BETA-3151 that uses SpongeAPI 7.1.0-SNAPSHOT-43d8496

**Comment by bonii-xx** [comment]
Thanks, closing this then.
