### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Chupp4-Jo3** [SlimeKnights/TinkersConstruct#3625]
I think this is something to do with RandomThings' Ender Bucket? (ln 63) or some fluid handling issue but I have no idea.

https://paste.dimdev.org/vulagecaqi.mccrash

Minecraft: 1.12.2
Forge: 14.23.4.2757
Mantle: 1.12-1.3.2.24
Tinkers Construct: 1.12.2-2.10.1.87

Let me know if you need more info

**Comment by Chupp4-Jo3** [comment]
I think it's [this](https://github.com/lumien231/Random-Things/issues/336) but would appreciate someone confiriming.

**Comment by bonii-xx** [comment]
Report to randomthings please, I don't know what their code does.
