### ISSUE TITLE
[REQUEST] Book's "appearance.json" should depend on the language

### ISSUE THREAD

**Issue by Allinxter** [SlimeKnights/TinkersConstruct#3626]
Pretty much title.

The file that dicts the text used in the cover of the book is a file called "appearance.json", found on .\assets\tconstruct\book. I think there should be a file for every language, since otherwise the cover will always stay on english regardless of the language set on the game config, as it is now.

**Comment by fuj1n** [comment]
It already does, languages can override appearance.json by placing it in their language root

For example:
`/book/ko_kr/appearance.json`
would overrule the one in `/book/appearance.json`

**Comment by fuj1n** [comment]
This works for any book resource, even the index
