### ISSUE TITLE
Cutlass

### ISSUE THREAD

**Issue by Spenny519** [SlimeKnights/TinkersConstruct#3630]
Could yoh possibly add back the cutlass for 1.12. I really miss that sword

**Comment by SweetSugarSugar** [comment]
Please read the FAQ before posting...

**Comment by KnightMiner** [comment]
Yes, we are aware there is a cutlass in 1.7. We know the 1.7 features pretty well. As stated on the FAQ, if its not ported, there is likely a reason, which may simply be time or needs more design considerations.
