### ISSUE TITLE
When "Force Unicode Font:" is set to "ON" Tinkers' construct "Materials and You" book breaks a little

### ISSUE THREAD

**Issue by Daniil1288** [SlimeKnights/TinkersConstruct#3635]
**Issue description:** 
If "Force Unicode Font:" is set to "ON" while the client's language is English the book appears a little wonky with text overlapping: 
![2018-09-02_17 26 55](https://user-images.githubusercontent.com/1404955/44957036-9f60fa00-aed5-11e8-92ef-8a881dab2f25.png)
This is also present when "Force Unicode Font:" is set to "ON" when the client's using a modified Better Unicode Resourcepack from [here](https://minecraft.curseforge.com/projects/minecraft-font-pc) and using a different language, here's how it looks like: 
![2018-09-02_17 25 19](https://user-images.githubusercontent.com/1404955/44956994-38434580-aed5-11e8-9902-ad2f4bf364bb.png)
And sometimes using the resourcepack from the link above causes this to happen: 
![2018-09-02_17 16 40](https://user-images.githubusercontent.com/1404955/44957091-80af3300-aed6-11e8-8650-8b0fd8685abe.png)
Looks like some botched PS2 translation :) 
**If crashed, link to crash report (use a site such as pastebin):** --

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2 - 14.23.4.2705
* Mantle: 1.12-1.3.2.24
* Tinkers Construct: 1.12.2-2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
--

**Comment by KnightMiner** [comment]
Does this happen without any resource packs loaded? And do you have any client side only mods that may affect graphics? (such as Optifine, that one unicode font mod, etc.)

**Comment by Daniil1288** [comment]
@KnightMiner, sorry for the late reply.
Yes, I do have OptiFine installed.
No resourcepacks enabled: 
![2018-09-08_17 20 06](https://user-images.githubusercontent.com/1404955/45255141-7cc65980-b38b-11e8-8d56-daa37484218a.png)
The text's still off.
And in English:
![2018-09-08_17 21 59](https://user-images.githubusercontent.com/1404955/45255160-ae3f2500-b38b-11e8-8f91-5c559ff578e6.png)
Also, I figured out that this
![2018-09-08_17 27 20](https://user-images.githubusercontent.com/1404955/45255245-708ecc00-b38c-11e8-83fc-3651438efaf0.png)
only happens after you enable the resourcepacks and after you restart the client this is how it looks like:
![2018-09-08_17 29 38](https://user-images.githubusercontent.com/1404955/45255278-c6637400-b38c-11e8-92cb-d3430910bad5.png)
The text's still off, obviously.

**Comment by KnightMiner** [comment]
Does this happen without Optifine? That is literally the point of the question you skipped above.

**Comment by KnightMiner** [comment]
Closing for lack of response, reproduce without Optifine if you think this is still an issue
