### ISSUE TITLE
Constantan alloy crash

### ISSUE THREAD

**Issue by CourtArtanis** [SlimeKnights/TinkersConstruct#3636]
Server crashes and world is corrupted after trying to alloy thermal foundation Nickel and Copper ores/ingots to make thermal foundation Constantan.
In the last crash I used thermal foundation Copper Ore blocks and Nickel Ingots.

Doesn't crash with other alloys, for example Bronze made with TF Ingots/ores.

Have to open world in MCedit and remove smeltery controller in order to enable the world to start again.

Crashreport: https://gist.github.com/CourtArtanis/3e969dd215843058838554838ab4b075

MC: 1.12.2
Forge: 2745
Mantle-1.12-1.3.2.24
TConstruct-1.12.2-2.10.1.87

**Comment by KnightMiner** [comment]
Looks like someone is either registering a broken constantan recipe or breaking your current one. Try and reproduuce with a minimal mod set like the issue template told you to do.

**Comment by CourtArtanis** [comment]
Basemetals would appear to be the cause.
