### ISSUE TITLE
Piggybackpack mob suffocation in ceiling made the piggybackpack not work anymore

### ISSUE THREAD

**Issue by turtleisaac** [SlimeKnights/TinkersConstruct#3637]
Had chicken on, it suffocated in ceiling. Piggybackpack no longer works, cant pick up new mobs with it

**Comment by KnightMiner** [comment]
Did you take the piggybackpack off your back before trying to pick up another mob?

**Comment by turtleisaac** [comment]
yes

**Comment by KnightMiner** [comment]
I cannot reproduce this in the latest version, and since this issue is pretty old I'm closing this.
