### ISSUE TITLE
Tinkers' Construct Issue Report

### ISSUE THREAD

**Issue by imaidenB666** [SlimeKnights/TinkersConstruct#3638]
It says: You must include the right dependencies for Tinkers' Construct: Requires mantle 1.12-1.3.1 or above (missing)

**Pastebin: https://pastebin.com/4rQKhNQf**

**[crash-2018-09-03_07.22.27-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2346631/crash-2018-09-03_07.22.27-client.txt)
**

**Probably can be reproduced with just Tinkers' Construct.**

**Comment by KnightMiner** [comment]
Yes, that is because Tinker Construct requires mantle 1.12-1.3.1 or above, and you do not have it. The error message is way more than clear.

**Comment by imaidenB666** [comment]
I don't understand what mantle 1.12-1.3.1 is.

**Comment by KnightMiner** [comment]
[Mantle](https://minecraft.curseforge.com/projects/mantle) is the mod we link on the Tinkers Construct download page itself. [Google is your friend](http://lmgtfy.com/?q=mantle+1.12-1.3.1)
