### ISSUE TITLE
Master branch missing commit(s)?

### ISSUE THREAD

**Issue by panoskj** [SlimeKnights/TinkersConstruct#3640]
According to https://github.com/SlimeKnights/TinkersConstruct/issues/3533#issuecomment-396426749 tconstruct.tools.ToolClientEvents.replaceTableModel has been updated but I can't find any changes in this repository. Am I missing something? As a result, compiling and using master branch will crash with construct's armory v1.1.0.

**Comment by fuj1n** [comment]
If I understand right, most of the changes happen outside the master branch in a version specific branch.
Here's the commit you're looking for: 6a7bb6da7e

**Comment by panoskj** [comment]
Thanks!
