### ISSUE TITLE
Issue when including NuclearCraft

### ISSUE THREAD

**Issue by DefenderofTheTimelines** [SlimeKnights/TinkersConstruct#3641]
I have only Tinkers Construct, Mantle, and NuclearCraft in the mods folder, and if either Tinkers(and Mantle) or NuclearCraft are removed, the game loads perfectly fine. With both mods in folder game crashes almost immediaetely, and never makes it to the main menu screen.

Crash report:
https://gist.github.com/DefenderofTheTimelines/36cd1e8c36867b67aadada930f40a321

Mod List:
   Mantle
   Tinkers Construct
   NuclearCraft

Versions:
   Minecraft: 1.12.2
   Forge: 14.23.4.2759
   Mantle: 1.3.2.24
   Tinkers Construct: 2.10.1.87
   NuclearCraft: 2.11c

Error:
java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo

**Comment by KnightMiner** [comment]
This is on NuclearCraft's side, they are using classes from our API without declaring `after:tconstruct` in their dependencies, which does funny things to the classloader. [Report to them](https://github.com/turbodiesel4598/NuclearCraft/issues).

**Comment by turbodiesel4598** [comment]
Ah, ok - thanks for the heads up!

**Comment by bonii-xx** [comment]
Fixed on their side.
