### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by Colton-Slayden** [SlimeKnights/TinkersConstruct#3642]
**Issue description:**
# If true all variants of the different tables will be listed in creative. Set to false to only have the oak variant for all tables.
    B:listAllTables=false

    # If true all material variants of the different parts, tools,... will be listed in creative. Set to false to only have the first found material for all items (usually wood).
    B:listAllMaterials=false

currently have those both set to false but when playing you are still able to make other variants of part builder and ect

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2760
* Mantle: 1.3.2.24
* Tinkers Construct: 2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

**Comment by KnightMiner** [comment]
Please explain your issue further. Those config options only control what you see in creative, not whether they can be crafted. I am not even sure why you would want to disable crafting of them.

**Comment by Colton-Slayden** [comment]
I guess i understand the config wrong. I thought there used to be a way to only have the default oak variant be crafted from all types of wood.

**Comment by KnightMiner** [comment]
That was the only option in 1.7. when the feature was added no toggle was added
