### ISSUE TITLE
Mining level names aren't changed by language

### ISSUE THREAD

**Issue by Goldenlion5648** [SlimeKnights/TinkersConstruct#3643]
**Issue description:**
The word after the text "Mining Level:" does not change with the language, even when defined in the language file. So the names "Iron", "Obsidian", "Diamond", and "Cobalt" cannot be changed. 
Here I am using the upside down text, and only the mining levels are not changed
![Screenshot](https://user-images.githubusercontent.com/32916571/45437976-ebedc780-b683-11e8-90cf-bb177db6e740.png)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2747
* Mantle: Mantle-1.12-1.3.2.24
* Tinkers Construct: TConstruct-1.12.2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Just tinkers

**Comment by SweetSugarSugar** [comment]
I don't think that's handled by Tinkers'...

**Comment by Goldenlion5648** [comment]
There is an entry in the language file for each of the mining levels, it's just not being used by the game for some reason.

**Comment by laz2727** [comment]
Can't confirm:
![lang test](https://user-images.githubusercontent.com/2369751/45491469-4e64c780-b759-11e8-8799-b8622ac26d42.png)
Yes, TiC's lang handlers' state is... bad, but they work with a restart.

**Comment by Goldenlion5648** [comment]
where did you put the lang file? can you share it?

**Comment by Goldenlion5648** [comment]
Thanks, before I was trying to use resource loader, but I had an assets folder before the tconstruct folder.
