### ISSUE TITLE
[1.12.2] Every fuel is lava.

### ISSUE THREAD

**Issue by NickelHub** [SlimeKnights/TinkersConstruct#3648]
I tried to add different fuels to the smeltery, but it only displays lava with 1300 degree. But I need even more. I added liquid dilithium and blazing pyrotheum. 
![2018-09-23_02 01 45](https://user-images.githubusercontent.com/26455012/45922849-47675300-bed7-11e8-8799-2466b32f3b6a.png)
![2018-09-23_02 01 48](https://user-images.githubusercontent.com/26455012/45922852-5221e800-bed7-11e8-81af-a57d9ec0bb99.png)

**Versions:**
* Minecraft: 1.12.2
* Forge: 2755
*1.12.2-2.10.1.87
* Mantle-1.12-1.3.2.2
 taiga-1.3.2
ThermalFoundation-1.12.2-2.5.0.19
CoFHCore-1.12.2-4.5.3.20
RedstoneFlux-1.12-2.0.2.3
CoFHWorld-1.12.2-1.2.0.5
--

**Comment by KnightMiner** [comment]
Did you try actually smelting an item? It either has not updated for the new fuel yet or just has a bit of the old one left over

**Comment by NickelHub** [comment]
Yes, but it smells everything like lava. For some things it says not enough temperature, but the fuels should have enough heat.

**Comment by KnightMiner** [comment]
Does this happen with a new smeltery? Just so we can rule out the old fuel still existing

**Comment by KnightMiner** [comment]
I mean literally make a new smeltery from scratch. Just removing the tanks stilligjt leave about 50mb in the controller itself of lava

**Comment by NickelHub** [comment]
Yeah, that worked. But does this mean you cannot have different types of fuel in a smeltery?


![2018-09-25_13 43 44](https://user-images.githubusercontent.com/26455012/46012298-10f12a00-c0c9-11e8-88c6-8d57c6fec3e0.png)

**Comment by KnightMiner** [comment]
This means what I said above, when switching fuel types you need to use up the old fuel first. If you go into the old smeltery and smelt a few items that don't need pyrothium, you should find it kicks in.
