### ISSUE TITLE
Game Crash Using Tool Forge

### ISSUE THREAD

**Issue by xthedemoncatx** [SlimeKnights/TinkersConstruct#3650]
When I try to use the Tool Forge crafting station to create anything, the game freezes for a moment and crashes when I try to take the finished tool out of the forge. Regardless if I try to rename it or not. I have only tested this on the Shuriken tool item so far, as I tend to use those the most in the game. I'll update as I test out which mods are conflicting.

Edit: It appears to be MoreCraft. I'll detail it below.

https://docs.google.com/document/d/1hcLeDjzyn-tK3QvrZHHQMzxcUGpuaZtVXYO3LbMH1Eg/edit?usp=sharing I hope Google Docs is permittable.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2759
* Mantle: 1.3.2.24
* Tinkers Construct: 2.10.1.87

Other Mods seem required, but I can't pick out which one yet. I can add a list of what I have if you wish as I'm testing this out.

Edit: Using MoreCraft-1.12.2-1.3.2b1 is the conflicting mod breaking removing forged tools from the Tool Forge.

**Comment by xthedemoncatx** [comment]
I have to hunt their CurseForge page down again, but I'm gonna.

**Comment by Kitteh6660** [comment]
I'll look into the issue with my mod and hopefully to get a fix out soon!
