### ISSUE TITLE
z-fighting

### ISSUE THREAD

**Issue by n77y** [SlimeKnights/TinkersConstruct#3652]
**Its just a graphical glitch but annoying all the same so pluz fix. Also I have noticed that prismarine tools seem to mine faster then their obsidian counterparts even though there is no rain and i'm not in water:**
* Prismarine mining speed: 5.5
* Obsidian mining speed: 7.07
![giphy](https://user-images.githubusercontent.com/43690021/46240233-1a90c100-c359-11e8-8cac-0f51ba6c8e3c.gif)
**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.4.2759
* Mantle: Mantle-1.12-1.3.2.24
* Tinkers Construct: TConstruct-1.12.2-2.10.1.87

**Can be reproduced with just Tinkers Construct and with additional mods**

**Comment by bonii-xx** [comment]
Yes, this always happens when you have overlapping pixels that are viewed at an angle. The only way to fix it is to not have any overlapping pixels, which is not feasible for our models that are layered.
You'll always have z-fighting, just the distance and angle required for it to occur varies.
