### ISSUE TITLE
Minecraft Crashed Tinkers Construct

### ISSUE THREAD

**Issue by COPIADEMESSI** [SlimeKnights/TinkersConstruct#3653]
game crashes when i try to add something to my tool in the tool station, PLZ HELP ME

crash report: https://pastebin.com/3hbMksrf

**Comment by TheQuadShot** [comment]
Your crashing in Iguanas Tinker Tweaks(iguanatweakstconstruct), not Tinkers Construct.

**Comment by KnightMiner** [comment]
Yep, this looks to be caused by Iguanas or NEI. In any case, we have not supported 1.7.10 for years.
