### ISSUE TITLE
Random tinker tank render crash

### ISSUE THREAD

**Issue by SynexWolf** [SlimeKnights/TinkersConstruct#3654]
The tinker tanks causes random render crash at times.
https://pastebin.com/bmDXMEWb

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2749
* Mantle: 1.12-1.3.2.24 
* Tinkers Construct: 1.12.2-2.10.1.87 
Not sure what causes it, the tinker tank has fluids in it, it might have some modded fluids. The tank crashes the game randomly. Sorry can't give any actual information on how and why it crashes as it just seems to crash at random times when the tank is in render distance.

**Comment by KnightMiner** [comment]
Are there any other tile entities in the render distance? This crash looks like someone started the buffer builder but never rendered what they started, so there is a chance another mod's block is to blame.

**Comment by SynexWolf** [comment]
Yes, a lot of machines and modded storage are nearby, is there a way to find out what caused it? or possibly make an exception so if won't cause an IllegalStateException? Sorry, if it's a dumb question I don't have much knowledge with modding and coding.

**Comment by KnightMiner** [comment]
Do the thing I said in my edit, apparently CodeChickenLib added a render exception catch which can sometimes lead to exceptions like this.

**Comment by KnightMiner** [comment]
Closing for lack of response, if the issue is still happening and you respond with the requested information we can look into this more
