### ISSUE TITLE
[Crush]After open Tools Station

### ISSUE THREAD

**Issue by Rumaruka** [SlimeKnights/TinkersConstruct#3655]
**Issue description:**

https://pastebin.com/HA1avRUM
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2707
* Mantle: 1.12-1.3.2.24 
* Tinkers Construct: 1.12.2-2.10.1.87
Only mods "SlimeKnights"

**Comment by bonii-xx** [comment]
That is really weird. Looks like it's drawing the GUI before it's initialized. Is that reproducable?

**Comment by bonii-xx** [comment]
Does it happen with newer forge versions? For example 2760?

**Comment by Rumaruka** [comment]
Use forge 2768, but still crush

**Comment by bonii-xx** [comment]
As far as I can tell this is not reproducable, however I've put a workaround the specific part where it crashes.. it might help. I suspect it's got something to do with specific setup.

**Comment by bonii-xx** [comment]
Well, I still couldn't reproduce it myself, but you can try the beta now ;)
