### ISSUE TITLE
BASE METALS ISSUE< ADAMANTINE being smelted as ADAMANT, two different metals..no crash

### ISSUE THREAD

**Issue by StarboundModderRWC** [SlimeKnights/TinkersConstruct#3658]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

**Comment by KnightMiner** [comment]
We don't add recipes for base metals, and any recipes we do add are based on ordict names (so it would come from a bug in their oredict names. I suggest you report this to base metals.

**Comment by bonii-xx** [comment]
Base metals issue -> report to base metals. You even put it into the title. ;P
