### ISSUE TITLE
Add a config option for Tinkers' tools under the mining level to still break the block

### ISSUE THREAD

**Issue by CrankySupertoon01** [SlimeKnights/TinkersConstruct#3659]
I am a modpack developer for Rebirth 3. It adds meteors which is a key part. They can only be broken with iron + level tools. But can be broken open with a lower level without getting the block. Vanilla tools can do that just fine. Tinkers tools simply wont. 

I see your mod is playing smart, but its kind of breaking my pack.
Care adding a config option to disable the smartness, since i couldnt find one. 

Thanks

**Comment by KnightMiner** [comment]
"playing smart", can you elaborate on that one?

**Comment by CrankySupertoon01** [comment]
The mod is not letting you mine the block so it doesnt break it. The fact is that i want the block to be mined.

And dont say change the harvestibility level, because the point is i dont want them veinmining them

**Comment by KnightMiner** [comment]
Last I checked we do the same thing vanilla tools do: we add a tool class to say what the tool can break, and have a check if it's effective to break it faster.

**Comment by CrankySupertoon01** [comment]
Yes i get that, but whenever i try to lets say mine obsidian with a stone pick, it would work with vanilla ones,  but tinkers is being smart and not letting me even try to mine it

**Comment by KnightMiner** [comment]
Wait, are you saying Tinkers pickaxes give no speed boost if the block is not minable, but vanilla tools still give a small boost for unminable blocks? Because it was not clear when you phrased it as the tools being "smart", and minable refers to whether it drops (breaking speed would have been better to say).

If that is the case, it does not sound intentional, but you would have to double check with @bonii-xx on that one as he wrote the original code in 1.8.

**Comment by CrankySupertoon01** [comment]
@KnightMiner I think thats what your saying. If the block is not mining, tinkers will simply refuse to try to break it. vanilla and any other mod will break it but not give you the item

**Comment by bonii-xx** [comment]
Looks like it has always been this way, but nobody ever noticed.

**Comment by KnightMiner** [comment]
Whenever the next release is; it's not a priority fix, but we have not had a build in a while.

**Comment by bonii-xx** [comment]
We'll probably get a release soonish. We also got a bugfix now.
