### ISSUE TITLE
Config for only showing one Table misleading.

### ISSUE THREAD

**Issue by Darkere** [SlimeKnights/TinkersConstruct#3660]
**Issue description:**
The config:
`  If true all variants of the different tables will be listed in creative. Set to false to only have the oak variant for all tables.`
Doesn't show the oak version but the first of the list.
This is a problem because when enderIO is installed the first item of the list for the tool forge is electrical steel. Many players are mistakenly assuming that packmakers are changing the recipe to require electrical steel. 

A solution would be to force the Iron tool forge to appear unless it was disabled. 
The same issue appears with the wooden tables although players here assume from experience that all types of wood will work.

**Versions:**
* Minecraft: 1.12.2
* Forge: 2760
* Mantle: 1.3.2.24
* Tinkers Construct: 2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Also requires enderIO, JEI

**Comment by bonii-xx** [comment]
Yeah, it should say "the first variant" instead, since the tool station doesn't even have an oak variant. I actually wanted it to be a single slot rotating through all the different variants.

**Comment by KnightMiner** [comment]
Perhaps we need a method on the item to set the default variant? Lets us set it to iron for the tool forge and oak for the table

**Comment by KnightMiner** [comment]
In 1.16, you can control the first variant as its the first entry in the tag, easy for datapacks to change. Not easy to change in 1.12, but this is a change that would break modpacks to try to change.

Adding to the milestone as a reminder to change the config text if another build is made

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support.
