### ISSUE TITLE
Insufficient info about the mod at Curseforge

### ISSUE THREAD

**Issue by djdanby** [SlimeKnights/TinkersConstruct#3662]
No word about it in the description that you need Mantle so that the mod works at all. I found it only by chance at Google. Would be nice if this information in the description of the mod lands, so that not others get the problem.^^
On the server you only get the following message when starting: 

Missing Mods: unknown: need [1.12-1.3.1,): have missing

Nobody can do anything with this ^^

**Comment by VT-14** [comment]
Curseforge has a dedicated dependency page for every mod.  It's under the "Relations" tab.

https://minecraft.curseforge.com/projects/tinkers-construct/relations/dependencies

**Comment by KnightMiner** [comment]
Yep, the dependencies tab is the place to see mantle is required. The in game error is a forge bug which updating Forge should fix (it will then properly show mantle is missing)

**Comment by bonii-xx** [comment]
It still should be at the top of the description.. I actually wondered about that because I just got mad at EIO for not having it there. I was under the impression that we had that.
