### ISSUE TITLE
Manual Book Materials and You incorrectly layered

### ISSUE THREAD

**Issue by Robijnvogel** [SlimeKnights/TinkersConstruct#3663]
**Issue description:**
I think that this picture speaks a thousand words:
![mc tinkers book](https://i.imgur.com/TqdHPEX.png)
1. As you can see, the text that is written on the page is layered over the tooltip box and text. It may only be apparent for the coloured text, but that's only because the black colour of the other text has this weird property that it is _dark_. :P
~~2. Besides this, the text flows out of the tooltip box, but that is probably an Optifine issue.~~

This issue may be related to #3635.

**Manually triggered crash report:**
https://paste.dimdev.org/pemajewoso.rb

**Versions:**
* Minecraft: 1.12.2
* Forge: 2765
* Mantle: 1.3.2.24
* Tinkers Construct: 2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
It can be reproduced with just TiC and Mantle.

**Comment by bonii-xx** [comment]
Yeah, we know, we've had that for a while, but it's not trivial to fix currently since all text is rendered at the same time.

**Comment by Robijnvogel** [comment]
I've seen this not only happen with text. I've seen tooltip boxes from the left page completely slide "under" the background of the right page and there were some armour parts (conarmour) that were rendered overtop the tooltip boxes as well.
This was when I still had Optifine and many other mods installed, though, so I am not certain that those had the same cause.

But good to know that you know. I couldn't find it in the issues, but I may have overlooked something. :)

**Comment by bonii-xx** [comment]
It looks like fujin actually fixed the underlying core problem in Mantle, we just haven't released that yet. So next TiC & Mantle version will have it fixed.

**Comment by Robijnvogel** [comment]
Thank you very much!

**Comment by bonii-xx** [comment]
I didn't do anything, @fuj1n did all the work.
