### ISSUE TITLE
Crafting Table Issue with Adjacent Simple Generators

### ISSUE THREAD

**Issue by Muddr** [SlimeKnights/TinkersConstruct#3667]
**Issue description:**
Crafting Table GUI won't open when right clicked if adjacent to a generator from Simple Generators. Throws a NullPointerException in console. I'm assuming it has something to do with reading it's inventory. Not sure if this issue would be on TC or SG.

**If crashed, link to crash report (use a site such as pastebin):**
[log_of_issue.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2508520/log_of_issue.txt) (Too large for pastebin?!?)

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2760
* Mantle: 1.3.3.39
* Tinkers Construct: 1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

Simple Generators version 2.0.17.1

Picture of block layout to reproduce. 
![2018-10-23_20 20 58](https://user-images.githubusercontent.com/1361860/47398235-2de93f00-d701-11e8-9dc9-7512d41e9ddf.png)

Picture of installed mods for issue testing.
![issue_installed_mods](https://user-images.githubusercontent.com/1361860/47398279-6be66300-d701-11e8-98ab-1dde05123e46.png)

**Comment by KnightMiner** [comment]
```
Caused by: java.lang.NullPointerException
	at com.valkyrieofnight.sg.m_generators.tile.TileGenBase.hasCapability(TileGenBase.java:113)
```
Looks like they are throwing a NPE when attempting to get the capability. Without looking at their code, my best guess is they are not treating the side as nullable (which it is). This issue is on Simple Generator's side.

**Comment by KnightMiner** [comment]
Closing as fixed in the other mod
