### ISSUE TITLE
slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Trying to register a modifier with the name auto-repair but it already is registered

### ISSUE THREAD

**Issue by comfuzzled** [SlimeKnights/TinkersConstruct#3668]
when i boot my modpack, it sends this error.:
slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Trying to register a modifier with the name auto-repair but it already is registered

https://pastebin.com/hmMUqgrF

**Versions:**
* Minecraft-1.12
* Forge-1.12-14.21.1.2443
* Mantle-1.12-1.3.2.24
* Tinkers Construct1.12-2.8.1.49

I have the following mods:
[modlist.zip](https://github.com/SlimeKnights/TinkersConstruct/files/2508619/modlist.zip)

**Comment by Lutor27** [comment]
Looks like Moar Tinkers mod and Tinker's Addon may be causing the crash, from what I can see in the crash log.

**Comment by bonii-xx** [comment]
Yup. You have two mods of which both add a modifier with the id `auto-repair`. Id's are unique. You can't use both mods at the same time like that.

**Comment by comfuzzled** [comment]
Thank you.
