### ISSUE TITLE
You can open locked Thermal Expansion strongboxes by putting a crafting station next to it.

### ISSUE THREAD

**Issue by Gladuin** [SlimeKnights/TinkersConstruct#3671]
**Issue description:**
You can open locked Thermal Expansion strongboxes by putting a crafting station next to it.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.2.24
* Tinkers Construct: 2.10.1.87
* Thermal expansion: 5.5.2.39

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
You need thermal expansion and it's dependencies

**Steps to reproduce**
1. Get a strongbox
2. Put a signalum security lock on it
3. Set the lock to Owner Only
4. Put a crafting station next to it
5. Open the crafting station (or let someone else do it)
6. Congrats, you now have access to someone elses strongbox

![2018-10-28_10 16 37](https://user-images.githubusercontent.com/34450360/47614116-bc134b80-da9a-11e8-8b27-e211a6280a0a.png)

**Comment by KnightMiner** [comment]
Can you actually remove the items and place items in, or just see them?

And what about hoppers? We call very similar code to most item pipes.

**Comment by Gladuin** [comment]
You have full access to the chest, I need to test hoppers but it'd most likely work

**Comment by KnightMiner** [comment]
Does the same thing happen if you use a vanilla hopper? Crafting stations use the same code as hoppers to determine if you can insert or extract an item

**Comment by KnightMiner** [comment]
Closing for lack of response, it sounds like TE's locked strongboxes are not locked for pipes, so this is likely intended. If not, you can always blacklist them in the config.

**Comment by ProfessorCool** [comment]
I am posting here to confirm that you can neither input nor output, either with pipes or hoppers, into a locked strongbox. However, a crafting station still bypasses the security measures.
