### ISSUE TITLE
source code for 1.7.10 doesnt have the Mantle api

### ISSUE THREAD

**Issue by Samuel1099** [SlimeKnights/TinkersConstruct#3672]
**Issue description:**
Im trying to edit the 1.7.10 version of TConstruct so i can make the infiniTools craftable but when i load the project into eclipse, I get an error when trying to import Mantle.  Looking through the API folder, I cant find the Mantle API.  I can't find it online either.

**Comment by KnightMiner** [comment]
Have you tried looking at the Mantle repository? Though it's easier to just use gradle to pull it from maven (use the command `gradlew setupDecompWorkspace`

**Comment by Samuel1099** [comment]
how would i go about doing that

**Comment by KnightMiner** [comment]
Open command prompt in the folder containing the cloned repository and run the command. If you are unsure how to do that, you should look into Forge modding tutorials as that is the same for any mod (need to know the basics before doing the complex stuff)
