### ISSUE TITLE
Lumberaxe should work on giant mushrooms

### ISSUE THREAD

**Issue by OfMCMXXXVII** [SlimeKnights/TinkersConstruct#3674]
Lumberaxes should work on giant mushrooms

**Comment by bonii-xx** [comment]
Possibly, but we have no priority on it. Maybe sometime.

**Comment by KnightMiner** [comment]
Lumber axes in 1.16 work on mushrooms with the fallback, but will not fell whole mushrooms as they violate so many assumptions about tree trunks to the point is probably not worth it. Going to close this, but I'll add a note to consider more targeted mushroom felling
