### ISSUE TITLE
Overfull Smeltery causing excessive lag

### ISSUE THREAD

**Issue by Yamza** [SlimeKnights/TinkersConstruct#3675]
## Issue description:
Over filling a smeltery causes quite severe lag.
https://i.imgur.com/rjio94e.png
https://i.imgur.com/0YRPQiT.png
Profile taken during this event: https://sparkprofiler.github.io/?cTNMDRvoRL
Screenshot of the line in question: https://i.imgur.com/jYsJd9c.png

The lag caused by this _is_ directly related to the Smeltery size. 

## Versions:
Modpack: ATM3 - Remix 1.0.0
Minecraft: 1.12.2
Forge: 14.23.5.2768

Mantle: 1.12-1.3.3.39
TConstruct: 1.12.2-2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Will update after checking.

**Comment by bonii-xx** [comment]
Yes, because it has to check the recipe for melting for each block, to check if it can put it into the tank. Since it never changes, it has to do that very ofter. Same as any crafting table. Probably not worth optimizing further since you need quite a lot smeltery slots trying to do that to become noticable.

**Comment by Yamza** [comment]
Fair enough.

**Comment by KnightMiner** [comment]
I pushed a commit that will fix this for the case of an overfull smeltery. Still need to think about whether we want to handle the case of a nearly full smeltery though.

One thing we could do is cache the recipe amount for each slot, then check if the recipe amount + current amount > capacity. That might be a bit much for how rare of a case this is, any opinion on that @bonii-xx ?

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. 1.16 has some per slot recipe caches that should prevent this from being an issue
