### ISSUE TITLE
Savegame ID?

### ISSUE THREAD

**Issue by sfxworks** [SlimeKnights/TinkersConstruct#3676]
I would like to know the savegame ID. We have a map that has spawned over 190,000 slimes... so we are using bad-mobs to temp ban this.

https://forums.spongepowered.org/t/whats-the-best-way-to-handle-lapitos-galacticrafts-official-servers-lag-spikes/26008

**Comment by KnightMiner** [comment]
Are you wanting the mobs string ID? That is `tconstruct:blueslime`. Guessing could have gotten you an answer quicker, or testing in a creative world with summon.

**Comment by sfxworks** [comment]
Thanks @KnightMiner 
@bonii-xx I am willing to give a copy of my server for research but turning on sponge's logs and sifting through entity logs is too much for me at this time.  It would also put a strain on our current player base.

**Comment by KnightMiner** [comment]
Since there is not a clear issue here, I am closing this. Feel free to comment if you have a specific bug though
