### ISSUE TITLE
Slime islands replacing terrain with air

### ISSUE THREAD

**Issue by Jdewi12** [SlimeKnights/TinkersConstruct#3677]
Slime islands replace nearby terrain with air. Specifically I ran into this issue when generating a customized type world where terrain often got close to the height limit. Empty blocks within the bounding box of the slime islands are replaced by air. Here is a screenshot of the issue:
![image](https://user-images.githubusercontent.com/25410318/48000959-cd232300-e152-11e8-889b-7e7317ff9fb5.png)

It's pretty minor, but I think this behaviour should be changed so air doesn't overwrite the terrain for cases like above, if it's not too hard. I know nothing about modding but I'm guessing maybe this can be done using structure void like how vanilla structure blocks work.

Versions:
Minecraft: 1.12.2
Forge: 1.12.2-14.23.4.2758
Mantle: 1.12-1.3.2.24
Tinkers Construct: 1.12.2-2.10.1.87

**Comment by Jdewi12** [comment]
Is this normal? Don't think I've seen this before with normal terrain: ![image](https://user-images.githubusercontent.com/25410318/48066022-21440b00-e218-11e8-8707-7557edbed256.png)

**Comment by bonii-xx** [comment]
Hehe, yes that can happen when the upper limit where we generate slime islands is reached. Fun stuff.

**Comment by KnightMiner** [comment]
Could we possibly use the vanilla "sturcture void" to prevent some of this? Not sure how much of our code uses the new structure stuff

**Comment by bonii-xx** [comment]
None of it, that code is 1.8. ;)

**Comment by KnightMiner** [comment]
Fixed in 1.16, no plans to rewrite our worldgen logic in 1.12 to fix this.
