### ISSUE TITLE
minetweaker3 zenscript tutorials outdated where to look

### ISSUE THREAD

**Issue by raziel23x** [SlimeKnights/TinkersConstruct#3679]
I gone to http://minetweaker3.powerofbytes.com/wiki/ModTweaker:TConstruct_Support

and i cant get any of this to work i did look at other mods and saw that they are using different methods IE 

//InputStack, OutputFluid, TemperatureAmount, BlockRender

mods.tconstruct.Smeltery.addMelting(<minecraft:porkchop>, <liquid:blood> * 200, 200, <TConstruct:MeatBlock>);

but this actually works 

mods.tconstruct.Melting.addRecipe(<liquid:dirt> * 648, <extrautils2:compresseddirt>, 200);

is there a place for all the minetweaker commands to better customize scripts

**Comment by KnightMiner** [comment]
Use the [crafttweaker main docs](https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/TConstruct/Commands/). We actually don't handle that anyways, it's modtweaker that adds support.
