### ISSUE TITLE
Update IMC on the wiki

### ISSUE THREAD

**Issue by OtisGoodman** [SlimeKnights/TinkersConstruct#3680]
Can you please update what needs to be inputted for the inmc on the wiki, #

**Comment by OtisGoodman** [comment]
It has not been updated In a wile and the method for sending a IMC packet is outdated.

**Comment by KnightMiner** [comment]
Explain how you know it's outdated

**Comment by OtisGoodman** [comment]
The Imc method is not supported in the current version of forge.

**Comment by KnightMiner** [comment]
I am closing this for lack of detail, as I've tested the code we have on the wiki and it fully works.
