### ISSUE TITLE
AchievementEvents causing server lag.

### ISSUE THREAD

**Issue by Slayer5934** [SlimeKnights/TinkersConstruct#3682]
**Issue description: AchievementEvents is causing massive lag on the server.**
![capture](https://user-images.githubusercontent.com/20819543/48426261-698d8c80-e734-11e8-9fa6-d4e2c407fbf7.PNG)
https://timings.aikar.co/?id=9cb913d32a1e4cf7ab0362a4517e72df

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2768
* SpongeForge: 2768-7.1.5-RC3506
* Mantle: 1.12-1.3.3.39
* Tinkers Construct: 1.12.2-2.10.1.87

**Comment by Slayer5934** [comment]
If theres anything I can do to research the issue further let me know.

**Comment by KnightMiner** [comment]
Does this happen on a normal Forge server, without Sponge? In any case, looks like you are damaging a ton of entities which could definitely lead to lag. I'm not sure what can be done to reduce the impact of the events but it should be small unless it's excessive amounts of mobs being damaged.

**Comment by Slayer5934** [comment]
So your saying the likely cause is someone on the server spam killing mobs? What about the onCraft event, whats that connected to? Any Idk if it happens on a server without sponge, I doubt it does, no real way to test that on a local server without a playerbase..

**Comment by bonii-xx** [comment]
Probably somebody autocrafting. Might be the crafting could use a check if it's only in our blocks, looks like that's missing. Either way, the logic there doesn't do anything complicated and is hardly noteworthy compared to the rest.
The damage entity code is even simpler than the crafting one, it just seems to be called a lot. As is there's nothing we can do without knowing what's causing it, and if it's even an issue in our mod.

**Comment by Slayer5934** [comment]
Right, you can close this issue and Ill reopen or comment back if theres any more info gathered.

**Comment by bonii-xx** [comment]
First I'd like to check if we can stop processing earlier - but I don't think we have the kind of info needed for that in the event itself.

**Comment by bonii-xx** [comment]
Does the issue still exist, and can you put a custom tic version onto the server? I'd like to see if there's any noticeable difference if I explicitly stop earlier if it's a fake player. I assume most of the calls (if not all) come from fake players.

**Comment by Slayer5934** [comment]
Sadly the server owner hasnt had the time to test again, but hes not complaining so maybe not? Sorry for not being more helpful..

**Comment by bonii-xx** [comment]
Okay, no worries, as we sad everything points to some extreme circumstances. I just was curious if the possible changes would even have a noticeable impact.
