### ISSUE TITLE
Jump When right-click with long-sword doesnN't work with shield...

### ISSUE THREAD

**Issue by Fireztonez** [SlimeKnights/TinkersConstruct#3683]
Hello, I made a sword with a Longsword made with an Manyullyn Sword Blade, and I try to kill somes enemies how is really really hard to kill without shield, so I have my shield in my second hand... But when I right click for get the shield protection, it doesn't work, and when I release the click I jump forward directly in face of my enemy!!

I think you should disable that effect when you have a shield in the second hand, because this is really annoying, and I have now to change my sword blade because of that...

Take note, I try with both, Spartan Sield and Vanilla Shield, and both doesn't work...

If needed, I can send you more information, give you a list of mods I have in my modpack or tests somes things for you...

* Minecraft: 1.12.2
* Forge: 14.23.5.2772
* Mantle: 1.3.3.39
* Tinkers Construct: 2.11.0.106

Same issue with only tinker...

Fireztonez

**Comment by bonii-xx** [comment]
Broadsword is for offhand usage. Weapons with right-click effects are for usage without shields. If you want to use a shield you need to use a broadsword.
