### ISSUE TITLE
Illagers should also produce liquid emerald when being melted down in the smeltery

### ISSUE THREAD

**Issue by mser7** [SlimeKnights/TinkersConstruct#3684]
**Issue description:**
Illagers are an accountant of villagers, they even drop emerald when killed, so they should become emerald when melted
There are three Illager types:Vindicator, Evoker and Illusioner.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* Mantle: Mantle-1.12-1.3.3.39
* Tinkers Construct: TConstruct-1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Only Tinkers is needed

**Comment by bonii-xx** [comment]
Yeah, those didn't exist back then. Simply haven't been added yet.

**Comment by mser7** [comment]
Will this be implemented in the next release?

**Comment by bonii-xx** [comment]
If we don't forget it, yes. Pinging @KnightMiner for safety
