### ISSUE TITLE
Primitive mobs villager mobs doesn't produce liquid emerald when smelted

### ISSUE THREAD

**Issue by mser7** [SlimeKnights/TinkersConstruct#3685]
**Issue description:**
Primitive mobs have mobs that is based on the vanilla villagers: Traveling Merchant, Ore/Gem Miner, both are just another villager variant, and the Villager Troll, which drop emerald when killed.

**If crashed, link to crash report (use a site such as pastebin):**

Minecraft: 1.12.2
Forge: 14.23.4.2705
Mantle: Mantle-1.12-1.3.3.39
Tinkers Construct: TConstruct-1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Requires Primitive mobs

**Comment by bonii-xx** [comment]
Primitive mods must integrate with TiC, if they want their mobs to melt into emeralds. We don't add support for specific mods.
