### ISSUE TITLE
I have a problem with textures of items

### ISSUE THREAD

**Issue by ra38** [SlimeKnights/TinkersConstruct#3686]
**Issue description:**

I have a problem with textures of items
The subject has an invisible texture and it is not clear that Kraft
I updated the mod and the library and still remained

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12
* Forge: 14.21.1.2406
* Mantle: 1.3.3.39
* Tinkers Construct: 2.8.1.49

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
![screenshot_23](https://user-images.githubusercontent.com/45143591/48672832-ca262a80-eb75-11e8-807e-7ba98af8c47f.png)

**Comment by SweetSugarSugar** [comment]
Are you using OptiFine?  Can you list your mods with versions (or packname and version)?  Have you tried reproducing this with only Tinkers' and Mantle?

**Comment by bonii-xx** [comment]
Reproduce with only mantle and tic. Remove any clientside mods, especially optifine.
