### ISSUE TITLE
Specific items don't give xp when smelted

### ISSUE THREAD

**Issue by mser7** [SlimeKnights/TinkersConstruct#3688]
**Issue description:**
Some items fron the mod does not reward xp when being smelted in the furnace, as far as I know, there is the grout and graveyard soil
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
*Minecraft: 1.12.2
*Forge: 14.23.4.2705
*Mantle: Mantle-1.12-1.3.3.39
*Tinkers Construct: TConstruct-1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Only Tinkers is needed.

**Comment by bonii-xx** [comment]
Sounds like a good idea. When somebody finds the time to check our recipes we'll add it.
