### ISSUE TITLE
Lumberaxe doesn't recognize acacia trees

### ISSUE THREAD

**Issue by mser7** [SlimeKnights/TinkersConstruct#3689]
**Issue description:**
Due to the odd diagonal log distribution of acacia trees, the lumberaxe doesn't always recognize the tree

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* Mantle: Mantle-1.12-1.3.3.39
* Tinkers Construct: TConstruct-1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Only Tinkers is needed

**Comment by KnightMiner** [comment]
Fixed in 1.16, no plans to rewrite tree chopping logic in 1.12
