### ISSUE TITLE
Rapier+macro=jetpack

### ISSUE THREAD

**Issue by Rubijox** [SlimeKnights/TinkersConstruct#3690]
**Issue description:**
Having a rapier and a macro that can output right click many times a second causes you to jump really high in the sky, 

Gif of it happening https://my.mixtape.moe/iocwok.gif (the file was 85mb, give it some time to load and play properly, this was literally the only site willing to let me upload it lol)

**If crashed, link to crash report (use a site such as pastebin):**
no crash
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.12-3.0.7
* Tinkers Construct: 1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
have not tested

**Comment by KnightMiner** [comment]
Please test this with just Tinkers Construct, just so we can rule out lag or another mod changing physics

**Comment by Rubijox** [comment]
just tested, made a new instance with only forge mantle and tinkers
(all same versions as mentionned above)

Does still happen in the exact same way as in the modpack

**Comment by Rubijox** [comment]
woops i missclick, did not mean to close >.<

**Comment by KnightMiner** [comment]
Interesting, sounds like it just needs some sort of cooldown then, probably the easiest thing
