### ISSUE TITLE
Slight smeltery issue

### ISSUE THREAD

**Issue by McShaneGun** [SlimeKnights/TinkersConstruct#3691]
**Issue description:**
Smeltery thinks im using blazing pyrotheum when using lava. Date: 11/30/2018 All versions are latest as of this date.

Steps to recreate problem using multiple mods: Ender IO fluid tank under TC smeltery tank. TC Smeltery tank empty. Ender IO fluid tank has lava in it. One bucket of blazing pyrotheum in TC smeltery tank. Partly smelted clay and pulled it out. It used 50 mB of blazing pyrotheum. Broke TC smeltery tank and replaced it with a new empty one. Had Ender IO fluid tank push lava into the new tank. Things kept smelting just as fast as using blazing pyrotheum. The smeltery didnt update or something. I was playing SP. Im no programmer but I couldnt find another way to report this bug. This could be a decent cheat for MP if applicable in MP.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: Latest as of 11/30/2018
* Mantle: Latest as of 11/30/2018
* Tinkers Construct: Latest as of 11/30/2018

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
With other mods. Only ones i can think of as notable are Ender IO, TC, Thermal Foundation.

**Comment by KnightMiner** [comment]
This sounds normal, to an extent. If you just broke the tank with pgrothium, it still has a little bit of that left before it gets new lava, does smelting a few more items change that?

**Comment by KnightMiner** [comment]
Yeah, we do not add pyrothium, but it sounds like whoever added it as a fuel made it last an excessively long time for that little bit. At least you know this for the future
