### ISSUE TITLE
Suggestion: Betweenlands Compatibility 

### ISSUE THREAD

**Issue by yoshmaster123** [SlimeKnights/TinkersConstruct#3692]
Betweenlands alloys / metals

I know this mod is compatible with most large mods, so I was wondering if there is a way to make tinkers integrate metals from the Betweenlands, such as Valonite. Thank you!

Mod Version 1.12.2

**Comment by KnightMiner** [comment]
We only add integrations for common metals such as copper or steel natively. If Between lands adds unusual materials it is up to them or an add-on to add integration. This is what Twilight Forest does for example.
