### ISSUE TITLE
Crash with planks in crafting station (Solo and Multiplayer)

### ISSUE THREAD

**Issue by Ciflire** [SlimeKnights/TinkersConstruct#3693]
**Issue description:**
Crash when placing acacia wood on midlle right grid od craftng station on server
**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/xrG8SW0y
**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2_14.23.5.2768
* Mantle: 1.12.2-1.3.3.39
* Tinkers Construct: 1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
(Impossible with only TC)
Using base configuration of TC
Craft a tool station
place acacia plank on the middle right of the crafting grid
EDIT: Tried solo and same crash happened
EDIT2: Works with the four last versions of TC

**Comment by bonii-xx** [comment]
Looks like a broken recipe. Does it also happen with other woods? From the stacktrace there's nothing TiC specific happening. Try removing mods until it works, and see which mod adds a recipe that causes it. Start with crafttweaker and similar.

**Comment by ZambrOvosky** [comment]
> Looks like a broken recipe. Does it also happen with other woods? From the stacktrace there's nothing TiC specific happening. Try removing mods until it works, and see which mod adds a recipe that causes it. Start with crafttweaker and similar.

I've tried to craft a lot of things (like wooden pickaxe and chest) with different planks and got the same crash. My friends tryna too and crashed.

**Comment by WenXin20** [comment]
I got the same crash in the Crafting Station, but with gold ingots. I was trying to craft something from Steve's Carts, but as soon as I tried to add gold, it crashed. The same thing happened when using the JEI auto fill for recipes. Maybe some mod has a broken recipe with gold in it?[ Crash Report](https://gist.github.com/WenXin20/2f6d7841c0a8dc5b01d8dda2c9fd0e80)
I'm using **Forge v14.23.5.2796**, **TConstruct v2.11.0.106**, and **Mantle v1.3.3.39**
![image](https://user-images.githubusercontent.com/12000593/50556213-97567280-0c9b-11e9-8b75-1684dc607891.png)

**Comment by Ciflire** [comment]
Hey in my case it appears that i launched minecraft with sponge in my mods folder.
In your case is it a modpack that you took on the internet like ftb or did you do it yourself. Then i saw that you allocatef 7.9 GB to your minecraft as you have only 8GB you have to beep at least 2GB for Windows 10 it's probable not the cause. Also i don't know how you did it but you put optifine with the last forge version try the last stable version of forge instead of that. Tell me if that changes something.

**Comment by KnightMiner** [comment]
Everyone having this issue appears to be dealing with a broken recipe, as no vanilla recipes cause this. You should experience the same thing in a vanilla table, so closing this for now

If you can find a specific mod recipe causing the issue we can repopen, but for now we have just too many variables.
