### ISSUE TITLE
Smeltery + Shulker suggestion

### ISSUE THREAD

**Issue by Thunder-Nova** [SlimeKnights/TinkersConstruct#3695]
While editing for a "bucket" suggestion in PlusTic mod (https://github.com/Landmaster/PlusTiC/issues/239) there is one part of the suggestion I made that I really wanted in the main Tinker's Construct mod.

Making a Shulker Smeltery. Simple definition, that unlike the normal smeltery, the Shulker smeltery won't mix the metals as it melts, almost as the Multiblock Seared Tank.

----

Why am I making this suggestion, when we can simply make a seared tank?

1. It is because this requires the end access and access to shulker shell and chorus fruit.

2. It saves space if you plan to auto smelt multiple metals.

3. Got tired in the past seeing my metals all fused because my friends melted them all in one go, in some cases ended with nuggets mismatches.

----

Why Shulker? They got the ability to float players and mobs, why not liquids? Preventing liquids to mix.

**Comment by bonii-xx** [comment]
I understand where you're coming from, but the smeltery is like that per design and wont be changed. If you want to automate the smeltery, you need to take care of these things. Best teach your friends. ;)

**Comment by Thunder-Nova** [comment]
Understandable @bonii-xx

Plus, either way, not forcing it.

Kinda wished for a multi-block structure that can require the end access as well for it's materials. And something other then tools or weapons.

Plus I tend to put signs on my smeltery as warnings to avoid it. I got set-ups as well that does the jobs as I requested here. This suggestion is more of a compact/endgame.

**Comment by bonii-xx** [comment]
I once wanted to explore the concept of smelteries built from different materials (nether/end) to allow upgrading your smeltery for faster speeds, potentially more alloys or something... but overall it doesn't provide much extra and I didn't have the time and motivation to look into it farther ;)

**Comment by Thunder-Nova** [comment]
I imagine you also play a role in yield (instead of a 1:2 ratio, it's 1:3 or 4), but understandable.

If you got an insperation it's up to you, even from our suggestions or even a bug. It is your mod.
