### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by GnomeEater** [SlimeKnights/TinkersConstruct#3696]
Before this is labelled as a clone of another report, I seem to be the only person with this specific issue. I use both TC, Constructs' Armory, and Armory Expansion, and textures are broken (pictured below {hopefully it works, as I only made this account to report this, so I'm not yet familiar with it}) I've tried with and without Optifine, I've updated all the related mods, I've tried them just by themselves, reinstalled the mods, and still nothing. I should note that it's still broken regardless of resource pack.
![2018-12-10_17 08 15](https://user-images.githubusercontent.com/45774539/49770054-f9751680-fc9f-11e8-8799-4606afd00ad9.png)

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.4.2750
* OptiFine: 1.12.2 HD U E3
* TC: 2.11.0.106
* Mantle: 1.3.3.39
* Constructs' Armory: 1.2.0.2
* Armory Expansion: 0.2.0

To my knowledge, i'm the only person to have this issue.

Updated the version list, hopefully it provides more information.

**Comment by KnightMiner** [comment]
There is no "most recent version". Give a version number

Have you tried restarting the game without a resource pack, or just switching mid game? Also, do you have any other mods installed? You listed those specific four, does it happen without Armory Expansion or Construct's Armory?

**Comment by KnightMiner** [comment]
I have honestly no idea what could be causing this, I have frequently seen Optifine cause this but if you say its not happening without it then I am not sure what to say, I have never had it happen myself.

I guess the best thing I can say is try and get a minimal setup to produce the issue. Make a fresh installation and install just Tinkers and Mantle, and see if it still happens

**Comment by GnomeEater** [comment]
Minor-ish update.
So i decided to try out a large modpack that had TC, and it was fully functional. So it's definitely one of my other mods screwing with TC.

**Comment by GnomeEater** [comment]
Yet another update.
Seems that removing FoamFix, even though it does make the game take way more memory, at least fixed the weapons and the icons for the armour. Now to see if changing resource packs will fix the rest of the armour.

**Comment by KnightMiner** [comment]
I assume you have TexFix installed as well then? If so this is the issue described in the spoiler at the top of [the TexFix description page](https://minecraft.curseforge.com/projects/texfix). I would have mentioned it sooner if you had responded to my prompt about a full mod list
