### ISSUE TITLE
Most current release crash.

### ISSUE THREAD

**Issue by SkyBoundPanda** [SlimeKnights/TinkersConstruct#3705]
**Issue description:**

Game crashes when I try to load Minecraft. 

**If crashed, link to crash report (use a site such as pastebin):**

The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: slimeknights.tconstruct.tools.ToolClientEvents.replaceTableModel(Lnet/minecraft/client/renderer/block/model/ModelResourceLocation;Lnet/minecraft/util/ResourceLocation;Lnet/minecraftforge/client/event/ModelBakeEvent;)V

**Versions:**
* Minecraft: 1.12.2
* Forge: 
* Mantle: Mantle-1.12-1.3.3.39
* Tinkers Construct: TConstruct-1.12.2-2.11.0.106

**Comment by KnightMiner** [comment]
Please follow the issue template. Specifically, give your *full* crash report using pastebin. Also, deleting the last question does not mean you don't have to answer it, we need to know what other mods you need to reproduce this.

If I had to guess without you providing any useful information, you probably need to update Construct Armory.
