### ISSUE TITLE
Server crashed, when hit zombies with rapier

### ISSUE THREAD

**Issue by lays24mc** [SlimeKnights/TinkersConstruct#3710]
**Issue description:**

When I hit a zombie with my rapier, my server crashed. 

**If crashed, link to crash report (use a site such as pastebin):**

https://pastebin.com/L2kZVKpW

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2784
* Mantle: 1.12-1.3.3.39
* Tinkers Construct: 1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

![2019-01-01_22 16 59](https://user-images.githubusercontent.com/38819519/50576527-ca237680-0e13-11e9-9dd5-f5e54ba60eae.png)

![2019-01-01_22 19 47](https://user-images.githubusercontent.com/38819519/50576535-00f98c80-0e14-11e9-93ab-2cad004d018c.png)

**Comment by KnightMiner** [comment]
Closing for lack of response

**Comment by KnightMiner** [comment]
Closing for lack of response
