### ISSUE TITLE
Ores do not exist

### ISSUE THREAD

**Issue by Latthe** [SlimeKnights/TinkersConstruct#3712]
**Issue description:**

**Versions:**
* Minecraft: 1.8.9
* Forge: 1.8.9-forge1.8.9-11.15.1.1902-189/fml,forge
* Mantle: 0.9.0 (1.8.9-0.9.0..jenkins97)
* Tinkers Construct: 1.8.9-2.2.1 (1.8.9-2.2.1..jenkins1005)

I don't know if the copper, aluminium,steel and such is a feature of the mod itself or I need to download the ores separately. Please help.

**Comment by laz2727** [comment]
TiC only has Cobalt and Arbite ores now.

**Comment by Latthe** [comment]
That makes a lot of sense but the other ores still exist in JEI?

**Comment by KnightMiner** [comment]
The materials still exist if another mod adds the ores. You can install nearly any mod with copper for example to get copper parts.
