### ISSUE TITLE
Rendering Crash with filled Seared Tank

### ISSUE THREAD

**Issue by implayin** [SlimeKnights/TinkersConstruct#3717]
**Issue description:**
The game crashes when I try to fill a Seared Tank/Window with Lava
**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/L0JNSSV8
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2796
* Mantle: 1.12-1.3.3.39
* Tinkers Construct: 1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
It doesn't happen with no other mods loaded, but I couldn't isolate the responsible mod yet.

**Comment by KnightMiner** [comment]
I'm having a hard time understanding the crash report as its pointing to non-existant lines and methods in our render util, making me wonder if someone else is somehow modifying it. You have a pretty large list of core mods loaded, removing some of them (especially ones related to rendering) is a good place to start debugging this.

**Comment by KnightMiner** [comment]
Closing for lack of response, and as the crash does not appear possible.
