### ISSUE TITLE
*Idea* I'd like to suggest a way to select which mod the block, ingots, and such pour into...

### ISSUE THREAD

**Issue by RepoDraghon** [SlimeKnights/TinkersConstruct#3718]
We all know there's so many mods that add their own metals and respective ores, right now, you pour and you get what in my assumption is the mod that dominates the others... 

I was wondering if you might be able to add a code/ggi/item or something that one would be able to say select what mod say Thaumcraft or IC2 or whatever mod one would want it to pour out as,... I dunno, I'm just spitballing...

**Comment by KnightMiner** [comment]
This feature already exists, check out our config file under `orePreference`
