### ISSUE TITLE
[2.12.0.113] Tinker Tank Multiblock doesn't form

### ISSUE THREAD

**Issue by rinart73** [SlimeKnights/TinkersConstruct#3719]
**Issue description:** After update Tinker Tank multiblock doesn't form anymore. All liquids inside are disappeared too (I checked this by downgrading).

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.39
* Tinkers Construct: 2.12.0.113

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Just Tinker Construct

**Comment by KnightMiner** [comment]
Can you give a screenshot of your structure?

**Comment by Sunekaer** [comment]
When do you think that update would be out @KnightMiner ?

**Comment by bonii-xx** [comment]
When I don't forget to put out another release >_>
