### ISSUE TITLE
No overworld oregen (1.12.2 - 113)

### ISSUE THREAD

**Issue by MarkColo2** [SlimeKnights/TinkersConstruct#3722]
No overworld gen of tinkers ores (copper, aluminum, ...)

**Versions:**
* Minecraft: 12.2
* Forge: 1.12.2-14.23.5.2768
* Mantle: 1.12-1.3.3.39
* Tinkers Construct: 1.12.2-2.12.0.113

Using only Tinkers and Mantle, I cannot find one single block of overworld tinker ore.  I'm flying through a dozen deep ravines in spectator mode.  Nothing but iron, lapis and gold.
I checked the nether.  It does have ardite and cobalt.

**Comment by laz2727** [comment]
Overworld ores don't exist anymore.

**Comment by MarkColo2** [comment]
That makes sense.  With iron in the world, who would make copper tools.
