### ISSUE TITLE
Custom Tool Output Support

### ISSUE THREAD

**Issue by Omegapsychosis** [SlimeKnights/TinkersConstruct#3723]
I am wondering if it is possible to add a custom output for things like the tool station using minetwearker/modtweaker etc.

I love this mod so much, but in an early tech progression modpack the tools can get very powerful very quickly and they overshadow many other mods items too quickly. I am looking to disable the custom tools aspect of the mod, while keeping it's core tool building features. I'd like to smelt ores to cast into patterns for pickaxe heads etc. Use only 1 material as a binding for a tool, and a tool rod, and have it output a vanilla tool as a result.

Example:
Iron pickaxe requires a Iron pickaxe head, hemp binding and wooden tool rod. Must be crafted in a tinkers tool station.

Not sure if this is currently possible, or if support for this type of thing is in the scope of what you want this mod to be, but it could be very useful to modpack makers.

**Comment by bonii-xx** [comment]
It might be possible with enough workarounds, but you probably wont be able to do it with minetweaker alone. Will most likely need a custom mod for it.

**Comment by KnightMiner** [comment]
This is possible in 1.16 via a custom recipe type, and I have no plans to change 1.12 to make it possible, so closing this.
