### ISSUE TITLE
My controller isnt showing the medals I put in.

### ISSUE THREAD

**Issue by Wancakes** [SlimeKnights/TinkersConstruct#3724]
**Issue description:**
So as the title says, I know I have put medals into my controller, and I know they're in there because I can still click on the drain to pour them out, but when I look into my controller, the medals are not there.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.6.4
* Forge: 9.11.1.965(Im not really sure i just know this pops up on the title screen)
* Mantle: 
* Tinkers Construct: Also not sure, I just know its the version in the most recent update of the "Attack of the B Team" modpack on the Technic Launcher, which is about 4 years old.

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?** Other mods might be required since it took place in a modpack.

**Comment by KnightMiner** [comment]
Closing for lack of response
