### ISSUE TITLE
Disabling fluids doesn't work properly

### ISSUE THREAD

**Issue by fer22f** [SlimeKnights/TinkersConstruct#3725]
**Issue description:** Disabling the TinkerFluids module in TinkerModules.cfg doesn't work properly. Liquids still show up in JEI and mods like Forestry create capsules for every liquid in Tinkers Construct.
![image](https://user-images.githubusercontent.com/3057302/51078032-429cf980-1696-11e9-9088-6afda1e5745d.png)

The config is as follows, I was looking for using just the gadgets and the world gen from Tinkers:

```
~CONFIG_VERSION: 1

modules {
    B:TinkerDebug=false
    B:TinkerFluids=false
    B:TinkerGadgets=true
    B:TinkerHarvestTools=false
    B:TinkerMaterials=false
    B:TinkerMeleeWeapons=false
    B:TinkerModelRegister=false
    B:TinkerModifiers=false
    B:TinkerRangedWeapons=false
    B:TinkerSmeltery=false
    B:TinkerTools=false
    B:TinkerWorld=true
    B:chiselIntegration=true
    B:chiselsandbitsIntegration=true
    B:craftingtweaksIntegration=true
    B:theoneprobeIntegration=true
    B:wailaIntegration=true
}
```

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2807
* Mantle: 1.3.3.39
* Tinkers Construct: 1.12.2-2.12.0.113

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?** I enabled just Tinkers Construct and JEI and the result is the screenshot above. With Forestry, capsules are also created for each of the liquids.

**Comment by bonii-xx** [comment]
Hm, it might be that we cant offer this option anymore. If I remember correctly something regarding fluid registration changed in Forge in 1.10 or early 1.12, which requires us to always register all our fluids ahead of time.

**Comment by XXxinsanityxX** [comment]
Is this still the case or has something been changed since to allow this to happen?

**Comment by KnightMiner** [comment]
Marking in the 1.12 milestone as reminder to mark fluids as not able to be disabled, as that is the simplest fix without making significant changes. Not sure if 1.12 will get any more builds still.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support.
