### ISSUE TITLE
Landmine in Regrowth

### ISSUE THREAD

**Issue by Ryuu605** [SlimeKnights/TinkersConstruct#3726]
**Issue description: Hi. I used the landmine in Regrowth and my Minecraft crashed, and if I try to open the map it still crashes.**

**If crashed, link to crash report (use a site such as pastebin): https://pastebin.com/yi0hLstD **

**Versions: 1.7.10 **
* Minecraft: Regrowth 1.0.2
* Forge: Forge-1.7.10-1.1.2.331-universal
* Mantle: Mantle-1.7.10-0.3.2b
* Tinkers Construct: TConstruct-1.7.10-1.8.8

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug? I don't know, I just want my map back because I played too much on it just to have it dead...**

**Comment by KnightMiner** [comment]
From the looks of the crash, the code for launching fireworks in a landmine is missing a null check for having no rider. Unfortunately, we have not released a 1.7.10 build in almost 3 years so really unlikely this will be fixed. Your best bet is restoring a backup or loading up the map in MCEdit and deleting the firework entity.
