### ISSUE TITLE
Using Tconstruct crafting station

### ISSUE THREAD

**Issue by HFinner** [SlimeKnights/TinkersConstruct#3727]
**Issue description:** Crashing client when moving items from the player inventory to a tinker construct's Crafting station. I also have turned off the item display on top of the station.

**If crashed, link to crash report (use a site such as pastebin):** https://pastebin.com/bki7kXUW

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2806
* Mantle: 1.3.3.39
* Tinkers Construct: 2.12.0.113

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Not sure, I think mouse tweaks was a contributing factor but even after disabling it, still crashing randomly when using the station.

**Comment by KnightMiner** [comment]
Looks like an issue with Industrial Wires with one of their recipes, does this happen in a vanilla crafting station if you try moving the same items?

In either case, report it to them as well, they will have a better idea what broke the recipe.

**Comment by HFinner** [comment]
Th

> Looks like an issue with Industrial Wires with one of their recipes, does this happen in a vanilla crafting station if you try moving the same items?
> 
> In either case, report it to them as well, they will have a better idea what broke the recipe.

Thanks for reply! I will send it over to them. But no normal crafting table works perfectly.

**Comment by KnightMiner** [comment]
Closing for lack of response as this appears to be a broken recipe
