### ISSUE TITLE
Crafting station discards excess items for stacks of more than 64 items

### ISSUE THREAD

**Issue by LlubNek** [SlimeKnights/TinkersConstruct#3728]
**Issue description:**
When using Tinkers Construct with StackUp, the crafting station, and other TConstruct tables, discard any items in excess of 64 items per stack.

Most likely this is because of a hard coded "64" instead of "Items.AIR.getItemStackLimit()" or whatever.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2796
* Mantle: 1.3.3.39
* Tinkers Construct: 2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
StackUp! 0.2.3
https://minecraft.curseforge.com/projects/stackup?gameCategorySlug=mc-mods&projectID=299488

**Comment by KnightMiner** [comment]
Yeah, currently just about all our inventories limit to 64 because Minecraft limits to 64. If a mod changes that core assumption,that it's their fault really.

Not saying this won't be fixed, just that it's not a huge priority.

**Comment by KnightMiner** [comment]
Closing this as I don't want to make significant changes to 1.12 and this will likely break things to fix. If someone makes such a breaking mod on 1.16 we can resonsider.
