### ISSUE TITLE
Slimball from leaves drop chance

### ISSUE THREAD

**Issue by pxoxd** [SlimeKnights/TinkersConstruct#3729]
**Issue description:**
When breaking slimy leaves there seems to be a possibility for them to drop slimeballs, except the chance is extremly small. Did some testing:

From 50 stacks of leaves i got:
Blue Slimy Leaves: 4 Blue slime balls and 7 green
Purple Slimy Leaves: 16 Purple Slime balls
Orange Slimy Leaves: 0
Got a bunch of saplings, but this is the result for slime ball drops.
Not sure if its intended to be such low drop rates.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:** 
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2807
* Mantle: 1.3.3.39
* Tinkers Construct: 1.12.2 - 2.12.0.113

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
yup

**Comment by bonii-xx** [comment]
The chance is exactly the same as getting an apple. And yes, it's intended, it's just a small bonus.
