### ISSUE TITLE
Wooden Rail with Trapdoor stops inserting after first slot runs out

### ISSUE THREAD

**Issue by fer22f** [SlimeKnights/TinkersConstruct#3730]
**Issue description:** If you have a hopper minecart with the first slot empty (which happens when it runs out), it stops outputting the other slots:
![image](https://user-images.githubusercontent.com/3057302/51290655-7efc8c80-19eb-11e9-9d7a-4df2d0e30cb8.png)

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2807
* Mantle: 1.3.3.39
* Tinkers Construct: 1.12-2.12.0.113

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?** I believe it can be reproduced just with Tinkers Construct.

Looking at the code, it seems like it would give up after the first slot becomes empty:
https://github.com/SlimeKnights/TinkersConstruct/blob/23034cb63e98bba06faf1cdc4074009daf93be1f/src/main/java/slimeknights/tconstruct/gadgets/block/BlockWoodRailDropper.java#L30-L37

**Comment by J-Dill** [comment]
I was able to recreate this problem by putting the Wood Rail Dropper on top of a dropper: only the first stack of items was pulled from the hopper. 

My above fix allows the Wood Rail Dropper to search through the rest of the slots in the Minecart with a Hopper.

**Comment by J-Dill** [comment]
Also, I noticed that the Wood Rail Dropper allows items to be moved much faster than a hopper can actually move items. Is this intended?

**Comment by J-Dill** [comment]
@bonii-xx Should this issue be closed out then? Or is there a reason to still keep it open?

**Comment by SweetSugarSugar** [comment]
@j-dill Issues are kept open until a release is pushed
