### ISSUE TITLE
[1.12.2] Kama only replants crops that use vanilla Minecraft blocks

### ISSUE THREAD

**Issue by Nosrick** [SlimeKnights/TinkersConstruct#3732]
Basically, I'm developing a mod that allows the user to grow string and spider eyes in one crop. Said crop grows on dirt and hangs on the underside of the block. The kama harvests these crops just fine, but doesn't replant at all.

I've tried several different configurations, and it all boils down to what kind of soil the crop uses. It has to be farmland (or I believe soul sand). All other blocks will not allow a replant, even when the crop is right-side up.

Is there any way to address this?

**Comment by KnightMiner** [comment]
Yes, we have events you can listen to in order to determine replanting behavior. See [OnScytheHarvest](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/library/events/TinkerToolEvent.java#L119)
