### ISSUE TITLE
seared furnace deletes items

### ISSUE THREAD

**Issue by gavinrobertkemp** [SlimeKnights/TinkersConstruct#3733]
**Issue description:**
it looks like when smelting items using producing multiple items (for example conduit binder from enderio) the items sometimes disappear. I believe this happens when the number of crafted items produced is higher than the internal stack limité of 16. their is a mecanisme to prevent that but i wonder if it take into account the items trickling in. it also possible the acceleration wand is related to this (i found this in the ultimate alchemy mod pack)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.4.2766
* Mantle: Mantl-1.12-3.0.5.jar
* Tinkers Construct: TConstruct-1.12.2-2.10.1.87.jar

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
the easiest would be to use ultimate alchemy but it could be an interaction with "not enough wands", "extra utilities 2" (mechanical user) and i found the bug with enderio item and what ever they are using to make compressed cobblestone become 4 iron (content tweeker or crafting tweaker i think)

**Comment by KnightMiner** [comment]
Can you make more clear steps to reproduce? Specifically, does this work without the acceleration wand? As you said, there are stack size checks so output greater than 16 should not be a problem.

**Comment by gavinrobertkemp** [comment]
Unfortunately it looks like i can't. for some reason the multiblock won't form (register) in creative and my normale world wont load i keep getting this error "The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded."
if you have any idea how to resolve this issue it would be welcome but i have no way off knowing if its related.

what i was observing though for the initial issue is as the item started arriving the first item would comes passe the stack test and start smelting then an other item would add to the stack but doesn't look like it takes the test. when the stack reaches 16 it keeps smelting. i noticed this because it recipes would never complete when using refined storage and even adding the ressources manually id not get the number of items i'd expect.

**Comment by laz2727** [comment]
Any updates on this? This bug is as old as the furnaces themselves.

**Comment by KnightMiner** [comment]
I've fixed this for the inventory. In my testing hoppers worked perfectly fine already so if you still have issues with those open a new issue.

Side note: we have a recipe in native Tinkers with a larger stack size, slime channels return 3 from a single congealed slime.
