### ISSUE TITLE
iron disappearing in smeltery

### ISSUE THREAD

**Issue by Muckraker-Joe** [SlimeKnights/TinkersConstruct#3734]
**Issue description:** Once iron is done smelting in the smeltery, it does not appear as a molten liquid inside the smeltery, effectively disappearing. This only appeared recently in the server I'm playing on and has not happened throughout the entire playthrough. I tested this is in a singleplayer world and couldn't manage to replicate it.

**Versions:**
* Minecraft: 1.7.10, Mianite Reborn Legacy
* Forge: 10.13.4.1614
* Tinkers Construct: 1.8.8

**Comment by KnightMiner** [comment]
What type of server are you on? Are other mods installed, specifically server side only mods?
