### ISSUE TITLE
GUI with double chest does not fit on screen

### ISSUE THREAD

**Issue by RomkeVdMeulen** [SlimeKnights/TinkersConstruct#3736]
**Issue description:**

When GUI size is set to "Auto", then the crafting station GUI doesn't fit on screen when attached to a double vanilla chest. It fits with a single chest: I guess the scrollbar is what makes the GUI just slightly too wide.

With single chest attached: https://imgur.com/QhWfq2l
With double chest attached: https://imgur.com/1ajenY8

Sorry if this has been reported before: if so, I couldn't find it.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2807
* Mantle: 
* Tinkers Construct: 1.12.2-2.10.1.87

**Comment by yay132411** [comment]
well set the GUI size to ''Normal''

**Comment by bonii-xx** [comment]
I've thought about this a bit, and the easiest solution would be to simply drop one column. But that would change the UI and make it even "taller". Since all slots are visible on screen and therefore can be used we'll stick with the current solution, even if it's suboptimal.

**Comment by RomkeVdMeulen** [comment]
Sounds reasonable.
