### ISSUE TITLE
Items disapper by magnet effect.

### ISSUE THREAD

**Issue by Werewolf74** [SlimeKnights/TinkersConstruct#3739]
**Issue description:**
Items disapper by magnet effect from Tinker Construct by weapon and armor from mod. construct-amory if player have full inventory and item get by using magnet effect, i lost my iron sword as example only to take it from tool rak but my inventory was full the sword drop on ground then to me 1. magnet effect and then the second magnet effect disapper my weapon, by only using magnet effect from tinker that will seen rar that items disapper but by using another mod with magnet effect increased this problem as example pickle tweaks magnet (enabled) i post first by his forum this bug, but now i play another mod. where is only your is with magnet effect and items disapper again.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
TConstruct-1.12.2-2.12.0.115.jar
* Minecraft: 
1.12.2
* Forge: 
forge-14.23.5.2808
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
I played before another mod where it was two different magnet effect that you can use to see am best the problem.
Use pickle tweak mod. his magnet (enabled) with any iron tool or amory, from tinker construct, and have i full inventory by farming full inventory what your char. not can take it in his inventory will disapper from ground.

regards.

Spowsi

ps. sry for my english , i can only a litle from this language i hope you understanding this problem.

**Comment by KnightMiner** [comment]
Can you clarify the issue? Which magnet is causing the issue? Tinkers Construct tools, Construct's Armory armor, or Pickle Tweaks? It sounds like its not a Tinkers Construct issue to me, especially since all our magnet does is move items towards the player.

**Comment by Werewolf74** [comment]
by all bouth mods is installed Tinkers Construct tools and Construct's Armory but by one mod i used only tinkers weapon with iron armor and test it with full inventory the items move to me in players centers and by 2-4 use with weapon or pickaxe with iron magnet effect the item disapper by player center.

If you use a another magnet effect how Botania or pickle tweak where items moving all time directly to the center from player and any magnet effect from tinkers construct is starting it will disapper item quikly in center from player.

by all 2 different mods i take off all magnet effect from tinkers construct so that only the magnet from botania or pickle tweak mod. as example works only on me and and the items did not disappear anymore.

So i can not realy say which mod make this problem, it is Tinkers Construct tools or Construct's Armory idk, all bouth mod used this last version from them. :/

**Comment by KnightMiner** [comment]
Does this happen with just Tinkers Construct tools?

Does this happen with just Construct's Armory armor?

If I am understanding this issue correctly, you are finding that if you have two magnets active at once, the items disappear? So you can have Botania and Tinker tools, Botania and Constructs Armory armor, or Tinker Tools and Construct's armory armor?

**Comment by KnightMiner** [comment]
Closing for lack of response, as I still have not seen anything that points to this being a problem in our code. If you have more to say on this issue, please respond in #3857 as thats the same issue.

As far as this issue goes, I still hold that it should be impossible, literally all we do is add motion to the item, and every single other magnet item I have seen either does the same or sets the item's position. If you can reproduce this with only Tinkers Construct and one other mod with a magnet, let me know and preferably post a video showing the behavior to #3857, because as of yet we are unable to reproduce this.
