### ISSUE TITLE
Wooden Rail with Trapdoor not working

### ISSUE THREAD

**Issue by lgnmcrules** [SlimeKnights/TinkersConstruct#3740]
**Issue description:**
Wooden Rail with Trapdoor item not working as intended in any situation.  Acts only as a straight rail and nothing else despite redstone powering and many different types of setups for the rail to work as intended.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: release 1.12.2-forge1.12.2-14.23.4.2705
* Mantle: Mantle-1.12-1.3.3.39
* Tinkers Construct: TConstruct-1.12.2-2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Just Construct

**Comment by KnightMiner** [comment]
Can you give a screenshot of what you are attempting to do?

**Comment by bonii-xx** [comment]
Currently, the direct block underneath is used for insertion. You propose an interesting variation that might be worth implementing.
As of now, you need to use some block that can support rails as well as has an inventory. Hoppers should work in your case. They were originally implemented for drying racks.

**Comment by KnightMiner** [comment]
Going to close this as wooden rails are likely not remaining in the mod for 1.16.
