### ISSUE TITLE
[ Question ] Disable crafting part from Smeltery, it's possible?

### ISSUE THREAD

**Issue by HurtsAsHell** [SlimeKnights/TinkersConstruct#3744]
As a title, can I eliminate the crafting of a part like pickaxe_head:iron?
or can you tell me if there is a mod that does it?

**Comment by KnightMiner** [comment]
If you want to remove smeltery recipes, use ModTweaker. See [the CraftTweaker docs](https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/TConstruct/Casting/).
