### ISSUE TITLE
[12.0.115] java.lang.NullPointerException

### ISSUE THREAD

**Issue by AnimalLover567** [SlimeKnights/TinkersConstruct#3748]
**Issue description:**
I crafted a hammer in the tool forge and was going to add modifiers, when i went to to place the hammer back into the tool forge it crashed and vinillafix said it was Tinkers' Construct Mantle.
**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/mEnVFqFA
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.25.5.2808
* Mantle: 3.3.29
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Tinkers Construct and Mantle as vinillafix said they were the blame.

**Comment by KnightMiner** [comment]
Did you actually test with just Tinkers Construct? Vanilla fix only looks at whose code crashed, not who is actually to blame. In this case, some addon is adding a broken modifier. Taiga is to blame in some older issues, but it looks like you have the fix for that so its another addon to blame.

**Comment by bonii-xx** [comment]
You most likely got a broken modifier that is not from TiC itself.

**Comment by KnightMiner** [comment]
Closing for lack of response
