### ISSUE TITLE
lib.jar is actually empty

### ISSUE THREAD

**Issue by Yaossg** [SlimeKnights/TinkersConstruct#3750]
**Issue description:**
most of xxx-lib.jar on the maven is actually empty (but with only a META-INF), how can I use such an API?
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: -
* Mantle: -
* Tinkers Construct: most of all 

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
just download one on [The Maven](http://dvs1.progwml6.com/files/maven/slimeknights/TConstruct/) to see

**Comment by bonii-xx** [comment]
Oh, we still have those. The lib build is actually a relic from the old build pipeline. The best way to use the API is to set up tic as deobfCompile dependency. It has the highest compatibility. We'll remove the lib build outputs.

**Comment by bonii-xx** [comment]
The deobf artifact will also be removed with 1.13 for the same reason, it's only kept for compatibility reasons.
