### ISSUE TITLE
Paper tool rod embossment on some Writable I tools doesn't give Writable II

### ISSUE THREAD

**Issue by TeeMee123** [SlimeKnights/TinkersConstruct#3751]
**Issue description:**
Embossed hammer and lumber axe with a paper tool rod (normal not tough) when it already had writable due to having a paper tough tool rod.
It did not add it on to make it writable II, but still used up the embossment.
Tried embossing with paper pan instead of tool rod, and it went to writable II as it should. Also tried with other material of normal rod and that gave the right embossment. Also tried embossing writable pan with paper tool rod and that worked.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2796
* Mantle: ?
* Tinkers Construct: 2.12.0.113

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Encountered in FTB Continuum 1.6.0, seems very unlikely to have been anything but tinkers construct causing the bug.

**Comment by KnightMiner** [comment]
Try that last question again, its not asking where you reproduced the bug, its asking if it can be reproduced with fewer mods

**Comment by TeeMee123** [comment]
> Try that last question again, its not asking where you reproduced the bug, its asking if it can be reproduced with fewer mods

Fixed

**Comment by bonii-xx** [comment]
That's because you're embossing a trait it already has. You already have the trait from a tool rod, you need the other trait from a toolhead then it'll work. Working as intended.

**Comment by TeeMee123** [comment]
Nope the intended effect is that you get the next level of writable. It works with other paper parts.
Please reopen.

**Comment by TeeMee123** [comment]
It should still stop you from embossing with something that wont do anything. It is not clear that such an embossment wont have any effect.

**Comment by bonii-xx** [comment]
Yes, it probably should.
