### ISSUE TITLE
Seared Brick Stairs/Slabs TileEntities?

### ISSUE THREAD

**Issue by RebelliousUno** [SlimeKnights/TinkersConstruct#3753]
Query, Seared brick stairs and Slabs are tile entities, but the whole blocks are not?

This means they can't be used with exchangers for example.  Is there a reason for them to be tile entities and is there a performance hit for using a lot of them in a build?

**Comment by laz2727** [comment]
*All* seared blocks are tiles. But they don't tick so they shouldn't cause performance problems.

**Comment by RebelliousUno** [comment]
Ok, scratch that, I see where they become tile entities now (since they extend BlockEnumSmeltery) but they still weirdly work with exchangers where slabs and stairs do not...

**Comment by KnightMiner** [comment]
Exchangers needs a TE whitelist then. The seared blocks are whitelistable with mods such as chisel and bits. Reason they are TEs is so the smeltery multiblock is not absolutely terrible on performance.
