### ISSUE TITLE
Casting not setting for some molds.

### ISSUE THREAD

**Issue by Novabella** [SlimeKnights/TinkersConstruct#3755]
**Issue description: Casting not working on some items, Example: Tough Rod.**

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1614
* Mantle: 
* Tinkers Construct: 1.7.10-1.8.8

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?: Unsure. Using "Infinity Evolved" modpack**

I put a stone tough rod into the casting table, and then poured gold over top of it, and waited. It sat for several minutes with no change. Did I do something wrong? 
![image](https://user-images.githubusercontent.com/17990493/52458559-f1f1b280-2b14-11e9-970d-e03f4a487db0.png)

**Comment by SweetSugarSugar** [comment]
It takes two gold ingots (288mb) to make a cast.

**Comment by Novabella** [comment]
Ohhhhhh. Thanks!
