### ISSUE TITLE
(Suggestion) Shulker Modifier, general seared upgrade, and blowdart

### ISSUE THREAD

**Issue by Thunder-Nova** [SlimeKnights/TinkersConstruct#3756]
This is a whimsical suggestion. Mostly because some ideas peaked my interest and tweaked on them by adding specifications. The seared upgrade idea is based on a previous idea I had, and edited and mixed in the possibility mentioned by @bonii-xx , and the shulker is highly based on it's portable abilities used in various mods which TiCon could use so tried my best in making a possible suggestion.

EDIT: Depending on the yes and no. If there are Yes, I will strike the no's if there are any. And add edit if there are some edits to be added.

####Shulker modifier

I have been thinking of a use for shulker for a while, they mainly been used for storage and wanted to keep them that way.

So primary the Shulker modifier has 4 names depending on what it is used on. Shift right click the tool at hand it will open up to a 3 slot inventory. 
 - Bows, Crossbow and Throwing weapons:
 Ammo slots (1 to 3): For bows and arrows it can be only filled with arrows or bolts depending on their ammo. For throwing weapon Sharpening kit or preferably their head piece which acts as an auto-restock.

- Mattock, Lumberjack, Scythe (Due to their uses and ability):
 Farming slot (1 to 3): It stores bonemeal for all and sapplings for Lumberjack. As you farm it can auto-plant and speed up growth by right clicking on the plant. Since Lumberjack has the ability to bring down the whole tree to it's leaves this will also add the ability to cut down the leaves as well to auto plant sapplings it has in it's inventory. (Idk if it will work for those 2x2 trees)

- Battlesign, Frying Pan:
Food quench (1 to 3): This stores food, and auto feeds the user if the item is placed in the off-hand. In added bonus, it can be auto-filled with bacon if it, or main hand (if tool is in off-hand) has the Tasty trait.

- All swords:
Coated blade: I know that mods that adds lead adds poison traits. But this modifier is more diverse yet limited. Weapons gains additional temporary effect by filling the slots with spider eyes (poison 1), wither bones (wither 1), cobweb (slowness 1), glistering melon (regen 1), ink sack (blindness 1), glowstone dust (glowing). Once a player attacks the weapon consumes 1 item or all 2 or 3 at once. And gives a 10 second application, but a 30 seconds cooldown before consuming another set. It can also store gunpowder to create a small explosion which adds an AOE damage and huge knockback, but also damages user, but not the blocks. When filled with gunpowder, attacking the ground will increase the range of AOE and knockback but reduces damage for escaping.

#### General Seared upgrade

This gives 2 new materials Seared Nether, and Seared End. This will give more use to the abundance of netherrack and end stone.

This can't be combined with each other in multiblock.

To make molten seared nether, must melt seared stone and netherrack together. This idea gives out more heat, which if build a multiblock structures out of this material, it will be faster to smelt items compared to the original seared multiblocks.

Seared End stone will act as a compacted upgrade to seared nether. It is made by melting seared nether with end stones. This doubles the slots of a build. Example: The usual 5x5x2 (counting sides and floor) smeltery has 9 slots of items, but an Seared End smeltery makes that 18. Plus it has the speed of the seared nether.

Their controller and tanks must be made out of the same material. But can use any faucets, upgraded faucets just boost speed of pouring.

The seared tank multiblock is pointless upgrading from seared to seared nether. But best if into seared end for it's doubling containment ability. So yea saw this while making the suggestion.

EDIT: There are 2 ways to create the upgraded controllers, create them from scratch. Or pour the molten liquid on top the old one. Seared End on Seared Nether on Seared

#### Blowdart

Like the bow is to a longbow. The blowdart is to a crossbow. It used same ammo as a crossbow. Less stronger and range, but near instant reload speed. It uses 1 tube (acts as bowlimb), stick and binding, Or 2 tubes and binding.

**Comment by SweetSugarSugar** [comment]
1) Balance issues, and also most of them are redundant.

2) Nether-type seared bricks are already planned and will be implemented differently.

3) Doesn't really fulfill or cover a need.  Also it makes the shortbow useless.

Refer to the FAQ for more information.

**Comment by Thunder-Nova** [comment]
@SweetSugarSugar

I am the type who is open to opinions and discussion, so might get disappointed for full shutdown, but never angry. I do love balancing ideas even to my own.

1. Balancing issues: understandable, though trying to grasp it. I originally though of adding a chest load as inventory. But stuck with 1 slot per upgrade while rethinking.

2. I did see a "possibility" and tried to go deeper into it. Did get mentioned about the exploration with future change ideas. Doesn't mean I can't add my own idea. What they do or don't take is up to them. It's their mod.

3. I didn't mention the blowdart in my introduction due to this. Kinda hoping a balance idea. Btw: blowdart doesn't use bow string. So might be significantly weaker then a bow, but since it mostly just a pipe. It has significantly weaker attack and range. But perhaps still can pierce armor. I don't know.

**Comment by KnightMiner** [comment]
The shulker modifier sounds like a ton to implement for a single modifier, I would rather not add the complexity of tools having an internal inventory. One of the design goals of Tinkers Construct is to keep things simple, and if the modifier not only adds an inventory to the tool but also changes its behavior based on that inventory that is way too complex.

As mentioned by Sugar, there are plans to make more smeltery materials, but its not a high priority. One important detail is we do not want the alternative materials to just be an upgraded smeltery. The goal of the mod is to Tinker, so different smelteries need different strengths and weaknesses. What this means is each of the block types will not be dependent on the "previous" material to craft, it will be closer to 1.7 where the nether smeltery is made exclusively out of nether materials and the end one likewise.

Blowdart I am not sure fits: the main point of the crossbow is its slow to reload but can be fired instantly once loaded. Adding something that just takes the load time out at the cost of damage basically gives you shurikens.
