### ISSUE TITLE
Create "item.tconstruct.bolt_core.prefix"

### ISSUE THREAD

**Issue by Regnander** [SlimeKnights/TinkersConstruct#3758]
**Issue description:**
The material strings in en_us.lang have optional strings that allow translators to place the material name after the tool name (for example changing `material.wood.prefix=Wooden %s` (default) to `material.wood.prefix=%s of wood`) in order to make it more appropriate in the translated language. From a translators standpoint, I'm really thankful for this.

However, this is not possible for the Bolt Core where the materials are always listed before the item name ("\<material1>-\<material2> Bolt Core", for example "Bone-Iron Bolt Core"). Therefore I suggest a new string similar to the prefix strings I mentioned earlier: `item.tconstruct.bolt_core.prefix`, which would default to `%1$s-%2$s %3$s` (`%1$s` is the first material, `%2$s` is the second material and `%3$s` is "Bolt Core"), since I would like to be able to replace the dash with a word.

**Versions:**
* Minecraft: Irrelevant
* Forge: Irrelevant
* Mantle: Irrelevant
* Tinkers Construct: Any version that has Bolt Cores

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Just Tinkers Construct, no other mods are required.

**Comment by KnightMiner** [comment]
No easy way to do this as you said, and bolt cores are gone in 1.16, so closing
