### ISSUE TITLE
Casting channel not pulling from Smeltery

### ISSUE THREAD

**Issue by Immaculala** [SlimeKnights/TinkersConstruct#3759]
Tinkers Construct 1.12.2
I wanted to set up a system of making many ingots at once and using casting channels to multi casting tables with hoppers underneath seemed to be a good option.
But I cannot get the channels attached directly to drains to pull liquid from the Smeltery. If I right click on the channel attached to the drain either nothing happens or it changes the orientation of the channel to sideways or input.

MC 1.12.2
TConstruct-1.12.2-2.12.0.115
Forge 1.12.2-14.23.4.2808
Mantle-1.12-1.3.3.39

![2019-02-11_04 23 22](https://user-images.githubusercontent.com/26187212/52546342-3fd91580-2db6-11e9-9d14-605fff42c048.png)

**Comment by KnightMiner** [comment]
Casting channels don't pull, use a faucet to pour into the channel.

**Comment by Immaculala** [comment]
Thanks for the quick reply, but I am confused.
In this video https://www.youtube.com/watch?v=dEFhrptuc0s I can see casting channels are pulling out – he also states it (approx 48 seconds). 
Is this a feature that TC used to have but has no longer?
I know about using a faucet to pull into the channel but then I have to stand there clicking one by one ingots.

**Comment by KnightMiner** [comment]
Video is pretty I would guess, I cannot even remember them pulling from tanks back in 1.7.10.
