### ISSUE TITLE
[1.12.2] Tesselating block tile tooltable causes crash.

### ISSUE THREAD

**Issue by GurtBFroe** [SlimeKnights/TinkersConstruct#3760]
**Issue description:**
Tesselating block crash caused by: Java.lang.RuntimeException: No OpenGL context found in the current thread. Tooltables causing exception.

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/2YcTCbtX

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.3.2768
* Mantle: 1.3.3.39
* Tinkers Construct: 1.12.2-2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Just Tinkers Construct. All I have to do is log in to the live server and my client will crash upon login.

**Comment by bonii-xx** [comment]
The crash is caused by another mods model, which is broken. That's what the last question means. It's another mods fault. Looks like forestry actually, which is quite surprising. Might be one of the coremods, too.
