### ISSUE TITLE
Cant smelt down iron and chain mail armor or tools in smeltery

### ISSUE THREAD

**Issue by chillcat222** [SlimeKnights/TinkersConstruct#3761]
**Issue description:**
Cant smelt down vanilla iron and chain mail armor or tools in smeltery, They were all at full durability but still siad "this item cannot be smelted"

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:  1.12.2
* Forge: 14.23.5.2811
* Mantle: 1.3.3.42
* Tinkers Construct: 2.12

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
I am unsure, the only mods i have that have related files to tinkers construct are tinkers tool leveling, and construct armory, both up to date

**Comment by KnightMiner** [comment]
Chain mail does not melt down.

For iron, try with just Tinkers Construct I installed, the mod does not have to be related to break a feature. The recipe specifically is generated frim the vanilla crafting table recipes, so some mod that changes recipes could be wrapping/modifying it.

**Comment by SweetSugarSugar** [comment]
The equipment needs to be full health and only iron armor is accepted out of all the items listed.

**Comment by chillcat222** [comment]
> Chain mail does not melt down.
> 
> For iron, try with just Tinkers Construct I installed, the mod does not have to be related to break a feature. The recipe specifically is generated frim the vanilla crafting table recipes, so some mod that changes recipes could be wrapping/modifying it.

Okay, the issue persists with only Tconstruct installed

**Comment by chillcat222** [comment]
I am unable to smelt down any tools or armor, yes there is lava in the smeltery tank, yes the smeltery is constructed properly, yes i am using the latest version of Tconstruct, no I'm not using any cracked software.

**Comment by chillcat222** [comment]
The only items i am able to smelt down are nuggets, ingots, and blocks, this is with just mantle and Tconstruct installed.

**Comment by SweetSugarSugar** [comment]
Can you give a screenshot?

**Comment by KnightMiner** [comment]
Fixed in the last build for pickaxes/shovels/etc
