### ISSUE TITLE
Request Export Registered tool Stats

### ISSUE THREAD

**Issue by Colton-Slayden** [SlimeKnights/TinkersConstruct#3763]
**Issue description:** I think it would be neat to be able to export all stats of the registered tools. This would allow for better planning of tools. Without the need of scrolling through tons of pages

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

**Comment by bonii-xx** [comment]
That's not how tinkering works ;P
