### ISSUE TITLE
Question since you guys turned off Curse post page ability.

### ISSUE THREAD

**Issue by SirTwsted** [SlimeKnights/TinkersConstruct#3765]
Why Slime Boots, can not be combined with Armor boots, and have an activation button,
when wanting to use the Slime bouncy feature of the slime boots when needed.??

I would love to be able to combine Slime Boots with Armor boots and have the feature of both items.
because if I use slime boots, I lose Armor because Im not able to wear armor boots.

**Comment by bonii-xx** [comment]
Yup, that's their tradeoff. They're designed to be that way.
