### ISSUE TITLE
Vanishing blocks

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#3766]
**Issue description:**
https://github.com/Modpack-Support/Beyond-The-Void-2/issues/74
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge:  14.23.5.2815
* Mantle: 1.12-1.3.3.42
* Tinkers Construct: 1.12.2-2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

**Comment by KnightMiner** [comment]
This is definitely not a Tinkers Construct bug, I have never heard of our blocks causing chucks to not render. Please answer the last question you skipped by finding a minimal set of mods required to produce this bug.

**Comment by KnightMiner** [comment]
Closing for lack of answer on the last question, and as the poster seems to have deleted their account.
