### ISSUE TITLE
Rendering Block Entity Error

### ISSUE THREAD

**Issue by Disenfranchised** [SlimeKnights/TinkersConstruct#3768]
When items are being smelted and the smeltery is broken, creates a Rendering Block Entity error.
I can't reconnect to the server where the issue occurred. I do remember I was pouring gold to make a cast, and I went to break a hole into the smeltery for another drain. That's when I crashed.

The mod pack I am using is All The Mods 3 completely unmodified

https://pastebin.com/GWfEhKDd
**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2768
* Mantle: mantle-1.12-1.3.3.39
* Tinkers Construct: TConstruct-1.12.2-2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
EDIT: Cannot be reproduced with or without mods. I'm unsure where to go from here however

**Comment by bonii-xx** [comment]
Try reproducing with the latest version and without coremods.

**Comment by KnightMiner** [comment]
Closing as you can no longer reproduce, probably just a random issue with concurrent modification, which there is not much that can be done about that.
