### ISSUE TITLE
I don't know why but this started happening today

### ISSUE THREAD

**Issue by border999** [SlimeKnights/TinkersConstruct#3770]
Crash before startup. Asking if there is a way in your config or anything that I missed to get this to stop. 
These mods were fine with each other yesterday.
https://paste.dimdev.org/urayifedam.mccrash
* Minecraft: 1.12.2
* Forge:  1.12.2 - 14.23.5.2814
* Mantle:  Mantle-1.12-1.3.3.42
* Tinkers Construct:  TConstruct-1.12.2-2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
I've tried removing the configs for those mods to see if that was the problem, crashed before it even got to that point.

**Comment by KnightMiner** [comment]
You've got two add-ons registering the same part type "plate", Extra Botany and Construsts Armory. Issue on one of their sides.

**Comment by border999** [comment]
https://pastebin.com/EBEKmdry
Dude, you're API is really starting to look like it's breaking.

**Comment by bonii-xx** [comment]
It's not breaking, it is behaving exactly as intended: Preventing multiple mods from registering the same materials.
