### ISSUE TITLE
"Infinity" enchantment cannot be applied to Xbows, Longbow

### ISSUE THREAD

**Issue by GregariousJB** [SlimeKnights/TinkersConstruct#3772]
**Issue description:**
Perhaps this is intentional since I'm new to modpacks, but I don't like managing ammo and got excited to try Infinity on a new crossbow. The anvil didn't accept the crossbow + enchantment book, and neither for the Longbow. Haven't tried a Shortbow yet. The enchantments are done with enchantment books made by the "Enchanter" station from Ender IO, in case that's relevant.

**Versions:**
* Minecraft: 1.12.2
* Tinkers Construct: 2.12.0.115
* Project Ozone 3 v3.0.38

**Comment by SweetSugarSugar** [comment]
Tinkers' Tools can't be enchanted and having enchantments on them will have no effect.

**Comment by GregariousJB** [comment]
Crap, sorry. I could've sworn I enchanted a Tinkerer tool earlier. Closing.
