### ISSUE TITLE
Can't Drop Weapons/Tools

### ISSUE THREAD

**Issue by Tatu098** [SlimeKnights/TinkersConstruct#3774]
**Issue description:**
Whenever a tinkers weapon/tool is dropped, it seems to duplicate a huge amount of that weapon/tool and ultimately causing immense FPS drops for the players in the server. If you leave and join back, it disappears, but it means that we can't drop any weapon/tool. The duplicates cannot be picked up, only the original weapon/tool can be picked up. It's a huge issue for the players in my private server.
**If crashed, link to crash report (use a site such as pastebin):**
No server crashes, only user.
**Versions:**
* Minecraft: 1.12.2
* Forge: Forge-1.12.2-14.23.5.2768
* Mantle: Mantle-1.12-1.3.3.42
* Tinkers Construct: TConstruct-1.12.2-2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
We have 50 mods on the server, but none seem to conflict with Tinkers. Here's a list:

Baubles 1.12-1.5.2
BetterFps-1.4.8
Bookshelf-1.12.2-2.3.575
Botania+r1.10-360
CodeChickenLib-1.12.2-3.2.2.353
CraftStudioAPI-1.0.1.95
CustomNPCs-1.12.2(30Jan19)
CyclopsCore-1.12.2-1.0.4
DoomLikeDungeons-1.12.3
DynamicSurroundings-1.12.2-3.5.4.3
Electroblobs+Wizardry++4.1.4
EvilCraft-1.12.2-0.10.69
ExtraSpells-1.12.2-1.0.3
ForgeMultipart-2.6.1.81
Forgelin-1.8.2
Galacticraft-Planets 4.0.2.190
GalacticraftCore-4.0.2.190
HuntingDimension-1.12.2-1.0.37
InventoryTweaks-1.64+dev.146
LuckPerms
Mantle-1.12-1.3.3.42
MicdoodleCore-4.0.2.190
MrTJPCore-2.1.3.35
Nucleus
OreLib 3.5.2.2
ProjectRed 4.9.1.92-Base
ProjectRed 4.9.1.92-Compat
ProjectRed 4.9.1.92-Lightning
ProjectRed 4.9.1.92-World
SeedsForWizardry 1.0
ShadowMC-3.8.0
TConstruct -1.12.2-2. 12.0.115
TinkerToolLeveling-1.1.0
Animania-1.6.2
Gravestone-1.10.1
IceandFire-1.6.1
Leveluphp-1.4.0
llibrary-1.7.14
spongeforge
tinkersjei-1.0
tweakersconstruct-1.12.2-1.3.0

**Comment by SweetSugarSugar** [comment]
Are you using anything like OptiFine?  Also is it a vanilla forge server?

**Comment by Tatu098** [comment]
> 
> 
> Are you using anything like OptiFine? Also is it a vanilla forge server?

I am not using OptiFine and neither is anyone else in the server. It is a spongeforge server.

**Comment by KnightMiner** [comment]
Test in single player and on a normal server. Also try on the sponge server with fewer mods, just because the mod is not related to tinkers does not mean it cannot break stuff (especially with core mods)

**Comment by KnightMiner** [comment]
Closing for lack of response, reproduce with a definitely mod list and we will look into this, but for now it seems a coremod is breaking your stuff.

**Comment by leelawd** [comment]
I just ran into this issue on the Project Ozone 3 modpack

**Comment by KnightMiner** [comment]
That really does not help unfortunately, a mod pack with 100ish mods is not closer than a list of 50. We need to narrow it down to a minimal list to reproduce.
