### ISSUE TITLE
[1.12.2] [addon] can't melt Material

### ISSUE THREAD

**Issue by ToMe25** [SlimeKnights/TinkersConstruct#3775]
**Issue description:**
I have made a addon for this Mod, it is named "ToMeTinkers", but for some Reason one Material can't be molten. I was able to melt the Material earlyer but since some time i can't melt it.
I used this to register the meltable Items: 
```java
mat.addCommonItems("CrystalMatrix");
matInt.setRepresentativeItem("ingotCrystalMatrix");
```
and as it has the Right Item in the Book and was meltable earlyer i am pretty sure the Item is registeres as "ingotCrystalMatrix".

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.43
* Tinkers Construct: 2.12.0.116

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
No. it can not be reproduced with just Tinkers Construct.

**Comment by KnightMiner** [comment]
Did you register your materal? And did you register a material integration for it? The recipe are not automatic, they go in registries

**Comment by ToMe25** [comment]
@KnightMiner I do register a Material and a MaterialIntegration for that Material.
I have other Materials in the same Mod(close to identically registered) and they do all work.
Also if i put the Material with a Bucket in the Smeltery i can cast Parts out of it. I just can't cast/smelt Blocks/Ingots.

**Comment by KnightMiner** [comment]
Are your blocks and I got registered in the oredictionary? Since you have other materials working it's pretty clear there is a user error on this one, so find what you did differently

**Comment by ToMe25** [comment]
The Items are in the OreDictionary.
I checked that multiple times and the Method 'matInt.setRepresentativeItem("ingotCrystalMatrix");' also uses with the OreDictionary and works.
Also as i allready sayed in the first Message it was working earlyer and i think i changed nothing on this Part of the Mod.

**Comment by ToMe25** [comment]
I am not completely sure but i think it has stopped working after updating Tinkers Construct, thats why i made this Issue here.

**Comment by KnightMiner** [comment]
Find what is different or find a different version that it worked in, you just saying you think it worked before gets us no where. Find when it worked before or explain what the differences in registration are.

**Comment by ToMe25** [comment]
1. I have tested it but i have no build version with working Crystal Matrix Smelting.
2. If you want i can comment the Source of the Registering Class, but i have searched long time for differences and found none except for the changed OreDictionary names.

**Comment by bonii-xx** [comment]
Your best bet is to debug the code where the melting registering happens. Put a conditional breakpoint for your material, and see if it's called at all.. and if not, where it stops being called.

**Comment by ToMe25** [comment]
Do you mean my code where i register the OreDict stuff or the Tinkers Code where it registeres the Smelting recipe? If you mean my Code: I have done something similar by adding a Log output to tell my what Items are registered with the used OreDictionary Name directly before and after the registration.
If you mean the Tinkers Code i could try it, but i would first look if the recipe is registered at postInit because i allready have some Smelting recipe checks there for something different.

**Comment by ToMe25** [comment]
@KnightMiner @bonii-xx Thank you both i figured out something changed a part of my code to lower only case, but the OreDict needs to contain upper case Chars.
