### ISSUE TITLE
crafting crashes

### ISSUE THREAD

**Issue by SpGilbert** [SlimeKnights/TinkersConstruct#3776]
**Issue description:**
Crashes when you craft an item in the players inventory for the 1st time with items in tcon or have compatibility with tcon 
**If crashed, link to crash report (use a site such as pastebin):**
https://paste.dimdev.org/ajahowamew.mccrash
**Versions:**
* Minecraft: 1.12.2
* Forge: latest 2815
* Mantle: 1.3.3.42
* Tinkers Construct: latest 115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
not sure but it will only crash the 2x2 crafting grid in the player's inventory and not a crafting table.

**Comment by KnightMiner** [comment]
Please reproduce with fewer mods. This looks like a generic broken recipe, so I fail to see from the crash how Tinkers is involved.

**Comment by KnightMiner** [comment]
Closing for lack of response, as the issue does not appear to be caused by our code.
