### ISSUE TITLE
[LOW] Terminology

### ISSUE THREAD

**Issue by RolanDecoy** [SlimeKnights/TinkersConstruct#3778]
**Issue description:**
The term 'Drawspeed' is confusing, since in practice the higher this number is, the longer it takes to draw. Therefor 'Drawtime' would be more appropriate and less confusing.

**Versions:**
Any & all.

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Not a bug, just a note for improvement and clarification of the manual & interfaces.

**Comment by laz2727** [comment]
I think it was Draw Time back in 1.7. Don't see why it was changed.

**Comment by EnderofGames** [comment]
Came here to open this, glad to see it was already opened. I find myself explaining this to others a lot, many times _after_ they construct a weapon.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. I will ensure 1.18 gets more clear names for this.
