### ISSUE TITLE
I would like to see the integration of AOA and Tinker construct

### ISSUE THREAD

**Issue by LXNAmazing** [SlimeKnights/TinkersConstruct#3780]
I would like to see the integration of AOA and Tinker construct.
Twilight Forest have this integration.
I am just want use Tinkers Survival in my modpack.
I see AOA and Tinker construct integration on 1.7.10 in ExtraTIC addon.
I think tinker construct tools better vanilla tools.

**Comment by KnightMiner** [comment]
We do not natively add integration, for instance Twilight Forest adds their own integration. Additionally, we no longer support 1.7.10, nothing new will he coming to that version.
