### ISSUE TITLE
Modifier is already applied on this attribute.

### ISSUE THREAD

**Issue by Slayer5934** [SlimeKnights/TinkersConstruct#3781]
**Issue description:**
Modifier is already applied on this attribute.

**If crashed, link to crash report (use a site such as pastebin):**
https://paste.dimdev.org/eyotakuzov.mccrash

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.42
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
I'm not sure, this is in a very large modpack called Tekxit 3. All the user knows is he thinks he had spiky applied to a broadsword and a battlesign, and he was being attacked by a spider in The End. He removed his entire playerdata file and the game still crashed, I got him to delete the entire dimension (The End) and it was able to start again.

**Comment by bonii-xx** [comment]
Hm, looks like the damage dealing from the spiky trait has an issue. It might have to do with having spiky on both tools. It's entirely possible that nobody has ever done that up to now.

**Comment by Slayer5934** [comment]
Upon trying to reenact the same scenario to strike up a crash, I went back into the crash log posted here, and noticed the the cave spider that was attacking him had the "Vengeance" attribute from infernal mobs which quote "Reflects a portion of all damage done. Reflected damage will apply other on-damage abilities like blastoff and wither."
I believe it could be related. :)

**Comment by bonii-xx** [comment]
Ah yes. Yeah it's quite problematic to deal damage when you receive damage due to how the attribute system works. Iirc we take care of our own code calling it multiple times, but I don't think we can handle other mods calling it before.

**Comment by Slayer5934** [comment]
You can talk with AtomicStryker about possible solutions on your or his end of things, he responds pretty fast usually. His issue page is here: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues

Let me know if I can do something to help as well, I'm the current Chococraft dev and I have "some" knowledge :P
