### ISSUE TITLE
Tinkers furnace bypass protection

### ISSUE THREAD

**Issue by felipeleite5w** [SlimeKnights/TinkersConstruct#3782]
**Issue description:**
Im using Grieffprevention to protect claims, but everybody can use the tinkers furnace and steal everything so what should I do?
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.7.10
* Forge: 7.10.99.99
* Mantle: 0.3.2b
* Tinkers Construct: 1.8.8

I think this happens in all versions 

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

**Comment by felipeleite5w** [comment]
to reproduce this you will need a protection plugin or mod

**Comment by bonii-xx** [comment]
You'll have to ask the people from Griefprevention, since we don't know what they're doing to protect things.

**Comment by felipeleite5w** [comment]
They use protection from building (right click) but the tinkers furnace is impossible to be protected...

**Comment by bonii-xx** [comment]
Right click behaviour for the furnace is the same as any other block. My guess is they're special casing things. Anyway, without knowing how they prevent the interaction there's nothing we can do.

**Comment by KnightMiner** [comment]
Closing for lack of response. Feel free to reply if you can give more information on how the protection plug handles things, but right now it sounds like a bug with the anti-grief plugin you use.
