### ISSUE TITLE
Mekanism + Tinkers Construct crash

### ISSUE THREAD

**Issue by kragnoth** [SlimeKnights/TinkersConstruct#3786]
https://github.com/dizzyd/Mekanism/issues/46

Link to relevant Mekanism issue on the fork branch.

**Comment by KnightMiner** [comment]
That is definitely not a Tinkers Construct issue, its just drawing a normal inventory item in a GUI in that crash. Chance the issue is #2776 as referenced, but in any case the issue said they fixed it on their side.

**Comment by kragnoth** [comment]
Thanks for looking at it, looks like it is indeed fixed on their end.
