### ISSUE TITLE
Ore duplication with thermal expansion

### ISSUE THREAD

**Issue by JotaEmePM** [SlimeKnights/TinkersConstruct#3787]
**Issue description:**
I have a strange bug, in Enigmatica 2 Expert. When I melted Osmium, I accidentally clicked on the cast and it disappeared, having a Hardened Fluiduct and a servo, it continues to generate ingots, even without having metal fluid in the tank.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2781
* Mantle: 1.3.3.42
* Tinkers Construct: 1.12.2-2.12.0.115
* Thermal Expansion: 5.5.3.41

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Thermal Expansion, and maybe Mekanism

https://imgur.com/a/xu2qyiv

**Comment by bonii-xx** [comment]
This is really weird, the casting table resets its state when it finishes casting, meaning it'd require the cast to find the ingot recipe again. It could be a clientside desync. Can you reproduce it? Otherwise this will be pretty impossible to find.

**Comment by KnightMiner** [comment]
@JotaEmePM any update on this?

**Comment by KnightMiner** [comment]
Closing for lack of response.
