### ISSUE TITLE
Give command gives 2x ammount of items

### ISSUE THREAD

**Issue by Maroxis** [SlimeKnights/TinkersConstruct#3788]
There is currently problem whenever i'm using give command with tinkers tools it gives me 2 items instead of 1.  
1 goes to my hotbar, 1 pops in front of me.

Here is example command i use for the item:

`/give @p tconstruct:bolt 1 0 {StatsOriginal:{AttackSpeedMultiplier:1.0f,Accuracy:0.5f,MiningSpeed:3.5f,FreeModifiers:3,Durability:1942,HarvestLevel:4,Attack:3.6f},Stats:{AttackSpeedMultiplier:1.0f,Accuracy:0.5f,MiningSpeed:3.5f,FreeModifiers:3,Durability:1942,HarvestLevel:4,Attack:3.6f},Special:{Categories:["no_melee","projectile","tool"]},TinkerData:{Materials:["reed","ardite","leaf"],Modifiers:[]},Modifiers:[{identifier:"breakable",color:-5579916,level:1},{identifier:"stonebound",color:-3063280,level:1}],Traits:["breakable","stonebound"]}`

Tested using commandblock since command is to long for chat. 
Item metadata was read and not modified from existing crafted item, tried to modify same result.

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2814
* Mantle: 1.12-1.3.3.42
* Tinkers Construct: 1.12.2-2.12.0.115

I have only tinkers installed (+ mantle), vanilla items works normally.

**Comment by KnightMiner** [comment]
This is MinecraftForge/MinecraftForge#2349, nothing we can do to fix, no longer an issue in 1.13.
