### ISSUE TITLE
[Suggestion] Mom's Spaghetti Ignore Hunger

### ISSUE THREAD

**Issue by ilhamfu** [SlimeKnights/TinkersConstruct#3789]
Just asking Mom's Spaghetti to be buffed little bit. It's really rare to find, but not really worth it,especially for adventurers player who really care about saturation instead of hunger bar. make it edible even hunger bar is full ( Like pams top tier food) is enough

**Comment by bonii-xx** [comment]
Might be worth it, up to a cap. Spaghetti already has very high efficiency though.

**Comment by ilhamsitok** [comment]
gotta admit, this is the best food while mining, especially when using vein miner. but for adventuring, or even boss battle, meh.

**Comment by KnightMiner** [comment]
Closing as no plans to implement on 1.12. The "tool" is already pretty strong
