### ISSUE TITLE
”Materials and You” book page progress resets after opening an inventory/GUI

### ISSUE THREAD

**Issue by Dimentive** [SlimeKnights/TinkersConstruct#3791]
**Issue description:**
If I open the “Materials and You” book, change the page, close it, and then re-open it, I’m on the page I was on when I closed it; however, when closing the book, opening any inventory or GUI (such as a chest or crafting table), and then re-opening the book, I am not on the page I was when I closed the book. When I do this, I always end up on the page showing the “Reinforced” modifier. I created a brand new Materials and You book just to see what would happen if I did this with a new book, and I just end up on the beginning of the book.

It seems like at some point, Tinkers’ Construct saved my progress when I was on the “Reinforced” page, which I was reading at one point, but then, it stopped saving the book progress, resetting to the that one page every time.

### Versions
* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), version 1.62
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Mantle:** 1.3.3.42
* **Tinkers’ Construct:** 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

I’m not sure if this is a mod conflict, although I assume that it can be reproduced with just Tinkers’ Construct installed.

**Comment by KnightMiner** [comment]
Want to test it with just Tinkers to make sure? This type of thing can easily be a conflict, such as some mod changing the way the player data saves.

**Comment by Dimentive** [comment]
All right, I’ll test it with just Tinkers’ Construct when I have time.

**Comment by KnightMiner** [comment]
While testing, make sure to test in the latest Mantle build, as that has some book fixes in it.

**Comment by Dimentive** [comment]
Closing, as I’m no longer having this issue using the latest version of Tinkers’ Construct and Mantle. 😄
