### ISSUE TITLE
[Suggestion] Remove or override embossment

### ISSUE THREAD

**Issue by Dimentive** [SlimeKnights/TinkersConstruct#3794]
![Tinkers’ error (cropped)](https://user-images.githubusercontent.com/34230933/54855799-07532280-4cf8-11e9-8755-69a2023718a4.png)

You currently cannot remove or replace an embossment and have to create a new tool if you accidentally embossed your item to get a trait that doesn’t work as expected, like I did.

It would be great if you could remove an embossment in some way—or simply override an existing embossment by embossing it again. Maybe there could be a penalty of an additional gold block to emboss an item a second time. Of course, the original embossed trait or traits would not remain on the tool or weapon.

**Comment by KnightMiner** [comment]
I discussed this with boni awhile back and he says embossment should be looked at as a modifier rather than like a part swap or a sharpening kit. This means that like when adding redstone or luck to your tool, adding an embossment cannot be removed or changed.
