### ISSUE TITLE
Patterns Unobtainable

### ISSUE THREAD

**Issue by NillerMedDild** [SlimeKnights/TinkersConstruct#3796]
**Issue description:**
The Stencil Table can no longer make Patterns of any kind. Everything looks normal, there's just never any output pattern available.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2781
* Mantle: 1.12-1.3.3.42
* Tinkers Construct: 1.12.2-2.12.0.123

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Unknown

**Comment by KnightMiner** [comment]
Unknown is not a valid answer to the last question. This is almost certainly caused by a mod conflict, so unless we know which mod is conflicting we can do nothing.

**Comment by NillerMedDild** [comment]
Alright, just a moment.

**Comment by NillerMedDild** [comment]
Reproduced with only Mantle, JEI and Tinkers' Construct.

**Comment by NillerMedDild** [comment]
Alright, definitely on my end then. Modpack is Enigmatica 2: Expert version 1.63.

**Comment by Axelandre42** [comment]
Did you solved your issue? We're having the same problem here...

**Comment by NillerMedDild** [comment]
Yep, the issue was NuclearCraft, updating it resolves the issue.

**Comment by bonii-xx** [comment]
It always amazes me how mods manage to break completely unrelated things.
