### ISSUE TITLE
Modifier conflict with Tool Sledge Hammer

### ISSUE THREAD

**Issue by AntoRod** [SlimeKnights/TinkersConstruct#3797]
**Issue description:**
When i use the Direct modifier (not tested with trait yet) on a Sledge hammer, it will break the block and teleport it in my inventory, plus it will drop the hammered version on the ground.
Also works with Width++ and Height++, Veinminer and OreEcavation.

**Versions:**

**Minecraft:** 1.12.2
**Forge:** 14.23.5.2808
**Mantle:** 1.3.3.42
**Tinkers Construct:** 2.12.0.115
**Thermal Expansion:** 5.5.3.41
**Ex Nihilo Creatio:** 0.3.7

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Needs EnderIO for the modifier to be activated; Ex Nihilo Creatio adds sledge hammer ?

**Comment by KnightMiner** [comment]
Sledge hammer is a Tinkers Complement feature, so this issue is not really Tinkers Construct's fault. Please report it to Tinkers Complement and Ender IO
