### ISSUE TITLE
Recipes can't be removed when multiple mods add the same fluid

### ISSUE THREAD

**Issue by EmosewaPixel** [SlimeKnights/TinkersConstruct#3798]
**Issue description:**
 When trying to remove melting recipes (with custom add-ons or CraftTweaker, it's the same method either way) when multiple mods have the same fluids (such as both Tinkers and Forestry having Glass) it simply doesn't work, whereas said recipes can simply be removed when only one mod adds the fluid. It also doesn't come down to the Tinkers version of the fluid registering first as that often times is the case.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2823
* Mantle: 1.12-1.3.3.42
* Tinkers Construct: 1.12.2-2.12.0.115

**Comment by KnightMiner** [comment]
Please post the code for your custom add-on, good chance you are not handling fluid delegates properly

**Comment by KnightMiner** [comment]
Closing for lack of response, we have not heard any other mods having this issue (notably crafttweaker) so its likely your addon doing things incorrectly.
