### ISSUE TITLE
“Finding new recipe for <player>” messages in console

### ISSUE THREAD

**Issue by Dimentive** [SlimeKnights/TinkersConstruct#3799]
**Issue description:** I’m constantly getting the following messages in the server console:
`[Server thread/INFO] [tconstruct]: Finding new recipe for Dimentive`

#### Versions
* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579)
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Tinkers’ Construct:** 2.12.0.123
* **Mantle:** 1.3.3.42

I never saw messages like this before I updated the modpack (which also updated Tinkers’ Construct). Are these messages in the log because I’m using an alpha test build of TiC?

**Comment by KnightMiner** [comment]
Yeah, debug method got left in the alpha. It's an alpha.

**Comment by Dimentive** [comment]
All right. I’m not sure why the modpack author updated to an alpha version of Tinkers’ Construct.

I’ll revert to the latest release version.

**Comment by KnightMiner** [comment]
Leaving this open for now so we remember to fix it before the release

**Comment by Dimentive** [comment]
Oh, all right.
