### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by RoSirius** [SlimeKnights/TinkersConstruct#3802]
**Question:** Which mods can bring the ores that do not generate naturally? (bronze, tin, aluminium, nickel,  silver, etc.) I'm trying to do a survival world with the TConstruct 2 tools.

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2768
* Mantle: Most recent
* Tinkers Construct: Most recent [R]eleased on CurseForge (TConstruct-1.12.2-2.12.0.115.jar)

**Comment by MaragretRLautzenhiser** [comment]
Thermal Foundation/Expansion, Embers, and Immersive engineering are three mods that add all of the listed ores (I assume by bronze you meant copper). Tech Reborn adds equivalent ores that require more complicated means of processing to produce the relevant metals.

**Comment by KnightMiner** [comment]
Maragret gave a pretty good list of mods that would work, I'll just add that the reason the ores were removed from the base mod is that an ore that is only used for low tier tools is not terribly useful, so I'd encourage choosing a mod that adds some content that uses the ores (immersive engineering is a personal favorite, embers has a style that might work better if you are not going for major tech mods)

**Comment by RoSirius** [comment]
> Thermal Foundation/Expansion, Embers, and Immersive engineering are three mods that add all of the listed ores (I assume by bronze you meant copper). Tech Reborn adds equivalent ores, some of which require more complicated means of processing to produce the relevant metals and thus are incompatible with the tinkers' smeltery.

I think it was the Chisel mod and Tinker's Construct mod working together to make a bronze tool forge, and thanks.

**Comment by bonii-xx** [comment]
> I think it was the Chisel mod and Tinker's Construct mod working together to make a bronze tool forge, and thanks.

Just as a side info, you can craft the tool forge out of any supported material, as long as it's present, since TiC integrates metal blocks into its recipe. So as long as you have a mod that adds bronze blocks you can make a tool forge out of it.
