### ISSUE TITLE
Recipe Issue

### ISSUE THREAD

**Issue by RoSirius** [SlimeKnights/TinkersConstruct#3804]
**Issue description:** Recipe error crashed my game

**If crashed, link to crash report (use a site such as pastebin):** **_https://pastebin.com/KP4j8pXV_**

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2768
* Mantle: Mantle-1.12-1.3.3.42
* Tinkers Construct: TConstruct-1.12.2-2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?** TConstruct 2 and EnderIO failure

**Comment by KnightMiner** [comment]
That is a bug with Ender IO, they are adding a broken recipe which would cause fluids to be deleted in the smeltery. Tell them to fix their code to not add that recipe.

**Comment by RoSirius** [comment]
> That is a bug with Ender IO, they are adding a broken recipe which would cause fluids to be deleted in the smeltery. Tell them to fix their code to not add that recipe.

I never updated the Ender IO version, it just happened now all of a sudden.

**Comment by KnightMiner** [comment]
If I remember correctly, one of the mods is blindly copying Thermal Expansion recipes to Ender IO, then Ender IO blindly copies them into smeltery recipes. They have had this issue for awhile, we just add the check because we were tired of people reporting that their smelteries were deleting fluids.

**Comment by RoSirius** [comment]
> If I remember correctly, one of the mods is blindly copying Thermal Expansion recipes to Ender IO, then Ender IO blindly copies them into smeltery recipes. Every once in a while that leads to an invalid recipe. They have had this issue for awhile, we just add the check because we were tired of people reporting that their smelteries were deleting fluids.

Ah, right, okay.
