### ISSUE TITLE
non decaying bounce cycle on congealed slime

### ISSUE THREAD

**Issue by Heyo13579** [SlimeKnights/TinkersConstruct#3805]
**Issue description: non decaying bounce cycle on congealed slime ive been bouncing on the slime to a consistent height of 2 blocks for the past 15 minutes with no signs of it stopping at any point, the only way to stop the bouncing to break the block or land on the edge of it. **

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 2823
* Mantle: 1.3.3.42
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

not sure if other mods are having any effect on the issue or not, im having this issue in a mod pack im currently developing called Guns N' Death on the curse and ATLauncher

 the mods list is as follows:

Tinkers' Survival (by wendall911)
Tiny Progressions (by Kashdeya)
FTB Library (by FTB)
FloodLights (by Keridos)
Ender IO (by CrazyPants_MC)
ZeroCore (by ZeroNoRyouki)
LibEx (by LogicTechCorp)
Actually Baubles (by Jacky1356400)
ShadowMC (by shadowfactsmc)
Hwyla (by TehNut)
Iron Chests (by progwml6)
NetherEx (by LogicTechCorp)
PlusTiC (by Landmaster_phuong0429)
Dynamic Lights (by AtomicStryker)
Mob Grinding Utils (by Vadis365)
McJtyLib (by McJty)
Actually Additions (by Ellpeck)
Ender Compass (by MrIbby)
LootBags (by Malorolam)
Hardcore Darkness (by lumien231)
Roguelike Dungeons (by Greymerk)
Ore Excavation (by Funwayguy)
Mouse Tweaks (by YaLTeR97)
Ore Excavation Integration (by BloodWorkXGaming)
OpenBlocks Elevator (by VsnGamer)
Inventory Pets (by Purplicious_Cow)
Techguns (by pWn3d_1337)
CXLibrary (by CubeX2)
Shadowfacts' Forgelin (by shadowfactsmc)
Realistic Torches (by ChaosTheDude)
Mantle (by mDiyo)
Advanced Rocketry (by zmaster587)
Custom Starter Gear (by brandon3055)
Extra Utilities (by RWTema)
Cucumber Library (by BlakeBr0)
CoroUtil (by Corosus)
WorldEdit (by sk89q)
Redstone Flux (by TeamCoFH)
Unlimited Chisel Works (by asiekierka)
Inventory Tweaks (by Kobata)
ConnectedTexturesMod (by tterrag1098)
Hardcore Questing Mode (by lorddusk)
JourneyMap (by techbrew)
Epic Siege Mod (by Funwayguy)
OpenBlocks (by OpenMods)
Silent Lib (by SilentChaos512)
Chisel (by tterrag1098)
Reborn Core (by modmuss50)
Chisels & Bits (by AlgorithmX2)
EnderCore (by tterrag1098)
Extreme Reactors (by ZeroNoRyouki)
CraftTweaker (by jaredlll08)
CodeChicken Lib 1.8.+ (by covers1624)
RFTools (by McJty)
Scaling Health (by SilentChaos512)
Potion Core (by Tmtravlr)
Clipboard (by shadowfactsmc)
ThutPerms (by patnevis)
BetterFps (by Guichaguri)
Immersive Engineering (by BluSunrize)
Biomes O' Plenty (by Glitchfiend)
Refined Storage (by raoulvdberge)
Mystical Agriculture (by BlakeBr0)
CreativeCore (by CreativeMD)
ComputerCraft (by dantwohundred)
OMLib (by Keridos)
Zombie Awareness (by Corosus)
Ender Storage 1.8.+ (by covers1624)
OpenModularTurrets (by Keridos)
Chunk-Pregenerator (by Speiger)
Baubles (by azanor)
LibVulpes (by zmaster587)
Tinkers' Tool Leveling (by bonusboni)
OpenModsLib (by OpenMods)
Wawla - What Are We Looking At (by Darkhax)
Random Things (by lumien231)
QuantumStorage (by Gigabit1011)
More Furnaces (by CubeX2)
Botania (by Vazkii)
DeathQuotes / Death Quotes (by andrenoel1)
Tinkers Construct (by mDiyo)
Thut Essentials (by patnevis)
Not Enough Items 1.8.+ (by covers1624)
Just Enough Items (JEI) (by mezz)
FTB Utilities: Backups (by LatvianModder)
FTB Utilities (by FTB)
Votifier - Forge Version | Voting Command (by UpcraftLP)
Just Enough Dimensions (by masa_)
Spartan Shields (by ObliviousSpartan)
MineTweaker RecipeMaker (by DoubleDoorDevelopment)
CoFH Core (by TeamCoFH)
CoFH World (by TeamCoFH)
Thermal Foundation (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Moar Tinkers (by Bartz24)
Project: Vibrant Journeys (by solis_nova123)

**Comment by KnightMiner** [comment]
This is by design, see #3597. There is a minimum height before it starts bouncing, but it theoretically can bounce you forever.

Side note, is it really so difficult to test in a pack with no other mods? Not sure is a terrible answer.
