### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by hurfy** [SlimeKnights/TinkersConstruct#3806]
when I leave the tool in the forge, and get out of it, my game crashes.

**Comment by hurfy** [comment]
the latest version of the mod, the rest of the information will provide later

**Comment by SweetSugarSugar** [comment]
Minecraft version?  Tinkers' version number?  Forge version number?  Crash log?

Also "latest version" will not help us narrow down your issue.

**Comment by KnightMiner** [comment]
Closing for lack of response, specifically no crash report which is 100% essential for crash issues.
