### ISSUE TITLE
Game crashing with latest tinkersConstruct version

### ISSUE THREAD

**Issue by Yzelast** [SlimeKnights/TinkersConstruct#3807]
**Issue description:**
Game crashed after installing latest mod version...
[https://pastebin.com/X158uL8C](url)
![Captura de tela de 2019-03-30 15-30-28](https://user-images.githubusercontent.com/8459626/55280829-653bc780-5301-11e9-9e10-d0bc9522f267.png)

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2824
* Mantle: 1.12-1.3.3.42
* Tinkers Construct: 1.12.2-2.12.0.133

**Comment by TheGoldenProof** [comment]
getting it too

**Comment by KnightMiner** [comment]
Yeah, slightly miscommunication caused the Tinkers build to be released without a new Mantle build. 09b9fcb addresses the issue.
