### ISSUE TITLE
[Suggestion] Shortcuts in Materials and You book

### ISSUE THREAD

**Issue by Dimentive** [SlimeKnights/TinkersConstruct#3809]
To save the player some time, it would be nice if you could, say, shift-click either arrow in the Materials and You book to move two pages at once instead of one page—and if you could, for instance, ctrl- or alt-click (or maybe there could be a different button altogether) to move to the previous or next index page (e.g., the “Modifiers” page).

That would be very convenient!

**Comment by KnightMiner** [comment]
The latest version of Mantle allows you to use the scroll wheel to pretty quickly turn pages. As for indexes, you can easily click the button that jumps to the beginning then click a new index.

**Comment by Dimentive** [comment]
I updated to the latest version of Mantle, and I’m loving the scroll feature!

As for the button that takes you to the beginning of the book, I’ve never noticed it. I feel pretty stupid. It’s so useful!
