### ISSUE TITLE
Crashing with Tinkers' Complement

### ISSUE THREAD

**Issue by Rynerik** [SlimeKnights/TinkersConstruct#3812]
**Issue description:** Whenever I attempt to place down a Melter from Tinkers' Complement my game immediately goes to "shutting down internal server" and I no longer have the ability to join said world. Not sure what is causing it as I know it works in other modpacks.

**Crash report:** https://paste.dimdev.org/ahacuyonul.mccrash

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2824
* Mantle: Mantle-1.12-1.3.3.49
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

* Tinkers' Complement: TinkersComplement-1.12.2-0.3.1

**Comment by KnightMiner** [comment]
So, the crash happens only with Tinkers Complement when placing a Tinkers Complement block. Do you think it might be a Tinkers Complement bug?

Try the latest alpha of Complement, if that does not fix it leave an issue on Tinker Conplements tracker.

**Comment by KnightMiner** [comment]
Cross linking for future readers: KnightMiner/TinkersComplement#40
