### ISSUE TITLE
Crash upon breaking tree with lumberaxe

### ISSUE THREAD

**Issue by Claytonol99** [SlimeKnights/TinkersConstruct#3813]
**Issue description:**
Hello all, I am just wondering, I have installed a few mods along with tinkers construct, and I have made an iron lumberaxe to chop trees down faster, I went to test it on a tree and the game crashed just as the block broke, I relaunched the game and went into the save file but straight away crashed again? I do not understand the crash reports just hoping someone can see if they can help
**If crashed, link to crash report (use a site such as pastebin):**
 Here is the link to the crash report https://pastebin.com/KnmRwR91
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.42
* Tinkers Construct: 1.12.2-2.12.0.123

**Comment by bonii-xx** [comment]
> at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:229)

Not related to lumber axe or TiC, it was just a coincidence that it broke at the same time. Remove damage indicators.

**Comment by Claytonol99** [comment]
Thank you very much boni i spotted that and took it out and it worked thank
you very much!

**Comment by bonii-xx** [comment]
No problem, you're welcome.
