### ISSUE TITLE
Dropping tools or armor causes them to turn into sticks

### ISSUE THREAD

**Issue by nmajask** [SlimeKnights/TinkersConstruct#3814]
Dropping tools or armor created through Tinkers Construct causes them to turn into sticks

Versions:
Minecraft: 1.12.2
Forge: 14.23.5.2824
Mantle-1.12-1.3.3.49
TConstruct-1.12.2-2.12.0.135

Mod List:
https://pastebin.com/uzmNQbUa

I have tried reproducing the issue with mods like Constructs Armory and PlusTiC that effect Tinkers Construct's tools but was unable to.

**Comment by KnightMiner** [comment]
Sounds like item stages causing this, there is no reason this would happen standalone.

**Comment by nmajask** [comment]
I found that is was a problem with Tweakers Construct and at least one other mod and also found that tools don't work with Realistic Item Drops

**Comment by KnightMiner** [comment]
Find out which mod is causing the issue and report it to them, our tools use a custom entity but use it properly, so good change the mod is not properly detecting that

**Comment by KnightMiner** [comment]
Closing as this appears to be an issue with another mod.
