### ISSUE TITLE
Crash my server

### ISSUE THREAD

**Issue by SeagalKru** [SlimeKnights/TinkersConstruct#3816]
[crash-2019-04-07_10.49.59-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3051323/crash-2019-04-07_10.49.59-server.txt)

**Comment by SeagalKru** [comment]
Server crash continues!
[crash-2019-04-12_11.20.24-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3072337/crash-2019-04-12_11.20.24-server.txt)
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/3072338/debug.log)
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/3072339/latest.log)
[screen.log](https://github.com/SlimeKnights/TinkersConstruct/files/3072340/screen.log)
[server.log](https://github.com/SlimeKnights/TinkersConstruct/files/3072341/server.log)

**Comment by bonii-xx** [comment]
You have vanilla slimes attacking things that crashes your game. In other words you have some coremod that messes things up. I'd start removing uncommon (core)mods until it stops. Not TiC related.
