### ISSUE TITLE
[1.10.2] Smeltery Will Not Form

### ISSUE THREAD

**Issue by bepis** [SlimeKnights/TinkersConstruct#3821]
**Issue description:**
Creating a smeltery of any size will not form. I have the controller and a tank on the same level and have tried clearing the inside of the smeltery of any invisible blocks by placing and mining cobblestone on the inside. I have removed all other mods and the issue persists with only TCon and Mantle.

![2019-04-12_13 08 31](https://user-images.githubusercontent.com/24402874/56061761-011cf880-5d30-11e9-8c80-5b8bb2b5725f.png)

**Versions:**
* Minecraft: 1.10.2
* Forge: 12.18.3.2511 OR 12.18.3.2488
* Mantle: 1.1.5
* Tinkers Construct: 2.6.5

**Comment by KnightMiner** [comment]
That is a seared furnace controller, not a smeltery controller. Its for a different multiblock.
