### ISSUE TITLE
[Suggestion] "Spiky" modifier pvp/pve behavoir config?

### ISSUE THREAD

**Issue by Aphrodite2430** [SlimeKnights/TinkersConstruct#3822]
i'm currently developing a multiplayer adventure pvp rpg modpack, the "spiky" modifier (cactus) is great to add some strategy to the pvp part of the pack, but extremly unbalanced in the pve part, there is a way to make the modifier only effective on players and not on mobs

**Comment by KnightMiner** [comment]
@Aphrodite2430 can you give more information on how this is imbalanced? In my experience, spiky is no different than vanilla's thorns, especially since the modifier requires being on a battle sign meaning its not constant (the player can just hit around the shield)

**Comment by Aphrodite2430** [comment]
i'm making a heavy pve server, with dungeon etc. if i put a mob in front of a player the mob constantly try to attack the player, the player just keep up the battlesign and the mob slowly kill himself with recoil, the battelsign does not "go on cooldown" and absorb all the damage, with the right material it doesn't break making the pve part a joke.
The pvp part is fine, if they block they can't attack and they can still be hitten from behind.

**Comment by KnightMiner** [comment]
Spiky will be readdressed in 1.16, but no plans to change how 1.12 traits work at this time
