### ISSUE TITLE
[suggestion] tracer modifier

### ISSUE THREAD

**Issue by mtjohnson47** [SlimeKnights/TinkersConstruct#3823]
Tracer modifiers can be applied to arrows, bolts, and shurikens.  It will cause projectiles fired to have a glowing effect applied to them.

I suggest the modifier be a glowball, gunpowder, and fire charge.  Each time they're added would increase the tracer time, 1 glowball/gunpowder/fire charge would be 2 ticks, increasing by 1 each time for a max 10 seconds (200 ticks).

**Comment by KnightMiner** [comment]
No plans to add this to 1.12, and 1.16 removed TiC arrows
