### ISSUE TITLE
Bypass Banitem plugin pickaxe right click

### ISSUE THREAD

**Issue by felipeleite5w** [SlimeKnights/TinkersConstruct#3824]
**Issue description:**
If someone uses the right click ability he will be able to bypass banitem plugins and the player will be able to put any banned blocks in the world
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1614
* Mantle: latest 1.7.10 
* Tinkers Construct: latest 1.7.10

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** you will need any ban item plugin

**Comment by KnightMiner** [comment]
1.7.10 is no longer supported, so unfortunately we have no plans to address this. 1.9+ solved this by using the new vanilla offhand instead of the special right click behavior.
