### ISSUE TITLE
Recipe UI not visible in inventory/crafting station 1.12.2

### ISSUE THREAD

**Issue by Chomasterq** [SlimeKnights/TinkersConstruct#3825]
When crafting or opening the inventory, the recipe section and Tinkers Construct tabs are absent, making survival harder/impossible to play. 

* Minecraft: 12.2.2
* Forge: 12.2.2
* Mantle: 1.3.3.42
* Tinkers Construct: 12.2.2

This issue also arises with Galacticraft, which I understand shares the framework for this part. Older versions give the same problem.

![mcbug2](https://user-images.githubusercontent.com/49672958/56247272-3c8e2e80-6072-11e9-84f2-6b3c4bd02c00.png)

**Comment by KnightMiner** [comment]
Please clarify this issue. First off, what do you mean by Tinekrs Construct tabs? If you mean the ones added to the player inventory, we have no had those since 1.7, feature is removed

Secondly, by recipe section, do you mean recipe book or JEI?

**Comment by Chomasterq** [comment]
recipe book works fine. probably JEI. I'm not a coder. But the interface allowing you to see all the mod objects and the materials to make them when opening the inventory/crafting menu, taking up the whole right half of the screen relative to my screenshot.

**Comment by KnightMiner** [comment]
Does it show up in any inventories? Do you have JEI installed?

**Comment by Chomasterq** [comment]
No not in any inventories, and all I have is the core .jar file(tinkers-construct-mod 12.2.2.jar).

**Comment by KnightMiner** [comment]
We do not add that feature, that is from another mod called [Just Enough Items](https://minecraft.curseforge.com/projects/jei), that link should let you download it.

Also, from the name of your Tinkers Construct jar, I am guessing you did not download it from CurseForge. The official downloads are [here](https://minecraft.curseforge.com/projects/tinkers-construct), we cannot account for files download on any other site.

**Comment by Chomasterq** [comment]
Thank you for the assistance!
