### ISSUE TITLE
Items ejected from smeltery when unloading then reloading area

### ISSUE THREAD

**Issue by DanielHeEGG** [SlimeKnights/TinkersConstruct#3826]
When item is placed in the smeltery and during the melting process, if the player goes to the nether then back, the items get ejected out of the smeltery and exists as items on the floor. (I tried both items that can be smelted, like iron, and those that cannot, like gunpowder).
Logging out then back in on a single player world seems to cause the same problem.
Reloading chunks (F3 + A) does not cause this problem.
If the area is chunk-loaded (by FTB utils), the problem does not happen.

Versions
* Minecraft: 1.12.2
* Forge: 14.23.5.2821
* Mantle: 1.3.3.42
* Tinkers Construct: 1.12.2-2.12.0.115

**Comment by bonii-xx** [comment]
That'd be because the smeltery unforms. Sounds like you have some other mod messing with chunkloading.

**Comment by KnightMiner** [comment]
@DanielHeEGG can you give us more details on how to reproduce? This does not happen in my testing. A minimal mod list would be a big part of this, does it happen with just Tinkers Construct?

**Comment by KnightMiner** [comment]
Closing for lack of response
