### ISSUE TITLE
Beheading Does Not Effect Headcrumbs Mobs

### ISSUE THREAD

**Issue by JakeOTwitch** [SlimeKnights/TinkersConstruct#3828]
**Issue description:**
I've been testing beheading on Headcrumbs mobs and the level of beheading appears to have no effect on the chance for a head to drop (but I can get heads to drop using a regular sword with looting on it, just at a very small chance). I'm unsure if this problem should be addressed here or with the devs of Headcrumbs so I apologize if this is in the wrong place. 

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2831
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

**Comment by KnightMiner** [comment]
Technically, this is on both sides, but we need to do something on our side first so headcrumbs can hook into it. I am looking into this right now.

**Comment by KnightMiner** [comment]
Closing as the latest version has an API that headcrumbs can use and I talked to the dev about code implementing this on their side.
