### ISSUE TITLE
Small Enhancement: Don’t display Damage on Squeaky Tools/Weapons.

### ISSUE THREAD

**Issue by SirAron111** [SlimeKnights/TinkersConstruct#3830]
Exactly as the titles already says tats all I think if a tool has Squeaky shouldn’t display that it has damage if it doesn’t do damage. I gave in my Modpack a Starting mattock but made it Squeaky so it can’t be used for combat only for harvesting etc but people get so confused as they don’t know why it doesn’t do damage when there is a blue number telling them it does 4.5 DMG. (It should display something like damage Squeaky sound or no tool damage due to Squeaky) Some even thought it was a bug and stopped Playing.

**Comment by Nightcaste** [comment]
I would suggest _changing the listed damage to zero_, rather than _not listing damage at all_ because then people are just going to start posting bug reports that their squeaky tool is missing stuff on the tooltip and does no damage.

**Comment by KnightMiner** [comment]
This will not be trivial to change on 1.12 so unlikely a later build will fix this. On 1.16 I have plans to support adjusting the displayed stat tooltip, but as we lack anything with this interaction this bug currently does not happen, so going to close this.
