### ISSUE TITLE
Ugh

### ISSUE THREAD

**Issue by dalekfan** [SlimeKnights/TinkersConstruct#3832]
The mod config resets itself whenever I start Minecraft up again. It basically nullifies all the changes I make to it, which also keeps Slime Islands spawning in other dimensions.

**Versions: 2.12.0.135**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

Configs shouldn't be effected like this by other mods.

**Comment by KnightMiner** [comment]
Please post a copy of your config before it reverts itself (use a site like pastebin), the config revering means Forge detected something invalid in your config, most likely you are separating the dimension IDs with commas which is invalid

**Comment by KnightMiner** [comment]
Closing for lack of response, I assume what is happening is you have something invalid in your config, which Forge automatically deletes, so nothing we can do without seeing the config pre-revert
