### ISSUE TITLE
Can't use the casts at all that require a smelted ore like cobalt

### ISSUE THREAD

**Issue by ArmoredDrake1** [SlimeKnights/TinkersConstruct#3835]
**Issue description: Can't do anything using smelter can't place a stone axe head for example in the casting table pour the material to make a cast it never dries I get one from creative and I try pour cobalt in the cast but it stops pouring instantly after I right click it

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue. 
![image](https://user-images.githubusercontent.com/49134083/56488347-7bfcc500-6521-11e9-8249-6aa7a59e4ad4.png)

**Comment by bonii-xx** [comment]
Try reproducing with only TiC and Mantle.

**Comment by KnightMiner** [comment]
Closing for lack of response
