### ISSUE TITLE
negative friction with slime boots and cyclic mod bouncy pad

### ISSUE THREAD

**Issue by Janeq189** [SlimeKnights/TinkersConstruct#3838]
There is a bug with slime pad (cyclic) "bouncy" effect and slime boots (tinkers construct).

The bouncy effect negates any friction you have while in air, and the slime boots do the same thing, but when they are used both at once, than you have "negative friction", this means that you accelerate VERY fast. I used it on superflat world and got to world border (30000000 blocks) in about 2 minutes (i have a slow computer so most of it was loading).

ps. i also used a slow falling potion to avoid obstcles that randomly generate and it may have a some effect on it but works without it.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* Mantle: 1.3.3.49
* Tinkers Construct: 1.12.2-2.12.0.135

you need cyclic mod.
i discovered it on enigmatica 2:expert

**Comment by bonii-xx** [comment]
There is no way of knowing if the player is affected by other effects manipulating movement. Can't fix.
