### ISSUE TITLE
Crash when putting/crafting flux storage in a tinkers crafting table 

### ISSUE THREAD

**Issue by PilLFIENd1** [SlimeKnights/TinkersConstruct#3840]
Crashing game/client when using flux storage containers in a tinkers table (drag dropping/splitting item stack)

[crash-2019-04-24_20.49.23-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3113104/crash-2019-04-24_20.49.23-client.txt)

Sky Factory 4.0.2
minecraftVersion": "1.12.2
forge-14.23.5.2831
Mantle-1.12-1.3.3.49
TinkersComplement-1.12.2-0.4.0

It can be reproduced definitely on SkyFactory 4.0.2 (not sure if other mod pacts are required IE, if reproduceable with just fluxnetworks-1.12.2-3.0.19-21 and TinkersComplement-1.12.2-0.4.0 just by them selves)

So this just started happening today, deleted mouse tweaks mod and had this to say. Playing the pack Sky Factory 4.0.2.
In my inventory/extended inventory/crafting table inventory i have no issues, i can reproduce it multiple times when i use a tinkers construct crafting table (i was testing it with the slab tinkers crafting table and have yet to try with a normal tinkers crafting table) with flux storage containers.

With some trouble shooting, with some admins and myself it seems it might have to do with something with flux storage containers and tinkers work tables not liking it, as well as some other items (not sure which) and the items rendering in the crafting table? but it is confirmed that it involves tinkers crafting tables and flux storage.

"The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.UnsupportedOperationException: Cannot cast map to int"

reinstalled the newest version and got this

The game crashed whilst handlemouseclick() threw an exception when called from mousetweaks.
Error: java.lang.reflect.InvocationTargetException

Already looked at and through the mouse tweaks Github.
https://github.com/YaLTeR/MouseTweaks/issues/15
They seem to imply that its not mouse tweaks but either flux storage or tinkers construct

**Comment by KnightMiner** [comment]
This looks like a CraftTweaker bug, the only thing our code is doing is calling the crafting recipe method. I highly doubt flux storage is to blame based on the stacktrace.

Can you confirm if this happens in other crafting tables? Also, can you answer the question you deleted from the issue template: find a minimal mod list to reproduce. As it stands I see nothing in that crash that is our fault so without a minimal list there is nothing we can do.

**Comment by KnightMiner** [comment]
Closing for lack of response, likely a crafttweaker bug
