### ISSUE TITLE
Compatibility Issue: Quark Sorting causes Pattern Chest to eat patterns.

### ISSUE THREAD

**Issue by AshtonSnapp** [SlimeKnights/TinkersConstruct#3841]
**Issue description:** With patterns or casts in a pattern chest, trying to use the Quark mod's sorting feature will cause the pattern chest to consume patterns. Sorting again will make it worse. Reloading the world and/or the game will not fix the issue.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* Mantle: 1.3.3.49
* Tinkers Construct: 1.12.2-2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** Requires Quark r1.5-146 (which requires AutoRegLib 1.3-26)

This issue has also been reported to Vazkii and the other 64 people working on Quark.

**Comment by KnightMiner** [comment]
Fixed on Quarks size in Vazkii/Quark#1215. In the future please link issues when reporting to multiple mods so we can keep track of them better.
