### ISSUE TITLE
Part Builder not working

### ISSUE THREAD

**Issue by TheSexyYeti** [SlimeKnights/TinkersConstruct#3844]
![2019-05-02_20 32 10](https://user-images.githubusercontent.com/50222286/57115061-89ccfa00-6d1a-11e9-9ef0-7f887b65234a.png)

I'm trying to get a basic part to make the casts. But the part builder isn't letting me make anything. Cobblestone, stone, wood. Nothing seems to show up when trying to use basic materials

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* Mantle: 1.12-1.3.3.49
* Tinkers Construct: 1.12.2-2.12.0.135

**Comment by KnightMiner** [comment]
What other mods do you have installed? There are many different ones that restrict part building or that randomly break our GUI.

**Comment by TheSexyYeti** [comment]
I was making this pack for a server. Here's my entire list. 


ArchitectureCraft - ElytraDev Version
Armory Expansion
AutoRegLib
Bauble of UNdying
Baubles
Better Foliage
BetterFPS
BiblioCraft
Bookshelf
Buildcraft
Cathedral
ChineseWorkshop
Chisel
Clumps
CodeChicken 1.8.+
CoFH World
Computercraft
CraftStudio API
Creature Whisperer
CTD Core
Cyclops Core
Damage Indicators Mod
Dark Roleplay Core
Dark Roleplay Medieval
Divincis Vessels
Dawn of Time - Builder Edition
Decocraft2
Earthworks
Enchanting Plus
Enderstorage 1.8.+
Equivalent Integrations
EvilCraft
Expanded Equivalence
Extra Alchemy
Extra Bit Manipulation
Extra Utilities
Fairy Lights
Forge MultiPart CBE
Giacomo's Fishing Net
Hammer (Lib) Core
Hide Names
Hwyla
Industrial Craft
Instant Unify
Inventory Tweaks
lvToolkit
JJ Coat of Arms
JJ Coins
JJSkill
JourneyMap
Just Enough Items (JEI)
Keep Inventory
LibrarianLib
LLibrary
LunatriuscORE
Magic Psi
MalisisCore
MalisisDoors
McJtyLib
Mikes Mobs Library
Mo' Glowstone
Mo' Villages
Mouse Tweaks
MovingWorld
Mowzie's Mobs
Multi Mob Library
Multi-Pison
NotEnoughIDs
Pam's HarvestCraft
Platforms
Primitive Mobs
Project EX
Project E
Psi
PTRLib
Redstone Flux
SecretRoomsMod
Shadowfact's Forgelin
ShetiPhianCore
Signpost
Soul Shards: The Old Ways
Stackie
Thamcraft
Thaumic Equivalence
Thaumic JEI
Thermal Foundation
Tinker's JEI
Tinkers Construct
Tinkers' Tool Leveling
Torch Lever
Tree Chopper
Wawla - What Are We Looking At
Wearable Backpacks
Wireless Redstone CBE

**Comment by TheSexyYeti** [comment]
Disregard this post. I'm a fricking idiot. I should have read more in the book. I was trying to make a bow and arrow. Not realizing each type of weapon part needed different items to craft them.
