### ISSUE TITLE
Mekanism glowstone ingot

### ISSUE THREAD

**Issue by Brutalcreeper** [SlimeKnights/TinkersConstruct#3845]
**Issue description:**
I made a sword using glowstone ingots from mekanism and occasionally it will crash the server (not client tho) on hit of VANILLA mobs or so far as i can tell (my modpack contains lycanites mobs and has never crashed on attacking them) 
so far this has work on zombie pigmen and normal zombies seems more stable with skellys
the specific weapon i created was a katana and i believe its the illuminati buff from the glowstone in the sword but im not a professional
(IMPORTANT EDIT) this only works in survival mode i tried to test in creative and it never crashed but as soon as i dropped into survival it crashed on the first attack
im sorry if this is the wrong place for this 
**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/gnxNm7Aa
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2835
* Mantle: 1.3.3.39
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Mekanism version 9.4.13.349

**Comment by KnightMiner** [comment]
We don't add glowstone ingots as a material, it's probably added on mekenisms side if not a third party.

**Comment by Landmaster** [comment]
@Brutalcreeper Update PlusTiC and see if the issue persists.
