### ISSUE TITLE
server 1.12.2 crash

### ISSUE THREAD

**Issue by Cronosus** [SlimeKnights/TinkersConstruct#3847]
**Issue description:**
server crash after placin wooden hopper
**If crashed, link to crash report (use a site such as pastebin):**
https://paste.ee/p/Fz4Ty
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2812
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
crashing everytime (even when player tried to log-in again)

**Comment by KnightMiner** [comment]
This looks like a Bukkit crash. Please try answering the last question again and reproduce this with just Tinkers Construct, then try just Tinkers and Bukkit as that appears to be the other mod involved.

**Comment by Cronosus** [comment]
ok, reproduced only with TiC
https://paste.ee/p/UrnNs
place example furnace, on top wooden hopper, on top of it another wooden hopper, then insert somethink into the upper hopper... crash

not reproduced in SP, only on server

**Comment by KnightMiner** [comment]
Still have a few non-Tinkers Construct mods
```
        | LCHIJA | worldborder | 1.0.0             | World-Border-1.12.2-1.0.5.jar         | None      |
	| LCHIJA | worldedit   | 6.1.8             | worldedit-forge-mc1.12-6.1.8-dist.jar | None      |
```

**Comment by Cronosus** [comment]
well.. yeah, but i dont think those two affected it :D
https://paste.ee/p/U6HYI

**Comment by bonii-xx** [comment]
Looks like the paste is not valid anymore :/

**Comment by Cronosus** [comment]
i forgot about this issue, its more than monh already? :D 
looks like when serverticks stopped working, it causes this crash

for archive purpose:
[crash-2019-05-10_22.36.14-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3292924/crash-2019-05-10_22.36.14-server.txt)

**Comment by bonii-xx** [comment]
Yeah, not much time currently. It still is useful to have a crashlog to look at later, since it might hint at problems somewhere, even if it isn't directly related or is already fixed.

The crash happens inside the vanilla hopper logic (wooden hoppers are just vanilla hoppers with 1 itemslot). Will have to see if I can reproduce it on a local server, but I doubt it's something we can fix if it's logic related.
