### ISSUE TITLE
<1.12.2>{2.12.0.135} upgrading duplicate items (kettle server)

### ISSUE THREAD

**Issue by Cronosus** [SlimeKnights/TinkersConstruct#3851]
**Issue description:**
When upgrading tool in tool station (example pickaxe), tool is created and items not consumed, duplicating
**If crashed, link to crash report (use a site such as pastebin):**
not crash, but video here: http://cronos.4fan.cz/mc/2019-05-10%2020-46-41.mkv
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2812
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
caused on server, also reproduced only with TiC...  
on SP not reproduced
full modlist https://paste.ee/p/svqtM (but as i said, it dit with only TiC)

**Comment by KnightMiner** [comment]
What type of server are you running? That typically has a large effect on this type of bug.

**Comment by Cronosus** [comment]
ah sorry
looks like i resolved it ... ticking bug
