### ISSUE TITLE
[Feature Request] Rivers of blood in the Nether

### ISSUE THREAD

**Issue by JTBlum** [SlimeKnights/TinkersConstruct#3855]
Currently, blood works like water and instantly evaporates in the Nether. I'd like to be able to use it as a thematic element in the Nether, but if it still behaved like water it could cause problems. My suggestion is "boiling blood", where liquid blood in the Nether would behave like lava but possibly less damaging. I've not been into the code so I don't know how viable this is, but it seems like something that would be cool in the overworld too.

As far as terrain integration goes, I think it would be really cool to add ponds and islands like you do with the slime generation that can be expanded on by the player(s).

**Comment by bonii-xx** [comment]
Does not fit Tinkers' thematic. I'd suggest looking into custom block mods and custom worldgen, that way you can do it without coding.
