### ISSUE TITLE
Casting table glitch.

### ISSUE THREAD

**Issue by themotorhead30** [SlimeKnights/TinkersConstruct#3856]
Casting only adds 6mb to table but uses 144mb from smeltery.

* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

Unknown if it's a mod conflict causing this.

**Comment by KnightMiner** [comment]
This is definitely a mod conflict causing this. Part of the template you deleted told you to test that by trying the game with fewer mods.

**Comment by themotorhead30** [comment]
Found it to be a conflict with SmithsCore.

**Comment by KnightMiner** [comment]
In that case, please report the issue to SmithsCore and link it back here

**Comment by bonii-xx** [comment]
Archiving for Cleanup.
