### ISSUE TITLE
Endspeed prevents Shortbows from gaining exp from Arrows

### ISSUE THREAD

**Issue by Newominus** [SlimeKnights/TinkersConstruct#3859]
**Issue description:**
Using any kind of arrow with endspeed on it (having an endrod arrow shaft) prevents the shortbow from gaining exp. This is not the case for both Crossbows and Longbows, they gain exp normally from endspeed arrows.

Killing a pig with an Endspeed arrow/bolt grants:
8 exp to the Crossbow and 10 exp to the bolt
5 exp to the Longbow and 10 exp to the arrow
0 exp to the Shortbow and 10 exp to the arrow

For some reason this doesn't happen to shortbows with the prosperous modifier (not prosperity limbs) and copper shortbows (copper hybrids still dont give exp unless they have prosperous).

**Versions:**
* Minecraft: 1.12.2
* TConstruct-1.12.2-2.12.0.135

Tested on SkyFactory 4 version 4.0.5

**Comment by KnightMiner** [comment]
This sounds like a Tinkers Tool Leveling issue, please report to that tracker.
