### ISSUE TITLE
Blue Slime Saplings grows Congealed Green Slime trees

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#3861]
**Issue description:**
Blue Slime Saplings grows Congealed Green Slime trees

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.135	

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes
![2019-05-20_10 59 42](https://user-images.githubusercontent.com/7185104/58009297-695cb800-7aee-11e9-9763-0507577ff83c.png)
![2019-05-20_10 59 43](https://user-images.githubusercontent.com/7185104/58009298-695cb800-7aee-11e9-8b95-35d505a93a00.png)

**Comment by Landmaster** [comment]
Blue slime trees are *supposed* to grow green slime trunks. You get blue slime from the leaves, if I recall correctly.

**Comment by KnightMiner** [comment]
Landmaster is correct. The tree texture shows what type of slime and leaves you get, you see a green stem and blue leaves there.

Blue slime leaves may drop blueslime, or the mob is the best way to get slime.
