### ISSUE TITLE
Cant repair/refill bolt or arrow with Evil Infused Ingot. 

### ISSUE THREAD

**Issue by pikizin** [SlimeKnights/TinkersConstruct#3862]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12
* Forge: 14.23.5.2836
* Mantle: Mantle-1.12-1.3.3.49.jar
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135.jar

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Extra Utilities material.
The problem i cant refill arrow / bolt with Evil Infused Material(Like Ingot) in tool forget.
And sword, i cant repair with Ingot too...

Dont appear nothing in craft result.
![2019-05-24_14 16 56](https://user-images.githubusercontent.com/51034518/58374958-fa80c400-7f1e-11e9-8aef-2676d0aa31f7.png)
![2019-05-24_14 16 42](https://user-images.githubusercontent.com/51034518/58374960-010f3b80-7f1f-11e9-87e6-041657adc031.png)

**Comment by pikizin** [comment]
Add:
With sharpening kit i can repair, but in tool forge not.

**Comment by KnightMiner** [comment]
Sounds like a bug on extra utilities side, like they forgot to add the material. Does it work with other tools? Does it show in the materials and you book as a valid material for the metal?

**Comment by pikizin** [comment]
![2019-05-26_19 49 08](https://user-images.githubusercontent.com/51034518/58388037-60d51780-7fef-11e9-8865-f76251466fe6.png)
![2019-05-26_19 49 02](https://user-images.githubusercontent.com/51034518/58388038-60d51780-7fef-11e9-8e7e-ce45e3d20e72.png)
![2019-05-26_19 49 04](https://user-images.githubusercontent.com/51034518/58388039-60d51780-7fef-11e9-9af5-4c9bb1324b2e.png)
As you can see, with other material work perf.

Prob error from Extra Utilities.

**Comment by pikizin** [comment]
extrautils2-1.12-1.9.9.jar

Version from EXTRA utilities.

**Comment by KnightMiner** [comment]
Can you answer my questions I asked above? That will guarentee that this is an Extra Utilities issue if you answer them.

> Does it work with other tools?
> Does it show in the materials and you book as a valid material for the metal?

**Comment by pikizin** [comment]
Does it work with other tools?
Dont work with tools too. As you can see at image.
![2019-05-27_02 56 27](https://user-images.githubusercontent.com/51034518/58398315-16718c00-802b-11e9-96d4-f336fa71627c.png)

Does it show in the materials and you book as a valid material for the metal?
No, in Book is shard as you can see in image, should be this... i will test if with shard i can repair...
![2019-05-27_02 58 13](https://user-images.githubusercontent.com/51034518/58398434-6c463400-802b-11e9-9b46-a355a46db1e2.png)

**Comment by pikizin** [comment]
![2019-05-27_03 00 12](https://user-images.githubusercontent.com/51034518/58398492-97c91e80-802b-11e9-9ad1-0426aa3b8be4.png)
Yeah... the problem is Ingot are not in Book.

Work to repair with shard...

**Comment by pikizin** [comment]
Now, thinking about this, i guess was a option because material is much expensive, spending 1 ingot is 1/8 nether star, maybe for that developer choose Shard instead Ingot.

**Comment by KnightMiner** [comment]
No, shard is added for all tools automatically regardless of it they have an ingot. This is definitely a bug on extra utilities side. Thanks for testing it.

It looks like you reported it to Extra Utilities at rwtema/Extra-Utilities-2-Source#319, so I'll close this issue as there is nothing to do on our side
