### ISSUE TITLE
Dupe with Crafting Table

### ISSUE THREAD

**Issue by barbaratimson** [SlimeKnights/TinkersConstruct#3863]
### Issue description
Dupe with TiC Crafting Table, shulker box and minecart with hopper. (May work with other types of hoppers)

Minecraft: 1.12.2
Forge: 14.23.5.2836
Mantle: Mantle-1.12-1.3.3.49
Tinkers Construct: TConstruct-1.12.2-2.12.0.135

1. You need a construction with rails  placed like letter "U". With two ramps on the ends.

 2.On one side you need to place a Crafting Table (From TC). Not far from ramp. And on the other side you need to place a minecart with hopper.

 3.When you need a shulker box and paint.

 4. Combine shulker box and paint in Crafting Table. (Don`t take the result of crafting)

 5. Push the minecart and get in Crafting Table. Wait when minecart take items from this.

 6. Take the result of crafting (painted shulker box) with items inside.

 7.Take the items from minecart (unpainted shulker box and paint). Unpainted Shulker box will be with the same items as painted.

Dupe can be produced with all type of timed hoppers and etc. You just need to get into Crafting Table before it takes item from this. Also backpacks can be duped.

**Comment by barbaratimson** [comment]
UPD. All craftable items can be duped

**Comment by SweetSugarSugar** [comment]
Please answer the question you omitted.

**Comment by barbaratimson** [comment]
What question? I think i answered all the questions.

**Comment by KnightMiner** [comment]
The "can it be reproduced with just Tinkers Construct" question

**Comment by KnightMiner** [comment]
Closing for lack of response, in my testing hoppers cannot pull from our tables at all. Verify you are not using that one add-on that replaces the crafting station, might be there bug

**Comment by Strykus** [comment]
> 
> 
> UPD. All craftable items can be duped

you idiot
