### ISSUE TITLE
Blood causing fires when placed in More Cauldrons wooden cauldron

### ISSUE THREAD

**Issue by Gunner76th** [SlimeKnights/TinkersConstruct#3864]
**Issue description:**
While using the wooden cauldrons, placing blood in them is causing fires to be spawned in the world.
Link to bug report filed with More Cauldrons mod: https://github.com/Mrbysco/MoreCauldrons/issues/5

## Steps to Reproduce 
Place a wooden cauldron in the world (Any type will do, in so long as it is a wooden variant.)
image
![image](https://user-images.githubusercontent.com/5566872/58416319-29965300-804f-11e9-8400-b3863a57c529.png)

Take a bucket of blood and pour it into the cauldron
![image](https://user-images.githubusercontent.com/5566872/58416323-2e5b0700-804f-11e9-8306-b4a45d434224.png)

Observe the fires being spawned around and on the cauldron.
![image](https://user-images.githubusercontent.com/5566872/58416329-33b85180-804f-11e9-8114-9b92317dc5f0.png)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 2831
* Mantle: Mantle-1.12-1.3.3.49.jar
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135.jar

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Sky Factory 4 modpack from Twitch launcher version 4.0.5 
One thing that MrBysco noticed is that blood is showing to have a temperature of 420K which is higher than lava, even though when placed in the world blood behaves the same as water, even so far as to turn lava into obsidian. Since the blood is a thing added by TCon, I have created this bug report to cover all bases. 

Additional bug reports are filed with More Cauldrons and Sky Factory 4, links provided below:

https://github.com/Mrbysco/MoreCauldrons/issues/5

https://github.com/Darkosto/SkyFactory4Issues/issues/1024

**Comment by Gunner76th** [comment]
This is confirmed to happen with only the following mods installed:
Mantle 1.12-1.3.3.55
Tinkers Construct 1.12.2-2.12.0.135
More Cauldrons 1.4.3

All configs used are default, unedited config files. I have confirmed this issue exists by recreating it in a new single player world using only the mods listed above.

**Comment by bonii-xx** [comment]
"Fixed" on their side. Tbh I have no idea why blood is that hot. Should be the same as water. Probably an old copy'n'paste error.
