### ISSUE TITLE
Close old milestones

### ISSUE THREAD

**Issue by Xalaxis** [SlimeKnights/TinkersConstruct#3866]
Perhaps the [milestone list](https://github.com/SlimeKnights/TinkersConstruct/milestones?state=open) should be reviewed and old milestones closed?  For example, the ["Tinkers 2.3"](https://github.com/SlimeKnights/TinkersConstruct/milestone/8) milestone was for MC 1.9.

**Comment by KnightMiner** [comment]
Closed
