### ISSUE TITLE
Faucet Casting Issues, 1.12.2 (Detailed) (Also Suggestion)

### ISSUE THREAD

**Issue by RealiTerra** [SlimeKnights/TinkersConstruct#3867]
This may be an old issue, but it's bugging me, and I can't find any issues regarding this. I'm using mods that I chose to play privately and if there's some mod that I should be aware of, please tell me :<
Whenever I try to pour something out of the smelter into my casting table, the faucet stops momentarily every time. I tried placing it again. Nada. :< After the cast is full the progression of the casting material stops and stays there. I tried replacing the casting table and it's still the same.

Now something that may be considered is that I have the Constructs' Armory mod, meaning the Smiths Core is included in my mods. Also, when I try using any workstation, the material that I place bugs out and stuff doesn't read properly. I place 2 blocks separately in one slot and it still is just one according to the game. Buggy? Or maybe mods?

Hi Devs :3 can you integrate armors into your mod? :)

**Comment by SweetSugarSugar** [comment]
Please list mods involved.  Are you playing singleplayer or on a server?  If it's a server, is it running Sponge?  What version of Tinkers' Construct?  What version of Mantle?  What version of Minecraft?  Etc.  Without this information there is no way someone can replicate the issue and narrow it down.

Constuct's Armory is a different mod and is not maintained by SlimeKnight and you would report related issues to them.

Also as it has been stated in the FAQ (https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ), armor will not be added and suggestions are generally not taken.

**Comment by KnightMiner** [comment]
Closing for lack of information/response as you missed most things from the issue template.
