### ISSUE TITLE
1.12.2 client crash

### ISSUE THREAD

**Issue by zsn741656478** [SlimeKnights/TinkersConstruct#3868]
**Issue description: My client always be crash when I run in the world**

**https://paste.ubuntu.com/p/sDVW4fShtC/**

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2835
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.135

**I tried to remove all TC attached mod. But it still be crash.**

**Comment by KnightMiner** [comment]
What makes you think this is a Tinkers Construct issue? If you can reproduce it with just Tinkers Construct, please link a crash report with no other mods

**Comment by zsn741656478** [comment]
I try to remove the TC mod and the client can't crash again.

**Comment by KnightMiner** [comment]
I asked a second question, can you reproduce this with just Tinkers Construct? And if so, please attach a crash report with just the mod.

**Comment by zsn741656478** [comment]
I test it. TC can't compatible with foamfix. My friend's computer only 4g RAM. We mustn't remove the foamfix. :(

**Comment by KnightMiner** [comment]
Many packs include just the two mods, so I don't think there is an incompatibility. Try running an older version of foamfix, and post a crash report with as few mods as possible

**Comment by zsn741656478** [comment]
https://paste.ubuntu.com/p/6ptKWgdTrN/
Only TC and foamfix.

**Comment by zsn741656478** [comment]
And I found that not only foamfix. TC and many mods will be incompatible, and all the same error.
But. The foamfix is very important. I can remove the other mods in addition to foamfix.

**Comment by KnightMiner** [comment]
Try updating Forge, it looks like build 2832 had a change that could cause this type of crash. At least 2836 should fix the issue.

**Comment by zsn741656478** [comment]
OK. I will try to use 2838 later.

**Comment by zsn741656478** [comment]
https://paste.ubuntu.com/p/2fJC24rZDQ/
This is forge2838 + foamfix 0.10.3

I try to use 2838 now.

**Comment by zsn741656478** [comment]
Oh. The 2838 is ok. :) 
Thank you a lot.

**Comment by KnightMiner** [comment]
No problem
