### ISSUE TITLE
[Question/Request] Smeltery fuels other than lava?

### ISSUE THREAD

**Issue by Carnaxus** [SlimeKnights/TinkersConstruct#3869]
**Issue description:**
I keep seeing references to Thermal Foundation's Blazing Pyrotheum being usable as a smeltery fuel, but it refuses to work for me.  Am I just not doing it right or is pyrotheum not a smeltery fuel anymore?

I am using a Thermal Expansion creative tank and an EnderIO Ender Fluid Conduit to feed the smeltery tank.  I tried all three smeltery tanks.

For reference, the item I am trying to smelt down are EnderIO dark steel boots, which apparently require a temperature of 1171 degrees.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2837
* Mantle: 1.3.3.49
* Tinkers Construct: 1.12.2-2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
It cannot be reproduced with just Tinkers' because it is an interaction (or rather the potential lack thereof) between Tinkers' and Thermal Foundation.  To reproduce you will need at least Mantle, Tinkers', CoFH Core, CoFH World, CoFH Lib, Thermal Foundation, and Thermal Expansion (I'm not sure if pyrotheum will work correctly without TE installed even though it's technically added by TF).

P.S. Tinkers' Construct is one of my favorite mods.  I've been playing Minecraft since the official release (I preordered, but then forgot I'd done so :P), and Tinkers' has become an essential mod in every pack I make.  If I play a pack that doesn't have Tinkers', it feels incomplete to me.  However, with all the mods people tend to put into their modpacks, there are more and more items that require a higher temperature than lava can give to be smelted down in the smeltery, and not being able to put anything but lava in as a fuel makes those recipes (which otherwise are perfectly normal) impossible to use.

**Comment by KnightMiner** [comment]
Tinkers Construct does not add Pyrothium natively, that is up to Thermal Expansion or an addon to integrate.

**Comment by Landmaster** [comment]
@Carnaxus In fact, Blazing Pyrotheum is added by PlusTiC.

**Comment by Carnaxus** [comment]
@Landmaster Thank you!
