### ISSUE TITLE
slime islands with biomes

### ISSUE THREAD

**Issue by Univizum** [SlimeKnights/TinkersConstruct#3870]
(https://user-images.githubusercontent.com/30324592/58768470-db5ee380-8569-11e9-912f-1abd0f3d4720.png)

1.12.2 mc on forge 14.23.5.2838 on mantle 1.3.3.55 on Tconstruct 2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** I think the mod Beta+ which generates beta style terrain might cause this

**Comment by KnightMiner** [comment]
If you think the last mod is the issue, try reproducing without it, and try reproducing with just that mod and Tinkers Construct. Slime Islands don't cause issues with most terrain gen as they generate as structures, which should happen after trees are added, so my guess is Beta+ generates oddly.

**Comment by KnightMiner** [comment]
Closing for lack of response
