### ISSUE TITLE
Project Ozone 3 Tinkers Construct Blazing Pyrotheum

### ISSUE THREAD

**Issue by Kekalicious** [SlimeKnights/TinkersConstruct#3871]
**Issue description:**
Blazing Pyrotheum in the Smeltery Controller allows for infinite smelting without having to add more fuel.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* Mantle: 1.3.3.49
* Tinkers Construct: 12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Blazing Pyrotheum is not a default fuel added by Tinkers Construct, it is added by another mod or a crafttweaker script. I would start on the issue tracker for Project Ozone 3
