### ISSUE TITLE
Tools getting their durrability back for no reason

### ISSUE THREAD

**Issue by ArtusianGamer** [SlimeKnights/TinkersConstruct#3872]
Almost all of my tools (haven't noticed it on the pickaxe) have been randomly getting their durrability back for no apparent reason, I dont know if they are getting it back over time or in an instant. It seems really game breaking and i'm pretty sure it's not intentional.
P.S: My tools are not some lategame powerhouses, they are simple iron tools with only the handle being made out of wood.

The game never crashed because of this

Versions: 1.12

This happened while using the FTB revelation modpack.

**Comment by KnightMiner** [comment]
Read materials and you and it would have told you the answer to this. Wood has an auto repair trait.
