### ISSUE TITLE
Obsidian Fortification issue!!

### ISSUE THREAD

**Issue by TheSexyYeti** [SlimeKnights/TinkersConstruct#3876]
![2019-06-11_11 33 42](https://user-images.githubusercontent.com/50222286/59286622-0f0ecd00-8c3e-11e9-97d3-48fe881701a7.png)
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.5
* Tinkers Construct: 2.12.0.135

Uhhhh I was tying to make an obsidian fortification. And after pouring it I can't remove the fortification or the pattern from the casting table. 

NOTE: The reason I'm using and older Forge version is because I'm beta testing Tango Tek's TekTopia Mod. And I wanted to see how well it would work with other mods.

**Comment by KnightMiner** [comment]
Look at the WAILA tooltip, you don't have enough obsidian for the cast. last, if you are trying to add the reinforcement modifier, the recipe changed since 1.7, look up reinforcement in JEI or in the Materials and You book.
