### ISSUE TITLE
Mod items (books II and III) do not exist in the game at all.

### ISSUE THREAD

**Issue by ParanoidStapler** [SlimeKnights/TinkersConstruct#3877]
Materials and you volume II and vol. III books do not exist.

1.12.2
Minecraft: 
Forge:  1.12.2 - 14.23.5.2768
Mantle: Mantle-1.12-1.3.3.55
Tinkers Construct: TConstruct-1.12.2-2.12.0.135

Is specific to TConstruct itself, reproducable by itself and with other mods.

**Comment by laz2727** [comment]
The important parts are in the first book.

**Comment by KnightMiner** [comment]
They were removed, everything is in book 1 that is finished.
