### ISSUE TITLE
it says that "requires mantel 1.12-1.3.1 or above (missing)"

### ISSUE THREAD

**Issue by realcoolfool2468** [SlimeKnights/TinkersConstruct#3878]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by alexbegt** [comment]
Download Mantle if you didn't. Tinkers Construct requires both: https://minecraft.curseforge.com/projects/mantle/files/2713386
