### ISSUE TITLE
[Minor] Interaction ± Universal Cell (IC2) Rendering of a fluid (Seared Gauge) + Missing texture = Crash

### ISSUE THREAD

**Issue by alxcool** [SlimeKnights/TinkersConstruct#3883]
* Minecraft: 1.12.2 (Previous minecraft launcher, Old Computer)
* Forge: 14.23.5.2838 (Single player)
* Mantle: Mantle-1.12-1.3.3.49
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135
* Industrialcraft: industrialcraft-2-2.8.159-ex112
* Immersive Engineering: ImmersiveEngineering-0.12-89
* + : immersivepetroleum-1.12.2-1.1.9
* RedstoneFlux-1.12-2.1.0.6-universal
* gregtech-1.12.2-1.8.1.404
* CodeChickenLib-1.12.2-3.2.2.353-universal

**Issue description:**

Hi! By using a bunch of mods, one of them Immersive Petroleum got a problem upon initialization or loading resulting with a registered fluid ( modname:Lubricant) who does not display his texture. This one is commutable with, or replace an another one,  a fluid from Gregtech community edition. Result, the fluid is usable both with JEI, in machine as recipe ingredient, but  won't display his texture. Minecraft missing texture have been used as replacement for the fluid.

As fluid storage, I was using multiple tinker construct seared gauge. The gauge was not linked to a tank and only 4-6 of them was rendering their fluid in-world, as most of the time I was storing every single one of them inside a chest. My motivation was to use a seared gauge anytime I have less than 4000mB of a fluid. As replacement for a bucket, I've used a IC2:universal fluid cell.

As soon as I've interacted with the seared gauge, a crash on a loop occur : 
[crash-2019-06-19_14.24.05-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3308335/crash-2019-06-19_14.24.05-client.txt)

[14:24:05] [Client thread/FATAL] [VanillaFix]: Minecraft ran into a problem! Report saved to: C:\Users\Alex B\AppData\Roaming\.minecraft\crash-reports\crash-2019-06-19_14.24.05-client.txt
---- Minecraft Crash Report ----
// Don't do that.

Time: 2019-06-19 14:24:05 EDT
Description: Rendering Block Entity

**How to Reproduce : **
I was trying to drop 750/1000 unit worth of Immersive petroleum lubricant stored inside a fluid cell in or inside a single tinker construct seared gauge.

I May need to interact with a fluid who use minecraft:missing texture, in order to reproduce this crash. Note : I guess there already is a system who prevent crash from this specific kind of interaction. Unfortunately, for this time, it din't work.

**If crashed, link to crash report (use a site such as pastebin):**
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/3308281/latest.log)
Note : Its a long file, so you could skip to [14:24:05]

**Versions:**
Note : I've moved this section as header for this Issue

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Note : Mod listed on the first lines.
Special : I've said trying to display a fluid whom have a missing texture, lower than 1000/1000 unit, was creating a crash on a loop. Fortunately, once a reload, before, I was throw back to title screen (thk to vanillafix mod),  I've broke the seared gauche who drop itself in item form, then the game resume. After that, I was able to play

So good luck if you try to solve this issue, maybe you don't need as it is not something who may occur so often and Thk for your work on tinker construct, as I really enjoy every aspect of it!

**Comment by KnightMiner** [comment]
That crash is pointing to a line of code that does not exist in Tinkers Construct, I am not sure exactly what is happening, but if I had to guess another mod is coremodding our render utility, which makes no sense. I suggest you try and narrow down what mods are required to reproduce this like the last question asks as something is modifying our code externally.

**Comment by KnightMiner** [comment]
Closing for lack of response, someone is seriously messing with our code at an ASM level, so find out who and report to them
