### ISSUE TITLE
grout recipe doesn't work with other mod gravels

### ISSUE THREAD

**Issue by Mrthomas20121** [SlimeKnights/TinkersConstruct#3884]
**Issue description:**

grout doesn't use oredict for gravel in its recipe. because of this, we are unable to use other mods gravel for the recipe. a simple way to fix it would be to use oredict for the gravel in the recipe.

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2837
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.135

Other mods that i know of that add gravel: underground biomes.

**Comment by KnightMiner** [comment]
Should be in the latest release.
