### ISSUE TITLE
Demand for roadmap planning

### ISSUE THREAD

**Issue by Timmmy001** [SlimeKnights/TinkersConstruct#3885]
Here's the question about planning for support for version 1.14.

It's not a push, it's just the question of what you have planned.

Thank you very much,
Tom

**Comment by KnightMiner** [comment]
1.14 will be released when 1.14 is released. There is not a public time table. There is a lot involved in updating Tinkers and none of the devs have a ton of time

**Comment by Timmmy001** [comment]
Sorry for the wrong word "Demand".

**Comment by AyItsJayy** [comment]
> 1.14 will be released when 1.14 is released. There is not a public time table. There is a lot involved in updating Tinkers and none of the devs have a ton of time

Does this mean when forge is out of beta?
