### ISSUE TITLE
Clay issue.

### ISSUE THREAD

**Issue by thorpey9490** [SlimeKnights/TinkersConstruct#3886]
**Clay wont melt in smeltry:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1614
* Mantle: 0.3.2b
* Tinkers Construct: 1.8.8.build991

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Clay did not melt in 1.7. update to 1.12 if you want that feature.
