### ISSUE TITLE
Concerning part casting at custom amounts

### ISSUE THREAD

**Issue by Landmaster** [SlimeKnights/TinkersConstruct#3887]
Most Tinkers tool parts are casted using 1 Material Unit = 144mB. However, there are a few materials, such as Emerald, where 1 Material Unit = 666mB is the standard. Since the multiples of 144mB are currently hardcoded in the part integration code, addons that want to integrate such materials would, as of now, have to do it all manually. Hence, there should be a scaling system, preferably in the `Material` class, so that such cases are taken into account.

(E.g. `public int /* or rational data type */ getMaterialUnitSize()` or something like that)

**Comment by bonii-xx** [comment]
No, a toolpart has a fixed cost, everything else is just confusing. Also not worth the effort for an edge case. You'll have to register the casting recipes manually.

You might be able to utilize the TableCastingRegisterEvents with the regular registration.

**Comment by Landmaster** [comment]
Fair enough.
