### ISSUE TITLE
Blue Slime spawning 1.12

### ISSUE THREAD

**Issue by sealchan1** [SlimeKnights/TinkersConstruct#3888]
**Issue description:**
Unable to determine how to create conditions for blue slimes to spawn.  it seems haphazard in my survival world and I am unable to accomplish it in my creative world.

Request is for steps to reproduce in creative mode circumstances for expecting a Blue Slime to spawn and/or a url to the code that describes the spawning decision making.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2831
* Mantle: 1.3.3.49
* Tinkers Construct: 1.12.2-2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Unknown

**Comment by sealchan1** [comment]
Okay, as soon as I post this I return to my creative world and revisit a pair of sky islands and they are prolifically spawning blue slimes...is there some sort of long term factor that suppresses spawning but allows it to occur prolifically on occasion?

**Comment by KnightMiner** [comment]
Probably were seeing the mob cap: slimes are treated as normal move so if you have too many hostiles of any type it won't allow slimes to spawn

**Comment by sealchan1** [comment]
Okay thanks!  I was tooling around my creative world at sky island level and noticed that many islands were now working to spawn blue slimes.  I was beginning to wonder whether there was a chance per chunk load for the spawning to work!

**Comment by KnightMiner** [comment]
Closing as this it seems to have been fixed for you
