### ISSUE TITLE
Crash when attacking too quickly

### ISSUE THREAD

**Issue by Testo0987** [SlimeKnights/TinkersConstruct#3889]
**Issue description:**
https://paste.dimdev.org/esibohegip.mccrash
****

**Versions:**
* Minecraft: 1.12.2 
* Forge: v2836
* Mantle: 1.12-1.3.3.49
* Tinkers Construct: 2.12.0.135

**Im not sure why, but without the battlesign on everything was fine but with it on, it seemed to crash every time i hit too quickly. Here is the video:

https://youtu.be/Tmg6SEIGBdo

EDIT: It now appears that the battlesign was not the source, so i'm really not sure.
**

**Comment by Testo0987** [comment]
Ok, this seems awfully similar to #3783. The crashes are different, but the first time i got the crash i also received the same crash log. I will remove dynamic surroundings to see if the issue still occurs.

**Comment by Testo0987** [comment]
I'm also sure this is related to #3710.

**Comment by KnightMiner** [comment]
Your crash report is pretty messed up, its missing the entire stacktrace. I think its vanillafix that modifies the crash report like that, but we really need a report with fewer than 100 mods to do anything.

By guess is with the full crash report you will find its the same a #3783.

**Comment by KnightMiner** [comment]
Closing for lack of response as I am certain this is a duplicate of #3783
