### ISSUE TITLE
Server crashes when being killed by monsters.

### ISSUE THREAD

**Issue by StrangeMP** [SlimeKnights/TinkersConstruct#3890]
**Issue description:**
I'v added the TConstruct mod into my server.
Everything goes perfectly at first.
But when one of the players in the server being killed by monsters,the server closed immediately.
This has happened many times.I find out this issue will happen only when the TConstrut mod is added to the server.Other mods have no influence on that.

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/3MWiRtC0

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.12.0.156

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by alexbegt** [comment]
Please update to 157, there was a bug that caused this crash and it was fixed.

**Comment by StrangeMP** [comment]
Issue has been solved out !
THANK YOU !
