### ISSUE TITLE
Request: A recipe for grout using compressed sand and gravel

### ISSUE THREAD

**Issue by RepoDraghon** [SlimeKnights/TinkersConstruct#3891]
**Versions:**
* Minecraft:  1.12.2
* Forge:  Latest
* Mantle:  Latest
* Tinkers Construct:  Latest

I'd like a grout recipe that includes Compressed blocks, I imagine it like the 1 clay 1 sand 1 gravel only 1 clay block 1 compressed sand 1 compressed gravel or something like that, that makes more sense cause compressed in 9 of each and clay blocks are only 4 of each well thinking of that is would probably be more clay blocks to compressed ratio...

**Comment by SweetSugarSugar** [comment]
You're free to add in your own recipe via CraftTweaker...

**Comment by RepoDraghon** [comment]
I don't know how...

**Comment by KnightMiner** [comment]
No plans to do this at this time as there is not a huge standard for compressed blocks. I suggest you Google the crafttweaker wiki, it describes how to add your own recipes well.
