### ISSUE TITLE
TConstruct Ammo-type items fool Durability101.

### ISSUE THREAD

**Issue by Khioni** [SlimeKnights/TinkersConstruct#3896]
**Issue description:** Cross-mod problem - Durability101 is fooled by the durability value of ammo items, resulting in incorrect display with their mod.

![image](https://user-images.githubusercontent.com/36409872/60763896-8ff99280-a04b-11e9-8275-a0839435e248.png)

For reference, the wood shortbow is just fine, showing proper durability.
* Cobalt shuriken actually has 94, NOT the 940 it shows.
* Silver arrows actually have 23, NOT the 230 it shows.

~Related to the "durability-ammo does not match actual counter": It also fools with the wood regen behind the scenes (with durability viewers, you can see it creating partial arrows)~

> That is the point, according to this line, every 10 durability of the ammo is worth one shot, otherwise auto-repair from wood would be overpowered, along with other durability modifiers. It sounds like Durability101 is just displaying the literal damage value, which means it is not always correct to how other mods use it.

**UPDATE**: So the 1/10th wood regen is intentional design, looks like something that would need a rework to totally fix it on TiCon's end.

**If crashed, link to crash report (use a site such as pastebin):** N/A

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
* [Durability101](https://www.curseforge.com/minecraft/mc-mods/durability101) required
* Version tested with: **Durability101-1.12-0.0.3**

[Cross-posted to Durability101 (1.12.2)'s end.](https://github.com/durability101/1.12/issues/1)

**Comment by ShayBox** [comment]
I am willing to create a mod specific workaround for tinkers in durability101, but I will wait to see what the tinkers devs have to say, maybe willing to change how durability is handled to produce the best fix for more than just my mod.

**Comment by KnightMiner** [comment]
That is the point, according to [this line](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/library/tools/ranged/ProjectileCore.java#L43), every 10 durability of the ammo is worth one shot, otherwise auto-repair from wood would be overpowered. It sounds like Durability101 is just displaying the literal damage value, which means it is not always correct to how other mods use it.

We really need to add that sort of thing natively for ammo, but there really is nothing wrong on our side, and arguably not on Durability101's side as it is displaying the correct durability, its just not the useful one that we show in the tooltip.

**Comment by Khioni** [comment]
I can see why it'd be OP to have that 10x wood regen on ammo items.

While Durability101 IS indeed working as intended, it definitely seems like it needs a patch workaround - that, or a more global patch _here_ that would fix it for all durability viewers, not just for each dev that factors it in and patches in a workaround.

**Comment by ShayBox** [comment]
Since I have little knowledge of tinkers, what would be the best way code wise to identify the problem items, look for the ammo line? or are there other items that have a similar problem

**Comment by KnightMiner** [comment]
We could slow down wood repair for ammo, yes, but that would be slowing it down to a random factor. To explain more, I cannot say regenerate at 1/10 of the speed as ammo is an integer, and adding in another property just to hold partial ammo would be a mess. And thats just autorepair, there still is normal tool repair, tool durability modifiers, etc. which all would have to be patched to special case ammo. Plus, any existing worlds will suddenly have the wrong durability on items. Long story short, Tinkers is using the most ideal solution for internal compatibility.

I will have to look into what methods Forge offers for durability display to determine if there is any way we can change what value we display to you. Sure, you could special case our items, but apart from doing `instanceof` checks there is no easy way to identify it as ammo. If you would leave a comment on which methods you use to get the durability numbers that would help when I look into this.

----

One possible solution: would you be willing to PR a partial version of the durability display for just the ammo items? We have been meaning to replace the durability bar with a number for ammo for awhile but have never had the time to look into it. If we handled the code internally, we could manually divide the number by 10, then you just add a blacklist on your side to skip Tinkers ammo items entirely.

**Comment by ShayBox** [comment]
My mod is a coremod that injects code in the [RenderItem class](https://github.com/durability101/1.12/blob/master/src/main/java/com/shaybox/durability101/mixin/MixinRenderItem.java)
Forge no longer has any way to access RenderItem, it used to in 1.7 but that was removed in 1.8
There is a way to do it without a coremod, but it wouldn't render *everywhere*, so only inventories you listen to, and not when moving items.
It's a fairly basic coremod, I don't know if tinkers has any coremods currently, though if you do something similar I will still have to identify your items with ammo to disable my counter on them

**Comment by KnightMiner** [comment]
Do you render it only when a durability bar is shown? Because if thats the case it would handle the blacklist automatically if its ever fixed on our side.

But yeah, I'll let you know if I find a way to change what durability we display to other mods as that would probably be the best way to solve the issue. I am pretty sure there is a method in the Item class for that, so I'll just have to make sure to override it and you to be using that method. Won't be able to look into this for a couple days though

**Comment by ShayBox** [comment]
Yes, only if `stack.getItem().showDurabilityBar(stack)` is true, that would work

**Comment by KnightMiner** [comment]
1.16 fixes this by removing ammo, it has many design issues so it was easier to just use vanilla ammo (which is more interesting now anyways).

I don't think there is an easy way to fix this in 1.12
