### ISSUE TITLE
Pattern Crafting?

### ISSUE THREAD

**Issue by artsyfarts** [SlimeKnights/TinkersConstruct#3897]
**Issue description:**
I can't seem to craft blank patterns in my inventory.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2 - 2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Answer the last question, I have seen this but caused by Optifine, the Aether, and other mods, so without knowing that youhave verified this issue with just Tinkers or a minimal lost we can do nothing. And stating your whole modpack is not a minimal list, try for less than 10 mods

**Comment by artsyfarts** [comment]
Tinkers is the only mod I have installed right now. That and the tinkers tool level-up mod.

**Comment by artsyfarts** [comment]
Oh lol, never mind. I was just crafting it incorrectly. Sorry for the inconvenience!!
