### ISSUE TITLE
Tinkers Construct is crashing minecraft when paired with other mods , i have crash report.

### ISSUE THREAD

**Issue by nikatark** [SlimeKnights/TinkersConstruct#3900]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 7/16/19 12:15 PM
Description: Registering texture

java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:239)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:230)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44)
	at net.minecraft.client.particle.ParticleManager.func_78874_a(ParticleManager.java:310)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1387)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:239)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:230)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/particle/particles.png
	Texture object class: net.minecraft.client.renderer.texture.SimpleTexture
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44)
	at net.minecraft.client.particle.ParticleManager.func_78874_a(ParticleManager.java:310)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1387)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['nikatark'/1356, l='MpServer', x=-204.70, y=71.00, z=362.24]]
	Chunk stats: MultiplayerChunkCache: 155, 155
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-252,64,252), Chunk: (at 4,4,12 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3302 game time, 3302 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 145 total; [EntityChicken['Chicken'/512, l='MpServer', x=-272.50, y=68.00, z=324.50], EntityChicken['Chicken'/513, l='MpServer', x=-273.50, y=68.00, z=322.50], EntityChicken['Chicken'/514, l='MpServer', x=-273.50, y=68.00, z=324.50], EntityChicken['Chicken'/524, l='MpServer', x=-270.50, y=68.00, z=321.50], EntityChicken['Chicken'/525, l='MpServer', x=-260.50, y=70.00, z=349.50], EntityChicken['Chicken'/526, l='MpServer', x=-257.50, y=70.00, z=348.50], EntityChicken['Chicken'/527, l='MpServer', x=-257.50, y=71.00, z=344.50], EntityChicken['Chicken'/528, l='MpServer', x=-258.50, y=69.00, z=353.50], EntityBat['Bat'/529, l='MpServer', x=-256.25, y=15.10, z=371.51], EntityCreeper['Creeper'/1041, l='MpServer', x=-125.50, y=14.00, z=295.50], EntityBat['Bat'/530, l='MpServer', x=-259.44, y=13.76, z=372.57], EntityItem['item.tile.gravel'/531, l='MpServer', x=-262.14, y=14.00, z=394.91], EntityItem['item.tile.gravel'/532, l='MpServer', x=-264.23, y=16.00, z=398.71], EntityZombie['Zombie'/1053, l='MpServer', x=-127.50, y=22.00, z=374.50], EntityZombie['Zombie'/1054, l='MpServer', x=-127.50, y=22.00, z=373.50], EntityBat['Bat'/556, l='MpServer', x=-244.53, y=12.07, z=368.58], EntityChicken['Chicken'/557, l='MpServer', x=-246.50, y=117.00, z=378.50], EntityChicken['Chicken'/558, l='MpServer', x=-245.50, y=113.00, z=381.50], EntityChicken['Chicken'/559, l='MpServer', x=-244.50, y=117.00, z=378.50], EntityChicken['Chicken'/560, l='MpServer', x=-245.50, y=116.00, z=379.50], EntityItem['item.tile.gravel'/561, l='MpServer', x=-245.88, y=33.00, z=393.59], EntityItem['item.tile.gravel'/562, l='MpServer', x=-245.37, y=37.00, z=395.70], EntitySkeleton['Skeleton'/563, l='MpServer', x=-253.50, y=14.00, z=402.50], EntityChicken['Chicken'/824, l='MpServer', x=-155.50, y=65.00, z=287.50], EntityChicken['Chicken'/825, l='MpServer', x=-152.50, y=64.00, z=284.50], EntityChicken['Chicken'/826, l='MpServer', x=-155.50, y=65.00, z=288.50], EntityChicken['Chicken'/827, l='MpServer', x=-157.50, y=66.00, z=289.50], EntityChicken['Chicken'/828, l='MpServer', x=-151.50, y=88.00, z=318.50], EntityChicken['Chicken'/829, l='MpServer', x=-151.50, y=88.00, z=320.50], EntityChicken['Chicken'/830, l='MpServer', x=-147.50, y=89.00, z=321.50], EntityChicken['Chicken'/831, l='MpServer', x=-147.50, y=89.00, z=321.50], EntityChicken['Chicken'/832, l='MpServer', x=-151.50, y=66.00, z=370.50], EntityChicken['Chicken'/833, l='MpServer', x=-151.50, y=66.00, z=370.50], EntityItem['item.item.seeds'/834, l='MpServer', x=-158.80, y=71.00, z=414.78], EntityItem['item.tile.flower1.dandelion'/835, l='MpServer', x=-159.77, y=71.00, z=414.44], EntityItem['item.item.seeds'/836, l='MpServer', x=-159.91, y=71.00, z=413.79], EntityItem['item.item.seeds'/837, l='MpServer', x=-157.42, y=71.00, z=415.78], EntityItem['item.tile.flower1.dandelion'/838, l='MpServer', x=-153.76, y=71.00, z=419.11], EntityItem['item.tile.flower1.dandelion'/839, l='MpServer', x=-156.79, y=71.00, z=416.32], EntityItem['item.item.seeds'/840, l='MpServer', x=-155.55, y=71.00, z=417.79], EntityItem['item.tile.flower1.dandelion'/841, l='MpServer', x=-155.34, y=71.00, z=417.55], EntityItem['item.item.seeds'/842, l='MpServer', x=-151.13, y=71.00, z=423.12], EntityItem['item.item.seeds'/843, l='MpServer', x=-156.83, y=71.00, z=416.70], EntityItem['item.item.seeds'/844, l='MpServer', x=-157.83, y=72.00, z=423.32], EntitySkeleton['Skeleton'/1357, l='MpServer', x=-229.50, y=38.00, z=390.50], EntityCow['Cow'/595, l='MpServer', x=-233.50, y=69.00, z=296.78], EntityCow['Cow'/596, l='MpServer', x=-229.44, y=69.00, z=306.69], EntityCow['Cow'/597, l='MpServer', x=-236.50, y=68.00, z=305.50], EntityCow['Cow'/598, l='MpServer', x=-236.50, y=68.00, z=304.50], EntitySkeleton['Skeleton'/599, l='MpServer', x=-236.50, y=14.00, z=333.50], EntityCreeper['Creeper'/600, l='MpServer', x=-225.50, y=13.00, z=347.50], EntityBat['Bat'/1368, l='MpServer', x=-211.75, y=39.29, z=325.90], EntitySkeleton['Skeleton'/601, l='MpServer', x=-234.50, y=42.00, z=339.50], EntityItem['item.item.seeds'/602, l='MpServer', x=-234.51, y=70.00, z=355.80], EntityItem['item.item.seeds'/603, l='MpServer', x=-228.31, y=70.00, z=355.13], EntityItem['item.item.seeds'/604, l='MpServer', x=-235.55, y=70.00, z=355.34], EntityItem['item.item.seeds'/605, l='MpServer', x=-231.10, y=70.00, z=353.13], EntityItem['item.item.seeds'/606, l='MpServer', x=-226.13, y=70.00, z=358.13], EntityCreeper['Creeper'/607, l='MpServer', x=-230.50, y=33.00, z=376.50], EntityItem['item.item.seeds'/608, l='MpServer', x=-228.59, y=77.00, z=368.17], EntityChicken['Chicken'/609, l='MpServer', x=-235.50, y=94.00, z=406.50], EntityChicken['Chicken'/610, l='MpServer', x=-235.50, y=94.00, z=406.50], EntityChicken['Chicken'/611, l='MpServer', x=-238.50, y=87.00, z=406.50], EntityChicken['Chicken'/612, l='MpServer', x=-234.50, y=97.00, z=407.50], EntityCow['Cow'/617, l='MpServer', x=-211.50, y=73.00, z=282.50], EntityCow['Cow'/619, l='MpServer', x=-211.50, y=73.00, z=283.50], EntityZombie['Zombie'/620, l='MpServer', x=-212.40, y=55.00, z=340.00], EntityVillager['Villager'/621, l='MpServer', x=-220.45, y=69.00, z=337.25], EntityVillager['Villager'/622, l='MpServer', x=-212.70, y=74.00, z=349.30], EntityBat['Bat'/623, l='MpServer', x=-209.61, y=57.75, z=358.61], EntityBat['Bat'/624, l='MpServer', x=-217.85, y=52.10, z=377.79], EntityCreeper['Creeper'/625, l='MpServer', x=-217.81, y=51.00, z=378.50], EntityBat['Bat'/626, l='MpServer', x=-219.25, y=52.10, z=378.42], EntityVillager['Villager'/627, l='MpServer', x=-222.50, y=98.00, z=381.50], EntityChicken['Chicken'/628, l='MpServer', x=-213.50, y=94.00, z=402.50], EntityChicken['Chicken'/629, l='MpServer', x=-215.50, y=105.00, z=403.50], EntityChicken['Chicken'/630, l='MpServer', x=-214.50, y=117.00, z=405.50], EntityChicken['Chicken'/631, l='MpServer', x=-215.50, y=120.00, z=405.50], EntityCow['Cow'/648, l='MpServer', x=-207.50, y=73.00, z=284.50], EntityCow['Cow'/649, l='MpServer', x=-207.50, y=72.00, z=285.50], EntitySkeleton['Skeleton'/1417, l='MpServer', x=-247.50, y=14.00, z=347.50], EntityCow['Cow'/650, l='MpServer', x=-203.50, y=72.00, z=287.50], EntityZombie['Zombie'/651, l='MpServer', x=-203.50, y=37.00, z=321.85], EntityVillager['Villager'/652, l='MpServer', x=-206.49, y=72.00, z=350.94], EntityVillager['Villager'/653, l='MpServer', x=-206.50, y=71.94, z=340.08], EntityCreeper['Creeper'/1421, l='MpServer', x=-266.50, y=13.00, z=374.50], EntityVillager['Villager'/654, l='MpServer', x=-207.67, y=71.00, z=353.50], EntitySkeleton['Skeleton'/1422, l='MpServer', x=-263.50, y=13.00, z=371.50], EntityVillager['Villager'/655, l='MpServer', x=-192.72, y=71.00, z=362.50], EntityVillager['Villager'/656, l='MpServer', x=-207.68, y=71.94, z=378.48], EntitySkeleton['Skeleton'/1424, l='MpServer', x=-264.50, y=13.00, z=371.50], EntityVillager['Villager'/657, l='MpServer', x=-196.19, y=67.94, z=368.31], EntityZombie['Zombie'/1425, l='MpServer', x=-260.50, y=13.00, z=375.50], EntityItem['item.item.seeds'/658, l='MpServer', x=-197.00, y=68.00, z=375.74], EntitySkeleton['Skeleton'/1426, l='MpServer', x=-259.50, y=19.00, z=408.50], EntityPig['Pig'/659, l='MpServer', x=-201.50, y=74.00, z=398.50], EntitySkeleton['Skeleton'/1427, l='MpServer', x=-258.50, y=19.00, z=406.50], EntityPig['Pig'/660, l='MpServer', x=-201.50, y=74.00, z=399.50], EntityCreeper['Creeper'/1428, l='MpServer', x=-140.50, y=19.00, z=329.50], EntityPig['Pig'/661, l='MpServer', x=-197.06, y=72.00, z=399.33], EntityPig['Pig'/662, l='MpServer', x=-203.50, y=77.00, z=403.50], EntityChicken['Chicken'/666, l='MpServer', x=-177.50, y=66.00, z=316.50], EntityChicken['Chicken'/667, l='MpServer', x=-176.50, y=66.00, z=317.50], EntitySkeleton['Skeleton'/668, l='MpServer', x=-186.50, y=42.00, z=335.50], EntityItem['item.item.potatoPoisonous'/669, l='MpServer', x=-190.75, y=71.94, z=333.08], EntityChicken['Chicken'/670, l='MpServer', x=-183.61, y=71.00, z=331.88], EntityVillager['Villager'/671, l='MpServer', x=-189.27, y=72.00, z=331.25], EntityBat['Bat'/672, l='MpServer', x=-187.37, y=35.19, z=342.17], EntityZombie['Zombie'/928, l='MpServer', x=-143.96, y=15.00, z=309.50], EntityChicken['Chicken'/673, l='MpServer', x=-181.23, y=68.00, z=350.16], EntityZombie['Zombie'/929, l='MpServer', x=-135.50, y=39.00, z=330.50], EntityVillager['Villager'/674, l='MpServer', x=-180.82, y=68.00, z=367.50], EntityZombie['Zombie'/930, l='MpServer', x=-135.50, y=41.00, z=326.50], EntityVillager['Villager'/675, l='MpServer', x=-187.88, y=68.00, z=367.80], EntityEnderman['Enderman'/931, l='MpServer', x=-128.50, y=22.00, z=375.50], EntityChicken['Chicken'/676, l='MpServer', x=-176.50, y=70.00, z=395.50], EntityChicken['Chicken'/677, l='MpServer', x=-176.50, y=71.00, z=398.13], EntityCreeper['Creeper'/933, l='MpServer', x=-135.50, y=41.00, z=405.50], EntityCreeper['Creeper'/678, l='MpServer', x=-182.50, y=48.00, z=433.50], EntitySkeleton['Skeleton'/1456, l='MpServer', x=-276.50, y=17.00, z=372.50], EntityBat['Bat'/1460, l='MpServer', x=-239.50, y=52.00, z=370.50], EntityBat['Bat'/1461, l='MpServer', x=-237.50, y=52.00, z=368.50], EntityChicken['Chicken'/697, l='MpServer', x=-174.50, y=66.00, z=313.50], EntityChicken['Chicken'/698, l='MpServer', x=-170.50, y=69.00, z=319.43], EntityChicken['Chicken'/699, l='MpServer', x=-173.82, y=69.00, z=326.41], EntityChicken['Chicken'/700, l='MpServer', x=-173.77, y=69.00, z=339.49], EntityVillager['Villager'/701, l='MpServer', x=-174.70, y=69.00, z=380.35], EntityVillager['Villager'/702, l='MpServer', x=-174.02, y=69.00, z=380.72], EntitySkeleton['Skeleton'/1470, l='MpServer', x=-190.50, y=44.00, z=325.50], EntityChicken['Chicken'/703, l='MpServer', x=-170.50, y=68.00, z=393.50], EntitySkeleton['Skeleton'/1471, l='MpServer', x=-188.50, y=44.00, z=326.50], EntityChicken['Chicken'/704, l='MpServer', x=-173.50, y=70.00, z=394.50], EntitySkeleton['Skeleton'/1472, l='MpServer', x=-190.50, y=44.00, z=326.50], EntityItem['item.item.seeds'/705, l='MpServer', x=-167.73, y=72.00, z=414.40], EntityItem['item.item.seeds'/706, l='MpServer', x=-163.80, y=71.00, z=410.00], EntityItem['item.item.seeds'/707, l='MpServer', x=-168.55, y=71.00, z=409.43], EntityItem['item.item.seeds'/708, l='MpServer', x=-167.15, y=71.00, z=408.13], EntityItem['item.item.seeds'/709, l='MpServer', x=-161.76, y=71.00, z=412.13], EntityItem['item.item.seeds'/710, l='MpServer', x=-165.80, y=72.00, z=417.13], EntityZombie['Zombie'/711, l='MpServer', x=-171.50, y=49.00, z=435.50], EntityPlayerSP['nikatark'/1356, l='MpServer', x=-204.70, y=71.00, z=362.24], EntityLatchedRenderer['unknown'/1496, l='MpServer', x=-204.70, y=71.00, z=362.24], EntitySkeleton['Skeleton'/509, l='MpServer', x=-276.50, y=46.00, z=282.50], EntitySkeleton['Skeleton'/510, l='MpServer', x=-280.50, y=28.00, z=301.50], EntitySkeleton['Skeleton'/511, l='MpServer', x=-282.50, y=28.00, z=303.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/1496, l='MpServer', x=-204.70, y=71.00, z=362.24]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 16215048 bytes (15 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version           | Source                                             | Signature                                |
	|:--------- |:------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2            | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | mcp                 | 9.42              | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | appliedenergistics2 | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJAAAA | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
	| UCHIJAAAA | bibliocraft         | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| UCHIJAAAA | codechickenlib      | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux        | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | brandonscore        | 2.4.16            | BrandonsCore-1.12.2-2.4.16.207-universal.jar       | None                                     |
	| UCHIJAAAA | buildcraftlib       | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UCHIJAAAA | buildcraftcore      | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UCHIJAAAA | buildcraftbuilders  | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UCHIJAAAA | buildcrafttransport | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UCHIJAAAA | buildcraftsilicon   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UCHIJAAAA | buildcraftenergy    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UCHIJAAAA | ic2                 | 2.8.109-ex112     | industrialcraft-2-2.8.109-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | jei                 | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| UCHIJAAAA | forestry            | 5.8.1.322         | forestry_1.12.2-5.8.1.322.jar                      | None                                     |
	| UCHIJAAAA | buildcraftcompat    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UCHIJAAAA | buildcraftfactory   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UCHIJAAAA | buildcraftrobotics  | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UCHIJAAAA | compactsolars       | 1.12.2-5.0.18.341 | CompactSolars-1.12.2-5.0.18.341-universal.jar      | None                                     |
	| UCHIJAAAA | draconicevolution   | 2.3.23            | Draconic-Evolution-1.12.2-2.3.23.345-universal.jar | None                                     |
	| UCHIJAAAA | lootablebodies      | 2.4.0             | DrCyanosLootableBodies_1.12-2.4.0.jar              | None                                     |
	| UCHIJAAAA | ichunutil           | 7.1.4             | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
	| UCHIJAAAA | ironbackpacks       | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| UCHIJAAAA | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.69.845.jar                    | None                                     |
	| UCHIJAAAA | jeibees             | 0.9.0.5           | jeibees-0.9.0.5-mc1.12.2.jar                       | None                                     |
	| UCHIJAAAA | journeymap          | 1.12.2-5.5.4      | journeymap-1.12.2-5.5.4.jar                        | None                                     |
	| UCHIJAAAA | mantle              | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                           | None                                     |
	| UCHIJAAAA | morph               | 7.1.2             | Morph-1.12.2-7.1.2.jar                             | None                                     |
	| UCHIJAAAA | morpheus            | 1.12-3.3.2        | Morpheus-1.12-3.3.2.jar                            | None                                     |
	| UCHIJAAAA | oreexcavation       | 1.4.137           | OreExcavation-1.4.137.jar                          | None                                     |
	| UCHIJAAAA | refinedstorage      | 1.6.14            | refinedstorage-1.6.14.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJAAAA | subcommonlib        | 1.2.0.1           | subcommonlib-sublib-1.12.2-1.2.0.4.jar             | None                                     |
	| UCHIJAAAA | tconstruct          | 1.12.2-2.10.1.87  | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
	| UCHIJAAAA | telepads            | $version          | telepads-1.12.2-1.1.0.5.jar                        | None                                     |
	| UCHIJAAAA | thaumcraft          | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| UCHIJAAAA | worldedit           | 6.1.8             | worldedit-forge-mc1.12-6.1.8-dist.jar              | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13559 Compatibility Profile Context 26.20.12001.11014' Renderer: 'Radeon RX 580 Series'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12001.11014, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

**Comment by KnightMiner** [comment]
You need more RAM, 1GB is no where near enough for modded Minecraft. Look online to find the way to increase your RAM
