### ISSUE TITLE
Replaced tool part has white texture regardless of material

### ISSUE THREAD

**Issue by TheWafflemancer** [SlimeKnights/TinkersConstruct#3902]
Replacing any tool part on an existing tool/weapon makes that part of the tool show up as white after said replacing.
![2019-07-16_21 57 21](https://user-images.githubusercontent.com/49215084/61325372-da7dca80-a814-11e9-914d-31f13c46b0d2.png)

**Comment by KnightMiner** [comment]
Please use the issue template, it asks you for information we need to debug this such as versions and other mods installed.

Also, does this only happens for you with broken tools, or any tool? I have never seen this issue myself before so give as much information as possible so it can be reproduced

**Comment by KnightMiner** [comment]
Closing for lack of response
