### ISSUE TITLE
Blood

### ISSUE THREAD

**Issue by Mihoshika** [SlimeKnights/TinkersConstruct#3903]
**Issue description:**
At some point, the blood in seared furnace became bugged, no longer able to increase or decrease it, despite having ample space in furnace. Was using it to make pig iron. Furnace was 3x3x2, occasionally broke top layer after falling in, to get out.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 8.0.99.99
* Mantle: 1.3.1.21
* Tinkers Construct:  1.12.2 - 2.9.1.65

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Edit: Happened again. I suspect it's caused by adding of new materials to furnace, or possibly making alloys.

**Comment by SweetSugarSugar** [comment]
Please answer the last question.

**Comment by Mihoshika** [comment]
I have no idea if it can be reproduced, as I'm not entirely certain as to what triggered it. It has only happened once. That being said, while I don't think other mods had an influence on it, what do I know. Using https://www.curseforge.com/minecraft/modpacks/not-tfc

**Comment by KnightMiner** [comment]
Going to need more information than that if we are going to fix this, as I have never seen this behavior. Likely some other mod is messing with fluids or adding invalid recipes.

**Comment by PrincessOfEvil** [comment]
Got the same bug in a modpack but managed to reproduce in just TiC (admittedly a rather old version).
It's basically an interaction of a smeltery that overflows with liquids due to breaking a block while it's full and the blood draining effect (probably a min(20, space left in smeltery) that doesn't realize that technically, the space left is negative.)

Way to reproduce: make at least 2 high smeltery, fill it with liquids above the 1st block, break one height level so it overflows and get drained of blood by an overflowing smeltery.

**Comment by KnightMiner** [comment]
Smelteries don't overflow, there is no logic in place to drain it when the size changes.

However, I managed to reproduce this issue by taking damage while in a full smeltery, the important detail here is taking damage in a full smeltery. I'll look into this issue.

**Comment by PrincessOfEvil** [comment]
Yeah, by "overflow" I meant "has more liquids than it can store".

**Comment by qaptivator** [comment]
i have a similar bug. i drain the blood so i can make pigiron, but it keeps on coming back with the same 400 ml.
i cant make any allows because it just keeps on screwing up the ratios

**Comment by qaptivator** [comment]
oh nevermind, it was probably intentional so i wont get rid of blood into nowhere. i was using a casting table and destroying it to get rid of it but it came back
