### ISSUE TITLE
Help! TinkerersConstruct Crashes when i try to use it

### ISSUE THREAD

**Issue by TheSilverScarf** [SlimeKnights/TinkersConstruct#3905]
I only have the TinkerersConstruct mod and when the server starts after like maybe 3 seconds it crashes. heres the crash report. any help would be awesome, thanks.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/18/19 8:28 PM
Description: Exception in server tick loop

Missing Mods:
	unknown : need [1.12-1.3.3.49,): have missing

net.minecraftforge.fml.common.MissingModsException: Mod tconstruct (Tinkers' Construct) requires [mantle@[1.12-1.3.3.49,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 849177320 bytes (809 MB) / 971505664 bytes (926 MB) up to 3808428032 bytes (3632 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version           | Source                                  | Signature                                |
	|:----- |:---------- |:----------------- |:--------------------------------------- |:---------------------------------------- |
	| L     | minecraft  | 1.12.2            | minecraft.jar                           | None                                     |
	| L     | mcp        | 9.42              | minecraft.jar                           | None                                     |
	| L     | FML        | 8.0.99.99         | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | forge      | 14.23.5.2838      | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | tconstruct | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar        | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by alexbegt** [comment]
Please download mantle. https://www.curseforge.com/minecraft/mc-mods/mantle

**Comment by TheSilverScarf** [comment]
what does mantle do? sorry im kinda new to this

**Comment by KnightMiner** [comment]
It provides shared code uses by Tinkers Construct and some other mods.
