### ISSUE TITLE
Suggestion: More variation or custom materials for example for Bowstrings.

### ISSUE THREAD

**Issue by SirAron111** [SlimeKnights/TinkersConstruct#3907]
You are already adding custom materials with the slime and cobalt etc wouldn’t it be possible to be able to make bowstrings with fun effects and variations in the draw speed modifier to the mod?

Like Slime Strings or Knightslime Strings, Vine Strings, Slime Vine Strings or for more advanced stuff leather String or new material Nylon Strings and so on and so on. I think the lack of String materials is sad for bow users. Especially since the crossbow nurfes!

Also the fact that most existing Bowstrings are all the same with the modifier set to 1.0 and the only ever add-on I saw that added a better bowstring material was natura with the flame spider strings but adding in natura just to get one more string isn’t really a good thing.

Well this is just one Suggestion I had if its not doable or a bad idea just ignore me I just thought it would be nice to have more base variations in the mod itself.

**Comment by bonii-xx** [comment]
Adding extra items just for an extra material, that is only usable in one toolpart at that, only leads to clutter. Besides that, bowstrings etc. have very limited options for diversity, so it's not very useful to have many. It's mostly to make things available with what you have.
