### ISSUE TITLE
[Question] Fix Tools stats after changing them?

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#3908]
I have a set of tools, then using CraftTweaker (or Tweakers Construct) I've changed some stats, e.g. mining speed for a specific materal. The problem is if I rejoin the world the tools will keep their old stats, there's no way to fix the stats of already made tools in-game?

**Comment by KnightMiner** [comment]
The old stats are cached in NBT so as to not tank performance with how often they are requested/how complex the calculations are. You should be able to update the stats by making any change to the tool.

Does this only happens for tools before you make your tweaks, or does it affect tools made after the tweaked stats?

**Comment by Insane96** [comment]
Only happens for tools before you make your tweaks, newly made tools after the tweaks have no problems.
> You should be able to update the stats by making any change to the tool.

Yep, this seems to work.
