### ISSUE TITLE
Tinker's Crash with Spiky trait + Mods that add 'proc'd' damage reflection on enemies

### ISSUE THREAD

**Issue by Ridley11** [SlimeKnights/TinkersConstruct#3909]
Hello. I have run into a recurring error resulting in a crash regarding the 'spiky' trait from tinker's construct. It seems to conflict with 'proc'd' damage reflection from mobs. In my case it is both the Vengeance trait from Infernal mobs & the red middle gem from the Betweenlands. I tested the Jagged trait from the Prismarine armor of Tinkers Armory (a similar damage reflect ability) just to be sure it was just the spiky trait, and indeed the prismarine armor trait did not cause a crash in the same instances.

It would also seem that the steel weapons' 'sharp' trait, or similar dots can trigger this interaction if the player is wearing anything with the spiky trait. Each individual 'bleed' damage proc from sharp can trigger a enemies damage reflect, in this case either the vengeance buff or the red middle gem, and if the player has the spiky trait then it will crash here too. 

Crash Report
https://pastebin.com/tK0EzKdc
[tK0EzKdc.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3430904/tK0EzKdc.txt)

**Versions:**
Minecraft 1.12.2
forge-14.23.5.2838
Mantle-1.12-1.3.3.49
TConstruct-1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
The Betweenlands
Infernal Mobs

Thanks :)

**Comment by Ridley11** [comment]
Sorry I meant Tinker's Armory, not Tinkers Compendium

**Comment by KnightMiner** [comment]
I am not sure if there is anything we can do about this, damage reflection is not a nor.ak behavior so there is not really a property we can set saying "don't reflect this". Can you also post to Between lands so the devs there can talk to us here about a solution?

**Comment by bonii-xx** [comment]
Since I don't want to do weird workarounds when dealing damage using steels trait, here's what will happen: The bleed causes the damage reflect, but spiky does not reflect reflected damage anymore (as long as it's marked as such. The guardians is.)
