### ISSUE TITLE
Add "toolShovel" and "toolAxe" as ore dictionary properties to the Mattock

### ISSUE THREAD

**Issue by bool3max** [SlimeKnights/TinkersConstruct#3911]
Right now the mattock only has `toolHoe` as an ore dictionary property (don't know if it's called a property, don't have modding experience). 

Since it acts as as both an axe, a hoe, and a shovel, it would be logical for it to be listed as a `toolAxe` and a `toolShovel` as well. This would allow it to be used as, e.g. an axe input in an EnderIO Slice&Splice.

**Comment by KnightMiner** [comment]
It is intentionally not marked as an axe or shovel, it is not a full axe or a full shovel thus should not work in that Ender IO block. Use a hatchet
