### ISSUE TITLE
mod crash

### ISSUE THREAD

**Issue by HyperNycer** [SlimeKnights/TinkersConstruct#3912]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by HyperNycer** [comment]
here's the link:
https://paste.dimdev.org/iqabogagiz.mccrash

**Comment by HyperNycer** [comment]
the other mod what reproduced the issue is FoamFix

**Comment by KnightMiner** [comment]
You need more RAM allocated to the game, you only gave it about 3GB, but you have hundreds of mods so you want at minimum 4GB, though I'd advise 6-8GB of RAM
