### ISSUE TITLE
Unable to create Soul shard respawn tool parts

### ISSUE THREAD

**Issue by IcyNight** [SlimeKnights/TinkersConstruct#3913]
I'm currently playing the "Hexxit updated" modpack and i can't make the tool parts made of corrupted ingot (a "soul shard respawn" item ), I tried making them using both casting and part builder and with both I failed, there is no option to cast the corruption fluid and the part builder just inform about the corrupted ingot usage and modifiers as parts of tools but doesn't let you actually create the tool parts.
Is it just a bug or am I not doing something correctly?

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

Can only be reproduced using the mod "Soul Shard Respawn"

**Comment by KnightMiner** [comment]
This is almost certainly a bug with Soul Shard Respawn, they added their integration improperly (we do not add integration for that mod ourselves). Find which mod adds this integration and report the issue to them

**Comment by KnightMiner** [comment]
Closing as a Soul Shard Respawn bug
