### ISSUE TITLE
Thaumcraft 6 Interaction Still Broken (Smeltry Chunk Graphics Glitch)

### ISSUE THREAD

**Issue by NihilEntropy** [SlimeKnights/TinkersConstruct#3915]
This issue has been reported with Iron Chests (now fixed apparently), and other mods. But is still a major annoyance involving thaumcraft 6 (anything, especially research and foci tables). I understand that if I move it from the chunk, it should not cause this affect. The issue was closed, but I see no changelog indicating a fix, has this issue been shelved or is there a possible solution in the future?

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

**Comment by KnightMiner** [comment]
@alexbegt mentioned he had an idea that could at least make this bug happen less often, but overall it's a vanilla issue that other mods just have to work around. So not much we can do beyond his fix.

**Comment by NihilEntropy** [comment]
Got it, it's a very odd issue though.
