### ISSUE TITLE
[Suggestion] Sneak = Breaking 1 block

### ISSUE THREAD

**Issue by SaeedGozai** [SlimeKnights/TinkersConstruct#3916]
**Issue description:**
There is a suggestion for the: Hammer, Excavator, Timberaxe, and all other items that break 3x3 or more.
If you can implement a way that when I use the sneak key it can allow me to just break 1 block instead of 3x3 it would be better. because right now I have a lot of tools in my inventory and I can't even use them all at the same time, I have to open the inventory and grab the other tool to break a single block. 

**If crashed, link to crash report (use a site such as pastebin):**
No Crash

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2824
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yeah, its only Tinkers' construct related

**Comment by KnightMiner** [comment]
Won't happen, it is an intentional design decision of Tinkers Construct to not make any tool replace another tools. Pickaxes are for small scale mining, hammers for large scale.
