### ISSUE TITLE
While below 10 hunger the chance for the Tasty Trait to nom the player is actually lower if has between 5 and 10 hunger.

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#3917]
**Issue description:**
https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/tools/traits/TraitTasty.java#L49
Here the chance should be higher but _5 - current_hunger_ could result in -5 which would lower the chance to -0.25% (or 0.75% if the player misses health) instead of increasing it.

In this case hunger will never go up since chance = 0%
![2019-08-06_10 49 40](https://user-images.githubusercontent.com/7185104/62525569-eff47c00-b837-11e9-8aef-dfb87ab43f24.png)

**Comment by bonii-xx** [comment]
Oh yeah. I hate it when values don't match up with the display.
