### ISSUE TITLE
the file

### ISSUE THREAD

**Issue by pikleman1** [SlimeKnights/TinkersConstruct#3918]
My server keeps crashing

---- Minecraft Crash Report ----
// You're mean.

Time: 8/6/19 3:58 PM
Description: Exception in server tick loop

Missing Mods:
	unknown : need [1.12-1.3.3.49,): have missing

net.minecraftforge.fml.common.MissingModsException: Mod tconstruct (Tinkers' Construct) requires [mantle@[1.12-1.3.3.49,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 545453432 bytes (520 MB) / 661651456 bytes (631 MB) up to 1873805312 bytes (1787 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version           | Source                                  | Signature                                |
	|:----- |:---------- |:----------------- |:--------------------------------------- |:---------------------------------------- |
	| U     | minecraft  | 1.12.2            | minecraft.jar                           | None                                     |
	| U     | mcp        | 9.42              | minecraft.jar                           | None                                     |
	| U     | FML        | 8.0.99.99         | forge-1.12.2-14.23.5.2768-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge      | 14.23.5.2768      | forge-1.12.2-14.23.5.2768-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | tconstruct | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar        | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
**Versions:**
* Minecraft:1.12.2
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Install Mantle, it is required by Tinkers Construct, as stated by the exception

**Comment by pikleman1** [comment]
Thanks
