### ISSUE TITLE
help

### ISSUE THREAD

**Issue by pikleman1** [SlimeKnights/TinkersConstruct#3919]
I think i might be the same problem but IDK could someone try and help

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MDECore-Core (mdecore-1.12-1.1.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/6/19 4:37 PM
Description: Exception in server tick loop

Missing Mods:
	unknown : need [14.23.5.2779,): have 14.23.5.2768

net.minecraftforge.fml.common.MissingModsException: Mod railcraft (Railcraft) requires [forge@[14.23.5.2779,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 551487320 bytes (525 MB) / 795869184 bytes (759 MB) up to 1873805312 bytes (1787 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 92 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                               | Signature                                |
	|:----- |:------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| U     | minecraft                 | 1.12.2                   | minecraft.jar                                        | None                                     |
	| U     | mcp                       | 9.42                     | minecraft.jar                                        | None                                     |
	| U     | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2768-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge                     | 14.23.5.2768             | forge-1.12.2-14.23.5.2768-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UD    | mdecore-core              | 1.0                      | minecraft.jar                                        | None                                     |
	| U     | micdoodlecore             |                          | minecraft.jar                                        | None                                     |
	| U     | foamfixcore               | 7.7.4                    | minecraft.jar                                        | None                                     |
	| U     | srm-hooks                 | 1.12.2-1.0.0             | minecraft.jar                                        | None                                     |
	| U     | additionalpipes           | 6.0.0.8                  | additionalpipes-6.0.0.8.jar                          | None                                     |
	| U     | advanced_machines         | 61.0.1                   | Advanced Machines-61.0.1.jar                         | None                                     |
	| U     | appliedenergistics2       | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar                 | None                                     |
	| U     | aroma1997core             | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                     | None                                     |
	| U     | aroma1997sdimension       | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar      | None                                     |
	| U     | autooredictconv           | 1.12-1.0.1               | autooredictconv-1.12-1.0.1.jar                       | None                                     |
	| U     | avaritia                  | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar               | None                                     |
	| U     | avaritiatweaks            | 1.12.2-1.1               | AvaritiaTweaks-1.12.2-1.1.jar                        | None                                     |
	| U     | bno                       | 1.12.2-1.0.4.0           | BasicNetherOres-1.12.2-1.0.4.0.jar                   | None                                     |
	| U     | betterquesting            | 3.5.299                  | BetterQuesting-3.5.299.jar                           | None                                     |
	| U     | biomesoplenty             | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar        | None                                     |
	| U     | bookshelf                 | 2.3.584                  | Bookshelf-1.12.2-2.3.584.jar                         | None                                     |
	| U     | buildcraftcompat          | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| U     | buildcraftbuilders        | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| U     | buildcraftcore            | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| U     | buildcraftenergy          | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| U     | buildcraftfactory         | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| U     | buildcraftlib             | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| U     | buildcraftrobotics        | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| U     | buildcraftsilicon         | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| U     | buildcrafttransport       | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| U     | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| U     | chisel                    | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| U     | clumps                    | 3.1.2                    | Clumps-3.1.2.jar                                     | None                                     |
	| U     | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar        | None                                     |
	| U     | compactmachines3          | 3.0.18                   | compactmachines3-1.12.2-3.0.18-b278.jar              | None                                     |
	| U     | compactsolars             | 1.12.2-5.0.18.341        | CompactSolars-1.12.2-5.0.18.341-universal.jar        | None                                     |
	| U     | compactstorage            | 3.1                      | CompactStorage-3.1-12.jar                            | None                                     |
	| U     | computercraft             | 1.80pr1                  | ComputerCraft1.80pr1.jar                             | None                                     |
	| U     | cookingforblockheads      | 6.4.70                   | CookingForBlockheads_1.12.2-6.4.70.jar               | None                                     |
	| U     | crafttweaker              | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
	| U     | crafttweakerjei           | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
	| U     | enderstorage              | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar          | None                                     |
	| U     | energyconverters          | 1.3.0.15                 | energyconverters_1.12.2-1.3.0.15.jar                 | None                                     |
	| U     | extracells                | 2.6.2                    | ExtraCells-1.12.2-2.6.2a.jar                         | None                                     |
	| U     | extraplanets              | 1.12.2-0.5.3             | ExtraPlanets-1.12.2-0.5.3.jar                        | None                                     |
	| U     | fastfurnace               | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                         | None                                     |
	| U     | fastleafdecay             | v14                      | FastLeafDecay-v14.jar                                | None                                     |
	| U     | fastbench                 | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                       | None                                     |
	| U     | foamfix                   | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                            | None                                     |
	| U     | microblockcbe             | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
	| U     | forgemultipartcbe         | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
	| U     | minecraftmultipartcbe     | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
	| U     | galacticraftplanets       | 4.0.2.210                | Galacticraft-Planets-1.12.2-4.0.2.210.jar            | None                                     |
	| U     | galacticraftcore          | 4.0.2.210                | GalacticraftCore-1.12.2-4.0.2.210.jar                | None                                     |
	| U     | hammercore                | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                        | None                                     |
	| U     | waila                     | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| U     | ic2                       | 2.8.109-ex112            | industrialcraft-2-2.8.109-ex112.jar                  | None                                     |
	| U     | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | None                                     |
	| U     | ironchest                 | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.69.845.jar                      | None                                     |
	| U     | jei                       | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                            | None                                     |
	| U     | lex                       | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                               | None                                     |
	| U     | mantle                    | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| U     | mdecore                   | 1.12-1.1                 | mdecore-1.12-1.1.jar                                 | None                                     |
	| U     | mjrlegendslib             | 1.12.2-1.1.8             | MJRLegendsLib-1.12.2-1.1.8.jar                       | None                                     |
	| U     | mmdlib                    | 1.0.0-rc2                | MMDLib-1.12-1.0.0-rc2.36.jar                         | None                                     |
	| U     | mrtjpcore                 | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar              | None                                     |
	| U     | oreexcavation             | 1.4.140                  | OreExcavation-1.4.140.jar                            | None                                     |
	| U     | harvestcraft              | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zd Surprise for Yogcast.jar | None                                     |
	| U     | projecte                  | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                          | None                                     |
	| U     | projectex                 | 1.2.0.36                 | ProjectEX-1.2.0.36.jar                               | None                                     |
	| U     | projectred-core           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar                  | None                                     |
	| U     | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar                | None                                     |
	| U     | projectred-fabrication    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar           | None                                     |
	| U     | projectred-integration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar           | None                                     |
	| U     | projectred-transmission   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar           | None                                     |
	| U     | projectred-illumination   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar              | None                                     |
	| U     | projectred-expansion      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar            | None                                     |
	| U     | projectred-relocation     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar            | None                                     |
	| U     | projectred-transportation | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar            | None                                     |
	| U     | projectred-exploration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-world.jar                 | None                                     |
	| U     | questbook                 | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                             | None                                     |
	| U     | railcraft                 | 12.0.0                   | railcraft-12.0.0.jar                                 | None                                     |
	| U     | reborncore                | 3.13.12.447              | RebornCore-1.12.2-3.13.12.447-universal.jar          | None                                     |
	| U     | reforged                  | 0.7.5                    | Reforged-0.7.5-1.12+.jar                             | None                                     |
	| U     | secretroomsmod            | 5.6.4                    | secretroomsmod-1.12.2-5.6.4.jar                      | None                                     |
	| U     | simplevoidworld           | 1.2.0.9                  | Simple-Void-World-1.12-1.2.0.9-universal.jar         | None                                     |
	| U     | snad                      | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                           | None                                     |
	| U     | bq_standard               | 3.4.158                  | StandardExpansion-3.4.158.jar                        | None                                     |
	| U     | tconstruct                | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                     | None                                     |
	| U     | tinkertoolleveling        | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                  | None                                     |
	| U     | wawla                     | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                             | None                                     |
	| U     | wrcbe                     | 2.3.1                    | WR-CBE-1.12.2-2.3.1.30-universal.jar                 | None                                     |
	| U     | zerocore                  | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                          | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MDECore-Core (mdecore-1.12-1.1.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Versions:**
* Minecraft: 
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Please post more descriptive issue titles than "help". And also verify that the issue is a Tinkers Construct issue before you post, this is an issue tracker for Tinkers Construct, not s general tech support forum. I suggest you try the Minecraft Forums or the Minecraft Forge Forums if you are not certain it is caused by this mod.

You need to update Forge for your version of Railcraft, again it says that near the top of the error:
> Mod railcraft (Railcraft) requires [forge@[14.23.5.2779,)]

It would also display a much friendlier version of the message in game that tells you exactly what I'm telling you now.

**Comment by pikleman1** [comment]
I will do that next time and thank you so much
