### ISSUE TITLE
Logical Progression Flaw

### ISSUE THREAD

**Issue by koorbmeh** [SlimeKnights/TinkersConstruct#3920]
In the latest version of Tinkers, Forge, and Mantle for 1.12.2, I'm not seeing Aluminum or Cooper anywhere.  So, then you need Gold to make casts?  But you can't mine gold without at least an iron pickaxe, and you can't make an iron pickaxe without gold for a cast...  See the problem?

**Comment by KnightMiner** [comment]
This is why clay casts exist, they are single use and allow you to make tool parts without needing gold.
