### ISSUE TITLE
No knockback on players

### ISSUE THREAD

**Issue by Wiral2** [SlimeKnights/TinkersConstruct#3923]
Basically the problem I'm having is that all weapons from Tinker construct have no knockback on players, but seem to work normally on mobs. Is there a fix for this? I've tested with only Mantle and Tinker Construct and the problem still presists.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2837
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Comment by KnightMiner** [comment]
Duplicate of #3480

**Comment by Wiral2** [comment]
Was there ever a fix?

**Comment by KnightMiner** [comment]
It's the same root cause. The previous issues was fixed but the fix is not yet released.

**Comment by Wiral2** [comment]
Is there an estimated date for the next update and it will it be for 1.12.2?
