### ISSUE TITLE
100+ dmg 

### ISSUE THREAD

**Issue by Draconian4466** [SlimeKnights/TinkersConstruct#3924]
With a tinkers construct weapon you are able to put way more quarts than the normal max (which is sharpestest increases dmg by 3ish) and you can put quarts to boost the dmg up to 100 
(possibly higher)

To Reproduce
1.Steps to reproduce the behavior:
2.Create any weapon
3.Get quarts
4.Put as much as you want on weapon
5.100+ dmg

![2019-08-08_20 24 15](https://user-images.githubusercontent.com/45436964/62840984-891ffa00-bc5f-11e9-805a-1732c16a6a23.png)

Versions:
Minecraft:1.12.2
Forge:14.23.5.2838
Mod Pack: WOD
Mod Name: Tinkers Construct
Mod Version:12.0.156

**Comment by Draconian4466** [comment]
pasted from here https://github.com/kreezxil/World-of-Dragons/issues/306

**Comment by Draconian4466** [comment]
also needs tinkers tool leveling

**Comment by KnightMiner** [comment]
Yeah, Tinkers Tool Leveling breaks the balance of the mod. It says so in the mod description. That said, we should have a cap on the max levels of sharpness.

**Comment by KnightMiner** [comment]
Just tested in game and I cannot reproduce with Tinkers Construct alone (using creative modifiers) or with just Tinkers Construct and Tinkers Tool Leveling. Please get a minimal modlist to reproduce this issue.

**Comment by PrincessOfEvil** [comment]
The *theoretical* maximum of sharpness is 19.25 damage - a bit less than
ten hearts, and it's completely unreachable. About five hearts is more
realistic. It *literally* cannot add more.

вт, 13 авг. 2019 г. в 00:50, KnightMiner <notifications@github.com>:

**Comment by bonii-xx** [comment]
There's probably some mod that changes the sharpness modifier. Not a TiC issue, as seen above.
