### ISSUE TITLE
conflict with mod natura

### ISSUE THREAD

**Issue by Bruno2592** [SlimeKnights/TinkersConstruct#3925]
tinkers mod is having serious errors and crashes with mod natura, when I start the game with these mods, there is a conflict between them and the game crashes, which doesn't happen without mod natura, fix this incompatibility for me to add one more mod in  my modpack

**Comment by KnightMiner** [comment]
Please actually fill out the issue template, you missed every piece of information we need to help you.

**Comment by bonii-xx** [comment]
Closing due to missing information.
