### ISSUE TITLE
Gloves?

### ISSUE THREAD

**Issue by MineTech123** [SlimeKnights/TinkersConstruct#3926]
Are the gloves removed? It existed in 1.7

**Comment by raziel23x** [comment]
it been removed several versions ago i think in 1.10.x

**Comment by SweetSugarSugar** [comment]
Not removed, just never put back im the rewrite.

https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ

**Comment by KnightMiner** [comment]
And no current plans to bring them back, Tinkers no longer adds custom inventory slots. Plus, really all they did was give you a craftable permanent haste effect. You can find similar features in other mods.
