### ISSUE TITLE
Visual duplicating

### ISSUE THREAD

**Issue by Lewui** [SlimeKnights/TinkersConstruct#3931]
**Issue description:Visual duplicating items on Engineering Workbench.When you open the workbench interface, item are duplicated.**

![image](https://user-images.githubusercontent.com/49539029/63664125-eb373e00-c7cd-11e9-9d57-2ab7db25803a.png)

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2 - 14.23.5.2838
* Mantle: 1.12-1.3.3.49
* Tinkers Construct: 1.12.2-2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? Yes**

**Comment by bonii-xx** [comment]
Your Screenshot clearly has more mods than just TiC. Try actually reproducing it with only TiC.

**Comment by KnightMiner** [comment]
Closing for lack of response. Reproduce with just Tinkers Construct to verify this is an issue, I know there are mods that replace our crafting station out there.
