### ISSUE TITLE
Textures with black backgrounds, are off-center from inventory slots

### ISSUE THREAD

**Issue by Unknow0059** [SlimeKnights/TinkersConstruct#3932]
**Issue description:**
[Screenshots](https://www.imgur.com/a/4nxHAWO)
I changed the orientation all of Tinker's Construct Shovel textures and now this glitch is happening. Textures have black backgrounds (non-transparent), are off-center from their respective inventory slots, and even a UI element unrelated to my changes is off-center.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Changed textures
https://www.dropbox.com/s/7qjjvlnjh8hbjxf/Flipped_Shovels.rar?dl=0

**Comment by bonii-xx** [comment]
You'll also have to fix all the models that use the textures: https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/resources/assets/tconstruct/models/item/parts/shovel_head.tmat.json

All the other parts you're noticing are autogenerated based on your textures. It uses transparency to detect stuff. So having a black background is a bad idea.

**Comment by Unknow0059** [comment]
@bonii-xx Well... they don't have a black background. They are all transparent.
What do you mean by "fix" the models that use the textures?

**Comment by KnightMiner** [comment]
You want it to be fully transparent to fix the textures, partially transparent will be treated like a solid colored pixel.

By "fix" the models, he means you modify the tool model JSONs, that is the tool we put in place so resource pack authors can determine how to line up items
