### ISSUE TITLE
Add option to config to change the Slime Island Blacklist to be a Whitelist instead

### ISSUE THREAD

**Issue by ProxyPlayerHD** [SlimeKnights/TinkersConstruct#3933]
title says it

reason: because in most packs it's much easier to say what dimensions you want the Islands to generate in than to say where you don't want them to generate.

in the default case it should just have dimension 0 in there. since that will break the least amount of mods you add afterwards that have dimensions (without having to worry about the config), like Advanced Rocketry for example.

**Comment by bonii-xx** [comment]
#3132
