### ISSUE TITLE
Newly crafted Drying Racks have NBT, but they lose it when they're placed and mined

### ISSUE THREAD

**Issue by aaronhowser1** [SlimeKnights/TinkersConstruct#3938]
**Issue description:**
Newly crafted:
![2019-08-31_03 42 39](https://user-images.githubusercontent.com/15698722/64061513-708d6a80-cba1-11e9-8586-66c8020480ea.png)
Placed and broken
![2019-08-31_03 42 42](https://user-images.githubusercontent.com/15698722/64061514-75eab500-cba1-11e9-9203-a33a4ad950d3.png)

**Versions:**
* Minecraft: 1.12
* Forge: 14.23.5.2838
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.12.0.157

**Comment by KnightMiner** [comment]
What are you using to break the racks? Can you reproduce with an empty hand? It works fine when I tested it.

And what other mods are in your pack? Can you reproduce with just Tinkers Construct?

**Comment by raziel23x** [comment]
I have always noticed this for a while that they do not stack after you place them and break them if you craft new ones that in order to stack them again you have to place them all an break them just this is the first time that anyone has actually reported this as i seen this happen on many of the FTB modpacks and other modpacks as well

**Comment by aaronhowser1** [comment]
Hmm, I can't reproduce it at all right now. Very strange. The pack I'm playing is FTB Academy.

**Comment by bonii-xx** [comment]
Well, as long as we can't reproduce it there's nothing we can do. As far as we know it works with every regular way of breaking them. Does it also happen for tables?

I suspect some mod is interfering with the breaking of the block.

**Comment by KnightMiner** [comment]
Closing for lack of response as you can no longer reproduce
