### ISSUE TITLE
Tinkers wont recognize Mystical Agriculture 

### ISSUE THREAD

**Issue by aussie4** [SlimeKnights/TinkersConstruct#3939]
**Issue description:** I installed Mystical Agriculture it a modpack im making and tinkers wont add the materials in from the mod. please help

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: ForgeMultipart-1.12.2-2.6.2.83-universal
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
MysticalAgriculture-1.12.2-1.7.5

**Comment by SweetSugarSugar** [comment]
More of a Mystical Agriculture issue.  Tinkers' provides support for other mods to implement materials but often other mods do not have this integration.  What you're probrably looking for is something like PlusTiC which integrates the mods.

**Comment by aussie4** [comment]
Okay, I thought it said somewhere it automatically recognizes mods its comp with. Im looking over the PlusTiC and im seeing nothing for mystical agriculture

**Comment by SweetSugarSugar** [comment]
It automatically recognizes common metals.

There's plenty of other integration mods, pretty sure there is one for Mystical Agriculture.

**Comment by aussie4** [comment]
im not seeing one, mind helping me?

**Comment by aussie4** [comment]
I know it works for skyfactory 4. ill have a look to see what bacon did it get it working

**Comment by aussie4** [comment]
NVM found it
Thanks!
