### ISSUE TITLE
When attacking multipart entities, onHit does not trigger

### ISSUE THREAD

**Issue by Landmaster** [SlimeKnights/TinkersConstruct#3940]
Peeking at `ToolHelper.attackEntity`, this behavior seems to be hardcoded in; this prevents trait attack event handlers from currently being usable on the ender dragon, which I would like to have working for a trait I'm writing.

**Comment by Landmaster** [comment]
The problem, of course, is that `onHit` and friends are fixed to take an `EntityLivingBase` rather than `Entity`, complicating the issue.

**Comment by bonii-xx** [comment]
I think I actually looked into this once, but there were issues with vanilla methods that required LivingBase. Will have to doublecheck.

**Comment by KnightMiner** [comment]
This is fixed in 1.16 due to the new Forge multipart entity hooks. I don't think 1.12 has any such hooks, so most likely this is can't fix, but I'll add it to the milestone to be looked at if we do another release.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support.
