### ISSUE TITLE
[Suggestion] 1.14.4 ?

### ISSUE THREAD

**Issue by Wissi** [SlimeKnights/TinkersConstruct#3942]
THE most essential mod for all our modpacks.

Love your work, hope to see you starting to port over to 1.14.4 soon.
Any plans for this?

We are ready to start testing it an give you feedback.

**Comment by Mrthomas20121** [comment]
taken from the faq on slimeknight discord: 
Question 12: Is Tinkers Construct going to be updated to 1.14?

Yes, it will be updated. There is not an ETA as 1.14 is a pretty major update from 1.12 between the Mojang and Forge rewrites. Additionally, Forge for 1.14 is not stable yet, it is still missing several features Tinkers Construct depends on. please be patient and stop ask about it.

**Comment by Wissi** [comment]
Thank you for posting this as i had read all issues and not seen an answer. 
I did not think to check Discord.
Might be great to add that part to the Tinker's Curse page? (just a suggestion).

Thanks for answering.

**Comment by Zito338** [comment]
Hello, how are you?

is there an update on this topic (and / or for any other version greater than 1.12.2)?

**Comment by KnightMiner** [comment]
Most mod authors get annoyed seeing comments asking for updates. It will get done when it gets done, if you want updates watch the commits on the 1.15 branch.
