### ISSUE TITLE
Bolt core replace does not work

### ISSUE THREAD

**Issue by Snowey1110** [SlimeKnights/TinkersConstruct#3944]
**Issue description:** I tried to replace my evil infused bolt core to demonic so my grass don't die, but after I replace it, it just turn back to what is was before.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:** 
* Minecraft: 1.12.2
* Forge: 1.12.2-forge1.12.2-14.23.5.2806
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

And here is the youtube video showing what happened: 
https://youtu.be/O376-Ku0v90

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by bonii-xx** [comment]
Can you reproduce it using only TiC materials? Can you reproduce it with only TiC and/or only with TiC and whatever adds those materials?

**Comment by KnightMiner** [comment]
Closing for lack of response. My best guess is you are seeing #3581.
