### ISSUE TITLE
unable to put binding in tool crafter

### ISSUE THREAD

**Issue by gareware** [SlimeKnights/TinkersConstruct#3945]
In the tool crafter If I want to make anithing with a binding in it i can't put in in the tool crafter.

versions
Minecraft: 1.12
 Forge: 12.23
 Tinkers Construct: 2.12

**Comment by KnightMiner** [comment]
Are you using the correct binding? There is regular binding and tough binding

**Comment by gareware** [comment]
oh, it was that easy. Thanks for helping
