### ISSUE TITLE
Low FPS with

### ISSUE THREAD

**Issue by cloewen8** [SlimeKnights/TinkersConstruct#3946]
**Issue description:**

A Combination of Tinkers Construct, Thermal Foundation and Twilight Forest halves my FPS. If I disable any of these mods, my fps goes back up to 20. Not great, but better than 2~.

This is with a fresh world, no items (beside the book), any location. I tested this with 2 different worlds, different seeds.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

- Thermal Foundation (2.6.3.27-universal)
- Twilight Forest (3.9.984-universal)
- Redstone Flux (2.1.0.6-universal)
- Patchouli (1.0-20)
- Connected Textures Mod (0.3.3.22)
- CoFH World (1.3.1.7-universal)
- CoFH Core (4.6.3.27-universal)

**Comment by bonii-xx** [comment]
TiC requires quite a bit in resources. Sounds like your computer is not able to handle the mods being loaded at the same time. Can you play any regular modpacks?

**Comment by cloewen8** [comment]
Does depend on what you consider "regular." I have played several popular modpacks on this machine in the past, most notably FoolCraft 3, All The Mods, FTB Unleashed.
More recently I have gotten into the habit of making my own modpacks. If you have any modpacks you'd like me to test, feel free to suggest them.

Either way, to test the low fps issue, I made a new modpack with only the specified mods. I don't feel like just those mods should be that intensive on their own.

**Comment by bonii-xx** [comment]
What happens if you remove Connected Textures? Just TiC and TF shouldn't cause any issues if you can run these modpacks. Other than that the only other option is doing some profiling.

**Comment by cloewen8** [comment]
Disabling Connected Textures worked. I wasn't able to reproduce the isolated environment listed above but it did work in one of my modpacks. I'll be sure to try and isolate this further next time I have a chance.

**Comment by KnightMiner** [comment]
Closing as it sounds like this is a connected textures issue, and there has not been a response in awhile.
