### ISSUE TITLE
Wooden Hopper deletes contents when wrenched

### ISSUE THREAD

**Issue by XXxinsanityxX** [SlimeKnights/TinkersConstruct#3947]
**Issue description:**
When trying to wrench the wooden hopper to change its side conection if theres anything inside while using a wrench it gets deleted.

The wrenching of the hopper does function, it does change the direction of the output.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2846
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
You need a mod that adds a type of wrench that can rotate blocks, the wrenches i tried are from GregTech CE and from Refined Storage.

**Comment by bonii-xx** [comment]
Of course vanilla TEs have special handling. Fixed next version
