### ISSUE TITLE
Localized name of inventory next to crafting station doesn't show up correctly

### ISSUE THREAD

**Issue by DeaSTL** [SlimeKnights/TinkersConstruct#3948]
**Localized name of inventory next to crafting station doesn't show up correctly**

**Versions:**
* Minecraft:  1.12.2
* Forge: 1.12.2 build 2838
* Mantle: 1.12-1.3.3.55
* Tinkers Construct:  1.12.2-2.12.0.157

**No it can't be reproduced with just tinkers**

![javaw_2019-09-16_14-43-07](https://user-images.githubusercontent.com/19532324/64984867-b03a9e80-d891-11e9-9dbd-c983c0e0b057.png)
This is with a strong box from the COFH mod suite
KingLemming thinks the crafting station is the issue

**Comment by KingLemming** [comment]
Well, sort of. I think that you should be calling localize on whatever you're querying in the GUI.

If the string is already localized, then it's np. If it's not, then it will localize it. The problem with some of the GUI functions is that there's not really a contract for what exactly should be returned; especially when localization itself is a client-side functionality.

**Comment by bonii-xx** [comment]
I'm actually a bit baffled that this hasn't appeared before. It's probably a bit of our own fault, because our container abstraction calls it "getDisplayName", but doesn't actually try to translate it.

**Comment by bonii-xx** [comment]
Hm, how are you handling tile names @KingLemming?
```public ITextComponent getDisplayName()```
That method of TileEntity.

From what I see it should always be TextComponentTranslate for Tiles, since the regular one returns a reset character at the end, meaning you can't even translate it.

**Comment by KingLemming** [comment]
I'm doing a TextComponentString. But you can translate that. I do it in my tiles all the time.

I can change it if necessary but if TextComponentTranslate is required, the method return should really be of that type. Ugh, Mojang.

**Comment by bonii-xx** [comment]
Ugh, indeed. What are you using to translate? I'm just calling the "getFormattedText", assuming that the TextComponent thing will return a presentation ready text. However for ComponentString it adds formatting that breaks translating it.. sigh. (https://github.com/SlimeKnights/Mantle/blob/1.12/src/main/java/slimeknights/mantle/inventory/BaseContainer.java#L143)

This was so much easier when it was just a String.
