### ISSUE TITLE
1.12.2 | Armour station Gui blank / inventory items not visible / gui not visible

### ISSUE THREAD

**Issue by mommajoe** [SlimeKnights/TinkersConstruct#3949]
**Issue description:**

when I enter the Armour crafting GUI, the slots are blank despite having  items in my inventory, first time using this mod, image ;  [image](https://i.imgur.com/3d5YAAy.png)

**Versions:**
* Minecraft: Version 1.12.2
* Forge: 14.23.5.2811
* Mantle: no clue what this is
* Tinkers Construct: Latest?

Quite a peculiar issue, seeing as all other GUIs and tables function as normal, pardon the lack of information, i'll check in on this post in a day or two.

for now, it's vanilla at the moment.

**Comment by KnightMiner** [comment]
Please don't answer "latest" for the version, it's pretty easy to check in game

In any case, the armor station is not from Tinkers Construct, it's an add-on called Construct's Armory. Report this issue to them.
