### ISSUE TITLE
[Suggestion] TinkersRegistry#getAllRegisteredTraits | TinkersRegistry#getAllRegisteredPartTypes

### ISSUE THREAD

**Issue by YaibaToKen** [SlimeKnights/TinkersConstruct#3950]
Hello, I'd like to request a method to get all the registered traits and all the registered tool parts, if possible. 
Currently, I generate a list of traits in use by cycling through all materials and adding their traits to a set (to avoid duplicate entries), but that leaves out traits that may have been registered and never used.
I use this information to generate help documents for my mod(Armory Expansion)'s configuration, where users can change my material stats and add traits to a material part through JSON files.

**Comment by bonii-xx** [comment]
Use the TraitRegisterEvent to create your list. Tool parts can already be gotten from the registry using `getToolParts`

**Comment by YaibaToKen** [comment]
Glad to know it's already possible and I just didn't find it. Could you please elaborate a bit more on the TraitRegisterEvent thing to get all traits?

**Comment by KnightMiner** [comment]
The event fires every time a trait is registered. List for that and put the traits in a set/list

**Comment by YaibaToKen** [comment]
Oh, awesome, thanks :D
