### ISSUE TITLE
All tool parts melt into seared stone

### ISSUE THREAD

**Issue by PrincessOfEvil** [SlimeKnights/TinkersConstruct#3951]
**Issue description:**
Title. All tool parts i've tested, including stuff that doesn't melt, like paper, melt into a respective amount of seared stone. JEI doesn't show any seared melting at all, except for stone ofc.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2760 and 14.23.5.2847 (noticed on latter, reverted to check if it's bugged)
* Mantle: Mantle-1.12-1.3.3.56
* Tinkers Construct: TConstruct-1.12.2-2.12.0.162 and TConstruct-1.12.2-2.12.0.164

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Just TiC, a completely fresh and empty installation.

Log, for whatever it's worth:
https://pastebin.com/RggSs2qt

![123](https://user-images.githubusercontent.com/2369751/65377146-f62fa200-dc97-11e9-8b51-0810a958fdc7.png)

**Comment by KnightMiner** [comment]
Fixed, closing this issue since its not a bug in a released build
