### ISSUE TITLE
Add Tektopia villagers into the list of mobs that create liquid emerald when smelted

### ISSUE THREAD

**Issue by kihgy** [SlimeKnights/TinkersConstruct#3952]
All mobs except the Necromancer give liquid emerald, children create the same amount of vanilla baby villagers

**Comment by bonii-xx** [comment]
We do not add specific mod support. The mods need to integrate their mobs.

**Comment by KnightMiner** [comment]
If you are working on a modpack, you can add the movs yourself using CraftTweaker and ModTweaker, see [the crafttweaker wiki](https://docs.blamejared.com/1.12/en/#Mods/Modtweaker/TConstruct/Melting/) for more information.
