### ISSUE TITLE
[1.12.2] Objects not Colored

### ISSUE THREAD

**Issue by Caaruzo** [SlimeKnights/TinkersConstruct#3954]
**Issue description:**

When i create an Object with Tinkers Construct (eg a Manyulynn hammer) its not colored. It stays blank white. The Item itself in Inventory of the Single parts are colored, the Object itself and the created hammer not.

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2838-universal
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.12.0.157

**Comment by KnightMiner** [comment]
You did not answer the last question, in which you would have found your answer.

Specifically, do you have any of the following?
* Optifine
* FoamFix
* TexFix

If the former, that breaks many mods. If the latter, that is a known bug in foamfix/TexFix which neither author will take blame for. You can find more details on that on the foamfix curseforge page

**Comment by Caaruzo** [comment]
thx for your help. Its the issue of foam fix. ill try an bit arround to figure the best way out between performance and resolve the issue xD
