### ISSUE TITLE
Smeltery causing a "Ticking Memory Connection" crash

### ISSUE THREAD

**Issue by taharihrogers** [SlimeKnights/TinkersConstruct#3956]
My Beyond Reality's Divergence server is crashing anytime I try to pour things out of the smeltery. If it's relevant: Fastcraft is enabled on the server, but the error occurs even when it's not enabled. I haven't tested if it occurs with any of the other mods though. From the looks of the crash report it seems its just Tinker's that's responsible for it.

Here is a link to a pastebin with the crash report: https://pastebin.com/0FK6BpdA

**Versions:**
* Minecraft: 1.7.10
* Forge: 
* Mantle: 1.7.10-0.3.2b
* Tinkers Construct: 1.7.10-1.8.8

**Comment by KnightMiner** [comment]
We have not released a 1.7.10 build in nearly 4 years, there will not be new fixes for that.

Your crash is caused by a missing tile entity in the world, hard to tell why it's missing, but if you used the latest builds for 1.12 we have long since added safety checks for that
