### ISSUE TITLE
Projectile attack damage is affected by player's attack speed

### ISSUE THREAD

**Issue by TheRandomLabs** [SlimeKnights/TinkersConstruct#3957]
**Issue description:**
When a player uses a projectile weapon, such as a crossbow, and if the player's attack speed (`SharedMonsterAttributes#ATTACK_SPEED`) is slowed down, the projectile deals minimal damage. This is an issue when using a mod such as [RandomConfigs](https://www.curseforge.com/minecraft/mc-mods/randomconfigs), which can be used to prevent bows from easily being used as melee weapons. Relevant issue: TheRandomLabs/RandomConfigs#11

This behavior is the result of [this](https://github.com/SlimeKnights/TinkersConstruct/blob/f3fe5e21b98db2c7485ac39e3c5c1ebdae9eb34d/src/main/java/slimeknights/tconstruct/library/utils/ToolHelper.java#L703) line. `EntityPlayer#getCooledAttackStrength` returns `0.0F`, significantly reducing the damage dealt. A possible solution could be to use `1.0F` as the attack strength if `tool` is an instance of `ProjectileCore`.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.123

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
No, another mod must be installed to set the player's attack speed, e.g. RandomConfigs.

**Comment by KnightMiner** [comment]
Please fill.in the rest of the information from the template, notably mod versions and minimal mods to reproduce

**Comment by TheRandomLabs** [comment]
Sorry, I didn't think it was important. Done!
