### ISSUE TITLE
Trap Doors and Pressure Plates not Visible in Casting Table

### ISSUE THREAD

**Issue by OceanSnipe17** [SlimeKnights/TinkersConstruct#3965]
Trap doors and pressure plates do not show up when you put them in the casting table, its like they render inside the table model itself. i have a few custom recipes that call for pouring iron on trap doors and pressure plates to make their iron versions. It still works just fine but visually you cant tell the difference.

I am on version 1.12.2

Tinkers Version TConstruct-1.12.2-2.12.0.157.jar

**Comment by KnightMiner** [comment]
Marking this in the 1.12 milestone to fix if its trivial and if we do another build, but odds are this will not be easy to fix without breaking the rendering for other blocks.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. 1.16 has different transforms on the items making them visible. Not sure how easy it would be to fix this on 1.12.
