### ISSUE TITLE
Crash when puring out liquid XP from open blocks

### ISSUE THREAD

**Issue by NancokPS2** [SlimeKnights/TinkersConstruct#3967]
**Issue description:** As i always do with tconstruct, i used the Tinker Tank to store liquid exp since i ran out of space with OpenBlocks tanks, when i did it this time around the exp appeared purple inside the tank with his texture only showing in the GUI, trying to extract it using the faucet crashes the game, i've also noticed many recipees missing, like not being able to pour resonant ender into a gem cast, not being able to pour destabilized redstone into a block cast, etc (all of this worked on my previous playrough)

**If crashed, link to crash report:** https://pastebin.com/g61uapuz

**Versions:**
* Minecraft: 1.12.2 
* Forge: 14.23.5.2846
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Requires OpenBlocks and OpenModsLib, thermalfoundation may be involved as well
I'm also using plustic, tinkersjei, tcomplement and tinkertoolleveling

**Comment by bonii-xx** [comment]
Sounds a lot like something in your modpack changed, like the mod that added your liquid xp getting removed. It shouldn't crash nontheless, might be a potential load-handling bug if the liquid got removed.
Also none of these things are added by TiC itself, so if it used to work there's no guarantee that it still works.

**Comment by ProsperCraft** [comment]
Having a similar crash - https://gist.github.com/ProsperCraft/4f3638058d72af58706a2262809a5338

Ichor from NetherEx in our Tinkers smeltery is missing a texture, when poured into an empty casting table the client crashes his single player world.

Reproduced here - https://paste.dimdev.org/xuduzubipu.mccrash

**Comment by ProsperCraft** [comment]
![2020-03-08_13 01 38](https://user-images.githubusercontent.com/4427684/76170295-38fe0d00-6146-11ea-8e1c-2e1986f6aa35.png)
![2020-03-08_13 03 53](https://user-images.githubusercontent.com/4427684/76170297-3996a380-6146-11ea-9f60-449a07b1fa06.png)
![2020-03-08_13 06 50](https://user-images.githubusercontent.com/4427684/76170298-3a2f3a00-6146-11ea-886b-af0967a71d0e.png)

**Comment by bonii-xx** [comment]
Remove vanillafix. They do stupid things and insert code into our rendering. That's what breaks.

**Comment by ProsperCraft** [comment]
Settings this in the vanillafix config stops the crashes-
B:textureFixes=false

**Comment by bonii-xx** [comment]
@ProsperCraft I don't have setup to reproduce this issue. Can you check if (with the fixes enabled) it still crashes when using this version? (And yes you have to unzip it because github doesn't allow jars)
[TConstruct-1.12.2-2.13.0.181.jar.zip](https://github.com/SlimeKnights/TinkersConstruct/files/4308416/TConstruct-1.12.2-2.13.0.181.jar.zip)

**Comment by NancokPS2** [comment]
> Remove vanillafix. They do stupid things and insert code into our rendering. That's what breaks.

I don't remember VanillaFix causing that issue, since i always paied it with Tinker in the past, maybe i changed some setting at some point and didn't realize
I'll try with that fix, thank you

**Comment by bonii-xx** [comment]
We actually released a fix, so the latest TiC version simply disables the vanillafix hackery.
