### ISSUE TITLE
Liquid Blue Slime has no recipies?

### ISSUE THREAD

**Issue by NotReallyACat** [SlimeKnights/TinkersConstruct#3968]
Just noticed the liquid Blue slime has no recipes is this a bug or just not been implemented yet? If so can they get some recipes other wise its just taking up space.
![2019-10-19_17 18 11](https://user-images.githubusercontent.com/49882452/67148197-9fb48400-f294-11e9-8183-987cd38aef42.png)
![2019-10-19_17 18 15](https://user-images.githubusercontent.com/49882452/67148198-9fb48400-f294-11e9-9e24-a314314f43e6.png)

**Comment by PrincessOfEvil** [comment]
It's the liquid on the islands that spawns slimes, so it obviously has no recipes or uses.

**Comment by NotReallyACat** [comment]
> 
> 
> It's the liquid on the islands that spawns slimes, so it obviously has no recipes or use

It would be nice if had more uses like like industrial foregoings pink slime or purple slime, at least the ability to get convert it in to slime balls would be great. I have 112 buckets of blue slime liquid as I had to remove a slime island so what do I do with them now besides use some of is to create a slime spawn area.

**Comment by YaibaToKen** [comment]
Would be nice if it had the same item and block types as purple slime.

**Comment by bonii-xx** [comment]
You can make slime tools out of them. Is that not good enough for you? ;P
Anyway, staying as it is.
