### ISSUE TITLE
Part Builder only works if full Material Cost is satisfied at once

### ISSUE THREAD

**Issue by delan** [SlimeKnights/TinkersConstruct#3969]
I searched for an existing issue but didn’t find one, sorry if this is a dupe.

**Issue description:**

To make a Flint Pickaxe Head you need a Pickaxe Head Pattern and 2 Flint, and this works for me if I drop two or more Flint onto the table at once, but if I drop them one at a time, the right hand side stays empty.

![screen recording](https://bucket.daz.cat/6ae89f47f3d01e09.gif)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2846
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Yes (the GIF was recorded in an FTB Academy world, but I can reproduce it in a clean world with Tinkers’ Construct only)

**Comment by bonii-xx** [comment]
Vanilla bug, sadly there's no way to detect stacksize changes because it doesn't fire any event.
