### ISSUE TITLE
Inconsistency around inserting into a tool station

### ISSUE THREAD

**Issue by TomyLobo** [SlimeKnights/TinkersConstruct#3970]
**Issue description:**
I can insert items into a tool station with a hopper, but not with most mod pipes:

| ↓via   into →                             | Chest | Tool Station |
|-------------------------------------------|-------|--------------|
| Vanilla Hopper                            | works | works        |
| Actually Additions Hopping Item Interface | works | doesn't work |
| Integrated Dynamics Item Exporter         | works | doesn't work |
| Thermal Dynamics Itemduct                 | works | doesn't work |

Insertion was, as far as I can tell, disabled along with extraction between 2.7.2.19 and 2.7.2.30 with #3143 to address #3104.
I think either it should also not be possible to insert with a hopper or (what I would prefer) it should be possible to insert into the tool station with any pipe.

**If crashed, link to crash report (use a site such as pastebin):**
N/A

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2846
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
* Actually Additions: 1.12.2-r150

**Comment by bonii-xx** [comment]
That's because the vanilla hopper falls back to vanilla insertion logic if capability insertion logic cannot insert. The code just denies capability insertion logic. It's either a forge bug or working as intended, depending on how you look at it.

As you said yourself, it was disabled, and we don't plan on enabling it again, sorry.

**Comment by TomyLobo** [comment]
I'm curious about why it was disabled in the first place.
The Git log only mentions extraction:
https://github.com/SlimeKnights/TinkersConstruct/commit/3e1d0384edf502f842bec86e9b297531e1fe46c9

**Comment by bonii-xx** [comment]
You can click the issue number (#3104) in the commit to get to the referenced issue.

**Comment by TomyLobo** [comment]
I'm aware of that issue.
From what I can tell, you'd need to extract items in order to duplicate things.
