### ISSUE TITLE
Tinkers Construct ores not spawning

### ISSUE THREAD

**Issue by murdermania** [SlimeKnights/TinkersConstruct#3972]
**Tinkers construct ores not spawning**

**Me and a friend instaled today tinkers C with a couple of mods (twilight forest and thaum craft) but we started to play and found no aluminium, copper or tin ores. We went to a creative map(new) and could not find the items on our inventory , the rest was there but not the ores. I went to the config files and found nothing about cooper, aluminiu or tin gen , just ardite and cobalt. I also checked the wiki config files and the file they talk about t (TinkersWorkshop.txt.) was not in my config file. I dont know what to do. 
I spent ours looking for other solutions but adding other mods as some people gugested doesnt seem to fic it because the ores dont smelt
Please help me , im going crazy:, also take in account i know nothing about programing so go easy on me.**

**Versions:**
* Minecraft: java edition  
* Forge: 1.12.2 - 14.23.5.2847
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
We have not provide the ores since 1.7, read the FAQ.
