### ISSUE TITLE
Tinkers' Smeltery is empty

### ISSUE THREAD

**Issue by migars123** [SlimeKnights/TinkersConstruct#3973]
**Issue description: The category of the tinkers' smeltery is empty, that way its completely unplayable.**
![image](https://user-images.githubusercontent.com/49610469/67328715-c7645000-f511-11e9-943c-920a5d5b5138.png)

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-forge1.12.2-14.23.5.2847
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
https://drive.google.com/file/d/1RnD1ZsMo0mQhWYKR3H7Pw1JulEUpD7vt/view?usp=sharing

**Comment by KnightMiner** [comment]
Your issue is the smeltery module is disabled, check your TinkersModule.cfg file to enable it again.

----
Also, you do not need 37 mods to reproduce this issue. You saying 37 mods are required says you did not try to reproduce this with fewer mods.

**Comment by migars123** [comment]
How do I activate it?
Where can I find the TinkersModule.cfg

**Comment by bonii-xx** [comment]
In your config directory, where all config files reside.
