### ISSUE TITLE
How can I activate the smeltery module?

### ISSUE THREAD

**Issue by migars123** [SlimeKnights/TinkersConstruct#3975]
**Issue description: I've done an issue report of my Tinkers' Smeltery being empty(https://github.com/SlimeKnights/TinkersConstruct/issues/3973) and he answered, but I don't know how to activate it and where the file is. Could you please help?**

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-forge1.12.2-14.23.5.2847 
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135

**Comment by KnightMiner** [comment]
This question would be better asked on the [Forge forums](https://www.minecraftforge.net/forum/) or Minecraft Forums as it is not an issue with Tinkers Construct code.

You find the config file in the same place as all other config files. The config folder is in the same folder as the resource packs folder and the world saves folder. I strongly suggest googling this as there are many guides on setting a config file.
