### ISSUE TITLE
Craft Crash

### ISSUE THREAD

**Issue by helpme1212** [SlimeKnights/TinkersConstruct#3977]
**Crafted construct crafting table, grout and it crashed the game**

**https://paste.dimdev.org/vipavikime.mccrash**

**Versions:**
* Minecraft: 1.12.2
* Forge: 
* Mantle: 
* Tinkers Construct: Last version

**Comment by bonii-xx** [comment]
That crash happened in an inventory screen, not one of our GUIs. We're not displaying recipebooks in any of our screens either. You probably have some mod that's messing with GUIs. Try reproducing with only TiC, keep adding mods until it happens, then you'll know which mod is at fault.
