### ISSUE TITLE
[FEATURE REQUEST] Config Option to make TiC tools Enchantable

### ISSUE THREAD

**Issue by xlea99** [SlimeKnights/TinkersConstruct#3979]
Hello, I'm currently designing a modpack in which I use a lot of different game mechanics to change up the usual modded MC experience. I was really hoping to be able to combine TiC tools with mods like Apotheosis to create a unique, unified feel between all the mods installed. 

I don't know how difficult it would be, but just a simple config option that allows TiC tools to be enchanted and basic modifiers disabled would be amazing. There doesn't even have to be any logic (pickaxes can have efficiency, can't have sharpness, etc) attached to it, I could customize all that myself via other mods like CraftTweaker and Enchantment Control.

Thank you so much for your time!

**Comment by bonii-xx** [comment]
The materials and the tools system is designed around using modifiers and having no enchantments.  It also gives people false expectations of TiC. I do not intend to split this up, ever. Sorry.
