### ISSUE TITLE
net.minecraft.client.renderer.StitcherException

### ISSUE THREAD

**Issue by FrostCreeper07** [SlimeKnights/TinkersConstruct#3980]
**Issue description:**
Can you help me figure this flipping error, i have absolutely no resource packs so that's obviously not the problem i'm about ready to scream because i don't understand what this error is about, i have 4 crash reports with the same error all with different items. For ease i'll link to one of them the error is the same just with different items.  

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/p4FqShk2

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.171 (For use with constructs armory)

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
um no the list of mods i have installed is at the bottom of crash report, i'd recommend using all of them and see if it can be reproduced as i don't know what mod is causing it and plus at this moment i'm at wits end.

**Comment by YaibaToKen** [comment]
You'll want to reduce that mod list to the bare minimum needed to reproduce. You can do this by removing half of your mods and seeing if it still happens. If it doesn't then test the other half. If it does repeat the process by removing half of those mods and testing again.

**Comment by KnightMiner** [comment]
Not needed for this issues the problem is simply he has more textures than fit in the texture sheet. I cannot remember exactly which part adjusted that, I think partly RAM and partly GPU. It's a side effect of having nearly 300 mods installed.

**Comment by bonii-xx** [comment]
Yup, your computer simply isn't able to handle all the mods you're using together.
