### ISSUE TITLE
cannot build from source 

### ISSUE THREAD

**Issue by Daniel-Pyemont** [SlimeKnights/TinkersConstruct#3981]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

There is no crash report, just an error when compiling from source.
"Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0."

I am not using Gradle 7.0, I am using Gradle 6.0.

**Versions:**
* Minecraft:  1.14.4
* Forge: 1.14.4 281.87
* Mantle: 1.14.4-1.4.32
* Tinkers Construct: Cloned the download straight from the git hub.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Other source mods do the same, so unless I miss something.

**Comment by bonii-xx** [comment]
Use the provided gradle wrapper.

**Comment by Daniel-Pyemont** [comment]
> Use the provided gradle wrapper.

I have used the included gradle wrapper, would it be because I downloaded a separate gradle and pathed it to that?

**Comment by bonii-xx** [comment]
Yes. Because that defeats the purpose of the gradle wrapper.

**Comment by Daniel-Pyemont** [comment]
> Yes. Because that defeats the purpose of the gradle wrapper.

Cheers,

So for every mod, I use the included gradle wrapper, and not the official one.  Good to know.

**Comment by Daniel-Pyemont** [comment]
So I managed to get it working, however, It is stuck on 61% for ages of building the source.

https://ibb.co/dPn6cgy (screenshot).

**Comment by bonii-xx** [comment]
> So for every mod, I use the included gradle wrapper, and not the official one. Good to know.

Yes. I suggest looking into https://docs.gradle.org/current/userguide/gradle_wrapper.html

> So I managed to get it working, however, It is stuck on 61% for ages of building the source.

That's all forgegradle, nothing we do. Have you tried simply running it again?

**Comment by Daniel-Pyemont** [comment]
> > So for every mod, I use the included gradle wrapper, and not the official one. Good to know.
> 
> Yes. I suggest looking into https://docs.gradle.org/current/userguide/gradle_wrapper.html
> 
> > So I managed to get it working, however, It is stuck on 61% for ages of building the source.
> 
> That's all forgegradle, nothing we do. Have you tried simply running it again?

Yes, I'm going to try on different system, to see if it's because I installed Gradle? Or config issue.

**Comment by Daniel-Pyemont** [comment]
No dice, I even installed older version of Java to see if it was the version (V6Update45)

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find net.minecraftforge:forge:1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.
     Searched in the following locations:
       - file:/C:/Users/Administrator/.m2/repository/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.pom
       - file:/C:/Users/Administrator/.m2/repository/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
       - https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.pom
       - https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
       - https://dvs1.progwml6.com/files/maven/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.pom
       - https://dvs1.progwml6.com/files/maven/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
       - https://maven.tterrag.com/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.pom
       - https://maven.tterrag.com/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
       - https://maven.k-4u.nl/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.pom
       - https://maven.k-4u.nl/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
       - https://tehnut.info/maven/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.pom
       - https://tehnut.info/maven/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
       - https://maven.covers1624.net/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.pom
       - https://maven.covers1624.net/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
       - file:/C:/Users/Administrator/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.pom
       - file:/C:/Users/Administrator/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
       - https://libraries.minecraft.net/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
       - https://repo.maven.apache.org/maven2/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.pom
       - https://repo.maven.apache.org/maven2/net/minecraftforge/forge/1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75/forge-1.14.4-28.1.56_mapped_snapshot_20190912-1.14.3_at_220e4758573a6d881bfaee05adcb98e2d0d45b75.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 31s
1 actionable task: 1 executed

**Comment by bonii-xx** [comment]
> No dice, I even installed older version of Java to see if it was the version (V6Update45)

You'll need at least java8. Looks like it didn't set up forge correctly. Again, this has nothing to do with TiC, but your environment. I suggest setting up a blank dev workspace to see if that even works for you, before trying to setup TiC.

**Comment by bonii-xx** [comment]
Closing this for tracker cleanup.
