### ISSUE TITLE
[1.12.2] Endspeed Bolts/Arrows 'skips' mobs if you have a high Range Multiplier.

### ISSUE THREAD

**Issue by SonicX8000** [SlimeKnights/TinkersConstruct#3982]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 10
CommonCapabilities-1.12.2-2.4.3
Cyclic-1.12.2-1.19.17
CyclopsCore-1.12.2-1.4.0
Forgelin-1.8.4
industrialforegoing-1.12.2-1.12.13-237
IntegrationForegoing-1.12.2-1.9
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
TConstruct-1.12.2-2.13.0.171
tesla-core-lib-1.12.2-1.0.15

-----

The Endspeed Trait allows your projectiles to travel instantly... it's so instant that it's like a sniper bullet that pierces through mobs, damaging them if they're lined up... however it seems that if you have a Bow Limb with a high Range Multiplier and you're using Endspeed projectiles... the projectile will 'skip' mobs without damaging them if they're lined up. Here's a screenshot...

![](https://cdn.discordapp.com/attachments/377171551155650560/643558821557567562/RMEndspeedTest.PNG)

I am using Cyclic Dummy Mobs since they don't move although I did do a test without Cyclic installed with Zombie Pigmen, the same thing occurs. In the upper left corner is a hud that marks down what mobs were hit.

Green means that mob was hit while Red means that mob wasn't hit. Any of the numbers that appear above the mob tells you how much damage the attack dealt to them, if they were damaged at all.

***Top:***
Using a Reinforced Pink Slime Bow Limb on a crossbow, it has 5.3 RM and I fired 3 Endspeed Bolts.
3 of 5 dummy mobs were hit by the projectile.

***Bottom:***
Using a Knightslime Bow Limb on a crossbow, it has 2 RM and I fired 3 Endspeed Bolts.
5 of 5 dummy mobs were hit by the projectile.

My only guess with this is that the projectile is launched so fast that it skips over mobs that are lined up although slower projectiles will hit them without issue.

Reinforced Pink Slime if I recall is from 'IntegrationForegoing' and as far as I know has the highest RM at 5.3. I don't think any of the vanilla tinker's materials have a high enough RM.

**Comment by bonii-xx** [comment]
I'm relatively sure that your derivation is correct. I don't have time to look into it further right now. Might only be fixed with 1.14. However it's relatively low priority for us since it only happens with 3rd party materials, which have ridiculous values at that.

**Comment by KnightMiner** [comment]
Not sure this is fixable easily, but will mark it in the milestone to look at again if we do another build. Might end up being won't fix.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support.
