### ISSUE TITLE
Cant melt Slime balls

### ISSUE THREAD

**Issue by Supernt26** [SlimeKnights/TinkersConstruct#3983]
**Issue description:**
Cant melt slime balls
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Email me so i can send u all 52 mods installed

**Comment by KnightMiner** [comment]
What do you mean you cannot melt slimeballs? What color slimeballs are you trying to melt? Most colors are not meltable with the exception of purple.

**Comment by KnightMiner** [comment]
Closing for lack of response
