### ISSUE TITLE
Can/'t emboss some materials onto crossbow bolt

### ISSUE THREAD

**Issue by HaxtonSale1** [SlimeKnights/TinkersConstruct#3984]
**Issue description:** I could emboss Pig Iron arrowhead to a crossbow bolt, but not Manyullyn arrowhead. 

![2019-11-15_22 59 18](https://user-images.githubusercontent.com/13237198/68948663-b4385d80-07fb-11ea-9007-e3fa35a21085.png)
![2019-11-15_22 59 28](https://user-images.githubusercontent.com/13237198/68948665-b6022100-07fb-11ea-8416-d05cdda11056.png)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** Yes

**Comment by bonii-xx** [comment]
Bolt embossing is quite tricky due to bolt shafts unique double-material nature. It probably broke during the last round of fixes. I'll try to solve the general problem in 1.14, since I don't really have time for 1.12.

**Comment by KnightMiner** [comment]
Going to close this as bolts are removed in 1.16 and 1.12 bolt code is too complex to be worth changing in a bugfix release. My understanding is you can use arrow shafts to emboss, so this just limits some embossment options.
