### ISSUE TITLE
Block of Cobalt has some wrong ore dictionaries

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [SlimeKnights/TinkersConstruct#3986]
**Issue description:**
Block of Cobalt has 2 wrong ore dictionaries:

1. oreCobalt
2. oreArdite

![2019-11-16_10 09 01](https://user-images.githubusercontent.com/37864486/68986395-f8f2e180-0859-11ea-8317-5f6a15b50ed4.png)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

IE 0.12-92

**Comment by KnightMiner** [comment]
Can you please show a screenshot of the issue with just Tinkers and Immersive Engineering if that is the minimal required? We do not add that oredict so I have no idea why it would be set.

**Comment by mc-kaishixiaxue** [comment]
IE can show the item's ore dictionary.

**Comment by mc-kaishixiaxue** [comment]
Only Tic is normal.
![2019-11-16_13 25 47](https://user-images.githubusercontent.com/37864486/68988586-b25eb080-0874-11ea-8de0-1902ff078a78.png)

[crash-2019-11-16_13.30.13-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3853851/crash-2019-11-16_13.30.13-client.txt)
mods list (created by "f3+c" button)

**Comment by KnightMiner** [comment]
Can you try to narrow down that mod list? The easiest way is to cut out half the mods at a time until the problem disappears.

**Comment by 3TUSK** [comment]
https://github.com/gkbm2013/tinker-IO/blob/dc8e69c78a632924a75a3eccda920a5093a5792e/src/main/java/tinker_io/registry/OreDictionaryRegister.java#L9-L10

Looks like it's on Tinker I/O side.

**Comment by KnightMiner** [comment]
I have absolutely no idea what their goal with that is, I was expecting this to be accidental from a registry scan from some mod.

Mind crossposting this issue to their tracker?

**Comment by 3TUSK** [comment]
https://github.com/gkbm2013/tinker-IO/blob/6197708b5b2c114f1c34ff87987d7f725051885f/src/main/java/tinker_io/registry/OreCrusherRecipeRegister.java#L69-L72

I assume they want some extra auto-cross-mod compatibility for this…

> GitHub search is your friend. 

Also Tinker I/O hasn't had new commit in past one year or so…

**Comment by gkbm2013** [comment]
Hello, the bug was solved in Tinker I/O rw2.8.0. Thank you all for discussing the issue. 😊
https://github.com/gkbm2013/tinker-IO/commit/f3d08037ec412b33bcbbe9ae16cc2b536102ffda
