### ISSUE TITLE
Missing ID for Cobalt Dust and Ardite Dust

### ISSUE THREAD

**Issue by Taquios** [SlimeKnights/TinkersConstruct#3989]
I loaded up SkyFactory 4 with all the mods updated and when I go into the server I have it gives an error where it is missing recipes for ardite dust and cobalt dust. After further investigation they don't seem to have a mod id in the config file, which leads me to believe that is what is causing the issue.

* Minecraft: 1.12.2
* Forge: forge-14.23.5.2847
* Mantle: Mantle-1.12-1.3.3.55.jar
* Tinkers Construct: TConstruct-1.12.2-2.13.0.171.jar

![Screenshot (5)](https://user-images.githubusercontent.com/44000407/69904434-53b92c80-1374-11ea-8b69-9acbe89ba3c7.png)
![Screenshot (6)](https://user-images.githubusercontent.com/44000407/69904442-59167700-1374-11ea-9fe8-403119293e30.png)

**Comment by KnightMiner** [comment]
Tinkers Construct does not have cobalt or ardite dust. It is pretty clear from the recipe that those were added by another mod (in this case, custom items from content tweaker).

It sounds like you loaded up the modpack wrongly as it is not getting all the configs loaded right. In any case, this is not a Tinkers Construct issue, but an issue with how you configured the pack. If it is unmodified configs and mod versions, take this to the SkyFactory 4 issue tracker. If you modified configs or mod versions, take it to the Minecraft Forums for help.
