### ISSUE TITLE
Game crashes upon login after making a sharpestest arrow

### ISSUE THREAD

**Issue by Emilyy27** [SlimeKnights/TinkersConstruct#3990]
Game crashed while going into render distance of the sharpestest arrow (Arrow is manyullin)
Happened while playing hexxit modpack (added tinkers tool leveling as well)

**If crashed, link to crash report (use a site such as pastebin): https://paste.dimdev.org/buqarizexi.mccrash

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2847
* Mantle: 1.12-1.3.3.55    
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
It can be reproduced with just Tinkers but the reason of crash stated by the game was also cause by abyssalcraft.

**Comment by KnightMiner** [comment]
If this can happen with just Tinkers, please post a crash report from just Tinkers. I am pretty sure this is an abyssalcraft issue with broken model tinting

Also, this crash does not look related to the arrows, it looks like you put an item on one of our tables that crashes when getting the color. You should be able to disable the table renderer to load the world again and find the item causing the crash. The crash says the table is at -131,63,120.
