### ISSUE TITLE
Trait "hellish" printed to console

### ISSUE THREAD

**Issue by Pheubel** [SlimeKnights/TinkersConstruct#3991]
**Issue description:**
When using the "hellish" trait on a "non-nether mob" (such as creeper) "boosted" gets printed in the server console. when used on scythe in a crowd, it spams the console. 

If i were to make a guess, i think that this line is responsible for this:
https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/tools/traits/TraitHellish.java#L25

**Versions:**
* Minecraft: 1.12
* Forge:  1.12-14.23.5.2847
* Mantle: -
* Tinkers Construct: 1.12.2.2-2.13.0.171

**server console output:**
![afbeelding](https://user-images.githubusercontent.com/22686676/70377913-62768500-191a-11ea-97dd-f8c6642c4fe6.png)

**Comment by bonii-xx** [comment]
Ah yes, debug code. Thanks for reporting it.

**Comment by Pheubel** [comment]
no worries, the only reason i found out about it in the first place because a friend of mine got scared of all the messages.

**Comment by jkapi** [comment]
I have the same problem, the console is absolutely spammed full, and the debug.log is gigantic
![chrome_YALYAbwb31](https://user-images.githubusercontent.com/16419568/72527787-d5541380-3869-11ea-87e2-3d85c4dfd3f7.png)
![chrome_JY8tbePfA1](https://user-images.githubusercontent.com/16419568/72527789-d5ecaa00-3869-11ea-9316-139697db6865.png)

**Comment by bonii-xx** [comment]
Yes, it has not been fixed yet since we currently don't work on 1.12. If we do a last 1.12 release we'll fix it.
