### ISSUE TITLE
Tin not added

### ISSUE THREAD

**Issue by CircusSeal** [SlimeKnights/TinkersConstruct#3992]
**Issue description:**
Along with Tinkers' Construct, I have Immersive Engineering and Forestry, both of which add certain ores. As promised on the main page, most of these ores were added into Tinkers' Construct automatically, except for Tin from Forestry. I haven't tried it with a smeltery, as I have not built one yet, but Tin is not included in the Materials and You material guide.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: release 1.12.2-forge1.12.2-14.23.5.2838
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Forestry; you can also add Immersive Engineering if you want.

**Comment by KnightMiner** [comment]
It does not show in the book as it is not a valid tool material. We add integration to melt tin down, but not as a tool material. You must alloy it with copper to make bronze to make tools.
