### ISSUE TITLE
Automating Evil Infused Tools

### ISSUE THREAD

**Issue by dnulho** [SlimeKnights/TinkersConstruct#3994]
**Issue description:**
Tools with an Evil Infused Part break on first use in multiple automated use machines.

**If crashed, link to crash report (use a site such as pastebin):**
NA

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
It is happening inside the Enigmatica 2: Expert v71 Pack, I haven't tried to drill down to exactly what mods are necessary to reproduce, but at least Extra Utilities (v1.9.9). Tried to automate with Extra Utilities Mechanical User, and Cyclic (v1.19.12) Automated User with same effect.

https://github.com/NillerMedDild/Enigmatica2Expert/issues/1436

**Comment by TherminatorX** [comment]
Does this bug occur with a tool that doesn't use materials provided by Extra Utilities 2? RWTema has been known to do unfriendly things with user blocks in the past, despite having them in their mod.

**Comment by SweetSugarSugar** [comment]
Evil Iron is added by ExU2 so not something Tinkers' can control.  Also it is intended for Evil Iron tools to break upon using them in any machine.  It's in one of the descriptions somewhere (as a trait I believe).

**Comment by dnulho** [comment]
This appears to be intended behavior, apparently. I think that the in-game documentation needs to be adjusted to better bring this to the player's attention though. And maybe this ticket will help people in the future, as I didn't find anything related to the inability to automate Evil Infused tools on Google either...
