### ISSUE TITLE
Stencil Table GUI scaling cuts off stencils

### ISSUE THREAD

**Issue by astra-midnight** [SlimeKnights/TinkersConstruct#3995]
I have Constructs Armory installed which already adds a lot of new stencils as well as PlusTiC and then I installed Yoyos and that added more stencils. Now I cannot see all the stencils on the screen without setting the scale to something smaller than the default (Auto). Perhaps some sort of pagination here would be appropriate?

**Comment by bonii-xx** [comment]
Hm, this is a somewhat edge case. There are hardly any situations where it's required and pagination is simply more effort to implement than it's worth it. Might see if an UI scaling approach is enough (the books also do that, up to a minimum, in their listings).
Probably wont be any change before 1.14/1.15 though.

**Comment by astra-midnight** [comment]
Yea, I think scaling it would be just as fine.

**Comment by KnightMiner** [comment]
This is fixed in 1.16. I don't feel like rewriting the UI on 1.12 to try to fix this, so unfortunately my best suggestion is installing fewer addons or installing a mod like TipTheScales that lets you apply a smaller UI scale.
