### ISSUE TITLE
Thermal Foundation liquid textures are missing

### ISSUE THREAD

**Issue by xJon** [SlimeKnights/TinkersConstruct#3996]
**Issue description:**
Reported in my modpack over https://github.com/xJon/The-1.12.2-Pack/issues/54, also reported over https://github.com/Landmaster/PlusTiC/issues/231 & related to https://github.com/SlimeKnights/TinkersConstruct/issues/3402 - but King Lemming said that the textures are:
> supposed to auto-gen
that's what their api claims
I'm using their texture, exactly how I am supposed to
https://github.com/CoFH/ThermalFoundation/blob/1.12/src/main/java/cofh/thermalfoundation/plugins/PluginTConstruct.java

Is there anything that can be done?

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
* Thermal mod suite.

**Comment by Routhinator** [comment]
Seeing this in our modpack as well.

**Comment by bonii-xx** [comment]
But does it happen if you ONLY use TiC and TE?

**Comment by KnightMiner** [comment]
Also, the screenshot posted shows that the in world model is missing, not the texture. It looks like for some reason it is trying to pull a non TiC fluid from the TiC fluid block model. Is this possibly an API weakness a they do not have a way to add to our model?

**Comment by xJon** [comment]
As @Routhinator mentioned here: https://github.com/Landmaster/PlusTiC/issues/231#issuecomment-569146851
> Thermal foundation has removed in-world liquid <metal> from their mod

I have checked and Tinkers' doesn't add it back, but PlusTiC does.

**Comment by KnightMiner** [comment]
My understanding is some mods had this working, and our API docs were just not super accurate. Registering fluids for another mod is not a great idea in any case, which is why our 1.16 API does not do this at all.

Based on that and the fact PlusTiC no longer exists (and thermal removed the in world blocks), going to close this as more effort than its worth to fix on an old version.
