### ISSUE TITLE
Techguns materials aren't adding themselves

### ISSUE THREAD

**Issue by YonathanYeager** [SlimeKnights/TinkersConstruct#3998]
So recently, (I know it's super late) I updated from MC1.7.10 to MC1.12.2. In 1.7.10, TC automatically added the Carbon(and maybe more) material to TC's weapons. However, now in 1.12.2, none of the materials from Techguns have weapons or parts in TC.
Now that I got that explained, Is there a way to get TC to auto add the materials? If not, is there a way to manually add them (And if so, can I set custom attributes for the materials?)?

No crash.

* Minecraft:From 1.7.10 to 1.12.2
* Forge:MC1.7.10-.13.4.1558---MC1.12.2-.23.5.2847
* Mantle:MC1.7.10-0.3.2b---MC1.12.2-1.3.3.55
* Tinkers Construct:MC1.7.10-1.8.8---MC1.12.2-2.13.0.171

Techguns, which requires chisel, chisel requires CTM

**Comment by KnightMiner** [comment]
Tinkers Construct does not automatically add those, I assume it was added on Tech Guns side and never got ported.

In any case, in 1.12 Tinkers only adds integration for common materials, specific mod support is left to the mod or to addons. I suggest you ask on Tech Guns GitHub or one of those addons, though I will warn a lot of mods are moving to 1.14 so 1.12 is getting fewer updates.

**Comment by YonathanYeager** [comment]
Okay, will do. Is there a way to manually add them if asking Tech Guns is a dead end?

**Comment by KnightMiner** [comment]
If you want proper materials, you can write your own add-on mod. Content tweaker is an option if you don't care about the materials not having unique traits
