### ISSUE TITLE
Unable to use blazing pyrothreum as fuel

### ISSUE THREAD

**Issue by EnhancedC** [SlimeKnights/TinkersConstruct#3999]
i cannot use blazing pyrotheum as fuel and cant melt certain metals. jei even says that to be able to mel "dark anvil" you need p blazing pyrotheum

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847-universal
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.171

**Comment by KnightMiner** [comment]
Are you getting atooltip on pyrothium that says it's not a valid fuel? If so, is it the same texture as the one shown in JEI?

We do not add blazing pyrothium as a fuel, that is added by some other mod. You might have multiple types of pyrothium, but in any case it sounds like a pack issue. If you can verify that it is an issue on our side we can look into it again, but for now contact the author of the integration (whoever makes pyrothium a fuel, pretty sure it's not Thermal Expansion, they just add the fluid)
