### ISSUE TITLE
1.10.2 (sky factory 3) - Ingot cast not working, embossment not working

### ISSUE THREAD

**Issue by Physaliidae** [SlimeKnights/TinkersConstruct#4001]
**Issue description:**
Ingot cast will not work (clicking on faucet does not cause molten metal to dispense into the cast). Have attempted to make new ingot casts, reinstall tinker's construct, etc. Oddly every other cast works as expected.
Embossment also does not work properly with proper materials provided (I.e. it works in the 1.12 version, but will not work in my sky factory 3 instance).

Have attempted both above with solely vanilla/TC materials (e.g. pouring an iron ingot, embossing an iron pickaxe head onto an obsidian pickaxe with the required slime crystals and gold block) with no success. 

**Versions:**
* Minecraft: 1.10.2
* Forge: 12.18.3.2511
* Mantle: 1.1.5
* Tinkers Construct: 2.6.5.10

Playing a slightly modified version of sky factory 3 but unsure if the other mods included are required to replicate the issue.

**Comment by KnightMiner** [comment]
Embossment did not exist in 1.10.

I have never seen an issue with ingot casts for 1.10, so odds are your pack broke it. In any case, we have not supported 1.10 for years, use 1.12.
