### ISSUE TITLE
bronze alloy missing

### ISSUE THREAD

**Issue by gallifreyhanyou** [SlimeKnights/TinkersConstruct#4003]
**Issue description:**
I am using galacticraft to provide copper, tin and aluminum ore. TC recognizes the tin but won't allow it to alloy with copper to create bronze. it will create aluminum brass, though. just like silver, lead, electrum, etc that galacticraft does not provide paths for, bronze does not show up in JEI in survival as a viable liquid or ingot/block.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.12.2-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
galacticraft core
galacticraft planets
micdoodle8 core
all version number 1.12.2-4.0.2.239

**Comment by KnightMiner** [comment]
Can you verify that there are ingots of both copper and tin? If so, do they both melt properly? I have no idea why this would happen if GalacticCraft registers their items correctly.

Also, does this happen with just those mods, or do you have other mods installed? Specifically mods that change recipes.

**Comment by gallifreyhanyou** [comment]
There are indeed ingots of copper and tin as well as blocks, and they melt in the smeltery. But no matter how long I leave them in there, they won't alloy. I don't have craft tweaker or any other mods that change recipes.

EDIT: I believe I may have found the culprit? while there are copper and tin ingots and blocks, there is no bronze ingot in galacticraft. there is bronze in the form of compressed bronze sheets only. could this be causing TC to not recognize bronze as viable?

**Comment by gallifreyhanyou** [comment]
bronze ingots and blocks don't exist through galacticraft, maybe this is the problem

**Comment by KnightMiner** [comment]
That would do it, Tinkers Construct only adds a bronze fluid if there is a bronze ingot. Sounds like they only have bronze for compatibility with other mods if they have no ingot. I'll close this, take it to GalacticCraft if they actually use bronze as they should then have ingots.
