### ISSUE TITLE
Missing Textures - All Kama are missing their respective textures

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SlimeKnights/TinkersConstruct#4004]
**Issue description:**
All kamas missing their respective textures
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: Mantle-1.12-1.3.3.55 
* Tinkers Construct: TConstruct-1.12.2-2.13.0.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

I don't know. 
![truE8Q01](https://user-images.githubusercontent.com/10351221/72112556-83f4d300-3303-11ea-80d9-17928a748061.png)
![OR6MsFU](https://user-images.githubusercontent.com/10351221/72112557-83f4d300-3303-11ea-9f56-a8ff0e0fcae4.png)

**Comment by KnightMiner** [comment]
Try that last question again. You can determine if it happens with just Tinkers Construct by removing all other mods. You can test to find which mod causes this.

I have never seen this before, so you definitely have another mod breaking things.

**Comment by P3rf3ctXZer0** [comment]
Sorry I will close this.

**Comment by Giamoco** [comment]
Tinkers Compendium is probably causing this afaik.
