### ISSUE TITLE
Steel not going through faucet

### ISSUE THREAD

**Issue by MasterMarkoJ** [SlimeKnights/TinkersConstruct#4008]
Issue description:
Cant empty steel from the smeltery, and there is no aluminium/aluminium brass

Minecraft: 1.12.2
Forge: 14.23.5.2847
Mantle: Newest
Tinkers Construct: Newest

I used steel from tehguns

**Comment by bonii-xx** [comment]
What are you trying to empty it into?
Also TiC does not add any ores/materials anymore, you need a separate mod to provide aluminium.

**Comment by MasterMarkoJ** [comment]
I fixed the problem, turns out that the mods that i had didn't include any
blocks

pon, 3. velj 2020. 13:25 boni <notifications@github.com> je napisao:
