### ISSUE TITLE
Armor Render Issue.

### ISSUE THREAD

**Issue by Theisgood** [SlimeKnights/TinkersConstruct#4023]
https://github.com/TheIllusiveC4/ConstructsArmory/issues/203

**Comment by KnightMiner** [comment]
I don't see how this is a Tinkers Construct issue. We do not add armor, and you clearly know that armor is from Constructs Armory and already reported it in the proper place.

**Comment by Theisgood** [comment]
well I updated your mod I thought it could be related sorry. You don't have any ideas what could be causing this?. I am only asking cause you are a modder.

**Comment by KnightMiner** [comment]
According to the other issue, you updated multiple mods and it broke, so nothing really says its a Tinkers Construct issue unless you can say that is the only mod you changed.

I did not write any of the code related to Constructs Armory rendering (never done anything related to entity rendering), so no answers there. In general you will not get good answers from just any modder, just wait on the author's response.

**Comment by Theisgood** [comment]
Yeah I guess its my fault eh :/ well at least you were nice and still helpful :) Hopefully it gets sorted out.

**Comment by Theisgood** [comment]
Good new it was mobends-0.24_for_MC-1.12 causing the render issue, sorry for the hassle.

Now I can leave you alone. :) have a good day sir
