### ISSUE TITLE
Do material traits stack in Tinkers Construct?

### ISSUE THREAD

**Issue by S0ulCub3** [SlimeKnights/TinkersConstruct#4024]
Hello there! First off my apologies but I did not know how to add a 'question' label to this issue. 

Do material traits stack in Tinkers Construct? For example: I make a hammer with 2 x cobalt plates and 1 x ardite hammer head. Does the 'momentum' trait get boosted by the presence of more than one part giving 'momentum'? I can't tell if it should appear as "momentum II" or if it has an effect without appearing with the "II" at the end.

**Comment by SweetSugarSugar** [comment]
I believe they stack but only if it's from a different material with the same trait.  Note it will only show as "Momentum"

For future questions consider joining the Discord.

**Comment by bonii-xx** [comment]
No, in general they don't stack unless specified otherwise. The ones with a number (like flint, iron) stack from different sources.
