### ISSUE TITLE
Crash with Greg's Construct

### ISSUE THREAD

**Issue by Archilyte** [SlimeKnights/TinkersConstruct#4025]
**Issue description:**
A crash (It says with [Greg's Construct](https://github.com/hjae78/GregsConstruct))
**If crashed, link to crash report (use a site such as pastebin):**
https://paste.dimdev.org/bakuyubuda.mccrash
**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2 - 14.23.5.2847
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
This is the original [Greg's Construct](https://www.curseforge.com/minecraft/mc-mods/gregs-construct) (the link above was supposed to be a "fixed" fork)

**Comment by KnightMiner** [comment]
Greg's Construct bug, they are registering a duplicate material to another mod (Armory Expansion - MatterOverdrive). We leave it to addons to decide how to resolve conflicts as there is no good solution.
