### ISSUE TITLE
[DRAFT] Silktouch Pickaxes drop incorrect third-party ItemStacks from third-party ore blocks

### ISSUE THREAD

**Issue by AhiVT** [SlimeKnights/TinkersConstruct#4027]
**Issue description:**
Currently a draft while I pinpoint patterns in how this issue manifests to help diagnose a root cause. The issue affects multiple mods. For example, an Immersive Engineering ore block may drop Apatite ore from the Forestry mod.
**Versions:**
* Minecraft: 1.12.2
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I'm experiencing the issue with the Engineer's Life modpack.

**Comment by KnightMiner** [comment]
You probably have a mod like unidict installed to unify the ore drops, maybe is working incorrectly. All our silk touch tools do is give you vanilla silk touch.

**Comment by AhiVT** [comment]
UniDict is not installed, would a mod like CraftTweaker be capable of causing an issue like this?

**Comment by bonii-xx** [comment]
Silktouch is quite literally vanilla silktouch. Have you tried if the same happens with vanilla pickaxes that are silktouch enchanted?

**Comment by KnightMiner** [comment]
Closing for lack of response, our code just uses vanilla logic
