### ISSUE TITLE
Glue missing in 1.12.2 (?)

### ISSUE THREAD

**Issue by AechtRob** [SlimeKnights/TinkersConstruct#4029]
I don't seem to have glue as a liquid anywhere in the registries in the 1.12.2 latest version. Horses generate blood when smelted. Is this an oversight or a deprecation?

Thanks.

**Comment by bonii-xx** [comment]
Deprecated, it was a joke thing but there was no usage for it.

**Comment by AechtRob** [comment]
Oh that;'s a shame - I was looking for glue to incorporate into a modpack I am working on which also happens to include Tinkers! I liked the method of obtaining it as different from just a crafting-table recipe..
