### ISSUE TITLE
Textures not connecting for the models in 1.12.2

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#4034]
![javaw_Z0idm3J6AP](https://user-images.githubusercontent.com/60620215/73675419-4852ec00-46aa-11ea-8401-7376b59b1126.png)
**Issue description:**The machines textures are not connecting in 1.12.2 is there a mod to help this?

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by UNBEATABLE23TTG** [comment]
the glass is sopposed to connect but it isn't

**Comment by bonii-xx** [comment]
It looks like you're using seared gauges and seared windows. Those are tanks, but do not connect. If you want the connecting glass, you need to use seared glass (the non-tank one)
