### ISSUE TITLE
Crash in RAD modpack. 

### ISSUE THREAD

**Issue by jayofvt** [SlimeKnights/TinkersConstruct#4036]
**Issue description:**
When adding Tinker to a modpack Roguelike Adventure Dungeons. The mod seems to create a conflict with Betweenlands.

**If crashed, link to crash report (use a site such as pastebin):**
![image](https://user-images.githubusercontent.com/60675987/73796589-9b48a400-477b-11ea-87c3-8f072cefe64c.png)

[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/4156663/latest.log)

**Versions:**
* Minecraft: 1.12.2
* Forge: 2.13.0.171
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

[ANGRY PIXEL] The Betweenlands	oily_oli	TheBetweenlands-3.5.5-universal.jar
Aether Continuation	raptor4694	aether_continuation-1.12.2-v1.2.3.jar
Aether: Lost Content	ModdingLegacy	lost_aether-content-1.12.2-v0.1.1.jar
AI Improvements	DarkGuardsman	AIImprovements-1.12-0.0.1b3.jar
Akashic Tome	Vazkii	AkashicTome-1.2-12.jar
AppleCore	squeek502	AppleCore-mc1.12.2-3.2.0.jar
AppleSkin	squeek502	AppleSkin-mc1.12-1.0.9.jar
Aquaculture 2	Shadowclaimer	Aquaculture-1.12.2-1.6.8.jar
Aroma1997Core	Aroma1997	Aroma1997Core-1.12.2-2.0.0.2.jar
Aroma1997s Dimensional World	Aroma1997	Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar
AtomicStryker's Infernal Mobs	atomicstrykergrumpy	InfernalMobs-1.12.2.jar
Atum 2: Return to the Sands	Shadowclaimer	Atum-1.12.2-2.0.16.jar
AutoRegLib	Vazkii	AutoRegLib-1.3-32.jar
Baubles	Azanor13	Baubles-1.12-1.5.2.jar
Better Advancements	way2muchnoise	BetterAdvancements-1.12.2-0.1.0.77.jar
BetterFps	Guichaguri	BetterFps-1.4.8.jar
BiblioCraft	Nuchaz	BiblioCraft[v2.4.5][MC1.12.2].jar
Bigger Packets Please	ElNounch	biggerpacketsplz-since1.8-1.2.jar
Biome Bundle	mc_pitman	Biome_Bundle-1.12.2-v6.1.jar
Bloodmoon	Lumien231	Bloodmoon-MC1.12.2-1.5.3.jar
Bonsai Trees 2	davenonymous	bonsaitrees-1.1.4-b170.jar
Bountiful	ejektaflex	Bountiful-2.2.1.jar
Building Gadgets	Direwolf20	BuildingGadgets-2.7.4.jar
Cavern II	kegare0127	Cavern_1.12.2-v2.2.0.jar
Chameleon	Texelsaur	Chameleon-1.12-4.1.3.jar
Chance Cubes	Turkey2349	ChanceCubes-1.12.2-4.1.0.300.jar
Charm	svenhjol	Charm-1.12.2-1.3.6.jar
Chest Transporter	cubex2	ChestTransporter-1.12.2-2.8.8.jar
Chicken Chunks 1.8.+	covers1624	ChickenChunks-1.12.2-2.4.2.74-universal.jar
Chisel	tterrag1098	Chisel-MC1.12.2-1.0.1.44.jar
Clumps	Jaredlll08	Clumps-3.1.2.jar
CodeChicken Lib 1.8.+	covers1624	CodeChickenLib-1.12.2-3.2.3.358-universal.jar
Colossal Chests	kroeser	ColossalChests-1.12.2-1.7.3.jar
Comforts	TheIllusiveC4	comforts-1.12.2-1.4.1.2.jar
Compact Drawers	samtrion	CompactDrawers-1.12.2-1.0.5.125.jar
ConnectedTexturesMod	tterrag1098	CTM-MC1.12.2-1.0.1.30.jar
Controlling	Jaredlll08	Controlling-3.0.8.jar
Cooking for Blockheads	BlayTheNinth	CookingForBlockheads_1.12.2-6.4.71.jar
Corail Tombstone	Corail_31	tombstone-3.6.4-1.12.2.jar
Cosmetic Armor Reworked	LainMI	CosmeticArmorReworked-1.12.2-v4a.jar
CplPibald's Tweaks	cplpibald	PiTweaks-1.12-1.1.1.jar
CraftTweaker	Jaredlll08	CraftTweaker2-1.12-4.1.20.jar
Creeper Confetti	SR2610	creeperconfetti-1.4.2.jar
Cucumber Library	BlakeBr0	Cucumber-1.12.2-1.1.3.jar
Custom Main Menu	Lumien231	CustomMainMenu-MC1.12.2-2.0.9.1.jar
Customized Dungeon Loot	XxRexRaptorxX	Customized-Dungeon-Loot-1.12 -(v.1.0.3).jar
Cyclic	Lothrazar	Cyclic-1.12.2-1.19.19.jar
Cyclops Core	kroeser	CyclopsCore-1.12.2-1.6.0.jar
DefaultSettings	PT400C	DefaultSettings-1.8.x-1.12.x-2.1.2.jar
DimensionalDoors	DimensionalDevelopment	DimensionalDoors-3.0.9-287.jar
DiscordSuite	HRZNStudio	DiscordSuite-2.2.4.jar
Doggy Talents	percivalalb	DoggyTalents-1.12.2-1.15.1.4-universal.jar
Doomlike Dungeons	JaredBGreat	DoomlikeDungeons-1.12.10-MC1.12.2.jar
Dungeon Tactics	PegBeard	DungeonTactics-1.12.2-0.16.6.jar
Dynamic Surroundings	OreCruncher	DynamicSurroundings-1.12.2-3.6.0.2.jar
Electroblob's Wizardry	Electroblob	Electroblob's Wizardry - 4.1.4 - MC 1.12.2.jar
Embers Rekindled	BordListian	EmbersRekindled-1.13-hotfix2.jar
Embersified	TheRealp455w0rd	Embersified-1.12.2-1.0.3.jar
Enchantment Descriptions	DarkhaxDev	EnchantmentDescriptions-1.12.2-1.1.15.jar
Engineers Workshop Reborn	modmuss50	EngineersWorkshopReborn-1.12.2-1.0.9.40.jar
Extra Alchemy	zabi94	extraalchemy-0.5.2.jar
Extra Utilities	RWTema	extrautils2-1.12-1.9.9.jar
EZStorage 2	zer0fall	ezstorage-2.5.0-[1.12.2].jar
Fast Leaf Decay	olafskiii	FastLeafDecay-v14.jar
FastFurnace	Shadows_of_Fire	FastFurnace-1.12.2-1.3.1.jar
FastWorkbench	Shadows_of_Fire	FastWorkbench-1.12.2-1.7.3.jar
Fence Jumper	TheRealp455w0rd	fencejumper-1.12-1.0.5.jar
FoamFix​	asiekierka	foamfix-0.10.10-1.12.2.jar
ForgeEndertech	EnderLanky	ForgeEndertech-1.12.2-4.5.0.0-build.0435.jar
FTB Backups	LatvianModder	FTBBackups-1.1.0.1.jar
FTB Guides 2	LatvianModder	FTBGuides-2.0.0.52.jar
FTB Library	LatvianModder	FTBLib-5.4.4.5.jar
FTB Money	LatvianModder	FTBMoney-1.1.0.42.jar
FTB Quests	LatvianModder	FTBQuests-1.8.0.237.jar
FTB Utilities	LatvianModder	FTBUtilities-5.4.0.124.jar
GottschCore	gottsch	GottschCore-mc1.12.2-f14.23.5.2768-v1.10.0.jar
Heroic Armory	skeddles	heroicarmory-1.2.0.jar
Hwyla	TehNut	Hwyla-1.8.26-B41_1.12.2.jar
Ice and Fire: Dragons in a whole new light!	alex1the1666	iceandfire-1.8.3.jar
Improved Backpacks	DreenDexTwitch	ImprovedBackpacks-1.12.2-1.4.0.0.jar
InGame Info XML	Lunatrius	InGameInfoXML-1.12.2-2.8.2.94-universal.jar
Inventory Pets	Purplicious_Cow_	inventorypets-1.12-2.0.3.jar
Inventory Tweaks	JimeoWan	InventoryTweaks-1.63.jar
Iron Backpacks	gr8pefish	IronBackpacks-1.12.2-3.0.8-12.jar
Item Filters	LatvianModder	ItemFilters-1.0.3.12.jar
ItemPhysic Lite	CreativeMD	ItemPhysic Lite 1.3.7 mc1.12.2.jar
ItemZoom	mezz	itemzoom_1.12.2-1.11.jar
IvToolkit	Ivorforce	IvToolkit-1.3.3-1.12.jar
Jack-O'-Launcher	ochotonida	Jack-O'-Launcher-1.12.2-1.7.0.jar
JourneyMap	techbrew	journeymap-1.12.2-5.5.6.jar
Just Enough Items (JEI)	mezz	jei_1.12.2-4.15.0.291.jar
Just Enough Resources (JER)	way2muchnoise	JustEnoughResources-1.12.2-0.9.2.60.jar
Land Manager	bright_spark	landmanager-1.12.2-1.4.0.jar
Lapis Stays in the Enchanting Table	csb987	EnchantingTable-1.12-1.1.3.jar
LetsEncryptCraft	CloudyPSP	letsencryptcraft-1.10.2-1.2.0.jar
Level Up! Reloaded	BeetoGuy	levelup2-1.2.1.jar
LibraryEx	LogicTechCorp	LibraryEx-1.12.2-1.0.12.jar
LimeLib	KidsDontPlay	limelib-1.12.2-1.7.12.jar
Living Enchantment	Clownvin	living_enchantment-3.2.0.jar
LLibrary	_ForgeUser11902522	llibrary-1.7.19-1.12.2.jar
Login Shield	Glasspelican	Login_Shield-1.12.2-3-g7c6e7ac.jar
LunatriusCore	Lunatrius	LunatriusCore-1.12.2-1.2.0.42-universal.jar
Mantle	mDiyo	Mantle-1.12-1.3.3.55.jar
MegaLoot	Winter_Grave	megaloot-1.12.2-0.2.40.jar
Minerva Library	zabi94	minerva-library-1.0.13.jar
Mouse Tweaks	YaLTeR	MouseTweaks-2.10-mc1.12.2.jar
Mowzie's Mobs	bobmowzie	mowziesmobs-1.5.4.jar
Mystical Agriculture	BlakeBr0	MysticalAgriculture-1.12.2-1.7.5.jar
Mystical Mechanics API	BordListian	Mystical Mechanics-0.11.jar
Nature's Compass	Chaosyr	NaturesCompass-1.12.2-1.8.3.jar
Neat	Vazkii	Neat 1.4-17.jar
NetherEx	LogicTechCorp	NetherEx-1.12.2-2.0.15.jar
NetherPortalFix	BlayTheNinth	NetherPortalFix_1.12.1-5.3.17.jar
No Recipe Book	Seneschal_Luwin	noRecipeBook_v1.2.2formc1.12.2.jar
Nomadic Tents	skyjay1	NomadicTents-1.12.2-9.5.2.jar
Oops! - Undo	darkevilmac	oops-1.12-5.11.jar
Open Terrain Generator (OpenTerrainGenerator / OTG)	team_otg	OpenTerrainGenerator-1.12.2 - v6.jar
OpenBlocks	OpenMods	OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib	OpenMods	OpenModsLib-1.12.2-0.12.2.jar
Ordinary Coins	flametaichou	ordinarycoins-1.12.2-1.5.jar
Ore Excavation	Funwayguy	OreExcavation-1.4.143.jar
OreLib	OreCruncher	OreLib-1.12.2-3.6.0.1.jar
Pam's HarvestCraft	pamharvestcraft	Pam's HarvestCraft 1.12.2zf.jar
Patchouli	Vazkii	Patchouli-1.0-20.jar
Phosphor	jellysquid_	phosphor-1.12.2-0.2.6+build50-universal.jar
Placeable Items	Ferdz_	placeableitems-3.3.jar
Placebo	Shadows_of_Fire	Placebo-1.12.2-1.6.0.jar
Portable Crafting	gr8pefish	PortableCrafting-1.12.2-1.0.2.jar
Potion Core	Tmtravlr	PotionCore-1.8_for_1.12.2.jar
Prefab	wuestman	prefab-1.3.0.26.jar
Progressive Bosses	InsaneGames_	ProgressiveBosses-1.5.4-mc1.12.x.jar
Project: Vibrant Journeys	solis_nova123	ProjectVibrantJourneys-1.12.2-1.6.4.jar
Pyramid Plunder	Laton95	PyramidPlunder-1.12.2-1.4.jar
Quality Tools	Tmtravlr	QualityTools-1.0.7_for_1.12.2.jar
Quark	Vazkii	Quark-r1.6-177.jar
Quark Oddities	Vazkii	QuarkOddities-1.12.2.jar
Random Loot Mod	milomaz1	randomloot 1.7.3.jar
Random Things	Lumien231	RandomThings-MC1.12.2-4.2.7.3.jar
RandomPatches	TheRandomLabs	randompatches-1.12.2-1.20.1.0.jar
RandomTweaks	TheRandomLabs	randomtweaks-1.12.2-2.7.1.0.jar
ReAuth	TechnicianLP	reauth-3.6.0.jar
Reborn Core	modmuss50	RebornCore-1.12.2-3.16.4.478-universal.jar
Recurrent Complex	Ivorforce	RecurrentComplex-1.4.8.2.jar
Reliquary v1.3	P3pp3rF1y	Reliquary-1.12.2-1.3.4.796.jar
Resource Loader	Lumien231	ResourceLoader-MC1.12.1-1.5.3.jar
Roguelike Dungeons	greymerktv	RoguelikeDungeons-1.12.2-1.8.0.jar
Rope Bridge	lordcazsius	ropebridge-1.12-2.0.7.jar
Rough Tweaks	Lellson8	roughTweaks0.2.4-1.12.2.jar
Rustic	mangoose3039	rustic-1.1.2.jar
Scaling Health	SilentChaos512	ScalingHealth-1.12.2-1.3.42+147.jar
Shadowfacts' Forgelin	ShadowfactsDev	Forgelin-1.8.4.jar
Signpost	Gollorum	signpost-1.12-1.06.1.jar
Silent Lib	SilentChaos512	SilentLib-1.12.2-3.0.14+168.jar
Simple Storage Network	Lothrazar	SimpleStorageNetwork-1.12.2-1.7.10.jar
Skewers	Casadis	Skewers-1.1.jar
Sound Filters	Tmtravlr	SoundFilters-0.11_for_1.12.jar
Spartan Shields	ObliviousSpartan	SpartanShields-1.12.2-1.5.4.jar
Spawn Temple	Iastre	SpawnTemple-v.2.1-mc1.12.jar
Spice of Life: Carrot Edition	lordcazsius	solcarrot-1.12.2-1.8.3.jar
Stackie	Lunatrius	Stackie-1.12.2-1.6.0.48-universal.jar
stimmedcow : NoMoreRecipeConflict	GotoLink	NoMoreRecipeConflict-0.13(1.12.2).jar
Storage Drawers	Texelsaur	StorageDrawers-1.12.2-5.4.0.jar
Straw Golem	fradige95	strawgolem-1.4.1.jar
Stuff A Sock In It	DarkhaxDev	StuffASockInIt-1.12.2-1.1.30.jar
Subterranean Switcheroo	Lordepos	SubSwitch1.1.0.jar
SwingThroughGrass	exidex	stg-1.12.2-1.2.3.jar
Terracart Reloaded	Kreezxil	terracartreloaded-1.12.2-1.2.3.jar
The Aether	GildedGames	aether_legacy-1.12.2-v1.4.4.jar
The Beneath	Shinoow	The Beneath-1.12.2-1.7.0.jar
The Disenchanter Mod	impelon	disenchanter-[1.12]1.6.jar
The Eight Fabled Blades	ShelterRin	TheEightFabledBlades V2.0.01.jar
The Twilight Forest	Benimatic	twilightforest-1.12.2-3.10.1013-universal.jar
Tinkers Construct	mDiyo	TConstruct-1.12.2-2.9.0.55.jar
Totemic	ljfa2	Totemic-1.12.2-0.11.6.jar
Tropicraft	Cojomax99	tropicraft-MC1.12.2-7.1.9.115.jar
Unique Crops	BlueNeenja	uniquecrops-1.12.2-0.1.98.jar
V-Tweaks	oitsjustjose	VTweaks-1.12.2-2.0.5.jar
VanillaFix	Runemoro	VanillaFix-1.0.10-99.jar
VanillaTweaks	StrikerRocker	VanillaTweaks-1.12.2-1.5.6.jar
ViesCraft - Airships!	Vies	ViesCraft-1.12.2-5.9.13.jar
Waystones	BlayTheNinth	Waystones_1.12.2-4.0.72.jar
What's That Slot?	gegy1000	WTS-1.1.0.jar

**Comment by KnightMiner** [comment]
You have too many mods installed, you ran out of block IDs. This only appeared to be caused by Tinkers or Betweenlands as both add a lot of blocks. Either trim down your mod list, or there are some "use at your own risk" mods that extend the ID limit.
