### ISSUE TITLE
Question(s) about configuration for the smeltery

### ISSUE THREAD

**Issue by luxidoptera** [SlimeKnights/TinkersConstruct#4041]
Sorry if this isn't really the right place for this, but I find myself curious. Is it possible to configure the speed at which materials melt in the smeltery, and/or what things you can melt? I checked the config folders and in the .jar itself and didn't see anything.

I'm using TConstruct with Extreme Reactors and I can't melt Yellorite Ore, which I would love to be able to do. And as for the former question I mostly just want to make Redstone melt faster lol

**Comment by KnightMiner** [comment]
Use CraftTweaker and ModTweaker if you want to configure recipes, there are way too many for us to make them all config based in 1.12.
