### ISSUE TITLE
3D tool models

### ISSUE THREAD

**Issue by VMan-2002** [SlimeKnights/TinkersConstruct#4042]
**Issue description:**
3D item models for tools and toolparts render as a generated item, ignoring the "elements" table

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.179

![I wanted a pickaxe, not a domino!](https://cdn.discordapp.com/attachments/395801350731989003/677436328887189504/unknown.png)

**Comment by bonii-xx** [comment]
Because they are generated items. I'm not sure if the current model system is capable of supporting 3d models. Do you happen to have an example model you're using?

**Comment by VMan-2002** [comment]
[Test3d.zip](https://github.com/SlimeKnights/TinkersConstruct/files/4207840/Test3d.zip)

Here is the model

**Comment by bonii-xx** [comment]
Thanks, I'll take a look when revisiting the models for 1.14/1.15. Will take a while. I don't have time to look into 1.12.

**Comment by PrincessOfEvil** [comment]
1.12 doesn't support 3d models for anything using the material recoloring system. They're all hardcoded as flat models. They just completely ignore the model.

Source: spent quite a bit of time trying to make 3d tools.

**Comment by KnightMiner** [comment]
1.16 should support 3D models if everything goes as planned. In 1.12 its not worth the effort
