### ISSUE TITLE
When will it be updated to 1.14

### ISSUE THREAD

**Issue by hec9527** [SlimeKnights/TinkersConstruct#4044]
**Issue description:** 

this issue content on things but ask the next version.

How long do we have to wait to play TinkersConstruct with Minecraft version 1.14
this preview edition is 1.16  now,  but this mod still suport 1.12.2 , Stable

If you have plans to update to 1.14 recently, please let me know.

Thanks to all the contributors

**Versions:** 1.12.2
* Minecraft:  1.14
* Forge: 28.2
* Tinkers Construct: without

**Comment by bonii-xx** [comment]
We'll probably skip 1.14 due to time constraints and missing model support.
