### ISSUE TITLE
multiple/duplicated smeltery recipes in JEI with enderio tic

### ISSUE THREAD

**Issue by Elay2306** [SlimeKnights/TinkersConstruct#4045]
**Issue description:**

when i look for example on the signalum ingot/alloy from thermal foundation, and i use the EnderIO Tic addon then i get 3 times the recipe, so i dont get 1 recipe, i get 3 recipes of the same recipe

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.6.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.179

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

i use Tconstruct, EnderIO Tic addon, thermal foundation and JEI
like i said in the issue description, if i search for an thermal foundation alloy/ingot how i can make it into the smeltery i got 3 recipes of the same recipe instead of 1 recipe, but thats only with the EnderIO Tic addon, i made a thread about that on EnderIO and they said its the Tconstruct's that make the problem, so they cannot do anything

**Comment by bonii-xx** [comment]
TiC does not add any recipes for those. Probably the addon adding them, while the mods themselves also add them. None of these recipes is from TiC itself.
