### ISSUE TITLE
Infinity Arrow/Bolt Bug

### ISSUE THREAD

**Issue by Dysnomia701** [SlimeKnights/TinkersConstruct#4046]
**Issue description:**
1) make arrow/bolt ammo 0
2) increased durability(ex: Diamond,Emerald) modifier add
3) infinity arrow/bolt complete

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.179

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Tinkers Construct Only

**Comment by bonii-xx** [comment]
Well that's a funny bug. I don't have a dev setup for this right now, but I can confirm the bug.
