### ISSUE TITLE
TConstruct village structure generation missing in 2.13.0.179

### ISSUE THREAD

**Issue by darth-crunchus** [SlimeKnights/TinkersConstruct#4047]
**Issue description:**
Tinkers' Construct Tool Workshops do not spawn in villages.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2768
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.179

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes, it can be reproduced with nothing but Mantle and Tinkers' Construct enabled.

**Comment by bonii-xx** [comment]
Yes, village integration for TiC2 hasn't been finished. It's missing from MC 1.8 onwards. It might come back eventually, but there has been no time so far.

**Comment by darth-crunchus** [comment]
Ohhhhhhhh, okay, I'm sorry, I didn't realize.  It's been a while since I messed with Tinker's.  I do apologize.

**Comment by bonii-xx** [comment]
No problem, you're welcome.
