### ISSUE TITLE
Arrows fired by longbow glitch

### ISSUE THREAD

**Issue by QazCetelic** [SlimeKnights/TinkersConstruct#4048]
**Issue description:**
The arrows visually go way of target but they still do image where they should have hit.

* Minecraft: 
1.12.2

* Forge: 
Latest for 1.12.2

* Mantle: 
1.3.3.55

* Tinkers Construct: 
2.13.0.179

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes

**Comment by bonii-xx** [comment]
Can you explain in more detail what you mean? Do you have screenshots or a video?

**Comment by QazCetelic** [comment]
I'm unable to reproduce the bug
