### ISSUE TITLE
Pam's Harvestcraft intergration

### ISSUE THREAD

**Issue by chyper111** [SlimeKnights/TinkersConstruct#4049]
**Issue description:** please make pam's tofu meats work to make moms spaghetti. I'm a vegan in real life and Minecraft and it would be awsome cuz that's how I like spaghetti. 

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by bonii-xx** [comment]
Spaghetti is hardcoded to vanilla meats, and does not support any modded meats/meat supplements. TiC does not support any specific mods.

**Comment by chyper111** [comment]
welp, then I guess no mom's spaghetti for me cuz me no kill animals.

**Comment by KnightMiner** [comment]
Support should already exist automatically, we use `listAllmeatcooked` for the list of meats that can be used to add meat to mom's spaghetti, which last I checked Pam's also used. However, the challenge is specifically you must have at least 3 different meats from that group, and I think tofu only counts towards one.

So basically, we support Pam's, but do not support tofu specifically.

**Comment by chyper111** [comment]
how do i change it or do that cuz it would be awesome.

**Comment by KnightMiner** [comment]
Add more meat alternatives to `listAllmeatcooked`. You can use a mod such as CraftTweaker to do this. Need at least 3 different meats to make the recipe.

**Comment by bonii-xx** [comment]
Whelp, you're right @KnightMiner, looked at the wrong line in the code. I was wondering if I misremembered that we use oredict...

**Comment by chyper111** [comment]
um what config is it in? i cant find that line anywhere?

**Comment by chyper111** [comment]
oh, nevermind I didn't see the craft tweaker thanks for the help.
