### ISSUE TITLE
Alenchok

### ISSUE THREAD

**Issue by chokyewfatt** [SlimeKnights/TinkersConstruct#4050]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by alexbegt** [comment]
This is an invalid issue report, please resubmit with information filled in so we know what your issue is.
