### ISSUE TITLE
Clear Glass not covering Carpenter's Block

### ISSUE THREAD

**Issue by Speed-Racer18** [SlimeKnights/TinkersConstruct#4054]
**Issue description:**
The clear glass blocks aren't covering the Carpenter Block from Carpenter's Block. Other blocks in TCon do.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2846
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.179

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Carpenter's Block 1.12.2
https://www.carpentersblocks.com/downloads.html

**Comment by bonii-xx** [comment]
What do you mean by covering the block? Also it's probably better to ask the carpenter block devs about this, since we have no idea what they do/rely on.

**Comment by KnightMiner** [comment]
Closing for lack of response
