### ISSUE TITLE
Smeletry not accepting blazing pyrotheum

### ISSUE THREAD

**Issue by MasterMarkoJ** [SlimeKnights/TinkersConstruct#4057]
Smeletry not accepting blazing pyrotheum

Versions: 1.12.2
Minecraft: 1.12.2
Forge: 14.23.5.2847
Mantle: 1.3.3.55
Tinkers Construct: 2.13.0.179

![2020-03-10_22 05 58](https://user-images.githubusercontent.com/59839585/76359615-dc544b00-631b-11ea-939a-082415dd3848.png)

**Comment by KnightMiner** [comment]
Yes, because we do not add it as a fuel. Ask the author of the mod that adds pyrotheum to make it a fuel, this is always an addon or a modpack that makes it work,

**Comment by MasterMarkoJ** [comment]
Well, I'm trying to make a modpack

uto, 10. ožu 2020. 22:17 KnightMiner <notifications@github.com> je napisao:

**Comment by KnightMiner** [comment]
I suggest you look into CraftTweaker and ModTweaker then. You can write a script which adds it as a fuel.

**Comment by MasterMarkoJ** [comment]
I will try, tnx for the support and have a nice day :)

uto, 10. ožu 2020. 22:20 KnightMiner <notifications@github.com> je napisao:
