### ISSUE TITLE
Slime Sling can only be made in one color regardless of which slime is used.

### ISSUE THREAD

**Issue by Taquios** [SlimeKnights/TinkersConstruct#4058]
I'm currently on FTB revelations 3.2.1 and when making the slime sling regardless of what color is used it defaults to the green color. Not sure if it's a bug or just something that's built into the code.

**Comment by KnightMiner** [comment]
FTB Revelations is using a super old build of Tinkers Construct. It was before the fix was added that prevents any recipe conflicts.
