### ISSUE TITLE
game crashes when effects are present

### ISSUE THREAD

**Issue by lennuh1** [SlimeKnights/TinkersConstruct#4059]
**Issue description:**
game crashes when im effected, for example when i drink potions. And says ¨error rendering an entity in the world¨
https://pastebin.com/YXgrHE8b
**Versions:**1.12.2-forge1.12.2-14.23.5.2847
* Minecraft: 1.12.2-forge1.12.2-14.23.5.2847
* Forge: 1.12.2-forge1.12.2-14.23.5.2847
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

[crash-2020-03-13_14.13.58-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/4329490/crash-2020-03-13_14.13.58-client.txt)

what else am i supposed to say?

**Comment by KnightMiner** [comment]
Crash report says this is from Damage Indicator Mod, what made you report it here? This is the reason in the issue template you deleted it asks you to test with just Tinkers Construct and see if it still happens.

**Comment by lennuh1** [comment]
sorry not good at looking for faults
