### ISSUE TITLE
Can't use bows in survival mode

### ISSUE THREAD

**Issue by EnvyingGolem47** [SlimeKnights/TinkersConstruct#4061]
**Issue description:**

Can't use long, short, or crossbows in survival mode. 
I could just be an idiot and not realizing how to use the bows. But whenever I use the bows
in creative mode, there is no arrow with the animation, it's like I'm shooting nothing...

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.179

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by SweetSugarSugar** [comment]
Please answer the last question.

**Comment by EnvyingGolem47** [comment]
Yeah sorry, I'm closing this as it was a Mod Conflict between Tinkers' Construct and Backpacked by MrCrayfish.
