### ISSUE TITLE
Autosmelt BUG

### ISSUE THREAD

**Issue by Ylarod** [SlimeKnights/TinkersConstruct#4065]
**Issue description:**

When I destroy a raw ore protected by the _Residance_ plugin, I get a smelted ingot, but the raw ore is still there.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Bukkit plugin: Residence 4.8.8.2

**Comment by KnightMiner** [comment]
Most Bukkit protection plugins do some pretty hacky stuff to prevent breaking blocks, so in general we do not support them. We already call the proper game logic which prevents breaking blocks without permission, so if the plugin is not using those hooks there is not much we can do. I suggest you report it to Residence as they will have a better idea about how their plugin works.

**Comment by bonii-xx** [comment]
Yes, autosmelt is connected to forge hooks, which fire **after** the block has been successfully broken. Nothing we can do.
