### ISSUE TITLE
Ghost trashcan in Tool Station GUI

### ISSUE THREAD

**Issue by llloyd4** [SlimeKnights/TinkersConstruct#4068]
**Issue description:**

So.  When I open the tool station I see a ghost image of a trash can in the far right top two inventory slots that is not in any of the other stations, not in the Inventory screen, not in the furnace or any other GUI, just the tool station. 

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:  1.12.2
* Forge: 14.23.5.2847
* Mantle: 1-12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

No idea, TBH. 

![2020-03-31_04 03 45](https://user-images.githubusercontent.com/7238110/78020374-37b79e80-7306-11ea-8f55-e1304bc63e13.png)

**Comment by KnightMiner** [comment]
The point of the last question is you test it with just Tinkers Construct. "No idea" means you did not even try.

In any case, if you did actually test with just Tinkers, you would find the problem went away. If you spent some time debugging, you would probably find the trash can is from Quark, then find your Quark version is outdated as that big was fixed on their side months ago.

**Comment by llloyd4** [comment]
Except my Quark version is 1.6-178, which is the last version of Quark released for 1.12.2, after that it's all 1.4.4 and 1.5.2 versions. But, let's assume your correct, as much as it kills me to uninstall a mod mid play though, I'll backup my world and pray I don't need to use it. Your never ever suppose to remove mods mid play, only between play though.  Now let me see... Clicking though the warning about a tonne of items missing and ... Ok, so even the latest version of Quark has the bug still. I'll give you this one, though now future people can search and find this and know to go bug the Quark team. Thank you.

**Comment by KnightMiner** [comment]
I never said you had to load the same world to test the bug. Create a new world and test it there, the UI hardly needs your specific world.

In any case, I have seen this issue report before, and I know the trash can is not on our side. If its not fixed like I thought, feel free to open an issue with Quark.

**Comment by llloyd4** [comment]
I did as removing Quark fixed it.

https://github.com/Vazkii/Quark/issues/1971

Again, thank you for your time, your info fixed it, and the issue is now out there for people in the future to read and know to go nag at Quark.
