### ISSUE TITLE
Stencil table not actually able to make patterns? (Solved, problem was in smithcore or more paltes)

### ISSUE THREAD

**Issue by liquidScienc3** [SlimeKnights/TinkersConstruct#4069]
HALFWAY THROUGH WRITING THIS I FIGURED OUT WHAT THE PROBLEM IS...
either smithscore or more plates (one of those) was causing this. This is just a bug report now :p 

When i try to use the stencil table to make a new pattern, it just doesn't work, I'm able to click on the part i want to create from the GUI but when i click on the part to craft it, it just goes back into a stencil (I'm not able to hold it or drag it with my mouse, it just disappears after 1s and then my stencils go from 4 back to 5, as it was before). Shift clicking it will place the actual pattern in my inventory (only works if there is just 1 stencil in the table) however after i right click into a chest or anything like that it just turns back into a normal stencil again.

It doesn't cause the game to crash or anything, it just appears that something is meddling with the stencil table.

* Minecraft: 1.12.2 
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

The issue doesn't occur with tinkers only so it's probably a mod meddling with it. The mods im using are as follows: - This is where i found whats causing the issue so I'll stop writing xd -

**Comment by bonii-xx** [comment]
Yup. You're best off reporting it to them, since they have to fix it ;)
