### ISSUE TITLE
[Suggestion] Alphabetized/filterable materials in Materials and You

### ISSUE THREAD

**Issue by SubtleSloth** [SlimeKnights/TinkersConstruct#4071]
**Issue description:**
Hey guys, I’ve been playing Enigmatica 2: Expert with my buddies and I came across something that kind of bothered me. Not saying you guys should or even would want to do this, but I feel like at least alphabetizing the Materials and You book would help anyone that is looking for a specific material instead of having to scroll through all of them to find which one they want. I feel like this would be the easiest solution. 

Another solution could be to add a filter so you can filter the materials by name, or modifier, etc. another idea would be a search bar. 

I think any/all of these idea could greatly help a nub Minecraft player like myself as they are trying to strugglebus their way through modded MC. 

Let me know what you think! Thanks for your time!

**Comment by SweetSugarSugar** [comment]
It might not be possible.  It first lists Tinkers' materials, the it repeats by whatever mod is loaded after it and their integrated materials are then put in the book.

You can use JEI to look at the materials (as tool parts) and then use the book to look at specifics (on the list of materials page).

I think there's a guide out there for materials in that pack as well.

**Comment by SubtleSloth** [comment]
@SweetSugarSugar I get how it works, but a search bar and/or filter wouldn’t be that difficult to implement at that point, neither would alphabetizing them. All the filter is doing is looking for matching strings. Once the program has the compiled list of materials and such, all it has to do is be programmed to alphabetize THAT list, regardless of what is in it, then compile it into the book like it does now. 

I’ve got somewhat of a background in programming, so I am under no impression that it would be easy, but I think it’s a decent, useful idea for the mod.

**Comment by KnightMiner** [comment]
No, @SweetSugarSugar, we dynamically add all materials that are registered, mods do not manually add those too the book. So alphabetizing is definitely doable. Challenge is I am not sure we will do another release for 1.12, but at least sorting should be considered for 1.15

Hard part with alphabetical is low tier materials like wood end up at the end of the list, though I am not sure of a better order to ensure you can still find modded materials.

**Comment by bonii-xx** [comment]
I'm not even convinced we want alphabetical. The order for the "vanilla" tic materials is like that deliberately. The whole simply isn't laid out to be used with tons of materials. We just made sure it's possible.

**Comment by Discomanco** [comment]
Would it be possible for Vanilla TiC to have its own order, and then extra materials ordered alphabetically? So we still have Wood, Stone, Gold, Iron, Obsidian, Cobalt, Ardite, Manyullun, and then whatever stuff other mods add, in order

**Comment by TherminatorX** [comment]
If possible, could have toggleable "default" and "alphabetized" versions, at least in the icon list at the beginning of the book.

**Comment by SweetSugarSugar** [comment]
> No, @SweetSugarSugar, we dynamically add all materials that are registered, mods do not manually add those too the book. So alphabetizing is definitely doable. Challenge is I am not sure we will do another release for 1.12, but at least sorting should be considered for 1.15
> 
> Hard part with alphabetical is low tier materials like wood end up at the end of the list, though I am not sure of a better order to ensure you can still find modded materials.

Sorry I'm a dummy x3

Apologies to whomever I misinformed ❤️

**Comment by bonii-xx** [comment]
> Would it be possible for Vanilla TiC to have its own order, and then extra materials ordered alphabetically? So we still have Wood, Stone, Gold, Iron, Obsidian, Cobalt, Ardite, Manyullun, and then whatever stuff other mods add, in order

Possible? Yes. Worth it? Probably not. There currently is no distinction between base tic materials and other materials, and it should stay that way.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. 1.16 has an addon called Tinkers Planner that nicely implements this feature.
