### ISSUE TITLE
Smeltery creating 2 different alloys

### ISSUE THREAD

**Issue by CoaLMaN122PL** [SlimeKnights/TinkersConstruct#4073]
The smeltery is alloying both **Brass** (copper and zinc) and **Aquarium** (copper, zinc and prismarine) at the same time

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Base Metals: 2.5.0-rc2.332 https://www.curseforge.com/minecraft/mc-mods/base-metals/

**Comment by KnightMiner** [comment]
We don't add an alloy for aquarium, go yell at the mod author who added an alloy with the same materials as a vanilla alloy. I'd assume based on your report it's base metals, they should make aquarium require brass.
