### ISSUE TITLE
Tconstruct vs conarm

### ISSUE THREAD

**Issue by pjindras** [SlimeKnights/TinkersConstruct#4074]
<!--
I have this error in my console
* Construct's Armory: conarm-1.12.2-1.2.5.4
* Tinkers' Construct: TConstruct-1.12.2-2.13.0.183
* Mantle: Mantle-1.12-1.3.3.55
Minecraft: 1.12.2
* Forge: 14.23.5.2852

You can see it here:
https://pastebin.com/gWehxMu0

**Comment by bonii-xx** [comment]
Spoiler: TConstruct wins
