### ISSUE TITLE
StatRegisterEvent can't be cancelled

### ISSUE THREAD

**Issue by RCXcrafter** [SlimeKnights/TinkersConstruct#4075]
I'm making a tweaks mod and I'd like to remove stats for certain toolparts without removing the entire material, but unlike most material events, StatRegisterEvent can't be cancelled. There doesn't seem to be any other way to remove stats.

**Comment by bonii-xx** [comment]
Hm, looks like an oversight yes. Meanwhile you can use the ToolPartCraftingEvent for that purpose. It's kinda bad because it shows the user that it exists.. but at least it also tells them why it doesn't work.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. I'm sure this would be a trivial addition so I added it to the milestone for issues to look into again if anyone picks up 1.12.
