### ISSUE TITLE
TraitRegisterEvent has no info on the stat the trait is being registered to

### ISSUE THREAD

**Issue by RCXcrafter** [SlimeKnights/TinkersConstruct#4076]
I'm making a tweaks mod and I'd like to remove traits for certain stats, but the TraitRegisterEvent does not contain any information on the stat that the trait is being registered to. So currently I can only remove the trait from all stats.

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release making 1.12 end of support. I'm sure this would be a trivial addition so I added it to the milestone for issues to look into again if anyone picks up 1.12.
