### ISSUE TITLE
Proble ma con Tconstruct

### ISSUE THREAD

**Issue by Voligoma** [SlimeKnights/TinkersConstruct#4078]
Issue description:crashea con el problema que dice que los mods que pudieron causar el problema son Mantle y el Tconstruct

If crashed, link to crash report (use a site such as pastebin):https://paste.dimdev.org/rizukisejo.mccrash

**Versions: ?
* Minecraft: 1.12.2
* Forge: Forge 14.23.5.2847
* Mantle: yes
* Tinkers Construct: ?

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.
AgriCraft (by InfinityRaider)
Ruins (Structure Spawning System) (by atomicstrykergrumpy)
Botania (by Vazkii)
AtomicStryker's Battle Towers (by atomicstrykergrumpy)
Moar Tinkers (by AshuraNoYami)
Waystones (by BlayTheNinth)
IvToolkit (by Ivorforce)
Tweakers Construct (by RCXcrafter)
AromaBackup (by Aroma1997)
ShadowMC (by ShadowfactsDev)
InstantUnify (by KidsDontPlay)
DimensionalDoors (by DimensionalDevelopment)
Flux Networks (by sonar_sonic)
MysticalLib (by EpicSquid319)
Ding (by ohaiiChun)
Integrated Tunnels (by kroeser)
PlusTiC (by landmaster_phuong0429)
InfinityLib (by InfinityRaider)
iChunUtil (by ohaiiChun)
Mantle (by mDiyo)
Hats (by ohaiiChun)
Portal Gun (by ohaiiChun)
Wither Skeleton Tweaks (by Shadows_of_Fire)
FTB Quests (by LatvianModder)
Tech Reborn (by modmuss50)
Dungeon Tactics (by PegBeard)
Gendustry (by bdew)
RFTools (by McJty)
Overloaded Armor Bar (by tfarecnim)
BdLib (by bdew)
Loot Games (by Time_Conqueror)
VanillaFix (by Runemoro)
Energy Converters (by xalcon)
Improved Backpacks (by DreenDexTwitch)
AttributeFix (by DarkhaxDev)
Open Modular Turrets (by Keridos)
DiscordCraft (by dierke9)
Common Capabilities (by kroeser)
Lods of Emone (by BordListian)
AutoRegLib (by Vazkii)
CraftTweaker (by Jaredlll08)
BiblioCraft (by Nuchaz)
Davincis Vessels (by darkevilmac)
Immersive Petroleum (by Flaxbeard)
ME Capability Adapter (by rfctksSparkle)
Controlling (by Jaredlll08)
MenuMobs (by Superbas11)
Loot Capacitor Tooltips (by tfarecnim)
Thermal Innovation (by TeamCoFH)
AE2 Wireless Terminal Library (by TheRealp455w0rd)
Corail Tombstone (by Corail_31)
stimmedcow : NoMoreRecipeConflict (by GotoLink)
Storage Drawers Extras (by Texelsaur)
Enchantment Descriptions (by DarkhaxDev)
ForgeEndertech (by EnderLanky)
FTB Money (by LatvianModder)
Advanced Hook Launchers (by EnderLanky)
Thaumcraft (by Azanor13)
Chunk-Pregenerator (by Speiger)
ExtraCells2 (by Destroyer7128)
Instrumental Mobs (by Mrbysco)
Cyclic (by Lothrazar)
Tinker's JEI (by Possible_triangle)
Item Filters (by LatvianModder)
Cooking for Blockheads (by BlayTheNinth)
Biomes O' Plenty (by Forstride)
Immersive Cables (by SanAndreasP)
Just Enough Energistics (JEE) (by TheRealp455w0rd)
Mowzie's Mobs (by bobmowzie)
FTB Utilities (by LatvianModder)
Just Enough Items (JEI) (by mezz)
Career Bees (by RWTema)
Auto Ore Dictionary Converter (by MattDahEpic)
MPUtils (by GenDeathrow)
GunpowderLib (by Jackyy)
Hardcore Darkness (by Lumien231)
Baubles (by Azanor13)
Aroma1997Core (by Aroma1997)
Mystical World (by EpicSquid319)
Gas Conduits (by pupnewfster)
Tinkers Construct (by mDiyo)
FoamFix​ (by asiekierka)
FTB Library (by LatvianModder)
Akashic Tome (by Vazkii)
WrapUp (by TheLMiffy1111)
Buildcraft (by Covert_Jaguar)
Sonar Core (by sonar_sonic)
MovingWorld (by darkevilmac)
MCMultiPart (by amadornes)
Applied Energistics 2 (by AlgorithmX2)
Inventory Pets (by Purplicious_Cow_)
Chameleon (by Texelsaur)
Forge MultiPart CBE (by covers1624)
Thermal Cultivation (by TeamCoFH)
Nature's Compass (by Chaosyr)
Simple Storage Network (by Lothrazar)
Roguelike Dungeons (by greymerktv)
Cyclops Core (by kroeser)
CodeChicken Lib 1.8.+ (by covers1624)
Reskillable (by lanse505)
Roots (by EpicSquid319)
In Control! (by McJty)
Astral Sorcery (by HellFirePvP)
Storage Drawers (by Texelsaur)
Mystical Agradditions (by BlakeBr0)
It's the little things (by Zlepper)
Treasure2! (by gottsch)
Signpost (by Gollorum)
Simply Jetpacks 2 (by Tomson124)
Redstone Flux (by TeamCoFH)
Just Enough Resources (JER) (by way2muchnoise)
Shadowfacts' Forgelin (by ShadowfactsDev)
Mekanism (by bradyaidanc)
Better Builder's Wands (by Portablejim)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Large Ore Deposits (by EnderLanky)
MalisisDoors (by Ordinastie)
Immersive Tech (by FerroO2000)
MalisisCore (by Ordinastie)
Cosmetic Armor Reworked (by LainMI)
HunterIllager (by bagu_chan)
Doomlike Dungeons (by JaredBGreat)
Charm (by svenhjol)
Actually Additions (by Ellpeck)
NotEnoughIDs (by fewizz_)
Farming for Blockheads (by BlayTheNinth)
Forestry (by _ForgeUser7678633)
Ender Storage 1.8.+ (by covers1624)
Biome Staff (by TheRealp455w0rd)
Ender Tweaker (by Shadows_of_Fire)
Practical Logistics 2 (by sonar_sonic)
p455w0rd's Library (by TheRealp455w0rd)
Fish's Undead Rising (by fish0016054)
Wireless Redstone CBE (by covers1624)
Grue (by Shinoow)
Nature's Aura (by Ellpeck)
Thermal Foundation (by TeamCoFH)
Spice of Life: Carrot Edition (by lordcazsius)
WanionLib (by WanionCane)
Bewitchment (by sunconure11)
MattDahEpic Core (MDECore) (by MattDahEpic)
Construct's Armory (by TheIllusiveC4)
Random Things (by Lumien231)
ArchitectureCraft - TridentMC Version (by darkevilmac)
Ice and Fire: Dragons in a whole new light! (by alex1the1666)
NuclearCraft (by tomdodd4598)
Integrated Dynamics (by kroeser)
OreLib (by OreCruncher)
ConnectedTexturesMod (by tterrag1098)
EnderCore (by tterrag1098)
XNet (by McJty)
Bookshelf (by DarkhaxDev)
DiscordIntegration (by TheChikachi)
Industrial Foregoing (by Buuz135)
DarknessLib (by Shinoow)
Culinary Construct (by TheIllusiveC4)
Block Drops (JEI Addon) (by KidsDontPlay)
AE2 Stuff (by bdew)
Mob Grinding Utils (by vadis365)
AI Improvements (by DarkGuardsman)
Ore Excavation (by Funwayguy)
Pam's HarvestCraft (by pamharvestcraft)
Thermal Dynamics (by TeamCoFH)
Vampirism - Become a vampire! (by maxanier)
FastWorkbench (by Shadows_of_Fire)
Chisel (by tterrag1098)
Patchouli (by Vazkii)
Paintings ++ (by AbsolemJackdaw)
Farseek (by delvr)
AmbientSounds 3 (by CreativeMD)
OpenComputers (by Sangar_)
Quark (by Vazkii)
Immersive Engineering (by BluSunrize)
Crafting Tweaks (by BlayTheNinth)
Doggy Talents (by percivalalb)
Totemic (by ljfa2)
SwingThroughGrass (by exidex)
Tinkers' Tool Leveling (by bonusboni)
UniDict (by WanionCane)
MTLib (by Jaredlll08)
McJtyLib (by McJty)
Custom Main Menu (by Lumien231)
OMLib (by Keridos)
RandomPatches (by TheRandomLabs)
Chance Cubes (by Turkey2349)
Rats (by alex1the1666)
Streams (by delvr)
Ghost's Explosives (by ghostgamingpe)
RFTools Dimensions (by McJty)
TAIGA (Tinkers alloying addon) (by zkafaceTV)
Extra Bit Manipulation (by Phylogeny)
Inventory Tweaks (by JimeoWan)
Resource Loader (by Lumien231)
AppleSkin (by squeek502)
Dungeons2 (by gottsch)
Compact Machines (by davenonymous)
OldJavaWarning (by DarkhaxDev)
Multi Mob Library (by Daveyx0)
Numina (by machinemuse)
Modular Powersuits (by machinemuse)
Fast Leaf Decay (by olafskiii)
The Summoner (by Daveyx0)
Minecolonies (by H3lay)
The Twilight Forest (by Benimatic)
Mouse Tweaks (by YaLTeR)
Iron Chests (by ProgWML6)
BetterFps (by Guichaguri)
ReAuth (by TechnicianLP)
Mystical Agriculture (by BlakeBr0)
Cucumber Library (by BlakeBr0)
CreativeCore (by CreativeMD)
ModTweaker (by Jaredlll08)
LittleTiles (by CreativeMD)
LLibrary (by _ForgeUser11902522)
Ender IO (by CrazyPants_MC)
Electroblob's Wizardry (by Electroblob)
Customized Dungeon Loot (by XxRexRaptorxX)
Login Shield (by Glasspelican)
Integration Foregoing (by Jackyy)
LagGoggles (by Terminator_NL)
Clumps (by Jaredlll08)
Level Up! Reloaded (by BeetoGuy)
Primitive Mobs (by Daveyx0)
Scannable (by Sangar_)
Stupid Things (by Furgle)
ICBM - Classic (by DarkGuardsman)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
Armory Expansion (by AshuraNoYami)
Just Enough Calculation (by towdium)
Pam's Cookables - Pam's Harvestcraft Addon (by BloodWorkXGaming)
Time Core (by Time_Conqueror)
Guide-API (by TehNut)
Electroblob's Wizardry: Twilight Forest Spell Pack (by Electroblob)
Dynamic Surroundings (by OreCruncher)
[ANGRY PIXEL] The Betweenlands (by oily_oli)
Just Enough HarvestCraft (JEHC) (by mrAppleXZ)
Morpheus (by Quetzi)
YNot (by asiekierka)
Bad Wither No Cookie - Reloaded (by Kreezxil)
Chisels & Bits (by AlgorithmX2)
JourneyMap (by techbrew)
NetherPortalFix (by BlayTheNinth)
Fairy Lights (by pau101)
Hwyla (by TehNut)
GottschCore (by gottsch)
Steve's Carts Reborn (by modmuss50)
CoFH Core (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Phosphor (Forge) (by jellysquid_)
Placebo (by Shadows_of_Fire)
Tesla Core Lib (by face_of_cat)
Extra Utilities (by RWTema)
LetsEncryptCraft (by CloudyPSP)
Wireless Crafting Terminal (by TheRealp455w0rd)
Armor Toughness Bar (by tfarecnim)
The Midnight (by cipher_zero_x)
ZeroCore (by ZeroNoRyouki)
Building Gadgets (by Direwolf20)
The Beneath (by Shinoow)
CoFH World (by TeamCoFH)
AppleCore (by squeek502)
/dank/null (by TheRealp455w0rd)
LunatriusCore (by Lunatrius)
More Overlays (by FeldiM245)
JAOPCA (by TheLMiffy1111)
Champions (by TheIllusiveC4)
Waila Harvestability (by squeek502)
Reborn Core (by modmuss50)

**Comment by KnightMiner** [comment]
A list of 100 mods should not be needed to cause a crash. In this case, your crash is from running out of RAM. For 318 mods, you need a lot more than 2GB of ram allocated. I suggest either increasing RAM allocation (you can find tutorials online) or removing some mods.

----

Una lista de 100 mods no debería ser necesaria para causar un bloqueo. En este caso, su bloqueo es por quedarse sin RAM. Para 318 mods, necesitas mucho más de 2 GB de RAM asignados. Sugiero aumentar la asignación de RAM (puede encontrar tutoriales en línea) o eliminar algunos mods. (perdón por la traducción incómoda, utilicé el traductor de Google)

**Comment by Voligoma** [comment]
ok no pasa nada con la traduccion pero gracias por responder
