### ISSUE TITLE
Support for Quiver from Thermal innovation 

### ISSUE THREAD

**Issue by ilhamfu** [SlimeKnights/TinkersConstruct#4079]
I know there is arrow in Tconstruct, but for early game, i rather used vanilla arrow with quiver so i can save some inventory space. Can you add support for Quiver from Thermal Innovation?

**Comment by bonii-xx** [comment]
No, we don't do mod-specific support. Furthermore that beats the purpose of having tinkers' arrows. Crafting a TiC arrow out of the same materials required for vanilla arrows is a lot cheaper, btw.
