### ISSUE TITLE
crashes server on load

### ISSUE THREAD

**Issue by lordzxion** [SlimeKnights/TinkersConstruct#4080]
trying to make a server file from a modpack with Tinkers Construct in it. works fine if i remove T-Con but crashes as soon as i try doing with T-Con in the pack.

https://hatebin.com/bmqhogqiih

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.12-1.3.3.55.jar
* Tinkers Construct: 1.12.2-2.13.0.183.jar

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Why do you have the `TinkerDebug` module and `dumpTextureMap` enabled? Those have almost no use outside a development environment. Sure, it should probably be caught by the logic, but there is no reason it should be enabled in a pack used on a server anyways.

**Comment by lordzxion** [comment]
thank you for that. i am kinda in over my head on this modpack stuff. its a steep learning curve.

**Comment by KnightMiner** [comment]
We have the debug module disabled by default, so depending on where you got your config means someone turned it on when they shouldn't. We probably should make the message clearer that you almost never need it
