### ISSUE TITLE
Game crash upon destruction of multiblock structure when GUI is open

### ISSUE THREAD

**Issue by Just-A-Nerd** [SlimeKnights/TinkersConstruct#4081]
**Issue description:**
If the player is in the Smeltery/Tinker Tank/Seared Furnace GUI and the multi-block structure becomes invalidated/destroyed, the game encounters a null pointer exception and crashes.

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/Fiw0GS1z

**Versions:**
* Minecraft: 1.12.2
* Forge: 12.23.5.2847
* Mantle:  1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
With only Tinkers' Contruct and Mantle, the bug is easily reproducible. If some TNT near the smeltery explodes or water flows in while the smeltery while the GUI for the structure is open, the game crashes.

**Comment by KnightMiner** [comment]
Closing as 1.16 received a beta making 1.12 end of support. Probably not a hard fix if anyone picks up 1.12 again, just need to trace back the NPE to find the best spot for a null check. I assume multiple spots will need the check, normally closing the UI would be sufficient as long as everything is safe until it has a chance to close.
