### ISSUE TITLE
Unable to replace tool parts on my tool (says 'ERROR' in Tool Forge/Station when trying to replace a part)

### ISSUE THREAD

**Issue by electrolight7** [SlimeKnights/TinkersConstruct#4082]
**Issue description:**
When trying to replace a tool part on my own pickaxe, the Tool Forge says "ERROR". No explanation as to why I can't replace tool parts. I'm still able to add modifiers and stuff. 

**If crashed, link to crash report (use a site such as pastebin):**
no crashes.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
It can be reproduced with Tinkers' Construct.

Here a screenshot of the Tool Forge interface with my tool and tool part I want to replace:
https://imgur.com/NG525Uj

**Comment by KnightMiner** [comment]
Can you post a copy of your game log? Good chance the error is being logged there. As for the reproduction question, your worded your answer really weirdly. Do you mean you have this same error with no other mods besides Tinkers Construct installed? Your answer just says it happens when the mod is installed.

**Comment by electrolight7** [comment]
Hi
Sorry this is my first time posting an issue on here, so forgive me for my lack of info.

But anyway, I made a backup of my world and tried to load my world with only TiC and Mantle. (It's gonna corrupt the world, I know, but it's just for testing purpose and I have a backup made)

I tried to add the cobalt pickaxe head to my custom stone pickaxe and the same "ERROR" appeared in the Tool Forge with only those 2 mods (and Forge ofcourse). So it looks like the problem is reproducable with only TiC, but the weird thing is that doesn't happen on a fresh new world, with the exact same tool, with the exact same modifiers.

About the error, it's not an error that is caused by the game itself. It is caused by the Tool Forge, because I don't see any error messages in the game log (see link to imgur). There is no explanation on the Tool Forge display as to why there is an error.

ERROR in Tool Forge with only TiC installed:
https://imgur.com/To4dN7B

Here is the game log if you still want to see it:
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/4473640/latest.log)

Debug log perhaps:
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/4473643/debug.log)

**Comment by bonii-xx** [comment]
What do you mean by custom stone pickaxe? It might also be that your tool has some broken data from some other mod.
There is nothing related to this in the logs.

**Comment by electrolight7** [comment]
I meant a stone pickaxe made with TiC where I want to replace the stone pickaxe head with a cobalt one.

But anyway, I'm not sure what else to do other than making a brand new pickaxe and get all the xp and modifers back. What else can I try?

**Comment by KnightMiner** [comment]
Can you get us the NBT from the pickaxe item stack? Mods like CraftTweaker can get this for you using `/ct hand`, or there are a few vanilla solutions to get it. We can then see what in the NBT is broken, and either find a way to make the mod fix it, or at minimum prevent the mod from breaking the NBT like that again.

**Comment by electrolight7** [comment]
I installed CraftTweaker do get the nbt from the pickaxe.
Here is what I got:
https://pastebin.com/VW44TYTu

**Comment by electrolight7** [comment]
I found the problem.
I remember from a week ago that I removed the OreExcavation Integration mod from my modpack. And I also remember that I had an Excavation modifier on my pickaxe. So it might have broken stuff when I removed the OreExcavation Integration mod. So when I added the mod back, I was able to change the tool part again without any error.

So yeah that was my fault. But I don't want the mod in my modpack again so.. and when I removed the mod again the ERROR came back. Maybe the Excavation modifer is still sort of on the pickaxe but just doesn't show on the Tooltip.

NBT thing:
https://pastebin.com/VW44TYTu

**Comment by electrolight7** [comment]
Update: I was able to go and edit the NBT from the pickaxe with the NBTEdit mod and removed the "oreexcavate" tag from the TinkerData-Modifiers list. Now I can replace tool parts like usual now.

You learn something new everyday.

**Comment by bonii-xx** [comment]
Curious. It should probably just ignore the modifier instead of error. One of those situation that happens so rarely that it takes forever to find.

**Comment by electrolight7** [comment]
Well I don't know what else there is to do at this point. It is atleast fixed on my part. :/

**Comment by TherminatorX** [comment]
Thank you for your work troubleshooting this, ElectroLight. Hopefully this will help others in the future.

**Comment by electrolight7** [comment]
Hey no problem ;) Idk if I should close the issue now or..

**Comment by KnightMiner** [comment]
Leave it open, this says there is an issue handling removed modifiers, they should be ignored.

**Comment by electrolight7** [comment]
Alrighty :)

**Comment by TherminatorX** [comment]
Should probably change the tags on this issue if it'll stay open

**Comment by KnightMiner** [comment]
Closing as 1.16 received a beta making 1.12 end of support. ultimately this was a bug where replacing parts fails if a tool has broken modifiers, which 1.16 fixes. 1.12 will need more complex logic to fix, so I added it to the milestone in case anyone picks up 1.12 again.
