### ISSUE TITLE
Swinging wrong Hand on Mattock use

### ISSUE THREAD

**Issue by Girithien** [SlimeKnights/TinkersConstruct#4083]
When using a Mattock in the Off-Hand and holding another TiC Item (even Arrows) in the Main-Hand the other Item will swing when tilling Dirt.
The same can't be recreated while harvesting Crops with an Off-Hand Kama, it's just the Mattock

happens on the newest Version of TiC for 1.12.2

https://gyazo.com/dbc90c31f6231b794247dde0d7c22156

**Comment by KnightMiner** [comment]
Closing as 1.16 received a beta making 1.12 end of support. Likely would not have been hard to fix so adding to the milestone to look into again if anyone ever picks up 1.12 again.
