### ISSUE TITLE
I cant Create or do anything in Tinkers' Construct

### ISSUE THREAD

**Issue by LunaAstraCassiopeia** [SlimeKnights/TinkersConstruct#4084]
I created a Personal Modpack for myself, but I Cant seem to create anything. Stencils: NO
Tools: NO, Modifiers: NO, Embossments: NO.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2 - 2.13.0.183

Im not sure what's causing the issue so I'll just right down all the mods
Mantle
Tinker's Construct
Tinkers' Tool Leveling
Just Enough Items
Tinker's JEI
Constructs' Armory
PlusTiC
Optifine
Xaero's Minimap
Xaero's World Map
Openblocks Elevator
Openblocks
OpenModsLib
Inventory Pets
Inventory Tweaks
Neat
Simple Storage Network
Simple Steel
Hwyla
Wawla - What Are We Looking At
Baubles
Baublelicious
iChunUtil
Hats
Extra Utilities
Advanced Capes
BedSpreads
CraftStudio-1.0.0.93-mc1.12-alpha
Tinkers' Complement
Tinkers' Addons
Yoyos
Armor Stand Configurator
Present Stand
Better Builder's Wand
SecretRoomsMod
Rhodonite - Tools & Armour
Applied Energistics 2
Waystones
Blocklings
Exp Ore
Just Another Rotten Flesh To Leather
Double Slabs
Mr Crayfish's Furniture Mod
Modern Metals
Ore Excavation
SmithsCore
Lag Removal
Future Versions
BiblioCraft
Cyclic

**Comment by bonii-xx** [comment]
Remove half the mods and see if it still happens. Keep going until you find the mod that causes it and remove it. You have some other mod breaking things.
