### ISSUE TITLE
Whats stopping me from just using the default vanilla tools???

### ISSUE THREAD

**Issue by Spaghettigag** [SlimeKnights/TinkersConstruct#4085]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
We do not have any logic preventing use of default vanilla tools, we only add in new tools. There are many different addons you may have installed with disable vanilla tools, Tinkers Hegemony and Tinkers Survival are two off the top of my head.
