### ISSUE TITLE
Depnedencies

### ISSUE THREAD

**Issue by pizzapaul** [SlimeKnights/TinkersConstruct#4086]
**Issue description:**
I keep getting the issue of missing dependencies, "Mantle 1.12.2 or higher "
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by Girithien** [comment]
That means you have to have the Dependency, in this Case "Mantle" I don't see the Issue here, just grab Mantle's most up-to-date Version on Curse

**Comment by bonii-xx** [comment]
Download the mod Mantle and add it to your game. It's required to run TiC.
