### ISSUE TITLE
isValidMaterial checks for head thrice

### ISSUE THREAD

**Issue by RCXcrafter** [SlimeKnights/TinkersConstruct#4090]
I beleive you intended to check for head or handle or extra instead.
https://github.com/SlimeKnights/TinkersConstruct/blob/acfe064af9fd6ac4ef0c590f305d36686fc2bfb5/src/main/java/slimeknights/tconstruct/library/book/sectiontransformer/MaterialSectionTransformer.java#L21

**Comment by KnightMiner** [comment]
We just want to be extra certain the head stats exist :)

**Comment by KnightMiner** [comment]
Closing as 1.16 received a beta making 1.12 end of support. The fix should be pretty clear from the issue description, we probably wanted to make that any of head, handle, or extra instead of just head.
