### ISSUE TITLE
The molten gold hasn't set in my casting table for about an hour.

### ISSUE THREAD

**Issue by urnanagatha** [SlimeKnights/TinkersConstruct#4092]
It's been stuck like this for about an hour and I don't know if I've done something wrong or if it's a glitch. Help would be appreciated x
https://cdn.discordapp.com/attachments/268488417833254912/703708273592893580/image0.jpg for what it looks like if you don't get what I'm on about

**Comment by KnightMiner** [comment]
Means you don't have enough gold in there. Pour more in.

**Comment by KnightMiner** [comment]
Closing for lack of response, likely you do not have enough gold, as it looks low in the screenshot
