### ISSUE TITLE
Suggestion: Store modifiers in Part Chest

### ISSUE THREAD

**Issue by Khris777** [SlimeKnights/TinkersConstruct#4093]
It would be great if modifiers like Mending Moss and Silk Jewels could be stored in Part Chests.

**Comment by bonii-xx** [comment]
I don't see why not, maybe sometime in the future, but not really a priority right now.

**Comment by KnightMiner** [comment]
A modifier chest exists in 1.16, and 1.12 is not getting any more major features (at most a bug fix release), so closing this.
