### ISSUE TITLE
Slimesling & Slimeboots too Overpowered

### ISSUE THREAD

**Issue by PlazmaKG** [SlimeKnights/TinkersConstruct#4095]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

This is more of an issue regarding the slime boots and the slime sling. I want to know if it's actually possible to disable just these 2 items, since I find that they're really overpowered, and break the balance of the game. Thanks in advance! :)

**Comment by Aquerr** [comment]
I would recommend using CraftTweaker to disable recipes for these two.

**Comment by bonii-xx** [comment]
Currently there's no way to disable them. Please use crafttweaker etc.
