### ISSUE TITLE
How to see if Momentum is active?

### ISSUE THREAD

**Issue by Ririshi** [SlimeKnights/TinkersConstruct#4098]
**Issue description:**
I created a hammer with a cobalt head in Direwolf20, which has the Momentum trait. Regardless of any (other) speed increase it has (from stonebound, redstone, momentum), it seems that the mining speed is capped at a fairly low speed. I'm wondering specifically about momentum as it is supposed to add 40% (really significant) speed while mining. The source code says it's a potion, but I cannot see any potion effects while or directly after mining. Is this an issue with the hammer mining speed being capped at a certain speed regardless of the speed shown in the tooltip?

**Versions:** 
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2821
* Mantle: 1.3.3.42
* Tinkers Construct: 2.12.0.115
* Modpack: Direwolf20 1.12, version 2.5.0

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Reproduced in Direwolf 20 in a superflat "redstone ready" world. Tested by mining the sandstone found in the world. Issue appears to be *just* Tinkers Construct, so I suppose no other mods are required to reproduce the issue.

**Comment by bonii-xx** [comment]
There is no visual indicator. It stops shortly after you stop breaking blocks. So, as long as you keep breaking blocks, it will increase mining speed, up to a max, and then reset. Especially with hammers it's usually noticable in the first few blockbreaks.

**Comment by KnightMiner** [comment]
I've heard various "testimonies" from people saying this works to think its working fine, if its not working fine I really don't have time to return to 1.12 to debug it. Call the current behavior the expected behavior and use a different material if its not strong enough I suppose.
