### ISSUE TITLE
Bringing critical hit logic for TiC's arrows in line with vanilla arrows

### ISSUE THREAD

**Issue by Eclairius** [SlimeKnights/TinkersConstruct#4099]
This is an unpleasant mechanic I have run with while working on my modpack, and it's something that also happens when only Tinker Construct is installed. Here is the setup for Tinker alone:
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2847
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.13.0.183

In a nutshell, the current tinker's arrows use the same logic for critical hits as melee weapons; and that cause all sorts of issues.
For vanilla arrows, critical hits works like this: if released at full power, there is 25% chance that the arrow will be critical.
However, tinker's arrows use the following logic: If you are in the air while releasing the arrow, then the arrow will be critical, no matter how far the bow is drawn.
This only happens with tinker's arrows, it doesn't affect vanilla arrows shot with a tinker's bow.

This discrepency is an issue for a lot of reason:
- For the players, it significantly change how to use a bow.
- Tinker's arrows that should be dealing the same damage as vanilla ones actually deal less because they never crit when shooting with the usual style.
- Once learnt, tinker's arrows' mechanic can be abused to easily crit with every shot.
- In situation in which it is impossible to jump (riding a boat, drawing a bow while sneaking) or in which shooting while jumping is too unpractical (riding a horse), tinker's arrows lose a significant amount of damage while vanilla ones doesn't.
- For modpack makers, balancing tinker's arrows with vanilla is nigh impossible because they work with fundamentaly different rules.

I was therefore wondering if it was possible to bring the way critical hit works with tinker's arrows closer to the vanilla arrow's critical hit logic.

**Comment by bonii-xx** [comment]
I think this is simply a bug/leftover from the old code.

**Comment by Pictoract** [comment]
Hi Eclairius , i am French and i had an old Friend on Minecraft who has the same name as you and want to re contact him
If its you, here my discord : Pictoract#4836

**Comment by KnightMiner** [comment]
Closing as 1.16 received a beta making 1.12 end of support. Honestly, the TiC arrows in 1.12 were very different from vanilla. 1.18 is dealing with this by making arrows that more closely resemble vanilla arrows which should deal with it.

Overall on 1.12 I found vanilla arrows gave the highest damage with a good velocity bow, while Tinkers arrows were better for low velocity bows.
