### ISSUE TITLE
Tinkers Construct is preventing my server to start.

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#4102]
**Issue description:**
The server that I'm making for [my modpack](https://www.curseforge.com/minecraft/modpacks/leos-modpack/files) isn't starting up and I found that Tinkers Construct is preventing the server from starting up.
(Version with Tinkers is not up yet)

**If crashed, link to crash report (use a site such as pastebin):**
[Crash Report](https://pastebin.com/hsHRi9CM)

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I have _TinkersComplement-1.12.2-0.4.3_ on too but it doesn't make a difference...

**Things I tried**
Allocating more ram
Running the server without Tinkers Construct (and it started)

**Comment by KnightMiner** [comment]
Crash report says Dynamic Trees ExC is the cause, what made you report this to us? The whole point of the "reproduce with just Tinkers Construct" question is to remove other mods to test it.

**Comment by ghost** [comment]
ok i didn't see that's all...
