### ISSUE TITLE
Can't seem to add a Casting Recipe

### ISSUE THREAD

**Issue by mattieboy079** [SlimeKnights/TinkersConstruct#4103]
**Issue description:**
It could be me, but I can't seem to create a new casting recipe using modtweaker. Removing casting recipes and adding alloy recipes worked fine. Maybe I'm just calling the function wrong, also I didn't really know what to put at the variable for the cast. 
Did I do something wrong? These are the commands I used.

Casting.addTableRecipe(<primal:brass_ingot>, <tconstruct:cast_custom:0>, <liquid:brass>, 144);
Casting.addTableRecipe(<primal:brass_plate>, <tconstruct:cast_custom:3>, <liquid:brass>, 144);

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

The brass ingots are from PrimalCore version 0.6.105

**Comment by bonii-xx** [comment]
We're not involved there, check with modtweaker. I don't know what modtweaker does with this.

**Comment by mattieboy079** [comment]
Ok thanks!
