### ISSUE TITLE
Suggestion: Make the mending moss not permanent

### ISSUE THREAD

**Issue by rtxyd** [SlimeKnights/TinkersConstruct#4106]
If I could just use one powerful weapon with mending moss, then I'd rather not create another weapon again neither the mending moss. So is there possible for making mending moss not permanent?

**Comment by KnightMiner** [comment]
I am not sure what you are asking here, are you wanting to be able to remove mending moss from your tool and put it on another? That goes against our design of modifiers. In any case, we typically do not take suggestions on Github, you are free to discuss ideas on our Discord as long as you have a well thought out idea.

**Comment by rtxyd** [comment]
@KnightMiner That's a misunderstanding. I will try using discord as I have not used it before.
