### ISSUE TITLE
Crash on Load with Smeltery Disabled when FaAR is installed

### ISSUE THREAD

**Issue by Orinai** [SlimeKnights/TinkersConstruct#4107]
There Seems to be some sort of issue causing the game to crash on startup when Fossils is installed alongside TiCon, but the smeltery module is disabled. Have had success loading the game with Fossils when smeltery is enabled, and With Smeltery disabled while Fossils is not. Contacted Fossils team as well, Compat is relatively new on their end, so likely and issue on their part, but posting here as well just in case.

Crash Report: https://www.dropbox.com/s/j2k8al41frf5e3m/crash-2020-05-17_21.44.03-client.txt?dl=0

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

Attempted using a clean instal of just Tinkers and Fossil, Problem persisted.

Fossils and Archeology Revival
* fossilsarcheology-8.0.4

**Comment by bonii-xx** [comment]
Fossils is adding support for the smeltery. However they can't know if the smeltery is disabled. I don't know what they're doing exactly, but I assume they're using an item that doesn't exist when the smeltery is disabled. We're currently not doing any more development for 1.12, so your best bet is to activate the smeltery.

**Comment by KnightMiner** [comment]
No plans to rework how modules work for 1.12 to prevent this. Going to close. Module disabling has been shakey in support at best, you are probably better off using CraftTweaker to remove recipes
