### ISSUE TITLE
Seared Drain breaks furnace

### ISSUE THREAD

**Issue by ShootingStar0312** [SlimeKnights/TinkersConstruct#4120]
So I managed to build the seared furnace, and it's working normally, until I remembered that I need  to also place drains if I wanna use it, but no matter where I place the seared drain in the furnace it stops working and the fire goes out.

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2 -14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Comment by KnightMiner** [comment]
Your issue description explains your problem exactly, it stops working without drains. Why are you placing a drain in the furnace? It does not handle fluids, just items. You are likely confusing it with the smeltery which uses drains.
