### ISSUE TITLE
Some Lines Seems Undone in Language Files

### ISSUE THREAD

**Issue by ETStareak** [SlimeKnights/TinkersConstruct#4121]
**Issue description:**
When I was playing the mod,I found that some text in game were not simple words.Then I checked [en_us.lang](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/resources/assets/tconstruct/lang/en_us.lang) ,and found some strange lines which seemed undone and useless. They are 287,289,561,562,572,573.Comparing with the game,I can make it sure that they are the lacked texts.
287:item.tconstruct.materials.slimecrystal_blue.tooltip=item.tconstruct.materials.slimecrystal_green.tooltip
289:item.tconstruct.materials.slimecrystal_magma.tooltip=item.tconstruct.materials.slimecrystal_green.tooltip
561:material.slimevine_orange.name=material.slimevine_blue.name
562:material.slimevine_purple.name=material.slimevine_blue.name
572:material.slimeleaf_orange.name=material.slimeleaf_blue.name
573:material.slimeleaf_purple.name=material.slimeleaf_blue.name

They do can display properly in English,but when the game is in other languages(such like my mothertouge,Chinese),they won't display properly.I think it will be better if you just use simple way to write these lines.

And also,I think I can help with translation for zh_cn.lang/json.As I know,there are many mistakes in the file now.

Last,how did you made the word 'Ardite' and 'Manyullyn'?By knowing root, prefix and suffix of them,I can translate them better,or at least make Chinese players understand them better.

Thank you for your time.
**Versions:**
* Minecraft: 1.12
* Forge: all
* Mantle: all
* Tinkers Construct: all

**Comment by bonii-xx** [comment]
Hi, thanks for the report. Those entries are entries that reference other entries inside the lang file. Our text rendering takes care of that. We'll have to check if there's a bug separately, but we aren't working on 1.12 anymore.

For the translations, please also check open PRs, often times we have translation PRs open where we have to wait for feedback, not knowing the language itself. But it's probably better to help with the next version when that's ready.

As for ardite and manyullyn.. that can best be answered by @mDiyo

**Comment by ETStareak** [comment]
Yes,another zh_cn.lang can display these sentences properly.I think it is the fault of the file in the jar itself.

As for translation fix,I will explain all the changes by comments in English.You can tell me which change is not good and should be turned back.As the long-term translator of Ice and Fire mod,The Aether series and GalactiCraft4 mod,I think I am a reliable translator,so don't worry about it.

And I will begin this work on July 12th I think.I will redo the zh_cn.lang first,so we can decide what change we should take and what we shouldn't through this PR.As Chinese is really a special language,we have our own way to change the translation of a no-more-developing mod,I just want to help with the mod,and get your approval.After that PR,I will make zh_cn.json for 1.15.

@bonii-xx Sorry for reply so late,I'm really busy these days,and have to suspend most of my translation works for about a month.
