### ISSUE TITLE
Crash when trying to open Gui of ToolStation

### ISSUE THREAD

**Issue by TheMaximilin** [SlimeKnights/TinkersConstruct#4125]
**So, I was upgrading my pickaxe with obsidian for durability - everything fine so far... left pickaxe on a table to grab some lazurite for more "luck" upgrade and when i clicked RMB on table - client crashed with exit code: -1**

crash report: https://pastebin.com/GyJYEQiT

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Mantle: Mantle-1.12-1.3.3.55.jar
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135.jar
* SevTech Ages 3.1.2 hotfix 1
![2020-06-03_05 38 50](https://user-images.githubusercontent.com/66344046/83589617-cf32ab00-a55c-11ea-837e-e2e722657f36.png)

**Comment by bonii-xx** [comment]
Most likely some clientside mod messing with minecraft rendering. Try removing/disabling (clientside) mods or reverting any rendering related config changes you did.

**Comment by TheMaximilin** [comment]
I assume it's 'cause of excavate upgrade for tinkers' tools somehow bugging pickaxe (detailed info on bottom right window of gui shows nothing with this upgrade). Breaking table helps with retrieving tool and reusing table for upgrades. Happens for me 2nd time after tho...broke table again and bug didn't reappear since.

**Comment by KnightMiner** [comment]
We don't add an excavate upgrade, can you check which addon its from?

**Comment by TheMaximilin** [comment]
Should be this one: [https://www.curseforge.com/minecraft/mc-mods/oreexcavation-integration](url)
I have oeintegration-2.3.4.jar version

**Comment by KnightMiner** [comment]
Since it only happens with that addon, report the issue to the addon now. We cannot fix something that is not in our code.
