### ISSUE TITLE
Fall damage still taken after landing

### ISSUE THREAD

**Issue by ecwwithgaming1** [SlimeKnights/TinkersConstruct#4133]
**Issue description:**
when i land with slime boots when i don't bounce (normal landing not sneaking) i take dmg.

**If crashed, link to crash report (use a site such as pastebin):**
didn't crash
**Versions:**
1.12
* Minecraft: 
java
* Forge: 
Twitch
* Mantle: 
IDK
* Tinkers Construct: 
IDk

**Can it be reproduced with *just* Tinkers Construct? Remove any mods besides Mantle and Tinkers Construct to test.**
im not sure i tried to test but i cant ¯\_('¬')_/¯
If other mods are required to reproduce the issue, list them here.

IDK Its my first time on GitHub for this sry for anything i did wrong

**Comment by Tahakk** [comment]
These are not really an answers. You can find forge version in the Twitch app, under the Profile Options. Mantle and TC version can be found Under Installed mods also. At the same time if you play any modpack the behavior can differ since other mods can alter it.

**Comment by Awesomespore** [comment]
Uhh... dude... you don't bounce if you hold shift... I'm assuming you were holding shift when you landed

**Comment by KnightMiner** [comment]
Closing for failure to follow the issue template, and for lack of response to the question about providing versions. You were probably holding shift like one user said
