### ISSUE TITLE
Clear Glass partial Oredictionary listing

### ISSUE THREAD

**Issue by minerguy341** [SlimeKnights/TinkersConstruct#4139]
Clear glass doesnt have the Oredictionary name "blockGlassColorless" in 1.12.2, using version 1.12.2-2.13.0.183

**Comment by KnightMiner** [comment]
There was probably a reason for this, maybe it caused a conflict between the clear stained glass recipes and the normal stained glass ones. In any case, 1.12 is basically EOL, we are focused on later versions, so unlike to change.

You can easily add this oredict name yourself using a mod like CraftTweaker if needed.
