### ISSUE TITLE
I don’t have a problem I just have a question. 

### ISSUE THREAD

**Issue by Squishybear1** [SlimeKnights/TinkersConstruct#4140]
Hello I am Squishy bear, I don't have a problem I just want to know. Are there any mods that can be put together with tinkers construct  to add new allows to tinkers construct?

**Comment by BookSerpent** [comment]
TAIGA is a mod that is supposed to add new alloys to Tinker's Construct. It isn't very good, honestly, but I don't know of any other ones. Sorry.

**Comment by SweetSugarSugar** [comment]
Hi, please report only problems on the issue tracker.  This is to allow the devs to keep track of actual issues reported with the mod.  If you have questions about the mod you can ask on the [Discord](discord.gg/njGrvuh ) or ask in any sort of modded Minecraft forums.
