### ISSUE TITLE
Tinkers Construct causing an excessive amount of lag

### ISSUE THREAD

**Issue by Yobolo** [SlimeKnights/TinkersConstruct#4142]
**Issue description:**
I’ve only very recently began getting into modding and I’ve got a bit of an issue Tinkers Construct causing snow excessive amount of lag. The game runs fine enough with the other mods I have installed but the moment I put Tinkers Construct in with them the framerate drops to the point of being entirely unplayable, I’ve tried all sorts of things from allocating more Ram to the game to downloading mods to boost my framerate but it’s only resulted in minor amounts of success, if anybody knows what might be causing this or how to fix it please let me know!

Minecraft: 1.12.2
Forge: 14.2.5.2854
Mantle: 1.3.3.55
Tinkers Construct: 2.13.0.183

I haven't done tests with just Tinkers Construct exclusively but I've done plenty of tests with and without it and it for sure is the cause of the issue.

**Comment by SweetSugarSugar** [comment]
Please include a list of all the mods you are using.

**Comment by Yobolo** [comment]
> Please include a list of all the mods you are using.

Actually I did some more experimenting and I found out the lag only happens when I use Tinkers Construct with Twilight Forest, both mods run fine on their own and with all my other mods, but when I put them both together it causes the insane lag spikes, I know both mods are made to be compatible with each other so I don't know what could be causing this.

**Comment by Nightcaste** [comment]
> > Please include a list of all the mods you are using.
> 
> Actually I did some more experimenting and I found out the lag only happens when I use Tinkers Construct with Twilight Forest, both mods run fine on their own and with all my other mods, but when I put them both together it causes the insane lag spikes, I know both mods are made to be compatible with each other so I don't know what could be causing this.

_Twilight Forest_ is _known_ to cause a huge performance hit, I'm more inclined to believe that's your problem, because Tinkers' _isn't doing anything_ if you're not interacting with one of the "machines."

**Comment by KnightMiner** [comment]
Closing as a pretty vague issue. If you can give specifics on what is causing lag we can help, but "adding your mod makes the framerate drop" makes little sense as Tinkers almost nothing when you are not using our stuff
