### ISSUE TITLE
Alloys

### ISSUE THREAD

**Issue by Xapientiae** [SlimeKnights/TinkersConstruct#4147]
**Issue description:**
I'd like just to give an idea. I'm playing tinkers construct 2 with metallurgy 4 reforged. This mod adds a lot of new ores and alloys. My materials keep mixing and creating alloys. I calculated it and I need 4 smelteries to protect everything from creating alloys. Maybe would you add a feature (or special skeltery type) which would prevent creating alloys.
**If crashed, link to crash report (use a site such as #pastebin):**

**Versions:**
* Minecraft: any
* Forge: any
* Mantle: any
* Tinkers Construct: any

**Can it be reproduced with *just* Tinkers Construct? Remove any mods besides Mantle and Tinkers Construct to test.**

If other mods are required to reproduce the issue, list them here.

**Comment by hanetzer** [comment]
Make a TinkerTank (its a similar multiblock to the Smeltery) and pipe your fluids into that
for storage. It can contain more fluids, and it does not alloy.

**Comment by Xapientiae** [comment]
Thanks. I didn't know about it.

sob., 11 lip 2020, 14:37 użytkownik hanetzer <notifications@github.com>
napisał:
