### ISSUE TITLE
Congealed slime & slime block issue

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#4151]
Overpowered Jumping due to a vertical speed issue

![Slime-issue](https://user-images.githubusercontent.com/29407027/87378912-43666280-c58f-11ea-9aa4-1a2379e3eb00.gif)

Versions:**
 Minecraft: 1.15.2
Forge: 1.15.2-forge-31.2.27
 Mantle:Mantle-1.15.2-1.5.15
Tinkers Construct:TConstruct-1.15.2-3.0.1.58 and before

You need a line made out of congealed slime , 1 slime block at the end and slime boots ( optional).
![2020-07-14_00 18 57](https://user-images.githubusercontent.com/29407027/87362382-c6c38c00-c56e-11ea-906c-0311e64d9d8b.png)

**Comment by Nightcaste** [comment]
well bye o/

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.78
