### ISSUE TITLE
Leveling Tools

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [SlimeKnights/TinkersConstruct#4159]
I think it would be good if the tools did not lose durability so quickly and if they were improved. Because the shovel with instant mining for example does not pay, since it breaks very fast compared to Vanilla.
Another thing is the way that the tools are recovered with the Patch modification, as they take a long time to recover and the XP collection system seems different from Vanilla and is not very efficient.

**Versions:** 1.12.2
* Minecraft: MultiMC 0.6.11
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Comment by KnightMiner** [comment]
Mending moss is on the list to redesign for 1.15, we have no plans to change it for 1.12 however.

There are a ton of modifiers that give you additional durability, including reinforcements and the diamond. If tools break too fast, maybe you focused too much on speed and not enough on durability. Also consider the tool parts you used. There are bindings that add more durability, and the tool rod has a pretty big impact.
