### ISSUE TITLE
Illuminati white screen bug

### ISSUE THREAD

**Issue by Aarhunt** [SlimeKnights/TinkersConstruct#4169]
**Issue description: Whenever I have my Illuminati pickaxe in my hand, and my friend is in my sight (has the glow effect) my screen turns completely white. To fix it, I have to look away of my friend, wait until my screen isn't white anymore and swap out my pickaxe for something else. Sometimes, it just doesn't fix and I have to restart my game. **

**If crashed, link to crash report (use a site such as pastebin):**

**Versions: **
* Minecraft: 1.12.2
* Forge: 14.23.5.2584
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.
I haven't experienced this problem ever before with Tinkers Construct. I have only encountered it in the ATM3 Remix pack.**

**Comment by ShadowBoxx-LLC** [comment]
There is no "Illuminati" material or "Illuminati pickaxe" in base TiC 2.13.0.183. This sounds like you have an issue with some addon to TiC (if Illuminati is a material) or another mod (if "Illuminati pickaxe" is a non TiC crafted tool).

**Comment by KnightMiner** [comment]
This is exactly why the last question exists. And why *required* is italic, provide no mods that are not required. I am going to close this as we definately do not have anything by that name in the mod, so its very likely an addon causing this bug, I suggest you look in JEI to see which addon adds the material (should be part of the tooltip, or look at the crafting recipe for the mod ID)
