### ISSUE TITLE
Compatibility with Back Tools or Mo'Bends

### ISSUE THREAD

**Issue by slave2midna** [SlimeKnights/TinkersConstruct#4172]
**Issue description:** Seems like Tinkers Tools are not tagged like normal tools and swords in the fact that mods like 'Back Tools' and 'Mo'Bends' don't pick them up like normal weapons. For 'Back Tools' you cannot get the tool to show up on the back. For 'Mo'bends' you do not get the new attack animation that only applies to sword attacks. Both of these don't require any unique setup, as any mod that reads weapons/tools a specific way will work with these two mods. Wondering if this was something that can be tweaked in the json?

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: Latest for 1.12.2
* Mantle: Latest
* Tinkers Construct: Latest 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Mo' Bends (Newest version)
Back Tools

**Comment by KnightMiner** [comment]
Mo Bends is most likely hardcoding their tool checks to be using `instanceof ItemSword` and alike. This is bad and is terriable for mod compat. They should instead be using Forge's tool types, which our tools implement as relevant. If there is something we need to add for compatibility, we are willing to talk to the dev, but we cannot change anything in our tools to make them work with instance checks.

I suggest you talk to the Mo' Bends author and tell him to talk to us if unsure the proper way to add compatibility, it should not need a special case for Tinkers Construct, just switching to the proper Forge methods. In any case, nothing will be changing on the 1.12 side for us, so closing this.

--
For the record, **never** write "latest" as a version, that is useless information. We need a number so we can verify if you are on the latest, as you may be mistaking an older version for the latest.
