### ISSUE TITLE
Question about updates.

### ISSUE THREAD

**Issue by Diskman20** [SlimeKnights/TinkersConstruct#4175]
Is TiC available for 1.15.2? If not, will it be updated? If it is already available for 1.15.2, then where is it as I cannot find it on Curseforge.

**Versions:**
* Minecraft: 1.15.2

**Comment by Lucky7s** [comment]
@Diskman20 

Its currently being worked on, you'll have to wait like the rest of us patient people...

https://github.com/SlimeKnights/TinkersConstruct/projects/1

**Comment by Diskman20** [comment]
Thanks
