### ISSUE TITLE
Endspeed and Hovering together is useless

### ISSUE THREAD

**Issue by embermctillhawk** [SlimeKnights/TinkersConstruct#4179]
**Issue description:**
Using Embossment to give the Hovering trait to a crossbow bolt with Endspeed gives the rather amusing, but almost completely useless, effect of the bolt going screaming up and off and away into space at unbelievable speed.

Is this intentional? I can't seem to find anything on it.

Also, uh, will the bolt ever despawn, or do we have a permanent projectile entity now in the server?

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Comment by KnightMiner** [comment]
Projectiles do despawn eventually. Getting both traits on one bolt was never really intentional, as you have to use embossment to get it. 1.12 is not receiving any more major updates in any case, and this feature was removed for the 1.16 designs, so will close this.
