### ISSUE TITLE
Smeltery Not Working

### ISSUE THREAD

**Issue by 4me2Nogal** [SlimeKnights/TinkersConstruct#4180]
Smeltery Controler is not Working

1.12.2
* Minecraft: 
* Forge: 14.23.5.2854
* Mantle: 
* Tinkers Construct: Yes

Sky Factory 4 
When making the smeltery controller does not light up and thus it does not work, ive been trying for hours and nothing works. I know im making it correct, i looked up several videos of how to do it.

**Comment by KnightMiner** [comment]
You provided no versions other than Forge, and no screenshots. I can guarantee you are not making it right as that version has been released for years and no one else has problems. If you need help figuring out the mistake you are making, feel free to join our [discord](https://discord.gg/njGrvuh) with *screenshots* so we can find the problem. I am betting you used the wrong controller, but general support is better done on the discord.
