### ISSUE TITLE
Suggestion: Change the model art of the "glowing" modifier

### ISSUE THREAD

**Issue by Nightcaste** [SlimeKnights/TinkersConstruct#4182]
Currently, the "glowing" effect on the inventory icon and in-hand model presents itself on the grip/handle.  The same grip/handle that would be covered up by your hand, which would therefore cover up the glow.  Thinking about it as if it were a real thing, by using the tool, you're turning off the thing that you spent a modifier slot on.

**Comment by KnightMiner** [comment]
Glowing does not apply when you use the tool on something, it applies when you are standing near something. It is reasonable to believe that by you holding the glowing handle, you become a conduit for the glow causing it to leak into the world as a new light source.  Plus, if glowing was on the head, it would wear off quicker as you use the tool as the head is the primary point of impact.

Yes, I totally just made that explanation up on the spot. This is a video game. Glowing looks decent on the handle, I think that is more important than a slight bit of realism. If we could actually make glowing tools a dynamic light source you can carry, I may have a different opinion, but for how it behaves I can argue the current location makes sense.
