### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by cactusjack95** [SlimeKnights/TinkersConstruct#4189]
Issue description: my server crashes as soon as I try to start it, but when I remove the T CONSTRUCT the server starts normal

crash report: https://pastebin.pl/view/90c605c4

**Versions:**
* Minecraft: 1.12.2
* Forge: i'm using Magma Dev HEAD-76d7610
* Mantle: Mantle-1.12-1.3.3.55.jar
* Tinkers Construct: TConstruct-1.12.2-2.13.0.183.jar

**Comment by cactusjack95** [comment]
I fixed the problem by changing the server to forge, but anyway the mod is not compatible with craftbukkit, spigot or sponge

**Comment by KnightMiner** [comment]
According to the error, your server software is missing one of the Java libraries we use in the mod. No idea why it would be missing, but start by looking there

We have never done much towards compat with non-Forge servers. They tend to break things that we cannot change, like this issue. In any case, we are basically done with 1.12 support in favor of 1.16

**Comment by Hexeption** [comment]
This was fixed in the latest version of Magma https://github.com/magmafoundation/Magma/commit/ade7751f92ba98bc68b5171cc84672a863c068ec
