### ISSUE TITLE
[1.12.2] Iron items melting into Pigiron

### ISSUE THREAD

**Issue by vizthex123** [SlimeKnights/TinkersConstruct#4190]
**Issue description:** What the title says, regular Iron items are melting into Pigiron and idk why.

**If crashed, link to crash report (use a site such as pastebin):** N/A

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
No clue, it's in my Aurora's Adventurer modpack.

I've got a few scripts that melt chainmail, minecarts, etc. into Iron, but it doesn't modify the regular tools & armour

Here's the script, in case that helps:

[tinkers.zip](https://github.com/SlimeKnights/TinkersConstruct/files/5180921/tinkers.zip)

**Comment by KnightMiner** [comment]
You sure its not alloying after melting? The alloy recipe is iron + seared stone + blood, all things you could likely have in a smeltery.

Check JEI if in doubt and see what recipes are reported

**Comment by vizthex123** [comment]
No, there's no blood or seared stone. I like to keep it empty.

I think it's because I gave the ingot the `ingotIron` OreDict entry, checking now.

Edit: Yeah that's why, I gave it the OreDict entry and that made it conflict. Sorry about this issue report lol.
