### ISSUE TITLE
Alloying with metallurgy 4 (version 1.1)

### ISSUE THREAD

**Issue by dablade11577** [SlimeKnights/TinkersConstruct#4191]
**Issue description:**
cant alloy to make Damascus steel or regular steel using the smeltery after installing and uninstalling Tinkers' Complement v0.4.3, and now i cant seem to find the fix to this issue.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
metallurgy 4 v1.1
Tinkers' Complement v0.4.3

**Comment by Mrthomas20121** [comment]
support is added by Metallurgy 4. post a issue on their issue tracker.

**Comment by dablade11577** [comment]
@Mrthomas20121 the issue happened after a mod i installed changed the recipe alloying with tconstructs smeltery and just want to know if there is somewhere in files where i can see the smelting recipes

**Comment by KnightMiner** [comment]
The recooes exist in code, not in files. Where depends on how Metallurgy is set up. There should be no reason why adding and removing a mod would change that on our side. This support is added by Metallurgy. Maybe they have a config option or something that disables recipes if Tinkers Complement is added, or you did not actually remove the mod. In either case, Tinkers Construct has no control over this issue, report to Metallurgy.

**Comment by dablade11577** [comment]
so found out that older versions could do this and their is a new recipe to get steel and Damascus steel
