### ISSUE TITLE
Vibrant Alloy Scythe Bug

### ISSUE THREAD

**Issue by AcidRaeyn** [SlimeKnights/TinkersConstruct#4192]
**Issue description:** Vibrant Alloy's "direct" modifier dupes seeds when on a scythe. When right clicking a crop with said scythe, it only replants the one you clicked, and puts twice as many seeds in your inventory.  Sometimes it replants none, and gives you 2x+1 seeds as well.

**If crashed, link to crash report (use a site such as pastebin):** N/A

**Versions:**
* Minecraft:  1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Requires Tinkers Construct and EnderIO, but is most effective/relevant with Mystical Agriculture.

**Comment by DabbingEevee** [comment]
this is an ender io issue, not a tinkers one

**Comment by KnightMiner** [comment]
Closing as its an addon material causing this
