### ISSUE TITLE
items non flat 3d models get rendered as blocks despite not having a 3d block model

### ISSUE THREAD

**Issue by nicolascrafter** [SlimeKnights/TinkersConstruct#4196]
**Issue description:**

Placing an item in an item/drying rack which has a non-flat 3d model will be rendered as block, and items with no bock form will be rendered as the pink and black missing model/texture block.
A easy way to see this issue is to place something like a shield in the item/drying rack.
The solution to this is pretty easy, just render items in item/drying racks as items no matter what their 3d model is, this won't affect the current visuals as every block's blockmodel matches it's itemmodel

![A shield in an drying rack](https://user-images.githubusercontent.com/37816644/94600541-650ae800-0268-11eb-8b8b-77c07ea7735c.png)

**Tinker's construct Version:** 2.13.0.183
**Mantle Version:** 1.3.3.55
**Minecraft version:** 1.12.2
**Forge Version:** 14.23.5.2854

**Comment by KnightMiner** [comment]
This affects anything with a TESR model, in other words anything that extends builtin/entity. Known issue, no easy fix with how racks work. Dealt with for 1.16
