### ISSUE TITLE
Can't Harvest Gold Ore to Craft A Sharpening Kit to Mine Gold Ore - Is Set to Diamond Level

### ISSUE THREAD

**Issue by DizzyDJW** [SlimeKnights/TinkersConstruct#4197]
**Issue description:**
A Stone Pickaxe has a mining level of iron and Gold Ore is default mining level of diamond, yet the only sharpening kits available that upgrade to diamond level are metal and would need to be smelted in the smeltery, yet gold is required for a cast. Can Gold Ore be dropped to Iron Level? No configs found that allow changing ores to different mining levels...

**Versions:**
* Minecraft: 1.12.2
* Forge: 12.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Comment by KnightMiner** [comment]
Clay casts exist for this reason. Clay is cheaper than gold and does not require expensive pickaxes
