### ISSUE TITLE
Consider to add a config option to disable weapon damage soft cap

### ISSUE THREAD

**Issue by lllMohandarlll** [SlimeKnights/TinkersConstruct#4199]
I was running a modpack with Scaling Health and various tweaks, with Tinker Construct and various addons in which there was TAIGA too, which was supposed to be for the endgame tools.
Soul Eater trait from Nihilite can theorically boost damage alot, expecially with the help of Fake Players tile entities like Killer Joe, but Mobs there reach easily 20-30k hp so it would be somehow balanced for and endgame trait considering how hard is to get it there in those circumstances.
Fact is that whatever the bonus damage you get, the maximum damage you're allowed to deal seems likely to be nerfed at about 160...
I took a look into TAIGA and (ofc I can be wrong) but seems all fine and fancy over there... so I guess that the damage cap is probably hardcoded on your side.

Not 100% sure but I have the feeling that is related to these lines:
![image](https://user-images.githubusercontent.com/11860704/94996928-ea173980-05a7-11eb-94fd-b7fd3a59e207.png)

If I'm not wrong, could you please consider to add an option in the mod config file to remove any eventual damage cap for TiC?
Or even better, to tweak the formula a bit?
This would really help in particular modpacks balancement...

edit;
(ofc I'm asking for 1.12.2)

**Comment by LinusCDE** [comment]
Seems that this file was removed in a overhaul. Not sure if the older 1.12 is still supported.

History of the file:
https://github.com/SlimeKnights/TinkersConstruct/commits/1.16/src/main/java/slimeknights/tconstruct/library/utils/ToolHelper.java

I forked it and made the changes here: https://git.cosmos-ink.net/linus/tinkersconstruct

Here is the compiled mod. I tested that it boots the server and lets the player join. Please test the damage first before using.

[TConstruct-1.12.2-2.13.0.183.zip](https://github.com/SlimeKnights/TinkersConstruct/files/5649471/TConstruct-1.12.2-2.13.0.183.zip)

**Comment by KnightMiner** [comment]
The logic still exists in 1.16, got moved around a few times. The whole point is so modifiers don't have to check the total damage before applying their boosts. Honestly, no one should add an entity with 20k health, the game is not designed for that. If such a mod pops up again in 1.16, it may be worth looking into again but you are really describing an unsupported use case.

So, long story short, our tools are not supposed to do 100+ damage. If you have tools doing that much damage, you have some serious power creep thats unsupported. Going to close this for now as I have no plans to disable this in 1.12
