### ISSUE TITLE
Tinkers Construct 1.16.3

### ISSUE THREAD

**Issue by Wibias** [SlimeKnights/TinkersConstruct#4203]
Hey!

Me and my mates are really excited for the new TinkersConstruct 1.16.3 Version! Is there like a really early Alpha Version that you can build already out of your current Eclipse project? No need to support it in sense of Issues while using it ofc. Or is it just not working at all yet? Was just Curious!

Regards

Wibias

**Comment by Mrthomas20121** [comment]
1.16.3 is in the work, it's not ready. just wait until it's done like the rest of us.

**Comment by KnightMiner** [comment]
We will not create a guide to build it. If you want to build it, you are on your own both to get it to compile and to get it working. No mod author wants to be asked "can I use your mod on a version with no release", so don't ask that.
