### ISSUE TITLE
TinkerAPIException Crashes Game On Startup

### ISSUE THREAD

**Issue by Speecker** [SlimeKnights/TinkersConstruct#4206]
**Issue description:**
- slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Error occured while processing: 
   tconstruct:items/bolt/shaft_treatedwood
Thats what the CrashLog tells me but i cant figure oout whats the actual problem
- Error occurs when trying to load up a Ressourcepack made out of the source assets of all mods inside my Modpack (about almost 500 Mods) .
- With any other RP or none the Error wont occur
- I dont really know whats the issue and how to solve it. Anybody here who might can help me with this ?

**If crashed, link to crash report (use a site such as pastebin):**

Full Crash-Report:
https://pastebin.com/et1du9FE

**Versions:**
* Minecraft:  1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.12-1.3.3.55
* Tinkers Construct:  1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I dont think so. See Crash-Report for full Mod-List.
Ask Any Questions For More Info When Needed.

**Comment by KnightMiner** [comment]
Sounds like a broken resource pack. What do you mean by "a Ressourcepack made out of the source assets of all mods inside my Modpack (about almost 500 Mods) ."? Did you copy the resources of every mod into a resource pack? Why?

**Comment by Speecker** [comment]
Seems like the mod (or whatever else) is trying to load the texture for anything ending on [...]_treatedwood that is related to TConstruct and Addons/Expansions (Any Mod that makes use of the TiC-API).
But as there seems to be either none or a unloadable resource inside the .jar files of the mod it searches inside the assets of my Ressourcepack for it.
If I just use I.e. the paper textures for the parts as template wich I copy and rename accordingly to [...]_treatedwood it won’t bother anymore cause it seems to be able to load that specific created texture it was missing before. Doing this currently for all the stuff until it won’t crash with that issue anymore. Hope that solves it when I’m done, but tedious 🍡 .
Ehm I took out any assets from /(root)/src/main/resources/assets/... For every mod and collected them together in a single /(myrpname)/assets/ folder and overridden them with my existing one.
This way I can sort out ‘dead textures’ wich are incorrectly named and see the exact namings for any items Ingame so I can replace some textures I want to have a different appearance to even if I can’t find any other RP that did it already.
Also I do not need to always head to the mods git site to review what’s the file name of texture xy.
Instead I have it directly in my RPs directory

Btw: thx for the short reply

**Comment by Speecker** [comment]
Yeeat ! 🥇 
It finally works 👍 
So yep it was just a resourcepack issue, but still a weird one tho.
How would you do it if you would create a resourcepack on your own where you want to effortlessly have the correct namings for certain textures so you avoid "dead" textures wich are unused or have an incorrect naming and to avoid glitches/bugs/missing textures or else issues that resides from it ?
Again thx for the quick response
Greetings

**Comment by KnightMiner** [comment]
You want to effortlessly copy all used resources from a mod? No way to effortlessly do that. You can write a program to do it probably, but without doing so there is no easy way to determine what is actually used and what is not. Note you can extract textures from the JAR files of mods using something like 7-Zip, I would encourage you to extract into a folder besides your resource pack and copy files as needed/only ones you changed, rather than copying all files as that will make the game take a lot longer to load.

Anyways, closing this as it seems your issue is addessed.
