### ISSUE TITLE
Slime-blocks allow endless Jumps - Setting (Feature request)

### ISSUE THREAD

**Issue by Petschko** [SlimeKnights/TinkersConstruct#4213]
**Issue description:**
Congealed Slime Blocks let you jump endlessly. (Can be used to bypass Anti-AFK methods)
While the Slimeblocks are general fun, they can be abused to bypass AFK-Kicks to load a chunk endlessly on Multiplayer-Public-Servers.
I think it would be nice, if there was a setting to turn off this endless behavior (Maybe let jump but just some bounces before just standing on the block then)

**If crashed, link to crash report (use a site such as pastebin):**
N/A

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes this is only possible with TC.

**Comment by KnightMiner** [comment]
Uh, AFK  kicks? From whom? Sounds poorly made if congealed slime breaks it.

I can say Quark handles AFK quite well, by tracking keypresses of the player rather than movement (which works perfectly fine with the slime blocks). Whatever mod you are using to detect AFK should do something like that.

**Comment by Petschko** [comment]
Well I tested now with 3 Mods

**AutoAfkKicker**
You dont get detected as AFK while auto-jump on the Slime-Block, else it works great

**Quark**
Has no AFK kick
Also don't detect you as AFK at all (don't show anything in chat, even when standing, its just for the sleeping skip I guess)

**ForgeEssentials**
You don't get detected as AFK while auto-jump on the Slime-Block. Else it works great

**Comment by KnightMiner** [comment]
I never said Quark had an AFK kick, I said Quark had a properly implemented AFK check. Mods should not be relying on player movement to detect AFK, there are a dozen vanilla cases that will break that, and even more modded cases. Supposing we limit functionality to fix your one case, another Forge mod will come along with a similar bypass to the poorly implemented AFK check.

I suggest you take this issue to the AFK checker mod instead. Adding motion from a block is not so out of the ordinary that it should break their check. Or they could just write their AFK check properly and detect that the player has not pressed any keys like Quark does and we would not be having this discussion.

**Comment by Petschko** [comment]
Key-Detection is impossible without a Client-Side Mod:

https://github.com/ForgeEssentials/ForgeEssentials/issues/2567#issuecomment-739325525

**Comment by KnightMiner** [comment]
If you are using Tinkers Construct, they are already required client side mods. So why not require a client side mod for that?

**Comment by Petschko** [comment]
Well just a client side mod for Anti-AFK? There are none so far beside from that.

I would prefer an option to turn off that behavior but i don't think this is happening, so i completely disable slime-islands and ban the slime block-placement
