### ISSUE TITLE
Cobalt and Ardite ore blocks do not generate

### ISSUE THREAD

**Issue by SpoonInMoon** [SlimeKnights/TinkersConstruct#4214]
Flown in creative through the nether and didnt find a single block, tped to 10000 10000 same result
ore blocks can be placed and broken if given through creative

Minecraft: 1.12.2
Forge: 14.23.5.2854
Mantle: 1.3.3.55
Tinkers Construct: 2.13.0.183

![Base Profile Screenshot 2020 11 01 - 22 39 48 77](https://user-images.githubusercontent.com/73795657/97812613-73975580-1c93-11eb-80de-f8e397796823.png)
![Base Profile Screenshot 2020 11 01 - 22 36 42 70](https://user-images.githubusercontent.com/73795657/97812615-74c88280-1c93-11eb-9582-a22a175f5e38.png)
![Base Profile Screenshot 2020 11 01 - 22 36 46 35](https://user-images.githubusercontent.com/73795657/97812616-75611900-1c93-11eb-9ba4-6073f8901144.png)

**Comment by KnightMiner** [comment]
First I've not heard of this. Many people have been playing 1.12 TiC with generating ores.

First, can you verify you did not disable oregen in the config? Second, verify you did not disable the world module. Third, test without Optifine, despite being a graphics mods I've heard reports of it messing with worldgen

**Comment by SpoonInMoon** [comment]
Oh, somewhy oregen was disabled for both (not by me, i dont change config files)

Thank you for your help

Edit: After enabling oregen everything works smoothly
![image](https://user-images.githubusercontent.com/73795657/97813371-c6bfd700-1c98-11eb-8378-1688162b1751.png)
![image](https://user-images.githubusercontent.com/73795657/97813400-01c20a80-1c99-11eb-9491-202eecedc98c.png)
