### ISSUE TITLE
Tinker Tank question/suggestion

### ISSUE THREAD

**Issue by natjam2000** [SlimeKnights/TinkersConstruct#4215]
I have a Tinker Tank set up in a Tekxit world and I want to use it to store all my metals. I am trying to set up an Applied Energistics setup to keep ingots in stock and it works except I have to manually change the metal in the tinker tank controller that is to be poured. Is there any way to do this automatically? I tried a redstone signal but that does nothing as far as I can tell. If not, I think that would be a cool thing to add.

MC 1.12.2
Forge: 14.23.5.2847
Tinkers Construct: 1.12.2-2.13.0.183

Other mods involved are AE2 and Ender IO or Thermal Expansion to drain the fluids (although ender io conduits randomly lose connection to the drains when I reload the world but that's a separate issue )

**Comment by KnightMiner** [comment]
It intentionally never had redstone control. The Tinker Tank was designed to be a manual way to store fluids, if you want to automate it, make multiple tinker tanks or make seared tanks is the plan.

That may change in 1.16, the design there is still a little up in the air. But for 1.12. make one tank per fluid if you want AE to treat them differently
