### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.block.BlockTallGrass cannot be cast to ovh.corail.tombstone.block.BlockGrave

### ISSUE THREAD

**Issue by AcruxOk** [SlimeKnights/TinkersConstruct#4216]
Sorry. xD

**Comment by KnightMiner** [comment]
No, this issue cannot be reproduced with just Tinkers, the exception makes it clear its a gravestone crash: `ovh.corail.tombstone.block.BlockGrave`. How did you end up at Tinkers Construct, I see nothing there that would bring you here.

For future reference, don't assume it can be reproduced with only Tinkers, actually try to reproduce it with only Tinkers.

**Comment by AcruxOk** [comment]
Sorry, my bad. XD

I should report the issue to the dev of Tombstone mod-
