### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [SlimeKnights/TinkersConstruct#4218]
**Issue description:**
MC crashes while launching
**If crashed, link to crash report (use a site such as pastebin):**
https://paste.ee/p/PRPHC
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** IDK both of the questions, VanillaFix only lists TiCon but it may be wrong

**Comment by KnightMiner** [comment]
That last question means you test with no other mods. Not you take vanilla Fix's word. Based on what I'm reading, you have a ton of missing resources, including some for Tinkers addons, chance some of those are causing this.

Reproduce with fewer mods (less than 5 ideally) if you want us to be able to help.

**Comment by BeansBeefBroccoli** [comment]
sorry I messed up my modpack its gone now so this doesn't matter
