### ISSUE TITLE
Not Able to Pour Overworld Metals over Arrow Shafts to make Bolt Cores

### ISSUE THREAD

**Issue by MrAlbum321** [SlimeKnights/TinkersConstruct#4219]
**Issue description:**

Not able to pour iron, bronze, copper, gold, etc. onto arrow shafts to construct crossbow bolt cores tipped with those metals. Running dedicated home server. Roguelike Adventures and Dungeons 1.40a, with some mods added/updated; full mod list is below: 

Full modlist for Roguelike Adventures and Dungeons 1.40a, 
plus/updated with: 
Actually Additions-1.12.2-r151-2
bonsaitrees-1.1.4-b170
Ceramics-1.12-1.3.7
CoFHCore-1.12.2-4.6.6.1-universal
CoFHWorld-1.12.2-1.4.0.1-universal
ColossalChests-1.12.2-1.7.3
conarm-1.12.2-1.2.5.9
environmentaltech-1.12.2-2.0.20.1
ImmersiveEngineering-0.12-98
immersivepetroleum-1.12.2-1.1.9
immersivetech-1.12-1.3.10
industrialforegoing-1.12.2-1.12.13-237
IronBackpacks-1.12.2-3.0.8-12
journeymap-1.12.2-5.7.1
Mantle-1.12-1.3.3.55
RedstoneFlux-1.12-2.1.1.1-universal
TConstruct-1.12.2-2.13.0.183
tesla-core-lib-1.12.2-1.0.17
theoneprobe-1.12-1.4.28
ThermalDynamics-1.12.2-2.5.6.1-universal
ThermalExpansion-1.12.2-5.5.7.1-universal
ThermalFoundation-1.12.2-2.6.7.1-universal
TinkersComplement-1.12.2-0.4.3
TinkerToolLeveling-1.12.2-1.1.0
torchmaster_1.12.2-1.8.4.84
Totemic-1.12.2-0.11.6
TreeChopper-1.12.2-1.2.4
valkyrielib-1.12.2-2.0.20.1
Xaeros_Minimap_20.27.2_Forge_1.12

We can make bolt cores by pouring Cobalt/Ardite/Manyullin onto arrow shafts. Could it be an ore dictionary tag problem? Overworld ores somehow not compatible with the bolts? Double-checked recipes and arrow shaft types, same problem. 

Playing on the server through ATLauncher, no more than 5 people online at any time. 

**If crashed, link to crash report (use a site such as pastebin):** No crash occurs. 

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

I honestly don't know. We're butting our heads against this thing and am not finding others with this issue, hence bringing it up here.

**Comment by MrAlbum321** [comment]
Further guesses after messing around a bit: 

Likely a conflict w/ Immersive Engineering/Thermal Foundation; multiple types of the same metal existing in JEI. Crafting ingots into blocks results in Embers Rekindled blocks, but the blocks/ingots poured from the smeltery are Thermal Foundation metals. For pouring the metal, would a mod conflict result in the bolt core recipe not recognizing the metal about to pour, thus refusing to pour? Not sure how likely that is without taking those mods out and giving it a try, and I admit to being busy at the moment. We will likely try it in a few days or so.

**Comment by KnightMiner** [comment]
Closing as 1.16 received a beta making 1.12 end of support. 

Not sure what caused this as it worked for a lot of people. 1.16 recipes are a lot cleaner so this is unlikely to happen if someone else brings back bolts, though TiC natively will just be using arrows this time around.
