### ISSUE TITLE
Old Version

### ISSUE THREAD

**Issue by WildcardV** [SlimeKnights/TinkersConstruct#4221]
**Issue description:**
Whenever i try to run minecraft it will open up and say file tconstruct is for an older version of forge and cannot be loaded idk if i just somehow have an old version of tinkers construct or what 

**Versions:**
* Minecraft: 1.16.4
* Forge: 1.16.4-forge-35.0.18 
* Mantle: Mantle-1.16.4-1.6.43
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I'm pretty sure i may have just messed something up with tinkers construct everything else works fine

**Comment by SweetSugarSugar** [comment]
You can't load 1.12 Tinkers' in 1.16 and there is no public release for 1.16 yet.

**Comment by KnightMiner** [comment]
Yes, I wonder why a version of Tinkers Construct for an older Forge would print a message saying its for an older Forge instead of just magically working for 1.16. When we release a build that works on 1.16, the name will include `1.16`
