### ISSUE TITLE
Question: How many ticks does a Seared Faucet take to pour out a certain amount of liquid?

### ISSUE THREAD

**Issue by jayschuster** [SlimeKnights/TinkersConstruct#4224]
Title
I was just wondering if anybody knew the exact amount (or close) of ticks it takes for the seared faucet to pour say 1000mB of fluid. I'm trying to automate glass, but a simple clock setup that works for ingots does not work for blocks due to the redstone cancelling pour mechanic.
I don't know if this has changed version to version, but here they are anyway:

**Versions**
* Minecraft: 1.12.2
* Forge: 14.23.5.2846
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

**Comment by jayschuster** [comment]
Sorry I'm new here on Github and don't know how to properly label 😅

**Comment by Nightraven17472** [comment]
if you have integrated dynamics you can set a Redstone signal to go off whenever the tank is empty, using a fluid reader and a Redstone writer. I had the same sort of problem. see below:
![int](https://user-images.githubusercontent.com/66979220/100199775-cc37d680-2f51-11eb-8c7b-450fbfc53890.png)
![int2](https://user-images.githubusercontent.com/66979220/100199787-ce9a3080-2f51-11eb-828d-ca23071ad8bb.png)

**Comment by jayschuster** [comment]
> if you have integrated dynamics you can set a Redstone signal to go off whenever the tank is empty, using a fluid reader and a Redstone writer. I had the same sort of problem. see below:
> ![int](https://user-images.githubusercontent.com/66979220/100199775-cc37d680-2f51-11eb-8c7b-450fbfc53890.png)
> ![int2](https://user-images.githubusercontent.com/66979220/100199787-ce9a3080-2f51-11eb-828d-ca23071ad8bb.png)

Unfortunately I don't have integrated dynamics in FTB Revelation, but I bet computercraft could do the same kind of thing. I'll test it out, but the amount of ticks would still be nice if the mod devs or anyone else knows.

**Comment by KnightMiner** [comment]
If I am remembering it right, we transfer 6mb per tick (tick being 1/20 of a second). That means about 120 mb per second. There is an incremental system where we try to extract in 144mb increments (value of an ingot), so chance it may be slightly slower between ingots.
