### ISSUE TITLE
[1.16.x] Missing mods.toml

### ISSUE THREAD

**Issue by EndlessEden** [SlimeKnights/TinkersConstruct#4225]
I know this is entirely too early, but testing necessitates the mods.toml inclusion in the jar.
Example mods.toml (https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/mdk/src/main/resources/META-INF/mods.toml)

**Comment by KnightMiner** [comment]
[We have a mods.toml](https://github.com/SlimeKnights/TinkersConstruct/blob/1.16/src/main/resources/META-INF/mods.toml), and its included in the JAR just fine as shown on ForgeCraft. Wherever you got a build from, its broken.

**Comment by gamax92** [comment]
When running `gradlew build`, no mods.toml ends up in the resulting jar, is there some other way to build this so the mods.toml ends up in the resulting jar?

**Comment by KnightMiner** [comment]
It works perfectly fine when I build, thats where all our test jars come from. Please go on the Tinkers Discord and we can attempt to debug your issue further, enough people are claiming it does not work that I am suspicious about what makes my system and the automated Jenkins server both work fine while yours does not.
