### ISSUE TITLE
Failed during gradlew.bat build 

### ISSUE THREAD

**Issue by CalebThePerson** [SlimeKnights/TinkersConstruct#4226]
**Issue description:**

I went through the eclipse phase and this it the last phase I needed to do but  I keep getting this error and unsure why?

What went wrong: |  
  | Execution failed for task ':compileJava'. |  
  | > Could not resolve all files for configuration ':compileClasspath'. |  
  | > Could not resolve slimeknights.mantle:Mantle:1.15.2-1.5.17_mapped_snapshot_20200530-1.15.1. |  
  | Required by: |  
  | project : |  
  | > Could not resolve slimeknights.mantle:Mantle:1.15.2-1.5.17_mapped_snapshot_20200530-1.15.1. |  
  | > Could not get resource 'https://tehnut.info/maven/slimeknights/mantle/Mantle/1.15.2-1.5.17_mapped_snapshot_20200530-1.15.1/Mantle-1.15.2-1.5.17_mapped_snapshot_20200530-1.15.1.pom'. |  
  | > Could not GET 'https://tehnut.info/maven/slimeknights/mantle/Mantle/1.15.2-1.5.17_mapped_snapshot_20200530-1.15.1/Mantle-1.15.2-1.5.17_mapped_snapshot_20200530-1.15.1.pom'. |  
  | > tehnut.info |  
  | > Could not resolve mcp.mobius.waila:Hwyla:1.10.8-B72_1.15.2_mapped_snapshot_20200530-1.15.1. |  
  | Required by: |  
  | project : |  
  | > Could not resolve mcp.mobius.waila:Hwyla:1.10.8-B72_1.15.2_mapped_snapshot_20200530-1.15.1. |  
  | > Could not get resource 'https://tehnut.info/maven/mcp/mobius/waila/Hwyla/1.10.8-B72_1.15.2_mapped_snapshot_20200530-1.15.1/Hwyla-1.10.8-B72_1.15.2_mapped_snapshot_20200530-1.15.1.pom'. |  
  | > Could not GET 'https://tehnut.info/maven/mcp/mobius/waila/Hwyla/1.10.8-B72_1.15.2_mapped_snapshot_20200530-1.15.1/Hwyla-1.10.8-B72_1.15.2_mapped_snapshot_20200530-1.15.1.pom'. |  
  | > tehnut.info |  
  | > Could not resolve mcjty.theoneprobe:TheOneProbe-1.15:1.15-2.0.2-4_mapped_snapshot_20200530-1.15.1. |  
  | Required by: |  
  | project : |  
  | > Could not resolve mcjty.theoneprobe:TheOneProbe-1.15:1.15-2.0.2-4_mapped_snapshot_20200530-1.15.1. |  
  | > Could not get resource 'https://tehnut.info/maven/mcjty/theoneprobe/TheOneProbe-1.15/1.15-2.0.2-4_mapped_snapshot_20200530-1.15.1/TheOneProbe-1.15-1.15-2.0.2-4_mapped_snapshot_20200530-1.15.1.pom'. |  
  | > Could not GET 'https://tehnut.info/maven/mcjty/theoneprobe/TheOneProbe-1.15/1.15-2.0.2-4_mapped_snapshot_20200530-1.15.1/TheOneProbe-1.15-1.15-2.0.2-4_mapped_snapshot_20200530-1.15.1.pom'. |  
  | > tehnut.info |  
  | > Could not resolve mezz.jei:jei-1.15.2:6.0.0.4_mapped_snapshot_20200530-1.15.1. |  
  | Required by: |  
  | project : |  
  | > Could not resolve mezz.jei:jei-1.15.2:6.0.0.4_mapped_snapshot_20200530-1.15.1. |  
  | > Could not get resource 'https://tehnut.info/maven/mezz/jei/jei-1.15.2/6.0.0.4_mapped_snapshot_20200530-1.15.1/jei-1.15.2-6.0.0.4_mapped_snapshot_20200530-1.15.1.pom'. |  
  | > Could not GET 'https://tehnut.info/maven/mezz/jei/jei-1.15.2/6.0.0.4_mapped_snapshot_20200530-1.15.1/jei-1.15.2-6.0.0.4_mapped_snapshot_20200530-1.15.1.pom'. |  
  | > tehnut.info |  
  | > Could not resolve net.minecraftforge:forge:1.15.2-31.2.8_mapped_snapshot_20200530-1.15.1_at_4b7772b7332d16056721287e2867ee187ef7ecd4. |  
  | Required by: |  
  | project : |  
  | > Could not resolve net.minecraftforge:forge:1.15.2-31.2.8_mapped_snapshot_20200530-1.15.1_at_4b7772b7332d16056721287e2867ee187ef7ecd4. |  
  | > Could not get resource 'https://tehnut.info/maven/net/minecraftforge/forge/1.15.2-31.2.8_mapped_snapshot_20200530-1.15.1_at_4b7772b7332d16056721287e2867ee187ef7ecd4/forge-1.15.2-31.2.8_mapped_snapshot_20200530-1.15.1_at_4b7772b7332d16056721287e2867ee187ef7ecd4.pom'. |  
  | > Could not GET 'https://tehnut.info/maven/net/minecraftforge/forge/1.15.2-31.2.8_mapped_snapshot_20200530-1.15.1_at_4b7772b7332d16056721287e2867ee187ef7ecd4/forge-1.15.2-31.2.8_mapped_snapshot_20200530-1.15.1_at_4b7772b7332d16056721287e2867ee187ef7ecd4.pom'. |  
  | > tehnut.info |  
 

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:  1.15.2
* Forge:  131.2.8
* Mantle:  1.5.17
* Tinkers Construct:  1.15.2 Modifiers

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
If you want to build stuff from Github, our official stance is you are on your own. Specifically, you choose an outdated 1.15 branch that is both alpha (likely to not build right) and still depends on a broken maven which we removed on the latest branch. So, don't build Jars from random repos unless you know what you are doing, and especially don't choose a feature branch with incomplete features.

----

If you want to join our discord (linked on CurseForge), we can walk you through building the 1.16 branch, assuming you want to help contribute to code. However, if you are just trying to play the mod early we really don't want people building for the sake of playing the mod early, as that leads to a bunch of half baked builds floating around.
