### ISSUE TITLE
Mod integration question

### ISSUE THREAD

**Issue by vNemesis** [SlimeKnights/TinkersConstruct#4228]
**Issue description:**

Hi,

Which version of 1.16 will this mod be updated to? I have my own mod that integrates with tinkers so wanted to know which version of Minecraft to to aim for when updating it.

Thanks!

**Comment by KnightMiner** [comment]
We will never target a version other than the latest for a major version without exceptional circumstances. Why would we target 1.16.2 when we can target 1.16.4?

So, latest 1.16.4

**Comment by vNemesis** [comment]
Yeah I was thinking 1.16.4 but I seen talk about 1.16.3 so just wanted to confirm, thanks 👍🏼

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
