### ISSUE TITLE
[1.16.4] Ticking Loop Crash in loading an already exist world

### ISSUE THREAD

**Issue by KhanhPham05** [SlimeKnights/TinkersConstruct#4230]
**Issue description:**
I have a world in 1.15.2 and ported to 1.16.4 to play for a short while now. But after i added tinkers the game crash with ticking loop EVERY TIME i load the world.   

**crash report :**
https://pastebin.com/iq1GESFU

**Versions:**
* Minecraft: 1.16.4
* Forge: 35.1.13
* Mantle: 1.6.43
* Tinkers Construct: 3.0.1.31

**Comment by KnightMiner** [comment]
Where did you get a 1.16.4 Tinkers Construct build? We don't have anything released for a reason, it's not done.

As for your crash, looks like someone changed the data structures used for worldgen to be immutable. Working fine on Forgecraft so I blame one of your other mods

**Comment by KhanhPham05** [comment]
> Where did you get a 1.16.4 Tinkers Construct build? We don't have anything released for a reason, it's not done.
> 
> As for your crash, looks like someone changed the data structures used for worldgen to be immutable. Working fine on Forgecraft so I blame one of your other mods 


From JEI maven link, i found tinkers so i took it

**Comment by KnightMiner** [comment]
Maven is for developers, not players. You are advised not to pull builds from there as they could be in any state of completion. Though, more importantly don't distribute them to other sources.

Anyways, I am going to close this issue. If you are still having issue when we actually release the mod we can look into it, but remember to properly follow the issue template then.
