### ISSUE TITLE
Tinker Tool Enchanting Suggestion

### ISSUE THREAD

**Issue by Fearaniar** [SlimeKnights/TinkersConstruct#4231]
Less of an issue and more of a recommendation:

I've seen plenty of people complaining about the how the modifier system completely overshadows vanilla enchanting; it renders an excellent mechanic practically useless. While there are probably dozens of ways of integrating the two--such as using levels for adding modifiers--I would like to propose a config option: That is, give us the ability to Enable/Disable the modifier system:

With the modifier system disabled, I suggest we keep the native, material attributes, but replace the additional modifiers with the potential for regular enchantments.

Personally, I love making the tinkers tools, but I always feel their aesthetic is marred by all their random colours and protruding bits and bobs; I often avoid certain modifiers just because I don't like the look of them. It would really be neat to have vanilla enchantments on tinkers tools, and I'm sure some system could be set in place. Give us the option in the configs, and I'm sure you'd make A LOT of people happy.

**Comment by KnightMiner** [comment]
Modifers are literally the whole point of tinker tools. If you want enchants, use vanilla tools.
