### ISSUE TITLE
Materials and You 2 Book Side Error Pages

### ISSUE THREAD

**Issue by dragon011** [SlimeKnights/TinkersConstruct#4234]
**No Crash but the Book Materials and You have 2 Book Side Error Pages :**

    *Minecraft Versions:*
     1.12.2

* Forge: *
14.23.5.2854

* Mantle: * 
Mantle-1.12-1.3.3.55

* Tinkers Construct: *
TConstruct-1.12.2-2.13.0.183

Here i post the Screen 2 Side on the Book not Work

1 Scrren
![1](https://user-images.githubusercontent.com/14083451/103142050-eeae4280-46fd-11eb-8dd0-14672fd1c0ad.JPG)

2 screen
![2](https://user-images.githubusercontent.com/14083451/103142058-f5d55080-46fd-11eb-8114-1f51a4ef7231.JPG)

**Comment by KnightMiner** [comment]
Looks like your book is displaying broken content, likely you have an addon trying to add things to the book without adding the actual tools, or a broken resource pack. Neither of the are with our own content, so going to close this
