### ISSUE TITLE
tinker cause crash in mods

### ISSUE THREAD

**Issue by legodragen** [SlimeKnights/TinkersConstruct#4235]
at a tertine point while playing the game crashes and them keeps crashing when ever i try to re-enter the world. i can make new worlds but these as well crash and can't be opened.

https://paste.ubuntu.com/p/V2JSKXDD95/

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-forge-14.23.5.2854
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

this crash appears to take time so doing a check with only this mod or add on will take time.

**Comment by KnightMiner** [comment]
What makes you say Tinkers causes this crash? Nothing in the report says Tinkers code is causing this.

Please reproduce the crash with just Tinkers installed if you say that works and post the crash report with just Tinkers here

**Comment by legodragen** [comment]
ok then so if that's may not be it i will try again as you said.  thanks for being willing to help.

**Comment by KnightMiner** [comment]
Closing as this does not appear to be a TiC issue
