### ISSUE TITLE
Faucet doesn't work

### ISSUE THREAD

**Issue by LeoDLucifers** [SlimeKnights/TinkersConstruct#4236]
Hi! so I just finish my Thaumcraft and blood magic research and starting Tinker construct. I have the smeltery on and everything ready, but for some reason, the faucet doesn't work. I'm playing on the 1.12 version. I did break the furnace to reset my furnace and still doesn't work. I wondering if there any way to fix the issue because tinker is one of my favorites I want to focus on in-game. Thank you.

https://user-images.githubusercontent.com/77022194/103687950-1c498600-4f5f-11eb-95ec-110fc6f70a37.png

**Comment by KnightMiner** [comment]
Corners are not part of the smeltery, never have been. Your side faucets (above the tables on the left) should work fine, but drain in the corner near the basin/right table is not part of the smeltery.

I'll make a note for 1.16 to make drains visually show they are part of the structure, something they have been needing to do for awhile.

**Comment by LeoDLucifers** [comment]
> Corners are not part of the smeltery, never have been. Your side faucets (above the tables on the left) should work fine, but drain in the corner near the basin/right table is not part of the smeltery.
> 
> I'll make a note for 1.16 to make drains visually show they are part of the structure, something they have been needing to do for awhile.

Omg! Thanks you so much.

**Comment by KnightMiner** [comment]
Was that your issue, the corners? If so we can close this issue.
