### ISSUE TITLE
A 1.16 build issue ? 

### ISSUE THREAD

**Issue by dextermovies** [SlimeKnights/TinkersConstruct#4237]
When I go to build the source as per the instructions I get this error. [](https://scans.gradle.com/s/dgerwa5aeqzq6) IT says something about a missing dependency.

This is the error --> https://scans.gradle.com/s/dgerwa5aeqzq6    

**Versions:** 1.16 github code
* Minecraft:  1.16.4
* Forge:  forge:1.16.4-35.0.1_mapped_snapshot_20200916
* Mantle: Unknown
* Tinkers Construct: Unknwn

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** Yes

**Comment by KnightMiner** [comment]
Your issue looks like a common failed to connect to server gradle issue. Our build.gradle works fine when run from our build servers or dev enviroments, so I'm more inclined to blame the build site you are using. In any case, people without experience developing mods to be able to debug gradle issues really should not be building Tinkers from the source anyways. We will release an alpha when its ready.
