### ISSUE TITLE
Glass Panes connect to work tables/pattern chest

### ISSUE THREAD

**Issue by sigmareaver** [SlimeKnights/TinkersConstruct#4238]
**Issue description:**
Glass panes connect to work stations/pattern chest.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Intended behavior should be like vanilla chest, glass panes do not connect to vanilla chests.

**Comment by KnightMiner** [comment]
Closing as 1.16 received a beta making 1.12 end of support. Fix shouldn't be hard if anyone picks up 1.12 at a later date, there is a method to override to prevent connections on tables.
