### ISSUE TITLE
Slime Trees eating chests

### ISSUE THREAD

**Issue by Shadowsoftime99** [SlimeKnights/TinkersConstruct#4239]
**Issue description:**

So I recently added slime trees to my farm, and found that after the first one grew its leaves were where my saplings chest was... and there was no chest any more. I'm fairly sure the chest and its contents just got voided, but it's possible they dropped and I wasn't around to pick them up

**Versions:**
* Minecraft: 1.7.10
* Forge: 7.10.99.99
* Mantle: 0.3.2b
* Tinkers Construct: 1.9.0.0-GTNH.build6 (did the GTNH guys break this?)

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Just TiCo as far as I can tell

**Comment by KnightMiner** [comment]
We are long, long past supporting 1.7.10. Last update was five years ago. No idea who GTNH are or why they are releasing builds of our mod, but we also won't support builds not made by us. Long story short, if you can reproduce this in a modern build (1.12.2) released by us we can take a look, but as it stands your version is unsupported for multiple reasons.
