### ISSUE TITLE
Crumbling trait doesn't do anything on hammers

### ISSUE THREAD

**Issue by nddragoon** [SlimeKnights/TinkersConstruct#4240]
**Issue description:**
I embossed a knightslime hammer head onto my mining hammer thinking it would work like a hammer and excavator in one, kinda like a pickaxe with crumbling works like a pickaxe, shovel, and axe in one, but a hammer with crumbling seems to work the same in every way, i can't even break dirt faster. This is the same with a knightslime head or a knightslime embossment

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct?**
Yes

**Comment by SonicX8000** [comment]
With an all Cobalt Hammer. 4.8 Mining Speed with the traits 'Lightweight' & 'Momentum'. Break Speed on a Dirt Block.

7% > 14% > 22% > 29%...

If embossed with Crumbling...

17% > 35% > 52% > 70%...

-----

With an all Bone Hammer. 2.04 Mining Speed with the traits 'Fractured' & 'Splintering'. Break Speed on a Dirt Block.
6% > 13% > 20% > 26%...

If embossed with Crumbling...
6% > 13% > 20% > 27%...

OR

Bone Hammer Head swapped with a Knightslime Hammer Head, the tool now has 2.18 Mining Speed and now has the 'Crumbling' Trait.
7% > 14% > 21% > 29%...

-----

The boost looks to be more noticeable the higher your Mining Speed is. I used The One Probe mod to show the progress bar for how close you are to breaking a block.

**Comment by KnightMiner** [comment]
based on @Z-Tinic's comment, sounds like its working, but is just not super noticeable. Crumbling is really not designed to boost blocks that are not affected by your tool to as fast as if you used a tool, its just a relative boost to everything with a low mining level. If you want an all in one mining tool, consider the blasting modifier, or upgrading width and height on a mattock.
