### ISSUE TITLE
Server Error on Joining

### ISSUE THREAD

**Issue by mitriic** [SlimeKnights/TinkersConstruct#4242]
**Issue description:**
Whenever I try to connect to any server with Tinkers', I get this error: "Connection Lost Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2121913 is larger then protocol maximum of 2097152."
Playing on the Forgecraft Season 14 modpack, Tinker's is the only additional mod added to the CurseForge pack
I can play singleplayer without any issues, it's only on the server that I am having problems

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.3
* Forge: 34.1.42
* Mantle: 1.6.56
* Tinkers Construct: 3.0.1.1

**Comment by BunCat09** [comment]
There isn't a relase for 1.16.3 yet. Wherever did you find the .jar it is probably fake.

**Comment by KnightMiner** [comment]
There are some people who built our alpha code floating around, so it may or may not be useful. If you post a full crash report/game log I can look into this and see if it's an issue, I can think of a few things that could produce large packets.

**Comment by mitriic** [comment]
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/5797746/latest.log)

> There are some people who built our alpha code floating around, so it may or may not be useful. If you post a full crash report/game log I can look into this and see if it's an issue, I can think of a few things that could produce large packets.

**Comment by KnightMiner** [comment]
Log says nothing useful. Does this issue happen when you load the pack with just Tinkers? Seems I misread your original post to imply you ran with just Tinkers.

**Comment by DeanR97** [comment]
This is an known Vanilla Bug. 
Here is a Mod which fixes the issue: https://www.curseforge.com/minecraft/mc-mods/recipebuffers

**Comment by KnightMiner** [comment]
Going to close this, assuming you are just hitting the issue where you have too many recipes. If you can reproduce this with just TiC we can look into it again.
