### ISSUE TITLE
[1.12.2] Fluid Handler override preventing full integration with Plethora (and maybe other mods)

### ISSUE THREAD

**Issue by kosakriszi** [SlimeKnights/TinkersConstruct#4243]
**Issue description:**
Plethora is a ComputerCraft: Tweaked addon mod that enables users to, among many other things, use any fluid handler capable blocks as peripherals. This is great in theory because it would enable full computer-based automation of the smeltery, something that many people have been trying to do for some time.
Unfortunately, the smeltery drains seem restricted to only be able to insert fluids into the smeltery, not drain them out. This is due to these two overrides found here: https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/library/fluid/FluidHandlerExtractOnlyWrapper.java#L42-L50

I commented these out and compiled the mod. it seems to fix the issue and you can interact with the tank through lua as you would expect. Is there some weird edge case bug that I didn't encounter in my testing that warrants this override? Is it intended to not be able to do this or might it just be an oversight?

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
* CC: Tweaked: 1.12.2-1.89.2
* Plethora: 1.12.2-1.2.3

**Comment by KnightMiner** [comment]
The smeltery is only drain only if you fetch the "internal" capability. Which is the one used for interactions such as right clicking with a bucket. Means you will never take fluid out of a smeltery using a drain. If Plethora uses the sided capability you will have full fluid access.

**Comment by KnightMiner** [comment]
Closing this as it wont be changed in 1.12. This shouldn't happen in 1.16 anyways, if it does those mods are still doing things wrong.
