### ISSUE TITLE
I've tried a few times and I think i've pinned my issue to this mod. My game will run fine for 30ish seconds then have a huge lag spike that freezes the game for about 5 seconds.

### ISSUE THREAD

**Issue by bananaboss123** [SlimeKnights/TinkersConstruct#4245]
I've tried a few times and I think i've pinned my issue to this mod. My game will run fine for 30ish seconds then have a huge lag spike that freezes the game for about 5 seconds.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183
* tinkers leveling: 1.12.2-1.1.0

**Comment by KnightMiner** [comment]
You ignored over half the issue template. Fill that out and we can consider helping you. Telling us "your mod causes lag" does not give us any information to work with.
