### ISSUE TITLE
[1.12.2] Momentum Trait bugs out if your mining speed is fast enough to almost instant-mine blocks while having the Momentum Boost.

### ISSUE THREAD

**Issue by SonicX8000** [SlimeKnights/TinkersConstruct#4250]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 4
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
TConstruct-1.12.2-2.13.0.183
theoneprobe-1.12-1.4.28

-----

GIF of the bug:
https://i.imgur.com/mf1eP5r.mp4

May be related to #3168. I was going to reply on that issue but figure I make a new one.

You may need other mods that can increase your mining speed just enough to instant-mine blocks but it's actually do-able if you somehow got a high enough Haste Potion Effect.

An all Cobalt Hammer has 4.8 Mining Speed but has the traits 'Lightweight' & 'Momentum'. I'm using The One Probe mod to show my break speed progress. It starts at 11% when mining Stone Blocks. With Momentum...

Block 1: 11%,
Block 2: 14%
Block 3+: 16%

Seems like it caps at 3 stacks, it doesn't go above 16% at this point when you start breaking the block. However... If I give myself Haste 27 via commands using '/effect player minecraft:haste 30 26'. This puts my break speed at 75%. With Momentum...

Block 1: 75%
Block 2: 89%
Block 3+: BREAK

Once you get to the third block and onward... this is where the block breaking gets buggy. You will 'break' 9 blocks however 8 blocks surrounding the middle block will reappear but not the middle block as that one is actually broken. You will sorta mine a 1 block tunnel even though the hammer is suppose to mine 9 blocks. If you try to move your view around to instant-mine blocks with the Momentum boost you will create 'ghost' blocks, blocks that are broken on your side but on the server side they are still there.

This doesn't seem to occur on tools that break 1 block at a time, such as a pickaxe.

*EDIT*
This can also happen with the 'Width++' & 'Height++' Modifiers on tools that break 1 block at a time, as those modifiers allow the tool to break up to 4 blocks in a 2x2 range. The block that you have highlighted is broken while the surrounding blocks reappear or will be 'broken' but act as ghost blocks.

**Comment by KnightMiner** [comment]
Sounds like normal block lag, meaning the vanilla bug. You'd likely notice a similar problem with that same speed in vanilla. It tends to affect lower end computers or servers where you have a poor connection. Not anything we can do about this, all we do is change block breaking speed.

Something is definitely wrong with your animations in that gif, I've only seen them freeze like that when you have an excessive level of the haste effect, which is already pretty broken in vanilla for the record.

**Comment by SonicX8000** [comment]
Yea, you can experience ghost blocks with a fast enough break speed with breaking only one block but not as often, at least as far as I've seen. As for the animations... that's indeed a vanilla thing as Haste doesn't normally go that high but I was checking to see if it occurs with just vanilla boosts. The Haste Level in that GIF is at Level 27 which was enough to put my Mining Speed to near instant.

In my modded survival world there's items that can boost your mining speed quite a bit, such as Quality Tools, RPG Inventory's accessories and Aether's Zanite accessories. Mix those with the Momentum Trait which I had on a Hammer at the time and that's when I noticed the blocks being strange when breaking them, if it was more than one block.

**Comment by KnightMiner** [comment]
This should be fixed in the 1.16 versions due to the new multiblock breaking code. I see no easy way to fix it in 1.12 and have no plans to make such a major change, so going to close this.
