### ISSUE TITLE
Tinkers Armory mod causing crash before the game even loads

### ISSUE THREAD

**Issue by ijohn78** [SlimeKnights/TinkersConstruct#4256]
**Issue description:** ive just got back into minecraft again and decided i wanted to play modded games again and seeing as tinkers construct has been my favorite mod since it dropped i figured id try all the different tinkers addons, which brings us to the armory mod. as the game is loaded it just crashes midway through, if someone could help me it would be greatly appreciated. crash is included down below

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/z79ufePF
**Versions:**1.12.2
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.12.2
* Tinkers Construct: 1.12.2

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Tinkers Armory mod is not Tinkers Construct. Report to the author of that addon (Constructs Armory)

**Comment by ijohn78** [comment]
> Tinkers Armory mod is not Tinkers Construct. Report to the author of that addon (Constructs Armory)

thanks!
