### ISSUE TITLE
1.12.2 crash

### ISSUE THREAD

**Issue by SouthWT** [SlimeKnights/TinkersConstruct#4263]
**---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2021-02-23 13:46:46 EET
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Construct (tconstruct)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "ruby": It was already registered by Tinkers' Construct
    at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:986)
    at slimeknights.tconstruct.library.TinkerRegistry.addMaterial(TinkerRegistry.java:131)
    at slimeknights.tconstruct.library.MaterialIntegration.preInit(MaterialIntegration.java:101)
    at slimeknights.tconstruct.TinkerIntegration.preInit(TinkerIntegration.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:90)
    at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_281, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1896061088 bytes (1808 MB) / 2788687872 bytes (2659 MB) up to 7456948224 bytes (7111 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms650m -Xmx8000m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 84 mods loaded, 83 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                    | Version                  | Source                                            | Signature                                |
       |:----- |:--------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft             | 1.12.2                   | minecraft.jar                                     | None                                     |
       | LCH   | mcp                   | 9.42                     | minecraft.jar                                     | None                                     |
       | LCH   | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2854-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                 | 14.23.5.2854             | forge-1.12.2-14.23.5.2854-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | otgcore               | 1.12.2-v9.3              | minecraft.jar                                     | None                                     |
       | LCH   | lesslag               | 1.0                      | minecraft.jar                                     | None                                     |
       | LCH   | foamfixcore           | 7.7.4                    | minecraft.jar                                     | None                                     |
       | LCH   | forgeendertech        | 1.12.2-4.5.5.0           | ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar      | None                                     |
       | LCH   | adlods                | 1.12.2-1.0.8.0           | AdLods-1.12.2-1.0.8.0-build.0504.jar              | None                                     |
       | LCH   | animalium             | 0.3.8                    | Animalium-0.3.8.jar                               | None                                     |
       | LCH   | jei                   | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                         | None                                     |
       | LCH   | appleskin             | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                       | None                                     |
       | LCH   | quark                 | r1.6-179                 | Quark-r1.6-179.jar                                | None                                     |
       | LCH   | autoreglib            | 1.3-32                   | AutoRegLib-1.3-32.jar                             | None                                     |
       | LCH   | betterbuilderswands   | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
       | LCH   | bettercaves           | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                      | None                                     |
       | LCH   | bettermineshafts      | 1.12.2-2.2               | BetterMineshaftsForge-1.12.2-2.2.jar              | None                                     |
       | LCH   | betternether          | 0.1.8.6                  | betternether-0.1.8.6.jar                          | None                                     |
       | LCH   | openterraingenerator  | v9.3                     | OpenTerrainGenerator-1.12.2-v9.3.jar              | None                                     |
       | LCH   | biomebundle           | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                      | None                                     |
       | LCH   | biomesoplenty         | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar     | None                                     |
       | LCH   | bbop                  | 1.0                      | Biome_Bundle_O_Plenty-1.12.2_v1.0.jar             | None                                     |
       | LCH   | bookworm              | 1.12.2-2.5.2.1           | bookworm-1.12.2-2.5.2.1.jar                       | None                                     |
       | LCH   | redstoneflux          | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar           | None                                     |
       | LCH   | cofhcore              | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar             | None                                     |
       | LCH   | boptools              | 0.0.3                    | boptools-1.12-0.0.3.0.jar                         | None                                     |
       | LCH   | ctm                   | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                         | None                                     |
       | LCH   | chisel                | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                      | None                                     |
       | LCH   | chiselsandbits        | 14.33                    | chiselsandbits-14.33.jar                          | None                                     |
       | LCH   | cosmeticarmorreworked | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar              | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | crafttweaker          | 4.1.20                   | CraftTweaker2-1.12-4.1.20.620.jar                 | None                                     |
       | LCH   | ctgui                 | 1.0.0                    | CraftTweaker2-1.12-4.1.20.620.jar                 | None                                     |
       | LCH   | crafttweakerjei       | 2.0.3                    | CraftTweaker2-1.12-4.1.20.620.jar                 | None                                     |
       | LCH   | denseores             | 1.0                      | denseores-1.12.2-1.0.6.jar                        | None                                     |
       | LCH   | dldungeonsjbg         | 1.13.1                   | DoomlikeDungeons-1.13.1-MC1.12.2.jar              | None                                     |
       | LCH   | orelib                | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround             | 3.6.2.1                  | DynamicSurroundings-1.12.2-3.6.2.1.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | effortlessbuilding    | 1.12.2-2.16              | effortlessbuilding-1.12.2-2.16.jar                | None                                     |
       | LCH   | elevatorid            | 1.3.11                   | ElevatorMod-1.12.2-1.3.11.jar                     | None                                     |
       | LCH   | extragems             | 1.2.8                    | ExtraGems-1.12.2-(v.1.2.8).jar                    | None                                     |
       | LCH   | falling_tree          | 2.4.0                    | FallingTree-1.12.2-2.4.0.jar                      | None                                     |
       | LCH   | fastfurnace           | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                      | None                                     |
       | LCH   | fastleafdecay         | v14                      | FastLeafDecay-v14.jar                             | None                                     |
       | LCH   | fastbench             | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                    | None                                     |
       | LCH   | foamfix               | 0.10.11-1.12.2           | foamfix-0.10.11-1.12.2.jar                        | None                                     |
       | LCH   | forgelin              | 1.8.4                    | Forgelin-1.8.4.jar                                | None                                     |
       | LCH   | fpsreducer            | mc1.12.2-1.18            | FpsReducer-mc1.12.2-1.18.jar                      | None                                     |
       | LCH   | ftblib                | 5.4.7.2                  | FTBLib-5.4.7.2.jar                                | None                                     |
       | LCH   | ftbutilities          | 5.4.1.131                | FTBUtilities-5.4.1.131.jar                        | None                                     |
       | LCH   | cfm                   | 6.3.1                    | furniture-6.3.1-1.12.2.jar                        | None                                     |
       | LCH   | futuremc              | 0.2.6                    | future-mc-1.12.2-0.2.6.1.jar                      | None                                     |
       | LCH   | gemsplusplus          | 1.12.2-V7.0.4            | gemsplusplus-1.12.2-7.0.4.jar                     | None                                     |
       | LCH   | inventorypets         | 2.0.12                   | inventorypets-1.12-2.0.12.jar                     | None                                     |
       | LCH   | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | ironbackpacks         | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
       | LCH   | ironchest             | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
       | LCH   | journeymap            | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                       | None                                     |
       | LCH   | jeresources           | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
       | LCH   | lootbags              | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                       | None                                     |
       | LCH   | mantle                | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                          | None                                     |
       | LCH   | mclib                 | 2.2.2                    | mclib-2.2.2-1.12.2.jar                            | None                                     |
       | LCH   | metamorph             | 1.2.6                    | metamorph-1.2.6-1.12.2.jar                        | None                                     |
       | LCH   | minetogether          | 2.4.2                    | MineTogether-1.12.2-2.4.2.jar                     | None                                     |
       | LCH   | minetogetherserver    | 2.4.2                    | MineTogether-1.12.2-2.4.2.jar                     | None                                     |
       | LCH   | mtrm                  | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar        | None                                     |
       | LCH   | mousetweaks           | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
       | LCH   | neat                  | 1.4-17                   | Neat+1.4-17.jar                                   | None                                     |
       | LCH   | harvestcraft          | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar                   | None                                     |
       | LCH   | roguelike             | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
       | LCE   | tconstruct            | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                  | None                                     |
       | LC    | shinygear             | 1.7                      | shinygear-1.7.jar                                 | None                                     |
       | LC    | silentlib             | 3.0.13                   | SilentLib-1.12.2-3.0.14+168.jar                   | None                                     |
       | LC    | silentgear            | 0.6.5                    | SilentGear-1.12.2-0.6.7+76.jar                    | None                                     |
       | LC    | veinminer             | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
       | LC    | silentgems            | 2.8.18                   | SilentsGems-1.12.2-2.8.22+327.jar                 | None                                     |
       | LC    | somanyenchantments    | 0.5.0                    | SoManyEnchantments-0.5.0.jar                      | None                                     |
       | LC    | theoneprobe           | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                       | None                                     |
       | LC    | tinkertoolleveling    | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
       | LC    | vanillafix            | 1.0.10-150               | VanillaFix-1.0.10-150.jar                         | None                                     |
       | LC    | veinminermodsupport   | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
       | LC    | zawa                  | 1.12.2-2.1.1             | zawa-1.12.2-2.1.1.jar                             | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
       | LC    | betteranimalsplus     | 9.0.1                    | betteranimalsplus-1.12.2-9.0.1.jar                | None                                     |
       | LC    | phosphor-lighting     | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar       | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | UD    | mclib_core            | 2.2.2                    | minecraft.jar                                     | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar)
                                        
                                      TransformLoader (denseores-1.12.2-1.0.6.jar)
                                        
                                      LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.11-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      McLib core mod (mclib-2.2.2-1.12.2.jar)
                                        mchorse.mclib.core.McLibCMClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      FutureMC (future-mc-1.12.2-0.2.6.1.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 452.56' Renderer: 'GeForce MX130/PCIe/SSE2'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Suspected Mods: Tinkers' Construct (tconstruct), Mantle (mantle)
  Launched Version: MultiMC5
  LWJGL: 2.9.4
  OpenGL: GeForce MX130/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.56, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
:**

**1.12.2:**
* Minecraft multimc 5: 
* 14.23.5.2854 forge: 
* Mantle 1.3.3.49 (i tried with 1.3.3.55 too): 
* Tinkers Construct 1.12.2-2.12.0 183:

**Comment by StaticPH** [comment]
It looks to me like some mod is doing something incorrectly when attempting to provide tinkers construct integration, and tries to register Ruby as a tool material even if a registration already exists.
As SilentLib and SilentGems haven't finished Pre-Init at the time of the crash, I suspect either extragems or gemsplusplus is the source; BiomesOPlenty could be as well, but that's rather unlikely given how long that would mean such an issue between two common mods had gone unnoticed. Could I get you to try without extragems and gemsplusplus?

**Comment by SouthWT** [comment]
thank you so much it worked

**Comment by KnightMiner** [comment]
In that case, report the issue to those mods, that they are not integrating properly.
