### ISSUE TITLE
is there going to be a fabric or 1.16 port?

### ISSUE THREAD

**Issue by aflacc** [SlimeKnights/TinkersConstruct#4264]
asking for a friend so i can tell him you guys arent

**Comment by ShinyPorygon** [comment]
![image](https://user-images.githubusercontent.com/35193007/108899219-2d6d5580-75e6-11eb-9da9-5f588e9ad9ab.png)

**Comment by KnightMiner** [comment]
Also, this tracker is for bug reports only. When you made this issue you were also linked to our discord, the place for questions

**Comment by aflacc** [comment]
hey guys the friend i was talking about called  you guys some mean names becuae you wouldnt do fabric version isnt that mean of him?

**Comment by aflacc** [comment]
he was rude to you

**Comment by KnightMiner** [comment]
This is not a forum, this is an issue tracker. Also, I don't care what if your friend insulted us, repeating it is nearly as bad as if he said it directly.. And honestly, if you friend is insulting devs of free content for not making him more free content, get a new friend.

**Comment by TJFJefroy** [comment]
So any news on this?

**Comment by KnightMiner** [comment]
Any news on what? There will be no fabric port as stated, and I will not change my mind. The mod has been on 1.16 for almost a year.
