### ISSUE TITLE
[1.12.2] Traits that deals 'Bonus' damage can bypass Squeaky Trait depending on it's order

### ISSUE THREAD

**Issue by SonicX8000** [SlimeKnights/TinkersConstruct#4269]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 3
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
TConstruct-1.12.2-2.13.0.183

-----

Alright, very late with reporting this, but it seems that depending the trait order you can get around a trait's drawback or to get a bigger boost than intended. Let's use the Squeaky Trait as an example which grants Silk Touch but prevents the tool from dealing damage.

I have an All Manyullyn Cleaver. I am going to attack a Iron Golem since it has 100 health. I also have ToroHud installed to show damage pop offs. The Cleaver's trait order is...

Cold-Blooded
Insatiable

In 10 Hits I deal...
27, 19, 19, 19, 20...

-

All Manyullyn Cleaver but with a Sponge Tough Tool Rod for it's 'Handle' slot which gives the Modifier & Durability. The Trait order is now...

Squeaky
Insatiable
Cold-Blooded

In 10 Hits I deal...
9, 0, 1, 1, 1, 2, 2, 2, 3, 3...

Base damage is ignored, but Cold Blood & Insatiable were able to deal damage.

-

Using another All Manyullyn Cleaver but with a Sponge Tough Tool Rod for it's 'Extra' slot which only gives Durability. The Trait order is now...

Cold-Blooded
Insatiable
Squeaky

In 10 hits on a Iron Golem...

0, 0, 0, 0, 0, 0, 0, 0, 0, 0...

Squeaky being below Cold-Blooded & Insatiable traits stops them from doing any damage.

=====

It seems that depending on where Squeaky is at, you can still deal damage. Might also make some traits give a bigger or lesser boost depending on it's order as well.

**Comment by KnightMiner** [comment]
Sideffect of how traits process. Probably an easy fix, so I marked it as easy things to fix if we make another 1.12 build

**Comment by KnightMiner** [comment]
Closing this as 1.16 received a beta and 1.12 is unlikely to get another build. I added it to the milestone to look into if anyone picks up 1.12 again, hard to say whether this is an easy fix or not as I have not touched 1.12 code in awhile.
