### ISSUE TITLE
What versions do I use for what?

### ISSUE THREAD

**Issue by BadgerTheBoss** [SlimeKnights/TinkersConstruct#4271]
What versions do I use for what? Kinda new to all this minecraft mods stuff, just want to know what works where.

**Versions:**
Minecraft: 1.16.4
Forge: 35.1.37
 Mantle: 1.12
 Tinkers Construct: 1.12.2

**Comment by KnightMiner** [comment]
Go to curseforge, the files for the minecraft version you want are labeled. Use the latest for that version and you will have few problems

If there are no builds for a version on curseforge, it means it's unreleased. So be patient
