### ISSUE TITLE
Modifier error

### ISSUE THREAD

**Issue by Override5** [SlimeKnights/TinkersConstruct#4274]
Im making this avaiable on every tinkers construct based mod i have installed in my pack.

there is an issue trying to add more then 9 modifiers to a tool or armor. Attempting to put more modifiers gets This error. Ive tried to look in the configs, but i found nothing. Also, There are still modifier slots avaiable.

Curretly, the tinkers mods installed are

Tinkers Construct 2.13.0.183
Construct's Armory 1.2.5.4
PlusTiC 8.0.0.1
Tinkers Tool Leveling 1.1.0
Tinkers Extras 1.1.0
Tinker I/O rw2.8.2
Tinkers Complement 0.4.3
![image](https://user-images.githubusercontent.com/69968054/111250918-53749b80-8662-11eb-9e8d-fe0f3c42c4be.png)

**Comment by KnightMiner** [comment]
Prove you have modifier slots remaining. Show the tool before you tried to add the modifier

What modifier are you trying to add? That is a really narrow screenshot. Have you tried adding a different modifier?

**Comment by Override5** [comment]
Ill get on the server and attach a screenshot next. Im using a Shurakin as the tool, but im also using Constructs Armory armor. Both output the same issue, just give me 3 mins to boot up

**Comment by Override5** [comment]
![image](https://user-images.githubusercontent.com/69968054/111258437-15cb3f00-8671-11eb-9284-f836a954451a.png)
![image](https://user-images.githubusercontent.com/69968054/111258452-1fed3d80-8671-11eb-96cb-bcb5e572746b.png)
![image](https://user-images.githubusercontent.com/69968054/111258487-3398a400-8671-11eb-8278-c3eaa960ddaf.png)


Im attempting to add the Beheading Modifier, but any other modifier i try to add also outputs this Error

**Comment by KnightMiner** [comment]
This error looks like either someone is using our API to cancel adding the modifier, or someone changed the modifier to require multiple slots. Can you reproduce the issue with a new tool? (in creative for instance) Can you reproduce this error with fewer addons? (use creative modifiers to get more slots)

There is no hard limit to modifiers when tool leveling is involved, so you shouldnt be getting this error. You are also the first to say you cannot add beyond 9 modifiers, I have seen many cases of it working for others making me think this is a mod conflict.

**Comment by Override5** [comment]
i can reproduce the issue with any tool or armor. I just got a notification from Tinker's Extras who claim its a config setting in THAT mod, but i cant see anything that would be that

![image](https://user-images.githubusercontent.com/69968054/111260638-4e6d1780-8675-11eb-9bfa-abd4fff28184.png)

**Comment by Override5** [comment]
never mind, ive found it. Its line 21. But its set to a hard cap of 100, so my issue is still an issue, But i dont think its TC's issue. so u can close this if u want
