### ISSUE TITLE
cannot build from source

### ISSUE THREAD

**Issue by asdfghjkl403622** [SlimeKnights/TinkersConstruct#4275]
I realize that this has already been looked at, but it's closed so I thought I'd make a new issue just to put it on the page. 

Version: 1.16.5
cloned straight from Github

I tried compiling from source on manjaro, no luck. I try changing java versions, deleting and reinstalling the folder, no dice. I go into a Pop! OS VM and try JDK 11 and JDK 8, no luck. when I read the original issue, it said that it was not an issue with tinkers construct so I would like to know how I am supposed to do it because nothing seems to be working, and it gives me the error that some of the features have been depreciated during building. 
"
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.8/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

> Configure project :
New Dep: net.minecraftforge:forge:1.16.5-36.0.42_mapped_snapshot_20201028-1.16.3_at_4ca872da001c805266ded7d76387757167938b2a

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6s
12 actionable tasks: 3 executed, 9 up-to-date
"
I got an error that looked nearly the exact same in the VM. 
Latest.log: https://pastebin.com/7RWdmHm4 

I cannot tell what I'm doing wrong, and I am fairly new. any help would be appericiated.

**Comment by KnightMiner** [comment]
You are building from source without knowing how to set up a mod workspace.

The mod will be released when it is ready, be patient like everyone else.
