### ISSUE TITLE
Endrod shaft arrows embossed with blaze rod shaft behave opposite of gravity

### ISSUE THREAD

**Issue by varappdev** [SlimeKnights/TinkersConstruct#4276]
**Issue description:**
So my smart self decided that by combining the endrod shaft and embossing it with blaze rod, the arrow will be very fast and have added range. But to my surprise, it just flew into the sky. I went under a block, and I was right. The arrow was going opposite of gravity as it was on the roof instead of the floor.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes, it just requires tinker's construct if it is just from the arrow shaft. If its not, it requires Ender IO as well for the making a Fake-Iron/Iron alloy shortbow, and an Electrical steel arrowhead with feather fletching.

**Comment by yeetgrenadewastaken** [comment]
I remember this happening too. it is easily reproducible.

**Comment by KnightMiner** [comment]
Closing this as 1.16 received a beta and 1.12 is unlikely to get another build. I added it to the milestone to look into if anyone picks up 1.12 again, though I do not know the fix in this case.

**Comment by varappdev** [comment]
👏
