### ISSUE TITLE
[1.16.5] Silky Block of Jewel unusable as a beacon base

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#4279]
**Issue description:**
The Silky Block of Jewel does not work when used as a beacon base, despite the tooltip saying otherwise. Other TCon blocks with the same tooltip such as Block of Copper and Block of Rose Gold do work properly as a beacon base, however.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.3
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.73

This issue is not on the roadmap or "What's New?"

This issue was originally produced with other mods, but the same result occurs with only TCon, Mantle, and JEI

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.76
