### ISSUE TITLE
Clear Glass Panes texture bug

### ISSUE THREAD

**Issue by Krappa322** [SlimeKnights/TinkersConstruct#428]
Clear glass appears differently from different sides as shown in screenshots. Both are the same window from different directions
![2014-01-16_17 51 39](https://f.cloud.github.com/assets/2184532/1932674/27fa23b4-7ecf-11e3-88da-b2c95360d133.png)
![2014-01-16_17 51 33](https://f.cloud.github.com/assets/2184532/1932673/27f9e9da-7ecf-11e3-8297-95aa47664125.png)

**Comment by zakdwyer** [comment]
This is still an issue for me as well. I've tried with and without Optifine, still the same issue. On 1.8.8.

**Comment by TehStoneMan** [comment]
I've noticed this with several different mods. It's just the way Minecraft textures glass planes. Annoying, but as far as I know, not much can be done about it. I believe it has something to do with how the built-in renderer wraps textures around boxes smaller than a block in size.
