### ISSUE TITLE
[1.16.5] Inventory Tweaks Renewed deletes contents of smeltery controller

### ISSUE THREAD

**Issue by FrostyFire1** [SlimeKnights/TinkersConstruct#4280]
**Issue description:**
Clicking the sort button in the smeltery controller deletes everything but one of each unique item put in it (see attached images).
![Before](https://user-images.githubusercontent.com/66720515/113336653-04e42400-9327-11eb-93be-c36bddb6224d.png)
![After](https://user-images.githubusercontent.com/66720515/113336650-044b8d80-9327-11eb-95e6-82db74f0f49d.png)

**Versions:**
* Minecraft:1.16.5
* Forge: 36.1.3
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.73

The issue is not covered on the roadmap or "Whats New?" 
Inventory Tweaks Renewed is required to reproduce the issue.

**Comment by KnightMiner** [comment]
Please report to inventory tweaks and cross link here

**Comment by KnightMiner** [comment]
Closing this as Inventory Tweaks Renewed appears to be unmaintained. I would advise using a different inventory sorter. Make a new ticket if you get a similar problem with another mod.
