### ISSUE TITLE
Skyslime liquid doesn't have same physics as water

### ISSUE THREAD

**Issue by Fisher2760** [SlimeKnights/TinkersConstruct#4281]
The Skyslime liquid doesn't have the same aspects of water e.g you can "swim" in it like if you had depth strider 3 furthermore you don't drowned in it

**Comment by KnightMiner** [comment]
Follow the issue template, don't bypass it

Assuming you are talking 1.16 (which I cannot tell since you ignored the issue template), its a Forge bug that we cannot solve. If that is the case open a new issue with the proper template.
