### ISSUE TITLE
Right-clicking on a crafting station's output produces approximately half of what it should

### ISSUE THREAD

**Issue by wwaisath** [SlimeKnights/TinkersConstruct#4282]
When right-clicking on the output of a recipe that produces more than one item (e.g. logs to planks, planks to sticks, recipe for blank patterns), the output is cut to two instead of the normal three or four, while still consuming the recipe's full required amounts.

This has not caused a crash, so no report.

* Minecraft: 1.16.5
* Forge:  36.1.3
* Mantle: Mantle-1.16.5-1.6.79
* Tinkers Construct: TConstruct-1.16.5-3.0.2.73

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Yes it can be reproduced with only TC. Created new instance using only JEI and the above Forge, TC, and Mantle, and reproduced the results

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.76
