### ISSUE TITLE
Part builder part bug

### ISSUE THREAD

**Issue by NinjaKnight1YT** [SlimeKnights/TinkersConstruct#4285]
**Issue description:**
you can receive infinite cheap parts using the part builder by shift+left clicking the output as it does not consume the pattern or material.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.16.5-1.6.79
* Tinkers Construct: 1.16.5-3.0.2

**Confirm below that this issue is not covered on the roadmap or "Whats New?"** From what I can see it's not

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** Yes, it can be reproduced with just Tinkers

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.76
