### ISSUE TITLE
[1.16.5] Insatiable effect does not function

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#4286]
**Issue description:**
Manyullyn's Insatiable trait does not function. Also does not work with different stacks of the trait either, and tools with the trait will do the same amount of damage each attack, assuming the weapon is fully charged.

However, because of how the trait is coded, mining a large number of blocks with Hepatizon's momentum and then attacking a target will increase the damage.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.3
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.73

This issue is not on the roadmap or "What's New?"

This issue is produced with very minor QoL mods: Hwyla, JEI, and MmmMmmMmmMmm. It is impossible to test without Hwyla or Mmm, because I would not be able to precisely monitor damage between attacks.

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.76
