### ISSUE TITLE
Stuck on Introduction

### ISSUE THREAD

**Issue by TheRealH0u** [SlimeKnights/TinkersConstruct#4287]
So I installed tinkers construct 2. And when i open the book (Materials And You) I only have i troduction and a border block for an image. I dont know why and how but the issue is I dont know all the recipes by hand and thought the books gonna help but its like "nah mate google it". I dont know whats wrong.

**Comment by KnightMiner** [comment]
Book is not done yet in 1.16. Book should work fine in 1.12. You ignored the issue templates, so I cannot tell which to help you with. If you are having trouble in 1.12. feel free to open a new issue with the proper template.
