### ISSUE TITLE
Accessing the Melter GUI crashes my game...

### ISSUE THREAD

**Issue by mjayvalen** [SlimeKnights/TinkersConstruct#4289]
**Issue description:**
So I was experimenting with the Melter Block and when I right clicked the Melter I would see the GUI for a few seconds and then my game would crash. I've added this to the FTB Endeavour modpack so maybe it would have to do with another mod that's incompatible maybe? 

Crash Log:
https://pastebin.com/FbkNpU92

**Versions:**
* Minecraft: 1.16.5
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
You ignored most of the issue template, and are using Optifine. If you can reproduce this without optifine, open another issue and actually provide the requested information. That last question is especially important.

**Comment by mjayvalen** [comment]
I apologized. This is my first time reporting an issue on github.
