### ISSUE TITLE
Infinite neighbour update loop

### ISSUE THREAD

**Issue by DBotThePony** [SlimeKnights/TinkersConstruct#4291]
**Issue description:**
TiC 3.0.2 crash the server when connecting Mekanism transfer pipes to smeltery

Crash report:
https://gist.github.com/DBotThePony/d5fd1e1012db4118367364302aa5ac5c

It appears that
https://github.com/SlimeKnights/TinkersConstruct/blob/804b456a802a03ea1772332ed83d361a6d88225d/src/main/java/slimeknights/tconstruct/smeltery/tileentity/SmelteryInputOutputTileEntity.java#L59-L75
is the cause. Notably, `setMaster` calls for neighbour update before setting new master, which cause pipe to check for capability, which come down to
https://github.com/SlimeKnights/TinkersConstruct/blob/804b456a802a03ea1772332ed83d361a6d88225d/src/main/java/slimeknights/tconstruct/smeltery/tileentity/SmelteryInputOutputTileEntity.java#L95-L110
which check for master validity again, which calls to `setMaster` and it go into infinite recursion. This can happen if pipe is both next to smeltery component and smeltery controller

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.3
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.73

**Comment by KnightMiner** [comment]
Try this again in 3.0.2.76. It should be fixed, but not certain.

**Comment by KnightMiner** [comment]
Closing this as fixed since there was no response. Feel free to reopen if this was not fixed

**Comment by DBotThePony** [comment]
I believe it is indeed fixed, just wasn't been able to 100% confirm it, but i am 90% certain it is.
