### ISSUE TITLE
Game crashes when activating smeltery

### ISSUE THREAD

**Issue by ItamarDenkberg** [SlimeKnights/TinkersConstruct#4292]
**Issue description:**
Every time I put anything in the smeltery my game just crashes.
I tested it multiple times with different fuels, and different items, it crashes every time.

**Crash report:**
https://pastebin.com/WvTeicKh

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.3
* Mantle: 1.16.5-1.6.72
* Tinkers Construct: 1.16.5-3.0.2.73

This issue is not covered on the roadmap or "What's new?"

https://user-images.githubusercontent.com/54473379/113486305-b2d40780-94ba-11eb-8d70-623cd20fe9c9.mp4

**Comment by PrincessOfEvil** [comment]
Optifine is unsupported.
