### ISSUE TITLE
[1.16] Smeltry alloys casting.

### ISSUE THREAD

**Issue by KodYazanDruid** [SlimeKnights/TinkersConstruct#4293]
**Issue description:**
It alloys but when i pour into cast or basin it gives me another material. It just with ingot cast. I can cast sword, pickaxe head without any problem.

**If crashed, link to crash report (use a site such as pastebin):**
No crash.

**Versions:**
* Minecraft: 1.16.5
* Forge: 16.1.2
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.73

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I don't think it is :D

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Thermal Series.

https://user-images.githubusercontent.com/45048634/113488523-6642f900-94c7-11eb-9133-8803c64fba7f.mp4

https://user-images.githubusercontent.com/45048634/113488530-6fcc6100-94c7-11eb-9ae4-56147fc12b84.mp4

**Comment by KnightMiner** [comment]
Duplicate of #4283. Remove performant to fix.

**Comment by KnightMiner** [comment]
Someone else on the team suggested this could be a problem with incorrectly tagged blocks. So reopening to confirm you do not have performant

**Comment by KodYazanDruid** [comment]
Performant really is the issue. It worked fine without performant.
