### ISSUE TITLE
Creeper Explosion Crashes Game

### ISSUE THREAD

**Issue by Mars455** [SlimeKnights/TinkersConstruct#4294]
Every time a creeper explodes, the game crashes, even without Tinkers being used in the game.
https://pastebin.com/2v9vfsr2

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0 and 36.1.3
* Mantle: Mantle-1.16.5-1.6.79
* Tinkers Construct: TConstruct-1.16.5-3.0.2.73

This is not mentioned in the roadmap

ScalingHealth is also required for this crash. 
(https://www.curseforge.com/minecraft/mc-mods/scaling-health)

**Comment by PrincessOfEvil** [comment]
I have no idea what ScalingHealth is doing to the looting event but it probably shouldn't.

Report it to them.

**Comment by KnightMiner** [comment]
Someone is firing the event with no damage source, should be explosion. However, easy catch for no damage source.

**Comment by KnightMiner** [comment]
Should be fixed in 3.0.2.76. Comment if its not fixed.
