### ISSUE TITLE
Fluids in world do not have any behavior

### ISSUE THREAD

**Issue by BookSerpent** [SlimeKnights/TinkersConstruct#4295]
If poured outside of a smeltery, molten blaze (and apparently all other fluids) do not behave as you would expect. If poured on water, they will simply replace the water and not interact with it at all. They also do not damage players or mobs or set them on fire.

Versions:
Minecraft: 1.16.5
Forge: 36.1.0
Mantle: 1.6.79
Tinkers Construct: 3.0.2.73

It can be reproduced with just Tinkers Construct.

**Comment by KnightMiner** [comment]
Yes, forge fluids are incomplete. Nothing we can do. Affects all fluids

**Comment by BookSerpent** [comment]
> Yes, forge fluids are incomplete. Nothing we can do. Affects all fluids

Ah ok.

**Comment by MarioSMB** [comment]
As a workaround, you may consider taking the approach Create has done, and include the molten fluids in the `minecraft:lava` tag so they share its behaviour.  
It's not perfect, but it allows the fluids to behave in the world prior to Forge solving this.

**Comment by KnightMiner** [comment]
That has too many potential side effects to do. You are free to do it in your own datapack, but be wary that bugs will be likely.

**Comment by KnightMiner** [comment]
MinecraftForge/MinecraftForge#7992 addresses this. Linking it to make it easier to track the progress.

**Comment by rdrpenguin04** [comment]
Superseded by MinecraftForge/MinecraftForge#8695, which is merged as of 11 days ago.

**Comment by KnightMiner** [comment]
Now that we have a release on 1.19.2, this is something we can fix. Will mark this issue as resolved once I figure out the fluid API.

**Comment by KnightMiner** [comment]
Fixed in [3.8.3.39](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/v3.8.3.39). This is not possible to backport to 1.18, so closing.
