### ISSUE TITLE
If Use Item/Place Block is bound to Left Button, you can't click on tools in the Anvil or Station

### ISSUE THREAD

**Issue by the-catt** [SlimeKnights/TinkersConstruct#4297]
**Issue description:**
If Use Item/Place Block is bound to Left Button, you can't click on tools in the Tinker's Anvil or Tinker's Station, it acts as if you're clicking on the block you're aiming at again, reopening the menu of the block you were originally looking at. 

**Versions:**
* Minecraft: 1.16.5
* Forge: forge-36.1.2
* Mantle: Mantle-1.16.5-1.6.79
* Tinkers Construct: Tinkers' Construct 3.0.2 and Tinkers' Construct 3.0.2.76

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Not covered from what I can tell
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes

**Comment by alexbegt** [comment]
Fixed in 3.0.2.78
