### ISSUE TITLE
[1.16] Casting Table & Basin - Crafting Station interaction

### ISSUE THREAD

**Issue by Excaliburns** [SlimeKnights/TinkersConstruct#4298]
**Issue description:**
When putting a crafting station next to a table or basin, the casting inventory will expose 2 inventory slots of which only one can be extracted from by the player. You can insert and extract out of the second slot, however doing so will not update the first input such as the sand cast.

Furthermore, the casting table and basin are missing translation entries.

<details>
<summary> Images </summary>

![image](https://user-images.githubusercontent.com/9357249/113496676-0e59c180-94ca-11eb-910a-d5f5b2f8904b.png)
![image](https://user-images.githubusercontent.com/9357249/113496678-16196600-94ca-11eb-96b2-e511f6946038.png)

</details>

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.76

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Could technically be covered as cleanup but thought it might as well be tracked.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
This is reproducible with just forge, TCon and Mantle.

**Comment by alexbegt** [comment]
Fixed in 3.0.2.78
