### ISSUE TITLE
Problem with Seared Channel

### ISSUE THREAD

**Issue by egnaro1007** [SlimeKnights/TinkersConstruct#4299]
**Issue description: The game crash when i try to place Seared Channel below another Seared Channel.**

**If crashed, link to crash report (use a site such as pastebin): [crash-2021-04-04_15.04.35-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/6254154/crash-2021-04-04_15.04.35-client.txt)**

**Versions:**
* Minecraft: 1.16.5
* Forge: 1.16.5-forge-36.1.0
* Mantle: Mantle-1.16.5-1.6.79
* Tinkers Construct: TConstruct-1.16.5-3.0.2.73

**This issue is not covered on the roadmap or "Whats New?"**

**Only TConstruct & Mantle**

**Comment by KnightMiner** [comment]
Ah right, that was the thing I forgot to do. Fixed this for ceramics but not for Tinkers

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.84
