### ISSUE TITLE
Minerais

### ISSUE THREAD

**Issue by xVodkaX** [SlimeKnights/TinkersConstruct#4300]
I find it unfortunate to have removed alumite and ardite, need just had to leave the choice to people to activate it or not I liked these alloys, especially since now in the nether there is only cobalt to mine this

Versions: 1.16.5

**Comment by KnightMiner** [comment]
We removed alumite years ago, back for 1.12. ardite was removed because it's redundant, I'm not developing a feature we don't need because "people might want it". You want it, add it to your own mod or commission a mod with it.
