### ISSUE TITLE
[1.16.5] Quark inventory sorting not working correctly

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#4302]
**Issue description:**
Quark's inventory sorting buttons aren't working correctly with Tinker's Construct stations.  
Example: https://i.imgur.com/HoxsVEc.png

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.76

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Likely not covered as this is a bug

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Quark r2.4-310

**Comment by KnightMiner** [comment]
Quark inventory sorting should not work on the side inventory, too risky because we don't control that inventory. Report this issue to quark and suggest a way to disable it for some inventories.

**Comment by FynnWaelsing** [comment]
There's a way to disable them from the Tinker's Construct stations. Consult the quark config to see how.

**Comment by MarioSMB** [comment]
To be clear, it is not something Tinker's Construct can solve on their end, and the Quark team is considering it solved by telling users to add class names to their configuration file in a closed issue.  
Unfortunately it looks like there won't be a clean solution to this problem, so you are free to close it.

**Comment by KnightMiner** [comment]
Try again in the latest alpha. There were some changes to how part and cast chests handle the dynamic slots that may have fixed this.

**Comment by KnightMiner** [comment]
Going to close this as it sounds like quarks policy for this type of issue is to just disable it in the config. They probably should add defaults in there with how many UIs it does not work it
