### ISSUE TITLE
[1.16] Storage Barrels - Crafting Station interaction

### ISSUE THREAD

**Issue by castilio20** [SlimeKnights/TinkersConstruct#4304]
**Issue description:**
Putting a Storage Barrel next to a crafting station exposes it's inventory, but trying to place an item in the slot crashes the client due to casting issues

**If crashed, link to crash report (use a site such as pastebin):**
[crash-2021-04-04_22.39.40-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/6254907/crash-2021-04-04_22.39.40-client.txt)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.76

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Yes it is not on the roadmap

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
You also need Storage Drawers.

**Comment by alexbegt** [comment]
Fixed in 3.0.2.78
