### ISSUE TITLE
Shader interaction

### ISSUE THREAD

**Issue by Slothincarnate** [SlimeKnights/TinkersConstruct#4305]
Broken interaction with shaders, specifically sildur's, tried with medium, high and extreme volumetric. When using shaders with a 3x3 tool (hammer/excavator shovel) screen turns black(or transparant) when cracks on blocks should appear. Additionally when swapping shaders in game the icon and texture of the tool turns into the UV box (purple/black checker, unsure actual name of it) then after using the tool the game crashes, crash report linked in pastebin. This has been tested with only tinkers and the shader/optifine as well as with a full modpack in development and the results were the same. Thanks

https://pastebin.com/WeT1Edi7

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 
* Tinkers Construct: TConstruct-1.16.5-3.0.2.73.jar

**Comment by PrincessOfEvil** [comment]
Optifine is unsupported.
