### ISSUE TITLE
Tinkers' Tools and Weapons deal one less damage than stated

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4306]
**Issue description:**
I have a stone axe with binding and handle out of wood, stating 7 damage, but testing it on a (poor) cow it deals only 6 damage.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.0.58
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.78

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**  
Yes

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**  
Yes

**Comment by KnightMiner** [comment]
Try with a different tool. Stonebound's trait lowers the tools damage as it loses more durability, so you probably dropped below the point of 7 damage into 6. I will look into a better way to show it in the tooltip again some time.

**Comment by Insane96** [comment]
Can confirm, the stonebound effect was the coulprit.
Maybe add a (-x) gray colored (more specifically trait colored) after the stat to show the stat changes?

Like
```
Attack: 7 (-1)
Mining Speed: 4 (+0.4)
```
