### ISSUE TITLE
Sweep attack doesn't damage mobs, seems to only knock them back

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4307]
**Issue description:**
Sweep attack doesn't damage mobs, seems to only knock them back. Also the area seems smaller.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.0.58
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.78

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**  
Yes

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**  
Yes

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.84
