### ISSUE TITLE
Fresh Tanks not stacking with used ones

### ISSUE THREAD

**Issue by Girithien** [SlimeKnights/TinkersConstruct#4308]
Once a Tank has been placed and broken (filled or unfilled doesn't matter) it no longer stacks with unplaced ones (might have something to do with it losing it's description text)

https://i.gyazo.com/4c26d8bb8d8b519d82e22ced29e114cb.mp4

**Versions:**
* Minecraft: 1.16.5
* Forge: 1.16.5 - 36.1.0
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.78

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Nothing of relevance to this matter on either 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes, on a fresh installation with just mantle and TiC

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.84
