### ISSUE TITLE
[1.16.5]TC Tools Optifine shader Support

### ISSUE THREAD

**Issue by DancingSnow0517** [SlimeKnights/TinkersConstruct#4309]
** Issue description:when i open shader,TC tools will become a purple black block **

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:3.0.2.78**
* Minecraft:1.16.5
* Forge: 36.1.3
* Mantle: 1.16.5-1.6.79
* Tinkers Construct:1.16.5-3.0.2.78 

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Yes, Optifine breaks most of Forge's rendering systems. No, there is nothing we can do about it. Report the issue to Optifine.

**Comment by gzr529** [comment]
Version G8 of OptiFine fixes this issue
