### ISSUE TITLE
disable tcon copper with config

### ISSUE THREAD

**Issue by ZEROX7** [SlimeKnights/TinkersConstruct#4310]
**so tcon adds its on copper but other mods do that too.**

**would it be possible to link the ingot nugget and block to the ore generation setting? that way you could disable the items by disabling the ores**

**Comment by PrincessOfEvil** [comment]
You cannot disable items with a config in 1.16. You can change the default output of most recipes with mantle server config, however.

**Comment by KnightMiner** [comment]
Yep, this is a problem as old as mods, and removing the items is not the solution. You have duplicates? Hide them in JEI, change the recipes.

**Comment by ZEROX7** [comment]
> You cannot disable items with a config in 1.16. You can change the default output of most recipes with mantle server config, however.

well wehn i add create between minecraft and tconstruct inside the mantle-server config inside the worlds folder it seems to be changing back after the restart is it not supported?

**Comment by KnightMiner** [comment]
That is a known bug in Mantle, but that config is just for convenience. Datapacks can already change all our recipes.
