### ISSUE TITLE
Mattock Kama Head and Tool Rod slots swapped in Tinker Anvil/Station

### ISSUE THREAD

**Issue by TeTeTri** [SlimeKnights/TinkersConstruct#4311]
**Issue description:**

![2021-04-05_21 44 18](https://user-images.githubusercontent.com/26594056/113619555-6bd04880-9659-11eb-8742-19679e9770f5.png)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.78

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Nothing of relevance to this matter on either

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes, on a fresh installation with just mantle and TiC

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.84
