### ISSUE TITLE
Tinkers missing stencil table

### ISSUE THREAD

**Issue by jgsanti** [SlimeKnights/TinkersConstruct#4312]
**Issue description:** In my experience, the stencil table does not to be appearing in the JEI alongside the patterns that it makes (does not appear to be craftable), making tinkers practically unusable in survival mode. Used on a heavily modded server tho, that could be a problem.

**If crashed, link to crash report (use a site such as pastebin):** No crashes

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.78

**Confirm below that this issue is not covered on the roadmap or "Whats New?"** The issue is not covered

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** Based on other topics i dont think so, but could be (not have tested yet) . Ill drop the list (optifine is included):

Bookshelf (by DarkhaxDev)
Just Enough Items (JEI) (by mezz)
ZeroCore 2 (by ZeroNoRyouki)
Extra Boats (by TeamAbnormals)
Enchantment Descriptions (by DarkhaxDev)
Refined Storage Addons (by raoulvdberge)
RFTools Base (by McJty)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
CleanCut (by Rongmario)
Flat Bedrock (by Sunekaer)
FTB Essentials (by FTB)
Mystical Agradditions (by BlakeBr0)
Inventory Pets (by Purplicious_Cow_)
Potions Master (by thevortexFoxTopia)
RandomPatches (Forge) (by TheRandomLabs)
Thermal Dynamics (by TeamCoFH)
Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
TOP Addons (by DrManganese)
Kotlin for Forge (by thedarkcolour)
Carry On (by Tschipp)
Ender Storage 1.8.+ (by covers1624)
Environmental Tech (by ValkyrieofNight)
Scannable (by Sangar_)
ReAuth (by TechnicianLP)
Powah! (by owmii)
Storage Drawers (by Texelsaur)
MrCrayfish's Furniture Mod (by MrCrayfish)
Industrial Foregoing (by Buuz135)
AppleSkin (by squeek502)
Refined Storage: Requestify (by Buuz135)
Lollipop (by owmii)
Cucumber Library (by BlakeBr0)
Architectury API (Forge) (by shedaniel)
FTB GUI Library (by FTB)
FTB Teams (by FTB)
Dungeon Crawl (by XIROC1337)
Reliquary v1.3 (by P3pp3rF1y)
Just Another Rotten Flesh to Leather Mod (by alexdaum1)
Cloth Config API (Forge) (by shedaniel)
Waystones (by BlayTheNinth)
Thermal Innovation (by TeamCoFH)
ValkyrieLib (by ValkyrieofNight)
Rats (by alex1the1666)
Spice of Life: Carrot Edition (by lordcazsius)
Metal Barrels (by tfarecnim)
Kiwi 🥝 (by Snownee_)
The One Probe (by McJty)
U Team Core (by HyCraftHD)
RSInfinityBooster (by hexeptiondev)
RFTools Builder (by McJty)
LibX (by noeppinoeppi)
The Mighty Architect (by simibubi)
Extra Armor (by Bailym)
Atmospheric (by TeamAbnormals)
Cyclops Core (by kroeser)
BetterEnd (Forge) (by Beethoven92)
Inspirations (by KnightMiner)
Simple Storage Network (by Lothrazar)
Snow! Real Magic! ⛄ (by Snownee_)
Runelic (by DarkhaxDev)
Trash Cans (by SuperMartijn642)
ItemPhysic Lite (by CreativeMD)
Glassential (by Lykrast)
Citadel (by alex1the1666)
SuperMartijn642's Core Lib (by SuperMartijn642)
Titanium (by hrznstudio)
RFTools Utility (by McJty)
Dark Utilities (by DarkhaxDev)
Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
Environmental Core (by ValkyrieofNight)
ProjectE (by SinKillerJ)
FastFurnace (by Shadows_of_Fire)
Biomes O' Plenty (by Forstride)
Flux Networks (by sonar_sonic)
The Endergetic Expansion (by TeamAbnormals)
Bountiful (by ejektaflex)
Server Tab Info (by black_dog20)
Useful Backpacks (by HyCraftHD)
Mystical Agriculture (by BlakeBr0)
Tinkers Construct (by mDiyo)
Crafting Tweaks (by BlayTheNinth)
Dynamic Surroundings (by OreCruncher)
SuperMartijn642's Config Lib (by SuperMartijn642)
Psi (by Vazkii)
Camera Mod (by henkelmax)
Construction Wand (by ThetaDev)
Compact Machines (by davenonymous)
TrashSlot (by BlayTheNinth)
Apotheosis (by Shadows_of_Fire)
Patchouli (by Vazkii)
Mantle (by mDiyo)
Building Gadgets (by Direwolf20)
Performant (by someaddon)
Structurize (by H3lay)
When Dungeons Arise (by Aureljz)
Morph-o-Tool (by Vazkii)
Structure Gel API (by ModdingLegacy)
Blood Magic (by WayofTime)
Macaw's Windows (by sketch_macaw)
Morpheus (by Quetzi)
Extreme Reactors (by ZeroNoRyouki)
Mekanism (by bradyaidanc)
Refined Storage (by raoulvdberge)
McJtyLib (by McJty)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Neat (by Vazkii)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Farming for Blockheads (by BlayTheNinth)
Modular Routers (by desht_08)
Angel Ring (by DenisMasterHerobrine)
Chunk-Pregenerator (by Speiger)
CodeChicken Lib 1.8.+ (by covers1624)
Solar Flux Reborn (by Zeitheron)
Client Tweaks (by BlayTheNinth)
Polymorph (Forge) (by TheIllusiveC4)
Akashic Tome (by Vazkii)
Mahou Tsukai (by stepcros)
Thermal Foundation (by TeamCoFH)
Artifacts (by ochotonida)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
JAOPCA (by TheLMiffy1111)
AttributeFix (by DarkhaxDev)
CoFH Core (by TeamCoFH)
Cooking for Blockheads (by BlayTheNinth)
Thermal Expansion (by TeamCoFH)
Lighting Wand 🌟 (by Snownee_)
Quark (by Vazkii)
Serene Seasons (by TheAdubbz)
Just Enough Resources (JER) (by way2muchnoise)
Farmer's Delight (by vectorwing)
Cosmetic Armor Reworked (by LainMI)
XP Tome (by bl4ckscor3)
Common Capabilities (by kroeser)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
ExtraStorage (by 3divad99)
Colossal Chests (by kroeser)
Clumps (by Jaredlll08)
Extreme sound muffler (Forge) (by LeoBeliik)
Security Craft (by Geforce132)
Click Machine (by Shadows_of_Fire)
Dynamic View (by someaddon)
Corail Tombstone (by Corail_31)
Better Advancements (by way2muchnoise)
Dank Storage (by tfarecnim)
Travel Anchors (by CastCrafter)
Comforts (Forge) (by TheIllusiveC4)
Quark Oddities (by Vazkii)
Wither Skeleton Tweaks (by Shadows_of_Fire)
Iron Chests (by ProgWML6)
FTB Backups (by FTB)
AutoRegLib (by Vazkii)
Abnormals Core (by TeamAbnormals)
FTB Chunks (by FTB)
Cyclic (by Lothrazar)
Fast Leaf Decay (by olafskiii)
Curios API (Forge) (by TheIllusiveC4)
Dungeons Plus (by ModdingLegacy)
YUNG's Better Portals (Forge) (by YUNGNICKYOUNG)
Simple Magnets (by SuperMartijn642)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
FPS Reducer (by bre2el)
BountifulBaubles (by Cursed1nferno)
Mod Name Tooltip (by mezz)
Ice and Fire: Dragons (by alex1the1666)
FastWorkbench (by Shadows_of_Fire)
Extra Disks (by MelanX)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Inventory Tweaks Renewed (by David1544)
Mouse Tweaks (by YaLTeR)
Better Burning (by DarkhaxDev)
Torchmaster (by xalcon)
MmmMmmMmmMmm (by bonusboni)
Pickle Tweaks (by BlakeBr0)
Macaw's Doors (by sketch_macaw)
Controlling (by Jaredlll08)
FTB Ultimine (by FTB)
Placebo (by Shadows_of_Fire)
JEI Integration (by SnowShock35)
[FORGE] Iron Furnaces (by XenoMustache)
Simply Jetpacks 2 (by Tomson124)
![abe6cd56cb24a9111686cbef153455b0](https://user-images.githubusercontent.com/34874344/113628455-4c2a2780-963b-11eb-8179-67a06474e499.png)
![bbfcf16114447855f78d60e113f98091](https://user-images.githubusercontent.com/34874344/113628474-54826280-963b-11eb-9c56-5978e8584223.png)

**Comment by ShinyPorygon** [comment]
Please see what's new as this has changed. This is not a bug.

**Comment by alexbegt** [comment]
There is no longer a stencil table in 1.16, please read the what's new page for more information. https://github.com/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3
