### ISSUE TITLE
Casting table always make my fluid into charred brick, no matter what my molten fluid is.

### ISSUE THREAD

**Issue by qyl27** [SlimeKnights/TinkersConstruct#4313]
**Issue description:**
When I use the smeltery to smelt aluminum (I had smelt iron before), I found that the casting basin always make my fluid into iron block, and the casting table always make my fluid into charred brick, no matter what my molten fluid is.

**If crashed, link to crash report (use a site such as pastebin):** No crash.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.2
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.78

**Confirm below that this issue is not covered on the roadmap or "Whats New?"** Yes

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** Yes

**Comment by alexbegt** [comment]
Duplicate of #4283, there is a reason that issue is pinned. Remove performant or disable caching of recipes.
