### ISSUE TITLE
Game Breaking Casting Basin Rendering Crash

### ISSUE THREAD

**Issue by lordeyahyahyah** [SlimeKnights/TinkersConstruct#4315]
**Issue description:** Tried to cast a Nauhatl tool rod and when it dried the game crashed. There was a hopper exporting items out of the basin into a chest but not sure if that's important. Logged back into the world to see some really strange rendering issues with blocks/items not even related to tinkers. Tried again and now pretty much nothing is rendering. Screenshots provided in the links below.

**Screenshots:**
![2021-04-06_13 21 37](https://user-images.githubusercontent.com/76751624/113755901-d2e41080-96de-11eb-9805-0954d727be51.png)
![2021-04-06_13 27 28](https://user-images.githubusercontent.com/76751624/113755905-d37ca700-96de-11eb-906a-1c596c0d10e2.png)

**Crash Report:** https://pastebin.com/3hHLwYmX

**Versions:**
Minecraft: 1.16.5
Forge: 36.1.2
Tinkers Construct: 3.0.2.76

Mod List provided in the crash report.
*(Running TNP Limitless 3 Modpack, version 1.9.9b, with the addition of Optifine and Horror Movie Monsters mod. Performant was in the pack but caused the Tinkers' bug where every metal poured out the smeltery was your first metal melted so I removed it.)

**Comment by PrincessOfEvil** [comment]
Optifine is unsupported.
