### ISSUE TITLE
Tools cannot be renamed in the Tinker Station or Anvil

### ISSUE THREAD

**Issue by BatteryVoltic** [SlimeKnights/TinkersConstruct#4317]
**Issue description:**
In my last live stream I had issues with naming tools, stream highlight will be posted for video evidence. When naming a tool, naming it with a capital letter it knocks you out of the gui and the name does not even stick to the tool. 

Stream Highlight: https://www.twitch.tv/videos/977736891

**If crashed, link to crash report (use a site such as pastebin):**
Does not apply

**Versions:** 
* Minecraft: 1.16.5
* Forge: 36.1.2
* Mantle: 1.16.5 1.6.79
* Tinkers Construct: 3.0.2.78 ALPHA

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Unsure, didnt know there is a roadmap
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I have only come across this once and that was on stream. Only ever did this once.

**Comment by KnightMiner** [comment]
Naming tools does not work, and I am half inclined to ditch the whole feature. Try renaming a tool in a vanilla anvil, let me know if anything does not properly persist.

**Comment by Insane96** [comment]
The only thing that annoys me is that the anvil requires 1 level to rename, other than that, I really don't see a reason to make tools nameable from the Tinkers' Station/Anvil

**Comment by KnightMiner** [comment]
3.0.2.84 removes the text field. I am not sure yet if I will bring it back, if so it will either be Tinker's Anvil exclusive or in a separate block. For now just use the anvil.

Going to change the tags on this to feature since the buggy behavior is gone, now its a feature that may get added

**Comment by KnightMiner** [comment]
For the record, my current plan is to provide some method for naming a tool on first creation, but will likely not allow renaming the tool to keep vanilla renaming relevant. Means the text field will only show up when selecting a layout. Still need to decide how to deal with syncing the name so its not super laggy with multiple players, might simply make the player who grabs the item the authority on the name.

**Comment by Gartebex-Ugandi** [comment]
Wait, cant you just use the vannila function for renaming ?

**Comment by KnightMiner** [comment]
Added in 3.6.2.92

And yes, why would Tinker tools not support vanilla renaming? We had our own for convivence, not because it was needed.
