### ISSUE TITLE
Easy duping

### ISSUE THREAD

**Issue by RonanNeox** [SlimeKnights/TinkersConstruct#4320]
Crafting station duplication

I placed iron nuggets on a crafting station and shift clicked the craft, i had an inventory full of iron ingots. I seems that the items needed for the recipe are not consumed after the craft.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by Random832** [comment]
Please fill out the issue template, including in particular what other mods you have installed. This issue did not happen for me when I tried to reproduce it.

**Comment by RonanNeox** [comment]
I played on the latest curseforge forge version, on a server with this
modpack, textures and shaders exactly.

Minecraft Server: IridiumCorp 1.16.5 Forge
Modpack: https://fromsmash.com/modpack12
- 178.32.145.107:25565 -

**Comment by PrincessOfEvil** [comment]
>shaders

So i'm flagging it under Optifine. If the issue persists without it, feel free to reopen the issue.
