### ISSUE TITLE
Make Soulspeed work on soul glass

### ISSUE THREAD

**Issue by wildcardgamez** [SlimeKnights/TinkersConstruct#4321]
---
name: 1.16 Enhancement
about: Suggest changes to existing features. For new feature suggestions, please bring
  to Discord.
title: ''
labels: Enhancement, Unreviewed, 1.16
assignees: ''

---

**Is your idea related to a problem? Please describe.**
It isn't related to a problem, but I think it'd be nice to have another block that works with soulspeed, and this just makes sense

**Describe the solution you'd like**
After looking through Minecraft's code, soul speed works through the soul_speed_blocks block tag, so just by adding soul glass and soul glass panes to that list, it should work fine.

**Describe alternatives you've considered**
If this doesn't work I don't really know what you could do to add it.

**Additional context**
N/A

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.78

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
Yes

**Comment by KnightMiner** [comment]
Added in 3.0.2.84
