### ISSUE TITLE
Slime islands teleporting through ground

### ISSUE THREAD

**Issue by AmburLoaf** [SlimeKnights/TinkersConstruct#4322]
I've gone up to 2 skyslime islands in two different worlds
The first one teleported me straight down into the ground and killed me via fall damage
The second one teleported me through bedrock and killed me with no chance of recovering my items

**Comment by KnightMiner** [comment]
Use the issue template. And play on the latest alpha. If this is still an issue, reopen an issue with the actual issue template.
