### ISSUE TITLE
hammer screen texture

### ISSUE THREAD

**Issue by TK5380** [SlimeKnights/TinkersConstruct#4323]
**Issue description:**
when mining with the hammer it puts a whit screen up and as you break a block it shows the screen breaking as well

**Versions:**
* Minecraft:1.16
* Forge: 36.1.0
* Mantle: 
* Tinkers Construct: latest 

[Bug.zip](https://github.com/SlimeKnights/TinkersConstruct/files/6274489/Bug.zip)
in this zip is a video of what's happening

**Comment by FynnWaelsing** [comment]
Do you have Optifine installed?

**Comment by KnightMiner** [comment]
Also, there is no latest version. I cannot tell if you are on the first alpha thinking its the latest, or you are on the alpha released yesterday. Type an actual version number

**Comment by TK5380** [comment]
> Also, there is no latest version. I cannot tell if you are on the first alpha thinking its the latest, or you are on the alpha released yesterday. Type an actual version number

Yesterdays release.

**Comment by TK5380** [comment]
> Do you have Optifine installed?

Yes I do

**Comment by KnightMiner** [comment]
Remove optifine and see if this issue still happens. If so, report the issue to the optifine devs. We do not support optifine because optifine is a closed source mod. If the dev knows how to fix this error, our mod is open source, so they are free to make a pull request.

**Comment by NomSTee** [comment]
Would it be possible to add config option to disable multiblock breaking animation as i believe this is the cause

**Comment by KnightMiner** [comment]
No, I am not going to add configs to disable every renderer that causes problems with Optifine. That would get exausting. Report the issue to Optifine if you want this fixed.

**Comment by KnightMiner** [comment]
3.0.2.96 changed some of the block breaking renderer based on some updates in other mods with a similar renderer. If that fixed this issue, great. If not, report it to optifine, as what we are doing now is definitely correct.

**Comment by KnightMiner** [comment]
Closing as an optifine bug, as I don't care to debug this any more. Tell Optifine to either make their mod open source so we can debug this issue, or to fix it themselves.
