### ISSUE TITLE
Require Netherite for indestructibility/no despawn

### ISSUE THREAD

**Issue by MagusLucius** [SlimeKnights/TinkersConstruct#4324]
Tinkers tools are naturally indestructible by any means other than a trash can, or using them while they're broken.

Netherite gives tools and armor protection from Lava in vanilla, and it would be great if this were also required (even optionally) for tinkers tools.

**Versions:**
* Minecraft: 1.16+

**Comment by KnightMiner** [comment]
Have you even played the 1.16 build? Obviously not, this is alreay a thing.
