### ISSUE TITLE
Repair Kits Return? 

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#4327]
Are repair kits making a comeback?  I'd hate to have to carry around a tool forge and have to put it down all the time.

**Comment by KnightMiner** [comment]
Probably, have not decided how they will look, but on the go repair will return in some form.

**Comment by MokahTGS** [comment]
Will they work any different or just look different?

**Comment by KnightMiner** [comment]
I did not mean look visually, I meant look functionally. They will be different potentially.

**Comment by KnightMiner** [comment]
Added to the roadmap, so closing this.
