### ISSUE TITLE
Add Compatibility for Advanced Chimneys and Pollution of the Realms

### ISSUE THREAD

**Issue by Drakma** [SlimeKnights/TinkersConstruct#4328]
**Is your idea related to a problem? Please describe.**
Currently the smeltery and melter can not be added to either mod as the status is always "active." If you were to use this status then it would constantly be blowing smoke/pollution.

**Describe the solution you'd like**
Added a new status to the smeltery controller, drain and melter that shows when it is actively melting or pouring.  This will allow smoke and pollution to be released when the blocks are actually being used.
**Describe alternatives you've considered**

**Additional context**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.79
* Tinkers Construct: 1.16.5-3.1.2.78

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
I do not see this idea/enhancement on your roadmap and would appreciate your concideration.

**Comment by KnightMiner** [comment]
In the smeltery, block updates are kinda a big deal, they can trigger structure rebuilds if I am not careful, which is super inefficient for a state that is constantly changing

Bigger problem is the controller lights up as a visual indication the structure is valid. I could probably make use of the fluid window for that and light the controller when melting though.

So overall, I'll look into it, but no promises to add anytime soon.

**Comment by KnightMiner** [comment]
As of 3.0.3.109, smeltery controllers now have two boolean properties: `active` and `in_structure`. Active will only be true when actively using fuel.

For the melter and heater, both also set `in_structure` when together, and `active` is set on both when burning fuel.
