### ISSUE TITLE
[1.16.5] Mobs are able to spawn on clear glass

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#4329]
**Issue description:**
Mobs are able to spawn on top of clear glass blocks (vanilla glass does not allow hostile mob spawns)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge:  36.1.4
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.76

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
This is a bug and likely not covered by roadmaps. Playing on a server, I am however unable to confirm whether this occurs in newer versions of the mod

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.96
