### ISSUE TITLE
[MC 1.16.5] Can't play with TC

### ISSUE THREAD

**Issue by TheDarkRisen** [SlimeKnights/TinkersConstruct#4331]
**Issue description:** Doesn't load my world with Tinkers Construct

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.88
* Tinkers Construct: 3.0.2.84 and tested 3.0.2.78 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Without Tinkers Construct everything fine.
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/6284941/latest.log)

**Comment by PrincessOfEvil** [comment]
Tinkers Construct is incompatible with Optifine.

**Comment by TheDarkRisen** [comment]
Oh, so sad. Can I mention this issue to OptiFine developers? Or you can fix that?

**Comment by PrincessOfEvil** [comment]
You can. We can't fix it cause Optifine is closed source and we have no idea what they're breaking.

**Comment by TheDarkRisen** [comment]
Done! Thx for answering!

**Comment by KnightMiner** [comment]
Your latest.log blames this on an out of memory error, you may simply need more RAM

**Comment by embeddedt** [comment]
If you are looking for a performance boost, you can give https://github.com/Pannoniae/sodium-forge a try. It gives a substantial boost, especially if your PC is not made for gaming, and appears to work well with most of the major mods, including Tinkers' Construct (though I only tried placing a few complex blocks from each).

Do note that as it's obviously an invasive mod you probably won't receive support from Tinkers devs for it.

**Comment by TheDarkRisen** [comment]
oh, thx I will try it!

**Comment by TheDarkRisen** [comment]
With Sodium everything is fine. I can play with TC

**Comment by KnightMiner** [comment]
Going to close as a non-Tinkers issue.
