### ISSUE TITLE
incorrect glass to glass panel recipe

### ISSUE THREAD

**Issue by AlleCraft-alterego** [SlimeKnights/TinkersConstruct#4333]
vanilla recipe for make require 6 glass block for make 16 panel

tinkers construct smelt 6 glass block for make 24 panel 

now tinker smelt 6 glass block 6'000 mb (1'000mb a block) for make 24 panel 6'000mb (250mb a panel)

but real mb of 1 panel is 375mb for make 16 panel (6'000mb of total)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.88
* Tinkers Construct: 3.0.2.84

**Comment by KnightMiner** [comment]
Works as intended. Casting molten glass into panes gives you a discount. I did the math, there should be no duplication bugs here, so 250mb seems good.

**Comment by AlleCraft-alterego** [comment]
ok
