### ISSUE TITLE
Container filling doesn't show in JEI

### ISSUE THREAD

**Issue by PrincessOfEvil** [SlimeKnights/TinkersConstruct#4335]
Container filling recipes, either of the two, just don't show in JEI, and it's not incredibly obvious that they even exist.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.2
* Mantle: 1.6.89
* Tinkers Construct: 3.0.2.86

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
Can confirm.

**Comment by KnightMiner** [comment]
Added in 3.0.2.96
