### ISSUE TITLE
Enderlime Sling behavious is strange

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4337]
**Issue description:**
Use a slimesling at x0.5 z0.5 towards +x you'll always find yourself to x6.0 z0.0, no matter where you aim.

Also, teleporting sideways
https://user-images.githubusercontent.com/7185104/114297855-60df4300-9ab3-11eb-9340-e4d8af78ce4e.mp4

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.88
* Tinkers Construct: 3.0.2.84

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I accept the terms and conditions

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes

**Comment by KnightMiner** [comment]
The left moving behavior is simply because when at the .0 coordinates in certain look directions, your look direction will cause the sling to try the block to the left. Centering the player on teleport prevented that issue.

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.96
