### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by xVodkaX** [SlimeKnights/TinkersConstruct#4339]
why we can no longer configure the mods as before with the choice of cobalt ardite alumite ores especially since it gave tinkers unique ore copper we see it everywhere alumite does not exist and for ardite natura is not update ^^
I would wait to see if natura puts the ardite ore for the nether 

Image 1.12.2
![genore](https://user-images.githubusercontent.com/30953385/114302706-790e8c80-9aca-11eb-84e9-3b42e506a7df.png)

**Comment by KnightMiner** [comment]
Uh, what? Forge has not implemented config GUIs yet. Configure it using the text file. I do not understand the rest of your request, something about rapid firing ores you want added. In that, I will remind you enhancements are about changes to *existing* features. Take new feature ideas to discord.
