### ISSUE TITLE
Broken beheading upgrade

### ISSUE THREAD

**Issue by RoBOticRebel** [SlimeKnights/TinkersConstruct#4340]
Broken beheading upgrade causes mobs and blocks to drop player heads

no crash

**Versions:**
* Minecraft:1.16.5
* Forge: 1.16.5 - 36.1.4
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.78

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
it is not
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
yes it can

to reproduce the issue the easiest way is to grab a beheading tool/sword in one hand and flint and steel in the other and rapidly set and put out fire

**Comment by KnightMiner** [comment]
Fixed in 3.0.2.96
