### ISSUE TITLE
Gold outputs copper

### ISSUE THREAD

**Issue by ARamlall** [SlimeKnights/TinkersConstruct#4341]
**Issue description:**
Gold changes to copper when poured out into basin, displays as gold in smeltery. ID mixup?  Other ores output as copper aswell.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.4
* Forge: 1.16.4 - 35.1.4
* Mantle:  1.6.88
* Tinkers Construct: latest

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
not there to my knowledge

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

modlist at bottom of https://www.curseforge.com/minecraft/modpacks/invicta-1

**Comment by castilio20** [comment]
you have performant in that pack and that is the cause

**Comment by ARamlall** [comment]
Thank you.

**Comment by KnightMiner** [comment]
Duplicate of #4283, there is a reason that issue is pinned. Don't report bugs with performance enhancers.
