### ISSUE TITLE
Stacked Copper Cans produces inconsistent results

### ISSUE THREAD

**Issue by Mrbysco** [SlimeKnights/TinkersConstruct#4342]
**Issue description:**
When right-clicking a Seared Tank using stacked Copper Cans (holding a fluid) (count of 2 or more)
It puts twice the amount of liquid into the Seared Tank. So instead of inserting 144mb it puts 288mb into the Seared Tank.

Video showing the bug in action:
[![](https://img.youtube.com/vi/ky2JDFaPH2M/maxresdefault.jpg)](http://www.youtube.com/watch?v=ky2JDFaPH2M "Tinkers' Construct - Stacked Copper Cans bug")

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.92
* Tinkers Construct: 3.0.2.96

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Couldn't find any mention.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
It can be reproduced with just Tinkers' Construct.

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.126
