### ISSUE TITLE
1.16.5 RU translate

### ISSUE THREAD

**Issue by Hmanubis** [SlimeKnights/TinkersConstruct#4343]
File translate ru_ru
[ru_ru.json.txt](https://github.com/SlimeKnights/TinkersConstruct/files/6297319/ru_ru.json.txt)

**Comment by KnightMiner** [comment]
Please open a pull request instead. Feel free to ping me on discord if you are unsure of how.

**Comment by Hmanubis** [comment]
> Please open a pull request instead. Feel free to ping me on discord if you are unsure of how.

ok, done)
