### ISSUE TITLE
Call PlayerInteractEvent.RightClickBlock when using tools

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4345]
**Is your idea related to a problem? Please describe.**
The mod [Dirt to Path](https://www.curseforge.com/minecraft/mc-mods/path-to-dirt) works only on the block right-clicked when using ~~the excavator~~ tools (since even a shovel can have the Expanded modifier).

**Describe the solution you'd like**
Call `PlayerInteractEvent.RightClickBlock` on the blocks in the whole area

**Describe alternatives you've considered**
None

**Additional context**
![2021-04-12_17 36 25](https://user-images.githubusercontent.com/7185104/114421568-b8fe6e00-9bb5-11eb-8bb8-a823d4be0d5a.png)
![2021-04-12_17 36 27](https://user-images.githubusercontent.com/7185104/114421571-b9970480-9bb5-11eb-9ec8-1c6c6ec89395.png)
![2021-04-12_17 36 29](https://user-images.githubusercontent.com/7185104/114421573-ba2f9b00-9bb5-11eb-9c42-8538237b14ff.png)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.92
* Tinkers Construct: 3.0.2.96

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
Confirm

**Comment by KnightMiner** [comment]
The mod Dirt to Path is doing things wrongly. They should be using the forge logic for shovel path blocks, not implementing it themselves in a right click block hook. Report this to them.

For reference, `BlockState::getToolModifiedState` and `BlockToolInteractEvent`

**Comment by Insane96** [comment]
I'm them ... gonna try and change it. Thanks
