### ISSUE TITLE
[1.16.5] Clear Item Frame entity name is unlocalized and also not transparent

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#4349]
**Issue description:**
The names of the Clear Item Frame entities show as entity.tconstruct.fancy_item_frame.clear (revealed by Hwyla) and also do not become transparent when an item is placed on them.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.3
* Mantle: 1.6.92
* Tinkers Construct: 3.0.2.96

This issue is not on the Roadmap or "What's New?"

This issue was originally produced on a multiplayer server with other mods, and one TCon version behind, but can be reproduced on the latest alpha in singleplayer without other mods (other than Hwyla).
![image](https://user-images.githubusercontent.com/58322110/114481322-510a5080-9bd2-11eb-9580-b18880d5b476.png)

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.109
