### ISSUE TITLE
Reinforced V not keeping tool from losing durability

### ISSUE THREAD

**Issue by bearbylon** [SlimeKnights/TinkersConstruct#4354]
I put together a Pickaxe, head, binding and rod all casted from Rose Gold. With Reinforcement V applied it is still losing durability (when mining vanilla stone in this test).

* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.16.5-1.6.92
* Tinkers Construct: 1.16.5-3.0.2.96

I used no other mods for this test. Tested both in SP and MP.

**Comment by KnightMiner** [comment]
Yes, that is intended. Full unbreakable costing just a few obsidian is dumb. We have a plan for that later. See also the roadmap, that the issue template told you to read and you ignored.
