### ISSUE TITLE
Compliance level will return?

### ISSUE THREAD

**Issue by ARCTICL1GHT** [SlimeKnights/TinkersConstruct#4355]
Will the compliance level return to create the unbreakable pickaxe?

**Comment by KnightMiner** [comment]
Compliance level? In any case, "when will X return" is not a enhancement. Do not ask for ETAs.

**Comment by LHDM2000** [comment]
sorry I wanted to refer to this
![143B4EC7-DF5D-4CE0-90CD-9B705181362B](https://user-images.githubusercontent.com/49601838/114777788-4e723d00-9d31-11eb-901c-e640e2fdbb6d.jpeg)
