### ISSUE TITLE
Incomplete casting makes basins and tables get "stuck"

### ISSUE THREAD

**Issue by mDiyo** [SlimeKnights/TinkersConstruct#4357]
Casting blocks can be put into a weird state using a few steps.

1. Partially fill a casting basin. Do not complete the cast
2. Drain the basin of liquid with a faucet so that it's empty.

In this state, the blocks will not accept any liquid other than the liquid they expect for their cast. eg an interrupted iron casting for a tool part requires iron. Swapping out a hammer head for a pickaxe head will still drain all 8 ingots expected of the larger hammer head and render strangely. 

![2021-04-14_16 42 58](https://user-images.githubusercontent.com/1430358/114794112-a3697f80-9d40-11eb-9420-f3cac0069836.png)

3. Save/Load the game, and the blocks are effectively broken. They will accept only the chosen liquid and will never finish their recipe. The client doesn't know this and will show an effective cast, leading to a situation where you can "create" an item and then pour the liquid out of the block.

![2021-04-14_16 40 31](https://user-images.githubusercontent.com/1430358/114793932-4e2d6e00-9d40-11eb-84b3-39d80958d138.png)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.92
* Tinkers Construct: 3.0.2.92

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
This sort of bug is not on the roadmap.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Tinkers Construct only.

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.109
