### ISSUE TITLE
Invisible blocks after planting slime saplings

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#4358]
**Issue description:**
I'm playing on a server. After a slime sapling fully grew into a tree, I could not see some slime blocks and slime leaves generated by the tree. However, I still collided with them, but could not destroy them. Placing any block on the invisible block seemed to "reveal" some of the blocks around it, which I could then destroy. Re-logging into the server seemed to show some of the blocks that I couldn't see before, but not all.

**If crashed, link to crash report (use a site such as pastebin):**
No crashes.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.2
* Mantle: 1.6.88
* Tinkers Construct: 3.0.2.84

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Yes.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I am playing on a modpack, but I believe this may only be an issue with Tinkers Construct.

**Comment by KnightMiner** [comment]
Try the last question again. "I believe it is only an issue with Tinkers Construct" is not testing it. Test it.

**Comment by ghost** [comment]
Just re-tested on with only Mantle and Tinkers installed:
Mantle 1.6.92
Tinkers Construct: 3.0.2.96
Forge 36.1.0

I could not re-produce the error on a client only. I did not test it while connected to an external server. :)
