### ISSUE TITLE
Some tools and weapons missing from the part builder

### ISSUE THREAD

**Issue by frog-gichur** [SlimeKnights/TinkersConstruct#4359]
**Issue description:**
Some of the tools, like the hammer, excavator, and many other tools, are seen in the JEI mod but are not seen in the Part Builder or any of the other Tinkers' crafting stations.
**If crashed, link to crash report (use a site such as pastebin):**
I did not crash, I am assuming it is just a bug.
**Versions:**1.16.5
* Minecraft: Java 1.16.5
* Forge: 1.16.5-36.1.4
* Mantle: 1.16.5-1.6.92
* Tinkers Construct: 1.16.5-3.0.2.96

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I looked through this website and the Curse Forge website and I did not see anything on it. In fact there are some photos with the missing parts in my game on the developers game.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I think that this is just a Tinkers' bug.

![image](https://user-images.githubusercontent.com/82608519/114918680-5a273780-9df5-11eb-99da-c912e6a4c31d.png)
![image](https://user-images.githubusercontent.com/82608519/114918707-64493600-9df5-11eb-829d-9c836e742df3.png)
![image](https://user-images.githubusercontent.com/82608519/114918739-6f03cb00-9df5-11eb-98b7-5a20842dfc04.png)
The third image is there to show that there are excavators and hammers and other items like that in the mod, but not appearing in the work stations.

**Comment by KnightMiner** [comment]
You did not look through "What's New". That was linked on the new issue screen at the bottom. If you did read it, you would have seen the line:

> Many parts that only got used once were removed in favor of reusing parts

Open up the tinker station/tinkers anvil, see what parts are required for tools

**Comment by PrincessOfEvil** [comment]
You need a Tinker Anvil to make broad tools. This isn't anything new to
TiC3.

**Comment by frog-gichur** [comment]
> You need a Tinker Anvil to make broad tools. This isn't anything new to TiC3.

OOOHHH THANKKKKK YOUUUUUUUU
