### ISSUE TITLE
Soul glass/panes do not support soul fire

### ISSUE THREAD

**Issue by muzikbike** [SlimeKnights/TinkersConstruct#4360]
Expectations would be that they would support soul fire due to being a derivative of soul sand (for example, quark's soul sandstone also supports it).

1.16.5, 36.1.0, 1.6.92, 3.0.2.96

Yes

Probably, would recommend not reproducing this alongside Immersive Portals as the mirror functionality will likely get in the way

![2021-04-15_23 21 38](https://user-images.githubusercontent.com/52297970/114950127-54a80c80-9e4a-11eb-8412-04af076e15d4.png)

Could be easily fixed just by adding the blocks to the appropriate tag.

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.109
