### ISSUE TITLE
[1.16.5] Duplication glitch using the Smeltery, Copper Cans, and other TCon fluid containers (Seared Gauge, etc)

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#4361]
**Issue description:**
When rapidly using fluid-filled Copper Cans on a Smeltery Drain, the attached smeltery will have more fluid than what was put in. This will also happen with TCon containers such as the Seared Gauge, but as with Seared containers, you are also able to rapidly _take out_ fluid using copper cans, which also causes you to take out less fluid than what was originally put in the Seared container.

Copper Cans will also duplicate fluids when rapidly using them on an Immersive Engineering Barrel. Rapidly using a fluid-filled Iron Bucket in creative on a TCon container or smeltery will also input more fluid than intended, but fluid does _not_ get duplicated this way if attempted on another mod container (IE barrels).

[This video](https://youtu.be/xLa_9dgJKWs) demonstrates the glitch in action. I had forgotten to show the empty Smeltery at the very beginning of the video, but breaking the Controller should be enough proof. Also note that I had slowly put in 4 cans worth of Netherite in a Seared Gauge, but took out 8 cans worth of Netherite from the same Gauge at the end of the video.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.3
* Mantle: 1.6.92
* Tinkers Construct: 3.0.2.96

This issue is not mentioned in the Roadmap or "What's New?"

This issue was originally produced a multiplayer server with ~40 mods and TCon running one version behind. However, this issue can also be reproduced with ONLY TCon 3.0.2.96 (latest) and Mantle installed in singleplayer.

**Comment by KnightMiner** [comment]
Should be fixed in 3.0.3.126 alongside #4342, I can no longer reproduce it at least. Feel free to repopen if this still happens.

If you have this issue with other mods, report to them..
