### ISSUE TITLE
The sound event for equipping slime boots reuses the slime block placement sound event instead of using a unique sound event, causing incorrect subtitles

### ISSUE THREAD

**Issue by muzikbike** [SlimeKnights/TinkersConstruct#4363]
The subtitle produced is "Block placed", which is obviously incorrect due to the fact that this action doesn't place a block. Compare the sound event for equipping vanilla armor.

![2021-04-16_01 39 29](https://user-images.githubusercontent.com/52297970/114955585-eae13000-9e54-11eb-81c1-93da1eae9d65.png)
![2021-04-16_01 39 31](https://user-images.githubusercontent.com/52297970/114955587-eb79c680-9e54-11eb-99ab-8849839951fa.png)
![2021-04-16_01 39 42](https://user-images.githubusercontent.com/52297970/114955589-ec125d00-9e54-11eb-9398-76c8f952a23c.png)
![2021-04-16_01 39 42_2](https://user-images.githubusercontent.com/52297970/114955591-ecaaf380-9e54-11eb-9476-2eadc45ac0d9.png)

This could be fixed by creating a new dedicated sound event, still pointing to the same sound files that the old sound event does, but to a new, actually correct translatable subtitle string.

* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.92
* Tinkers Construct: 3.0.2.96

Confirmed

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Almost certaintly

**Comment by KnightMiner** [comment]
Fixed in 3.1.3.271, let me know if I missed anything
