### ISSUE TITLE
Nether slime island doesn't generate in BoP world

### ISSUE THREAD

**Issue by luckyu19** [SlimeKnights/TinkersConstruct#4368]
**Issue description:**
Tinkers' Construct nether slime island doesn't generate in BoP world.
Tested with a fixed seed, overworld and end slime island generates normally.

**If crashed, link to crash report (use a site such as pastebin):**

Minecraft: 1.16.5
Forge: 36.1.4
Mantle: 1.6.88
Tinkers Construct: 3.0.2.84
Biome O Plenty: 13.0.0.431

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Yes

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Requires Biome O Plenty 13.0.0.431

Generated with just Tinkers' Construct
![2021-04-16_20 14 39](https://user-images.githubusercontent.com/19247442/115024899-47932800-9ef3-11eb-97d0-712ee44abd8d.png)
Around the same area, with BoP world generation enabled
![2021-04-16_20 41 40](https://user-images.githubusercontent.com/19247442/115025658-372f7d00-9ef4-11eb-923f-42adec5952ae.png)

Link to issue on BoP:
Glitchfiend/BiomesOPlenty#1838

**Comment by Gbergz** [comment]
Can also mention that they don't generate in [BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go) (nether) world either.

**Comment by KnightMiner** [comment]
@Gbergz please make a separate report for BYG, that may or may not be the same cause so I want to track them separately. Also report the issue to BYG so we can figure out the solution with those devs.

**Comment by KnightMiner** [comment]
For some more context, our current logic checks for the nether biome provider to add the needed structure info to the nether. However, most mods that replace the nether replace the biome provider, meaning our check fails. @alexbegt said he would look into injecting our structure info into the default map, its a bit more awkward to do but should fix this issue.

**Comment by KnightMiner** [comment]
Should be fixed in 3.0.3.144
