### ISSUE TITLE
Stencil Table And Pattern Chest Are Missing

### ISSUE THREAD

**Issue by ACLuckey** [SlimeKnights/TinkersConstruct#4370]
I can't craft or find the stencil table or pattern chest. I loaded up a creative single-player world and I could not craft or find them there either. Does anyone know what might be up?

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.0.55
* Mantle: 1.6.92
* Tinkers Construct: 3.0.2.96

**Comment by PrincessOfEvil** [comment]
They don't exist anymore. Part builder does everything you need.
