### ISSUE TITLE
Rename "Cobalt Ore" to "Nether Cobalt Ore"

### ISSUE THREAD

**Issue by muzikbike** [SlimeKnights/TinkersConstruct#4371]
This is pretty minor, but all other vanilla ores which are visually embedded inside netherrack are prefixed with "Nether" (and, in 1.17+, everything inside deepslate with "Deepslate"), so it would make sense for cobalt to follow suit here.

**Comment by KnightMiner** [comment]
Changed in 3.0.3.109
