### ISSUE TITLE
Temp requirements for Steel Melting

### ISSUE THREAD

**Issue by denniswed** [SlimeKnights/TinkersConstruct#4372]
**Describe the solution you'd like**
I don't agree with smelting steel requiring blaze fuel vs lava. Seems ironic that i can't smelt steel dust with lava in the smeltery but can melt it into bars using coal in a standard furnace. I personally would prefer there not be temperature distinguishment with the smeltery. If there is a way to increase the smeltery temp outside of an obscure blaze fuel then would be happy to do that, but right now it seems extremely impractical to have to resort to blaze fuel vs lava. 

**Describe alternatives you've considered**
Alternatives could be ways of increasing the temp like adding more stacked lava  tanks.

**Additional context**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.92
* Tinkers Construct:  3.0.2.96

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"
No idea where the roadmap is, so sincere apologies i can't verify.

**Comment by KnightMiner** [comment]
This is already fixed, just not released. Waiting on a few things for the next alpha.

Commit for reference: 3a9ae12

**Comment by denniswed** [comment]
Thank you for the update. I appreciate it.

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.109
