### ISSUE TITLE
Reinforments are bugged?

### ISSUE THREAD

**Issue by ThreadedSkurt** [SlimeKnights/TinkersConstruct#4373]
I got a Rose gold picaxe with Reinforment (V / 5) and still takes durability both with a excuvation mod and diging normaly. Aka vanila breaking blocks

1.16.5
* Minecraft: Lidgit?
* Forge: 36.1.4 with Curseforge patches 
* Mantle: Mantle by Mdiyo
* Tinkers Construct: 1.16.5-3.0.2.96.jar

Phase 1 is first release and it says that its a implimented modifier?

**As far as i am concerned i dont have any mods that conflict with tinkers.**
Mod list
Jei
Jer
Tinkers construction 1.16.5-3.0.2.96
Mantle by @Mdiyo
Building gadgets
Craete 1.16.5
Hwyla       Forge ver
AutoReglib
achitechury api By @shedaniel
Ore excavation  By @funwayguy
Journeymap
simple stroage network
Iron chests
Fast leaf decay By @olafskiii
quark
quark oddities
mouse tweaks
Carry on
Cyclic
Mrcrayfish furniture mod
mcaws windows
macaws roofs
Ftb gui
Ftb backups
Chisel N bits
And some other mods i either added or Just didnt have enough effort off typing out because its not about me its about a modifier that dont seem to work?

**Comment by ThreadedSkurt** [comment]
Please i know this is a bit rushed... But update the wikis and give a in game explaination! Thanks sorry if this is a problem of people asking the same thing but old tinkers was like this and most just want the old so they can replay tinkers with newer versions of minecraft Because of mods like create

**Comment by KnightMiner** [comment]
This is an alpha. Want documentation? Wait for the full release.
