### ISSUE TITLE
Config to un-nerf slime sling

### ISSUE THREAD

**Issue by McHaunty** [SlimeKnights/TinkersConstruct#4376]
There should be a config option to revert the slime sling back to its unnerfed version.

Or maybe a config to edit the properties of the slime sling, like durability and launching power

**Comment by KnightMiner** [comment]
Nerfed? The earth slime sling is identical to 1.12, there was no nerf. The other slime slings (besides earth) are different than earth slime slings, each with advantages of their own, but if you want 1.12 slime slings they literally still exist.
