### ISSUE TITLE
Player Crash upon joining server

### ISSUE THREAD

**Issue by MrVauxs** [SlimeKnights/TinkersConstruct#4377]
**Issue description:** As the title suggests. The crash tends to be immediate after joining but sometimes the player can stay for a couple of seconds before, again, crashing.

**If crashed, link to crash report (use a site such as pastebin):** https://pastebin.com/raw/wDHZebPA

**Versions:**
* Minecraft: 1.16.5
* Forge: 1.16.5-36.1.0
* Mantle: .16.5-1.6.92
* Tinkers Construct: 1.16.5-3.0.3.109

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Could not find anything similar, given the newest update also has been just released.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Unable to test that at the time, will come later if necessary.

**Comment by KnightMiner** [comment]
Sounds like someone broke tags in a dumb way. This might be fixed with b198764? Try again on build 111 on Curseforge.

**Comment by MrVauxs** [comment]
Yes, it has been fixed, sorry for not saying that sooner.
