### ISSUE TITLE
Crash by IllegalArgumentException

### ISSUE THREAD

**Issue by keriotisna** [SlimeKnights/TinkersConstruct#4378]
**Issue description:**
Crashed by IllegalArgumentException from tconstruct:casting_table. This usually happens when I have a casting table filling/cooling a cast automatically by redstone, and might be caused when the chunks containing these blocks are loaded/unloaded.
**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/vKze9Dya
**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.16.5-1.6.92
* Tinkers Construct: 1.16.5-3.0.3.109

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Haven't seen anything like this before on either page
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes, replicated with fresh install of Tinkers Construct and Mantle.

**Comment by KnightMiner** [comment]
Fixed by 7229f1b, in build 3.0.3.111
