### ISSUE TITLE
[Suggestion] Casting molten magma cream into cobblestone produces magmatic stone (BYG)

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#4379]
**Is your idea related to a problem? Please describe.**

**Describe the solution you'd like**
This seems like a great way to make a nice block from Oh The Biomes You'll Go renewable: casting magma cream into a cobblestone block in a casting basin turns it into magmatic stone.

**Describe alternatives you've considered**
Create may also be able to handle this by compacting magma cream into cobblestone, though Tinker's Construct has a much better way of facilitating it.

**Additional context**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.88
* Tinkers Construct: 3.0.2.84

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
This seems obscure enough to not have a mention elsewhere!

**Comment by KnightMiner** [comment]
I have no plans to make a block from another mod renewable. They are free to add the recipe themselves, but there is too high of a risk of messing with mod balance if we start adding random recipes for other mods blocks.

You are free to add this with a datapack yourself.

**Comment by MarioSMB** [comment]
Fair enough, it is probably better done on their end, I've made an issue on their tracker for it.  
I have already made a data pack for this as well, but would much rather see native support for such interactions.
