### ISSUE TITLE
Slime boots in curio slot?

### ISSUE THREAD

**Issue by tsheinen** [SlimeKnights/TinkersConstruct#4380]
**Describe the solution you'd like**

I wear slime boots bc I love the bouncing but I would also like to armor up. I'm probably going to modify it for myself regardless, but if that is something you'd like I could put a little more effort into the modification (config options and such) and make a pull request. 

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
Doesn't seem to be -- I checked the 1.16 update project. I assume that is the roadmap?

**Comment by KnightMiner** [comment]
Tradeoffs are good. Want to armor up? You don't get slime boots. It's like elytra vs chest plate 

In any case, slime boots are getting merged into the armor design eventually, So I have no plans to overdevelop such a feature.
