### ISSUE TITLE
[1.16] Container filling recipe cleans NBT from items

### ISSUE THREAD

**Issue by PrincessOfEvil** [SlimeKnights/TinkersConstruct#4381]
**Issue description:**
Container filling recipe removes all NBT from its item output on craft, except for the fluid that's put into it.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.0.42
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.111

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Can confirm.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
A datapack and any modded container that stores things other than its fluid.

**Comment by PrincessOfEvil** [comment]
The base issue seems to be fixed, however, now the filling recipe has a corner case where it deletes the input item if it's not a container. It would also be nice if it checked if the container can actually take the liquid before the recipe logic runs, or if the recipe checked if the container can actually take the fluid to begin with.

**Comment by KnightMiner** [comment]
Recipe should properly check capacity and other details in 3.0.3.126.
