### ISSUE TITLE
speed bug using Slime boots, slime sling and dolphins grace

### ISSUE THREAD

**Issue by AlphaMode** [SlimeKnights/TinkersConstruct#4382]
**Issue description:**
If you use a slime sling and slime boots and get dolphins grace and use the slime sling you can go really fast

*Edit* You have to also be in water
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.0.42
* Mantle: 1.6.91
* Tinkers Construct: 3.0.3.DEV.a0d74a02a

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Can Confirm

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes

**Comment by KnightMiner** [comment]
There is no fabric version, at least we don't make it.

**Comment by Insane96** [comment]
Had the same problem, but without the slimesling, just with boots and Dolphin's Grace.

**Comment by 5thPrincexMike** [comment]
Similar problem with green slime boots, but I've got saturation effect

**Comment by KnightMiner** [comment]
3.3.2.324 most likely fixes this, please test to verify.

**Comment by KnightMiner** [comment]
Going to close as most likely fixed
