### ISSUE TITLE
The way to get molten blaze is too hard.

### ISSUE THREAD

**Issue by tim2350outlook** [SlimeKnights/TinkersConstruct#4384]
**Issue description:**
please create new ways to get the molten blaze.It's too hard for us to put a blaze mob into the smeltery.LOL
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:1.16.5
* Forge: 36.1.4
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.111

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by PrincessOfEvil** [comment]
Don't place blazes into a smeltery. Place a smeltery around a blaze spawner.

**Comment by tim2350outlook** [comment]
> Don't place blazes into a smeltery. Place a smeltery around a blaze spawner.





Oh. I haven't think about this ,nice idea, thanks

**Comment by KnightMiner** [comment]
Alternatively, fire resist potions and piggybackpack or ichor slime slings.
