### ISSUE TITLE
Last Localizations

### ISSUE THREAD

**Issue by TheVikingWarrior** [SlimeKnights/TinkersConstruct#439]
I've made a list of things that we can't translate yet:

  -Modifiers and ability: Reinforced, Unbreaking (Reinforced x10) and all the other Modifiers
  -Broken tools (Tooltip)
  -Tool Forge's GUI (Modifiers, tool description and tool title)
  -Armour and glove modifiers (both tooltips and Tool Forge's GUI)
  -Books
  -Slime King Tools (drop)
  -Creative Modifiers (Tooltips)
  -Waila
  -(Extra) Proper localization of the GUI names, in case the full name is too fit into the GUI, so you can shorten the text shown there

**Comment by bonii-xx** [comment]
As to my knowledge wo get everything know. :)
