### ISSUE TITLE
Optifine.

### ISSUE THREAD

**Issue by RafaelZ49** [SlimeKnights/TinkersConstruct#4390]
About optifine.

In my pc i dont no why, but optife works with tinkers, i just needed reinstall the mod, is just that.

Versions:
Minecraft:1.16.5
Forge: 36.1.0
Mantle:1.6.92
Tinkers Construct: 3.0.3.111

**Comment by PrincessOfEvil** [comment]
Optifine's ability to work greatly shifts with your CPU and GPU. It has like fifty code paths.

**Comment by KnightMiner** [comment]
How is this a bug? We do not support Optifine. That does not mean Optifine works or does not work, that means when it breaks things (and I mean when), we will not add special patches that only benefit optifine.
