### ISSUE TITLE
Stencil Table Craft 

### ISSUE THREAD

**Issue by danielss24** [SlimeKnights/TinkersConstruct#4391]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: Mantle-1.16.5-1.6.92.jar
* Tinkers Construct: 1.16.5-3.0.3.111

Cant craft patterns cause Stencil Table craft is not display, cant craft it, any solutions to create the patterns?

**Comment by Insane96** [comment]
Stencil Table was removed. There's only the Part Builder.
Please take a look here: https://github.com/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3

**Comment by castilio20** [comment]
this should be a question on discord not a issue on github

**Comment by KnightMiner** [comment]
There is a reason the new issue button links you to the "Whats new" page. So you read it before making an issue. Notably issues about missing content
