### ISSUE TITLE
[1.16.5] Extra reach distance does not work on mobs

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#4392]
**Issue description:**
The Reach ability, an ability that increases the range of TCon tools being able to target both blocks and mobs, currently does not function against mobs. The same goes for tools that have a +reach distance stat by default, such as broadswords and cleavers.

Edit: extra reach distance seems to [work as intended](https://youtu.be/DTDRvWA9_B8) in creative, just not survival.

[Video Demostration](https://youtu.be/MPa5RBE0Kio)

**Versions:**
* Minecraft: 1.16.5
* Forge: 3.1.0
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.111

This issue is not mentioned on the roadmap or "What's New?"

This issue is able to be reported with only TCon, Mantle, and Hwyla (for easier testing).

**Comment by KnightMiner** [comment]
Related: MinecraftForge/MinecraftForge#4736. I think Forge tried to fix this bug before, but it never got merged. Guess I never realized it did not work on entities in testing (was mainly focused on blocks).

Might need a Forge PR to fix, might be possible to fix on our side.

**Comment by KnightMiner** [comment]
MinecraftForge/MinecraftForge#7808 was recently opened, which addresses this.

**Comment by KnightMiner** [comment]
For the record, my current plan for this is to implement a second modifier, range, for attack distance given it seems forge is planning on two attributes.

**Comment by KnightMiner** [comment]
3.5.1.31 for 1.18.2 adds mob support to the reach modifier.
