### ISSUE TITLE
Latest version of forge says tinkers construct is for an older version of forge

### ISSUE THREAD

**Issue by BarltonCanks** [SlimeKnights/TinkersConstruct#4394]
**Issue description:**
After loading forge it just says TK is not supported as its for an older version of forge. Please help.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.4
* Forge: 35.1.37
* Mantle: ??
* Tinkers Construct: 1.12.2

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Couldn't see the issue in the whats new
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Let me get this straight. You download the **1.12** version of Tinkers Construct, and tried running it on **1.16**, and are wondering why its not working. And you ignored the 1.16 version of Tinkers Construct because?

If you want to play on 1.16, download a 1.16 build.

**Comment by BarltonCanks** [comment]
Yeah that makes sense now, I had no idea what I was doing but thanks.
