### ISSUE TITLE
[1.16.5] "Materials and You" not exhibiting proper book behavior

### ISSUE THREAD

**Issue by Seth0067** [SlimeKnights/TinkersConstruct#4395]
The TC guidebook, "Materials and You" is (in the current build) not behaving like a book.  I can not place it in an Akashic Tome, nor in a modded bookshelf (The mod Builders Additions provides a bookshelf that contains an inventory like Bibliocraft did before it).

Minecraft: 1.16.5
Forge: 36.1.4
Mantle: 1.6.92
Tinkers Construct: 3.0.3.111

**Confirm below that this issue is not covered on the roadmap or "What's New?"** 
Didnt see this specific problem, but I understand this is an Alpha so this may simply not be done yet.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
See notes above inre: Akashic Tome and Builder's Additions.

**Comment by KnightMiner** [comment]
I have tagged all my books under the item tag `forge:books/guide` and `forge:books`. Suggest to the other mods they should be using a tag check instead of a registry ID string match, way too many false positives in experience with registry ID check

**Comment by KnightMiner** [comment]
Closing as a bug in other mods, if anyone has this issue yell at the offending mod for reading registry names instead of using tags
