### ISSUE TITLE
Players Still Start With Book

### ISSUE THREAD

**Issue by GittyUpMyHorsey** [SlimeKnights/TinkersConstruct#4398]
**Issue description:**
When I change the config option to not have new players start with the book, they still start with it.

**If crashed, link to crash report (use a site such as pastebin):**
No crash

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 
* Tinkers Construct: 3.0.3.111

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
No

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes

**Comment by KnightMiner** [comment]
Can't reproduce. Please give more information. For instance, are you running on a server, or single player? If on a server, there is a chance your player's config is out of sync.

**Comment by KnightMiner** [comment]
Closing for lack of response as I cannot reproduce this issue. Give me more information if this bug is still happening for you.
