### ISSUE TITLE
Crafting Station doesn't keep its material when broken

### ISSUE THREAD

**Issue by PrincessOfEvil** [SlimeKnights/TinkersConstruct#4400]
**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.2
* Mantle: .92
* Tinkers Construct: .118

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Can confirm.

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.126.
