### ISSUE TITLE
slime tree trunks will not grow through slimy leaves

### ISSUE THREAD

**Issue by Random832** [SlimeKnights/TinkersConstruct#4401]
**Issue description:**
As described in the title: when growing a slime tree next to an existing slime tree, its trunk has a giant gap in the middle where the existing leaves were

**If crashed, link to crash report (use a site such as pastebin):**
not crashed

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.0.42
* Mantle: 1.6.91
* Tinkers Construct: 3.0.3.DEV.2990f3a5e

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
This is not a roadmap feature issue.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Occurred in the dev environment, so the only other suspects are TOP and JEI. I guess I *could* remove them to double check, but it seems unlikely.

**Comment by Random832** [comment]
oops, I wasn't paying attention to what my farm was doing as it grew

**Comment by KnightMiner** [comment]
Probably fixed in 3.0.3.126.
