### ISSUE TITLE
Slimy Grass breaks under Snow

### ISSUE THREAD

**Issue by ABrokenPearl** [SlimeKnights/TinkersConstruct#4403]
this isn't necessarily a problem, but when the slimy grass turns into slimy dirt due to snow, it gets rid of the grass snow texture on the side of the block; making a hard line between the two blocks. But, the team could simply make the snow layer(s) not destroy the slimy grass block to fix this.

![image](https://user-images.githubusercontent.com/83144059/115975447-6bc1bb00-a52a-11eb-80f3-945d275cf0e3.png)

* Minecraft: 1.16
* Forge: 36.1.12
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.111

Its not shown on the roadmap, and as a very small fix it probably wouldn't.

This doesn't involve any other mods so it should be fine to fix.

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.136
