### ISSUE TITLE
Smelting crashes the game (1.16)

### ISSUE THREAD

**Issue by Anhilowasntavailabewhotookit** [SlimeKnights/TinkersConstruct#4404]
amazing mod, but i literally cant smelt anything without the game crashing.  it appears to be an issue when going into the gui, but it also just does it randomly.
i dont have logs or anything, weird glitch with my launcher, so i cant have any of that information.

**Comment by ShinyPorygon** [comment]
#4316 This is caused by optifine which is not supported. Removing optifine will fix it.

**Comment by KnightMiner** [comment]
Deleting the issue template does not prevent you from needing to add a crash report for crashes. Without a crash report this issue is useless to us. If your launcher does not give you logs, get a non-broken launcher.
