### ISSUE TITLE
Nether Slime Islands Arn't spawning with Oh The Biomes You'll Go Generatoin!

### ISSUE THREAD

**Issue by Kqmu** [SlimeKnights/TinkersConstruct#4405]
**Issue description:**
Nether slime islands Arn't spawning in "Oh the Biome You'll Go" Generation
( I seen a issue opened about the same issue for Biomes O' Plenty but I didnt see one for BYG, so I opened one ) 

**Versions:** 1.16.5
* Minecraft: 1.16.5
* Forge:  36.1.2
* Mantle: 1.6.92
* Tinkers Construct:  TConstruct-1.16.5-3.0.2.96

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Probably same issue as #4368. I'll leave open as its easier to track separately.

**Comment by KnightMiner** [comment]
Should be fixed in 3.0.3.144

**Comment by pm065** [comment]
I'm not sure this is resolved. /locate tconstruct:nether_slime_island in a BYG nether world produces coordinates, but when I teleport to them, mining vertically both ways I cannot find them. I've tried several times, this is me falling down a hole from the top to the bottom of the world in a spot where /locate claims there is an island: https://i.gyazo.com/e26b9f13915d77d2020e37f7facd5cc0.mp4

**Comment by KnightMiner** [comment]
There are a few conditions to island spawning that locate does not catch. The islands must spawn above the lava ocean, if you see no island running locate a second time usually finds a new spot. You are probably getting unlucky, or BYG removes too many lava oceans. Try turning up the island frequency in the config.
