### ISSUE TITLE
[1.16.5] Hammers can break indestructible blocks in their AOE

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#4406]
**Issue description:**
Hammers are capable of breaking unbreakable blocks, such as Bedrock or End Portal Frames, when breaking other breakable blocks (example: stone) within the AOE range. This may or may not go with Excavators too, but I can't think of indestructible blocks that shovels would be "effective" against. This issue also wasn't present in older 1.16.5 alphas of the mod.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.126

This issue is not on the Roadmap or "What's New?"

This issue can be reproduced with only Tinkers' Construct.

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.136
