### ISSUE TITLE
Tinker's construct tools can crit regardless of attack cooldown

### ISSUE THREAD

**Issue by DrFlavin** [SlimeKnights/TinkersConstruct#4407]
Mod versions:
Forge:1.16.5-36.1.13
Mantle:1.16.5-1.6.92
Tinkers Construct:1.16.5-3.0.3.126

Mods other than Tinker's Installed:
JEI & Torohealthbars, both at the latest versions.

Title says it all, really. Tinker's construct tool's ignore Minecraft's critical hit rules,
allowing them to crit whenever instead of only when the tool is fully deployed.
This bug applies to all tools but is most noticeable with the hammer.
This isn't that big of a deal for most tools. But combined with the already overtuned cleaver,
it can be pushed to smash 4 cloud levels of broken, outputting damage nearly equivalent to the hammer
at the speed of a broadsword. so like, yeah. Kinda bust(er sword)ed

**Comment by DrFlavin** [comment]
_Man_, that last sentence was kinda forced, hastily _constucted_, if you will.
All jokes aside I Really like the changes made in Tinker's Construct 3,
You guys are doing a great job with it!
Anyways, Imma head out.

**Comment by KnightMiner** [comment]
Leave this open until we release an alpha with the fix.

**Comment by DrFlavin** [comment]
Ah, Oops. Okay.

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.136
