### ISSUE TITLE
Brass is uncraftable

### ISSUE THREAD

**Issue by smallone369** [SlimeKnights/TinkersConstruct#4408]
when trying to create brass I learned tin was not anywhere in the mod, not in the JEI, not in the creative menu, and not in the world except for a molten bucket of tin. I added a mod with tin in it, and the smeltery did turn it into molten tin but it would not alloy with copper to create brass. If there is a mod to fix this it please let me know, and if I'm just being dumb and this project is far from finished please let me know.

**Comment by KnightMiner** [comment]
First off, brass is copper and zinc. Copper and tin is bronze. Second off, the compat recipes require that bronze exists as well, there are mods that add tin without bronze, rarely, so possible you have one of those cases. In any case, this sounds like something you should debug on discord. Once we determine if this is an issue, you can make one with the proper issue template.
