### ISSUE TITLE
Broadsword, katana, etc. dont exist

### ISSUE THREAD

**Issue by smallone369** [SlimeKnights/TinkersConstruct#4409]
**Issue description:**
inside of the tool builder, there are only options for the stock tools and the hoe axe thing
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:1.16.5
* Forge: 36.1.0
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.126

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
yes
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
yes

**Comment by KnightMiner** [comment]
Broad sword exists. Look again. For the remainder, read "Whats New" as you lied by saying you have read. It talks about which weapons were removed since 1.12.
