### ISSUE TITLE
slimeknight error causing me to crash while loading in

### ISSUE THREAD

**Issue by pancakeceiling** [SlimeKnights/TinkersConstruct#4413]
I don't know if this issue has already been solved or what but I couldn't find anything about it. Whenever I try to load in minecraft it crashes a says java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo

pastebin https://pastebin.com/57yTK1dw hopefully it works now I set expiration date to 1 year

I have 
Minecraft: 1.12.2
Forge: 1.12.2-forge-14.23.5.2854
Mantle: 1.12-1.3.3.55
Tinkers Construct: 1.12.2-2.13.0.183

and its only with tinkers construct no other mod causes this problem

**Comment by StaticPH** [comment]
Your pastebin link is dead. Nothing we can do without more information.

**Comment by pancakeceiling** [comment]
I figured out what was wrong and fixed it

**Comment by bogboybingles** [comment]
how did you fix it, i have the same problem

**Comment by KnightMiner** [comment]
Looks like a duplicate of #4441. Fix it by removing LuCraft or yelling at them to fix their broken mod, I am pretty tired of dealing with their bug.

**Comment by MistikCodes** [comment]
have the same issue but on 1.18.2 and not with LuCraft
"Failed to create mod instance. ModID: tconstruct, class slimeknights.tconstruct.TConstruct"
https://pastebin.com/wLY3B6NQ
for crash log
