### ISSUE TITLE
server crashes when trying to add a protection type to a voodoo puppet

### ISSUE THREAD

**Issue by zaze06** [SlimeKnights/TinkersConstruct#4417]
**Issue description:**
Server and Client (only if its a sigel player world) coaches when I try to add a protection type to a voodoo puppet from the mod Corail Tombstone

**If crashed, link to crash report (use a site such as pastebin):**
https://gist.github.com/zaze06/1bf7d10ba1a5a5c43b144133eb00be38

**Versions:**
* Minecraft: 1.16
* Forge: 36.1.0
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.126

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
pretty sure it isn't in the roadmap when its a crash caused by anaphor mod combined whit tinkers

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
no I can't just have tinker because its related to another mod
mod list: https://gist.github.com/zaze06/b311122590e12ba400a46f405cf90a8e

**Comment by PrincessOfEvil** [comment]
This happens cause the CraftingInventoryWrapper never gets its eventHandler set, which is technically no one's bug cause it's private in vanilla and is only used in like three methods and thus one probably shouldn't expect it to exist.

**Comment by zaze06** [comment]
ok is it a problem whit tinkers or what?

**Comment by KnightMiner** [comment]
I would blame Corail Tombstone for this one. Forge provides a method for retriving the player at a crafting table (in ForgeHooks), but they are instead reading a private field that we override the need for. Report this issue to them and tell them to use `ForgeHooks::getCraftingPlayer`.

Will still be null during result calculation though are our crafting table is not player sensitive (not sure there is a good way to obtain the player), they need to include null checks probably.

**Comment by KnightMiner** [comment]
Fixed in Corail Tombstone and in 983be37 (released in 3.0.3.144)

For reference, issue on their tracker: https://www.curseforge.com/minecraft/mc-mods/corail-tombstone/issues/12
