### ISSUE TITLE
Molten Blaze recepie

### ISSUE THREAD

**Issue by DangerTheRealOne** [SlimeKnights/TinkersConstruct#4419]
Many of the late-game materials require the smeltery temperature to be over 1000 to get melted. Molten Blaze allows that, but it is very hideous to make. You have to get a living Blaze and melt it in a smeltery. To do this you have to lead the Blaze to your smeltery, which would most probably be in the overworld, which is in my opinion pretty hard, if not impossible

My solution is to make the player able to do the same thing using Blaze Rods or Blaze Powder.

Maybe instead of melting Blaze Rods or Powder make an item that is dropped from a Blaze but is a bit rarer than Rods that you can melt into Molten Blaze.

Minecraft: 1.16.5
Forge: 36.1.13
Mantle: 1.6.92
Tinkers Construct: 3.0.3.126

I made the research and I heavily belive there is no other way to get Molten Blaze.

**Comment by PrincessOfEvil** [comment]
Make a smeltery under a Blaze spawner.

**Comment by DangerTheRealOne** [comment]
I aleready did that, you have to push them in and it is still very hard to do.

**Comment by DangerTheRealOne** [comment]
> Make a smeltery under a Blaze spawner.

You have to push them in, and it is still hard.

**Comment by DangerTheRealOne** [comment]
And the guy just closed the issue like nothing happened and said "Make a smeltery under a Blaze spawner.". *Slow claps*

I love this community.

**Comment by ShinyPorygon** [comment]
Perhaps if you are having troubles you should come ask in the discord. Many people are doing it without troubles. Furthermore blaze rods or powder won't be added as it will be too easy.
