### ISSUE TITLE
Molten Blaze Recepie "Reposted"

### ISSUE THREAD

**Issue by DangerTheRealOne** [SlimeKnights/TinkersConstruct#4420]
A... moderator?.. closed my earlyer post about the same topic and all they did is just saying "Make a smeltery under a blaze spawner", which didn't help at all and does not adress my point. I want them to concider this more.

Many of the late-game materials require the smeltery temperature to be over 1000 to get melted. Molten Blaze allows that, but it is very hideous to make. You have to get a living Blaze and melt it in a smeltery. To do this you have to lead the Blaze to your smeltery, which would most probably be in the overworld, which is in my opinion pretty hard, if not impossible

My solution is to make the player able to do the same thing using Blaze Rods or Blaze Powder.

Maybe instead of melting Blaze Rods or Powder make an item that is dropped from a Blaze but is a bit rarer than Rods that you can melt into Molten Blaze.

Minecraft: 1.16.5
Forge: 36.1.13
Mantle: 1.6.92
Tinkers Construct: 3.0.3.126

I made the research and I heavily belive there is no other way to get Molten Blaze.

**Comment by ShinyPorygon** [comment]
Perhaps if you are having troubles you should come ask in the discord. Many people are doing it without troubles. Furthermore blaze rods or powder won't be added as it will be too easy.

You can build a smeltery under the spawner in the nether. It's not impossible or super hard.

**Comment by DangerTheRealOne** [comment]
> Perhaps if you are having troubles you should come ask in the discord. Many people are doing it without troubles. Furthermore blaze rods or powder won't be added as it will be too easy.
> 
> You can build a smeltery under the spawner in the nether. It's not impossible or super hard.

What about the rare drop I mentioned?

**Comment by ShinyPorygon** [comment]
That isn't the point of molten blaze. If you want to melt something to turn an item into molten blaze you can add it via datapack.

**Comment by DangerTheRealOne** [comment]
> That isn't the point of molten blaze. If you want to melt something to turn an item into molten blaze you can add it via datapack.

What datapack? Do I make it myself?

**Comment by PrincessOfEvil** [comment]
![image](https://user-images.githubusercontent.com/2369751/116565082-0ccac000-a8f5-11eb-8387-484bd4cb67ff.png)
Making a working blaze farm is very easy. Adding any rare drops would make the whole mechanic irrelevant.

**Comment by KnightMiner** [comment]
For the record, I (a developer of the mod) agree with the moderator. This is not as painful as you make it out to be. I have plans for a second way to get the fluid, but it won't be as trivial as you are suggestion. I won't get rid of an interesting mechanic because you want a boring or a purely RNG one.

Join our discord any talk about this instead of spamming our issue tracker with the same thing multiple times.
