### ISSUE TITLE
[1.16] Cleaver is about 50% faster than it should be

### ISSUE THREAD

**Issue by PrincessOfEvil** [SlimeKnights/TinkersConstruct#4421]
Right now, the Cleaver has the attack speed of 1.2. This is entirely too fast for its damage multiplier and makes it strictly better than broadsword. A proposed better speed would be 0.8.

**Versions:**
* Minecraft: 1.16.5
* Mantle: .92
* Tinkers Construct: .127

**Comment by mDiyo** [comment]
Some of the tools feel kind of weird in their use as weapons. Most seem more-or-less okay, with the main exception of people absolutely destroying everything in their paths with cleavers. Materials play a large role in the way weapons work and may need evaluated separately. 

Tool data gathered from [ToolBaseStatDefinitions](https://github.com/SlimeKnights/TinkersConstruct/blob/1.16/src/main/java/slimeknights/tconstruct/tools/ToolBaseStatDefinitions.java). Proposed changes are in bold

Pickaxe
Attack Speed: 1.2
Attack Multiplier: 1x
Base Damage: 1
Ability: None

Sledge Hammer
**Attack Speed: 0.7** (was 0.5)
Attack Multiplier: 1.5x
Base Damage: 5

Vein Hammer
Attack Speed: 1.0
Attack Multiplier: 1.25x
**Base Damage: 3** (was 2)

Mattock
Attack Speed: 1.0
Attack Multiplier: 1x
Base Damage: 1.5

Excavator
Attack Speed: 0.7
Attack Multiplier: 1.25x
Base Damage: 1.5

Hand Axe
Attack Speed: 0.9
Attack Multiplier: 1x
Base Damage: 6

Broad Axe
Attack Speed: 0.6
Attack Multiplier: 2x
Base Damage: 2

Kama
**Attack Speed: 2.0** (was 1.3)
Attack Multiplier: 1x
**Base Damage: -1** (was 1)

Scythe
Attack Speed: 0.8
Attack Multiplier: 1.25x
Base Damage: 1

Sword
Attack Speed: 1.6
Attack Multiplier: 1x
Base Damage: 3

Cleaver
**Attack Speed: 0.8** (was 1.2)
Attack Multiplier: 1.75x
Base Damage: 3

**Comment by PrincessOfEvil** [comment]
Kama would need a negative damage multiplier but i agree otherwise.

**Comment by KnightMiner** [comment]
I don't like making the cleaver the same attack speed as the broad axe. Most of the time the broad axe will be higher damage, so that takes away the cleavers advantage. 0.8 is probably a better attack speed for it, or even 0.9.

Negative damage bonuses are not possible as the hand has a bonus of 0, and wood has a value of 0, so at that point a wooden kama does less than fist damage. 0 is as low as we can go and that's garbage. A damage multiplier that is less than 1 is probably the better option here.

**Comment by mDiyo** [comment]
I swear I meant to put in 0.8 speed for the cleaver, as exactly half the speed of a sword makes the most sense. I blame my brain in thinking that 0.6 is half of 1.6 here.

**Comment by KnightMiner** [comment]
Makes me wonder if the broad axe should be slower. Maybe give it speed closer to 0.4 to 0.5, half the hand axe.

**Comment by mDiyo** [comment]
The broad axe is already as slow as a reasonable tool can be. Any slower and the tools become unwieldly from a control standpoint. The sledge hammer hangs out offscreen just a biiiiiit too long to make it feel useful as a weapon, hence why it should get a boost up to 0.6 at least.

All of these tool stats will need re-evaluated when weapon based abilities become parts of the tools, like the sledge hammer doing bonus damage vs undead. The tools feel more or less like reskins of each other currently.
