### ISSUE TITLE
the ingot cast wrong

### ISSUE THREAD

**Issue by RaziJemni** [SlimeKnights/TinkersConstruct#4423]
i made a small server with create mod and tconstuct
so when i tried to cast some copper block it came as iron block
it showed the fluid like its was copper but then got iron block
i tried to get some bronze with copper and glass i think
i cast it and got iron block
i tried making brass from create mod and use ingot casting plate but i got copper ingot instead of brass
any reason for these
tc mod 3.0.2.96 but i didn't see any fix in the change-log of later updates
i have some optimization mods like you see in this pics
https://i.imgur.com/SCwXkMD.png
mantle 1.6..92
forge 36.1.0
version 1.16.5

**Comment by KnightMiner** [comment]
Duplicate of #4283, search before you report issues. And ***never*** report issues using optimization mods without first testing without them.
