### ISSUE TITLE
Textless tooltip when hovering over "No stats" in book

### ISSUE THREAD

**Issue by aaronhowser1** [SlimeKnights/TinkersConstruct#4424]
**Issue description:**

It shows up when hovering over the whole line
![image](https://user-images.githubusercontent.com/15698722/116638484-0b68ba00-a92c-11eb-91ac-fa18de105c91.png)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: Mantle-1.16.5-1.6.92
* Tinkers Construct: TConstruct-1.16.5-3.0.3.126

**Comment by ShinyPorygon** [comment]
Known bug! Current priority is getting the books out then worrying about weird stuff like that (:

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.136
