### ISSUE TITLE
Smeltery not Hot Enough

### ISSUE THREAD

**Issue by Logics2996** [SlimeKnights/TinkersConstruct#4425]
**Issue description:**

im trying to make a manyullyn tool part on the smeltery, it says that i need more heat to smelt this item, how do i get more heat into the smeltery
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
![gferf](https://user-images.githubusercontent.com/83439271/116709515-a7e09a00-a9c8-11eb-9f9e-385e0a3615b7.png)

* Minecraft:
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by PrincessOfEvil** [comment]
You need to use molten blaze. It's created by melting live blazes in the smeltery.

**Comment by Logics2996** [comment]
oh thank you, i will try that

**Comment by ShinyPorygon** [comment]
This was covered on the what's new it asked you if you read in the template.

**Comment by KnightMiner** [comment]
To quote "What's New":

> Molten Blaze is available from absorbing down blazes, granting up to 1500 C.

Follow the issue template when making new issues, do not ignore it
