### ISSUE TITLE
No drying rack?

### ISSUE THREAD

**Issue by BellaTheAlphaWolf** [SlimeKnights/TinkersConstruct#4426]
Well, I'm dumb, that was completely on me, but thank you guys

**Comment by ShinyPorygon** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3

The issue tracker asks if you read what's new which you deleted. Don't delete it and read it.

**Comment by KnightMiner** [comment]
Deleting the issue template is not an excuse for not reading or following it. The answer to your questions would have been revealed if you followed the issue template.
