### ISSUE TITLE
Slime island generate above 255 build limit and got cut

### ISSUE THREAD

**Issue by foxwhite25** [SlimeKnights/TinkersConstruct#4428]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):** Not crashed

**Versions:**
* Minecraft:1.16.5
* Forge: 36.1.4
* Mantle: Mantle-1.16.5-1.6.92
* Tinkers Construct: TConstruct-1.16.5-3.0.3.126

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Yes
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes , I dont know the probability but its there
![图片](https://user-images.githubusercontent.com/39846845/116806095-63d2ce00-ab5d-11eb-97b9-9506d3057344.png)
![图片](https://user-images.githubusercontent.com/39846845/116806107-73521700-ab5d-11eb-8b2d-2888d66754f8.png)

**Comment by embeddedt** [comment]
Can you provide the seed? That will make it easier for devs to reproduce this when testing a fix.

**Comment by foxwhite25** [comment]
> Can you provide the seed? That will make it easier for devs to reproduce this when testing a fix.

Its in a modpack called seaopoils and you cant really set seed for it , I can provide a world download tho

**Comment by embeddedt** [comment]
Based on other issues, this will most likely need to be reproduced with just Tinkers Construct and Mantle if it's going to be fixed. Modpacks are extremely difficult to test fixes in as far as I know.

EDIT: Is there a possibility that [this line](https://github.com/SlimeKnights/TinkersConstruct/blob/72f3d1132caf1a5ecc04f549ed5a32680a3f157f/src/main/java/slimeknights/tconstruct/world/worldgen/islands/overworld/OverworldSlimeIslandStructure.java#L85) is the culprit?

**Comment by KnightMiner** [comment]
IIRC, slime islands generate a certain number of blocks above the surface, with some random height. Possible the reporter's modpack makes the surface higher than we expect, normally we have about 200 blocks of freedom. Worth adding a max height for the islands from that line though.

**Comment by KnightMiner** [comment]
Fixed in 3.1.1.252
