### ISSUE TITLE
mistakes and incorrect information in the Materials and You book

### ISSUE THREAD

**Issue by Kodi4444** [SlimeKnights/TinkersConstruct#4430]
**Issue description:**
in the Materials and You book, I found a few mistakes and incorrect information.
the Hatchet page renamed to Pickaxe needs to be replaced with the hand axe information.
![image](https://user-images.githubusercontent.com/26844364/116846883-9523bc00-aba6-11eb-8ded-e5b8ebaf9d47.png)

and the information about the Mattock and the Kama need to be updated to reflect the new changes to those tools. 

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.126

**Comment by PrincessOfEvil** [comment]
@ShinyPorygon

**Comment by KnightMiner** [comment]
No, not Shiny's fault. The updated book is not in an alpha yet. So yes, the current book is inaccurate and not done. Wait until the changelog says its updated.

**Comment by KnightMiner** [comment]
There is an actual book now in 3.0.3.136
