### ISSUE TITLE
Slime Boots stop working with Angel Ring

### ISSUE THREAD

**Issue by reckonedstormlight** [SlimeKnights/TinkersConstruct#4432]
When slime boots are equipped with any version of an angel ring also equipped, neither work (although you definitely don't take fall damage but bouncing definitely doesn't work)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 
* Tinkers Construct: 3.0.3.126
* Angel ring: the one by DenisMasterHerobrine version 1.3.3 but it also happens with any other kind of angel ring available for 1.16.5

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
confirmed

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Angel ring: the one by DenisMasterHerobrine version 1.3.3 but it also happens with any other kind of angel ring available for 1.16.5

They were working together just fine prior to my updating TC yesterday to the latest version

**Comment by KnightMiner** [comment]
"Other kind of angel rings" is vague and not useful. Exact mod names or the report is useless.

For DenisMasterHerobrine's mod, cross-report this issue to his tracker and link it here. Though odds are this is not possible to fix. Creative mode normally prevents fall damage so good chance that mod disables fall damage (no fall damage means no bounce)

**Comment by reckonedstormlight** [comment]
Angel Ring by DenisMasterHerobrine
AzureDooms Angel Ring by AzureDoomC

Those are the 2 available for forge and 1.16.5 and neither work. It was working fine before but now it's not.

I'll cross-report

**Comment by reckonedstormlight** [comment]
https://github.com/DenisMasterHerobrine/AngelRing/issues/12

**Comment by embeddedt** [comment]
As far as I know this behavior happens on 1.12 modpacks with creative flight as well - not sure this is a bug.
