### ISSUE TITLE
Unable to draw TC bows in survival mode

### ISSUE THREAD

**Issue by Rafcamora** [SlimeKnights/TinkersConstruct#4434]
**Issue description:**
I´m currently playing a 1.12.2 modpack called Fossilized and I´m unable to draw TC bows while in survival mode. I´ve tried having vanilla arrows as well as TC arrows in my inventory but neither did anything to fix it. I tried to use the same bow in creative mode and it worked, back in survival it didn´t again. I tried other worlds and restarting everything. I couldn´t find anything online about this and no one in the modpack discord knows anything either. I´m unsure if this is the correct place for this as it is in a modpack and it could maybe be a modconflict (but many others play it and no one has this issue. 
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 
* Tinkers Construct: 1.12.2-1.1.0

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
If you think this is a mod conflict, answer the last question. Report is useless to us without that answer

**Comment by KnightMiner** [comment]
Closing for lack of information. I have never seen this issue before, and you seem to assume its a mod conflict but gave no info about other mods, so nothing I can do.
