### ISSUE TITLE
Wrong amount of output

### ISSUE THREAD

**Issue by DreaminBoi** [SlimeKnights/TinkersConstruct#4435]
**Issue description:**
Wall crafted from seared cobblestone and seared bricks outputted the wrong amount, which is 4 instead of the usual amount of 6
<br>
**Seared Cobblestone**
![java_sFk6frHY1l](https://user-images.githubusercontent.com/39964470/116919263-38de9c00-ac7b-11eb-89b6-f85f21170636.png)
<br>
**Seared Brick**
![java_tycFiwznab](https://user-images.githubusercontent.com/39964470/116919455-7ba07400-ac7b-11eb-8345-2e6acbc4dcad.png)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.15
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.126

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Fixed in 3.0.3.136
