### ISSUE TITLE
Mod Loading Failure (Versioning)

### ISSUE THREAD

**Issue by Coraline77447** [SlimeKnights/TinkersConstruct#4440]
**Issue description:** 
It's telling me that I don't have the latest version of Tinkers' Construct when I have the latest version and the error message isn't telling me what the required version that I need in order to have both mods to load properly during mod loading. 
This issue might be on Walia Harvestability's end but that doesn't mean that I'll still open this issue with Tinkers' Construct since the error message is saying "tconstruct". 
That's all that I can explain since I don't know what else to explain about this since I don't know what's going on...
The last time I've played with both Tinkers' Construct and Walia Harvestability that they've worked before and now they don't work together....

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/ckzRJMzp

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.13
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.136

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I can confirm that it's not on the roadmap and not in "What's New?"

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Walia Harvestability

Screenshot:
![Screenshot (4)](https://user-images.githubusercontent.com/72243304/117246626-35bdea00-adfa-11eb-815d-fe1da845cffe.png)

**Comment by KnightMiner** [comment]
Update to the latest forge. If that does not fix your error, try removing Optifine. Forge recently changed how they do optional dependencies and I am going to guess optifine is broken with it. If this still happens on the latest forge without optifine, we can reopen.
