### ISSUE TITLE
Possibly missing config

### ISSUE THREAD

**Issue by xXPhinkXx** [SlimeKnights/TinkersConstruct#4442]
**I am a new modpack creator using the newest version of tinkers construct and can't seem to wrap my head around how to get the smeltery to even be craft-able. I've searched throughout my whole file and cannot find the config that fixes this. Please Help thank you:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 
* Mantle: newest
* Tinkers Construct: newest

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
First off, report 1.16 issues with the 1.16 template 

Second, actually use the template.

Third, have you never heard of JEI? JEI tells you how to craft things, go install it and look up the recipe

**Comment by xXPhinkXx** [comment]
I apologize for not following the template first time user but I DO have JEI and I was having issues with locating a config file which for some reason removes the smeltery controller from being craft able. Maybe someone else would be willing to help explain?

**Comment by KnightMiner** [comment]
There is no config file that removes the smeltery controller recipe. The recipe is just different from in 1.12. Thats why I say look in JEI, the recipe is shown in there.

**Comment by xXPhinkXx** [comment]
The Recipe for the version I am running literally tells me to put copper in a smeltery and that how I get the smeltery controller. Do I need to update it or something? When I look at the description it tells me that its disabled by default and that I change that using a config file I do not have. Was this maybe a bug and I need to update? Do you handle 1.16 side of things or do I need to try something else? Just trying to enjoy some craft man.

**Comment by StaticPH** [comment]
Have you tried making a Melter first? Making the Smeltery now requires the use of the more primitive Melter to, as the name implies, melt down the aforementioned copper.
