### ISSUE TITLE
[Bug] Copper ore RenderTypeLookup missing

### ISSUE THREAD

**Issue by anchorit3** [SlimeKnights/TinkersConstruct#4445]
Hi, 
first of all - sorry for my English.
From what I discovered Copper Ore can't be textured with overlay.

Basically, the problem was for me so strange because **Cobalt Ore** worked with _"cube_overlay_all"_  fine (all: _netherrack_ and overlay: _transparent cobalt_ore_) but **Copper Ore** not (all: _stone_ and overlay: _transparent copper_ore_)
So I cloned the repository and browsed code. 

### From my research and tests inside **WorldCientEvents.java** missing:
```java
  static void clientSetup(FMLClientSetupEvent event) {
    (...)
    // render types - ores
    RenderTypeLookup.setRenderLayer(TinkerWorld.copperOre.get(), cutoutMipped);
    (...)
  }
```

### Screenshots:

Behavior with release 3.0.3.144:
![image](https://user-images.githubusercontent.com/10498621/117535165-d5df6300-aff4-11eb-99c2-2d33ae900684.png)

Behavior after added missing line:
![image](https://user-images.githubusercontent.com/10498621/117535243-2787ed80-aff5-11eb-97b7-cb710d209100.png)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.126, 3.0.3.144 (so I expect in all previous where copper ore appeared)

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
Confirmed

**Comment by KnightMiner** [comment]
That's not our copper ore texture, that's a resource pack. If you tried the same thing on vanilla ores, you'd get the same issue. I honestly don't see much point changing the render type, you can just use a single layer texture for the ore in your pack.

The fact that cobalt.works is leftover legacy stuff and probably will get removed later.
