### ISSUE TITLE
Silky Jewel disappeared from most recent version

### ISSUE THREAD

**Issue by JadeKaiser** [SlimeKnights/TinkersConstruct#4449]
**Issue description:**
The Silky Jewel and Block of Silky Jewel items have disappeared from the most recent version of the 1.16 variant of the mod. They were there and useable in the prior version, but when I switched out for the newest version today, they had vanished from JEI. I suspect the disappearance may have had something to do with the change from crafting Silky Cloth with Rose Gold instead of with regular Gold.

Oddly enough, as I was also using the Block Armor mod in the playthrough where I first discovered this, the armor set coinciding with Blocks of Silky Jewel is still showing up in JEI, and selecting them does show them to be made from Blocks of Silky Jewel. However, the blocks themselves do not appear outside the crafting recipe, and if the intent was to change the texture of the jewel/blocks of jewel to match the new, Rose Gold-based color of the Silky Cloth, it seems to have failed because the one from before is what shows up.
**If crashed, link to crash report (use a site such as pastebin):**
No crash.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 1.16.5-1.6.92
* Tinkers Construct: 1.16.5-3.0.3.144

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
It is not covered by the roadmap, and is clearly an issue caused by recent tweaks to existing feature. Of course, it could just be a known thing where the item and block in question were disabled intentionally while new textures are being made, but I don't know that for sure so I decided to report it anyways.
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes, it can.

**Comment by KnightMiner** [comment]
This is not a bug, silky jewels are getting removed in the near future. For now they are just hidden. Look in JEI for the new silk touch recipe.

**Comment by JadeKaiser** [comment]
Alright, thank you very much. And thank you for your Extremely prompt response. Though may I ask, if silky jewels are being removed, is there going to be a new purpose for silky cloth? I don't see one on the roadmap, but the changed recipe implies that it's not just going away.

**Comment by KnightMiner** [comment]
Silk touch?

**Comment by JadeKaiser** [comment]
I should probably have said that I did check JEI with that possibility in mind, and couldn't find any sort of substitute. What's the name of the new variant, if you don't mind, because it doesn't seem to include any variant of the words "silk," "touch," "modifier," "ability," "soft," or a few other words that I thought might be involved in such a thing?

**Comment by JadeKaiser** [comment]
And using SIlky Cloth on its own doesn't seem to work.

**Comment by KnightMiner** [comment]
You do realize modifiers are a tab in JEI, right? They are like crafting recipes or furnace recipes. Not every modifier is a single item.

Look up usages of silky cloth in JEI

**Comment by JadeKaiser** [comment]
Are you perhaps using a JEI addon in addition to the baseline? Because that's not true of baseline as best I can tell, and there are several such addons to be found. The Tinkers'-specific one is only available for Tinkers' 1.12 ver.

**Comment by JadeKaiser** [comment]
Aha, I figured out what you were saying. A whole section of JEI functionality that I apparently just never noticed. So sorry for the bother, my bad.
