### ISSUE TITLE
Shift Clicking parts out of the Part Builder crashes client.

### ISSUE THREAD

**Issue by Veggetossj** [SlimeKnights/TinkersConstruct#4450]
When i tried to create a bunch of Stone Repair Kits for my Stone Pickaxe, I tried to Shift+Click them out of the Part Builder, yet that crashed my client. Restrarted Modpack, retried it with a Pickaxe Head, leaving 2 cobble in the Parts Builder, same thing happened.

https://pastebin.com/nQe7gkRM

**Versions:**
* Minecraft: 1.16.5
* Forge: Forge-36.1.16
* Mantle: -
* Tinkers Construct: TConstruct-1.16.5-3.0.3.144.jar

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Not that I can see.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
It might, havent tested it, was using a custom a custom modpack created by our community: https://www.curseforge.com/minecraft/modpacks/mhg/files

**Comment by KnightMiner** [comment]
Answer that last question again. The point is that tyoh reproduce this crash without 100 mods.

**Comment by Veggetossj** [comment]
Tested it in a singleplayer world with just TC and Mantle, worked fine. Might be a MP issue.

**Comment by G-Stav** [comment]
Had the same issue. Mods in common are

> AI improvements
> Akashic Tome
> Appleskin
> Astral Sorcery
> Autoreglib
> Baubley Heart Canisters
> Botania
> Citadel
> Cloth Config Api
> Clumps
> Cofh Core
> Collective
> Controlling
> Cooking for Blockheads
> Crafting Tweaks
> Crafttweaker
> Create
> Curios Api
> Default Options
> Dungeon Crawl
> Enchanted Book Redesign
> Enchantment Descriptions
> Ensorcellation
> Forge Endertech
> Ftb Chunks
> Ftb Essentials
> Ftb Library
> Ftb Quests
> Ice and Fire: Dragons
> Immersive Engineering
> Immersive Petroleum
> Integraed Crafting
> Integrated Dynamics
> Integrated NBT
> Integrated Tunnels
> Item Filters
> JEITweaker
> Just Enough Items
> Light Overlay
> Mantle
> More Dragon Eggs
> Moph-o-Tool
> Mouse Tweaks
> MythicBotany
> Natures Compass
> Pam's HarvestCraft 2 - Crops
> Pam's HarvestCraft 2 - Food Core
> Pam's HarvestCraft 2 - Food Extended
> Pam's HarvestCraft 2 - Trees
> Patchouli
> Placebo
> Polymorph
> Quark
> Quark Oddities
> Repurposed Structures
> Simply Jetpacks 2
> Spawner Bug Fix
> Tinkers Construct
> Toast Control

However this is where it get's strange. Tried to see which mod was causing it, adding 5-10 more to the list until the crash occured, and it never did. So I'm guessing that it's a config change we've both made that causes it?

**Comment by G-Stav** [comment]
Removing FastWorkbench Minus Replacement fixed it for me. Fast Furnace Minus Replacement was in Veggetossj's pack, maybe there is a common code between the mods that cause it?

**Comment by KnightMiner** [comment]
Closing as I cannot do anything about this issue when you require lists of 100+ mods to reproduce. Get me a list of 4 mods or less and I can look into it.
