### ISSUE TITLE
Multiple Modifiers from 1 Upgrade Enhancement

### ISSUE THREAD

**Issue by Pitti11** [SlimeKnights/TinkersConstruct#4451]
**Is your idea related to a problem? Please describe.**
I'd like to add an upgrade modifier recipe which adds two seperate modifiers at the same time, but that doesn't seem to be possible or even intended.

**Describe the solution you'd like**
A way for recipes to have multiple results like the options for requirement, maybe.

**Describe alternatives you've considered**
Or it could be added in code with an onCraft event in [Modifiers.java](https://github.com/SlimeKnights/TinkersConstruct/blob/1.16/src/main/java/slimeknights/tconstruct/library/modifiers/Modifier.java)

**Additional context**
How it is
![grafik](https://user-images.githubusercontent.com/43349907/117585717-2bf6f800-b114-11eb-8169-2fed8bc28c80.png)
How it could look like
![grafik](https://user-images.githubusercontent.com/43349907/117585741-44ffa900-b114-11eb-9ade-7b227efa4004.png)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.95
* Tinkers Construct: 3.0.3.144

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
Confirm

**Comment by KnightMiner** [comment]
This very much violates how modifier recipes work, it will not display well in JEI. Please explain why you need to be able to add multiple modifiers with one recipe.

**Comment by Pitti11** [comment]
Well the plan was to have an upgrade from x material also add the trait of x material to tools which aren't made from x and thus don't have the trait at all. Kinda like the upgrade would count as an extra part and therefore also provide the trait.
Is that a bad idea? Another way would be to add a new modifier which combines both functions of the trait and upgrade.

**Comment by KnightMiner** [comment]
Yeah, just add a modifier with both effects. If needed, you can use volatile mod data or `IModifierToolStack::getModifierLevel` to have them detect each other.

**Comment by Pitti11** [comment]
Well, thank you very much for answering.
I am now using the solution with 3 modifier recipes and two modifiers where i rename the upgrade modifier to "Upgrade + Trait" if the trait is not on the tool. And if the tool has the trait, they sense each other and display a correct level.
