### ISSUE TITLE
Pickaxe levels completely broken.

### ISSUE THREAD

**Issue by Swagbasket** [SlimeKnights/TinkersConstruct#4452]
Encountered in Enigmatica Expert 2 (which has never had problems before). I don't really know how to describe this issue because it seems to have no rhyme or reason. An iron pickaxe head can mine anything in the game at a low speed. Replacing the head changes what it can mine, but it does not match up to the WAILA mining level. Pickaxe heads also do not match the mining level that the final pickaxe has. This is gamebreaking

**Comment by ShinyPorygon** [comment]
Deleting the issue template is not an excuse for ignoring it. Open a new issue and actually follow the issue template, you left out vital information if we are to fix this.

**Comment by KnightMiner** [comment]
Going to close this per Shiny's comment. In my experience pickaxe levels work perfectly fine, if they are not showing right in WAILA thats probably a WAILA bug.

If you can provide more information, you can reopen and actually use the issue template.
