### ISSUE TITLE
bloodshroom planks

### ISSUE THREAD

**Issue by benbenlaw** [SlimeKnights/TinkersConstruct#4454]
**Is your idea related to a problem? Please describe.**
bloodshroom planks too bright
**Describe the solution you'd like**
reduced brightness
**Describe alternatives you've considered**
texture pack
**Additional context**
![image](https://user-images.githubusercontent.com/42780877/117662422-72416b00-b197-11eb-81bd-dab84dc9a8dd.png)

**Versions:** latest dev
* Minecraft: 1.16.5
* Forge:  36.1.16
* Mantle:  1.6.92
* Tinkers Construct:   3.0.3.144

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**

**Comment by KnightMiner** [comment]
They are supposed to be bright. All the slimy wood is bright, like the slimeballs. Want a darker red wood? Use crimson or acacia.
