### ISSUE TITLE
Killing Pigs should repair Pig iron

### ISSUE THREAD

**Issue by ShinyPorygon** [SlimeKnights/TinkersConstruct#4455]
**Is your idea related to a problem? Please describe.**
From a certain point of view everything is a problem. So no and yes ;P 
**Describe the solution you'd like**
With a pig iron tool killing a pig should repair the tool by 1 (or more)
**Describe alternatives you've considered**
Not killing a pig to repair it? Killing a cow to repair it? Repairing it normally?
**Additional context**
![image](https://user-images.githubusercontent.com/35193007/117671968-5cbc4900-b177-11eb-9313-5ae76d4367d8.png)
mDiyo said so
**Versions:**
* Minecraft:1.16.5
* Forge: 36.1.16
* Mantle: 1.6.9.2
* Tinkers Construct: 3.0.3.144

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
As of 10:08am EST it is not on either.

**Comment by KnightMiner** [comment]
This feature exists indirectly. Pig iron killing pigs gives a chance to drop bacon, and that bacon can be used to repair pig iron tools. In my opinion, that is sufficient for this idea.
