### ISSUE TITLE
Some casting recipes do not use tags

### ISSUE THREAD

**Issue by Freebi85** [SlimeKnights/TinkersConstruct#4456]
Not sure if this is truly a bug, but smeltery recipes for casting certain ingots do not use tags and instead use the respective ingot from tinkers only. This breaks compatibility with other mods ingots when altering or unifiyng stuff, and can be fixed very easily by replacing the respective code in the datapacks to tag. Example for recipes/smeltery/casting/metal/copper/ingots casts

`
{
  "type": "tconstruct:casting_table",
  "cast": {
    "tag": "tconstruct:casts/single_use/ingot"
  },
  "cast_consumed": true,
  "fluid": {
    "name": "tconstruct:molten_copper",
    "amount": 144
  },
  "result": "tconstruct:copper_ingot",
  "cooling_time": 50
}`

to 

`
{
  "type": "tconstruct:casting_table",
  "cast": {
    "tag": "tconstruct:casts/single_use/ingot"
  },
  "cast_consumed": true,
  "fluid": {
    "name": "tconstruct:molten_copper",
    "amount": 144
  },
  "result": {
    "tag": "forge:ingots/copper"
  },
  "cooling_time": 50
}
`

**Comment by KnightMiner** [comment]
The tag output was originally so we could give a predictable output when crafting items that do not belong to our mod, if it belongs to our mod we did not need a tag output.

That said, I fixed this about 2 days ago in d6548d5 for the sake of better compat, will be in the next release.

----

For the record, if nothing is broken, enhancement is a better template than bug.

**Comment by Freebi85** [comment]
Thank you very much for the fast answer. This is really very helpful! 😃 

Sorry will choose the next time enhancement for something like this.

Cheers 🍺

**Comment by KnightMiner** [comment]
Added in  3.0.3.152
