### ISSUE TITLE
Tool Forge

### ISSUE THREAD

**Issue by GivHenTie** [SlimeKnights/TinkersConstruct#4457]
**Is your idea related to a problem? Please describe.**
No
**Describe the solution you'd like**
Please add the tool forge
**Describe alternatives you've considered**

**Additional context**
I wanted to make an unbreakable shuriken but can't because it requires tool forge

**Versions:**
* Minecraft:1.16.5
* Forge: 1.16.5
* Mantle: 
* Tinkers Construct: Tinkers' Construct 3.0.3.144 for 1.16.5

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
Yes

**Comment by PrincessOfEvil** [comment]
Tinkers Anvil already exists. Please actually read the resources provided next time.
