### ISSUE TITLE
TinkerModules.cfg missing

### ISSUE THREAD

**Issue by unDefine404** [SlimeKnights/TinkersConstruct#4458]
Issue description: TinkerModules.cfg not appearing in config folder, therefore, I can't enable the smeltery

Minecraft: 1.16.5
Forge: 36.1.0
Mantle: 1.6.92
Tinkers Construct: 3.0.3.144

**Comment by ShinyPorygon** [comment]
Deleting the issue template is not an excuse for ignoring it. Open a new issue and actually follow the issue template, you left out vital information if we are to fix this.

Equally the smeltery is "enabled" it has a different recipe than you are used to. Check JEI

**Comment by KnightMiner** [comment]
Modules are gone, forge revamped the config system. I also don't know what you mean by "enable the smeltery", its always enabled. You probably just do not understand that the crafting recipe changed, which you would have learned if you read "Whats New" as the issue template you deleted told you to read.
