### ISSUE TITLE
Sledgehammer doesn't work with offhand

### ISSUE THREAD

**Issue by acastor01** [SlimeKnights/TinkersConstruct#4459]
**Issue description:**
As of 3.03.144 right-click to use offhand no longer works with the sledgehammer. Was working on previous versions. Not sure if this is intended as the sledgehammer is a large tool or if broken on 3.03.144.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 1.6.92
* Tinkers Construct: 3.03.144

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Not explicitly covered, could be covered by the limitations on large tools, assuming this is the intended behavior of the hammer.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Is reproducible with just TCon and Mantle

**Comment by PrincessOfEvil** [comment]
Not a bug, all broad tools block off hand interactions.

**Comment by KnightMiner** [comment]
I'll make sure what's new says this.
