### ISSUE TITLE
Tinkers Tool Leveling in Tinkers

### ISSUE THREAD

**Issue by GianBala83** [SlimeKnights/TinkersConstruct#4460]
The creator of Tikers Tool Leveling mod maybe wont add the mod to 1.16, so i think everybody would love if you implement this as a oficial feature of Tinkers, that would help a lot!!!!

**Comment by KnightMiner** [comment]
I inherited the mod from the original creator, it was I who said I won't add it to 1.16 in addition to boni retiring. Also, do at least a little research before making a suggestion like this, there is a lot more that could be said on the topic that does not belong here.
