### ISSUE TITLE
Server console errors pointing towards TCon

### ISSUE THREAD

**Issue by Kamisoi** [SlimeKnights/TinkersConstruct#4462]
**Issue description:**
Server console is spammed by errors.

**Link to spam:**
https://pastebin.com/0YmPeRYy

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
No idea; errors come on modpack GreedyCraft, ver. 1.34.1.115.1.

**Comment by KnightMiner** [comment]
No idea is not a valid answer. Give a useful answer to the last question.

**Comment by Kamisoi** [comment]
Look, only thing I can tell and find, is that it might be issue with TCon & Construct's Armory. Error comes up randomly, not really when I want to.

**Comment by KnightMiner** [comment]
Is it spamming you, or is it rarely happening? If its spamming, it should be easy to reproduce. If its rare, I don't see how this is a huge issue.

According to the info you provided, something with Tinkers Complement knight slime armor is triggering an error saying your server network is invalid.

I have never seen this issue before, so you have a mod breaking Forge's network system. I cannot fix this unless you give me information to reproduce it, if you don't want to provide information I see no reason to keep this issue open.

**Comment by Kamisoi** [comment]
Once it happens; it spams quite a bit on logs [loops roughly 20-60 times]. Right now stripping whole pack down for server pack to check, will take a while.

**Comment by Kamisoi** [comment]
**How to reproduce:**
Modlist:
![image](https://user-images.githubusercontent.com/26931504/118097451-00556580-b3d3-11eb-9ba8-30d1bb69756c.png)
Wear Tinker's Complement Knightslime armor, jump around to take slime boost like from slimeboots.
Server's console should produce error similar to: https://pastebin.com/SBDpN7WR

**Comment by KnightMiner** [comment]
Does this happen with regular slime boots?

Does this happen on a server only, or also in single player?

Can you get more minimal than that? I do not see why you would need B.A.S.E or CraftTweaker for this, nor Construct's Armory. In theory this issue would affect just Tinkers Construct and Tinkers Complement

**Comment by Kamisoi** [comment]
Seems to appear only on server; 
Seems like happens only with Knightslime. 

Disabling rest of mods and keeping only Mantle, TCon & TComp still keeps the issue.

**Comment by KnightMiner** [comment]
Honestly surprised this only happens with KnightSlime. In any case, no good fix without major refactors. I did those refactors on 1.16.

Closing as 1.16 got a beta, so 1.12 is at end of support.
