### ISSUE TITLE
Crossbow crashing my game

### ISSUE THREAD

**Issue by OneTrain73** [SlimeKnights/TinkersConstruct#4463]
**Issue description:**
For some reason, sometimes when I try to load my Crossbow, it crashes my game. The crossbow is an Electrum crossbow with Hemp Fibre bowstring, Netherrack tool rod and Manyullyn tough binding, embossed with Paper. The bolt is an Endrod bolt tipped with manyullyn, with Steeleaf fletching
**If crashed, link to crash report (use a site such as pastebin):**
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: -1
**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-forge-14.23.5.2854
* Mantle: I'm not sure what Mantle is
* Tinkers Construct: TConstruct-1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Immersive Engineering
Twilight Forest
Tinkers' Tool Levelling (potentially)

**Comment by KnightMiner** [comment]
Read the template instructions on the crash report again. The first line is useless, we need the full report.

Also, on the last question, your answer screams that you have not tested with fewer mods. Test with just Tinkers. Test with just the three you listed (I see no reason thowe 3 would cause this, most conflicts are no more than 2 mods excluding dependencies)

**Comment by KnightMiner** [comment]
Closing for lack of full crash report.
