### ISSUE TITLE
Durability use bug with a third party mod

### ISSUE THREAD

**Issue by DarkScorn** [SlimeKnights/TinkersConstruct#4464]
Issue description:
Tools do not use durability within a specific situation.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.3
* Mantle: 1.6.97
* Tinkers Construct: 3.0.3.144 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
 Epic Fight: 1.16.5-3.2.2

Steps to reproduce:
Download Epic Fight alongside Tinkers,
Toggle build/battle mode of Epic Fight (initial key is R),
Use any tool to attack any mob.
As long as player is in battle mode, tools do not use durability.

**Comment by KnightMiner** [comment]
Cross post this to Epic Fight Mods issue tracker, there is no reason our tools would not take damage unless they do things in a really weird way.

**Comment by KnightMiner** [comment]
Going to close this as the epic fight mod github closed the issue. I think that means he fixed it, but the guy makes 0 use of github features to be able to tell. Specifically, he did not comment on the issue whether he fixed it, and the only commit record is one giant commit for the entire update.
