### ISSUE TITLE
issue with Nether Cobalt Ore in Spectator Mode

### ISSUE THREAD

**Issue by asdasdasadg** [SlimeKnights/TinkersConstruct#4466]
https://i.imgur.com/RW3S6Za.png

**Comment by ShinyPorygon** [comment]
Deleting the issue template is not an excuse for ignoring it. Open a new issue and actually follow the issue template, you left out vital information if we are to fix this.
Leaving out every bit of info is even worse.

**Comment by KnightMiner** [comment]
This is fixed 53fbe7b

**Comment by KnightMiner** [comment]
Fixed in one of the recent releases
