### ISSUE TITLE
Greenheart, Skyroot and Bloodshroom Trapdoors using Wood sounds

### ISSUE THREAD

**Issue by asdasdasadg** [SlimeKnights/TinkersConstruct#4467]

**Comment by ShinyPorygon** [comment]
Deleting the issue template is not an excuse for ignoring it. Open a new issue and actually follow the issue template, you left out vital information if we are to fix this.
Leaving out every bit of info is even worse.

**Comment by ShinyPorygon** [comment]
Deleting the issue template is not an excuse for ignoring it. Open a new issue and actually follow the issue template, you left out vital information if we are to fix this.
Leaving out every bit of info is even worse.

**Comment by mDiyo** [comment]
The issue template is not optional.
