### ISSUE TITLE
Tall Grass getting cut off on Clay Islands

### ISSUE THREAD

**Issue by asdasdasadg** [SlimeKnights/TinkersConstruct#4468]
https://i.imgur.com/30umv0J.png

**Comment by ShinyPorygon** [comment]
Deleting the issue template is not an excuse for ignoring it. Open a new issue and actually follow the issue template, you left out vital information if we are to fix this.
Leaving out every bit of info is even worse.

**Comment by mDiyo** [comment]
The issue template is not optional. I have no idea what the problem is from just the screenshot.
