### ISSUE TITLE
Smeltery problem 

### ISSUE THREAD

**Issue by AwildGeese** [SlimeKnights/TinkersConstruct#4469]
So i was playing Sky Factory 4 about to do the smeltery and i searched how to do it and it says i need the "Smeltery Controller" and other blocks that dosnt even apear on the jei am i blind, wrong or that thing changed 

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.49
* Tinkers Construct: 
Leveling: 1.1.0
Complement: 0.4.0

I didnt touch anything from the modpack so all the mods are the same

**Comment by PrincessOfEvil** [comment]
Iirc Sky Factory changes a lot of recipes. Make sure you follow its path.
