### ISSUE TITLE
textures become transparent or black 

### ISSUE THREAD

**Issue by harmalom** [SlimeKnights/TinkersConstruct#4470]
**Issue description:**

textures become transparent or black from some blocks, it does not produce any blocking or closing of the game, functional if you interact with them but it is annoying.  

**Versions:**
  TConstruct-1.16.5-3.0.3.152

* Minecraft:
 1.16.5

* Forge: 
  36.1.16

* Mantle: 
  1.16.5-1.6.97

* Tinkers Construct: 
* 
 some images
![2021-05-11_08 23 16](https://user-images.githubusercontent.com/67077986/118344480-d8a9ee80-b4f3-11eb-9440-48cf63e77ba1.png)

![2021-05-14_19 41 21](https://user-images.githubusercontent.com/67077986/118344482-dd6ea280-b4f3-11eb-88c5-361ab9426052.png)

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Mod List
https://pastebin.com/jjNQgFmk

**Comment by KnightMiner** [comment]
The last question is not "list all your mods", its "tell me exactly the mods required to reproduce the issue".

This does not happen for me, and you provided a list with 100 mods. I do not have time to search through your mod list trying to find the conflict. So if you want this fixed, narrow down the mod list to find the mod breaking it. You should have about 5 by the end. Also remove any graphics related mods or performance enchancers.

**Comment by KnightMiner** [comment]
Closing for lack of response. Reproduce this issue with no performance enhancers or graphics mods and we can look into it again.
