### ISSUE TITLE
Crash when trying to bookmark air in the smeltery

### ISSUE THREAD

**Issue by benbenlaw** [SlimeKnights/TinkersConstruct#4471]
**Issue description:**
Crash when trying to bookmark in JEI air in the smeltery
**If crashed, link to crash report (use a site such as pastebin):**
[crash-2021-05-15_23.27.29-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/6487480/crash-2021-05-15_23.27.29-client.txt)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 1.6.97
* Tinkers Construct: 3.0.3.152

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
tinkers and JEI

**Comment by KnightMiner** [comment]
How is this a tinkers bug? I see nothing referencing our code in that stacktrace. What are you trying to bookmark that is causing this issue?

In any case, sounds like a JEI bug to me, we do nothing more than expose our fluids to JEI. Report this to the proper mod.

**Comment by KnightMiner** [comment]
Closing as I still don't know what problem this issue is describing, all I see is a crash report generated in JEI code and no steps explaining how our mod caused it.
