### ISSUE TITLE
slimeknights/tconstruct/library/client/MaterialRenderInfo Error Crash

### ISSUE THREAD

**Issue by Calebplaysgames** [SlimeKnights/TinkersConstruct#4472]
**Issue description:**
litterally nothing since I cant explain other than *newest 1.12.2 version*
**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/9WqFzrWW
**Versions:**
* Minecraft: 1.12.2
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Duplicate of #4441, not our bug. LUCraft is using one of our classes wrongly, report to them.
