### ISSUE TITLE
1.16.6 Slime Islands Spawn too Frequently

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#4475]
Changing the configs to 50 chunk separation does not seem to thin out the number of islands that generate all over the place.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 1.6.97
* Tinkers Construct: 3.0.0.152

**Comment by KnightMiner** [comment]
50 is not that might higher than the default 30. The configs work perfectly fine in my testing, try a higher number. Note this is a vanilla mechanic controlling their placement, same logic that places nether fortresses or ruined nether portals.

I've also seen at least one mod that changes other mods structure generation settings, make sure you have none of those.

**Comment by MokahTGS** [comment]
Well I'll close this as it seems to be an interaction with Terraforged.
