### ISSUE TITLE
Tinker Construct and TerraForged

### ISSUE THREAD

**Issue by ErisWhistles** [SlimeKnights/TinkersConstruct#4476]
**Issue description:**
When using TerraForged and tinkers construct the floating slime islands and other variants seemingly spawn every few chunks or so, changing the config for Tinkers Construct didn't fix the issue, I believe its something wrong with TerraForged, nonetheless I hope you guys can fix it or at least give an option to completely turn off the islands by default.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
TerraForged-1.16.5-0.2.10 - TConstruct-1.16.5-3.0.3.152

**Comment by PrincessOfEvil** [comment]
Duplicate of #4475.

**Comment by PrincessOfEvil** [comment]
Duplicate of #4473.
