### ISSUE TITLE
Cannot fully reinforce a tool

### ISSUE THREAD

**Issue by robotgryphon** [SlimeKnights/TinkersConstruct#4477]
**Issue description:** Cannot fully apply reinforced to a crafted tool; was going for an unbreakable sword and applied writable and harmonious to the tool. Tool says 83 percent reinforced, instead of unbreakable at tier V.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.144

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

![image](https://user-images.githubusercontent.com/8529636/118520698-43cc0e80-b708-11eb-9f95-7e459d096004.png)
![image](https://user-images.githubusercontent.com/8529636/118521167-c2c14700-b708-11eb-9f50-ea7afec88912.png)

**Comment by PrincessOfEvil** [comment]
Unbreakable is a separate ability now, which is something you would know if you read the resources provided.

**Comment by robotgryphon** [comment]
Where the heck is said resource?! I've read both of the books ingame, JEI, the mod page FAQ and "What Changed" section...

**Comment by PrincessOfEvil** [comment]
If you don't have it in JEI, your mod version is too old.

**Comment by Toby222** [comment]
JEI isn't really a resource that's "provided" here. You'd think it would be written in one of the books.

**Comment by robotgryphon** [comment]
So, I found it. You had to know to dig through the MODIFIERS section, instead of ABILITIES, and it's a small little note in the changelog. I would have never seen that, since there's literally no mention of Unbreakable in the mod books, but Reinforced is there. Not to mention, there's no documentation on how to even get to the modifiers page in JEI as well. Had to find that by sheer luck in a test world.
