### ISSUE TITLE
Crashing with Latex Processing Unit

### ISSUE THREAD

**Issue by specopswarrior** [SlimeKnights/TinkersConstruct#4478]
**Issue description:**
Crashed when trying to take out tiny dry rubber from LPU from industrial foregoing with a crafting station.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:** TConstruct-1.16.5-3.0.3.126 / industrial-foregoing-1.16.5-3.2.11-55cb112.
* Minecraft: 1.16.5
* Forge:  forge-36-1.2
* Mantle: Mantle-1.16.5-1.6.92
* Tinkers Construct:  TConstruct-1.16.5-3.0.3.126

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
As far as im aware no.
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
No it would need  Industrial Foregoing.

**Comment by PrincessOfEvil** [comment]
>  If crashed, link to crash report (use a site such as pastebin)

**Comment by specopswarrior** [comment]
https://pastebin.com/ECrvfvnP

**Comment by KnightMiner** [comment]
The crash report makes no sense as its getting an array out of bounds error in a context that lacks any array accesses. I assume a mixin or a coremod is to blame.

Do what the issue template recommended and reproduce with minimal mods. Give me a crash report with less than 10 mods, ideally less than 5. You may need to try a few combinations to find the proper mod list.

**Comment by Random832** [comment]
It really does happen with only TCon and IF - it looks like the mixins were obscuring part of the stack trace, the array out of bounds error happens inside ArrayList.

Here's a clean crash report
https://hastebin.com/raw/oxedezaroc

**Comment by KnightMiner** [comment]
Looks like an industrial foregoing issue. They are doing something really weird with inventories. Report this issue to them so we can figure it out.

**Comment by Random832** [comment]
Further investigation: dragging items in and out normally works fine [EDIT: there's actually a constant logspam background noise of "failed client tasks" even when doing nothing], only shift-click crashes. Though I think I managed to dupe an item by putting an incorrect item in the bucket input slot [first slot], I can't reproduce it reliably. Trying to drop any item [including tiny dry rubber] into the output slots crashes with a similar error.

**Comment by KnightMiner** [comment]
This issue has been closed on Industrial Foregoing's issue tracker, so either it was fixed or it never will be. If this issue exists on 1.19.2 we can reopen.
