### ISSUE TITLE
[RESOLVED] Floating Island is generated as vanilla terrain

### ISSUE THREAD

**Issue by FiammaVerde** [SlimeKnights/TinkersConstruct#4480]
Minecraft: 1.16.5
Java: AdoptOpenJDK (jdk-11.0.11.9)
Forge: 36.1.23
Tinker's Construct: 3.0.3.152
    Mantle: 1.6.97
Seed: -8836811803329303795
Tinker's Construct Floating Island Coordinates: x=-133; z=150; y=-145

On a new world on a fresh install (only Forge and TC+Mantle), Floating Islands generate as vanilla terrain without the "slime-type" stuff.

![TC Island](https://user-images.githubusercontent.com/60235666/118805472-3c426c00-b8a6-11eb-8c09-2d14d5a37abb.png)

**Comment by ShinyPorygon** [comment]
That's a new clay island. It's intended.

**Comment by DreaminBoi** [comment]
It should be the tinker clay island check in the pond to see if there's a clay

**Comment by FiammaVerde** [comment]
So it is!

![TC Clay Island](https://user-images.githubusercontent.com/60235666/118806911-ef5f9500-b8a7-11eb-9ee2-ebe1da2ea075.png)

Thank you!
