### ISSUE TITLE
[Not Important Issue] blank clay cast's texture and name are broken

### ISSUE THREAD

**Issue by delta-nos** [SlimeKnights/TinkersConstruct#4482]
**Issue description:**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

Please check this image. Texture is same as (normal) blank cast and name is not translated, it shows unlocalized name. Blank clay cast is unused item so it's not important, but I'll tell it. Thanks.
![2021-05-20_21 27 32](https://user-images.githubusercontent.com/83546876/118978393-3d60bf80-b9b2-11eb-8f7b-e8d47128c1c6.png)

**Comment by KnightMiner** [comment]
Closing as 1.16 received a beta and 1.12 is no longer receiving builds. Added to the milestone as this is a pretty trivial fix, a resource pack could also fix it. Practically I don't think that item was meant to exist.
