### ISSUE TITLE
Change tag of TinkersConstruct books

### ISSUE THREAD

**Issue by glahera** [SlimeKnights/TinkersConstruct#4488]
**Is your idea related to a problem? Please describe.**
Currently TinkersConstruct book is tagged as "forge:books"

**Describe the solution you'd like**
It'd be better if it is tagged as "forge:lectern_books" so that it aligns with other guide books from other mods

**Comment by KnightMiner** [comment]
You are thinking `minecraft:lectern_booms`, and that's not what that tag is for. That tag makes a book work with the lectern. Many non-guidebooks  have that tag. ThAt is why we tag our books `forge:books/guide`, so only guidebooks are there. I'd advise other guidebook mods to do the same.

I'll probably tag our books for the lectern eventually if I can get the UI working properly, but that tag is not assigned arbitrarily
