### ISSUE TITLE
optifine rendering issue with tinkers will there be a fix?

### ISSUE THREAD

**Issue by SPEEDYMAN56** [SlimeKnights/TinkersConstruct#4489]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by ShinyPorygon** [comment]
Duplicate of #4316
