### ISSUE TITLE
When did an tinkers axe break stone/cobblestone instant?

### ISSUE THREAD

**Issue by MrStatman80** [SlimeKnights/TinkersConstruct#4490]
I am playing Seaopolis modpack and only got stone tools with tinkers... but i used a axe not pickaxe but the axs broke stone instance like in creative mode

This is not a crash but a bug

**Comment by MrStatman80** [comment]
and due to water logged

**Comment by KnightMiner** [comment]
I have not had this happen, and you failed to use the issue template. Open a new issue and actually fill out the issue template, you left out vital information.
