### ISSUE TITLE
1.16.5 3.0.4.171 requires mantle version "1.6.102" 

### ISSUE THREAD

**Issue by Ajw2003** [SlimeKnights/TinkersConstruct#4491]
mantle version 1.6.102 isn't available anywhere to download 

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 1.16.5 36.1.24
* Mantle: 1.6.97
* Tinkers Construct:  3.0.4.171

just won't launch, new version came out 30 minutes ago as of posting, so no other account of this issue has been reported yet to my knowledge

**Comment by KnightMiner** [comment]
Uploaded Mantle 1.6.103, should be available on CurseForge now.
