### ISSUE TITLE
Obsidian Pane Tags

### ISSUE THREAD

**Issue by WenXin20** [SlimeKnights/TinkersConstruct#4493]
**Issue description:**
- Obsidian Panes are missing the block tag `#minecraft:dragon_immune`.

**Versions:**
* Minecraft: v1.16.5
* Forge: v36.1.24
* Mantle: v1.6.103
* Tinkers Construct: v3.0.4.171

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
- Yes

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
- Yes

**Comment by KnightMiner** [comment]
Fixed in 3.0.4.194
