### ISSUE TITLE
Datapack error

### ISSUE THREAD

**Issue by TheSexyYeti** [SlimeKnights/TinkersConstruct#4494]
Minecraft: 1.16.5
Forge: 36.1.23
Mantle: 1.6.103
Tinkers Construct: 3.0.4.171

I'm not sure if this is on the roadmap or not cuz I'm not sure where to find it to look. But I wanted to inform you that with TConstruct and Mantle. I'm getting a datapack error saying that your mod is incompatible with 1.16.5. preventing game worlds from loading or even being created. And it's not just your mod. There are many other popular mods that are giving the same error. In the screenshot I don't show specifically your mod. But this is essentially what I'm seeing in the datapack screen when I scroll down to your mod.
![datapackerror](https://user-images.githubusercontent.com/50222286/119911958-6e983d00-bf28-11eb-84b7-57a211063af7.jpg)

**Comment by ShinyPorygon** [comment]
If you are using a datapack made for more tinkers mats for version 3.0.4.152 or lower than it will not work.

**Comment by KnightMiner** [comment]
The datapack being "incompatible" does not prevent worlds from loading. That is really a warning, but you can load them anyways. You have a different issue preventing worlds from loading

Going to leave this open as a reminder to increase that arbitrary number, but this is not an issue that will break anything.

**Comment by TheSexyYeti** [comment]
Ok. But honestly I didn't install any datapacks at all. I only installed mods. And I haven't installed any other Tinkers related mod that could have also installed a datapack. So I'm kind of stumped as to why it's doing this then.

**Comment by PrincessOfEvil** [comment]
Post the crashlog, then.

**Comment by KnightMiner** [comment]
> Ok. But honestly I didn't install any datapacks at all. I only installed mods.

Mods are datapacks. They also have code, but every mod is both a datapack and a resource pack.

**Comment by KnightMiner** [comment]
Closing as the issue on our side was fixed and you never provided any useful logs linking your other error to us.
