### ISSUE TITLE
Invalid foundry structure and client crash

### ISSUE THREAD

**Issue by Random832** [SlimeKnights/TinkersConstruct#4497]
**Issue description:**
A foundry structure that should have been invalid was allowed to form, and after I melted something it it crashed the client.

The structure consisted of two 1x1x1 interior foundries sharing the controller in the bottom front block and a tank in the dividing wall between them. The structure was built out of scorched stone, then the controller was placed [the structure formed at this time], then the dividing wall was removed and the tank placed. I did not record what cardinal direction the structure was facing, and I cannot load the world without crashing.

**If crashed, link to crash report (use a site such as pastebin):**
https://hastebin.com/uqewacixeq.txt

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.13
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.171

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
This is a crashing bug

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
This happened in a non-dev environment that had about two dozen mods installed (though, to be clear, there were no performance enhancing mods); I have not yet attempted to reproduce with only Tinker's Construct yet. I wanted to get this report ready first because I've run into some apparently nondeterministic behavior regarding structure validation before, so there's no guarantee that I can reproduce it at all. I do still have the world file this happened in.

**Comment by Random832** [comment]
Opened the world with an NBT editor, the controller was facing south, and the NBT for the controller tile entity is in a screenshot at https://media.discordapp.net/attachments/395801350731989003/848063401229287424/unknown.png

**Comment by KnightMiner** [comment]
Fixed in 3.0.4.194.

Let me know if old worlds cannot be reopened still, I think I caught it so it will no longer crash, but you definitely want to break and reform the old structure
