### ISSUE TITLE
Seared Drain doesnt work when filtering Molten Blaze

### ISSUE THREAD

**Issue by Quick27Draw** [SlimeKnights/TinkersConstruct#4498]
**Issue description:**
Seared drain does not pour liquid when filtering Molten Blaze normal drain works but not seared

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I see the drain is in alpha but no specifics on if this issue has been brought up

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Uh, what? What drain are you using that is not the seared drain? Drains are not filtered, ducts are, and both are seared unless you are using a foundry.

You also ignored half the issue template, so not just do I not know what you are talking about, you missed vital information. Fill in the information you missed from the template, and post screenshots if you cannot clearly explain what you mean.

**Comment by Quick27Draw** [comment]
Hi i'm sorry about missing parts of the template I wasn't sure what to put in some of the places this is my first issue post. As far as the issue is concerned the modpack I was playing on was one update behind and after updating it now works. Once again I apologize for the confusion there is no longer an issue.
