### ISSUE TITLE
Piggybackpack Vision

### ISSUE THREAD

**Issue by kurai-ookami** [SlimeKnights/TinkersConstruct#4499]
When using the piggybackpack, mobs picked up drastically obstruct view in first person unless you are in a prone position. This has been the case for several versions and persists in version TConstruct-1.16.5-3.0.4.171

**Comment by ShinyPorygon** [comment]
Are you expecting the mob to float above your head? This is the "down-side" of using it.

**Comment by kurai-ookami** [comment]
With the pumpkin heads your view is obstructed as well but you can still see. Even if they were just high enough so that it only obstructed the top 2/3 of the screen i feel like that would have more parity to Minecraft's other vision obstructing effects. But if this is as intended then so be it.

**Comment by KnightMiner** [comment]
All the piggybackpack does us make the entity ride you. Minecraft is responsible for where they ride you, so if you can't see blame Mojang.

**Comment by kurai-ookami** [comment]
Understood. And thanks for taking the time to read it over!
