### ISSUE TITLE
Tinker's Books cannot be kept on a lectern

### ISSUE THREAD

**Issue by Seiya2333** [SlimeKnights/TinkersConstruct#4501]
The Books cannot be kept on a lectern, I used the lectern to wantch fast the book, and with the Tinker's Book is too necesary because it is a Consultation book, but it can't be kept on a lectern. 
Pd. Sorry for my English 
**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.24
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.171

**Comment by KnightMiner** [comment]
Known issue, lecterns are not trivial to implement support. Vanilla hardcoded it to the written book, and a few places in our book are hardcoded to the players hand. The hooks needed to override vanilla are not too bad, but need to wait on a few mantle changs to do anything.

**Comment by judicius** [comment]
would this be the same issue to why Puny Smelting, Mighty Smelting and Gadgetry don't work on Builders crafts & Addons bookshelves?

**Comment by KnightMiner** [comment]
No, that is #4395. Short version: they are either using the wrong tag (lectern books is not a proper list of books), or are using the hacky solution of checking registry names (no sense in doing that when we have tags)

Report the issue to Builders Crafts and Additions, tell them to use `forge:books`. Its what I do in Inspirations

**Comment by KnightMiner** [comment]
Added in 3.0.4.194, commit 4f46e30
