### ISSUE TITLE
Modifiers do not visibly show on tools 

### ISSUE THREAD

**Issue by AlphaBeta116** [SlimeKnights/TinkersConstruct#4502]
After adding any modifiers to any weapon or tool, the associated visual changes do not occur but stat changes do.

- Minecraft: 1.16.5
- Forge: 36.1.24
- Optifine HD U G8
- Tinker's Construct 3.0.4.171

**Comment by ShinyPorygon** [comment]
Will come later. Don't delete the issue template next time as it asked you to look at the roadmap which would have told you this. Also don't use optifine.
