### ISSUE TITLE
Luck ability broken in TConstruct-1.16.5-3.0.4.171

### ISSUE THREAD

**Issue by WalpurgisAk** [SlimeKnights/TinkersConstruct#4504]
Luck ability cannot be applied in tinker anvil or tinker station to any tinker's tool.

**Versions:**
*Minecraft 1.16
* Forge 36.1.0: 
* Mantle: 1.16.5-1.6.103
* Tinkers Construct: 1.16.5-3.0.4.171

I could not find any other bug report on this issue, and there is no mention of the luck ability upgrade being removed from roadmap or "what's new"

Bug reproducible with only Tconstruct and mantle installed

**Comment by KnightMiner** [comment]
The modifier is not removed or broken, recipe changed. Look in JEI in the modifers tab for recipes, or actually read the changelog of new alphas.

**Comment by TheOnlyMann** [comment]
https://cdn.discordapp.com/attachments/395801350731989003/846292294164021288/unknown.png

https://cdn.discordapp.com/attachments/395801350731989003/846292332755288104/unknown.png

are you sure its not this?

**Comment by WalpurgisAk** [comment]
> 
> 
> The modifier is not removed or broken, recipe changed. Look in JEI in the modifers tab for recipes, or actually read the changelog of new alphas.

I am not using JEI, and while, on second look at the changelog I can find that the recipe changed, i cannot find the new recipe anywhere in it. Sorry for bothering you with a bug report, when I guess i should have been just asking for help finding the new recipe.

**Comment by WalpurgisAk** [comment]
> 
> 
> https://cdn.discordapp.com/attachments/395801350731989003/846292294164021288/unknown.png
> 
> https://cdn.discordapp.com/attachments/395801350731989003/846292332755288104/unknown.png
> 
> are you sure its not this?

thanks for the help. I really appreciate it.

**Comment by KnightMiner** [comment]
> I am not using JEI

Do not play the alpha without JEI. As of yet that is the only source of recipe information (the screenshots TheOnlyMan posted were just JEI recipes). Eventually there will be other sources of information, but as of yet that is the supported way for up to date information
