### ISSUE TITLE
Sky Slime Vine Crash

### ISSUE THREAD

**Issue by WenXin20** [SlimeKnights/TinkersConstruct#4505]
**Issue description:**
While playing on my server, I randomly got a crash client-side.
**If crashed, link to crash report (use a site such as pastebin):**
https://gist.github.com/WenXin20/80b53d59909e2420d810fa85ea98b491
**Versions:**
* Minecraft: v1.16.5
* Forge: v36.1.24
* Mantle: v1.6.103
* Tinkers Construct: v3.0.4.171

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Yes
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Unsure, I haven't tested with fewer mods yet.

**Comment by KnightMiner** [comment]
Unsure is not a valid answer to the last question. And deleting the part of the issue templating telling you how to answer the last question is equally invalid. I assume this crash is caused by Optifine as you have Optifine installed. Reproduce with fewer than 10 mods as the statement you deleted said to do, notably without Optifine, and we can reopen.

**Comment by WenXin20** [comment]
I know it was there, I removed it because I did not think it was needed to be kept in the post as I like to keep my reports clean. I posted the crash report as soon as I got it and did not have time yet to do anything else, which is why I put that I was unsure, I did not want to put no if I didn't yet know the answer as others can help if they see this same crash, you did not even give a chance for it to be reproduced without it. This type of debugging takes time to do so.

**Comment by KnightMiner** [comment]
Then debug before posting the issue. You don't think it takes time for me to deal with an issue that has not been debugged?

We also do not support Optifine. They are closed source, so we have no way to know what they change. Any bugs caused by Optifine are on Optifine to fix.

**Comment by WenXin20** [comment]
Yes, I know it takes time on both sides, I've done my own share of modding. If there's an issue report, then its known something is causing it to crash. I've posted over a thousand issue reports over the years, so I know how this works. This is the first I've seen someone so against a bug report for their mod. Thanks for the support.

**Comment by KnightMiner** [comment]
Yeah, good luck finding a popular mod that supports Optifine.

**Comment by WenXin20** [comment]
I never said anything about optifine. And I don't care if the mod is popular or not. And after your demoralizing speeches, I won't be wasting my time on this. 
I was already able to load the world again without the crash, so it will be impossible to debug if it's not consistent and I doubt it has anything to do with optifine since the stacktrace doesn't even mention it.

**Comment by jeremiahwinsley** [comment]
We had a report of this crash on the ATM6 pack from a user without Optifine, crash log here:
https://gist.github.com/jeremiahwinsley/5274bda7370cb0850c2c215acb9cd31a

**Comment by KnightMiner** [comment]
Still nothing I can do about it, I see nothing in that report specific to Tinkers, it looks like someone changed how model loading works and is loading models asynchronously. Give me a minimal list (less than 5 mods) and I might be able to do something, but its absolutely useless to say this crash happens with 200+ mods in code that is not even mine. Nothing in that report says it won't just happen with vanilla vines.
