### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by TomasArrinda** [SlimeKnights/TinkersConstruct#4507]
I've installed a few mods, but one of the core mods (Lucraft Core) seems to conflict with Tinkers Construct. How can I fix this?

Error description in the launcher:
https://ghostbin.co/paste/wz2g7v2

Crash log:
https://ghostbin.co/paste/vfm5oas

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.179

Mod list:
![image](https://user-images.githubusercontent.com/76977212/120401368-d0341f00-c30d-11eb-868b-ec0be907bfb0.png)

(Still new to this site, if I made any mistakes please let me know)

**Comment by ShinyPorygon** [comment]
Duplicate of #4441 not tinkers fault.

**Comment by TomasArrinda** [comment]
Issue fixed. I just lacked some of my mod's dependencies.
