### ISSUE TITLE
Bottle O' Enchanting Modifier does not work on any tool or weapon

### ISSUE THREAD

**Issue by UlIlI** [SlimeKnights/TinkersConstruct#4508]
**Issue description:**
How to reproduce: Go to repair/modify on a Tinker Station/ Tinker's Anvil, and insert a tinkers tool/weapon in the slot where a there is a outlined pickaxe. Then put a Bottle O' Enchanting in any of the Modifier Slots (the slots where there is item outline, but the outline is not in the shape of a pickaxe)
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.23 
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.171

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
This issue has not been covered yet
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
This bug can be reproduced with just Tinkers Construct.
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by PrincessOfEvil** [comment]
Cannot confirm. Please fill out the issue template.

**Comment by UlIlI** [comment]
I have fixed this a while ago. I will let you guys take your time and just act chill

**Comment by KnightMiner** [comment]
Uh, what? Are you no longer experiencing this issue? Or are you doubting that we cannot reproduce. Your wording is really unclear.

**Comment by UlIlI** [comment]
I meant that I fix the description of the issue

**Comment by UlIlI** [comment]
I am going to close this issue. I Just had to uninstall a mod
