### ISSUE TITLE
Smite XI does not show up properly.

### ISSUE THREAD

**Issue by wilyank** [SlimeKnights/TinkersConstruct#4509]
**Issue description:**
If you make a Sledgehammer, Cleaver or Vein Hammer completely out of Silver, add three upgrade slots (book and quill + golden apple works), and add the Smite modifier (glistening melon) five times, the tooltip says "Smite enchantment.level.11" instead of "Smite XI".

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.24
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Any mod that adds Silver is required to reproduce this bug.
For me it was Ice and Fire - Dragons, but I assume any mod that adds silver reveals this bug.

**Comment by KnightMiner** [comment]
Fixed in 3.1.1.252
