### ISSUE TITLE
Ardite not found

### ISSUE THREAD

**Issue by Torpefy-ok** [SlimeKnights/TinkersConstruct#4510]
**Issue description:**
I recently downloaded Tinker's along with some other mods  and created a server with a friend i dont now too much and have been watching tutorials on how to get started some of them mentioned Ardite ore which isnt anywhere to be found all the other ores to my knowledge are there idk if it was removed in the 1.16 version and im just being silly or it actually a fault could anyone help

**Versions:** 1.16.5 
* Minecraft: 1.16.5
* Forge: 1.16.5
* Mantle: 1.16.5
* Tinkers Construct: 1.16.5

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
yes im not sure what that is but ok
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
alexsmobs
architectury
BiomesOplenty
Bookshelf
Cgm
Citadel
cofh_core
Dungeons gear
Dungeons mod
Enchantment descriptions
Extraspace +
ftb chunks
ftb gui library
iron chest
lostcities
Mantle
Neat+
nuclear craft
obfuscate
smallships
storage drawers
Tconstruct
thermal expansion
thermal foundation
Twilightforest
waystones
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by PrincessOfEvil** [comment]
Ardite doesn't exist anymore. Check JEI for new recipes.

**Comment by Torpefy-ok** [comment]
> Ardite doesn't exist anymore. Check JEI for new recipes.

Ok thanks
