### ISSUE TITLE
Missing Furnace

### ISSUE THREAD

**Issue by AwildGeese** [SlimeKnights/TinkersConstruct#4514]
So i was playing on a normal minecraft world and i was about to get in tinker's construct first making the big furnace but i didnt find it and i dont know if there its no furnace anymore i tried to search if it was missing but i dont find anything

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.25
* Mantle: 1.6.97
* Tinkers Construct: 3.0.3.152

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I actualy dont know if its already there

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Just tinkers construct

**Comment by PrincessOfEvil** [comment]
No, it isn't.
