### ISSUE TITLE
Seared channels with liquid in them will reappear after being broken

### ISSUE THREAD

**Issue by DarkAngel22579** [SlimeKnights/TinkersConstruct#4516]
**Issue description:**
Seared channels with liquid in them will reappear after being broken.

Steps to reproduce:
- Place down a seared tank and fill with molten metal (copper)
- Place a line of seared channels leading into the tank, say 6 for example
- Pour molten metal into the seared channel at the end and wait for them all to fill up
- Starting at the back, break the channels one by one, observing that the channel previously broken reappears after breaking the channel in front of it

This can also be reproduce by breaking them in different orders, but this method should be 100% reliable.
This also happens with the scorched variants.

**If crashed, link to crash report (use a site such as pastebin):**
n/a

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.24
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.181

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Issue is not covered by the roadmap or "Whats New?".

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Can be reproduced with only Tinkers Construct.

Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Edit:** I'm helping Shiny with parts of the books so thats why I have this version :P

**Comment by KnightMiner** [comment]
Fixed in 3.0.4.194
