### ISSUE TITLE
Missing Ardite

### ISSUE THREAD

**Issue by howroyd** [SlimeKnights/TinkersConstruct#4520]
**Issue description:**
New to hosting servers so not 100% sure if this is an issue at my end or with TC.  Apologies if it's my fault.

Ardite, of any description (ore, ingots, blocks, etc), just don't seem to exist in MC at all.  JEI finds nothing and if I do `/give <me> tc` nothing ardite related shows up at all as a match.
![image](https://user-images.githubusercontent.com/4547783/121067148-9d34d400-c7c2-11eb-9400-411ec4dfa010.png)

Cobalt shows up fine, I can mine the ore and smelt it in the smeltery.  No issue with cobalt.

Also, putting the `Materials and you: Vol 1` into the crafting bench should apparently turn it into the `vol 2`?  This doesn't appear to work and again in JEI, etc, the only book that shows is `vol 1`.

![image](https://user-images.githubusercontent.com/4547783/121069325-411f7f00-c7c5-11eb-9025-d485532cac65.png)

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: Mantle-1.16.5-1.6.103.jar
* Tinkers Construct: TConstruct-1.16.5-3.0.4.171.jar
* Java: OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Not that I can see

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
The only mods (in `/data/mods/`) I have on this server are:
```
jei-1.16.5-7.7.0.104.jar
journeymap-1.16.5-5.7.1.jar
Mantle-1.16.5-1.6.103.jar
modnametooltip_1.16.2-1.15.0.jar
Placebo-1.16.4-4.5.0.jar
TConstruct-1.16.5-3.0.4.171.jar
```

**Comment by ShinyPorygon** [comment]
Reread whats new. Ardite is moving to natura.

**Comment by howroyd** [comment]
...I'm an idiot. Thank you
