### ISSUE TITLE
Create incompatibility: Crash when certain tinker tables are in a schematic

### ISSUE THREAD

**Issue by globalcringe** [SlimeKnights/TinkersConstruct#4521]
**Issue description:**
When using Create's schematic item with any of the following blocks in it:
Crafting Station 
Tinker Station
Part Builder
Tinker's Anvil
the game will immediately crash upon previewing the schematic. All of these blocks can show items on the top, so perhaps that's related?

**If crashed, link to crash report (use a site such as pastebin):**
Crafting Station: https://pastebin.com/dnEiREme
Tinker Station: https://pastebin.com/qZ28FSGk
Part Builder: https://pastebin.com/c4ciFJKd
Tinker's Anvil: https://pastebin.com/ukQeFfTw

**Versions:**
* Minecraft: 1.16.5
* Forge: Tested on both 36.1.0 (current recommended) and 36.1.25 (current latest)
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.171

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Confirmed.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Create 0.3.1c (obtained from https://www.curseforge.com/minecraft/mc-mods/create/files/3278516 )
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

Steps to reproduce:
Get a schematic and quill, and right-click on any of the above blocks twice, then right-click again elsewhere to save it.
Name it whatever and click "Save & upload immediately".
Then, right-click anywhere to cause a crash.

**Comment by TheOnlyMann** [comment]
Seems like rendering incompatibility of create's schematics. 
I had this issue a while back with Pneumaticraft, there is a way to avoid the crash from other mod's side but its best for the create dev to fix it i guess.
https://github.com/TeamPneumatic/pnc-repressurized/issues/812

**Comment by KnightMiner** [comment]
This is either a forge bug or a create bug, not sure yet. All we do is call a forge method. The fact that forge method crashes when its not the main client world is absolutely stupid because that means we have to add a ton of hacky client only code to detect that. There might be something create can do about this, but I somehow doubt it.

Have you reported this to Create? One of the devs of that mod added the line in forge causing this crash, so I'll leave it up to them to decide how this gets fixed.

**Comment by globalcringe** [comment]
Create devs report this as fixed in the dev version, so it's just a waiting game now.

**Comment by globalcringe** [comment]
Create released update 0.3.2 which fixes this issue, so I'm gonna close this.
