### ISSUE TITLE
[1.16.5] Tasty trait can still function after tool breaks

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#4523]
**Issue description:**
Pig Iron's Tasty trait, allowing the player to eat their tool at the cost of durability, can continue to work even if the tool cannot spare the durability and is in broken state.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.171

This issue is not mentioned on the roadmap or "What's New?"

This issue can be reproduced with only Tinkers' and Mantle.

**Comment by KnightMiner** [comment]
Fixed in 3.0.4.194
