### ISSUE TITLE
[1.12.2] slimeknights.tconstruct.library.client.MaterialRenderInfo causing crash on startup?

### ISSUE THREAD

**Issue by zenithpheonix** [SlimeKnights/TinkersConstruct#4528]
I've had this issue a couple of times before, where the modpack I created has a similar crash. I thought it would fix it by unzipping TinkersConstruct.zip and then tried reinstalling it as well, but it didn't work. I tried booting the modpack without Tinkers and still got the same error. Minecraft registers the crash as Error Code:0 despite the crash report saying its the renderinfo. I also tried adding the mixin source to see if that was the issue, but that didn't help either.

https://pastebin.com/E2iEMAws

**Versions:**
* Minecraft: 1.12.2
* Forge: 0.174.1.22
* Mantle: 1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.13.0.183

**Comment by KnightMiner** [comment]
Duplicate of #4441. The fact it still happened when you uninstalled the mod was a clue the mod is not to blame

**Comment by zenithpheonix** [comment]
Tried following solution for #4441, still receiving same error as well as error code.

**Comment by zenithpheonix** [comment]
Issue resolved, latest Lucraft version conflicting with Tconstruct

**Comment by KnightMiner** [comment]
Yes, this is a bug with Lucraft. There is nothing we can do, the only reason Tinkers is even mentioned is because its a bug with their Tinkers compat.
