### ISSUE TITLE
It is a small thing but would make things look better

### ISSUE THREAD

**Issue by Glittersword** [SlimeKnights/TinkersConstruct#4530]
Could you add a corner connecter piece for the drying rack?  The way it is now you go to the end of the wall one way you can't connect to a line going down the connecting wall and it just looks unfinished. Just needs to be decorative and not functional with variants that will match the existing Drying racks in coloration and texture.

**Comment by ShinyPorygon** [comment]
Is this for 1.12? Drying racks are not in 1.16 as they are moving to natura which isn't released yet.

**Comment by KnightMiner** [comment]
Yeah, 1.12 is getting no new featues. There are plenty of mods adding such a corner piece, such as chisel and bits.

For 1.16, Tinkers no longer has drying racks.
