### ISSUE TITLE
Bronze ingot is mistagged as forge:ingots/silicon_bronze

### ISSUE THREAD

**Issue by jmdev91** [SlimeKnights/TinkersConstruct#4531]
**Issue description:**
Bronze ingots from this mod won't work with recipes in other mods because instead of being tagged as forge:ingots/bronze they're tagged as forge:ingots/silicon_bronze.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:1.16.5
* Forge: 36.1.0
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.171 (default configs, not as part of a modpack)

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes, in that you can see that the tag is wrong, but it only causes issues when other mods use forge:ingots/bronze in their recipes (such as Thermal and Mekanism).

Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by ShinyPorygon** [comment]
Tinkers bronze is not other mods bronze. Tinkers bronze is silicon bronze.

**Comment by jmdev91** [comment]
What's the point of that? It's exactly the same recipe as other forms of bronze, just done in the smeltery. This mod has always played rather well with other mods, so why draw a line in the sand here?

**Comment by ShinyPorygon** [comment]
It's not the same recipe? It uses sand. Perhaps you should investigate further as you didn't do much research.

**Comment by jmdev91** [comment]
Yeah, my bad. Something must have been bugging on me because I was trying to find it in backwards order and neither Thermal's nor Mekanism's variant gave me a smeltery listing. I'm seeing it now, after a restart.
