### ISSUE TITLE
Unable to craft items with crafting station

### ISSUE THREAD

**Issue by TurtleCreater** [SlimeKnights/TinkersConstruct#4533]
**Issue description:**
When I attempt to craft any item using a crafting station, a chat message appears saying that the player currently cannot craft the item. This occurs for both modded and vanilla items, but for whatever reason it allows crafting if the player holds the shift key (using default keybinds).
Additionally, if this is intended (as there was nothing logged in the server console about this when i found it) then a) it can be avoided by holding shift and b) please add some way to turn this off. the only game rule I found talking about limited crafting was set to false and it changed nothing, and I could find nothing in config files regarding this.
**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.23
* Mantle: 1.6.109 
* Tinkers Construct: 3.0.4.194

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
As far as I can tell, this issue is on neither the roadmap or any changelog
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
This can be reproduced using only Tinkers Construct and mantle
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by KnightMiner** [comment]
This is not intentional, you saw the logic in place for if someone adds a player sensitive recipe and you do not have access to it. However, you should have access to the recipe, so the message was wrong.

**Comment by KnightMiner** [comment]
Fixed in 3.0.4.197, should appear on curseforge any minute
