### ISSUE TITLE
New configuration option to disable materials, if possible.

### ISSUE THREAD

**Issue by AbsorbingSafe11** [SlimeKnights/TinkersConstruct#4534]
My idea is related to a problem, in which myself and many other player will only use the cheapest tool they can. I understand much work was put into balancing (I really like the new mending concept, over moss) and no material is too unbalanced compared to vanilla. However, if not too difficult or time consuming, can a material disabling feature be added to the config?

Preferably the solution I would like, is for an option in the config for disabling any material set to be hidden in JEI.
(as that config option for material hiding helps very much and works very well)

Alternatives I have considered, would be a white/black list for materials tool parts can be made from and/or an option in the config for disabling specific parts in specific tools. (example, disabling cobblestone for hammer heads and plates)

**Additional context**
None of the config changes would need to effect Creative players, and I hope I made this issue correctly as I am not very good at using GitHub. (also, sorry if I was asking for something annoying or difficult to add)

**Versions:**
* Minecraft: 1.16.5
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
I read the Contributing Guidelines, the roadmap, and the F.A.Q, but couldn't find anything relating to my issue. Also, I am unable to properly use Discord and I had trouble finding the Whats New page. (sorry if this issue was listed somewhere and/or I was supposed to find the solution elsewhere)

**Comment by KnightMiner** [comment]
You an disable materials using datapacks. Config is redundant. You can also disable just one stat type if you wish
