### ISSUE TITLE
Cant alloy Hepatizon in foundry

### ISSUE THREAD

**Issue by campbebj** [SlimeKnights/TinkersConstruct#4535]
**Issue description:** Cant alloy Hepatizon in my foundry. 
![2021-06-16_11 06 08](https://user-images.githubusercontent.com/14897652/122270319-0ab3c500-ce93-11eb-9c16-ee1a3e4a5c89.png)
That is a block of cobalt, copper, and multiple blocks of obsidian. (the recipe from JEI says it only requires smaller amounts of those 3 items)

**If crashed, link to crash report (use a site such as pastebin):**
No crash

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.171

**Confirm below that this issue is not covered on the roadmap or "Whats New?"** 
Hepatizon is claimed to be present.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
reproed with just tinkers

**Comment by PrincessOfEvil** [comment]
Foundry cannot alloy.

**Comment by campbebj** [comment]
Strange. this needs better documented. as i couldnt figure that out, and i thought i had to use a foundry to use blaze fluid.

**Comment by KnightMiner** [comment]
JEI shows you which blocks can alloy in the catalysts area. As for needing better documentation, you are the one playing an alpha. Want documentation? Wait for the release.

**Comment by campbebj** [comment]
i didnt see anything in the "whats new" the in game books, or the readme. a one liner saying that foundrys cant alloy or that only smelterys can alloy would be best.


Giving feedback since the documentation should be improved as part of the alpha proces as well.

**Comment by KnightMiner** [comment]
From "[Whats New](https://github.com/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3)" which you were linked on the new issue screen:

> **Foundry**
> * Nether smeltery variant
> * Aids in nether survival, crafted from basalt/gravel, magma cream, and soul sand
> * Requires the frame and floor corners to build, but has increased capacity
> * Cannot alloy and lower ore multiplier, but ores give byproducts

You were given documentation out of game, and in game in JEI as I told you. You choose to ignore both.

I don't need feedback saying that the in game books should be finished, I know they should be and we have team members working hard on them. If you don't want to read the resources we provide, don't play the alphas and wait for the books to be done.

**Comment by campbebj** [comment]
Thanks for pointing it out. i missed it in the "whats new" 

My point with the JEI was that it was confusing.

**Comment by KnightMiner** [comment]
JEI is confusing. Its a recipe viewer, not a tutorial. Which is why JEI is not going to be our only documentation. It just is the best right now.
