### ISSUE TITLE
Tinkers construct recipe

### ISSUE THREAD

**Issue by Spin5123** [SlimeKnights/TinkersConstruct#4536]
Hi I am running an all the mods 1.6.10 server and in the server i cannot craft the tool heads to make the moulds if i hover over the pickaxe head or broad blade head or any such tools it shows up as item.tconstruct.part.missing_info i cannot make the tool heads itself so cannot make the moulds so the smelter is pretty useless how can i fix this issue 

**Versions:**
* Minecraft:1.16.5
* Forge: 36.1.31
* Mantle: 1.16.5-1.6.103
* Tinkers Construct: 1.16.5-3.0.4.171

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
confirm

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
. All the mods 6
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by PrincessOfEvil** [comment]
We don't do issue reports about modpacks, either show it to the people who made the modpack or replicate with a minimal mod list.
