### ISSUE TITLE
Tinkers Bows can't be drawn, can't fire arrows/bolts

### ISSUE THREAD

**Issue by bigyihsuan** [SlimeKnights/TinkersConstruct#4538]
**Issue description:** All bows, after crafting, cannot be drawn. It cannot shoot any arrows, neither vanilla nor TiC. Using the bow as a melee weapon damages it as usual. Vanilla bows work like vanilla.

Shotbows and Longbows have their crosshair stuck at a square, and the crossbow is stuck on its "open" position.

**If crashed, link to crash report (use a site such as pastebin):** N/A

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
* PlusTiC: 8.0.3

**Modpack:** [CMFR-MC Modpack v7.0](https://www.technicpack.net/modpack/cmfr-mc-modpack.1857528)

![2021-06-17_19 10 12](https://user-images.githubusercontent.com/12767476/122483148-f01b4200-cf9f-11eb-9b80-b470fcb15762.png)

![2021-06-17_19 13 19](https://user-images.githubusercontent.com/12767476/122483217-180aa580-cfa0-11eb-9de1-337d80b95dd0.png)

![2021-06-17_19 17 12](https://user-images.githubusercontent.com/12767476/122483459-a2530980-cfa0-11eb-9b38-5356135b34e4.png)

![2021-06-17_19 16 46](https://user-images.githubusercontent.com/12767476/122483442-92d3c080-cfa0-11eb-82a4-12ea09e78eb4.png)

![2021-06-17_19 17 51](https://user-images.githubusercontent.com/12767476/122483496-bbf45100-cfa0-11eb-8a2a-02794621fa07.png)

**Comment by KnightMiner** [comment]
You ignored half the issue template. Answer again with the missing half filled in.

**Comment by KnightMiner** [comment]
Closing for lack of response. Answer the questions you skipped if you want to reopen.
