### ISSUE TITLE
Copper Ingot Recipe Tag Issue

### ISSUE THREAD

**Issue by zachsai** [SlimeKnights/TinkersConstruct#4539]
**Issue description:**
The tinkers construct copper ingot recipe has tags for the forge copper nugget for all slots except the middle one
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
3.0.4.197
* Minecraft:
* 1.16
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
no
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
no, use create mod
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by ShinyPorygon** [comment]
From my understanding this is a "universal standard" if you have more than one mod that adds a specific ingot the recipe changes to this. It is so you can make a specific ingot from a specific mod, you can have this effect go away if you have only one type of an ingot.

Also fully fill out the form even if you do not think the information is vital.

**Comment by zachsai** [comment]
what im saying is you did it correctly with the forge tags, except for the middle nugget in a crafting grid

**Comment by ShinyPorygon** [comment]
It's supposed to be like that if you have more than one mod installed that adds an ingot.

**Comment by StaticPH** [comment]
> what im saying is you did it correctly with the forge tags, except for the middle nugget in a crafting grid

When you have multiple variants of the same metal, the middle nugget is often used to determine which ingot variant you get as the crafting result. i.e., with a copper nugget from Immersive Engineering in the center, and copper nuggets from Mekanism and Tinkers Construct in the other 8 slots, the craft should result in an Immersive Engineering copper ingot. If you swap the Immersive Engineering nugget with any of the Mekanism nuggets, the result should be a Mekanism copper ingot.
If the middle nugget was tagged, the output would (presumably) be whichever copper ingot is first in the list of items with the matching ingot tag, as opposed to a particular variant the player might have wanted instead.
I hope that helps clarify why it is intended and desirable that the central copper nugget remains without Forge's copper nugget tag.
