### ISSUE TITLE
Ingot Compatibility

### ISSUE THREAD

**Issue by zachsai** [SlimeKnights/TinkersConstruct#4540]
**Is your idea related to a problem? Please describe.**
no
**Describe the solution you'd like**
Ingots to add for compatibility which would be nice:

Netpunium Ingot (Aquaculture 2)
Zinc & Brass (Create)
All `Upgraded Netherite` ingots with their intrinsic benefit added to the tool when the source ingot is apart of the tool

**Describe alternatives you've considered**

**Additional context**

**Versions:**
* Minecraft:
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**

**Comment by ShinyPorygon** [comment]
This would be an addons job. Also properly fill out the forms rather you think it needs it or not.
