### ISSUE TITLE
Config 

### ISSUE THREAD

**Issue by zachsai** [SlimeKnights/TinkersConstruct#4543]
**Issue description:**
Please add the ability to disable the casting and the making of certain parts so we can disable types of tools we do not want allowed when making a modpack.

I want to disallow the ability to make excavators, sledge hammers, vein hammers
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by ShinyPorygon** [comment]
https://minecraft.fandom.com/wiki/Data_Pack

Still not filling out the template properly.
