### ISSUE TITLE
Placing a seared tank disabled the melter GUI

### ISSUE THREAD

**Issue by aetherpirate** [SlimeKnights/TinkersConstruct#4545]
Placing a seared tank disables melter GUI

There is no crash

A user reported this issue on my server (88ish mods)

I setup a test pack in MultiMC with just these mods:

MC 1.16.5
1.16.5-forge-36.1.32
mantle-1-16-5-1-6-109
tconstruct-1-16-5-3-0-4-197
jei-1-16-5-7-7-0-106
![chatpic](https://user-images.githubusercontent.com/11506409/122813436-f3b11080-d2a0-11eb-843c-ca0b1d31150b.PNG)

**Comment by ShinyPorygon** [comment]
![image](https://user-images.githubusercontent.com/35193007/122814002-9ff2f700-d2a1-11eb-8073-0dec434c9a3d.png)
Works fine for me 
Same versions you have, are you sure you don't have any more mods? any performance mods?

**Comment by aetherpirate** [comment]
In my little test pack in MultiMC I only had the mods I listed. I'll try it again in a few min and see if I can get more info.

**Comment by KnightMiner** [comment]
You could also try providing game logs, if the UI is failing to open, there likely is an error being produced somewhere.

**Comment by aetherpirate** [comment]
Have more info. If you try to interact with the GUI with the same inventory slot selected that the tank formerly occupied, it does not work. Other slots do. 
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/6689013/debug.log)
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/6689014/latest.log)

**Comment by KnightMiner** [comment]
Are you actively holding a tank while trying to interact with the melter UI? If so, that is your problem. The tanks have a fluid capability, which means the melter interpreted your right click as trying to fill/drain the melter with the tank using the melter's internal tank

**Comment by aetherpirate** [comment]
No, I *was* holding a tank before trying to interact with the GUI. It is acting like I still am, after I place the tank down.

**Comment by KnightMiner** [comment]
Ah, I see, its a dumb forge issue not properly invalidating fluid handlers for an empty stack, tanks are probably just the first case to hit this.

Probably still worth tweaking the UI to not block the UI if no fluid transfer happens, but thats a later fix.

**Comment by KnightMiner** [comment]
Fixed in 3.1.0.231
