### ISSUE TITLE
 Will be secret weapons in the Tinkers Construct 1.16.5?

### ISSUE THREAD

**Issue by davigsm** [SlimeKnights/TinkersConstruct#4546]
In 1.7.10 we have the Cutlass
In 1.12.2 we have the Bane of Pigs
In 1.16.5 what we will have?

i know the mod is still in development but it would be nice if they add these secret weapons, they are interesting for modpack makers who want powerful weapons and add recipes for them.

I appreciate the attention.

![Sem título-1](https://user-images.githubusercontent.com/73342935/122918273-5358fb80-d335-11eb-8508-f78e57c8de3b.png)
.
.
.
.
![mod pack dos brodi](https://user-images.githubusercontent.com/73342935/122918400-78e60500-d335-11eb-85b0-fe7ff5badc79.png)

By Modpack dos Brodi team

**Comment by ShinyPorygon** [comment]
Please follow the template that was provided when you went to create a new issue. We can't possibly know what you want without following it. If it didn't appear hit "new issue" again and copy it from there.

**Comment by SayuuAndTheStrawberryCake** [comment]
this is really cool

**Comment by KnightMiner** [comment]
Modpack makers can easily add these themselves. Its trivial to add a bunch of extra modifiers to the tool NBT, and to add custom OP materials with datapacks, they should just do that
