### ISSUE TITLE
Lapis not working to create luck modifier

### ISSUE THREAD

**Issue by StankSquatch** [SlimeKnights/TinkersConstruct#4547]
**Issue description:**
Was it changed to another material? Placing lapis into the Tinker Anvil along with a tool used to work to get the luck modifier. I tried using other materials like redstone and they worked fine.
**If crashed, link to crash report (use a site such as pastebin):**
No crash
**Versions:** 
* Minecraft: 1.16.5
* Forge: 
* Mantle: 
* Tinkers Construct: 3.0.2

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
It isn't, it says the luck modifier should be in, and I have seen it used on youtube videos, it doesn't say if the material has been changed though
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Playing in the All The Mods 6 modpack
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by PrincessOfEvil** [comment]
Yes it was. Check the JEI modifier tab.

**Comment by StankSquatch** [comment]
How do I do that? I tried checking in the Materials and you book and that modifier is absent

**Comment by KnightMiner** [comment]
> Check the JEI modifier tab.

Same way you check any other recipe, usage on an input (such as a tool), or view all recipes

**Comment by StankSquatch** [comment]
Ok, thanks so much, I figured it out, I didn't know I could do that so it should help with other modifier recipes too, thanks bruddah, you a real G
