### ISSUE TITLE
Add Necrotic Bone Block

### ISSUE THREAD

**Issue by g0urra** [SlimeKnights/TinkersConstruct#4548]
**Is your idea related to a problem? Please describe.**
Space issues.

**Describe the solution you'd like**
Add a Necrotic Bone Block made of 9 Necrotic Bone in a 3x3 pattern.

**Describe alternatives you've considered**
None.

**Additional context**
None

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.31
* Mantle: 1.6.109
* Tinkers Construct: 3.0.4.197

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
Did not see this.

**Comment by TheOnlyMann** [comment]
![image](https://user-images.githubusercontent.com/82017462/123104415-e303c480-d471-11eb-8da6-a358cde7535c.png)

**Comment by g0urra** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/82017462/123104415-e303c480-d471-11eb-8da6-a358cde7535c.png)

I don't see what this has to do with anything? I said Necrotic Bone Block, not Bone Block.

**Comment by KnightMiner** [comment]
Their point is such a block would be inconsistent with the vanilla bone block, as the vanilla one uses bone meal, not bones.

I have more plans for necrotic bones in the future, don't worry. A block like the vanilla one is likely to be added.
