### ISSUE TITLE
1.16 server GUI never shows

### ISSUE THREAD

**Issue by Ergush** [SlimeKnights/TinkersConstruct#4549]
**Issue description:**
I am working on setting up a 1.16.5 server at home for LAN play only. Server is set up with only Mantle and Tinkers Construct. The server GUI pops up, but is EXTREMELY laggy or unresponsive entirely. Continues to blink and go to Not Responding.

**If crashed, link to crash report (use a site such as pastebin):**
No crash report. 

**Versions:**
* Minecraft: up to 1.17 (server folder has minecraft_server.1.16.5.jar)
* Forge: forge-1.16.5-36.1.0.jar
* Mantle: Mantle-Mod-1.16.5.jar
* Tinkers Construct: Tinkers-Construct-Mod-1.165.5.jar 

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I have not been able to locate any documentation on this issue anywhere.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Must have Mantle. Just Tinkers causes a "Mods not loading" crash report. 

Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

Final note: I am giving up on loading this for now, will use other mods in place of the things we want on the server.

**Comment by KnightMiner** [comment]
None of those are official builds. We do not give support for mods downloaded from anywhere except Github and CurseForge.

Also, we have many people testing this mod on servers and none have reported unbearable lag. So I assume you downloaded malware which is what is causing so much lag.

**Comment by Ergush** [comment]
Thank you for the info, apparently my son does not follow directions well...

**Comment by Ergush** [comment]
Not sure if you still look at ones you tag invalid, but I deleted the old server and started up a new one with all new files:

https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html  <--- forge download  (file is  forge-1.16.5-36.1.32.jar)

https://www.curseforge.com/minecraft/mc-mods/mantle/download/3352484 <--- Mantle Download (file is Mantle-1.16.5-1.6.109.jar)

https://www.curseforge.com/minecraft/mc-mods/tinkers-construct <--- Tinkers download (File is TConstruct-1.16.5-3.0.4.197.jar)

As you can see, all three files are from Curse Forge, and I am still experiencing all of the lag problems. Current issue is GUI never opens (within 5 minutes of starting)

**Comment by Insane96** [comment]
How do you run the server?

**Comment by Ergush** [comment]
Double click on the forge file in the server folder I have everything in.

**Comment by Insane96** [comment]
Do you have discord so we don't flood this issue's comments?

**Comment by Ergush** [comment]
ErgushCF#5811

**Comment by Ergush** [comment]
Just adding a final closing comment:

Insane and I were able to successfully get my server up and running. Thank you so much for the support Insane!
