### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo Exit Code: -1

### ISSUE THREAD

**Issue by bogboybingles** [SlimeKnights/TinkersConstruct#4550]
**Issue description:**
i cant find the issue

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: yes
* Mantle: yes
* Tinkers Construct: 

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  wings (wings-1.1.6-1.12.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  HatedMobsLoadingPlugin (hatedmobs-1.5.0.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.14.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/24/21 10:14 AM
Description: Initializing game

java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.library.client.MaterialRenderInfo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1165265360 bytes (1111 MB) / 1661992960 bytes (1585 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 156 mods loaded, 155 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                     | Source                                            | Signature                                |
	|:----- |:--------------------- |:--------------------------- |:------------------------------------------------- |:---------------------------------------- |
	| L     | minecraft             | 1.12.2                      | minecraft.jar                                     | None                                     |
	| L     | mcp                   | 9.42                        | minecraft.jar                                     | None                                     |
	| L     | FML                   | 8.0.99.99                   | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | forge                 | 14.23.5.2855                | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | advancedrocketrycore  | 1                           | minecraft.jar                                     | None                                     |
	| L     | obfuscate             | 0.4.2                       | minecraft.jar                                     | None                                     |
	| L     | srm-hooks             | 1.12.2-1.0.0                | minecraft.jar                                     | None                                     |
	| L     | vclothes              | 2.9.6                       | [1.12.2] Valtiel s Clothes Mod-2.3.1.jar          | None                                     |
	| L     | a_man_with_plushies   | 1.0.6                       | A Man With Plushies 1.12.2 (1.0.6).jar            | None                                     |
	| L     | actuallybaubles       | 1.1                         | ActuallyBaubles-1.12-1.1.jar                      | None                                     |
	| L     | advancedrocketry      | 1.7.0.-232                  | AdvancedRocketry-1.12.2-1.7.0-232-universal.jar   | None                                     |
	| L     | ageofweapons          | 0.13.5                      | Age of Weapons 1.12.2  (v.0.13.5).jar             | None                                     |
	| L     | animepets             | 2.1.5                       | AnimePets.jar                                     | None                                     |
	| L     | aquaculture           | 1.6.8                       | Aquaculture-1.12.2-1.6.8.jar                      | None                                     |
	| L     | armorsouls            | 1.0.1                       | Armor Souls 1.0.1 Forge.jar                       | None                                     |
	| L     | autoreglib            | 1.3-32                      | AutoRegLib-1.3-32.jar                             | None                                     |
	| L     | baubles               | 1.5.2                       | Baubles-1.12-1.5.2.jar                            | None                                     |
	| L     | bibliocraft           | 2.4.5                       | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| L     | biomesoplenty         | 7.0.1.2441                  | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar     | None                                     |
	| L     | moreswords            | 1.0.0                       | BlockSword+1.12.2+Bye BlockSword.jar              | None                                     |
	| L     | bloodmagic            | 1.12.2-2.4.3-105            | BloodMagic-1.12.2-2.4.3-105.jar                   | None                                     |
	| L     | blue_skies            | 1.1.3                       | blue_skies-1.12.2-v1.1.3.jar                      | None                                     |
	| L     | blur                  | 1.0.4-14                    | Blur-1.0.4-14.jar                                 | None                                     |
	| L     | bonsaitrees           | 1.1.4                       | bonsaitrees-1.1.4-b170.jar                        | None                                     |
	| L     | bookshelf             | 2.3.590                     | Bookshelf-1.12.2-2.3.590.jar                      | None                                     |
	| L     | bookworm              | 1.12.2-2.5.2.1              | bookworm-1.12.2-2.5.2.1.jar                       | None                                     |
	| L     | careerbees            | 1.0                         | careerbees-0.4.0.jar                              | None                                     |
	| L     | catwalks              | 1.12.2-4.0.45               | catwalks-1.12.2-4.0.45.jar                        | None                                     |
	| L     | chameleon             | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| L     | chisel                | MC1.12.2-1.0.2.45           | Chisel-MC1.12.2-1.0.2.45.jar                      | None                                     |
	| L     | chiselsandbits        | 14.33                       | chiselsandbits-14.33.jar                          | None                                     |
	| L     | chococraft            | 0.9.9.0                     | chococraft_1.12.2-0.9.9.0.jar                     | None                                     |
	| L     | classyhats            | %VERSION%                   | classyhats-1.6.0.jar                              | None                                     |
	| L     | claysoldiers          | 3.0.0-beta.2                | ClaySoldiersMod-1.12.2-3.0.0-beta.2.jar           | None                                     |
	| L     | codechickenlib        | 3.2.3.358                   | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | None                                     |
	| L     | cofhcore              | 4.6.6                       | CoFHCore-1.12.2-4.6.6.1-universal.jar             | None                                     |
	| L     | cofhworld             | 1.4.0                       | CoFHWorld-1.12.2-1.4.0.1-universal.jar            | None                                     |
	| L     | colored_water         | 1.12.2-b37                  | ColoredWater-1.12.2-b37.jar                       | None                                     |
	| L     | conarm                | 1.2.5.10                    | conarm-1.12.2-1.2.5.10.jar                        | None                                     |
	| L     | connectedglass        | 1.0.8                       | connectedglass-1.0.8-mc1.12.jar                   | None                                     |
	| L     | cosmeticarmorreworked | 1.12.2-v5a                  | CosmeticArmorReworked-1.12.2-v5a.jar              | None                                     |
	| L     | miccw                 | 1.0                         | CosmicArmoury-1.6.55.jar                          | None                                     |
	| L     | ctm                   | MC1.12.2-1.0.2.31           | CTM-MC1.12.2-1.0.2.31.jar                         | None                                     |
	| L     | customnpcs            | 1.12                        | CustomNPCs_1.12.2-(05Jul20).jar                   | None                                     |
	| L     | cyclopscore           | 1.6.7                       | CyclopsCore-1.12.2-1.6.7.jar                      | None                                     |
	| L     | cycp                  | 1.0                         | cycp_1.12-1.0.jar                                 | None                                     |
	| L     | darkutils             | 1.8.230                     | DarkUtils-1.12.2-1.8.230.jar                      | None                                     |
	| L     | props                 | 2.6.3.7                     | Decocraft-2.6.3.7_1.12.2.jar                      | None                                     |
	| L     | display               | 1.2.4                       | Display-1.2.4.jar                                 | None                                     |
	| L     | dragonmounts          | 1.12.2-1.6.3                | DragonMounts2-1.12.2-1.6.3.jar                    | None                                     |
	| L     | drones                | 0.3.1                       | Drones-0.3.1.jar                                  | None                                     |
	| L     | dc                    | Beta 1.0.0                  | DungeonCraft Beta 1.0.0.jar                       | None                                     |
	| L     | engineeredgolems      | 1.2                         | Engineered Golems-1.2a.jar                        | None                                     |
	| L     | everlastingabilities  | 1.5.3                       | EverlastingAbilities-1.12.2-1.5.3.jar             | None                                     |
	| L     | exoticbirds           | 1.0                         | Exotic Birds 1.12.2-3.2.0.jar                     | None                                     |
	| L     | golems                | 7.1.9                       | ExtraGolems-1.12-7.1.9.jar                        | None                                     |
	| L     | extreme_weapons       | 1.0.0                       | ExtremeWeapons B4.0 1.12.2Forge.jar               | None                                     |
	| L     | fairylights           | 2.1.10                      | fairylights-2.2.0-1.12.2.jar                      | None                                     |
	| L     | ferdinandsflowers     | 1.10.4.1                    | Ferdinand's Flowers-1.12.x-1.10.4.1.jar           | None                                     |
	| L     | flatcoloredblocks     | mc1.12-6.8                  | flatcoloredblocks-mc1.12-6.8.jar                  | None                                     |
	| L     | forestry              | 5.8.2.387                   | forestry_1.12.2-5.8.2.387.jar                     | None                                     |
	| L     | forgelin              | 1.8.4                       | Forgelin-1.8.4.jar                                | None                                     |
	| L     | fossil                | 8.0.5                       | fossilsarcheology-8.0.5.jar                       | None                                     |
	| L     | furenikusroads        | 1.1.10                      | Fureniku's Roads-1.1.10.jar                       | None                                     |
	| L     | cfm                   | 6.3.1                       | furniture-6.3.1-1.12.2.jar                        | None                                     |
	| L     | glassential           | 1.1.0                       | glassential-1.12.2-1.1.0.jar                      | None                                     |
	| L     | swords__guns          | 5.0                         | Great_Swords_AV_5.0.0.jar                         | None                                     |
	| L     | guideapi              | 1.12-2.1.8-63               | Guide-API-1.12-2.1.8-63.jar                       | None                                     |
	| L     | cgm                   | 0.15.3                      | guns-0.15.3-1.12.2.jar                            | None                                     |
	| L     | hatedmobs             | 1.5.0                       | hatedmobs-1.5.0.jar                               | None                                     |
	| L     | hatstands             | 1.0.0                       | hatstands-1.0.0-1.12.2.jar                        | None                                     |
	| L     | heroesexpansion       | 1.12.2-1.3.5                | HeroesExpansion-1.12.2-1.3.5.jar                  | None                                     |
	| L     | heroicarmory          | 1.1.3                       | heroicarmory-1.2.0.jar                            | None                                     |
	| L     | furniture             | 2.0.3                       | How'BoutThatFurniture-2.0.3.jar                   | None                                     |
	| L     | httymd                | 1.1.0_MC-1.12.2             | How-To-Train-Your-Minecraft-Dragon-Mod-1.12.2.jar | None                                     |
	| L     | ichunutil             | 7.2.2                       | iChunUtil-1.12.2-7.2.2.jar                        | None                                     |
	| L     | imageutils            | 1.0.5                       | ImageUtils-1.0.5-recommended.jar                  | None                                     |
	| L     | inventorypets         | 2.0.15                      | inventorypets-1.12-2.0.15.jar                     | None                                     |
	| L     | inventorytweaks       | 1.63+release.109.220f184    | InventoryTweaks-1.63.jar                          | None                                     |
	| L     | ironbackpacks         | 1.12.2-3.0.8-12             | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| L     | ironchest             | 1.12.2-7.0.67.844           | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
	| L     | jojobadv              | 1.1.2                       | JojoBAdv-1.1.2 - 12.2.2.jar                       | None                                     |
	| L     | jojobizadv            | 0.5 - 1.12.2                | jojobizadv-2.1.jar                                | None                                     |
	| L     | librarianliblate      | 4.22                        | librarianlib-1.12.2-4.22.jar                      | None                                     |
	| L     | librarianlib          | 4.22                        | librarianlib-1.12.2-4.22.jar                      | None                                     |
	| L     | libvulpes             | 0.4.2.-83                   | LibVulpes-1.12.2-0.4.2-83-universal.jar           | None                                     |
	| L     | lucraftcore           | 1.12.2-2.4.14               | LucraftCore-1.12.2-2.4.14.jar                     | None                                     |
	| L     | magicbees             | 1.0                         | MagicBees-1.12.2-3.1.10.jar                       | None                                     |
	| L     | magic_doorknob        | 1.12.2-0.0.2.364            | MagicDoorknob-1.12.2-0.0.2.364.jar                | None                                     |
	| L     | malisiscore           | 1.12.2-6.5.1-SNAPSHOT       | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	| L     | malisisdoors          | 1.12.2-7.3.0                | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| L     | mantle                | 1.12-1.3.3.55               | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| L     | mca                   | 6.1.0                       | MCA-1.12.2-6.1.0-universal.jar                    | None                                     |
	| L     | medieval_craft        | 1.14.4                      | MedievalCraft-1.12.2-1.15.6.jar                   | None                                     |
	| L     | minergolems           | 2.1.1                       | minergolems-2.1.1.jar                             | None                                     |
	| L     | powersuits            | 1.12.2-1.0.46               | ModularPowersuits-1.12.2-1.0.46.jar               | None                                     |
	| L     | guilib                | $version                    | morepaintings-paintings-1.12.2-5.0.1.2.jar        | None                                     |
	| L     | paintingselgui        | $version                    | morepaintings-paintings-1.12.2-5.0.1.2.jar        | None                                     |
	| L     | morepaintings         | $version                    | morepaintings-paintings-1.12.2-5.0.1.2.jar        | None                                     |
	| L     | moreplayermodels      | 1.12.2                      | MorePlayerModels_1.12.2-(05Dec19).jar             | None                                     |
	| L     | msmlegacy             | @VERSION@                   | MoreSwordsLegacy-1.12.2-1.0.7.jar                 | None                                     |
	| L     | morph                 | 7.2.0                       | Morph-1.12.2-7.2.1.jar                            | None                                     |
	| L     | mo_swords             | v5                          | moSwords-1.12.2v5.jar                             | None                                     |
	| L     | mousetweaks           | 2.10                        | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
	| L     | mowziesmobs           | 1.5.8                       | mowziesmobs-1.5.8.jar                             | None                                     |
	| L     | mutantbeasts          | 1.12.2-1.0.2                | MutantBeasts-1.12.2-1.0.2.jar                     | None                                     |
	| L     | my_hero_academia      | 1.0.0                       | My Hero Alpha 0.1.3.1 (Bugfix).jar                | None                                     |
	| L     | mysticallib           | 1.12.2-1.10.0               | mysticallib-1.12.2-1.10.0.jar                     | None                                     |
	| L     | mysticalworld         | 1.12.2-1.9.8                | mysticalworld-1.12.2-1.9.8.jar                    | None                                     |
	| L     | neid                  | 1.5.4.4                     | NotEnoughIDs-1.5.4.4.jar                          | None                                     |
	| L     | numina                | 1.12.2-1.0.38               | Numina-1.12.2-1.0.38.jar                          | None                                     |
	| L     | openglider            | @VERSION@                   | OpenGlider-1.12.1-1.1.0.jar                       | None                                     |
	| L     | patchouli             | 1.0-23.6                    | Patchouli-1.0-23.6.jar                            | None                                     |
	| L     | pingdisplayer         | 1.12.2-1.6                  | pingdisplayer-1.12.2-1.6.jar                      | None                                     |
	| L     | pixelmon_clothes      | 1.2.3                       | pixelmonclothes-1.2.3.jar                         | None                                     |
	| L     | placebo               | 1.6.0                       | Placebo-1.12.2-1.6.0.jar                          | None                                     |
	| L     | psi                   | r1.1-78                     | Psi-r1.1-78.2.jar                                 | None                                     |
	| L     | ptrmodellib           | 1.0.5                       | PTRLib-1.0.5.jar                                  | None                                     |
	| L     | randomthings          | 4.2.7.4                     | RandomThings-MC1.12.2-4.2.7.4.jar                 | None                                     |
	| L     | redstoneflux          | 2.1.1                       | RedstoneFlux-1.12-2.1.1.1-universal.jar           | None                                     |
	| L     | xreliquary            | 1.12.2-1.3.4.796            | Reliquary-1.12.2-1.3.4.796.jar                    | None                                     |
	| L     | sanlib                | 1.6.3                       | SanLib-1.12.2-1.6.3.jar                           | None                                     |
	| L     | sanplayermodel        | 1.2.2                       | SanLib-1.12.2-1.6.3.jar                           | None                                     |
	| L     | baggablemobs          | 1.0.0                       | SBM-Baggable-Mobs-1.12.2-1.0.0b21.jar             | None                                     |
	| L     | sbmlizarddogo         | 1.12.2-1.0.0.20190112155428 | SBM-Lizard-Dogo-1.12.2-1.0.0.jar                  | None                                     |
	| L     | merpig                | 1.12.2-0.0.1.20190504132448 | SBM-Merpig-1.12.2-0.0.1b20190504132456.jar        | None                                     |
	| L     | secretroomsmod        | 5.6.4                       | secretroomsmod-1.12.2-5.6.4.jar                   | None                                     |
	| L     | simplylight           | 1.12.2-0.8.7                | simplylight-1.12.2-0.8.7.jar                      | None                                     |
	| L     | skyes_bakery          | 2.1.1                       | Skye's Bakery 2.1.1 for MC1.12.2.jar              | None                                     |
	| L     | spartanshields        | 1.5.4                       | SpartanShields-1.12.2-1.5.4.jar                   | None                                     |
	| L     | spartanweaponry       | beta 1.3.8                  | SpartanWeaponry-1.12.2-beta-1.3.8.jar             | None                                     |
	| L     | storagedrawers        | 5.2.2                       | StorageDrawers-1.12.2-5.4.2.jar                   | None                                     |
	| L     | strawgolem            | 1.3                         | strawgolem-1.4.1.jar                              | None                                     |
	| L     | sm                    | 1.1                         | Sunglasses and more 1.1.jar                       | None                                     |
	| L     | tconstruct            | 1.12.2-2.13.0.183           | TConstruct-1.12.2-2.13.0.183.jar                  | None                                     |
	| L     | thaumcraft            | 6.1.BETA26                  | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
	| L     | golems_thermal        | 7.1.5-0                     | Thermal-Golems-Addon-7.1.5-0.jar                  | None                                     |
	| L     | thermaldynamics       | 2.5.6                       | ThermalDynamics-1.12.2-2.5.6.1-universal.jar      | None                                     |
	| L     | thermalexpansion      | 5.5.7                       | ThermalExpansion-1.12.2-5.5.7.1-universal.jar     | None                                     |
	| L     | thermalfoundation     | 2.6.7                       | ThermalFoundation-1.12.2-2.6.7.1-universal.jar    | None                                     |
	| L     | toastcontrol          | 1.8.1                       | Toast Control-1.12.2-1.8.1.jar                    | None                                     |
	| L     | xat                   | 0.30                        | Trinkets and Baubles-0.30.1.jar                   | None                                     |
	| L     | tropicraft            | 7.1.9.115                   | tropicraft-MC1.12.2-7.1.9.115.jar                 | None                                     |
	| L     | twilightforest        | 3.11.1021                   | twilightforest-1.12.2-3.11.1021-universal.jar     | None                                     |
	| L     | ultimate_unicorn_mod  | 1.5.17                      | ultimate_unicorn_mod-1.12.2-1.5.17.jar            | None                                     |
	| L     | useless_sword         | 1.2.2                       | UselessSword-1.12.2-V1.2.2.jar                    | None                                     |
	| L     | vehicle               | 0.44.1                      | vehicle-mod-0.44.1-1.12.2.jar                     | None                                     |
	| L     | waystones             | 4.1.0                       | Waystones_1.12.2-4.1.0.jar                        | None                                     |
	| L     | mowzies_wings         | 1.0.0                       | wings-1.1.6-1.12.2.jar                            | None                                     |
	| L     | bauble_wings          | 1.0.0                       | wings-1.1.6-1.12.2.jar                            | None                                     |
	| UD    | mobends_wings         | 1.0.0                       | wings-1.1.6-1.12.2.jar                            | None                                     |
	| L     | wings                 | 1.1.6                       | wings-1.1.6-1.12.2.jar                            | None                                     |
	| L     | worldedit             | 6.1.10                      | worldedit-forge-mc1.12.2-6.1.10-dist.jar          | None                                     |
	| L     | zawa                  | 1.12.2-2.1.3                | zawa-1.12.2-2.1.3.jar                             | None                                     |
	| L     | immersiveengineering  | 0.12-98                     | ImmersiveEngineering-0.12-98.jar                  | None                                     |
	| L     | llibrary              | 1.7.20                      | llibrary-1.7.20-1.12.2.jar                        | None                                     |

	Loaded coremods (and transformers): 
wings (wings-1.1.6-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
HatedMobsLoadingPlugin (hatedmobs-1.5.0.jar)
  fr.uranoscopidae.hatedmobs.asm.HatedMobsTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.14.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1660/PCIe/SSE2'
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

**Comment by PrincessOfEvil** [comment]
Lucraft issue,

**Comment by bogboybingles** [comment]
THANK YOU I HAVE BEEN TRYING TO FIND AN ISSUE FOR SO LONG THANKS

**Comment by KnightMiner** [comment]
To keep things organized, duplicate of #4441
