### ISSUE TITLE
Tinkers anvil can only use alloys

### ISSUE THREAD

**Issue by MVethana** [SlimeKnights/TinkersConstruct#4551]
**Issue description:**
Tooltip for the anvil suggests that almost any metal can be used but in reality it seems that only "alloys" from tinkers work

* Minecraft: 1.16
* Forge: 36.1.16 & 36.1.31
* Mantle: 1.6.92 & 1.6.109
* Tinkers Construct: 3.0.3.144 & 3.0.4.197

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Tooltip states most metal blocks, "Whats New?" states "Recipe requires 3 metal blocks and 4 seared bricks"

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Attempted on Enigmatica 6 0.5 and 3.0.3.144 Standalone, issue still remains

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2521

**Comment by KnightMiner** [comment]
No clue what tooltip you are talking about. Alloys only is intentional, its called progression. I'll update the wiki page.

**Comment by MVethana** [comment]
Thanks for the clarification, this is the tooltip I was referring to
![image](https://user-images.githubusercontent.com/17278251/123318256-058eef80-d4fd-11eb-9622-c1d9bb068a01.png)

**Comment by KnightMiner** [comment]
That is not added by us. The first clue is its gold, all our item description tooltips are grey. Second clue is your pack literally has a line of code adding it.

Don't add faulty tooltips then ask us why the tooltip is not accurate.
