### ISSUE TITLE
Can't disable Wood Material with CraftTweaker

### ISSUE THREAD

**Issue by Darkorg69** [SlimeKnights/TinkersConstruct#4553]
**Issue description:** 

I'm building a modpack, which consists of removing all wooden\stone tools from the mod.

Removing stone as material seems OK:

`<recipetype:tconstruct:material>.removeByName("tconstruct:tools/materials/stone");` 
**Successfully removes all stone materials from the part builder.**

Removing wood as material on the other hand:

`<recipetype:tconstruct:material>.removeByName("tconstruct:tools/materials/wood");`
**Doesn't remove wood as a material and throws a warning:
No recipe with type: "tconstruct:material" and name: "tconstruct:tools/materials/wood"**

Probably I'm doing something wrong, rather than the mod having a bug, but I'm just too not knowing to know what to do, so I'm seeking help on how to remove wood as material.

**If crashed, link to crash report (use a site such as pastebin): Game doesn't crash, just throws warning.**

**Versions:**
* Minecraft: 1.16.5
* Forge: 1.16.5 - 36.1.32
* Mantle: 1.6.109
* Tinkers Construct: 3.0.4.197

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I can't 100% confirm that is not covered, but I confirm I looked through and didn't find anything related to this problem.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Only TConstruct and CraftTweaker are needed to reproduce the issue.

**Comment by KnightMiner** [comment]
Thats not at all how recipes work. Remove by name removes a recipe by name. There is no recipe named wood, there are actually 3 recipes based on whether you to use sticks, planks, or logs. Look in the JAR file for recipe names, or they should hopefully show in JEI when you use F3+H.

Also, I feel the need to emphasizes those are not materials, those are material recipes. In other words, you are not removing wood, you are preventing crafting wood in the part builder and repairing tools using wood. Fully removing wood so it does not show in JEI is one more step, but is not supported by CraftTweaker at this time (so you will need a proper datapack).

**Comment by Darkorg69** [comment]
Thanks for the fast answer.
Just one question, since disabling wood functionality would be a very bad idea, how I could probably make wooden tools useless or with 1 durability? Is it possible to be made by another mod (like CraftTweaker) or I need to change this in the mod source,
since recipes id's in JEI don't show up?

**Comment by KnightMiner** [comment]
Materials are just data in json. I suggest you read about datapacks on the Minecraft Wiki, then look inside the mod jar for the material JSONs. Most of them you can replace.

However, I also don't see much point making wood useless, we like to have all materials be useful in some form
