### ISSUE TITLE
Slimes not spawning on islands...

### ISSUE THREAD

**Issue by PequenoReptil** [SlimeKnights/TinkersConstruct#4559]
When I first created the world on 1.16.5, the spawns were normal. After some days of playing all of them stopped suddenly. Even undiscovered slime islands of all kinds. Regular slimes, skyslimes, etc.

playing on forge 36.1.0 and with the create mc mod

**Comment by PequenoReptil** [comment]
We had to afk for a long time (couple of in-game days) close to the islands and they went back to normal. Very strange.  Thank god it's solved for now

**Comment by PequenoReptil** [comment]
Still no spawns on islands that we discovered. Is it related to removing the congelated slime blocks or messing around with the fluids?

**Comment by ShinyPorygon** [comment]
Due to a github bug you missed the template. Try opening a new issue and grabbing the template and properly fill out the template.

**Comment by KnightMiner** [comment]
Note that slime islands use the exact same logic to change spawns as nether fortresses do. I really doubt they would stop working and nether fortresses would keep working. Probably another mod at play here, which that template will help answer if you follow it

**Comment by KnightMiner** [comment]
Closing as #4560 was opened.
