### ISSUE TITLE
No slime spawns on islands

### ISSUE THREAD

**Issue by PequenoReptil** [SlimeKnights/TinkersConstruct#4560]
**Issue description:**

No slime spawns on every type of island. Islands that I've removed some congealed blocks simply don't spawn and undiscovered islands just spawn one small slime and never again. I've tried AFKing close to them, on them, some chunks away, but nothing happened apart from the occasional "1 small slime spawn and nothing more". The funny thing is that our server had normal spawns when we created it. Some days of playing later this issue began to occur. Currently playing with the Create MC mod on 0.3.1 (which has nice integration with tinkers actually! The copper ore is shared between both mods), along with waystones 7.4.0, travellers backpack 5.4.2 and twilight forest 4.0.490. Don't really know if entering the twilight zone for the first time made the spawns bug out. Dimensions are always weird.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.109
* Tinkers Construct: 3.0.4.197

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
...

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Can't really say so, since playing with other mods initially didn't have any impact on the slime spawns, but I'll try entering the twilight dimension on a new world to see if the spawns are broken and try to prove my hypothesis, but I have no clue about what's happening

**Comment by embeddedt** [comment]
What's your view-distance set to in `server.properties`? If it's anything less than 10, spawning can be inconsistent.

**Comment by KnightMiner** [comment]
Closing for lack of response. We have spawns on slime islands in both testing in dev and in many modpacks.
