### ISSUE TITLE
problema con el hierro

### ISSUE THREAD

**Issue by carlossxd** [SlimeKnights/TinkersConstruct#4561]
Hola
vengo a buscar una solución para un problema que tengo con el hierro en la versión 1.12.2 del minecraft y en la version 
tinker_io-1.12.2-rw2.7.1 
el problema es el que vera en la siguiente foto, que consiste en que no deja crear por ejemplo el mango de hierro. sin embargo con otros materiales si sirve
hay una solución para esto? o es la versión? o es algo que desconozco del mod?

![WhatsApp Image 2021-07-06 at 10 41 25 PM](https://user-images.githubusercontent.com/87053473/124697095-da68b080-deab-11eb-8858-76a9c516f67e.jpeg)

**Comment by ShinyPorygon** [comment]
Necesitas usar la fundición para hacer piezas de metal. Esto debería explicarse a grandes rasgos en Materiales y usted. En pocas palabras, necesita la fundición, luego necesita hacer un molde y luego vierte sus materiales en el molde para las piezas que no se pueden hacer en el constructor de piezas.

**Comment by carlossxd** [comment]
> Necesitas usar la fundición para hacer piezas de metal. Esto debería explicarse a grandes rasgos en Materiales y usted. En pocas palabras, necesita la fundición, luego necesita hacer un molde y luego vierte sus materiales en el molde para las piezas que no se pueden hacer en el constructor de piezas.

te agradezco por la explicación, gracias.
