### ISSUE TITLE
My unbreakable pickaxe broke

### ISSUE THREAD

**Issue by MrOmegaBeast** [SlimeKnights/TinkersConstruct#4562]
I'm unsure if this is because of the modpack im playing (Project Ozone 3 A New Way Forward), but I was veinmining marble with my unbreakable pickaxe and it just straight broke. It went from full durability to broken at some random point while veinmining the marble. The picture shows my pickaxe where its both unbreakable and broken at the same time.
![HOWWW](https://user-images.githubusercontent.com/87117310/124883467-7d3a3f80-e010-11eb-9a07-d02029f995ea.PNG)

**Comment by PrincessOfEvil** [comment]
Magically brittle sometimes just straight up breaks tools. Not a bug, and not ours besides, that's on ExU.

**Comment by MrOmegaBeast** [comment]
Thanks for clearing that up, i guess it's a pretty low chance to break as i've never had that happen before
