### ISSUE TITLE
[1.16.5] Smelting Iron Bars gives wrong amount of molten Iron

### ISSUE THREAD

**Issue by LuciusV** [SlimeKnights/TinkersConstruct#4563]
**Issue description:**
As 16 Iron bars = 6 Iron Ingots (144mb), smelting this should be 864 mb total and so one single bar is equivalent of
864 / 16 = 54 mb.
But it gives only 48mb
*It was correct in 1.12.2 with 8 iron bars smelting exactly to 3 ingots, so I see this as bug* 

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Mantle: 1.6.109
* Tinkers Construct: 3.0.4.197

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by PrincessOfEvil** [comment]
Intentional. Smelting bars is less efficient, but you can also cast them for that amount.

**Comment by LuciusV** [comment]
Ok. Can I fix it with custom datapack if I prefer old ratio?

**Comment by PrincessOfEvil** [comment]
Yes.
