### ISSUE TITLE
Crafting Station Blacklist

### ISSUE THREAD

**Issue by 4Finger** [SlimeKnights/TinkersConstruct#4564]
Issue description: The crafting station blacklist doesn't seem to be working whenever I add the block names. I've tried typing in `thermalexpansion:machine` and `thermalexpansion:dynamo` but they never go away when I go into the crafting station gui.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
* Thermal Expansion 5.5.7.1

**Comment by KnightMiner** [comment]
Its not block names, its tile entity names, as stated by the comment. If you need the names, use a mod such as The One Probe's creative probe.
