### ISSUE TITLE
Crafting recepies not working 

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#4565]
The crafting recepies for the tool station and the stencil table are not working,it just doesn’t show the item it’s supposed to give me 

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:1.16.5
* Minecraft:Java
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Ye 
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
It can be reproduced with just the tinkers mod 
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by PrincessOfEvil** [comment]
Stencil table doesn't exist. JEI is your friend.

**Comment by ghost** [comment]
What u mean, like not in this Version or what?

**Comment by ghost** [comment]
> Stencil table doesn't exist. JEI is your friend.

1. I don’t gebe JEI 2. it’s Right there on the Wiki, what do you mean it doesn’t exist

**Comment by Insane96** [comment]
You lied in your report, you didn't read the What's new page as it's stated there. Also you didn't fill out the report correctly.

Also also, JEI

**Comment by Toby222** [comment]
The Stencil Table is part of the Part Builder.
If the recipe of the Tool Station is also missing, consider making a new report and properly filling out the form
