### ISSUE TITLE
More of a question less of an issue, need help please!

### ISSUE THREAD

**Issue by BubbaMisch** [SlimeKnights/TinkersConstruct#4568]
**Issue description:**

Im trying to make my own mod pack remake of rlcraft and i want to make tinkers tools to make it to end game and compete with all it ice and fire tool. Only thing is that there are enchantments that can me tinkers tool useless after iron level. Example theres Supreme Sharpness 5 (Sharpness 20) when tinkers sharpness modifier limit is around sharpness 5. is there anyway to remove or increase the limit to sharpness, hast, luck... ext? Please let me know, wall help is appreciated. Thank you in advance. 

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
There have been mods before that let you change e the limits, I don't know of any though. If you update to 1.16, it's a pretty trivial change in a datapack to increase the limit.

Also, please don't open issue reports for questions, go to discord as the issue selection screen told you
