### ISSUE TITLE
conflict with JER (just enough resources) and AOA3

### ISSUE THREAD

**Issue by Dancing-Github** [SlimeKnights/TinkersConstruct#4570]
the version 3.0.9 works perfectly ，the JER can display the drop information of mobs  in AOA3. However , as  I  update  tic 3 to 3.1.0version , the information cannot be shown .

**Comment by KnightMiner** [comment]
Try filling out the issue again, this time actually following the issue template that you deleted.

**Comment by KnightMiner** [comment]
Updated issue is at #4574, for my future reference.
