### ISSUE TITLE
conflict with JER ，JEA and AOA3

### ISSUE THREAD

**Issue by Dancing-Github** [SlimeKnights/TinkersConstruct#4574]
### Minecraft Version

1.16.5

### Forge Version

36.1.32

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.0.231

### Describe your issue

the version 3.0.4.197 works ，the JER(just enough resources) can display the drop information of mobs in AOA3，but it seems JEA  doesn't  work. Then , as I update TIC 3 to 3.1.0 version , JEA works , but  the information of drops by AOA3 cannot be shown . After I delete JEA(just enough advancement),  the malfunction disappears.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

JustEnoughResources-1.16.5-0.12.1.121.jar
JustEnoughAdvancements-1.16.5-1.0.0.jar
jei-1.16.5-7.7.1.110.jar
AoA3-3.5.4-1.16.5.jar

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
This sounds like a rather complicated conflict. Can you also report to the issue trackers of JustEnoughResources and JustEnoughAdvancements and link those issues here? If I had to guess, Tinkers did not cause this problem, but something in the load order changed with the new update which changed the issue. Alternatively, one of your mods has a compatibility module with Tinkers and the update broke it.

Also, you did not check the last box to say you are not using performance enhancers. Are you using them? If so, test without them.

**Comment by KnightMiner** [comment]
Closing for lack of information. If you want this fixed, report it to the other related mods, and properly fill out the issue report here (including testing without performance enhancers)
