### ISSUE TITLE
Orange Slime Islands don't generate with BoP

### ISSUE THREAD

**Issue by paypur** [SlimeKnights/TinkersConstruct#4575]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2855

### Mantle Version

1.3.3.55

### Tinkers' Construct Version

1.12.2-2.13.0.183

### Describe your issue

Orange Slime Islands don't generate with Biomes O Plenty installed
Same issue as #4368 but for 1.12.2

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Biomes O Plenty

**Comment by orrinpants** [comment]
I am on 1.16 and didn't even know they existed, I guess that's because I didn't see them because I have Biomes O' Plenty.

**Comment by paypur** [comment]
Actually they do spawn, I just saw them in a normal BOP world but for some reason they did not spawn in my superflat testing world

**Comment by KnightMiner** [comment]
Superflat has different rules than normal worlds, I don't know the config string required to add islands to superflat, or if we need to register something to make it work. If the latter is the case, not something likely to change.

We might have special cased no superflat back in 1.12. I'll look into what it takes to add them to superflat in 1.16 now that the world gen system is cleaner, but going to consider this issue resolved.
