### ISSUE TITLE
Posible incompativility with consecration

### ISSUE THREAD

**Issue by aburone** [SlimeKnights/TinkersConstruct#4577]
### Minecraft Version

1.16.5

### Forge Version

36.1.63

### Mantle Version

Mantle-1.16.5-1.6.115.jar

### Tinkers' Construct Version

TConstruct-1.16.5-3.1.0.231.jar

### Describe your issue

I assume it has something to do with consecration because it is on the log. But the affected entity is a creeper and consecration doesn't touch them....
I' m reporting this to both

consecration-forge-1.16.5-4.0.0.5.jar

### Crash Report

https://hastebin.com/efuwajexah.rb

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Maybe? Consecration

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
Sodium reforged is a performance enhancer. Please remove them for bug reports even if you think they have nothing to do with it.

**Comment by KnightMiner** [comment]
The new alpha renamed one of our classes, and as a result compat is out of date. Please report this to Consecration, as they need to update their compat.

**Comment by TheIllusiveC4** [comment]
This is fixed in the latest Consecration update.
