### ISSUE TITLE
Include the content of precedent books in Tier 2+ books

### ISSUE THREAD

**Issue by Fireztonez** [SlimeKnights/TinkersConstruct#4579]
### Minecraft Version

1.16.5

### Forge Version

36.1.65

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.0.231

### Problem description

Hello,
I play in enigmatica 6 a bit and try the new version of Tinker. I kind a like the idea of having multiples book, question of only seeing the informations for things where we are on the mod and not having all the information directly. The only thing I found really anoying is to not being able have informations for materials and sutch from the tier 1 book into the tier 2 book or tier 1 and 2 material in the tier 3 book, etc. Basically each time I want to make a new tool, I have to look inside multiples book question to compare all material stats.

### Suggested solution

I think all precedent book information (at least for materials) should be added on the next book level, question of practicality. When you start making better tools or upgrade your tool, you don't always have the material availiable for making everithing with last tier material.

### Alternatives considered

Not really other idea for now.

### Additional context

I know the last book tier include all the information of the precedents one, but before being able to make that last book, you still have to go to the nether, kill somes Magma Cubes or blaze, get soulsand question to make somes Nether Grout and craft the tier 4 book. Why not simply use the tier 1 book, in the tier 2 recipe, the tier 2 book in the tier 3 (...), just question to upgrade your book and add the new information you learn...

Another small improvement that could be nice to the book, if by clicking on an icon of the material it could open the page of this material on JEI (Especially for alloys, it could be very practical to quickly see in 1 or 2 clicks the recipe)

### 

- [x] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
The reason you don't see all the information is to prevent clutter. The books are primarily to teach players about the mod, so the goal is to not be confusing. Having all the previous info in each new book is just confusing as now the player does not know what is new about this tier.

Also, in my opinion, having to read multiple books is not that bad. If you are annoyed about using a bunch of hotbar slots, make lecterns and place each book on one. Looks way cooler to have multiple books on a lectern anyways.

Alternatively, just use the encyclopedia. Yes, you need nether access to get it. Its not like you can't reach the nether in less than an hour.

----

JEI integration from the book UI is not trivial, so its a low priority.

**Comment by Fireztonez** [comment]
I understand,
I just let know my opinion about that, but that's true, having too mutch information at the same times and in the same place is not necessairly better and can be confusing.

For the time for acceding to the nether this always depends of the modpack, but after book recipes can always be altered by the modpack dev too if needed.

Continue your great job on the mod, this is clearly a really really great update and a lot of great change!!
