### ISSUE TITLE
Cast chest duplicates casts when exploded

### ISSUE THREAD

**Issue by Icosahunter** [SlimeKnights/TinkersConstruct#4580]
### Minecraft Version

1.16.5

### Forge Version

36.1.35

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.0.231

### Describe your issue

When a cast chest containing casts is exploded (say by a creeper) it will retain the casts in the dropped cast chest item but also drop the casts as independent items, thereby duplicating all the casts. I tested it again with tnt and without other mods and confirmed the issue. I tried it with the parts chest and got the same results.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed in 3.1.1.252
