### ISSUE TITLE
Melting modifier unbalanced

### ISSUE THREAD

**Issue by Habeeb-M** [SlimeKnights/TinkersConstruct#4581]
### Minecraft Version

1.16.5

### Forge Version

36.1.65

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.0.231

### Problem description

(I'm not entirely sure if this is intended)
The melting modifier on combat tools is based on hits rather than damage. 
This means that a manyullyn broad axe(with the tank and melting modifier) can one-hit kill a blaze, yielding only 20mb of blaze blood in its tank - while a wooden dagger(also with the modifiers) can ten-hit kill a blaze, yielding 200mb of blaze blood.

### Suggested solution

I feel like the amount of melted liquid should be based on total damage done rather than the amount of hits done on the mob. 

Rather than a set amount of mB being given per hit, there should be a total amount of mB in a mob, and then the tool gives a % of that based on the damage that the tool does; for example

Blaze gives 100mB of blood per mob

Manyullyn axe does 20 hearts(on crit), so 

20(damage hit) divided by 20(total mob health) = 100%
100% * 100mB = 100mB given per hit

Wooden dagger does 1 heart, so

1/20 = 5%
5% * 100 mB = 5mB given per hit.

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
Thats called misusing the modifier, the modifier is balanced towards number of hits, so you will get more fluid from a weapon that does less damage. It makes sense thematically, you extract fluid per hit, so more hits is more fluid.

I do think I need to double the max amount of health that you get fluid for, but in general this is intended.
