### ISSUE TITLE
Vein Hammer doesn't pick up diagonal ores

### ISSUE THREAD

**Issue by Habeeb-M** [SlimeKnights/TinkersConstruct#4582]
### Minecraft Version

1.16.5

### Forge Version

36.1.65

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.0.231

### Describe your issue

![image](https://user-images.githubusercontent.com/29381753/126815197-6178af66-4c96-4054-ac1e-f5e3925a251e.png)
![image](https://user-images.githubusercontent.com/29381753/126815224-6602d25c-fd97-4a88-834c-fc327e3ff326.png)

Diagonal configurations of any ores are not picked up by the vein hammer

### Reproduced with only Tinkers' Construct?

No

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
Please test without optifine. Due to optifines amazing ability on 1.16 to screw up everything from save files to oregen it should be removed for any bug reports since it can do apparently anything to your game.

**Comment by KnightMiner** [comment]
This has nothing to do with optifine, its just a misunderstanding about how the vein hammer works. But using performance enhancers is grounds for instantly closing issues that are not intented. You also violated the requirement to either find it works with just tinkers or list the required mods, actually read the template in the future.

For more details on the hammer, it mines the block plus adjacent neighbors to a distance, diagonal neighbors would both cause it to mine way too many blocks at a range of 1 (more than a hammers 3x3 AOE), and is pretty redundant to a range of 2, so I opted for just direct neighbors. This is consistent with nearly everything else in the vanilla game, redstone is the only thing you will find considering diagonal neighbors, and only upwards.
