### ISSUE TITLE
Add config for dimension whitelist for slime islands

### ISSUE THREAD

**Issue by Goldenlion5648** [SlimeKnights/TinkersConstruct#4584]
### Minecraft Version

1.16.5

### Forge Version

36.1.61

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.0.231

### Problem description

My modpack does not have the player go to the overworld, nether or end, but I would like certain slime islands to be in certain dimensions. Currently, the islands are only able to spawn in the overworld, nether, and end

### Suggested solution

Add a config to whitelist certain dimensions for each time of slime island

### Alternatives considered

just not have slime islands in my custom dimensions

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
Slime islands are controlled by structure separation settings. You should be able to configure them using a datapack. Where do your extra dimensions come from, and can you use a datapack to configure them?

**Comment by Goldenlion5648** [comment]
My custom dimensions are from a data pack I made. 

I did not realize the slime islands were structures, I thought they would be features, and did not see them listed as features when I used the tellme command. I was able to get the islands spawning in my dimension using the structure section of the custom dimension file.

Thanks

**Comment by KnightMiner** [comment]
Glad to see it working. If your project is public, feel free to link it here as an example for the next person wanting to add islands to their dimension.

**Comment by Goldenlion5648** [comment]
Here 2.5 years later haha. Better late than never https://github.com/Goldenlion5648/ModpackDevExamples/blob/master/example_data_pack/data/rework/dimension/tinkerer_world.json#L57C1-L65C14
