### ISSUE TITLE
Seared/Scorched Channels break flow in multiplayer

### ISSUE THREAD

**Issue by Yaevo** [SlimeKnights/TinkersConstruct#4587]
### Minecraft Version

1.16.5

### Forge Version

36.2.1

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.0.231

### Describe your issue

While in multiplayer session (Forge server version 36.2.1), when you make a flow with the Channels, all goes well, but after the user that set the flows disconnects and connects again, they get messed up randomly, and have to be set again in order to function correctly.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Explain "messed up randomly" better, maybe try some screenshots?

**Comment by Yaevo** [comment]
This is just logging in:
![image](https://user-images.githubusercontent.com/70084940/127509037-96466b8b-2f1f-4c5d-8ec9-09ac76df583e.png)
Now it's set up to flow correctly:
![image](https://user-images.githubusercontent.com/70084940/127509549-05573c4f-ec19-4bf7-a233-b1f5dfaf623d.png)
After disconnecting and logging in again, it "messes up":
![image](https://user-images.githubusercontent.com/70084940/127522529-18ac3afe-91e9-4563-80ff-7432b5fe62db.png)

**Comment by KnightMiner** [comment]
Is this just visual, or functional? In other words, is it a desync?

**Comment by Yaevo** [comment]
It's both visual and functional, I have to set them correctly again to get the ore to flow

**Comment by KnightMiner** [comment]
It resetting functionally on login sounds unlikely, unless that area was unloaded. Do you get the same behavior if you unload the chunks without logging off then come back? Or if you log in while another player by your channels?

**Comment by Yaevo** [comment]
I haven't tried unloading the chunks, I'll do it when I can login again. And some of the friends that are near my house, often come by and tell me that they fix the channels because they find it like in the screenshots. At the moment I've tried only with me near the channels to check if they reset, I'll have to try with someone near them too.

**Comment by KnightMiner** [comment]
Oh, one more thing. Can you use `F3` + G` to show chunk borders? I'm trying to find the logic behind those channels being the ones that disconnect

**Comment by KnightMiner** [comment]
Its been about 2 months with no update, and I still cannot reproduce this, so going to close. Give more information if you want a reopen
