### ISSUE TITLE
Luck and Autosmelt

### ISSUE THREAD

**Issue by ItsTruffle** [SlimeKnights/TinkersConstruct#4590]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.0.231

### Describe your issue

queenslime pick with autosmelt and luckiest ? expected fortune 3 and autosmelt to get more out of my ores, am only getting 1 per, everytime. bug or is luck something different ?

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Intentional, because a duplication mechanic is basically just asking for duplication bugs and vanilla minecraft is making fortune multiply ores in 1.17.
