### ISSUE TITLE
Missing Modifier Information From Book: Looting?

### ISSUE THREAD

**Issue by toastonrye** [SlimeKnights/TinkersConstruct#4591]
### Minecraft Version

1.16.5

### Forge Version

Forge: 36.1.23

### Mantle Version

Mantle-1.16.5-1.6.97

### Tinkers' Construct Version

TConstruct-1.16.5-3.0.3.152

### Describe your issue

I didn't think looting was an available modifier in 1.16 because I didn't see it in the book. A lot has changed since 1.12.2 so I was using the book as a guide, but it turns out looting by adding lapis is still in the mod!

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
Your tinkers version is way out of date to the point where all the books were not done. Therefore updating will have the books show all abilities and upgrades.
