### ISSUE TITLE
Crafttweaker fuel amount

### ISSUE THREAD

**Issue by DolphinGui** [SlimeKnights/TinkersConstruct#4594]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.1.252

### Describe your issue

relevent zs script:
`<recipetype:tconstruct:fuel>.addFuel("waterfuel", <fluid:minecraft:water>, 12, 1000);`

When adding a fuel via the crafttweaker integration, it only consumes 1 mB at a time. Given there's no amount paramter, I don't think this is intended behavior.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Crafttweaker 7.1.0.374

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Have you tried `<fluid:minecraft:water> * 50`? Amounts are native to CraftTweaker's fluid ingredients, so there is no need for another paramter

**Comment by DolphinGui** [comment]
That worked. I guess I'll add that to the crafttweaker docs.
