### ISSUE TITLE
Enchanting

### ISSUE THREAD

**Issue by Set2Minecraft** [SlimeKnights/TinkersConstruct#4596]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.1.252

### Describe your issue

Enchantments do not work with tools/wepaons that have modifiers/mix of materials in them, (/enchant does work, anvil not)

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
Tinkers tools are not meant to be enchanted. Modifiers are your enchantments.
