### ISSUE TITLE
Materials All Missing and do not show in the Tinker's construct books

### ISSUE THREAD

**Issue by SmoothEnigma** [SlimeKnights/TinkersConstruct#4597]
### Minecraft Version

1.16.5

### Forge Version

36.2.1

### Mantle Version

1.16.5-1.6.115

### Tinkers' Construct Version

1.16.5-3.1.1.252

### Describe your issue

I am playing the pack Enigmatica 6 with someone and all tool parts say "material missing" and as such i'm unable to play the mod. The parts also don't show up in JEI, but the visuals for the created parts are correct. Along with this none of the materials show up in any of the tinkers construct books. We are playing over LAN using a VPN to do so, and when playing in a single player the parts show up in JEI but still do not appear in the books so an issue still exists.

Googling around has provided no help and this is my last shot. I just wanna be able to play my fav mod

### Reproduced with only Tinkers' Construct?

No

### Other mods required

The entirety of Enigmatica 6 pack downloaded through Curseforge

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
This is a bit of an odd one. There's a bug with lan but it's been fixed with a test build you can grab in our discord. You could also wait for the next update.
https://discord.gg/njGrvuh

**Comment by SmoothEnigma** [comment]
This fix worked, thank you!

**Comment by KnightMiner** [comment]
Leave this open until the fix is released.

**Comment by KnightMiner** [comment]
For the sake of tracking, fixed by e3c8eff.

**Comment by KnightMiner** [comment]
Fixed in 3.1.2.265
