### ISSUE TITLE
Cobalt as an ore is completely missing from the game

### ISSUE THREAD

**Issue by OddJarro** [SlimeKnights/TinkersConstruct#4598]
### Minecraft Version

1.16.5

### Forge Version

36.2.1

### Mantle Version

idk what this is

### Tinkers' Construct Version

3.1.1.252

### Describe your issue

There are cobalt recipes, but the ore and the ingot dont exist in the game.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
I think we are going to need a lot more info than this... Equally if you don't even know what mantle is I'm unsure if you were able to reproduce it with just tinkers...

**Comment by OddJarro** [comment]
Sorry, didn’t realized what it was when I was filling this out.
Mantle 1.6.115
And there really is no other info. Cobalt doesn’t exist in the game. I go into the nether, there is no cobalt. I look it up, but there are only the things cobalt is used for, but the ore and the ingot don’t exist.

**Comment by ShinyPorygon** [comment]
Do you have a legit version of MC? this has yet to happen to anyone else, equally have you tried a new world.

**Comment by KnightMiner** [comment]
I find that highly unlikely given I have seen cobalt in several major modpacks and it exists in our development environment. I assume you have other mods installed and did not realize what the checkbox meant when you answered yes. Provide **literally anything** to help us debug this

**Comment by OddJarro** [comment]
Legit like do I own minecraft? Yes, I bought it. The issue came up on enigmatica 6. While we were playing a new world. Loaded up a single player world and it was still there. Looked it up, couldn’t find anything on it. Put it into a folder and loaded it up on it’s own, everything else is there except the cobalt across all these situations.

**Comment by KnightMiner** [comment]
Enigmatic 6 replaces cobalt ore and ingots with its own block and item. If you ran a world created in Enigmatic 6 without the modpack, its possible it was permanently replacedso you won't see our ore.

When I say test this with only tinkers, I mean make a pack with only tinkers, and then create a new world with only tinkers, and see if the issue persists.

**Comment by OddJarro** [comment]
Okay. I’ll do it again. I’ll be back in a few minutes.

**Comment by OddJarro** [comment]
Same issue

**Comment by KnightMiner** [comment]
![image](https://user-images.githubusercontent.com/12155288/129429250-7bb2ac77-0406-4647-a2f4-11156231c148.png)
Your issue is not present with just Tinkers Construct and mantle. So again I ask you, give me literally any information about why your setup is different. What are you not telling me? Do you have other mods installed (optifine is a mod). Are you playing on a custom client? Do you have resource packs installed? How did you determine there is no cobalt? Can you provide screenshots proving what you are saying?

**Comment by Vojt4** [comment]
What about Ardite ore is that missing too or only cobalt is that problem ?

**Comment by PrincessOfEvil** [comment]
Ardite doesn't exist.

**Comment by Vojt4** [comment]
> Ardite doesn't exist.

Sorry I'm old tinkers construct user and in 1.7.10 and 1.12.2 ardite was there.

**Comment by KnightMiner** [comment]
Closing for lack of response. I have shown this issue does not happen on a new world with just tinkers and mantle. I assume the issue is confusion over the fact that Enigmatica 6 replaces our cobalt ore with their own block.
