### ISSUE TITLE
Fast moving when spaming Flint Shuriken

### ISSUE THREAD

**Issue by Vojt4** [SlimeKnights/TinkersConstruct#4599]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.1.252

### Describe your issue

Good day, recently I try new Tinkers Construct 1.16.5 becouse I never test it before. I found when spaming mouse button with Flint Shuriken I go realy fast forward. When you combinate with slime boots its realy crazy.   https://www.youtube.com/watch?v=b1llV5zog24

### Reproduced with only Tinkers' Construct?

Yes

### Other mods required

No other mods

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed in 3.1.2.265
