### ISSUE TITLE
Foundry bugged

### ISSUE THREAD

**Issue by Stultophobia** [SlimeKnights/TinkersConstruct#4600]
### Minecraft Version

1.16.5

### Forge Version

1.16.5

### Mantle Version

1.16.5

### Tinkers' Construct Version

1.16.5

### Describe your issue

When building a foundry in survival, the controller doesnt seem to recognise all of the blocks.

When building it claims that there is an invalid block on the edge of the floor and outlines it in red but the block is not invalid as it is Seared Brick and definitely from Tinkers.

I went to my creative testing world where it works the way it is supposed to.

I created a second survival world to make sure that it wasn't an issue with that world and the problem persisted.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
1.16.5 is not an acceptable answer for all of those questions. We need specific versions of the mods

**Comment by KnightMiner** [comment]
Whenever trying to debug structure issues, provide screenshots. Sounds like you are building the structure wrong from your description, but not sure exactly how.

**Comment by KnightMiner** [comment]
Closing for lack of response. I assume this is a misunderstanding of the foundry requirements, which reading the book would have solved. Provide screenshots and versions like requested if you want a reopen.
