### ISSUE TITLE
Heater/Melter consumes bucket

### ISSUE THREAD

**Issue by Sunekaer** [SlimeKnights/TinkersConstruct#4602]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

 Mantle-1.16.5-1.6.115

### Tinkers' Construct Version

TConstruct-1.16.5-3.1.1.252

### Describe your issue

Using a lava bucket in a Heater/Melter consumes the bucket.

![image](https://s1.sunekaer.com/i/15-08-2021_12-40-19_%25pn.gif)

### Crash Report

None

### Reproduced with only Tinkers' Construct?

Yes

### Other mods required

None

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [x] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
It probably shouldn't consume the bucket, though there is no reason to use a heater with a lava bucket. Fuel lasts just as long if you use a lava tank, but melts faster.

**Comment by KnightMiner** [comment]
Fixed in 3.1.2.265
