### ISSUE TITLE
[1.16.5] Ticking block entity

### ISSUE THREAD

**Issue by TheSnowyChickens** [SlimeKnights/TinkersConstruct#4603]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.1.252

### Describe your issue

The seared Faucet crash the server, if we try to fill a table with a ingot cast with molten materials.

### Crash Report

https://pastebin.com/YGarXydx

### Reproduced with only Tinkers' Construct?

No

### Other mods required

![grafik](https://user-images.githubusercontent.com/29357962/129655461-27c5287a-f25e-4c7a-8dd8-6f29fd77810b.png)

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
You did not follow the issue template. According to the template, the list of mods *required* to reproduce a bug should be less than 10. I can do nothing with a list of 200+ mods for reproducing an issue.

For the record, this crash is impossible unless something broke the worlds datapack state. Its essentially saying one of my recipes is referencing a tag instance that does not exist in the current world, despite having fetched that instance from the current world

**Comment by TheSnowyChickens** [comment]
sry, I had a headache for a few hours:

But make it easy: there are 3 mods with ingots / ores mainly, so:

Mekanism
Immersive
Geolosys

The big list is only for the possibility, that you may know already a mod, which can do the crash.

**Comment by KnightMiner** [comment]
I have no idea what mod might be breaking datapacks in this way. I doubt its the ingot you were casting that caused the problem, more likely one of your performance mods, so try testing without them to start.

For the record, [this mantle commit](https://github.com/SlimeKnights/Mantle/commit/ad6fb2d655b6233ac787132244ac34f45cff8d99) replaces the crash with a warning in the log. It does not fix the issue as I still don't know why it happens, but I figure logging an error is better than a full crash. Will be in the next mantle update.

**Comment by TheSnowyChickens** [comment]
The mantle commit is for the begin the way to stop blocking us on playing the pack. =)
Thanks for that already. 👍 

I will test more variants of mod combinations in the next time.
We have problems with the general overworld performance anyway, so there is still a lot of test time anyway.

**Comment by KnightMiner** [comment]
Mantle 1.6.123 prevents the crash, but the underlying bug is still there. Find more information about why it happens if you want this to be fully addressed.

**Comment by TheSnowyChickens** [comment]
The server is now close to 2 weeks online and no further crash from this kind of crash anymore.

However, we have not rebuilt or expanded the smeltery to any great extent, have left all drains and faucets in place, and we stopped using "Pipez" to pull out the fluids.

In 2 weeks we restart the server map and maybe we can find such crash entries there again.
(because some new smelteries)

**Comment by KnightMiner** [comment]
I have heard reports from other mod devs that Pipez misuses forge fluid capabilities and causes problems, and notably the author does not work well with other devs suggesting he change his code to use them properly. I would suggest you try a different pipe mod. Pretty Pipes comes to mind, or Refined Pipes. Personally I use pipes that come with the mods I install, such as Immersive Engineering or Create.

**Comment by TheSnowyChickens** [comment]
Oh, good to know.
I liked Pipez mod because the heavy performance difference to Meka pipes, but good coding is more important.

I take a look in Pretty Pipes and Refined Pipes. 👍

**Comment by KnightMiner** [comment]
Closing as we have no idea what causes this, but its likely another mod breaking datapacks or doing recipes wrongly. The mantle patch will make it just log an error, provide more info if you want to remove that log spam.
