### ISSUE TITLE
Hopper and Heaters

### ISSUE THREAD

**Issue by benbenlaw** [SlimeKnights/TinkersConstruct#4604]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.1.252

### Describe your issue

Using a hopper to try and fill a heater with coal results in only one item going in:

![image](https://user-images.githubusercontent.com/42780877/129699939-1d8d0c1d-de9e-4aad-956f-6b4dae6f445a.png)
![image](https://user-images.githubusercontent.com/42780877/129699973-f9c333a7-e7b4-42ca-9d70-529b0161a759.png)
![image](https://user-images.githubusercontent.com/42780877/129699993-bedaf6e3-4298-44bf-9e59-196953665434.png)

### Crash Report

No Crash

### Reproduced with only Tinkers' Construct?

Yes

### Other mods required

No

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed in mantle 1.6.123
