### ISSUE TITLE
Melting/Tank Upgrade incorrect capacity

### ISSUE THREAD

**Issue by NielsPilgaard** [SlimeKnights/TinkersConstruct#4605]
### Minecraft Version

1.16.5

### Forge Version

1.16.5-36.2.2

### Mantle Version

Mantle-1.16.5-1.6.115

### Tinkers' Construct Version

TConstruct-1.16.5-3.1.1.252

### Describe your issue

While making a TiCon sword, I added the Melting ability to it, giving it 1296mb fluid capacity for the weapon to melt fluid into. When adding a Seared Tank, this should add another 1296mb to the capacity. When doing so, however, the fluid capacity only goes up to 2448mb instead of the 2592mb that math says I should get.

![2021-08-17 18_59_16-Window](https://user-images.githubusercontent.com/11296552/129777346-9ef01428-4e53-4451-92f8-ea3b9f693300.jpg)
![2021-08-17 19_01_11-Window](https://user-images.githubusercontent.com/11296552/129777350-9a48b469-5ac9-4d7b-9263-513cce782933.jpg)
![2021-08-17 19_00_57-Window](https://user-images.githubusercontent.com/11296552/129777351-1702c3da-3d91-4bf4-9722-69ba8c27485c.jpg)
![2021-08-17 18_59_25-Window](https://user-images.githubusercontent.com/11296552/129777352-2cb8eec7-2b38-4cc2-95e5-7bac9a1f2971.jpg)

### Reproduced with only Tinkers' Construct?

No

### Other mods required

To my knowledge no other mods are required to reproduce this issue, but I have not tested it.

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
> To my knowledge no other mods are required to reproduce this issue, but I have not tested it.

Test it. All you have to do is boot the game with two mods installed, should take less than 15 minutes.

**Comment by DarkAngel22579** [comment]
Forge Version
1.16.5-36.2.2

Mantle Version
Mantle-1.16.5-1.6.115

Tinkers' Construct Version
TConstruct-1.16.5-3.1.1.252

Happens with just tinkers and mantle present. A tool with Melting and Tank 1 has 2448mB capacity instead of the expected 2592mB.

**Comment by KnightMiner** [comment]
2448 is 17 ingots by the looks of things. Looks like the upgrade is currently 8 ingots but the documentation says 9. I'll have to decide which is the more correct behavior.

**Comment by KnightMiner** [comment]
Fixed in 3.1.2.265
