### ISSUE TITLE
Bloodbone recipe is wrong

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [SlimeKnights/TinkersConstruct#4607]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.1.252

### Describe your issue

The recipe for bloodbone has been messed up, instead of taking 250mb of blood, it takes 250 mb of blazing blood.

![image](https://user-images.githubusercontent.com/40587985/130171939-b4bda326-7056-4173-98a0-8af83584dc91.png)

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed in 3.1.2.265
