### ISSUE TITLE
Villager AI to avoid smeltery or foundry blocks

### ISSUE THREAD

**Issue by Mirooomir** [SlimeKnights/TinkersConstruct#4608]
### Minecraft Version

1.16.5

### Forge Version

36.1.0

### Mantle Version

1.16.5

### Tinkers' Construct Version

1.16.5

### Problem description

Greetings! I just noticed that the villagers that are hanging around my foundry tend to get stuck with the smeltery blocks such as the faucet, the casting table or the casting basin.  They literally try to walk it and they won't avoid it unless you push them back into another path. Can you please take a look at this?

### Suggested solution

Maybe try to program the villager's AI to consider those as obstructive blocks too so that they can avoid it.

### Alternatives considered

I have no other alternatives.

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by ShinyPorygon** [comment]
1.16.5 is not a valid response for mantle and tinkers construct version

**Comment by ghost** [comment]
I can reproduce this with the following mods (exclusively):
Mantle-1.16.5-1.6.115
TConstruct-1.16.5-3.1.1.252

Tested using foxes. They try to walk through Seared Casting Basins and Crafting Stations. In contrast, they will jump over vanilla crafting tables and walk around vanilla fences.

https://user-images.githubusercontent.com/83793683/130361905-7651fa23-0815-49ed-9052-69eff67c8112.mp4

Possibly the same problem as https://github.com/cweckerl/simplefarming/issues/160

**Comment by KnightMiner** [comment]
Fixed in 3.1.2.265
