### ISSUE TITLE
affection gear from other mods how do i fix

### ISSUE THREAD

**Issue by Lslender** [SlimeKnights/TinkersConstruct#4609]
### Minecraft Version

1.12.2

### Forge Version

1.12

### Mantle Version

1.12

### Tinkers' Construct Version

1.12

### Describe your issue

i want it to have tinker for rogue like minecraft but i also wanna be able to use everything else normally

### Reproduced with only Tinkers' Construct?

Yes

**Comment by KnightMiner** [comment]
I have absolutely no idea what you are saying in this issue. I think you are suggesting a feature, if so we no longer are taking suggestions for 1.12. If not, open a new issue and actually follow the issue template.
