### ISSUE TITLE
[1.16.5] Melting Time Multipliers Config

### ISSUE THREAD

**Issue by conneich** [SlimeKnights/TinkersConstruct#4610]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.1.252

### Problem description

Allow a user to increase or decrease the melting times of the melter, smeltery, and foundry as a whole through a config setting, or a way to do so in conjuction with CraftTweaker coding.

The reason being is I feel a lot of the melting recipes are too slow, but considering how many things are meltable using the three structures I would have to remove all recipes and then manually add each one back in with the melting time I would prefer. Considering the structures are tiered to an extent, it would make sense that the melter takes longer than the foundry.

### Suggested solution

This can simply be three variables like "melterMeltingTimeMultiplier=1.0". This would be a 1.0-5.0 setting, with anything outside the range being clamped. It would then be a simple addition to melting times within the source code being something like "baseTime / config.meltingTimeMultiplier". Clamping would keep from worry about division by zero errors.

### Alternatives considered

An alternative would be a way to access and adjust the melting times of recipes through CraftTweaker integration. Though I am unsure if that is your project or from CraftTweaker's dev.

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
I don't think this is worthwhile to add. Datapacks let you tweak all the recipes already, so you can add or subtract time to your hearts content. A global multiplier will just mess with the math, especially in terms of fuel usage.

For the record, if I remember the current numbers were set so melting 3x iron ore in the melter with solid fuel is comparable to melting 3 ore in the furnace.
