### ISSUE TITLE
Change/Add molten fluid tags for compatibility

### ISSUE THREAD

**Issue by TheLMiffy1111** [SlimeKnights/TinkersConstruct#4615]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Problem description

Currently, molten fluid tags do not exist in the forge namespace, possibly discouraging cross-mod compatibility between mods that uses molten fluids with the same 144mb per ingot standard.

### Suggested solution

Change/Add the molten fluid tags to be in the forge namespace, for example `forge:molten_iron`

### Alternatives considered

Maintaining the current tags, and have other mods use fluid tags in the tconstruct namespace.

### Additional context

See Da-Technomancer/Crossroads#154

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
Added in 3.1.3.271
