### ISSUE TITLE
Change Harvest Level Name

### ISSUE THREAD

**Issue by Sindusk** [SlimeKnights/TinkersConstruct#4616]
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Problem description

I'd like to change the names of harvest levels on tools. For example:

[Image](https://i.imgur.com/XvQoZn9.png)

I'd like to change "Mining Level: Netherite" to "Mining Level: Manyullyn"

### Suggested solution

A simple and fast solution would be to add a `setHarvestLevelName()` method to the following class:

[https://github.com/SlimeKnights/TinkersConstruct/blob/1.16/src/main/java/slimeknights/tconstruct/library/utils/HarvestLevels.java](https://github.com/SlimeKnights/TinkersConstruct/blob/1.16/src/main/java/slimeknights/tconstruct/library/utils/HarvestLevels.java)

### Alternatives considered

Alternatively, allowing the harvest levels to be configured via datapack or configuration file change would make it easier to configure for end users.

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
They can be changed via resource pack, where names are supposed to be changed. Datapacks are not supposed to change names.

If you are wondering what the keys are to change the name, look in our language file.
