### ISSUE TITLE
All parts and tools are all white using Sodium

### ISSUE THREAD

**Issue by TylerPienta** [SlimeKnights/TinkersConstruct#4618]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

Updating from 3.1.1.252 to 3.1.2.265 all the tools and parts are all white. In 3.1.1.252, everything was fine and there were no issues at all, 3.1.2.265 is where it emerged. I'm using Sodium, and I suspected that would be an issue, and upon removing it the colors returned. 

Has anyone else had this issue and fixed it?

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Sodium ( https://www.curseforge.com/minecraft/mc-mods/sodium )

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
This is something they have to fix. Downgrade a version of sodium reforged until then

**Comment by KnightMiner** [comment]
Duplicate of #4614. Will be interesting to see how many reports of Sodiums bug we get.

**Comment by furtabs** [comment]
Do you know what part of sodium is causing this weird bug and what to do to disable that feature of sodium.

**Comment by KnightMiner** [comment]
Why are you commenting on an issue closed as a duplicate? At least comment on the original.

In any case, no clue. I don't use sodium as I do not trust most performance enhancers. You are better off having a bit of patience waiting for a response on the other issue, or just trying all the options if you want a faster answer.

**Comment by Lucathejedi65** [comment]
> This is something they have to fix. Downgrade a version of sodium reforged until then

which version specifically

**Comment by KnightMiner** [comment]
This is a sodium bug and a duplicate. I do not know what changes are needed to make it work in sodium, I am pretty sure the downgrade comment was a mistake.

Going to lock this issue as I am tired of people using it as a discussion forum. If you must discuss this issue, talk about it on the sodium issue tracker where the dev who caused this problem can help. For the sake of people who cannot follow the link I already posted to the original TiC report, see spoorn/sodium-forge#163 for the sodium issue.
