### ISSUE TITLE
sword missing bonus ability slot

### ISSUE THREAD

**Issue by TurtleCreater** [SlimeKnights/TinkersConstruct#4621]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

Sword type tools only have 1 default ability slot, and are not missing 1 upgrade slot, contrary to their description in the whats new, the FAQ and the in game encyclopedia

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
They are only supposed to have 1 ability slot, that got changed later as it turned out they were the one of the best weapons even without it. Might have missed updating some of the docs, so will leave this open until docs are updated.

**Comment by KnightMiner** [comment]
Fixed in 3.1.3.271
