### ISSUE TITLE
Silky jewel recipe not found

### ISSUE THREAD

**Issue by Leidenfrost245** [SlimeKnights/TinkersConstruct#4625]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

There is no recipe to be found for silky jewel and I cannot craft it.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
Silky jewel was removed. Look in Mighty Smelting or use JEI as the FAQ told you if you read it to find the new recipe for the silky modifier.
