### ISSUE TITLE
Hover text renders behind crafting recipe in TiC manuals

### ISSUE THREAD

**Issue by luckyu19** [SlimeKnights/TinkersConstruct#4626]
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Mantle Version

1.16.5-1.6.123

### Tinkers' Construct Version

1.16.5-1.6.123

### Describe your issue

![2021-09-19_22 59 18](https://user-images.githubusercontent.com/19247442/133933594-0e715fd4-1f49-4574-bedf-6ad37eb7427e.png)

As shown in the screenshot.
Doesn't happen with all instances, for example this won't happen with modifiers page, I assume they are of different type.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed in Mantle 1.6.146
