### ISSUE TITLE
Mattock make path, but dont make farmland

### ISSUE THREAD

**Issue by olegikoligik** [SlimeKnights/TinkersConstruct#4627]
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

In 1.12 mattock work like hoe, and making farmland (Right click mouse). But in 1.16 it work only like shovel, and make path.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
The kama is now the tool that hoes dirt, this is intended.

**Comment by olegikoligik** [comment]
Ok, thanks for fast answer
