### ISSUE TITLE
Add Polymorph support to Crafting Station

### ISSUE THREAD

**Issue by XenoMustache** [SlimeKnights/TinkersConstruct#4628]
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Problem description

Polymorph is not supported currently in the Crafting Station UI. This means that items that have conflicting recipes are unable to be cycled through or selected. 

Polymorph - https://github.com/TheIllusiveC4/Polymorph

### Suggested solution

See title.

### Alternatives considered

The regular crating station does support Polymorph, so it's not a massive deal at the moment having to place down a regular crafting table, simply a minor inconvenience if you don't want to be carrying around both a vanilla crafting able and a TiC crafting station.

### Additional context

N/A

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
This is on Polymorph or an addon to add. Between the fact that I tend to not add special support for mods like that, I also personally don't believe polymorph is a good idea. Better to just not have conflicting crafting recipes.

So tl;dr fix this with a datapack or ask the polymorph dev.
