### ISSUE TITLE
Gem Pouring 

### ISSUE THREAD

**Issue by ethanmpurds** [SlimeKnights/TinkersConstruct#4630]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

Mantle-1.16.5-1.6.123

### Tinkers' Construct Version

TConstruct-1.16.5-3.1.2.265

### Describe your issue

when using the smeltery and pouring gems (emerald and diamond) unable to pour them into any cast into any tool part (havent tested every material but most work still) still able to pour into blocks and gems after melted 

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Yes, because diamond is not a tool material. Molten fluid != makes a tool material.

**Comment by ethanmpurds** [comment]
in the previous version of tinkers I made the blade of my sword out of molten emerald since the update I cannot make another

**Comment by KnightMiner** [comment]
Tinkers has never had molten emerald blades. You probably had an addon installed.

**Comment by ethanmpurds** [comment]
![Screenshot 2021-09-28 224213](https://user-images.githubusercontent.com/91581660/135199367-00b4a076-ed78-4de5-aa52-75189be9659b.png)
genuine question because it says tinkers in the box  do you happen to know what mod that couldve come from?

**Comment by KnightMiner** [comment]
![image](https://user-images.githubusercontent.com/12155288/135199479-2fc594e9-9424-46c9-8f8d-444083924ac2.png)
