### ISSUE TITLE
Minecraft's infinite rail dupe bug allows to break modded game

### ISSUE THREAD

**Issue by ValentinJD-Pro** [SlimeKnights/TinkersConstruct#4635]
### Minecraft Version

1.16.5

### Forge Version

 36.2.0

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Problem description

Minecraft has a lot of rail dupe glitches, but as normal rails car be turned into iron in the smeltery it allows to every player to have infinite iron ingots which pretty much breaks the game.

### Suggested solution

Remove this recipe.

### Alternatives considered

Add a config to turn it off.

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by ShinyPorygon** [comment]
You can disable recipes with a datapack

**Comment by ValentinJD-Pro** [comment]
wth ? never seen that tinker was allowing datapack recipes ? is there any examples somewhere ?

**Comment by ShinyPorygon** [comment]
Well this confirms you didn't check out "What's new" as it would have informed you so. **https://github.com/SlimeKnights/TinkersConstruct/wiki/Recipe-JSON-List**
