### ISSUE TITLE
Melting, Modifiers and Alloying recipes not visible in JEI

### ISSUE THREAD

**Issue by luckyu19** [SlimeKnights/TinkersConstruct#4636]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.16.5-1.6.127

### Tinkers' Construct Version

1.16.5-3.1.3.271

### Describe your issue

As per title.
Tested with a fresh profile and a new world.
Casting recipes are visible.

Tried checking if the recipe itself is working with water+lava in smeltery and melting spider into venom, and they are working fine.
Log files attached below.

[Log file](https://gist.github.com/luckyu19/b375c1b0eb648b1bb3800395514c47e9)

Don't know if this is helpful but ran another instance to try and get a debug log.
[Debug log](https://gist.github.com/luckyu19/c275ab826e1ed3a2a6521b1280bf75ff)

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Requires JEI 1.16.5-7.7.1.122

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Did you test with an older Tinkers Construct? Did you test with an older JEI?

Your debug log file is incomplete, you never even started a world according to it, so I can pull no information from that. Delete/move all the logs in your log folder so you do not give me the wrong one, then launch the game and start a world to experience the bug so we can get a useful log.

**Comment by luckyu19** [comment]
I confirmed it is working on instance with TiC3 version 1.16.5-3.1.2.265 and JEI version 1.16.5-7.7.1.121.
For some reason it started to spam the error logs once I entered the fml early loading screen, even with the old version and older forge version.
I'm not sure reinstalling MC and Curseforge launcher would help, but I'll report back tomorrow if there is any update.

**Comment by KnightMiner** [comment]
I assume this is probably mezz/JustEnoughItems#2514. I only say assume because the issue you are reporting is inconsistent with that issue. In other words, I would expect that you see only casting recipes, but you imply you only see a different set of recipes.

If all you see is casting recipes, this is officially a JEI bug. Something I can easily handle, but since it broke basically every mod its something that JEI should really fix.

**Comment by luckyu19** [comment]
Yes, only casting recipes are visible, I meant alloying instead of casting. I'll update the title.

**Comment by luckyu19** [comment]
Seems like it's fixed with jei-1.16.5-7.7.1.125
