### ISSUE TITLE
Obsidian ingot cannot be crafted.

### ISSUE THREAD

**Issue by mihaitacgeorge** [SlimeKnights/TinkersConstruct#4640]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2847

### Mantle Version

1.3.3.55

### Tinkers' Construct Version

2.13.0.183

### Describe your issue

There are no obsidian ingots in the game. They cannot be crafted and they do not appear in JEI.
Obsidian tools require them in order to be repaired, yet they do not exist.

I saw a similar report, but the link to the "solution" provided no information at all, so I fail to see how this issue was "solved".

### Reproduced with only Tinkers' Construct?

Yes

**Comment by ShinyPorygon** [comment]
Obsidian ingots are not a thing. They never have been in tinkers. You can use obsidian blocks or obsidian sharpening kits to repair a tool. If something says it requires an obsidian ingot high chance it's an add-on or something else messing with it.

**Comment by KnightMiner** [comment]
Obsidian ingots were a thing in 1.7.10. so not never, just never on 1.8+. However, 1.7.10 was a wild time, there really is no reason for the ingots once repair kits were added.
