### ISSUE TITLE
Crafting station + red string container duplicate

### ISSUE THREAD

**Issue by bigenergy** [SlimeKnights/TinkersConstruct#4645]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

Dupe through botania and tinker. Red string container and tinker workbench. We connect the shulker through the red string container to the tinker workbench. We go to the workbench menu. We break the shulker. Things remain.

See a video for more information https://www.youtube.com/watch?v=uMo7-ZksqMA

### Reproduced with only Tinkers' Construct?

No

### Other mods required

botania

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by luckyu19** [comment]
Able to replicate this issue on singleplayer with only Botania and Tinkers' Construct. (JEI is installed but I don't think would make a difference)

Steps to reproduce:
1. Place a TiC3's crafting station.
2. Place a Botania's Red Stringed Container, with the red part facing the Crafting Station.
3. Place a Shulker Box containing any item.
4. While in Crafting Station's GUI, break the shulker box (you can use a timed piston).
5. Take out the items shown in the storage box to the left of the crafting station.
6. Pick up the shulker box.

Was unable to replicate this issue using just crafting station or crafting table+red stringed container.
Logs attached below.

[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/7402625/latest.log)

**Comment by KnightMiner** [comment]
Sounds to me.like it just needs to be blacklisted, the crafting station inventory view does not work well with containers that can change sizes as there is no way to notify of such a change.

You can add it to the blacklist via the appropriate tag.

**Comment by KnightMiner** [comment]
Closing this as it probably just needs to be blacklisted, the crafting station relies on people properly implementing capabilities, and even then the caps being relatively normal. If the cap is too weird or improperly implemented, you get behaviors like this, hence the blacklist.

For the record, blacklist is a datapack tag, pretty easy to add yourself. I would rather not blacklist other mods personally, as I don't want them to fix the bug but still be blacklisted, so report to Botania to add the blacklist tag or make your own datapack.
