### ISSUE TITLE
MC not starting

### ISSUE THREAD

**Issue by CCs555** [SlimeKnights/TinkersConstruct#4651]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2847

### Mantle Version

1.12.2 newest

### Tinkers' Construct Version

newest 1.12.2

### Describe your issue

cant start

### Crash Report

slimeknights/tconstruct/library/recipe/casting/ItemCastingRecipe$Table.getType()Lnet/minecraft/item/crafting/IRecipeType; 

### Reproduced with only Tinkers' Construct?

No

**Comment by KnightMiner** [comment]
If you are just going to disregard the entire issue template, why even report the issue?

If you have a crash, try again actually following the template. Meaning actual versions, a full crash report, and taking some time to test with fewer mods.
