### ISSUE TITLE
[Forbidden and Arcanus V 16.2.0-BETA-4] Eternal stella "Indestructible" removed on tools with "Lucky/Luckier/Luckiest"

### ISSUE THREAD

**Issue by V2LenKagamine** [SlimeKnights/TinkersConstruct#4653]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

Giving a tool "Lucky/luckier/luckiest" causes the "Indestructible" enchant given by "Forbidden and Arcanus" [Version 16.2.0-BETA-4] to be removed. Note that other tool modifiers work fine. Re-applying "Indestructible" is removed when breaking a block/attacking an entity.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

"Forbidden and Arcanus" [Version 16.2.0-BETA-4]

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Tinkers tools are not enchantable. Any method of adding enchantments to them is unsupported. Forbidden Arcanus should check the isEnchantable function on the tool and use that to see the tool cannot be enchanted.

If they wish, they could add a modifier with similar behavior. Or you could just use our unbreakable modifier.
