### ISSUE TITLE
Leaves not dropping with kama from some modded leaves

### ISSUE THREAD

**Issue by benbenlaw** [SlimeKnights/TinkersConstruct#4655]
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Mantle Version

1.6.117

### Tinkers' Construct Version

3.2.0.290

### Describe your issue

Kama doesnt collect leaves from some modded leaves;
so current list
Working:
Minecraft
TConstruct
Oh Biomes You Go
Biomes o Plenty

Not Working:
Integated Dynamics
Quark

### Crash Report

No Crash

### Reproduced with only Tinkers' Construct?

Yes

### Other mods required

Reproduced with just tinkers and quark
Reproduced with just tinkers and Integated dynamics

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Sounds like a Quark/ID bug. Forge changes vanilla loot tables to work with modded shears. Those mods don't support modded shears. Any mod adding new shears will have the same bug

So, go report to Quark and Integrated Dynamics

**Comment by benbenlaw** [comment]
thanks very much have reported and linked this issue

**Comment by KnightMiner** [comment]
Closing as fixed in the other mods
