### ISSUE TITLE
Server running error

### ISSUE THREAD

**Issue by JohnnyR-Bwh** [SlimeKnights/TinkersConstruct#4660]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2855

### Mantle Version

1.3.3.49

### Tinkers' Construct Version

2.13.0.183

### Describe your issue

[05:13:44 ERROR]: IC2 API error, please update your mods. Error: java.lang.NullPointerException
[05:13:44 ERROR]: java.lang.NullPointerException
[05:13:44 ERROR]: ic2.api.energy.event.EnergyTileEvent.<init>(EnergyTileEvent.java:15)
[05:13:44 ERROR]: ic2.api.energy.event.EnergyTileUnloadEvent.<init>(EnergyTileUnloadEvent.java:24)
[05:13:44 ERROR]: IC2 API error: EnergyTileUnloadEvent is loaded from jar:file:/home/container/./mods/railcraft-12.0.0.jar!/ic2/api/energy/event/EnergyTileUnloadEvent.class

### Reproduced with only Tinkers' Construct?

No

### Other mods required

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:u1="tencent"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\admin\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\admin\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">
<meta charset=utf-8>

When there is a problem, the mod list and jar package：
CodeChicken   Lib | CodeChickenLib-1.12.2-3.2.3.358-universal.jar
-- | --
Inventory Tweaks | InventoryTweaks-1.63.jar
Just Enough Items | jei_1.12.2-4.16.1.301.jar
Mantle | Mantle-1.12-1.3.3.49.jar
Not Enough Items | NotEnoughItems-1.12.2-2.4.3.245-universal.jar
Railcraft | railcraft-12.0.0.jar
Tinkers' Construct 2 | TConstruct-1.12.2-2.13.0.183.jar
Techguns | techguns-1.12.2-2.0.2.0_pre3.2.jar
OptiFine | OptiFine_1.12.2_HD_U_G5.jar
Updater | Updater-1.12.2-2.3.1.jar
Traveler's Backpack | TravelersBackpack-1.12.2-1.0.35.jar
VoxelMap | forgemod_VoxelMap-1.9.28_for_1.12.2.jar
Here's What You're Looking At | Hwyla-1.8.26-B41_1.12.2.jar
Jade | Jade-0.1.0.jar
McJtyLib | mcjtylib-1.12-3.5.4.jar
RFTools | rftools-1.12-7.73.jar
Waila Harvestability | WailaHarvestability-mc1.12-1.1.12.jar
What Are We Looking At | Wawla-1.12.2-2.6.275.jar
InstantLava | InstantLava_1.10.2-1.1.1.jar
BuildCraft | buildcraft-all-7.99.24.8.jar
Neat | Neat+1.4-17.jar
Advanced XRay | xray-1.12.2-1.6.0.jar

</body>

</html>

### 

- [ ] Confirm you have searched the tracker to see if your issue already exists
- [ ] Confirm you are not using performance enhancers, such as optifine
- [ ] Confirm you have tested without external core mods/mixins

**Comment by KnightMiner** [comment]
How did you end up on the Tinkers' Construct issue tracker? The error you pasted says its an IC2 API error caused by Railcraft.

Also, you failed to follow the issue template. You are supposed to test with fewer mods and you are supposed to test without performance enhancers.

**Comment by JohnnyR-Bwh** [comment]
> 问题跟踪
What is Tinkers' Construct issue tracker ？

**Comment by JohnnyR-Bwh** [comment]
> How did you end up on the Tinkers' Construct issue tracker? The error you pasted says its an IC2 API error caused by Railcraft.
> 
> Also, you failed to follow the issue template. You are supposed to test with fewer mods and you are supposed to test without performance enhancers.

What is Tinkers' Construct issue tracker ？

**Comment by KnightMiner** [comment]
https://lmgtfy.app/?q=tinkers+construct+issue+tracker

I question even more how you ended up here without knowing the answer to that question.

**Comment by JohnnyR-Bwh** [comment]
> https://lmgtfy.app/?q=tinkers+construct+issue+tracker
> 
> I question even more how you ended up here without knowing the answer to that question.

Because I saw this error reported in the server operation log, I don't know what the cause of this error is and whether it affects the use of the function. It seems that there is no impact for the time being, but after all, the server reported an error. I would like to ask you to help check the cause. If it is a problem with other mods, of course, go to the other mods to inquire about the problem.

**Comment by KnightMiner** [comment]
This is not an issue with Tinkers Construct. I cannot help you with the issue because I did not write the mod that is generating the error. I asked how you ended up here because that error nowhere says "This is a Tinkers Construct error". The error says "IC2" and "Railcraft", two mods that are not Tinkers Construct. And no, it is not my job to talk to those other mods. You are free to talk to those other mods yourself. My job is to help with the mod I make.

We are not a modded error support forum, those exist if you want to talk to them. This issue tracker (where you are posting right now) can only help you with issues related to Tinkers Construct.
