### ISSUE TITLE
Kick when accessing Furnace controller of a too high Furnace

### ISSUE THREAD

**Issue by DemonGamingLP** [SlimeKnights/TinkersConstruct#4661]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2855

### Mantle Version

1.3.3.55

### Tinkers' Construct Version

2.13.0.183

### Describe your issue

when building a furnace thats higher than anyone would need it, you get kicked (at least for server, idk what singleplayer does, however i assume youll get the same error) with the message; "Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NegativeArraySizeException" Timestamp in debug log file: [21:06:42]

Modpack: Insanecraft.

### Crash Report

not crash; debug: https://gist.github.com/DemonGamingLP/4ae4b67b08d25f9202621627c5452c73

### Reproduced with only Tinkers' Construct?

No

### 

- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine
- [X] Confirm you have tested without external core mods/mixins

**Comment by KnightMiner** [comment]
> io.netty.handler.codec.DecoderException: java.lang.RuntimeException: VarInt too big

Looks like something is too big, probably the number of slots in the furnace (as its 4x the size and the size can get big). Probably not fixable, especially since 1.12 is only receiving minor fixes if it ever gets another build and I suspect that is deep within mojang code where the size is encoded. Make a smaller seared furnace.

**Comment by DemonGamingLP** [comment]
well after a restart the issue resolved itself for some reason.

appreciate the quick answer tho! thanks!

**Comment by KnightMiner** [comment]
Closing as 1.16 got a beta release and I have no current plans for additional 1.12 builds. This bug really requires a max size limit to fix, which is something 1.16 has.
