### ISSUE TITLE
Death `smeltery_heat.player` type not in lang file

### ISSUE THREAD

**Issue by BD103** [SlimeKnights/TinkersConstruct#4662]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

When my friend died in a smeltery, it printed `death.attack.tconstruct.smeltery_heat.player`. I could not find this in the lang file.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

I was using the Create Above and Beyond modpack. I'll try to recreate it later, sorry!

### 

- [ ] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
63cd664

**Comment by KnightMiner** [comment]
Fixed in 3.3.0.307
