### ISSUE TITLE
[eclipse/build] datagen sprite reader fails to find queens_slime_border

### ISSUE THREAD

**Issue by Magnymbus** [SlimeKnights/TinkersConstruct#4666]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.2.1.296

### Describe your issue

While running datagen in Eclipse, sprite reader fails with `Caused by: java.io.FileNotFoundException: tconstruct:textures/item/materials/generator/queens_slime_border.png` and does not generate any material sprite past that; only Constantan and Silver are generated. The image is present in eclipse's repo pull, so I'm unsure if this is a problem on my end or with the image itself.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

My own unreleased work in progress mod. https://github.com/Magnymbus/Tinkers-Epic-Fight

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Clarify, are you writing an addon or are you trying to build TiC yourself?

**Comment by Magnymbus** [comment]
Sorry, writing an addon.

**Comment by KnightMiner** [comment]
Did you follow the directions on the [Github wiki](https://github.com/SlimeKnights/TinkersConstruct/wiki/Texture-Generators-%28Modders%29#part-sprite-provider)? Notably, the existing mod? I suspect not as this works perfectly in materialis.

**Comment by Magnymbus** [comment]
I did actually. however I missed a step
