### ISSUE TITLE
[1.16.5] Client crash

### ISSUE THREAD

**Issue by zISKo666** [SlimeKnights/TinkersConstruct#4667]
### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Mantle Version

One of the versions higher than1.6.128

### Tinkers' Construct Version

Any version higher than 3.2.1.297

### Describe your issue

My client crashes when entering my server with a TC version higher than 3.2.1.297 (from jenkins)

I reported this to the @covers1624 because i thought it is related to the Enderstorage mod.
But it turns out that it is an issue with TinkerConstruct and/or Mantle (not sure about this).

Kind regards
zISKo

### Crash Report

https://pastebin.com/EAnY2mbX

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Enderstorage

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
How is this a Tinkers' Construct issue? All I see in that crash report is Ender Storage errors. If the mod author sent you here give me the exact thing they said. If not I see no reason for this to be reported to Tinkers.

Also, if this crash really happens with just the two mods, give me a crash report with no other mods installed.

----

Edit: I see digging more in the crash report one line referencing TiC, though I suspect something really broken is going on if that line is causing a crash in ender storage.

**Comment by KnightMiner** [comment]
Looks like CC is creating an [entity with a null world](https://github.com/TheCBProject/CodeChickenLib/blob/master/src/main/java/codechicken/lib/render/RenderUtils.java#L42). This violates the contact of that method, making it a bug in CodeChicken Lib, as per the java doc:
> Get the world, if available. <b>{@code null} is not allowed!</b> If you are not an entity in the world, return the overworld

Report this to CodeChicken lib and tell them to stop violating the Minecraft API.
