### ISSUE TITLE
Potions are colorless

### ISSUE THREAD

**Issue by Ch1216** [SlimeKnights/TinkersConstruct#4668]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.0.308

### Describe your issue

When putting a potion in a smeltery/foundry (I use create for this) colors shown on the drains and the smeltery controller are a white fluid ignoring whatever color the potion is (But it can be seen in the smeltery/foundry itself)

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Create.

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Ah, yes, I know why that is. Most potion fluids use NBT to store the type. Will have to decide the easiest way to fix this.

It will probably be weird as I don't think copper cans support NBT fluids so not sure the ducts will ever work, but the drains should be straight forward.

**Comment by KnightMiner** [comment]
3.3.2.324 fixes this, along with casting NBT fluids into fluid containers
