### ISSUE TITLE
Luck Modifier Inconsistency 

### ISSUE THREAD

**Issue by SpiDrone** [SlimeKnights/TinkersConstruct#4669]
### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Mantle Version

1.6.147

### Tinkers' Construct Version

1.16.5-3.3.0.308

### Describe your issue

The Tinkers book says luck can be added to a tool 3 times, but in practice it only allows the luck modifier to be applied a single time.  If its only meant to work one time, please fix the book.  vise versa

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
The book is correct, there are little arrows that show the following two recipes in the book under the first recipe, perhaps delve a little further. Also shows three recipes in JEI
