### ISSUE TITLE
Melting damaged items in smelteries leaves a residue that cannot casted into any items

### ISSUE THREAD

**Issue by ChronoVortex07** [SlimeKnights/TinkersConstruct#4671]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

I would like to report an issue on smelteries not rounding the output to the nearest item that can be casted when smelting certain items, like damaged weapon and tools. According to some members of slimeknights in the discord, this should not be the case, and they have asked me to make a report on it. This bug can be replicated by melting any meltable item with durability lost in a smeltery, and the result would be that it would often produce values smaller than a nugget which then cannot be fully extracted via casting, for example, melting a piece of leggings at about half durability would yield 3 ingots, 4 nuggets and 5 mb.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
The leftover is perfectly usable if you melt down more items. If this changes, the result will be rounding down so you get less fluid to prevent dupes. Alternatively, you could just discard the extra fluid, so not overall convinced this is a problem. It's definitely an enchancement request rather than a bug though.

**Comment by KnightMiner** [comment]
3.5.1.31 adds a new property to the damagable serializer to specify the unit size for melting, for metals for instance, the min fluid is 10mb (1 nugget), and the fluid is always rounded down to the nearest nugget.
