### ISSUE TITLE
Molten stone

### ISSUE THREAD

**Issue by InventionIO** [SlimeKnights/TinkersConstruct#4675]
### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Mantle Version

dont know, what it is. 1.6.147

### Tinkers' Construct Version

... whats the latest ? 3.3.0.308

### Problem description

you cant melt stone tools

### Suggested solution

add liquid molten stone

### Alternatives considered

none

### Additional context

already added all of it up there

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by Vojt4** [comment]
In 1.12.2 version when you melt cobblestone or store you get shared brick in ingot cast and shared stone in block cast. It was easy to mage bigger smeltery how it works in 1.16 i dont know. Wait for someone else

**Comment by KnightMiner** [comment]
You did not explain why it matters that you cannot melt stone tools. You cannot melt wooden tools either, by the logic in the suggestion should we add molten wood as well?

More importantly, what would molten stone do other than be confused with seared stone and lava?

----

Regarding getting seared stone, have you considered maybe we don't want bigger smelteries to be free? There are plenty of ways for you to produce a lot of seared stone (including melting certain mobs), so I would rather not give it to you for a block as cheap as cobblestone.

**Comment by InventionIO** [comment]
No, i dont wanna get seared stone, molten stone.

**Comment by InventionIO** [comment]
like stone but molten

**Comment by InventionIO** [comment]
you could cast stone into the cauldrons from tinkers

**Comment by InventionIO** [comment]
and bricks from ingots

**Comment by InventionIO** [comment]
> You did not explain why it matters that you cannot melt stone tools. You cannot melt wooden tools either, by the logic in the suggestion should we add molten wood as well?
> 
> More importantly, what would molten stone do other than be confused with seared stone and lava?
> 
> Regarding getting seared stone, have you considered maybe we don't want bigger smelteries to be free? There are plenty of ways for you to produce a lot of seared stone (including melting certain mobs), so I would rather not give it to you for a block as cheap as cobblestone.

Its because you cant trash them normally. wooden tools you can

**Comment by InventionIO** [comment]
like smelting with them.

**Comment by InventionIO** [comment]
Stone tools you need to burn

**Comment by InventionIO** [comment]
in fire

**Comment by InventionIO** [comment]
Wooden tools would burn there anyway, so it would be useless.

**Comment by InventionIO** [comment]
Its basically how i say it, molten stone, stone melted by lava. what else would you imagine ?

**Comment by InventionIO** [comment]
a gray molten stone.

**Comment by KnightMiner** [comment]
Github is not discord. Please post complete thoughts in a single comment rather than spamming comments.

It sounds to me like your idea is not super thought out yet. I suggest joining the SlimeKnights discord (was linked on the new issues screen) and we can discuss it further there. Overall I still don't see a need for melting stone just so you can recycle stone tools. They cost all of 3 cobblestone, which you can get in less time than it takes to melt the tools.

**Comment by InventionIO** [comment]
Wheres the link ?
