### ISSUE TITLE
Armor from Creative Menu has 1 durability

### ISSUE THREAD

**Issue by PutridNonsense** [SlimeKnights/TinkersConstruct#4676]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.1.316

### Describe your issue

Not counting the Piggybackpack, if you take an armor piece from the creative menu, it has 1 durability.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
This is a known thing, but I don't believe it can be fixed. The effects of the armor are applied on crafting, creative menu does not abide to that and therefore doesn't work. You can grab it from JEI and it should be fine however.

**Comment by KnightMiner** [comment]
For the record, same issue as #4314. Tools and tool parts are datapack controlled, but the creative search menu is loaded and frozen far before we have a chance to do anything.

For the sake of tracking, if you want to add a comment to the other issue about armor.feel free
.have to do it for pickaxes and alike.too if missing.

All in all, creative search sucks, don't use it

Anyways, I think the best "fix" for this big is just removing the armor from the creative search. Or maybe I can insert an uninitialized item, that will automatically init like crafting recipes, hmm... Not sure that's possible without a constant tick handler. Might leave this open while I consider.

**Comment by KnightMiner** [comment]
c4023c0 resolves the issue by giving tools a way to initialize their data. As a result tools obtained via the give command also automatically get NBT from datapacks set

**Comment by KnightMiner** [comment]
3.3.2.324 includes the above fix
