### ISSUE TITLE
Issue Tracker doesn't allow for posting issues via 'New issue' button

### ISSUE THREAD

**Issue by mDiyo** [SlimeKnights/TinkersConstruct#4677]
Issues can be created via https://github.com/SlimeKnights/TinkersConstruct/issues/new/, but this bypasses issue templates. Instead, the 'new issue' button leads to this screen:
![image](https://user-images.githubusercontent.com/1430358/146694896-19597baf-6c75-414f-8019-101719fa2bde.png)

**Comment by KnightMiner** [comment]
Github bug, nothing we can do about it. See github/feedback#4530, related to github/feedback#4696.

Closing as this is on Github to fix.

----

Edit: misread the issue. Github changed an optional field in the issue form to required and as a result just hides all our issue templates. They are now updated.
