### ISSUE TITLE
Shift-click crafting of new armor items have 1 durability

### ISSUE THREAD

**Issue by mDiyo** [SlimeKnights/TinkersConstruct#4678]
**Minecraft Version**
1.16.5

**Forge Version**
36.2.8

**Mantle Version**
1.6.147

**Tinkers' Construct Version**
3.3.0.312

**Describe your issue**
When making an armor item for the first time the item may be created without any NBT data. This leaves the item with 1 durability. This problem has more than one way to perform the glitch, notably when shift-crafting an item for the first time.

**Reproduced with only Tinkers' Construct?**
This may be a cross-mod interaction. If anyone has this issue, please narrow down the mods to Mantle + Tinkers' Construct and any other mods that cause the problem.

**Comment by KnightMiner** [comment]
I cannot reproduce this in testing, so either it was fixed or its a mod conflict. Going to close.

If anyone can reproduce this in 3.3.2.324 or later, leave a comment and it can be looked into again.
