### ISSUE TITLE
Traveler's vest prevent certain mods interactions when right clicking empty handed

### ISSUE THREAD

**Issue by MiyaPixai** [SlimeKnights/TinkersConstruct#4679]
### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.1.316

### Describe your issue

Interacting (right clicking) expecting an action from another mod while wearing the traveler's vest will prevent this action from happening.

Mods listed below are example mods
    1. Quarks double door opening feature: while empty handed and wearing the traveler's vest, only one door is opened.
    2. Tensura: spell casting (using right click) while empty handed and wearing the traveler's vest won't cast spell.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Quark - open double doors feature
Tensura Mod

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed by 51bee1c, will be in next alpha

**Comment by KnightMiner** [comment]
3.3.2.324 fixes this.
