### ISSUE TITLE
Tool station just doesn't exist

### ISSUE THREAD

**Issue by Ivoo09** [SlimeKnights/TinkersConstruct#4680]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.1.316

### Describe your issue

Tool forge does not exist, i installed everything on server i'm playing on with my friens, and i saw that tool station oes not exist.
The crafting for it creates  crafting statio
![2021-12-20_15 39 29](https://user-images.githubusercontent.com/86615157/146784433-ce9781bd-08d6-4c53-bfc9-2b9aea78e2a2.png)
n

### Reproduced with only Tinkers' Construct?

No

### Other mods required

No. I think not.

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
You confirmed you read the "what's new" which if you did you'd know that the table has changed names. Equally you could check the books. You're looking for the tinker station
