### ISSUE TITLE
Double jump doesn't work reliably on multiplayer

### ISSUE THREAD

**Issue by baltassarmonkey** [SlimeKnights/TinkersConstruct#4681]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.1.316

### Describe your issue

The double jump ability when applied to boots seems to only sometimes when playing multiplayer. Especially confusing, when two of us on a server both have it, only one of us can use the double jump ability at a time. Relogging or changing dimension can restore the ability, but have yet to get both of us with the ability working at the same time, in the same dimension.

One player can even not have the boots in their inventory and the other player is unable to double jump.

I haven't tested what happens what happens with more than two players.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed in cefff9d

**Comment by KnightMiner** [comment]
3.3.2.324 fixes this.
