### ISSUE TITLE
Slimeslings can occasionly fire twice on a server with bad connection

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4682]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

Mantle-1.16.5-1.6.147

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.1.316

### Describe your issue

Slime slings can sometimes fire twice. This is on a server to which I have decent connection (same city) and seems to only happen when that degrades slightly (less than the full 5 bars).

https://user-images.githubusercontent.com/73862885/146853710-c93a6cba-cc5a-4d17-8bf4-3a00b6a623e8.mp4

### Reproduced with only Tinkers' Construct?

No

### Other mods required

I have a very minimal mod list (entirely QOL and mostly client Side) and I am not the server owner so cannot change mods there for testing. Tinkers is the only large content mod however.

Extra mods are below in case needed:
Xaero's Minimap
Xaero's World Map
AppleSkin
Better Advancements
Clumps
ConnectedTexturesMod
Controlling
Fast Leaf Decay
Iron Chests
Just Enough Items (JEI)
Mouse Tweaks
Tinker's Planner
Waystones

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by Insane96** [comment]
This happenes to me in SP too when generating chunks and the internal server would lag.

**Comment by KnightMiner** [comment]
I cannot tell what is happening by watching that video. Can you clarify exactly what you mean by "fire twice"?

I assume this is caused by the sling running velocity code on both sides though, so easy enough to patch it to serverside only. Means it may end up slightly different than old slimeslings, I might want to move forwards when I properly fix the slings.

**Comment by ChiefArug** [comment]
At 00:03 I get second lot of velocity from the slimesling, speeding up again and reaching a higher height than I should be able to.

**Comment by KnightMiner** [comment]
3.3.2.324 most likely fixes this

**Comment by ChiefArug** [comment]
Yes. It was fixed. It does however now happen with slimeboots. Will make a new issue for them.
