### ISSUE TITLE
You can only use double/triple jump once when in Creative

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4683]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

Mantle-1.16.5-1.6.147

### Tinkers' Construct Version

 TConstruct-1.16.5-3.3.1.316

### Describe your issue

Reloading the world allows you to jump again, and swapping into survival, doing a double jump then swapping into creative again also works.

https://user-images.githubusercontent.com/73862885/146873906-7843efb6-b277-4e12-aea6-07841212b89e.mp4

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
You are in creative, you can fly. Not convinced it matters.

Anyways, for future reference if we ever try to fix this, the event we use to reset the number of jumps so far is the same event that handles fall damage. Probably does not run in creative. Not sure there is another way to handle it, so going to mark this as won't fix as it has basically 0 impact.
