### ISSUE TITLE
You can double/triple jump again after reloading a world

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4684]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

Mantle-1.16.5-1.6.147

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.1.316

### Describe your issue

It isn't very helpful, however does allow effectively staying in the air indefinitely.

https://user-images.githubusercontent.com/73862885/146874183-ccde959e-24f4-408a-a534-7b7f51d5add0.mp4

.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
3.3.2.324 fixes this.
