### ISSUE TITLE
Reloading a world resets cooling animations and sometimes bugs it out completely

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4685]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

Mantle-1.16.5-1.6.147

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.1.316

### Describe your issue

While the stop is only visual for some recipes, it isnt for others
https://user-images.githubusercontent.com/73862885/146874704-70bc8b4d-da7d-4d60-94cf-b36bbe3a5a3a.mp4
(for some reason this video is refusing to embed properly)

I suspect it may be composite casting that doesn't work at all, regular casts work fine (except for the reset animation) from my testing.

https://user-images.githubusercontent.com/73862885/146880650-cd46a2f2-51f4-4917-a4ad-ea6b877c0ff1.mp4

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
3.3.2.324 fixes this.
