### ISSUE TITLE
Some Clear Glass textures are missing the up side, resulting in odd looking CT

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4686]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

Mantle-1.16.5-1.6.147

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.1.316

### Describe your issue

Clear glass textures look odd when placed next to each other, some states are missing the top texture line
![2021-12-22_11 47 02](https://user-images.githubusercontent.com/73862885/147007566-3b9ad619-f385-4729-a299-207426d2b3ef.png)
After looking into the mod jar I discovered that the actual texture files are missing the line, specifically `dlr.png`, `lr.png` and `dl.png`.
I have made a resourcepack to replace these with textures that actually have the top line (pixels copied from one of the existing textures).
[glass_fix.zip](https://github.com/SlimeKnights/TinkersConstruct/files/7758785/glass_fix.zip)
And with the fix pack applied:
![2021-12-22_11 51 24](https://user-images.githubusercontent.com/73862885/147007895-a6c39a23-763d-4051-958f-ab32883f1c2b.png)

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed by a0dd0f1.

**Comment by KnightMiner** [comment]
3.3.2.324 fixes this.
