### ISSUE TITLE
Incorrect/copied mouse hovering text for "Spider Disguise"

### ISSUE THREAD

**Issue by Ramiels** [SlimeKnights/TinkersConstruct#4690]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.1.316

### Describe your issue

Incorrect text in tinker's gadgetry book for spider slimeskull "Spider Disguise", showing "Makes you look more like a skeleton to other skeletons" dispite being spider disguise and not skeleton disguise upon hovering over

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Yes, this was already fixed in 3.3.2.324, which is the latest build. Go update.
