### ISSUE TITLE
Lets talk about 1.16 Bouncy

### ISSUE THREAD

**Issue by Castone22** [SlimeKnights/TinkersConstruct#4691]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.16.5-1.6.147

### Tinkers' Construct Version

1.16.5-3.3.0.308

### Problem description

Current experience with the bouncy mod feels just... bad, when playing in SMP they have a huge delay upon hitting the ground unlike the old ones which felt way more fluid.

Example:
https://youtu.be/1YmtoGyfLsw 

### Suggested solution

Use old method for handling bounce

### Alternatives considered

or bring back old slime boots, the fact that they don't provide any armor or enchantments was a pretty big draw back anyway.

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
Why are you making a suggestion on an old alpha? Go update to the latest alpha, bouncy has changed twice since 3.3.0. Let me know if you concerns still apply.

**Comment by Castone22** [comment]
Ah i didn't realize there was a new update, i'll try on that and see what it's like and get back to you.  Create Above and Beyond seems to be locked at this version.  Depending on my findings i'll follow up with them.

**Comment by Castone22** [comment]
Thanks for the quick response, sorry about the issue, should have double checked the versions.
