### ISSUE TITLE
Rework slimesuit repair materials repaired durability

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4692]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

 Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.2.324

### Problem description

It currently takes 18 phantom membranes to repair a completely broken Slimelytra (with no durability upgrades. It increases to 37 if you have both Diamond and Netherite). This is insane and anyone who tries to obtain that many in a reasonable period of time is going to have a lot of trouble. This is also not inline with vanilla. It takes 4 membranes to repair an elytra, which has half the durability of a Slimelytra.
Likewise for Slimeboots, it takes 33 rabbit hides to fully repair a pair of broken Slimeboots. Whilst this isn't as bad because rabbits are farmable and are not limited to very specific spawning conditions, unlike phantoms, it is still a considerable effort to obtain that many.
Some Slimeskulls are similarly affected. It takes a stack and 51 (115) gunpowder to fully repair a creeper one. This sits in the same boat as the rabbit hide, its a lot but farmable if you have the dedication to. The metal based skulls are okay, as they only take around 10 ingots to repair.
The zombie one however, only takes 11 rotten flesh to repair. WHY. The easiest mob drop to get, and yet it repairs almost double phantom membranes durability. The enderman Slimeskull only requires 8 pearls, and yet that is one of the most easily farmable resources in the game (once you are in the end, which you need to be to obtain a slimeskull)
The Slimeshell is okay. It takes 30 popped chorus fruit to repair, but that is incredibly easy to obtain and farm.

Enderslimealso repairs at an abysmal rate, 8 durability per enderslime ball.  

### Suggested solution

Rethink the values for some of these materials, taking into consideration that there is no way to increase the durability repaired per piece, unlike with the Cultivated trait on tools.
Some suggestions for durability repaired: 
- All bones are fine (Further thinking and normal bones repair value should probably be decreased, however consideration needs to be taken because it is also a normal material)
- All metals are fine
- Popped Chorus is okay
- Rotten flesh - 36 to repair - 14 repair durability
- Venom - 6 to repair - 71 repair durability (Thats still 60 spider eyes, 30 fermented spider eyes, 6 spider heads or 15 melted spiders to fully repair a Cave Spider Slimeskull)
- Spider - 18 to repair - 25 repair durability
- Gunpowder - 24 to repair - 18 repair durability
- Enderpearl - 15 to repair - 40 repair durability
- Phantom - 5 to repair - 135 repair durability
- Rabbit Hide - 14 to repair - 39 repair durability
~~- Enderslime - 20 repair durability (Just a buff because 8 is terrible)~~ After actually playing a bit, eight is fine. You get stacks upon stacks from raiding end islands.

### Alternatives considered

Some way to add Cultivated or Overgrowth to armour.
Some form of Mending
Wasting 7 upgrades and an ability on Unbreakable for every single armour piece.
Using a few upgrade slots to apply Overforced and try to remember to top up Overslime often.

### Additional context

All required material amounts to repair all current slime suit pieces
![image](https://user-images.githubusercontent.com/73862885/147319103-f7107059-1181-44df-9c07-1a3e45b7f430.png)

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
This is resolved for 1.18 (see aa70581), will be backported for the final release for 1.16 later.

**Comment by KnightMiner** [comment]
Updated in 3.3.4.335 for 1.16.5
