### ISSUE TITLE
Crafting Station Not Working

### ISSUE THREAD

**Issue by mixxinitup** [SlimeKnights/TinkersConstruct#4693]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

1.16.5-1.6.152

### Tinkers' Construct Version

1.16.5-3.3.2.324

### Describe your issue

Modpack loads correctly, all items still craftable in traditional crafting table***
Able to open crafting station, place items on table, but unable to craft items.

Example:

Walk up to crafting station, access it, place items in pattern, no item available to pull as crafted item. IE. put in 3 seared bricks in V pattern, but unable to pull out spout. 

Can confirm you can craft these items in the crafting table.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Using Modpack: FTB University 1.40
Additional mod: Sophisticated bags (sophisticatedbackpacks-1.16.5-3.14.3.479)

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Test with fewer mods. I cannot help you if it takes 100+ mods to reproduce.

**Comment by mixxinitup** [comment]
Confirmed issue was resolved by removing sophisticated bag mod.

**Comment by KnightMiner** [comment]
Try reproducing with just Tinkers and Sophisticated Bags. If you can reproduce, give me your full game log.

**Comment by KnightMiner** [comment]
Closing for lack of response. Give me a minimal mod list to reproduce the bug and we can look into it again.
