### ISSUE TITLE
Ziglin skull is missing two pixels on the bottom

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4697]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

 Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.1.316

### Describe your issue

![image](https://user-images.githubusercontent.com/73862885/147437291-faabb3d0-9e43-49fe-9fbd-74dfe29edc8a.png)
As you can see the bottom is missing two pixels. This is in both the wall and normal versions
![image](https://user-images.githubusercontent.com/73862885/147437410-395be4f1-9c49-4478-b038-df3c3fa9478f.png)

### Reproduced with only Tinkers' Construct?

No

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
No its not. That is what the zombie piglin head looks like, look at it on the mob.

**Comment by ChiefArug** [comment]
Turns out they do
Mojangs even marked it as intended on their issue tracker: https://bugs.mojang.com/browse/MC-176085
Well this kinda sucks
