### ISSUE TITLE
Spamming the detonate keybind with a creeper slimeskull causes a crash

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4698]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

 Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.2.324

### Describe your issue

By spamming the detonate keybind (shift + z by default) with a creeper skull on it causes a crash.
https://user-images.githubusercontent.com/73862885/147442548-c2836c01-948b-430f-9f61-51bfae358bfa.mp4

### Crash Report

https://gist.github.com/ChiefArug/d5e8e46b8ede2a319bf34623e622a322

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
... okay, but why are you doing that?

**Comment by KnightMiner** [comment]
Fixed in 3.3.3.332
