### ISSUE TITLE
Materials and You Text Overflow

### ISSUE THREAD

**Issue by MagicMason1000** [SlimeKnights/TinkersConstruct#4699]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2855

### Mantle Version

1.3.3.55

### Tinkers' Construct Version

2.13.0.183

### Describe your issue

The text on the Materials and You book overflows and goes off the screen:
![image](https://user-images.githubusercontent.com/46111269/147519734-f5cf2d25-193f-42eb-b220-2859606da658.png)
This happens for a few pages whenever there is a large block of text:
![image](https://user-images.githubusercontent.com/46111269/147519779-a7e06e17-2bca-4e1b-9712-c631fa08c9c7.png)
If there is a quick way to make the text have a smaller area to fit into, that might work.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine
- [X] Confirm you have tested without external core mods/mixins

**Comment by MagicMason1000** [comment]
Nevermind, after reloading the game it worked.

**Comment by KnightMiner** [comment]
Looks like the common optifine bug.
