### ISSUE TITLE
Plate armor having nothing but 1 durability, exept the helmet which worked just fine

### ISSUE THREAD

**Issue by Namekiangod77** [SlimeKnights/TinkersConstruct#4700]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.1.316

### Describe your issue

Just like the title says, but it fixed once I leaved and rejoined the world

### Reproduced with only Tinkers' Construct?

No

### Other mods required

CodeChicken Lib 1.8.+ version:CodeChickenLib-1.16.5-4.0.5.438-universal.jar
Hwyla version:Hwyla-forge-1.10.11-B78_1.16.2.jar
Just Enough Items (JEI) version:jei-1.16.5-7.7.1.138.jar
Waila Harvestability version:WailaHarvestability-mc1.16.x-forge-1.1.15.jar

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [ ] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
That little check mark of "Searching the issue tracker" would have saved you time if you looked as this was already fixed in an update
