### ISSUE TITLE
Tinkers Anvil allows removal of Curse of Binding armour

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4702]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

 Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.2.324

### Describe your issue

You can remove Curse of Binding armour using the armour slots in the Tinkers Anvil UI.

https://user-images.githubusercontent.com/73862885/147723602-73557148-118a-49be-8f3e-b21f256296ab.mp4

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed in 3.3.3.332
