### ISSUE TITLE
Magnetic on armour works in Spectator mode

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4703]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

 Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.2.324

### Describe your issue

https://user-images.githubusercontent.com/73862885/147864911-d2dd1b8e-2b1e-4ea9-ba0a-5cd4840441fe.mp4

It works very well for revealing your position

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by BloodshotPico** [comment]
Is this spectator mode?

**Comment by KnightMiner** [comment]
> Is this spectator mode?

Did you try reading issue title? Its pretty clear this issue is about spectator mode.

**Comment by KnightMiner** [comment]
Fixed in 3.3.3.332
