### ISSUE TITLE
Auto-tinker

### ISSUE THREAD

**Issue by janIpen** [SlimeKnights/TinkersConstruct#4706]
### Minecraft Version

1.16.5 (create above and beyond 1.3)

### Forge Version

(create above and beyond 1.3)

### Mantle Version

(create above and beyond 1.3)

### Tinkers' Construct Version

(create above and beyond 1.3)

### Problem description

I am playing on my server, and my only diamond pickaxe is about to break.

### Suggested solution

Automatically convert crafted tools into tinkers construct tools

### Alternatives considered

None

### Additional context

create above and beyond 1.3

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
Take your diamond pickaxe, melt it in a smeltery (using blazing blood) and turn the diamond into the diamond modifier. Or use it to mine some obsidian/cobslt. There, gave you alternatives to consider.

I have no plans to force everyone playing a pack with this mod to use tinker tools. They are intentionally optional so you can choose to use them or vanilla tools at your discretion. It's not tinkers job to make sure you don't waste your vanilla tools.
