### ISSUE TITLE
Typo in Encyclopedia Haste description

### ISSUE THREAD

**Issue by BHuntemann** [SlimeKnights/TinkersConstruct#4709]
### Minecraft Version

1.16.5

### Forge Version

\*

### Mantle Version

\*

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

There is a typo in the [encyclopedia's haste decription](https://github.com/SlimeKnights/TinkersConstruct/blame/1.16/src/main/resources/assets/tconstruct/book/encyclopedia/en_us/upgrades/harvest/haste.json#L5). A percent sign is missing

Current: `"On harvest tools and weapons, grants +5 mining speed and +5% attack speed per level."`
Fixed: `"On harvest tools and weapons, grants +5% mining speed and +5% attack speed per level."`

### Reproduced with only Tinkers' Construct?

No

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
No, it is correct. It grants 5 mining speed. Look at how your mining speed stat goes up when you apply haste. If you start with `X` mining speed, you end with `X + 5`

Attack damage is a percent boost. Meaning if you start with `X`, you end with `X * 105%`
