### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Elfinlocks** [SlimeKnights/TinkersConstruct#4711]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Describe your issue

Tinker's crashed upon load with the following repor
[crash-2022-01-11_22.23.58-fml.txt](https://github.com/SlimeKnights/TinkersConstruct/files/7851459/crash-2022-01-11_22.23.58-fml.txt)
t

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Occurred in the following modpack ver:

https://www.curseforge.com/minecraft/modpacks/astral-engineering/files/3600278

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Someone broke the game state causing registry events to not fire, nothing we can do. If you give me a full game log I might be able to find the actual exception that broke the game state.

**Comment by KnightMiner** [comment]
Closing for lack of response, I cannot do anything without a full log, and honestly its not a tinkers bug, its whoever broke the game state causing registry events to fail.
