### ISSUE TITLE
[1.16.5] Iron Reinforcement is super annoying to make

### ISSUE THREAD

**Issue by LuciusV** [SlimeKnights/TinkersConstruct#4712]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

Mantle-1.16.5-1.6.127

### Tinkers' Construct Version

TConstruct-1.16.5-3.2.1.296

### Problem description

It just takes a lot of BORING clicks to get reinforcement 5. Please simplify recipe (not materials required, they are ok)

### Suggested solution

Just make some another convenient way of making Iron Reinforcement without BORING CLICKS FOR HALF AN HOUR

### Alternatives considered

Make Iron Reinforcement use more materials and make upgrade require proportionally less of them

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
Use hoppers. It's super trivial to automate the two parts. First, put a hopper under a table to create the obsidian panes. Next, put a second hopper in the side to add panes to a table to put the iron on. It was quite simple to do in my survival world
