### ISSUE TITLE
Nahuatl's large plate doesn't use the correct texture

### ISSUE THREAD

**Issue by That-One-Dude** [SlimeKnights/TinkersConstruct#4714]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Describe your issue

Nahuatl large plate uses the wrong texture. It should use the wooden large plate texture, but it uses the default

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Tinkers Archery

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Nahuatl does not fall back to wood textures for any other part, why do you believe the large plate should? It uses the `constrast` default only

**Comment by That-One-Dude** [comment]
mostly because it looks weird for it to not use the wooden large plate, given how it is produced and the nahuatl plank block

**Comment by KnightMiner** [comment]
This is resolved for 1.18. Will likely backport in the final 1.16 build

**Comment by KnightMiner** [comment]
Resolved by 7ddb532 for 1.16

**Comment by KnightMiner** [comment]
Fixed in 3.3.4.335 for 1.16.5
