### ISSUE TITLE
Bones use the wrong model

### ISSUE THREAD

**Issue by That-One-Dude** [SlimeKnights/TinkersConstruct#4716]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Problem description

Bones use the wrong model. The vanilla bone has the model parent item/handheld parent, but Necrotic Bone, Bloodbone, Necronium Bone, and Blazing Bone use the forge:item/default parent

### Suggested solution

change those item models to have the item/bone model

### Alternatives considered

You could change the models to be the same as bone, but not using the item/bone parent

### Additional context

![2022-01-13_16 18 59](https://user-images.githubusercontent.com/55768623/149418095-2953dbe2-c2b7-4526-bd39-f8324382e959.png)

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
I think you misunderstand how model parents work. A custom model loader that generates quads cannot parent to a vanilla model. So yes, I agree the model angles are wrong, but your solution is not the right one.

Forge probably has a transform set that can be used without parenting the the vanilla generated model.

**Comment by That-One-Dude** [comment]
huh. I think forge:default-tool has the desired angles

**Comment by KnightMiner** [comment]
This is resolved for 1.18. Will likely backport for the final 1.16 release.

**Comment by KnightMiner** [comment]
Fixed in 3.3.4.335 for 1.16.5
