### ISSUE TITLE
Incorrect description of "Mighty Smelting"

### ISSUE THREAD

**Issue by koh-gh** [SlimeKnights/TinkersConstruct#4717]
### Minecraft Version

1.16.5

### Forge Version

36.2.23

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Describe your issue

![2022-01-14_16 09 23](https://user-images.githubusercontent.com/36918206/149468956-c47bf60b-281c-4986-ac64-aafdac9bb55d.png)
"Weapon Abilities" page describes about "Weapon Upgrades".
Encyclopedia seems correct.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by koh-gh** [comment]
Another one in Encyclopedia.

![2022-01-16_17 39 18](https://user-images.githubusercontent.com/36918206/149653113-99d42c0d-b761-4db8-83e8-11015416bce0.png)
"Armor Upgrades" page describes about "Armor Abilities".

**Comment by KnightMiner** [comment]
This is resolved for 1.18. Will likely backport for the final 1.16 release.

**Comment by KnightMiner** [comment]
Fixed by 4c56081 for 1.16.5

**Comment by koh-gh** [comment]
Armor Upgrades page does not seem to be fixed.

**Comment by KnightMiner** [comment]
Fixed in 3.5.1.31
