### ISSUE TITLE
Skyroot Trapdoor

### ISSUE THREAD

**Issue by AcidArmy** [SlimeKnights/TinkersConstruct#4719]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.2.324

### Describe your issue

Skyroot and Bloodshroom trapdoor textures are not consistent with vanilla behavior. See picture:
![image](https://user-images.githubusercontent.com/17466447/149638673-69c18055-76c8-404c-8dc2-3e7b87572de3.png)
![image](https://user-images.githubusercontent.com/17466447/149638689-5e36008f-e9fd-4e01-9379-ad2e644ec1ae.png)

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
I think you are using a resource pack. The vanilla 1.16.5 models do not make trapdoors 3D
