### ISSUE TITLE
3 hands while holding a map

### ISSUE THREAD

**Issue by MasterSloth1** [SlimeKnights/TinkersConstruct#4721]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

Tconstruct-1.16.5-3.3.2.324

### Describe your issue

If you have a piece of armour with the modifier `Unarmed Attack`, then hold a map in your main hand and look down at the map you will notice there are now 3 hands. Removing the armour piece removes the 3rd hand.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [ ] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Lets try this issue report again. When we ask you to reproduce without other mods, that means you reproduce the issue without other mods. Saying no and not giving a minimal mod list is not a useful report.

**Comment by MasterSloth1** [comment]
sweet,
i have reproduced the issue with just Tconstruct, Mantle and Jei
using the same versions of the mods i listed above

**Comment by KnightMiner** [comment]
Leaving this comment as a reminder to myself to backport the fix to 1.16

**Comment by KnightMiner** [comment]
Fixed in 3.3.4.335 for 1.16.5
