### ISSUE TITLE
Allow Slime flora to be placed into Flower Pots

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4722]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

 Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.2.324

### Problem description

Slime flora cannot be placed into flower pots.

### Suggested solution

Allow things such as the four types of Slimy saplings (Greenheart, Skyroot, Enderslime and Bloodshrrom), Slimy Tall Grass and Slimy Ferns to be placed into flower pots, which will allow decorating with them.

### Alternatives considered

Force people to use slimedirt blocks to decorate with these plants.
Slimy Pots for Slimy flora, crafted with Slimy Dirt or maybe Slimy Seeds. Would fit in aesthetically too.

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
Added in 3.6.0.73
