### ISSUE TITLE
Slime island structures do not process jigsaw blocks correctly.

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4723]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

 Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.2.324

### Describe your issue

You can replace slime island structures using datapacks. When replacing ~~any~~ vanilla structures *that support it* you can use a series of jigsaw blocks to randomly generate parts of the structure (villages are a ton of jigsaw blocks). When using jigsaw blocks on slime islands however, they do not properly generate the parts attached to them like they should. 

This example datapack replaces all sky slime variant islands with a simple structure with some jigsaw blocks. It also does the same for all plains villages (exactly the same structure): 
[data.zip](https://github.com/SlimeKnights/TinkersConstruct/files/7895097/data.zip)

To reproduce, generate a world with the seed `8577580297105733120` and the datapack enabled (use the Datapacks button on the world creation screen). 
Then `/tp -203 150 397` for a slime island: (note the lack of 'bridges')
![image](https://user-images.githubusercontent.com/73862885/150087485-45d73b00-1ab9-4a39-a9bb-c142b18206b7.png)

`/tp -674 69 1074` for a village, where it works (the 'bridges' are it working)
![image](https://user-images.githubusercontent.com/73862885/150087537-e0fdec63-f0d3-47eb-a69b-2fef24c22a49.png)

Note that some processing is done on them, they do get replaced with their 'replace block' (the block they turn into after generating their structure), but the actual placing of the additional parts of the structure does not happen.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
> When replacing any vanilla structure you can use a series of jigsaw blocks to randomly generate parts of the structure (villages are a ton of jigsaw blocks).

Going to need more evidence for that statement. You only told me villages support jigsaw blocks. What about ruined nether portals? It sounds to me like villages are a jigsaw structure but not every structure is a jigsaw structure.

**Comment by ChiefArug** [comment]
You are correct, it turns out at least both ruined portals and shipwrecks do not generate jigsaw blocks, just like the slime islands.
Datapack used to test it incase anyone wants it:
[data.zip](https://github.com/SlimeKnights/TinkersConstruct/files/7910549/data.zip)
 
This does make this a feature request then, not a bug report.

**Comment by KnightMiner** [comment]
I'm not convinced its worth adding support for jugsaw blocks unless we use them, its a pretty big refactor. You are free to attempt to PR it, but otherwise this request will likely never be added.

**Comment by KnightMiner** [comment]
Going to close this as I have no plans for jigsaw support on 1.16, and 1.18 structures are so much of a mess I want to deal with them as little as possible. If you can make a minimal changes required PR to 1.18 to add jigsaw support I will accept it, otherwise just accept the islands do not do jigsaw
