### ISSUE TITLE
Typo in Cleaver's description

### ISSUE THREAD

**Issue by HarutyunSoghomonyan** [SlimeKnights/TinkersConstruct#4724]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Describe your issue

There's a typo in Cleaver's description. The word _though_ should be changed into _through._

"item.tconstruct.cleaver.description": "The Cleaver is a weapon for a smeltery master. High range attacks keep cut **_though_** the toughest of foes."

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Fixed by 8e187c7 (1.18.1) and [4c56081](https://github.com/SlimeKnights/TinkersConstruct/commit/4c560816afe7f13e3875e25c30093e1d9dd7fef4) (1.16.5)

**Comment by KnightMiner** [comment]
Fixed in 3.3.4.335 for 1.16.5
