### ISSUE TITLE
Armor Protection Balance

### ISSUE THREAD

**Issue by dannydjdk** [SlimeKnights/TinkersConstruct#4726]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Problem description

Maxing out the armor defense slots results in protection that is significantly less protective than the maximum vanilla protection enchants.

Vanilla Protection IV provides 16% protection from most types of damage each piece, providing a total of 64% protection from most types of damage if all pieces are enchanted. The specific protection enchants (blast, projectile and fire protection) at level IV provide 32% protection, theoretically allowing 128% protection but capped at 80%.

Currently, with the plate armor, you can, at maximum achieve 64% protection from a single type of damage. If you want to attempt to protect from 4 different types of damage to get something like vanilla's Protection, you can, at max get 16% protection with the entire set maxed out. This is almost, but not quite, as good to a vanilla set of armor with Protection I. "Almost" because vanilla protection actually protects from all 5 and more (like ender pearl damage, for instance).

I understand that this armor is potentially more powerful than vanilla's armor due to the upgrades and abilities, but vanilla's general Protection IV enchant is extremely powerful. I feel that its absence here tips the balance too far in the other direction.

### Suggested solution

I think it would be a fair balance for either the existing defense upgrades to provide a greater amount of protection, and/or the addition of a general Protection upgrade similar to vanilla's protection.

### Alternatives considered

Not sure if this would be too complicated, but perhaps general protection defense upgrades would only provide 2% protection, and an ability slot could be used to double any defense upgrades, bringing them up to vanilla's. This would provide a counterbalance such that if you want full vanilla protection, then you need to choose it instead of another ability.

### Additional context

I absolutely love this armor!
Thank you!!!

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
> Currently, with the plate armor, you can, at maximum achieve 64% protection from a single type of damage. 

Uh, what? You can receive a full 128% capped at 80% just like vanilla. Don't know how you came up with 64%. Note melee protection has a bugged tooltip, it protects twice as much as it lists.

> If you want to attempt to protect from 4 different types of damage to get something like vanilla's Protection, you can, at max get 16% protection with the entire set maxed out. 

32% with the entire set maxed out, assuming you choose 4 different types.

> "Almost" because vanilla protection actually protects from all 5 and more (like ender pearl damage, for instance).

Melee protection protects against everything the other four types don't, which includes ender pearl damage.

> but vanilla's general Protection IV enchant is extremely powerful.

Hence why I did not include it, it removes all interesting choice to the system.

----

As for your solutions,

> and an ability slot could be used to double any defense upgrades, bringing them up to vanilla's

Where are you getting these numbers that they are half vanilla? With the exception of not providing protection, all our enchants are actually stronger than vanilla as it provides the exact same protection and we provide more secondary effects.

> I think it would be a fair balance for either the existing defense upgrades to provide a greater amount of protection, and/or the addition of a general Protection upgrade similar to vanilla's protection.

Adding more protection means they are strictly better than the vanilla ones, not sure I want to go that route. I do have a plan for an end tier modifier to allow you to get +1 defense slot, letting you go up to 40% with the whole set, though that will not happen until 1.18 or later. Still not vanilla's 64%, but as you said vanilla protection is kinda OP. I agree its worth coming up with a way to make up the difference, a defense based ability modifier is probably the best way to go. Have to think about how to do it so armor does not end up too strong, perhaps limiting it to a single level would be enough, 8% on all four pieces means +32% defense, added to the 32% of each unique type gives you vanilla's 64%.

**Comment by dannydjdk** [comment]
The bugged tooltip IS where I came up with the 64% figure. So really, the whole premise of my proposed solution is flawed.
Now that I know the upgrades are providing 8% protection and not 4%, the whole system makes a lot more sense, and the challenge of deciding which and how much of each protection upgrades to apply feels a lot more reasonable and interesting.

The solutions you propose in the last paragraph would be amazing: definitely better than mine. In fairness though, I was working with bad data. 😛

**Comment by KnightMiner** [comment]
For the record, only melee protection had a bugged tooltip. Every other variant of protection had a correct tooltip.

Doing more math, I think the best plan is an ability that provides +6% on the first level, +4% on the second. That means at most you get +40% protection from the ability. Combined with the +40% once the final defense slot is added means you get the max possible, +80% against almost types of damage (at a huge cost to you)

**Comment by KnightMiner** [comment]
1.18 adds the protection ability, and 3.3.3.332 fixes the tooltip on melee protection. I'll probably backport the protection ability to 1.16 in the final release.

**Comment by KnightMiner** [comment]
a2dfc65 adds the protection ability modifier to 1.16.5

**Comment by KnightMiner** [comment]
Added in 3.3.4.335 for 1.16.5
