### ISSUE TITLE
Configurable Dragon Scale Blasting

### ISSUE THREAD

**Issue by Alcates** [SlimeKnights/TinkersConstruct#4728]
### Minecraft Version

1.16.5

### Forge Version

36.2.21

### Mantle Version

1.6.154

### Tinkers' Construct Version

3.3.2.324

### Problem description

There currently does not appear to be any way to configure whether or not the dragon drops scales when blasted.

### Suggested solution

The simplest solution would be a true/false variable in the config file to toggle whether or not the dragon drops dragon scales when blasted.

### Alternatives considered

An alternative solution would be to implement blasting as a sort of crafting recipe, much like entity melting or severing currently is. This would enable pack devs to have any item drop from any entity when hit by an explosion.

### Additional context

I was instructed by KnightMiner on the Discord to post this here.

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
Added in 1.18 in e9c48da (3.4.1.46), will be backported to the last release of 1.16.5

**Comment by KnightMiner** [comment]
Added in 3.3.4.335 for 1.16.5
