### ISSUE TITLE
Error when loading new world

### ISSUE THREAD

**Issue by Zer0-kUn** [SlimeKnights/TinkersConstruct#4729]
### Minecraft Version

1.16.5

### Forge Version

36.2.21

### Mantle Version

1.16.5-1.6.152

### Tinkers' Construct Version

1.16.5-3.0.2.84

### Describe your issue

When trying to load a new world with the modpack i put together myself, it seems to give an error.
I have no clue if it has to do with any other mods or something.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [x] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [x] Confirm you have searched the tracker to see if your issue already exists
- [x] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
Update your mod you're on an extremely old version

**Comment by KnightMiner** [comment]
Also, never make an issue report saying it errors without providing the error message. I can do nothing for a crash without a crash report.

**Comment by Zer0-kUn** [comment]
the mod itself or mantle?

**Comment by KnightMiner** [comment]
Update everything. There is absolutely no reason to be playing an old version of any mod except in extreme cases.

**Comment by Zer0-kUn** [comment]
so you want me to update everything to 1.18 versions?

**Comment by KnightMiner** [comment]
That is not what I said. You are playng 1.16. Stop playing old mods on 1.16. Play the latest mods on 1.16. It is a very straightforward idea, don't play old builds of mods when you can play new builds.

**Comment by Zer0-kUn** [comment]
i get that but i cant seem to find the 1.16.5 version on curseforge to start with.
this is the version i found when searching "tinkers construct 1.16.5" on google.
all the ones i found on curseforge are 1.12.

**Comment by Zer0-kUn** [comment]
i have no clue how github works so if ur telling me i can download it here then please provide a link or a zip file

**Comment by KnightMiner** [comment]
Its on curseforge. Click files then view all

**Comment by Zer0-kUn** [comment]
alright found it! Thanks for the help! im totally not experienced in stuff like this so its all figuring out for me xD
