### ISSUE TITLE
Mod conflict/unwanted behavior

### ISSUE THREAD

**Issue by castilio20** [SlimeKnights/TinkersConstruct#4731]
### Minecraft Version

1.16.5

### Forge Version

1.16.5-forge-36.2.23

### Mantle Version

Mantle-1.16.5-1.6.152

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.2.324

### Describe your issue

Lost Trinkets adds an ability that can repair items that is held in hand and it works with tinker construct to ( unwanted behavior)

### Crash Report

no

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Lost Trinkets and the dependency Lollipop

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
I don't understand this issue report. Another mod *lets you* repair our tools? That sounds like intended behavior for a mod that lets you repair tools in the hotbar. If you dislike this behavior, you should request that Lost Trinkets adds a blacklist, as there is nothing we can do to prevent another mod from repairing our tools.
