### ISSUE TITLE
Crafting station invisible outputs

### ISSUE THREAD

**Issue by Mofo50C** [SlimeKnights/TinkersConstruct#4732]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Mantle Version

1.3.3.55

### Tinkers' Construct Version

1.12.2-2.13.0.183

### Describe your issue

Crafting the quark added recipes: slabs into blocks, stairs into blocks and slabs into stairs with the Tinkers crafting station causes desync and the output of the recipe to be invisible. You can click on the slot and it gives the items correctly and they become visible again. Also leaving the station with the ingredients in and re-opening it also makes the output visible again. This doesnt happen in the vanilla crafting table. It also happens to any slabs/stairs modded or vanilla and even the ones from quark and tinkers.

[Slabs to blocks](https://user-images.githubusercontent.com/21063744/152173941-07143070-850f-4a34-8d5f-230d9b11621d.png)

[Stairs to blocks](https://user-images.githubusercontent.com/21063744/152173997-345b09b6-fa88-4f37-8904-5f28d1b66970.png)

[Slabs to stairs](https://user-images.githubusercontent.com/21063744/152174047-dad19d5b-cd8c-4e23-889e-3c2652c94ffa.png)

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Quark + AutoRegLib

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by Mofo50C** [comment]
Also idk why github has automatically added the 1.16 label

**Comment by ShinyPorygon** [comment]
1.12 Is now no longer receiving support in the form of updates as 1.16 has a beta release.

**Comment by Mofo50C** [comment]
its a bug though :/

**Comment by Mofo50C** [comment]
> 1.12 Is now no longer receiving support in the form of updates as 1.16 has a beta release.

But its still a bug

**Comment by ShinyPorygon** [comment]
And 1.12 is still unsupported. 1.12 has not had a release for almost two years now. If this happens in 1.16 or 1.18 it can be addressed. But 1.12 will no longer receive any updates. If this is even a bug on tinkers end, and it would have been caught a long time ago it could have been fixed. But officially 1.12 is EOL (End of life) for tinkers. All bugs that exist now will exist forever.

The 1.12 issue report template got taken off to even further indicate this

**Comment by Mofo50C** [comment]
> And 1.12 is still unsupported. 1.12 has not had a release for almost two years now. If this happens in 1.16 or 1.18 it can be addressed. But 1.12 will no longer receive any updates. If this is even a bug on tinkers end, and it would have been caught a long time ago it could have been fixed. But officially 1.12 is EOL (End of life) for tinkers. All bugs that exist now will exist forever.
> 
> The 1.12 issue report template got taken off to even further indicate this

kinda cringe

**Comment by KnightMiner** [comment]
For the record, no one else has reported this issue in the past two years and there have been many packs with both Tinkers and quark. The problem is in your setup, not the mod.

And yes, it is pretty cringy when someone is told a version is unsupported but continues to pretend it's supported.

**Comment by Mofo50C** [comment]
> For the record, no one else has reported this issue in the past two years and there have been many packs with both Tinkers and quark. The problem is in your setup, not the mod.
> 
> And yes, it is pretty cringy when someone is told a version is unsupported but continues to pretend it's supported.

when did i pretend it was supported i literally didnt know until the other guy told me. And no it isnt a problem with my setup its literally a fresh environment only tinkers and quark what ever tho its unsupported type less mald more
