### ISSUE TITLE
Tinkers 1.18 messes with Texturepack and Journeymap when Optifine is enabled

### ISSUE THREAD

**Issue by Jessman5** [SlimeKnights/TinkersConstruct#4735]
### Minecraft Version

1.18.1

### Forge Version

39.0.64

### Mantle Version

1.8.31 Alpha

### Tinkers' Construct Version

3.4.0.34 Alpha

### Describe your issue

I have a cutom modpack that includes Journeymap and Optifine. I added TC to my game today and since then I have issues regarding my texturepack and Journeymap. 
I have put an issue in the Journeymap repo first because I didn't know if this part is TC or JM related or both. These issues don't occur, when TC is removed/disabled. 

So what happens:
when I start the game with TC, the log throws a lot of errors regarding my texturepack and errors about the JM rendering. In the game the textures for some blocks are missing then. (notice the tree stems on the right and the gravel at the bottom)
<img width="1018" alt="Bildschirmfoto 2022-02-03 um 20 30 21" src="https://user-images.githubusercontent.com/4819469/152415406-4c42f123-53ec-462f-b61a-02e0f64c997a.png">

After disabling the texturepack, everything is fine, except for JM still being messed up.
<img width="1014" alt="Bildschirmfoto 2022-02-03 um 20 30 35" src="https://user-images.githubusercontent.com/4819469/152415636-de36eceb-40a4-43d1-b934-01efbd10d077.png">
<img width="1016" alt="Bildschirmfoto 2022-02-03 um 20 30 53" src="https://user-images.githubusercontent.com/4819469/152415715-3ffa7f92-5563-4cae-ae63-d8fe88d0a05c.png">

Enabling the texturepack again, textures are again missing but this time not all of them (notice the tree stems and the gravel again.) So it's kinda randomly messing with textures.
<img width="1013" alt="Bildschirmfoto 2022-02-03 um 20 31 17" src="https://user-images.githubusercontent.com/4819469/152415955-720f1aec-71f4-4314-979d-17bb2b734721.png">
If I disable and enable the texturepack again a couple of times, the missing textures will be gone. But the JM issue still exists. 

What I found out after that: 
JM + Optifine = all good
JM + Optifine + TC = messed up
JM + TC = map looks like the messed up screen first but gets to normal shortly after.

When Optifine is disabled, the issues with the textures are gone but JM is still messed up for a second or two. It goes back to normal then. So I guess it's rather an issue with TC + Optifine that messes up the textures and JM second handedly.

I don't know if TC is not supporting Optifine anymore? I never had issues like that before and I used the 1.16.5 version with Optifine too.

I also attached the latest log and the JM log files (with Optifine enabled):
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/7997547/latest.log)
[journeymap.log](https://github.com/SlimeKnights/TinkersConstruct/files/7997550/journeymap.log)
And here's the issue in the JM repo in case you'd like to see the conversation https://github.com/TeamJM/journeymap/issues/391

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Okay, and Optifine also crashes Tinkers. See pinned issues, optifine is not supported

> I don't know if TC is not supporting Optifine anymore? 

Never did in the first place. The question is whether Optifine is supporting Tinkers.

**Comment by KnightMiner** [comment]
For the record, you error is
> [20:10:48] [Worker-Main-37/ERROR]: Using missing texture, unable to load minecraft:textures/item/stone_pickaxe.png : java.io.FileNotFoundException: /Applications/ATLauncher.app/Contents/Java/instances/118clone/resourcepacks/j5 textures 1.18 v0/assets/minecraft/textures/item/stone_pickaxe.png (Too many open files)

The last part says too many open files, probably a memory issue.

**Comment by Jessman5** [comment]
okay thanks!
