### ISSUE TITLE
Seared brick casting requires wrong amount of Seared Stone

### ISSUE THREAD

**Issue by Funnymeme1** [SlimeKnights/TinkersConstruct#4736]
### Minecraft Version

1.18.1

### Forge Version

39.0.64

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.0.4.34

### Describe your issue

Seared bricks cast for 90 mB of seared stone, while every other recipe treats them as 250 mB per brick

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Huh, weird. Must have missed that when I changed the brick scale. For content, in 1.16 bricks were on the ingot scale, switched them to the clay scale in 1.18.

**Comment by KnightMiner** [comment]
Fixed in 3.4.1.45.
