### ISSUE TITLE
Travelers Boots crashing the game

### ISSUE THREAD

**Issue by AscheWolf** [SlimeKnights/TinkersConstruct#4738]
### Minecraft Version

1.18.1

### Forge Version

39.0.59

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.0.34

### Describe your issue

When i tried to equip the Boots, my game crashed and after a restart of Minecraft my Game keeps on crashing, as soon as i try to open my inventory.

I tried it with only TConstruct, Mantle and latest Optifine and still get the same result.

### Crash Report

https://pastebin.com/BSsRTJKm

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Check if you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Check if you have searched the tracker to see if your issue already exists
- [X] Check if you are not using performance enhancers, such as optifine
- [X] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by mDiyo** [comment]
☑ Check if you are not using performance enhancers, such as optifine
☑ Check if you did not read all of the above checkboxes and just checked all the boxes
 The crashlog says you have OptiFine installed. Try again.
 
 OptiFine does not do what you think it does.
 https://web.archive.org/web/20210131212246/https://gist.github.com/jellysquid3/e46882e37907dfbb3d03d26f589b1c6a
 
 If you want shaders, grab these and turn fabulous graphics on.
 https://github.com/bradleyq/mc_vanilla_shaders/releases/tag/v2.3

**Comment by KnightMiner** [comment]
For the sake of record keeping, duplicate of #4734 

Also, because you are the third person reporting this and I still have not seen it on the optifine issue tracker, you can report bugs to optifine. Go report this at https://github.com/sp614x/optifine/issues. Its their problem, not ours.
