### ISSUE TITLE
Crash with Traveler's Goggles

### ISSUE THREAD

**Issue by Cicopath** [SlimeKnights/TinkersConstruct#4739]
### Minecraft Version

1.18.1

### Forge Version

39.0.66

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.0.34

### Describe your issue

On a server with two other players, we all had OptiFine installed; no problems arose with any of the mods we have. Recently, we added Tinker's Construct.

One of the players, who I will refer to as PLAYER3, had created the Traveler's Goggles. He successfully crafted them and put them in his inventory. However, once he wore them, his Minecraft crashed.

After hearing this and doing some research, it seemed that OptiFine was the main cause of this. To test it out, I simply removed OptiFine from my mods folder. Upon rejoining the server, I crafted the Traveler's Goggles, put them in my inventory, and wore them; no crash occurred. However, the other player, who I will refer to as PLAYER2, still had OptiFine installed, and he crashed upon my character loading while I wore the Traveler's Goggles.

Both crash logs are reported below.

From this, it appears that none of the installed mods had any elation to the crashes except Tinker's Construct and OptiFine. Indeed, once OptiFine was removed from the mods folder, the Traveler's Goggles could be worn without any crashes occurring. In addition, half of the mods add new structures and affect only world generation, not add new blocks. The mods that add new blocks, items, mobs, and so on, which could be related to the crashes, will be listed below.

I completely understand this may not be an issue the developers of Tinker's Construct can fix. I am simply posting the issue here to make it known.

### Crash Report

https://paste.gg/p/anonymous/a1b208c586414fcaa17a4233c4ee9338

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Ars Nouveau
Waystones
Farmer's Delight
Mystical Agriculture
MrCrayfish's Furniture Mod
Building Gadgets

### Confirm the following

- [ ] Check if you are not using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you have look at FAQ to see if your issue is answered
- [ ] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by KnightMiner** [comment]
Try that second checkbox again. This is a duplicate of #4734, which was pinned. Optifine is a bad mod, okay?

**Comment by Cicopath** [comment]
This may be considered a duplicate of #4734,

**Comment by Cicopath** [comment]
I was told to report this here as part of the OptiFine issue tracker.

**Comment by KnightMiner** [comment]
and it was already reported here. You could have just linked the existing issue for Optifine.

**Comment by Cicopath** [comment]
You mean reference #4734 in my post? I was just going to reference in the comments. Or, edit the post to include it if necessary. I reported the issue here as part of the OptiFine issue tracker; forgive me for following the direction of another administrator, even after stating it was an OptiFine issue. I realize the team has to deal with many of these reports, especially since, from my understanding, they cannot directly fix it, but my goodness.

EDIT: Nonetheless, at least it adds to the OptiFine issue tracker.

**Comment by KnightMiner** [comment]
Does the optifine issue tracker not let you report a bug without opening a new issue for the mod dev? You should be able to link an already existing issue. That is, link #4734 in your issue on Optifine.

**Comment by Cicopath** [comment]
Oh my god... I am dumb. I just realized the administrator linked me the actual OptiFine GitHub to report the problem. Please forgive my stupidity, I thought I was to provide more proof here of the OptiFine crash... for some reason. Again, forgive me!

**Comment by ghost** [comment]
Tinkers optifine is not supported
