### ISSUE TITLE
Desync when pouring from a melter/smeltery into a casting basin/table

### ISSUE THREAD

**Issue by TJT01** [SlimeKnights/TinkersConstruct#4743]
### Minecraft Version

1.18.1

### Forge Version

39.0.66

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.0.34

### Describe your issue

Pouring fluids from a melter or smeltery into a casting basin or casting table will cause a clientside desync; where the client thinks there's less fluid than what's actually there.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Check if you are not using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you have look at FAQ to see if your issue is answered
- [ ] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by KnightMiner** [comment]
I have not personally noticed any desync, and I've even been testing the mod on a rather laggy server. Can you give a bit more information about your environment?

**Comment by TJT01** [comment]
This test was done in a singleplayer world. OS is Windows 10; 64 bit.

https://user-images.githubusercontent.com/87955906/152845876-62b58783-bd58-443e-8c90-82ce46be0b1a.mp4

**Comment by KnightMiner** [comment]
Most likely fixed by the commit, as this issue never existed in 1.16 and that is the main bug I noticed in the update. Not 100% certain though without doing more testing.

**Comment by KnightMiner** [comment]
Fixed in 3.4.1.45.
