### ISSUE TITLE
Geodes spawning in non-overworld dimensions

### ISSUE THREAD

**Issue by leafreynolds** [SlimeKnights/TinkersConstruct#4746]
### Minecraft Version

1.18.1

### Forge Version

39.0.66

### Mantle Version

1.18.1-1.8.31

### Tinkers' Construct Version

1.18.1-3.4.0.34

### Describe your issue

Geodes are spawning in other mod dimension. I assume this is a bug, since there's no config option to turn it off and other config options imply control over all world generation.

![javaw_zcwcr6ptge](https://user-images.githubusercontent.com/80794784/153075643-d66a692c-f825-43fd-90b3-4f5ef6130a2b.png)

### Reproduced with only Tinkers' Construct?

Yes

### Other mods required

SoulHome-Mod-1.18.1-39.0.66-b1

### Confirm the following

- [X] Check if you are not using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you have look at FAQ to see if your issue is answered
- [ ] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by KnightMiner** [comment]
Geode spawning is biome based, not dimension based, so any dimension with the biome gets the geodes. They shouldn't be spawning in mid air, but this is mostly a bug with said mod as you don't include overworld biomes without wanting overworld features 

Worth asking, what dimension is that in the screenshot? Given it looks like a void world, they should probably be using the void biome, or otherwise disable all worldgen. I suspect the only reason they do not get vanilla ores or geodes is there is no valid place for them to spawn, skyslime geodes are a bit more lenient

**Comment by leafreynolds** [comment]
Pardon, but it's not an overworld biome, but a custom biome related to the mod. I may be misreading the tinkers world gen source code, but this line seems to only check if the biome category is nether or end, if it is neither then it dumps geodes everywhere else?https://github.com/SlimeKnights/TinkersConstruct/blob/37b15045039e8a3ccbc7a2f9391b219817270b3f/src/main/java/slimeknights/tconstruct/world/WorldEvents.java#L77


The dimension itself is essentially a skyblock, with it's own custom biome to try avoid being part of anything Vanilla related. I'll try double check that though
![image](https://user-images.githubusercontent.com/80794784/153100165-27095a31-c18c-438c-8054-014b90298f1f.png)

**Comment by Falkory220** [comment]
also appearing in the bumblezone mod 
![image](https://user-images.githubusercontent.com/63330954/153100686-0b96b03e-ef2f-491f-950f-8622e955e4ad.png)

**Comment by KnightMiner** [comment]
Sounds like my detection for overworld biomes has a bug. Still weird your void world is generating anything at all, but the geodes appear in non-void dimensions as well.

**Comment by KnightMiner** [comment]
Fixed in 3.4.1.45. Note old worlds will obviously be unaffected, so if you want to test again try generating a new world.
