### ISSUE TITLE
Scrolling does not work on tool stat display window 

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#4747]
### Minecraft Version

1.18.1

### Forge Version

39.0.75

### Mantle Version

Mantle-1.18.1-1.8.31.jar

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.0.34.jar

### Describe your issue

When you add a material to the part table or add a tool into the upgrade station, you can't scroll up or down on the right stat window. 
In 1.16, you can scroll and you even have a scroll bar for you to slide. But those are missing in 1.18

Here is 1.16 (As you can see, there is a scroll bar on the window)
![image](https://user-images.githubusercontent.com/44974827/153118849-ade57385-4d12-433e-b9c2-dc0ab3c4d236.png)

Here is 1.18 (There is no scroll bar)
![image](https://user-images.githubusercontent.com/44974827/153118884-97f06a9a-34f7-4799-8734-e19126d15bf2.png)

### Reproduced with only Tinkers' Construct?

Yes

### Other mods required

NO

### Confirm the following

- [X] Check if you are not using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you have look at FAQ to see if your issue is answered
- [ ] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by KnightMiner** [comment]
Confirmed that the slider is still there, its just invisible. That said, its super awkward to interact with when invisible so hard to notice. Scroll wheel works though. Will be fixed in next build.

**Comment by KnightMiner** [comment]
Fixed in 3.4.1.45

**Comment by ffuentesm** [comment]
Now is the Part Builder that has the invisible Scrolling bar in the TConstruct-1.18.1-3.4.2.60.jar
Also, the area of scrolling is only at the bottom of the Menu
![image](https://user-images.githubusercontent.com/44974827/161408588-402dc0e7-0ada-45a5-bc1f-9513e460c320.png)
The Highlighted area is the only area you can scroll 
![image](https://user-images.githubusercontent.com/44974827/161408619-3af366cd-9622-4112-aa3e-938cd7e26c82.png)

**Comment by KnightMiner** [comment]
Fixed in [3.5.0.18](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.0.18) for 1.18.2. No plans to backport to 1.18.1
