### ISSUE TITLE
CTD when interacting with Tinker's Station next to School of Magic Podium

### ISSUE THREAD

**Issue by ofseaandstars** [SlimeKnights/TinkersConstruct#4748]
### Minecraft Version

1.18.1

### Forge Version

39.0.75

### Mantle Version

Mantle-1.18.1-1.8.31

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.0.34

### Describe your issue

If you have a podium from School of Magic: Second Semester with a Basic Arcana book on it, and interact with the Tinker's Crafting Station, the game will crash.

Steps to reproduce:

- Place any podium and place a Basic Arcana on it.
- Place a Crafting Station next to the podium.
- Right-click the Crafting Station.
- Crash.

### Crash Report

https://pastebin.com/022ZZyQF

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Schools of Magic: Second Semester (SoMSecondSemester1.18.1-3.0.09) https://www.curseforge.com/minecraft/mc-mods/schools-of-magic-second-semester

### Confirm the following

- [X] Check if you are not using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you have look at FAQ to see if your issue is answered
- [ ] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by KnightMiner** [comment]
This is a bug with Schools of Magic, not tinkers. If they do not have a display name, they should not be implementing `MenuProvider`. Worst case, they could at least not return null from a method marked as nonnull, tell them to return `StringTextComponent.EMPTY` instead.

Report this bug to them and link the issue report here.

**Comment by ofseaandstars** [comment]
Hi Knight - thanks for that, I'll pass this on to them :)

**Comment by KnightMiner** [comment]
3.7.0.152 for 1.18.2 has a workaround for the issue of "Schools of Magic" doing stupid stuff. Should prevent the crash from our side, but its only a matter of time before it crashes someone else.
