### ISSUE TITLE
Fluid pouring from faucets does not render properly

### ISSUE THREAD

**Issue by EvergreenSystems** [SlimeKnights/TinkersConstruct#4749]
### Minecraft Version

1.18.1

### Forge Version

39.0.59

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.0.34

### Describe your issue

When molten fluids are poured from a faucet into a channel, the fluid will not render when falling but _will_ render inside the channel. Fluid in image is molten copper, but this occurs with other fluids as well. Occurs on fast and fancy graphic settings, fabulous graphics has its own issues
![2022-02-10_14 35 00](https://user-images.githubusercontent.com/23658767/153492598-8778442d-ddc5-4cc3-a5d0-9b8fe5e8f994.png)

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Check if you are not using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you have look at FAQ to see if your issue is answered
- [ ] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by KnightMiner** [comment]
That screenshot is not with just Tinkers Construct. Please provide a screenshot with a minimal mod list

**Comment by EvergreenSystems** [comment]
Apologies, forgot to get a screenshot in my testing directory. The fluid appears to render for long enough to fill the channel directly under it, but when the fluid starts moving into other channels it stops rendering the "pour" but continues to render the movement into the other channels. Tested in these shots with molten copper, cobalt and electrum
![2022-02-10_14 47 53](https://user-images.githubusercontent.com/23658767/153494163-6e51d418-3352-4b74-b2be-e8c4bbfdf3db.png)
![2022-02-10_14 48 35](https://user-images.githubusercontent.com/23658767/153494164-e2b00ecc-7df1-464b-95be-f8818ba983ee.png)
![2022-02-10_14 48 44](https://user-images.githubusercontent.com/23658767/153494168-3fb3bfd6-612f-484e-b301-d0b645815fbb.png)

**Comment by KnightMiner** [comment]
Most likely fixed by the commit, as this issue never existed in 1.16 and that is the main bug I noticed in the update. Not 100% certain though without doing more testing.

**Comment by EvergreenSystems** [comment]
Fantastic, once the fixed build is available I will retest the issue. Thanks!

**Comment by KnightMiner** [comment]
Fixed in 3.4.1.45
