### ISSUE TITLE
JEI displays melting, foundry, and casting recipes incorrectly

### ISSUE THREAD

**Issue by NyanMC** [SlimeKnights/TinkersConstruct#4750]
### Minecraft Version

1.18.1

### Forge Version

39.0.76

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.0.34

### Describe your issue

JEI appears to have odd bugginess when it comes to displaying melting, foundry, and casting recipes.

For melting recipes, liquid fuel and the output are missing from the recipe. (this is supposed to show the raw iron recipe)
![image](https://user-images.githubusercontent.com/44331238/153728572-88a0b140-c325-4cc6-99fd-1c04ef039b72.png)

For foundry recipes, the same bug is present except the main output is properly showing while the secondary output is not (this is supposed to show the raw iron recipe)
![image](https://user-images.githubusercontent.com/44331238/153728662-e16a2a65-e0cd-4e1a-9476-dda81c6b9929.png)

Lastly, casting recipes are the weirdest when it comes to this bug. All recipes show that pouring air on top of a specific fluid at a specific amount of mb will give you the exact same fluid at the exact same mb. (this applies to the casting basin as well)
![image](https://user-images.githubusercontent.com/44331238/153728775-a017cde2-d872-4695-9a14-5db85e27e449.png)

Alloying recipes seem to display properly. All of these bugs seem to apply to all recipes of the respective categories, not just the examples I showed here.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

JEI is required to reproduce this issue. Tested using version 9.3.2.92.

### Confirm the following

- [X] Check if you are not using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you have look at FAQ to see if your issue is answered
- [ ] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by NyanMC** [comment]
update: the solution is literally just to downgrade jei to the last non-beta release or anywhere near that point by a version or two, probably jei's fault and not tinkers but i will reopen the issue if the bug persists even with future jei versions

**Comment by KnightMiner** [comment]
That does not mean this issue should be closed. Leave the issue open until its fixed

The actual problem is JEI changed some APIs, and it seems their backwords compat is not fully working. Its possible TiC was misusing the old APIs, not sure, but I am updating to the new ones anyways.

For the record, this is mezz/JustEnoughItems#2720

**Comment by KnightMiner** [comment]
1e9fd16 solves this. Not sure when it will be released though, as it solves it by adding a hard dependency on the latest JEI, and not sure I want to force other mods to update to use the latest TiC build.

**Comment by mezz** [comment]
I'll try to fix up the legacy support, I wouldn't set a hard-dep on the new version until legacy support is working properly or else it would just force everyone to update.

**Comment by mezz** [comment]
This issue is fixed in JEI version 9.3.2.94

**Comment by KnightMiner** [comment]
Closing as fixed in JEI, if someone is still experiencing this on 9.3.2.94 or later leave a comment and we can look into this again
