### ISSUE TITLE
Travellers Armour "Golden" Trait not functioning when Mana and Artifice is Installed

### ISSUE THREAD

**Issue by Benjamboo** [SlimeKnights/TinkersConstruct#4756]
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

Title,  Travellers Armour with Golden trait does not render the Piglins Passive when Mana and Artifice is active.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Mana And Artifice

### Confirm the following

- [x] Check if you are using performance enhancers, such as optifine
- [x] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [x] Check if you read FAQ to see if your issue is answered

**Comment by Benjamboo** [comment]
Ticket in the M&A Github.
https://github.com/Mithion/Mana-And-Artifice/issues/441

**Comment by KnightMiner** [comment]
Mana and Artifice say they fixed this in their version 1.7.2.3, so closing.
