### ISSUE TITLE
Issues with loading mantle

### ISSUE THREAD

**Issue by foxesinthewood** [SlimeKnights/TinkersConstruct#4758]
### Minecraft Version

1.16.5

### Forge Version

Java

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

Whenever I open minecraft, it give me a mod loading errror screen. I don't know how to check the tracker for this stuff, sorry...
![Screenshot 2022-02-15 195306](https://user-images.githubusercontent.com/99779365/154193082-29269dbd-3598-435a-878f-a29d74c60c6a.png)
.

### Crash Report

 -- System Details -- Details: 	Minecraft Version: 1.16.5 	Minecraft Version ID: 1.16.5 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 1.8.0_51, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 1181958856 bytes (1127 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB) 	CPUs: 16 	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	ModLauncher: 8.0.9+86+master.3cf110c 	ModLauncher launch target: fmlclient 	ModLauncher naming: srg 	ModLauncher services:  		/mixin-0.8.4.jar mixin PLUGINSERVICE  		/eventbus-4.0.0.jar eventbus PLUGINSERVICE  		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE  		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE  		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE  		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE  		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE  		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE  		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE  		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE  	FML: 36.2 	Forge: net.minecraftforge:36.2.20 	FML Language Providers:  		javafml@36.2 		minecraft@1 	Mod List:  		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE 		TConstruct-1.16.5-3.1.3.271.jar                   |Tinkers' Construct            |tconstruct                    |3.1.3.271           |SIDED_SETU|Manifest: NOSIGNATURE 		FarmersDelight-1.16.5-0.5.4.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.5.4        |SIDED_SETU|Manifest: NOSIGNATURE 		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5 		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90 		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |SIDED_SETU|Manifest: NOSIGNATURE 		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |ERROR     |Manifest: NOSIGNATURE 		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |SIDED_SETU|Manifest: NOSIGNATURE 		JRFTL+[1.16.5]-1.2.jar                            |JRFTL                         |jrftl                         |1.2                 |SIDED_SETU|Manifest: NOSIGNATURE 		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |SIDED_SETU|Manifest: NOSIGNATURE 		WAWLA-1.16.5-8.0.1.jar                            |WAWLA                         |wawla                         |8.0.1               |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5 		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |SIDED_SETU|Manifest: NOSIGNATURE 		jei-1.16.5-7.7.1.145.jar                          |Just Enough Items             |jei                           |7.7.1.145           |SIDED_SETU|Manifest: NOSIGNATURE 	Crash Report UUID: 53b1f820-9969-4c65-8448-e24abd56da25 	OptiFine Version: OptiFine_1.16.5_HD_U_G8 	OptiFine Build: 20210515-161946 	Render Distance Chunks: 8 	Mipmaps: 4 	Anisotropic Filtering: 1 	Antialiasing: 0 	Multitexture: false 	Shaders: BSL_v8.1.02.1.zip 	OpenGlVersion: 4.6.0 NVIDIA 496.49 	OpenGlRenderer: NVIDIA GeForce RTX 2060 with Max-Q Design/PCIe/SSE2 	OpenGlVendor: NVIDIA Corporation 	CpuCount: 16

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Bookshelf-1.16.5-10.0.1, create-mc1.16.5_v0.3.2g, FarmersDelight-1.16.5-0.5.4, flywheel-1.16-0.2.5, Hwyla-forge-1.10.11-B78_1.16.2, jei-1.16.5-7.7.1.145, JRFTL+[1.16.5]-1.2, Mantle-1.16.5-1.6.157, OptiFine_1.16.5_HD_U_G8, TConstruct-1.16.5-3.1.3.271, WailaHarvestability-mc1.16.x-forge-1.1.15, WAWLA-1.16.5-8.0.1

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [ ] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [ ] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Update Tinkers' Construct. There is no reason to be playing on such old versions. I told you in your other issue to be on the **latest** version before reporting issues. The latest is 3.3.3.332

**Comment by foxesinthewood** [comment]
didn't see that, i just updated to the latest version that it displayed

**Comment by KnightMiner** [comment]
Latest version what displayed? Curseforge clearly shows 3.3.3 as the latest beta, and 3.3.2 as the latest alpha.
![image](https://user-images.githubusercontent.com/12155288/154196268-dace1334-ab05-48a1-95d0-d432b41ca72c.png)

If you are getting your mods anywhere besides curseforge, github, or an official site, you are at risk of downloading malware. Tinkers Construct has no official sites besides github and curseforge.

**Comment by foxesinthewood** [comment]
I might have mis-clicked or something sorry.
