### ISSUE TITLE
There's no information in the manual on how to fill items with the slurping modifier

### ISSUE THREAD

**Issue by roosemberth** [SlimeKnights/TinkersConstruct#4762]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.0.308

### Describe your issue

The manual is very clear on what this effect does, but it is not clear to a new player how to fill the helmet.

I personally had to come and look at the code to understand this. I think it should be part of the in-game documentation.

Previous attempt at solving this: https://github.com/SlimeKnights/TinkersConstruct/pull/4761 but there are more interactions with slurping than I know of.

### Reproduced with only Tinkers' Construct?

No

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Improved descriptions of several modifiers in 3.5.1.31, though a lot of them already had information. Do not currently plan to backport the changes to 1.16
