### ISSUE TITLE
Toolbelt will not go to level 2

### ISSUE THREAD

**Issue by Wattaton** [SlimeKnights/TinkersConstruct#4764]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

N/A

### Tinkers' Construct Version

3.3.2.324

### Describe your issue

As the title says, I was able to add one level of the Toolbelt ability

1. made traveler's leggings Traveler's leggings
2. added 1 level of toolbelt
3. added the pocket chain upgrade
4. attempt to add a second level of toolbelt

Expected behavior
I expected to be able to get a second level of the toolbelt, as the book describes

Screenshots
![image](https://user-images.githubusercontent.com/47191442/154612571-e42e5221-60bd-4e69-8f33-d34eeef63b03.png)
![image](https://user-images.githubusercontent.com/47191442/154612596-41ad4985-d67b-489f-9adf-72a6dc58dd71.png)

Version Information (please complete the following information):

Mod Version: 3.3.2.24
Forge Version: 36.2.20

### Reproduced with only Tinkers' Construct?

No

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by Faeranne** [comment]
Just to help a bit, the mantle version is 1.6.152.  I'm running the mod pack it's used in, and was able to check that for @Wattaton.

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.60 for 1.18.1

**Comment by KnightMiner** [comment]
Fixed in 3.3.4.335 for 1.16.5
