### ISSUE TITLE
Mobs are positioned wrong in "Entity Melting" tab of JEI

### ISSUE THREAD

**Issue by enigmaquip** [SlimeKnights/TinkersConstruct#4767]
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

![image](https://user-images.githubusercontent.com/6134440/154734389-d097ab42-194a-489a-b5f8-a509b7616707.png)
Mob images show on the upper left corner of minecraft, not within the smeltery of the entity melting tab

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Not reproduced with only Tinkers' since it does require JEI for the "bug". Reproduced with only JEI, Mantle, and Tinkers though.

jei-1.18.1-9.4.1.100

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Same as #4750, JEI bug as they changed their API. I have a fix for this that was pending for JEI to make their API more stable, I suppose its a better time to do that now.

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.60
