### ISSUE TITLE
Plate armor made with cobalt won’t repair

### ISSUE THREAD

**Issue by PandaBearLoki** [SlimeKnights/TinkersConstruct#4768]
### Minecraft Version

1.16.5

### Forge Version

0.192.1.5

### Mantle Version

Unknown

### Tinkers' Construct Version

3.3.332

### Describe your issue

I made a set of Plate Armor using cobalt instead of manyullyn, but I can’t repair it. Do I have to use manyullyn to repair it even though it’s made of cobalt?

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Ah, this one took awhile to actually make it to github. You need to repair it with manyullyn as that recipe did not get updated when the recipe changed. It will be fixed in the next 1.16 build to properly be cobalt

**Comment by PandaBearLoki** [comment]
> 

Omg thank you so much! I’ve been searching for answers for days!

**Comment by KnightMiner** [comment]
Leave it open until the fix is released.

**Comment by aethaerya** [comment]
Here's a datapack fix that you can use in the mean time.

https://github.com/aethaerya/TiC3-Plate-Armor-Repair-Fix/releases/tag/Release

**Comment by Grinnling** [comment]
how does one use this to fix the recipe?

**Comment by aethaerya** [comment]
Download the ZIP file (tic3-plate-armor-fix.zip) and add it to your world's datapack folder.

**Comment by Grinnling** [comment]
oh derp ok thank you sorry im just overseeing a server mod pack and we were running into this issue as well thank you.

**Comment by Grinnling** [comment]
so in the resource pack section correct cause i did that and loaded the pack and it didnt work properly

**Comment by KnightMiner** [comment]
No, its not a resource pack, its a datapack. See [the Minecraft Wiki article](https://minecraft.fandom.com/wiki/Data_pack#Usage)

**Comment by Grinnling** [comment]
oooooooh mega derp sorry thank you.

**Comment by KnightMiner** [comment]
Fixed in 3.3.4.335
