### ISSUE TITLE
Pickadze does not respect the block on top of the clicked block when pathing

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4770]
### Minecraft Version

1.18.1

### Forge Version

39.07.9

### Mantle Version

Mantle-1.18.1-1.8.31

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.1.46

### Describe your issue

When you right click a block with a shovel in vanilla it will only path it if there is an air block on top of it, so stuff like flowers and saplings will stop it from pathing. The pickadze seems to only check if its a solid block/block with a hitbox, meaning that it will cause any flowers or similar to pop off the block if pathed.

https://user-images.githubusercontent.com/73862885/154778134-edaf2443-1532-4241-924f-a72403ff61d1.mp4

Path maker on boots also has this issue, however I do not think that needs fixing.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Intentional, the vanilla behavior sucks. Hoes would do the same thing if vanilla did not force me to require air above for compat.

Go try making paths with an excavator and tell me you prefer it not breaking plants after that
