### ISSUE TITLE
Scorched tables disallow pouring of certain fluids

### ISSUE THREAD

**Issue by EvergreenSystems** [SlimeKnights/TinkersConstruct#4772]
### Minecraft Version

1.18.1

### Forge Version

39.0.59

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.0.43

### Describe your issue

Scorched casting tables disallow the pouring of certain fluids when the table is empty. This includes obsidian and glass: a scorched channel can pour obsidian into a seared table, but not a scorched one, etc etc. Any fluid that would normally pour into an empty seared table does _not_ work with a scorched one.

On a related note: the only platform that I have found to work in scorched basins is the gold platform; the other types of platform are ineffectual.
![2022-02-18_19 11 00](https://user-images.githubusercontent.com/23658767/154780125-0e1c460b-b0ad-48ac-a379-13a2880ee824.png)
![2022-02-18_19 11 46](https://user-images.githubusercontent.com/23658767/154780142-d53cc9c2-ca85-4420-ae7a-35e076f4f9e3.png)
![2022-02-18_19 14 49](https://user-images.githubusercontent.com/23658767/154780143-b15e24e9-37d3-4952-b4b1-d603120b1b17.png)

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Intentional, read Fantastic Foundry or the changelog.

You need to use gold bars/gold platform as a blank cast. And yes, other platform types don't work, that is because they are not gold platforms, casts are gold. Just like iron bars don't work in the table
