### ISSUE TITLE
Tinkers Bronze embellishment does not show up on the item properly

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4775]
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

Mantle-1.18.1-1.8.31

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.1.46

### Describe your issue

As you can see it shows up fine when worn, but not in item form.
![image](https://user-images.githubusercontent.com/73862885/154895006-a9391339-0184-48cd-8cff-37332877c66e.png)

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Yep, I can see why. Tinkers Bronze internally is `tconstruct:bronze#silicon`, but the material modifier model was not yet updated to [use material variants](https://github.com/SlimeKnights/TinkersConstruct/blob/1.18/src/main/java/slimeknights/tconstruct/library/client/modifiers/BreakableMaterialModifierModel.java#L72), so it thinks that is an invalid material ID (non variant material IDs don't support `#`). Easy enough fix, just something missed in the material variant update.

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.60. Not that anyone will notice, as Tinkers Bronze was removed.
