### ISSUE TITLE
Modded Raw Ores do not melt in Melter [Tag issue]

### ISSUE THREAD

**Issue by FryoKnight** [SlimeKnights/TinkersConstruct#4776]
### Minecraft Version

1.18.1

### Forge Version

39.0.76

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

Mods that just add the `forge:raw_ores/[Ore]` tag but not the `forge:raw_materials/[Ore]` tag can not be melted in the Smeltery/Foundry/Melter.

I found this issue with Immersive Engineering's Raw Bauxite (Aluminum) and Raw Lead. They have the `forge:raw_ores` tags, but not the `forge:raw_materials`. The actual Ore blocks and smelted ingots work, just not the Raw ores.

I will also be cross-posting this on their issue tracker as well.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Immersive Engineering - version 7.1.0-145

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by luckyu19** [comment]
Seems like they have already resolved the issue, but they are waiting to push a release.
[[1.18.1] IE raw ores are missing #forge:raw_materials tags](https://github.com/BluSunrize/ImmersiveEngineering/issues/5221)

**Comment by KnightMiner** [comment]
`forge:raw_materials/` is the name used by forge for whatever reason. I am using names consistent with forge, and other mods should use consistent names as well. Report this issue to the relevant mods.

Also, don't use Optifine.
