### ISSUE TITLE
Raw cobalt missing #forge:raw_materials tag

### ISSUE THREAD

**Issue by TJT01** [SlimeKnights/TinkersConstruct#4780]
### Minecraft Version

1.18.1

### Forge Version

39.0.66

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

![2022-02-22_18 40 40](https://user-images.githubusercontent.com/87955906/155238614-9fc1f8c0-4263-4c3e-8c2d-23aca0bad655.png)
![2022-02-22_18 40 42](https://user-images.githubusercontent.com/87955906/155238626-5ae8d79a-2fd5-419e-9525-dcc5eb0b0ab7.png)
Raw Cobalt is missing the `#forge:raw_materials` tag.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.60
