### ISSUE TITLE
Invariant trait has inaccurate description

### ISSUE THREAD

**Issue by nphhpn** [SlimeKnights/TinkersConstruct#4786]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.0.308

### Describe your issue

The invariant trait's description says it increases damage in neutral temperature, however it actually increases damage in hot/cold temperature instead.

This is because in the code, the bonus damage scales with absolute of difference between temperature and baseline temperature.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Didn't test with tinkers only so I chose no, but should be reproduceable with Tinkers' Construct only

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
The description is correct, its the behavior that is incorrect if its not dealing more damage in neutral biomes.

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.60 for 1.18.1

**Comment by KnightMiner** [comment]
Fixed in 3.3.4.335 for 1.16.5
