### ISSUE TITLE
Some blocks for the smeltery/foundry are missing "mineable" tags

### ISSUE THREAD

**Issue by atealein** [SlimeKnights/TinkersConstruct#4787]
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

Noticed that few of the blocks that can be used as building blocks of the Smeltery and Foundry are non-mineable - meaning it takes forever to mine them and when you do they don't drop the block. Verified examples: seared_triangle_bricks, scorched_chute. The last one, sadly, is more complicated to make and since it fixes your input/output it might take few changes in position when you are re-designing your item flows. Not being mineable is I think a bug/mistake, since all other chute/drains for the smeltery and foundry are mineable.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Yeah, I see I tagged scorched duct twice instead of tagging chute. Note you can fix this with a datapack until it get properly fixed.

**Comment by KnightMiner** [comment]
Do not close issues that are fixed but not released. It is closed when it either is no longer an issue in the latest support version, or if its unfixable.

**Comment by atealein** [comment]
I am sorry, I wasn't sure if I was supposed to do this or it was going to be done by you or another dev.

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.60
