### ISSUE TITLE
Stencil Table Is Completely Missing!!

### ISSUE THREAD

**Issue by TrippyBakel** [SlimeKnights/TinkersConstruct#4790]
### Minecraft Version

1.18.1

### Forge Version

39.0.88

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

I started up my world and finally was getting ready to start my smelting adventure and I noticed that I was missing something. So I watched a YouTube video and found it was the stencil table. I switched to creative and see if I could find it there but was unable. I even checked the tinkers construct book to see if something was just different because its a newer version and it doesn't even mention the stencil table in any of my tinkers books.

### Other mods

ato, balm, bop, configured, cooking4blockheads,cucmber,fastfurncae, mrcrayfish furinture, gravestone, jei, mantle, mcm bridges, modnametooltip, mystical agriculture, neat,placebo, simplylight, sophiscated backpacks, tcontrsuct, terrablender, waystones

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues, Used the search bar, Checked the FAQ

**Comment by Random832** [comment]
Watch a newer video, the stencil table no longer exists since 1.16. You can make parts using blank templates in the part builder.

**Comment by TheOnlyMann** [comment]
![image](https://user-images.githubusercontent.com/82017462/156713503-9f559a23-7c51-48e2-a80c-b9322973d1d2.png)

**Comment by KnightMiner** [comment]
@TheOnlyMann is correct, this is covered by FAQ. If you did not check FAQ, don't claim that you checked FAQ, that's just dishonest. Its perfectly acceptable for you to say you did not search, your issue is not answered faster by claiming you searched places you did not.

**Comment by TrippyBakel** [comment]
Yeah I was finally able to find a newer video and wasn’t sure how to get
rid of the post on GitHub. Thank you for your time tho
