### ISSUE TITLE
Slime suit crash with Wildfire gender mod

### ISSUE THREAD

**Issue by EvergreenSystems** [SlimeKnights/TinkersConstruct#4791]
### Minecraft Version

1.18.1

### Forge Version

39.0.88

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

The game crashes when a slime helmet is worn when Wildfire Female Gender mod is loaded. The crash only occurs when rendering the helmet, ie when the player is in third person.

Latest log: https://gist.github.com/Shedao-Shai/f7772d4415e4aa816070f6c02eee787d

Debug log: https://gist.github.com/Shedao-Shai/f8584ec4d4a520992e6b68367c39246e

I am also going to report this to Wildfire's issue tracker

### Crash Report

https://gist.github.com/Shedao-Shai/4871f23334aac1347fe225ac41b931a8

### Other mods

Mantle
Tinkers Construct
Wildfire Female Gender mod 2.8.1

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by TheOnlyMann** [comment]
>Wildfire Gender Mod

I assume this is the same thing that I know about the only "good" female gender mod there is
😩

**Comment by KnightMiner** [comment]
Report this to Wildfire Gender Mod as well and link it here, they likely will better know why this crash happens than I

Also, does this happen with other armor pieces? And non-slimesuit helmets?

**Comment by EvergreenSystems** [comment]
I have not observed it with other pieces of the slimesuit, I will test with other helmets. I have reported it to wildfire as well (curseforge issue tracker ;-;)

**Comment by EvergreenSystems** [comment]
Alright I have determined that this issue is not specific to tinkers construct, it crashes with any modded chestplate or armor piece that has a custom model.

**Comment by KnightMiner** [comment]
Can you link the issue here?

**Comment by EvergreenSystems** [comment]
https://www.curseforge.com/minecraft/mc-mods/female-gender-forge/issues/13

**Comment by KnightMiner** [comment]
Based on that info, I'll assume this is not a tinkers bug. Can you give an example of another mod that has a custom model for the sake of testing?

**Comment by EvergreenSystems** [comment]
I have also reproduced the crash with the supremium chest plate from Mystical Agriculture

**Comment by KnightMiner** [comment]
Looks like Windfire Gender moved to a Github issue tracker instead of curseforge, but did not migrate any of their issues. Will someone experiencing this issue please report it to their new github issue tracker and crosslink the issue?

**Comment by EvergreenSystems** [comment]
eugh yeah I will transfer the issue

**Comment by EvergreenSystems** [comment]
https://github.com/WildfireRomeo/WildfireFemaleGenderMod/issues/14

**Comment by KnightMiner** [comment]
Going to close this as its closed as fixed on the other tracker. If its not fixed, please comment there to say the fix did not work.
