### ISSUE TITLE
[1.18] Luck modifiers are not affecting the geode shards

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#4794]
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

Mantle-1.18.1-1.8.31.jar

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.1.46.jar

### Describe your issue

Luck modifiers are not affecting the geode shards.
I have luck on Pickaxe, Hammer, Vain Hammer. They all drop 2 shards, no matter the Geode type. 

Normal Vanilla Fortune 3 Pickaxe works. 

> You should get 2 shards when breaking with the wrong tool, 4 with a pickaxe.
> Fortune I gives a 1⁄3 chance for eight shards; Fortune II gives a 25% chance (each) to give eight or 12 shards, and Fortune III gives a 20% chance (each) to give 8, 12, or 16 shards.
> I am using a Luckier Pickaxe and I only get 2 shards

### Other mods

Basi Tinker's essentials 

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Likely due to a missing tag. Vanilla decided tags are the ideal way to mark a pickaxe for the drops, so I have to add that tag.

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.60
