### ISSUE TITLE
Scorched basin/chute doesn't pour out "normal" molten metals

### ISSUE THREAD

**Issue by atealein** [SlimeKnights/TinkersConstruct#4797]
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

The JEI lists that I should be able to pour out molten copper (and other molten metals) into scorched basin to produce metal blocks, same as seared basin from Smeltery, but using a foundry. However, it does not activate for me, I have tried different configurations, different liquids. Supplying screens of the setup and recipes below, I am not sure what is going wrong. I've had similar problem with alloyer, refusing to cast obsidian blocks into scorched basin, so I had to export the molten obsidian and pour it into a seared basin. 

![Screenshot 2022-03-13 at 19 50 58](https://user-images.githubusercontent.com/25322782/158074656-b934b124-df99-4cc2-ba8d-794f10e107f8.png)
![Screenshot 2022-03-13 at 19 49 20](https://user-images.githubusercontent.com/25322782/158074663-ef6ef993-9851-4f61-9367-980d93a6ec34.png)

### Other mods

Refined storage (used to syphon fluids in/out, didn't have issues connected with that)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
You need to put a gold platform in basins for blocks and gold bars for plates. This is listed in fantastic foundry.

**Comment by atealein** [comment]
I apologise! I wish there was a way to list this in the JEI recipe. I will close the issue.

**Comment by KnightMiner** [comment]
Showing it in JEI would be a bit awkward as its really a function of the basin, not the recipe. I'll consider further.

Key detail to remember here is the scorched stuff is not simply a retexture of the seared stuff.
