### ISSUE TITLE
[1.18] Bonus chest tool having no modifier 

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#4798]
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

 Mantle-1.18.1-1.8.37.jar

### Tinkers' Construct Version

 TConstruct-1.18.1-3.4.2.60.jar

### Describe your issue

Got this axe in the bonus chest, the only thing I did to it was to change the head to silver.
IT has no upgrade or ability modifier.
The chest also came with a vanilla wood pick
![image](https://user-images.githubusercontent.com/44974827/158446322-c8ba4965-069e-4f15-b2a7-07defa3ab448.png)

### Other mods

base tinkers requirements mods

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed by 935278f

**Comment by KnightMiner** [comment]
Fixed in [3.5.0.18](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.0.18) for 1.18.2. No plans to backport to 1.18.1
