### ISSUE TITLE
Support 1.18.2

### ISSUE THREAD

**Issue by BingYanchi** [SlimeKnights/TinkersConstruct#4802]
### Minecraft Version

1.18.2

### Forge Version

40.0.12

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Problem description

Support 1.18.2

### Suggested solution

Support 1.18.2

### Alternatives considered

Support 1.18.2

### Searched for existing enhancement?

Used the search bar

**Comment by KnightMiner** [comment]
Yeah, I have completely forgotten about 1.18.2 existing and would have never supported it if it were not for this issue. Super helpful suggestion.

A little patience would go a long way. Got a life outside giving you free updates.
