### ISSUE TITLE
JEI Version Combatibility

### ISSUE THREAD

**Issue by getxd-dev** [SlimeKnights/TinkersConstruct#4803]
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

1.18.1 Tinker's Construct requires JEI 9.4.0 and above but it's only supported for 1.18.2.

### Other mods

Just JEI and Tinkers.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Magnesium, Other (specify under other mods)

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Since this was closed without comment, I'll just say 9.4.0 does exist for 1.18.1

**Comment by BonaireDreams** [comment]
Last release for JEI 1.18.1 is 9.2.1.69. The 9.4.xx stream is Beta only.  If you are using something like Curse Forge you need to go to Curse and manually download The 9.4.xx version you want and then JEI and Tinkers will work fine.
