### ISSUE TITLE
Incorrectly aligned cursor on Mac OS

### ISSUE THREAD

**Issue by SpeedyZ500** [SlimeKnights/TinkersConstruct#4805]
### Minecraft Version

1.18.1

### Forge Version

39.1.0

### Mantle Version

1.8.37

### Tinkers' Construct Version

9.4.1.112

### Describe your issue

I play on my Mac book, and I have noticed that in the tinker's books that it is not in the same place as my cursor, my cursor interacts properly with the left and right arrows, but not the jump to selections, unless I move my cursor far to the right and below the item, it has this same problem when hi-lighting text in the book to see what a trait does

### Other mods

Tinkers, Mantel

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment]
So this is a known issue due to mac's odd resolution. It fixes itself if you use a normal resolution but beyond that not much has been found/done as Knight doesn't own a mac

**Comment by SpeedyZ500** [comment]
You can set the aspect ratio on windows to a Mac aspect ratio, it is less a Mac problem and more a consistency across aspect ratios then, which can be tested without a mac which has a 16:10 aspect ratio and you can set windows and Linux to output a 16:10 aspect ratio

**Comment by KnightMiner** [comment]
Pretty sure this is a duplicate of #4663. Check that issue, if you can confirm it's the same add additional information there.

**Comment by SpeedyZ500** [comment]
It is essentially a duplicate, should I close this and add any information I have to the other issue?

**Comment by SpeedyZ500** [comment]
I’ll just close it because this is a duplicate

**Comment by KnightMiner** [comment]
Yep, just add any new info to the other issue.
