### ISSUE TITLE
Tinker gear and powdered snow freezing protection 

### ISSUE THREAD

**Issue by SpeedyZ500** [SlimeKnights/TinkersConstruct#4807]
### Minecraft Version

1.18.1

### Forge Version

39.1.0

### Mantle Version

1.8.37

### Tinkers' Construct Version

9.4.1.112

### Problem description

Powdered snow, sinking and freezing damage, you use leather to make tinker’s gear, yet it does not grant the snow walker or frost damage protection like leather armor does, and it would just be cool to have a modifier, upgrade, or ability that can allow you to walk on the top of powdered snow, or protect you from freezing damage it could even be tinker’s set exclusive 

### Suggested solution

Maybe have it be a base trait for the tinkers set, and then have a modifier or ability called warm inner lining, made of wool and leather, and make it so that each piece of armor with that modifier equipped give the armor the same effect as wearing a piece or pieces of leather armor
And for walking on powdered snow a modifier called snow walker, made with sticks strings and leather, and have it be like attaching snow shoes to your boots, maybe have it require warm inner lining to add
maybe also add effects to the stray head slime set piece as the skeletons turn into strays in powdered snow, and I don’t believe strays take freezing damage 

### Alternatives considered

Maybe have it be exclusive to the tinker’s set or just have the modifiers as explained above potentially just have it one or the other modifier, and not have it be applied on tinkers armor at craft time as tinker’s armor does have metal in the recipe, or make it exclusive to the stray head, could also ad the snow walker effect to the snow drift ability, as snow golems are also immune to the freezing de-buff

### Additional context

There is no freezing protection, nor snow walker in Tinkers Construct, leather armor in Minecraft does this, and it would make tinker’s armor more viable in exploring the new mountain biomes in Minecraft, leather provides protection from the freezing debuff.

### Searched for existing enhancement?

Used the search bar

**Comment by SpeedyZ500** [comment]
I just thought of another think but I am not sure if it already does this, so flame wake should just remove powdered snow as you walk into it, I haven’t tested if it does, but when you are on fire and go into powdered snow it removes it so I am not changing my suggestion for this as it probably already does this I just haven’t tested it

**Comment by SpeedyZ500** [comment]
For more information on powdered snow visit: https://minecraft.fandom.com/wiki/Powder_Snow

**Comment by KnightMiner** [comment]
MinecraftForge/MinecraftForge#8514

**Comment by KnightMiner** [comment]
For a little more info on my plans, I currently plan to give travelers gear a trait that protects you from powdered snow, similarly to leather armor. No modifier recipe for the trait, gives incentive to stick with travelers even after you unlocked plate and slime suit.

Forge pull request I linked is a hook I am waiting on to add this feature to Tinkers (at least for leather walking on powdered snow)

**Comment by SpeedyZ500** [comment]
That actually had been how I had assumed it would be implemented funnily enough, but then I thought that you might not be doing set exclusive traits for armor for some reason, which is why I tried thinking of what I thought a modifier recipe could look like for a hypothetical modifier. though I am not a mod developer and have no Idea what would be balanced and fun, but you seem to, because you develop an amazing mod, that is fun and as far as I'm concerned balanced, thank you for all your amazing work

**Comment by KnightMiner** [comment]
Half of the slimesuit is set exclusive traits. And the plate armor's exclusive "trait" is the fact it can reach 20 armor and has decent toughness. So yeah, we do exclusive traits. Besides, the way leather armor protecting you from freezing is implemented, we would have a hard time implementing it as a proper modifier, the logic is all tag based.

**Comment by KnightMiner** [comment]
Added in [3.5.0.18](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.0.18) for 1.18.2. No plans to backport to 1.18.1
