### ISSUE TITLE
Tinkers' Construct fails to load correctly

### ISSUE THREAD

**Issue by Ifyksfyrd** [SlimeKnights/TinkersConstruct#4809]
### Minecraft Version

1.18.2

### Forge Version

40.0.19

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

While loading the game I get an error:

Tinkers' Construct (tconstruct) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

![obraz_2022-03-20_214503](https://user-images.githubusercontent.com/82973194/159185279-c0e57bce-ac7a-4e8f-8d5d-4a9ed5837b5b.png)

### Crash Report

https://drive.google.com/file/d/1c5UfIh_uEv6KrNTfxCYTpXkj-vl7snnt/view?usp=sharing

### Other mods

Only TConstruct-1.18.1-3.4.2.60.jar and Mantle-1.18.1-1.8.37.jar

![image](https://user-images.githubusercontent.com/82973194/159185395-6066295c-fec6-4785-a3ca-db48653bd3e3.png)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Tinkers is not for 1.18.2 yet. Wait for it to release
