### ISSUE TITLE
"Pocket Chain" is not actually slotless.

### ISSUE THREAD

**Issue by Aqua-Convallaria** [SlimeKnights/TinkersConstruct#4812]
### Minecraft Version

1.18.1

### Forge Version

40.0.24

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

"Pocket Chain" is not actually slotless.

### Other mods

none

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
What makes you think pocket chain should be slotless?

**Comment by Aqua-Convallaria** [comment]
> What makes you think pocket chain should be slotless?
It's in the Encyclopedia of Tinkering.
Effects:
·Maxium of 1 level
·Slotless
·Requires tool belt or shield strap
![image](https://user-images.githubusercontent.com/102253976/161677066-afeedfab-bd82-49e8-afe2-51aaf589cfa4.png)

**Comment by KnightMiner** [comment]
Alright, so the bug is the encyclopedia of tinkering has a typo. In the future, it helps to start with that information.

**Comment by KnightMiner** [comment]
Fixed in [3.5.0.18](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.0.18) for 1.18.2. No plans to backport to 1.18.1
