### ISSUE TITLE
Unarmed Attack Modifier makes me hit a sheep when I shear it

### ISSUE THREAD

**Issue by jpcrowe** [SlimeKnights/TinkersConstruct#4813]
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Problem description

Steps to Reproduce:

1. Modify Plate Chestplate with Unarmed Attack
2. Hold Shears in main hand
3. Empty offhand
4. Shear Sheep

I would expect to ONLY shear the sheep, but I shear the sheep AND hit the sheep with my offhand.

### Suggested solution

Do not perform an offhand attack when using shears

### Alternatives considered

None

### Additional context

If I hold the shears in my offhand to shear, I don't hit the sheep.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
You are likely seeing normal vanilla behavior where holding right click after using your mainhand uses your offhand. I suspect you will notice the same behavior if you put a dagger in your offhand, or similar if you put food in your offhand. Please test these to verify if that is your issue. I doubt this is anything that can be fixed, its simply how the offhand works.

You can install [Sticky Hands](https://www.curseforge.com/minecraft/mc-mods/sticky-hands), a mod that prevents automatically using the offhand after the main hand when holding right click too long. Note its not extensively tested with Tinkers.

**Comment by KnightMiner** [comment]
Did some testing and confirmed this to be a forge bug. When shearing sheep, forge returns that nothing happened client side, meaning the offhand runs client side. Can confirm the interaction with a name tag.

**Comment by KnightMiner** [comment]
MinecraftForge/MinecraftForge#8597

**Comment by KnightMiner** [comment]
Forge PR is merged and Tinkers is released for 1.18.2, so closing as fixed.

For 1.18.1 and earlier, no fix is coming unless someone wants to backport the forge PR.
