### ISSUE TITLE
Round plate is miscolored

### ISSUE THREAD

**Issue by SilverMedal02** [SlimeKnights/TinkersConstruct#4814]
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.18.1-1.8.37

### Tinkers' Construct Version

1.18.1-3.2.4.60

### Describe your issue

![unknown](https://user-images.githubusercontent.com/102337998/160042026-5aae0317-c270-4e0b-844b-fefe593060f4.png)
The round plate has a darker shade, I'm pretty sure its pitch black.

### Other mods

Create 1.18.1 0.4f (with dependencies)
TiC 3.4.2.60 (with dependencies)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Fixed in [3.5.0.18](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.0.18) for 1.18.2. No plans to backport to 1.18.1
