### ISSUE TITLE
Tool forge not appearing at all

### ISSUE THREAD

**Issue by luizguipro** [SlimeKnights/TinkersConstruct#4817]
### Minecraft Version

1.16.5

### Forge Version

36.2.29

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

Tool forge not appearing in creative menu, JEI menu, and i cant craft them at all.

### Other mods

Scootys+Pvz 0.8.1
JEI 1.16.5-7.7.1.152
ironchest 1.16.5-11.2.21
ironfurnaces 1.16.5-2.7.7

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
The tool forge was removed. Replaced with the tinkers anvil 

I suggest reading the new books and familiarizing yourself with the new tinkers
