### ISSUE TITLE
Allow the spread of Slime grass to be the same as nylium

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#4818]
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

 Mantle-1.18.1-1.8.37.jar

### Tinkers' Construct Version

 TConstruct-1.18.1-3.4.2.60.jar

### Problem description

Just a way to speed the spread the slime grass to other dirt blocks in a vanilla way

### Suggested solution

Make the slime grass spread to be the same as nylium, that when using bonemeal the slime grass spread faster. 

### Alternatives considered

Another way is to have Slime seeds drop when breaking slime tall grass

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Why make slime grass inconsistent? Nylium in vanilla spreads with bonemeal and not on random tick. Grass in vanilla spreads on random tick and not with bonemeal

**Comment by ffuentesm** [comment]
Well that is why I also suggested the slime seed drop from breaking the tall grass.

**Comment by KnightMiner** [comment]
I think you missed the point of my question. Why do you need slimegrass to be easier to spread, thus being inconsistent with vanilla? I honestly have no problems filling a large area with slimy grass with a bit of patience, and you could also construct a farm to constantly produce slimy grass so you have large quantiles when needed with no need to wait for spread. Why remove all challenge when its not that hard of a problem to solve?

**Comment by KnightMiner** [comment]
Closing for lack of response. As I said, current behavior is consistent with grass, and I have not had issues with slime grass being too rare (especially with how little it does)
