### ISSUE TITLE
Immersive engineering Raw Ores dont works whit smeltery

### ISSUE THREAD

**Issue by IvorAmlug** [SlimeKnights/TinkersConstruct#4820]
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

Well so ive installed tinkers  as well as Immersive enginerring and realised that u cant smelt the raw ores for ex silver in a smeltery
u can smellt the Ingots, the ingot blocks, the sheetmetal and the ore blocks themselfs but not the raw silver or rawsilver block.
Also stuff like alloying Electrum whit gold and silver or Using it to make silver items works.

So i hope this is something that can be fixed at your side, since it semes like that isnt intentional

### Other mods

ImmersiveEngineering-1.18.1-7.1.0-145

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues

**Comment by KnightMiner** [comment]
Bug on immersive engineering's side, they were using a different tag convention for raw ores. Pretty sure this is fixed already, if not fixed in the near future, but maybe the fix was only released on 1.18.2

So, nothing should need to change in tinkers, just in immersive engineering.

**Comment by IvorAmlug** [comment]
Well okay then thx for takin ur time answering me.
Well since i will move to 1.18.2 as soon as the rest of my mods allow it (i have a "few" others, but didnt wrote them down since i only tested whit just the 2 mods and i still was the case)
Thx again for takin ur time.

**Comment by KnightMiner** [comment]
Going to close this as the fix is not on our side, and pretty sure its resolved in 1.18.2. If not, make an issue on IE's tracker and link it here.
