### ISSUE TITLE
> What makes you think pocket chain should be slotless?

### ISSUE THREAD

**Issue by Aqua-Convallaria** [SlimeKnights/TinkersConstruct#4823]
> "Pocket Chain" is not actually slotless.
It's in the Encyclopedia of Tinkering.
Effects:
·Maxium of 1 level
·Slotless
·Requires tool belt or shield strap
![image](https://user-images.githubusercontent.com/102253976/161677066-afeedfab-bd82-49e8-afe2-51aaf589cfa4.png)

_Originally posted by @Aqua-Convallaria in https://github.com/SlimeKnights/TinkersConstruct/issues/4812#issuecomment-1088246996_

**Comment by KnightMiner** [comment]
Do not make a new issue to followup on an existing issue, use the old issue.
