### ISSUE TITLE
> The formula is simply `((((Head + Tool Bonus) * Handle) + Modifier Bonus) * Modifier Multiplier * Tool Multiplier) + 1` which is basically what you said (assuming 0 modifier bonus and 1 modifier multiplier). And it is not wrong. Give me specific examples with numbers why you think its wrong.

### ISSUE THREAD

**Issue by Aqua-Convallaria** [SlimeKnights/TinkersConstruct#4825]
> The formula is simply `((((Head + Tool Bonus) * Handle) + Modifier Bonus) * Modifier Multiplier * Tool Multiplier) + 1` which is basically what you said (assuming 0 modifier bonus and 1 modifier multiplier). And it is not wrong. Give me specific examples with numbers why you think its wrong.
> 
> Also, I think you have some multipliers wrong in your comment. They have changed since 1.16, so if you are reading an old spreadsheet they are wrong. They should be updated in the books, but if not that is the bug you found. You can find the [correct values here](https://github.com/SlimeKnights/TinkersConstruct/tree/1.18/src/generated/resources/data/tconstruct/tinkering/tool_definitions) if you want to verify whether the books are correct.

The problem should really be that the book is wrong. These figures are in good agreement with the new table.

Also, there seems to be a problem with the description of bones in the book.

_Originally posted by @Aqua-Convallaria in https://github.com/SlimeKnights/TinkersConstruct/issues/4824#issuecomment-1090405441_

**Comment by ShinyPorygon** [comment]
Don't make a new issue to follow up an active one.
