### ISSUE TITLE
Add Ability to Configure Tier Upgrade for Diamond and Emerald Modifiers

### ISSUE THREAD

**Issue by wendall911** [SlimeKnights/TinkersConstruct#4826]
### Minecraft Version

1.18.1

### Forge Version

36.1.0

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Problem description

Harvest tier of all materials is settable via datapack. However, emerald and diamond modifiers have the tier hard coded. For any progression mod where mining tiers are tweaked to match a progression style of play this breaks the progression possibilities and forces vanilla tiers.

### Suggested solution

Simply add a setting for tier in the config for the modifiers. This is currently done with other recipes where datapack overrides aren't an option.

### Alternatives considered

Add "tier" as a property to the upgrade modifier so it can be overridden in a datapack. This is probably the "proper" way of doing this, but I'd not be bothered to see this as a configuration option.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
This is already planned on the roadmap, under dynamic modifiers. Short version is you will be able to add modifiers using JSON, and many existing modifiers will be migrated to JSON. No sense making a ton of config options for each modifier when we can have a general one for all modifier stats

**Comment by wendall911** [comment]
Ok, thanks, that makes a lot of sense. I looked at the roadmap, but it wasn't clear that this was covered. Much appreciate the changes.

**Comment by KnightMiner** [comment]
344c3e6 has the implementation of dynamic modifiers.

**Comment by wendall911** [comment]
Ok, I've tested this and it works great! Much appreciated.

**Comment by KnightMiner** [comment]
Leave it open until its released. And do not use unofficial builds. If it was ready for people to use 1.18.2 it would be released.

**Comment by wendall911** [comment]
Was just testing with git. Will leave open. Appreciated.

**Comment by KnightMiner** [comment]
Added in [3.5.0.18](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.0.18) for 1.18.2.
