### ISSUE TITLE
NullPointerException Error

### ISSUE THREAD

**Issue by SightedNZ** [SlimeKnights/TinkersConstruct#4831]
### Minecraft Version

1.16.5

### Forge Version

36.2.31

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

Upon game launch, the game crashes with the following error:

Details:
	Mod File: TConstruct-1.16.5-3.3.4.335.jar
	Failure message: Tinkers' Construct (tconstruct) encountered an error during the sided_setup event phase
		java.lang.NullPointerException: Registry Object not present: tconstruct:melter
	Mod Version: 3.3.4.335
	Mod Issue URL: https://github.com/SlimeKnights/TinkersConstruct/issues
	Exception message: java.lang.NullPointerException: Registry Object not present: tconstruct:melter

Prior to logging off the world last, I had built and activated a basic reactor with Extreme Reactors, built a Mekanism Teleporter with one end in the nether, and had built a Foundry around a blaze spawner in the nether fortress.

Please find attached the relevant crash and game log.

I am happy to create a OneDrive link to a share of the game world if required.

[crash-2022-04-11_20.13.29-fml.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8462428/crash-2022-04-11_20.13.29-fml.txt)

[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/8462419/latest.log)

### Other mods

Below is the use of all mods I am using. This is a custom pack.

Advanced Finders
AdFinders-1.16.5-5.0.11.1-build.0214.jar

Better Foliage
BetterFoliage-2.7.1-Forge-1.16.5.jar

Better Fps - Render Distance[Forge]
betterfpsdist-1.1.jar

Brandon's Core
BrandonsCore-1.16.5-3.0.13.244-universal.jar

Chisel
Chisel-MC1.16.5-2.0.1-alpha.4.jar

CodeChicken Lib 1.8.+
CodeChickenLib-1.16.5-4.0.7.445-universal.jar

CoFH Core
cofh_core-1.16.5-1.4.2.9.jar

Configured
configured-1.5.1-1.16.5.jar

ConnectedTexturesMod
CTM-MC1.16.1-1.1.2.6.jar

Corail Recycler
corail_recycler-1.16.5-5.2.0.jar

Cyclic
Cyclic-1.16.5-1.5.15.jar

Draconic Evolution
Draconic-Evolution-1.16.5-3.0.22.444-universal.jar

Extreme Reactors
ExtremeReactors2-1.16.5-2.0.41.jar

Fast Leaf Decay
FastLeafDecay-v25.2.jar

ForgeEndertech
ForgeEndertech-1.16.5-7.2.2.0-build.0202.jar

Inventory Tweaks Renewed
invtweaks-1.16.4-1.0.1.jar

Iron Chests
ironchest-1.16.5-11.2.21.jar

JourneyMap
journeymap-1.16.5-5.8.0.jar

Just Enough Items (JEI)
jei-1.16.5-7.7.1.152.jar

Just Enough Resources (JER)
JustEnoughResources-1.16.5-0.12.1.133.jar

Kotlin for Forge
kotlinforforge-1.17.0-obf.jar

Large Ore Deposits
AdLods-1.16.5-4.1.9.2-build.0217.jar

Mantle
Mantle-1.16.5-1.6.157.jar

Materialis
materialis-1.16.5-2.5.1.jar

McJtyLib
mcjtylib-1.16-5.1.5.jar

Mekanism
Mekanism-1.16.5-10.1.2.457.jar

Mekanism Generators
MekanismGenerators-1.16.5-10.1.2.457.jar

Mekanism Tools
MekanismTools-1.16.5-10.1.2.457.jar

More Overlays Updated
moreoverlays-1.18.18-mc1.16.5.jar

NoCaves Mining Dimension
MiningDimension_1.16.5_mod.jar

OptiForge
OptiForge-MC1.16.5-0.5.7.jar

Ore Excavation
OreExcavation-1.8.157.jar

Patchouli
Patchouli-1.16.4-53.2.jar

Project Intelligence
ProjectIntelligence-1.16.5-1.1.0.35-universal.jar

RFTools Base
rftoolsbase-1.16-2.1.3.jar

RFTools Builder
rftoolsbuilder-1.16-3.1.7.jar

RFTools Dimensions
rftoolsdim-1.16-7.0.20-beta.jar

RFTools Power
rftoolspower-1.16-3.0.13.jar

Simply Light
simplylight-1.16.5-1.4.2-build.32.jar

Sophisticated Backpacks
sophisticatedbackpacks-1.16.5-3.15.13.560.jar

Storage Drawers
StorageDrawers-1.16.3-8.5.1.jar

The One Probe
theoneprobe-1.16-3.1.5.jar

Tinkers Construct
TConstruct-1.16.5-3.3.4.335.jar

U Team Core
u_team_core-1.16.5-3.2.1.196.jar

Useful Railroads
useful_railroads-1.16.5-1.4.6.38.jar

ZeroCore 2
ZeroCore2-1.16.5-2.1.9.jar

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine, Other (specify under other mods)

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment]
Please reproduce without any present performance mods. I am unable to reproduce without any other mods. It's probably optifine/optiforge, which you shouldn't be using.

**Comment by SightedNZ** [comment]
> Please reproduce without any present performance mods. I am unable to reproduce without any other mods. It's probably optifine/optiforge, which you shouldn't be using.

Thanks for that, disabling Optiforge did the trick!
