### ISSUE TITLE
unable to make an Ingot cast

### ISSUE THREAD

**Issue by Szymonc4pro** [SlimeKnights/TinkersConstruct#4832]
### Minecraft Version

1.16.5

### Forge Version

36.2.33

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

i can't make a gold or sand cast for an ingot 
for example if i put an ingot on the seared brick table and try to pour some gold to make a cast i click on the faucet and nothing happens
if i place a blank sand cast and click on it with an ingot in hand the cast comes back to my inventory but if i do that with a pickaxe head or anything else it works

### Other mods

i don't know what mods i should list i was playing on a self made modpack with about 100 mods including tinkers

but i had stuff the whole thermal series
no tree punching
ice and fire 
replay mod
biomes o planety
quark
and other stuff,

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues, Searched open issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Remove optifine wouldn't be surprised if that caused it  with everything else it has.

**Comment by Szymonc4pro** [comment]
>



> Remove optifine wouldn't be surprised if that caused it with everything else it has.

i am about to test if the issue is still there without any other mods than tinkers and mantle

**Comment by Szymonc4pro** [comment]
just tested without any other mods other than tinkers and mantle and the issue is not there now gonna test this but with optifine

**Comment by KnightMiner** [comment]
you most likely have a mod breaking the ingot tag. Tags are surprisingly fragile sometimes, and all it takes is one mod adding a broken entry for all mods to have broken tags.

To verify if this is the issue, run `/mantle tags_for held item` while holding any ingot

**Comment by Szymonc4pro** [comment]
> just tested without any other mods other than tinkers and mantle and the issue is not there now gonna test this but with optifine

alright did the same test with optifine and it still working can make an ingot cast

did the same with my client side mods and still works

**Comment by ChiefArug** [comment]
One mod which is known to mess with tags like that is TAIGA, the author knows about it but hasn't fixed it yet (I think).
Do you have that, and does it go away after removing it?

**Comment by Szymonc4pro** [comment]
> One mod which is known to mess with tags like that is TAIGA, the author knows about it but hasn't fixed it yet (I think). Do you have that, and does it go away after removing it?

i do have taiga in my mod pack gonna test with taiga and see if it is the problem

**Comment by Szymonc4pro** [comment]
found the trouble maker 
its taiga

**Comment by Szymonc4pro** [comment]
gonna close the issue now thanks for the help
