### ISSUE TITLE
Does the bow and arrow have a chance to return?

### ISSUE THREAD

**Issue by erney519** [SlimeKnights/TinkersConstruct#4833]
### Minecraft Version

1.18.1

### Forge Version

39.0.76

### Mantle Version

Mantle-1.18.1-1.8.37

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.2.60

### Problem description

Tinker's bow and arrow are long gone
They are very helpful for survival

### Suggested solution

Hope Tinker's bow and arrow can return

### Alternatives considered

don;t have alternative

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Check faq again. Specifically roadmap.
