### ISSUE TITLE
Using Too Much Resources

### ISSUE THREAD

**Issue by tsujidospride** [SlimeKnights/TinkersConstruct#4834]
### Minecraft Version

1.16.5

### Forge Version

36.2.33

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

I run various other mods but never had this issue while running the same combo of mods...currently lava is used up way too quickly when smelting anything even an iron ingot goes through too much resources...iron ingot goes through over 1k mb to smelt same thing with a single seared brick...i have iron furnace installed also which is using update 2.7.7 so idk if code is conflicting presently...if theres a fix without me removing iron furnace please let me know

### Other mods

iron furnace version 2.7.7 (this is the only one i can think is interfering), cyclic version 1.5.15, quark version 2.4-322, plus a few mods that alter world such as biomes o plenty 13.1.0.477, botania, 420.2, ice and fire 2.1.9, mowzie's mobs 1.5.23, and twilight forest 4.0.870, along with various dungeon crawler type mods from yung but i doubt the world mods ive mentioned is affecting tinkers construct

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
How big is your smeltery? Bigger smelteries use fuel faster. Its more fuel efficient if you fill all slots, but if you choose not fill only a couple slots its a waste

> Searched open issues, I did not search

Which is it, did you search or not?

**Comment by tsujidospride** [comment]
> How big is your smeltery? Bigger smelteries use fuel faster. Its more fuel efficient if you fill all slots, but if you choose not fill only a couple slots its a waste
> 
> > Searched open issues, I did not search
> 
> Which is it, did you search or not?

i searched open...my smeltry is 49+ blocks tall center of which is 5x5...i dont recall smeltry burning through resources faster the bigger they are

**Comment by TheOnlyMann** [comment]
> i dont recall smeltry burning through resources faster the bigger they are

https://github.com/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3#mechanics

**Comment by tsujidospride** [comment]
> > i dont recall smeltry burning through resources faster the bigger they are
> 
> https://github.com/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3#mechanics

ah gotcha...thanks
