### ISSUE TITLE
Wood/slimewood material bug when using logs or "wood" blocks for tool parts

### ISSUE THREAD

**Issue by CybernetCatgirl** [SlimeKnights/TinkersConstruct#4835]
### Minecraft Version

1.18.1

### Forge Version

Tested on Forge 39.1.2

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

On the current release of Tinkers Construct 3, there is a bug with the Wood material. Using some logs on various tool parts makes them give back four planks exactly, regardless of how much should be returned. First tested with Birch Logs, any time a part with a cost of four or eight is created (large plates, hammer heads, large blades, broad axe heads), the part builder consumes the correct amount of logs as normal, but returns four planks of the given type--an erroneous behavior, as it allows for a 50% recollection of planks after creating large tool heads, or what is effectively a full refund after creating large plates. This works on logs, "wood"/"hyphae" blocks (created by combining four wood blocks to get three--effectively a wood block with bark on every side), and all their stripped variants, and occurs with every wood variant, including the variants of slimewood, that have trees.

### Other mods

Capable of reproducing with only Mantle and Tinkers' Construct, without any extra mods.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
Also present on 1.16 -
Forge - 36.2.34
Mantle - 1.6.157
Tcon - 3.3.4.336
No other mods

**Comment by KnightMiner** [comment]
Fixed in [3.5.0.18](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.0.18) for 1.18.2. No plans to backport to 1.18.1
