### ISSUE TITLE
Scorched Casting Table can't be automated?

### ISSUE THREAD

**Issue by LordXerus** [SlimeKnights/TinkersConstruct#4836]
### Minecraft Version

1.18.1

### Forge Version

39.1.0

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

I created a scorched casting table + alloyer to quickly create obsidian panes. However, hoppers pull out the gold bars instead of the obsidian panes. A quick search `scorched` doesn't show me anything related. Is this intentional?

### Other mods

Tinker's Construct + Minecraft
Rubidium (I believe it's a fork of  Magnesium)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched closed issues

**Comment by KnightMiner** [comment]
If you power a casting table with redstone, it switches the input and the output. This is discussed n Mighty Smelting. Gold bars are supposed to be the input, but redstone power makes them the output so hoppers take them.

**Comment by LordXerus** [comment]
I see. That explains everything. I think for convenience I placed levers on an adjacent stone block. That might have powered the table and inverted the outputs.

Thanks for the help.
