### ISSUE TITLE
Nether Slime Island doesn't spawn when a datapack called Incedium is using together.

### ISSUE THREAD

**Issue by liu13755305** [SlimeKnights/TinkersConstruct#4837]
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

I found that Nether Slime Island didn't spawn when I used incedium(a datapack).
I search this question among all issues and I only found somebody post this question in 1.18.1.
I don't know how I can replace 1.16.5 code from the solving code in 1.18.1.
I really love tinker's constract. My English is not fluently.
Thank you very much.

### Other mods

![image](https://user-images.githubusercontent.com/74533409/164631538-86bf94cd-96ed-420b-8be6-768f3dcfa901.png)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Magnesium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by aethaerya** [comment]
Datapacks that affect worldgen usually prevent modded structures from spawning. I don't think they'll update the 1.16 version anymore unless it's a critical bug within TiC, since active development has shifted to 1.18.2.

**Comment by liu13755305** [comment]
> 

But as I know, some others like Reproposed Structures' can spawn successfully.
I still want to make clear the differences between two mods.
I'm making modpack for my girlfriend recently and I can't find the way to make the nether beautiful unless I use incendium.
Anyway,I really want to do something to make them work together,whether it's a line code or a file.
Otherwise I will make a choice.

**Comment by KnightMiner** [comment]
Datapacks are not true mods, and without pretty big hacks that essentially ignore datapacks, its not possible to ensure Tinkers' structures spawn when datapacks replace the nether.

It is possible in 1.16.5 to readd the structure to the modified nether using the datapack, though I am not certain of the details. 1.18.1 made it impossible to fix this issue in datapacks alone so tinkers had a code solution, and 1.18.2 entirely fixed the problem so no hacks are required. I have no plans to backport the hack to 1.16.5
