### ISSUE TITLE
Cannot click certain GUI buttons (Draconic Evolution Fusion Crafting GUI specifically) with Plate Armor Chestplate

### ISSUE THREAD

**Issue by FoxMcloud5655** [SlimeKnights/TinkersConstruct#4838]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

While the user has a Tinker's Construct Plate Armor Chestplate equipped, you cannot click the craft button in Draconic Evolution's Fusion Crafting GUI.  Not sure if this affects anything else, but I've confirmed that this bug happens across multiple computers, Minecraft accounts, and worlds (thanks to help from others in the Draconic Evolution Discord).

### Other mods

BrandonsCore-1.16.5-3.0.13.244-universal
CodeChickenLib-1.16.5-4.0.7.445-universal
Draconic-Evolution-1.16.5-3.0.22.444-universal
Mantle-1.16.5-1.6.157
TConstruct-1.16.5-3.3.4.335

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Checked the FAQ

**Comment by StaticPH** [comment]
I don't expect it to be of importance, but can we assume you have confirmed this occurs with armor made of a variety of different materials? In particular, using only materials available with the base Tinkers Construct mod, on the off chance that some other mod is adding a material with a new trait that causes this behavior.

**Comment by FoxMcloud5655** [comment]
As I have listed in the other mods section, I only used those mods in testing.  I used Plate Armor pulled from the creative menu to test on my end.  Personally, I have not tried using other materials.

**Comment by KnightMiner** [comment]
To be completely honest, I see no reason why wearing our armor would change the behavior of a UI. Here are the steps you can do to get this issue resolved:

* Test with other Tinkers' Construct chestplate sets, lets determine if its only plate armor or also travelers and slime suit
* Report to Draconic Evolution, they could shed light on what makes the fusion crafting GUI abnormal
* Explain in more detail about what Fusion Crafting is (or link a resource explaining it), I do not use Draconic Evolution, but if this is an in world GUI it would give more information to debug this.

**Comment by KnightMiner** [comment]
Fixed in the latest release of BransonsCore
