### ISSUE TITLE
Prevent Slime Islands from Generating in Worldspawn Radius

### ISSUE THREAD

**Issue by wendall911** [SlimeKnights/TinkersConstruct#4843]
### Minecraft Version

1.18.2

### Forge Version

40.1.0

### Mantle Version

1.9

### Tinkers' Construct Version

3.5.0

### Problem description

While testing writing TCon addons, I had a couple instances where the slime island is generated over the worldspawn. This causes a somewhat hilarious situation where the user spawns on a island high in the sky. I've had this happen twice over maybe 50 different seeds.

### Suggested solution

Possibly not generate islands if in the random spawn radius of the worldspawn.

### Alternatives considered

Just leave it? It is kinda funny when it happens. Takes a few falling deaths before finally getting spawned on the ground. I'm not sure if this is a major issue, but just something to ponder fixing.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
There is no 1.18.2 release. Are you actually playing on 1.18.1 or are you using unofficial builds?

**Comment by wendall911** [comment]
I'm working on my addons for TCon in preparation for 1.18.2. This was also an issue with 1.18.1, but thought I would report it. I have been building and testing early for whenever things get released. Not in any rush, just wanted to make sure I'm updating code.

**Comment by KnightMiner** [comment]
Going to close this as I currently do not have any desire to implement this. Slime islands are simply a structure registered with the vanilla structure system, which does not support suppressing around spawn. The only other method I have to do such suppression can lead to false positives with the locate command.
