### ISSUE TITLE
1.18.2 multiplayer is broken

### ISSUE THREAD

**Issue by Jannik-rg** [SlimeKnights/TinkersConstruct#4846]
### Minecraft Version

1.18.2

### Forge Version

40.1.0

### Mantle Version

1.18.2-1.9.DEV

### Tinkers' Construct Version

1.18.2-3.5.0.DEV

### Describe your issue

When creating a singleplayer world, there is no problem. But in multiplayer you get "invalid player data" as an error message on the client and this on the server.

### Crash Report

https://github.com/SlimeKnights/TinkersConstruct/files/8597944/error.txt

### Other mods

Mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
1.18.2 is not released. Any bugs you experience are as is. Wait for it to release. 
Also don't distribute unofficial builds.
