### ISSUE TITLE
Protection ability requiring an additional slot for each upgrade.

### ISSUE THREAD

**Issue by Vipth** [SlimeKnights/TinkersConstruct#4847]
### Minecraft Version

1.18.1

### Forge Version

39.0.85

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

## Primary Issue
Abilities, as I understand them currently, only need to use an ability slot once. Whenever I try to add anything beyond Protection I, this is not the case. I have to add an extra ability slot each time.

## Addition Things
- [This Spreadsheet](https://docs.google.com/spreadsheets/d/17qwV8UOR0DBsUqbxyernG4e4LtjAZ55DMAqnJWc2kLw/edit#gid=0) shows that Protection has been implemented, however, Protection is nowhere to be found in any of the Tinker's books. I only know that it exists because of JEI and the previously mentioned spreadsheet.
- When I add extra slots using the "Creative Ability" item, Protection seems to be uncapped, I was able to get it to 30+. I'm not sure if this is intentional, so I wanted to bring it up here.

### Modpack:
[Minecolonies Official - Adventure - Create your Colony](https://www.curseforge.com/minecraft/modpacks/minecolonies-adventure-create).

### Specific Performance Mods: 
(I only went over the mod list for the modpack once, please forgive me if I missed one.)
- [Starlight](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
- [Better FPS Distance](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
- [Dynamic View Distance](https://github.com/ldtteam/DynView/)
- [Ferrite Core](https://www.curseforge.com/minecraft/mc-mods/ferritecore)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
You misunderstand abilities. Luck only uses a slot for the first level, but that is just luck. Expanders requires a level for each, so does spilling, and strength, and literally every other ability. 

Also, books are manually written. JEI is automatic. JEI is the true source.

And yes, most abilities are uncapped. You can get a max of 2 slots, that is the cap

**Comment by Tobuscouse** [comment]
So Protection II is the intended max per armor piece? @KnightMiner

**Comment by KnightMiner** [comment]
that is what I said, yes.

* Abilities have a most two slots
* Abilities that support multi-level have no level limit
* Therefore, for multi-level abilities, level 2 is the max
