### ISSUE TITLE
Cannot fly with Slimelytra

### ISSUE THREAD

**Issue by Gompy54** [SlimeKnights/TinkersConstruct#4848]
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

I cannot fly when I equip the slimelytra.  Not with rockets.  Not with the slingshot.  Not by jumping off cliffs.  The slimelytra seems to only deploy when using the sneak key, not the jump (spacebar) key  like the normal elytra.  The plain elytra does work as it should.

I searched all issues, only found 3 related to "slimelytra", none of which addressed the flight issue.

### Other mods

None.  Only using Tinkers and Mantle.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched closed issues

**Comment by ShinyPorygon** [comment]
Unable to reproduce, with tinkers + mantle .

Can fly like normal, use rockets, ect. We need more information

**Comment by Gompy54** [comment]
My bad.  I only tried it in Creative mode.  It does work in Survival with only Tinkers + Mantle.  However, on our server, with a boatload of other mods, it does not.  We are using a total of 72 mods on the server, including Tinkers and Mantle.  Immersive Engineering, Creative, Applied Energistics, Quark, and more.  I will try to figure out which mod is causing the problem and update the issue.

Thanks,

~Andy

________________________________

**Comment by KnightMiner** [comment]
Probably caused by Caelus. Ensure you are on the latest version of Caelus, and test without it. If you do not have that mod or still have issues, find the mod causing problems. Without that information we can do *nothing* for you.

**Comment by KnightMiner** [comment]
Closing for lack of response.

**Comment by Gompy54** [comment]
Man, you’re good.  Updated Caelus to the 3.0.0.2 version and it now works.  At least, the single player version works.  The server version still does not.  (Yes, I double-checked the Caelus version on the server.)

At any rate, this is now a server problem, not a Tinkers problem, so thanks for all the help.  If I find the solution for the server, I will come back and update this issue.

~Andy
