### ISSUE TITLE
Hard to read the text in the mighty smelting book (visual issue)

### ISSUE THREAD

**Issue by Ninjarogersgithub** [SlimeKnights/TinkersConstruct#4851]
### Minecraft Version

1.18.2

### Forge Version

40.1.19

### Mantle Version

1.18.2-1.9.20

### Tinkers' Construct Version

1.18.2-3.5.0.17 (first alpha release of 1.18.2)

### Describe your issue

The backround of the mighty smelting book makes it incredibly difficult for me to read the text, both cause of the dimness of the backround and the thinness of the text

### Crash Report

_No crash, this is purely an issue with the visuals of the book_

I've cut out the extra fluff that was unrelated to my issue, as this isn't a crash.

**Comment by ShinyPorygon** [comment]
Made as proper enhancement

**Comment by KnightMiner** [comment]
Same as #4852, for the sake of searchability in the future
