### ISSUE TITLE
Hard to read the text in mighty smelting book

### ISSUE THREAD

**Issue by Ninjarogersgithub** [SlimeKnights/TinkersConstruct#4852]
### Minecraft Version

1.18.2

### Forge Version

40.1.19

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Problem description

It's hard to read the text on the might smelting book. The dark grey backround paired with the thin black text makes it all kinda mesh together for my eyes.

### Suggested solution

A lighter backround would probably fix this

### Alternatives considered

outlining the text/making the font slightly bigger could also help

### Additional context

I have vision problems and need to wear glasses, which is definitely part of the reason why I struggle to be able to read the text in the book, but I can read the other books just fine.

### Searched for existing enhancement?

Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.5.1.31
