### ISSUE TITLE
TConstruct is incompatible with RecipeStages

### ISSUE THREAD

**Issue by Darmstadtium271** [SlimeKnights/TinkersConstruct#4853]
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Mantle Version

1.16.5-1.6.157

### Tinkers' Construct Version

1.16.5-3.3.4.335

### Describe your issue

I added a recipe using RecipeStages. When I crafting it in a CraftingStation, the game crash.

### Other mods

 Tinkers' Construct
 CraftTweaker
 JEI
 Jade
 GameStage
 RecipeStages

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked the FAQ

**Comment by ShinyPorygon** [comment]
Without a crash report there is nothing that could be done. 
Looking at a previous issue regarding Recipe Stage but different problem there may not be much we can do regardless?

**Comment by ShinyPorygon** [comment]
Closing for lack of response.
