### ISSUE TITLE
Crashes upon startup

### ISSUE THREAD

**Issue by RedstoneFox** [SlimeKnights/TinkersConstruct#4854]
### Minecraft Version

1.18.2

### Forge Version

40.1.0

### Mantle Version

1.18.2-1.9.20

### Tinkers' Construct Version

1.18.2-3.5.0.17

### Describe your issue

Upon launching with T-Construct either enabled or disabled, the game crashes and issues an "Error:1" code. The pack I've developed works with Mantle installed, but for some reason it causes an issue if T-Construct exists in the pack at all.

Mods are listed below as well.
Performance Enhancer mods are: Radium and Radon.

### Other mods

![image_2022-05-09_123507795](https://user-images.githubusercontent.com/14907966/167456204-c5d04b8e-3fef-4313-8150-154ab9d9b51a.png)
![image_2022-05-09_123534502](https://user-images.githubusercontent.com/14907966/167456271-66721464-dbc4-4669-b326-452575941875.png)
![image_2022-05-09_123556847](https://user-images.githubusercontent.com/14907966/167456333-7e8f25f1-4676-4b39-a85a-889b5f60f407.png)
![image_2022-05-09_123617794](https://user-images.githubusercontent.com/14907966/167456377-34ffc950-6c99-4a64-8f12-099cd283d3aa.png)
![image_2022-05-09_123638253](https://user-images.githubusercontent.com/14907966/167456431-23d640e5-79c0-4a70-b9cf-bb39ef21d7a8.png)
![image_2022-05-09_123709312](https://user-images.githubusercontent.com/14907966/167456508-6495e851-c3eb-4962-8d89-1a13ece5c046.png)
![image_2022-05-09_123732847](https://user-images.githubusercontent.com/14907966/167456584-3d8fab1c-cdce-43f2-8dca-1f3e8273aabb.png)
![image_2022-05-09_123753513](https://user-images.githubusercontent.com/14907966/167456657-03288132-57b4-4166-b993-9e5f99c1da78.png)
![image_2022-05-09_123817155](https://user-images.githubusercontent.com/14907966/167456725-459e62b6-37e6-4393-b285-c8fce0a00fb3.png)
![image_2022-05-09_123829143](https://user-images.githubusercontent.com/14907966/167456759-ad784619-ed1a-489d-b4f7-d43ea3edd632.png)

### Tried reproducing with just Tinkers?

I will go do that now (Edit: Just tested with just Tinker's. Crash still occours.)

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
Since you say it crashes but provide no crash log there is not much we can do.

**Comment by RedstoneFox** [comment]
Doing my best to figure out a way to pull the crashlog from GD Launcher.

**Comment by RedstoneFox** [comment]
Ah! I have found the issue! Version of Forge is outdated for T-Construct. Updating the version to see if that solves it.

**Comment by RedstoneFox** [comment]
[2022-05-09-7.log.gz](https://github.com/SlimeKnights/TinkersConstruct/files/8653721/2022-05-09-7.log.gz)
Managed to get the log of the crash!

**Comment by Dreki1984** [comment]
Check if your mantle is updated too.

should be Mantle-1.18.2-1.9.20.jar

**Comment by Dreki1984** [comment]
Unless I am missing something, that isn't a log, I opened it in Notepad++ and it is a bunch of gibberish.

And to add to this: My game works just fine with pretty much the same mods.

Try using the latest version of Forge instead of the recommended.

**Comment by KnightMiner** [comment]
That is a log in a compressed file format @Dreki1984, its the format mojang uses for logs once its no longer latest.

@RedstoneFox that log has no mention of Tinkers' Construct, all I see is an exception in maxhenkel.gravestone. Clear out your logs folder, then run the game and give me the latest.log. Alternatively, switch to the vanilla launcher and copy over your mod list, its likely your launcher is messing with the logs

**Comment by RedstoneFox** [comment]
This is getting odd... The maxhenkel.gravestone and maxhenkel.corpse shouldn't show up as I don't have those mods installed at all.

Here's the latest log after clearing out the old ones. 
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/8654903/latest.log)

**Comment by RedstoneFox** [comment]
Currently about to test from the Vanilla/Curseforge launchers to see if there is any difference.

**Comment by RedstoneFox** [comment]
Log from the Curseforge launcher
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/8654943/latest.log)

**Comment by RedstoneFox** [comment]
Debug and latest log from the vanilla launcher
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/8655001/debug.log)
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/8655002/latest.log)

**Comment by BlackStarG5** [comment]
To add on, same as before ^^ settings wis
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/8655403/latest.log)
This is the only information the log displays with it open as minecraft prepares. Possible an issue with Mantle?

**Comment by KnightMiner** [comment]
What makes you think its a Mantle issue? You are randomly guessing problems instead of taking time to debug.

Most of the logs tell me you have a class not found error with the mods I mentioned above. Some mention a class not found error with a different mod class (`snownee.snow` or `me.jellysquid.mods.sodium`). Your last one (BlackStarG5s) has Optifine, which is bad, but most don't have Optifine. In general though, none of them have a clear error.

So, rather than randomly blaming mods, lets narrow down the problem. I know Tinkers' Construct works in large modpacks, its actively being used on the ForgeCraft server and in Darkosto's in dev Journey 2 the Core pack, and neither is having issues. This means one of your mods is causing problems. So lets narrow down the issue:

* You claim you tested with only Tinkers' Construct. If that is true, give me a log with *only* tinkers construct, all this mixin spam is not helping read the log and we dont use mixins.
* If you cannot get a crash with only tinkers, narrow down the minimal mod list to make this happen.

We can do more debugging once you find me a minimal mod list then get me a log or crash report with a minimal list.

**Comment by RedstoneFox** [comment]
I'll do my best to limit down the modlist to what causes it to crash.

**Comment by BlackStarG5** [comment]
Same as well, Sorry for for my _random assumption_ I don't code java anymore haha lost a lot of skill in it :). I'll start by comparing my mod list with yours RedstoneFox to see if we have any mods in common

**Comment by BlackStarG5** [comment]
@RedstoneFox DUDE LMFAO I JUST READ YOUR LOG
USE 40.1.16 forge loader
Currently using 40.1.19 (No issues yet)

**Comment by BlackStarG5** [comment]
How the F was I the first to notice this HAHA

**Comment by RedstoneFox** [comment]
Here is a copy of the latest log with just TC and Mantle Installed
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/8655925/latest.log)

**Comment by KnightMiner** [comment]
That log has surprisingly little information. Got a debug.log file? You could also try running on the latest forge. build  40.1.19 instead of  40.1.16

**Comment by RedstoneFox** [comment]
Here's the debug with 40.1.19 and latest log.
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/8656035/debug.log)
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/8656036/latest.log)

**Comment by KnightMiner** [comment]
That debug.log still lacks any information that tells me why its not working. I could produce the exact same sort of log by starting the game then quitting once I reach title screen. 

Please verify whether this issue happens on the same forge version without tinkers. Also test without both tinkers and mantle. Get the same two logs for each.

**Comment by RedstoneFox** [comment]
The crash is when launching Minecraft itself, not to do with messing around in a world. I'm gonna spend a few hours and try slowly adding in mods to test and see which mod might be causing the crash.

**Comment by RedstoneFox** [comment]
@KnightMiner I have discovered the issue. When Create and Tinker's is installed together it crashes upon launch and gives me a repeatable "Error: Uncaught Fatal Exception  code: 1".

**Comment by RedstoneFox** [comment]
Wait... no, now it's working nicely...

**Comment by RedstoneFox** [comment]
I finally managed to pull open and pull the console logs directly from GD Launcher. I threw Tinker's and Mantle into a duplicate of the pack I've been working on and this is the word spaghetti it throws back at me
[Launcher console Error thingy.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8656276/Launcher.console.Error.thingy.txt)
.

**Comment by RedstoneFox** [comment]
Issue has been narrowed down to Pehkui. Will be bringing it to that dev's attention. Sorry for the hold up fellows.
