### ISSUE TITLE
kama mystical agriculture right click

### ISSUE THREAD

**Issue by Warbringer12** [SlimeKnights/TinkersConstruct#4855]
### Minecraft Version

1.16.5

### Forge Version

36.2.33

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

right clicking with the kama on mystical agriculture crops don't seem to work

### Crash Report

none

### Other mods

mystical agriculture: 1.16.5-4.2.6
cucumber: 1.16.5-4.1.12

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Report this to mystical agriculture as well and link it here.

Also, can you verify whether this happens on 1.18.2?

**Comment by Warbringer12** [comment]
can verify this happens on 1.18.2 also

**Comment by Warbringer12** [comment]
link to issue on mystical agri https://github.com/BlakeBr0/MysticalAgriculture/issues/569

**Comment by KnightMiner** [comment]
This is marked as fixed in Mystical Agriculture so closing.
