### ISSUE TITLE
[1.18.2] Book index taking you to the worng page

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#4856]
### Minecraft Version

1.18.2

### Forge Version

40.1.19

### Mantle Version

 Mantle-1.18.2-1.9.20.jar

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.0.17.jar

### Describe your issue

When I click on the index for the modifiers in the book, I am taken to another page that is not the one that I wanted

Trying to check the Draconic modifier
![image](https://user-images.githubusercontent.com/44974827/168086959-1e351a8e-d795-49e4-bf84-6b24af067b40.png)

I am taken to the Stripping page
![image](https://user-images.githubusercontent.com/44974827/168087024-7ab3acf4-55bc-4b48-a62e-ddb98aaae5d6.png)

### Other mods

Tinkers
Mantle 

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by KnightMiner** [comment]
Fixed in Mantle 1.9.27
