### ISSUE TITLE
Lacerating causes guardians to deal constant thorns damage

### ISSUE THREAD

**Issue by Kenpari** [SlimeKnights/TinkersConstruct#4857]
### Minecraft Version

1.18.2

### Forge Version

40.1.19

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.18

### Describe your issue

When attacking a guardian with a weapon that has Lacerating, if the damage over time effect of Lacerating is applied to the guardian, the player will take thorns damage with every tick of lacerating while the guardian's thorns are extended.

### Other mods

BiomesOPlenty
carryon
mr crayfish's furniture
mr crayfish's guns mod
dynamiclightsreforged
openblocks elevator
framework
InventoryProfilesNext
jei
macawsbridges bop addon
macawsroofs bop addon
Mantle
mcw bridges
mcw windows
mcw roofs
MouseTweaks
NaturesCompass
oculus
refinedstorage
rubidium_extras
rubidium
selene
sophisticatedbackpacks
sophisticatedcore
supplementaries
TConstruct
TerraBlender

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Magnesium

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by luckyu19** [comment]
Able to replicate this issue with only TiC3 and Mantle.
Forge version is 40.1.20.
Guardians can switch attack target and the damage would still able to be passed back to the player.

**Comment by KnightMiner** [comment]
Fixed in 3.5.1.31
