### ISSUE TITLE
Bug tuxteres

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#4858]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

![Screenshot 2022-05-15 093338](https://user-images.githubusercontent.com/76481256/168460399-3a885127-332d-464b-8314-426f4d00528f.png)
![Screenshot](https://user-images.githubusercontent.com/76481256/168460559-60cb0e47-006b-41d3-a4c5-3132d06a4d85.png)
![Screenshot](https://user-images.githubusercontent.com/76481256/168460884-eb14aa2a-51a3-421a-bc5a-863e0c9aadce.png)

### Other mods

Better FPS, Entity culling, Dynamic view

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine, Other (specify under other mods)

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Has bugged textures, Has optifine. Has not come to the conclusion those tend to be related. 

Do as we told you and try to reproduce with minimal mods. We ask you for performance enchancers because they cause bugs. Test without them, and if it works then find which performance enhancer causes this.

**Comment by ghost** [comment]
Removing Optifine helped
