### ISSUE TITLE
Ukrainian Translation

### ISSUE THREAD

**Issue by MrSvyatik** [SlimeKnights/TinkersConstruct#4860]
[RobloMinerYT](https://github.com/RobloMinerYT)
RobloMinerYT commented [11 hours ago](https://github.com/SlimeKnights/TinkersConstruct/pull/4859#issue-1236413938) • 
https://drive.google.com/drive/folders/1Slu1d6BSP3Nq44tb5u9ZP2zFyySR5YVL ukrainan translate TConstruct-1.16.5-3.3.4.335

_Originally posted by @RobloMinerYT in https://github.com/SlimeKnights/TinkersConstruct/issues/4859#issuecomment-1127380333_

**Comment by KnightMiner** [comment]
See also #4861, will need to figure out how to deal with these after getting a response on the other issue.

**Comment by KnightMiner** [comment]
Closing as #4861 exists, PRs are preferred when possible, I only suggested an issue as the previous PR was done wrongly.
