### ISSUE TITLE
Blaze heads doesnt drop when blaze is kill by other mods then Tinkers

### ISSUE THREAD

**Issue by Sunekaer** [SlimeKnights/TinkersConstruct#4863]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

 Mantle-1.18.2-1.9.20.jar

### Tinkers' Construct Version

3.5.0.18

### Describe your issue

Blaze heads doesnt drop when blaze is kill by Mob Masher with beheading upgrade ( Mob Grinding Utils )

### Other mods

https://www.feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18/mods

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Not something we can fix. From my understanding, Mob Grinding Utils hardcodes the list of mob heads they can drop, so we have no way to add new ones. This would be on them to support. I would strongly encourage them to support it via JSON recipes like we do with our beheading.

**Comment by Flanks255** [comment]
Fixed in 1.18.2-0.4.38

**Comment by KnightMiner** [comment]
Great, thanks. See it's even in nice JSON recipes
