### ISSUE TITLE
Breaking insta-break blocks with broken tools voids drops

### ISSUE THREAD

**Issue by tomatheb** [SlimeKnights/TinkersConstruct#4864]
### Minecraft Version

1.18.2

### Forge Version

40.1.19

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.18

### Describe your issue

Breaking items with zero hardness (such as torches) can be broken with a broken tool, but they do not drop their item. While I'd expect no drop from blocks with toughness, instabreak blocks should generally drop regardless.

## Steps to reproduce:
Create Tinkers tool.
In survival, exhaust durability of said tool
Attempt to break a placed torch.

### Expected result:
Torch breaks instantly and drops.

### Observed result:
Torch breaks instantly, but do item is created.

Tested on:
Java 17.0.2 (OpenJDK)
Debian Testing

### Other mods

Originally discovered on FTB Presents Direwolf20 1.18 version 1.0.0, but can be reproduced with just Mantle and TConstruct installed.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.5.1.31
