### ISSUE TITLE
Shift Clicking Items out of the smeltery causes random items from inventory to go into the smeltery

### ISSUE THREAD

**Issue by IdealIdeas** [SlimeKnights/TinkersConstruct#4865]
### Minecraft Version

1.18.2

### Forge Version

40.1.2

### Mantle Version

idk

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

Modpack is TNP Limitless 5

Shift clicking on items in the smeltery side to take them out and return them to the inventory will cause random items from the player's inventory to be placed inside the smeltery.

### Other mods

TNP Limitless 5 Modpack

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues

**Comment by KnightMiner** [comment]
Try reproducing just tinkers, that is why the issue templates tells you to do it

**Comment by ShinyPorygon** [comment]
Unable to reproduce with just Tinkers and Mouse Tweaks since that would be relevant here. Assuming another mod is interfering.

**Comment by IdealIdeas** [comment]
TNP Limitless 5 doesnt have mouse tweaks for 1.18.2

**Comment by KnightMiner** [comment]
Okay, so? Shiny could not reproduce with a minimal mod list. Since you are the one experiencing this bug, try to reproduce with a smaller list of mods than an entire modpack.

**Comment by Kenpari** [comment]
I believe this issue is most likely caused by Inventory Profiles Next or Sophisticated Backpacks. Try reproducing without either of those. I have the same issue myself, but it's not important enough to me to isolate it.

**Comment by KnightMiner** [comment]
Closing for lack of response. Reproduce with a minimal modlist if you want a reopen, as stated above we cannot reproduce.
