### ISSUE TITLE
Ingot gauges only fill to 4000 mb

### ISSUE THREAD

**Issue by Kenpari** [SlimeKnights/TinkersConstruct#4866]
### Minecraft Version

1.18.2

### Forge Version

40.1.19

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.18

### Describe your issue

As the title reads, ingot gauges of both varieties will only hold an amount up to 4000 mb. As mDiyo said when I discussed this issue in Discord, they were changed "a while ago" to 4320 mb from 4000, so it appears that this shouldn't be the case. 

Specifically, ingot gauges, when filled via right-clicking on a drain that is part of a smeltery/foundry with sufficient liquid volume (4320+ mb), fill the proper, expected value of 4320 mb. However, if filled via other means (including by faucet), the ingot gauge will only fill to 4000 mb. 

To add some context, I only began experiencing this issue recently. A number of ingot gauges I already had placed in my world seem to fill to 4320 mb fine, but when broken and replaced, they start to only fill to 4000 mb (as do any newly crafted/placed ingot gauges). I thought it might be a mod conflict, so I ran the gamut of diagnostic mod-disabling, etc., but it turns out that the issue persists even with only mantle and tinker's construct active in a newly-generated world. What's more, I performed a completely fresh install of Minecraft and Forge 40.1.19, only to find the error still persists. It seems strange to me, since I don't think I've changed my verison of TiC or Mantle within the time period this suddenly started happening, but I suppose I might/must be wrong and it's a new issue.

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by luckyu19** [comment]
Only able to replicate this issue partially.
Filling both from a valid smeltery and from a tank returns the same value, 44 ingots (4000mb), instead of the described 48 ingots.
Tried switching to a different tank but didn't help.
Tried updating to 40.1.20 didn't help.

**Comment by KnightMiner** [comment]
Fixed in 3.5.1.31
