### ISSUE TITLE
Slime Boots Physics Not Working Properly

### ISSUE THREAD

**Issue by AzazelFTL** [SlimeKnights/TinkersConstruct#4871]
### Minecraft Version

1.18.1 / 1.18.2

### Forge Version

40.1.16 for 1.18.2  &  39.1.0 for 1.18.1

### Mantle Version

1.9.20 for 1.18.2  &  1.8.37 for 1.18.1

### Tinkers' Construct Version

3.5.0.17 (Alpha) for 1.18.2  &  3.4.2.60 (Beta) for 1.18.1

### Describe your issue

(My first issue on github, apologies if anything seems odd)
I've downloaded the alpha and beta versions for TCon from CurseForge and when I went to try the now only slime boots and a slime sling, the physics are very clearly not working properly.

The momentum is not conserved as in the past, though i have not checked since 1.16.5, and those could be the new ones (and nerfed if so) and when bouncing off the ground, even when not pressing any direction besides forward, I get launched in a slight diagonal from the player's perspective.
I've tried both versions and none showed different results, and also tried with and without other mods, including OF.

I don't know where i could post this problem, and I do get it's and alpha/beta and as such I can't demand a fix, but since i didn't see anyone mentioning this (besides one reddit post about 6 months ago, and for the 1.16.5 TCon version) I thought I could try and get more information about this, or if there's some misinformation I'm not aware of.

(Edit: Changed version, not minecraft alpha/beta, but Tinker's alpha/beta versions).

### Crash Report

No Crashes, can send video if needed.

### Other mods

None, tried with some mods AND OptiFine, without anything except OF and no mods (same results).

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
The boots never preserved momentum (or in MC terms its better to say velocity). They multiplied your movement speed if your speed changed, meaning they were effectively a constant speed boost while in air. This lead to problems notably with vanilla mechanics such as dolphins grace that could give you infinite speed.

The current code has them preserving speed, which will notably be a bit less than multiplying speed, but its also accurate to what you claim you want.

As for bouncing in inconsistent directions, I need more information about that. My experience is the boots bounce you in the direction you landed, that is what they are supposed to do. Switching directions mid air is difficult but keeping the same direction is easy. I'm inclined to say its different from before so you are interpreting it as wrong.

**Comment by AzazelFTL** [comment]
Thanks for the quick response.
I do remember going really fast in the water with dolphin's grace in 1.16.5 so I guess it's a fair change, though i do wonder if there's a middle alternative to this problem, say, for example, multiplying speed the first time when bouncing off the ground for some time and then reducing and maintaining that preserved speed.

I will try to show what I'm saying by going in the wrong direction.
See, when I bounce off the ground, I'm not changing direction mid-air, but rather the bouncing changes direction when touching the ground. Sounds similar to (sort of) bouncing of walls and reflecting the energy, but in this case it just bounces at the wrong direction. It is significant enough to reduce speed as you bounce, since it seems to stop just ever-so-slightly the direction towards an axis and a little upwards?

Here's a demonstration anyways:
[Minecraft_ 1.18.1 - Singleplayer 2022-05-20 17-40-36.zip](https://github.com/SlimeKnights/TinkersConstruct/files/8744729/Minecraft_.1.18.1.-.Singleplayer.2022-05-20.17-40-36.zip)

I just realized it's more of a vertical boost rather than any other direction, because i do get sent slightly upwards in the video all the time, unless it's a client error.
You can also see the bouncing around when I get stopped by a wall.

I hope this helps.

**Comment by KnightMiner** [comment]
Bouncing off walls is a new feature as a sideeffect of preserving speed instead of the weird velocity thing we had before, I quite like it hence it being treated as a feature.

As for the actual bouncing, if I understand this right you do not hold forward while bouncing? Try doing so, that has always been the standard way to use boots in my understanding. I can look into that a bit more as it does seem you don't bounce far enough based on your initial speed, but thats not related to the speed conservation code, that looks like you just lose velocity as you land.

**Comment by AzazelFTL** [comment]
I see, that's cool

That is incorrect though, I'm holding forward, but I do bounce less far as it used to, and it's hard to gain speed in tight places.
I'm not sure if _that_ is intentional, but, I would appreciate considering one of my requests even though I it's an issue.
I was thinking about it and, what if the bouncing had an initial boosted diagonal bouncing, rather than reflecting just the speed? Or perhaps there could be a way to separate between swimming and bouncing with the boots, so it doesn't get soft-nerfed.

**Comment by KnightMiner** [comment]
No, swimming is not the problem. Swimming simply showed the problem existed. Multiplying your speed every tick when it changes is super unstable code. Unstable code will cause more bugs later. I decided to use stable code.

And honestly, is it such a big deal if the boots are slightly nerfed by that? The boots were absolutely OP in 1.12.

**Comment by AzazelFTL** [comment]
It's true, and I guess it was worth mentioning since it's one of the coolest mechanics I've seen and It's kind of a shame it's not as before, though it's fairly nerfed. You could maybe add a way to boost the sling to counter act the boot problem, seems to be the best idea, maybe an enchantment or another version of every sling.

**Comment by KnightMiner** [comment]
yeah, what the mod needs is 10 variants of the slimesling. Few enough people realize blue and green are different. Slings will not be made enchantable, they might be made modifiable one day but that will likely be by nerfing the slings and letting you add modifiers to get back to their current behavior 

Also, your concern is the boots do not bounce you enough, changing the sling will not change your concern at all, the boots will be just as bouncy.

As one last point, yes it was fun, but so is creative flight and creative resource duplication. Not everything that is fun makes good gameplay, the goal is for slimeboots to fit alongside other content such as transport methods, not to render them useless. Getting free fast travel for a cost of less than 20 slimeballs was excessive.

**Comment by KnightMiner** [comment]
Leave this open so I have time to investigate if the boots are in fact not bouncing enough. I think air behavior is fine but the actual bounce might need adjustment.

**Comment by KnightMiner** [comment]
3.5.1.31 adjusts slime boots behavior slightly. Boots now preserve your initial X and Z velocity from the bounce instead of just your Y velocity, seemed there was a bit of a loss by the time the actual bounce happened. Also tweaked the parameters slightly, so you bounce a bit more and a bit faster.
