### ISSUE TITLE
1.18.2 Tinkers Crashing - Tinkers' Construct (tconstruct) has failed to load correctly

### ISSUE THREAD

**Issue by ixRaiin** [SlimeKnights/TinkersConstruct#4872]
### Minecraft Version

1.18.2

### Forge Version

minecraftforge:40.1.20

### Mantle Version

Mantle-1.18.1-1.8.37.jar

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.0.17.jar

### Describe your issue

Tinkers Construct is available for 1.18.2 but it keeps failing to load 

### Crash Report

https://pastebin.com/35n16PWG

### Other mods

1). Tetra which is also crashing

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched closed issues

**Comment by KnightMiner** [comment]
Update mantle.
