### ISSUE TITLE
I dont have bauxite and ardite ores.

### ISSUE THREAD

**Issue by eyvanx** [SlimeKnights/TinkersConstruct#4873]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

no

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

Hi i play with friends in a 1.18.2 server version with Aternos.
We install Tinkers Constructor, but cant found Ardite and Bauxite ores.
Cobalt is to slow.
Some help to fix that??

### Other mods

AnimePets 4.7.0 (1.18.2).jar
awesomedungeon-2.0.8.jar
AwesomeDungeonNether-Forge-1.18.2-1.0.1.jar
AwesomeDungeonOcean-Forge-1.18.2-2.0.5.jar
Bookshelf-Forge-1.18.2-13.0.13.jar
FallingTree-1.18.2-3.5.1.jar
Goblins_Dungeons_1.0.8.jar
jei-1.18.2-9.7.0.195.jar
journeymap-1.18.2-5.8.3-forge.jar
JustEnoughAdvancements-1.18.2-3.2.0.jar
LibraryFerret-Forge-1.18.2-1.0.3.jar
LibX-1.18.2-3.2.17.jar
Mantle-1.18.2-1.9.20.jar
Quick Harvest-1.18.2-1.6.1.jar
RottenLeather-1.18.2-1.3.jar
TConstruct-1.18.2-3.5.0.17.jar
u_team_core-1.18.2-4.0.0.204.jar
useful_backpacks-1.18.2-1.12.1.93.jar

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Checked the FAQ

**Comment by KnightMiner** [comment]
That is because we don't add bauxite or ardite ores. Ardite was removed in 1.16, and bauxite never existed in the mod. Go install a mod with bauxite if you want bauxite.

**Comment by eyvanx** [comment]
> That is because we don't add bauxite or ardite ores. Ardite was removed in 1.16, and bauxite never existed in the mod. Go install a mod with bauxite if you want bauxite.

ty ill instal Thermal Foundition , i think that have the solution !
