### ISSUE TITLE
Slimelytra implement Curios API

### ISSUE THREAD

**Issue by Raidobw2** [SlimeKnights/TinkersConstruct#4878]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

Mantle-1.18.2-1.9.20.jar

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.0.17.jar

### Problem description

The Slimelytra uses the chestplate slot, but in most modpacks you can put the Minecraft Elytra in the "Back" slot, which render the Slimelytra less useful than the normal elytra in my opinion

### Suggested solution

I'd like to suggest to implement the Caelus/Curios API to enable the Slimelytra to be put in the Back slot
https://www.curseforge.com/minecraft/mc-mods/curious-elytra
![image](https://user-images.githubusercontent.com/17010632/169894898-8d3a0d9e-d003-4d60-8b27-0b4e58d26d76.png)

### Alternatives considered

Putting the Slimelytra in the chestplate slot, which currently works

### Additional context

N/A

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by aethaerya** [comment]
I feel you'd have more luck suggesting this to C4, the dev of Curios, Caelus, and Curious Elytra.

**Comment by Raidobw2** [comment]
Thanks, this was suggested to them at https://github.com/TheIllusiveC4/CuriousElytra/issues/43 as well yes!

**Comment by KnightMiner** [comment]
Nope, not adding. That entirely defeats the purpose of the tradeoff between the slimelytra and the plate chestplate. The entirely point of slime armor is you more mobility at the cost of less armor. If I ditch the less armor cost, its a pure upgrade with no downside which is just bad design. If you must have both armor and an elytra, use the vanilla one, 50% of my modifiers would not even work in a curio slot

As an aside, I really dislike putting the elytra in its own slot in general, I would much rather support armored elytra approaches.

**Comment by Raidobw2** [comment]
Thanks for the answer! No worries, I had not checked if the Slimelytra had the possibility of armor -- I had been told by a colleague that it did not. Upon checking on it, it looks like it behaves like other accessories with upgrade slots, meaning it's effectively an armoreable elytra. Your explanation makes a lot of sense. Thanks for your time and have a good day!
