### ISSUE TITLE
Tool parts missing

### ISSUE THREAD

**Issue by nothendev** [SlimeKnights/TinkersConstruct#4879]
### Minecraft Version

1.16.5

### Forge Version

36.2.33-0a4760e0

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

I've set up a dedicated server, with Magma 1.16.5, and when I check the creative tab (and REI tool parts too), there are no tool parts! it is just empty. In singleplayer it works perfectly.
And also I have these plugins: [CMI, CMILib, DeadlyDisasters].

### Other mods

Rubidium, REI, BiomesYoullGo, Mekanism, TConstruct, Mantle, Create (and Flywheel), RefinedStorage

### Tried reproducing with just Tinkers?

Yes, issues didn't happen

### Performance Enchancers

Other (specify under other mods)
Rubidium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ChiefArug** [comment]
Alternative forge servers like magma, cauldron, mohist, sponge ect are all known to be quite buggy with mods, you should see if it happens in just a regular forge server.

**Comment by nothendev** [comment]
In a forge server everything works fine.
I'm gonna try with Mohist

**Comment by nothendev** [comment]
YESSSSSSSS IT WORKS!!!
Don't use Magma with Tinkers' Construct, it breaks something; use Mohist!
