### ISSUE TITLE
Visual/audial indicator for casting devices slots being swapped by redstone

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4880]
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.18.1-1.8.31

### Tinkers' Construct Version

1.18.1-3.4.1.46

### Problem description

When automating casting many people run redstone around tables/basins to get to the faucet that feeds into it, then get confused as to why the cast is being pulled out, not realising the feature of casting tables responding to redstone to swap its inventory around a bit.

### Suggested solution

A small sound, like a click, whenever a casting table gets triggered by redstone. A visual indicator of which item is currently in the 'input' slot and which is in the 'output' slot would also be good, although I cannot think of a good way to do that, given the two items occupy exactly the same space. (maybe have the output one sit a pixel lower than the input one?)

### Alternatives considered

Particle effects when it swaps (could be confusing for some people)
Giving them a gui 😆 

### Additional context

![image](https://user-images.githubusercontent.com/73862885/170455536-8d1b4925-016f-4efd-803e-1a5514633a37.png)
Example of a setup to power the faucets which also happens to power the tables because the block next to them is powered.
Credit to Bobby Aditya on the SlimeKnights Discord.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Not convinced a click will be less confusing than what we have now, what is to say the click means the slots are swapped? Plus, the swap happens at the end of casting, so the proposed click will happen at the same time as the casting table plays the cool sound (meaning sound overlap).

I agree it can be confusing for new players who don't read the books (they should honestly read the books), but not convinced this is the best way to tell them what is going on.

**Comment by KnightMiner** [comment]
I added a click sound to in 3.4.2.40, honestly should have a model difference between the two tables but for now I'll call it resolved
