### ISSUE TITLE
Seared bricks look very similar to netherite ingots

### ISSUE THREAD

**Issue by Keltas** [SlimeKnights/TinkersConstruct#4883]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

1.18.2-1.9.20

### Tinkers' Construct Version

1.18.2-3.5.0.17

### Problem description

Seared bricks look extremely similar to netherite ingots. You can recognise them side by side, as netherite is a bit brighter and smaller, however I struggle to recognise them on their own without hovering over to check the name. In fact if you were to rename the bricks as netherite ingots I am quite confident you could prank someone with fake netherite ingots if they don't have any.

### Suggested solution

Change the seared brick texture so it is a bit more distinct.

### Alternatives considered

Perhaps change the outline color of seared bricks to be brighter as that would make it quite distinct.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Seared bricks are twice as thick as netherite. 
I see no reason you would assume an ingot twice as thick as regular is netherite The two are quite obviously different as seared bricks look different from every single other ingot. Give me a side by side screenshot of the two if you think I'm wrong.

We already fixed this at the beginning of 1.16.5, only reason you'd still be confused is if you use a resource pack
