### ISSUE TITLE
Ichor Crystals and Blocks

### ISSUE THREAD

**Issue by hrc2021** [SlimeKnights/TinkersConstruct#4884]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.18

### Describe your issue

Currently you can turn ichor crystals into ichor crystal blocks, but you cannot turn blocks back to crystals in any way. Recommend a process similar to amethyst requiring to melt it down and cast in gem cast.

### Other mods

Direwolf20 1.18

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
You cannot turn skyslime crystal blocks into skyslime crystals, or earthslime crystal blocks into earthslime crystals, or enderslime into enderslime crystals. Honestly I should disable the recipe letting you cast amethyst crystals as its inconsistent with how vanilla balances them. The blocks are easy to obtain in mass, the crystals require you to wait a bit, they are not equivelent.
