### ISSUE TITLE
Shovels?

### ISSUE THREAD

**Issue by lxlvp** [SlimeKnights/TinkersConstruct#4885]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.6.157

### Tinkers' Construct Version

1.6.157

### Describe your issue

Sorry, I've looked through the FAQ and roadmap more times than I can count, but I didn't see anything on shovels. For me, I noticed they were missing from my game completely. There is no pattern or shovelheads at all, even in JEI. Is this on purpose? Again, sorry if i missed it in the forums -_-'
I looked in the config too, but couldn't find anything about shovels
![2022-05-27_21 50 23](https://user-images.githubusercontent.com/106416397/170807021-dc812300-9209-4482-8d60-507dbc059b5b.png)

![2022-05-27_21 50 32](https://user-images.githubusercontent.com/106416397/170807018-564eeb0d-de5e-4fa0-8c6b-131b2523d312.png)

### Other mods

adv chimneys
alexs mobs
aquaculture
astikor carts
biomes o plenty
bountiful baubles
craftable horse armor
clumps
cold sweat
comforts
create
doggy talents
exotic birds
farmers delight
genetic animals
immersive cooking
macaw bridges, windows etc
mekanism
MCA reborn
quark
rats
supplementaries

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by aethaerya** [comment]
Mattocks!

**Comment by KnightMiner** [comment]
[you did not look at the FAQ that hard](https://github.com/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-FAQ#where-did-shovels-go). All you had to do was read the table of contents to find that.

**Comment by vovchisko** [comment]
😢 why?

**Comment by KnightMiner** [comment]
I already answered why above in the FAQ post. If you bothered to read it, you would know the answer.
