### ISSUE TITLE
config common has some typos/ardite confusion

### ISSUE THREAD

**Issue by ryanmattt** [SlimeKnights/TinkersConstruct#4887]
### Minecraft Version

1.18.2

### Forge Version

40.1.25

### Mantle Version

1.18.2-1.9.20

### Tinkers' Construct Version

1.18.2-3.5.0.17

### Describe your issue

There's inconsistent periods in the common config and I'm honestly not sure if this is an issue but the word _slimealls_ is on line 27 don't know if that's meant to be slimeballs or not.

Also the ardite bucket still exists?
[src/main/resources/assets/tconstruct/models/item/molten_ardite_bucket.json](https://github.com/SlimeKnights/TinkersConstruct/blob/40a668af4d0596fd4700785dc01c5cf1a17848d4/src/main/resources/assets/tconstruct/models/item/molten_ardite_bucket.json)

### Crash Report

N/A

### Other mods

N/A

### Tried reproducing with just Tinkers?

N/A

### Performance Enchancers

N/A

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
An extra JSON file does not matter. 

I'll leave this open for the minor config typo. The inconsistent periods does not matter as well, its a config file, not an academic paper.

**Comment by KnightMiner** [comment]
The really minor config typo was fixed in 3.5.1.31.
