### ISSUE TITLE
pickadze modifier textures are not appropriate

### ISSUE THREAD

**Issue by Simon-LYL** [SlimeKnights/TinkersConstruct#4888]
### Minecraft Version

1.18.2

### Forge Version

40.1.125

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

Netherite, silky modifier textures are wrong.
![pickadze modifier texture](https://user-images.githubusercontent.com/106414652/171604973-11417713-d55f-42c9-aa4b-07b1a603afd9.JPG)

### Other mods

/

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by Simon-LYL** [comment]
It seems lto be mattock's

**Comment by Simon-LYL** [comment]
It seems to be mattock's modifier texture.

**Comment by KnightMiner** [comment]
Yes, modifier textures are not done. Been true for awhile. They will be finished when they are finished.

Closing as I have a place to track modifier textures elsewhere.
