### ISSUE TITLE
Smeltery not showing detection of Blaze Blood

### ISSUE THREAD

**Issue by FooterManDev** [SlimeKnights/TinkersConstruct#4889]
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

Seen on version 1.2.1 of Enigmatica 6:

On servers, it appears the Smeltery does not like to display detection of Blaze Blood in the UI, only Lava, this has been a thing for quite a few months now and hasn't been reported to my knowledge, so I went ahead and made an issue for you guys here. I'll try to get a screenshot of the issue as soon as possible as I don't have one currently.

### Other mods

Enigmatica 6 1.2.1 base mods.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
A couple of things

Try to reproduce with just tinkers

Is there only blazing blood in the smeltery? If not it doesn't auto switch fluids. You can't have both a lava and blazing blood tank and expect them to switch automagically

**Comment by FooterManDev** [comment]
Only Blaze, I'll test with just tinkers later

**Comment by KnightMiner** [comment]
When you melt items, you get a small buffer of about 50mb, which then sets that fuel as the "preferred fuel" until its used up. You might need to try smelting an item after you switched fuel so the smeltery actually switches.

**Comment by KnightMiner** [comment]
Closing for lack of response. Reproduce with minimal mods if you want to reopen.
