### ISSUE TITLE
Scorching and Cooling do many times more damage than they say they do.

### ISSUE THREAD

**Issue by weirdo001** [SlimeKnights/TinkersConstruct#4890]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

The scorching and cooling traits appear to be far more powerful than they say they should be. For example, a cleaver made completely out of scorched brick with an emerald on says it does 15 bonus damage to burning enemies. However, when I tested it on a target dummy from the MmmMmmMmmMmm mod that was decked out in full netherite armor, after lighting it on fire, the cleaver did 71.94 damage without crit. On a crit, it did 107.9. I don't know how to make a target dummy immune to fire, but I tested a cooling V rose gold cleaver with emerald on a wither skeleton with 100 health and it instantly killed it on a crit. I am sure that this is not simply the base damage of the cleaver, as when I hit the dummy without fulfilling the conditional damage requirements, both cleavers did less than 3 damage. The only tests I have done were using cleavers, no other weapons. If this amount of damage is intentional, then I seriously suggest lowering it, as this is way overpowered.

### Other mods

- Optifine
- MmmMmmMmmMmm (target dummy mod)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Already fixed by 74ec777. Will be in the next release, just need to get some language fixes.

Guess it was reported on discord as I do not see a ticket, reminder to discord people to make bug reports like this one.

**Comment by KnightMiner** [comment]
Fixed in 3.5.1.31
