### ISSUE TITLE
No Fuel Found

### ISSUE THREAD

**Issue by ecksfiftyone** [SlimeKnights/TinkersConstruct#4892]
### Minecraft Version

1.18.2

### Forge Version

40.1.25

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

I'm hoping I'm not just being stupid, but the smeltery is not detecting any fuel. 
I have been using Tinkers for ages. It's been a year or more since I last used it, so maybe there have been changes...? 

I have built a smeltery.
I have placed the smeltery controller.
I have placed the Seared fuel tank. 
I have filled the tank with lava. 

The smeltery appears to be built properly, as the controller and drains have changed to graphics indicating it's correct. 
I have tried placing the tank above and at the same level as the controller. 

I have also tried with a gauge instead. 
![2022-06-03_11 05 49](https://user-images.githubusercontent.com/17909212/171884335-ce93c434-2daa-4f09-b70a-a5b6588399be.png)
![2022-06-03_11 05 24](https://user-images.githubusercontent.com/17909212/171884341-c420d6a6-a8ee-40a2-af51-c6e02ca77ed5.png)
![2022-06-03_11 05 29](https://user-images.githubusercontent.com/17909212/171884342-ccd87154-f149-4273-8dc7-2fcda7d65058.png)
<img width="444" alt="2022-06-03_Mod_List" src="https://user-images.githubusercontent.com/17909212/171884345-65fe84ae-979e-429c-a742-e1d5cc3a06c6.png">

### Other mods

advanced-xray-forge-1.18.2-2.11.0-build.7.jar                         
alexsmobs-1.18.3.jar                                                  
architectury-4.4.68.jar                                               
armorplus-1.18.2-18.0.5-beta.jar                                      
badpackets-forge-0.1.2.jar                                            
betteranimalsplus-1.18.2-11.0.5-forge.jar                             
Bookshelf-Forge-1.18.2-13.0.13.jar                                    
carryon-1.18.2-1.17.0.8.jar                                           
cfm-7.0.0-pre29-1.18.2.jar                                            
citadel-1.11.3-1.18.2.jar                                             
CraftTweaker-forge-1.18.2-9.1.144.jar                                 
FastLeafDecay-28.jar                                                  
forge-1.18.2-40.1.25-installer.jar                                    
forgeautofish-4.1.0-1.18.2.jar                                        
geckolib-1.18-forge-3.0.12.jar                                        
gravestone-1.18.2-1.0.2.jar                                           
jei-1.18.2-9.7.0.195.jar                                              
journeymap-1.18.2-5.8.4-forge.jar                                     
JustEnoughResources-1.18.2-0.14.1.160.jar                             
Mantle-1.18.2-1.9.20.jar                                              
Mekanism-1.18.2-10.2.2.462.jar                                        
MekanismGenerators-1.18.2-10.2.2.462.jar                              
MekanismTools-1.18.2-10.2.2.462.jar                                   
MyBrightness-1.18-01.jar                                              
Patchouli-1.18.2-67.jar                                               
SoL-Carrot-1.18.1-1.12.0.jar                                          
StorageDrawers-1.18.2-10.2.1.jar                                      
TConstruct-1.18.2-3.5.0.17.jar                                        
thedragonlib-1.18.1-1.0.0.jar                                         
theoneprobe-1.18-5.1.0.jar                                            
TrampleStopper-3.1.0-build.27+mc1.18.2.jar                            
useful_backpacks-1.18.2-1.12.1.93.jar                                 
u_team_core-1.18.2-4.0.1.210.jar                                      
wthit-forge-4.10.3.jar    

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by ShinyPorygon** [comment]
Try placing an actual meltable item in. You can no longer melt cobble for seared stone.

**Comment by ecksfiftyone** [comment]
Doh!  So yeah, actual smeltable items do indeed work, however the controller still says "No Fuel Found" even though the items seem to melt properly. 

(I think) I'm used to this gauge being full in the controller with the fuel type displayed. 

Is this still a bug?

**Comment by ShinyPorygon** [comment]
Reproduce with just tinkers (especially without optifine)

**Comment by KnightMiner** [comment]
Closing for lack of response.
