### ISSUE TITLE
Can't use Flint and Brick to lit up Ominous Banners with Savage and Ravage

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4893]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

With Savage and Ravage you can lit up Ominous Banners but Flint and Brick doesn't work on it.

Also reported to Savage and Ravage: https://github.com/team-abnormals/savage-and-ravage/issues/103

### Other mods

Blueprint: 5.3.2
Savage and Ravage: 4.0.0

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Basically any time a sentence starts with "can't use flint and brick to ___" its a bug that the other mod has to fix.

The last mod asking for compat suggested a tool action `light_campfires`, seen [here](https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/main/java/slimeknights/tconstruct/tools/modifiers/ability/interaction/FirestarterModifier.java#L420). Could come up with a generic light fires tool action, or reuse that action, or come up with one specific to the other mod.

**Comment by KnightMiner** [comment]
Marking this resolved as I have done everything I can on my side. Up to Savage and Ravage to do the rest.

**Comment by KnightMiner** [comment]
I added a tool action in 3.6.0.73, going to close this as its up to that mod to support
