### ISSUE TITLE
Wrong sort of Flint and bronze in Mighty Smelting

### ISSUE THREAD

**Issue by obscure-man** [SlimeKnights/TinkersConstruct#4894]
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

Flint and bronze is sorted to Broad Tools in Mighty Smelting, but it's sorted to Small Tools in Encyclopedia of Tinkering.

### Other mods

Cloth Config v4 API
IngameIME
Just Enough Items
Kotlin for Forge
Mantle
Patchouli
Psi
RpmtwUpdateMod
Tinkers' Construct

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Flint and bronze requires alloys to craft making it post smeltery, thus being in mighty smelting. It 8a not a large tool, so the encyclopedia that can sort based on categories rather than progression put it in the more logical place .

It has aore early game recipe in 1.18, I suggest updating.
