### ISSUE TITLE
Saturation values of fluids don't match vanilla values

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4895]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

Reporting the same I wrote on Discord

Vanilla rabbit stew gives 10 hunger and 12 saturation.
Full Molten rabbit stew gives 10 hunger and 50 saturation
You divided 12 by 5 which is 2.4, correct in the data, but the calculation for saturation is actually saturation_multiplier * 2 * hunger, which in vanilla is 0.6 * 2 * 10 = 12 with full soup, where in tconstruct is 2.4 * 2 * 2 = 9.6 per 50mb = 48 with full soup.
I think the same thing applies to other soups 
Yep, less op but the same applies to other soups (Mushroom is 15 total saturation vs 7.2 vanilla

A simple fix would be to set the saturation of spilling effects be the same as this table: https://minecraft.fandom.com/wiki/Food#Foods divided by 2 (same as vanilla multiplier)

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Resolved by 24657b8

**Comment by KnightMiner** [comment]
Fixed in 3.5.1.31
