### ISSUE TITLE
Blaze heads / Blazing blood in peaceful

### ISSUE THREAD

**Issue by Neurosis404** [SlimeKnights/TinkersConstruct#4896]
### Minecraft Version

1.18.2

### Forge Version

40.1.16

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Problem description

When playing on peaceful, there is no way to obtain blaze heads, which makes it impossible to obtain blazing blood for top tier material. There is 3rd party mod that enables a recipe for blaze heads, but only for 1.16.

### Suggested solution

Probably the easiest solution: It would be nice to add the possibility to disable the blazing blood in config file, so that every material can be smelted and alloyed with lava (1000° instead of 1250°/1500°)

### Alternatives considered

Craftable blazing skulls

### Searched for existing enhancement?

Used the search bar

**Comment by KnightMiner** [comment]
Barter with piglins. This is covered by Fantastic Foundry.

As for "disable in the config file", that is also an option via datapacks. You can change every single recipe, including fuel requirements.

----

As an aside, blaze heads is a really inefficient way to get blazing blood. Melting blazes via a smeltery or the modifier is far better.
