### ISSUE TITLE
Books can't be placed into the Akashic Tome

### ISSUE THREAD

**Issue by vizthex123** [SlimeKnights/TinkersConstruct#4901]
### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

As the title says, you can't put the books into the Akashic Tome

### Other mods

Akashic tome

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by KnightMiner** [comment]
Our books are nothing special. They are items, and they are properly tagged as [forge:books/guide](https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/generated/resources/data/forge/tags/items/books/guide.json). If Akashic Tome is still not using tags and its 1.18, then they are a broken mod. Report this bug to Akashic Tome, they are probably still hardcoding that books have `book` in the registry ID, which is a terrible, terrible practice and should have stopped when tags were added.

See also VazkiiMods/AkashicTome#68

**Comment by vizthex123** [comment]
Alright then, will do.
