### ISSUE TITLE
Weird tinkers conflict on startup (Invokation Target Exception)

### ISSUE THREAD

**Issue by halvalla01** [SlimeKnights/TinkersConstruct#4902]
### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

Conflict on startup, won't launch game. See log file link for details

### Crash Report

https://drive.google.com/file/d/1VbVJFYJZseiRU-xO4F6zAAgSb7tEslVo/view?usp=sharing

### Other mods

I have tested using only tinkers, same error occurs

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked the FAQ

**Comment by ShinyPorygon** [comment]
Mod File: TConstruct-1.18.1-3.4.2.60.jar
You have 1.18.1 tinkers, you need 1.18.2
