### ISSUE TITLE
Sever startup issue

### ISSUE THREAD

**Issue by xmsteele23** [SlimeKnights/TinkersConstruct#4903]
### Minecraft Version

1.18.2

### Forge Version

forge-1.18.2-40.1.31

### Mantle Version

Mantle-1.18.2-1.9.20

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.0.17

### Describe your issue

Crash on startup[https://gist.github.com/xmsteele23/2eb46ef653607580e6ce7c77dbfdddb9](url) this is the debug log

### Crash Report

https://pastebin.com/2UXwkqE1

### Other mods

connectivity, fps reducer, ferrite core, lazy DFU, ksyxis, fast bench and furnace

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, I did not search

**Comment by ShinyPorygon** [comment]
Step 1: reinstall the mod on both server and client. 
Step 2: remove all performance mods if it still doesn't work

**Comment by KnightMiner** [comment]
Closing for lack of response
