### ISSUE TITLE
Issue with crafting the Smeltery

### ISSUE THREAD

**Issue by TubbyBakedCakes** [SlimeKnights/TinkersConstruct#4905]
### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Mantle Version

Not sure what this means

### Tinkers' Construct Version

Tconstruck-1.18.2-3.5.0.17.jar

### Describe your issue

So friends of mine have started a server using All the Mods 7 through curseforge and Ive been playing around with the new version of Tinkers and I cant get the molten copper to pour over the heater. Nothing I try works and I dont know how to fix the issue so I am hoping someone here can help.

### Other mods

modpack is All the Mods 7

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Checked the FAQ

**Comment by ChiefArug** [comment]
Pour molten copper over a seared brick block, the books are outdated. (JEI has the correct recipe though)
