### ISSUE TITLE
Soulbound items despawn upon death when twilight forest mod is included

### ISSUE THREAD

**Issue by Gemedet03** [SlimeKnights/TinkersConstruct#4906]
### Minecraft Version

1.18.2

### Forge Version

40.1.22

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

Soulbound upgrade causes items to despawn upon death when twilight forest is included.

This was tested with only Twlight Forest 4.1.1096, Tinker's Construct 3.5.0.17, and Mantle 1.9.20 installed.
(It only occurs when the player is in survival. When in creative mod, soulbound seems to work fine)

This only happens when Twilight Forest is installed in addition to Tinkers construct so it may be related to the Charm of Keeping. The player does not need to be holding a charm of keeping for soulbound items to despawn upon player death.

### Other mods

Twlight Forest 4.1.1096

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Relevant code for soul bound: https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/main/java/slimeknights/tconstruct/tools/modifiers/upgrades/general/SoulboundModifier.java

**Comment by KnightMiner** [comment]
Fixed in the latest Twilight Forest release
