### ISSUE TITLE
Crash due to Spilling Upgrade

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [SlimeKnights/TinkersConstruct#4907]
### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.18

### Describe your issue

Server crashed when player was attacked while wearing Traveler's Leggings with Spilling upgrade filled with milk. You will find the server crash log linked below.

### Crash Report

https://pastebin.com/MSdKvV8s

### Other mods

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/lapis/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/lapis/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

YUNG's   Better Dungeons | 1.18.2-Forge-2.1.0
-- | --
SuperMartijn642's Config   Lib | 1.0.9
PAUCAL | 0.4.5
Simple Magnets | 1.1.7
IntegratedTerminals | 1.2.16
Better Amethyst | 1.0.1
Just Another Void Dim | 3.0.0-build.54+mc1.1
Bamboo Everything | 1.2.7-build.14+mc1.1
Mod Name Tooltip | 1.18.0
Neat | 1.8-30
LaserIO | 1.1.1
YUNG's API | 1.18.2-Forge-2.0.8
Ranged Pumps | 0.9.2
Shrink | 1.3.3
Secret Rooms 6 | 1.18.2-1.1.5
Mute | 1.0.0-build.2+mc1.18
DarkUtilities | 10.0.4
Balm | 3.0.3+0
Tool Kit | 2.2.1-build.4+mc1.18
Cloth Config v4 API | 6.2.62
WhyYouMakeLag | 1.1.3a
ShetiPhian-Core | 3.10.9
Emojiful | 1.18.2-3.0.1
TKLib | 0.0.23
Refined Storage | 1.10.2
Torchmaster | 18.1.0
TipTheScales | 5.0.6
Better Compatibility   Checker | 1.1.14-build.26+mc1.
SuperMartijn642's Core   Lib | 1.0.18
Botania | 1.18.2-433
KubeJS Thermal | 1802.1.5-build.previ
Enchantment Transfer | 0.0.4
spark | 1.9.1
Curios API | 1.18.2-5.0.7.0
Advanced Netherite | 1.12.3
Angel Ring | 1.5.0
Nature's Aura | 36.2
Construction Wand | 1.18.2-2.7
Macaw's Roofs | 2.1.2
Little Logistics | 1.2.5
Cobble For Days | 1.5.1
FastLeafDecay | 28
YUNG's Better Mineshafts | 1.18.2-Forge-2.1.3
GeckoLib | 3.0.21
Super Factory Manager | 4.1.1
Fallingthrough mod | 1.18.2-2.4
Netherite Elytra | 1.1.0-1.18.1-curios
Just Enough Items | 9.7.0.195
AttributeFix | 14.0.2
Tesseract | 1.0.26
Mekanism | 10.2.2
Luggage | 1.3.1
Caelus API | 1.18.1-3.0.0.2
Nature's Compass | 1.18.2-1.9.5-forge
Jumpy Boats | 1.18.2-0.1.0.3
LibX | 1.18.2-3.2.15
Compact Machines 4 | 4.3.0
Champions | 1.18.2-2.1.5.4
Curio of Undying | 1.18-5.3.0.0
PneumaticCraft:   Repressurized | 1.18.2-3.2.4-93
Catalogue | 1.6.2
Oreberries Replanted | 0.1.7
Chalk | 1.2.1
Iron Chests | 1.18.2-13.1.9
MythicBotany | 1.18.2-2.1.7
IntegratedCrafting | 1.0.23
Zero CORE 2 | 1.18.2-2.1.17
Minecraft | 1.18.2
Flopper | 1.1.2
The One Probe | 1.18-5.1.0
Applied Energistics 2 | 11.1.1
AEInfinityBooster | 1.18.2-1.1.0+9
Immersive Engineering | 1.18.2-8.0.1-147
Ceiling Torch | 1.18
Sushi Go Crafting | 0.3.4
Domum Ornamentum | 1.18.2-1.0.50-ALPHA
Mysterious Mountain Lib | 1.0.2-1.18.2
Pipez | 1.18.2-1.1.5
Flywheel | 1.18-0.6.2
Create: Alloyed | 1.18.2
Mantle | 1.9.20
IntegratedDynamics | 1.11.0
Item Collectors | 1.1.5
Gravestone Mod | 1.18.2-1.0.2
ServerConfig Updater | 2
Polymorph | 1.18.2-0.44
AutoRegLib | 1.7-53
Structurize | 1.18.2-1.0.411-ALPHA
portabletanks | 1.1.4
Lootr | 0.2.17.54
Connected Glass | 1.1.3a
Rain Shield | 1.0.0
Puzzles Lib | 3.3.5
Extreme Sound Muffler | 3.27_forge-1.18.1
CosmeticArmorReworked | 1.18.2-v2
Ender Mail | 1.18.2-1.2.4
XP Tome | 2.1.5
RSRequestify | 2.2.0
Cyclops Core | 1.14.0
Super Circuit Maker | 0.2.9
NetherPortalFix | 9.0.0
Advanced Peripherals | 0.7.15b
Curious Shulker Boxes | 1.18.1-4.2.0.0
Pocket Storage | 1.18.2-1.0.1-build.1
Connectivity Mod | 1.18.2-2.9
Incendium | 0.0NONE
Sophisticated Core | 1.18.2-0.2.8.35
InsaneLib | 1.4.8
Glassential | 1.18.2-1.2.3
CookingForBlockheads | 12.0.1
Jump Over Fences | 1.18-1.0.1
Feature NBT Deadlock Be   Gone | 2.0.0+1.18.2
Culinary Construct | 1.18.2-4.3.1.0
Bookshelf | 13.0.13
Sophisticated Backpacks | 1.18.2-3.17.2.588
Little Contraptions | 1.18.2.0
Building Gadgets | 3.13.0-build.5+mc1.1
FramedBlocks | 5.2.1
Forge | 40.1.47
Right Click, Get Crops | 1.2.1.5
CoFH Core | 1.6.3.19
Thermal Series | 1.6.2.27
Thermal Innovation | 1.6.1.10
Thermal Locomotion | 1.6.0.6
Thermal Cultivation | 1.6.1.9
AppleSkin | 2.4.0+mc1.18
Simple Planes | 1.18.2-4.13.3
Progressive Bosses | 3.5.11
Mekanism: Generators | 10.2.2
Carry On | 1.17.0.8
No Night Vision Flashing | 1.4.0.2
Mob Grinding Utils | 1.18.2-0.4.39
Create Cafe | 1.4-1.18.2
Air Hop | 3.2.0
Just Another Mining   Dimension | 1.7.0-build.25+mc1.1
Farmer's Delight | 1.18.2-1.1.1
Corn Delight | 1.0.4-1.18.2
Honey expansion | 1.1.1
Farmer's Respite | 1.18.1-1.2.0
RebornStorage | 4.0.10
It Shall Not Tick | 1.0.20-build.21
Customizable Elytra | 1.18.2-1.6.5
Entangled | 1.3.11
EnderTanks | 1.11.6
CommonCapabilities | 2.8.2
Crash Utilities | 4.1
Macaw's Fences and Walls | 1.0.5
Wireless Chargers | 1.0.6
Simply Light | 1.18.2-1.4.2-build.3
Simply Backpacks | 1.18.2-2.1.1-build.3
DataPack Anvil | 1.18.2-3.4.0c
Patchouli | 0.0NONE
Ars Nouveau | 2.5.0
UI Library Mod | 1.18.2-0.0.48-ALPHA
Multi-Piston | 1.18.2-1.2.7-ALPHA
More Charcoal | 1.18.2-1
Spyglass Improvements | 1.2+mc1.18.x
OreExcavation | 1.10.161
Time In A Bottle | 2.1.0-mc1.18.1
Thermal Expansion | 1.6.1.11
IntegratedTunnels | 1.8.11
Elevator Mod | 1.18.2-1.8.4
YUNG's Better Strongholds | 1.18.2-Forge-2.1.1
Runelic | 11.0.1
Mekanism: Tools | 10.2.2
Architectury | 4.4.68
FTB Library | 1802.3.6-build.119
FTB Industrial   Contraptions | 1802.1.5-build.144
Myrtrees | 1.1.0-build.29
FTB Auxilium | 1802.1.7-build.31
FTB Teams | 1802.2.6-build.51
FTB Ranks | 1802.1.8-build.34
FTB Essentials | 1802.1.7-build.42
Curious Elytra | 1.18.1-5.0.1.0
CC: Tweaked | 1.100.5
AI-Improvements | 0.5.0
Extreme Reactors | 1.18.2-2.0.44
Trash Cans | 1.0.15
Enchant With Mob | 1.18.2-4.2.0
PolyLib | 1801.0.2-build.13
BlockShot | 1.2.6
Void Totem | 1.18.2-1.3.1
Simple Inventory Sorter | 19.0.0
Rhino | 1802.1.13-build.175
Cucumber Library | 5.1.1
AE2WTLib | 11.0.1
Flat Bedrock | 1.4.2-build.10+mc1.1
Sophisticated Storage | 1.18.2-0.1.1.35
Snad | 1.18.2-1.22.04.15a
ElementalCraft | 1.18.2-4.4.4
Scannable | 1.7.6
Ensorcellation | 1.6.0.7
Create | 0.4.1
Create Deco | 1.2.7-1.18.2
Waystones | 10.0.0
Golden Hopper | 1.2.6
Clumps | 8.0.0+8
Journeymap | 5.8.5
Nasty Mobs | 1.0.0.9
Comforts | 1.18.2-5.0.0.4
Configured | 1.5.3
Charging Gadgets | 1.7.0
FTB Backups 2 | 1.0.10
Create Confectionery | 1.0.8
Travel Anchors | 1.18.2-3.3
McJtyLib | 1.18-6.0.14
RFToolsBase | 1.18-3.0.8
XNet | 1.18-4.0.5
RFToolsDimensions | 1.18-8.0.6
RFToolsPower | 1.18-4.0.5
RFToolsBuilder | 1.18-4.0.12
DeepResonance | 3.0.6
RFToolsStorage | 1.18-3.0.8
RFToolsControl | 1.18-5.0.6
Mahou Tsukai | 1.18.2-v1.34.16
Farsight mod | 1.18.2-1.9
Terralith | 0.0NONE
Mining Gadgets | 1.11.0
Hex Casting | 0.8.3
Akashic Tome | 1.5-20
FTB Chunks | 1802.3.6-build.145
KubeJS | 1802.5.3-build.444
KubeJS Create | 1802.2.2-build.26
KubeJS Immersive   Engineering | 1802.2.1-build.35
KubeJS Mekanism | 1802.1.3-build.8
KubeJS UI | 1802.1.7-build.13
Mystical Agriculture | 5.1.0
Mystical Agradditions | 5.1.1
CraftingTweaks | 14.0.2
Tinkers' Construct | 3.5.0.18
KubeJS Tinkers Construct | 1802.1.0-build.1
RFToolsUtility | 1.18-4.0.16
Dynmap | 3.4-beta-3-774
Titanium | 3.5.5
Retraining | 1.1.0
Archer's Paradox | 1.6.0.5
SoulShards | 1.18.2-1.2.2
Nethers Delight | 2.2
Oh My Gourd | 1.6.0.4
Easy Villagers | 1.18.2-1.0.5
Quark | 3.2-357
brutalbosses mod | 1.18.2-4.9
PigPen | 8.0.1
EnderChests | 1.9.5
Applied Botanics | 1.0.1
MineColonies | 1.18.2-1.0.792-ALPHA
Hunter Illager | 1.18.2-4.0.1
Ferrite Core | 0.0NONE
MineTogether | 5.2.7
Functional Storage | 1.18.2-0.0.15
More Dragon Eggs | 3.1
Modular Routers | 9.1.1-93
Refined Storage Addons | 0.8.2
Applied Mekanistics | 1.2.0
Valhelsia Core | 1.18.2-0.3.1
Forbidden & Arcanus | 1.18.2-2.1.0-beta1
Chisels & bits | 1.2.90
Create Crafts &   Additions | 1.18.2-20220517a
Control Engineering | 0.1.1

</body>

</html>

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Can this be reproduced with only tinkers? You have a ton of mods there

**Comment by Insane96** [comment]
Try without (or only with) "It Shall Not Tick"

**Comment by KnightMiner** [comment]
Most likely fixed in 3.5.1.31. In the future, minimal mods means test with fewer, this just happened to be a but where it does not matter.
