### ISSUE TITLE
Bouncy ability incorrectly shown on item modifier list

### ISSUE THREAD

**Issue by snackerpirater** [SlimeKnights/TinkersConstruct#4908]
### Minecraft Version

1.18.2

### Forge Version

40.1.51

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Bouncy is shown as 'Bouncy I' despite only having one level
![2022-06-12_22 29 05](https://user-images.githubusercontent.com/107385468/173287492-fa742ec0-1f75-4823-8304-2f535153c027.png)

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.40
