### ISSUE TITLE
Blasting doesn't use modifier's scaled level

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4912]
### Minecraft Version

1.18.2

### Forge Version

40.1.51

### Mantle Version

1.9.28

### Tinkers' Construct Version

3.5.1.32

### Describe your issue

Blasting doesn't get the scaled level of the modifier.
Right now it always applies the full blasting speed (the tooltip shows the correct behaviour)

https://github.com/SlimeKnights/TinkersConstruct/blob/3.5.1.31/src/main/java/slimeknights/tconstruct/tools/modifiers/upgrades/harvest/BlastingModifier.java 

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.40
