### ISSUE TITLE
Tinkers construct heads crashing with optifine

### ISSUE THREAD

**Issue by zorex73** [SlimeKnights/TinkersConstruct#4913]
### Minecraft Version

1.18.2

### Forge Version

40.1.51

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Whenever viewing on of the custom heads Tinkers construct implements while having optifine installed, the game crashes.

### Crash Report

The game crashed whilst rendering item
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.model.SkullModelBase.m_142698_(float, float, float)" because "modelBaseIn" is null
Exit Code: -1

### Other mods

optifine

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment]
Optifine is not supported. Report to optifine devs

**Comment by zorex73** [comment]
thanks
