### ISSUE TITLE
No Tinker's equivalent to Depth Strider enchantment

### ISSUE THREAD

**Issue by eSonOfAnder** [SlimeKnights/TinkersConstruct#4914]
### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.0.18

### Describe your issue

Unsure if this is a bug/issue, or if this is actually something missing (which would make this an enhancement request rather than an issue), but looking through the in game book and doing some Googling, I cannot find any Upgrade or Ability that can be applied to the Tinker's armor that creates an effect that is the equivalent of the vanilla Depth Strider enchantment. There are multiple ways of getting an Aqua Affinity style effect either on a specific tool or on a helmet, but no Depth Strider.

Is this something I am just completely missing, or does it just not exist in the current version? I looked at the roadmap, and did not see anything there related to this either.

### Other mods

I am using the FTB Presents Direwolf20 1.18 modpack.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
See the full modifier list, which is linked from [what's new](https://github.com/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3). It is planned but not implemented.

Also see the turtle shell modifier. Its not equivalent but its similar. 

That said, there is no requirement that we reimplement every vanilla enchantment. We reimplement the ones we want to reimplement.
