### ISSUE TITLE
Saplings cannot grow below Y=0

### ISSUE THREAD

**Issue by xbxbxb123** [SlimeKnights/TinkersConstruct#4916]
### Minecraft Version

1.18.2

### Forge Version

40.1.19

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

Slime saplings (or at least Greenheart saplings) cannot grow past stage 1 while below y=0. 

### Other mods

The entire Refreshing Springs modpack. There are a lot of mods in this, I haven't tested with less, sorry.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
>  I haven't tested with less, sorry.

It will take you less than 30 minutes to do so

**Comment by xbxbxb123** [comment]
I will do this tomorrow if still needed. I wanted to submit this before I
forgot.

**Comment by ShinyPorygon** [comment]
Able to reproduce with just tinkers 3.5.1.32

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.40
