### ISSUE TITLE
Slime boots

### ISSUE THREAD

**Issue by EliasZockt** [SlimeKnights/TinkersConstruct#4918]
### Minecraft Version

1.18.2

### Forge Version

40.1.51

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

I have a problem, in this mod is a slime sling but the slime boots missing. 

### Suggested solution

is there a way to fix this?

### Alternatives considered

change mod version

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
have you tried typing "slime boots" into JEI? Also consider the bouncy modifier.

**Comment by Insane96** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-FAQ#where-did-x-go

**Comment by EliasZockt** [comment]
yes, but there are only the purple ones, I'm looking for the green ones, they jump better

**Comment by EliasZockt** [comment]
> yes, but there are only the purple ones, I'm looking for the green ones, they jump better

yes, but there are only the purple ones, I'm looking for the green ones, they jump better

**Comment by EliasZockt** [comment]
> have you tried typing "slime boots" into JEI? Also consider the bouncy modifier.

yes, but there are only the purple ones, I'm looking for the green ones, they jump better
