### ISSUE TITLE
Mini Smeltery -> Smeltery Controller Process is Bugged

### ISSUE THREAD

**Issue by kizielinski** [SlimeKnights/TinkersConstruct#4919]
### Minecraft Version

1.18.2

### Forge Version

40.1.51

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

The Mini Smeltery does not allow copper to be poured onto the Smeltery Heater and therefore the Smeltery Controller cannot be made.

### Other mods

![List of Mods](https://user-images.githubusercontent.com/42786625/174522253-15f2fe2a-13fe-4bf6-9ee7-3ca0728d1ffc.png)

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Duplicate of #4867. Update your mod and the book is corrected. Use JEI to look at recipes instead of assuming its unchanged.
