### ISSUE TITLE
Client crash with only latest Tinkers Beta 3.5.1.31 installed

### ISSUE THREAD

**Issue by archonsd** [SlimeKnights/TinkersConstruct#4921]
### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Client crashes on startup.  Does *NOT* happen with the last version. (3.5.0.17)

Happens with any version of Tinkers Reforged or without.

### Crash Report

https://pastebin.com/tNPZ95ze

### Other mods

Only Mantle-1.18.2-1.9.20 and TConstruct-1.18.2-3.5.1.31, with Forge 1.18.2-40.1.52.  No other mods are required to cause this crash.

The Crash report shows a lot of mods.  I cleared ALL the mods out but Mantle and TConstruct after getting that first crash report.  It still crashes with the exact same trace.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by alexbegt** [comment]
The version of mantle you are running is out of date for Tinkers 3.5.1.31. Update mantle to 1.9.27 and see if this resolves your issue.

**Comment by archonsd** [comment]
Will do.  Thank you for the *very* quick response.

Archon

**Comment by archonsd** [comment]
Confirmed.  Updating Mantle to 1.9.27 allowed the client to start properly.

Thank you Alex.
