### ISSUE TITLE
Unable to view crafted slimeskulls modifier recipes in JEI

### ISSUE THREAD

**Issue by luckyu19** [SlimeKnights/TinkersConstruct#4924]
### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Mantle Version

1.18.2-1.9.27

### Tinkers' Construct Version

1.18.2-3.5.1.31

### Problem description

Currently you can only view slimeskull modifier recipe if you check the modifier recipe on the blank slimeskull, instead of the crafted slimeskulls (such as creeper slimeskull).
It is a minor thing, but would be helpful/convenient if it could be redirected in a way to the list of modifier recipes.

### Suggested solution

Extend the list of modifier recipes for slimeskulls to all slimeskulls.

### Alternatives considered

None.

### Additional context

Requires Just Enough Items (JEI) [tested on 9.7.0.209].

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Works fine for me

![image](https://user-images.githubusercontent.com/12155288/188297310-d1fe1f93-1232-45dd-85e7-a317fcb244c7.png)

**Comment by luckyu19** [comment]
The crafting recipe works, but if you were to check the modifier recipes available for crafted slimeskulls, it won't pop up as easily as their traveller/plated counterparts.

**Comment by KnightMiner** [comment]
Ah, I see. That is unfortunately not cleanly fixable. Each of these shows as a separate item in JEI as otherwise the casting recipes would not work. Showing them all in the main recipe would make it difficult to see all options for helmets.

**Comment by KnightMiner** [comment]
Fixed in 3.6.0.73
