### ISSUE TITLE
Wetting Modifier Description Typo

### ISSUE THREAD

**Issue by jetpacker06** [SlimeKnights/TinkersConstruct#4925]
### Minecraft Version

1.18.2

### Forge Version

40.1.51

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

The description for the Wetting modifier has a typo: says "diiferent".

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by ShinyPorygon** [comment]
Reported on typo thread.
