### ISSUE TITLE
Bundles gets deleted when it collect the craft from a Crafting Station

### ISSUE THREAD

**Issue by StellaBiscuit** [SlimeKnights/TinkersConstruct#4926]
### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

When you right click the crafting result with a Bundle inside of a Crafting Station, it deletes the bundle and replace it with whatever was the result

Other stations seems to be fine and does not destroy the bundle

### Crash Report

Not a crash

### Other mods

No other mods were used

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
A) There is no chance this happens with just tinkers, because bundles got removed from vanilla without a datapack
B) Other mods or datapacks had to be used.
C) Bundles are an experimental feature that shouldn't really be used so I'm almost going to mark this as not a problem we can solve

**Comment by StellaBiscuit** [comment]
A) Bundle are in the game by default, they are just not in the creative inventory and need to be /give (like command block)
B) No, again, refer to A), while yes to get one you would need a datapack/mod, the issue does NOT come from one
C) Yes they are experimental, that's why it's unobtainable by default, but the problem WILL pop out once it isn't experimental anymore so why not fixing it now (since, on top of that, a bunch of mods/datapack adds a craft to the bundle WITHOUT MODIFYING IT)

**Comment by StellaBiscuit** [comment]
Oh and bonus

D) How is a datapack that only add a craft be revelant? For a mod, ok, but a datapacks cannot modify the core game that drasticly to the point of "breaking" a block

**Comment by StellaBiscuit** [comment]
(Ok so nice, got answered on Discord instead of Github and didn't see it, so now I look like a dumbass for being angry woooo)

**Comment by KnightMiner** [comment]
Fixed in 3.6.0.73
