### ISSUE TITLE
Vain Mining is kind of awkward!

### ISSUE THREAD

**Issue by f0kx** [SlimeKnights/TinkersConstruct#4927]
### Minecraft Version

1.18.1

### Forge Version

40.1.51

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

When i have Veinmining upgrade its strange that i can mine like a circle around me and not only the connected Ores or stone?

### Suggested solution

Isnt it better to have veinmine like normal veinmining is done in the past? 

### Alternatives considered

for example there a are vainmining upgrades that do like only check one block and see if there are connected ones and will destroy them. if you have an upgrade for vainming it will get bigger and check more around the one you destroy first!

### Searched for existing enhancement?

Used the search bar

**Comment by Insane96** [comment]
Vein* mining is supposed to mine a few connected blocks (in a 2 block radius iirc). It doesn't check for diagonal blocks, and that's intended behaviour

**Comment by KnightMiner** [comment]
Isn't it better to do what was done before? No. If you want what was done before, go download one of those other mods.

This is my take on vein mining, it has limited range to be consistent with other hammer types. You can increase the range with expanders.
