### ISSUE TITLE
minecraft opens but shows me error loading mods

### ISSUE THREAD

**Issue by RaggedyMan1** [SlimeKnights/TinkersConstruct#4930]
### Minecraft Version

1.18.2

### Forge Version

40.1.54

### Mantle Version

1.18.2

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

minecraft failed to load the mod when there are only [2 mods](https://gyazo.com/c7ba1fb0795fed976824033d8872660e) in the folder am i missing something stupid?

### Crash Report

---- Minecraft Crash Report ---- // Daisy, daisy...  Time: 01/07/2022, 18:11 Description: Mod loading error has occurred  java.lang.Exception: Mod Loading has failed 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.54-universal.jar%2359!/:?] {re:classloading} 	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.18.2-40.1.54-universal.jar%2359!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:555) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.54.jar%2316!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {} -- MOD tconstruct -- Details: 	Caused by 0: java.lang.reflect.InvocationTargetException 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {} 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {} 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {} 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {} 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {} 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.54.jar%2356!/:?] {} 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.54.jar%2355!/:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}  	Caused by 1: java.lang.NoClassDefFoundError: slimeknights/mantle/fluid/UnplaceableFluid 		at slimeknights.tconstruct.fluids.TinkerFluids.<clinit>(TinkerFluids.java:74) ~[TConstruct-1.18.2-3.5.1.31.jar%2353!/:1.18.2-3.5.1.31] {re:classloading,pl:eventbus:A} 		at slimeknights.tconstruct.TConstruct.<init>(TConstruct.java:95) ~[TConstruct-1.18.2-3.5.1.31.jar%2353!/:1.18.2-3.5.1.31] {re:classloading,pl:eventbus:A} 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {} 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {} 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {} 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {} 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {} 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.54.jar%2356!/:?] {} 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.54.jar%2355!/:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}  	Mod File: TConstruct-1.18.2-3.5.1.31.jar 	Failure message: Tinkers' Construct (tconstruct) has failed to load correctly 		java.lang.reflect.InvocationTargetException: null 	Mod Version: 3.5.1.31 	Mod Issue URL: https://github.com/SlimeKnights/TinkersConstruct/issues 	Exception message: java.lang.ClassNotFoundException: slimeknights.mantle.fluid.UnplaceableFluid Stacktrace: 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {} 	at slimeknights.tconstruct.fluids.TinkerFluids.<clinit>(TinkerFluids.java:74) ~[TConstruct-1.18.2-3.5.1.31.jar%2353!/:1.18.2-3.5.1.31] {re:classloading,pl:eventbus:A} 	at slimeknights.tconstruct.TConstruct.<init>(TConstruct.java:95) ~[TConstruct-1.18.2-3.5.1.31.jar%2353!/:1.18.2-3.5.1.31] {re:classloading,pl:eventbus:A} 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {} 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {} 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {} 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.54.jar%2356!/:?] {} 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.54.jar%2355!/:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}   -- System Details -- Details: 	Minecraft Version: 1.18.2 	Minecraft Version ID: 1.18.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.1, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 851618112 bytes (812 MiB) / 1375731712 bytes (1312 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 8 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz 	Identifier: Intel64 Family 6 Model 94 Stepping 3 	Microarchitecture: Skylake (Client) 	Frequency (GHz): 4.01 	Number of physical packages: 1 	Number of physical CPUs: 4 	Number of logical CPUs: 8 	Graphics card #0 name: NVIDIA GeForce GTX 1070 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x1b81 	Graphics card #0 versionInfo: DriverVersion=30.0.14.9676 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 2.40 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 2.40 	Memory slot #1 type: DDR4 	Memory slot #2 capacity (MB): 8192.00 	Memory slot #2 clockSpeed (GHz): 2.40 	Memory slot #2 type: DDR4 	Memory slot #3 capacity (MB): 8192.00 	Memory slot #3 clockSpeed (GHz): 2.40 	Memory slot #3 type: DDR4 	Virtual memory max (MB): 34746.72 	Virtual memory used (MB): 22016.02 	Swap memory total (MB): 2048.00 	Swap memory used (MB): 297.50 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	ModLauncher: 9.1.3+9.1.3+main.9b69c82a 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		 mixin PLUGINSERVICE  		 eventbus PLUGINSERVICE  		 slf4jfixer PLUGINSERVICE  		 object_holder_definalize PLUGINSERVICE  		 runtime_enum_extender PLUGINSERVICE  		 capability_token_subclass PLUGINSERVICE  		 accesstransformer PLUGINSERVICE  		 runtimedistcleaner PLUGINSERVICE  		 mixin TRANSFORMATIONSERVICE  		 fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		TConstruct-1.18.2-3.5.1.31.jar                    |Tinkers' Construct            |tconstruct                    |3.5.1.31            |ERROR     |Manifest: NOSIGNATURE 		forge-1.18.2-40.1.54-universal.jar                |Forge                         |forge                         |40.1.54             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		Mantle-Mod-1.18.2.jar                             |Mantle                        |mantle                        |1.9.20              |COMMON_SET|Manifest: NOSIGNATURE 	Crash Report UUID: 81c1ece9-93a3-493a-a431-837305c057e1 	FML: 40.1 	Forge: net.minecraftforge:40.1.54

### Other mods

none

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked the FAQ

**Comment by KnightMiner** [comment]
Where did you download your mods from? We have no `Mantle-Mod-1.18.2` jar. Try downloading an official build from CurseForge rather than what is likely Malware from wherever you are downloading it.

**Comment by RaggedyMan1** [comment]
> Where did you download your mods from? We have no `Mantle-Mod-1.18.2` jar. Try downloading an official build from CurseForge rather than what is likely Malware from wherever you are downloading it.

ill dowqnload another one hold on

**Comment by RaggedyMan1** [comment]
> Where did you download your mods from? We have no `Mantle-Mod-1.18.2` jar. Try downloading an official build from CurseForge rather than what is likely Malware from wherever you are downloading it.

https://www.curseforge.com/minecraft/mc-mods/mantle/download/3829975 is this not correct one?

**Comment by KnightMiner** [comment]
That is the correct file. But that file is not `Mantle-Mod-1.18.2`, that file is `Mantle-1.18.2-1.9.27`. The only sites that name our jars like `Mantle-Mod-1.18.2` are mod rehost sites that are filled with viruses.

**Comment by KnightMiner** [comment]
Closing for lack of response. Reproduce this error with real builds from curseforge for a reopen. I will know based on the log file if they are real builds.
