### ISSUE TITLE
Add modifiers [severing, melting, etc] to recipe catalyst list in JEI

### ISSUE THREAD

**Issue by Random832** [SlimeKnights/TinkersConstruct#4933]
### Minecraft Version

1.18.2

### Forge Version

40.1.54

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

Discoverability of modifiers that are associated with loot or recipes in JEI tabs

### Suggested solution

Use modifier pseudo-ingredient in JEI in the list of recipe catalysts on the left side of the screen.

### Alternatives considered

N/A

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Added in 3.4.2.40
