### ISSUE TITLE
Plate chestplate and mob heads crash game

### ISSUE THREAD

**Issue by LeWolfYT** [SlimeKnights/TinkersConstruct#4934]
### Minecraft Version

1.18.2

### Forge Version

40.1.51

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

i was playing minecraft and i made a brass (create mod) embellished plate chestplate, and when i loaded my player model while wearing it my game crashed
I tested it without optifine, and it worked fine

[crash-2022-07-05_13.41.13-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/9048465/crash-2022-07-05_13.41.13-client.txt)
.

### Crash Report

Attatched

### Other mods

optifine, tconstruct, mantle.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Report to optifine. optifine is not supported.

**Comment by KnightMiner** [comment]
Duplicate of the pinned issue #4734, which you claimed to have read in your description. Lying does not get you help faster, be honest and only click the things you actually did.
