### ISSUE TITLE
Pickadze cannot break Skyslime Grass (and other slimy grass blocks)

### ISSUE THREAD

**Issue by Hiconel** [SlimeKnights/TinkersConstruct#4936]
### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

The Pickadze cannot break slimy grass. The only variant that seems to work properly is the tconstruct:sky_sky_slime_grass, while all other variants are broken as if you were punching them. However, it works fine with slimy dirt and vanilla dirt-like blocks.

### Other mods

Tested with just Forge, Mantle and Tinker's Construct.
![image](https://user-images.githubusercontent.com/1748758/178578737-16f0dc74-f8bb-4b72-b502-362b51312428.png)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Pickadze has limited mining level (limited to gold, which is between wood and stone). Slimy dirt has a mining level, based on the type it will be greater than gold. If you want to break it, a mattock is an option. No mining level is the cost for the pickadze having the largest list of minable blocks.

**Comment by Hiconel** [comment]
Oh sorry, I didn't even consider that the gold mining level is lower than stone. However, the Pickadze is capable of breaking one of the variants successfully. Is that a bug?

**Comment by KnightMiner** [comment]
> Slimy dirt has a mining level, based on the type it will be greater than gold. 

**based on its type it** will be greater than gold

Some variants have lower mining levels. Ichor has the highest. The level is based on the higher of the dirt and the foliage level.

**Comment by Hiconel** [comment]
Alright, huge thank you for clarifying and for the quick responses!
