### ISSUE TITLE
Alloyer doesnt like using basins as tanks

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4937]
### Minecraft Version

1.18.2

### Forge Version

40.1.46

### Mantle Version

Mantle-1.18.2-1.9.27

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.1.31

### Describe your issue

I was playing around with ~~breaking~~ *adjusting* the alloyers tanks list and found that when you add the `tconstruct:alloyer_tanks` block tag to basins, then place the basin next to the alloyer and open the alloyers it crashes. It does not crash if the basin has fluid in it, only if it is empty.

*Shiny pls dont kill me, Knight sent me*

### Crash Report

https://gist.github.com/ChiefArug/35dfd8d1ef928052f3d493a66c2bb469

### Other mods

A few well known mods, and my one tiny 2 block mod. I am very confident this is reproducible without these though, as no other mods are mentioned in the main part of the stack trace and it seems that this is the sort of thing that wouldn't be a mod interaction.
```         
TConstruct-1.18.2-3.5.1.31.jar                  
FarmersDelight-1.18.2-1.1.1.jar                 
rhino-forge-1802.1.14-build.190.jar             
MouseTweaks-forge-mc1.18-2.21.jar               
[FORGE]-Croparia-LITE-4.0.1.jar                 
jei-1.18.2-9.7.0.209.jar                        
appliedenergistics2-11.1.4.jar                  
heftycrops-1.18.2-1.1.jar                       
flywheel-forge-1.18-0.6.2.jar                   
FarmersRespite-1.18.2-1.2.0.jar                 
Patchouli-1.18.2-67.jar                         
Mantle-1.18.2-1.9.27.jar                        
create-mc1.18.2_v0.4.1.jar                      
Borealis-2.0.0.jar                              
Croptopia-1.18.2-FORGE-2.0.1.jar                
Controlling-forge-1.18.2-9.0+19.jar             
BetterThirdPerson-Forge-1.18.2-1.8.1.jar        
complete_compost-1.0.1.jar                      
overweightfarming-1.18.2-1.2.1-forge.jar        
farmingforblockheads-forge-1.18.2-10.0.2.jar    
pneumaticcraft-repressurized-1.18.2-3.2.2-79.jar
endercrop-1.18.2-1.7.0-beta.jar                 
architectury-4.5.76-forge.jar                   
kubejs-forge-1802.5.4-build.510.jar             
KubeJSBorealis-2.0.3.jar                        
cc-tweaked-1.18.2-1.100.5.jar                   
balm-3.1.0+0.jar                                
probejs-2.9.0-forge.jar                               
cofh_core-1.18.2-1.6.4.21.jar                   
thermal_foundation-1.18.2-1.6.3.28.jar          
thermal_expansion-1.18.2-1.6.3.13.jar           
kubejs-thermal-1802.1.5-build.14.jar            
appleskin-forge-mc1.18-2.4.0.jar                
DarkModeEverywhere-1.18.1-1.0.1.jar             
```

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.40
