### ISSUE TITLE
[1.18.2] Tinkers cobalt plate armor rendering incorrectly on player?

### ISSUE THREAD

**Issue by NovaLynxie** [SlimeKnights/TinkersConstruct#4938]
### Minecraft Version

1.18.2

### Forge Version

40.1.41

### Mantle Version

1.9.26

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

Tinkers armor embellishments don't render correctly on the player in-game yet render correctly.
I would expect the armor to show as seen on the player in the inventory screen yet this does not seem to be the case |:T
In game player: (what is actually seen)
![image](https://user-images.githubusercontent.com/21307676/178997604-60572324-0fb0-4493-bc2e-0768cd76301b.png)
Inventory player: (what I should expect to see?)
![image](https://user-images.githubusercontent.com/21307676/178997615-8f5c11ec-7bfd-424b-8d35-0774e1310dc0.png)

Just to prove the affected armor parts do in fact have embellishments:
Chestplate:
![image](https://user-images.githubusercontent.com/21307676/178999716-79906c8c-4356-41b7-b4b4-23c15b9b6a7c.png)
Boots:
![image](https://user-images.githubusercontent.com/21307676/178999820-a63b778a-6e1a-42a7-bf09-176ea8e2b51d.png)

So far have tested with the listed other mods that could be causing the problem which has not had any effect.
I cannot be sure what mods could be causing this but will try to investigate further to see if there are any other mods causing it from the modpack I am playing this on.

### Crash Report

visual bug only - no crash report generated

### Other mods

Oculus - 1.2.5
Rubidium - 0.5.2a

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Your tinkers is out of date, and unable to reproduce on latest tinkers version.

**Comment by NovaLynxie** [comment]
Huh... good to know. Am going to try the latest version to see if this was fixed.
Also update I was able to replicate this issue on the versions listed. It was my helmet with golden modifier that caused the rendering bug.

**Comment by NovaLynxie** [comment]
Ok, have been testing and was able to reproduce it with latest tinkers with oculus installed.
With oculus installed, as soon as I take off my helmet with golden modifier the embellishments of the other pieces of armor  will also render correctly.
As soon as I remove oculus all the armor embellishments renders as normal equipped.

**Comment by ShinyPorygon** [comment]
Report here https://github.com/Asek3/Oculus/issues nothing we can do about performance/shader mod bugs
