### ISSUE TITLE
Pick block feature does not take Tinkers tools into consideration

### ISSUE THREAD

**Issue by ciserman** [SlimeKnights/TinkersConstruct#4939]
### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

When right clicking on a block Minecraft will swap your currently selected item to that block, if it is in your inventory. If it is not on your hotbar, and your hotbar is full, it will swap that item from your inventory with your current hotbar slot, unless you are currently holding a vanilla enchanted tool. If you have an enchanted tool it will swap with the next non-tool slot on your hotbar. 
There is currently no consideration for this if you have a Tinker's tool as your current item. If you have your hotbar full, and have a Tinkers tool in hand, and use Pick Block (middle click by default), the block will replace your Tinkers tool: throwing off what may be your typical tool sorting order.

Steps to Reproduce:
1. Have a Tinkers tool in slot 1
2. Fill your other hotbar slots with other blocks
3. Have your tool in slot 1 currently active
4. Use the Pick Block command (middle-click by default) while looking at a block that is not on your hotbar, but is in your inventory
Expected Result:
- The type of item you are looking at when using Pick Block will be swapped from your inventory with your item in the first non-tool slot (slot 2). This is how vanilla works with enchanted tools.
Actual Result:
- The type of item you are looking at when using Pick Block swaps from your inventory with your tool, putting it out of your hotbar.

### Other mods

Reproducible with Tinkers only

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
I really doubt anything can be done about this. Mojang hardcoded nearly every pick block behavior. It would probably be on Forge's side to fix.

**Comment by ciserman** [comment]
It's something that has bugged me for a while, and limits my use of Tinkers on occasion. Would it be worth trying to open a ticket with Forge?

**Comment by KnightMiner** [comment]
It appears forge now has a hook for this on 1.19. Not sure if that will get added to 1.18, so for now I'll just mark this issue to review once the mod gets a port to 1.19

**Comment by KnightMiner** [comment]
v3.8.1.16 for 1.19.2 now uses the new forge hook to fix that. will not be added to 1.18 as the hook does not exist, so closing
