### ISSUE TITLE
More than 44 mods causes modifier textures to disapear

### ISSUE THREAD

**Issue by TheTraveller-g** [SlimeKnights/TinkersConstruct#4941]
### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Installing more than 44 mods causes the modifier textures to disapear from the tool
which i find confusing.

### Other mods

same as issue #4940

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Do not create duplicates. Just leave a comment as you did.
