### ISSUE TITLE
Piggybackpack Server Crashes

### ISSUE THREAD

**Issue by FlewittGuy** [SlimeKnights/TinkersConstruct#4942]
### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

When using the Piggybackpack, if you try to use it on a mob already above your head, the server crashes.

### Crash Report

https://pastebin.com/LJKfFR6u

### Other mods

Origins (Forge)
Origins++
Pehkui
Clumps

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by ChiefArug** [comment]
There isn't a crash in that server log you posted, maybe its in the seperate crash reports folder?

**Comment by ShinyPorygon** [comment]
Unable to reproduce on provided versions on a server using just tinkers and mantle.

**Comment by KnightMiner** [comment]
Closing for lack of response as we cannot reproduce. If you want a reopen, give a crash report.

**Comment by Lil-Vince** [comment]
I was able to recreate this on my 1.16.5 server I have 14 mods on the server and I have 1 mod that this person also had, Pehkui so I think Pehkui has something to do with the crashes since Pehkui is a SIZE changer mod but the server didn't crash untill I tried picking up a third mob with 2 other mobs on my head

**Comment by KnightMiner** [comment]
Again, without a crash report we cannot help you. 1.16.5 is also out of support, so reproduce it on 1.18 or we cannot help you.

**Comment by Lil-Vince** [comment]
I can't reproduce it on 1.18 because of the fact I no longer have a damn laptop to play minecraft on
