### ISSUE TITLE
Mining level issue

### ISSUE THREAD

**Issue by TheBlueFreezy** [SlimeKnights/TinkersConstruct#4943]
### Minecraft Version

1.18.2

### Forge Version

40.1.31 and up

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

In all the mods 7, tinkers construct mining level is bugged. My cobalt pick axe wont let me mine anything above level 1 stuff, so stone and coal. will not let me mine anything on the same level as a stone axe and above.

### Other mods

All the mods 7

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by ChiefArug** [comment]
Are you sure you made a pick**axe** and not a pick**adze**?
The pickadze is too weak to mine most ores, as mentioned in at least two of the books.

**Comment by TheBlueFreezy** [comment]
valid point. its been a while since ive had this pack, its quite confusing.

**Comment by TheBlueFreezy** [comment]
> Are you sure you made a pick**axe** and not a pick**adze**? The pickadze is too weak to mine most ores, as mentioned in at least two of the books.

thanks for the insite. i did make the wrong pick
