### ISSUE TITLE
slimeskulls are 1/1 durability

### ISSUE THREAD

**Issue by WilloIzCitron** [SlimeKnights/TinkersConstruct#4944]
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Mantle Version

1.6.147

### Tinkers' Construct Version

1.16-3.3.0.308

### Describe your issue

i was in my discord friend server and he crafted a blaze slimeskull and he said "it's broken", and i tried it with wither skeleton and it's broken with 1/1 durability

### Other mods

Create: Above & Beyond modpack 
Rubbidium 
Oculus

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

I did not search

**Comment by WilloIzCitron** [comment]
![image](https://user-images.githubusercontent.com/49786146/179743479-3c089ed4-4dfb-46d9-ac2b-4c59666844ed.png)
i forgot to put image sorry

**Comment by ChiefArug** [comment]
You need to update Tinkers Construct to latest (`3.3.4.335`) manually on both the server and your clients, what you are using is quite old (CAAB may of still not updated it yet...)

**Comment by ShinyPorygon** [comment]
This is a bug that has been long fixed. Create A&B has the first armor alpha build. Their pack has not been updated, updating tinkers and mantle will fix this bug. I can't find the original issue for this to properly mark as duplicate. But this has been fixed.

**Comment by WilloIzCitron** [comment]
ok thanks
