### ISSUE TITLE
Cannot place tools in Immersive Engineering toolbox

### ISSUE THREAD

**Issue by Random832** [SlimeKnights/TinkersConstruct#4947]
### Minecraft Version

1.18.2

### Forge Version

40.1.54

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

IE currently requires tools to either extend DiggerItem or ShearsItem or tag with immersiveengineering:toolbox/tools

Cross-reported at https://github.com/BluSunrize/ImmersiveEngineering/issues/5367 with a suggestion that they should use ToolActions, Not sure what's the best viable solution between that or having TCon tag the items.

### Other mods

Immersive Engineering

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Fixed on IE's end
