### ISSUE TITLE
Copper duplication bug in smeltery

### ISSUE THREAD

**Issue by LysLuc** [SlimeKnights/TinkersConstruct#4948]
### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

There is a duplication recipe for Copper using Cut Copper. You can either craft 4 copper blocks to 4 cut copper or use the stonecutter to get 4 cut copper out of 1 copper block

If you look at the recipes for Cut Copper in the smeltery then you have 2 recipes, 1 which gives a full copper block worth of molten copper and 1 that gives 1/4th of a block worth of copper.

![image](https://user-images.githubusercontent.com/40733794/180322486-71ae4f68-2b7f-477b-bae3-ce084561a246.png)

### Other mods

No other mods are used for this, the recipe IDs are from Tinkers itself.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
![image](https://user-images.githubusercontent.com/35193007/180324155-c41d4f7b-141d-4f85-acdb-0d596aeae96e.png)
Well the stonecutter thing works but I only see one recipe for smelting.

**Comment by KnightMiner** [comment]
Tell people to stop tagging cut copper as a copper block. Forge had a broken tag back in 1.18.1 but it was fixed long before your forge build.

To verify, run `/mantle tags_for held item` while holding a cut copper block. If its in the tag, will have to look through datapacks/mods to find which one added the tag.

**Comment by LysLuc** [comment]
After trying out the command and looking through the mods I found out that it's Chisel's and Bits that added the tag to copper, my apologies for the confusion!
