### ISSUE TITLE
Ichor has not melting recipe

### ISSUE THREAD

**Issue by Wolfstar1010** [SlimeKnights/TinkersConstruct#4949]
### Minecraft Version

1.18.2

### Forge Version

40.1.30

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

There are no recipes currently available for melting any ichor block in the smeltery or the foundry. Not sure if this is intentional but wanted to make sure you were aware.

### Other mods

NA

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
Ichor will be a gas so nope, won't be a recipe until the endery unless KnightMiner has changed his mind!

**Comment by Wolfstar1010** [comment]
Oh that sounds really cool! Can't wait to see how that works in the future. Thanks for the quick response!
