### ISSUE TITLE
Manasteel components in tools lead to not being able to log in to server until tool is deleted from inventory

### ISSUE THREAD

**Issue by KuroNecron** [SlimeKnights/TinkersConstruct#4950]
### Minecraft Version

1.18.2

### Forge Version

40.1.55

### Mantle Version

Mantle-1.18.2-1.9.27.jar

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.1.31.jar

### Describe your issue

Built a Pickaxe, Rose Gold Head and Handle, Manasteel Binding
When doing anything, i get kicked "Internal Server Error", and the serverlog says
`[Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER`
Upon trying to log back in, same thing.

Workaround: NBTExplorer to delete the tool from Playerdata

Latest login attempt starts at Line 4954 of the attached file, actual trouble starts in 5012
[crashlog for Tinkers devs.txt](https://github.com/SlimeKnights/TinkersConstruct/files/9175350/crashlog.for.Tinkers.devs.txt)

### Other mods

Public Modpack:
https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-3 
Version AQM3-1.0.6

Using the serverfiles offered by Curseforge for the modpack.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Magnesium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
We do not add those. Find whichever addon does

**Comment by ChiefArug** [comment]
This is the addon `tcintegrations`'s fault, they forgot to seperate their client only code.

**Comment by KuroNecron** [comment]
Thank you very much for your answers, i couldn't find tci in the modlist, so assumed it wasnt included.
The issue is known to them.
