### ISSUE TITLE
Cant right click in server when wear TC3 chestplate.

### ISSUE THREAD

**Issue by Dobe-Leo** [SlimeKnights/TinkersConstruct#4951]
### Minecraft Version

1.16.5

### Forge Version

36.2.35

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

I hold a small server for friend to play(base on a unofficial mod server which depend on spigot). And we find that the plugins(such as LWC, quickshop, BlockLocker) cant protect chest and someone could open it freely if it equips the tc3's chestplate. So I try to fix it and I find it may cause by the method _chestplateInteractWithBlock_ in _InteractionHandler.class_ . I guess it cancels the event so the spigot cant get the _PlayerInteractEvent_ anymore.
But this is just my guess. I dont know how to fix it because I dont have enough code experience. I temporarily banned chestplate to avoid this problem, and I hope it can be solved.

ps: I didnt test the other version.(i guess it also exist) And I am sorry for my pool English and hope it didnt anger you.

### Other mods

I have test while only running TC3. It still happens.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues

**Comment by KnightMiner** [comment]
We cancel the event at lowest priority, if they are using the event thet should be using higher priority. More likely it's because I use a different implementation of interaction logic and spigot is not using the events. 

That said, I don't support non-forge servers, not worth the effort. I'll double check I'm calling all vanilla protection hooks, beyond that nothing I can do. If you need protection mods for a small server, you really don't have good friends.

**Comment by Omniains** [comment]
having similar issue with the travlers vest in the create astral pack, has tag for hephaestus. have to have an item in hand in order to interact with bed, seats, mounts. in multiplayer, curseforge download. not host.

**Comment by KnightMiner** [comment]
Hephaestus is not us, that is a different author. bugs with that mod do not belong here

**Comment by KnightMiner** [comment]
I am going to go ahead and close this issue as we handle this to the best of our ability and it works with Forge mods. If this issue still happens on the 1.19.2 version, give exact mod listing that causes it and we can reopen.

As a note for server makers: if you remove chestplates from the interactable armor item tag (should be under `modifiable/interactable/armor`, though path varies a bit based on edition), you can disable the chestplate interaction modifiers entirely, which will prevent any sorts of conflicts. It will disable a small chunk of chestplate modifiers, but it guarantees our logic there won't run.
