### ISSUE TITLE
Stencil table is completely missing

### ISSUE THREAD

**Issue by kbn005** [SlimeKnights/TinkersConstruct#4954]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

The stencil table simply does not exist.  I cannot find it in the creative menu, I cannot give it to myself with commands, and the crafting recipe doesn't work.  Has it been replaced with something else?

### Other mods

nothing except tinkers and mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment]
The stencil table no longer exists, try reading the new books or faq on this github
