### ISSUE TITLE
Bouncy ability doesnt have maximum level

### ISSUE THREAD

**Issue by Zen9890** [SlimeKnights/TinkersConstruct#4955]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Bouncy ability doesnt have maximum level defined, so you can apply bouncy 2 to your boots, which wouldnt have any different effect from bouncy 1
![2022-07-30_07 08 20](https://user-images.githubusercontent.com/62694017/181872020-8621fbe4-8966-4622-a535-d8e058f6c31d.png)
Screenshot of applying bouncy 2

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.40. For the sake of bookkeeping, this bug is related to #4955, as between the number counting up and not having a max level, some might have believed bouncy II did something. It does not, 1 level is the same as 1000
