### ISSUE TITLE
Step Up should not apply while crouching

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#4956]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

The step up armor upgrade is amazing, but it would be nice if it didn't apply while crouching! It's unexpected to go down an entire block while sneaking on the edge of it, and going up would likely have the same effect if you're trying to hide.

### Suggested solution

N/A

### Alternatives considered

N/A

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
I don't control step up behavior. I just enabled it using the forge attribute.

I suppose it could be possible to remove the attribute while sneaking, but that would be a pain. So doubt anything will be don't about this.

**Comment by MarioSMB** [comment]
Yeah... I'm just gonna leave this here https://youtu.be/ySUhG7ELABw

**Comment by KnightMiner** [comment]
If you wish you can report this to forge as undesirable behavior. Or alternatively, ask on the forge discord whether this is a bug
