### ISSUE TITLE
Sturdy Multiplier wrong in Encyclopedia 

### ISSUE THREAD

**Issue by chrisi5700** [SlimeKnights/TinkersConstruct#4958]
### Minecraft Version

1.18.2

### Forge Version

40.1.24

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

See https://github.com/SlimeKnights/TinkersConstruct/blob/3b01d1d817c5a261bfbb6370d7538dd7795e5f94/src/main/resources/assets/tconstruct/lang/en_us.json 
at line 1370 "Gives an extra 10% durability per part"

But in the code 
https://github.com/SlimeKnights/TinkersConstruct/blob/55f376dd24216c533f9f46f169521f33e9c4846a/src/main/java/slimeknights/tconstruct/tools/data/ModifierProvider.java
at line 154 "addModifier(ModifierIds.sturdy, StatBoostModifier.builder().multiplyBase(ToolStats.DURABILITY, **0.15f**).build());"

### Other mods

Optifine

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Please add this to #4932, easier to track all the typos in one place.

**Comment by KnightMiner** [comment]
Closing as covered in the typo thread
