### ISSUE TITLE
Ore doubling with ore block despite ore rate config

### ISSUE THREAD

**Issue by SamuelYaron** [SlimeKnights/TinkersConstruct#4961]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Hi,

I am using Tinkers Construct in concert with some other (technical) mods, which have some mechanisms to increase yields from mined ores. I do not want any possible ore duplication with the mechanisms from Tinkers Construct and ended up with this configuration for ore rates:

```
[recipes.ore_rates]

		#Ore rates when melting in the melter
		[recipes.ore_rates.melter]
			#Number of nuggets produced per metal ore unit melted. 9 nuggets would give 1 ingot
			#Range: 1 ~ 45
			nuggetsPerMetal = 9
			#Number of gem shards produced per gem ore unit melted. 4 gem shards would give 1 gem
			#Range: 1 ~ 20
			shardsPerGem = 4

		#Ore rates when melting in the smeltery
		[recipes.ore_rates.smeltery]
			#Number of nuggets produced per metal ore unit melted. 9 nuggets would give 1 ingot
			#Range: 1 ~ 45
			nuggetsPerMetal = 9
			#Number of gem shards produced per gem ore unit melted. 4 gem shards would give 1 gem
			#Range: 1 ~ 20
			shardsPerGem = 4

		#Ore rates when melting in the foundry
		[recipes.ore_rates.foundry]
			#Number of nuggets produced per metal ore unit melted. 9 nuggets would give 1 ingot
			#Range: 1 ~ 45
			nuggetsPerMetal = 9
			#Number of gem shards produced per gem ore unit melted. 4 gem shards would give 1 gem
			#Range: 1 ~ 20
			shardsPerGem = 4

		#Byprouct rates when melting in the foundry
		[recipes.ore_rates.foundry_byproduct]
			#Number of nuggets produced per metal ore unit melted. 9 nuggets would give 1 ingot
			#Range: 1 ~ 45
			nuggetsPerMetal = 1
			#Number of gem shards produced per gem ore unit melted. 4 gem shards would give 1 gem
			#Range: 1 ~ 20
			shardsPerGem = 1
```

In my understanding this should remove any extra gains from smelting in any of Tinkers smelting systems (except for the byproduct, which I can live with) and it seems to work fine. But I had to realize that putting the actual ore block (not the raw ore, but the ore block obtained from mining with Silk Touch) still yields two ingots. So my question is the following:

Is that behavior as intended and if yes, can you introduce some extra config to also tweak this?

Thanks for all your work, greetings

### Other mods

-

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Yes, ore blocks produce more metal than raw ore. An ore block can be fortuned into more than one raw ore (2.5 on average).

No, there is not a config to change this.. But you can change all the relevant recipes with datapacks.  No plans to add a config option as datapacks exist, the ore rate one is just for convenience as that is a common request and its different per machine (for a single recipe) but making ores not 2x is uncommon.
