### ISSUE TITLE
Quark double door opening does not work with Tinker's Construct chestplates equipped

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#4962]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

With a Tinker's Construct chestplate equipped (e.g. Plate Chestplate), the double door opening functionality from Quark doesn't work while unarmed. Holding any item or removing the chestplate allows the double doors to open correctly, this only applies to the chestplate.  
This is likely a conflict caused by the unarmed combat adjustments made with Tinker's Construct chestplates.

### Other mods

Quark

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
On our end the tinkers armor is already using the lowest possible priority, meaning that the tinkers action will run last compared to any others, however quark is also doing this so nothing can be done about it from our end. They need to up their priority in order for this to be fixed. 

https://github.com/VazkiiMods/Quark/issues/3751
