### ISSUE TITLE
Pls remove Compatibility to create alloys

### ISSUE THREAD

**Issue by Gartebex-Ugandi** [SlimeKnights/TinkersConstruct#4963]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

Tinkers contruct is a nice mod, but in my opinion the crafting recipes for alloys kinda break the creates experience. Like for example to create an andesite alloy in advanced way you need a mixer whitch at least costs 5 iron. but with tinkers construct, you just need some puny gravel, sand, and clay. Whitch is in my opinion frustrating. But this is just a small detail compared to the brass recipe. For brass, originally you need to go to the nether and find a fortress. Whitch can be very time consuming. But its very rewarding. Because with brass you can do kinda everything. But in tinkers. you just get it from start. no need to go kinda anywhere for 9000 hours. And theres not even any need at least for blazing blood. Whitch totally crushes the rewarding feeling, and totally breaks the gameplay of create. Making it extremely incompatible with the mod.

### Suggested solution

Removing those recipes whitch causes the gameplay shalanaga.

### Alternatives considered

I removed them by crafttweaker. Thats the alternative that can be used i think.

### Additional context

Not needed.

### Searched for existing enhancement?

Used the search bar

**Comment by ShinyPorygon** [comment]
Well, you already have your own solution to it. The brass alloy specifically is not a specific compat to create. The brass compat is for any mod that adds brass. You can crafttweaker them out if you don't like them, but there are no plans to remove them from base tinkers. Some mods make brass easier than others, create apparently makes it harder. In regards to the andesite alloy it's there as an optional thing, no one has to use it and no one from create has came and said it breaks the entire mod.

**Comment by Gartebex-Ugandi** [comment]
eh ?

**Comment by Gartebex-Ugandi** [comment]
The thing is, that people can think it, but they dont have to say it.

**Comment by Gartebex-Ugandi** [comment]
I would personally like knightminer know what he thinks about it, because im not sure about your opinion. It also sounds very arrogant.

**Comment by ShinyPorygon** [comment]
I don't see how I'm being arrogant. Brass is added as a common material which can be found in code [here](https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/generated/resources/assets/tconstruct/tinkering/materials/brass.json) Create is not the only mod that adds brass, each mod has the obtainability of it different. As for andesite alloy, I believe Knight went and asked in both the Create and Tinkers discord before he added it. I don't see why he would remove it.

**Comment by Gartebex-Ugandi** [comment]
ok

**Comment by Gartebex-Ugandi** [comment]
thanks :)

**Comment by Gartebex-Ugandi** [comment]
Eh, what kind of other mods add brass ? Just out of interest, because i wanna look at those mods.

**Comment by KnightMiner** [comment]
Whatever the current red power clone is called. I think its Project Red still?

> I would personally like knightminer know what he thinks about it, because im not sure about your opinion. It also sounds very arrogant.

Shiny has access to manage issues on this tracker because they know my opinions on a lot of stuff like this. If I did not trust them to accurately represent my views on the mod, I would not let them close issues.

For the record, for any recipe if you dislike it, *you* can remove it via datapack. No point complaining about a compat thing (that I will note the create devs were on board with) when you have full ability to remove it.

**Comment by Gartebex-Ugandi** [comment]
ok, thanks.
