### ISSUE TITLE
Can't use Flint and Brick to light up candles

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4965]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Can't use Flint and Brick to light up candles

### Other mods

A lot, gonna test later with Tinker only

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Got this mostly fixed, seems that you still eat the cake when lighting a cake candle, so need to find why that is and how to prevent it. Might just need to have firestarter always return true on the cake, even if not able to light it.

Seems vanilla cake has hardcoded behavior to check for flint and steel and ignore interaction, so I will have to special case it, fun...

**Comment by KnightMiner** [comment]
Should be fixed in 3.4.2.40. There might be some edge case I missed though, candle cakes are dumb.
