### ISSUE TITLE
Tinted glass has two recipes due to forge tags, one is useless. 

### ISSUE THREAD

**Issue by ShinyPorygon** [SlimeKnights/TinkersConstruct#4966]
### Minecraft Version

1.18.2

### Forge Version

40.1.69 (nice)

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Tinted glass has a dual recipe that melts into glass and amethyst due to it having the forge:glass tag, the clear variant melts into amethyst and byproducts into glass as I'm assuming the glass should. 
![image](https://user-images.githubusercontent.com/35193007/183290509-e10aa96e-a061-43c5-9818-997326eaa39d.png)

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Should be fixed in 3.4.2.40. I ended up needing to manually handle glass panes as there is no standard silica glass pane tag in forge, so its possible some mod support was lost by this change. Asking the dev to tag appropriately will fix it.
