### ISSUE TITLE
Liquids not rendering with shaders enabled

### ISSUE THREAD

**Issue by Nevrai** [SlimeKnights/TinkersConstruct#4968]
Liquids in the smeltery, and lava in the seared fuel tank or seared melter, don’t render with shaders enabled.

### Screenshots
<details>
  <summary>Comparison screenshots (click to expand)</summary>
  
#### Shaders off
![2022-08-11_22 06 37](https://user-images.githubusercontent.com/59761487/184233781-3a7fb000-9cff-4e9e-9443-908412f219ff.png)

#### Shaders on
![2022-08-11_22 06 35](https://user-images.githubusercontent.com/59761487/184233787-1715b7aa-6215-4ea1-a13b-0d4652c47f08.png)

#### Shaders off
![2022-08-11_22 13 24](https://user-images.githubusercontent.com/59761487/184233833-76773e5f-3001-4e7b-a0d1-44a079dfb80c.png)

#### Shaders on
![2022-08-11_22 13 22](https://user-images.githubusercontent.com/59761487/184233839-d1543a5e-6b1d-41bb-9d0a-3a16176c1e63.png)

  
</details>

[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) are used for shaders. Tested with [Complementary Shaders v4](https://www.curseforge.com/minecraft/customization/complementary-shaders), [Complementary Reimagined](https://www.curseforge.com/minecraft/customization/complementary-reimagined), and [SEUS Renewed](https://www.sonicether.com/seus/), but the same issue occurs with all shader packs. I don’t believe this was a problem in 1.12.2.

Tested without any mods except Tinkers’ Construct, Mantle, Rubidium, and Oculus.

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Tinkers’ Construct:** 3.5.1.31 (latest)
* **Mantle:** 1.9.27 (latest)
* **Rubidium:** 0.5.3a (latest)
* **Oculus:** 1.2.5a (latest)

### Other mods

[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus).

### Searched for known issues?

Checked pinned issues, searched open issues, searched closed issues, checked the FAQ.

**Comment by ShinyPorygon** [comment]
This is oclus/rubidium's problem to fix.
