### ISSUE TITLE
Step Up level II not working

### ISSUE THREAD

**Issue by Nevrai** [SlimeKnights/TinkersConstruct#4969]
Step Up II on my traveler’s leggings doesn’t let me climb up two blocks. It lets me climb up only one, which is the same as Step Up I.

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.25—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Tinkers’ Construct:** 3.5.1.31 (latest)
* **Mantle:** 1.9.27 (latest)

### Searched for known issues?

Checked pinned issues, searched open issues, searched closed issues, and checked the FAQ.

**Comment by ChiefArug** [comment]
Step up only increases step height by 0.5 blocks.
With step up 1 that means 1 full block, step up 2 is 1.5 blocks (so fences and slabs on top of blocks)

**Comment by KnightMiner** [comment]
Default step height is 0.5, level 1 makes you go +0.5. Don't know how you decided that its +1 block per level.

**Comment by Nevrai** [comment]
Oh, my apologies. I misunderstood it. I could climb up normal blocks (one-block tall blocks) with level 1, though, which is why I was confused. Could that be a bug?

**Comment by ChiefArug** [comment]
You can step up 0.5 height blocks in vanilla (slabs). All the step up modifier does is increase that value by 0.5.
