### ISSUE TITLE
Mention the Encyclopedia of Tinkering in Materials and You

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#4970]
### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

It is the only book not mentioned in a previous book. This means players don't know about it unless they have JEI installed, or watch/read a tutorial.

### Suggested solution

Add a sentence or two to the further reading section of Materials and You. Because the player doesn't know about casting yet it could be vague about "coating a book in molten gold".

### Alternatives considered

Mentioning it inside Puny Smelting **and** Fantastic Foundry, so that players will understand casting by the time they read it. It should be in both of them so that nether only runs have it mentioned too.

### Additional context

as a side note, the default mc version for this issue template should be updated to 1.18.2, instead of 1.18.1

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Puny melting is where casting book recipes go

**Comment by KnightMiner** [comment]
In 3.4.20, puny melting now advertises recipes for both mighty smelting and the encyclopedia. Interesting mighty was absent before (unless I just missed it).
