### ISSUE TITLE
More smeltery controller types

### ISSUE THREAD

**Issue by Gartebex-Ugandi** [SlimeKnights/TinkersConstruct#4973]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

Mantle-1.18.2-1.9.27.jar

### Tinkers' Construct Version

 TConstruct-1.18.2-3.5.1.31.jar

### Problem description

Its not really a problem, but it would be a nice thing for detailists.
The thing is, that there is only one type of smeltery controller.

### Suggested solution

The solution is: making other smeltery controllers with corresponding bricktypes.

### Alternatives considered

Maybe retexturing the smeltery controller ? but that would be a problem for multiple smelteries.

### Additional context

No need

### Searched for existing enhancement?

Used the search bar

**Comment by KnightMiner** [comment]
For the record, have not done much with this as while I like the idea, I dont want to clutter JEI with blocks that are essentially the same but with different textures. If I do this feature, I may end up just doing what I did with anvils/the tool tables as I can easily make the recipe work without JEI clutter (and the block already requires a TE unconditionally)

**Comment by KnightMiner** [comment]
Added in a17c53c. Works the same as tool tables, so you can choose to hide the extra variants in JEI.

**Comment by KnightMiner** [comment]
Released in 3.6.1.85
