### ISSUE TITLE
Client crash when Player2 mouses over Player1's [Blood Island] Advancement / achievement

### ISSUE THREAD

**Issue by mjevans** [SlimeKnights/TinkersConstruct#4975]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

[17:20:10] [Server thread/INFO] [minecraft/DedicatedServer]: Player1 has reached the goal [Blood Island]
[17:20:45] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Player2 lost connection: Disconnected

Player2 reports mousing over Player1's achievement in their chat log which appears to have precipitated the crash.

[RenderThread/ERROR] header... net.minecraft.ReportedException: mouseClicked event handlr...

Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.advancements.Advancement.m_138319_()" because "current" is null

### Other mods

Occurred using an E8 2.1.0 server and client (FTB Backups disabled on both) https://www.curseforge.com/minecraft/modpacks/enigmatica8

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
If you are going to tell me there is a crash, I need a full crash report or game log I can do nothing. Giving me random excerpts is only useful if you know what the exact issue is, which you did not provide

That said, this advancement is not using anything defined in tinkers, it's all vanilla criteria. As a result, it's unlikely tinkers is the cause. Reproduce with fewer mods, and also tet reproducing with a different modded structure (e.g. Twilight forest) and a vanilla structure (I believe end cities have an advancement)

**Comment by mjevans** [comment]
For anyone else that comes here, it's apparently a known issue with a second mod interacting with achievements.

https://github.com/someaddons/ClickableAdvancements/issues/8
