### ISSUE TITLE
Slime Dirt "spreading" does not work

### ISSUE THREAD

**Issue by NyakoFox** [SlimeKnights/TinkersConstruct#4977]
### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

I've never done this before, so I could definitely be doing something wrong, however apparently the way to "duplicate" slime dirt is having a slime fluid flow onto a dirt block, from a slime dirt block. I found this method explained [here](https://www.reddit.com/r/feedthebeast/comments/9ou8ww/comment/e7xa3gc/?utm_source=share&utm_medium=web2x&context=3), and an imgur album [here](https://imgur.com/a/76LEydf), but it doesn't seem to work.

### Other mods

Mantle and Tinkers' Construct only.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
What you are describing is 1.12 behavior, as well as the thing you linked. You will not really find an online guide for TIC3, aka 1.16+ please use the in game books to find your info, or you can join the discord for other questions. However this isn't how the grass spreads anymore, in fact I don't think anything like this is entirely possible anymore either. I'm not sure why you'd need that much slime dirt.

**Comment by NyakoFox** [comment]
Large amounts of slime dirt is useful to make farms of slime trees, mostly. I assumed the behavior existed but was just broken in 1.16+ because it looks like the code still exists over in SlimeFluid.java, so I assumed it's a bug...

**Comment by ShinyPorygon** [comment]
Forge fluids are not great until 1.19, I'm not sure much effort was put into them doing anything

**Comment by NyakoFox** [comment]
Looking at it, I feel like this code was simply forgotten about. [Here it is in 1.12](https://github.com/SlimeKnights/TinkersConstruct/blob/c01173c0408352c50a2e8c5017552323ce42f5b4/src/main/java/slimeknights/tconstruct/shared/block/BlockLiquidSlime.java#L28), and [here it is in 1.18.2](https://github.com/SlimeKnights/TinkersConstruct/blob/5dfa77d74fa8b1e36fc9d6c7b548aa0928a939b1/src/main/java/slimeknights/tconstruct/fluids/fluids/SlimeFluid.java#L29). It would be nice to see this feature make a return in a later version.

**Comment by Insane96** [comment]
Can't you just use bone meal?

**Comment by Random832** [comment]
It appears the reason this code doesn't work is that the fluid properties are not set to randomly tick.

**Comment by KnightMiner** [comment]
One major difference between 1.12 and 1.16+ is liquid slime is now way easier to make. Which would let you easily create slime dirt. Not sure that slime dirt shouldn't be craftable, but its something that needs to be considered if this behavior is to be re-enabled

**Comment by NyakoFox** [comment]
> Can't you just use bone meal?

We're talking about duplicating slime dirt, not grass. However, spreading grass using bonemeal doesn't seem to work either.
