### ISSUE TITLE
Tools with materials from the Allthemodium mod are all white.

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [SlimeKnights/TinkersConstruct#4981]
### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

All tools with materials from the Allthemodium mod are white.

### Suggested solution

Use mod colors.

### Alternatives considered

I can't think of anything

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Well, first off, that's not tinkers adding that. And second off that would be caused by a performance mod.

**Comment by CapivaraTupiniquim** [comment]
Sorry for opening the problem. About the mod you mentioned, I use Rubidium, Magnesium/Rubidium Extras and Dynamic Lights, is that the problem? (Google Translator)

**Comment by ChiefArug** [comment]
Probably Rubidium
