### ISSUE TITLE
Able to pick up chickens without piggybackpack

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#4982]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Right-clicking a chicken without any armor on picks up the chicken, this doesn't work with armor on and doesn't seem to require the piggybackpack.

### Other mods

Unsure if any would have an effect on this.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by luckyu19** [comment]
This sounds like you have Carry On in your pack. Kindly check if you have that listed in your instance and if not, kindly work out which mods are allowing you to interact in that way by the following method:
1. Disable/remove half of mods and check if it still behaves that way. If failed check the other half.
2. If one of the parts have said behaviour, repeat step 1 with the current half of the mods.
3. Repeat until you have the mod responsible.

Let us know your findings.

**Comment by ShinyPorygon** [comment]
Judging by my ability to not reproduce this with just tinkers I'd say you 100% have carry-on. Please remember that if you have any mods at all you need to list them under "other mods" even if you think they have no effect.

**Comment by MarioSMB** [comment]
I don't have the Carry On mod, but I'll go through and see which mod might be adding a feature like this, thanks for the heads up.  

EDIT: It was Quark... I should have figured as they were the cause of the last Tinker's Construct-related armor issue!
