### ISSUE TITLE
Getting protection level 5 for TC armor is impossible in survival

### ISSUE THREAD

**Issue by MrMateusz** [SlimeKnights/TinkersConstruct#4984]
### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

It is not possible to get max Protection Armor Modifier because it uses 1 Ability slot per level and 2 (using a dragon head) ability slots are the max for survival.
I would suggest disabling the "1 slot per level" mechanic since it either takes all possible to get modifier slots or straight up makes reaching max level not possible, example: most defense upgrades as they cap at level 10 but max defense slot i found were 4 per piece, Reinforcment takes 5 modifier/upgrade slots (a pickaxe is created with 3 and you are able to give it 4 more) 
If in your opinion not having to use all modifier slots to get tinkers construct version of unbreaking 3 efficiency 5 pickaxe then i would recommend going with how luck-luckier-luckiest works, having a diffrent recipe per level to make it harder (i also must say going on adventure to find the needed items was more fun then sitting at the forge getting all the plates for reinforcment 1)

### Crash Report

none

### Other mods

3d skin layers
alexs mobs
citadel
create
easy villagers
flywheel forge
gravestones
inventory profiles next
jei
jeienchantinfo
jeiintegration
kotlinforforge
mantle
notenoughanimations
preview optifine H9
sounds physcis remaster
simple voice chat
xaeros minimap & worldmap

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment]
Protection works differently than vanilla. You're not supposed to be able to get protection 5. You use the other 5 sub protection modules to strengthen up the armor. 

Also don't use optifine.

**Comment by KnightMiner** [comment]
Also, getting Protection 5 is impossible on vanilla armor unless mods change enchanting. Don't know why you expected it would be possible on our armor.
