### ISSUE TITLE
Can't set `max_tier` in random material function

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4985]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Setting the `max_tier` for a random material is not possible as the mod reads `min_tier` twice instead of min and max_tier 
https://github.com/SlimeKnights/TinkersConstruct/blob/3b01d1d817c5a261bfbb6370d7538dd7795e5f94/src/main/java/slimeknights/tconstruct/library/json/RandomMaterial.java#L170

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Ah, so there were two bugs making that feature difficult to use. Shows how few people tried to use it.

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.40
