### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by DamianBerek** [SlimeKnights/TinkersConstruct#4991]
### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Mantle Version

?

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

fuel tanks or any transparent block dont display any liquid inside like lava or melted ingots. i use complimentary shaders if that mater

### Other mods

TNP limitless 5

with rubidium

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues

**Comment by ShinyPorygon** [comment]
Duplicate of #4968
