### ISSUE TITLE
Better Combat animations don't work on tinkers weapons

### ISSUE THREAD

**Issue by SkillfulLupus** [SlimeKnights/TinkersConstruct#4993]
### Minecraft Version

1.18.2

### Forge Version

40.1.79

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

Better Combat animations don't work on Tinkers weapons/tools

### Suggested solution

I would like it if the animations worked although i know that might be difficult as it might play havoc with the daggers as they already add dual wield support

### Alternatives considered

there isn't an alternative, i looked and couldn't find anything to add animations but i don't want to uninstall the mod so for now i'm just dealing with it.

### Searched for existing enhancement?

Used the search bar

**Comment by ShinyPorygon** [comment]
There is no plans to make tinkers compatible with mods like these. Someone is free to make an add-on for it.

**Comment by sentwayfarer** [comment]
[constructcombat.zip](https://github.com/SlimeKnights/TinkersConstruct/files/9546752/constructcombat.zip)
here ya go buddy :)
made a datapack just for this
edit: formatted wrong. fixed

**Comment by RedTactic** [comment]
where am I supposed to place the datapack?

**Comment by KnightMiner** [comment]
https://minecraft.fandom.com/wiki/Data_pack

**Comment by Nking20** [comment]
I need 1.19.2Better Combat and tinkers
