### ISSUE TITLE
[BUG] Duping with Sribe's Table and Tinker's Contstructs' Crafting Station

### ISSUE THREAD

**Issue by dumbdemon** [SlimeKnights/TinkersConstruct#4994]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

As described in  baileyholl/Ars-Nouveau#695:
`There's a duplication glitch with the interaction between the crafting station and Ars Nouveau's Scribe's Table when placed next to each other in 1.18.2. It showed up in All the Mods 7 and I tried it again with only just the two mods and its dependencies. When placed next to each other the crafting station detects the scribe's table inventory. When you place a item with at least two ore more into that inventory and try to take it out with out shift-clicking it creates a new stack and lessens what's in the detected inventory by one.`

### Other mods

Ars Nouveau v2.7.8

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by luckyu19** [comment]
Able to replicate this issue with the specified mod version.
This is probably a case similar to the duplication issue with Botania [#4645](https://github.com/SlimeKnights/TinkersConstruct/issues/4645) where those two items were not meant to have any interaction.

**Comment by KnightMiner** [comment]
We have a blacklist for a reason. So you can blacklist things like this.

All the crafting station does is access the blocks item handler for a modifiable item handler, if we cannot do so without dupes, their item handler is broken and should never have been released via getCapability. So to be completely honest, there is no bug on tinkers side. Tell mods to stop implementing `IItemHandlerModifiable` if they are not going to support the methods there, you only need to use `IItemHandler` if you slots do not behave properly.
