### ISSUE TITLE
(TYPO) Ingot tanks hold same amount, appears contrary to description text ~~bug~~

### ISSUE THREAD

**Issue by NuancNewt** [SlimeKnights/TinkersConstruct#4996]
### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

![image](https://user-images.githubusercontent.com/113639718/190503744-d3b6bbf4-f8f0-4587-80c3-720109c50a32.png)

Image 1 says that the seared tank holds up to 48 ingots

![image](https://user-images.githubusercontent.com/113639718/190503829-92e426c1-1f13-40ab-8f29-8d02de1704d3.png)

Image 2 says that the scorched tank holds up to 3 molten blocks, which i would assume is 27 ingots

![image](https://user-images.githubusercontent.com/113639718/190504024-f7530703-ecf6-4daa-87af-102f13f7c59c.png)
![image](https://user-images.githubusercontent.com/113639718/190504306-18bd7c55-fb4b-4158-91d0-e4dff0b757f2.png)

Image 3 and 4 shows 2 tanks both of which are filled to "4.32 buckets" however the seared should be holding close to double the scorched. is this an intended feature with incorrect flavour text / unimplemented feature / a bug / Me not understanding the math used to calculate the conversion from images to blocks to buckets in tinkers form?

### Other mods

Currently playing on 

Better MC PLUS V13 1.18
Linked here
https://www.curseforge.com/minecraft/modpacks/better-mc-plus-new

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by NuancNewt** [comment]
there is no crash sorry should have commented that

**Comment by KnightMiner** [comment]
That looks like an outdated tooltip. Please add this to the typo collection issue from the pins, its not a gameplay bug.
