### ISSUE TITLE
Optimize Smeltery Bricks

### ISSUE THREAD

**Issue by SoniEx2** [SlimeKnights/TinkersConstruct#4997]
### Minecraft Version

1.18.1

### Forge Version

N/A

### Mantle Version

N/A

### Tinkers' Construct Version

N/A

### Problem description

Seared blocks use block entities for optimization. This optimization is inefficient when they're being used for decoration.

### Suggested solution

It's possible to lazily convert them into block entities when a controller is present instead. This would avoid the BE overhead when it's not needed while still providing the BE-based optimization.

### Alternatives considered

Doing nothing is always an option.

### Additional context

Feel free to assign @SoniEx2 for this issue. Not sure when we'll be able to look into it tho.

### Searched for existing enhancement?

Used the search bar

**Comment by ShinyPorygon** [comment]
Please still list tcon version that you find this problem on. Because if it's for 1.18.1, that version is not receiving any updates.

**Comment by SoniEx2** [comment]
Oh. Sorry, this is still an issue on the current development branch (1.18.2). We're not sure what version that maps to.

**Comment by KnightMiner** [comment]
Yes, I am aware this can be done. It is already on the todo list. No, I would rather optimizations not be done by someone I have never met before. It will be done when I care to do it.
