### ISSUE TITLE
Floating Skyslime geode

### ISSUE THREAD

**Issue by Landrozaum** [SlimeKnights/TinkersConstruct#4999]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

I saw too many times in other worlds, some floating skyslime geodes with some stones around, was this supposed to happen?
![2022-09-19_00 47 56](https://user-images.githubusercontent.com/76543480/190947429-e8598b81-5996-4eb6-a2a7-ba4f00b72697.png)

### Other mods

The only worldgen mod i have is Biomes O' Plenty, i think the other mods doesnt conflict in any thing to this.

Performance Enchancers
Rubidium
Radon
Radium

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment]
I've never ever seen this before and I'm not able to reproduce in any way. Find out what mod/s from the rest of your list is causing this. Don't dismiss mods as "can't be the cause it shouldn't be."

After being a little more awake, they are supposed to mostly be underground, though with world gen mods this is bound to happen.

**Comment by KnightMiner** [comment]
Most likely their biome mods just add in deeper valleys than expected. What Y level is the floor in that valley? 

The geodes are supposed to only spawn in blocks, but by the looks of that screenshot there was a small floating chunk of granite, so I think this is expected to me. The one issue is that the geode does not fully have a diorite border.

**Comment by KnightMiner** [comment]
7c9e651 makes sky slime geodes more picky about where they spawn, about all we really can do if biome mods are going to be weird.

**Comment by KnightMiner** [comment]
[3.5.3.63](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.3.63) has the change mentioned above. Not a lot more I can do as (demonstrated by the screenshot) the geodes can generate in floating stone.

Hopefully the new look will make them more thematic, its mossy cobble on the outside suggesting its a boulder.
