### ISSUE TITLE
Clear glass can not be molten

### ISSUE THREAD

**Issue by ShinyPorygon** [SlimeKnights/TinkersConstruct#5000]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

As discovered by Smartn't#6315 on discord. Clear glass can not be molten. Glass is fragile ya know stop breaking it.

https://github.com/SlimeKnights/TinkersConstruct/commit/92bc849d61b4f8294e25b3d4beb40f36da0c68ff 
You just forgot to add it here

### Other mods

Mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in [3.5.3.63](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.3.63)
