### ISSUE TITLE
Infinite storage (and potential chunkban) with Tinkers and Create

### ISSUE THREAD

**Issue by snackerpirater** [SlimeKnights/TinkersConstruct#5001]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

Create's Toolbox is allowed to go into the inventory of Tinkers gear (using Pockets, Shield Strap, etc.), and Tinkers gear is conversely allowed to go into the Toolbox as well. Assuming this is unintended since neither allow shulker boxes.

### Other mods

Create (0.5.0d)
Flywheel (Dependency of Create, 0.6.5)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
to blacklist create tool boxes from create, looks like I can use [this method](https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/main/java/com/simibubi/create/content/curiosities/toolbox/ToolboxInventory.java#L91)

Does not seem to be stack sensitive, so barring a forge PR the best I could do is entirely blacklist armor from the create toolbox. Alternatively, I could accept that armor can be in tool boxes and not vice versa.

----

Mind crossposting this to create's tracker? The resolution above will probably be sufficient, but they may have balance concerns regarding an item with inventory slots being in their toolbox. [Relevant blacklist code in tinkers](https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/main/java/slimeknights/tconstruct/library/tools/capability/ToolInventoryCapability.java#L89).

**Comment by KnightMiner** [comment]
Fixed in [3.5.3.63](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.3.63)
