### ISSUE TITLE
[Idea] Special ability for the future end smeltry

### ISSUE THREAD

**Issue by StellaBiscuit** [SlimeKnights/TinkersConstruct#5002]
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Problem description

In minecraft, when you mine or smelt ores, you get experience, something that the thinker smeltry lacks

It is a good way to balance early smeltry, you get more ressource but you don't get the experience

Another problem is that the end smeltry doesn't have a defined "special feature" like the nether smeltry (ability to have no alloy formation and also to have multiple liquid be output by a single item)

The only special ability is gaz and even then I wouldn't consider it an upgrade but more a way to limit the 2 others abilities

### Suggested solution

And so, I though of something, I though that one of the added gaz that the end smeltry could have is "Gaz Experience" (didn't search for a name lmao)

When you sublimate ores (actual term for solid to gaz btw) you also create Xp Gaz, it could even have it's own special duct so it could be transfered to the player's xp bar

Another idea is that enchantments on tools and other meltable items would also grant xp when sublimated, rarer and stronger enchant = more xp (make it better then grindstone so you have a reason to use it)
I always wanted to just drop enchanted item from loot chests without needing to grind them one by one

### Alternatives considered

I did though of an alternative way, but it would be harder to code. Maybe have sublimated enchanted items retain their enchant power (**not the enchant itself!**) inside the smeltery, enchanted material would give small boost to stats then regular material, the boost would depend on the enchant power of the material (Could also transfer to alloys so alloys can have those stat boost! Maybe even add a mechanic so you can put enchanted books in the end smeltery so it can "enchant" the material in it)

That would make enchant be meaningfull when playing Tinker without making tools/weapons/armor enchantable! No more "make tinker items enchantable" suggestion!

Ngl, I would want BOTH system to be combined

### Additional context

Was a bit inspired by how Tetra does tool transformation, it keeps the enchants allowing you to have a stronger variant of the normal tool (that you can empower more with enchanted books)
The gaz xp mechanic, and not the "liquid" itself, is a totally original idea by me :D

### Searched for existing enhancement?

Used the search bar

**Comment by KnightMiner** [comment]
I don't tend to consider suggestions on future features. Half the time the ideas end up being far from what we plan to do, half the time we already considered the ideas. If you wish to discuss future content, use the discord.

Gaseous XP is already planned, most ores will just melt into gas, giving no metal as a result. Mobs will also melt into gaseous XP instead of blood. There are some bigger problems to deal with before adding that sort of thing.

**Comment by StellaBiscuit** [comment]
Happy that the gazeous xp is already planned
