### ISSUE TITLE
Swapping Tool Belt with a shulker box in the hotbar replaces the item in the pants, losing it

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#5003]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

Video: https://www.youtube.com/watch?v=ITiX-NP5EK4

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by Insane96** [comment]
Updated with video and Tinkers only test

**Comment by KnightMiner** [comment]
Yeah, I could see that happening.

**Comment by KnightMiner** [comment]
Fixed in [3.5.3.63](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.3.63)
