### ISSUE TITLE
No use item stats for custom weapons

### ISSUE THREAD

**Issue by MarkusBordihn** [SlimeKnights/TinkersConstruct#5007]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

This is related to issue report https://github.com/MarkusBordihn/BO-s-Dynamic-Player-Progression-and-Difficulty/issues/4 were the issue was reported that Tinker Construct weapons are not processing.

I took a closer look into this and it seems that Tinker Construct has not implemented the items stats for their custom weapons.
This means regardless how often I using a weapon to kill a mob, it will not show up in the statistics page like:

![image](https://user-images.githubusercontent.com/12183293/193457212-65bd6849-35ad-497e-95e6-35039b77a99d.png)

I would expect that Tinker Construct weapons tracking their item stats the same way, like the standard weapon like the wood, stone, iron, diamond and netherite sword.

### Other mods

https://www.curseforge.com/minecraft/mc-mods/dynamic-player-weapon-progression-and-difficulty

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Worth noting, you won't see stats for each material, you will just see a single (probably white) tinkers sword in stats. Confirm whether that is the case

**Comment by MarkusBordihn** [comment]
At the moment I see nothing in the stats system even no base (white) weapon or so.
Having at least one item like the base weapon (white) in the stats would be already helpful for better integrations with other mods or advancements.

I'm happy to create and provide a PR, if preferred.

**Comment by ShinyPorygon** [comment]
![image](https://user-images.githubusercontent.com/35193007/194044156-cd2f77e7-13da-4547-b96f-61665c0895dd.png)
I do see all tinkers tools in the stats menu, granted yes they are white and non material specific.

**Comment by MarkusBordihn** [comment]
> ![image](https://user-images.githubusercontent.com/35193007/194044156-cd2f77e7-13da-4547-b96f-61665c0895dd.png) I do see all tinkers tools in the stats menu, granted yes they are white and non material specific.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback.
They show up If they are used inside an anvil, but there is no use stats. I was not able to get any use state by just using the waepons on mobs.

**Comment by KnightMiner** [comment]
Should be fixed in [3.5.3.63](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.3.63). Leave a comment if I missed something.

Note that if you use an AOE weapon like a scythe, it should only increase usage ticks by 1 per hit rather than one per mob hit, let me know if its not the case.
