### ISSUE TITLE
Shift clicking items into pants (with either Pockets or Tool Belt) makes them disappear

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#5009]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.44

### Describe your issue?

Get yourself travelers pants with Pockets
Put 1 item of any kind in the pants
Close and reopen pants ui
Shift click 32 items into pants
Close and reopen and the pants have 1 item instead of 33
https://discord.com/channels/381483562576379907/395801350731989003/1026565210238091264

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Please clarify, did you test with just tinkers and create? Did you reproduce without create?

**Comment by Insane96** [comment]
I've tested without Create and same thing happened (updated issue accordingly)

**Comment by KnightMiner** [comment]
I still have not managed to reproduce this issue. However, I did recently rewrite the internals of how we handle inventories for a couple of reasons, and reportably they fixed the issues someone else had with item deletion on shift click. 

Try on the latest public build (the one which makes shield strap an upgrade). If it still happens there, ping me on discord and I will send you a build with the new internal rewrites.

**Comment by Insane96** [comment]
Still happens with builds 63 and 70

**Comment by KnightMiner** [comment]
Should be fixed in 3.6.0.73

**Comment by Katkovb587** [comment]
> Should be fixed in 3.6.0.73

Can this bug be fixed in version for 1.16.5?

**Comment by KnightMiner** [comment]
I am currently in the process of adding new features for 1.18 and porting to 1.19, plus I have a real job. I make no promises about outdated versions
