### ISSUE TITLE
Part Builder UI is garbled and messy while using TC inside of Better MC [FORGE]

### ISSUE THREAD

**Issue by CommonITGuru** [SlimeKnights/TinkersConstruct#5010]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Mantle Version

1.18.2-1.9.27

### Tinkers' Construct Version

1.18.2-5.0.8

### Describe your issue

I installed Mantle and TC inside Better MC modpack in curseforge and everything was running smoothly until the UI got confused when working in the part builder. 

Do you know of a mod/reason that this would happen?

![image](https://user-images.githubusercontent.com/46451933/195471409-2cf3b0ba-2514-4d5f-88c6-ed3f17654ec5.png)

### Other mods

Better MC [FORGE] 1.18.2 with all the mods active + Mantle + TC

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
You have a broken texture pack. Use a texture pack actually made for 1.18
