### ISSUE TITLE
Add a config option to make repair kits repair more

### ISSUE THREAD

**Issue by ShadowDragon1848** [SlimeKnights/TinkersConstruct#5012]
### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

Hey guys,
I recently noticed that a repair kit repairs exactly the same as two ingots would do. As they cost two ingots themselves they aren´t any more efficient. A reason I heared for this was that it simple much more convenient to carry around a few kits than ingots plus a tinker station or an anvil. Which is true. But in my opinion a dedicated repair kit should be better in repairing than a simple ingot. Sure to argue with realism is a bit weird in a game with no gravity. ^^ 
When you would add a config for this people can decide for themselves if they want it or not. As long as is "easy" to add something like that (I know not much about Minecraft modding), I would really like such a feature. It would not only make more sense, but would also give an incentive to people to make repair kits. Which is in my opinion also a nice thing. 

### Suggested solution

Add a config option to make repair kits more efficient. For example make them add 25, 50, 75 or 100 percent more hit points back to a tool. 

### Alternatives considered

I mean you can do it or not. It´s not the most important thing ever, but it would be nice.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
The next update will have a config option for repair kit repair amount. Note that the cost of the repair kit is already controlled by JSON recipes, so it is possible in the current release to make repair kits cheaper (but they will always repair 2 ingots worth). The change means the 2 ingots is no longer forced

**Comment by KnightMiner** [comment]
Added in 3.6.1.85. Note that update also adds Json Things support to add custom repair kits, so you may prefer to add a new one with whatever rate you want instead of changing the default one
