### ISSUE TITLE
Tinkers' Construct Upgrades Won't Show Visually.

### ISSUE THREAD

**Issue by hacim** [SlimeKnights/TinkersConstruct#5013]
### Minecraft Version

1.18.2 

### Forge Version

40.1.80

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

When I try to add an upgrade to my tool (diamond, redstone etc.) it doesn't update/add visually to my tool.

I've tried removing all my mods, clean install, restarting PC. I have also tried with and without optifine. I run a small server with some of my friends and they don't have the same problem as me with the exact same mod list.

![Screenshot_8](https://user-images.githubusercontent.com/15189700/197697988-04326aba-d2ce-43c8-b038-06db29a61d3a.png)
![Screenshot_7](https://user-images.githubusercontent.com/15189700/197698016-4f3dd5fa-cc97-4e66-9bdf-c8f6d26c19f7.png)
![Screenshot_9](https://user-images.githubusercontent.com/15189700/197698276-98c017e4-3b58-4a49-b6f9-3a204de0036e.png)

### Other mods

JEI.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine, None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Are you using tlauncher? Thus far that is the only common thread with all the reports of this issue.

**Comment by alperozoner** [comment]
It should be fixed in tinker's construct 3.5.3.

**Comment by KnightMiner** [comment]
What makes you say that? I have made no upcoming changes that would have fixed this. I still have no idea why this happens to some people.

**Comment by KnightMiner** [comment]
Closing for lack of response. I can do nothing to debug this without information, If you are not using tlauncher, we can reopen.
