### ISSUE TITLE
Framed blocks in smeltery causes instant crash

### ISSUE THREAD

**Issue by Bludacious** [SlimeKnights/TinkersConstruct#5015]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

Game crashes when joining server / loading world if slopes from Framed Blocks mod are inside a smeltery. 

### Crash Report

https://pastebin.com/2DTsbkFC

### Other mods

All The Mods 6 - running on RedHat JDK distribution

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
This sort of bug is one I you should report to the frame mod, they are doing hacky stuff so its their problem to fix

You also should state if it happens in 1.18. This type of bug typically requires major refactors to fix, so assuming its on tinkers side its too late for 1.16.

**Comment by XFactHD** [comment]
I just stumbled upon this by chance. Since I'm releasing a critical bug fix for FramedBlocks 1.16 shortly anyway, I'll include a fix for this. I missed the state passed to `IForgeBakedModel#getQuads()` being nullable.
I'm not sure what you are implying with "doing hacky stuff".

**Comment by KnightMiner** [comment]
I mean all we do is render a block model, which per vanilla API should not crash. Thus if it's crashing I assume hacky stuff. Usually this sort of crash is more extreme than a missing null check.

**Comment by XFactHD** [comment]
Fair enough but this time it's just a dumb mistake in an (over)complicated custom baked model.

**Comment by XFactHD** [comment]
The FramedBlocks update with the fix for this crash has been released.

**Comment by KnightMiner** [comment]
Closing as fixed then
