### ISSUE TITLE
Fluids un-rendering when CC:Tweaked computer and monitor placed nearby

### ISSUE THREAD

**Issue by fatboychummy** [SlimeKnights/TinkersConstruct#5017]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

When specific blocks are placed near a tinker's construct smeltery, the lava in the tanks unrenders. Placing other mods' tanks nearby with fluid in them causes the render to work appropriately.

I am assuming this is more of a CC:Tweaked issue rather than a Tinkers issue, and have already reported there. I am creating this issue currently just to track this, in case it may not be on CC's end.

## Video demonstration

https://cdn.discordapp.com/attachments/477911902152949771/1037961268998443008/ding152.mp4 (Video too large to upload to github)

## Test with just CC:Tweaked / TConstruct
![image](https://user-images.githubusercontent.com/39929480/199899960-5b98e1a8-3e6c-45d6-8c4e-04e60533e531.png)

There should be lava in the tanks in the above image.

### Other mods

Tested only with CC:Tweaked.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Does this bug still occur on 1.18? 1.16 is pretty much done

**Comment by fatboychummy** [comment]
Not sure if this is the case in 1.18 as well, however SquidDev has confirmed this is an issue on CC's end, rather than TConstruct. Closing this for now.
