### ISSUE TITLE
Soulspeed Doubling on Soul Sand

### ISSUE THREAD

**Issue by tired9494** [SlimeKnights/TinkersConstruct#5019]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

The soulspeed modifier applies additional speed on soul sand compared to other soul blocks, but keeps the soul sand slowing effect. Vanilla soul speed removes soul sand's slowing effect and applies speed equally to all soul blocks.

Video showcasing the issue here: https://streamable.com/tfkcxm

### Other mods

No other mods

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Yeah, that is because tinkers soul speed is not vanilla soul speed, its stupid hardcoded.

#9090 will let me hack around it in a better way until I port to 1.19 and get a better hack there. Until then, whatever behavior you see is what you get.
