### ISSUE TITLE
Gold platforms and gold bars cannot be stored in cast chests

### ISSUE THREAD

**Issue by BitBlitObviMormon** [SlimeKnights/TinkersConstruct#5020]
### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

The cast chest does not accept gold bars and gold platforms as valid casts. These casts are also blocks so it might be intentional? Can an option to store at least one of each be added? I've been using regular chests over cast chests because of this.

### Other mods

none

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by BitBlitObviMormon** [comment]
Storing only one or a stack of bars or platforms would probably be best (to keep it from being an infinite platform container).

**Comment by KnightMiner** [comment]
Cast chest already forbids storing multiple stacks of a single type of cast.

Storing gold bars and platforms in cast chests seems like a fair goal, so Ill look into it, not really a bug though.

**Comment by KnightMiner** [comment]
Added in [3.5.3.63](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.3.63)
