### ISSUE TITLE
Bouncy modifier makes boots too bouncy

### ISSUE THREAD

**Issue by caljam6164** [SlimeKnights/TinkersConstruct#5021]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.2.40

### Problem description

the bouncy modifier makes boots way too bouncy, they make you bounce after only 3/4 block of a fall (even a regular jump), it's annoying and has killed me multiple times in the nether.
[video](https://youtu.be/txMJtBde1xk)

### Suggested solution

make the minimum fall distance the same way it was before, about 1 1/2 blocks of fall before you bounce

### Alternatives considered

not wearing the boots at all

### Additional context

https://youtu.be/txMJtBde1xk

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
The bouncy modifier was too good before. It is dirt cheap feather falling with no real downside. Not being able to turn it off without taking fall damage was chosen to be the downside to avoid the feather falling modifier being useless. The design for the boots is they neutralize fall damage and make you move quickly, at the cost of you sometimes moving too quickly in dangerous situations. Consider making multiple pairs of boots, one for fast travel and one for travel in risky places like the nehter. Consider also using other modifiers to help you recover from dangerous bounces, such as double jump, enderslime in a slurping helmet, or fire resistance.

We do have plans for a way to make feather falling entirely nullify fall damage (possibly via an ability, possibly via a lot of upgrade slots), so in the future you can combine that with bouncy and hold shift to prevent bouncing.
