### ISSUE TITLE
Create Above and Beyond modpack Luck enchantment not working on Vein Hammer

### ISSUE THREAD

**Issue by koalalord9999** [SlimeKnights/TinkersConstruct#5022]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

Mantle-1.16.5-1.6.147

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.0.308

### Describe your issue

Not sure if it is intended or not, but using the Luck modifier on a Vein Hammer (In my case, a stone one with diamond and 'luckier') doesn't seem to affect the drop quantity of anything. If I'm not mistaken, Luckier is basically Fortune 2? I've mind over 60 diamond ores, and I only have 60 diamonds.

Come to find out, unfortunately this is probably some kind of setting disabled in the modpack. Just incase anyone comes looking for answers I'm posting this, but it can be closed immediately.

### Other mods

Create Above and Beyond 1.3

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Luck is literally just vanilla fortune, no reason it would fail unless another mod is doing hacky stuff. That said, Create Above and Beyond has not been updated in a *long* time, so we do not support bugs in it. Update Tinkers Construct and see if the bug still happens. And actually test with no other mods installed, if you did so your other mods list should be empty.

**Comment by koalalord9999** [comment]
Thats why I added the second paragraph, because I did test it outside of the modpack, solo install, giving me a probable conclusion

**Comment by KnightMiner** [comment]
You sure its a setting that was disabled? Tinkers has no such setting. They may simply be on an old build, because they are, the pack has not updated in nearly a year and we released many 1.16 builds after that date.

Anyways, there is nothing I can fix, so  closing this. Report the bug to Create Above and Beyond.
