### ISSUE TITLE
JEI Double Fluid Amount if ModNameFormat is set to ""

### ISSUE THREAD

**Issue by shedaniel** [SlimeKnights/TinkersConstruct#5023]
### Minecraft Version

1.18.2

### Forge Version

40.1.21

### Mantle Version

1.9.29

### Tinkers' Construct Version

3.5.2

### Describe your issue

![image](https://user-images.githubusercontent.com/34910653/202868575-f3d12369-b564-4ac6-a3e0-786b3efcd895.png)

## How to reproduce
- Use JEI
- Set the `ModNameFormat` from `config/jei-client.toml` to `""`, that disables the mod name tooltip at the end
- Because the mod name is no longer the end, `IRecipeTooltipReplacement` no longer correctly withholds the correct tooltip lines

### Bonus
This also affects REI, since the mod name is added after processing the tooltip callbacks.

## Suggested Solution
I recommend just setting a custom renderer for the slot and returning the custom amount tooltip.

### Other mods

JEI

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Just don't set the format to empty. Why would you want that?

honestly surprised this is a feature, but easy enough fix.

**Comment by MaxNeedsSnacks** [comment]
I do think it's desirable to disable JEI's mod name tooltip if (a) either another mod already does it or (b) you want to do it yourself or in a custom way (for example, I made a KubeJS script that adds mod name tooltips *with* mod icons through a custom font)

But yes, either way, this should be an easy fix like you said ^^

**Comment by KnightMiner** [comment]
Fixed in [3.5.3.63](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.3.63)
