### ISSUE TITLE
Repairing any tool with slimeballs give the tool Overslime

### ISSUE THREAD

**Issue by ariosos** [SlimeKnights/TinkersConstruct#5024]
### Minecraft Version

1.18.2

### Forge Version

Version used with Stoneblock3 1.3.0

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

Using slime balls to repair a tool without Overslime gives it Overslime. In the below example, I used 2 wooden tough tool rods and 2 large stone plates. 

![image](https://user-images.githubusercontent.com/7917753/203555666-1c87bc94-a7c8-43fe-a273-4a7933a9eaa3.png)

### Other mods

Stoneblock 3 Modpack.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
![image](https://user-images.githubusercontent.com/35193007/203558363-e694eabf-f67b-4e50-9f0f-1bfc052b34ed.png)
Because overslime is also a modifier. And that's exactly how you add it.
