### ISSUE TITLE
Removing modifiers only gives one sponge per session.

### ISSUE THREAD

**Issue by TJT01** [SlimeKnights/TinkersConstruct#5025]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Mantle Version

1.18.2-1.9.31

### Tinkers' Construct Version

1.18.2-3.5.3.63

### Describe your issue

Removing a modifier using a wet sponge will only give you back a dry sponge once, and wont give you back another until you restart the world.
## Repro Steps
1) Remove a modifier using a wet sponge.
2) Get a dry sponge back.
3) Remove another modifier, again using a wet sponge.
4) Get *nothing* back

### Other mods

N/A

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.6.0.73
