### ISSUE TITLE
Removing a modifier using venom gives you a free sponge.

### ISSUE THREAD

**Issue by TJT01** [SlimeKnights/TinkersConstruct#5026]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Mantle Version

1.18.2-1.9.31

### Tinkers' Construct Version

1.18.2-3.5.3.63

### Describe your issue

Removing a modifier using either a venom bucket or a venom bottle gives you a dry sponge.

### Other mods

N/A

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.6.0.73
