### ISSUE TITLE
Rendering issue with certain items causes crash

### ISSUE THREAD

**Issue by Chburbsgeeser** [SlimeKnights/TinkersConstruct#5030]
### Minecraft Version

1.18.2

### Forge Version

40.1.79

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.2.50

### Describe your issue

There is a rendering issue with certain items, not sure which because my game crashes before I can see anything.  Typing "tr" into jei will crash and also looking at the "slimy vine" or "slimeskulls" page in the Tinkers Encyclopedia will cause the crash too.

### Other mods

I didnt have time to reproduce with any alternate testing but thought it should be known

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked the FAQ

**Comment by ChiefArug** [comment]
Send a link to the crash report/log file (use a paste site like https://gist.github.com).
No one can do much about reproducing this without either of those, as it would be a game of guessing mods you had.

**Comment by Chburbsgeeser** [comment]
forgot, sorry!
https://gist.github.com/Chburbsgeeser/58eea989fb53789f7e3b68e098379c01

**Comment by ChiefArug** [comment]
99% sure its Optifine. Don't use it, it causes all sorts of issues with mods these days.

If you want shaders use Oculus + Rubidium, they are more compatible with other mods.

**Comment by Chburbsgeeser** [comment]
works now, thank you so much! didnt even know rubidium existed, thats such a life saver!

**Comment by ShinyPorygon** [comment]
Duplicate of #4316
