### ISSUE TITLE
Game crashes on start, on server has worked before but doesnt want to now. works in singleplayer

### ISSUE THREAD

**Issue by thebikwirm** [SlimeKnights/TinkersConstruct#5031]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

[crash-2022-12-06_06.49.09-fml.txt](https://github.com/SlimeKnights/TinkersConstruct/files/10164971/crash-2022-12-06_06.49.09-fml.txt)

I reset my server recently reuploaded the mods and now tinkers want to crash not sure why tho

I have lots of mods the pack is public
https://www.curseforge.com/minecraft/modpacks/steaming-forwards-ir/relations/dependencies

### Other mods

there are two many other mods for me to list

Here the link to the list read yourself
https://www.curseforge.com/minecraft/modpacks/steaming-forwards-ir/relations/dependencies

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Magnesium, Other (specify under other mods)

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment]
This has absolutely nothing to do with tinkers. The crash log tells you that it has to do with extendedcrafting...

**Comment by thebikwirm** [comment]
no read it lower tinkers errors as well

**Comment by KnightMiner** [comment]
Not exactly. Another mod killed forge and Tinkers happened to be the first to notice when we tried to start loading. The error screams about mixins a ton and we don't use mixin, so its not us.

To be honest, not even sure Extended Crafted is the cause, Mixin crash report can be very hard to read and as I said, I don't use mixins, no experience with it. Best I can say is someone tried to mixin something client side only on a server, but I cannot tell who.

**Comment by PhweeDev** [comment]
Do you have a latest.log that I could look into?
