### ISSUE TITLE
новая версия

### ISSUE THREAD

**Issue by Emil2010** [SlimeKnights/TinkersConstruct#5032]
### Minecraft Version

1.19

### Forge Version

41.1.0

### Mantle Version

1.10.0

### Tinkers' Construct Version

3.6.0.10

### Problem description

нету версий для 1.19 и выше

### Suggested solution

добавить в страницу curseforge

### Alternatives considered

добавить в страницу curseforge

### Searched for existing enhancement?

I did not search

**Comment by ShinyPorygon** [comment]
Correct, there isn't. You can wait.
