### ISSUE TITLE
Support tin for alloying pewter if present

### ISSUE THREAD

**Issue by SpeedyZ500** [SlimeKnights/TinkersConstruct#5033]
### Minecraft Version

1.18.2

### Forge Version

40.1.21

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.3.63

### Problem description

Right now the recipe for Pewter is iron and lead, pewter is a compatibility alloy which means it inherits the recipe from another mod, which is why it is not tin and lead

### Suggested solution

Make it so that when tin is detected that it allows a tin lead combination to create pewter 

### Alternatives considered

Make it so that both tin lead combination and a iron lead combination make pewter

### Searched for existing enhancement?

Used the search bar

**Comment by KnightMiner** [comment]
I know you came from Materialis (for my reference, RCXcrafter/Materialis#12), but supposing I did not this issue could really use a bit more context.

For context:
* Current alloy is supporting Eidolon, which alloys pewter from iron and lead
* Allomancy uses tin and lead to alloy pewter
* The Eidolon dev does not feel it would be imbalanced to use tin, they just did not want to provide tin

----

By the way, if you are a Sanderson fan, check out the slurping modifier. Filling your helmet with molten metals and drinking it will give you some effects inspired by Mistborn

**Comment by KnightMiner** [comment]
Added in 3.6.0.73
