### ISSUE TITLE
Drinking new consumables does not return bottle

### ISSUE THREAD

**Issue by BitBlitObviMormon** [SlimeKnights/TinkersConstruct#5034]
### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.3.63

### Describe your issue

Drinking these consumables does not return the bottle in survival Minecraft:
- Venom Bottle
- Slime Bottle
- Skyslime Bottle
- Enderslime Bottle
- Ichor Bottle
- Bottle o' Blood
- Magma Bottle

This does not follow vanilla behavior where bottled consumables return the bottle. I also hear a crunching sound at the end of drinking these. Guess Steve is hungry for bottles now?

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.6.0.73
