### ISSUE TITLE
Hand axe on cobwebs.

### ISSUE THREAD

**Issue by Ackmard** [SlimeKnights/TinkersConstruct#5039]
### Minecraft Version

1.18.2

### Forge Version

40.1.86

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.3.63

### Problem description

I prefer to use a hand axe as a weapon but there is a "downside" of not being able to deal with cobwebs.

### Suggested solution

Allow to hand axe to break cobwebs, maybe a bit slower than a sword.

### Alternatives considered

Maybe a modifier that allows it to work as a sword on cobwebs.

### Additional context

I can pick them up with a kama/scythe but I would still need a sword or dagger to get the string.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
It's called tradeoffs my dude. If you use an axe, you don't get faster cobweb breaking, just like if you use a sword you don't get faster wood breaking.

That said, all this behavior is controlled by datapacks, so if you want you can change it your self. Just look inside the mod Jar for the JSON foles controlling the behavior, and check the Minecraft wiki for instructions

**Comment by Ackmard** [comment]
I understand, thanks for your time anyway.
