### ISSUE TITLE
SoulBound armor and off hand items are not kept in the armor and off hand slots

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#5040]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.3.63

### Describe your issue

Whenever you die with soul bound armor, the armor is placed in the first hot bar slots, instead of staying in the armor slots.  
This happens with off-hand slots too

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Fixed in 3.6.0.73
