### ISSUE TITLE
Bow enderporting ignores dimensions and their coordinate scaling

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#5046]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Mantle Version

1.18.2-1.9.31

### Tinkers' Construct Version

1.18.2-3.6.0.73

### Describe your issue

The video describes it better than I can

https://user-images.githubusercontent.com/73862885/209786213-8e9c9628-1709-4a77-98d3-6e5669839482.mp4

Arrows fired from enderporting bows will still teleport you if you change dimension, keeping you inside the same dimension but teleporting you to the arrows landing coords. Combined with the nethers coordinate scaling this is quite powerful to travel long distances.

*Even better than food!*

### Other mods

JEI

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by ChiefArug** [comment]
Shiny wants to ruin his fun and get me to say that this makes getting on the Nether ceiling laughably simple, and getting to the world border much easier (due to the 8x coordinate scaling).

**Comment by KnightMiner** [comment]
Fixed in 3.6.1.85. For the record, the fix is the same as ender pearls: ignore if the player is in another dimension.
