### ISSUE TITLE
[1.18.2] Crossbow shoots firework rockets from below the player

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#5047]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.6.0.73

### Describe your issue

When a tinkers crossbow fires firework rockets, they appear ~1.5 blocks lower than they should (crossbow height). This means that:

- When standing still and pointing forward or downward, the firework rocket(s) appear directly below the player and do not deal damage to either the player or surrounding entities
- When shooting from an elevated point or when shooting while jumping, the firework(s) appear lower than usual but are able to deal damage, and if shot slightly downward the player will hurt themselves due to the offset
- When shooting at an angle of elevation, the firework(s) may find their target, but still appear lower than usual

This does not occur with vanilla crossbows, they shoot at the normal height. This does not occur when shooting arrows out of a tinkers crossbow, they shoot at the normal height.

[Video demo](https://youtu.be/BEyaGIjnMkc)
The attached video contains Mmm dummy, JEI, and ironchest. This issue occurs without these mods.

### Other mods

Mantle, Tinkers Construct

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.6.1.85
