### ISSUE TITLE
tconstruct:insatiable_ranged doesn't increase ranged weapons damage, while tconstruct:insatiable does

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#5048]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.6.0.73

### Describe your issue

With ranged insatiable the damage doesn't increase, but melee insatiable increases the damage 

`/effect give @p tconstruct:insatiable 100 77`
Increases ranged damage
`/effect give @p tconstruct:insatiable_ranged 100 77`
Doesn't

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Fixed in 3.6.1.85
