### ISSUE TITLE
Material Master achievement doesn't complete

### ISSUE THREAD

**Issue by EdgedancerRadiant** [SlimeKnights/TinkersConstruct#5049]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

The Achievement "Material Master" still checks for Tinker's Bronze in the materials needed for it, despite the fact that Tinker's Bronze was removed in version 3.4.2.60

### Other mods

Twilight Forest

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment]
That's a rather out of date tinkers version. Can you reproduce with a newer version as well?

**Comment by EdgedancerRadiant** [comment]
Can't. Any time I try to boot up the latest version it just gives java.lang.reflect.invocationtargetexception: null

**Comment by ShinyPorygon** [comment]
You need to update forge or mantle then. Try with just tinkers and mantle and see.

**Comment by EdgedancerRadiant** [comment]
Yeah, Mantle needed updating.
The most recent version is even worse, as it says there's only 28 materials, when there's 32. It doesn't count Bamboo, and even after using every single material in the book, including Glass, Enderslime, and Rotten Flesh, it still wouldn't give me the achievement.
Should mention that the 32 are *just* the ones listed in the Tiers of Materials. That isn't counting the Glass, Enderslime, or Rotten Flesh.

**Comment by KnightMiner** [comment]
That's not entirely accurate. It still checks for ordinary bronze. As in the one that other mods add. So right now you can only get it if you add a mod that adds bronze

**Comment by KnightMiner** [comment]
Fixed in 3.6.1.85
