### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by EmojiKraft62** [SlimeKnights/TinkersConstruct#5052]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Mantle Version

I don’t use it

### Tinkers' Construct Version

Tinkers' Construct 3.0.2 for 1.16.5

### Describe your issue

Whenever I load up my game it crashes

### Crash Report

The game crashed whilst rendering overlay Error: net .minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file tconstruct-client.tomI of type CLIENT for modid tconstruct

### Other mods

![66FF6AF9-45A8-4D2A-B740-CC01EC199308](https://user-images.githubusercontent.com/121969700/210622622-0f366543-6025-4bd7-ab24-3c1645a23960.jpeg)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked the FAQ

**Comment by KnightMiner** [comment]
Try deleting your config file then restarting the game. I have seen broken syntax causing crashes. If that does not work, post the full crash report and full client config here

**Comment by KnightMiner** [comment]
Closing for lack of response. As I stated earlier, your config file is broken, and forge on that version likes to crash from broken config files. I have not seen anyone else crashing on 1.16 with this issue, so its something specific you changed, not a general issue I can fix.
