### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by bootsbloodNbeer** [SlimeKnights/TinkersConstruct#5056]
### Minecraft Version

1.19.3

### Forge Version

1.19.3-forge-44.1.5

### Mantle Version

1.18.2

### Tinkers' Construct Version

1.18.2

### Problem description

Java states that the mod needs to be 1.19 or newer

### Suggested solution

Reupdate the mod to match the Java version

### Alternatives considered

figure out a way to run Tinker's Construct without constant updating

### Searched for existing enhancement?

Used the search bar

**Comment by KnightMiner** [comment]
ah yes, I can update my mod to newer versions. I never would have considered doing that if not for this insightful issue.

You could try actually following the issue template, which would have directed you to our FAQ with the answer to this.

**Comment by bootsbloodNbeer** [comment]
my apologies im new to the mod game for MC. thank you
