### ISSUE TITLE
Delete slime island

### ISSUE THREAD

**Issue by Nagisocks** [SlimeKnights/TinkersConstruct#5057]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.3.63

### Describe your issue

I have no idea where the config for tinker want to remove slime islands, please help

### Other mods

nope

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Checked the FAQ

**Comment by KnightMiner** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-FAQ#how-do-i-configure-slime-islands
