### ISSUE TITLE
[1.18.2] Crash when trying to remove modifier from legging

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#5058]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.6.0.73

### Describe your issue

When I clicked to remove the Tool Belt Modifier from the Legging the game crashed 

### Crash Report

https://crashy.net/ybrDhfXslMdEUnaMti1A?raw

### Other mods

https://crashy.net/ybrDhfXslMdEUnaMti1A

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Fixed in 3.6.1.85
