### ISSUE TITLE
Tinker's Construct Crashing the game due to a rendering issue

### ISSUE THREAD

**Issue by The-Nyla** [SlimeKnights/TinkersConstruct#5059]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

Mantle-1.18.2-1.9.31

### Tinkers' Construct Version

TConstruct-1.18.2-3.6.0.73

### Describe your issue

something goes wrong with rendering fluids and the game crashes when trying to view some items or book pages, I don't know which items cause the issue exactly but from one of the crash logs I think the seared stone bucket is one

### Crash Report

https://crashy.net/thuiaXNggPH7JK4OFEAc

### Other mods

I'm unsure how to recreate the issue, I've tried but I can't pinpoint the mod(s) causing it, I had rubidium installed but I can't reproduce the crash with it

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment]
Did it happen with just tinkers? You said you tried with just tinkers but made no mention of it. If so give us that log, if not you'll have to try and find the mod causing this using binary searching.

**Comment by The-Nyla** [comment]
I did try with just tinkers but I could not reproduce the issue

**Comment by The-Nyla** [comment]
I'll start working on trying to find to the mod causing the issue and hopefully I find it soon

**Comment by KnightMiner** [comment]
Looks to me like a broken bucket item, meaning some mod did something wrong when registering their bucket

**Comment by The-Nyla** [comment]
I found the issue, and it's surprisingly not related to buckets at all. For some unknown reason, it's actually caused by the dynamic crosshair mod (https://www.curseforge.com/minecraft/mc-mods/dynamic-crosshair)

**Comment by KnightMiner** [comment]
Please make a report on their tracker and link it here

**Comment by The-Nyla** [comment]
https://github.com/Crendgrim/DynamicCrosshair/issues/36

**Comment by KnightMiner** [comment]
Closing this as fixed in Dynamic Crosshair, apparently a mixin conflicted with a forge patch.
