### ISSUE TITLE
Comparator output for better smeltery automation

### ISSUE THREAD

**Issue by haltalt** [SlimeKnights/TinkersConstruct#5060]
### Minecraft Version

1.18.2

### Forge Version

36.2.0

### Mantle Version

1.18.2-1.9.31

### Tinkers' Construct Version

3.6.0.73

### Problem description

I believe that it'd be great if tinkers' allowed for more automation - i'd love to make a larger scale project that'd allow me to make a all in one foundry/smeltery setup. A lot of things necessary for that are already there, for example the pretty recent addition of the alloyer. The one feature that tinkers' is lacking to allow that, however, is the detection of a lot of smeltery parameters.

### Suggested solution

Comparators are a vanilla thing, and tinkers' has a lot of blocks added. So, why not add in interactions with all of the functional ones?
Tanks already have one, and it's good.
Maybe basins and tables could be changes around a little to allow detecting how much fluid is poured, but that wouldn't be that useful, so idk.
Seared drains, ducts and controllers could output based on the amount of liquid. Drains would output based on the liquid at the bottom, ducts based on the one specified, controllers based on the sum of all liquids. The output values should be thought out so that the most important threshholds are there - nugget, ore, block, to allow for example automatically pouring out the bottommost liquid without any loss (This is already possible with chaining tables and basins, but such a solution requires quite a lot of space per pouring module.)
Seared chutes should output based on item amount, nothing revolutionary there.
Additionally, maybe some differences between smeltery and foundry could be made to stay more in line with their purposes.

### Alternatives considered

Inbuilt ways to deal with some of the problems, like the alloyer that was added. But adding too many things would be content bloat plus would need more work, and comparators are a vanilla feature that could be perfectly utilised.

### Additional context

I found some comparator-related github issues but those dated back to TiCon2.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
I feel like you should actually play the mod a bit more before making suggestions. Basins and tables already have comparator support. The only thing in your suggestion that does not is the smeltery perhipherals, since the nature of the smeltery building makes it really inefficient to update comparators via those.

Going to close this as I already have smeltery comparator support on the list of things to consider, and everything else here already exists.

**Comment by haltalt** [comment]
> I feel like you should actually play the mod a bit more before making suggestions. Basins and tables already have comparator support. The only thing in your suggestion that does not is the smeltery perhipherals, since the nature of the smeltery building makes it really inefficient to update comparators via those.
> 
> Going to close this as I already have smeltery comparator support on the list of things to consider, and everything else here already exists.

umm... I said basins and tables have support. I have tested these things, so I just suggested tables being changed (my apology, I also mentioned basins there, but they are p much ok). And 4 new blocks with support isn't that few.
But the efficiency issue is very fair.

**Comment by KnightMiner** [comment]
You said tables and basins could be changed to detect poured fluid. They already let you detect the fluid level

**Comment by haltalt** [comment]
> You said tables and basins could be changed to detect poured fluid. They already let you detect the fluid level

Don't tables output anyways if they have a cast? I didn't meant to include basins.
Whatever, I suppose stuff is already closed.

**Comment by KnightMiner** [comment]
Tables have output based on having a cast, fluid amount, and cooling time. Read the book or experiment for more details.

**Comment by haltalt** [comment]
Orrr read github :P thanks
