### ISSUE TITLE
minecraft Tconstuct crash 1.18.2 crash on load 

### ISSUE THREAD

**Issue by Anonymouwus** [SlimeKnights/TinkersConstruct#5062]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.3.63

### Describe your issue

upon load to the game, it gives the prompt:

tinkers' construct (Tconstruct) has failed to load correctly 
java.lang.reflect.invocationtargetexception: null

I attempted to remove all configs from the previous version but that didn't help the issue and to check I put the game on it's own in a pack with just Mantle and on an older version of forge (40.1.82) and that also didn't resolve the issue.

### Crash Report

https://pastebin.com/EevraR2g

### Other mods

Tinkers construct
Mantle 

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Update mantle.

**Comment by KnightMiner** [comment]
Crash says Mantle is out of date. When we asked you for versions, we want *versions* you are using. Do **not** lie to us in hopes it will get you help when literally you just need to update.

![image](https://user-images.githubusercontent.com/12155288/212565201-24be3308-1971-4cc6-8d85-17153d63c340.png)
