### ISSUE TITLE
No Overslime penalty for ranged without Slime Friend

### ISSUE THREAD

**Issue by Doomathon** [SlimeKnights/TinkersConstruct#5063]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.3.63

### Problem description

There is no attribute penalty to applying Overslime to a ranged tool (Longbow or Crossbow) that isn't a Slime Friend. While penalties exist for harvest tools, melee tools, or armor, there aren't any that apply to ranged.

### Suggested solution

Penalize some attribute (Draw Speed would be my suggestion) for applying Overslime to a ranged tool that isn't a Slime Friend

### Alternatives considered

If the existing penalty to melee attack damage for Overslime would also apply to a ranged tool, that is technically a penalty, but not a relevant one for most ranged tool builds.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.6.1.85
