### ISSUE TITLE
{Suggestion} Item Frame Modifier and Botania's Mana Mirrors

### ISSUE THREAD

**Issue by SonnyLonglegs** [SlimeKnights/TinkersConstruct#5066]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.1.88

### Problem description

I had the brilliant idea to put a mana mirror in my item frame slot to keep an eye on my mana supply while I'm away from home(without doing the thing where it covers my xp bar with blue), but it doesn't tick the item and update in real time.

### Suggested solution

I've seen it done before, like in an old mod called Random Utilities or something where an item inventory is designed to tick without a player, but I have no idea what that means besides the name. Is this doable?

### Alternatives considered

I could just carry the mana mirrors in my inventory but this seemed like such a cool idea that I wanted to share it with you guys.

### Searched for existing enhancement?

Used the search bar

**Comment by KnightMiner** [comment]
I have no plans to tick items in the modifier, the way those items are stored makes it not very efficient, and it would be a pretty major balance change with some of our modifiers.

Not sure how mana mirrors work, but if its just meant to be visual, they should work without ticking. If its not just meant to be visual, its not what item frame is made for.
