### ISSUE TITLE
Add Modifier Worktable and Modifier Tuning's Description in Guide books

### ISSUE THREAD

**Issue by Cactusstudent** [SlimeKnights/TinkersConstruct#5067]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.1.91 (Build)

### Problem description

Modifier Tuning is a large system in TiC3 and maybe will add more feature in the future, it need a documentation for players.

### Suggested solution

1. Add _Modifier Tuning_ index in _Material and You_. And add a description about how to craft and use the Modifer Worktable; how to do some "basic modifier tuning". (like _Remove Modifier_; _Sort Modifier_; _Invisible Ink_; _Visible Ink_)
2. Add _Advanced Modifier Tuning index_ in maybe _Tinker's Gadgetry_ (I don't know, maybe can in other books, this up to you), this index can tell Tinkers how to use "Advanced Modifier Tuning" (like _Extract Modifier/Ability/Upgrade/Defense_)
3. Add _Modifier Tuning_ in _Encyclopedia_. Add all the Modifier Tuning in it.

### Alternatives considered

By Adding a new book, and only description the Modfier Worktable and Modfier Tuning, but it's difficult. solution1 is more convinient.

### Additional context

For solution one
(1) I I divide modifier tuning into two. One is Basic, and another is Advanced. You can follow this, or you not.
The basic tuning is easy. You dont need to have some expensive item such as Manyullyn.
The advanced tuning is little difficult, you should travel to nether/end or need to use Smeltery to get some expensive item/material.
(2) You can write this in two books, or one. That's OK, up to you.

I'm sorry for my bad writing english. Hope you can understand these request.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Modifier worktable recipes are already in JEI, so I don't see much need to also include them in the encyclopedia (the JEI descriptions are quite sufficient). For reference outside of JEI, I will add them to gadgetry as they fit best thematically there.

I also do not see a need to divide tuning into categories, none of them need manyullyn, the most expensive you get is enderslime which is only expensive as it takes some effort to get.

Pages are added in d757069

**Comment by KnightMiner** [comment]
Added in 3.6.2.92
