### ISSUE TITLE
durability tooltip area in books extends too far to the right, sometimes resulting in garbled tooltips

### ISSUE THREAD

**Issue by esotericist** [SlimeKnights/TinkersConstruct#5068]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.18.2-1.9.43

### Tinkers' Construct Version

1.18.2-3.6.2.92

### Describe your issue

when mousing over certain parts of the books, it's possible to have both the durability tooltip and another tooltip render at the same time.

in this image, the mouse cursor is over the left edge of the `D` in durability, under the handle header. both the head and handle durability tooltips are rendering. the overlap spot for this one is only about a couple pixels wide on gui scales 2 and 3 on my 1080p display.
![2023-01-23_03 09 07](https://user-images.githubusercontent.com/1569754/214025511-a52a2bc4-248a-4767-bb20-4663aeae1438.png)

in this image, the mouse cursor is over the left half of the part builder, on the right page. both the durability and the part builder tooltips are overlapping. the overlap is most of the part builder asset. same thing also occurs for bucket assets, for casted materials.
![2023-01-23_03 09 10](https://user-images.githubusercontent.com/1569754/214025529-b3c60942-751d-430a-ae3c-352e54ed12d6.png)

this only appears to be an issue with the durability tooltips.

### Other mods

reproduced with just forge, mantle, tconstruct, json things (1.18.2-9.7.0.209) and tinkers things (1.18.2-1.0.2).

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Still happens on 3.6.4.113

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2, does not affect 1.19.2.
