### ISSUE TITLE
right-clicking to use a bow (longbow or shortbow, but not crossbow) immediately consumes an arrow

### ISSUE THREAD

**Issue by esotericist** [SlimeKnights/TinkersConstruct#5071]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.18.2-1.9.43

### Tinkers' Construct Version

1.18.2-3.6.2.92

### Describe your issue

right-clicking with the longbow (and also the shortbow from tinkers things) always consumes an arrow instead of only doing so when successfully firing like vanilla bows. this means rapid right clicking deletes arrows.

### Other mods

reproduced with just forge, mantle, tconstruct, json things (1.18.2-9.7.0.209) and tinkers things (1.18.2-1.0.2).

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.6.3.111.
