### ISSUE TITLE
Game crashes on startup with JSON Things 0.4.5/6

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#5078]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.2.92

### Describe your issue

Game crashes at startup (with no warning that the game requires Rhino, only the logs) when using JsonThings 0.4.5/6.

Reverting to JsonThings 0.4.2 fixes the issue

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Issue appears to be crossposted already at gigaherz/JsonThings#15. I will be able to look into updates for the next Tinkers' Construct build, though gigaherz said he would look into restoring backwards compatibility with the APIs I used.

**Comment by KnightMiner** [comment]
Fixed in 3.6.3.111.
