### ISSUE TITLE
Shields continue to block damage after breaking while holding right click

### ISSUE THREAD

**Issue by snackerpirater** [SlimeKnights/TinkersConstruct#5079]
### Minecraft Version

1.18.2

### Forge Version

40.1.93

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.2.98

### Describe your issue

If the shield breaks while the player is blocking, the shield continues to block damage. Works with anything that has blocking on it. Trying to block again after un-blocking doesn't work.
![image](https://user-images.githubusercontent.com/107385468/216779602-65653761-3706-4637-9d08-3b646bf020f1.png)

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Fixed in 3.6.3.111.
