### ISSUE TITLE
Unable to damage mobs with fists while chestplate is equipped

### ISSUE THREAD

**Issue by snackerpirater** [SlimeKnights/TinkersConstruct#5080]
### Minecraft Version

1.18.2

### Forge Version

40.1.93

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.2.98

### Describe your issue

While a Plate/Traveler’s Chestplate is equipped, you are unable to damage mobs by punching. Happens even with Ambidextrous on the Chestplate.

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Fixed in 3.6.3.111.
