### ISSUE TITLE
loss of resources from ores when smelting and pulling out at the same time

### ISSUE THREAD

**Issue by howardxu23** [SlimeKnights/TinkersConstruct#5081]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.18.2-1.9.43

### Tinkers' Construct Version

1.18.2-3.6.2.92

### Describe your issue

When you bulk smelt large amounts of raw ore blocks/raw ore into a large full smeltery/foundary, then pull the results out fast enough at the same time , there is occasionally loss of motlen metal from the smelting.

It is the easiest to reproduce with modded pumps that can extract the fluid fast enough, but I managed to get it to happen with enough drains and faucets on both smelter and foundary(about 20 on a 6x6 smelter all dumping)

### Other mods

Pipez, mekanism(fluid ducts), trash can

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Nothing in the smeltery code would lead to the behavior you are describing. When you melt an item, the fluid is immediately put in the tank, not less than the fluid, the full amount. The only way you could get less fluid is if somehow the tank was filled (not drained) at the exact instant melting finishes, which should be impossible as the game is not threaded in that way.

In other words, I need more information about how to reproduce this issue you are seeing, as you are the first person to ever experience this.

----

Now, when you bulk smelt in a **foundry**, it is possible you lose some byproducts when the foundry is full. That is simply a limitation of output detection. Plan accordingly. I highly suspect what you saw was loss of byproducts, not loss of regular output making the smeltery entirely unaffected.

**Comment by KnightMiner** [comment]
Closing for lack of response, going to assume your issue is foundry byproducts unless you give me more information.
