### ISSUE TITLE
Seared Cobblestone Drains drop Seared Brick Drain

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#5082]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.2.92

### Describe your issue

Breaking a Seared Cobblestone Drains drop Seared Brick Drain

### Other mods

Some, but I don't think they can break loot tables

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Fixed in 3.6.3.111.
