### ISSUE TITLE
Stoneshield trait consuming stone but not giving the shield

### ISSUE THREAD

**Issue by nonatee** [SlimeKnights/TinkersConstruct#5087]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

The stoneshield trait consumes stone broken but does not actually give the shield and uses the durability.  I tried breaking any type of stone, including vanilla but the issue persisted.

### Other mods

The enigmatica 6 modpack.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Stoneshield is chance based, the higher the level the more likely it is to apply, try with a higher level, aka more parts of it. It works fine for me with just tinkers.

**Comment by KnightMiner** [comment]
Closing for lack of response.
