### ISSUE TITLE
Duplication bug involving any held tool with an inventory modifier

### ISSUE THREAD

**Issue by NyanMC** [SlimeKnights/TinkersConstruct#5088]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

Using the number keys allows you to move the tool with the opened inventory out of its hotbar slot, allowing you to drop the tool and duplicate the items.

Steps to reproduce:
Acquire a tool (not armor, sorry pockets modifier) with a modifier capable of storing items, such as a crossbow with bulk quiver
Open the tool's inventory GUI, insert items
Press the number key corresponding to the hotbar slot the tool is located, while hovering over any other inventory slot (e.g. press 1 if the item is in hotbar slot 1)
Drop the tool without closing the inventory
Take out the items and pick back up the tool, you have just duplicated the items

### Other mods

Just Tinkers Construct and Mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Your steps to reproduce forgot "drop the tool without closing the inventory"

**Comment by NyanMC** [comment]
oops, fixed

**Comment by KnightMiner** [comment]
Fixed in 3.6.4.113
