### ISSUE TITLE
Tall slimy grass issue

### ISSUE THREAD

**Issue by haltalt** [SlimeKnights/TinkersConstruct#5089]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

Scythe doesn't harvest tall slimy grass in a 3x3 area. Also tried hammer and expanded pickadze.
EDIT: Seems to also happen /w slimy ferns.

### Other mods

Starlight, ferritecore, MmmMmmMmm (mod for target dummies), create and flywheel.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
Tall grass doesn't appear to have a "proper tool" set for them, which appears to be why

**Comment by KnightMiner** [comment]
Fixed in 3.6.4.113
