### ISSUE TITLE
Mushroom and Beetroot take way too long to melt in the smeltery

### ISSUE THREAD

**Issue by NyanMC** [SlimeKnights/TinkersConstruct#5090]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

The melting recipes for Beetroot into Beetroot Soup and Mushrooms into Mushroom Stew take 83 seconds each. This occurs in both JEI's tooltip and when actually melting the items. I was told to open a github issue about it due to possibly being an error.

![image](https://user-images.githubusercontent.com/44331238/219971162-c574a985-7ceb-44b5-af09-5524c4f45296.png)

![image](https://user-images.githubusercontent.com/44331238/219971157-48f22f41-c304-4687-9bba-acccce1eb519.png)

### Other mods

Tinkers Construct and Mantle (versions are already listed above)
JEI (10.2.1.1002) was used for convenience to get a screenshot of the tooltip melting error, I did test the issue without it and it still occurred when melting beetroots

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.6.4.113
