### ISSUE TITLE
Dagger modifier duping (And a proposal to fix it)

### ISSUE THREAD

**Issue by RaiXgame** [SlimeKnights/TinkersConstruct#5093]
### Minecraft Version

1.18.2

### Forge Version

Forge: 1.18.2-40.2.0

### Mantle Version

Mantle: 1.18.2-1.9.43

### Tinkers' Construct Version

 TConstruct: 1.18.2-3.6.3.111

### Describe your issue

Upon modifying daggers, you can stack up to two of the same type to make modifiers cheaper.
When using the modifier workbench to extract the modifiers from the daggers, you can remove it from both at the same time (giving you one modifier crystal) or you can remove it from both at separate times (giving you two modifier crystals).
Stack the daggers, modify them together, un-stack them, extract their modifiers separately, re-modify the daggers (now together again), repeat the process.
As enderslime crystals are farmable and sponged don't dissapear, all modifiers tool/weapon modifiers (and abilities) can be duped this way.
The screenshots will show the steps to repoduce it.

1. Craft daggers
![image](https://user-images.githubusercontent.com/84103201/220447607-cb82d32f-0b7e-4701-8f29-676372c496b5.png)

2. Modify them.
![image](https://user-images.githubusercontent.com/84103201/220447743-a01987a2-b4fe-47f3-9e1f-ebbc35558c01.png)

3. Un-modify them separately.
![image](https://user-images.githubusercontent.com/84103201/220448275-97473902-6597-4832-ba92-86cdf88fcd92.png)
![image](https://user-images.githubusercontent.com/84103201/220448141-9fa6bc0e-d330-4d4d-a151-c2171d02acae.png)

4. Re-modify them.
![image](https://user-images.githubusercontent.com/84103201/220448456-2adba5df-8e82-4ae4-b6bf-a4b691a0c529.png)

5. Repeat the process.

This simple way, you are capable of duping modifiers that can be put to any other tool (and that can be quite costly).

**Suggested solution**
To add some coherence between the different tools and the way to modify them, I would say that modifying a single dagger should give you a "damaged" or "partially used" modifier crystal, that could only give a modifier to another dagger. Modifying the double daggers however, would not give you any extra crystals. When translating this to the modifier workbench, a single dagger gives you the "damaged" version, ans the two daggers together give you the normal verison of the crystal.
Upon combining (I suppose in an anvil) two "damaged" crystals together, they would turn into the normal version.
To avoid having to add yet another item, maybe using durability as the way to indicate how is the crystal doing (2/2 = full crystal, 1/2 = damaged crystal) could work.
Just removing modifier extraction from the daggers could also work.

### Crash Report

No crash

### Other mods

JEI: 1.18.2-9.7.1.255

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
This has already been talked about in the discord and a plan is in place. I will keep this marked as open so people know it has a plan already to be fixed.

**Comment by KnightMiner** [comment]
Already fixed in https://github.com/SlimeKnights/TinkersConstruct/commit/be7b23a6b05f26534d11285088d65ec5e786c434

When fixing bugs, it's best to avoid adding a huge overcomplicated mechanic. A simple requirement that the dagger has stack size 2 is enough

**Comment by RaiXgame** [comment]
Alright, I posted here knowing it was discussed (it was me who brought it up, mgmah64). I just wanted to put it here to avoid others the making of this report.

**Comment by KnightMiner** [comment]
Fixed in 3.6.4.113
