### ISSUE TITLE
JEI usability issues - mostly anvil related

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#5096]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.2.92

### Describe your issue

I've noticed a few issues with JEI integration, mostly regarding the Tinker's Anvil:  
- If the ingredients are in your hotbar instead of your inventory, they will be listed as "Missing Items", but it's a bit strange as one item in the list will work:  
![2023-02-27_17 27 29](https://user-images.githubusercontent.com/1998392/221500590-a4f35e83-71d5-4cce-b69e-ff5aab48cb67.png)
- Pressing the plus that moves items into the Tinker's Anvil doesn't actually move the items, or puts them in weird positions, for example when crafting my cleaver into the Glowing modifier:  
![2023-02-27_17 28 59](https://user-images.githubusercontent.com/1998392/221500840-27a02729-add8-4325-9ac9-d7d710c11c4c.png)

### Other mods

JEI

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by MarioSMB** [comment]
JEI doesn't seem to be seeing the tinker slots properly, as one time it actually put one of the crafting items into my off-hand!

**Comment by KnightMiner** [comment]
Fixed in [3.6.4.113](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.6.4.113), just forgot to label it so it never got closed.
