### ISSUE TITLE
Part Builder plays sound for every item crafted

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#5097]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.2.92

### Describe your issue

Crafting multiple items at once in the Part Builder will overlap the sawing sound that plays. When crafting an entire stack of wooden repair kits at once for example the sound will be deafening!

### Other mods

N/A

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
This is true, but not sure there is anything I can do about it. Low priority anyways.

**Comment by KnightMiner** [comment]
Fixed in 3.7.0.152 for 1.18.2
