### ISSUE TITLE
Skeleton Arrow Shield Pickup Glitch (featuring Strays with Uncraftable Tipped Arrows)

### ISSUE THREAD

**Issue by CybernetCatgirl** [SlimeKnights/TinkersConstruct#5098]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

Tinkers' Construct shields seem to allow you to lift Skeleton arrows once they have been deflected, even without modifiers applied. This is not vanilla behavior, as in vanilla, you cannot pick up arrows deflected by shields. I have not been able to replicate this glitch with CONSISTENCY, but it seems to happen where an arrow will either fly farther than normal or flat-out teleport to a further location (likely calculated as a stronger deflection but shown as a weaker one, leading to teleportation visual?). Worse, this also allows the obtaining of Uncraftable Tipped Arrows, based on my testing with Strays. I have not managed to get this to work with a slimestaff with Blocking as a modifier, however.

### Other mods

Only mods were Forge, Mantle, and Tinkers' Construct.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Fixed in 3.6.4.113
