### ISSUE TITLE
Slurping can crash the game the first time a fluid is tried upon starting a world?

### ISSUE THREAD

**Issue by CybernetCatgirl** [SlimeKnights/TinkersConstruct#5099]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.19.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

While holding a shield in the offhand, and attempting to drink from a slimestaff with Slurping in the main hand, the game crashes due to a ConcurrentModificationException.
Linked is a copy of a Google Doc, which I directly copy-pasted the crash log into.

### Crash Report

https://docs.google.com/document/d/1TBG4cxOqj0j-eNVMM1EP0B1K7lT2p7lbW8nKSjVizko/edit?usp=sharing

### Other mods

Solely Forge, Tinkers' Construct, and Mantle.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by CybernetCatgirl** [comment]
Update: Does not actually seem to require shields, or ANYTHING in the off hand whatsoever. Testing with other fluids now.

**Comment by KnightMiner** [comment]
I somehow doubt stuff in the offhand causes it to happen, more likely its just a random occurance. 89a8fbd should prevent it from happening though.

**Comment by KnightMiner** [comment]
Fixed in 3.6.4.113
