### ISSUE TITLE
inventory profiles next compatibility problem

### ISSUE THREAD

**Issue by joinmod** [SlimeKnights/TinkersConstruct#5100]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

in modpack age of fate, i saw bug when you shift click in crafting station to quick move items, somehow it also quick moves items 1-2 rows under mouse pointer.
it affects all tconstruct inventory...
i created new minecraft instance with same forge and mod version and found out ipn interfere only with tconstruct

#4865 
blackd/Inventory-Profiles#295

### Other mods

inventory profiles next 1.9.2
kotlinforforge 1.17.0-obf
libIPN 2.0.2

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
1.16 is pretty much unsupported at this time, there likely will be nothing done on our end to fix it due to that.

**Comment by joinmod** [comment]
it happening also at 1.18 by pervious report in here

**Comment by ShinyPorygon** [comment]
If this still occurs in 1.18.2, and there is already a report then it has already been looked into/will be looked into for 1.18.2. But this report is for 1.16.5. Closing this due to 1.16.5 being unsupported.
