### ISSUE TITLE
Stacking of items without 64 stack in Pockets leggings and other inventories

### ISSUE THREAD

**Issue by CybernetCatgirl** [SlimeKnights/TinkersConstruct#5101]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

When accessing any Tinkers' Construct tool with a custom inventory (such as leggings with pockets, or any add-ons that give custom "bags" such as Tinkers' JSON Things), you can take items with identical NBT data and stack them to 64. This pays no mind to stack size limits, so you can stack items like Eggs, vanilla tools, or tinker tools up to a max stack of 64. This does check for NBT data, however--tools with different names, enchantments, modifiers, or durability, among other things, will not stack. However, this allows for--for example--easy transfer of large quantities of cake.

These "illegal stacks" are, however, limited. They can only be moved "completely" with shift-click, as attempting to move them with just the mouse will result in only placing a "legal" stack in the inventory. Additionally, this behavior prevents them from being used for modifier duplication in things such as the Tinker Anvil or Modifier Station due to said stations forcing the "moved" units to respect stack limits.

### Other mods

Only done with Forge, Tinkers' Construct, and Mantle.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
This is actually a Mantle issue, see SlimeKnights/Mantle#197

**Comment by KnightMiner** [comment]
Fixed in Mantle 1.9.45
