### ISSUE TITLE
Dagger stacking issue with first application of Tank modifier

### ISSUE THREAD

**Issue by CybernetCatgirl** [SlimeKnights/TinkersConstruct#5102]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

Upon first applying Tank to daggers, and filling one of the two with fluid, the two daggers will NOT stack until the other of the pair has been used to hold fluid at least once. This happens even if the first dagger is emptied, and the bug restarts again if Tank is removed and reapplied.

### Other mods

Solely done with Forge, Mantle, and Tinkers' Construct.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Fixed in 3.6.4.113
