### ISSUE TITLE
Piercing arrows lock up the game when "reflected" by shields

### ISSUE THREAD

**Issue by CybernetCatgirl** [SlimeKnights/TinkersConstruct#5103]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

DISCLAIMER: Though I also experienced this bug approximately one hour after, this was still first discovered by Trollofduty007#5482 on Discord.

Arrows shot from Piercing crossbows, when reflected by a shield with Reflecting in the first 2 seconds of putting up the shield (ignoring other bugs with Reflecting), the game proceeds to blare the "shield hit" sound effect repeatedly, locking up and becoming unplayable. 

If the game does continue to run in brief spurts, it results in interesting results, such as a FPS less than one, and enemy AI seeming to cease to exist. However, given that the game often tends to simply freeze, and require a close, this is difficult to test.

### Crash Report

Did not generate a crash log, but did generate exit code -805306369, an "out of memory" exit code.

### Other mods

Tested and confirmed with only Forge, Mantle, and Tinkers' Construct.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
There is no duplication, its all 1 arrow. It just locking up the game thread. Seems to be an issue with the forge event.

[9d79ac1](https://github.com/SlimeKnights/TinkersConstruct/commit/9d79ac1792c0342eb340b0d4d683f5c5711db28a) fixes it by just not running my logic if the owner is the same as the reflecting entity, as I can guarantee that will be false after reflecting arrows

**Comment by KnightMiner** [comment]
Fixed in 3.6.4.113
