### ISSUE TITLE
[1.18.2] Using Glass Bottles on a Honey Tank gets you water bottles 

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#5104]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

When I try to bottle Honey from the Tank, I get a water bottle.
![image](https://user-images.githubusercontent.com/44974827/223301752-0e6b90a0-0b9b-461a-8eda-11da2ac1cb5c.png)
![image](https://user-images.githubusercontent.com/44974827/223301786-021a56f2-8549-44b2-b443-6260aa21d87c.png)

### Other mods

Create
Rubrium 

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Sounds like a typical case of someone misusing the vanilla tags for things that are not vanilla water or vanilla lava. Luckily I can just not use those tags there, bit surprised that one made it past detection for so long.

**Comment by KnightMiner** [comment]
Fixed in 3.7.0.152 for 1.18.2
