### ISSUE TITLE
Bow Accuracy

### ISSUE THREAD

**Issue by yeetgrenadewastaken** [SlimeKnights/TinkersConstruct#5107]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Mantle Version

Mantle-1.18.2-1.9.43.jar

### Tinkers' Construct Version

TConstruct-1.18.2-3.6.3.111.jar

### Problem description

some weapon parts that affect accuracy like manyullyn bow limbs and rose gold grips have way to drastic of an impact on accuracu.

### Suggested solution

Make effects that boost or hurt accuracy be multiplied by (1-current accuracy). That way, instead of +0.3 accuracy turning your bow into a perfectly accurate weapon and -0.3 making it unusable beyond 14 centimeters, they would have a more reasonable effect. Additionally, stacking two accuracy buffs wouldn't just automatically make it laser-accurate.

### Alternatives considered

Do a flat across the board reduction to effects that impact accuracy.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
I feel like part of what you are seeing is just the impact of velocity on accuracy, not high inaccuracy making bows unusable. I might need to rework that as low accuracy tends to already exist on high velocity materials.

Use the `/tconstruct` command to set the accuracy stat on a bow directly and give me more info on if a same accuracy bow still has such the extreme range you are seeing.

**Comment by yeetgrenadewastaken** [comment]
What you said about velocity messing up accuracy is true and seems quite
extreme from my testing, however the issue of weapon parts having too big
of an impact on accuracy still remains. A single weapon part like the rose
gold bow grip takes your bow from being about as accurate as in vanilla to
being laser accurate at all ranges. The equivalent of putting two manyullyn
limbs on your bow (-0.3 accuracy) makes it inconsistent at hitting a
normal-sized mob beyond about 10 blocks.

**Comment by KnightMiner** [comment]
3.6.4.113 makes velocity no longer directly affect inaccuracy, may make more changes later.

**Comment by KnightMiner** [comment]
I'm going to go ahead and close this issue. If you want to have a more comprehensive discussion about accuracy on Discord we can potentially come up with a solution, but otherwise I'll stick with the original system for simplicity. Such changes would likely not be applied until 1.20 anyways.
