### ISSUE TITLE
Filled/drained message cannot be translated

### ISSUE THREAD

**Issue by koh-gh** [SlimeKnights/TinkersConstruct#5108]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

The message displayed when adding or removing liquid from the Tinker's fluid tank is not translated. Liquid names are translated.

The screenshots below are in Japanese, but I got the same result with other languages, so I don't think it's a problem with the language file. (I have confirmed the same results in Chinese and Polish)
![2023-03-09_20 02 55](https://user-images.githubusercontent.com/36918206/224009896-ea8477f5-dca2-4fec-a5c0-2b9e8cc117d8.png)
![2023-03-09_20 03 07](https://user-images.githubusercontent.com/36918206/224009921-51d8cdce-07b7-405b-b94d-179db1a9071a.png)

I believe the translation keys are `block.tconstruct.tank.drained` and `block.tconstruct.tank.filled`, and the translations were applied correctly in 1.16.

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Those translations strings are Mantle, not tinkers. They are not special, you have an old key.
