### ISSUE TITLE
Seared/Scorched Ladder continuity

### ISSUE THREAD

**Issue by AemonJape** [SlimeKnights/TinkersConstruct#5109]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Problem description

I made my foundry right above my smeltery, and built a continuous ladder. However, the ladder does not recognize each other, and I cannot get up top. 

### Suggested solution

I suggest a change so that the two ladders are interchangable and connect smoothly.

### Alternatives considered

The indented ladders are so useful, consider making some more with other textures like wood or stone.

### Additional context

![2023-03-10_18 48 39](https://user-images.githubusercontent.com/83991998/224285943-543035cc-f122-4c23-b403-dba9cf48517f.png)

### Searched for existing enhancement?

Used the search bar

**Comment by KnightMiner** [comment]
Fixed in 3.6.4.113
