### ISSUE TITLE
Sprint jumping and crouching stops player midair

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#5110]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

Leggings with the step-up modifier have a bit of an issue currently: if you're sprinting and jump then press crouch while midair you'll stop moving forward jarringly.

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Step up is not controlled by Tinkers, its a Forge attribute. Any odd behavior you see is on their side.

You probably are seeing another sideeffect of vanilla step height being used for things besides step height. I recommend creating some vanilla armor with the attribute and reproducing the issue, then reporting it to forge.

**Comment by MarioSMB** [comment]
Would you mind mentioning which attribute that is so that I can test and report it to them?

**Comment by KnightMiner** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/generated/resources/data/tconstruct/tinkering/modifiers/step_up.json

**Comment by MarioSMB** [comment]
This has been fixed upstream, though it will only apply to 1.19 versions of Forge.
