### ISSUE TITLE
deletion bug with shift clicking into tool inventories 1.16.5

### ISSUE THREAD

**Issue by Katkovb587** [SlimeKnights/TinkersConstruct#5111]
### Minecraft Version

1.16.5

### Forge Version

36.2.35

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

Get yourself any pants with Pockets from tinker's construct mod
Put 1 item of any kind in the pants
Close and reopen pants ui
Shift click 32 items into pants
Close and reopen and the pants have 1 item instead of 33

p.s. i know this bug fixed in 1.18.2.

### Other mods

with and without mods

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Searched closed issues

**Comment by Katkovb587** [comment]
I know that the bug has been fixed in newer versions. I'll just leave this post as a reminder that the bug still exists in this version. 
Here is a link to the original post: https://github.com/SlimeKnights/TinkersConstruct/issues/5009

**Comment by ShinyPorygon** [comment]
Well as you said this bug has been fixed in newer versions. 1.16 is no longer supported however. And is missing quite a lot of features vs 1.18.
