### ISSUE TITLE
Crafting Station + Colossal Chests Duplication Glitch

### ISSUE THREAD

**Issue by Demosthenes178** [SlimeKnights/TinkersConstruct#5112]
### Minecraft Version

1.18.2

### Forge Version

40.1.93

### Mantle Version

1.18.2-1.9.43

### Tinkers' Construct Version

1.18.2-3.6.3.111

### Describe your issue

Crafting operations in a crafting station that is sharing an inventory with a colossal chest (from colossal chests, via either their core or interface blocks) allows crafting of more results than there are inputs for, and will crash the client on attempting to craft an entire stack. 

### Other mods

ColossalChests-1.18.2-1.8.3

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by ShinyPorygon** [comment]
If the mod crashes we need a crash report.
