### ISSUE TITLE
Recipe type "damagable_melting" not getting registered as a tag for crafttweaker to use

### ISSUE THREAD

**Issue by rjames0820** [SlimeKnights/TinkersConstruct#5113]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

I am currently adding custom melting recipes using crafttweaker, went on to test out any item that can be damaged (eg knives from farmer's delight) and for some reason the <recipetype:tconstruct:damagable_melting> doesnt work, even though the <recipetype:tconstruct:melting> does work. Doing a /ct dumping of the recipe types, I found out that it is not detecting that specifically at all, all the other recipe types like basin, alloying and such are detected except for damagable melting, went to check the wiki and the json files of the mod and i am doing the format right and the main tc mod has no problems with it, the recipe type seems to be like it is not "public" or something.

### Other mods

Crafttweaker
Farmer's Delight as an example

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Magnesium

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
Crafttweaker isn't fully supported. And last I knew is partially commented out due to it being broken. Your better bet is to use datapacks. A fantastic resource given to you by vanilla!

**Comment by rjames0820** [comment]
never tried using the datapacks folder yet, im sure it will work and a solution for this problem, i just find it weird though that while i could make all tc recipes with crafttweaker (and i am kinda trying to put some support with creating recipe making work with tc), just one recipe tag is not detected with crafttweaker. I'll consider using the classic datapacks, would be nice though if you could figure out whats wrong with tc and ct, its okay if you dont

**Comment by KnightMiner** [comment]
The recipe type is registered with vanilla and works with vanilla. If it does not work with craft tweaker then craft tweaker is doing something wrong or you spelled it wrong. We register it no differently from our other types. Nothing we can do, talk to the craft tweaker devs.
