### ISSUE TITLE
Config option to allow foundry to alloy

### ISSUE THREAD

**Issue by Hexasphere0** [SlimeKnights/TinkersConstruct#5116]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Problem description

I want the foundry to be able to alloy in my modpack.

### Suggested solution

Give a config option to users allowing the foundry to alloy.

### Alternatives considered

.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Not happening. It alloying would conflict with byproducts, and is a feature used by many players for an alloy free tank. I'm not letting modpacks subvert expectations that much, I've dealt with player responses from modpacks making such major changes before and never care to do so again.
