### ISSUE TITLE
Pam's HarvestCraft 2 intergration

### ISSUE THREAD

**Issue by Adam4CZ** [SlimeKnights/TinkersConstruct#5118]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.40

### Problem description

Hi,

I have a Forge server with several mods that I play on with friends. The modpack also includes TConstruct 3 and Pam's HarvestCraft 2.
I ran into a problem with the **Scythe** tool, which is supposed to be able to harvest and replant crops. I first tried it on vanilla crops, where it works without problems. But unfortunately I found that it doesn't work on crops from Pam's HarvestCraft mod. At first I thought this tool could only harvest and plant vanilla crops, but then I tried crops from the Thermal Expansion mod (which is also a part of my modpack), and it can harvest and plant those as well.

Would it be possible to add support for the HarvestCraft mod as well?

Thank you.

### Suggested solution

Add support with Pam's HarvestCraft 2 mod to harvest and plant its crops (primary for the Scythe tool) if it would be possible.

### Alternatives considered

None

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Pam's crops are not tagged as crops. Thermals works because they are tagged as crops, as can be seen in the images.
![image](https://user-images.githubusercontent.com/35193007/228612545-46e236eb-ed42-4f14-9ec4-3c338d136502.png)
![image](https://user-images.githubusercontent.com/35193007/228612607-1e976344-e119-4621-8240-d0bb4c9fdbf8.png)
 There is nothing that can be done on Tinkers end. You can add tags to the crops with datapacks (probably) but this would have to be fixed on Pam's end. Because mostly every other mod automatically works, and was checked.

**Comment by Adam4CZ** [comment]
Ok, thank you so much @ShinyPorygon for the explanation.
It didn't occur to me that the mod author didn't do this. I'll try using datapack to fix it and report it to the mod author.
Thanks again.

**Comment by Adam4CZ** [comment]
Hi @ShinyPorygon 

I managed to add tags to all crops from HarvestCraft using datapack and harvesting crops using Scythe works.
However, planting does not work, while harvested crops can be directly planted. No more tags come to my mind when comparing with e.g. Thermal series crops (where the planting works well).

![screenshot 20230330-1](https://user-images.githubusercontent.com/15090021/228691801-f781cc33-516b-481d-b4c4-74c782e2b391.png)
![screenshot 20230330-2](https://user-images.githubusercontent.com/15090021/228691626-01a0cfd6-f043-474c-aa06-406499cc9110.png)

Do you know what could be causing this, or if there is any way to fix it?
Thanks

**Comment by KnightMiner** [comment]
you need to put the seeds in the seed item tag.

**Comment by Adam4CZ** [comment]
> you need to put the seeds in the seed item tag.

I checked that and it seems to me that the seeds (and crops) are fine, or am I missing something?

Seeds:
![bean_seed](https://user-images.githubusercontent.com/15090021/228974471-4dedfa58-1af1-409b-bccc-8c69eb18d571.png)
![onion_seeds](https://user-images.githubusercontent.com/15090021/228974521-952fd08e-e531-4fbb-8ee2-d87eb2181e45.png)

Crops:
![bean](https://user-images.githubusercontent.com/15090021/228974579-c5861372-88b2-45f5-9a74-9e23266b6adc.png)
![onion](https://user-images.githubusercontent.com/15090021/228974637-19b0b7eb-4480-473c-a68f-86a537e22ca4.png)
![potato](https://user-images.githubusercontent.com/15090021/228975227-678a3236-39ab-419d-bb1b-e2d66bec14e1.png)


Only what I found out that HC crops also have block tags (like the potato from vanilla MC). I think it's because they can be planted directly into the ground versus crops from Thermal series.

**Comment by KnightMiner** [comment]
Unless Pams is not dropping seeds as part of their loot tables (highly unlikely), I see no reason it wouldn't work if properly tagged. What you have looks like it should work, and the fact it works for vanilla means there is no bug in Tinkers.

That said, I recommend moving this discussion over to Discord, unless you confirm there is an actual bug in Tinkers. This issue tracker is meant for discussing bugs with the mod, not for debugging datapacks that are not working. We have channels on Discord for discussing that sort of stuff.

**Comment by Adam4CZ** [comment]
Solved on Discord.
It can be fixed by adding the `tconstruct:seeds` tag to all crops that HC2 has.

![fixed](https://user-images.githubusercontent.com/15090021/229598261-100d4cfa-1a96-4f45-b76c-a4f4af2eb7a0.png)

Basically the whole issue is due to a combination of crops not dropping seeds (they don't have them in loot-tables) and the crops themselves not being defined as seeds.
Issue with harvesting is easy to solve just by adding each crop block to basic `minecraft:seeds` tag (solved earlier) and for the re-planting it is necessary to add each crop to `tconstruct:seeds` tag OR add crop seeds of the loot-tables of each crop block.

Thank you for your help. It was not your fault.
