### ISSUE TITLE
Faucet's not working

### ISSUE THREAD

**Issue by Rajala1404** [SlimeKnights/TinkersConstruct#5120]
### Minecraft Version

1.16.5

### Forge Version

36.2.28

### Mantle Version

1.16.5-1.6.127

### Tinkers' Construct Version

1.16.5-3.2.1.296

### Describe your issue

I have build a giant Smeltery but the Faucet's do not working but the smeltery smelt and work only the faucet's not here is a screenshot
![screenshot](https://user-images.githubusercontent.com/115874847/229255722-4106c6d1-b278-417f-86a0-51e6038e7c30.png)

### Other mods

Modpack: [SkyFactory One](https://www.curseforge.com/minecraft/modpacks/skyfactory-one) by darkosto
Modpack Version: 1.0.5
Personal Changes:
Switch from JourneyMap to Xaeros Minimap & Worldmap (Xaeros_Minimap_23.3.2_Forge_1.16.5, XaerosWorldMap_1.29.4_Forge_1.16.5)

Added Mods: 
Carry On (carryon-1.16.5-1.15.5.22)
FTB Essentials (Forge) (ftb-essentials-1605.1.5-build.32)
FTB Ultimine (Forge) (ftb-ultimine-forge-1605.3.1-build.45)
Light Overlay (Rift/Forge/Fabric) (light-overlay-5.8.1)
Magnesium/Rubidium Dynamic Lights (dynamiclightsreforged-mc1.16.5_v1.0.1)
Magnesium/Rubidium Extras (magnesium_extras-mc1.16.5_v1.4.0)
Rubidium (rubidium-0.2.11)
Saturn (saturn-mc1.16.5-0.0.3.jar)
Precise Block Placing (preciseblockplacing-1.07+1.16.5.jar)
Quark (Quark-r2.4-322.jar)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched closed issues

**Comment by KnightMiner** [comment]
Faucets go on drains. Read Mighty Smelting.

**Comment by Rajala1404** [comment]
> Faucets go on drains. Read Mighty Smelting.
How i read that when i can't craft it
![grafik](https://user-images.githubusercontent.com/115874847/229256157-f822a75b-b876-4362-9e2e-4adef2cf9920.png)
Edit i make it with the smelter

**Comment by DreaminBoi** [comment]
nono, you need the drains block, then place the faucet infront of the drains block
