### ISSUE TITLE
Disable feature

### ISSUE THREAD

**Issue by felipeleite5w** [SlimeKnights/TinkersConstruct#5121]
### Minecraft Version

1.16.5

### Forge Version

Latest for 1.16.5

### Mantle Version

Latest for 1.16.5

### Tinkers' Construct Version

334335

### Describe your issue

Hi, I wanna know if its possible to disable right click block placing. It will be very useful for me, and if its possible to do it in older versions. Thanks for reading =)

### Other mods

none

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Magnesium, Optifine, Performant, Other (specify under other mods), None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
I have absolutely no clue what this is supposed to be for. But granted it's for 1.16 which is unsupported. Whatever you are trying to ask is not happening. I don't know what is meant by "right click place"

**Comment by KnightMiner** [comment]
Right click block placing is a 1.8 and earlier feature. It no longer exists, so there is no need to disable it.
