### ISSUE TITLE
Experienced modifier not dropping exp

### ISSUE THREAD

**Issue by dnorris2018** [SlimeKnights/TinkersConstruct#5122]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

I have put the experienced upgrade on a pickaxe and when I go to mine a block it doesn't give exp.

### Other mods

using the Enigmatica 6 modpack

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Experienced does not make blocks drop XP. It increases XP of blocks that already drop XP. Confirm whether you are mining a block that drops XP already.

**Comment by dnorris2018** [comment]
What else do you need?

**Comment by KnightMiner** [comment]
I just told you. Tell me what blocks you are mining. And go mine a block that drops XP without the modifier and see that it drops more with the modifier

**Comment by dnorris2018** [comment]
Sorry I understand now.  I didn't see the comment. 
Yes it gave more exp from a block that does give exp.

**Comment by KnightMiner** [comment]
That means its working as intended. The modifier description does not state anywhere that it makes regular blocks drop XP. It just makes things that drop XP drop more.
