### ISSUE TITLE
cant make smelter controller

### ISSUE THREAD

**Issue by cryo1372** [SlimeKnights/TinkersConstruct#5124]
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.0.308

### Describe your issue

When i go to make the smeltery controller when i right click the spout it doesnt drain out over the block to make the controller

### Other mods

Shutup Experimental Settings!
Corgi_Taco
shutupexperimentalsettings-1.0.3.jar

Sound Filters
Tmtravlr
SoundFilters-0.14_for_1.16.2.jar

Spawner Bug Fix
MacTso
SpawnerFix-1.16.2-1.0.0.2.jar

Straw Golem Rebaled - Forge
CommodoreThrawn
strawgolem-1.16-1.9.jar

The Mighty Architect
simibubi
mightyarchitect-mc1.16.3_v0.5.jar

Titanium
Buuz135
titanium-1.16.5-3.2.8.7-22.jar

Torchmaster
xalcon

Water Strainer
Ruuubi
WaterStrainer-1.16.3-10.0.0.jar

Worldshape
simibubi
worldshape-1.0.jar

XK's Decoration
xekr
xkdeco_0.2.4.jar

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked the FAQ

**Comment by ShinyPorygon** [comment]
A) your tinkers construct is out of date for 1.16
B) actually look at the recipe closely. Report back if it still doesn't work after checking these two things.

**Comment by KnightMiner** [comment]
Closing for lack of response.
