### ISSUE TITLE
Visual: Tier 0 harvest level description become tconstruct.harvest_tier.twilightforest.ice

### ISSUE THREAD

**Issue by Deadmanovi4** [SlimeKnights/TinkersConstruct#5125]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

Tinkers Construct with installed Twillight Forest change description of tier 0 blocks (stone, dirt, sand etc) to tconstruct.harvest_tier.twilightforest.ice

Screenshot: https://prnt.sc/LPOnKz4HZwwh

Twilight Forest doesn't have any ice tools or materials.

Mods separated works as intended. Only if they both do this issue.

### Other mods

Twilight Forest 4.1.1494
WTHIT Harvestability 2.0 (show harvest level, dependencies below)
WTHIT 4.3.16
badpackets 0.1.3

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Tinkers by itself does not add any of the twilight forest integration. That's on twilight's end, and should be reported to them.
