### ISSUE TITLE
FTBIC cells in a basic will infinitely void fluids

### ISSUE THREAD

**Issue by Saereth** [SlimeKnights/TinkersConstruct#5126]
### Minecraft Version

1.18.2

### Forge Version

40.1.93

### Mantle Version

Mantle-1.18.2-1.9.43

### Tinkers' Construct Version

TConstruct-1.18.2-3.6.3.111

### Describe your issue

FTB Contraptions fluid cells starts voiding/deleting fluids after being completely filled with a Tinker's Construct smelter.

Steps to reproduce
Build standard Tinkers smeltery.
Place FTB Contraptions Fluid Cell into TC's Cast basin.
Fill said Cell with water/lava or other fluid of choice.
Leave the filled cell in the basin try to fill it again fluid gets voided/deleted.

A video of this bug inaction posted to my YouTube. https://youtu.be/HiXm7sbM8tg 

Originally reported to our tracker here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2901

and independently verified

### Other mods

myrtrees-forge-1.1.0-build.29
ftb-industrial-contraptions-1802.1.6-build.220

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
That is not a helpful mod list, we do not have time to find a problem in a whole pack. If you can try and narrow it down from this "considerable mod list" that would be useful. 

I'd also like to say that the casting basin is nothing special. And I'd almost be likely to say that it's a cause of how that fluid cell is done. See if any other fluid holding item like that can replicate this issue

**Comment by Saereth** [comment]
Trimmed down to minimal reproducible mod list. 

I tried it with a few other mods, dark tanks from evil craft the faucet doesn't pour, vanilla buckets work fine. Im sure it IS some interaction with the way the cells are coded, but it's ultimately tinkers that is voiding the fluid here. Is there perhaps a blacklist I can add these cells to? I see no specific compat code from either mod to specifically attempt to make the cells work with tinkers. Would be best if I could just disable that feature for them.

**Comment by Saereth** [comment]
To clarify I dont think this is tinker's fault, I'm only checking if there is a way to blacklist these items. Im pretty sure its actually ftbic's implementation here not checking if the contianer is full:

https://github.com/FTBTeam/FTB-Industrial-Contraptions/blob/main/src/main/java/dev/ftb/mods/ftbic/item/FluidCellHandler.java#L65-L75

But I dont beleive that mod is currently supported atm so im checking my options

**Comment by ShinyPorygon** [comment]
Tinkers has no backlist like you are wanting

**Comment by Saereth** [comment]
Ok np, Any data pack overrides could do for the recipe or is it just hard coded?

**Comment by KnightMiner** [comment]
There is no casting basin recipe to fill fluid cells. They only allow filling our own tanks, its on a whitelist. So this is not our bug, this is a bug with whoever added that recipe. If you can reproduce this with seared tanks, buckets, or copper cans we can reopen.

As far as a blacklist, disable the recipe. Again, no idea who is adding it. I have a suspicion you are the ones adding the recipe in your pack.

----

Quick glance at the code, only reason this would cause voiding is if FTBIC cells has a broken fluid handler implementation or the wrong number is specified in the recipe, so its their bug or a bug of the one adding the recipe. Also, you can add container filling recipes using a casting table too, does not have to be a basin. Flat items look dumb in basins.
