### ISSUE TITLE
Inventorio mining speed

### ISSUE THREAD

**Issue by romaust** [SlimeKnights/TinkersConstruct#5129]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

With the Inventorio mod, the mining speed of all tools has decreased to the speed of manual mining

### Other mods

[Inventorio 1.7.5](https://github.com/Lizard-Of-Oz/Inventorio)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Our tools use vanilla hooks to handle mining speed. If Inventorio cannot be bothered to implement vanilla hooks and instead hardcodes to vanilla classes (as explained in their description), nothing we can do. Report this bug to them and tell them to use tool actions if they must to detect pickaxes and alike.
