### ISSUE TITLE
Multiple slime buckets turn into 1 empty when used

### ISSUE THREAD

**Issue by Aceplante** [SlimeKnights/TinkersConstruct#5130]
### Minecraft Version

1.18.2

### Forge Version

latest one?

### Mantle Version

idk what mantle is

### Tinkers' Construct Version

1.18.2-3.6.3.111

### Describe your issue

I had 8 skyslime buckets and clicked with them, and they turned into 1 empty bucket. In your defense I'm pretty sure this is vanilla behavior becuase buckets are not usually able to be stacked, but I hope this can be fixed

### Other mods

yours

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Uh, you can't stack our buckets. Whatever mod is making them stackable, it's their bug.

If you can stack them with just tinkers construct installed, comment here and we can reopen.
