### ISSUE TITLE
Error with tconstruct 1.18.2

### ISSUE THREAD

**Issue by LinusFlamingo** [SlimeKnights/TinkersConstruct#5132]
### Minecraft Version

1.18.2

### Forge Version

40.2.2

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Had this error 3 times in a row trying to see recipes for pig iron and stuff using the JEI mod. Is there a way to fix it?

### Crash Report

https://paste.ee/p/cxha2

### Other mods

Tinkers' Construct
Farmer's Delight
Jade
Just Enough Items
Sophisticated Core
Flywheel 
Curios API 
Mantle    
Create            
Waystones 
Croptopia    
Journeymap    
Comforts   
AutoRegLib    
Joy of Painting
Elevator Mod (Open blocks)
Sophisticated Backpacks 
MrCrayfish's Furniture Mod  
Balm                         
Carry On       
Quark                      
CodeChicken Lib          
EnderStorage             
Selene  
Supplementaries 
Corpse

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Remove Optifine.
