### ISSUE TITLE
Axe type Tinker's tools cannot perform scrape function

### ISSUE THREAD

**Issue by CrusaderRabbit** [SlimeKnights/TinkersConstruct#5133]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Mantle Version

1.19.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Vanilla Minecraft has a feature where you can scrape wax off of copper using an axe. Some mods also utilize this feature such as Create. Tinker's Construct axe type tools does not have "ToolAction.AXE_SCRAPE" so there are no tools in the mod that can perform this function.

### Other mods

Have tried this with just Tinker's Construct.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
In case anyone sees this issue in the future, we discussed it on Discord and found the tool actually works fine, the user just did not understand where the tool action was coming from (as both tools and modifiers can define tool actions). They were testing on a modded block/in JEI, neither of which are guaranteed to use tool actions properly.
