### ISSUE TITLE
Tall Grass unobtainable

### ISSUE THREAD

**Issue by Aceplante** [SlimeKnights/TinkersConstruct#5134]
### Minecraft Version

1.18.2

### Forge Version

1.18.2

### Mantle Version

idk what mantle is

### Tinkers' Construct Version

1.18.2-3.6.3.111

### Describe your issue

Tall slimy and tall sky grass seems to be unobtainable. I went to a slime island and used a ton of bonemeal and never got any. I used bonemeal ON the grass and it does not seem to be bonemealable. I did the same at a sky slime island, same thing.

### Other mods
nevermind

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Yes, didnt see anything

**Comment by ShinyPorygon** [comment]
I am fully able to bonemeal the slimy grass at islands and acquire tall slimy grass. Putting "yes but not relevant" for other mods is never a good idea when it appears that they may be relevant.

**Comment by Aceplante** [comment]
So youre saying it must be an incompatibility? I put not relevant becuase I cant imagine how another mod would prevent me from using bonemeal specifically on yours. I'll try to do more testing i guess.

Also added my modlist, but most of them are clientside

**Comment by Aceplante** [comment]
Edit: so uh apparently regular one block high grass is considered "tall"...

**Comment by ShinyPorygon** [comment]
Yes. Slimy grass doesn't grow as tall as normal grass, because it's a different type of grass.

**Comment by KnightMiner** [comment]
Two block tall grass is commonly called double tall grass

**Comment by Aceplante** [comment]
I have never called it that in my life. there is grass and tall grass

**Comment by KnightMiner** [comment]
Grass is the cube, tall grass is the stuff that goes on top of the cube.

**Comment by Aceplante** [comment]
https://minecraft.fandom.com/wiki/Grass
"This article is about the non-solid plant. For the solid block, see [Grass Block](https://minecraft.fandom.com/wiki/Grass_Block). 

Grass is a non-[solid](https://minecraft.fandom.com/wiki/Solid) plant [block](https://minecraft.fandom.com/wiki/Block) that has [wheat seeds](https://minecraft.fandom.com/wiki/Wheat_seeds) as a [drop](https://minecraft.fandom.com/wiki/Drop). Its color is [biome](https://minecraft.fandom.com/wiki/Biome)-dependent, and matches the color of grass blocks.

Tall grass (in [Java Edition](https://minecraft.fandom.com/wiki/Java_Edition)), also known as double tallgrass (in [Bedrock Edition](https://minecraft.fandom.com/wiki/Bedrock_Edition)), is a two-block high variety of grass."

It seems it is called that in bedrock. Ex bedrock player?

**Comment by KnightMiner** [comment]
Never played Bedrock, nope. Just have been using those names for years. Anyways, this is all off topic, there is no double tall grass for slimy grass. There is regular tall grass, which you can get from bonemeal.

**Comment by Aceplante** [comment]
I think continuing to call them "tall" is going to confuse a lot of players. I doubt its just me. I have fixed them in my personal texture pack but perhaps this can be helpful to you as well:

"block.tconstruct.earth_slime_tall_grass": "Earth Slime Grass",
  "block.tconstruct.sky_slime_tall_grass": "Sky Slime Grass",
  "block.tconstruct.ender_slime_tall_grass": "Ender Slime Grass",
  "block.tconstruct.blood_slime_tall_grass": "Blood Slime Grass"

Also, by default they are ALL called "tall slimy grass" and are not uniquely named?

**Comment by KnightMiner** [comment]
None of the slime foliage is uniquely named. Just how its always been.

And the blood stuff is not grass.

**Comment by Aceplante** [comment]
which is fine, it doesn't have to be. But if thats the case why is the blood one also called tall slimy grass

**Comment by KnightMiner** [comment]
Ah, too much nit picking is causing me to mix up blocks. Yeah, that one is grass.

Anyways, names have been like this since 1.12.2, you are the first one confused. Not convinced changing all the names is less confusing then leaving them as is, its already different from vanilla foliage.

**Comment by Aceplante** [comment]
Fair enough, and yea that makes sense. Thank you for your time
