### ISSUE TITLE
Invalid Modifier Modifier... yeah

### ISSUE THREAD

**Issue by TheMyth27** [SlimeKnights/TinkersConstruct#5136]
### Minecraft Version

1.18.2

### Forge Version

40.2.4

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Most modifiers have a white book as an icon and say "Invalid modifier Modifier" while a few modifiers have their icons but also have "Invalid modifier" as a modifier describtion, jei doesnt show crafting recipes for modifiers, tinkers shields cant be interacted with (they wont block) and worlds with tconstruct weapons that have modifiers crash every time. Smeltery and foundry arent working correctly (will smelt and can use fuel but wont accept buckets or tanks of molten stuff nor will it cast anything else other than blocks and ingots, it wont create casts even if i try to pour gold on parts to make casts). 

i updated forge because of create and create works fine for the most part

(I think its an issue with the forge version because Materialis and Tinkers rapiers also have problems with modifiers, compatibility and mechanics)

Edit: Pastebin link should work now. Also tinkers construct works on its own (even with performance mods)

![2023-05-28_21 07 07](https://github.com/SlimeKnights/TinkersConstruct/assets/134874363/e2123dc2-1887-4a44-8524-ec1a9e42fe8c)

### Crash Report

https://pastebin.com/embed_js/Y8hZ4RL4

### Other mods

rubidium-0.5.6 (performance enhancer)
ferritecore-4.2.2 (performance enhancer)
tinker_rapier-1.1.5
materialis-2.8.0
create-0.5.1.b

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched open issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Try removing the performance mods and see if it still happens. Also your log is private/something going on there

**Comment by KnightMiner** [comment]
This is probably due to running Materialis with Create. Create changed some things in their API and Materialis has not yet had a chance to update. If you can confirm the issue exists without that combo, we can reopen. Provide a log we can actually see in that case.
