### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MCBEModder2020** [SlimeKnights/TinkersConstruct#5137]
### Minecraft Version

1.18.2

### Forge Version

40.2.4

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

crash when put item in tinker anvil
https://bytebin.lucko.me/3Vf6d2fQnA

### Crash Report

https://bytebin.lucko.me/3Vf6d2fQnA

### Other mods

in crash report
tis a chonky modpack
it used to work otherwise i wouldnt have my fancy tools
perf enh: rubidium

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
This is caused by the Materalis add-on not being updated for the newest version of create. You either can remove Materalis, or downgrade create.
