### ISSUE TITLE
Crossbow Animations

### ISSUE THREAD

**Issue by Thresh90** [SlimeKnights/TinkersConstruct#5138]
### Minecraft Version

1.18.2

### Forge Version

40.2.2

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Problem description

I noticed the lack of proper pulling and aiming animations for crossbows which really threw me off at first.
While its not a major issue I would to see all crossbows receive proper pulling and aiming animations.

off note, this does effect some third person mods that have some crosshair issues when loading said crossbows

### Suggested solution

Pretty straightforward, animations for both loading and aiming for Crossbows.

### Alternatives considered

Refer to Suggested

### Additional context

To add notes: Haven't REALLY played tinkers construct since 1.6 back when the old mod packs were spread around during the 2010s and I gotta say i really do see the love and effort put into it, I'm eager to try more apon getting into 1.18.

Keep up the great work!

### Searched for existing enhancement?

Used the search bar

**Comment by ShinyPorygon** [comment]
Afaik this isn't planned to be added. The entire bow animation had to be bypassed for tinkers. You also can dual wield them, which would look even worse if the animation was there holding a bow loading a bow, then loading a bow holding a bow.

**Comment by KnightMiner** [comment]
We do have animations for loading bows? the string pulls back, what more do you want?

Vanilla arm animations we have basically no control over, but no mod should be relying on those.

**Comment by Thresh90** [comment]
Ahh, I see. Fair enough just thought I'd ask really, had no idea it wasn't planned for them

Thank you, reagardless!
