### ISSUE TITLE
Part builder clones hotbar to top of inventory [Optifine]

### ISSUE THREAD

**Issue by ShadeTheCat** [SlimeKnights/TinkersConstruct#5141]
### Minecraft Version

1.18.2

### Forge Version

40.2.4

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

As title state Part crafter clones the hotbar to top of inventory, but what I cut for length of the title is that it only does so if connected to a tool workstation (wood) and a double chest and only that. Only the cloned hotbar can put stuff into the part builder everything below including your inventory will just dissapear until you exit and move stuff.

### Other mods

Tinkers construct 1.18.2
Thinkers' tinkering 0.0.5.2
Polymorph
Mouse tweaks
JEI
JEI integration 
JSON things
Ex Nihilo Sequentia + Tinkers compat + Ex Compressum
Create + Create Additions 
Immersive Engineering
Ferrite core 4.2.2
Optifine (latest 1.18.2 as of 21-jun-23)
Edit to add: Canary 0.2.1
+ Various dependencies and or FPS boosters that don't affect gui's
Hand made small Skyblock pack.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine, Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
Unable to reproduce with just tinkers. Part builder is not cloning the hotbar. If yours actually is, some other mod is causing it to do so.

As a side note: Mods like especially Optifine, and your other FPS boosters do a lot more than you think. And could honestly be responsible for stuff like this. Optifine especially has been known to mess with everything it shouldn't... Use Rubidium + oculus instead of optifine

**Comment by ShadeTheCat** [comment]
Unlisted FPS boosters are Antighost and Clumps, which should not interact with inventory at all.
Will switch optifine for Rubidium and Oculus and write again.

**Comment by ShadeTheCat** [comment]
Update: Unrepeatable with Optifine alternatives, even with exact setup.

Conclusion: Optifine issue.

*Optifine has seriously gone down hill since my 1.6-1.7-1.12 modding days.*

**Comment by ShadeTheCat** [comment]
Let this be a warning to anyone using optifine with forge also having this issue now adays.

Just don't. Get the alternatives.

**Comment by KnightMiner** [comment]
> Optifine has seriously gone down hill since my 1.6-1.7-1.12 modding days.

Optifine started going downhill way before that. 1.12 Optifine was just as bad, just click the "Performance Enhancers/Optifine" label and click "closed issues" to see the many, many bugs reported about it on 1.12 and before.

**Comment by ShadeTheCat** [comment]
Minor texture issues in 1.12 yes but never the weird stuff I heard people talking about in the newer versions especially the hotbar thing.

Also "is: issue label: 1.12 optifine" and similar doesn't show anything for me.

**Comment by KnightMiner** [comment]
We did not start using version labels consistently until around 1.16, so issues from 1.12 optifine (and 1.10, and before) all have no version label.

I can tell you it broke many things, from crashing our models to rendering tank fluids inside out to generally making the game less performant.

Optifine has never really been good outside vanilla (and these days, even in vanilla its not great, author has barely done more than port the mod and rely on reputation for downloads). They have never had forge compatability, they just pretend to to get more downloads. They do not respond to issues on their issue tracker, and delete forge code to make their hacks work (breaking all mods relying on that forge code). None of this is new, you were just lucky enough to not notice major problems before

**Comment by ShadeTheCat** [comment]
Guess I was just lucky with my old mashup packs. Hate to see it fall from grace but I'm glad people are keeping it's spirit, kinda, alive.

*Cough faithful cough*
