### ISSUE TITLE
No crossbow animation

### ISSUE THREAD

**Issue by Aceplante** [SlimeKnights/TinkersConstruct#5142]
### Minecraft Version

1.18.2

### Forge Version

40.2.9

### Mantle Version

idk what mantle is

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

There is no crossbow loading animation for your custom crossbows

### Other mods

better third person

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment]
Duplicate of #5138
