### ISSUE TITLE
Too many tags being applied to the Create Mod Toolbox

### ISSUE THREAD

**Issue by PowerMeep** [SlimeKnights/TinkersConstruct#5143]
### Minecraft Version

1.18.2

### Forge Version

40.2.4

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

For some reason, a Create Mod Toolbox is given a huge amount of tags. I suspect this _might_ be causing my server to not be able to create a packet for the toolbox, and the end result is that toolboxes are not usable on my server. When I disable Tinker's and Mantle, the toolboxes are able to open and no packet error is logged.

Screenshot:
https://media.discordapp.net/attachments/689866656914210897/1125086109555228782/image.png

### Other mods

Create Mod 5.1b

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment]
If errors are being logged a log would be helpful. Also a mod list unless you actually tested this with just tinkers + create.

**Comment by KnightMiner** [comment]
Looks to me like you installed one of those dumb mods that dumps all NBT into the tooltip. There is a reason we don't do that, items can have a lot of NBT. There are commands to print the NBT if you need it.

**Comment by PowerMeep** [comment]
I used a command to grab the NBT and parsed through it very carefully. Turns out, what I'm seeing is the inventories of the toolbox and a specific Traveler's Backpack are getting mixed up somehow, and it just so happens that the last few items in the backpack are Tinker tools, which have enough NBT on their own to fill up the tooltip.

This is not an issue with Tinker's. My apologies.
