### ISSUE TITLE
Tool belt ability glitch

### ISSUE THREAD

**Issue by Jujujunk** [SlimeKnights/TinkersConstruct#5145]
### Minecraft Version

1.18.2

### Forge Version

40.2.4

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

When removing tool belt (II,III,IV...) with spider venom, it will give the leggings an ability slot even though they are slotless past the first level of tool belt. basically, making it possible to duplicate ability slots using the tool belt ability.

### Other mods

- Tinkers' Construct
- Mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Fixed in 3.7.0.152 for 1.18.2
