### ISSUE TITLE
Incorrect JEI recipe for Scorched Drain

### ISSUE THREAD

**Issue by luckyu19** [SlimeKnights/TinkersConstruct#5147]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Tested with JEI 10.2.1.1005.
Recipe showed up normally using Minecraft's native recipe book.
JEI does not show the correct recipe.

![2023-07-16_01 12 18](https://github.com/SlimeKnights/TinkersConstruct/assets/19247442/ca808a44-fd7d-4d69-8d77-9347ab7685df)
![2023-07-16_01 11 49](https://github.com/SlimeKnights/TinkersConstruct/assets/19247442/3e3be708-1f80-4429-8f8a-b10601bea404)

### Other mods

JEI 10.2.1.1005

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by TheMCSpacePro** [comment]
If I remember correctly, that icon in JEI that looks like two arrows twisting over each other means the recipe is shapeless, meaning it doesn't matter how the recipe is arranged as long as all items are there.

**Comment by luckyu19** [comment]
> If I remember correctly, that icon in JEI that looks like two arrows twisting over each other means the recipe is shapeless, meaning it doesn't matter how the recipe is arranged as long as all items are there.

If that is the case, then it is marked incorrectly, since scorched chute uses the same items in a top down configuration.

**Comment by KnightMiner** [comment]
Give me a full game log from the time this issue happened.

**Comment by luckyu19** [comment]
[Game Log](https://gist.github.com/luckyu19/4e0d6792bff18c770f82a2f7ad10dd7fl)

Not sure if you needed a debug log, but here it is as well.
[Debug Log](https://gist.github.com/luckyu19/bffe8b6a2eac8cd2ebc2ca4f52d4745c)

**Comment by willownezz** [comment]
https://github.com/SlimeKnights/TinkersConstruct/assets/3631656/c7f30647-e198-401c-bc27-a5904d098aaf

I also have the same issue

**Comment by KnightMiner** [comment]
At a quick glance, I am using the proper API for this but it seems JEI introduced a newer API and the old one is deprecated. Its possible they removed the old API in newer JEI which is what is causing this.

In any case, its up to Mantle to fix this.

**Comment by KnightMiner** [comment]
Fixed in Mantle 1.9.50.
