### ISSUE TITLE
[CTD] Crash to Desktop when displaying ore items in creative inventory and JEI

### ISSUE THREAD

**Issue by Chaos02** [SlimeKnights/TinkersConstruct#5148]
### Minecraft Version

1.18.2

### Forge Version

40.2.9

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Crash to desktop when attempting to display ore items from tconstruct?

multiple crash reports:
1. https://pastebin.com/cdSR0VBS JEI some other ore searrch I don't remember
2. https://pastebin.com/dc1KAxFD JEI "al" (uminum) search
3. https://pastebin.com/gm70ttPz creative inventory search tab

I should mention that I need to use this version of tinkers because the latest one is incompatible with the version of Create I need

### Other mods

TechAttack
Modpack version with the issue present:
https://github.com/Chaos02/TechAttack/commit/03602046c5e9422c8a3abe5575835de2fc87cfb5

Performance enhancers:

- Magnesium/Rubidium Dynamic Lights
    dynamiclightsreforged-1.18.2_v1.3.3.jar

- Magnesium/Rubidium Extras
    rubidium_extras-1.18.2_v1.3.2.jar

- Rubidium
    rubidium-0.5.6.jar

- Rubidium Extra
    rubidium-extra-0.4.18+mc1.18.2-build.86.jar

- TexTrue's Rubidium Options
    TextruesRubidiumOptions-1.0.5-mc1.18.2.jar

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched closed issues

**Comment by KnightMiner** [comment]
Give me your full game log, this crash is always caused by an addon crashing during init but somehow forge not caring and continuing to launch the game. Log tends to tell you which one.

I can probably guess without the log that its Materialis with an incompatibe create version.

**Comment by Chaos02** [comment]
> Give me your full game log, this crash is always caused by an addon crashing during init but somehow forge not caring and continuing to launch the game. Log tends to tell you which one.
> 
> I can probably guess without the log that its Materialis with an incompatibe create version.

ohhh, I DO have materealis installed, I did not anticipate to downgrade it aswell. I will try. in the meantime, have the complete game logs:
https://1drv.ms/f/s!AidcC4FAYZiXgYe6c8tOASHvRpcsPdg?e=Jhs8Hm

**Comment by Chaos02** [comment]
fixed issue by downgrading Materialis to [v2.8.0](https://www.curseforge.com/minecraft/mc-mods/materialis/files/4422733) for Create [v0.5.0.i](https://www.curseforge.com/minecraft/mc-mods/create/files/4371807)!
Thank you for this fast resolving!! ^^

**Comment by KnightMiner** [comment]
For the record, you game logs require a login to view. In the future, please use a site that does not require a login to view, such as gist.github.com or pastebin.com.

Related issue: #5136. Not sure if thats the first, but want to start linking them all together so will use that one.
