### ISSUE TITLE
[1.18.2] A tool with the Rebalanced modifier can still consume materials to get an identical modifier

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#5149]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

When giving any tool the Rebalanced modifier, you can also use the same recipe as the existing version of the modifier, which will consume the materials used without any benefit.
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/58322110/45dee732-7d0b-4a9d-8b9c-27cb3ec53195)

### Other mods

JEI 10.2.1.1004

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Resolved by a1a3e72

**Comment by KnightMiner** [comment]
Fixed in 3.7.0.152 for 1.18.2
