### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by SansWarYT1** [SlimeKnights/TinkersConstruct#5150]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

After restarting the server to fix a simple voice chat issue, it suddenly started crashing the server.

I cannot remove the mod because it is one of the staples of the server.

### Crash Report

https://pastebin.com/8WFAAM5r

### Other mods

https://pastebin.com/gBiT3c1T

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment]
You are using custom server software which tends to mess up mods. In this instance it is Mohist. That is the cause of your crash. And is unsupported.
