### ISSUE TITLE
Traducción al español

### ISSUE THREAD

**Issue by Jaxer091** [SlimeKnights/TinkersConstruct#5152]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Problem description

Me encuentro trabajando en una traducción para el español, en un inicio quería hacerlo solo para uso personal, pero quiero compartilo.

### Suggested solution

Tendre algo listo muy pronto y lo traeré aquí.

### Alternatives considered

No estoy seguro de si será como un archivo adicional o si en su lugar hare que remplace el ingles, en todo caso lo hare funcionar.

### Searched for existing enhancement?

I did not search

**Comment by Jaxer091** [comment]
Bueno, 1 día de trabajo y tengo esto


[es_es.zip](https://github.com/SlimeKnights/TinkersConstruct/files/12140266/es_es.zip)

NO FUNCIONA, es solo el avance de lo que he echo. La traducción la hice con chat GPT porque que pereza hacerlo uno por uno XD.

Para los que también estén interesados hay esta para que puedan ver donde esta el error y hacerlo funcionar, yo por mi lado seguiré trabajando pero me tomare mi dulce tiempo.

**Comment by ShinyPorygon** [comment]
Este no es realmente el caso de uso de un problema. Si desea compartir la traducción con todos, siéntase libre de hacer una solicitud de extracción en github una vez que haya terminado. O ven a compartirlo en el discord. Sin embargo, voy a cerrar este tema.

**Comment by KnightMiner** [comment]
For the record, I would rather not have machine generated translations, if you are too lazy to make a proper translation, then I would rather you not submit one than submit one you translated with google translate/chat GPT. 

----

Para que conste, preferiría no tener traducciones generadas por máquinas, si es demasiado perezoso para hacer una traducción adecuada, entonces preferiría no enviar una que enviar una traducida con google translate/chat GPT.

Traducido por Google Translate, es una buena herramienta para los comentarios, pero no es una buena herramienta para las traducciones utilizadas en el mod.
