### ISSUE TITLE
Applying the Tank modifier with a filled tank will consume only the fluid

### ISSUE THREAD

**Issue by SilverMedal02** [SlimeKnights/TinkersConstruct#5155]
### Minecraft Version

1.18.2

### Forge Version

40.2.4

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

It seems that, when applying the Tank modifier onto a tool, only the fluid inside will be consumed.

### Other mods

Did not reproduce without other mods

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Fixed in 3.7.0.152 for 1.18.2
