### ISSUE TITLE
[21:49:00] [Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot read field "f_46443_" because the return value of "net.minecraft.world.entity.Entity.m_20193_()" is null

### ISSUE THREAD

**Issue by Jan-Setnicky** [SlimeKnights/TinkersConstruct#5159]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Everytime i add your mod to my modpack it crashes

[crash-2023-08-27_21.49.09-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/12448743/crash-2023-08-27_21.49.09-client.txt)

### Other mods

My private modpack, but if you want all the mods i can write it for you.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Not listing mods makes this report useless to us.

Your crash report is not the same issue as your issue description. You also need to test with minimal mods.
