### ISSUE TITLE
[21:49:00] [Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot read field "f_46443_" because the return value of "net.minecraft.world.entity.Entity.m_20193_()" is null

### ISSUE THREAD

**Issue by Jan-Setnicky** [SlimeKnights/TinkersConstruct#5160]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Everytime i add your mod to my mods folder it crashes
[crash-2023-08-27_21.49.09-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/12448775/crash-2023-08-27_21.49.09-client.txt)

### Other mods

architectury
mantle
mtr
not enough crashes

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by Jan-Setnicky** [comment]
Will someone help me?

**Comment by KnightMiner** [comment]
Please do not close and reopen your issue. Just comment on the issue. We did not need to recreate #5159 

Again, your issue description does not match your crash report. And again, I need more information. Did a smaller mod list reproduce the issue? What were you doing when the crash happened? There is still nothing I can do without more info.

**Comment by KnightMiner** [comment]
Closing for lack of response. I need a crash report that matches your issue description if I am going to do anything.
