### ISSUE TITLE
Problem with finding the item id

### ISSUE THREAD

**Issue by neizvedaniydag** [SlimeKnights/TinkersConstruct#5161]
### Minecraft Version

1.16.5

### Forge Version

latest

### Mantle Version

1.0.5

### Tinkers' Construct Version

latest

### Describe your issue

Еhe crux of the problem is that I can't find the cobalt id for melting objects.  

### Other mods

tinkers construct 

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by TheMCSpacePro** [comment]
Why didn't you search for known issues?

**Comment by ShinyPorygon** [comment]
This is not a good use of an issue. This should be a question for the discord. F3 + h in game shows you  IDs. In the future, do not make issues for questions
