### ISSUE TITLE
Scorched casting basin is useless

### ISSUE THREAD

**Issue by joeyjumper94** [SlimeKnights/TinkersConstruct#5163]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Mantle Version

Mantle-1.18.2-1.9.45.jar

### Tinkers' Construct Version

TConstruct-1.18.2-3.6.4.113.jar

### Describe your issue

the scorched casting basin cannot accept any fluids, rendering the scorched casting basin useless.

### Other mods

this happens even without other mods

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
There is a section in fantastic foundry that explains them. You have to have a cast even in basins to pour. They work fine, you just don't have a cast.
