### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by TheSexyYeti** [SlimeKnights/TinkersConstruct#5166]
### Minecraft Version

1.18.1

### Forge Version

none

### Mantle Version

none

### Tinkers' Construct Version

newer

### Problem description

compatability

### Suggested solution

I know section is supposed to be for Minecraft version 1.18.1. But I was wondering if y'all plan to release Tinkers Construct for newer versions. If you will be planning to include compatibility for combat mods like Better Combat and/or Epic Fight mod. It would be great to combine them. Especially Epic Fight.

### Alternatives considered

nope

### Searched for existing enhancement?

Checked the FAQ

**Comment by ShinyPorygon** [comment]
The faq you checked answers about new versions... Try reading it again. Compatibly for those mods can be done by add-ons or data packs.
