### ISSUE TITLE
option to turn off blood and gore

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [SlimeKnights/TinkersConstruct#5167]
### Minecraft Version

1.16.5

### Forge Version

.

### Mantle Version

.

### Tinkers' Construct Version

i have used it before

### Problem description

it takes me too long to transition back to 1.18.2
so i play in 1.16.5 for now
blood and gore is too inappropriate for me, so i want to turn it off

### Suggested solution

add a config option to turn off anything that contains blood and gore example: beheading modifier

### Alternatives considered

none

### Searched for existing enhancement?

Used the search bar

**Comment by SonicTheHedgehog58987276** [comment]
bleeding effect might be ok for me, so long as there is no blood there, if i want it off i can just use a separate config option

**Comment by TheMCSpacePro** [comment]
Can't tell if this is a troll or not.

**Comment by castilio20** [comment]
what about minecraft gore is that ok?

**Comment by KnightMiner** [comment]
Nothing in Tinkers' Construct is really inherently more gory than Minecraft itself. You used beheading as an example, but all that does is give you more mob drops which are also available from other mechanics, so there is no sense tying that to config (plus, you can literally just not craft it if you dislike it so much). You could argue that blood in the smeltery is gory, I won't disagree there, but a config to turn that off does not make sense, you'd have to find something to replace it with as the fallback.

So honestly, what you want is a resource pack to change 5 lang entries from "blood" to "jello" and your gore is gone. I see no reason to make a config option for something you can change with the existing config options (datapacks and resource packs).

**Comment by SonicTheHedgehog58987276** [comment]
im not trolling nor am i a troll

**Comment by SonicTheHedgehog58987276** [comment]
and beheading is too violent for me.

**Comment by SonicTheHedgehog58987276** [comment]
also i can't use cleavers until that happens

**Comment by SonicTheHedgehog58987276** [comment]
> Nothing in Tinkers' Construct is really inherently more gory than Minecraft itself. You used beheading as an example, but all that does is give you more mob drops which are also available from other mechanics, so there is no sense tying that to config (plus, you can literally just not craft it if you dislike it so much). You could argue that blood in the smeltery is gory, I won't disagree there, but a config to turn that off does not make sense, you'd have to find something to replace it with as the fallback.
> 
> So honestly, what you want is a resource pack to change 5 lang entries from "blood" to "jello" and your gore is gone. I see no reason to make a config option for something you can change with the existing config options (datapacks and resource packs).

beheading in real-life is accompanied by blood

**Comment by castilio20** [comment]
so that means you didnt kill anthing ever????

**Comment by ChiefArug** [comment]
*A mysterious resource pack appears*
[nogore.zip](https://github.com/SlimeKnights/TinkersConstruct/files/13041216/nogore.zip)

(It replaces all references to blood, severing and beheading with jello or mysterious looting respectively).
Minecraft complaining about it being made for a newer/older version can be ignored, thats just MC being dumb with how they implemented that system.
Tested on 1.18, probably works on 1.16 unless tinkers changed lang entry names/book page names in the version diff.

**Comment by KnightMiner** [comment]
> > Nothing in Tinkers' Construct is really inherently more gory than Minecraft itself. You used beheading as an example, but all that does is give you more mob drops which are also available from other mechanics, so there is no sense tying that to config (plus, you can literally just not craft it if you dislike it so much). You could argue that blood in the smeltery is gory, I won't disagree there, but a config to turn that off does not make sense, you'd have to find something to replace it with as the fallback.
> > So honestly, what you want is a resource pack to change 5 lang entries from "blood" to "jello" and your gore is gone. I see no reason to make a config option for something you can change with the existing config options (datapacks and resource packs).
> 
> beheading in real-life is accompanied by blood

Oh, I see. The problem is not that the mod has gore, you are imagining the gore yourself. Yeah, that's a you problem

Let me reiterate, beheading is a thing in vanilla Minecraft

**Comment by SonicTheHedgehog58987276** [comment]
no it isn't, it's just heads for creative mode and skull drops aren't graphic, else the vanilla version of the game wouldn't be child friendly, minecraft is recommended for everyone 10+

**Comment by SonicTheHedgehog58987276** [comment]
esrb rating here https://www.esrb.org/ratings/39546/minecraft/
xbox version

**Comment by KnightMiner** [comment]
How is killing a mob in a giant explosion to make the head drop or killing a wither skeleton with a sword to make the head drop less graphic than killing the skeleton/zombie/etc. with a sword to make the head drop?

If its not considered above a E 10 rating in vanilla, I don't see why its above E 10 in tinkers when **its the same thing**. As I said, there is no gore involved in that process, blood does not squirt everywhere when you use ***severing*** to get the additional drop. Beheading literally does not even exist in the mod these days, and the head drop is no more violent than any other mob drop.

**Comment by SonicTheHedgehog58987276** [comment]
still is inappropriate for me blood there or not, unless it is skeleton skulls only

**Comment by SonicTheHedgehog58987276** [comment]
transitioned to 1.20.1 not very long ago.

**Comment by SonicTheHedgehog58987276** [comment]
![undertale_text_box](https://github.com/SlimeKnights/TinkersConstruct/assets/115895321/0819a9d8-d26e-4021-9ea2-e3f32c04a558)

**Comment by SonicTheHedgehog58987276** [comment]
hint: change the blood color to censor the blood by making it not look like blood and not calling it blood
maybe a resource pack?
example: making it look like milk, or curds and whey
and a way to disable head drops, leave the skull drops

**Comment by SonicTheHedgehog58987276** [comment]
> _A mysterious resource pack appears_ [nogore.zip](https://github.com/SlimeKnights/TinkersConstruct/files/13041216/nogore.zip)
> 
> (It replaces all references to blood, severing and beheading with jello or mysterious looting respectively). Minecraft complaining about it being made for a newer/older version can be ignored, thats just MC being dumb with how they implemented that system. Tested on 1.18, probably works on 1.16 unless tinkers changed lang entry names/book page names in the version diff.

blood color needs to be changed too, for example: spoiled milk or green jello

**Comment by castilio20** [comment]
Stll think they are a troll bc they are fine with guns but not with the word behading?
And about the blood color or name you can do that with a texture pack or datapck for name not 100% sure

**Comment by KnightMiner** [comment]
Yeah, at this point this issue is going no where. User has completely arbitrary definitions of gore which are entirely centered around elements which are not unique to tinkers and thinks the mod needs to change to suit them. I have no plans to change it for one guys taste, but everything you dislike is changable in a resource pack.
