### ISSUE TITLE
There are no entry for shortbow in encyclopedia and tools and you

### ISSUE THREAD

**Issue by Zen9890** [SlimeKnights/TinkersConstruct#5168]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/62694017/14e9b579-ede3-4aee-87a5-9cca446cfba2)

Also there are no entrie for shortbow in materials and you

### Other mods

I dont think any mods cause this since this isnt UI problem

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by Zen9890** [comment]
Shortbow comes from tinkers' things so it shouldnt be there on a second thought, sorry for any trouble

**Comment by KnightMiner** [comment]
https://github.com/SlimeKnights/TinkersConstruct/commit/a994baf79c2bdcf29d08d2dc39bb958597befe5d adds a feature which makes this possible without writing java
