### ISSUE TITLE
tconstruct crashing when pouring liquid xp into smelter

### ISSUE THREAD

**Issue by mikusPL** [SlimeKnights/TinkersConstruct#5172]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Mantle Version

Mantle-1.12-1.3.3.55

### Tinkers' Construct Version

TConstruct-1.12.2-2.13.0.183

### Describe your issue

My game was crashing every time i tried to pour liquid xp into smeltery and now the game crashes before it even loads up. I don't have vanillafix, or other mods that could cause the problem that I know of. Thanks for your support.

### Crash Report

https://pastebin.com/WUf4mChb

### Other mods

I'm currently playing on SkyFactory 4

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched closed issues

**Comment by KnightMiner** [comment]
1.12 is no longer supported. Your crash also has no mention of tinkers, just a broken sound engine. I have heard of no one else with issues on SkyFactory 4, so likely you modified the pack. If you did not, no idea the issue. In any case, 1.12 is no longer supported, submitting the issue anyways ignoring the lack of 1.12 option does not make it supported.

**Comment by mikusPL** [comment]
I did not modify my pack in any way. But do you know at least what my crash logs mean so I can search somewhere else?

**Comment by mikusPL** [comment]
nvm i just reinstalled it and it somehow started working
