### ISSUE TITLE
Add Logs to the minecraft:logs_that_burn Alias

### ISSUE THREAD

**Issue by Zetal911** [SlimeKnights/TinkersConstruct#5176]
### Minecraft Version

1.18.2

### Forge Version

40.2.14

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Problem description

Currently, custom logs added by Tinkers cannot be used as fuel nor can they be converted into charcoal. 

### Suggested solution

This can be resolved by adding the logs (and stripped varieties) to the logs_that_burn minecraft alias for blocks. 

### Alternatives considered

It's possible that this is intended behavior. I'd personally prefer otherwise, but if it is then the alternative would just be to ignore this.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
Slimewood is not flammable. It is thus not logs that burn. Any vanilla impact of that strictly follows from the not flammable observation

You should see their behavior is fully consistent with nether logs in that regard.
