### ISSUE TITLE
Infinite block duration by dual-wielding offhanded parrying daggers

### ISSUE THREAD

**Issue by NyanMC** [SlimeKnights/TinkersConstruct#5177]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

When dual-wielding daggers which both have the offhanded and parrying modifiers, you can press the Swap Item With Offhand key (default: F) to swap them with each other. Doing this resets the blocking duration, however does not cause the player to stop blocking. This can be used to block indefinitely while dealing constant melee damage to enemies.

This works without offhanded, however is much less useful as you will not attack when blocking, effectively turning it into merely a shield which requires two hands.

This does not seem like intended behavior, as the Encyclopedia of Tinkering specifically mentions that the blocking duration is supposed to be brief.

https://github.com/SlimeKnights/TinkersConstruct/assets/44331238/6f0b778c-f683-4081-a4b8-b3edbcead5fd

A few things worth noting:
- The skeleton in that video has Resistance V for demonstration purposes.
- Every time the skeleton takes damage in the video, I am pressing Swap Item With Offhand to swap my main hand and offhand daggers.
- This is a bit finicky to perform, as there is a small window of time when swapping daggers in which you can be hit. This is why I take damage from one of the skeleton's arrows as it shoots me while I'm swapping daggers.

### Other mods

Just Tinkers Construct and Mantle.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by NyanMC** [comment]
i proofread this twice and still somehow made a mistake in the issue description, should be fixed now

**Comment by KnightMiner** [comment]
I can agree this looks like a bug. I am not sure it will be practical to fix but it also looks like its not practical to abuse, so going to call it low priority.

Leaving this as unreviewed until me (or a triage member) verifies in game just for bookkeeping.

**Comment by KnightMiner** [comment]
I just tested this out myself, and I could not get infinite block duration. What I could get was restarting the parrying timer, but the short cooldown when you begin blocking meant you were vulnerable for a short time while attempting this. So overall, I think this is a non-issue.

Practically speaking, if you managed to circumvent the limitation with perfect timing, all you gain is an inferior shield given your method takes both hands to use. The useful usage of parrying is unaffected so I'm going to close this.
