### ISSUE TITLE
Infinite Arrow with Shield Strap 1 Modifier

### ISSUE THREAD

**Issue by GuardianMilky** [SlimeKnights/TinkersConstruct#5179]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Using **Legging Swap Keybinds**, put the arrow on the **additional off-hand slot** then charge a bow. Once the bow is **charged**, hit the Legging Swap Keybind and fire the bow. You'll not only avoid consuming the arrow, you'll get an additional one making it an arrow duplication glitch.

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/36284837/8f1501e2-4653-446e-894e-d6387d2001bb)
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/36284837/d59ba770-8b21-4222-803b-de760831d88f)
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/36284837/110b4dff-7cd2-4bf5-816a-49a902b4b045)

### Other mods

Tinker's Construct

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by KnightMiner** [comment]
Already fixed by f64cd5a which is in the next update.

**Comment by KnightMiner** [comment]
Does this issue happen with vanilla bows by the way? That would really be a vanilla problem, but its something I could work around if needed.

Edit: we have verified this does not happen with vanilla bows.

**Comment by KnightMiner** [comment]
Fixed in 3.7.0.152 for 1.18.2
