### ISSUE TITLE
No weapons damage with Aternos server and classic TC

### ISSUE THREAD

**Issue by EgorAkulyonak** [SlimeKnights/TinkersConstruct#5182]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Playing on aternos we made first daggers (with blue nether ore) – one whole, one with iron handle. Tested it out but got no damage, no RMB or LMB works even though there's 2 per craft so they're probably throwable (long time no play)
I get default animation, but no interaction at all, don't know where's issue

Checked aternos forum and they had same issue, someone pointed that mod is the root, not the server hosting, yet in signle player damage is done
Also I've checked in my solo mode, damage is dealt but there's no animation while I'm destroying blocks and it seems I can't break blocks in gm 1 (though it's classical for weapons)

### Crash Report

-

### Other mods

Corail tombstones (I heard there was some revive mod doubling damage)
Ars Nouveau, Omega and elemental
Inventory profiles next
Tree harvester

Pam's harvestcraft 2
REI
Dynamic trees
Ferrite core – performance enchanter if I get it right

Sophisticated core (for sophisticated backpacks)
Patchouli
Kotlin for forge
LinIPN
Geckolib
Comforts forge
Collective
Cloth config

Some decoration mods
Waystones

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Checked the FAQ

**Comment by EgorAkulyonak** [comment]
Huh, now that's weird
I tested red dagger, it works (even on server), I tested other kobold weapons and one item of each type (random pickaxe, hammer etc), everything works!
I don't know if issue is that I created this one myself or what...

**Comment by EgorAkulyonak** [comment]
Now I get it... Daggers don't do damage when stacked... It makes some sense but also is _very_ confusing. I'm sorry for troubles if it was already known

**Comment by KnightMiner** [comment]
Why is that confusing? No tool does damage in stacks. Daggers just stack to let you craft things cheaper
