### ISSUE TITLE
Putting powdered snow in a tank doesn't return the bucket

### ISSUE THREAD

**Issue by Xenon372** [SlimeKnights/TinkersConstruct#5183]
### Minecraft Version

1.18.2

### Forge Version

40.2.9

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.0.152

### Describe your issue

Right-clicking on any tank with a bucket of powdered snow will deposit it in the tank, but won't return the bucket. This issue doesn't seem to affect tools with the tank modifier.

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment]
Worth noting that it does the same when attempting to right click a bucket into a thermal tank. Does not display behavior with copper cans however, they work fine.

**Comment by KnightMiner** [comment]
Fixed in 3.7.1.155
