### ISSUE TITLE
Part Builder's material value not updating properly

### ISSUE THREAD

**Issue by Sun-Tears** [SlimeKnights/TinkersConstruct#5184]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

The part builder's material value number does not update when adding/removing items to a stack that is in the part builder.

https://github.com/SlimeKnights/TinkersConstruct/assets/121831840/c602db21-fa13-4016-b848-75001cf7313a

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2. Was never an issue on 1.19.2
