### ISSUE TITLE
Milk doesnt produce sound when interacting with tinkers fluid containers

### ISSUE THREAD

**Issue by Zen9890** [SlimeKnights/TinkersConstruct#5185]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

Taking/inserting milk fluid into tinkers container doesnt produce any sound, this includes:
All seared/scorched tanks
Seared melter
Smeltery
Foundry
Alloyer
Tools that have fluid capacity

### Other mods

Tinkers construct, mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
This is really a forge bug. We could work around it, though Mantle is the place for the workaround.

The 1.19 forge API led me to implement the workaround by default as they actually marked fluid sounds as nullable.

**Comment by KnightMiner** [comment]
This fix did not make it into 1.18.2, but it is really a Forge bug anyways. Will leave this issue open for now in case another bug fix build is needed for 1.18.2.

**Comment by KnightMiner** [comment]
Fixed in Mantle 1.9.46 for 1.18.2.
