### ISSUE TITLE
Skyslime slimy vine binding compensates airborne mining penalty when player is not airborne

### ISSUE THREAD

**Issue by Zen9890** [SlimeKnights/TinkersConstruct#5186]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

Tools with slimy vine binding obtain insane ammounts of mining speed this way, to the point where barely modified pickaxe can instamine stone, while having normal mining speed airborne

### Other mods

Just tinkers and mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Please explain when they receive the benefit, is it always? Is it just some cases?

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2. Was never an issue on 1.19.2
