### ISSUE TITLE
Book link doesn't work correctly

### ISSUE THREAD

**Issue by koh-gh** [SlimeKnights/TinkersConstruct#5188]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

For upgrades that have multiple types with the same name (e.g. Pierce, Fiery, Freezing), pressing any link will jump to the same page. Lightspeed jumps to the correct page, so I think a similar fix is needed.
The targets are Puny Smelting and Encyclopedia.

### Other mods

JEI
Jade

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
Light speed is actually two modifiers. The rest are all a single one. Light speed needs to get merged eventually but has not yet for a few internal reasons

**Comment by koh-gh** [comment]
For example, pierce has different effects at melee and at ranged, and  there has two table of contents and two pages. But pressing any link will jump to the same page.
I think this will not be integrated as I feel the effect was intentionally changed.
![2024-03-03_12 54 19](https://github.com/SlimeKnights/TinkersConstruct/assets/36918206/984377f0-a394-4c0c-b20a-ca4fd45e9049)

**Comment by KnightMiner** [comment]
Yeah, I understand the issue, was just being clear about why lightspeed works.

Fixing this will probably mess with the translation strings in the `language.lang` files but should be doable.

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2. Was never an issue on 1.19.2
