### ISSUE TITLE
Amethyst staff is crafted instead of shortbow on tinkers station

### ISSUE THREAD

**Issue by Zen9890** [SlimeKnights/TinkersConstruct#5193]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/62694017/b7b8374d-d0c6-4ae7-93d7-04a9b195a487)
This bug is not present when using tinkers anvil

### Other mods

KnightMiner thinks recipe order determines whether this bug happens, so it may not always be reproducible depending on mod list

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2. Was never an issue on 1.19.2
