### ISSUE TITLE
creative qol

### ISSUE THREAD

**Issue by OscarTheFox** [SlimeKnights/TinkersConstruct#5194]
### Minecraft Version

1.18.1

### Forge Version

40.2.0

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.6.4.113

### Problem description

I want to make max out tools and armor in creative but it takes a long time and is repetitive.

### Suggested solution

allow the creative modifiers and crystals to be added a stack at a time or to the max of the modifier.

### Alternatives considered

none

### Searched for existing enhancement?

Used the search bar

**Comment by KnightMiner** [comment]
Its not worth the effort to make crystals work a stack at a time, it would require massive reworks to the way modifier recipes work and would break quite a few modifier recipes where they have different requirements each level. My priority is supporting survival mode players, creative mode saving a few seconds is not that important by comparison.

As for creative modifiers, those are honestly probably getting removed in a later update as their main purpose is served by a command and modpacks keep using them to break our mod design. We have datapack methods that give them 10x more control than creative modifiers do (letting them both recreate creative modifiers or make their own thing with limits) and I'd rather they use that instead.

----

I recommend you look into the commands under `/tconstruct`, notably `/tconstruct modifiers` and `/tconstruct slots`. They will let you add multiple modifiers at a time without crafting, just note the modifiers command does not consume any slots when used.

**Comment by KnightMiner** [comment]
Was looking for a different issue report and stumbled upon this one so figured I'd add some new info for anyone who finds this later.

The new bundle hooks allow you when in creative mode/an operator to right click a stack of modifier crystals onto an item to add it multiple at a time. Unlike the tinker station recipe, this will not consume modifier slots, just force the modifier onto the tool.
