### ISSUE TITLE
Placing enderslime staff with other staff

### ISSUE THREAD

**Issue by imsi32** [SlimeKnights/TinkersConstruct#5195]
### Minecraft Version

1.18.1

### Forge Version

40.2.0

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Problem description

 Enderslime staff is placed in end of the Tinker's Tools creative page.

### Suggested solution

Placing enderslime staff next to ichor staff will fixed the issue.

### Alternatives considered

None

### Additional context

![enderslime_staff](https://github.com/SlimeKnights/TinkersConstruct/assets/81227251/44fd3ae0-35d4-4356-9bf7-7f58fe0bccce)

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
The order of items in creative tabs is just the order they were registered. On an existing world, new items will end up at the end. Nothing we can do about this.

Well, there is one thing we can do, which is update to 1.19.4 where we can control creative tab ordering. That will be a bit though.
