### ISSUE TITLE
Feather falling not showing correctly.

### ISSUE THREAD

**Issue by Blue7x** [SlimeKnights/TinkersConstruct#5197]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

Feather fall does not show incremental progress correctly instead just showing as just the upgrade and level. Also, was told that the fact that it was showing 15% means that it might not be scaling correctly. 
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/39844501/62c8435f-79ad-4ef9-83c5-3708f439f219)

### Other mods

For content just a few dimension mods and Ice and Fire. A few add-on tinkers mods, like tinkers planner, integrations, json things, and materialis.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

Checked pinned issues, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2. Was never an issue on 1.19.2
