### ISSUE TITLE
Materials and You's tool page show different texts

### ISSUE THREAD

**Issue by imsi32** [SlimeKnights/TinkersConstruct#5198]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

The texts of tools in Materials and You not shows expected text in the path:
src/main/resources/assets/tconstruct/book/materials_and_you/en_us/tools
Instead of these texts it uses "item.tconstruct.TOOL.description" inside of the en_us.json which used in Tinkers Station or Tinkers Anvil.

### Other mods

- Tinkers Construct
- Mantle
- Jade
- Forge

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by imsi32** [comment]
The issue has been in the roadmap.

**Comment by KnightMiner** [comment]
Already fixed in 51010c9. It was mentioned on #4932 but it did not really belong there as it was a broader issue than a missing translation.

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2. Was never an issue on 1.19.2
