### ISSUE TITLE
Aquatic text overlaping with effects parts

### ISSUE THREAD

**Issue by imsi32** [SlimeKnights/TinkersConstruct#5199]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

Aquatic's upgrade page in Puny Smelting is long. Thus, it overlaps with effects section in that page.
![antiaquatic](https://github.com/SlimeKnights/TinkersConstruct/assets/81227251/e6c82f6e-52ec-44bb-9ce9-10c039d7bdaa)

### Other mods

- Tinkers Construct
- Mantle
- Jade
- Forge

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
While not *technically* a typo, this is the type of thing that will get fixed alongside typos, so can you post this on #4932?

**Comment by imsi32** [comment]
I moved it
