### ISSUE TITLE
Exception caught during firing event: Duplicate key class net.minecraft.world.entity.EntityType (twilight forest and tconstruct incompat?)

### ISSUE THREAD

**Issue by carbonatek** [SlimeKnights/TinkersConstruct#5203]
### Minecraft Version

1.19.2

### Forge Version

43.3.0

### Mantle Version

1.10.23

### Tinkers' Construct Version

3.8.0.14

### Describe your issue

I am unable to open my inventory as I have JEI installed, and it hard locks the game when trying to open the inventory, apparently due to class collision (I don't understand Java, but that's what I think happened)
Log from lockup: [lockup.txt](https://github.com/SlimeKnights/TinkersConstruct/files/14853585/lockup.txt)
There is no Twilight compat at this point I suppose, so that's also probably why it crashed. If that is the case, please feel free to either enlighten me or close this issue. It does not happen with REI and it's companion mod REIPC (JEI compat) installed.

### Other mods

Just Enough Items - 11.6.0.1019
Embeddium 0.3.12
Performant 5.8

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment]
A couple things. Twilight adds their own compat, tinkers doesn't. If that's the log with just tinkers you have more mods, I can see that in the log, just tinkers would be only twilight forest + tinkers + JEI. Please try with actually just tinkers and JEI, but do note that twilight does the compat.

**Comment by carbonatek** [comment]
[Here's](https://github.com/SlimeKnights/TinkersConstruct/files/14854040/log.txt) the log with just JEI, Tinkers' Construct, Twilight Forest and Mantle installed.

**Comment by KnightMiner** [comment]
Did some questioning on various discords, apparently the entity ingredient type in Twilight Forest is new to 1.19 hence why we never had this issue before, and since they updated without us they never noticed the conflict.

Back on 1.18 it is unclear whether the JEI API allowed multiple ingredients of the same class or whether we somehow were the only mod using that class. Either way, the fix is pretty straight forward, will be in the next build.

**Comment by KnightMiner** [comment]
Fixed in v3.8.1.16
