### ISSUE TITLE
Tinkers Construct breaks Creates JEI-integration after reloading Datapacks

### ISSUE THREAD

**Issue by Gitcrafter** [SlimeKnights/TinkersConstruct#5204]
### Minecraft Version

1.19.2

### Forge Version

43.3.7

### Mantle Version

1.19.2 1.10.23

### Tinkers' Construct Version

1.19.2 3.8.0.14

### Describe your issue

After reloading Datapacks with /reload JEI will no longer show any createspecific Recipetypes like for example milling, deploying, washing, etc., but the recipes still work

### Crash Report

no Crash involved

### Other mods

Create-1.19.2-0.5.1.f
JEI-1.19.2-forge-11.6.0.1019

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
give me a full game log, either `latest.log` or `debug.log` from when the issue happened.

**Comment by Gitcrafter** [comment]
here you go:
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/14857582/debug.log)
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/14857583/latest.log)

**Comment by KnightMiner** [comment]
Hmm yep, that log tells me this issue is the same as #5202. Which again, funny it breaks on a reload and not on the first load, but such is weird bugs like this.
