### ISSUE TITLE
Longbows (seemingly) always fire at maximum velocity 

### ISSUE THREAD

**Issue by snackerpirater** [SlimeKnights/TinkersConstruct#5206]
### Minecraft Version

1.19.2

### Forge Version

43.3.9

### Mantle Version

1.10.23

### Tinkers' Construct Version

3.8.0.14

### Describe your issue

Longbows will always fire arrows at their maximum velocity (as if fully drawn) regardless of draw time. This includes merely clicking the bow. The bow appears to draw at a normal speed (based on its animation), but the arrow always fires at the same velocity. Tested with multiple longbows to confirm that the fired arrow's velocity depends on the maximum velocity of the bow itself.  

### Other mods

None, confirmed with solely Tinkers' and Mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Fixed in v3.8.1.16
