### ISSUE TITLE
Create Automatic Crafters Recipe problem in JEI

### ISSUE THREAD

**Issue by GonzoOO7** [SlimeKnights/TinkersConstruct#5210]
### Minecraft Version

1.19.2

### Forge Version

43.3.5

### Mantle Version

1.10.23

### Tinkers' Construct Version

3.8.0.14

### Describe your issue

The Problem seems to be that when i add **Tinkers Construct** to my mods, the **JEI Recipes** for **Create Crafting blocks (eg. Automatic Crafters)** don't seem to show up anymore and you **cannot see Recipes**.

### Other mods

Create - 0.5.1.e
JEI - 11.6.0.1011
TConstruct - 3.8.0.14
Mantle - 1.10.23

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Duplicate of #5202
