### ISSUE TITLE
Emissive texture bug on small weapons

### ISSUE THREAD

**Issue by TerravoltPrime** [SlimeKnights/TinkersConstruct#5212]
### Minecraft Version

1.19.2

### Forge Version

43.3.9

### Mantle Version

1.10.24

### Tinkers' Construct Version

3.8.1.16

### Describe your issue

small weapons made from glowing material seem to not glow while large ones do.

![2024-04-08_09 03 32](https://github.com/SlimeKnights/TinkersConstruct/assets/118013254/4a75f850-ac42-4e05-8e88-707e2c933565)
![2024-04-08_09 03 42](https://github.com/SlimeKnights/TinkersConstruct/assets/118013254/1c9eb80b-13e9-4673-b46f-4cc60303069f)

### Other mods

Oculus

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by TerravoltPrime** [comment]
Additionaly I want to appoligize for the bot that hacked my account and spammed the discord server, I was irresponsble with the security of said account.

**Comment by KnightMiner** [comment]
Fixed in 3.8.2.32
