### ISSUE TITLE
Items in TiC inventories invisible until interacted with outside of TiC inventory

### ISSUE THREAD

**Issue by Ryukuwa** [SlimeKnights/TinkersConstruct#5213]
### Minecraft Version

1.19.2

### Forge Version

43.3.0

### Mantle Version

1.10.24

### Tinkers' Construct Version

3.8.1.16

### Describe your issue

I may use some techy words incorrectly, apologies.

Every time a TiC inventory renders there will be some degree of invisibility to the items within the container. 

Crafting Station - As pictured below, items within the Crafting Station's chest sidebar are entirely invisible - unless items are deposited into the chest via said sidebar, moved around in a different inventory, or shift-clicked to the crafting grid from the sidebar.  These items once again become invisible upon world reload.

Part Chest/Cast Chest - Items placed into the part chest or cast chest before unloading a world will become invisible when the world is reloaded. These items must be moved into the player inventory and interacted with outside of the chest menu before they reappear, and only sometimes do they reappear first try.

![2024-04-08_22 13 21](https://github.com/SlimeKnights/TinkersConstruct/assets/13861013/4d29c68c-c34f-49bc-9e4a-e30408fc58ff)

![2024-04-08_22 15 08](https://github.com/SlimeKnights/TinkersConstruct/assets/13861013/0f153971-b341-46b2-83a8-678e044f75ed)

### Other mods

This issue originally happened on a large personal modpack, but I tested it with _only_ 

Tinker's Construct 3.8.1.16
Mantle 1.10.24

and was able to recreate the issue.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by alpm3434** [comment]
I found that for the part chest you just have to break it and it will spit out all your parts again. For now I'm just not using it altogether.

**Comment by KnightMiner** [comment]
Fixed in Mantle 1.10.36
