### ISSUE TITLE
Magnetic effect always active while magnetic tool is held

### ISSUE THREAD

**Issue by Ryukuwa** [SlimeKnights/TinkersConstruct#5214]
### Minecraft Version

1.19.2

### Forge Version

43.3.0

### Mantle Version

1.10.24

### Tinkers' Construct Version

3.8.1.16

### Describe your issue

While any tool with Magnetic is held out, items will gravitate towards the player. This is regardless of the actual status effect. (The status effect does appear when blocks are broken with the tool, but the mechanic persists.)

https://github.com/SlimeKnights/TinkersConstruct/assets/13861013/166defdf-6288-4c46-9b37-4dffc6320895

### Crash Report

does not produce crash

### Other mods

Issue was reproduced using _only_ TConstruct and Mantle.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
Fixed in 3.8.2.32. Looks like this is also an issue on 1.18 though so will leave open for now.

**Comment by erney519** [comment]
Minecraft Version
1.19.2

Forge Version
43.3.13

Mantle Version
1.10.24

Tinkers' Construct Version

3.8.3.39

Magnetic don't work on any tools

Uploading 錄製_2024_06_03_17_03_14_23.mp4…

**Comment by KnightMiner** [comment]
I can assure you, magnetic does in fact work as I am using it in my survival world. Your video did not successfully upload, but if I had to guess you are not using the tool. Either mine a block or attack a monster to activate magnetic. If you are doing those tasks and its still not working, open a new issue report.

**Comment by erney519** [comment]
Successfully activated, but you have to activate it again every time you switch tools.Is that normal?

**Comment by KnightMiner** [comment]
It only activates for a couple seconds, it's not permanent. You want more magnet, you mine more blocks

**Comment by erney519** [comment]
I see. Is there a list of feature changes? My English is not very good and I can’t find it on the wiki.

**Comment by KnightMiner** [comment]
That's not a feature change. That was a bug that existed in a single 1.18 build. Every other build had magnetic functioning correctly 

All the change logs can be found on the releases page

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2. Already fixed on 1.19.2.

Since this was a longstanding bug, just want to make it clear to anyone finding this in the future that magnetic pickaxes are only supposed to trigger after mining blocks, not be a passive magnet. Armor is for passive magnets.
