### ISSUE TITLE
Double jump doesn't double jump

### ISSUE THREAD

**Issue by ShinyPorygon** [SlimeKnights/TinkersConstruct#5215]
### Minecraft Version

1.19.2

### Forge Version

43.3.9

### Mantle Version

1.10.28

### Tinkers' Construct Version

3.8.1.18

### Describe your issue

Double jump doesn't allow you to actually double jump 

### Other mods

JEI 

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
Fixed in 3.8.2.32
