### ISSUE TITLE
Extra parts stat's titles display wrongly in build version 3.8.1.26

### ISSUE THREAD

**Issue by Cactusstudent** [SlimeKnights/TinkersConstruct#5219]
### Minecraft Version

1.19.2

### Forge Version

43.3.13

### Mantle Version

1.10.34 (Build)

### Tinkers' Construct Version

3.8.1.26 (Build)

### Describe your issue

In everybook, in the material lists. The extra parts stats title will not display correctly. Just with part of the localization key.
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/97865546/ecbfcae0-a4d6-48aa-a180-6f56fc0bb76a)

### Crash Report

With No Crash

### Other mods

JEI
Mantle
Tinkers' Construct 3

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
This belongs on #5201. Though I've already got this fixed for the next build.
