### ISSUE TITLE
Show modifier descripition in JEI ingredient list and on Modifier Crystals 

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#5222]
### Minecraft Version

1.19.2 (doesn't seem to be a 1.19.2 enhancement issue type, but this could be applied to 1.18.2 as well)

### Forge Version

43.3.2

### Mantle Version

1.10.24

### Tinkers' Construct Version

3.8.1.16

### Problem description

When picking modifiers from JEI and as crystals it is hard to tell what the modifier does just by the name and picture if you are not used to the mod/have not played for a while.

### Suggested solution

Add the modifier description (or lore, but that is not as nice) to the tooltip of modifier crystals and the modifier 'ingredients' in JEI's ingredient list.

### Alternatives considered

Memorize what every single modifier does.
Make the names very descriptive.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
This seems like a reasonable feature, shouldn't be too hard to implement.

Worth noting that all modifiers displayed are recipe modifers though, so you can always just look up recipes for to get the tooltip. Dropping the extra step though would be good.

**Comment by KnightMiner** [comment]
Added in 3.8.2.32. Ended up being pretty easy to do, so will probably backport to 1.18.

**Comment by KnightMiner** [comment]
Added in 3.7.2.167 for 1.18.2
