### ISSUE TITLE
Modifiers need a recipe to be able to be applied with a modifier crystal

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/TinkersConstruct#5223]
### Minecraft Version

1.19.2 (doesn't seem to be a 1.19.2 enhancement issue type, but this could be applied to 1.18.2 as well)

### Forge Version

43.3.2

### Mantle Version

1.10.24

### Tinkers' Construct Version

3.8.1.16

### Problem description

Modifiers need a recipe to be able to be applied with a modifier crystal. This means that even if you only want a modifier to be a reward for something, or a drop from a special boss, you need to give the modifier a normal recipe and cannot just allow it to be applied from a crystal.

### Suggested solution

Move the `allow_crystal` field to one of the modifier json files. This makes more sense as allow_crystal only needs to be set to true once, but a modifier can have multiple recipes, so using one of the files only defined once per modifier means that there is a centralized place to change it.

### Alternatives considered

Because `allow_crystal` is recipe related moving it to something not recipe related could be rather difficult. Instead a recipe that only has the `allow_crystal` and `result` field could also work to fulfill the usecase of a modifier being only appliable via crystal.
Another option is making the modifier recipes nbt sensitive, meaning one can add a recipe that just takes the modifier crystal as input.

Finally you could also expect anyone doing something this custom to just make a new item and use that in the recipe, but I am trying to do this for a large number of modifiers (60+) so that is not ideal.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
You can add a recipe that is just crystals, we do so in a few cases. Doing it without a recipe is impossible as you need to know slot consumption

**Comment by ChiefArug** [comment]
One of the two aforementioned examples, for those who come looking later: https://github.com/SlimeKnights/TinkersConstruct/blob/1.19.2/src/generated/resources/data/tconstruct/recipes/tools/modifiers/ability/luck_crystal.json
