### ISSUE TITLE
[1.19.2] Tank modifier graphic is in the wrong place of Slimestaves when held/thrown/placed in frame

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/TinkersConstruct#5227]
### Minecraft Version

1.19.2

### Forge Version

43.3.13

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.2.32

### Describe your issue

On all Slimestaves, the Tank modifier graphic is floating away from its intended location (seen in the inventory sprite), leaving behind a gap. Appears like this anywhere except the inventories (when dropped, when held, when placed in an item frame, etc). This only happens if there is fluid in the tank; it looks normal when empty.
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/58322110/cc5f265a-6810-4380-933c-5d2e4ab49161)
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/58322110/14fa8149-6fc3-4bbb-909c-e7d94ff5e11c)
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/58322110/3bc48f31-d33a-42b5-81ac-610d33647a1e)

### Other mods

- Tinkers
- Mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Fixed in 3.8.3.39
