### ISSUE TITLE
mod update to version 1.20.1 and 1.21

### ISSUE THREAD

**Issue by CleversonCJ** [SlimeKnights/TinkersConstruct#5228]
### Minecraft Version

1.20.1

### Forge Version

.

### Mantle Version

.

### Tinkers' Construct Version

.

### Describe your issue

Will there be an update to Tinkers Construct for versions 1.20.1 and 1.21 of Minecraft?

### Other mods

.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment]
Your answer can be found in the frequently asked questions it asked you to read before making an issue.
