### ISSUE TITLE
Whitestone durability not being prioritized.

### ISSUE THREAD

**Issue by SS1206** [SlimeKnights/TinkersConstruct#5231]
### Minecraft Version

1.19.2

### Forge Version

43.3.8

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

Whilst mining with any whitestone tool, stoneshield will not be prioritized over durability when at minimum or full, it will drain the tools durability while keeping or gaining stoneshield. I have not tested breaking the tools completely, nor have I tried them on every block.

### Other mods

I tested this with a list of 52 mods, including json things, and tinkers integrations and tweaks, however after testing them with JUST mantle and tinkers, the problem still persists.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

Checked the in game books

**Comment by PyroPhile232** [comment]
Can confirm

**Comment by KnightMiner** [comment]
Fixed in 3.8.4.50 for 1.19.2. Does not affect 1.18.2
