### ISSUE TITLE
Ability Master achievement not working

### ISSUE THREAD

**Issue by programgames** [SlimeKnights/TinkersConstruct#5233]
### Minecraft Version

1.18.2

### Forge Version

40.2.21

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

The achievement 'Ability master' is not achievable because the ability 'protection' is not detected.
I applied 'protection I' to something like 5 tool and the trigger of the achievement is not working.
I actually have reached 38/39 task in the quest. I reproduced in vanilla tinker's too.

I found that my achievement file from my world contain this :

```  "tconstruct:smeltery/abilities": {
    "criteria": {
      "path_maker": "2024-05-29 20:01:53 +0000",
      "silky": "2024-05-30 11:35:21 +0000",
      "long_fall": "2024-05-29 17:42:41 +0000",
      "slurping": "2024-05-30 10:57:29 +0000",
      "luck": "2024-04-28 19:36:19 +0000",
      "gilded": "2024-05-25 11:25:37 +0000",
      "strength": "2024-05-30 11:05:41 +0000",
      "spilling": "2024-05-30 11:07:33 +0000",
      "reach": "2024-05-30 10:44:20 +0000",
      "reflecting": "2024-05-30 10:55:10 +0000",
      "melting": "2024-05-30 11:19:18 +0000",
      "ambidextrous": "2024-05-29 11:42:46 +0000",
      "pathing": "2024-05-12 16:29:49 +0000",
      "exchanging": "2024-05-30 11:30:39 +0000",
      "bouncy": "2024-05-26 06:49:27 +0000",
      "flamewake": "2024-05-29 16:51:31 +0000",
      "stripping": "2024-05-12 14:42:05 +0000",
      "double_jump": "2024-05-29 16:48:59 +0000",
      "expanded": "2024-05-30 11:34:23 +0000",
      "pockets": "2024-05-26 06:48:22 +0000",
      "crystalshot": "2024-05-29 11:27:13 +0000",
      "blocking": "2024-05-12 11:14:04 +0000",
      "unbreakable": "2024-04-28 19:36:19 +0000",
      "frost_walker": "2024-05-29 17:25:03 +0000",
      "trick_quiver": "2024-05-29 11:34:08 +0000",
      "snowdrift": "2024-05-30 11:03:29 +0000",
      "autosmelt": "2024-05-30 11:26:38 +0000",
      "firestarter": "2024-05-28 19:58:39 +0000",
      "dual_wielding": "2024-05-30 11:16:44 +0000",
      "plowing": "2024-05-29 20:32:11 +0000",
      "tilling": "2024-05-12 14:45:19 +0000",
      "aqua_affinity": "2024-05-29 11:45:44 +0000",
      "multishot": "2024-05-29 11:32:15 +0000",
      "glowing": "2024-05-29 11:06:17 +0000",
      "bulk_quiver": "2024-05-29 11:25:36 +0000",
      "bucketing": "2024-05-28 18:55:35 +0000",
      "parrying": "2024-05-30 11:20:37 +0000",
      "tool_belt": "2024-05-30 11:08:41 +0000"
    },
    "done": false
  },
```
  
  And i checked the code of the achievement : 
  
  ``` 
"protection": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "type": "tconstruct:tool_stack",
            "predicate": {
              "type": "tconstruct:has_modifier",
              "modifier": "tconstruct:protection",
              "level": {
                "min": 1
              },
              "check": "upgrades"
            }
          }
        ]
      }
    },
```
  
  But I can't get the achievement to work.
  
![2024-05-30_19 54 35](https://github.com/SlimeKnights/TinkersConstruct/assets/18596429/4ebe2741-3a17-4e31-86da-ea5225a69aae)

  
![2024-05-30_19 54 43](https://github.com/SlimeKnights/TinkersConstruct/assets/18596429/7b341c59-51c2-42f6-9a9a-a1f87977c954)

  
  
  

### Other mods

https://www.curseforge.com/minecraft/modpacks/ragnamod-vii/relations/dependencies

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books, I did not search

**Comment by ShinyPorygon** [comment]
If you tried reproducing with just tinkers, which you said you did. Can we have the information from that instance? 

With tinkers protection does indeed up the count for ability master.

**Comment by programgames** [comment]
I have JEi, tinker mantle, forge 40.2.21
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/18596429/4a16f794-422a-4d2b-95d5-a01d506bb1d9)

**Comment by programgames** [comment]
Ok... I finally updated tinker's to the 3.7.1.155 version and it is working. I guess i have to update my modpack ^^
