### ISSUE TITLE
[1.19.2] Osmium book material entry shows two traits and an error

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#5237]
### Minecraft Version

1.19.2

### Forge Version

43.3.0

### Mantle Version

Mantle-1.19.2-1.10.36

### Tinkers' Construct Version

TConstruct-1.19.2-3.8.3.39

### Describe your issue

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/44974827/59c52b2f-6269-4c11-930e-5ab08d3e14eb)
As you can see, something seems wrong in this description with

### LOG
https://pastebin.com/BR8FaQ2P

### Other mods

All the Ores

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
Give me your full game log, that issue would only happen if something failed to load. If I had to guess, an addon is adding something broken but hard to say.

**Comment by ffuentesm** [comment]
Yep, just checked, and seems that https://www.curseforge.com/minecraft/mc-mods/tcintegrations
Causes the invalid modifier error.
Going to report it there.

**Comment by KnightMiner** [comment]
> Yep, just checked, and seems that https://www.curseforge.com/minecraft/mc-mods/tcintegrations Causes the invalid modifier error. Going to report it there.

Worth saying, the game log still has valuable info here. Post it either here or on that other issue.

**Comment by wendall911** [comment]
@KnightMiner Thanks for letting me know, I'll remove the conflict. Issue is reported here: https://github.com/wendall911/TCIntegrations/issues/61

**Comment by wendall911** [comment]
This is now resolved and pushed. I completely missed that Osmium modifier/stats were added back. FYI, since I am adding in Create integration, I added back stats for brass. Hopefully this does not create a conflict in the future. I'm unsure of the plans for the brass material.

**Comment by ffuentesm** [comment]
Here are all the current Native compatibility materials https://docs.google.com/spreadsheets/d/1c8SOET2_i82slCiay_Cn0NNmoGBYn-IhmIl9PePwqEY/edit?usp=sharing

**Comment by KnightMiner** [comment]
> This is now resolved and pushed. I completely missed that Osmium modifier/stats were added back. FYI, since I am adding in Create integration, I added back stats for brass. Hopefully this does not create a conflict in the future. I'm unsure of the plans for the brass material.

If you want to avoid conflict, don't use material IDs under `tconstruct` for your new material. Using existing material IDs should only be for adding new stats to an existing material.
