### ISSUE TITLE
Better Combat?

### ISSUE THREAD

**Issue by Embeiii** [SlimeKnights/TinkersConstruct#5240]
### Minecraft Version

1.19.2

### Forge Version

Most recent

### Mantle Version

No clue what that is

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

The weapons don't work with better combat, what gives??

### Other mods

Better Combat

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
What gives? No one wrote an addon to make them work and Better Combat does not use proper Forge hooks to make the weapons work. Its on their side or an addon to fix.

**Comment by Embeiii** [comment]
What the hey? I want better Combat support because vanilla combat is boring and really turns me away from making tinker's swords

**Comment by KnightMiner** [comment]
Thats nice, but this mod is not the place for support to be added. I support vanilla combat and implement all the appropiate Forge hooks. Better Combat bypasses Forge hooks, so ask them for support.
