### ISSUE TITLE
Slimy Leaves suffocate players

### ISSUE THREAD

**Issue by PyroPhile232** [SlimeKnights/TinkersConstruct#5242]
### Minecraft Version

1.19.2

### Forge Version

43.4.13

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

When a player is inside slimy leaves, they suffocate. This is not the case for regular leaves.

### Other mods

Tinkers' Construct
Mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Fixed in 3.8.4.50 for 1.19.2. Leaving open until its backported to 1.18.

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2
