### ISSUE TITLE
When adding Tinkers Construct upon pressing play it freezes the loading screen and says (Not Responding)

### ISSUE THREAD

**Issue by SmileyWasTaken** [SlimeKnights/TinkersConstruct#5247]
### Minecraft Version

1.19.2

### Forge Version

43.4.0

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

When adding Tinkers Construct to my modpack whenever I press play for minecraft it freezes on a white screen and says (Not Responding)
When having only tinkers installed, it freezes on the white screen for like 5 seconds then it goes to the loading screen and loads up fine, though it takes a bit.
![image](https://github.com/user-attachments/assets/e2108467-a018-43e6-8890-6207691b8f39)

### Crash Report

https://mclo.gs/apz0Gyr

### Other mods

https://www.curseforge.com/minecraft/modpacks/justright
Performance mods used:
Oculus, Canary, Saturn, Rubidium

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

I did not search

**Comment by Mrthomas20121** [comment]
replace rubidium by embeddium. and remove canary

**Comment by SmileyWasTaken** [comment]
> replace rubidium by embeddium. and remove canary

Thanks, fixed my issue though can I ask what the issue is with canary?

**Comment by Mrthomas20121** [comment]
Canary causes more problem than it solves from my experience, that's it.

**Comment by SmileyWasTaken** [comment]
> Canary causes more problem than it solves from my experience, that's it.

Oh alr, apparently the problems still happening dont know what happened

**Comment by ChiefArug** [comment]
Likely a duplicate of https://github.com/SlimeKnights/TinkersConstruct/issues/5229, caused by Diagonal Windows/Fences.

**Comment by SmileyWasTaken** [comment]
> Likely a duplicate of #5229, caused by Diagonal Windows/Fences.

thanks! this has been driving me crazy. Now its fixed
