### ISSUE TITLE
soulspeed not working

### ISSUE THREAD

**Issue by DangoncitoVT** [SlimeKnights/TinkersConstruct#5248]
### Minecraft Version

1.19.2

### Forge Version

43.4.2

### Mantle Version

10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

When I put the soul speed improvement on the boots they don't work directly the vanillas work but the tinkers ones don't work I'm playing in pojavlauncher I don't know if it has anything to do with it, I sent a video of the demo to the discord

### Crash Report

No crash

### Other mods

Jei and offlineskins, I don't have any other mod because I want to play tinkers as vanilla as possible

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by TheMCSpacePro** [comment]
Have you tried seeing if this occurs on actual Java Edition (on PC, not on phone)?

**Comment by luckyu19** [comment]
Able to replicate the issue with Forge version 43.4.0 and only TiC3.
Tried Depth Strider and Bouncy just to see, but those seems to work fine, only Soul Speed is affected.
Log as attached for reference.

[latest.log](https://github.com/user-attachments/files/16334176/latest.log)

**Comment by KnightMiner** [comment]
Fixed in 3.8.4.50 for 1.19.2. Does not affect 1.18.2
