### ISSUE TITLE
[Crash] Tnkers crashing with jei while trying to render scorched anvil

### ISSUE THREAD

**Issue by AHChaves** [SlimeKnights/TinkersConstruct#5251]
### Minecraft Version

1.19.2

### Forge Version

43.3.5

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

The game is crashing when I try to search for anvil in JEI

### Crash Report

https://paste.gg/p/anonymous/9ba404446eed422380c7c80139ac21e9

### Other mods

all of create(modpack)
waystones(added)
CC:Tweaked(added)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment]
That looks to be a problem with the mod Connectedness, try without that mod. This doesn't happen with just tinkers so it's some other mod causing it

**Comment by AHChaves** [comment]
thank you! disabling connectedness resolved the problem!

Sorry for my poor english in any case
