### ISSUE TITLE
Ore block broken doesn't drop ores when using Tinker's Construct.

### ISSUE THREAD

**Issue by Greemole** [SlimeKnights/TinkersConstruct#5252]
### Minecraft Version

1.18.2

### Forge Version

40.20.21

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

Specifically can't mine the blocks from the mod "Potassium & Sulfur's Gunpowder Mod" with tinker's tools. Can mine them with iron tools and other mods, but can't with Tinker's specifically. 

### Other mods

Tinkers Construst, 
Mantle, 
Potassium & Sulfur's Gunpowder Mod: https://www.curseforge.com/minecraft/mc-mods/create-gunpowder-crafting/comments

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
The only way this can happen is if that mod is very badly coded. We make use of the vanilla API for checking what we can harvest. They should use the vanilla API for setting how to mine blocks, it's just a tag unless they do it a stupid way.

So, report the bug to them and tell them to just use tags like every other mod does.

**Comment by esotericist** [comment]
this very issue was reported to that mod's dev by a tetra user back in march and they seemed to think it would be "difficult" to fix.

it's an mcreator based mod, so my money's on them just not being prepared to understand what's going on.

**Comment by KnightMiner** [comment]
It is absolutely trivial to fix if they have any understanding of datapacks. Problem is MCreator does things in a stupid way instead of just having their authors do datapacks. I'd recommend they learn datapacks, it's something every real modder has to know how to use
