### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by AnterCreeper** [SlimeKnights/TinkersConstruct#5253]
### Minecraft Version

1.19.2

### Forge Version

43.4.0

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

1. Item lost duration(become broken) after re-enter the server
![2024-08-14_18 18 05](https://github.com/user-attachments/assets/64399e46-e50d-4928-9ed1-e8fc3a5e2ee8)

2. Craft station Totally wrong.
![2024-08-14_18 48 28](https://github.com/user-attachments/assets/9c887905-8979-4fa6-b43a-f8f6192d62b5)
![2024-08-14_18 48 31](https://github.com/user-attachments/assets/d24678c5-946b-4cd0-a401-d71d1d93dd39)
![2024-08-14_18 48 35](https://github.com/user-attachments/assets/772e1be0-2b1c-4982-a702-8fe31f9be2b8)

_No response_

### Other mods

TCIntegrations-1.19.2-2.0.21.7
TinkerSurvival-1.19.2-4.1.1.7
and other about 200 mods.

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Please give this issue a better title. Summarize the issue in the title.

Also,.go reproduce without your performance enhancers, ideally in a mod list with just tinkers and mantle so we can narrow down this bug.

**Comment by AnterCreeper** [comment]
Have tested, and not caused by Tconstruct.

/
The second one is unclear rightnow, i will do more investigation later.

**Comment by AnterCreeper** [comment]
> Have tested, and not caused by Tconstruct. The first one is cleared, caused by lightspeed and i will go to ask for their help. The second one is unclear rightnow, i will do more investigation later.

Second one is clear rightnow, caused by canary + Kiwi(together, if delete one then disappear)
