### ISSUE TITLE
Fluid order in Smelteries/Foundries can be changed while in Spectator Mode

### ISSUE THREAD

**Issue by Toastr125** [SlimeKnights/TinkersConstruct#5254]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Steps to reproduce:
1. Make a Smeltery or Foundry
2. Put multiple fluids in it
3. Go into Spectator Mode
4. Click on the controller
5. Click on the fluids to reorder them

Spectator Mode players should not be able to interact with the world in such a way.

### Other mods

Confirmed with just Tinkers Construct and Mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by Toastr125** [comment]
Confirmed still present on 1.19.2
Forge version: 43.4.0
Mantle version: 1.10.36
TConstruct version: 3.8.3.39

**Comment by KnightMiner** [comment]
Fixed in 3.8.4.50 for 1.19.2. Leaving open until the fix is backported to 1.18.

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2.
