### ISSUE TITLE
Mud bricks slab and mud bricks stairs have no preferred tool to mine them with

### ISSUE THREAD

**Issue by cuberyl-catastrophe** [SlimeKnights/TinkersConstruct#5255]
### Minecraft Version

1.18.2

### Forge Version

40.2.21

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

Mud bricks slabs and mud bricks stairs have no preferred tool to mine them in 1.18.2 with because they don't have the minecraft:mineable/shovel tag.
The non slab variant can be mined quickly with a shovel.

This block does not exist in the 1.19.2 version of tinker's construct since it got replaced with minecraft's mud bricks.

### Other mods

Mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment]
Fixed in 3.7.2.167 for 1.18.2, does not affect 1.19.2.
