### ISSUE TITLE
Liquid Dupe

### ISSUE THREAD

**Issue by xKarmaStrikeogg** [SlimeKnights/TinkersConstruct#5256]
### Minecraft Version

1.19.2

### Forge Version

43.4.0

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

When you put the melting ability and the tank upgrade on a weapon then fill it with a liquid with making it full and kill a mob (tested it and it does it with every mob) it fills the tank in the weapon with the liquid that was already in the weapon, duping it

https://github.com/user-attachments/assets/8f19c876-ffb7-4273-9f20-fe830b4e5460

### Other mods

No other mod needed for the bug

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
Fixed in 3.8.4.50 for 1.19.2. Does not affect 1.18.2
