### ISSUE TITLE
Exchanging modifier breaks with Multi Mine installed

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#5260]
### Minecraft Version

1.19.2

### Forge Version

43.4.0

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

With [Multi Mine](https://www.curseforge.com/minecraft/mc-mods/multi-mine) installed the Exchanging modifier becomes broken; it will attempt to swap the first block out but drop a second item from your offhand, and the second block broken will just break both blocks.  
In singleplayer the behaviour is slightly different but still broken in a similar way.

### Other mods

Multi Mine

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by MarioSMB** [comment]
Also reported on the Multi Mine tracker: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/519

**Comment by KnightMiner** [comment]
Closing this as fixed in Multi Mine
