### ISSUE TITLE
foundry dont put liquid

### ISSUE THREAD

**Issue by slavaherobrins** [SlimeKnights/TinkersConstruct#5261]
### Minecraft Version

1.19.2

### Forge Version

43.4.0

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

foundry dont put liquid into cating

### Other mods

![image](https://github.com/user-attachments/assets/fa4a7e32-c470-4188-8fbf-c7cf7397d674)

Uploading 2024-09-11-22-21-59.mp4…

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Scorched Casting Tables and Basins require a cast. This is discussed in its tooltip, and in the fantastic foundry book. This is different from the seared tables for the sake of easing some difficulties that come up in automating the seared tables.
