### ISSUE TITLE
No Sharpening Kits?

### ISSUE THREAD

**Issue by KeelReaper** [SlimeKnights/TinkersConstruct#5264]
### Minecraft Version

1.18.2

### Forge Version

Forge-40.2.21

### Mantle Version

Mantle-1.18.2-1.9.50.jar

### Tinkers' Construct Version

TConstruct-1.18.2-3.7.2.167.jar

### Describe your issue

I'm playing the newest version at 1.18.2, I saw that there was saying in the page mod that now we have Sharpening Kits, but in my game there is only Repair Kits. Was it supposed to be like this?

### Other mods

TConstruct-1.18.2-3.7.2.167.jar, Mantle-1.18.2-1.9.50.jar

### Tried reproducing with just Tinkers?

Yes

### Does this issue affect Tinkers' Construct in 1.19.2?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
You can't trust random sources on the internet about whats in the mod. If it was an official resource such as a changelog, you can let me know and we can get that updated. That said, I do know the CurseForge description was never updated past the 1.12 version, 1.16+ is a bit different.

Sharpening Kits were replaced by the diamond/emerald/netherite modifiers. Repair kits are just for repair.

**Comment by KeelReaper** [comment]
Yes, I saw it at the CurseForge mod description. That said, do Diamond, Emerald e Netherite modifiers upgrade the mining level?

**Comment by KnightMiner** [comment]
I just told you they replace sharpening kits, if they did not upgrade the mining level it would not be a replacement.

**Comment by KeelReaper** [comment]
Yeah, sorry, english is not my first language and some times I'm kinda slow, Thanks for the support and help, It worked, and thanks for maintening Tinkers, that is one of my favorite mods since 1.7.10 ❤
