### ISSUE TITLE
totems of undying

### ISSUE THREAD

**Issue by Quaresma1717** [SlimeKnights/TinkersConstruct#5265]
### Minecraft Version

1.20.1

### Forge Version

47.3.0

### Mantle Version

na

### Tinkers' Construct Version

na

### Describe your issue

made a farm for tottems of undying but they wont stack any hints on how i could make them stack?

### Other mods

i have curently 145 mods but i have tried with just bigger stacks and it still doesnt let me stack them

### Tried reproducing with just Tinkers?

No

### Does this issue affect Tinkers' Construct in 1.19.2?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment]
I don't understand how this has any relation to tinkers. Tinkers doesn't change the totem of undying in any way... You should find a modded discord to ask questions like this. https://discord.com/invite/moddedmc Here is the general modded MC discord.

**Comment by xbxbxb123** [comment]
There is no mod changing this. Totems of undying just don't stack. That's normal.
