### ISSUE TITLE
Double Jump and Zoom not working

### ISSUE THREAD

**Issue by gamerleo815** [SlimeKnights/TinkersConstruct#5271]
### Minecraft Version

1.19.2

### Forge Version

43.4.0

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.84.50

### Describe your issue

So this 2 issues in one post here, this is my first time suggesting something on github so i'm not sure if i should seperate these...
so basically, Zoom seemingly doesn't work on helmets (I only tried traveler's goggles, it might work on other helmets), and the OTHER thing is that double jump only works... a SINGLE TIME (per world). Tried it across different pairs of traveler's boots, but as soon as I do it ONCE in a world it will no longer work. The 1st one may be because I have crouching bound to C and the 2nd one may be because I am braindead and do not know how double jump works. (the first one could also be the same thing to be honest)

### Other mods

![image](https://github.com/user-attachments/assets/15b68bc7-66e6-4a11-b0c0-cc257f5c55c5)
this
ignore checkmarks, I just tried all mods and no mods but mantle and tinkers.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
Do not make multiple issues in one bug report. Make separate ones.

In regards to zoom, did you try holding shift before pressing Z like the tooltip tells you to?

In regards to double jump, please confirm you are not using a slow falling potion, that is known to break the modifier and I have not found a good fix yet.

**Comment by ShinyPorygon** [comment]
All the keybinds and double jump works perfectly fine with just mantle and tinkers on 1.19.2

**Comment by gamerleo815** [comment]
> Do not make multiple issues in one bug report. Make separate ones.
> 
> In regards to zoom, did you try holding shift before pressing Z like the tooltip tells you to?
> 
> In regards to double jump, please confirm you are not using a slow falling potion, that is known to break the modifier and I have not found a good fix yet.

1. didnt know there were keybinds, now i do so uh... thanks :)
2. No, i was not using any slow falling effects. i was messing around in creative mode and the double jump just doesn't work... in creative mode. ... sorry for wasting your time because i'm an idiot :/

**Comment by KnightMiner** [comment]
Yeah, unsurprising the modifier does not work in creative, creative does not fire a lot of events for player movement.
