### ISSUE TITLE
Smeltery not working in stoneblock 2

### ISSUE THREAD

**Issue by Sammy20050307** [SlimeKnights/TinkersConstruct#5272]
### Minecraft Version

1.12.2

### Forge Version

12.0.157

### Mantle Version

12.0.15

### Tinkers' Construct Version

1.12.2-12.0.15

### Describe your issue

Whenever I try to build the smeltery, the whole system for it doesn't work. The ui doesn't pop up, and when I throw some ores inside, they don't convert into their molten form. I had tested this in a creative world (still using multiMC and the modpack) and it still wouldn't work. I made it as a 3x3 with several different layers, but it still doesn't work.

### Other mods

The modpack i was using is the stoneblock 2 from FTB. I was using MultiMC (latest version 0.7.0) to run the modpack.

### Tried reproducing with just Tinkers?

I will go do that now

### Does this issue affect Tinkers' Construct in 1.19.2?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
The modpack can change how things work, I suggest go asking in the https://go.ftb.team/discord discord. They made it, also don't alter a bug report for your version. 1.12 is long unsupported.
