### ISSUE TITLE
Pattern

### ISSUE THREAD

**Issue by GhostKing0001** [SlimeKnights/TinkersConstruct#5280]
### Minecraft Version

1.21.50

### Forge Version

1.21.50

### Mantle Version

1.21.50

### Tinkers' Construct Version

Lite

### Describe your issue

No option to create a pattern for any tools on the basic tools. All your able to do it create a blank pattern and that's it. and the anvil won't let you do anything.

### Other mods

Tinkers construct lite

### Tried reproducing with just Tinkers?

Yes

### Does this issue affect Tinkers' Construct in 1.19.2?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues, Searched open issues, Checked the FAQ

**Comment by paypur** [comment]
This is for Java not Bedrock

**Comment by KnightMiner** [comment]
Tinkers Construct for forge has not had tool part patterns for years. Read the on game guide books, they explain how things work.

And please actually read the issue template and follow it, you completely failed to do so which should have tipped you off this is not the place for bedrock issues

**Comment by GhostKing0001** [comment]
When I looked at the tinkers construct for bedrock it sent me her to put in a issue with it. Sorry for any inconvenience I caused but I highly suggest looking into the link located with the bedrock version so you don't have other issues arise.

**Comment by KnightMiner** [comment]
> When I looked at the tinkers construct for bedrock it sent me her to put in a issue with it.

I highly doubt that. Most likely you misread the page you were on.

I have absolutely zero control over the bedrock edition so if one of their links is wrong that is just yet another thing that bugs me about their edition, go yell at the authors of the mod.

**Comment by GhostKing0001** [comment]
Thank you for the information I appreciate the feedback. Much appreciated have a good day
