### ISSUE TITLE
[Feature request] tinkers construckt fishing rod

### ISSUE THREAD

**Issue by svennieke** [SlimeKnights/TinkersConstruct#863]
since 1.7.X has enchantings for fishing rods and a chanse for differetn fish junk and treashures i was wondering if we could have a tinkers fishing rod?

**Comment by InkDragon** [comment]
would be extremely useful when used with mariculture

**Comment by bonii-xx** [comment]
Let's face it, I'll never not have way too many other things I want done to implement them. Better as an addon by somebody else :L
