### ISSUE TITLE
Suggestion: Add language support for these manuals

### ISSUE THREAD

**Issue by Mrkwtkr** [SlimeKnights/TinkersConstruct#867]
Since Mariculture has its manuals, and they can be loaded in certain language when we launch the game. If TinkersConstruct could add this support (such like xxxxx_en_US.xml, xxxxx_ru_RU.xml and so on), that will be very helpful for those from different countries. Thank u :D

**Comment by bonii-xx** [comment]
Closing that since it's technically possible to translate them. They're just a derp.
