### ISSUE TITLE
Improvement - Make Smeltery Lava Tanks stackable

### ISSUE THREAD

**Issue by BakermanLP** [SlimeKnights/TinkersConstruct#975]
Hello,
This yould be a nice feature. Just make the lava tank in the smeltery stackable. Just put 2 Seared Tanks on top of each other and double the capacity of lava with that.

Michael (aka BakermanLP)

**Comment by KnightMiner** [comment]
@bonii-xx is this still relevant since the smeltery now uses all seared tanks in the structure for fuel?

**Comment by bonii-xx** [comment]
It always used all tanks for fuel. It's relevant for stacking tacks together to get a bigger tank. ;o

**Comment by Garonne** [comment]
Current version does at least display the entire amount of lava available (prior versions at times only displayed the "main" tank on the controller level in the GUI, but that did change).

Not an issue at all for me anymore as multiple tanks work like a charm as well as refilling from the outside.

**Comment by KnightMiner** [comment]
No plans to do this in 1.16 at all, Ceramics adds in stackable fluid tanks if you want. Our tanks doing so would mess with smelteries
